Kaldi: DecodableAmSgmm Class Reference
DecodableAmSgmm Class Reference
#include <decodable-am-sgmm.h>
Classes
struct LikelihoodCacheRecord
Defines a cache record for a state.
Public Member Functions
DecodableAmSgmm (const SgmmGselectConfig &opts, const AmSgmm &am, const SgmmPerSpkDerivedVars &spk, const TransitionModel &tm, const Matrix< BaseFloat > &feats, const std::vector< std::vector< int32 > > &gselect_all, BaseFloat log_prune)
virtual BaseFloat LogLikelihood (int32 frame, int32 tid)
Returns the log likelihood, which will be negated in the decoder.
int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Protected Member Functions
void ResetLogLikeCache ()
virtual BaseFloat LogLikelihoodZeroBased (int32 frame, int32 pdf_id)
Protected Attributes
const AmSgmm & acoustic_model_
const SgmmGselectConfig & sgmm_config_
const SgmmPerSpkDerivedVars & spk_
const TransitionModel & trans_model_
for tid to pdf mapping
const Matrix< BaseFloat > & feature_matrix_
const std::vector< std::vector
< int32 > > gselect_all_
if nonempty,
int32 previous_frame_
BaseFloat log_prune_
std::vector
< LikelihoodCacheRecord > log_like_cache_
Cached per-frame quantities used in SGMM likelihood computation.
std::vector< int32 > gselect_
SgmmPerFrameDerivedVars per_frame_vars_
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmSgmm)
Detailed Description
Definition at line 33 of file decodable-am-sgmm.h.
Constructor & Destructor Documentation
DecodableAmSgmm (const SgmmGselectConfig & opts, const AmSgmm & am, const SgmmPerSpkDerivedVars & spk, const TransitionModel & tm, const Matrix< BaseFloat > & feats, const std::vector< std::vector< int32 > > & gselect_all, BaseFloat log_prune) inline
Definition at line 35 of file decodable-am-sgmm.h.
References DecodableAmSgmm::ResetLogLikeCache().
                                       :  // gselect_all may be empty
       acoustic_model_(am), sgmm_config_(opts), spk_(spk),
       trans_model_(tm), feature_matrix_(feats),
       gselect_all_(gselect_all), previous_frame_(-1),
       log_prune_(log_prune) {
     ResetLogLikeCache();
   }
Member Function Documentation
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 57 of file decodable-am-sgmm.h.
References KALDI_ASSERT, and DecodableAmSgmm::NumFramesReady().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmSgmm) private
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Reimplemented in DecodableAmSgmmScaled.
Definition at line 51 of file decodable-am-sgmm.h.
References DecodableAmSgmm::LogLikelihoodZeroBased(), DecodableAmSgmm::trans_model_, and TransitionModel::TransitionIdToPdf().
{
     return LogLikelihoodZeroBased(frame, trans_model_.TransitionIdToPdf(tid));
   }
BaseFloat LogLikelihoodZeroBased (int32 frame, int32 pdf_id) protected virtual
Definition at line 27 of file decodable-am-sgmm.cc.
References DecodableAmSgmm::acoustic_model_, AmSgmm::ComputePerFrameVars(), VectorBase< Real >::Dim(), DecodableAmSgmm::feature_matrix_, AmSgmm::FeatureDim(), AmSgmm::GaussianSelection(), DecodableAmSgmm::gselect_, DecodableAmSgmm::gselect_all_, KALDI_ASSERT, KALDI_ERR, KALDI_ISINF, KALDI_ISNAN, DecodableAmSgmm::log_like_cache_, DecodableAmSgmm::log_prune_, AmSgmm::LogLikelihood(), DecodableAmSgmm::NumFramesReady(), DecodableAmSgmm::NumIndices(), DecodableAmSgmm::per_frame_vars_, DecodableAmSgmm::previous_frame_, MatrixBase< Real >::Row(), DecodableAmSgmm::sgmm_config_, and DecodableAmSgmm::spk_.
Referenced by DecodableAmSgmm::LogLikelihood(), and DecodableAmSgmmScaled::LogLikelihood().
{
   KALDI_ASSERT(frame >= 0 && frame < NumFramesReady());
   KALDI_ASSERT(pdf_id >= 0 && pdf_id < NumIndices());
   if (log_like_cache_[pdf_id].hit_time == frame) {
     return log_like_cache_[pdf_id].log_like;  // return cached value, if found
   }
   const VectorBase<BaseFloat> &data = feature_matrix_.Row(frame);
   // check if everything is in order
   if (acoustic_model_.FeatureDim() != data.Dim()) {
     KALDI_ERR << "Dim mismatch: data dim = "  << data.Dim()
         << "vs. model dim = " << acoustic_model_.FeatureDim();
   }
   if (frame != previous_frame_) {  // Per-frame precomputation for SGMM.
     if (gselect_all_.empty())
       acoustic_model_.GaussianSelection(sgmm_config_, data, &gselect_);
     else {
       KALDI_ASSERT(frame < gselect_all_.size());
       gselect_ = gselect_all_[frame];
     }
     acoustic_model_.ComputePerFrameVars(data, gselect_, spk_,
                                         0.0 /*FMLLR logdet*/, &per_frame_vars_);
     previous_frame_ = frame;
   }
   BaseFloat loglike = acoustic_model_.LogLikelihood(per_frame_vars_, pdf_id,
                                                     log_prune_);
   if (KALDI_ISNAN(loglike) || KALDI_ISINF(loglike))
     KALDI_ERR << "Invalid answer (overflow or invalid variances/features?)";
   log_like_cache_[pdf_id].log_like = loglike;
   log_like_cache_[pdf_id].hit_time = frame;
   return loglike;
 }
int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 54 of file decodable-am-sgmm.h.
References DecodableAmSgmm::feature_matrix_, and MatrixBase< Real >::NumRows().
Referenced by DecodableAmSgmm::IsLastFrame(), and DecodableAmSgmm::LogLikelihoodZeroBased().
 { return feature_matrix_.NumRows(); }
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst.
Implements DecodableInterface.
Definition at line 55 of file decodable-am-sgmm.h.
References TransitionModel::NumTransitionIds(), and DecodableAmSgmm::trans_model_.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
 { return trans_model_.NumTransitionIds(); }
void ResetLogLikeCache () protected
Definition at line 63 of file decodable-am-sgmm.cc.
References DecodableAmSgmm::acoustic_model_, DecodableAmSgmm::log_like_cache_, and AmSgmm::NumPdfs().
Referenced by DecodableAmSgmm::DecodableAmSgmm().
{
   if (log_like_cache_.size() != acoustic_model_.NumPdfs()) {
     log_like_cache_.resize(acoustic_model_.NumPdfs());
   }
   vector<LikelihoodCacheRecord>::iterator it = log_like_cache_.begin(),
       end = log_like_cache_.end();
   for (; it != end; ++it) { it->hit_time = -1; }
 }
Member Data Documentation
const AmSgmm& acoustic_model_ protected
Definition at line 66 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased(), and DecodableAmSgmm::ResetLogLikeCache().
const Matrix<BaseFloat>& feature_matrix_ protected
Definition at line 70 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased(), and DecodableAmSgmm::NumFramesReady().
std::vector<int32> gselect_ protected
Definition at line 84 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
const std::vector<std::vector<int32> > gselect_all_ protected
if nonempty,
precomputed gaussian indices.
Definition at line 71 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
std::vector<LikelihoodCacheRecord> log_like_cache_ protected
Cached per-frame quantities used in SGMM likelihood computation.
Definition at line 83 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased(), and DecodableAmSgmm::ResetLogLikeCache().
BaseFloat log_prune_ protected
Definition at line 74 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
SgmmPerFrameDerivedVars per_frame_vars_ protected
Definition at line 85 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
int32 previous_frame_ protected
Definition at line 73 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
const SgmmGselectConfig& sgmm_config_ protected
Definition at line 67 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
const SgmmPerSpkDerivedVars& spk_ protected
Definition at line 68 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased().
const TransitionModel& trans_model_ protected
for tid to pdf mapping
Definition at line 69 of file decodable-am-sgmm.h.
Referenced by DecodableAmSgmm::LogLikelihood(), DecodableAmSgmmScaled::LogLikelihood(), and DecodableAmSgmm::NumIndices().
The documentation for this class was generated from the following files:
sgmm/decodable-am-sgmm.h
sgmm/decodable-am-sgmm.cc