Kaldi: OnlineGenericBaseFeature< C > Class Template Reference
OnlineGenericBaseFeature< C > Class Template Reference
OnlineFeatureExtraction
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
OnlineGenericBaseFeature (const typename C::Options &opts)
virtual void AcceptWaveform (BaseFloat sampling_rate, const VectorBase< BaseFloat > &waveform)
This would be called from the application, when you get more wave data.
virtual void InputFinished ()
InputFinished() tells the class you won't be providing any more waveform.
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Attributes
C mfcc_or_plp_
Matrix< BaseFloat > features_
bool input_finished_
int32 num_frames_
BaseFloat sampling_frequency_
Vector< BaseFloat > waveform_remainder_
Detailed Description
template<class C>
class kaldi::OnlineGenericBaseFeature< C >
Definition at line 46 of file online-feature.h.
Constructor & Destructor Documentation
OnlineGenericBaseFeature (const typename C::Options & opts) explicit
Definition at line 42 of file online-feature.cc.
     :mfcc_or_plp_(opts), input_finished_(false), num_frames_(0),
     sampling_frequency_(opts.frame_opts.samp_freq) { }
Member Function Documentation
void AcceptWaveform (BaseFloat sampling_rate, const VectorBase< BaseFloat > & waveform) virtual
This would be called from the application, when you get more wave data.
Note: the sampling_rate is typically only provided so the code can assert that it matches the sampling rate expected in the options.
Implements OnlineBaseFeature.
Definition at line 48 of file online-feature.cc.
References VectorBase< Real >::Dim(), KALDI_ERR, kaldi::kCopyData, MatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), and Vector< Real >::Resize().
Referenced by kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), and kaldi::TestOnlineTransform().
{
   if (waveform.Dim() == 0) {
     return;  // Nothing to do.
   }
   if (input_finished_) {
     KALDI_ERR << "AcceptWaveform called after InputFinished() was called.";
   }
   if (sampling_rate != sampling_frequency_) {
     KALDI_ERR << "Sampling frequency mismatch, expected "
               << sampling_frequency_ << ", got " << sampling_rate;
   }
   Vector<BaseFloat> appended_wave;
   const VectorBase<BaseFloat> &wave_to_use = (waveform_remainder_.Dim() != 0 ?
                                               appended_wave : waveform);
   if (waveform_remainder_.Dim() != 0) {
     appended_wave.Resize(waveform_remainder_.Dim() +
                          waveform.Dim());
     appended_wave.Range(0, waveform_remainder_.Dim()).CopyFromVec(
         waveform_remainder_);
     appended_wave.Range(waveform_remainder_.Dim(),
                         waveform.Dim()).CopyFromVec(waveform);
   }
   waveform_remainder_.Resize(0);
   Matrix<BaseFloat> feats;
   BaseFloat vtln_warp = 1.0;  // We don't support VTLN warping in this wrapper.
   mfcc_or_plp_.Compute(wave_to_use, vtln_warp, &feats, &waveform_remainder_);
   if (feats.NumRows() == 0) {
     // Presumably we got a very small waveform and could output no whole
     // features.  The waveform will have been appended to waveform_remainder_.
     return;
   }
   int32 new_num_frames = num_frames_ + feats.NumRows();
   BaseFloat increase_ratio = 1.5;  // This is a tradeoff between memory and
                                    // compute; it's the factor by which we
                                    // increase the memory used each time.
   if (new_num_frames > features_.NumRows()) {
     int32 new_num_rows = std::max<int32>(new_num_frames,
                                          features_.NumRows() * increase_ratio);
     // Increase the size of the features_ matrix and copy over any existing
     // data.
     features_.Resize(new_num_rows, Dim(), kCopyData);
   }
   features_.Range(num_frames_, feats.NumRows(), 0, Dim()).CopyFromMat(feats);
   num_frames_ = new_num_frames;
 }
virtual int32 Dim () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 51 of file online-feature.h.
References OnlineGenericBaseFeature< C >::mfcc_or_plp_.
Referenced by kaldi::TestOnlineTransform().
 { return mfcc_or_plp_.Dim(); }
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 29 of file online-feature.cc.
References VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), and KALDI_ASSERT.
{
   KALDI_ASSERT(frame >= 0 && frame < num_frames_);
   KALDI_ASSERT(feat->Dim() == Dim());
   feat->CopyFromVec(features_.Row(frame));
 };
virtual void InputFinished () inline virtual
InputFinished() tells the class you won't be providing any more waveform.
This will help flush out the last few frames of delta or LDA features (it will typically affect the return value of IsLastFrame.
Implements OnlineBaseFeature.
Definition at line 77 of file online-feature.h.
References OnlineGenericBaseFeature< C >::input_finished_.
Referenced by kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), and kaldi::TestOnlineTransform().
 { input_finished_= true; }
bool IsLastFrame (int32 frame) const virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 37 of file online-feature.cc.
{
   return (frame == num_frames_ - 1 && input_finished_);
 }
virtual int32 NumFramesReady () const inline virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 58 of file online-feature.h.
References OnlineGenericBaseFeature< C >::num_frames_.
 { return num_frames_; }
Member Data Documentation
Matrix<BaseFloat> features_ private
Definition at line 84 of file online-feature.h.
bool input_finished_ private
Definition at line 87 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::InputFinished().
C mfcc_or_plp_ private
Definition at line 81 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::Dim().
int32 num_frames_ private
Definition at line 93 of file online-feature.h.
Referenced by OnlineGenericBaseFeature< C >::NumFramesReady().
BaseFloat sampling_frequency_ private
Definition at line 97 of file online-feature.h.
Vector<BaseFloat> waveform_remainder_ private
Definition at line 102 of file online-feature.h.
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc