Kaldi: Nnet Class Reference
Nnet Class Reference
#include <nnet-nnet.h>
Public Member Functions
void ReadConfig (std::istream &config_file)
int32 NumComponents () const
int32 NumNodes () const
Component * GetComponent (int32 c)
return component indexed c. not a copy; not owned by caller.
const Component * GetComponent (int32 c) const
return component indexed c (const version).
const NetworkNode & GetNode (int32 node) const
returns const reference to a particular numbered network node.
bool IsComponentNode (int32 node) const
Returns true if this is a component node, meaning that it is of type kComponent.
bool IsDimRangeNode (int32 node) const
Returns true if this is a dim-range node, meaning that it is of type kDimRange.
bool IsInputNode (int32 node) const
Returns true if this is an output node, meaning that it is of type kInput.
bool IsDescriptorNode (int32 node) const
Returns true if this is a descriptor node, meaning that it is of type kDescriptor.
bool IsOutputNode (int32 node) const
Returns true if this is an output node, meaning that it is of type kDescriptor and is not directly followed by a node of type kComponent.
bool IsComponentInputNode (int32 node) const
Returns true if this is component-input node, i.e.
const std::vector< std::string > & GetNodeNames () const
returns vector of node names (needed by some parsing code, for instance).
const std::string & GetNodeName (int32 node_index) const
returns individual node name.
const std::vector< std::string > & GetComponentNames () const
returns vector of component names (needed by some parsing code, for instance).
const std::string & GetComponentName (int32 component_index) const
returns individual component name.
int32 GetNodeIndex (const std::string &node_name) const
returns index associated with this node name, or -1 if no such index.
int32 GetComponentIndex (const std::string &node_name) const
returns index associated with this component name, or -1 if no such index.
int32 InputDim (const std::string &input_name) const
int32 OutputDim (const std::string &output_name) const
void Read (std::istream &istream, bool binary)
void Write (std::ostream &ostream, bool binary) const
void Check () const
note to self: one thing of many that we need to check is that no output nodes are referred to in Descriptors.
std::string Info () const
returns some human-readable information about the network, mostly for debugging purposes.
int32 Modulus () const
[Relevant for clockwork RNNs and similar].
~Nnet ()
Nnet ()
Nnet (const Nnet &nnet)
Nnet * Copy () const
Nnet & operator= (const Nnet &nnet)
Private Member Functions
void Destroy ()
std::string GetAsConfigLine (int32 node_index, bool include_dim) const
void GetConfigLines (bool include_dim, std::vector< std::string > *config_lines) const
void ProcessComponentConfigLine (int32 initial_num_components, ConfigLine *config)
void ProcessComponentNodeConfigLine (int32 pass, ConfigLine *config)
void ProcessInputNodeConfigLine (ConfigLine *config)
void ProcessOutputNodeConfigLine (int32 pass, ConfigLine *config)
void ProcessDimRangeNodeConfigLine (int32 pass, ConfigLine *config)
void GetSomeNodeNames (std::vector< std::string > *modified_node_names) const
Static Private Member Functions
static void RemoveRedundantConfigLines (int32 num_lines_initial, std::vector< std::string > *first_tokens, std::vector< ConfigLine > *configs)
Private Attributes
std::vector< std::string > component_names_
std::vector< Component * > components_
std::vector< std::string > node_names_
std::vector< NetworkNode > nodes_
Detailed Description
Definition at line 115 of file nnet-nnet.h.
Constructor & Destructor Documentation
~Nnet () inline
Definition at line 216 of file nnet-nnet.h.
References Nnet::Destroy().
 { Destroy(); }
Nnet () inline
Definition at line 219 of file nnet-nnet.h.
Referenced by Nnet::Copy().
 { }
Nnet (const Nnet & nnet)
Definition at line 741 of file nnet-nnet.cc.
References Nnet::Check(), Nnet::components_, and rnnlm::i.
                           :
     component_names_(nnet.component_names_),
     components_(nnet.components_.size()),
     node_names_(nnet.node_names_),
     nodes_(nnet.nodes_) {
   for (size_t i = 0; i < components_.size(); i++)
     components_[i] = nnet.components_[i]->Copy();
   Check();
 }
Member Function Documentation
void Check () const
note to self: one thing of many that we need to check is that no output nodes are referred to in Descriptors.
This might mess up the combination of each output node into a single step, as dependencies would be messed up. Also make sure no nodes referred to in Descriptors, or in kDimRange, are themselves Descriptors.
Definition at line 660 of file nnet-nnet.cc.
References NetworkNode::component_index, Nnet::component_names_, Nnet::components_, NetworkNode::descriptor, NetworkNode::dim, NetworkNode::Dim(), NetworkNode::dim_offset, Nnet::GetComponent(), Nnet::GetComponentIndex(), Descriptor::GetNodeDependencies(), Nnet::GetNodeIndex(), rnnlm::i, Component::InputDim(), Nnet::IsOutputNode(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, kaldi::nnet3::kComponent, kaldi::nnet3::kDescriptor, kaldi::nnet3::kDimRange, kaldi::nnet3::kInput, rnnlm::n, NetworkNode::node_index, Nnet::node_names_, NetworkNode::node_type, Nnet::nodes_, kaldi::SortAndUniq(), and NetworkNode::u.
Referenced by Nnet::Nnet(), Nnet::operator=(), and Nnet::ReadConfig().
{
   int32 num_nodes = nodes_.size(),
     num_input_nodes = 0,
     num_output_nodes = 0;
   KALDI_ASSERT(num_nodes != 0);
   std::vector<bool> component_used(components_.size());
   for (int32 n = 0; n < num_nodes; n++) {
     const NetworkNode &node = nodes_[n];
     std::string node_name = node_names_[n];
     KALDI_ASSERT(GetNodeIndex(node_name) == n);
     switch (node.node_type) {
       case kInput:
         KALDI_ASSERT(node.dim > 0);
         num_input_nodes++;
         break;
       case kDescriptor: {
         if (IsOutputNode(n))
           num_output_nodes++;
         std::vector<int32> node_deps;
         node.descriptor.GetNodeDependencies(&node_deps);
         SortAndUniq(&node_deps);
         for (size_t i = 0; i < node_deps.size(); i++) {
           int32 src_node = node_deps[i];
           KALDI_ASSERT(src_node >= 0 && src_node < num_nodes);
           NodeType src_type = nodes_[src_node].node_type;
           if (src_type != kInput && src_type != kDimRange &&
               src_type != kComponent)
             KALDI_ERR << "Invalid source node type in Descriptor: source node "
                       << node_names_[src_node];
         }
         break;
       }
       case kComponent: {
         KALDI_ASSERT(n > 0 && nodes_[n-1].node_type == kDescriptor);
         const NetworkNode &src_node = nodes_[n-1];
         const Component *c = GetComponent(node.u.component_index);
         component_used[node.u.component_index] = true;
         int32 src_dim = src_node.Dim(*this), input_dim = c->InputDim();
         if (src_dim != input_dim) {
           KALDI_ERR << "Dimension mismatch for network-node "
                     << node_name << ": input-dim "
                     << src_dim << " versus component-input-dim "
                     << input_dim;
         }
         break;
       }
       case kDimRange: {
         int32 input_node = node.u.node_index;
         KALDI_ASSERT(input_node >= 0 && input_node < num_nodes);
         NodeType input_type = nodes_[input_node].node_type;
         if (input_type != kInput && input_type != kComponent)
           KALDI_ERR << "Invalid source node type in DimRange node: source node "
                     << node_names_[input_node];
         int32 input_dim = nodes_[input_node].Dim(*this);
         if (!(node.dim > 0 && node.dim_offset >= 0 &&
               node.dim + node.dim_offset <= input_dim)) {
           KALDI_ERR << "Invalid node dimensions for DimRange node: " << node_name
                     << ": input-dim=" << input_dim << ", dim=" << node.dim
                     << ", dim-offset=" << node.dim_offset;
         }
         break;
       }
       default:
         KALDI_ERR << "Invalid node type for node " << node_name;
     }
   }
   int32 num_components = components_.size();
   for (int32 c = 0; c < num_components; c++) {
     const std::string &component_name = component_names_[c];
     if (!component_used[c]) {
       KALDI_WARN << "Orphan component " << component_name;
     }
     KALDI_ASSERT(GetComponentIndex(component_name) == c &&
                  "Duplicate component names?");
   }
   KALDI_ASSERT(num_input_nodes > 0);
   KALDI_ASSERT(num_output_nodes > 0);
 }
Nnet* Copy () const inline
Definition at line 225 of file nnet-nnet.h.
References Nnet::Nnet().
Referenced by NnetTrainer::NnetTrainer().
 { return new Nnet(*this); }
void Destroy () private
Definition at line 540 of file nnet-nnet.cc.
References Nnet::component_names_, Nnet::components_, rnnlm::i, Nnet::node_names_, and Nnet::nodes_.
Referenced by Nnet::operator=(), Nnet::Read(), and Nnet::~Nnet().
                    {
   for (size_t i = 0; i < components_.size(); i++)
     delete components_[i];
   component_names_.clear();
   components_.clear();
   node_names_.clear();
   nodes_.clear();
 }
std::string GetAsConfigLine (int32 node_index, bool include_dim) const private
Definition at line 58 of file nnet-nnet.cc.
References Nnet::component_names_, Nnet::IsOutputNode(), KALDI_ASSERT, KALDI_ERR, kaldi::nnet3::kComponent, kaldi::nnet3::kDescriptor, kaldi::nnet3::kDimRange, kaldi::nnet3::kInput, kaldi::nnet3::kLinear, Nnet::node_names_, and Nnet::nodes_.
Referenced by Nnet::GetConfigLines().
{
   std::ostringstream ans;
   KALDI_ASSERT(node_index < nodes_.size() &&
                nodes_.size() == node_names_.size());
   const NetworkNode &node = nodes_[node_index];
   const std::string &name = node_names_[node_index];
   switch (node.node_type) {
     case kInput:
       ans << "input-node name=" << name << " dim=" << node.dim;
       break;
     case kDescriptor:
       // assert that it's an output-descriptor, not one describing the input to
       // a component-node.
       KALDI_ASSERT(IsOutputNode(node_index));
       ans << "output-node name=" << name << " input=";
       node.descriptor.WriteConfig(ans, node_names_);
       if (include_dim)
         ans << " dim=" << node.Dim(*this);
       ans << " objective=" << (node.u.objective_type == kLinear ? "linear" :
                                "quadratic");
       break;
     case kComponent:
       ans << "component-node name=" << name << " component="
           << component_names_[node.u.component_index] << " input=";
       KALDI_ASSERT(nodes_[node_index-1].node_type == kDescriptor);
       nodes_[node_index-1].descriptor.WriteConfig(ans, node_names_);
       if (include_dim)
         ans << " input-dim=" << nodes_[node_index-1].Dim(*this)
             << " output-dim=" << node.Dim(*this);
       break;
     case kDimRange:
       ans << "dim-range-node name=" << name << " input-node="
           << node_names_[node.u.node_index] << " dim-offset="
           << node.dim_offset << " dim=" << node.dim;
       break;
     default:
       KALDI_ERR << "Unknown node type.";
   }
   return ans.str();
 }
Component * GetComponent (int32 c)
return component indexed c. not a copy; not owned by caller.
Definition at line 137 of file nnet-nnet.cc.
References Nnet::components_, and KALDI_ASSERT.
Referenced by Compiler::AddBackpropStep(), ComputationGraphBuilder::AddDependencies(), kaldi::nnet3::AddNnet(), Compiler::AddPropagateStep(), Nnet::Check(), ComputationChecker::CheckComputationIndexes(), kaldi::nnet3::ComponentDotProducts(), kaldi::nnet3::ComputeCommandAttributes(), ComputationGraphBuilder::ComputeComputableInfo(), kaldi::nnet3::ComputeComputationGraph(), Compiler::ComputeDerivNeeded(), NnetCombiner::ComputeUpdatableComponentDims(), ModelUpdateConsolidator::ConsolidateModelUpdate(), ModelUpdateConsolidator::ConsolidateUpdateForComponent(), NnetComputer::DebugAfterExecute(), NnetComputer::DebugBeforeExecute(), NetworkNode::Dim(), kaldi::nnet3::DotProduct(), NnetComputer::ExecuteCommand(), VariableMergingOptimizer::MergeVariables(), DerivativeTimeLimiter::ModifyCommand(), kaldi::nnet3::NnetParametersAreIdentical(), kaldi::nnet3::NumParameters(), kaldi::nnet3::NumUpdatableComponents(), kaldi::nnet3::PerturbParams(), NnetCombiner::PrintParams(), kaldi::nnet3::PrintVectorPerUpdatableComponent(), ComputationGraphBuilder::PruneDependencies(), kaldi::nnet3::compute_computation_steps::ReorderIndexes(), kaldi::nnet3::ScaleNnet(), kaldi::nnet3::SetLearningRate(), Compiler::SetUpPrecomputedIndexes(), kaldi::nnet3::SetZero(), kaldi::nnet3::UnVectorizeNnet(), kaldi::nnet3::VectorizeNnet(), and kaldi::nnet3::ZeroComponentStats().
{
   KALDI_ASSERT(static_cast<size_t>(c) < components_.size());
   return components_[c];
 }
const Component * GetComponent (int32 c) const
return component indexed c (const version).
not a copy; not owned by caller.
Definition at line 132 of file nnet-nnet.cc.
References Nnet::components_, and KALDI_ASSERT.
{
   KALDI_ASSERT(static_cast<size_t>(c) < components_.size());
   return components_[c];
 }
int32 GetComponentIndex (const std::string & node_name) const
returns index associated with this component name, or -1 if no such index.
Definition at line 452 of file nnet-nnet.cc.
References Nnet::component_names_, and rnnlm::i.
Referenced by Nnet::Check(), Nnet::ProcessComponentConfigLine(), and Nnet::ProcessComponentNodeConfigLine().
{
   size_t size = component_names_.size();
   for (size_t i = 0; i < size; i++)
     if (component_names_[i] == component_name)
       return static_cast<int32>(i);
   return -1;
 }
const std::string & GetComponentName (int32 component_index) const
returns individual component name.
Definition at line 655 of file nnet-nnet.cc.
References Nnet::component_names_, and KALDI_ASSERT.
Referenced by NnetComputer::DebugAfterExecute(), NnetComputer::ExecuteCommand(), kaldi::nnet3::NnetParametersAreIdentical(), kaldi::nnet3::PrintCommand(), NnetCombiner::PrintParams(), and kaldi::nnet3::PrintVectorPerUpdatableComponent().
{
   KALDI_ASSERT(static_cast<size_t>(component_index) < component_names_.size());
   return component_names_[component_index];
 }
const std::vector< std::string > & GetComponentNames () const
returns vector of component names (needed by some parsing code, for instance).
Definition at line 54 of file nnet-nnet.cc.
References Nnet::component_names_.
{
   return component_names_;
 }
void GetConfigLines (bool include_dim, std::vector< std::string > * config_lines) const private
Definition at line 152 of file nnet-nnet.cc.
References Nnet::GetAsConfigLine(), Nnet::IsComponentInputNode(), rnnlm::n, and Nnet::NumNodes().
Referenced by Nnet::Info(), Nnet::ReadConfig(), and Nnet::Write().
{
   config_lines->clear();
   for (int32 n = 0; n < NumNodes(); n++)
     if (!IsComponentInputNode(n))
       config_lines->push_back(GetAsConfigLine(n, include_dim));
 }
const NetworkNode& GetNode (int32 node) const inline
returns const reference to a particular numbered network node.
Definition at line 135 of file nnet-nnet.h.
References KALDI_ASSERT, and Nnet::nodes_.
Referenced by Compiler::AddBackpropStep(), ComputationGraphBuilder::AddDependencies(), kaldi::nnet3::compute_computation_steps::AddDimRangeSteps(), ComputationGraphBuilder::AddInputs(), kaldi::nnet3::computation_graph::AddInputToGraph(), Compiler::AddPropagateStep(), ComputationGraphBuilder::ComputeComputableInfo(), kaldi::nnet3::ComputeComputationGraph(), Compiler::ComputeDerivNeeded(), Compiler::ComputeInputLocationsList(), Compiler::CreateLocationInfo(), Compiler::CreateStepInfo(), SimpleForwardingDescriptor::Dim(), Compiler::DoBackwardComputation(), Compiler::DoForwardComputation(), kaldi::nnet3::NnetToDirectedGraph(), NnetComputeProb::PrintTotalStats(), NnetComputeProb::ProcessOutputs(), NnetTrainer::ProcessOutputs(), ComputationGraphBuilder::PruneDependencies(), kaldi::nnet3::compute_computation_steps::ReorderIndexes(), and Compiler::SetUpPrecomputedIndexes().
{
     KALDI_ASSERT(node >= 0 && node < nodes_.size());
     return nodes_[node];
   }
int32 GetNodeIndex (const std::string & node_name) const
returns index associated with this node name, or -1 if no such index.
Definition at line 444 of file nnet-nnet.cc.
References rnnlm::i, and Nnet::node_names_.
Referenced by NnetComputer::AcceptInputs(), ComputationGraphBuilder::AddInputs(), kaldi::nnet3::compute_computation_steps::AddInputSteps(), kaldi::nnet3::computation_graph::AddInputToGraph(), ComputationGraphBuilder::AddOutputs(), kaldi::nnet3::compute_computation_steps::AddOutputSteps(), kaldi::nnet3::computation_graph::AddOutputToGraph(), Nnet::Check(), kaldi::nnet3::ComputeSimpleNnetContextForShift(), ComputationGraphBuilder::GetComputableInfo(), kaldi::nnet3::GetComputationRequest(), NnetComputer::GetMatrixIndex(), Nnet::InputDim(), kaldi::nnet3::IsSimpleNnet(), Nnet::OutputDim(), NnetComputeProb::PrintTotalStats(), Nnet::ProcessComponentNodeConfigLine(), Nnet::ProcessDimRangeNodeConfigLine(), Nnet::ProcessInputNodeConfigLine(), Nnet::ProcessOutputNodeConfigLine(), NnetComputeProb::ProcessOutputs(), and NnetTrainer::ProcessOutputs().
{
   size_t size = node_names_.size();
   for (size_t i = 0; i < size; i++)
     if (node_names_[i] == node_name)
       return static_cast<int32>(i);
   return -1;
 }
const std::string & GetNodeName (int32 node_index) const
returns individual node name.
Definition at line 650 of file nnet-nnet.cc.
References KALDI_ASSERT, and Nnet::node_names_.
Referenced by NnetComputer::CheckInputs(), ComputationGraphBuilder::PrintCindexId(), and kaldi::nnet3::PrintComputationPreamble().
{
   KALDI_ASSERT(static_cast<size_t>(node_index) < node_names_.size());
   return node_names_[node_index];
 }
const std::vector< std::string > & GetNodeNames () const
returns vector of node names (needed by some parsing code, for instance).
Definition at line 50 of file nnet-nnet.cc.
References Nnet::node_names_.
Referenced by Compiler::ComputeDerivNeeded(), Compiler::DeallocateMatrices(), kaldi::nnet3::EvaluateComputationRequest(), and kaldi::nnet3::PrintComputationPreamble().
{
   return node_names_;
 }
void GetSomeNodeNames (std::vector< std::string > * modified_node_names) const private
Definition at line 549 of file nnet-nnet.cc.
References rnnlm::i, kaldi::nnet3::kComponent, kaldi::nnet3::kDimRange, kaldi::nnet3::kInput, Nnet::node_names_, and Nnet::nodes_.
Referenced by Nnet::ProcessComponentNodeConfigLine(), and Nnet::ProcessOutputNodeConfigLine().
{
   modified_node_names->resize(node_names_.size());
   const std::string invalid_name = "**";
   size_t size = node_names_.size();
   for (size_t i = 0; i < size; i++) {
     if (nodes_[i].node_type == kComponent ||
         nodes_[i].node_type == kInput ||
         nodes_[i].node_type == kDimRange) {
       (*modified_node_names)[i] = node_names_[i];
     } else {
       (*modified_node_names)[i] = invalid_name;
     }
   }
 }
std::string Info () const
returns some human-readable information about the network, mostly for debugging purposes.
Also see function NnetInfo() in nnet-utils.h, which prints out more extensive infoformation.
Definition at line 765 of file nnet-nnet.cc.
References Nnet::component_names_, Nnet::components_, Nnet::GetConfigLines(), rnnlm::i, Nnet::Modulus(), and kaldi::nnet3::NumParameters().
Referenced by AmNnetSimple::Info(), and kaldi::nnet3::NnetInfo().
{
   std::ostringstream os;
   os << "num-parameters: " << NumParameters(*this) << "\n";
   os << "modulus: " << this->Modulus() << "\n";
   std::vector<std::string> config_lines;
   bool include_dim = true;
   GetConfigLines(include_dim, &config_lines);
   for (size_t i = 0; i < config_lines.size(); i++)
     os << config_lines[i] << "\n";
   // Get component info.
   for (size_t i = 0; i < components_.size(); i++)
     os << "component name=" << component_names_[i]
        << " type=" << components_[i]->Info() << "\n";
   return os.str();
 }
int32 InputDim (const std::string & input_name) const
Definition at line 635 of file nnet-nnet.cc.
References NetworkNode::dim, Nnet::GetNodeIndex(), kaldi::nnet3::kInput, rnnlm::n, NetworkNode::node_type, and Nnet::nodes_.
Referenced by kaldi::nnet3::ComputeExampleComputationRequestSimple(), NnetDecodableBase::EnsureFrameIsComputed(), AmNnetSimple::Info(), AmNnetSimple::InputDim(), AmNnetSimple::IvectorDim(), and kaldi::nnet3::NnetInfo().
{
   int32 n = GetNodeIndex(input_name);
   if (n == -1) return -1;
   const NetworkNode &node = nodes_[n];
   if (node.node_type != kInput) return -1;
   return node.dim;
 }
bool IsComponentInputNode (int32 node) const
Returns true if this is component-input node, i.e.
a node of type kDescriptor that immediately precedes a node of type kComponent.
Definition at line 144 of file nnet-nnet.cc.
References KALDI_ASSERT, kaldi::nnet3::kComponent, kaldi::nnet3::kDescriptor, and Nnet::nodes_.
Referenced by Nnet::GetConfigLines().
{
   int32 size = nodes_.size();
   KALDI_ASSERT(node >= 0 && node < size);
   return (node + 1 < size &&
           nodes_[node].node_type == kDescriptor &&
           nodes_[node+1].node_type == kComponent);
 }
bool IsComponentNode (int32 node) const
Returns true if this is a component node, meaning that it is of type kComponent.
Definition at line 119 of file nnet-nnet.cc.
References KALDI_ASSERT, kaldi::nnet3::kComponent, and Nnet::nodes_.
Referenced by Compiler::ComputeDerivNeeded(), and kaldi::nnet3::compute_computation_steps::ExtractOnlyComponentCindexes().
{
   int32 size = nodes_.size();
   KALDI_ASSERT(node >= 0 && node < size);
   return (nodes_[node].node_type == kComponent);
 }
bool IsDescriptorNode (int32 node) const
Returns true if this is a descriptor node, meaning that it is of type kDescriptor.
Exactly one of IsOutput or IsComponentInput will also apply.
Definition at line 113 of file nnet-nnet.cc.
References KALDI_ASSERT, kaldi::nnet3::kDescriptor, and Nnet::nodes_.
{
   int32 size = nodes_.size();
   KALDI_ASSERT(node >= 0 && node < size);
   return (nodes_[node].node_type == kDescriptor);
 }
bool IsDimRangeNode (int32 node) const
Returns true if this is a dim-range node, meaning that it is of type kDimRange.
Definition at line 125 of file nnet-nnet.cc.
References KALDI_ASSERT, kaldi::nnet3::kDimRange, and Nnet::nodes_.
Referenced by kaldi::nnet3::compute_computation_steps::AddDimRangeSteps().
{
   int32 size = nodes_.size();
   KALDI_ASSERT(node >= 0 && node < size);
   return (nodes_[node].node_type == kDimRange);
 }
bool IsInputNode (int32 node) const
Returns true if this is an output node, meaning that it is of type kInput.
Definition at line 107 of file nnet-nnet.cc.
References KALDI_ASSERT, kaldi::nnet3::kInput, and Nnet::nodes_.
Referenced by NnetComputer::AcceptInputs(), kaldi::nnet3::ComputeMatrixAccesses(), Compiler::DeallocateMatrices(), kaldi::nnet3::GetComputationRequest(), kaldi::nnet3::IsSimpleNnet(), kaldi::nnet3::NumInputNodes(), kaldi::nnet3::ReplaceInOutput(), and Compiler::SetInputOutputInfo().
{
   int32 size = nodes_.size();
   KALDI_ASSERT(node >= 0 && node < size);
   return (nodes_[node].node_type == kInput);
 }
bool IsOutputNode (int32 node) const
Returns true if this is an output node, meaning that it is of type kDescriptor and is not directly followed by a node of type kComponent.
Definition at line 99 of file nnet-nnet.cc.
References KALDI_ASSERT, kaldi::nnet3::kComponent, kaldi::nnet3::kDescriptor, and Nnet::nodes_.
Referenced by Compiler::AllocateMatrices(), ComputationGraphBuilder::AllOutputsAreComputable(), Nnet::Check(), ComputationGraphBuilder::Check(), NnetComputer::CheckInputs(), Compiler::ComputeDerivNeeded(), kaldi::nnet3::ComputeMatrixAccesses(), ComputationGraphBuilder::ComputeRequiredArray(), Compiler::DeallocateMatrices(), ComputationGraphBuilder::ExplainWhyAllOutputsNotComputable(), Nnet::GetAsConfigLine(), kaldi::nnet3::GetComputationRequest(), NnetComputer::GetMatrixIndex(), kaldi::nnet3::IsSimpleNnet(), kaldi::nnet3::NumOutputNodes(), Nnet::OutputDim(), NnetComputeProb::ProcessOutputs(), NnetTrainer::ProcessOutputs(), kaldi::nnet3::ReplaceInInput(), kaldi::nnet3::ReplaceInOutput(), and Compiler::SetInputOutputInfo().
{
   int32 size = nodes_.size();
   KALDI_ASSERT(node >= 0 && node < size);
   return (nodes_[node].node_type == kDescriptor &&
           (node + 1 == size ||
            nodes_[node + 1].node_type != kComponent));
 }
int32 Modulus () const
[Relevant for clockwork RNNs and similar].
Computes the smallest integer n >=1 such that the neural net's behavior will be the same if we shift the input and output's time indexes (t) by integer multiples of n. Does this by computing the lcm of all the moduli of the Descriptors in the network.
Definition at line 624 of file nnet-nnet.cc.
References NetworkNode::descriptor, kaldi::nnet3::kDescriptor, kaldi::Lcm(), Descriptor::Modulus(), rnnlm::n, NetworkNode::node_type, Nnet::nodes_, and Nnet::NumNodes().
Referenced by NnetDecodableBase::CheckAndFixConfigs(), kaldi::nnet3::ComputeSimpleNnetContext(), and Nnet::Info().
{
   int32 ans = 1;
   for (int32 n = 0; n < NumNodes(); n++) {
     const NetworkNode &node = nodes_[n];
     if (node.node_type == kDescriptor)
       ans = Lcm(ans, node.descriptor.Modulus());
   }
   return ans;
 }
int32 NumComponents () const inline
Definition at line 122 of file nnet-nnet.h.
References Nnet::components_.
Referenced by kaldi::nnet3::AddNnet(), ComputationChecker::CheckComputationIndexes(), kaldi::nnet3::ComponentDotProducts(), NnetCombiner::ComputeUpdatableComponentDims(), ModelUpdateConsolidator::ConsolidateModelUpdate(), kaldi::nnet3::DotProduct(), kaldi::nnet3::NnetParametersAreIdentical(), kaldi::nnet3::NumParameters(), kaldi::nnet3::NumUpdatableComponents(), kaldi::nnet3::PerturbParams(), NnetCombiner::PrintParams(), kaldi::nnet3::PrintVectorPerUpdatableComponent(), kaldi::nnet3::ScaleNnet(), kaldi::nnet3::SetLearningRate(), kaldi::nnet3::SetZero(), kaldi::nnet3::UnVectorizeNnet(), kaldi::nnet3::VectorizeNnet(), and kaldi::nnet3::ZeroComponentStats().
 { return components_.size(); }
int32 NumNodes () const inline
Definition at line 124 of file nnet-nnet.h.
References Nnet::nodes_.
Referenced by kaldi::nnet3::compute_computation_steps::AddDimRangeSteps(), kaldi::nnet3::computation_graph::ComputeEpochInfo(), Nnet::GetConfigLines(), Nnet::Modulus(), kaldi::nnet3::NnetToDirectedGraph(), kaldi::nnet3::NumInputNodes(), and kaldi::nnet3::NumOutputNodes().
 { return nodes_.size(); }
Nnet & operator= (const Nnet & nnet)
Definition at line 751 of file nnet-nnet.cc.
References Nnet::Check(), Nnet::component_names_, Nnet::components_, Nnet::Destroy(), rnnlm::i, Nnet::node_names_, and Nnet::nodes_.
{
   if (this == &nnet)
     return *this;
   Destroy();
   component_names_ = nnet.component_names_;
   components_.resize(nnet.components_.size());
   node_names_ = nnet.node_names_;
   nodes_ = nnet.nodes_;
   for (size_t i = 0; i < components_.size(); i++)
     components_[i] = nnet.components_[i]->Copy();
   Check();
   return *this;
 }
int32 OutputDim (const std::string & output_name) const
Definition at line 643 of file nnet-nnet.cc.
References NetworkNode::Dim(), Nnet::GetNodeIndex(), Nnet::IsOutputNode(), rnnlm::n, and Nnet::nodes_.
Referenced by AmNnetSimple::Info(), kaldi::nnet3::NnetInfo(), AmNnetSimple::NumPdfs(), AmNnetSimple::SetNnet(), AmNnetSimple::SetPriors(), kaldi::nnet3::UnitTestNnetInputDerivatives(), and kaldi::nnet3::UnitTestNnetModelDerivatives().
{
   int32 n = GetNodeIndex(input_name);
   if (n == -1 || !IsOutputNode(n)) return -1;
   const NetworkNode &node = nodes_[n];
   return node.Dim(*this);
 }
void ProcessComponentConfigLine (int32 initial_num_components, ConfigLine * config) private
Definition at line 225 of file nnet-nnet.cc.
References Nnet::component_names_, Nnet::components_, Nnet::GetComponentIndex(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), Component::InitFromConfig(), kaldi::IsToken(), KALDI_ERR, Component::NewComponentOfType(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
Referenced by Nnet::ReadConfig().
{
   std::string name, type;
   if (!config->GetValue("name", &name))
     KALDI_ERR << "Expected field name=<component-name> in config line: "
               << config->WholeLine();
   if (!IsToken(name)) // e.g. contains a space.
     KALDI_ERR << "Component name '" << name << "' is not allowed, in line: "
               << config->WholeLine();
   if (!config->GetValue("type", &type))
     KALDI_ERR << "Expected field type=<component-type> in config line: "
               << config->WholeLine();
   Component *new_component = Component::NewComponentOfType(type);
   if (new_component == NULL)
     KALDI_ERR << "Unknown component-type '" << type
               << "' in config file.  Check your code version and config.";
   // the next call will call KALDI_ERR or KALDI_ASSERT and die if something
   // went wrong.
   new_component->InitFromConfig(config);
   int32 index = GetComponentIndex(name);
   if (index != -1) {  // Replacing existing component.
     if (index >= initial_num_components) {
       // that index was something we added from this config.
       KALDI_ERR << "You are adding two components with the same name: '"
                 << name << "'";
     }
     delete components_[index];
     components_[index] = new_component;
   } else {
     components_.push_back(new_component);
     component_names_.push_back(name);
   }
   if (config->HasUnusedValues())
     KALDI_ERR << "Unused values '" << config->UnusedValues()
               << " in config line: " << config->WholeLine();
 }
void ProcessComponentNodeConfigLine (int32 pass, ConfigLine * config) private
Definition at line 264 of file nnet-nnet.cc.
References kaldi::nnet3::DescriptorTokenize(), Nnet::GetComponentIndex(), Nnet::GetNodeIndex(), Nnet::GetSomeNodeNames(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ASSERT, KALDI_ERR, kaldi::nnet3::kComponent, kaldi::nnet3::kDescriptor, Nnet::node_names_, Nnet::nodes_, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
Referenced by Nnet::ReadConfig().
{
   std::string name;
   if (!config->GetValue("name", &name))
     KALDI_ERR << "Expected field name=<component-name> in config line: "
               << config->WholeLine();
   std::string input_name = name + std::string("_input");
   int32 input_node_index = GetNodeIndex(input_name),
       node_index = GetNodeIndex(name);
   if (pass == 0) {
     KALDI_ASSERT(input_node_index == -1 && node_index == -1);
     // just set up the node types and names for now, we'll properly set them up
     // on pass 1.
     nodes_.push_back(NetworkNode(kDescriptor));
     nodes_.push_back(NetworkNode(kComponent));
     node_names_.push_back(input_name);
     node_names_.push_back(name);
     return;
   } else {
     KALDI_ASSERT(input_node_index != -1 && node_index == input_node_index + 1);
     std::string component_name, input_descriptor;
     if (!config->GetValue("component", &component_name))
       KALDI_ERR << "Expected component=<component-name>, in config line: "
                 << config->WholeLine();
     int32 component_index = GetComponentIndex(component_name);
     if (component_index == -1)
       KALDI_ERR << "No component named '" << component_name
                 << "', in config line: " << config->WholeLine();
     nodes_[node_index].u.component_index = component_index;
     if (!config->GetValue("input", &input_descriptor))
       KALDI_ERR << "Expected input=<input-descriptor>, in config line: "
                 << config->WholeLine();
     std::vector<std::string> tokens;
     if (!DescriptorTokenize(input_descriptor, &tokens))
       KALDI_ERR << "Error tokenizing descriptor in config line "
                 << config->WholeLine();
     std::vector<std::string> node_names_temp;
     GetSomeNodeNames(&node_names_temp);
     tokens.push_back("end of input");
     const std::string *next_token = &(tokens[0]);
     if (!nodes_[input_node_index].descriptor.Parse(node_names_temp,
                                                    &next_token))
       KALDI_ERR << "Error parsing Descriptor in config line: "
                 << config->WholeLine();
     if (config->HasUnusedValues())
       KALDI_ERR << "Unused values '" << config->UnusedValues()
                 << " in config line: " << config->WholeLine();
   }
 }
void ProcessDimRangeNodeConfigLine (int32 pass, ConfigLine * config) private
Definition at line 398 of file nnet-nnet.cc.
References NetworkNode::dim, NetworkNode::dim_offset, Nnet::GetNodeIndex(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ASSERT, KALDI_ERR, kaldi::nnet3::kComponent, kaldi::nnet3::kDimRange, kaldi::nnet3::kInput, NetworkNode::node_index, Nnet::node_names_, NetworkNode::node_type, Nnet::nodes_, NetworkNode::u, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
Referenced by Nnet::ReadConfig().
{
   std::string name;
   if (!config->GetValue("name", &name))
     KALDI_ERR << "Expected field name=<input-name> in config line: "
               << config->WholeLine();
   int32 node_index = GetNodeIndex(name);
   if (pass == 0) {
     KALDI_ASSERT(node_index == -1);
     nodes_.push_back(NetworkNode(kDimRange));
     node_names_.push_back(name);
   } else {
     KALDI_ASSERT(node_index != -1);
     std::string input_node_name;
     if (!config->GetValue("input-node", &input_node_name))
       KALDI_ERR << "Expected input-node=<input-node-name>, in config line: "
                 << config->WholeLine();
     int32 dim, dim_offset;
     if (!config->GetValue("dim", &dim))
       KALDI_ERR << "Expected dim=<feature-dim>, in config line: "
                 << config->WholeLine();
     if (!config->GetValue("dim-offset", &dim_offset))
       KALDI_ERR << "Expected dim-offset=<dimension-offset>, in config line: "
                 << config->WholeLine();
     int32 input_node_index = GetNodeIndex(input_node_name);
     if (input_node_index == -1 ||
         !(nodes_[input_node_index].node_type == kComponent ||
           nodes_[input_node_index].node_type == kInput))
       KALDI_ERR << "invalid input-node " << input_node_name
                 << ": " << config->WholeLine();
     if (config->HasUnusedValues())
       KALDI_ERR << "Unused values '" << config->UnusedValues()
                 << " in config line: " << config->WholeLine();
     NetworkNode &node = nodes_[node_index];
     KALDI_ASSERT(node.node_type == kDimRange);
     node.u.node_index = input_node_index;
     node.dim = dim;
     node.dim_offset = dim_offset;
   }
 }
void ProcessInputNodeConfigLine (ConfigLine * config) private
Definition at line 320 of file nnet-nnet.cc.
References Nnet::GetNodeIndex(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ASSERT, KALDI_ERR, kaldi::nnet3::kInput, Nnet::node_names_, Nnet::nodes_, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
Referenced by Nnet::ReadConfig().
{
   std::string name;
   if (!config->GetValue("name", &name))
     KALDI_ERR << "Expected field name=<input-name> in config line: "
               << config->WholeLine();
   int32 dim;
   if (!config->GetValue("dim", &dim))
     KALDI_ERR << "Expected field dim=<input-dim> in config line: "
               << config->WholeLine();
   if (config->HasUnusedValues())
     KALDI_ERR << "Unused values '" << config->UnusedValues()
               << " in config line: " << config->WholeLine();
   KALDI_ASSERT(GetNodeIndex(name) == -1);
   if (dim <= 0)
     KALDI_ERR << "Invalid dimension in config line: " << config->WholeLine();
   int32 node_index = nodes_.size();
   nodes_.push_back(NetworkNode(kInput));
   nodes_[node_index].dim = dim;
   node_names_.push_back(name);
 }
void ProcessOutputNodeConfigLine (int32 pass, ConfigLine * config) private
Definition at line 346 of file nnet-nnet.cc.
References kaldi::nnet3::DescriptorTokenize(), Nnet::GetNodeIndex(), Nnet::GetSomeNodeNames(), ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ASSERT, KALDI_ERR, kaldi::nnet3::kDescriptor, kaldi::nnet3::kLinear, kaldi::nnet3::kQuadratic, Nnet::node_names_, Nnet::nodes_, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
Referenced by Nnet::ReadConfig().
{
   std::string name;
   if (!config->GetValue("name", &name))
     KALDI_ERR << "Expected field name=<input-name> in config line: "
               << config->WholeLine();
   int32 node_index = GetNodeIndex(name);
   if (pass == 0) {
     KALDI_ASSERT(node_index == -1);
     nodes_.push_back(NetworkNode(kDescriptor));
     node_names_.push_back(name);
   } else {
     KALDI_ASSERT(node_index != -1);
     std::string input_descriptor;
     if (!config->GetValue("input", &input_descriptor))
       KALDI_ERR << "Expected input=<input-descriptor>, in config line: "
                 << config->WholeLine();
     std::vector<std::string> tokens;
     if (!DescriptorTokenize(input_descriptor, &tokens))
       KALDI_ERR << "Error tokenizing descriptor in config line "
                 << config->WholeLine();
     tokens.push_back("end of input");
     // if the following fails it will die.
     std::vector<std::string> node_names_temp;
     GetSomeNodeNames(&node_names_temp);
     const std::string *next_token = &(tokens[0]);
     if (!nodes_[node_index].descriptor.Parse(node_names_temp, &next_token))
       KALDI_ERR << "Error parsing descriptor (input=...) in config line "
                 << config->WholeLine();
     std::string objective_type;
     if (config->GetValue("objective", &objective_type)) {
       if (objective_type == "linear") {
         nodes_[node_index].u.objective_type = kLinear;
       } else if (objective_type == "quadratic") {
         nodes_[node_index].u.objective_type = kQuadratic;
       } else {
         KALDI_ERR << "Invalid objective type: " << objective_type;
       }
     } else {
       // the default objective type is linear.  This is what we use
       // for softmax objectives; the LogSoftmaxLayer is included as the
       // last layer, in this case.
       nodes_[node_index].u.objective_type = kLinear;
     }
     if (config->HasUnusedValues())
       KALDI_ERR << "Unused values '" << config->UnusedValues()
                 << " in config line: " << config->WholeLine();
   }
 }
void Read (std::istream & istream, bool binary)
Definition at line 565 of file nnet-nnet.cc.
References Nnet::component_names_, Nnet::components_, Nnet::Destroy(), kaldi::nnet3::ExpectToken(), KALDI_ASSERT, KALDI_ERR, kaldi::ReadBasicType(), Nnet::ReadConfig(), Component::ReadNew(), and kaldi::ReadToken().
Referenced by AmNnetSimple::Read(), and kaldi::nnet3::UnitTestNnetIo().
{
   Destroy();
   ExpectToken(is, binary, "<Nnet3>");
   std::ostringstream config_file_out;
   std::string cur_line;
   getline(is, cur_line);  // Eat up a single newline.
   if (!(cur_line == "" || cur_line == "\r"))
     KALDI_ERR << "Expected newline in config file, got " << cur_line;
   while (getline(is, cur_line)) {
     // config-file part of file is terminated by an empty line.
     if (cur_line == "" || cur_line == "\r")
       break;
     config_file_out << cur_line << std::endl;
   }
   // Now we read the Components; later we try to parse the config_lines.
   ExpectToken(is, binary, "<NumComponents>");
   int32 num_components;
   ReadBasicType(is, binary, &num_components);
   KALDI_ASSERT(num_components >= 0 && num_components < 100000);
   components_.resize(num_components, NULL);
   component_names_.resize(num_components);
   for (int32 c = 0; c < num_components; c++) {
     ExpectToken(is, binary, "<ComponentName>");
     ReadToken(is, binary, &(component_names_[c]));
     components_[c] = Component::ReadNew(is, binary);
   }
   ExpectToken(is, binary, "</Nnet3>");
   std::istringstream config_file_in(config_file_out.str());
   this->ReadConfig(config_file_in);
 }
void ReadConfig (std::istream & config_file)
Definition at line 161 of file nnet-nnet.cc.
References Nnet::Check(), Nnet::components_, Nnet::GetConfigLines(), rnnlm::i, KALDI_ERR, Nnet::node_names_, Nnet::nodes_, Nnet::ProcessComponentConfigLine(), Nnet::ProcessComponentNodeConfigLine(), Nnet::ProcessDimRangeNodeConfigLine(), Nnet::ProcessInputNodeConfigLine(), Nnet::ProcessOutputNodeConfigLine(), kaldi::nnet3::ReadConfigFile(), and Nnet::RemoveRedundantConfigLines().
Referenced by Nnet::Read(), kaldi::nnet3::UnitTestNnetAnalyze(), kaldi::nnet3::UnitTestNnetCompile(), kaldi::nnet3::UnitTestNnetCompute(), kaldi::nnet3::UnitTestNnetContext(), kaldi::nnet3::UnitTestNnetInputDerivatives(), kaldi::nnet3::UnitTestNnetIo(), kaldi::nnet3::UnitTestNnetModelDerivatives(), and kaldi::nnet3::UnitTestNnetOptimizeWithOptions().
{
   std::vector<std::string> lines;
   // Write into "lines" a config file corresponding to whatever
   // nodes we currently have.  Because the numbering of nodes may
   // change, it's most convenient to convert to the text representation
   // and combine the existing and new config lines in that representation.
   const bool include_dim = false;
   GetConfigLines(include_dim, &lines);
   // we'll later regenerate what we need from nodes_ and node_name_ from the
   // string representation.
   nodes_.clear();
   node_names_.clear();
   int32 num_lines_initial = lines.size();
   ReadConfigFile(config_is, &lines);
   // now "lines" will have comments removed and empty lines stripped out
   std::vector<std::string> first_tokens(lines.size());
   std::vector<ConfigLine> config_lines(lines.size());
   for (size_t i = 0; i < lines.size(); i++) {
     std::istringstream is(lines[i]);
     std::string first_token;
     is >> first_token;
     first_tokens[i] = first_token;
     std::string rest_of_line;
     getline(is, rest_of_line);
     if (!config_lines[i].ParseLine(rest_of_line))
       KALDI_ERR << "Could not parse config-file line '" << lines[i] << "'";
   }
   // the next line will possibly remove some elements from "first_tokens" and
   // "config_lines" so nothing is doubly defined.
   RemoveRedundantConfigLines(num_lines_initial, &first_tokens, &config_lines);
   int32 initial_num_components = components_.size();
   for (int32 pass = 0; pass <= 1; pass++) {
     for (size_t i = 0; i < config_lines.size(); i++) {
       if (first_tokens[i] == "component") {
         if (pass == 0)
           ProcessComponentConfigLine(initial_num_components,
                                      &(config_lines[i]));
       } else if (first_tokens[i] == "component-node") {
         ProcessComponentNodeConfigLine(pass,  &(config_lines[i]));
       } else if (first_tokens[i] == "input-node") {
         if (pass == 0)
           ProcessInputNodeConfigLine(&(config_lines[i]));
       } else if (first_tokens[i] == "output-node") {
         ProcessOutputNodeConfigLine(pass, &(config_lines[i]));
       } else if (first_tokens[i] == "dim-range-node") {
         ProcessDimRangeNodeConfigLine(pass, &(config_lines[i]));
       } else {
         KALDI_ERR << "Invalid config-file line ('" << first_tokens[i]
                   << "' not expected): " << config_lines[i].WholeLine();
       }
     }
   }
   Check();
 }
void RemoveRedundantConfigLines (int32 num_lines_initial, std::vector< std::string > * first_tokens, std::vector< ConfigLine > * configs) static private
Definition at line 464 of file nnet-nnet.cc.
References ConfigLine::GetValue(), rnnlm::i, kaldi::nnet3::IsValidName(), KALDI_ASSERT, KALDI_ERR, and ConfigLine::WholeLine().
Referenced by Nnet::ReadConfig().
{
   int32 num_lines = first_tokens->size();
   KALDI_ASSERT(configs->size() == num_lines &&
                num_lines_initial <= num_lines);
   // node names and component names live in different namespaces.
   unordered_map<std::string, int32, StringHasher> node_name_to_most_recent_line;
   unordered_set<std::string, StringHasher> component_names;
   typedef unordered_map<std::string, int32, StringHasher>::iterator IterType;
   std::vector<bool> to_remove(num_lines, false);
   for (int32 line = 0; line < num_lines; line++) {
     std::string first_token = (*first_tokens)[line];
     ConfigLine &config_line = (*configs)[line];
     std::string name;
     if (!config_line.GetValue("name", &name))
       KALDI_ERR << "Config line has no field 'name=xxx': "
                 << config_line.WholeLine();
     if (!IsValidName(name))
       KALDI_ERR << "Name '" << name << "' is not allowable, in line: "
                 << config_line.WholeLine();
     if ((*first_tokens)[line] == "component") {
       // a line starting with "component"... components live in their own
       // namespace.  No repeats are allowed because we never wrote them
       // to the config generated from the nnet.
       if (!component_names.insert(name).second) {
         // we could not insert it because it was already there.
         KALDI_ERR << "Component name " << name
                   << " appears twice in the same config file.";
       }
     } else {
       // the line defines some sort of network node, e.g. component-node.
       IterType iter = node_name_to_most_recent_line.find(name);
       if (iter != node_name_to_most_recent_line.end()) {
         // name is repeated.
         int32 prev_line = iter->second;
         if (prev_line >= num_lines_initial) {
           // user-provided config contained repeat of node with this name.
           KALDI_ERR << "Node name " << name
                     << " appears twice in the same config file.";
         }
         // following assert checks that the config-file generated
         // from an actual nnet does not contain repeats.. that
         // would be a bug so check it with assert.
         KALDI_ASSERT(line >= num_lines_initial);
         to_remove[prev_line] = true;
       }
       node_name_to_most_recent_line[name] = line;
     }
   }
   // Now remove any lines with to_remove[i] = true.
   std::vector<std::string> first_tokens_out;
   std::vector<ConfigLine> configs_out;
   first_tokens_out.reserve(num_lines);
   configs_out.reserve(num_lines);
   for (int32 i = 0; i < num_lines; i++) {
     if (!to_remove[i]) {
       first_tokens_out.push_back((*first_tokens)[i]);
       configs_out.push_back((*configs)[i]);
     }
   }
   first_tokens->swap(first_tokens_out);
   configs->swap(configs_out);
 }
void Write (std::ostream & ostream, bool binary) const
Definition at line 596 of file nnet-nnet.cc.
References Nnet::component_names_, Nnet::components_, Nnet::GetConfigLines(), rnnlm::i, KALDI_ASSERT, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by kaldi::nnet3::UnitTestNnetIo(), and AmNnetSimple::Write().
{
   WriteToken(os, binary, "<Nnet3>");
   os << std::endl;
   std::vector<std::string> config_lines;
   const bool include_dim = false;
   GetConfigLines(include_dim, &config_lines);
   for (size_t i = 0; i < config_lines.size(); i++) {
     KALDI_ASSERT(!config_lines[i].empty());
     os << config_lines[i] << std::endl;
   }
   // A blank line terminates the config-like section of the file.
   os << std::endl;
   // Now write the Components
   int32 num_components = components_.size();
   WriteToken(os, binary, "<NumComponents>");
   WriteBasicType(os, binary, num_components);
   if (!binary)
     os << std::endl;
   for (int32 c = 0; c < num_components; c++) {
     WriteToken(os, binary, "<ComponentName>");
     WriteToken(os, binary, component_names_[c]);
     components_[c]->Write(os, binary);
     if (!binary)
       os << std::endl;
   }
   WriteToken(os, binary, "</Nnet3>");
 }
Member Data Documentation
std::vector<std::string> component_names_ private
Definition at line 287 of file nnet-nnet.h.
Referenced by Nnet::Check(), Nnet::Destroy(), Nnet::GetAsConfigLine(), Nnet::GetComponentIndex(), Nnet::GetComponentName(), Nnet::GetComponentNames(), Nnet::Info(), Nnet::operator=(), Nnet::ProcessComponentConfigLine(), Nnet::Read(), and Nnet::Write().
std::vector<Component*> components_ private
Definition at line 292 of file nnet-nnet.h.
Referenced by Nnet::Check(), Nnet::Destroy(), Nnet::GetComponent(), Nnet::Info(), Nnet::Nnet(), Nnet::NumComponents(), Nnet::operator=(), Nnet::ProcessComponentConfigLine(), Nnet::Read(), Nnet::ReadConfig(), and Nnet::Write().
std::vector<std::string> node_names_ private
Definition at line 298 of file nnet-nnet.h.
Referenced by Nnet::Check(), Nnet::Destroy(), Nnet::GetAsConfigLine(), Nnet::GetNodeIndex(), Nnet::GetNodeName(), Nnet::GetNodeNames(), Nnet::GetSomeNodeNames(), Nnet::operator=(), Nnet::ProcessComponentNodeConfigLine(), Nnet::ProcessDimRangeNodeConfigLine(), Nnet::ProcessInputNodeConfigLine(), Nnet::ProcessOutputNodeConfigLine(), and Nnet::ReadConfig().
std::vector<NetworkNode> nodes_ private
Definition at line 301 of file nnet-nnet.h.
Referenced by Nnet::Check(), Nnet::Destroy(), Nnet::GetAsConfigLine(), Nnet::GetNode(), Nnet::GetSomeNodeNames(), Nnet::InputDim(), Nnet::IsComponentInputNode(), Nnet::IsComponentNode(), Nnet::IsDescriptorNode(), Nnet::IsDimRangeNode(), Nnet::IsInputNode(), Nnet::IsOutputNode(), Nnet::Modulus(), Nnet::NumNodes(), Nnet::operator=(), Nnet::OutputDim(), Nnet::ProcessComponentNodeConfigLine(), Nnet::ProcessDimRangeNodeConfigLine(), Nnet::ProcessInputNodeConfigLine(), Nnet::ProcessOutputNodeConfigLine(), and Nnet::ReadConfig().
The documentation for this class was generated from the following files:
nnet3/nnet-nnet.h
nnet3/nnet-nnet.cc