Kaldi: MatrixRandomizer Class Reference
MatrixRandomizer Class Reference
Randomizes rows of a matrix according to a mask.
#include <nnet-randomizer.h>
Public Member Functions
MatrixRandomizer ()
MatrixRandomizer (const NnetDataRandomizerOptions &conf)
void Init (const NnetDataRandomizerOptions &conf)
Set the randomizer parameters (size)
void AddData (const CuMatrixBase< BaseFloat > &m)
Add data to randomization buffer.
bool IsFull ()
Returns true, when capacity is full.
int32 NumFrames ()
Number of frames stored inside the Randomizer.
void Randomize (const std::vector< int32 > &mask)
Randomize matrix row-order using mask.
bool Done ()
Returns true, if no more data for another mini-batch (after current one)
void Next ()
Sets cursor to next mini-batch.
const CuMatrixBase< BaseFloat > & Value ()
Returns matrix-window with next mini-batch.
Private Attributes
CuMatrix< BaseFloat > data_
CuMatrix< BaseFloat > data_aux_
CuMatrix< BaseFloat > minibatch_
int32 data_begin_
Cursor to beginning of data (row index, moves as mini-batches are delivered)
int32 data_end_
Cursor past the end of data (row index)
NnetDataRandomizerOptions conf_
Detailed Description
Randomizes rows of a matrix according to a mask.
Definition at line 66 of file nnet-randomizer.h.
Constructor & Destructor Documentation
MatrixRandomizer () inline
Definition at line 68 of file nnet-randomizer.h.
 : data_begin_(0), data_end_(0) { }
MatrixRandomizer (const NnetDataRandomizerOptions & conf) inline
Definition at line 69 of file nnet-randomizer.h.
References MatrixRandomizer::Init().
 : data_begin_(0), data_end_(0) { Init(conf); }
Member Function Documentation
void AddData (const CuMatrixBase< BaseFloat > & m)
Add data to randomization buffer.
Definition at line 45 of file nnet-randomizer.cc.
References MatrixRandomizer::conf_, MatrixRandomizer::data_, MatrixRandomizer::data_begin_, MatrixRandomizer::data_end_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), NnetDataRandomizerOptions::randomizer_size, CuMatrix< Real >::Resize(), CuMatrixBase< Real >::RowRange(), and kaldi::nnet3::SetZero().
Referenced by main(), and UnitTestMatrixRandomizer().
{
   // pre-allocate before 1st use
   if(data_.NumCols() == 0) {
     data_.Resize(conf_.randomizer_size,m.NumCols());
   }
   // optionally put previous left-over to front
   if (data_begin_ > 0) {
     KALDI_ASSERT(data_begin_ <= data_end_); // sanity check
     int32 leftover = data_end_ - data_begin_;
     KALDI_ASSERT(leftover < data_begin_); // no overlap
     if(leftover > 0) {
       data_.RowRange(0,leftover).CopyFromMat(data_.RowRange(data_begin_,leftover));
     }
     data_begin_ = 0; data_end_ = leftover;
     data_.RowRange(leftover,data_.NumRows()-leftover).SetZero(); // zeroing the rest
   }
   // extend the buffer if necessary
   if(data_.NumRows() < data_end_ + m.NumRows()) {
     CuMatrix<BaseFloat> data_aux(data_);
     data_.Resize(data_end_ + m.NumRows() + 1000, data_.NumCols()); // +1000 row extra
     data_.RowRange(0,data_aux.NumRows()).CopyFromMat(data_aux);
   }
   // copy the data
   data_.RowRange(data_end_,m.NumRows()).CopyFromMat(m);
   data_end_ += m.NumRows();
 }
bool Done () inline
Returns true, if no more data for another mini-batch (after current one)
Definition at line 83 of file nnet-randomizer.h.
References MatrixRandomizer::conf_, MatrixRandomizer::data_begin_, MatrixRandomizer::data_end_, and NnetDataRandomizerOptions::minibatch_size.
Referenced by main(), and UnitTestMatrixRandomizer().
 { return (data_end_ - data_begin_ < conf_.minibatch_size); }
void Init (const NnetDataRandomizerOptions & conf) inline
Set the randomizer parameters (size)
Definition at line 71 of file nnet-randomizer.h.
References MatrixRandomizer::conf_.
Referenced by MatrixRandomizer::MatrixRandomizer(), and UnitTestMatrixRandomizer().
 { conf_ = conf; }
bool IsFull () inline
Returns true, when capacity is full.
Definition at line 76 of file nnet-randomizer.h.
References MatrixRandomizer::conf_, MatrixRandomizer::data_begin_, MatrixRandomizer::data_end_, and NnetDataRandomizerOptions::randomizer_size.
Referenced by main(), and UnitTestMatrixRandomizer().
 { return ((data_begin_ == 0) && (data_end_ > conf_.randomizer_size )); }
void Next ()
Sets cursor to next mini-batch.
Definition at line 89 of file nnet-randomizer.cc.
References MatrixRandomizer::conf_, MatrixRandomizer::data_begin_, and NnetDataRandomizerOptions::minibatch_size.
Referenced by main(), and UnitTestMatrixRandomizer().
{
   data_begin_ += conf_.minibatch_size;
 }
int32 NumFrames () inline
Number of frames stored inside the Randomizer.
Definition at line 78 of file nnet-randomizer.h.
References MatrixRandomizer::data_end_.
Referenced by main(), and UnitTestMatrixRandomizer().
 { return data_end_; }
void Randomize (const std::vector< int32 > & mask)
Randomize matrix row-order using mask.
Definition at line 72 of file nnet-randomizer.cc.
References CuArray< T >::CopyFromVec(), MatrixRandomizer::data_, MatrixRandomizer::data_aux_, MatrixRandomizer::data_begin_, MatrixRandomizer::data_end_, KALDI_ASSERT, and kaldi::cu::Randomize().
Referenced by main(), and UnitTestMatrixRandomizer().
{
   KALDI_ASSERT(data_begin_ == 0);
   KALDI_ASSERT(data_end_ > 0);
   KALDI_ASSERT(data_end_ == mask.size());
   // Copy to auxiliary buffer for unshuffled data
   data_aux_ = data_;
   // Put the mask to GPU
   CuArray<int32> mask_in_gpu(mask.size());
   mask_in_gpu.CopyFromVec(mask);
   // Randomize the data, mask is used to index rows in source matrix:
   // (Here the vector 'mask_in_gpu' is typically shorter than number of rows in 'data_aux_',
   //  because the the buffer 'data_aux_' is larger than capacity 'randomizer_size'.
   //  The extra rows in 'data_aux_' do not contain speech frames and are not copied
   //  from 'data_aux_', the extra rows in 'data_' are unchanged by cu::Randomize.)
   cu::Randomize(data_aux_, mask_in_gpu, &data_);
 }
const CuMatrixBase< BaseFloat > & Value ()
Returns matrix-window with next mini-batch.
Definition at line 93 of file nnet-randomizer.cc.
References MatrixRandomizer::conf_, CuMatrixBase< Real >::CopyFromMat(), MatrixRandomizer::data_, MatrixRandomizer::data_begin_, MatrixRandomizer::data_end_, KALDI_ASSERT, kaldi::kUndefined, MatrixRandomizer::minibatch_, NnetDataRandomizerOptions::minibatch_size, CuMatrixBase< Real >::NumCols(), CuMatrix< Real >::Resize(), and CuMatrixBase< Real >::RowRange().
Referenced by main(), and UnitTestMatrixRandomizer().
{
   KALDI_ASSERT(data_end_ - data_begin_ >= conf_.minibatch_size); // have data for minibatch
   minibatch_.Resize(conf_.minibatch_size, data_.NumCols(),kUndefined);
   minibatch_.CopyFromMat(data_.RowRange(data_begin_,conf_.minibatch_size));
   return minibatch_;
 }
Member Data Documentation
NnetDataRandomizerOptions conf_ private
Definition at line 99 of file nnet-randomizer.h.
Referenced by MatrixRandomizer::AddData(), MatrixRandomizer::Done(), MatrixRandomizer::Init(), MatrixRandomizer::IsFull(), MatrixRandomizer::Next(), and MatrixRandomizer::Value().
CuMatrix<BaseFloat> data_ private
Definition at line 90 of file nnet-randomizer.h.
Referenced by MatrixRandomizer::AddData(), MatrixRandomizer::Randomize(), and MatrixRandomizer::Value().
CuMatrix<BaseFloat> data_aux_ private
Definition at line 91 of file nnet-randomizer.h.
Referenced by MatrixRandomizer::Randomize().
int32 data_begin_ private
Cursor to beginning of data (row index, moves as mini-batches are delivered)
Definition at line 95 of file nnet-randomizer.h.
Referenced by MatrixRandomizer::AddData(), MatrixRandomizer::Done(), MatrixRandomizer::IsFull(), MatrixRandomizer::Next(), MatrixRandomizer::Randomize(), and MatrixRandomizer::Value().
int32 data_end_ private
Cursor past the end of data (row index)
Definition at line 97 of file nnet-randomizer.h.
Referenced by MatrixRandomizer::AddData(), MatrixRandomizer::Done(), MatrixRandomizer::IsFull(), MatrixRandomizer::NumFrames(), MatrixRandomizer::Randomize(), and MatrixRandomizer::Value().
CuMatrix<BaseFloat> minibatch_ private
Definition at line 92 of file nnet-randomizer.h.
Referenced by MatrixRandomizer::Value().
The documentation for this class was generated from the following files:
nnet/nnet-randomizer.h
nnet/nnet-randomizer.cc