Kaldi: MultiSinusoidDetector Class Reference
MultiSinusoidDetector Class Reference
FeatureExtraction
#include <sinusoid-detection.h>
Public Member Functions
MultiSinusoidDetector (const MultiSinusoidDetectorConfig &config, int32 sampling_freq)
void AcceptWaveform (const VectorBase< BaseFloat > &waveform)
This is how the class acccepts its input.
void WaveformFinished ()
The user calls this to announce to the class that the waveform has ended; this forces any pending data to be flushed.
void Reset ()
Resets the state of the class so you can start processing another waveform.
bool Done () const
This returns true if the class currently has no more data ready to output.
void GetNextFrame (MultiSinusoidDetectorOutput *output)
Outputs the next frame of output to "frame", which must be non-NULL.
BaseFloat FrameShiftSecs () const
BaseFloat SamplingFrequency () const
Private Member Functions
void GetNextFrameOfSignal (Vector< BaseFloat > *frame)
bool DetectedTwoFrequency (BaseFloat signal_energy, const Sinusoid &sinusoid1, BaseFloat energy1, const Sinusoid &sinusoid2, BaseFloat energy2, MultiSinusoidDetectorOutput *output)
bool DetectedOneFrequency (BaseFloat signal_energy, const Sinusoid &sinusoid1, BaseFloat energy1, const Sinusoid &sinusoid2, BaseFloat energy2, MultiSinusoidDetectorOutput *output)
int32 NumSubsampledSamplesReady (int32 max_samp) const
Private Attributes
MultiSinusoidDetectorConfig config_
int32 sample_freq_
int32 samples_per_frame_subsampled_
int32 samples_shift_subsampled_
bool waveform_finished_
std::deque< Vector< BaseFloat > * > subsampled_signal_
int32 samples_consumed_
LinearResample resampler_
SinusoidDetector detector_
Detailed Description
Definition at line 336 of file sinusoid-detection.h.
Constructor & Destructor Documentation
MultiSinusoidDetector (const MultiSinusoidDetectorConfig & config, int32 sampling_freq)
Definition at line 666 of file sinusoid-detection.cc.
References MultiSinusoidDetectorConfig::Check().
                         :
     config_(config),
     sample_freq_(sampling_freq),
     samples_per_frame_subsampled_(0.001 * config.frame_length_ms *
                                   static_cast<BaseFloat>(config.subsample_freq)),
     samples_shift_subsampled_(0.001 * config.frame_shift_ms *
                               static_cast<BaseFloat>(config.subsample_freq)),
     waveform_finished_(false),
     samples_consumed_(0),
     resampler_(sampling_freq, config.subsample_freq,
                config.subsample_filter_cutoff, config.subsample_filter_zeros),
     detector_(config.subsample_freq, samples_per_frame_subsampled_) {
   config.Check();
 }
Member Function Documentation
void AcceptWaveform (const VectorBase< BaseFloat > & waveform)
This is how the class acccepts its input.
You can put the waveform in piece by piece, if it's an online application.
Definition at line 710 of file sinusoid-detection.cc.
References LinearResample::Resample(), MultiSinusoidDetector::resampler_, and MultiSinusoidDetector::subsampled_signal_.
Referenced by kaldi::DetectSinusoids(), and kaldi::UnitTestToneDetection2().
{
   subsampled_signal_.push_back(new Vector<BaseFloat>());
   bool flush = false;
   resampler_.Resample(waveform, flush,
                       subsampled_signal_.back());
   if (subsampled_signal_.back()->Dim() == 0) {
     delete subsampled_signal_.back();
     subsampled_signal_.pop_back();
   }
 }
bool DetectedOneFrequency (BaseFloat signal_energy, const Sinusoid & sinusoid1, BaseFloat energy1, const Sinusoid & sinusoid2, BaseFloat energy2, MultiSinusoidDetectorOutput * output) private
Definition at line 880 of file sinusoid-detection.cc.
References MultiSinusoidDetector::config_, MultiSinusoidDetectorOutput::energy1, MultiSinusoidDetectorOutput::energy2, Sinusoid::freq, MultiSinusoidDetectorOutput::freq1, MultiSinusoidDetectorOutput::freq2, MultiSinusoidDetectorConfig::max_freq, MultiSinusoidDetectorConfig::min_freq, and MultiSinusoidDetectorConfig::one_freq_min_energy.
Referenced by MultiSinusoidDetector::GetNextFrame().
{
   // If sinusoid detection were performing exactly to spec, we could assume
   // energy1 >= energy2, but we don't assume this as it's not guaranteed.
   if (energy1 > energy2 && energy1 > signal_energy *
       config_.one_freq_min_energy &&
       sinusoid1.freq >= config_.min_freq &&
       sinusoid1.freq <= config_.max_freq) {
     output->freq1 = sinusoid1.freq;
     output->energy1 = energy1 / signal_energy;
     output->freq2 = 0.0;
     output->energy2 = 0.0;
     return true;
   } else if (energy2 > energy1 && energy2 > signal_energy *
              config_.one_freq_min_energy &&
              sinusoid2.freq >= config_.min_freq &&
              sinusoid2.freq <= config_.max_freq) {
     output->freq1 = sinusoid2.freq;
     output->energy1 = energy2 / signal_energy;
     output->freq2 = 0.0;
     output->energy2 = 0.0;
     return true;
   } else {
     return false;
   }
 }
bool DetectedTwoFrequency (BaseFloat signal_energy, const Sinusoid & sinusoid1, BaseFloat energy1, const Sinusoid & sinusoid2, BaseFloat energy2, MultiSinusoidDetectorOutput * output) private
Definition at line 850 of file sinusoid-detection.cc.
References MultiSinusoidDetector::config_, MultiSinusoidDetectorOutput::energy1, MultiSinusoidDetectorOutput::energy2, Sinusoid::freq, MultiSinusoidDetectorOutput::freq1, MultiSinusoidDetectorOutput::freq2, MultiSinusoidDetectorConfig::max_freq, MultiSinusoidDetectorConfig::min_freq, kaldi::swap(), MultiSinusoidDetectorConfig::two_freq_min_energy, and MultiSinusoidDetectorConfig::two_freq_min_total_energy.
Referenced by MultiSinusoidDetector::GetNextFrame().
{
   if (energy1 + energy2 >= signal_energy *
       config_.two_freq_min_total_energy &&
       std::min(energy1, energy2) >= signal_energy *
       config_.two_freq_min_energy &&
       std::min(sinusoid1.freq, sinusoid2.freq) >= config_.min_freq &&
       std::max(sinusoid1.freq, sinusoid2.freq) <= config_.max_freq) {
     output->freq1 = sinusoid1.freq;
     output->energy1 = energy1 / signal_energy;
     output->freq2 = sinusoid2.freq;
     output->energy2 = energy2 / signal_energy;
     if (output->freq1 > output->freq2) {
       std::swap(output->freq1, output->freq2);
       std::swap(output->energy1, output->energy2);
     }
     return true;
   } else {
     return false;
   }
 }
bool Done () const
This returns true if the class currently has no more data ready to output.
Definition at line 739 of file sinusoid-detection.cc.
References MultiSinusoidDetector::NumSubsampledSamplesReady(), MultiSinusoidDetector::samples_per_frame_subsampled_, and MultiSinusoidDetector::waveform_finished_.
Referenced by kaldi::DetectSinusoids(), and kaldi::UnitTestToneDetection2().
{
   int32 samp_ready = NumSubsampledSamplesReady(samples_per_frame_subsampled_);
   if ((samp_ready >= samples_per_frame_subsampled_ && !waveform_finished_) ||
       (samp_ready > 0 && waveform_finished_))
     return false;
   else
     return true;
 }
BaseFloat FrameShiftSecs () const inline
Definition at line 362 of file sinusoid-detection.h.
References MultiSinusoidDetector::config_, and MultiSinusoidDetectorConfig::frame_shift_ms.
Referenced by kaldi::DetectSinusoids().
 { return 0.001 * config_.frame_shift_ms; }
void GetNextFrame (MultiSinusoidDetectorOutput * output)
Outputs the next frame of output to "frame", which must be non-NULL.
It is an error to call this if Done() has returned true, or has not been checked.
Definition at line 778 of file sinusoid-detection.cc.
References VectorBase< Real >::Add(), kaldi::AddSinusoid(), MultiSinusoidDetector::config_, MultiSinusoidDetector::DetectedOneFrequency(), MultiSinusoidDetector::DetectedTwoFrequency(), MultiSinusoidDetector::detector_, SinusoidDetector::DetectSinusoid(), VectorBase< Real >::Dim(), MultiSinusoidDetector::GetNextFrameOfSignal(), KALDI_VLOG, M_PI, MultiSinusoidDetectorConfig::one_freq_min_energy, Sinusoid::phase, MultiSinusoidDetectorConfig::subsample_freq, VectorBase< Real >::Sum(), MultiSinusoidDetectorOutput::tot_energy, MultiSinusoidDetectorConfig::two_freq_min_energy, MultiSinusoidDetectorConfig::two_freq_min_total_energy, and kaldi::VecVec().
Referenced by kaldi::DetectSinusoids(), and kaldi::UnitTestToneDetection2().
{
   Vector<BaseFloat> frame;
   GetNextFrameOfSignal(&frame);
   // Mean subtraction
   frame.Add(-1.0 * frame.Sum() / frame.Dim());
   *output = MultiSinusoidDetectorOutput();  // reset to default.
   BaseFloat signal_energy = VecVec(frame, frame);
   output->tot_energy = signal_energy / frame.Dim();
   if (signal_energy == 0.0) return;
   // min_energy1 is the lowest energy we might care about.
   BaseFloat min_energy1 = signal_energy *
       std::min<BaseFloat>(config_.two_freq_min_total_energy * 0.5,
                           config_.one_freq_min_energy);
   Sinusoid sinusoid1;
   BaseFloat energy1 = detector_.DetectSinusoid(min_energy1,
                                                       frame,
                                                       &sinusoid1);
   if (energy1 == 0.0) return;  // Nothing detected.
   // we only care about the 2nd sinusoid if
   // energy1 + energy2 >= signal_energy * two_freq_min_total_energy,
   // and energy2 >= signal_energy * config.two_freq_min_energy.
   BaseFloat min_energy2 =
       std::max(signal_energy * config_.two_freq_min_energy,
                signal_energy * config_.two_freq_min_total_energy
                - energy1);
   BaseFloat energy2;
   Sinusoid sinusoid2;
   // If there is enough energy left in the signal that we could
   // possibly detect a sinusoid of energy at least min_energy2...
   if (min_energy2 <= signal_energy - energy1) {
     sinusoid1.phase += M_PI;  // reverse the phase.
     AddSinusoid(config_.subsample_freq, sinusoid1, &frame);
     energy2 = detector_.DetectSinusoid(min_energy2,
                                               frame,
                                               &sinusoid2);
     if (energy2 > energy1) {
       // The following is just for our information, so we are aware
       // when the sinusoid detection gives us the non-optimal sinusoid
       // first.
       BaseFloat factor = energy2 / energy1;
       KALDI_VLOG(2) << "Second sinusoid greater than first by a factor of "
                     << factor << ".  (This means sinusoid detection is not "
                     << " working ideally).";
     }
     if (DetectedTwoFrequency(signal_energy,
                              sinusoid1, energy1,
                              sinusoid2, energy2,
                              output))
       return;
   } else {
     energy2 = 0.0;
   }
   // We don't need the return status of the following; we just return anyway.
   DetectedOneFrequency(signal_energy,
                        sinusoid1, energy1,
                        sinusoid2, energy2,
                        output);
 }
void GetNextFrameOfSignal (Vector< BaseFloat > * frame) private
Definition at line 748 of file sinusoid-detection.cc.
References VectorBase< Real >::Dim(), KALDI_ASSERT, kaldi::kUndefined, VectorBase< Real >::Range(), Vector< Real >::Resize(), MultiSinusoidDetector::samples_consumed_, MultiSinusoidDetector::samples_per_frame_subsampled_, MultiSinusoidDetector::subsampled_signal_, and MultiSinusoidDetector::waveform_finished_.
Referenced by MultiSinusoidDetector::GetNextFrame().
{
   frame->Resize(samples_per_frame_subsampled_, kUndefined);
   int32 sample_offset = 0,
       samples_needed = samples_per_frame_subsampled_;
   while (samples_needed > 0 &&
          !subsampled_signal_.empty()) {
     Vector<BaseFloat> *src = subsampled_signal_.front();
     int32 num_samples_avail = src->Dim() - samples_consumed_;
     KALDI_ASSERT(num_samples_avail > 0);
     int32 chunk_size = std::min(num_samples_avail,
                                  samples_needed);
     frame->Range(sample_offset, chunk_size).CopyFromVec(
         src->Range(samples_consumed_, chunk_size));
     sample_offset += chunk_size;
     samples_needed -= chunk_size;
     samples_consumed_ += chunk_size;
     if (samples_consumed_ == src->Dim()) {
       samples_consumed_ = 0;
       delete src;
       subsampled_signal_.pop_front();
     }
   }
   if (samples_needed > 0) {
     KALDI_ASSERT(waveform_finished_ && sample_offset > 0);  // or code error.
     frame->Range(sample_offset, samples_needed).SetZero();
   }
 }
int32 NumSubsampledSamplesReady (int32 max_samp) const private
Definition at line 724 of file sinusoid-detection.cc.
References rnnlm::i, KALDI_ASSERT, MultiSinusoidDetector::samples_consumed_, and MultiSinusoidDetector::subsampled_signal_.
Referenced by MultiSinusoidDetector::Done().
{
   KALDI_ASSERT(samples_consumed_ >= 0 &&
                ((subsampled_signal_.empty() && samples_consumed_ == 0) ||
                 (!subsampled_signal_.empty () && samples_consumed_ <
                  subsampled_signal_[0]->Dim())));
   int32 ans = -samples_consumed_;
   for (size_t i = 0; i < subsampled_signal_.size(); i++) {
     ans += subsampled_signal_[i]->Dim();
     if (ans > max_samp) break;
   }
   KALDI_ASSERT(ans >= 0);
   return std::min(ans, max_samp);
 }
void Reset ()
Resets the state of the class so you can start processing another waveform.
Definition at line 684 of file sinusoid-detection.cc.
References MultiSinusoidDetector::resampler_, LinearResample::Reset(), MultiSinusoidDetector::samples_consumed_, MultiSinusoidDetector::subsampled_signal_, and MultiSinusoidDetector::waveform_finished_.
Referenced by kaldi::DetectSinusoids().
{
   waveform_finished_ = false;
   samples_consumed_ = 0;
   while(!subsampled_signal_.empty()) {
     delete subsampled_signal_.front();
     subsampled_signal_.pop_front();
   }
   resampler_.Reset();
 }
BaseFloat SamplingFrequency () const inline
Definition at line 364 of file sinusoid-detection.h.
References MultiSinusoidDetector::sample_freq_.
Referenced by kaldi::DetectSinusoids().
 { return sample_freq_; }
void WaveformFinished ()
The user calls this to announce to the class that the waveform has ended; this forces any pending data to be flushed.
Definition at line 694 of file sinusoid-detection.cc.
References KALDI_ASSERT, LinearResample::Resample(), MultiSinusoidDetector::resampler_, MultiSinusoidDetector::subsampled_signal_, and MultiSinusoidDetector::waveform_finished_.
Referenced by kaldi::DetectSinusoids(), and kaldi::UnitTestToneDetection2().
{
   KALDI_ASSERT(!waveform_finished_ &&
                "WaveformFinished() called twice.");
   Vector<BaseFloat> empty_waveform;
   subsampled_signal_.push_back(new Vector<BaseFloat>());
   bool flush = true;
   resampler_.Resample(empty_waveform, flush,
                       subsampled_signal_.back());
   waveform_finished_ = true;
   if (subsampled_signal_.back()->Dim() == 0) {
     delete subsampled_signal_.back();
     subsampled_signal_.pop_back();
   }
 }
Member Data Documentation
MultiSinusoidDetectorConfig config_ private
Definition at line 396 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::DetectedOneFrequency(), MultiSinusoidDetector::DetectedTwoFrequency(), MultiSinusoidDetector::FrameShiftSecs(), and MultiSinusoidDetector::GetNextFrame().
SinusoidDetector detector_ private
Definition at line 424 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::GetNextFrame().
LinearResample resampler_ private
Definition at line 420 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::AcceptWaveform(), MultiSinusoidDetector::Reset(), and MultiSinusoidDetector::WaveformFinished().
int32 sample_freq_ private
Definition at line 397 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::SamplingFrequency().
int32 samples_consumed_ private
Definition at line 416 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::GetNextFrameOfSignal(), MultiSinusoidDetector::NumSubsampledSamplesReady(), and MultiSinusoidDetector::Reset().
int32 samples_per_frame_subsampled_ private
Definition at line 398 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::Done(), and MultiSinusoidDetector::GetNextFrameOfSignal().
int32 samples_shift_subsampled_ private
Definition at line 400 of file sinusoid-detection.h.
std::deque<Vector<BaseFloat>* > subsampled_signal_ private
Definition at line 410 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::AcceptWaveform(), MultiSinusoidDetector::GetNextFrameOfSignal(), MultiSinusoidDetector::NumSubsampledSamplesReady(), MultiSinusoidDetector::Reset(), and MultiSinusoidDetector::WaveformFinished().
bool waveform_finished_ private
Definition at line 404 of file sinusoid-detection.h.
Referenced by MultiSinusoidDetector::Done(), MultiSinusoidDetector::GetNextFrameOfSignal(), MultiSinusoidDetector::Reset(), and MultiSinusoidDetector::WaveformFinished().
The documentation for this class was generated from the following files:
feat/sinusoid-detection.h
feat/sinusoid-detection.cc