Kaldi: ContextMatcher< Arc, LabelT > Class Template Reference
ContextMatcher< Arc, LabelT > Class Template Reference
"Classes and functions related to context expansion"
#include <context-fst.h>
Public Types
typedef Fst< Arc > FST
typedef ContextFst< Arc, LabelT > ContextF
typedef Arc::StateId StateId
typedef Arc::Label Label
typedef Arc::Weight Weight
Public Member Functions
ContextMatcher (const FST &fst, MatchType match_type)
ContextMatcher (const ContextMatcher< Arc, LabelT > &matcher, bool safe)
virtual ~ContextMatcher ()
virtual const FST & GetFst () const
virtual ContextMatcher< Arc,
LabelT > * Copy (bool safe=false) const
virtual MatchType Type (bool test) const
void SetState (StateId s)
bool Find (Label match_label)
bool Done () const
const Arc & Value () const
void Next ()
virtual uint64 Properties (uint64 props) const
Private Member Functions
virtual void SetState_ (StateId s)
virtual bool Find_ (Label label)
virtual bool Done_ () const
virtual const Arc & Value_ () const
virtual void Next_ ()
void operator= (const SortedMatcher< FST > &)
Private Attributes
const FST * fst_
MatchType match_type_
Label match_label_
StateId s_
Arc arc_
bool ready_
bool current_loop_
Detailed Description
template<class Arc, class LabelT>
class fst::ContextMatcher< Arc, LabelT >
Definition at line 389 of file context-fst.h.
Member Typedef Documentation
typedef ContextFst<Arc, LabelT> ContextF
Definition at line 394 of file context-fst.h.
typedef Fst<Arc> FST
Definition at line 391 of file context-fst.h.
typedef Arc::Label Label
Definition at line 396 of file context-fst.h.
typedef Arc::StateId StateId
Definition at line 395 of file context-fst.h.
typedef Arc::Weight Weight
Definition at line 397 of file context-fst.h.
Constructor & Destructor Documentation
ContextMatcher (const FST & fst, MatchType match_type) inline
Definition at line 403 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::match_type_.
       : fst_(fst.Copy()),
         match_label_(kNoLabel),
         s_ (kNoStateId),
         ready_(false) {
     if (match_type == MATCH_OUTPUT && fst.Type() == (string)"context") {
       match_type_ = MATCH_OUTPUT;
     } else {
       match_type_ = MATCH_NONE;
     }
   }
ContextMatcher (const ContextMatcher< Arc, LabelT > & matcher, bool safe) inline
Definition at line 415 of file context-fst.h.
       : fst_(matcher.fst_->Copy(safe)),
         match_type_(matcher.match_type_),
         match_label_(kNoLabel),
         s_ (kNoStateId),
         ready_(false) {}
virtual ~ContextMatcher () inline virtual
Definition at line 422 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::fst_.
{
     delete fst_;
   }
Member Function Documentation
virtual ContextMatcher<Arc, LabelT>* Copy (bool safe = false) const inline virtual
Definition at line 428 of file context-fst.h.
{
     return new ContextMatcher<Arc, LabelT>(*this, safe);
   }
bool Done () const inline
Definition at line 444 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::ready_.
Referenced by ContextMatcher< Arc, LabelT >::Done_().
                     {
     return !ready_;
   }
virtual bool Done_ () const inline private virtual
Definition at line 465 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::Done().
 { return Done(); }
virtual bool Find_ (Label label) inline private virtual
Definition at line 464 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::Find().
 { return Find(label); }
virtual const FST& GetFst () const inline virtual
Definition at line 426 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::fst_.
 { return *fst_; }
void Next () inline
Definition at line 453 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::ready_.
Referenced by ContextMatcher< Arc, LabelT >::Next_().
               {  // we only ever get one arc so just set ready_ to false.
     assert(ready_);
     ready_ = false;
   }
virtual void Next_ () inline private virtual
Definition at line 467 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::Next().
 { Next(); }
void operator= (const SortedMatcher< FST > &) private
virtual uint64 Properties (uint64 props) const inline virtual
Definition at line 459 of file context-fst.h.
 { return props; } // simple matcher that does
void SetState (StateId s) inline
Definition at line 436 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::match_type_, and ContextMatcher< Arc, LabelT >::s_.
Referenced by ContextMatcher< Arc, LabelT >::SetState_().
{
     if (match_type_ == MATCH_NONE)
       LOG(FATAL) << "ContextMatcher: bad match type";
     s_ = s;
   }
virtual void SetState_ (StateId s) inline private virtual
Definition at line 463 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::SetState().
 { SetState(s); }
virtual MatchType Type (bool test) const inline virtual
Definition at line 432 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::match_type_.
{
     return match_type_;
   }
const Arc& Value () const inline
Definition at line 448 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::arc_, and ContextMatcher< Arc, LabelT >::ready_.
Referenced by ContextMatcher< Arc, LabelT >::Value_().
{
     assert(ready_);
     return arc_;
   }
virtual const Arc& Value_ () const inline private virtual
Definition at line 466 of file context-fst.h.
References ContextMatcher< Arc, LabelT >::Value().
 { return Value(); }
Member Data Documentation
Arc arc_ private
Definition at line 473 of file context-fst.h.
Referenced by ContextMatcher< Arc, LabelT >::Value().
bool current_loop_ private
Definition at line 475 of file context-fst.h.
const FST* fst_ private
Definition at line 469 of file context-fst.h.
Referenced by ContextMatcher< Arc, LabelT >::GetFst(), and ContextMatcher< Arc, LabelT >::~ContextMatcher().
Label match_label_ private
Definition at line 471 of file context-fst.h.
MatchType match_type_ private
Definition at line 470 of file context-fst.h.
Referenced by ContextMatcher< Arc, LabelT >::ContextMatcher(), ContextMatcher< Arc, LabelT >::SetState(), and ContextMatcher< Arc, LabelT >::Type().
bool ready_ private
Definition at line 474 of file context-fst.h.
Referenced by ContextMatcher< Arc, LabelT >::Done(), ContextMatcher< Arc, LabelT >::Next(), and ContextMatcher< Arc, LabelT >::Value().
StateId s_ private
Definition at line 472 of file context-fst.h.
Referenced by ContextMatcher< Arc, LabelT >::SetState().
The documentation for this class was generated from the following files:
fstext/context-fst.h
fstext/context-fst-inl.h