Kaldi: WaveHolder Class Reference
WaveHolder Class Reference
#include <wave-reader.h>
Public Types
typedef WaveData T
Public Member Functions
void Copy (const T &t)
void Clear ()
const T & Value ()
WaveHolder & operator= (const WaveHolder &other)
WaveHolder (const WaveHolder &other)
WaveHolder ()
bool Read (std::istream &is)
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Attributes
T t_
Detailed Description
Definition at line 111 of file wave-reader.h.
Member Typedef Documentation
typedef WaveData T
Definition at line 113 of file wave-reader.h.
Constructor & Destructor Documentation
WaveHolder (const WaveHolder & other) inline
Definition at line 140 of file wave-reader.h.
 : t_(other.t_) {}
WaveHolder () inline
Definition at line 142 of file wave-reader.h.
 {}
Member Function Documentation
void Clear () inline
Definition at line 132 of file wave-reader.h.
References WaveData::Clear(), and WaveHolder::t_.
 { t_.Clear(); }
void Copy (const T & t) inline
Definition at line 128 of file wave-reader.h.
References WaveData::CopyFrom(), and WaveHolder::t_.
 { t_.CopyFrom(t); }
static bool IsReadInBinary () inline static
Definition at line 130 of file wave-reader.h.
 { return true; }
WaveHolder& operator= (const WaveHolder & other) inline
Definition at line 136 of file wave-reader.h.
References WaveData::CopyFrom(), and WaveHolder::t_.
{
     t_.CopyFrom(other.t_);
     return *this;
   }
bool Read (std::istream & is) inline
Definition at line 144 of file wave-reader.h.
References kaldi::IsKaldiError(), KALDI_WARN, WaveData::Read(), and WaveHolder::t_.
{
     // We don't look for the binary-mode header here [always binary]
     try {
       t_.Read(is);  // throws exception on failure.
       return true;
     } catch (const std::exception &e) {
       KALDI_WARN << "Exception caught in WaveHolder object (reading).";
       if (!IsKaldiError(e.what())) { std::cerr << e.what(); }
       return false;  // write failure.
     }
   }
const T& Value () inline
Definition at line 134 of file wave-reader.h.
References WaveHolder::t_.
 { return t_; }
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 115 of file wave-reader.h.
References kaldi::IsKaldiError(), KALDI_ERR, KALDI_WARN, and WaveData::Write().
{
     // We don't write the binary-mode header here [always binary].
     if (!binary)
       KALDI_ERR << "Wave data can only be written in binary mode.";
     try {
       t.Write(os);  // throws exception on failure.
       return true;
     } catch (const std::exception &e) {
       KALDI_WARN << "Exception caught in WaveHolder object (writing).";
       if (!IsKaldiError(e.what())) { std::cerr << e.what(); }
       return false;  // write failure.
     }
   }
Member Data Documentation
T t_ private
Definition at line 157 of file wave-reader.h.
Referenced by WaveHolder::Clear(), WaveHolder::Copy(), WaveHolder::operator=(), WaveHolder::Read(), and WaveHolder::Value().
The documentation for this class was generated from the following file:
feat/wave-reader.h