Kaldi: DecodableAmNnetParallel Class Reference
DecodableAmNnetParallel Class Reference
This version of DecodableAmNnet is intended for a version of the decoder that processes different utterances with multiple threads.
#include <decodable-am-nnet.h>
Public Member Functions
DecodableAmNnetParallel (const TransitionModel &trans_model, const AmNnet &am_nnet, const CuMatrix< BaseFloat > *feats, bool pad_input=true, BaseFloat prob_scale=1.0)
void Compute ()
virtual BaseFloat LogLikelihood (int32 frame, int32 transition_id)
Returns the log likelihood, which will be negated in the decoder.
int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
~DecodableAmNnetParallel ()
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Protected Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmNnetParallel)
Protected Attributes
const TransitionModel & trans_model_
const AmNnet & am_nnet_
CuMatrix< BaseFloat > log_probs_
const CuMatrix< BaseFloat > * feats_
bool pad_input_
BaseFloat prob_scale_
Detailed Description
This version of DecodableAmNnet is intended for a version of the decoder that processes different utterances with multiple threads.
It needs to do the computation in a different place than the initializer, since the initializer gets called in the main thread of the program.
Definition at line 105 of file decodable-am-nnet.h.
Constructor & Destructor Documentation
DecodableAmNnetParallel (const TransitionModel & trans_model, const AmNnet & am_nnet, const CuMatrix< BaseFloat > * feats, bool pad_input = true, BaseFloat prob_scale = 1.0) inline
Definition at line 107 of file decodable-am-nnet.h.
References DecodableAmNnetParallel::feats_, and KALDI_ASSERT.
                                  :
       trans_model_(trans_model), am_nnet_(am_nnet), feats_(feats),
       pad_input_(pad_input), prob_scale_(prob_scale) {
     KALDI_ASSERT(feats_ != NULL);
   }
~DecodableAmNnetParallel () inline
Definition at line 166 of file decodable-am-nnet.h.
References DecodableAmNnetParallel::feats_.
{
     delete feats_;
   }
Member Function Documentation
void Compute () inline
Definition at line 118 of file decodable-am-nnet.h.
References CuMatrixBase< Real >::AddVecToRows(), DecodableAmNnetParallel::am_nnet_, CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyLog(), DecodableAmNnetParallel::feats_, AmNnet::GetNnet(), KALDI_ASSERT, DecodableAmNnetParallel::log_probs_, kaldi::nnet2::NnetComputation(), TransitionModel::NumPdfs(), CuMatrixBase< Real >::NumRows(), DecodableAmNnetParallel::pad_input_, AmNnet::Priors(), DecodableAmNnetParallel::prob_scale_, CuMatrix< Real >::Resize(), CuMatrixBase< Real >::Scale(), and DecodableAmNnetParallel::trans_model_.
Referenced by DecodableAmNnetParallel::LogLikelihood().
                  {
     log_probs_.Resize(feats_->NumRows(), trans_model_.NumPdfs());
     // the following function is declared in nnet-compute.h
     NnetComputation(am_nnet_.GetNnet(), *feats_,
                     pad_input_, &log_probs_);
     log_probs_.ApplyFloor(1.0e-20); // Avoid log of zero which leads to NaN.
     log_probs_.ApplyLog();
     CuVector<BaseFloat> priors(am_nnet_.Priors());
     KALDI_ASSERT(priors.Dim() == trans_model_.NumPdfs() &&
                  "Priors in neural network not set up.");
     priors.ApplyLog();
     // subtract log-prior (divide by prior)
     log_probs_.AddVecToRows(-1.0, priors);
     // apply probability scale.
     log_probs_.Scale(prob_scale_);
     delete feats_;
     feats_ = NULL;
   }
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 162 of file decodable-am-nnet.h.
References KALDI_ASSERT, and DecodableAmNnetParallel::NumFramesReady().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmNnetParallel) protected
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 139 of file decodable-am-nnet.h.
References DecodableAmNnetParallel::Compute(), DecodableAmNnetParallel::feats_, DecodableAmNnetParallel::log_probs_, DecodableAmNnetParallel::trans_model_, and TransitionModel::TransitionIdToPdf().
{
     if (feats_) Compute(); // this function sets feats_ to NULL.
     return log_probs_(frame,
                       trans_model_.TransitionIdToPdf(transition_id));
   }
int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 145 of file decodable-am-nnet.h.
References DecodableAmNnetParallel::am_nnet_, DecodableAmNnetParallel::feats_, AmNnet::GetNnet(), Nnet::LeftContext(), DecodableAmNnetParallel::log_probs_, CuMatrixBase< Real >::NumRows(), DecodableAmNnetParallel::pad_input_, and Nnet::RightContext().
Referenced by DecodableAmNnetParallel::IsLastFrame().
{
     if (feats_) {
       if (pad_input_) return feats_->NumRows();
       else {
         int32 ans = feats_->NumRows() - am_nnet_.GetNnet().LeftContext() -
             am_nnet_.GetNnet().RightContext();
         if (ans < 0) ans = 0;
         return ans;
       }
     } else {
       return log_probs_.NumRows();
     }
   }
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst.
Implements DecodableInterface.
Definition at line 160 of file decodable-am-nnet.h.
References TransitionModel::NumTransitionIds(), and DecodableAmNnetParallel::trans_model_.
 { return trans_model_.NumTransitionIds(); }
Member Data Documentation
const AmNnet& am_nnet_ protected
Definition at line 171 of file decodable-am-nnet.h.
Referenced by DecodableAmNnetParallel::Compute(), and DecodableAmNnetParallel::NumFramesReady().
const CuMatrix<BaseFloat>* feats_ protected
Definition at line 174 of file decodable-am-nnet.h.
Referenced by DecodableAmNnetParallel::Compute(), DecodableAmNnetParallel::DecodableAmNnetParallel(), DecodableAmNnetParallel::LogLikelihood(), DecodableAmNnetParallel::NumFramesReady(), and DecodableAmNnetParallel::~DecodableAmNnetParallel().
CuMatrix<BaseFloat> log_probs_ protected
Definition at line 172 of file decodable-am-nnet.h.
Referenced by DecodableAmNnetParallel::Compute(), DecodableAmNnetParallel::LogLikelihood(), and DecodableAmNnetParallel::NumFramesReady().
bool pad_input_ protected
Definition at line 175 of file decodable-am-nnet.h.
Referenced by DecodableAmNnetParallel::Compute(), and DecodableAmNnetParallel::NumFramesReady().
BaseFloat prob_scale_ protected
Definition at line 176 of file decodable-am-nnet.h.
Referenced by DecodableAmNnetParallel::Compute().
const TransitionModel& trans_model_ protected
Definition at line 170 of file decodable-am-nnet.h.
Referenced by DecodableAmNnetParallel::Compute(), DecodableAmNnetParallel::LogLikelihood(), and DecodableAmNnetParallel::NumIndices().
The documentation for this class was generated from the following file:
nnet2/decodable-am-nnet.h