Kaldi: LmTable Class Reference
LmTable Class Reference
LanguageModel
Basic Kaldi implementation for reading ARPA format files.
#include <kaldi-lmtable.h>
Public Member Functions
LmTable ()
~LmTable ()
bool ReadFstFromLmFile (std::istream &istrm, fst::StdVectorFst *pfst, bool useNaturalLog, const string startSent, const string endSent)
Private Attributes
LmFstConverter * conv_
Detailed Description
Basic Kaldi implementation for reading ARPA format files.
It does not rely on any external toolkit but only supports standard ARPA format language model files.
Definition at line 133 of file kaldi-lmtable.h.
Constructor & Destructor Documentation
LmTable () inline
Definition at line 135 of file kaldi-lmtable.h.
References LmTable::conv_.
 { conv_ = new LmFstConverter; }
~LmTable () inline
Definition at line 136 of file kaldi-lmtable.h.
References LmTable::conv_.
 { delete conv_; }
Member Function Documentation
bool ReadFstFromLmFile (std::istream & istrm, fst::StdVectorFst * pfst, bool useNaturalLog, const string startSent, const string endSent)
Definition at line 168 of file kaldi-lmtable.cc.
References LmFstConverter::AddArcsForNgramProb(), LmFstConverter::ConnectUnusedStates(), LmTable::conv_, rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_STRTOF, KALDI_WARN, and LmFstConverter::UseNaturalLog().
Referenced by LangModelFst::ReadStream().
{
 #ifdef KALDI_PARANOID
   KALDI_ASSERT(fst);
   KALDI_ASSERT(fst->InputSymbols() && fst->OutputSymbols());
 #endif
   conv_->UseNaturalLog(useNaturalOpt);
   // do not use state symbol table for word histories anymore
   string inpline;
   size_t pos1, pos2;
   int ngram_order, max_ngram_order = 0;
   // process \data\ section
   while (getline(istrm, inpline) && !istrm.eof()) {
     std::istringstream ss(inpline);
     std::string token;
     ss >> token >> std::ws;
     if (token == "\\data\\" && ss.eof()) break;
   }
   if (istrm.eof()) {
     KALDI_ERR << "\\data\\ token not found in arpa file.";
   }
   std::vector<int> orders;
   while (getline(istrm, inpline) && !istrm.eof()) {
     // break out of loop if another section is found
     if (inpline.find("-grams:") != string::npos) break;
     if (inpline.find("\\end\\") != string::npos) break;
     // look for valid "ngram N = M" lines
     pos1 = inpline.find("ngram");
     pos2 = inpline.find("=");
     if (pos1 == string::npos ||  pos2 == string::npos || pos2 <= pos1) {
       continue;  // not valid, continue looking
     }
     // found valid line
     ngram_order = atoi(inpline.substr(pos1+5, pos2-(pos1+5)).c_str());
     orders.push_back(ngram_order);
     if (ngram_order > max_ngram_order) {
       max_ngram_order = ngram_order;
     }
   }
   if (max_ngram_order == 0) {
     // reached end of loop without having found any n-gram
     KALDI_ERR << "No ngrams found in specified file";
   }
   for (int32 i = 0; i < orders.size(); i++) {
     if (orders[i] != i+1)
       KALDI_ERR << (i + 1) <<"-grams not specified in arpa file";
   }
   // process "\N-grams:" sections, we may have already read a "\N-grams:" line
   // if so, process it, otherwise get another line
   while (inpline.find("-grams:") != string::npos
          || (getline(istrm, inpline) && !istrm.eof()) ) {
     // look for a valid "\N-grams:" section
     pos1 = inpline.find("\\");
     pos2 = inpline.find("-grams:");
     if (pos1 == string::npos || pos2 == string::npos || pos2 <= pos1) {
       continue;  // not valid line, continue looking for one
     }
     // found, set current level
     ngram_order = atoi(inpline.substr(pos1+1, pos2-(pos1+1)).c_str());
     if (orders[0] != ngram_order)
       KALDI_ERR << ngram_order << "-grams not specified in arpa header, or "
                 << "statistics of "<< orders[0] << "-grams not provided ? "
                 << "Check your arpa lm file.";
     else {
       cerr << "Processing " << ngram_order << "-grams" << endl;
       orders.erase(orders.begin());
     }
     // process individual n-grams
     while (getline(istrm, inpline) && !istrm.eof()) {
       // break out of inner loop if another section is found
       if (!inpline.empty() && inpline[0] == '\\') {
         if (inpline.find("-grams:") != string::npos) break;
         if (inpline.find("\\end\\") != string::npos) break;
       }
       // parse ngram line: first field = prob, other fields = words,
       // last field = backoff (optional)
       std::vector<string> ngramString;
       float prob, bow;
       // eat up space.
       const char *cur_cstr = inpline.c_str();
       while (*cur_cstr && isspace(*cur_cstr))
         cur_cstr++;
       if (*cur_cstr == '\0') // Ignore empty lines.
         continue;
       char *next_cstr;
       // found, parse probability from first field
       prob = KALDI_STRTOF(cur_cstr, &next_cstr);
       if (prob != prob || prob - prob != 0) {
         KALDI_ERR << "nan or inf detected in LM file [parsing " << (ngram_order)
             << "-grams]: " << inpline;
       }
       if (next_cstr == cur_cstr)
         KALDI_ERR << "Bad line in LM file [parsing "<<(ngram_order)<<"-grams]: "<<inpline;
       cur_cstr = next_cstr;
       while (*cur_cstr && isspace(*cur_cstr))
         cur_cstr++;
       // element 0 will be empty, element 1 will be the current word,
       // element 2 will be the immediately preceding word, and so on.
       // Apparently an IRSTLM convention.
       ngramString.resize(ngram_order + 1);
       bool illegal_bos_or_eos = false;
       for (int i = 0; i < ngram_order; i++) {
         if (*cur_cstr == '\0')
           KALDI_ERR << "Bad line in LM file [parsing "<<(ngram_order)<<"-grams]: "<<inpline;
         const char *end_cstr = strpbrk(cur_cstr, " \t\r");
         std::string this_word;
         if (end_cstr == NULL) {
           this_word = std::string(cur_cstr);
           cur_cstr += strlen(cur_cstr);
         } else {
           this_word = std::string(cur_cstr, end_cstr-cur_cstr);
           cur_cstr = end_cstr;
           while (*cur_cstr && isspace(*cur_cstr))
             cur_cstr++;
         }
         // Checks if <s> only appears at the beginning of the ngram, and if </s>
         // only appears at the end of the ngram.
         if ((ngram_order > 1 && i != 0 && this_word == "<s>") ||
             (ngram_order > 1 && i != ngram_order - 1 && this_word == "</s>")) {
           illegal_bos_or_eos = true;
           break;
         }
         ngramString[ngram_order - i].swap(this_word);
       }
       if (illegal_bos_or_eos) {
         KALDI_WARN << "<s> is not at the beginning of the n-gram, or </s> is "
             << "not at the end of the n-gram, skipping it: " << inpline;
         continue;
       }
       bow = 0;
       if (ngram_order < max_ngram_order) {
         // try converting anything left in the line to a backoff weight
         if (*cur_cstr != '\0') {
           char *end_cstr;
           bow = KALDI_STRTOF(cur_cstr, &end_cstr);
           if (bow != bow || bow - bow != 0) {
             KALDI_ERR << "nan or inf detected in LM file [parsing " << (ngram_order)
                 << "-grams]: " << inpline;
           }
           if (end_cstr != cur_cstr) {  // got something.
             while (*end_cstr != '\0' && isspace(*end_cstr))
               end_cstr++;
             if (*end_cstr != '\0')
               KALDI_ERR << "Junk " << (end_cstr) << " at end of line [parsing "
                         << (ngram_order) << "-grams]" << inpline;
           } else {
             KALDI_ERR << "Junk " << (cur_cstr) << " at end of line [parsing "
                       << (ngram_order) << "-grams]" << inpline;
           }
         }
       }
       conv_->AddArcsForNgramProb(ngram_order, max_ngram_order, prob, bow,
                                  ngramString, fst,
                                  startSent, endSent);
     }  // end of loop on individual n-gram lines
   }
   if (orders.size() > 0)
     KALDI_ERR << orders[0] << "-grams specified in arpa header "
               << "but no statistics provided to build FST";
   conv_->ConnectUnusedStates(fst);
   // not used anymore: delete pStateSymbs;
   // input and output symbol tables will be deleted by ~fst()
   return true;
 }
Member Data Documentation
LmFstConverter* conv_ private
Definition at line 144 of file kaldi-lmtable.h.
Referenced by LmTable::LmTable(), LmTable::ReadFstFromLmFile(), and LmTable::~LmTable().
The documentation for this class was generated from the following files:
lm/kaldi-lmtable.h
lm/kaldi-lmtable.cc