Kaldi: CompactLatticeWeightTpl< WeightType, IntType > Class Template Reference
CompactLatticeWeightTpl< WeightType, IntType > Class Template Reference
#include <lattice-weight.h>
Public Types
typedef WeightType W
typedef
CompactLatticeWeightTpl
< WeightType, IntType > ReverseWeight
Public Member Functions
CompactLatticeWeightTpl ()
CompactLatticeWeightTpl (const WeightType &w, const vector< IntType > &s)
CompactLatticeWeightTpl & operator= (const CompactLatticeWeightTpl< WeightType, IntType > &w)
const W & Weight () const
const vector< IntType > & String () const
void SetWeight (const W &w)
void SetString (const vector< IntType > &s)
CompactLatticeWeightTpl
< WeightType, IntType > Reverse () const
bool Member () const
CompactLatticeWeightTpl Quantize (float delta=kDelta) const
istream & Read (istream &strm)
ostream & Write (ostream &strm) const
size_t Hash () const
Static Public Member Functions
static const
CompactLatticeWeightTpl
< WeightType, IntType > Zero ()
static const
CompactLatticeWeightTpl
< WeightType, IntType > One ()
static string GetIntSizeString ()
static const string & Type ()
static const
CompactLatticeWeightTpl
< WeightType, IntType > NoWeight ()
static uint64 Properties ()
Private Attributes
W weight_
vector< IntType > string_
Detailed Description
template<class WeightType, class IntType>
class fst::CompactLatticeWeightTpl< WeightType, IntType >
Definition at line 393 of file lattice-weight.h.
Member Typedef Documentation
typedef CompactLatticeWeightTpl<WeightType, IntType> ReverseWeight
Definition at line 397 of file lattice-weight.h.
typedef WeightType W
Definition at line 395 of file lattice-weight.h.
Constructor & Destructor Documentation
CompactLatticeWeightTpl () inline
Definition at line 406 of file lattice-weight.h.
Referenced by CompactLatticeWeightTpl< WeightType, IntType >::Quantize().
 { }
CompactLatticeWeightTpl (const WeightType & w, const vector< IntType > & s) inline
Definition at line 408 of file lattice-weight.h.
                                                                         :
       weight_(w), string_(s) { }
Member Function Documentation
static string GetIntSizeString () inline static
Definition at line 435 of file lattice-weight.h.
Referenced by CompactLatticeWeightTpl< WeightType, IntType >::Type().
{
     char buf[2];
     buf[0] = '0' + sizeof(IntType);
     buf[1] = '\0';
     return buf;
   }
size_t Hash () const inline
Definition at line 511 of file lattice-weight.h.
References rnnlm::i, CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
                       {
     size_t ans = weight_.Hash();
     // any weird numbers here are largish primes
     size_t sz = string_.size(), mult = 6967;
     for(size_t i = 0; i < sz; i++) {
       ans += string_[i] * mult;
       mult *= 7499;
     }
     return ans;
   }
bool Member () const inline
Definition at line 461 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
Referenced by fst::CompactLatticeWeightTest().
                       {
     // a semiring has only one zero, this is the important property
     // we're trying to maintain here.  So force string_ to be empty if
     // w_ == zero.
     if (!weight_.Member()) return false;
     if (weight_ == WeightType::Zero())
       return string_.empty();
     else
       return true;
   }
static const CompactLatticeWeightTpl<WeightType, IntType> NoWeight () inline static
Definition at line 447 of file lattice-weight.h.
{
     return CompactLatticeWeightTpl<WeightType, IntType>(
         WeightType::NoWeight(), std::vector<IntType>());
   }
static const CompactLatticeWeightTpl<WeightType, IntType> One () inline static
Definition at line 430 of file lattice-weight.h.
Referenced by kaldi::nnet2::AppendDiscriminativeExamples(), fst::CompactLatticeWeightTest(), kaldi::GenerateCompactLatticeRandomly(), LatticeLexiconWordAligner::ProcessFinal(), LatticePhoneAligner::ProcessQueueElement(), LatticeWordAligner::ProcessQueueElement(), and LatticeReader::ReadText().
{
     return CompactLatticeWeightTpl<WeightType, IntType>(
         WeightType::One(), vector<IntType>());
   }
CompactLatticeWeightTpl& operator= (const CompactLatticeWeightTpl< WeightType, IntType > & w) inline
Definition at line 411 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
{
     weight_ = w.weight_;
     string_ = w.string_;
     return *this;
   }
static uint64 Properties () inline static
Definition at line 476 of file lattice-weight.h.
{
     return kLeftSemiring | kRightSemiring | kPath | kIdempotent;
   }
CompactLatticeWeightTpl Quantize (float delta = kDelta) const inline
Definition at line 472 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::CompactLatticeWeightTpl(), CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
Referenced by fst::CompactLatticeWeightTest().
{
     return CompactLatticeWeightTpl(weight_.Quantize(delta), string_);
   }
istream& Read (istream & strm) inline
Definition at line 482 of file lattice-weight.h.
References rnnlm::i, CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
Referenced by fst::CompactLatticeWeightTest().
{
     weight_.Read(strm);
     if (strm.fail()){ return strm; }
     int32 sz;
     ReadType(strm, &sz);
     if (strm.fail()){ return strm; }
     if (sz < 0) {
       std::cerr << "Negative string size!  Read failure.";
       strm.clear(std::ios::badbit);
       return strm;
     }
     string_.resize(sz);
     for(int32 i = 0; i < sz; i++) {
       ReadType(strm, &(string_[i]));
     }
     return strm;
   }
CompactLatticeWeightTpl<WeightType, IntType> Reverse () const inline
Definition at line 453 of file lattice-weight.h.
References rnnlm::i, CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
{
     size_t s = string_.size();
     vector<IntType> v(s);
     for(size_t i = 0; i < s; i++)
       v[i] = string_[s-i-1];
     return CompactLatticeWeightTpl<WeightType, IntType>(weight_, v);
   }
void SetString (const vector< IntType > & s) inline
Definition at line 423 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::string_.
Referenced by fst::operator>>().
 { string_ = s; }
void SetWeight (const W & w) inline
Definition at line 421 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::weight_.
Referenced by kaldi::CompactLatticeNormalize(), fst::operator>>(), and kaldi::RescoreCompactLatticeInternal().
 { weight_ = w; }
const vector<IntType>& String () const inline
Definition at line 419 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::string_.
Referenced by fst::ApproxEqual(), fst::Compare(), fst::Divide(), CompactLatticeMinimizer< Weight, IntType >::InitHashValue(), MapTransitionIdsToTransitionStates(), fst::operator!=(), CompactLatticeWeightCommonDivisorTpl< BaseWeightType, IntType >::operator()(), fst::operator==(), fst::ScaleTupleWeight(), WordAlignedLatticeTester::TestFinal(), fst::Times(), and CompactLatticeMinimizer< Weight, IntType >::UpdateHashValueForTransition().
 { return string_; }
static const string& Type () inline static
Definition at line 441 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::GetIntSizeString().
{
     static const string type = "compact" + WeightType::Type()
         + GetIntSizeString();
     return type;
   }
const W& Weight () const inline
Definition at line 417 of file lattice-weight.h.
References CompactLatticeWeightTpl< WeightType, IntType >::weight_.
Referenced by fst::ApproxEqual(), kaldi::CompactLatticeNormalize(), fst::Compare(), fst::Divide(), MapTransitionIdsToTransitionStates(), fst::operator!=(), CompactLatticeWeightCommonDivisorTpl< BaseWeightType, IntType >::operator()(), fst::operator==(), kaldi::RescoreCompactLatticeInternal(), fst::ScaleTupleWeight(), and fst::Times().
 { return weight_; }
ostream& Write (ostream & strm) const inline
Definition at line 502 of file lattice-weight.h.
References rnnlm::i, CompactLatticeWeightTpl< WeightType, IntType >::string_, and CompactLatticeWeightTpl< WeightType, IntType >::weight_.
{
     weight_.Write(strm);
     if (strm.fail()){ return strm; }
     int32 sz = static_cast<int32>(string_.size());
     WriteType(strm, sz);
     for(int32 i = 0; i < sz; i++)
       WriteType(strm, string_[i]);
     return strm;
   }
static const CompactLatticeWeightTpl<WeightType, IntType> Zero () inline static
Definition at line 425 of file lattice-weight.h.
Referenced by CompactLatticePusher< Weight, IntType >::ApplyShifts(), CompactLatticePusher< Weight, IntType >::CheckForConflict(), kaldi::CompactLatticeStateTimes(), fst::CompactLatticeWeightTest(), CompactLatticePusher< Weight, IntType >::ComputeShifts(), fst::Divide(), CompactLatticePusher< Weight, IntType >::GetString(), CompactLatticeMinimizer< Weight, IntType >::InitHashValue(), kaldi::LongestSentenceLength(), LatticePhoneAligner::ProcessQueueElement(), LatticeWordAligner::ProcessQueueElement(), LatticeLexiconWordAligner::ProcessQueueElement(), kaldi::RescoreCompactLatticeInternal(), LatticeReader::StrToCWeight(), WordAlignedLatticeTester::Test(), kaldi::TestPushCompactLatticeStrings(), and fst::Times().
{
     return CompactLatticeWeightTpl<WeightType, IntType>(
         WeightType::Zero(), vector<IntType>());
   }
Member Data Documentation
vector<IntType> string_ private
Definition at line 523 of file lattice-weight.h.
Referenced by CompactLatticeWeightTpl< WeightType, IntType >::Hash(), CompactLatticeWeightTpl< WeightType, IntType >::Member(), CompactLatticeWeightTpl< WeightType, IntType >::operator=(), CompactLatticeWeightTpl< WeightType, IntType >::Quantize(), CompactLatticeWeightTpl< WeightType, IntType >::Read(), CompactLatticeWeightTpl< WeightType, IntType >::Reverse(), CompactLatticeWeightTpl< WeightType, IntType >::SetString(), CompactLatticeWeightTpl< WeightType, IntType >::String(), and CompactLatticeWeightTpl< WeightType, IntType >::Write().
W weight_ private
Definition at line 522 of file lattice-weight.h.
Referenced by CompactLatticeWeightTpl< WeightType, IntType >::Hash(), CompactLatticeWeightTpl< WeightType, IntType >::Member(), CompactLatticeWeightTpl< WeightType, IntType >::operator=(), CompactLatticeWeightTpl< WeightType, IntType >::Quantize(), CompactLatticeWeightTpl< WeightType, IntType >::Read(), CompactLatticeWeightTpl< WeightType, IntType >::Reverse(), CompactLatticeWeightTpl< WeightType, IntType >::SetWeight(), CompactLatticeWeightTpl< WeightType, IntType >::Weight(), and CompactLatticeWeightTpl< WeightType, IntType >::Write().
The documentation for this class was generated from the following file:
fstext/lattice-weight.h