Kaldi: DecodableAmDiagGmmRegtreeMllr Class Reference
DecodableAmDiagGmmRegtreeMllr Class Reference
#include <decodable-am-diag-gmm-regtree.h>
Public Member Functions
DecodableAmDiagGmmRegtreeMllr (const AmDiagGmm &am, const TransitionModel &tm, const Matrix< BaseFloat > &feats, const RegtreeMllrDiagGmm &mllr_xform, const RegressionTree &regtree, BaseFloat scale, BaseFloat log_sum_exp_prune=-1.0)
~DecodableAmDiagGmmRegtreeMllr ()
virtual BaseFloat LogLikelihood (int32 frame, int32 tid)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumFramesReady ()
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
const TransitionModel * TransModel ()
Public Member Functions inherited from DecodableAmDiagGmmUnmapped
DecodableAmDiagGmmUnmapped (const AmDiagGmm &am, const Matrix< BaseFloat > &feats, BaseFloat log_sum_exp_prune=-1.0)
If you set log_sum_exp_prune to a value greater than 0 it will prune in the LogSumExp operation (larger = more exact); I suggest 5.
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Protected Member Functions
virtual BaseFloat LogLikelihoodZeroBased (int32 frame, int32 state_index)
Protected Member Functions inherited from DecodableAmDiagGmmUnmapped
void ResetLogLikeCache ()
Private Member Functions
void InitCache ()
Initializes the mean & gconst caches.
const Matrix< BaseFloat > & GetXformedMeanInvVars (int32 state_index)
Get the transformed means times inverse variances for a given pdf, and cache them.
const Vector< BaseFloat > & GetXformedGconsts (int32 state_index)
Get the cached (while computing transformed means) gconsts for likelihood calculation.
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmDiagGmmRegtreeMllr)
Private Attributes
const TransitionModel & trans_model_
BaseFloat scale_
const RegtreeMllrDiagGmm & mllr_xform_
const RegressionTree & regtree_
std::vector< Matrix< BaseFloat > * > xformed_mean_invvars_
Cache of transformed means time inverse variances for each state.
std::vector< Vector< BaseFloat > * > xformed_gconsts_
Cache of transformed gconsts for each state.
std::vector< bool > is_cached_
Boolean variable per state to indicate whether the transformed means for that state are cached.
Vector< BaseFloat > data_squared_
Cached for fast likelihood calculation.
Additional Inherited Members
Protected Attributes inherited from DecodableAmDiagGmmUnmapped
const AmDiagGmm & acoustic_model_
const Matrix< BaseFloat > & feature_matrix_
int32 previous_frame_
BaseFloat log_sum_exp_prune_
std::vector
< LikelihoodCacheRecord > log_like_cache_
Detailed Description
Definition at line 80 of file decodable-am-diag-gmm-regtree.h.
Constructor & Destructor Documentation
DecodableAmDiagGmmRegtreeMllr (const AmDiagGmm & am, const TransitionModel & tm, const Matrix< BaseFloat > & feats, const RegtreeMllrDiagGmm & mllr_xform, const RegressionTree & regtree, BaseFloat scale, BaseFloat log_sum_exp_prune = -1.0) inline
Definition at line 82 of file decodable-am-diag-gmm-regtree.h.
References DecodableAmDiagGmmRegtreeMllr::InitCache().
                                                                    :
       DecodableAmDiagGmmUnmapped(am, feats, log_sum_exp_prune),
       trans_model_(tm), scale_(scale), mllr_xform_(mllr_xform),
       regtree_(regtree), data_squared_(feats.NumCols()) { InitCache(); }
~DecodableAmDiagGmmRegtreeMllr ()
Definition at line 91 of file decodable-am-diag-gmm-regtree.cc.
References kaldi::DeletePointers(), DecodableAmDiagGmmRegtreeMllr::xformed_gconsts_, and DecodableAmDiagGmmRegtreeMllr::xformed_mean_invvars_.
{
   DeletePointers(&xformed_mean_invvars_);
   DeletePointers(&xformed_gconsts_);
 }
Member Function Documentation
const Vector< BaseFloat > & GetXformedGconsts (int32 state_index) private
Get the cached (while computing transformed means) gconsts for likelihood calculation.
The 'state_index' is 0-based.
Definition at line 180 of file decodable-am-diag-gmm-regtree.cc.
References DecodableAmDiagGmmRegtreeMllr::is_cached_, KALDI_ASSERT, KALDI_ERR, and DecodableAmDiagGmmRegtreeMllr::xformed_gconsts_.
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
                  {
   if (!is_cached_[state]) {
     KALDI_ERR << "GConsts not cached for state: " << state << ". Must call "
               << "GetXformedMeanInvVars() first.";
   }
   KALDI_ASSERT(xformed_gconsts_[state] != NULL);
   return *xformed_gconsts_[state];
 }
const Matrix< BaseFloat > & GetXformedMeanInvVars (int32 state_index) private
Get the transformed means times inverse variances for a given pdf, and cache them.
The 'state_index' is 0-based.
Definition at line 151 of file decodable-am-diag-gmm-regtree.cc.
References DecodableAmDiagGmmUnmapped::acoustic_model_, kaldi::ComputeGconsts(), AmDiagGmm::Dim(), AmDiagGmm::GetPdf(), RegtreeMllrDiagGmm::GetTransformedMeans(), DiagGmm::inv_vars(), DecodableAmDiagGmmRegtreeMllr::is_cached_, KALDI_ASSERT, KALDI_VLOG, DecodableAmDiagGmmRegtreeMllr::mllr_xform_, DiagGmm::NumGauss(), DecodableAmDiagGmmRegtreeMllr::regtree_, DiagGmm::weights(), DecodableAmDiagGmmRegtreeMllr::xformed_gconsts_, and DecodableAmDiagGmmRegtreeMllr::xformed_mean_invvars_.
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
                  {
   if (is_cached_[state]) {  // found in cache
     KALDI_ASSERT(xformed_mean_invvars_[state] != NULL);
     KALDI_VLOG(3) << "For PDF index " << state << ": transformed means "
                   << "found in cache.";
     return *xformed_mean_invvars_[state];
   } else {  // transform the means and cache them
     KALDI_ASSERT(xformed_mean_invvars_[state] == NULL);
     KALDI_VLOG(3) << "For PDF index " << state << ": transforming means.";
     int32 num_gauss = acoustic_model_.GetPdf(state).NumGauss(),
         dim = acoustic_model_.Dim();
     const Vector<BaseFloat> &weights = acoustic_model_.GetPdf(state).weights();
     const Matrix<BaseFloat> &invvars = acoustic_model_.GetPdf(state).inv_vars();
     xformed_mean_invvars_[state] = new Matrix<BaseFloat>(num_gauss, dim);
     mllr_xform_.GetTransformedMeans(regtree_, acoustic_model_, state,
                                     xformed_mean_invvars_[state]);
     xformed_gconsts_[state] = new Vector<BaseFloat>(num_gauss);
     // At this point, the transformed means haven't been multiplied with
     // the inv vars, and they are used to compute gconsts first.
     ComputeGconsts(weights, *xformed_mean_invvars_[state], invvars,
                    xformed_gconsts_[state]);
     // Finally, multiply the transformed means with the inv vars.
     xformed_mean_invvars_[state]->MulElements(invvars);
     is_cached_[state] = true;
     return *xformed_mean_invvars_[state];
   }
 }
void InitCache () private
Initializes the mean & gconst caches.
Definition at line 97 of file decodable-am-diag-gmm-regtree.cc.
References DecodableAmDiagGmmUnmapped::acoustic_model_, kaldi::DeletePointers(), DecodableAmDiagGmmRegtreeMllr::is_cached_, AmDiagGmm::NumPdfs(), DecodableAmDiagGmmUnmapped::ResetLogLikeCache(), DecodableAmDiagGmmRegtreeMllr::xformed_gconsts_, and DecodableAmDiagGmmRegtreeMllr::xformed_mean_invvars_.
Referenced by DecodableAmDiagGmmRegtreeMllr::DecodableAmDiagGmmRegtreeMllr().
{
   if (xformed_mean_invvars_.size() != 0)
     DeletePointers(&xformed_mean_invvars_);
   if (xformed_gconsts_.size() != 0)
     DeletePointers(&xformed_gconsts_);
   int32 num_pdfs = acoustic_model_.NumPdfs();
   xformed_mean_invvars_.resize(num_pdfs);
   xformed_gconsts_.resize(num_pdfs);
   is_cached_.resize(num_pdfs, false);
   ResetLogLikeCache();
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmDiagGmmRegtreeMllr) private
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Reimplemented from DecodableAmDiagGmmUnmapped.
Definition at line 95 of file decodable-am-diag-gmm-regtree.h.
References DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::scale_, DecodableAmDiagGmmRegtreeMllr::trans_model_, and TransitionModel::TransitionIdToPdf().
{
     return scale_*LogLikelihoodZeroBased(frame,
                                          trans_model_.TransitionIdToPdf(tid));
   }
BaseFloat LogLikelihoodZeroBased (int32 frame, int32 state_index) protected virtual
Reimplemented from DecodableAmDiagGmmUnmapped.
Definition at line 190 of file decodable-am-diag-gmm-regtree.cc.
References DecodableAmDiagGmmUnmapped::acoustic_model_, VectorBase< Real >::AddMatVec(), VectorBase< Real >::ApplyPow(), VectorBase< Real >::CopyFromVec(), DecodableAmDiagGmmRegtreeMllr::data_squared_, VectorBase< Real >::Dim(), DiagGmm::Dim(), DecodableAmDiagGmmUnmapped::feature_matrix_, AmDiagGmm::GetPdf(), DecodableAmDiagGmmRegtreeMllr::GetXformedGconsts(), DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), DiagGmm::inv_vars(), KALDI_ASSERT, KALDI_ERR, KALDI_ISINF, KALDI_ISNAN, kaldi::kNoTrans, DecodableAmDiagGmmUnmapped::log_like_cache_, DecodableAmDiagGmmUnmapped::log_sum_exp_prune_, VectorBase< Real >::LogSumExp(), DecodableAmDiagGmmRegtreeMllr::NumFramesReady(), DecodableAmDiagGmmRegtreeMllr::NumIndices(), DecodableAmDiagGmmUnmapped::previous_frame_, and MatrixBase< Real >::Row().
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihood().
{
 //  KALDI_ERR << "Function not completely implemented yet.";
   KALDI_ASSERT(frame < NumFramesReady() && frame >= 0);
   KALDI_ASSERT(state < NumIndices() && state >= 0);
   if (log_like_cache_[state].hit_time == frame) {
     return log_like_cache_[state].log_like;  // return cached value, if found
   }
   const DiagGmm &pdf = acoustic_model_.GetPdf(state);
   const VectorBase<BaseFloat> &data = feature_matrix_.Row(frame);
   // check if everything is in order
   if (pdf.Dim() != data.Dim()) {
     KALDI_ERR << "Dim mismatch: data dim = "  << data.Dim()
         << " vs. model dim = " << pdf.Dim();
   }
   if (frame != previous_frame_) {  // cache the squared stats.
     data_squared_.CopyFromVec(feature_matrix_.Row(frame));
     data_squared_.ApplyPow(2.0);
     previous_frame_ = frame;
   }
   const Matrix<BaseFloat> &means_invvars = GetXformedMeanInvVars(state);
   const Vector<BaseFloat> &gconsts = GetXformedGconsts(state);
   Vector<BaseFloat> loglikes(gconsts);  // need to recreate for each pdf
   // loglikes +=  means * inv(vars) * data.
   loglikes.AddMatVec(1.0, means_invvars, kNoTrans, data, 1.0);
   // loglikes += -0.5 * inv(vars) * data_sq.
   loglikes.AddMatVec(-0.5, pdf.inv_vars(), kNoTrans, data_squared_, 1.0);
   BaseFloat log_sum = loglikes.LogSumExp(log_sum_exp_prune_);
   if (KALDI_ISNAN(log_sum) || KALDI_ISINF(log_sum))
     KALDI_ERR << "Invalid answer (overflow or invalid variances/features?)";
   log_like_cache_[state].log_like = log_sum;
   log_like_cache_[state].hit_time = frame;
   return log_sum;
 }
virtual int32 NumFramesReady () inline virtual
Definition at line 100 of file decodable-am-diag-gmm-regtree.h.
References DecodableAmDiagGmmUnmapped::feature_matrix_, and MatrixBase< Real >::NumRows().
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), and main().
 { return feature_matrix_.NumRows(); }
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst.
Reimplemented from DecodableAmDiagGmmUnmapped.
Definition at line 103 of file decodable-am-diag-gmm-regtree.h.
References TransitionModel::NumTransitionIds(), and DecodableAmDiagGmmRegtreeMllr::trans_model_.
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
 { return trans_model_.NumTransitionIds(); }
const TransitionModel* TransModel () inline
Definition at line 105 of file decodable-am-diag-gmm-regtree.h.
References DecodableAmDiagGmmRegtreeMllr::trans_model_.
 { return &trans_model_; }
Member Data Documentation
Vector<BaseFloat> data_squared_ private
Cached for fast likelihood calculation.
Definition at line 134 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased().
std::vector<bool> is_cached_ private
Boolean variable per state to indicate whether the transformed means for that state are cached.
Definition at line 132 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::GetXformedGconsts(), DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), and DecodableAmDiagGmmRegtreeMllr::InitCache().
const RegtreeMllrDiagGmm& mllr_xform_ private
Definition at line 122 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars().
const RegressionTree& regtree_ private
Definition at line 123 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars().
BaseFloat scale_ private
Definition at line 121 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihood().
const TransitionModel& trans_model_ private
Definition at line 120 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::LogLikelihood(), DecodableAmDiagGmmRegtreeMllr::NumIndices(), and DecodableAmDiagGmmRegtreeMllr::TransModel().
std::vector< Vector<BaseFloat>* > xformed_gconsts_ private
Cache of transformed gconsts for each state.
Definition at line 129 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::GetXformedGconsts(), DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), DecodableAmDiagGmmRegtreeMllr::InitCache(), and DecodableAmDiagGmmRegtreeMllr::~DecodableAmDiagGmmRegtreeMllr().
std::vector< Matrix<BaseFloat>* > xformed_mean_invvars_ private
Cache of transformed means time inverse variances for each state.
Definition at line 127 of file decodable-am-diag-gmm-regtree.h.
Referenced by DecodableAmDiagGmmRegtreeMllr::GetXformedMeanInvVars(), DecodableAmDiagGmmRegtreeMllr::InitCache(), and DecodableAmDiagGmmRegtreeMllr::~DecodableAmDiagGmmRegtreeMllr().
The documentation for this class was generated from the following files:
transform/decodable-am-diag-gmm-regtree.h
transform/decodable-am-diag-gmm-regtree.cc