Kaldi: DeterminizerStar< F > Class Template Reference
DeterminizerStar< F > Class Template Reference
#include <determinize-star-inl.h>
Classes
struct Element
class EpsilonClosure
class PairComparator
class SubsetEqual
class SubsetEqualStates
class SubsetKey
struct TempArc
Public Member Functions
void Output (MutableFst< GallicArc< Arc > > *ofst, bool destroy=true)
void Output (MutableFst< Arc > *ofst, bool destroy=true)
DeterminizerStar (const Fst< Arc > &ifst, float delta=kDelta, int max_states=-1, bool allow_partial=false)
void Determinize (bool *debug_ptr)
bool IsPartial ()
void FreeMostMemory ()
~DeterminizerStar ()
Private Types
typedef F::Arc Arc
typedef Arc::Label Label
typedef Arc::Weight Weight
typedef Arc::StateId InputStateId
typedef Arc::StateId OutputStateId
typedef Arc::Label StringId
typedef StringRepository
< Label, StringId > StringRepositoryType
typedef unordered_map< const
vector< Element >
*, OutputStateId, SubsetKey,
SubsetEqual > SubsetHash
Private Member Functions
void ProcessFinal (const vector< Element > &closed_subset, OutputStateId state)
void ProcessTransition (OutputStateId state, Label ilabel, vector< Element > *subset)
void ProcessTransitions (const vector< Element > &closed_subset, OutputStateId state)
OutputStateId SubsetToStateId (const vector< Element > &subset)
void ProcessSubset (const pair< vector< Element > *, OutputStateId > &pair)
void Debug ()
DISALLOW_COPY_AND_ASSIGN (DeterminizerStar)
Private Attributes
deque< pair< vector< Element >
*, OutputStateId > > Q_
vector< vector< TempArc > > output_arcs_
const Fst< Arc > * ifst_
float delta_
int max_states_
bool determinized_
bool allow_partial_
bool is_partial_
SubsetKey hasher_
SubsetEqual equal_
SubsetHash hash_
StringRepository< Label, StringId > repository_
EpsilonClosure epsilon_closure_
Detailed Description
template<class F>
class fst::DeterminizerStar< F >
Definition at line 164 of file determinize-star-inl.h.
Member Typedef Documentation
typedef F::Arc Arc private
Definition at line 165 of file determinize-star-inl.h.
typedef Arc::StateId InputStateId private
Definition at line 253 of file determinize-star-inl.h.
typedef Arc::Label Label private
Definition at line 251 of file determinize-star-inl.h.
typedef Arc::StateId OutputStateId private
Definition at line 254 of file determinize-star-inl.h.
typedef Arc::Label StringId private
Definition at line 255 of file determinize-star-inl.h.
typedef StringRepository<Label, StringId> StringRepositoryType private
Definition at line 256 of file determinize-star-inl.h.
typedef unordered_map<const vector<Element>*, OutputStateId, SubsetKey, SubsetEqual> SubsetHash private
Definition at line 350 of file determinize-star-inl.h.
typedef Arc::Weight Weight private
Definition at line 252 of file determinize-star-inl.h.
Constructor & Destructor Documentation
DeterminizerStar (const Fst< Arc > & ifst, float delta = kDelta, int max_states = -1, bool allow_partial = false) inline
Definition at line 181 of file determinize-star-inl.h.
                                                                    :
       ifst_(ifst.Copy()), delta_(delta), max_states_(max_states),
       determinized_(false), allow_partial_(allow_partial),
       is_partial_(false), equal_(delta),
       hash_(ifst.Properties(kExpanded, false) ?
               down_cast<const ExpandedFst<Arc>*,
               const Fst<Arc> >(&ifst)->NumStates()/2 + 3 : 20,
             hasher_, equal_),
       epsilon_closure_(ifst_, max_states, &repository_, delta) { }
~DeterminizerStar () inline
Definition at line 247 of file determinize-star-inl.h.
References DeterminizerStar< F >::FreeMostMemory().
                       {
     FreeMostMemory();
   }
Member Function Documentation
void Debug () private
Definition at line 1078 of file determinize-star-inl.h.
References DeterminizerStar< F >::hash_, rnnlm::i, rnnlm::j, DeterminizerStar< F >::output_arcs_, DeterminizerStar< F >::repository_, and kaldi::swap().
Referenced by DeterminizerStar< F >::Determinize().
{
   // this function called if you send a signal
   // SIGUSR1 to the process (and it's caught by the handler in
   // fstdeterminizestar).  It prints out some traceback
   // info and exits.
   std::cerr << "Debug function called (probably SIGUSR1 caught).\n";
   // free up memory from the hash as we need a little memory
   { SubsetHash hash_tmp; std::swap(hash_tmp, hash_); }
   if (output_arcs_.size() <= 2) {
     std::cerr << "Nothing to trace back";
     exit(1);
   }
   size_t max_state = output_arcs_.size() - 2;  // don't take the last
   // one as we might be halfway into constructing it.
   vector<OutputStateId> predecessor(max_state+1, kNoStateId);
   for (size_t i = 0; i < max_state; i++) {
     for (size_t j = 0; j < output_arcs_[i].size(); j++) {
       OutputStateId nextstate = output_arcs_[i][j].nextstate;
       // always find an earlier-numbered prececessor; this
       // is always possible because of the way the algorithm
       // works.
       if (nextstate <= max_state && nextstate > i)
         predecessor[nextstate] = i;
     }
   }
   vector<pair<Label, StringId> > traceback;
   // traceback is a pair of (ilabel, olabel-seq).
   OutputStateId cur_state = max_state;  // a recently constructed state.
   while (cur_state != 0 && cur_state != kNoStateId) {
     OutputStateId last_state = predecessor[cur_state];
     pair<Label, StringId> p;
     size_t i;
     for (i = 0; i < output_arcs_[last_state].size(); i++) {
       if (output_arcs_[last_state][i].nextstate == cur_state) {
         p.first = output_arcs_[last_state][i].ilabel;
         p.second = output_arcs_[last_state][i].ostring;
         traceback.push_back(p);
         break;
       }
     }
     assert(i != output_arcs_[last_state].size());  // or fell off loop.
     cur_state = last_state;
   }
   if (cur_state == kNoStateId)
     std::cerr << "Traceback did not reach start state (possibly debug-code error)";
   std::cerr << "Traceback below (or on standard error) in format ilabel (olabel olabel) ilabel (olabel) ...\n";
   for (ssize_t i = traceback.size() - 1; i >= 0; i--) {
     std::cerr << traceback[i].first << ' ' << "( ";
     vector<Label> seq;
     repository_.SeqOfId(traceback[i].second, &seq);
     for (size_t j = 0; j < seq.size(); j++)
       std::cerr << seq[j] << ' ';
     std::cerr << ") ";
   }
   std::cerr << '\n';
   exit(1);
 }
void Determinize (bool * debug_ptr) inline
Definition at line 192 of file determinize-star-inl.h.
References DeterminizerStar< F >::allow_partial_, DeterminizerStar< F >::Debug(), DeterminizerStar< F >::determinized_, DeterminizerStar< F >::ifst_, DeterminizerStar< F >::is_partial_, KALDI_WARN, DeterminizerStar< F >::max_states_, DeterminizerStar< F >::output_arcs_, DeterminizerStar< F >::ProcessSubset(), DeterminizerStar< F >::Q_, DeterminizerStar< F >::repository_, DeterminizerStar< F >::Element::state, DeterminizerStar< F >::Element::string, DeterminizerStar< F >::SubsetToStateId(), and DeterminizerStar< F >::Element::weight.
Referenced by fst::DeterminizeStar().
{
     assert(!determinized_);
     // This determinizes the input fst but leaves it in the "special format"
     // in "output_arcs_".
     InputStateId start_id = ifst_->Start();
     if (start_id == kNoStateId) { determinized_ = true; return; } // Nothing to do.
     else {  // Insert start state into hash and queue.
       Element elem;
       elem.state = start_id;
       elem.weight = Weight::One();
       elem.string = repository_.IdOfEmpty();  // Id of empty sequence.
       vector<Element> vec;
       vec.push_back(elem);
       OutputStateId cur_id = SubsetToStateId(vec);
       assert(cur_id == 0 && "Do not call Determinize twice.");
     }
     while (!Q_.empty()) {
       pair<vector<Element>*, OutputStateId> cur_pair = Q_.front();
       Q_.pop_front();
       ProcessSubset(cur_pair);
       if (debug_ptr && *debug_ptr) Debug();  // will exit.
       if (max_states_ > 0 && output_arcs_.size() > max_states_) {
         if (allow_partial_ == false) {
           std::cerr << "Determinization aborted since passed " << max_states_
                     << " states.\n";
           throw std::runtime_error("max-states reached in determinization");
         } else {
           KALDI_WARN << "Determinization terminated since passed " << max_states_
                      << " states, partial results will be generated.";
           is_partial_ = true;
           break;
         }
       }
     }
     determinized_ = true;
   }
DISALLOW_COPY_AND_ASSIGN (DeterminizerStar< F >) private
void FreeMostMemory () inline
Definition at line 235 of file determinize-star-inl.h.
References DeterminizerStar< F >::hash_, and DeterminizerStar< F >::ifst_.
Referenced by DeterminizerStar< F >::Output(), and DeterminizerStar< F >::~DeterminizerStar().
{
     if (ifst_) {
       delete ifst_;
       ifst_ = NULL;
     }
     for (typename SubsetHash::iterator iter = hash_.begin();
         iter != hash_.end(); ++iter)
       delete iter->first;
     SubsetHash tmp;
     tmp.swap(hash_);
   }
bool IsPartial () inline
Definition at line 229 of file determinize-star-inl.h.
References DeterminizerStar< F >::is_partial_.
Referenced by fst::DeterminizeStar().
                    {
     return is_partial_;
   }
void Output (MutableFst< GallicArc< Arc > > * ofst, bool destroy = true)
Definition at line 871 of file determinize-star-inl.h.
References DeterminizerStar< F >::determinized_, DeterminizerStar< F >::FreeMostMemory(), rnnlm::i, DeterminizerStar< F >::TempArc::ilabel, DeterminizerStar< F >::TempArc::nextstate, DeterminizerStar< F >::TempArc::ostring, DeterminizerStar< F >::output_arcs_, DeterminizerStar< F >::repository_, and DeterminizerStar< F >::TempArc::weight.
Referenced by fst::DeterminizeStar().
{
   assert(determinized_);
   if (destroy) determinized_ = false;
   typedef GallicWeight<Label, Weight> ThisGallicWeight;
   typedef typename Arc::StateId StateId;
   if (destroy)
     FreeMostMemory();
   StateId nStates = static_cast<StateId>(output_arcs_.size());
   ofst->DeleteStates();
   ofst->SetStart(kNoStateId);
   if (nStates == 0) {
     return;
   }
   for (StateId s = 0;s < nStates;s++) {
     OutputStateId news = ofst->AddState();
     assert(news == s);
   }
   ofst->SetStart(0);
   // now process transitions.
   for (StateId this_state = 0; this_state < nStates; this_state++) {
     vector<TempArc> &this_vec(output_arcs_[this_state]);
     typename vector<TempArc>::const_iterator iter = this_vec.begin(),
         end = this_vec.end();
     for (; iter != end; ++iter) {
       const TempArc &temp_arc(*iter);
       GallicArc<Arc> new_arc;
       vector<Label> seq;
       repository_.SeqOfId(temp_arc.ostring, &seq);
       StringWeight<Label, STRING_LEFT> string_weight;
       for (size_t i = 0;i < seq.size();i++) string_weight.PushBack(seq[i]);
       ThisGallicWeight gallic_weight(string_weight, temp_arc.weight);
       if (temp_arc.nextstate == kNoStateId) {  // is really final weight.
         ofst->SetFinal(this_state, gallic_weight);
       } else {  // is really an arc.
         new_arc.nextstate = temp_arc.nextstate;
         new_arc.ilabel = temp_arc.ilabel;
         new_arc.olabel = temp_arc.ilabel;  // acceptor.  input == output.
         new_arc.weight = gallic_weight;  // includes string and weight.
         ofst->AddArc(this_state, new_arc);
       }
     }
     // Free up memory.  Do this inside the loop as ofst is also allocating memory
     if (destroy) { vector<TempArc> temp; temp.swap(this_vec); }
   }
   if (destroy) { vector<vector<TempArc> > temp; temp.swap(output_arcs_); }
 }
void Output (MutableFst< Arc > * ofst, bool destroy = true)
Definition at line 921 of file determinize-star-inl.h.
References DeterminizerStar< F >::determinized_, DeterminizerStar< F >::FreeMostMemory(), rnnlm::i, DeterminizerStar< F >::TempArc::ilabel, DeterminizerStar< F >::TempArc::nextstate, DeterminizerStar< F >::TempArc::ostring, DeterminizerStar< F >::output_arcs_, DeterminizerStar< F >::repository_, and DeterminizerStar< F >::TempArc::weight.
{
   assert(determinized_);
   if (destroy) determinized_ = false;
   // Outputs to standard fst.
   OutputStateId num_states = static_cast<OutputStateId>(output_arcs_.size());
   if (destroy)
     FreeMostMemory();
   ofst->DeleteStates();
   if (num_states == 0) {
     ofst->SetStart(kNoStateId);
     return;
   }
   // Add basic states-- but will add extra ones to account for strings on output.
   for (OutputStateId s = 0; s < num_states; s++) {
     OutputStateId news = ofst->AddState();
     assert(news == s);
   }
   ofst->SetStart(0);
   for (OutputStateId this_state = 0; this_state < num_states; this_state++) {
     vector<TempArc> &this_vec(output_arcs_[this_state]);
     typename vector<TempArc>::const_iterator iter = this_vec.begin(),
         end = this_vec.end();
     for (; iter != end; ++iter) {
       const TempArc &temp_arc(*iter);
       vector<Label> seq;
       repository_.SeqOfId(temp_arc.ostring, &seq);
       if (temp_arc.nextstate == kNoStateId) {  // Really a final weight.
         // Make a sequence of states going to a final state, with the strings as labels.
         // Put the weight on the first arc.
         OutputStateId cur_state = this_state;
         for (size_t i = 0; i < seq.size();i++) {
           OutputStateId next_state = ofst->AddState();
           Arc arc;
           arc.nextstate = next_state;
           arc.weight = (i == 0 ? temp_arc.weight : Weight::One());
           arc.ilabel = 0;  // epsilon.
           arc.olabel = seq[i];
           ofst->AddArc(cur_state, arc);
           cur_state = next_state;
         }
         ofst->SetFinal(cur_state, (seq.size() == 0 ? temp_arc.weight : Weight::One()));
       } else {  // Really an arc.
         OutputStateId cur_state = this_state;
         // Have to be careful with this integer comparison (i+1 < seq.size()) because unsigned.
         // i < seq.size()-1 could fail for zero-length sequences.
         for (size_t i = 0; i+1 < seq.size();i++) {
           // for all but the last element of seq, create new state.
           OutputStateId next_state = ofst->AddState();
           Arc arc;
           arc.nextstate = next_state;
           arc.weight = (i == 0 ? temp_arc.weight : Weight::One());
           arc.ilabel = (i == 0 ? temp_arc.ilabel : 0);  // put ilabel on first element of seq.
           arc.olabel = seq[i];
           ofst->AddArc(cur_state, arc);
           cur_state = next_state;
         }
         // Add the final arc in the sequence.
         Arc arc;
         arc.nextstate = temp_arc.nextstate;
         arc.weight = (seq.size() <= 1 ? temp_arc.weight : Weight::One());
         arc.ilabel = (seq.size() <= 1 ? temp_arc.ilabel : 0);
         arc.olabel = (seq.size() > 0 ? seq.back() : 0);
         ofst->AddArc(cur_state, arc);
       }
     }
     // Free up memory.  Do this inside the loop as ofst is also allocating memory
     if (destroy) { vector<TempArc> temp; temp.swap(this_vec); }
   }
   if (destroy) {
     vector<vector<TempArc> > temp;
     temp.swap(output_arcs_);
     repository_.Destroy();
   }
 }
void ProcessFinal (const vector< Element > & closed_subset, OutputStateId state) inline private
Definition at line 441 of file determinize-star-inl.h.
References DeterminizerStar< F >::ifst_, DeterminizerStar< F >::TempArc::ilabel, DeterminizerStar< F >::TempArc::nextstate, DeterminizerStar< F >::TempArc::ostring, DeterminizerStar< F >::output_arcs_, fst::Plus(), DeterminizerStar< F >::Element::state, DeterminizerStar< F >::Element::string, fst::Times(), DeterminizerStar< F >::Element::weight, and DeterminizerStar< F >::TempArc::weight.
Referenced by DeterminizerStar< F >::ProcessSubset().
{
     // processes final-weights for this subset.
     bool is_final = false;
     StringId final_string = 0;  // = 0 to keep compiler happy.
     Weight final_weight = Weight::One();  // This value will never be accessed, and
     // we just set it to avoid spurious compiler warnings.  We avoid setting it
     // to Zero() because floating-point infinities can sometimes generate
     // interrupts and slow things down.
     typename vector<Element>::const_iterator iter = closed_subset.begin(),
         end = closed_subset.end();
     for (; iter != end; ++iter) {
       const Element &elem = *iter;
       Weight this_final_weight = ifst_->Final(elem.state);
       if (this_final_weight != Weight::Zero()) {
         if (!is_final) {  // first final-weight
           final_string = elem.string;
           final_weight = Times(elem.weight, this_final_weight);
           is_final = true;
         } else {  // already have one.
           if (final_string != elem.string) {
             std::cerr << "DeterminizerStar: FST was not functional -> not determinizable\n";
             throw std::runtime_error("Non-functional FST: cannot determinize.\n");
           }
           final_weight = Plus(final_weight, Times(elem.weight, this_final_weight));
         }
       }
     }
     if (is_final) {
       // store final weights in TempArc structure, just like a transition.
       TempArc temp_arc;
       temp_arc.ilabel = 0;
       temp_arc.nextstate = kNoStateId;  // special marker meaning "final weight".
       temp_arc.ostring = final_string;
       temp_arc.weight = final_weight;
       output_arcs_[state].push_back(temp_arc);
     }
   }
void ProcessSubset (const pair< vector< Element > *, OutputStateId > & pair) inline private
Definition at line 595 of file determinize-star-inl.h.
References DeterminizerStar< F >::epsilon_closure_, DeterminizerStar< F >::EpsilonClosure::GetEpsilonClosure(), DeterminizerStar< F >::ProcessFinal(), and DeterminizerStar< F >::ProcessTransitions().
Referenced by DeterminizerStar< F >::Determinize().
{
     const vector<Element> *subset = pair.first;
     OutputStateId state = pair.second;
     vector<Element> closed_subset;  // subset after epsilon closure.
     epsilon_closure_.GetEpsilonClosure(*subset, &closed_subset);
     // Now follow non-epsilon arcs [and also process final states]
     ProcessFinal(closed_subset, state);
     // Now handle transitions out of these states.
     ProcessTransitions(closed_subset, state);
   }
void ProcessTransition (OutputStateId state, Label ilabel, vector< Element > * subset) private
Definition at line 998 of file determinize-star-inl.h.
References fst::Divide(), rnnlm::i, DeterminizerStar< F >::TempArc::ilabel, DeterminizerStar< F >::TempArc::nextstate, DeterminizerStar< F >::TempArc::ostring, DeterminizerStar< F >::output_arcs_, fst::Plus(), DeterminizerStar< F >::repository_, DeterminizerStar< F >::SubsetToStateId(), and DeterminizerStar< F >::TempArc::weight.
Referenced by DeterminizerStar< F >::ProcessTransitions().
{
   // At input, "subset" may contain duplicates for a given dest state (but in sorted
   // order).  This function removes duplicates from "subset", normalizes it, and adds
   // a transition to the dest. state (possibly affecting Q_ and hash_, if state did not
   // exist).
   typedef typename vector<Element>::iterator IterType;
   {  // This block makes the subset have one unique Element per state, adding the weights.
     IterType cur_in = subset->begin(), cur_out = cur_in, end = subset->end();
     size_t num_out = 0;
     // Merge elements with same state-id
     while (cur_in != end) {  // while we have more elements to process.
       // At this point, cur_out points to location of next place we want to put an element,
       // cur_in points to location of next element we want to process.
       if (cur_in != cur_out) *cur_out = *cur_in;
       cur_in++;
       while (cur_in != end && cur_in->state == cur_out->state) {  // merge elements.
         if (cur_in->string != cur_out->string) {
           std::cerr << "DeterminizerStar: FST was not functional -> not determinizable\n";
           throw std::runtime_error("Non-functional FST: cannot determinize.\n");
         }
         cur_out->weight = Plus(cur_out->weight, cur_in->weight);
         cur_in++;
       }
       cur_out++;
       num_out++;
     }
     subset->resize(num_out);
   }
   StringId common_str;
   Weight tot_weight;
   {  // This block computes common_str and tot_weight (essentially: the common divisor)
     // and removes them from the elements.
     vector<Label> seq;
     IterType begin = subset->begin(), iter, end = subset->end();
     {  // This block computes "seq", which is the common prefix, and "common_str",
       // which is the StringId version of "seq".
       vector<Label> tmp_seq;
       for (iter = begin; iter != end; ++iter) {
         if (iter == begin) {
           repository_.SeqOfId(iter->string, &seq);
         } else {
           repository_.SeqOfId(iter->string, &tmp_seq);
           if (tmp_seq.size() < seq.size()) seq.resize(tmp_seq.size());  // size of shortest one.
           for (size_t i = 0; i < seq.size(); i++) // seq.size() is the shorter one at this point.
             if (tmp_seq[i] != seq[i]) seq.resize(i);
         }
         if (seq.size() == 0) break;  // will not get any prefix.
       }
       common_str = repository_.IdOfSeq(seq);
     }
     {  // This block computes "tot_weight".
       iter = begin;
       tot_weight = iter->weight;
       for (++iter; iter != end; ++iter)
         tot_weight = Plus(tot_weight, iter->weight);
     }
     // Now divide out common stuff from elements.
     size_t prefix_len = seq.size();
     for (iter = begin; iter != end; ++iter) {
       iter->weight = Divide(iter->weight, tot_weight);
       iter->string = repository_.RemovePrefix(iter->string, prefix_len);
     }
   }
   // Now add an arc to the state that the subset represents.
   // We may create a new state id for this (in SubsetToStateId).
   TempArc temp_arc;
   temp_arc.ilabel = ilabel;
   temp_arc.nextstate = SubsetToStateId(*subset);  // may or may not really add the subset.
   temp_arc.ostring = common_str;
   temp_arc.weight = tot_weight;
   output_arcs_[state].push_back(temp_arc);  // record the arc.
 }
void ProcessTransitions (const vector< Element > & closed_subset, OutputStateId state) inline private
Definition at line 508 of file determinize-star-inl.h.
References DeterminizerStar< F >::ifst_, DeterminizerStar< F >::ProcessTransition(), DeterminizerStar< F >::repository_, DeterminizerStar< F >::Element::state, DeterminizerStar< F >::Element::string, fst::Times(), and DeterminizerStar< F >::Element::weight.
Referenced by DeterminizerStar< F >::ProcessSubset().
{
     vector<pair<Label, Element> > all_elems;
     {  // Push back into "all_elems", elements corresponding to all non-epsilon-input transitions
       // out of all states in "closed_subset".
       typename vector<Element>::const_iterator iter = closed_subset.begin(),
           end = closed_subset.end();
       for (; iter != end; ++iter) {
         const Element &elem = *iter;
         for (ArcIterator<Fst<Arc> > aiter(*ifst_, elem.state);
              !aiter.Done(); aiter.Next()) {
           const Arc &arc = aiter.Value();
           if (arc.ilabel != 0) {  // Non-epsilon transition -- ignore epsilons here.
             pair<Label, Element> this_pr;
             this_pr.first = arc.ilabel;
             Element &next_elem(this_pr.second);
             next_elem.state = arc.nextstate;
             next_elem.weight = Times(elem.weight, arc.weight);
             if (arc.olabel == 0) // output epsilon-- this is simple case so
                                  // handle separately for efficiency
               next_elem.string = elem.string;
             else {
               vector<Label> seq;
               repository_.SeqOfId(elem.string, &seq);
               seq.push_back(arc.olabel);
               next_elem.string = repository_.IdOfSeq(seq);
             }
             all_elems.push_back(this_pr);
           }
         }
       }
     }
     PairComparator pc;
     std::sort(all_elems.begin(), all_elems.end(), pc);
     // now sorted first on input label, then on state.
     typedef typename vector<pair<Label, Element> >::const_iterator PairIter;
     PairIter cur = all_elems.begin(), end = all_elems.end();
     vector<Element> this_subset;
     while (cur != end) {
       // Process ranges that share the same input symbol.
       Label ilabel = cur->first;
       this_subset.clear();
       while (cur != end && cur->first == ilabel) {
         this_subset.push_back(cur->second);
         cur++;
       }
       // We now have a subset for this ilabel.
       ProcessTransition(state, ilabel, &this_subset);
     }
   }
OutputStateId SubsetToStateId (const vector< Element > & subset) inline private
Definition at line 562 of file determinize-star-inl.h.
References DeterminizerStar< F >::allow_partial_, DeterminizerStar< F >::hash_, DeterminizerStar< F >::output_arcs_, and DeterminizerStar< F >::Q_.
Referenced by DeterminizerStar< F >::Determinize(), and DeterminizerStar< F >::ProcessTransition().
                                                                {  // may add the subset to the queue.
     typedef typename SubsetHash::iterator IterType;
     IterType iter = hash_.find(&subset);
     if (iter == hash_.end()) {  // was not there.
       vector<Element> *new_subset = new vector<Element>(subset);
       OutputStateId new_state_id = (OutputStateId) output_arcs_.size();
       bool ans = hash_.insert(std::pair<const vector<Element>*,
                                         OutputStateId>(new_subset,
                                                        new_state_id)).second;
       assert(ans);
       output_arcs_.push_back(vector<TempArc>());
       if (allow_partial_ == false) {
         // If --allow-partial is not requested, we do the old way.
         Q_.push_front(pair<vector<Element>*, OutputStateId>(new_subset,  new_state_id));
       } else {
         // If --allow-partial is requested, we do breadth first search. This
         // ensures that when we return partial results, we return the states
         // that are reachable by the fewest steps from the start state.
         Q_.push_back(pair<vector<Element>*, OutputStateId>(new_subset,  new_state_id));
       }
       return new_state_id;
     } else {
       return iter->second;  // the OutputStateId.
     }
   }
Member Data Documentation
bool allow_partial_ private
Definition at line 620 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Determinize(), and DeterminizerStar< F >::SubsetToStateId().
float delta_ private
Definition at line 617 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::EpsilonClosure::AddOneElement().
bool determinized_ private
Definition at line 619 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Determinize(), and DeterminizerStar< F >::Output().
EpsilonClosure epsilon_closure_ private
Definition at line 627 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::ProcessSubset().
SubsetEqual equal_ private
Definition at line 623 of file determinize-star-inl.h.
SubsetHash hash_ private
Definition at line 624 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Debug(), DeterminizerStar< F >::FreeMostMemory(), and DeterminizerStar< F >::SubsetToStateId().
SubsetKey hasher_ private
Definition at line 622 of file determinize-star-inl.h.
const Fst<Arc>* ifst_ private
Definition at line 616 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Determinize(), DeterminizerStar< F >::EpsilonClosure::ExpandOneElement(), DeterminizerStar< F >::FreeMostMemory(), DeterminizerStar< F >::ProcessFinal(), and DeterminizerStar< F >::ProcessTransitions().
bool is_partial_ private
Definition at line 621 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Determinize(), and DeterminizerStar< F >::IsPartial().
int max_states_ private
Definition at line 618 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Determinize().
vector<vector<TempArc> > output_arcs_ private
Definition at line 614 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Debug(), DeterminizerStar< F >::Determinize(), DeterminizerStar< F >::Output(), DeterminizerStar< F >::ProcessFinal(), DeterminizerStar< F >::ProcessTransition(), and DeterminizerStar< F >::SubsetToStateId().
deque<pair<vector<Element>*, OutputStateId> > Q_ private
Definition at line 612 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::Determinize(), and DeterminizerStar< F >::SubsetToStateId().
StringRepository<Label, StringId> repository_ private
Definition at line 626 of file determinize-star-inl.h.
Referenced by DeterminizerStar< F >::EpsilonClosure::AddOneElement(), DeterminizerStar< F >::Debug(), DeterminizerStar< F >::Determinize(), DeterminizerStar< F >::EpsilonClosure::ExpandOneElement(), DeterminizerStar< F >::Output(), DeterminizerStar< F >::ProcessTransition(), and DeterminizerStar< F >::ProcessTransitions().
The documentation for this class was generated from the following file:
fstext/determinize-star-inl.h