Kaldi: VectorBase< Real > Class Template Reference
VectorBase< Real > Class Template Reference
%Matrix and vector classes
Provides a vector abstraction class.
#include <kaldi-vector.h>
Public Member Functions
void SetZero ()
Set vector to all zeros.
bool IsZero (Real cutoff=1.0e-06) const
Returns true if matrix is all zeros.
void Set (Real f)
Set all members of a vector to a specified value.
void SetRandn ()
Set vector to random normally-distributed noise.
MatrixIndexT RandCategorical () const
This function returns a random index into this vector, chosen with probability proportional to the corresponding element.
MatrixIndexT Dim () const
Returns the dimension of the vector.
MatrixIndexT SizeInBytes () const
Returns the size in memory of the vector, in bytes.
Real * Data ()
Returns a pointer to the start of the vector's data.
const Real * Data () const
Returns a pointer to the start of the vector's data (const).
Real operator() (MatrixIndexT i) const
Indexing operator (const).
Real & operator() (MatrixIndexT i)
Indexing operator (non-const).
SubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l)
Returns a sub-vector of a vector (a range of elements).
const SubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l) const
Returns a const sub-vector of a vector (a range of elements).
void CopyFromVec (const VectorBase< Real > &v)
Copy data from another vector (must match own size).
template<typename OtherReal >
void CopyFromPacked (const PackedMatrix< OtherReal > &M)
Copy data from a SpMatrix or TpMatrix (must match own size).
template<typename OtherReal >
void CopyFromVec (const VectorBase< OtherReal > &v)
Copy data from another vector of different type (double vs. float)
template<typename OtherReal >
void CopyFromVec (const CuVectorBase< OtherReal > &v)
Copy from CuVector. This is defined in ../cudamatrix/cu-vector.h.
void ApplyLog ()
Apply natural log to all elements.
void ApplyLogAndCopy (const VectorBase< Real > &v)
Apply natural log to another vector and put result in *this.
void ApplyExp ()
Apply exponential to each value in vector.
void ApplyAbs ()
Take absolute value of each of the elements.
MatrixIndexT ApplyFloor (Real floor_val)
Applies floor to all elements. Returns number of elements floored.
MatrixIndexT ApplyCeiling (Real ceil_val)
Applies ceiling to all elements. Returns number of elements changed.
MatrixIndexT ApplyFloor (const VectorBase< Real > &floor_vec)
Applies floor to all elements. Returns number of elements floored.
Real ApplySoftMax ()
Apply soft-max to vector and return normalizer (log sum of exponentials).
Real ApplyLogSoftMax ()
Applies log soft-max to vector and returns normalizer (log sum of exponentials).
void Tanh (const VectorBase< Real > &src)
Sets each element of *this to the tanh of the corresponding element of "src".
void Sigmoid (const VectorBase< Real > &src)
Sets each element of *this to the sigmoid function of the corresponding element of "src".
void ApplyPow (Real power)
Take all elements of vector to a power.
void ApplyPowAbs (Real power, bool include_sign=false)
Take the absolute value of all elements of a vector to a power.
Real Norm (Real p) const
Compute the p-th norm of the vector.
bool ApproxEqual (const VectorBase< Real > &other, float tol=0.01) const
Returns true if ((*this)-other).Norm(2.0) <= tol * (*this).Norm(2.0).
void InvertElements ()
Invert all elements.
template<typename OtherReal >
void AddVec (const Real alpha, const VectorBase< OtherReal > &v)
Add vector : *this = *this + alpha * rv (with casting between floats and doubles)
void AddVec2 (const Real alpha, const VectorBase< Real > &v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring].
template<typename OtherReal >
void AddVec2 (const Real alpha, const VectorBase< OtherReal > &v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring], with casting between floats and doubles.
void AddMatVec (const Real alpha, const MatrixBase< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
Add matrix times vector : this <– beta*this + alpha*M*v.
void AddMatSvec (const Real alpha, const MatrixBase< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
This is as AddMatVec, except optimized for where v contains a lot of zeros.
void AddSpVec (const Real alpha, const SpMatrix< Real > &M, const VectorBase< Real > &v, const Real beta)
Add symmetric positive definite matrix times vector: this <– beta*this + alpha*M*v.
void AddTpVec (const Real alpha, const TpMatrix< Real > &M, const MatrixTransposeType trans, const VectorBase< Real > &v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
void ReplaceValue (Real orig, Real changed)
Set each element to y = (x == orig ? changed : x).
void MulElements (const VectorBase< Real > &v)
Multipy element-by-element by another vector.
template<typename OtherReal >
void MulElements (const VectorBase< OtherReal > &v)
Multipy element-by-element by another vector of different type.
void DivElements (const VectorBase< Real > &v)
Divide element-by-element by a vector.
template<typename OtherReal >
void DivElements (const VectorBase< OtherReal > &v)
Divide element-by-element by a vector of different type.
void Add (Real c)
Add a constant to each element of a vector.
void AddVecVec (Real alpha, const VectorBase< Real > &v, const VectorBase< Real > &r, Real beta)
Add element-by-element product of vectlrs:
void AddVecDivVec (Real alpha, const VectorBase< Real > &v, const VectorBase< Real > &r, Real beta)
Add element-by-element quotient of two vectors.
void Scale (Real alpha)
Multiplies all elements by this constant.
void MulTp (const TpMatrix< Real > &M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
void Solve (const TpMatrix< Real > &M, const MatrixTransposeType trans)
If trans == kNoTrans, solves M x = b, where b is the value of *this at input and x is the value of *this at output.
void CopyRowsFromMat (const MatrixBase< Real > &M)
Performs a row stack of the matrix M.
template<typename OtherReal >
void CopyRowsFromMat (const MatrixBase< OtherReal > &M)
void CopyRowsFromMat (const CuMatrixBase< Real > &M)
The following is implemented in ../cudamatrix/cu-matrix.cc.
void CopyColsFromMat (const MatrixBase< Real > &M)
Performs a column stack of the matrix M.
void CopyRowFromMat (const MatrixBase< Real > &M, MatrixIndexT row)
Extracts a row of the matrix M.
template<typename OtherReal >
void CopyRowFromMat (const MatrixBase< OtherReal > &M, MatrixIndexT row)
Extracts a row of the matrix M with type conversion.
template<typename OtherReal >
void CopyRowFromSp (const SpMatrix< OtherReal > &S, MatrixIndexT row)
Extracts a row of the symmetric matrix S.
template<typename OtherReal >
void CopyColFromMat (const MatrixBase< OtherReal > &M, MatrixIndexT col)
Extracts a column of the matrix M.
void CopyDiagFromMat (const MatrixBase< Real > &M)
Extracts the diagonal of the matrix M.
void CopyDiagFromPacked (const PackedMatrix< Real > &M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
void CopyDiagFromSp (const SpMatrix< Real > &M)
Extracts the diagonal of a symmetric matrix.
void CopyDiagFromTp (const TpMatrix< Real > &M)
Extracts the diagonal of a triangular matrix.
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Real Max (MatrixIndexT *index) const
Returns the maximum value of any element, and the associated index.
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
Real Min (MatrixIndexT *index) const
Returns the minimum value of any element, and the associated index.
Real Sum () const
Returns sum of the elements.
Real SumLog () const
Returns sum of the logs of the elements.
void AddRowSumMat (Real alpha, const MatrixBase< Real > &M, Real beta=1.0)
Does *this = alpha * (sum of rows of M) + beta * *this.
void AddColSumMat (Real alpha, const MatrixBase< Real > &M, Real beta=1.0)
Does *this = alpha * (sum of columns of M) + beta * *this.
void AddDiagMat2 (Real alpha, const MatrixBase< Real > &M, MatrixTransposeType trans=kNoTrans, Real beta=1.0)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
void AddDiagMatMat (Real alpha, const MatrixBase< Real > &M, MatrixTransposeType transM, const MatrixBase< Real > &N, MatrixTransposeType transN, Real beta=1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
Real LogSumExp (Real prune=-1.0) const
Returns log(sum(exp())) without exp overflow If prune > 0.0, ignores terms less than the max - prune.
void Read (std::istream &in, bool binary, bool add=false)
Reads from C++ stream (option to add to existing contents).
void Write (std::ostream &Out, bool binary) const
Writes to C++ stream (option to write in binary).
template<>
void AddVec (const float alpha, const VectorBase< float > &rv)
template<>
void AddVec (const double alpha, const VectorBase< double > &rv)
template<>
void AddVec (const float alpha, const VectorBase< float > &v)
template<>
void AddVec (const double alpha, const VectorBase< double > &v)
Protected Member Functions
~VectorBase ()
Destructor; does not deallocate memory, this is handled by child classes.
VectorBase ()
Empty initializer, corresponds to vector of zero size.
void CopyFromPtr (const Real *Data, MatrixIndexT sz)
Load data into the vector: sz must match own size.
KALDI_DISALLOW_COPY_AND_ASSIGN (VectorBase)
Protected Attributes
Real * data_
data memory area
MatrixIndexT dim_
dimension of vector
Friends
class VectorBase< double >
class VectorBase< float >
class CuVectorBase< Real >
class CuVector< Real >
Detailed Description
template<typename Real>
class kaldi::VectorBase< Real >
Provides a vector abstraction class.
This class provides a way to work with vectors in kaldi. It encapsulates basic operations and memory optimizations.
Definition at line 39 of file kaldi-vector.h.
Constructor & Destructor Documentation
~VectorBase () inline protected
Destructor; does not deallocate memory, this is handled by child classes.
This destructor is protected so this object so this object can only be deleted via a child.
Definition at line 354 of file kaldi-vector.h.
 {}
VectorBase () inline explicit protected
Empty initializer, corresponds to vector of zero size.
Definition at line 357 of file kaldi-vector.h.
                        : data_(NULL), dim_(0) {
     KALDI_ASSERT_IS_FLOATING_TYPE(Real);
   }
Member Function Documentation
void Add (Real c)
Add a constant to each element of a vector.
Definition at line 929 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by AmSgmm2::ComponentLogLikes(), kaldi::ComputeCorrelation(), AmSgmm::ComputeNormalizersNormalized(), OnlineNaturalGradient::ComputeZt(), OnlinePreconditioner::ComputeZt(), kaldi::ExtractWindow(), IvectorExtractor::GetAcousticAuxfWeight(), LogisticRegression::GetLogPosteriors(), MultiSinusoidDetector::GetNextFrame(), AmSgmm::LogLikelihood(), Plda::LogLikelihoodRatio(), main(), kaldi::nnet1::MomentStatistics(), PitchInterpolator::MultiplyObsProb(), OnlinePitchFeatureImpl::OnlinePitchFeatureImpl(), PdfPrior::PdfPrior(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), AccumDiagGmm::SmoothStats(), AccumDiagGmm::SmoothWithModel(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmm2Updater::UpdateSubstateWeights(), MleAmSgmm2Updater::UpdateW(), MleAmSgmm2Updater::UpdateWGetStats(), MleSgmm2SpeakerAccs::UpdateWithU(), MleAmSgmmUpdaterMulti::UpdateWParallel(), and MleAmSgmmUpdater::UpdateWParallel().
{
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] += c;
   }
 }
void AddColSumMat (Real alpha, const MatrixBase< Real > & M, Real beta = 1.0)
Does *this = alpha * (sum of columns of M) + beta * *this.
Definition at line 724 of file kaldi-vector.cc.
References rnnlm::i, rnnlm::j, KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::RowData(), and VectorBase< Real >::Set().
Referenced by kaldi::CuVectorUnitTestAddColSumMat(), KlHmm::PropagateFnc(), kaldi::UnitTestAddColSumMatSpeed(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), and kaldi::UnitTestSimpleForVec().
{
   KALDI_ASSERT(dim_ == M.NumRows());
   MatrixIndexT num_cols = M.NumCols();
   // implement the function according to a dimension cutoff for computation efficiency
   if (num_cols <= 64) {
     for (MatrixIndexT i = 0; i < dim_; i++) {
       double sum = 0.0;
       const Real *src = M.RowData(i);
       for (MatrixIndexT j = 0; j < num_cols; j++)
         sum += src[j];
       data_[i] = alpha * sum + beta * data_[i];
     }
   } else {
     Vector<Real> ones(M.NumCols());
     ones.Set(1.0);
     this->AddMatVec(alpha, M, kNoTrans, ones, beta);
   }
 }
void AddDiagMat2 (Real alpha, const MatrixBase< Real > & M, MatrixTransposeType trans = kNoTrans, Real beta = 1.0)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
Definition at line 1271 of file kaldi-vector.cc.
References kaldi::cblas_Xdot(), MatrixBase< Real >::Data(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by kaldi::CuVectorUnitTestAddDiagMat2(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), kaldi::SlidingWindowCmnInternal(), and kaldi::UnitTestAddDiagMat2().
{
   if (trans == kNoTrans) {
     KALDI_ASSERT(this->dim_ == M.NumRows());
     MatrixIndexT rows = this->dim_, cols = M.NumCols(),
            mat_stride = M.Stride();
     Real *data = this->data_;
     const Real *mat_data = M.Data();
     for (MatrixIndexT i = 0; i < rows; i++, mat_data += mat_stride, data++)
       *data = beta * *data + alpha * cblas_Xdot(cols,mat_data,1,mat_data,1);
   } else {
     KALDI_ASSERT(this->dim_ == M.NumCols());
     MatrixIndexT rows = M.NumRows(), cols = this->dim_,
            mat_stride = M.Stride();
     Real *data = this->data_;
     const Real *mat_data = M.Data();
     for (MatrixIndexT i = 0; i < cols; i++, mat_data++, data++)
       *data = beta * *data + alpha * cblas_Xdot(rows, mat_data, mat_stride,
                                                  mat_data, mat_stride);
   }
 }
void AddDiagMatMat (Real alpha, const MatrixBase< Real > & M, MatrixTransposeType transM, const MatrixBase< Real > & N, MatrixTransposeType transN, Real beta = 1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
Definition at line 1295 of file kaldi-vector.cc.
References kaldi::cblas_Xdot(), MatrixBase< Real >::Data(), rnnlm::i, KALDI_ASSERT, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Stride(), and kaldi::swap().
Referenced by kaldi::UnitTestAddDiagMatMat().
                {
   MatrixIndexT dim = this->dim_,
       M_col_dim = (transM == kTrans ? M.NumRows() : M.NumCols()),
       N_row_dim = (transN == kTrans ? N.NumCols() : N.NumRows());
   KALDI_ASSERT(M_col_dim == N_row_dim); // this is the dimension we sum over
   MatrixIndexT M_row_stride = M.Stride(), M_col_stride = 1;
   if (transM == kTrans) std::swap(M_row_stride, M_col_stride);
   MatrixIndexT N_row_stride = N.Stride(), N_col_stride = 1;
   if (transN == kTrans) std::swap(N_row_stride, N_col_stride);
   Real *data = this->data_;
   const Real *Mdata = M.Data(), *Ndata = N.Data();
   for (MatrixIndexT i = 0; i < dim; i++, Mdata += M_row_stride, Ndata += N_col_stride, data++) {
     *data = beta * *data + alpha * cblas_Xdot(M_col_dim, Mdata, M_col_stride, Ndata, N_row_stride);
   }
 }
void AddMatSvec (const Real alpha, const MatrixBase< Real > & M, const MatrixTransposeType trans, const VectorBase< Real > & v, const Real beta)
This is as AddMatVec, except optimized for where v contains a lot of zeros.
Definition at line 104 of file kaldi-vector.cc.
References VectorBase< Real >::Data(), MatrixBase< Real >::Data(), VectorBase< Real >::dim_, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Stride(), and kaldi::Xgemv_sparsevec().
Referenced by kaldi::UnitTestVecmul().
{
   KALDI_ASSERT((trans == kNoTrans && M.NumCols() == v.dim_ && M.NumRows() == dim_)
                || (trans == kTrans && M.NumRows() == v.dim_ && M.NumCols() == dim_));
   KALDI_ASSERT(&v != this);
   Xgemv_sparsevec(trans, M.NumRows(), M.NumCols(), alpha, M.Data(), M.Stride(),
                   v.Data(), 1, beta, data_, 1);
   return;
   /*
   MatrixIndexT this_dim = this->dim_, v_dim = v.dim_,
       M_stride = M.Stride();
   Real *this_data = this->data_;
   const Real *M_data = M.Data(), *v_data = v.data_;
   if (beta != 1.0) this->Scale(beta);
   if (trans == kNoTrans) {
     for (MatrixIndexT i = 0; i < v_dim; i++) {
       Real v_i = v_data[i];
       if (v_i == 0.0) continue;
       // Add to *this, the i'th column of the Matrix, times v_i.
       cblas_Xaxpy(this_dim, v_i * alpha, M_data + i, M_stride, this_data, 1);
     }
   } else { // The transposed case is slightly more efficient, I guess.
     for (MatrixIndexT i = 0; i < v_dim; i++) {
       Real v_i = v.data_[i];
       if (v_i == 0.0) continue;
       // Add to *this, the i'th row of the Matrix, times v_i.
       cblas_Xaxpy(this_dim, v_i * alpha,
                   M_data + (i * M_stride), 1, this_data, 1);
     }
     }*/
 }
void AddMatVec (const Real alpha, const MatrixBase< Real > & M, const MatrixTransposeType trans, const VectorBase< Real > & v, const Real beta)
Add matrix times vector : this <– beta*this + alpha*M*v.
Calls BLAS GEMV.
Definition at line 91 of file kaldi-vector.cc.
References kaldi::cblas_Xgemv(), VectorBase< Real >::Data(), MatrixBase< Real >::Data(), VectorBase< Real >::dim_, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by OnlineIvectorEstimationStats::AccStats(), FmllrDiagGmmAccs::AccumulateFromPosteriors(), MleSgmm2SpeakerAccs::AccumulateFromPosteriors(), MleSgmmSpeakerAccs::AccumulateFromPosteriors(), LdaEstimate::AddMeanOffset(), kaldi::ApplyAffineTransform(), ApplyFmllrXform(), Fmpe::ApplyProjection(), IvectorExtractorStats::CommitStatsForWPoint(), AmSgmm2::ComponentLogLikes(), kaldi::ComputeAmGmmFeatureDeriv(), Plda::ComputeDerivedVars(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), Mfcc::ComputeInternal(), Plp::ComputeInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm2::ComputePerSpkDerivedVars(), MleAmSgmmUpdater::ComputeSMeans(), MleAmSgmm2Updater::ComputeSMeans(), FmllrRawAccs::ConvertToSimpleStats(), kaldi::CuVectorUnitTestAddMatVec(), BasisFmllrEstimate::EstimateFmllrBasis(), FeatureTransformEstimateMulti::EstimateTransformPart(), kaldi::generate_features(), IvectorExtractor::GetAcousticAuxfMean(), IvectorExtractor::GetAcousticAuxfWeight(), kaldi::GetFeatDeriv(), OnlineTransform::GetFrame(), IvectorExtractor::GetIvectorDistMean(), IvectorExtractor::GetIvectorDistWeight(), LogisticRegression::GetLogPosteriors(), IvectorExtractorStats::GetOrthogonalIvectorTransform(), RegtreeMllrDiagGmm::GetTransformedMeans(), FmllrRawAccs::InitSingleFrameStats(), AmSgmm::LogLikelihood(), FullGmm::LogLikelihoods(), DiagGmm::LogLikelihoods(), DiagGmm::LogLikelihoodsPreselect(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), main(), MleAmSgmmUpdaterMulti::RenormalizeV(), MleAmSgmm2Updater::RenormalizeV(), MleAmSgmmUpdater::RenormalizeV(), kaldi::SolveDoubleQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), Plda::TransformIvector(), UnitTestEstimateLda(), kaldi::UnitTestMul(), kaldi::UnitTestPldaEstimation(), HldaAccsDiagGmm::Update(), FmllrRawAccs::Update(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), EbwAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), IvectorExtractorStats::UpdatePrior(), MleSgmm2SpeakerAccs::UpdateWithU(), MleAmSgmmUpdaterMulti::UpdateWParallel(), MleAmSgmmUpdater::UpdateWParallel(), MleAmSgmmUpdater::UpdateWSequential(), and kaldi::VecMatVec().
{
   KALDI_ASSERT((trans == kNoTrans && M.NumCols() == v.dim_ && M.NumRows() == dim_)
                || (trans == kTrans && M.NumRows() == v.dim_ && M.NumCols() == dim_));
   KALDI_ASSERT(&v != this);
   cblas_Xgemv(trans, M.NumRows(), M.NumCols(), alpha, M.Data(), M.Stride(),
               v.Data(), 1, beta, data_, 1);
 }
void AddRowSumMat (Real alpha, const MatrixBase< Real > & M, Real beta = 1.0)
Does *this = alpha * (sum of rows of M) + beta * *this.
Definition at line 704 of file kaldi-vector.cc.
References kaldi::cblas_Xaxpy(), kaldi::cblas_Xscal(), MatrixBase< Real >::Data(), rnnlm::i, KALDI_ASSERT, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), VectorBase< Real >::Set(), and MatrixBase< Real >::Stride().
Referenced by CovarianceStats::AccStats(), PldaStats::AddSamples(), kaldi::nnet2::AverageConstPart(), IvectorExtractorStats::CommitStatsForW(), kaldi::CuVectorUnitTestAddRowSumMat(), LdaEstimate::GetStats(), AmSgmm2::LogLikelihood(), main(), AmSgmm2::SplitSubstatesInGroup(), kaldi::UnitTestAddRowSumMatSpeed(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), UnitTestEstimateFullGmm(), EbwAmSgmm2Updater::Update(), MleAmSgmm2Updater::Update(), and kaldi::nnet2::UpdateHash().
{
   KALDI_ASSERT(dim_ == M.NumCols());
   MatrixIndexT num_rows = M.NumRows(), stride = M.Stride(), dim = dim_;
   Real *data = data_;
   // implement the function according to a dimension cutoff for computation efficiency
   if (num_rows <= 64) {
     cblas_Xscal(dim, beta, data, 1);
     const Real *m_data = M.Data();
     for (MatrixIndexT i = 0; i < num_rows; i++, m_data += stride)
       cblas_Xaxpy(dim, alpha, m_data, 1, data, 1);
   } else {
     Vector<Real> ones(M.NumRows());
     ones.Set(1.0);
     this->AddMatVec(alpha, M, kTrans, ones, beta);
   }
 }
void AddSpVec (const Real alpha, const SpMatrix< Real > & M, const VectorBase< Real > & v, const Real beta)
Add symmetric positive definite matrix times vector: this <– beta*this + alpha*M*v.
Calls BLAS SPMV.
Definition at line 140 of file kaldi-vector.cc.
References kaldi::cblas_Xspmv(), VectorBase< Real >::Data(), PackedMatrix< Real >::Data(), VectorBase< Real >::dim_, KALDI_ASSERT, and PackedMatrix< Real >::NumRows().
Referenced by kaldi::CalBasisFmllrStepSize(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputePerFrameVars(), AmSgmm2::ComputePerFrameVars(), MleAmSgmmUpdater::ComputeSmoothingTerms(), FullGmmNormal::CopyToFullGmm(), kaldi::CuVectorUnitTestAddSpVec(), kaldi::Debias(), kaldi::FmllrAuxfGradient(), kaldi::FmllrAuxFuncDiagGmm(), kaldi::FmllrInnerUpdate(), IvectorExtractor::GetAcousticAuxfMean(), FullGmm::GetComponentMean(), IvectorExtractor::GetIvectorDistribution(), PldaEstimator::GetStatsFromClassMeans(), kaldi::GpsrBasicAlpha(), kaldi::GpsrBB(), main(), kaldi::MllrAuxFunction(), FullGmm::SetInvCovars(), FullGmm::SetInvCovarsAndMeans(), kaldi::SolveQuadraticProblem(), AmSgmm::SplitSubstates(), AmSgmm2::SplitSubstatesInGroup(), SpMatrix< Real >::TopEigs(), kaldi::UnitTestLbfgs(), kaldi::UnitTestLinearCgd(), kaldi::UnitTestMul(), kaldi::UnitTestSolve(), MlltAccs::Update(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), EbwAmSgmm2Updater::UpdatePhoneVectorsInternal(), and MleSgmm2SpeakerAccs::UpdateWithU().
{
   KALDI_ASSERT(M.NumRows() == v.dim_ && dim_ == v.dim_);
   KALDI_ASSERT(&v != this);
   cblas_Xspmv(alpha, M.NumRows(), M.Data(), v.Data(), 1, beta, data_, 1);
 }
void AddTpVec (const Real alpha, const TpMatrix< Real > & M, const MatrixTransposeType trans, const VectorBase< Real > & v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
Works even if rv == *this.
Definition at line 1230 of file kaldi-vector.cc.
References VectorBase< Real >::dim_, KALDI_ASSERT, VectorBase< Real >::MulTp(), and PackedMatrix< Real >::NumRows().
Referenced by FastNnetCombiner::ComputeCurrentNnet(), FastNnetCombiner::ComputeObjfAndGradient(), FastNnetCombiner::ComputePreconditioner(), SgmmClusterable::Objf(), kaldi::nnet2::PerturbTrainingExample(), FullGmmNormal::Rand(), kaldi::UnitTestCuVectorAddTp(), kaldi::UnitTestCuVectorAddTpVec(), kaldi::UnitTestMul(), and kaldi::UnitTestTriVecSolver().
{
   KALDI_ASSERT(dim_ == v.dim_ && dim_ == M.NumRows());
   if (beta == 0.0) {
     if (&v != this) CopyFromVec(v);
     MulTp(M, trans);
     if (alpha != 1.0) Scale(alpha);
   } else {
     Vector<Real> tmp(v);
     tmp.MulTp(M, trans);
     if (beta != 1.0) Scale(beta);  // *this <-- beta * *this
     AddVec(alpha, tmp);          // *this += alpha * M * v
   }
 }
void AddVec (const float alpha, const VectorBase< float > & rv)
void AddVec< double > (const double alpha, const VectorBase< double > & rv)
void AddVec (const float alpha, const VectorBase< float > & v)
Definition at line 74 of file kaldi-vector.cc.
References kaldi::cblas_Xaxpy(), VectorBase< Real >::Data(), VectorBase< Real >::dim_, and KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == v.dim_);
   KALDI_ASSERT(&v != this);
   cblas_Xaxpy(dim_, alpha, v.Data(), 1, data_, 1);
 }
void AddVec (const double alpha, const VectorBase< double > & v)
Definition at line 83 of file kaldi-vector.cc.
References kaldi::cblas_Xaxpy(), VectorBase< Real >::Data(), VectorBase< Real >::dim_, and KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == v.dim_);
   KALDI_ASSERT(&v != this);
   cblas_Xaxpy(dim_, alpha, v.Data(), 1, data_, 1);
 }
void AddVec (const Real alpha, const VectorBase< OtherReal > & v)
Add vector : *this = *this + alpha * rv (with casting between floats and doubles)
Definition at line 1017 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, and KALDI_ASSERT.
Referenced by OptimizeLbfgs< Real >::AcceptStep(), SgmmClusterable::Accumulate(), HldaAccsDiagGmm::AccumulateFromPosteriors(), AccumFullGmm::AccumulateFromPosteriors(), FmllrRawAccs::AccumulateFromPosteriors(), AccumDiagGmm::AccumulateFromPosteriors(), MleAmSgmm2Accs::AccumulateFromPosteriors(), MleSgmm2SpeakerAccs::AccumulateFromPosteriors(), MleSgmmSpeakerAccs::AccumulateFromPosteriors(), FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect(), SgmmClusterable::Add(), VectorClusterable::Add(), AccumDiagGmm::Add(), IvectorExtractorStats::Add(), MleAmSgmmGlobalAccs::AddAccumulators(), PldaStats::AddSamples(), PldaUnsupervisedAdaptor::AddStats(), Fmpe::ApplyProjection(), VectorBase< Real >::ApproxEqual(), IvectorExtractorStats::CommitStatsForM(), IvectorExtractorStats::CommitStatsForPrior(), AmSgmm2::ComponentLogLikes(), kaldi::ComputeAmGmmFeatureDeriv(), kaldi::ComputeAndSubtractMean(), PitchFrameInfo::ComputeBacktraces(), Fmpe::ComputeC(), AmSgmmFunctions::ComputeDistances(), kaldi::ComputeFeatureNormalizer(), kaldi::ComputeFeatureNormalizingTransform(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), AmSgmm2::ComputeGammaI(), Sgmm2Project::ComputeLdaStats(), kaldi::ComputeLocalCost(), OptimizeLbfgs< Real >::ComputeNewDirection(), PldaEstimator::ComputeObjfPart2(), EbwAmSgmmUpdater::ComputePhoneVecStats(), EbwAmSgmm2Updater::ComputePhoneVecStats(), MleAmSgmmUpdater::ComputeSmoothingTerms(), AmSgmm::ComputeSmoothingTermsFromModel(), BasisFmllrEstimate::ComputeTransform(), CompressedAffineXformStats::CopyFromAffineXformStats(), kaldi::Debias(), kaldi::DiagGmmToStats(), kaldi::EBWUpdateGaussian(), kaldi::FmllrInnerUpdate(), kaldi::GenRandStats(), kaldi::GetFeatureMeanAndVariance(), IvectorExtractor::GetIvectorDistribution(), GetLogLikeTest(), NnetCombiner::GetNnetParameters(), PldaEstimator::GetStatsFromClassMeans(), AmSgmm::GetSubstateSpeakerMean(), AmSgmm2::GetSubstateSpeakerMean(), kaldi::GpsrBasic(), kaldi::GpsrBasicAlpha(), kaldi::GpsrBB(), kaldi::GpsrGradient(), kaldi::GpsrObjective(), FmllrRawAccs::InitSingleFrameStats(), kaldi::LinearCgd(), AmSgmm::LogLikelihood(), Plda::LogLikelihoodRatio(), main(), FullGmm::Merge(), DiagGmm::merged_components_logdet(), FullGmm::MergedComponentsLogdet(), SoftmaxComponent::MixUp(), PitchInterpolator::MultiplyObsProb(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), kaldi::nnet3::PrintPriorDiagnostics(), kaldi::nnet2::PrintPriorDiagnostics(), DeltaFeatures::Process(), ShiftedDeltaFeatures::Process(), kaldi::nnet2::ProcessFile(), AccumFullGmm::Read(), LdaEstimate::Read(), OptimizeLbfgs< Real >::Restart(), NnetCombiner::SelfTestDerivatives(), NnetCombiner::SelfTestModelDerivatives(), kaldi::SlidingWindowCmnInternal(), Plda::SmoothWithinClassCovariance(), kaldi::SolveQuadraticProblem(), SgmmClusterable::Sub(), VectorClusterable::Sub(), kaldi::TestClusterKMeansVector(), SpMatrix< Real >::TopEigs(), kaldi::TypeOneUsage(), kaldi::UnitTestAddDiagMat2(), kaldi::UnitTestAddDiagMatMat(), kaldi::UnitTestAddDiagVecMat(), kaldi::UnitTestAddVecCross(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), kaldi::UnitTestCuVectorAddVec(), UnitTestEstimateDiagGmm(), UnitTestEstimateLda(), kaldi::UnitTestEstimateMmieDiagGmm(), kaldi::UnitTestLbfgs(), kaldi::UnitTestLinearCgd(), kaldi::UnitTestSparseVectorAddToVec(), HldaAccsDiagGmm::Update(), kaldi::UpdateEbwDiagGmm(), MleAmSgmmUpdater::UpdateN(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), EbwAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), PldaUnsupervisedAdaptor::UpdatePlda(), EbwAmSgmm2Updater::UpdateU(), MleAmSgmm2Updater::UpdateU(), EbwAmSgmm2Updater::UpdateW(), MleSgmm2SpeakerAccs::UpdateWithU(), EbwAmSgmmUpdater::UpdateWParallel(), and MleAmSgmmUpdater::UpdateWSequential().
{
   KALDI_ASSERT(dim_ == v.dim_);
   // remove __restrict__ if it causes compilation problems.
   register Real *__restrict__ data = data_;
   register OtherReal *__restrict__ other_data = v.data_;
   MatrixIndexT dim = dim_;
   if (alpha != 1.0)
     for (MatrixIndexT i = 0; i < dim; i++)
       data[i] += alpha * other_data[i];
   else
     for (MatrixIndexT i = 0; i < dim; i++)
       data[i] += other_data[i];
 }
void AddVec2 (const Real alpha, const VectorBase< Real > & v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring].
Definition at line 1222 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, and KALDI_ASSERT.
Referenced by RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), BasisFmllrEstimate::ComputeAmDiagPrecond(), kaldi::DiagGmmToStats(), kaldi::EBWUpdateGaussian(), kaldi::GetFeatureMeanAndVariance(), kaldi::InitGmmFromRandomFrames(), main(), DiagGmm::merged_components_logdet(), DiagGmm::MergeKmeans(), kaldi::SlidingWindowCmnInternal(), kaldi::UnitTestAddVecCross(), UnitTestEstimateDiagGmm(), kaldi::UnitTestEstimateMmieDiagGmm(), and HldaAccsDiagGmm::Update().
{
   KALDI_ASSERT(dim_ == v.dim_);
   for (MatrixIndexT i = 0; i < dim_; i++)
     data_[i] += alpha * v.data_[i] * v.data_[i];
 }
void AddVec2 (const Real alpha, const VectorBase< OtherReal > & v)
Add vector : *this = *this + alpha * rv^2 [element-wise squaring], with casting between floats and doubles.
Definition at line 1038 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == v.dim_);
   // remove __restrict__ if it causes compilation problems.
   register Real *__restrict__ data = data_;
   register OtherReal *__restrict__ other_data = v.data_;
   MatrixIndexT dim = dim_;
   if (alpha != 1.0)
     for (MatrixIndexT i = 0; i < dim; i++)
       data[i] += alpha * other_data[i] * other_data[i];
   else
     for (MatrixIndexT i = 0; i < dim; i++)
       data[i] += other_data[i] * other_data[i];
 }
void AddVecDivVec (Real alpha, const VectorBase< Real > & v, const VectorBase< Real > & r, Real beta)
Add element-by-element quotient of two vectors.
this <—- alpha*v/r + beta*this
Definition at line 1007 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, and KALDI_ASSERT.
Referenced by kaldi::UnitTestSimpleForVec().
{
   KALDI_ASSERT((dim_ == v.dim_ && dim_ == rr.dim_));
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] = alpha * v.data_[i]/rr.data_[i] + beta * data_[i] ;
   }
 }
void AddVecVec (Real alpha, const VectorBase< Real > & v, const VectorBase< Real > & r, Real beta)
Add element-by-element product of vectlrs:
Definition at line 973 of file kaldi-vector.cc.
References kaldi::cblas_Xgbmv(), VectorBase< Real >::data_, VectorBase< Real >::dim_, KALDI_ASSERT, and kaldi::kNoTrans.
Referenced by FmllrRawAccs::AccumulateFromPosteriors(), MleAmSgmm2Accs::CommitStatsForSpk(), kaldi::ComputeAmGmmFeatureDeriv(), kaldi::ComputeLocalCost(), OptimizeLbfgs< Real >::ComputeNewDirection(), kaldi::CuVectorUnitTestAddVecVec(), and kaldi::GetFeatDeriv().
{
   KALDI_ASSERT(v.data_ != this->data_ && r.data_ != this->data_);
   // We pretend that v is a band-diagonal matrix.
   KALDI_ASSERT(dim_ == v.dim_ && dim_ == r.dim_);
   cblas_Xgbmv(kNoTrans, dim_, dim_, 0, 0, alpha, v.data_, 1,
               r.data_, 1, beta, this->data_, 1);
 }
void ApplyAbs ()
Take absolute value of each of the elements.
Definition at line 797 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by kaldi::nnet2::PrintPriorDiagnostics(), kaldi::nnet3::PrintPriorDiagnostics(), and kaldi::UnitTestTopEigs().
{
   for (MatrixIndexT i = 0; i < dim_; i++) { data_[i] = std::abs(data_[i]); }
 }
MatrixIndexT ApplyCeiling (Real ceil_val)
Applies ceiling to all elements. Returns number of elements changed.
Definition at line 814 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by kaldi::CuVectorUnitTestApplyCeiling(), and FeatureTransformEstimate::EstimateInternal().
{
   MatrixIndexT num_changed = 0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     if (data_[i] > ceil_val) {
       data_[i] = ceil_val;
       num_changed++;
     }
   }
   return num_changed;
 }
void ApplyExp ()
Apply exponential to each value in vector.
Definition at line 790 of file kaldi-vector.cc.
References kaldi::Exp(), and rnnlm::i.
Referenced by ComputeLogPosteriors(), kaldi::nnet2::ComputeObjfAndGradient(), AmSgmm2::ComputePerSpkDerivedVars(), IvectorExtractor::GetAcousticAuxfWeight(), NnetCombiner::GetWeights(), kaldi::nnet2::ShrinkNnet(), kaldi::nnet2::UnitTestAmNnet(), kaldi::nnet2::UnitTestNnetDecodable(), kaldi::UnitTestPosteriors(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmm2Updater::UpdateWGetStats(), MleSgmm2SpeakerAccs::UpdateWithU(), and MleAmSgmmUpdaterMulti::UpdateWParallel().
{
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] = Exp(data_[i]);
   }
 }
MatrixIndexT ApplyFloor (Real floor_val)
Applies floor to all elements. Returns number of elements floored.
Definition at line 802 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by Spectrogram::Compute(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), kaldi::CuVectorUnitTestApplyFloor(), PldaEstimator::GetOutput(), kaldi::GpsrBasic(), kaldi::GpsrBB(), IvectorExtractor::InvertWithFlooring(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::SlidingWindowCmnInternal(), kaldi::SolveQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), SpMatrix< Real >::SymPosSemiDefEig(), IvectorExtractorStats::UpdatePrior(), MleAmSgmmUpdaterMulti::UpdateVars(), MleAmSgmm2Updater::UpdateVars(), and MleAmSgmmUpdater::UpdateVars().
{
   MatrixIndexT num_floored = 0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     if (data_[i] < floor_val) {
       data_[i] = floor_val;
       num_floored++;
     }
   }
   return num_floored;
 }
MatrixIndexT ApplyFloor (const VectorBase< Real > & floor_vec)
Applies floor to all elements. Returns number of elements floored.
Definition at line 827 of file kaldi-vector.cc.
References VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(floor_vec.Dim() == dim_);
   MatrixIndexT num_floored = 0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     if (data_[i] < floor_vec(i)) {
       data_[i] = floor_vec(i);
       num_floored++;
     }
   }
   return num_floored;
 }
void ApplyLog ()
Apply natural log to all elements.
Throw if any element of the vector is negative (but doesn't complain about zero; the log will be -infinity
Definition at line 773 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ERR, and kaldi::Log().
Referenced by AmSgmm2::ComponentLogLikes(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), IvectorExtractor::GetAcousticAuxfWeight(), NnetCombiner::GetInitialParameters(), SpMatrix< Real >::Log(), PdfPrior::PdfPrior(), LogisticRegression::ScalePriors(), and MleSgmm2SpeakerAccs::UpdateWithU().
{
   for (MatrixIndexT i = 0; i < dim_; i++) {
     if (data_[i] < 0.0)
       KALDI_ERR << "Trying to take log of a negative number.";
     data_[i] = Log(data_[i]);
   }
 }
void ApplyLogAndCopy (const VectorBase< Real > & v)
Apply natural log to another vector and put result in *this.
Definition at line 782 of file kaldi-vector.cc.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, and kaldi::Log().
Referenced by kaldi::UnitTestSimple().
{
   KALDI_ASSERT(dim_ == v.Dim());
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] = Log(v(i));
   }
 }
Real ApplyLogSoftMax ()
Applies log soft-max to vector and returns normalizer (log sum of exponentials).
This is the same as:
Definition at line 850 of file kaldi-vector.cc.
References kaldi::Exp(), rnnlm::i, and kaldi::Log().
Referenced by kaldi::UnitTestSimpleForVec().
{
   Real max = this->Max(), sum = 0.0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     sum += Exp((data_[i] -= max));
   }
   sum = Log(sum);
   this->Add(-1.0 * sum);
   return max + sum;
 }
void ApplyPow (Real power)
Take all elements of vector to a power.
Definition at line 448 of file kaldi-vector.cc.
References rnnlm::i, and KALDI_ERR.
Referenced by AccumDiagGmm::AccumulateForComponent(), AccumDiagGmm::AccumulateFromPosteriors(), SpMatrix< Real >::ApplyFloor(), SpMatrix< Real >::ApplyPow(), DiagGmm::ComponentLogLikelihood(), OnlineNaturalGradient::ComputeEt(), OnlinePreconditioner::ComputeEt(), Plp::ComputeInternal(), kaldi::CuVectorUnitTestApplyPow(), Plda::LogLikelihoodRatio(), DiagGmm::LogLikelihoods(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), main(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::SlidingWindowCmnInternal(), Plda::SmoothWithinClassCovariance(), kaldi::SolveQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), MatrixBase< Real >::SymPosSemiDefEig(), UnitTestEstimateDiagGmm(), kaldi::UnitTestEstimateMmieDiagGmm(), kaldi::UnitTestPower(), and IvectorExtractorStats::UpdatePrior().
{
   if (power == 1.0) return;
   if (power == 2.0) {
     for (MatrixIndexT i = 0; i < dim_; i++)
       data_[i] = data_[i] * data_[i];
   } else if (power == 0.5) {
     for (MatrixIndexT i = 0; i < dim_; i++) {
       if (!(data_[i] >= 0.0))
         KALDI_ERR << "Cannot take square root of negative value "
                   << data_[i];
       data_[i] = std::sqrt(data_[i]);
     }
   } else {
     for (MatrixIndexT i = 0; i < dim_; i++) {
       data_[i] = pow(data_[i], power);
       if (data_[i] == HUGE_VAL) {  // HUGE_VAL is what errno returns on error.
         KALDI_ERR << "Could not raise element "  << i << "to power "
                   << power << ": returned value = " << data_[i];
       }
     }
   }
 }
void ApplyPowAbs (Real power, bool include_sign = false)
Take the absolute value of all elements of a vector to a power.
Include the sign of the input element if include_sign == true. If power is negative and the input value is zero, the output is set zero.
Definition at line 475 of file kaldi-vector.cc.
References rnnlm::i, and KALDI_ERR.
Referenced by kaldi::UnitTestPowerAbs().
{
   if (power == 1.0)
     for (MatrixIndexT i = 0; i < dim_; i++)
       data_[i] = (include_sign && data_[i] < 0 ? -1 : 1) * std::abs(data_[i]);
   if (power == 2.0) {
     for (MatrixIndexT i = 0; i < dim_; i++)
       data_[i] = (include_sign && data_[i] < 0 ? -1 : 1) * data_[i] * data_[i];
   } else if (power == 0.5) {
     for (MatrixIndexT i = 0; i < dim_; i++) {
       data_[i] = (include_sign && data_[i] < 0 ? -1 : 1) * std::sqrt(std::abs(data_[i]));
     }
   } else if (power < 0.0) {
     for (MatrixIndexT i = 0; i < dim_; i++) {
       data_[i] = (data_[i] == 0.0 ? 0.0 : pow(std::abs(data_[i]), power));
       data_[i] *= (include_sign && data_[i] < 0 ? -1 : 1);
       if (data_[i] == HUGE_VAL) {  // HUGE_VAL is what errno returns on error.
         KALDI_ERR << "Could not raise element "  << i << "to power "
                   << power << ": returned value = " << data_[i];
       }
     }
   } else {
     for (MatrixIndexT i = 0; i < dim_; i++) {
       data_[i] = (include_sign && data_[i] < 0 ? -1 : 1) * pow(std::abs(data_[i]), power);
       if (data_[i] == HUGE_VAL) {  // HUGE_VAL is what errno returns on error.
         KALDI_ERR << "Could not raise element "  << i << "to power "
                   << power << ": returned value = " << data_[i];
       }
     }
   }
 }
Real ApplySoftMax ()
Apply soft-max to vector and return normalizer (log sum of exponentials).
This is the same as:
Definition at line 840 of file kaldi-vector.cc.
References kaldi::Exp(), rnnlm::i, and kaldi::Log().
Referenced by Fmpe::ApplyProjection(), Fmpe::ApplyProjectionReverse(), IvectorExtractorStats::CommitStatsForWPoint(), FullGmm::ComponentPosteriors(), DiagGmm::ComponentPosteriors(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), kaldi::CuVectorUnitTestApplySoftMax(), IvectorExtractor::GetIvectorDistWeight(), main(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), EbwAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), and kaldi::VectorToPosteriorEntry().
{
   Real max = this->Max(), sum = 0.0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     sum += (data_[i] = Exp(data_[i] - max));
   }
   this->Scale(1.0 / sum);
   return max + Log(sum);
 }
bool ApproxEqual (const VectorBase< Real > & other, float tol = 0.01) const
Returns true if ((*this)-other).Norm(2.0) <= tol * (*this).Norm(2.0).
Definition at line 548 of file kaldi-vector.cc.
References VectorBase< Real >::AddVec(), VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, KALDI_ASSERT, KALDI_ERR, and VectorBase< Real >::Norm().
Referenced by kaldi::ApproxEqual(), AccumDiagGmm::AssertEqual(), kaldi::AssertEqual(), kaldi::CuVectorUnitTestCopyDiagFromPacked(), FmllrRawAccs::DataHasChanged(), FmllrDiagGmmAccs::DataHasChanged(), and kaldi::UnitTestNorm().
{
   if (dim_ != other.dim_) KALDI_ERR << "ApproxEqual: size mismatch "
                                     << dim_ << " vs. " << other.dim_;
   KALDI_ASSERT(tol >= 0.0);
   if (tol != 0.0) {
     Vector<Real> tmp(*this);
     tmp.AddVec(-1.0, other);
     return (tmp.Norm(2.0) <= static_cast<Real>(tol) * this->Norm(2.0));
   } else { // Test for exact equality.
     const Real *data = data_;
     const Real *other_data = other.data_;
     for (MatrixIndexT dim = dim_, i = 0; i < dim; i++)
       if (data[i] != other_data[i]) return false;
     return true;
   }
 }
template void CopyColFromMat (const MatrixBase< OtherReal > & M, MatrixIndexT col)
Extracts a column of the matrix M.
Definition at line 648 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ASSERT, MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by kaldi::ComputeVadEnergy(), FmllrRawAccs::FmllrRawAccs(), kaldi::generate_features(), kaldi::IncreaseTransformDimension(), main(), OnlineTransform::OnlineTransform(), TestSgmm2PreXform(), TestSgmmPreXform(), kaldi::UnitTestAddDiagVecMat(), kaldi::UnitTestRow(), kaldi::UnitTestSimpleForVec(), and kaldi::UnitTestSpliceRows().
{
   KALDI_ASSERT(col < mat.NumCols());
   KALDI_ASSERT(dim_ == mat.NumRows());
   for (MatrixIndexT i = 0; i < dim_; i++)
     data_[i] = mat(i, col);
   // can't do this very efficiently so don't really bother. could improve this though.
 }
void CopyColsFromMat (const MatrixBase< Real > & M)
Performs a column stack of the matrix M.
Definition at line 375 of file kaldi-vector.cc.
References MatrixBase< Real >::Data(), rnnlm::i, rnnlm::j, KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by kaldi::UnitTestSpliceRows().
{
   KALDI_ASSERT(dim_ == mat.NumCols() * mat.NumRows());
   Real*       inc_data = data_;
   const MatrixIndexT  cols     = mat.NumCols(), rows = mat.NumRows(), stride = mat.Stride();
   const Real *mat_inc_data = mat.Data();
   for (MatrixIndexT i = 0; i < cols; i++) {
     for (MatrixIndexT j = 0; j < rows; j++) {
       inc_data[j] = mat_inc_data[j*stride];
     }
     mat_inc_data++;
     inc_data += rows;
   }
 }
void CopyDiagFromMat (const MatrixBase< Real > & M)
Extracts the diagonal of the matrix M.
Definition at line 666 of file kaldi-vector.cc.
References kaldi::cblas_Xcopy(), MatrixBase< Real >::Data(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by kaldi::CuVectorUnitTestCopyDiagFromMat(), kaldi::UnitTestAddDiagMat2(), kaldi::UnitTestAddDiagMatMat(), kaldi::UnitTestSpliceRows(), and kaldi::UnitTestTopEigs().
{
   KALDI_ASSERT(dim_ == std::min(M.NumRows(), M.NumCols()));
   cblas_Xcopy(dim_, M.Data(), M.Stride() + 1, data_, 1);
 }
void CopyDiagFromPacked (const PackedMatrix< Real > & M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
Definition at line 672 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ASSERT, and PackedMatrix< Real >::NumCols().
Referenced by VectorBase< BaseFloat >::CopyDiagFromSp(), VectorBase< BaseFloat >::CopyDiagFromTp(), DiagGmm::CopyFromFullGmm(), kaldi::CuVectorUnitTestCopyDiagFromPacked(), and SpMatrix< Real >::Eig().
{
   KALDI_ASSERT(dim_ == M.NumCols());
   for (MatrixIndexT i = 0; i < dim_; i++)
     data_[i] = M(i, i);
   // could make this more efficient.
 }
void CopyDiagFromSp (const SpMatrix< Real > & M) inline
Extracts the diagonal of a symmetric matrix.
Definition at line 287 of file kaldi-vector.h.
Referenced by kaldi::SolveQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), and SpMatrix< Real >::TopEigs().
 { CopyDiagFromPacked(M); }
void CopyDiagFromTp (const TpMatrix< Real > & M) inline
Extracts the diagonal of a triangular matrix.
Definition at line 290 of file kaldi-vector.h.
 { CopyDiagFromPacked(M); }
template void CopyFromPacked (const PackedMatrix< OtherReal > & M)
Copy data from a SpMatrix or TpMatrix (must match own size).
Definition at line 236 of file kaldi-vector.cc.
{
   SubVector<OtherReal> v(M);
   this->CopyFromVec(v);
 }
void CopyFromPtr (const Real * Data, MatrixIndexT sz) protected
Load data into the vector: sz must match own size.
Load data into the vector.
Definition at line 248 of file kaldi-vector.cc.
References KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == sz);
   std::memcpy(this->data_, data, Dim() * sizeof(Real));
 }
void CopyFromVec (const VectorBase< Real > & v)
Copy data from another vector (must match own size).
Copy data from another vector.
Definition at line 227 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::Dim(), and KALDI_ASSERT.
Referenced by OptimizeLbfgs< Real >::AcceptStep(), RegtreeMllrDiagGmmAccs::AccumulateForGaussian(), RegtreeMllrDiagGmmAccs::AccumulateForGmm(), AccumFullGmm::AccumulateFromPosteriors(), kaldi::ApplyAffineTransform(), Fmpe::ApplyC(), kaldi::ClusterGaussiansToUbm(), NnetCombiner::Combine(), kaldi::nnet2::CombineNnets(), kaldi::nnet2::CombineNnetsA(), FullGmm::ComponentPosteriors(), DiagGmm::ComponentPosteriors(), Spectrogram::Compute(), kaldi::ComputeAndSubtractMean(), OnlineNaturalGradient::ComputeEt(), OnlinePreconditioner::ComputeEt(), kaldi::ComputeFeatureNormalizer(), kaldi::ComputeFeatureNormalizingTransform(), Fbank::ComputeInternal(), Plp::ComputeInternal(), AmSgmm::ComputePerFrameVars(), AmSgmm2::ComputePerFrameVars(), AmSgmm2::ComputePerSpkDerivedVars(), EbwAmSgmmUpdater::ComputePhoneVecStats(), EbwAmSgmm2Updater::ComputePhoneVecStats(), OnlineCmvn::ComputeStatsForFrame(), FmllrRawAccs::ConvertToSimpleStats(), kaldi::ConvolveSignals(), SgmmClusterable::Copy(), DiagGmmNormal::CopyFromDiagGmm(), FullGmm::CopyFromDiagGmm(), DiagGmm::CopyFromDiagGmm(), FullGmmNormal::CopyFromFullGmm(), FullGmm::CopyFromFullGmm(), DiagGmm::CopyFromFullGmm(), DiagGmmNormal::CopyToDiagGmm(), FullGmmNormal::CopyToFullGmm(), CuVectorBase< Real >::CopyToVec(), kaldi::CuVectorUnitTestCopyCross2(), kaldi::Debias(), DiscriminativeExampleSplitter::DoExcise(), kaldi::EBWUpdateGaussian(), NnetDecodableBase::EnsureFrameIsComputed(), OnlinePitchFeatureImpl::ExtractFrame(), kaldi::ExtractWaveformRemainder(), kaldi::ExtractWindow(), FastNnetCombiner::FastNnetCombiner(), kaldi::FFTbasedBlockConvolveSignals(), kaldi::FFTbasedConvolveSignals(), kaldi::FilterMatrixRows(), FullGmm::GetComponentMean(), FullGmm::GetCovarsAndMeans(), kaldi::GetFeatureMeanAndVariance(), OnlineGenericBaseFeature< C >::GetFrame(), OnlineMatrixFeature::GetFrame(), OnlineCmvn::GetFrame(), OnlineTransform::GetFrame(), OnlineCacheFeature::GetFrame(), IvectorExtractor::GetIvectorDistribution(), RegtreeFmllrDiagGmm::GetLogDets(), LogisticRegression::GetLogPosteriors(), FullGmm::GetMeans(), NnetCombiner::GetNormalizedWeights(), LogisticRegression::GetObjfAndGrad(), NnetDecodableBase::GetOutputForFrame(), NnetCombiner::GetParamsDeriv(), OnlineCmvn::GetState(), AmSgmm::GetSubstateMean(), AmSgmm2::GetSubstateMean(), NnetCombiner::GetUnnormalizedWeightsDeriv(), AmSgmm::GetVarScaledSubstateSpeakerMean(), AmSgmm2::GetVarScaledSubstateSpeakerMean(), NnetCombiner::GetWeights(), kaldi::GpsrBasic(), kaldi::GpsrBB(), kaldi::GpsrGradient(), kaldi::GpsrObjective(), FmllrDiagGmmAccs::InitSingleFrameStats(), kaldi::IsmoothStatsDiagGmm(), IvectorExtractor::IvectorExtractor(), kaldi::LinearCgd(), FullGmm::LogLikelihoods(), DiagGmm::LogLikelihoods(), DiagGmm::LogLikelihoodsPreselect(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), main(), DiagGmm::merged_components_logdet(), FullGmm::MergedComponentsLogdet(), DiagGmm::MergeKmeans(), SoftmaxComponent::MixUp(), Vector< BaseFloat >::operator=(), OnlineNaturalGradientSimple::PreconditionDirections(), OnlinePreconditionerSimple::PreconditionDirections(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::nnet3::ProcessFile(), kaldi::nnet2::ProcessFile(), FullGmmNormal::Rand(), kaldi::RealFftInefficient(), OptimizeLbfgs< Real >::Restart(), kaldi::ReverseFrames(), DiagGmm::SetComponentInvVar(), FullGmm::SetInvCovars(), Sgmm2PerSpkDerivedVars::SetSpeakerVector(), Nnet::SetWeights(), FullGmm::SetWeights(), DiagGmm::SetWeights(), kaldi::SlidingWindowCmnInternal(), kaldi::SolveQuadraticProblem(), SpMatrix< Real >::TopEigs(), Plda::TransformIvector(), kaldi::UnitTestAddDiagVecMat(), kaldi::UnitTestComplexFft(), kaldi::UnitTestCuVectorCopyFromVec(), kaldi::UnitTestDiagGmm(), UnitTestEstimateLda(), UnitTestFullGmm(), kaldi::UnitTestIoCross(), kaldi::UnitTestPower(), kaldi::UnitTestPowerAbs(), UnitTestReadWave(), kaldi::UnitTestRealFft(), kaldi::UnitTestRegtreeFmllrDiagGmm(), kaldi::UnitTestSimpleForVec(), kaldi::UnitTestSplitRadixComplexFft(), kaldi::UnitTestSplitRadixComplexFft2(), kaldi::UnitTestSplitRadixRealFft(), kaldi::UnitTestSubvector(), FmllrRawAccs::Update(), MleSgmmSpeakerAccs::Update(), kaldi::UpdateEbwDiagGmm(), kaldi::UpdateEbwWeightsDiagGmm(), MleSgmm2SpeakerAccs::UpdateNoU(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), PldaUnsupervisedAdaptor::UpdatePlda(), IvectorExtractorStats::UpdateProjection(), IvectorExtractorStats::UpdateVariances(), IvectorExtractorStats::UpdateWeight(), MleSgmm2SpeakerAccs::UpdateWithU(), VectorRandomizer::Value(), Vector< BaseFloat >::Vector(), PerElementScaleComponent::Vectorize(), PerElementOffsetComponent::Vectorize(), NormalizeComponent::Write(), and NonlinearComponent::Write().
{
   KALDI_ASSERT(Dim() == v.Dim());
   if (data_ != v.data_) {
     std::memcpy(this->data_, v.data_, dim_ * sizeof(Real));
   }
 }
void CopyFromVec (const VectorBase< OtherReal > & v)
Copy data from another vector of different type (double vs. float)
Definition at line 255 of file kaldi-vector.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == other.Dim());
   Real * __restrict__  ptr = data_;
   const OtherReal * __restrict__ other_ptr = other.Data();
   for (MatrixIndexT i = 0; i < dim_; i++)
     ptr[i] = other_ptr[i];
 }
void CopyFromVec (const CuVectorBase< OtherReal > & v)
Copy from CuVector. This is defined in ../cudamatrix/cu-vector.h.
Definition at line 346 of file cu-vector.h.
{
   cu.CopyToVec(this);
 }
void CopyRowFromMat (const MatrixBase< Real > & M, MatrixIndexT row)
Extracts a row of the matrix M.
Could also do this with this->Copy(M[row]).
Definition at line 392 of file kaldi-vector.cc.
References KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::RowData().
Referenced by RegtreeFmllrDiagGmmAccs::AccumulateForGaussian(), RegtreeFmllrDiagGmmAccs::AccumulateForGmm(), DiagGmm::GetComponentMean(), DiagGmm::GetComponentVariance(), LdaEstimate::GetStats(), main(), UnitTestEstimateDiagGmm(), kaldi::UnitTestEstimateMmieDiagGmm(), kaldi::UnitTestPosteriors(), kaldi::UnitTestRow(), and kaldi::UnitTestSpliceRows().
{
   KALDI_ASSERT(row < mat.NumRows());
   KALDI_ASSERT(dim_ == mat.NumCols());
   const Real *mat_row = mat.RowData(row);
   memcpy(data_, mat_row, sizeof(Real)*dim_);
 }
void CopyRowFromMat (const MatrixBase< OtherReal > & M, MatrixIndexT row)
Extracts a row of the matrix M with type conversion.
Definition at line 401 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::RowData().
{
   KALDI_ASSERT(row < mat.NumRows());
   KALDI_ASSERT(dim_ == mat.NumCols());
   const OtherReal *mat_row = mat.RowData(row);
   for (MatrixIndexT i = 0; i < dim_; i++)
     data_[i] = static_cast<Real>(mat_row[i]);
 }
template void CopyRowFromSp (const SpMatrix< OtherReal > & S, MatrixIndexT row)
Extracts a row of the symmetric matrix S.
Definition at line 416 of file kaldi-vector.cc.
References PackedMatrix< Real >::Data(), rnnlm::i, KALDI_ASSERT, PackedMatrix< Real >::NumCols(), and PackedMatrix< Real >::NumRows().
Referenced by CompressedAffineXformStats::CopyFromAffineXformStats().
{
   KALDI_ASSERT(row < sp.NumRows());
   KALDI_ASSERT(dim_ == sp.NumCols());
   const OtherReal *sp_data = sp.Data();
   sp_data += (row*(row+1)) / 2; // takes us to beginning of this row.
   MatrixIndexT i;
   for (i = 0; i < row; i++) // copy consecutive elements.
     data_[i] = static_cast<Real>(*(sp_data++));
   for(; i < dim_; ++i, sp_data += i)
     data_[i] = static_cast<Real>(*sp_data);
 }
void CopyRowsFromMat (const MatrixBase< Real > & M)
Performs a row stack of the matrix M.
Definition at line 333 of file kaldi-vector.cc.
References MatrixBase< Real >::Data(), rnnlm::i, KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::RowData(), and MatrixBase< Real >::Stride().
Referenced by BasisFmllrAccus::AccuGradientScatter(), FmllrSgmmAccs::AccumulateForFmllrSubspace(), FmllrSgmm2Accs::AccumulateForFmllrSubspace(), kaldi::CuVectorUnitTestCopyFromMat(), FmllrRawAccs::GetAuxf(), kaldi::nnet1::MomentStatistics(), kaldi::nnet2::PerturbTrainingExample(), LogisticRegression::TrainParameters(), and kaldi::UnitTestSpliceRows().
{
   KALDI_ASSERT(dim_ == mat.NumCols() * mat.NumRows());
   Real *inc_data = data_;
   const MatrixIndexT cols = mat.NumCols(), rows = mat.NumRows();
   if (mat.Stride() == mat.NumCols()) {
     memcpy(inc_data, mat.Data(), cols*rows*sizeof(Real));
   } else {
     for (MatrixIndexT i = 0; i < rows; i++) {
       // copy the data to the propper position
       memcpy(inc_data, mat.RowData(i), cols * sizeof(Real));
       // set new copy position
       inc_data += cols;
     }
   }
 }
void CopyRowsFromMat (const MatrixBase< OtherReal > & M)
Definition at line 353 of file kaldi-vector.cc.
References rnnlm::i, rnnlm::j, KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::RowData().
{
   KALDI_ASSERT(dim_ == mat.NumCols() * mat.NumRows());
   Real *vec_data = data_;
   const MatrixIndexT cols = mat.NumCols(),
       rows = mat.NumRows();
   for (MatrixIndexT i = 0; i < rows; i++) {
     const OtherReal *mat_row = mat.RowData(i);
     for (MatrixIndexT j = 0; j < cols; j++) {
       vec_data[j] = static_cast<Real>(mat_row[j]);
     }
     vec_data += cols;
   }
 }
void CopyRowsFromMat (const CuMatrixBase< Real > & M)
The following is implemented in ../cudamatrix/cu-matrix.cc.
Definition at line 2115 of file cu-matrix.cc.
References CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::RowData(), and CuMatrixBase< Real >::Stride().
{
   KALDI_ASSERT(dim_ == mat.NumCols() * mat.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     if (mat.Stride() == mat.NumCols()) {
       cudaMemcpy(data_, mat.Data(), sizeof(Real)*dim_, cudaMemcpyDeviceToHost);
     } else {
       // we could definitely do better than the following.
       Real* vec_data = data_;
       for (MatrixIndexT r = 0; r < mat.NumRows(); r++) {
         cudaMemcpy(vec_data, mat.RowData(r), sizeof(Real) * mat.NumCols(),
                    cudaMemcpyDeviceToHost);
         vec_data += mat.NumCols();
       }
     }
     CuDevice::Instantiate().AccuProfile("CuVectorBase::CopyRowsFromMat", tim.Elapsed());
   } else
 #endif
   {
     CopyRowsFromMat(mat.Mat());
   }
 }
Real* Data () inline
Returns a pointer to the start of the vector's data.
Definition at line 65 of file kaldi-vector.h.
Referenced by kaldi::AccCmvnStats(), SpMatrix< Real >::AddDiagVec(), MatrixBase< Real >::AddDiagVecMat(), SpMatrix< Real >::AddMat2Sp(), SpMatrix< Real >::AddMat2Vec(), MatrixBase< Real >::AddMatDiagVec(), VectorBase< Real >::AddMatSvec(), VectorBase< Real >::AddMatVec(), kaldi::AddOuterProductPlusMinus(), kaldi::AddSinusoid(), VectorBase< Real >::AddSpVec(), SparseVector< Real >::AddToVec(), VectorBase< Real >::AddVec(), SpMatrix< Real >::AddVec2(), SpMatrix< Real >::AddVec2Sp(), MatrixBase< Real >::AddVecToCols(), MatrixBase< Real >::AddVecToRows(), MatrixBase< Real >::AddVecVec(), SpMatrix< Real >::AddVecVec(), PitchInterpolator::Backtrace(), kaldi::ComplexFft(), kaldi::ComplexFftRecursive(), kaldi::ComplexFt(), kaldi::nnet3::ComponentDotProducts(), Spectrogram::Compute(), PitchFrameInfo::ComputeBacktraces(), SinusoidDetector::ComputeCoarseInfo(), OnlineNaturalGradient::ComputeEt(), OnlinePreconditioner::ComputeEt(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), Plp::ComputeInternal(), kaldi::ComputeLpc(), kaldi::ComputeVadEnergy(), MatrixBase< Real >::CopyColFromVec(), MatrixBase< Real >::CopyColsFromVec(), CompressedMatrix::CopyColToVec(), MatrixBase< Real >::CopyDiagFromVec(), SparseVector< Real >::CopyElementsToVec(), SparseMatrix< Real >::CopyElementsToVec(), CuVectorBase< Real >::CopyFromVec(), PackedMatrix< Real >::CopyFromVec(), VectorBase< Real >::CopyFromVec(), MatrixBase< Real >::CopyRowFromVec(), MatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), CompressedMatrix::CopyRowToVec(), CuVectorBase< Real >::CopyToVec(), SinusoidDetector::CreateCosAndSin(), VectorBase< Real >::DivElements(), kaldi::FFTbasedBlockConvolveSignals(), kaldi::FFTbasedConvolveSignals(), FullGmm::GaussianSelection(), DiagGmm::GaussianSelection(), AmSgmm::GaussianSelection(), AmSgmm2::GaussianSelection(), FullGmm::GaussianSelectionPreselect(), DiagGmm::GaussianSelectionPreselect(), AmSgmm::GaussianSelectionPreselect(), MatrixBase< Real >::LapackGesvd(), SoftmaxComponent::MixUp(), VectorBase< Real >::MulElements(), SpMatrix< Real >::Qr(), kaldi::RealFft(), kaldi::SelectLags(), AmSgmm2::SplitSubstatesInGroup(), SubVector< Real >::SubVector(), kaldi::nnet3::SummarizeVector(), SpMatrix< Real >::Tridiagonalize(), kaldi::UnitTestEigSp(), kaldi::UnitTestPldaEstimation(), kaldi::UnitTestSimpleForMat(), kaldi::UnitTestSplitRadixComplexFft(), kaldi::UnitTestSplitRadixRealFft(), kaldi::UnitTestSplitRadixRealFftSpeed(), kaldi::UnitTestTopEigs(), kaldi::VecSpVec(), kaldi::VecSvec(), and kaldi::VecVec().
 { return data_; }
const Real* Data () const inline
Returns a pointer to the start of the vector's data (const).
Definition at line 68 of file kaldi-vector.h.
 { return data_; }
MatrixIndexT Dim () const inline
Returns the dimension of the vector.
Definition at line 59 of file kaldi-vector.h.
Referenced by kaldi::AccCmvnStats(), kaldi::AccCmvnStatsWrapper(), OnlineGenericBaseFeature< C >::AcceptWaveform(), OnlinePitchFeatureImpl::AcceptWaveform(), LdaEstimate::Accumulate(), AccumFullGmm::AccumulateForComponent(), AccumDiagGmm::AccumulateForComponent(), FmllrRawAccs::AccumulateForGmm(), kaldi::AccumulateForUtterance(), AccumDiagGmm::AccumulateFromDiag(), MlltAccs::AccumulateFromPosteriors(), HldaAccsDiagGmm::AccumulateFromPosteriors(), AccumFullGmm::AccumulateFromPosteriors(), AccumDiagGmm::AccumulateFromPosteriors(), MleAmSgmm2Accs::AccumulateFromPosteriors(), MleAmSgmmAccs::AccumulateFromPosteriors(), MleSgmm2SpeakerAccs::AccumulateFromPosteriors(), FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect(), AccumulateMultiThreadedClass::AccumulateMultiThreadedClass(), VectorRandomizer::AddData(), SpMatrix< Real >::AddDiagVec(), MatrixBase< Real >::AddDiagVecMat(), kaldi::AddFreqToSignal(), SpMatrix< Real >::AddMat2Vec(), MatrixBase< Real >::AddMatDiagVec(), Nnet::AddNnet(), kaldi::AddOuterProductPlusMinus(), kaldi::AddSinusoid(), kaldi::AddSinusoidSimple(), PldaUnsupervisedAdaptor::AddStats(), SparseVector< Real >::AddToVec(), SpMatrix< Real >::AddVec2(), SpMatrix< Real >::AddVec2Sp(), MatrixBase< Real >::AddVecToCols(), MatrixBase< Real >::AddVecToRows(), kaldi::AddVectorsOfUnequalLength(), MatrixBase< Real >::AddVecVec(), SpMatrix< Real >::AddVecVec(), kaldi::nnet2::AppendDiscriminativeExamples(), kaldi::AppendVector(), kaldi::AppendVectorToFeats(), kaldi::ApplyAffineTransform(), VectorBase< Real >::ApplyFloor(), SpMatrix< Real >::ApplyFloor(), ApplyFmllrXform(), VectorBase< Real >::ApplyLogAndCopy(), Fmpe::ApplyProjection(), Fmpe::ApplyProjectionReverse(), AssertEqual(), kaldi::nnet2::AverageConstPart(), MleAmSgmm2Accs::Check(), MleAmSgmmAccs::Check(), IvectorExtractorStats::CheckDims(), MleSgmm2SpeakerAccs::Clear(), kaldi::nnet2::CombineNnets(), kaldi::nnet2::CombineNnetsA(), IvectorExtractorStats::CommitStatsForM(), MleAmSgmm2Accs::CommitStatsForSpk(), MleAmSgmmAccs::CommitStatsForSpk(), kaldi::ComplexFft(), kaldi::ComplexFftRecursive(), kaldi::ComplexFt(), kaldi::nnet3::ComponentDotProducts(), Nnet::ComponentDotProducts(), FullGmm::ComponentLogLikelihood(), DiagGmm::ComponentLogLikelihood(), AmSgmm2::ComponentLogLikes(), DiagGmm::ComponentPosteriors(), Spectrogram::Compute(), MelBanks::Compute(), kaldi::ComputeAndProcessKaldiPitch(), PitchFrameInfo::ComputeBacktraces(), FastNnetCombiner::ComputeCurrentNnet(), kaldi::ComputeEarlyReverbEnergy(), OnlineNaturalGradient::ComputeEt(), OnlinePreconditioner::ComputeEt(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), AmSgmm2::ComputeGammaI(), kaldi::ComputeGconsts(), FullGmm::ComputeGconsts(), DiagGmm::ComputeGconsts(), SgmmClusterable::ComputeH(), AmSgmm2::ComputeHsmFromModel(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), Plp::ComputeInternal(), kaldi::ComputeKaldiPitch(), kaldi::ComputeKaldiPitchFirstPass(), kaldi::ComputeLifterCoeffs(), kaldi::ComputeLocalCost(), kaldi::ComputeLpc(), kaldi::ComputeNccf(), kaldi::nnet2::ComputeObjfAndGradient(), FastNnetCombiner::ComputeObjfAndGradient(), AmSgmm::ComputePerFrameVars(), AmSgmm2::ComputePerFrameVars(), AmSgmm::ComputePerSpkDerivedVars(), AmSgmm2::ComputePerSpkDerivedVars(), kaldi::ComputePowerSpectrum(), AmSgmm::ComputeSmoothingTermsFromModel(), OnlineNaturalGradient::ComputeWt1(), OnlinePreconditioner::ComputeWt1(), OnlineNaturalGradient::ComputeZt(), OnlinePreconditioner::ComputeZt(), MatrixBase< Real >::Cond(), kaldi::ConvolveSignals(), MatrixBase< Real >::CopyColFromVec(), MatrixBase< Real >::CopyColsFromVec(), CompressedMatrix::CopyColToVec(), MatrixBase< Real >::CopyDiagFromVec(), SparseVector< Real >::CopyElementsToVec(), SparseMatrix< Real >::CopyElementsToVec(), DiagGmmNormal::CopyFromDiagGmm(), DiagGmm::CopyFromDiagGmm(), CuVectorBase< Real >::CopyFromVec(), PackedMatrix< Real >::CopyFromVec(), VectorBase< Real >::CopyFromVec(), MatrixBase< Real >::CopyRowFromVec(), MatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), CompressedMatrix::CopyRowToVec(), DiagGmmNormal::CopyToDiagGmm(), FullGmmNormal::CopyToFullGmm(), CuVectorBase< Real >::CopyToVec(), SinusoidDetector::CreateCosAndSin(), kaldi::CreateEigenvalueMatrix(), CuVector< BaseFloat >::CuVector(), FmllrRawAccs::DataHasChanged(), FmllrDiagGmmAccs::DataHasChanged(), kaldi::Debias(), DeltaFeatures::DeltaFeatures(), MatrixBase< Real >::DestructiveSvd(), SinusoidDetector::DetectSinusoid(), kaldi::DetectSinusoids(), Plda::Dim(), OnlineTransform::Dim(), kaldi::Dither(), VectorBase< Real >::DivElements(), NnetDecodableBase::DoNnetComputation(), kaldi::DoReverberation(), kaldi::EBWUpdateGaussian(), SpMatrix< Real >::Eig(), kaldi::ElementwiseProductOfFft(), Sgmm2PerSpkDerivedVars::Empty(), FeatureTransformEstimate::EstimateInternal(), kaldi::EstimateSgmm2FmllrSubspace(), kaldi::EstimateSgmmFmllrSubspace(), Xent::Eval(), Mse::Eval(), OnlinePitchFeatureImpl::ExtractFrame(), kaldi::ExtractWaveformRemainder(), kaldi::ExtractWindow(), FastNnetCombiner::FastNnetCombiner(), kaldi::FFTbasedBlockConvolveSignals(), kaldi::FFTbasedConvolveSignals(), AmSgmm::GaussianSelection(), AmSgmm2::GaussianSelection(), AmSgmm::GaussianSelectionPreselect(), DiagGmm::Generate(), FullGmm::GetComponentMean(), DiagGmm::GetComponentMean(), DiagGmm::GetComponentVariance(), kaldi::GetFeatureMeanAndVariance(), OnlineGenericBaseFeature< C >::GetFrame(), OnlineCmvn::GetFrame(), OnlineProcessPitch::GetFrame(), OnlineSpliceFrames::GetFrame(), OnlineDeltaFeature::GetFrame(), OnlineAppendFeature::GetFrame(), OnlinePitchFeatureImpl::GetFrame(), EigenvalueDecomposition< Real >::GetImagEigenvalues(), NnetCombiner::GetInitialParameters(), OnlineIvectorEstimationStats::GetIvector(), NnetDecodableBase::GetIvectorDim(), IvectorExtractor::GetIvectorDistribution(), Nnet::GetLearningRates(), RegtreeFmllrDiagGmm::GetLogDets(), LogisticRegression::GetLogPosteriors(), MultiSinusoidDetector::GetNextFrame(), MultiSinusoidDetector::GetNextFrameOfSignal(), NnetCombiner::GetNnetParameters(), kaldi::GetOccs(), Nnet::GetParams(), ParallelComponent::GetParams(), FramePoolingComponent::GetParams(), NnetCombiner::GetParamsDeriv(), IvectorExtractor::GetPriorAuxf(), EigenvalueDecomposition< Real >::GetRealEigenvalues(), kaldi::GetSplitTargets(), AmSgmm::GetSubstateMean(), AmSgmm2::GetSubstateMean(), AmSgmm::GetSubstateSpeakerMean(), AmSgmm2::GetSubstateSpeakerMean(), AmSgmm::GetVarScaledSubstateSpeakerMean(), AmSgmm2::GetVarScaledSubstateSpeakerMean(), Nnet::GetWeights(), NnetCombiner::GetWeights(), NnetCombiner::GetWeightsDeriv(), kaldi::GpsrBasic(), kaldi::GpsrBasicAlpha(), kaldi::GpsrBB(), kaldi::GpsrCalcLinearCoeff(), kaldi::GpsrGradient(), kaldi::GpsrObjective(), AmNnet::Info(), AmNnetSimple::Info(), AmNnet::Init(), FramePoolingComponent::InitData(), InitRand(), kaldi::InitRand(), FmllrRawAccs::InitSingleFrameStats(), SgmmPerFrameDerivedVars::IsEmpty(), Sgmm2FmllrGlobalParams::IsEmpty(), SgmmFmllrGlobalParams::IsEmpty(), OnlineIvectorEstimationStats::IvectorDim(), kaldi::nnet3::KlDivergence(), kaldi::nnet2::KlDivergence(), MatrixBase< Real >::LapackGesvd(), NnetDiscriminativeUpdater::LatticeComputations(), FullGmm::LogLikelihoods(), DiagGmm::LogLikelihoods(), FullGmm::LogLikelihoodsPreselect(), DiagGmm::LogLikelihoodsPreselect(), DecodableAmDiagGmmRegtreeFmllr::LogLikelihoodZeroBased(), DecodableAmSgmm::LogLikelihoodZeroBased(), DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), main(), TransitionModel::MapUpdate(), TransitionModel::MapUpdateShared(), DiagGmm::merged_components_logdet(), FullGmm::MergedComponentsLogdet(), SoftmaxComponent::MixUp(), kaldi::MleDiagGmmUpdate(), TransitionModel::MleUpdate(), TransitionModel::MleUpdateShared(), kaldi::nnet1::MomentStatistics(), MatrixBase< Real >::MulColsVec(), VectorBase< Real >::MulElements(), MatrixBase< Real >::MulRowsVec(), SgmmPerFrameDerivedVars::NeedsResizing(), FullGmm::NumGauss(), DiagGmmNormal::NumGauss(), DiagGmm::NumGauss(), SgmmClusterable::Objf(), OnlinePitchFeatureImpl::OnlinePitchFeatureImpl(), FisherComputationClass::operator()(), CuVector< BaseFloat >::operator=(), Vector< BaseFloat >::operator=(), OptimizeLbfgs< Real >::OptimizeLbfgs(), PdfPrior::PdfPrior(), kaldi::Preemphasize(), TransitionModel::Print(), NnetCombiner::PrintParams(), kaldi::nnet3::PrintPriorDiagnostics(), kaldi::nnet2::PrintPriorDiagnostics(), kaldi::nnet3::PrintVectorPerUpdatableComponent(), IvectorExtractorStats::PriorDiagnostics(), DeltaFeatures::Process(), ShiftedDeltaFeatures::Process(), NnetDiscriminativeUpdater::Propagate(), kaldi::unittest::RandDiagGaussFeatures(), kaldi::unittest::RandFullGaussFeatures(), FullGmm::Read(), MleAmSgmm2Accs::Read(), MleAmSgmmAccs::Read(), VectorBase< Real >::Read(), Vector< Real >::Read(), PermuteComponent::Read(), kaldi::RealFft(), kaldi::RealFftInefficient(), OnlinePitchFeatureImpl::RecomputeBacktraces(), ArbitraryResample::Resample(), LinearResample::Resample(), DiagGmmNormal::Resize(), FullGmmNormal::Resize(), FullGmm::Resize(), DiagGmm::Resize(), Sgmm2PerFrameDerivedVars::Resize(), Nnet::ScaleComponents(), DiagGmm::SetComponentInvVar(), DiagGmm::SetComponentMean(), ArbitraryResample::SetIndexes(), Nnet::SetLearningRates(), PitchFrameInfo::SetNccfPov(), AmNnetSimple::SetNnet(), kaldi::nnet2::SetPriors(), kaldi::nnet3::SetPriors(), AmNnet::SetPriors(), AmNnetSimple::SetPriors(), LinearResample::SetRemainder(), Sgmm2PerSpkDerivedVars::SetSpeakerVector(), Nnet::SetWeights(), FullGmm::SetWeights(), DiagGmm::SetWeights(), kaldi::SolveQuadraticProblem(), kaldi::SortSvd(), AmSgmm::SplitSubstates(), AmSgmm2::SplitSubstates(), SubVector< Real >::SubVector(), kaldi::nnet3::SummarizeVector(), MatrixBase< Real >::SymPosSemiDefEig(), SpMatrix< Real >::TopEigs(), RegtreeFmllrDiagGmm::TransformFeature(), Plda::TransformIvector(), kaldi::TypeOneUsage(), kaldi::UnitTestBlockConvolution(), kaldi::UnitTestConvolution(), kaldi::UnitTestCuMatrixSetRandUniform(), kaldi::UnitTestDelay(), UnitTestEstimateLda(), UnitTestLinearResample(), UnitTestLinearResample2(), kaldi::UnitTestPieces(), kaldi::UnitTestPldaEstimation(), UnitTestReadWave(), kaldi::UnitTestReplaceValue(), kaldi::UnitTestSetRandUniform(), kaldi::UnitTestSimple(), UnitTestSimple(), kaldi::UnitTestSvdNodestroy(), kaldi::UnitTestToneDetection2(), AffineComponent::UnVectorize(), RepeatedAffineComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), Convolutional1dComponent::UnVectorize(), CompositeComponent::UnVectorize(), kaldi::nnet3::UnVectorizeNnet(), MleSgmm2SpeakerAccs::Update(), MleSgmmSpeakerAccs::Update(), MleSgmm2SpeakerAccs::UpdateNoU(), PldaUnsupervisedAdaptor::UpdatePlda(), OnlinePitchFeatureImpl::UpdateRemainder(), EbwAmSgmmUpdater::UpdateSubstateWeights(), EbwAmSgmm2Updater::UpdateSubstateWeights(), MleSgmm2SpeakerAccs::UpdateWithU(), RegtreeFmllrDiagGmm::Validate(), kaldi::VecMatVec(), kaldi::VecSpVec(), kaldi::VecSvec(), Vector< BaseFloat >::Vector(), AffineComponent::Vectorize(), RepeatedAffineComponent::Vectorize(), BlockAffineComponent::Vectorize(), ConvolutionComponent::Vectorize(), Convolutional1dComponent::Vectorize(), CompositeComponent::Vectorize(), kaldi::nnet3::VectorizeNnet(), kaldi::VectorToPosteriorEntry(), kaldi::VecVec(), and AccumDiagGmm::Write().
 { return dim_; }
void DivElements (const VectorBase< Real > & v)
Divide element-by-element by a vector.
Definition at line 984 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, and KALDI_ASSERT.
Referenced by DiagGmm::GetComponentMean(), main(), and kaldi::SolveQuadraticProblem().
{
   KALDI_ASSERT(dim_ == v.dim_);
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] /= v.data_[i];
   }
 }
void DivElements (const VectorBase< OtherReal > & v)
Divide element-by-element by a vector of different type.
Definition at line 993 of file kaldi-vector.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == v.Dim());
   const OtherReal *other_ptr = v.Data();
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] /= other_ptr[i];
   }
 }
void InvertElements ()
Invert all elements.
Definition at line 766 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by OnlineNaturalGradient::ComputeEt(), OnlinePreconditioner::ComputeEt(), OnlineNaturalGradient::ComputeWt1(), OnlinePreconditioner::ComputeWt1(), DiagGmm::CopyFromFullGmm(), CuMatrixBase< Real >::DivRowsVec(), DiagGmm::GetComponentVariance(), kaldi::GetFeatureMeanAndVariance(), IvectorExtractor::InvertWithFlooring(), Plda::LogLikelihoodRatio(), main(), DiagGmm::MergeKmeans(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), DiagGmm::SetComponentInvVar(), AccumDiagGmm::SmoothStats(), kaldi::SolveQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), kaldi::UnitTestCuMatrixDivRowsVec(), and kaldi::UnitTestCuVectorInvertElements().
{
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] = static_cast<Real>(1 / data_[i]);
   }
 }
bool IsZero (Real cutoff = 1.0e-06) const
Returns true if matrix is all zeros.
Definition at line 292 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by MleAmSgmm2Accs::Check(), MleAmSgmmAccs::Check(), MleAmSgmm2Accs::CommitStatsForSpk(), MleAmSgmmAccs::CommitStatsForSpk(), main(), and kaldi::UnitTestSimpleForVec().
{
   Real abs_max = 0.0;
   for (MatrixIndexT i = 0; i < Dim(); i++)
     abs_max = std::max(std::abs(data_[i]), abs_max);
   return (abs_max <= cutoff);
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (VectorBase< Real >) protected
Real LogSumExp (Real prune = -1.0) const
Returns log(sum(exp())) without exp overflow If prune > 0.0, ignores terms less than the max - prune.
[Note: in future, if prune = 0.0, it will take the max. For now, use -1 if you don't want it to prune.]
Definition at line 745 of file kaldi-vector.cc.
References kaldi::Exp(), rnnlm::i, kaldi::kLogZeroDouble, kaldi::kLogZeroFloat, kaldi::kMinLogDiffDouble, kaldi::kMinLogDiffFloat, and kaldi::Log().
Referenced by AmSgmm::ComputeNormalizersNormalized(), IvectorExtractor::GetAcousticAuxfWeight(), LogisticRegression::GetLogPosteriors(), FullGmm::LogLikelihood(), DiagGmm::LogLikelihood(), DecodableAmDiagGmmRegtreeMllr::LogLikelihoodZeroBased(), main(), kaldi::UnitTestDiagGmm(), UnitTestFullGmm(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), MleAmSgmm2Updater::UpdatePhoneVectorsInternal(), MleAmSgmm2Updater::UpdateW(), MleAmSgmm2Updater::UpdateWGetStats(), MleSgmm2SpeakerAccs::UpdateWithU(), MleAmSgmmUpdaterMulti::UpdateWParallel(), MleAmSgmmUpdater::UpdateWParallel(), and MleAmSgmmUpdater::UpdateWSequential().
{
   Real sum;
   if (sizeof(sum) == 8) sum = kLogZeroDouble;
   else sum = kLogZeroFloat;
   Real max_elem = Max(), cutoff;
   if (sizeof(Real) == 4) cutoff = max_elem + kMinLogDiffFloat;
   else cutoff = max_elem + kMinLogDiffDouble;
   if (prune > 0.0 && max_elem - prune > cutoff) // explicit pruning...
     cutoff = max_elem - prune;
   double sum_relto_max_elem = 0.0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     BaseFloat f = data_[i];
     if (f >= cutoff)
       sum_relto_max_elem += Exp(f - max_elem);
   }
   return max_elem + Log(sum_relto_max_elem);
 }
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Definition at line 566 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by kaldi::nnet3::ComputeAccuracy(), kaldi::ComputeEarlyReverbEnergy(), kaldi::CuVectorUnitTestMax(), OptimizeLbfgs< Real >::DoStep(), FeatureTransformEstimate::EstimateInternal(), AmNnetSimple::Info(), kaldi::InitGmmFromRandomFrames(), SpMatrix< Real >::LimitCond(), main(), SpMatrix< Real >::MaxAbsEig(), kaldi::MaxAbsolute(), kaldi::nnet1::MomentStatistics(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::nnet2::PrintPriorDiagnostics(), kaldi::nnet3::PrintPriorDiagnostics(), OnlineNaturalGradient::SelfTest(), OnlinePreconditioner::SelfTest(), kaldi::SolveQuadraticMatrixProblem(), kaldi::SolveQuadraticProblem(), SpMatrix< Real >::SymPosSemiDefEig(), kaldi::TestVectorToPosteriorEntry(), kaldi::UnitTestMaxAbsEig(), kaldi::UnitTestMaxMin(), kaldi::UnitTestSparseVectorMax(), kaldi::UnitTestVectorMax(), and IvectorExtractorStats::UpdatePrior().
{
   Real ans = - std::numeric_limits<Real>::infinity();
   const Real *data = data_;
   MatrixIndexT i, dim = dim_;
   for (i = 0; i + 4 <= dim; i += 4) {
     Real a1 = data[i], a2 = data[i+1], a3 = data[i+2], a4 = data[i+3];
     if (a1 > ans || a2 > ans || a3 > ans || a4 > ans) {
       Real b1 = (a1 > a2 ? a1 : a2), b2 = (a3 > a4 ? a3 : a4);
       if (b1 > ans) ans = b1;
       if (b2 > ans) ans = b2;
     }
   }
   for (; i < dim; i++)
     if (data[i] > ans) ans = data[i];
   return ans;
 }
Real Max (MatrixIndexT * index) const
Returns the maximum value of any element, and the associated index.
Error if vector is empty.
Definition at line 584 of file kaldi-vector.cc.
References rnnlm::i, and KALDI_ERR.
{
   if (dim_ == 0) KALDI_ERR << "Empty vector";
   Real ans = - std::numeric_limits<Real>::infinity();
   MatrixIndexT index = 0;
   const Real *data = data_;
   MatrixIndexT i, dim = dim_;
   for (i = 0; i + 4 <= dim; i += 4) {
     Real a1 = data[i], a2 = data[i+1], a3 = data[i+2], a4 = data[i+3];
     if (a1 > ans || a2 > ans || a3 > ans || a4 > ans) {
       if (a1 > ans) { ans = a1; index = i; }
       if (a2 > ans) { ans = a2; index = i + 1; }
       if (a3 > ans) { ans = a3; index = i + 2; }
       if (a4 > ans) { ans = a4; index = i + 3; }
     }
   }
   for (; i < dim; i++)
     if (data[i] > ans) { ans = data[i]; index = i; }
   *index_out = index;
   return ans;
 }
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
Definition at line 606 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by OnlinePitchFeatureImpl::AcceptWaveform(), kaldi::ApplyHessianXformToGradient(), kaldi::ApplyInvHessianXformToChange(), kaldi::CuVectorUnitTestMin(), OptimizeLbfgs< Real >::DoStep(), kaldi::EBWUpdateGaussian(), kaldi::GetFeatureMeanAndVariance(), PldaEstimator::GetOutput(), AmNnet::Info(), AmNnetSimple::Info(), main(), SpMatrix< Real >::MaxAbsEig(), kaldi::MaxAbsolute(), MatrixBase< BaseFloat >::MinSingularValue(), kaldi::nnet1::MomentStatistics(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePitchFeatureImpl::RecomputeBacktraces(), OnlineNaturalGradient::SelfTest(), OnlinePreconditioner::SelfTest(), Nnet::SetLearningRates(), SpMatrix< Real >::SymPosSemiDefEig(), kaldi::UnitTestFloorUnit(), kaldi::UnitTestMaxAbsEig(), kaldi::UnitTestMaxMin(), kaldi::UnitTestVectorMin(), and IvectorExtractorStats::UpdatePrior().
{
   Real ans = std::numeric_limits<Real>::infinity();
   const Real *data = data_;
   MatrixIndexT i, dim = dim_;
   for (i = 0; i + 4 <= dim; i += 4) {
     Real a1 = data[i], a2 = data[i+1], a3 = data[i+2], a4 = data[i+3];
     if (a1 < ans || a2 < ans || a3 < ans || a4 < ans) {
       Real b1 = (a1 < a2 ? a1 : a2), b2 = (a3 < a4 ? a3 : a4);
       if (b1 < ans) ans = b1;
       if (b2 < ans) ans = b2;
     }
   }
   for (; i < dim; i++)
     if (data[i] < ans) ans = data[i];
   return ans;
 }
Real Min (MatrixIndexT * index) const
Returns the minimum value of any element, and the associated index.
Error if vector is empty.
Definition at line 624 of file kaldi-vector.cc.
References rnnlm::i, and KALDI_ERR.
{
   if (dim_ == 0) KALDI_ERR << "Empty vector";
   Real ans = std::numeric_limits<Real>::infinity();
   MatrixIndexT index = 0;
   const Real *data = data_;
   MatrixIndexT i, dim = dim_;
   for (i = 0; i + 4 <= dim; i += 4) {
     Real a1 = data[i], a2 = data[i+1], a3 = data[i+2], a4 = data[i+3];
     if (a1 < ans || a2 < ans || a3 < ans || a4 < ans) {
       if (a1 < ans) { ans = a1; index = i; }
       if (a2 < ans) { ans = a2; index = i + 1; }
       if (a3 < ans) { ans = a3; index = i + 2; }
       if (a4 < ans) { ans = a4; index = i + 3; }
     }
   }
   for (; i < dim; i++)
     if (data[i] < ans) { ans = data[i]; index = i; }
   *index_out = index;
   return ans;
 }
void MulElements (const VectorBase< Real > & v)
Multipy element-by-element by another vector.
Definition at line 941 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, rnnlm::i, and KALDI_ASSERT.
Referenced by RegtreeMllrDiagGmmAccs::AccumulateForGaussian(), RegtreeMllrDiagGmmAccs::AccumulateForGmm(), Plp::ComputeInternal(), EbwAmSgmm2Updater::ComputePhoneVecStats(), kaldi::Debias(), kaldi::ExtractWindow(), main(), DiagGmm::MergeKmeans(), kaldi::nnet1::MomentStatistics(), kaldi::SlidingWindowCmnInternal(), kaldi::SolveQuadraticProblem(), kaldi::UnitTestSimpleForVec(), and kaldi::UnitTestVector().
{
   KALDI_ASSERT(dim_ == v.dim_);
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] *= v.data_[i];
   }
 }
void MulElements (const VectorBase< OtherReal > & v)
Multipy element-by-element by another vector of different type.
Definition at line 958 of file kaldi-vector.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
{
   KALDI_ASSERT(dim_ == v.Dim());
   const OtherReal *other_ptr = v.Data();
   for (MatrixIndexT i = 0; i < dim_; i++) {
     data_[i] *= other_ptr[i];
   }
 }
void MulTp (const TpMatrix< Real > & M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
Definition at line 151 of file kaldi-vector.cc.
References kaldi::cblas_Xtpmv(), PackedMatrix< Real >::Data(), KALDI_ASSERT, and PackedMatrix< Real >::NumRows().
Referenced by VectorBase< Real >::AddTpVec(), FullGmm::Perturb(), FullGmm::Split(), kaldi::UnitTestCuVectorMulTp(), and kaldi::UnitTestMulTp().
{
   KALDI_ASSERT(M.NumRows() == dim_);
   cblas_Xtpmv(trans,M.Data(),M.NumRows(),data_,1);
 }
Real Norm (Real p) const
Compute the p-th norm of the vector.
Definition at line 508 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ASSERT, VectorBase< Real >::Norm(), and VectorBase< Real >::Scale().
Referenced by OptimizeLbfgs< Real >::AcceptStep(), VectorBase< Real >::ApproxEqual(), OptimizeLbfgs< Real >::ComputeHifNeeded(), SinusoidDetector::DetectSinusoid(), IvectorExtractor::GetIvectorDistribution(), PldaEstimator::GetOutput(), kaldi::GpsrBasic(), kaldi::GpsrBB(), main(), VectorBase< Real >::Norm(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OptimizeLbfgs< Real >::Restart(), Plda::TransformIvector(), kaldi::UnitTestGpsr(), kaldi::UnitTestLbfgs(), kaldi::UnitTestLinearCgd(), kaldi::UnitTestNorm(), kaldi::UnitTestSimpleForVec(), IvectorExtractorStats::UpdatePrior(), and IvectorExtractTask::~IvectorExtractTask().
{
   KALDI_ASSERT(p >= 0.0);
   Real sum = 0.0;
   if (p == 0.0) {
     for (MatrixIndexT i = 0; i < dim_; i++)
       if (data_[i] != 0.0) sum += 1.0;
     return sum;
   } else if (p == 1.0) {
     for (MatrixIndexT i = 0; i < dim_; i++)
       sum += std::abs(data_[i]);
     return sum;
   } else if (p == 2.0) {
     for (MatrixIndexT i = 0; i < dim_; i++)
       sum += data_[i] * data_[i];
     return std::sqrt(sum);
   } else {
     Real tmp;
     bool ok = true;
     for (MatrixIndexT i = 0; i < dim_; i++) {
       tmp = pow(std::abs(data_[i]), p);
       if (tmp == HUGE_VAL) // HUGE_VAL is what pow returns on error.
         ok = false;
       sum += tmp;
     }
     tmp = pow(sum, static_cast<Real>(1.0/p));
     KALDI_ASSERT(tmp != HUGE_VAL); // should not happen here.
     if (ok) {
       return tmp;
     } else {
       Real maximum = this->Max(), minimum = this->Min(),
           max_abs = std::max(maximum, -minimum);
       KALDI_ASSERT(max_abs > 0); // Or should not have reached here.
       Vector<Real> tmp(*this);
       tmp.Scale(1.0 / max_abs);
       return tmp.Norm(p) * max_abs;
     }
   }
 }
Real operator() (MatrixIndexT i) const inline
Indexing operator (const).
Definition at line 71 of file kaldi-vector.h.
{
     KALDI_PARANOID_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                  static_cast<UnsignedMatrixIndexT>(dim_));
     return *(data_ + i);
   }
Real& operator() (MatrixIndexT i) inline
Indexing operator (non-const).
Definition at line 78 of file kaldi-vector.h.
{
     KALDI_PARANOID_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                  static_cast<UnsignedMatrixIndexT>(dim_));
     return *(data_ + i);
   }
MatrixIndexT RandCategorical () const
This function returns a random index into this vector, chosen with probability proportional to the corresponding element.
Requires that this->Min() >= 0 and this->Sum() > 0.
Definition at line 310 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ASSERT, and kaldi::RandUniform().
Referenced by FullGmmNormal::Rand(), and kaldi::UnitTestRandCategorical().
{
   kaldi::RandomState rstate;
   Real sum = this->Sum();
   KALDI_ASSERT(this->Min() >= 0.0 && sum > 0.0);
   Real r = RandUniform(&rstate) * sum;
   Real *data = this->data_;
   MatrixIndexT dim = this->dim_;
   Real running_sum = 0.0;
   for (MatrixIndexT i = 0; i < dim; i++) {
     running_sum += data[i];
     if (r < running_sum) return i;
   }
   return dim_ - 1; // Should only happen if RandUniform()
                    // returns exactly 1, or due to roundoff.
 }
SubVector<Real> Range (const MatrixIndexT o, const MatrixIndexT l) inline
Returns a sub-vector of a vector (a range of elements).
Parameters
o [in] Origin, 0 < o < Dim()
l [in] Length 0 < l < Dim()-o
Returns
A SubVector object that aliases the data of the Vector object. See SubVector class for details
Definition at line 89 of file kaldi-vector.h.
Referenced by OnlineGenericBaseFeature< C >::AcceptWaveform(), RegtreeFmllrDiagGmmAccs::AccumulateForGaussian(), RegtreeFmllrDiagGmmAccs::AccumulateForGmm(), FmllrRawAccs::AccumulateFromPosteriors(), FmllrSgmmAccs::AccumulateFromPosteriors(), FmllrSgmm2Accs::AccumulateFromPosteriors(), VectorRandomizer::AddData(), kaldi::AddVectorsOfUnequalLength(), kaldi::AppendVector(), Fmpe::ApplyProjection(), Fmpe::ApplyProjectionReverse(), FmllrRawAccs::CommitSingleFrameStats(), FmllrDiagGmmAccs::CommitSingleFrameStats(), MelBanks::Compute(), BasisFmllrEstimate::ComputeAmDiagPrecond(), kaldi::ComputeEarlyReverbEnergy(), Sgmm2Project::ComputeLdaTransform(), kaldi::ConvolveSignals(), FmllrRawAccs::DataHasChanged(), OnlinePitchFeatureImpl::ExtractFrame(), CompressedAffineXformStats::ExtractOneG(), kaldi::ExtractWindow(), kaldi::FFTbasedBlockConvolveSignals(), kaldi::FFTbasedConvolveSignals(), FmllrDiagGmmAccs::FmllrDiagGmmAccs(), kaldi::FmllrInnerUpdate(), kaldi::GenerateDtmfTestCase(), Nnet::GetGradient(), IvectorExtractor::GetIvectorDistribution(), MultiSinusoidDetector::GetNextFrameOfSignal(), Nnet::GetParams(), LinearTransform::GetParams(), AffineTransform::GetParams(), ParallelComponent::GetParams(), TCNProjectionComponent::GetParams(), FramePoolingComponent::GetParams(), LstmProjectedStreams::GetParams(), TCNComponent::GetParams(), ConvolutionalComponent::GetParams(), Convolutional2DComponent::GetParams(), BLstmProjectedStreams::GetParams(), Nnet::GetWeights(), kaldi::GpsrCalcLinearCoeff(), kaldi::GpsrGradient(), kaldi::GpsrObjective(), FramePoolingComponent::InitData(), FmllrRawAccs::InitSingleFrameStats(), MelBanks::MelBanks(), kaldi::MergeFullGmm(), SoftmaxComponent::MixUp(), kaldi::RealFftInefficient(), Nnet::SetWeights(), FullGmm::Split(), DiagGmm::Split(), SpMatrix< Real >::TopEigs(), UnitTestLinearResample(), kaldi::UnitTestRange(), UnitTestVectorRandomizer(), Nnet::UnVectorize(), RepeatedAffineComponent::UnVectorize(), AffineComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), Convolutional1dComponent::UnVectorize(), VectorRandomizer::Value(), RepeatedAffineComponent::Vectorize(), AffineComponent::Vectorize(), BlockAffineComponent::Vectorize(), ConvolutionComponent::Vectorize(), and Convolutional1dComponent::Vectorize().
{
     return SubVector<Real>(*this, o, l);
   }
const SubVector<Real> Range (const MatrixIndexT o, const MatrixIndexT l) const inline
Returns a const sub-vector of a vector (a range of elements).
Parameters
o [in] Origin, 0 < o < Dim()
l [in] Length 0 < l < Dim()-o
Returns
A SubVector object that aliases the data of the Vector object. See SubVector class for details
Definition at line 98 of file kaldi-vector.h.
{
     return SubVector<Real>(*this, o, l);
   }
void Read (std::istream & in, bool binary, bool add = false)
Reads from C++ stream (option to add to existing contents).
Throws exception on failure
Definition at line 1059 of file kaldi-vector.cc.
References VectorBase< Real >::Dim(), KALDI_ERR, and Vector< Real >::Read().
Referenced by kaldi::operator>>().
{
   if (add) {
     Vector<Real> tmp(Dim());
     tmp.Read(is, binary, false);  // read without adding.
     if (this->Dim() != tmp.Dim()) {
       KALDI_ERR << "VectorBase::Read, size mismatch " << this->Dim()<<" vs. "<<tmp.Dim();
     }
     this->AddVec(1.0, tmp);
     return;
   } // now assume add == false.
   //  In order to avoid rewriting this, we just declare a Vector and
   // use it to read the data, then copy.
   Vector<Real> tmp;
   tmp.Read(is, binary, false);
   if (tmp.Dim() != Dim())
     KALDI_ERR << "VectorBase<Real>::Read, size mismatch "
               << Dim() << " vs. " << tmp.Dim();
   CopyFromVec(tmp);
 }
void ReplaceValue (Real orig, Real changed)
Set each element to y = (x == orig ? changed : x).
Definition at line 949 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by kaldi::UnitTestCuVectorReplaceValue(), and kaldi::UnitTestReplaceValue().
{
   Real *data = data_;
   for (MatrixIndexT i = 0; i < dim_; i++)
     if (data[i] == orig) data[i] = changed;
 }
void Scale (Real alpha)
Multiplies all elements by this constant.
Definition at line 936 of file kaldi-vector.cc.
References kaldi::cblas_Xscal().
Referenced by FmllrSgmmAccs::AccumulateForFmllrSubspace(), FmllrSgmm2Accs::AccumulateForFmllrSubspace(), FmllrDiagGmmAccs::AccumulateForGmm(), FmllrRawAccs::AccumulateForGmm(), RegtreeMllrDiagGmmAccs::AccumulateForGmm(), RegtreeFmllrDiagGmmAccs::AccumulateForGmm(), AccumAmDiagGmm::AccumulateForGmmTwofeats(), RegressionTree::BuildTree(), kaldi::ClusterGaussiansToUbm(), kaldi::ComputeAmGmmFeatureDeriv(), Fmpe::ComputeC(), kaldi::ComputeFeatureNormalizer(), kaldi::ComputeFeatureNormalizingTransform(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), Plp::ComputeInternal(), NnetCombiner::ComputeObjfAndDerivFromNnet(), EbwAmSgmm2Updater::ComputePhoneVecStats(), FmllrRawAccs::ConvertToSimpleStats(), kaldi::CuVectorUnitTestScale(), kaldi::Debias(), DeltaFeatures::DeltaFeatures(), MatrixBase< Real >::DestructiveSvd(), kaldi::DoReverberation(), kaldi::EBWUpdateGaussian(), BasisFmllrEstimate::EstimateFmllrBasis(), kaldi::FFTbasedBlockConvolveSignals(), kaldi::FFTbasedConvolveSignals(), kaldi::FmllrInnerUpdate(), kaldi::GenRandStats(), IvectorExtractor::GetAcousticAuxfVariance(), kaldi::GetFeatDeriv(), kaldi::GetFeatureMeanAndVariance(), PldaEstimator::GetOutput(), LdaEstimate::GetStats(), kaldi::GpsrBB(), NonlinearComponent::Info(), Rbm::InitData(), kaldi::unittest::InitRandDiagGmm(), kaldi::unittest::InitRandFullGmm(), kaldi::InitRandomGmm(), kaldi::IsmoothStatsDiagGmm(), main(), kaldi::MapDiagGmmUpdate(), FullGmm::Merge(), DiagGmm::merged_components_logdet(), FullGmm::MergedComponentsLogdet(), DiagGmm::MergeKmeans(), kaldi::MleDiagGmmUpdate(), kaldi::MleFullGmmUpdate(), TransitionModel::MleUpdate(), TransitionModel::MleUpdateShared(), VectorBase< Real >::Norm(), PdfPrior::PdfPrior(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), IvectorExtractorStats::PriorDiagnostics(), rand_diag_gmm(), kaldi::RealFft(), OnlinePitchFeatureImpl::RecomputeBacktraces(), DiagGmm::RemoveComponent(), FullGmm::RemoveComponent(), SgmmClusterable::Scale(), LdaEstimate::Scale(), IvectorExtractorUtteranceStats::Scale(), AccumFullGmm::Scale(), AccumDiagGmm::Scale(), VectorClusterable::Scale(), OnlineIvectorEstimationStats::Scale(), ShiftedDeltaFeatures::ShiftedDeltaFeatures(), kaldi::SlidingWindowCmnInternal(), AccumDiagGmm::SmoothStats(), kaldi::TestClusterKMeansVector(), kaldi::nnet3::TestNnetComponentUpdatable(), kaldi::TestVectorToPosteriorEntry(), SpMatrix< Real >::TopEigs(), Plda::TransformIvector(), kaldi::UnitTestAddDiagMat2(), kaldi::UnitTestAddDiagMatMat(), kaldi::UnitTestAddDiagVecMat(), kaldi::nnet2::UnitTestAmNnet(), kaldi::UnitTestComplexFft(), kaldi::UnitTestComplexFt(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), kaldi::UnitTestCuVectorAddVec(), UnitTestEstimateDiagGmm(), UnitTestEstimateFullGmm(), UnitTestEstimateLda(), kaldi::UnitTestEstimateMmieDiagGmm(), kaldi::UnitTestIo(), kaldi::UnitTestIoCross(), kaldi::UnitTestLbfgs(), kaldi::nnet2::UnitTestNnetDecodable(), kaldi::UnitTestNorm(), kaldi::UnitTestPldaEstimation(), kaldi::nnet3::UnitTestPreconditionDirectionsOnline(), kaldi::nnet2::UnitTestPreconditionDirectionsOnline(), kaldi::UnitTestRealFft(), kaldi::UnitTestSimpleForVec(), kaldi::UnitTestSplitRadixComplexFft(), kaldi::UnitTestSplitRadixRealFft(), kaldi::UnitTestVector(), HldaAccsDiagGmm::Update(), IvectorExtractorStats::UpdatePrior(), EbwAmSgmmUpdater::UpdateSubstateWeights(), EbwAmSgmm2Updater::UpdateSubstateWeights(), EbwAmSgmm2Updater::UpdateU(), MleAmSgmm2Updater::UpdateU(), MleAmSgmm2Updater::UpdateW(), MleSgmm2SpeakerAccs::UpdateWithU(), MleAmSgmmUpdaterMulti::UpdateWParallel(), MleAmSgmmUpdater::UpdateWParallel(), VectorClusterable::VectorClusterable(), NormalizeComponent::Write(), and NonlinearComponent::Write().
{
   cblas_Xscal(dim_, alpha, data_, 1);
 }
void Set (Real f)
Set all members of a vector to a specified value.
Definition at line 327 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by VectorBase< Real >::AddColSumMat(), VectorBase< Real >::AddRowSumMat(), MatrixBase< Real >::AddVecToCols(), MatrixBase< Real >::AddVecToRows(), kaldi::nnet2::CombineNnetsA(), kaldi::ComputeLocalCost(), PitchInterpolator::Forward(), kaldi::nnet2::GetInitialModel(), FastNnetCombiner::GetInitialModel(), NnetCombiner::GetInitialParameters(), FastNnetCombiner::GetInitialParams(), kaldi::nnet2::GetInitialScaleParams(), LogisticRegression::GetLogPosteriors(), kaldi::nnet2::GetUpdateDirection(), kaldi::GpsrCalcLinearCoeff(), OnlinePreconditionerSimple::InitDefault(), OnlineNaturalGradientSimple::InitDefault(), OnlineNaturalGradient::InitDefault(), OnlinePreconditioner::InitDefault(), main(), AmNnet::ResizeOutputLayer(), VectorClusterable::SetZero(), kaldi::SlidingWindowCmnInternal(), Plda::SmoothWithinClassCovariance(), VectorClusterable::Sub(), TestSgmm2FmllrAccsIO(), TestSgmm2FmllrSubspace(), TestSgmm2PreXform(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmPreXform(), kaldi::TrainOneIter(), kaldi::UnitTestAddVecToCols(), kaldi::UnitTestAddVecToRows(), UnitTestRegressionTree(), and kaldi::UnitTestSimpleForVec().
{
   // Why not use memset here?
   for (MatrixIndexT i = 0; i < dim_; i++) { data_[i] = f; }
 }
void SetRandn ()
Set vector to random normally-distributed noise.
Definition at line 300 of file kaldi-vector.cc.
References rnnlm::i, kaldi::RandGauss(), and kaldi::RandGauss2().
Referenced by kaldi::CuVectorUnitTestAddVecVec(), kaldi::GenerateDtmfTestCase(), LogisticRegression::MixUp(), SoftmaxComponent::MixUp(), PitchInterpolator::MultiplyObsProb(), FullGmm::Perturb(), kaldi::nnet2::PerturbTrainingExample(), FullGmmNormal::Rand(), FullGmm::Split(), kaldi::TestClusterKMeansVector(), kaldi::TestClusterUtilsVector(), kaldi::TestVectorToPosteriorEntry(), SpMatrix< Real >::TopEigs(), kaldi::UnitTestAddDiagVecMat(), kaldi::UnitTestAddMatDiagVec(), kaldi::UnitTestAddSinusoid(), kaldi::UnitTestAddVec2Sp(), kaldi::UnitTestAddVecToColsSpeed(), kaldi::UnitTestAddVecToRowsSpeed(), kaldi::UnitTestAddVecVec(), kaldi::nnet2::UnitTestAmNnet(), kaldi::UnitTestBlockConvolution(), kaldi::UnitTestConvolution(), kaldi::UnitTestCuMatrixAddVecVec(), kaldi::UnitTestCuSpMatrixAddVec2(), kaldi::UnitTestCuVectorAddTp(), kaldi::UnitTestCuVectorCopyFromVec(), kaldi::UnitTestCuVectorMulTp(), kaldi::UnitTestCuVectorReplaceValue(), kaldi::UnitTestFloorCeiling(), kaldi::UnitTestLinearCgd(), UnitTestLinearResample(), UnitTestLinearResample2(), kaldi::UnitTestMulTp(), kaldi::nnet2::UnitTestNnetDecodable(), kaldi::UnitTestPldaEstimation(), kaldi::nnet3::UnitTestPreconditionDirectionsOnline(), kaldi::nnet2::UnitTestPreconditionDirectionsOnline(), kaldi::UnitTestReplaceValue(), kaldi::UnitTestSinusoidDetectorNoisy(), kaldi::UnitTestSolve(), kaldi::UnitTestSparseVectorAddToVec(), kaldi::UnitTestSparseVectorMax(), kaldi::UnitTestSparseVectorSum(), kaldi::UnitTestSparseVectorVecSvec(), kaldi::nnet3::UnitTestSummarizeVector(), kaldi::UnitTestTriVecSolver(), kaldi::UnitTestVecmul(), kaldi::UnitTestVector(), kaldi::UnitTestVectorMax(), and kaldi::UnitTestVectorMin().
{
   kaldi::RandomState rstate;
   MatrixIndexT last = (Dim() % 2 == 1) ? Dim() - 1 : Dim();
   for (MatrixIndexT i = 0; i < last; i += 2) {
     kaldi::RandGauss2(data_ + i, data_ + i +1, &rstate);
   }
   if (Dim() != last) data_[last] = static_cast<Real>(kaldi::RandGauss(&rstate));
 }
void SetZero ()
Set vector to all zeros.
Definition at line 287 of file kaldi-vector.cc.
Referenced by MinimumBayesRisk::AccStats(), MleSgmm2SpeakerAccs::Clear(), MleSgmmSpeakerAccs::Clear(), FmllrDiagGmmAccs::CommitSingleFrameStats(), MleAmSgmm2Accs::CommitStatsForSpk(), MleAmSgmmAccs::CommitStatsForSpk(), OptimizeLbfgs< Real >::ComputeNewDirection(), AmSgmm::ComputeSmoothingTermsFromModel(), kaldi::ConvolveSignals(), SparseVector< Real >::CopyElementsToVec(), kaldi::DiagGmmToStats(), kaldi::EBWUpdateGaussian(), OnlinePitchFeatureImpl::ExtractFrame(), kaldi::FFTbasedBlockConvolveSignals(), FullGmm::GetComponentMean(), OnlineIvectorEstimationStats::GetIvector(), NnetCombiner::GetNnetParameters(), NnetCombiner::GetParamsDeriv(), kaldi::GpsrBasic(), FmllrRawAccs::InitSingleFrameStats(), FmllrDiagGmmAccs::InitSingleFrameStats(), FullGmm::Merge(), FullGmm::MergePreselect(), DeltaFeatures::Process(), ShiftedDeltaFeatures::Process(), AccumFullGmm::Read(), LdaEstimate::Read(), SgmmClusterable::SetZero(), AccumFullGmm::SetZero(), AccumDiagGmm::SetZero(), FmllrRawAccs::SetZero(), CuMatrixBase< Real >::SetZeroAboveDiag(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), MleAmSgmmUpdater::UpdateWSequential(), MleAmSgmmGlobalAccs::ZeroAccumulators(), and LdaEstimate::ZeroAccumulators().
{
   std::memset(data_, 0, dim_ * sizeof(Real));
 }
void Sigmoid (const VectorBase< Real > & src)
Sets each element of *this to the sigmoid function of the corresponding element of "src".
Definition at line 911 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, kaldi::Exp(), rnnlm::i, and KALDI_ASSERT.
Referenced by MatrixBase< Real >::Sigmoid().
{
   KALDI_ASSERT(dim_ == src.dim_);
   for (MatrixIndexT i = 0; i < dim_; i++) {
     Real x = src.data_[i];
     // We aim to avoid floating-point overflow here.
     if (x > 0.0) {
       x = 1.0 / (1.0 + Exp(-x));
     } else {
       Real ex = Exp(x);
       x = ex / (ex + 1.0);
     }
     data_[i] = x;
   }
 }
MatrixIndexT SizeInBytes () const inline
Returns the size in memory of the vector, in bytes.
Definition at line 62 of file kaldi-vector.h.
 { return (dim_*sizeof(Real)); }
void Solve (const TpMatrix< Real > & M, const MatrixTransposeType trans)
If trans == kNoTrans, solves M x = b, where b is the value of *this at input and x is the value of *this at output.
If trans == kTrans, solves M' x = b. Does not test for M being singular or near-singular, so test it before calling this routine.
Definition at line 158 of file kaldi-vector.cc.
References kaldi::cblas_Xtpsv(), PackedMatrix< Real >::Data(), KALDI_ASSERT, and PackedMatrix< Real >::NumRows().
Referenced by kaldi::UnitTestTriVecSolver().
{
   KALDI_ASSERT(M.NumRows() == dim_);
   cblas_Xtpsv(trans, M.Data(), M.NumRows(), data_, 1);
 }
Real Sum () const
Returns sum of the elements.
Definition at line 680 of file kaldi-vector.cc.
References rnnlm::i.
Referenced by OnlinePitchFeatureImpl::AcceptWaveform(), AccumAmDiagGmm::AccumulateFromPosteriors(), FmllrDiagGmmAccs::AccumulateFromPosteriors(), FmllrDiagGmmAccs::AccumulateFromPosteriorsPreselect(), IvectorExtractorStats::AuxfPerFrame(), Nnet::Check(), kaldi::ClusterGaussiansToUbm(), IvectorExtractorStats::CommitStatsForWPoint(), kaldi::nnet3::ComputeAccuracy(), kaldi::ComputeCorrelation(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), NnetCombiner::ComputeObjfAndDerivFromNnet(), EbwAmSgmm2Updater::ComputePhoneVecStats(), kaldi::ComputeVadEnergy(), OnlineNaturalGradient::ComputeWt1(), OnlinePreconditioner::ComputeWt1(), kaldi::CuVectorUnitTestCopyDiagFromMat(), Xent::Eval(), Mse::Eval(), kaldi::ExtractWindow(), DiagGmm::Generate(), kaldi::GenRandStats(), IvectorExtractor::GetAcousticAuxf(), IvectorExtractor::GetAcousticAuxfVariance(), IvectorExtractor::GetAuxf(), IvectorExtractor::GetIvectorDistWeight(), MultiSinusoidDetector::GetNextFrame(), LdaEstimate::GetStats(), AmNnet::Info(), AmNnetSimple::Info(), kaldi::unittest::InitRandDiagGmm(), kaldi::InitRandomGmm(), IvectorExtractorStats::IvectorVarianceDiagnostic(), kaldi::nnet3::KlDivergence(), kaldi::nnet2::KlDivergence(), AffineComponent::LimitRank(), main(), TransitionModel::MapUpdate(), TransitionModel::MapUpdateShared(), kaldi::MleFullGmmUpdate(), TransitionModel::MleUpdate(), TransitionModel::MleUpdateShared(), kaldi::nnet1::MomentStatistics(), SgmmClusterable::Normalizer(), IvectorExtractorUtteranceStats::NumFrames(), SgmmClusterable::Objf(), LimitRankClass::operator()(), PdfPrior::PdfPrior(), OnlineNaturalGradientSimple::PreconditionDirectionsCpu(), OnlinePreconditionerSimple::PreconditionDirectionsCpu(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), IvectorExtractorStats::PriorDiagnostics(), DiagGmm::RemoveComponent(), FullGmm::RemoveComponent(), MleAmSgmm2Updater::RenormalizeN(), MleAmSgmm2Updater::RenormalizeV(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), OnlineNaturalGradient::SelfTest(), OnlinePreconditioner::SelfTest(), CuVectorBase< Real >::Sum(), kaldi::nnet3::SummarizeVector(), LdaEstimate::TotCount(), kaldi::TraceMatMat(), kaldi::nnet2::UnitTestAmNnet(), kaldi::UnitTestDiagGmm(), kaldi::UnitTestEigSymmetric(), UnitTestFullGmm(), kaldi::nnet2::UnitTestNnetDecodable(), kaldi::UnitTestPosteriors(), kaldi::UnitTestRandCategorical(), kaldi::UnitTestRange(), kaldi::UnitTestResize(), kaldi::UnitTestSimpleForVec(), kaldi::UnitTestSparseVectorSum(), MleSgmm2SpeakerAccs::Update(), MleSgmmSpeakerAccs::Update(), IvectorExtractorStats::Update(), kaldi::UpdateEbwWeightsDiagGmm(), EbwAmSgmmUpdater::UpdateM(), EbwAmSgmm2Updater::UpdateM(), EbwAmSgmmUpdater::UpdateN(), EbwAmSgmm2Updater::UpdateN(), MleSgmm2SpeakerAccs::UpdateNoU(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), IvectorExtractorStats::UpdateProjections(), OnlinePitchFeatureImpl::UpdateRemainder(), EbwAmSgmmUpdater::UpdateSubstateWeights(), EbwAmSgmm2Updater::UpdateSubstateWeights(), MleAmSgmm2Updater::UpdateSubstateWeights(), EbwAmSgmm2Updater::UpdateU(), MleAmSgmm2Updater::UpdateU(), IvectorExtractorStats::UpdateVariances(), MleAmSgmmUpdaterMulti::UpdateVars(), EbwAmSgmm2Updater::UpdateVars(), MleAmSgmm2Updater::UpdateVars(), MleAmSgmmUpdater::UpdateVars(), EbwAmSgmm2Updater::UpdateW(), MleAmSgmm2Updater::UpdateW(), IvectorExtractorStats::UpdateWeights(), MleSgmm2SpeakerAccs::UpdateWithU(), EbwAmSgmmUpdater::UpdateWParallel(), MleAmSgmm2Accs::~MleAmSgmm2Accs(), and MleAmSgmmAccs::~MleAmSgmmAccs().
{
   double sum = 0.0;
   for (MatrixIndexT i = 0; i < dim_; i++) { sum += data_[i]; }
   return sum;
 }
Real SumLog () const
Returns sum of the logs of the elements.
More efficient than just taking log of each. Will return NaN if any elements are negative.
Definition at line 687 of file kaldi-vector.cc.
References rnnlm::i, and kaldi::Log().
Referenced by Plda::LogLikelihoodRatio(), main(), and GaussClusterable::Objf().
{
   double sum_log = 0.0;
   double prod = 1.0;
   for (MatrixIndexT i = 0; i < dim_; i++) {
     prod *= data_[i];
     // Possible future work (arnab): change these magic values to pre-defined
     // constants
     if (prod < 1.0e-10 || prod > 1.0e+10) {
       sum_log += Log(prod);
       prod = 1.0;
     }
   }
   if (prod != 1.0) sum_log += Log(prod);
   return sum_log;
 }
void Tanh (const VectorBase< Real > & src)
Sets each element of *this to the tanh of the corresponding element of "src".
Definition at line 873 of file kaldi-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, kaldi::Exp(), rnnlm::i, and KALDI_ASSERT.
Referenced by MatrixBase< Real >::Tanh().
{
   KALDI_ASSERT(dim_ == src.dim_);
   for (MatrixIndexT i = 0; i < dim_; i++) {
     Real x = src.data_[i];
     if (x > 0.0) {
       Real inv_expx = Exp(-x);
       x = -1.0 + 2.0 / (1.0 + inv_expx * inv_expx);
     } else {
       Real inv_expx = Exp(x);
       x = 1.0 - 2.0 / (1.0 + inv_expx * inv_expx);
     }
     data_[i] = x;
   }
 }
void Write (std::ostream & Out, bool binary) const
Writes to C++ stream (option to write in binary).
Definition at line 1198 of file kaldi-vector.cc.
References rnnlm::i, KALDI_ASSERT, KALDI_ERR, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by main(), kaldi::UnitTestIo(), kaldi::UnitTestIoCross(), UnitTestRegressionTree(), AmNnet::Write(), NnetExample::Write(), AmNnetSimple::Write(), SgmmClusterable::Write(), AccumFullGmm::Write(), LdaEstimate::Write(), SgmmFmllrGlobalParams::Write(), Sgmm2FmllrGlobalParams::Write(), Plda::Write(), TransitionModel::Write(), FullGmm::Write(), VectorClusterable::Write(), NormalizeComponent::Write(), DiagGmm::Write(), DiscriminativeNnetExample::Write(), IvectorExtractor::Write(), CuVector< Real >::Write(), OnlineIvectorEstimationStats::Write(), NonlinearComponent::Write(), and IvectorExtractorStats::Write().
{
   if (!os.good()) {
     KALDI_ERR << "Failed to write vector to stream: stream not good";
   }
   if (binary) {
     std::string my_token = (sizeof(Real) == 4 ? "FV" : "DV");
     WriteToken(os, binary, my_token);
     int32 size = Dim();  // make the size 32-bit on disk.
     KALDI_ASSERT(Dim() == (MatrixIndexT) size);
     WriteBasicType(os, binary, size);
     os.write(reinterpret_cast<const char*>(Data()), sizeof(Real) * size);
   } else {
     os << " [ ";
     for (MatrixIndexT i = 0; i < Dim(); i++)
       os << (*this)(i) << " ";
     os << "]\n";
   }
   if (!os.good())
     KALDI_ERR << "Failed to write vector to stream";
 }
Friends And Related Function Documentation
friend class CuVector< Real > friend
Definition at line 349 of file kaldi-vector.h.
friend class CuVectorBase< Real > friend
Definition at line 348 of file kaldi-vector.h.
friend class VectorBase< double > friend
Definition at line 346 of file kaldi-vector.h.
friend class VectorBase< float > friend
Definition at line 347 of file kaldi-vector.h.
Member Data Documentation
Real* data_ protected
data memory area
Definition at line 373 of file kaldi-vector.h.
Referenced by VectorBase< Real >::AddVec(), VectorBase< Real >::AddVec2(), VectorBase< Real >::AddVecDivVec(), VectorBase< Real >::AddVecVec(), VectorBase< Real >::ApproxEqual(), VectorBase< Real >::CopyFromVec(), VectorBase< BaseFloat >::Data(), VectorBase< Real >::DivElements(), VectorBase< Real >::MulElements(), VectorBase< BaseFloat >::operator()(), Vector< Real >::Resize(), VectorBase< Real >::Sigmoid(), SubVector< Real >::SubVector(), CuVector< Real >::Swap(), Vector< Real >::Swap(), and VectorBase< Real >::Tanh().
MatrixIndexT dim_ protected
dimension of vector
Definition at line 375 of file kaldi-vector.h.
Referenced by VectorBase< Real >::AddMatSvec(), VectorBase< Real >::AddMatVec(), VectorBase< Real >::AddSpVec(), VectorBase< Real >::AddTpVec(), VectorBase< Real >::AddVec(), VectorBase< Real >::AddVec2(), VectorBase< Real >::AddVecDivVec(), VectorBase< Real >::AddVecVec(), VectorBase< Real >::ApproxEqual(), CuVector< Real >::CuVector(), VectorBase< BaseFloat >::Dim(), VectorBase< Real >::DivElements(), VectorBase< Real >::MulElements(), VectorBase< BaseFloat >::operator()(), VectorBase< Real >::Sigmoid(), VectorBase< BaseFloat >::SizeInBytes(), SubVector< Real >::SubVector(), CuVector< Real >::Swap(), Vector< Real >::Swap(), and VectorBase< Real >::Tanh().
The documentation for this class was generated from the following files:
matrix/kaldi-vector.h
matrix/kaldi-vector.cc
cudamatrix/cu-matrix.cc
cudamatrix/cu-vector.h