Kaldi: RepeatedAffineComponent Class Reference
RepeatedAffineComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
RepeatedAffineComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
const CuVector< BaseFloat > & BiasParams ()
const CuMatrix< BaseFloat > & LinearParams ()
RepeatedAffineComponent (const RepeatedAffineComponent &other)
void Init (int32 input_dim, int32 output_dim, int32 num_repeats, BaseFloat param_stddev, BaseFloat bias_mean, BaseFloat bias_stddev)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Protected Member Functions
virtual void Update (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
virtual void SetNaturalGradientConfigs ()
const RepeatedAffineComponent & operator= (const RepeatedAffineComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
int32 num_repeats_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 392 of file nnet-simple-component.h.
Constructor & Destructor Documentation
RepeatedAffineComponent () inline
Definition at line 401 of file nnet-simple-component.h.
Referenced by RepeatedAffineComponent::Copy().
 { } // use Init to really initialize.
RepeatedAffineComponent (const RepeatedAffineComponent & other) explicit
Definition at line 936 of file nnet-simple-component.cc.
                                                                                           :
     UpdatableComponent(component),
     linear_params_(component.linear_params_),
     bias_params_(component.bias_params_),
     num_repeats_(component.num_repeats_) {}
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from Component.
Definition at line 948 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), RepeatedAffineComponent::bias_params_, KALDI_ASSERT, and RepeatedAffineComponent::linear_params_.
{
   const RepeatedAffineComponent *other =
       dynamic_cast<const RepeatedAffineComponent *>(&other_in);
   KALDI_ASSERT(other != NULL);
   linear_params_.AddMat(alpha, other->linear_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1077 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::ColRange(), kaldi::DeletePointers(), rnnlm::i, kaldi::kNoTrans, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and RepeatedAffineComponent::Update().
{
   RepeatedAffineComponent *to_update = dynamic_cast<RepeatedAffineComponent*>(to_update_in);
   // Propagate the derivative back to the input.
   // add with coefficient 1.0 since property kBackpropAdds is true.
   // If we wanted to add with coefficient 0.0 we'd need to zero the
   // in_deriv, in case of infinities.
   if (in_deriv) {
     int32 block_rows = linear_params_.NumRows();
         int32 block_cols = linear_params_.NumCols();
         std::vector<CuSubMatrix<BaseFloat> *> in_deriv_batch, out_deriv_batch,
         linear_params_batch;
         CuSubMatrix<BaseFloat>* params_elem =
             new CuSubMatrix<BaseFloat>(linear_params_.ColRange(0, block_cols));
     //split the out_deriv and the in_deriv mat into blocks.
     for (int i = 0; i < num_repeats_; i++) {
       in_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(in_deriv->ColRange(
                                    i * block_cols, block_cols)));
       out_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(out_deriv.ColRange(
                                     i * block_rows, block_rows)));
       linear_params_batch.push_back(params_elem);
     }
     AddMatMatBatched<BaseFloat>(1.0, in_deriv_batch, out_deriv_batch, kNoTrans,
                                 linear_params_batch, kNoTrans, 1.0);
     delete params_elem;
     DeletePointers(&in_deriv_batch);
     DeletePointers(&out_deriv_batch);
   }
   // Next update the model (must do this 2nd so the derivatives we propagate are
   // accurate, in case this == to_update_in.)
   if (to_update != NULL)
     to_update->Update(in_value, out_deriv);
 }
const CuVector<BaseFloat>& BiasParams () inline
Definition at line 434 of file nnet-simple-component.h.
References RepeatedAffineComponent::bias_params_.
 { return bias_params_; }
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Reimplemented in NaturalGradientRepeatedAffineComponent.
Definition at line 984 of file nnet-simple-component.cc.
References RepeatedAffineComponent::RepeatedAffineComponent().
{
   RepeatedAffineComponent *ans = new RepeatedAffineComponent(*this);
   return ans;
 }
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 989 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, kaldi::kTrans, RepeatedAffineComponent::linear_params_, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const RepeatedAffineComponent *other =
       dynamic_cast<const RepeatedAffineComponent*>(&other_in);
   return TraceMatMat(linear_params_, other->linear_params_, kTrans)
                      + VecVec(bias_params_, other->bias_params_);
 }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 975 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, UpdatableComponent::Info(), RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", num-repeats=" << num_repeats_;
   PrintParameterStats(stream, "linear-params", linear_params_);
   PrintParameterStats(stream, "bias", bias_params_, true);
   return stream.str();
 }
void Init (int32 input_dim, int32 output_dim, int32 num_repeats, BaseFloat param_stddev, BaseFloat bias_mean, BaseFloat bias_stddev)
Definition at line 996 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Add(), RepeatedAffineComponent::bias_params_, KALDI_ASSERT, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), RepeatedAffineComponent::SetNaturalGradientConfigs(), CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
Referenced by RepeatedAffineComponent::InitFromConfig().
{
   KALDI_ASSERT(input_dim % num_repeats == 0 && output_dim % num_repeats == 0);
   linear_params_.Resize(output_dim / num_repeats, input_dim / num_repeats);
   bias_params_.Resize(output_dim / num_repeats);
   num_repeats_ = num_repeats;
   KALDI_ASSERT(output_dim > 0 && input_dim > 0 && param_stddev >= 0.0);
   linear_params_.SetRandn(); // sets to random normally distributed noise.
   linear_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
   bias_params_.Add(bias_mean);
   SetNaturalGradientConfigs();
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1013 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), RepeatedAffineComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ASSERT, KALDI_ERR, RepeatedAffineComponent::num_repeats_, ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   int32 num_repeats = num_repeats_;
   int32 input_dim = -1, output_dim = -1;
   InitLearningRatesFromConfig(cfl);
   ok = cfl->GetValue("num-repeats", &num_repeats) && ok;
   ok = cfl->GetValue("input-dim", &input_dim) && ok;
   ok = cfl->GetValue("output-dim", &output_dim) && ok;
   KALDI_ASSERT(input_dim % num_repeats == 0 &&
                "num-repeats must divide input-dim");
   KALDI_ASSERT(output_dim % num_repeats == 0 &&
                "num-repeats must divide output-dim");
   BaseFloat param_stddev = 1.0 / std::sqrt(input_dim / num_repeats),
       bias_mean = 0.0, bias_stddev = 0.0;
   cfl->GetValue("param-stddev", &param_stddev);
   cfl->GetValue("bias-mean", &bias_mean);
   cfl->GetValue("bias-stddev", &bias_stddev);
   Init(input_dim, output_dim,
        num_repeats, param_stddev, bias_mean, bias_stddev);
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
                   << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 395 of file nnet-simple-component.h.
References RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, and CuMatrixBase< Real >::NumCols().
 { return linear_params_.NumCols() * num_repeats_; }
const CuMatrix<BaseFloat>& LinearParams () inline
Definition at line 435 of file nnet-simple-component.h.
References RepeatedAffineComponent::linear_params_.
 { return linear_params_; }
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 1221 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, CuVectorBase< Real >::Dim(), RepeatedAffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by RepeatedAffineComponent::UnVectorize(), and RepeatedAffineComponent::Vectorize().
{
   // Note: unlike AffineComponent, InputDim() & OutputDim() are not used here and below,
   // for they are multipled by num_repeats_.
   return linear_params_.NumCols() * linear_params_.NumRows() + bias_params_.Dim();
 }
const RepeatedAffineComponent& operator= (const RepeatedAffineComponent & other) protected
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 396 of file nnet-simple-component.h.
References RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, and CuMatrixBase< Real >::NumRows().
 { return linear_params_.NumRows() * num_repeats_; }
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 966 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), RepeatedAffineComponent::bias_params_, RepeatedAffineComponent::linear_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_linear_params(linear_params_);
   temp_linear_params.SetRandn();
   linear_params_.AddMat(stddev, temp_linear_params);
   CuVector<BaseFloat> temp_bias_params(bias_params_);
   temp_bias_params.SetRandn();
   bias_params_.AddVec(stddev, temp_bias_params);
 }
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Implements Component.
Definition at line 1039 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyRowsFromVec(), kaldi::DeletePointers(), CuVectorBase< Real >::Dim(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, kaldi::kUndefined, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   // No need for asserts as they'll happen within the matrix operations.
   int32 block_rows = linear_params_.NumRows();
   int32 block_cols = linear_params_.NumCols();
   {
     // copy bias_params_ to each row  of *out
     CuVector<BaseFloat> tmp_repeated_bias(num_repeats_ * bias_params_.Dim(),
                                           kUndefined);
     CuSubMatrix<BaseFloat> tmp_bias_mat(tmp_repeated_bias.Data(), num_repeats_,
                                         bias_params_.Dim(), bias_params_.Dim());
     tmp_bias_mat.CopyRowsFromVec(bias_params_);
     out->CopyRowsFromVec(tmp_repeated_bias);
   }
   std::vector<CuSubMatrix<BaseFloat> *> in_batch, out_batch,
       linear_params_batch;
   CuSubMatrix<BaseFloat>* params_elem =
       new CuSubMatrix<BaseFloat>(linear_params_.ColRange(0, block_cols));
   //split the in and out mat into blocks.
   for (int i = 0; i < num_repeats_; i++) {
     in_batch.push_back(new CuSubMatrix<BaseFloat>(in.ColRange(
                            i * block_cols, block_cols)));
     out_batch.push_back(new CuSubMatrix<BaseFloat>(
                             out->ColRange(i * block_rows, block_rows)));
     linear_params_batch.push_back(params_elem);
   }
   AddMatMatBatched<BaseFloat>(1.0, out_batch, in_batch, kNoTrans,
                               linear_params_batch, kTrans, 1.0);
   delete params_elem;
   DeletePointers(&in_batch);
   DeletePointers(&out_batch);
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 403 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kLinearInParameters, kaldi::nnet3::kSimpleComponent, and kaldi::nnet3::kUpdatableComponent.
{
     return kSimpleComponent|kUpdatableComponent|kLinearInParameters|
              kBackpropNeedsInput|kBackpropAdds;
   }
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 1191 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), kaldi::ReadBasicType(), UpdatableComponent::ReadUpdatableCommon(), RepeatedAffineComponent::SetNaturalGradientConfigs(), and RepeatedAffineComponent::Type().
{
   // This Read function also works for NaturalGradientRepeatedAffineComponent.
   ReadUpdatableCommon(is, binary);  // read opening tag and learning rate.
   ExpectToken(is, binary, "<NumRepeats>");
   ReadBasicType(is, binary, &num_repeats_);
   ExpectToken(is, binary, "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   ExpectToken(is, binary, "<IsGradient>");
   ReadBasicType(is, binary, &is_gradient_);
   ExpectToken(is, binary, std::string("</") + Type() + std::string(">"));
   SetNaturalGradientConfigs();
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from Component.
Definition at line 943 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, RepeatedAffineComponent::linear_params_, CuVectorBase< Real >::Scale(), and CuMatrixBase< Real >::Scale().
{
   linear_params_.Scale(scale);
   bias_params_.Scale(scale);
 }
virtual void SetNaturalGradientConfigs () inline protected virtual
Reimplemented in NaturalGradientRepeatedAffineComponent.
Definition at line 451 of file nnet-simple-component.h.
Referenced by RepeatedAffineComponent::Init(), and RepeatedAffineComponent::Read().
 { }
void SetZero (bool treat_as_gradient) virtual
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
Implements UpdatableComponent.
Definition at line 956 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, UpdatableComponent::is_gradient_, UpdatableComponent::learning_rate_, RepeatedAffineComponent::linear_params_, CuVectorBase< Real >::SetZero(), and CuMatrixBase< Real >::SetZero().
{
   if (treat_as_gradient) {
     learning_rate_ = 1.0;  // don't call SetLearningRate, that would apply the
                            // learning rate factor.
     is_gradient_ = true;
   }
   linear_params_.SetZero();
   bias_params_.SetZero();
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Reimplemented in NaturalGradientRepeatedAffineComponent.
Definition at line 402 of file nnet-simple-component.h.
Referenced by RepeatedAffineComponent::Read(), and RepeatedAffineComponent::Write().
 { return "RepeatedAffineComponent"; }
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 1234 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, CuVectorBase< Real >::CopyFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), VectorBase< Real >::Dim(), CuVectorBase< Real >::Dim(), KALDI_ASSERT, RepeatedAffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), RepeatedAffineComponent::NumParameters(), CuMatrixBase< Real >::NumRows(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   linear_params_.CopyRowsFromVec(params.Range(0, linear_params_.NumCols() * linear_params_.NumRows()));
   bias_params_.CopyFromVec(params.Range(linear_params_.NumCols() * linear_params_.NumRows(),
                                         bias_params_.Dim()));
 }
void Update (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) protected virtual
Reimplemented in NaturalGradientRepeatedAffineComponent.
Definition at line 1120 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddRowSumMat(), RepeatedAffineComponent::bias_params_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::Data(), kaldi::DeletePointers(), CuVectorBase< Real >::Dim(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Row(), CuMatrixBase< Real >::RowRange(), and CuMatrixBase< Real >::Stride().
Referenced by RepeatedAffineComponent::Backprop().
{
   int32 block_rows = linear_params_.NumRows();
   int32 block_cols = linear_params_.NumCols();
   std::vector<CuSubMatrix<BaseFloat> *> in_value_batch,
       out_deriv_batch, linear_params_deriv_batch;
   CuMatrix<BaseFloat> linear_params_deriv_repeated(
       block_rows * num_repeats_, block_cols);
   for (int i = 0; i < num_repeats_; i++) {
     in_value_batch.push_back(new CuSubMatrix<BaseFloat>(in_value.ColRange(
         i * block_cols, block_cols)));
     out_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(out_deriv.ColRange(
         i * block_rows, block_rows)));
     linear_params_deriv_batch.push_back(
         new CuSubMatrix<BaseFloat>(linear_params_deriv_repeated.RowRange(
             i * block_rows, block_rows)));
   }
   AddMatMatBatched<BaseFloat>(learning_rate_,
                               linear_params_deriv_batch,
                               out_deriv_batch, kTrans,
                               in_value_batch, kNoTrans, 0.0);
   { // sum up the repeated blocks of pieces of derivative (from
     // linear_params_deriv_repeated) into linear_params_.  We do this without
     // the use of loops by means of a little fakery, viewing
     // linear_params_deriv_repeated as a matrix with a larger stride than it
     // really has to sum up its rows.  This may generate some spurious
     // valgrind/memcheck warnings due to accessing the memory in between rows
     // of a matrix that has been allocated using cudaMallocPitch.
     // view linear_params_deriv_repeated as a matrix where each row
     // corresponds to one repeat.
     // usage of linear_params_deriv_repeated.Stride() instead of
     // linear_params_.Stride() is important here. CUDA does not guarantee
     // that two matrices of the same number of columns
     // (linear_params_deriv_repeated and linear_params_) have the same stride.
     // i.e., we cannot reliably do:
     // KALDI_ASSERT(linear_params_.Stride() == linear_params_deriv_repeated.Stride())
     int32 size_as_vector =
         (linear_params_.NumRows() - 1) * linear_params_deriv_repeated.Stride() +
         linear_params_.NumCols(),
         stride_as_matrix = linear_params_.NumRows() * linear_params_deriv_repeated.Stride();
     CuSubMatrix<BaseFloat> linear_params_deriv_repeated_as_mat(
         linear_params_deriv_repeated.Data(), num_repeats_,
         size_as_vector, stride_as_matrix);
     // add all remaining rows to the first row, of
     // linear_params_deriv_repeated_as_mat
     if (num_repeats_ > 1)
       linear_params_deriv_repeated_as_mat.Row(0).AddRowSumMat(
           1.0, linear_params_deriv_repeated_as_mat.RowRange(1,
                                                             num_repeats_ - 1));
     linear_params_.AddMat(1.0, linear_params_deriv_repeated.RowRange(
         0, linear_params_.NumRows()));
   }
   { // deal with the derivative w.r.t. the bias.
     CuVector<BaseFloat> repeated_bias_deriv(
         num_repeats_ * bias_params_.Dim());
     repeated_bias_deriv.AddRowSumMat(1.0, out_deriv, 0.0);
     CuSubMatrix<BaseFloat> bias_deriv_mat(repeated_bias_deriv.Data(),
                                           num_repeats_, bias_params_.Dim(), // num rows, num cols
                                           bias_params_.Dim()); // stride
     bias_params_.AddRowSumMat(learning_rate_,
                               bias_deriv_mat);
   }
   DeletePointers(&in_value_batch);
   DeletePointers(&out_deriv_batch);
   DeletePointers(&linear_params_deriv_batch);
 }
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 1227 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, VectorBase< Real >::Dim(), CuVectorBase< Real >::Dim(), KALDI_ASSERT, RepeatedAffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), RepeatedAffineComponent::NumParameters(), CuMatrixBase< Real >::NumRows(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   params->Range(0, linear_params_.NumCols() * linear_params_.NumRows()).CopyRowsFromMat(linear_params_);
   params->Range(linear_params_.NumCols() * linear_params_.NumRows(),
                 bias_params_.Dim()).CopyFromVec(bias_params_);
 }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 1206 of file nnet-simple-component.cc.
References RepeatedAffineComponent::bias_params_, UpdatableComponent::is_gradient_, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, RepeatedAffineComponent::Type(), CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   // This Write function also works for NaturalGradientRepeatedAffineComponent.
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<NumRepeats>");
   WriteBasicType(os, binary, num_repeats_);
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   // write closing token.
   WriteToken(os, binary, std::string("</") + Type() + std::string(">"));
 }
Member Data Documentation
CuVector<BaseFloat> bias_params_ protected
Definition at line 455 of file nnet-simple-component.h.
Referenced by RepeatedAffineComponent::Add(), RepeatedAffineComponent::BiasParams(), RepeatedAffineComponent::DotProduct(), RepeatedAffineComponent::Info(), RepeatedAffineComponent::Init(), RepeatedAffineComponent::NumParameters(), RepeatedAffineComponent::PerturbParams(), RepeatedAffineComponent::Propagate(), RepeatedAffineComponent::Read(), RepeatedAffineComponent::Scale(), RepeatedAffineComponent::SetZero(), RepeatedAffineComponent::UnVectorize(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), RepeatedAffineComponent::Vectorize(), and RepeatedAffineComponent::Write().
CuMatrix<BaseFloat> linear_params_ protected
Definition at line 454 of file nnet-simple-component.h.
Referenced by RepeatedAffineComponent::Add(), RepeatedAffineComponent::Backprop(), RepeatedAffineComponent::DotProduct(), RepeatedAffineComponent::Info(), RepeatedAffineComponent::Init(), RepeatedAffineComponent::InputDim(), RepeatedAffineComponent::LinearParams(), RepeatedAffineComponent::NumParameters(), RepeatedAffineComponent::OutputDim(), RepeatedAffineComponent::PerturbParams(), RepeatedAffineComponent::Propagate(), RepeatedAffineComponent::Read(), RepeatedAffineComponent::Scale(), NaturalGradientRepeatedAffineComponent::SetNaturalGradientConfigs(), RepeatedAffineComponent::SetZero(), RepeatedAffineComponent::UnVectorize(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), RepeatedAffineComponent::Vectorize(), and RepeatedAffineComponent::Write().
int32 num_repeats_ protected
Definition at line 456 of file nnet-simple-component.h.
Referenced by RepeatedAffineComponent::Backprop(), RepeatedAffineComponent::Info(), RepeatedAffineComponent::Init(), RepeatedAffineComponent::InitFromConfig(), RepeatedAffineComponent::InputDim(), RepeatedAffineComponent::OutputDim(), RepeatedAffineComponent::Propagate(), RepeatedAffineComponent::Read(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), and RepeatedAffineComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc