Kaldi: AffineComponent Class Reference
AffineComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
AffineComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void SetParams (const VectorBase< BaseFloat > &bias, const MatrixBase< BaseFloat > &linear)
const CuVector< BaseFloat > & BiasParams ()
const CuMatrix< BaseFloat > & LinearParams ()
AffineComponent (const AffineComponent &other)
AffineComponent (const CuMatrixBase< BaseFloat > &linear_params, const CuVectorBase< BaseFloat > &bias_params, BaseFloat learning_rate)
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev)
void Init (std::string matrix_filename)
virtual void Resize (int32 input_dim, int32 output_dim)
Component * CollapseWithNext (const AffineComponent &next) const
Component * CollapseWithNext (const FixedAffineComponent &next) const
Component * CollapseWithNext (const FixedScaleComponent &next) const
Component * CollapseWithPrevious (const FixedAffineComponent &prev) const
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Protected Member Functions
virtual void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
virtual void UpdateSimple (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const AffineComponent & operator= (const AffineComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Friends
class SoftmaxComponent
class NaturalGradientAffineComponent
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 297 of file nnet-simple-component.h.
Constructor & Destructor Documentation
AffineComponent () inline
Definition at line 307 of file nnet-simple-component.h.
Referenced by AffineComponent::Copy().
 { } // use Init to really initialize.
AffineComponent (const AffineComponent & other) explicit
Definition at line 672 of file nnet-simple-component.cc.
                                                                 :
     UpdatableComponent(component),
     linear_params_(component.linear_params_),
     bias_params_(component.bias_params_) { }
AffineComponent (const CuMatrixBase< BaseFloat > & linear_params, const CuVectorBase< BaseFloat > & bias_params, BaseFloat learning_rate)
Definition at line 677 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Dim(), KALDI_ASSERT, CuMatrixBase< Real >::NumRows(), and UpdatableComponent::SetLearningRate().
                                                          :
     linear_params_(linear_params),
     bias_params_(bias_params) {
   SetLearningRate(learning_rate);
   KALDI_ASSERT(linear_params.NumRows() == bias_params.Dim()&&
                bias_params.Dim() != 0);
 }
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 664 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), AffineComponent::bias_params_, KALDI_ASSERT, and AffineComponent::linear_params_.
{
   const AffineComponent *other =
       dynamic_cast<const AffineComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   linear_params_.AddMat(alpha, other->linear_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 808 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), UpdatableComponent::is_gradient_, kaldi::kNoTrans, AffineComponent::linear_params_, AffineComponent::Update(), and AffineComponent::UpdateSimple().
{
   AffineComponent *to_update = dynamic_cast<AffineComponent*>(to_update_in);
   // Propagate the derivative back to the input.
   // add with coefficient 1.0 since property kBackpropAdds is true.
   // If we wanted to add with coefficient 0.0 we'd need to zero the
   // in_deriv, in case of infinities.
   if (in_deriv)
     in_deriv->AddMatMat(1.0, out_deriv, kNoTrans, linear_params_, kNoTrans,
                         1.0);
   if (to_update != NULL) {
     // Next update the model (must do this 2nd so the derivatives we propagate
     // are accurate, in case this == to_update_in.)
     if (to_update->is_gradient_)
       to_update->UpdateSimple(in_value, out_deriv);
     else  // the call below is to a virtual function that may be re-implemented
       to_update->Update(debug_info, in_value, out_deriv);  // by child classes.
   }
 }
const CuVector<BaseFloat>& BiasParams () inline
Definition at line 347 of file nnet-simple-component.h.
References AffineComponent::bias_params_.
 { return bias_params_; }
Component * CollapseWithNext (const AffineComponent & next) const
Definition at line 873 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddMatVec(), AffineComponent::bias_params_, AffineComponent::Copy(), AffineComponent::InputDim(), KALDI_ASSERT, kaldi::kNoTrans, AffineComponent::linear_params_, AffineComponent::OutputDim(), and CuMatrix< Real >::Resize().
{
   AffineComponent *ans = dynamic_cast<AffineComponent*>(this->Copy());
   KALDI_ASSERT(ans != NULL);
   // Note: it's possible that "ans" is really of a derived type such
   // as AffineComponentPreconditioned, but this will still work.
   // the "copy" call will copy things like learning rates, "alpha" value
   // for preconditioned component, etc.
   ans->linear_params_.Resize(next_component.OutputDim(), InputDim());
   ans->bias_params_ = next_component.bias_params_;
   ans->linear_params_.AddMatMat(1.0, next_component.linear_params_, kNoTrans,
                                 this->linear_params_, kNoTrans, 0.0);
   ans->bias_params_.AddMatVec(1.0, next_component.linear_params_, kNoTrans,
                               this->bias_params_, 1.0);
   return ans;
 }
Component * CollapseWithNext (const FixedAffineComponent & next) const
Definition at line 891 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddMatVec(), FixedAffineComponent::bias_params_, FixedAffineComponent::Copy(), AffineComponent::InputDim(), KALDI_ASSERT, kaldi::kNoTrans, FixedAffineComponent::linear_params_, FixedAffineComponent::OutputDim(), and CuMatrix< Real >::Resize().
{
   // If at least one was non-updatable, make the whole non-updatable.
   FixedAffineComponent *ans =
       dynamic_cast<FixedAffineComponent*>(next_component.Copy());
   KALDI_ASSERT(ans != NULL);
   ans->linear_params_.Resize(next_component.OutputDim(), InputDim());
   ans->bias_params_ = next_component.bias_params_;
   ans->linear_params_.AddMatMat(1.0, next_component.linear_params_, kNoTrans,
                                 this->linear_params_, kNoTrans, 0.0);
   ans->bias_params_.AddMatVec(1.0, next_component.linear_params_, kNoTrans,
                               this->bias_params_, 1.0);
   return ans;
 }
Component * CollapseWithNext (const FixedScaleComponent & next) const
Definition at line 907 of file nnet-simple-component.cc.
References AffineComponent::Copy(), FixedScaleComponent::InputDim(), KALDI_ASSERT, AffineComponent::OutputDim(), and FixedScaleComponent::scales_.
{
   KALDI_ASSERT(this->OutputDim() == next_component.InputDim());
   AffineComponent *ans =
       dynamic_cast<AffineComponent*>(this->Copy());
   KALDI_ASSERT(ans != NULL);
   ans->linear_params_.MulRowsVec(next_component.scales_);
   ans->bias_params_.MulElements(next_component.scales_);
   return ans;
 }
Component * CollapseWithPrevious (const FixedAffineComponent & prev) const
Definition at line 919 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddMatVec(), AffineComponent::bias_params_, FixedAffineComponent::bias_params_, FixedAffineComponent::Copy(), FixedAffineComponent::InputDim(), KALDI_ASSERT, kaldi::kNoTrans, AffineComponent::linear_params_, FixedAffineComponent::linear_params_, AffineComponent::OutputDim(), and CuMatrix< Real >::Resize().
{
   // If at least one was non-updatable, make the whole non-updatable.
   FixedAffineComponent *ans =
       dynamic_cast<FixedAffineComponent*>(prev_component.Copy());
   KALDI_ASSERT(ans != NULL);
   ans->linear_params_.Resize(this->OutputDim(), prev_component.InputDim());
   ans->bias_params_ = this->bias_params_;
   ans->linear_params_.AddMatMat(1.0, this->linear_params_, kNoTrans,
                                 prev_component.linear_params_, kNoTrans, 0.0);
   ans->bias_params_.AddMatVec(1.0, this->linear_params_, kNoTrans,
                               prev_component.bias_params_, 1.0);
   return ans;
 }
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 724 of file nnet-simple-component.cc.
References AffineComponent::AffineComponent().
Referenced by AffineComponent::CollapseWithNext().
{
   AffineComponent *ans = new AffineComponent(*this);
   return ans;
 }
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 729 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, kaldi::kTrans, AffineComponent::linear_params_, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const AffineComponent *other =
       dynamic_cast<const AffineComponent*>(&other_in);
   return TraceMatMat(linear_params_, other->linear_params_, kTrans)
       + VecVec(bias_params_, other->bias_params_);
 }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 716 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, UpdatableComponent::Info(), AffineComponent::linear_params_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info();
   PrintParameterStats(stream, "linear-params", linear_params_);
   PrintParameterStats(stream, "bias", bias_params_, true);
   return stream.str();
 }
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev)
Definition at line 736 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, AffineComponent::linear_params_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
Referenced by AffineComponent::InitFromConfig().
{
   linear_params_.Resize(output_dim, input_dim);
   bias_params_.Resize(output_dim);
   KALDI_ASSERT(output_dim > 0 && input_dim > 0 && param_stddev >= 0.0);
   linear_params_.SetRandn(); // sets to random normally distributed noise.
   linear_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
 }
void Init (std::string matrix_filename)
Definition at line 747 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, AffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Range(), kaldi::ReadKaldiObject(), CuVector< Real >::Resize(), and CuMatrix< Real >::Resize().
{
   CuMatrix<BaseFloat> mat;
   ReadKaldiObject(matrix_filename, &mat); // will abort on failure.
   KALDI_ASSERT(mat.NumCols() >= 2);
   int32 input_dim = mat.NumCols() - 1, output_dim = mat.NumRows();
   linear_params_.Resize(output_dim, input_dim);
   bias_params_.Resize(output_dim);
   linear_params_.CopyFromMat(mat.Range(0, output_dim, 0, input_dim));
   bias_params_.CopyColFromMat(mat, input_dim);
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 758 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), AffineComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), AffineComponent::InputDim(), KALDI_ASSERT, KALDI_ERR, AffineComponent::OutputDim(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   std::string matrix_filename;
   int32 input_dim = -1, output_dim = -1;
   InitLearningRatesFromConfig(cfl);
   if (cfl->GetValue("matrix", &matrix_filename)) {
     Init(matrix_filename);
     if (cfl->GetValue("input-dim", &input_dim))
       KALDI_ASSERT(input_dim == InputDim() &&
                    "input-dim mismatch vs. matrix.");
     if (cfl->GetValue("output-dim", &output_dim))
       KALDI_ASSERT(output_dim == OutputDim() &&
                    "output-dim mismatch vs. matrix.");
   } else {
     ok = ok && cfl->GetValue("input-dim", &input_dim);
     ok = ok && cfl->GetValue("output-dim", &output_dim);
     BaseFloat param_stddev = 1.0 / std::sqrt(input_dim),
         bias_stddev = 1.0;
     cfl->GetValue("param-stddev", &param_stddev);
     cfl->GetValue("bias-stddev", &bias_stddev);
     Init(input_dim, output_dim,
          param_stddev, bias_stddev);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 301 of file nnet-simple-component.h.
References AffineComponent::linear_params_, and CuMatrixBase< Real >::NumCols().
Referenced by AffineComponent::CollapseWithNext(), AffineComponent::InitFromConfig(), NaturalGradientAffineComponent::InitFromConfig(), AffineComponent::NumParameters(), AffineComponent::UnVectorize(), and AffineComponent::Vectorize().
 { return linear_params_.NumCols(); }
const CuMatrix<BaseFloat>& LinearParams () inline
Definition at line 348 of file nnet-simple-component.h.
References AffineComponent::linear_params_.
 { return linear_params_; }
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 857 of file nnet-simple-component.cc.
References AffineComponent::InputDim(), and AffineComponent::OutputDim().
Referenced by AffineComponent::UnVectorize(), and AffineComponent::Vectorize().
{
   return (InputDim() + 1) * OutputDim();
 }
const AffineComponent& operator= (const AffineComponent & other) protected
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 302 of file nnet-simple-component.h.
References AffineComponent::linear_params_, and CuMatrixBase< Real >::NumRows().
Referenced by AffineComponent::CollapseWithNext(), AffineComponent::CollapseWithPrevious(), AffineComponent::InitFromConfig(), NaturalGradientAffineComponent::InitFromConfig(), AffineComponent::NumParameters(), AffineComponent::UnVectorize(), and AffineComponent::Vectorize().
 { return linear_params_.NumRows(); }
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 706 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), AffineComponent::bias_params_, AffineComponent::linear_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_linear_params(linear_params_);
   temp_linear_params.SetRandn();
   linear_params_.AddMat(stddev, temp_linear_params);
   CuVector<BaseFloat> temp_bias_params(bias_params_);
   temp_bias_params.SetRandn();
   bias_params_.AddVec(stddev, temp_bias_params);
 }
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Implements Component.
Definition at line 791 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), AffineComponent::bias_params_, CuMatrixBase< Real >::CopyRowsFromVec(), kaldi::kNoTrans, kaldi::kTrans, and AffineComponent::linear_params_.
{
   // No need for asserts as they'll happen within the matrix operations.
   out->CopyRowsFromVec(bias_params_); // copies bias_params_ to each row
   // of *out.
   out->AddMatMat(1.0, in, kNoTrans, linear_params_, kTrans, 1.0);
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 309 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kLinearInParameters, kaldi::nnet3::kSimpleComponent, and kaldi::nnet3::kUpdatableComponent.
{
     return kSimpleComponent|kUpdatableComponent|kLinearInParameters|
         kBackpropNeedsInput|kBackpropAdds;
   }
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 835 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, AffineComponent::linear_params_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), kaldi::ReadBasicType(), and UpdatableComponent::ReadUpdatableCommon().
{
   ReadUpdatableCommon(is, binary);  // read opening tag and learning rate.
   ExpectToken(is, binary, "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   ExpectToken(is, binary, "<IsGradient>");
   ReadBasicType(is, binary, &is_gradient_);
   ExpectToken(is, binary, "</AffineComponent>");
 }
void Resize (int32 input_dim, int32 output_dim) virtual
Reimplemented in NaturalGradientAffineComponent.
Definition at line 658 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, AffineComponent::linear_params_, CuVector< Real >::Resize(), and CuMatrix< Real >::Resize().
{
   KALDI_ASSERT(input_dim > 0 && output_dim > 0);
   bias_params_.Resize(output_dim);
   linear_params_.Resize(output_dim, input_dim);
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 653 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, AffineComponent::linear_params_, CuVectorBase< Real >::Scale(), and CuMatrixBase< Real >::Scale().
{
   linear_params_.Scale(scale);
   bias_params_.Scale(scale);
 }
void SetParams (const VectorBase< BaseFloat > & bias, const MatrixBase< BaseFloat > & linear) virtual
Definition at line 699 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, CuVectorBase< Real >::Dim(), KALDI_ASSERT, AffineComponent::linear_params_, and CuMatrixBase< Real >::NumRows().
{
   bias_params_ = bias;
   linear_params_ = linear;
   KALDI_ASSERT(bias_params_.Dim() == linear_params_.NumRows());
 }
void SetZero (bool treat_as_gradient) virtual
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
Implements UpdatableComponent.
Definition at line 689 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, UpdatableComponent::is_gradient_, UpdatableComponent::learning_rate_, AffineComponent::linear_params_, CuVectorBase< Real >::SetZero(), and CuMatrixBase< Real >::SetZero().
{
   if (treat_as_gradient) {
     learning_rate_ = 1.0;  // don't call SetLearningRate, that would apply the
                            // learning rate factor.
     is_gradient_ = true;
   }
   linear_params_.SetZero();
   bias_params_.SetZero();
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 308 of file nnet-simple-component.h.
 { return "AffineComponent"; }
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 866 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, CuVectorBase< Real >::CopyFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), VectorBase< Real >::Dim(), AffineComponent::InputDim(), KALDI_ASSERT, AffineComponent::linear_params_, AffineComponent::NumParameters(), AffineComponent::OutputDim(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   linear_params_.CopyRowsFromVec(params.Range(0, InputDim() * OutputDim()));
   bias_params_.CopyFromVec(params.Range(InputDim() * OutputDim(),
                                         OutputDim()));
 }
virtual void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) inline protected virtual
Reimplemented in NaturalGradientAffineComponent.
Definition at line 375 of file nnet-simple-component.h.
References AffineComponent::UpdateSimple().
Referenced by AffineComponent::Backprop().
{
     UpdateSimple(in_value, out_deriv);
   }
void UpdateSimple (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) protected virtual
Definition at line 801 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddRowSumMat(), AffineComponent::bias_params_, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, and AffineComponent::linear_params_.
Referenced by AffineComponent::Backprop(), and AffineComponent::Update().
{
   bias_params_.AddRowSumMat(learning_rate_, out_deriv, 1.0);
   linear_params_.AddMatMat(learning_rate_, out_deriv, kTrans,
                            in_value, kNoTrans, 1.0);
 }
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 860 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, VectorBase< Real >::Dim(), AffineComponent::InputDim(), KALDI_ASSERT, AffineComponent::linear_params_, AffineComponent::NumParameters(), AffineComponent::OutputDim(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   params->Range(0, InputDim() * OutputDim()).CopyRowsFromMat(linear_params_);
   params->Range(InputDim() * OutputDim(),
                 OutputDim()).CopyFromVec(bias_params_);
 }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Reimplemented in NaturalGradientAffineComponent.
Definition at line 846 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, UpdatableComponent::is_gradient_, AffineComponent::linear_params_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   WriteToken(os, binary, "</AffineComponent>");
 }
Friends And Related Function Documentation
friend class NaturalGradientAffineComponent friend
Definition at line 372 of file nnet-simple-component.h.
friend class SoftmaxComponent friend
Definition at line 298 of file nnet-simple-component.h.
Member Data Documentation
CuVector<BaseFloat> bias_params_ protected
Definition at line 389 of file nnet-simple-component.h.
Referenced by AffineComponent::Add(), NaturalGradientAffineComponent::Add(), AffineComponent::BiasParams(), AffineComponent::CollapseWithNext(), AffineComponent::CollapseWithPrevious(), AffineComponent::DotProduct(), AffineComponent::Info(), NaturalGradientAffineComponent::Info(), AffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::PerturbParams(), AffineComponent::Propagate(), AffineComponent::Read(), NaturalGradientAffineComponent::Read(), AffineComponent::Resize(), NaturalGradientAffineComponent::Resize(), AffineComponent::Scale(), NaturalGradientAffineComponent::Scale(), AffineComponent::SetParams(), AffineComponent::SetZero(), AffineComponent::UnVectorize(), NaturalGradientAffineComponent::Update(), AffineComponent::UpdateSimple(), AffineComponent::Vectorize(), AffineComponent::Write(), and NaturalGradientAffineComponent::Write().
CuMatrix<BaseFloat> linear_params_ protected
Definition at line 388 of file nnet-simple-component.h.
Referenced by AffineComponent::Add(), NaturalGradientAffineComponent::Add(), AffineComponent::Backprop(), AffineComponent::CollapseWithNext(), AffineComponent::CollapseWithPrevious(), AffineComponent::DotProduct(), AffineComponent::Info(), NaturalGradientAffineComponent::Info(), AffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::InputDim(), AffineComponent::LinearParams(), AffineComponent::OutputDim(), AffineComponent::PerturbParams(), AffineComponent::Propagate(), AffineComponent::Read(), NaturalGradientAffineComponent::Read(), AffineComponent::Resize(), NaturalGradientAffineComponent::Resize(), AffineComponent::Scale(), NaturalGradientAffineComponent::Scale(), AffineComponent::SetParams(), AffineComponent::SetZero(), AffineComponent::UnVectorize(), NaturalGradientAffineComponent::Update(), AffineComponent::UpdateSimple(), AffineComponent::Vectorize(), AffineComponent::Write(), and NaturalGradientAffineComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc