Kaldi: OnlineCacheFeature Class Reference
OnlineCacheFeature Class Reference
OnlineFeatureExtraction
This feature type can be used to cache its input, to avoid repetition of computation in a multi-pass decoding context.
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
virtual ~OnlineCacheFeature ()
void ClearCache ()
OnlineCacheFeature (OnlineFeatureInterface *src)
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Attributes
OnlineFeatureInterface * src_
std::vector< Vector< BaseFloat > * > cache_
Detailed Description
This feature type can be used to cache its input, to avoid repetition of computation in a multi-pass decoding context.
Definition at line 485 of file online-feature.h.
Constructor & Destructor Documentation
virtual ~OnlineCacheFeature () inline virtual
Definition at line 497 of file online-feature.h.
References OnlineCacheFeature::ClearCache().
 { ClearCache(); }
OnlineCacheFeature (OnlineFeatureInterface * src) inline explicit
Definition at line 504 of file online-feature.h.
 : src_(src) { }
Member Function Documentation
void ClearCache ()
Definition at line 487 of file online-feature.cc.
References OnlineCacheFeature::cache_, and rnnlm::i.
Referenced by kaldi::GetOutput(), and OnlineCacheFeature::~OnlineCacheFeature().
{
   for (size_t i = 0; i < cache_.size(); i++)
     delete cache_[i];
   cache_.resize(0);
 }
virtual int32 Dim () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 487 of file online-feature.h.
References OnlineFeatureInterface::Dim(), and OnlineCacheFeature::src_.
Referenced by OnlineCacheFeature::GetFrame().
 { return src_->Dim(); }
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 472 of file online-feature.cc.
References OnlineCacheFeature::cache_, VectorBase< Real >::CopyFromVec(), OnlineCacheFeature::Dim(), OnlineFeatureInterface::GetFrame(), KALDI_ASSERT, and OnlineCacheFeature::src_.
Referenced by kaldi::GetOutput().
{
   KALDI_ASSERT(frame >= 0);
   if (static_cast<size_t>(frame) < cache_.size() && cache_[frame] != NULL) {
     feat->CopyFromVec(*(cache_[frame]));
   } else {
     if (static_cast<size_t>(frame) >= cache_.size())
       cache_.resize(frame + 1, NULL);
     int32 dim = this->Dim();
     cache_[frame] = new Vector<BaseFloat>(dim);
     // The following call will crash if frame "frame" is not ready.
     src_->GetFrame(frame, cache_[frame]);
     feat->CopyFromVec(*(cache_[frame]));
   }
 }
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 489 of file online-feature.h.
References OnlineFeatureInterface::IsLastFrame(), and OnlineCacheFeature::src_.
Referenced by kaldi::GetOutput().
{
     return src_->IsLastFrame(frame);
   }
virtual int32 NumFramesReady () const inline virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 493 of file online-feature.h.
References OnlineFeatureInterface::NumFramesReady(), and OnlineCacheFeature::src_.
 { return src_->NumFramesReady(); }
Member Data Documentation
std::vector<Vector<BaseFloat>* > cache_ private
Definition at line 508 of file online-feature.h.
Referenced by OnlineCacheFeature::ClearCache(), and OnlineCacheFeature::GetFrame().
OnlineFeatureInterface* src_ private
Definition at line 507 of file online-feature.h.
Referenced by OnlineCacheFeature::Dim(), OnlineCacheFeature::GetFrame(), OnlineCacheFeature::IsLastFrame(), and OnlineCacheFeature::NumFramesReady().
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc