Kaldi: Input Class Reference
Input Class Reference
"Classes for opening streams"
#include <kaldi-io.h>
Public Member Functions
Input (const std::string &rxfilename, bool *contents_binary=NULL)
The normal constructor.
Input ()
bool Open (const std::string &rxfilename, bool *contents_binary=NULL)
bool OpenTextMode (const std::string &rxfilename)
bool IsOpen ()
void Close ()
std::istream & Stream ()
~Input ()
Private Member Functions
bool OpenInternal (const std::string &rxfilename, bool file_binary, bool *contents_binary)
KALDI_DISALLOW_COPY_AND_ASSIGN (Input)
Private Attributes
InputImplBase * impl_
Detailed Description
Definition at line 188 of file kaldi-io.h.
Constructor & Destructor Documentation
Input (const std::string & rxfilename, bool * contents_binary = NULL)
The normal constructor.
Opens the stream in binary mode. Equivalent to calling the default constructor followed by Open(); then, if binary != NULL, it calls ReadHeader(), putting the output in "binary"; it throws on error.
Definition at line 733 of file kaldi-io.cc.
References KALDI_ERR, Input::Open(), and kaldi::PrintableRxfilename().
                                                      : impl_(NULL) {
   if (!Open(rxfilename, binary)) {
     KALDI_ERR << "Error opening input stream "
               << PrintableRxfilename(rxfilename);
   }
 }
Input () inline
Definition at line 196 of file kaldi-io.h.
 : impl_(NULL) {}
~Input ()
Definition at line 798 of file kaldi-io.cc.
References Input::Close(), and Input::impl_.
 { if (impl_) Close(); }
Member Function Documentation
void Close ()
Definition at line 740 of file kaldi-io.cc.
References Input::impl_.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Close(), RandomAccessTableReaderArchiveImplBase< Holder >::CloseInternal(), Nnet::Init(), LinearTransform::InitData(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), SequentialTableReaderScriptImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::Open(), Input::OpenInternal(), PdfPrior::PdfPrior(), Nnet::Read(), and Input::~Input().
                   {
   if (impl_) {
     delete impl_;
     impl_ = NULL;
   }
 }
bool IsOpen () inline
Definition at line 34 of file kaldi-io-inl.h.
References Input::impl_.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Close(), RandomAccessTableReaderArchiveImplBase< Holder >::CloseInternal(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), Input::OpenInternal(), and Input::Stream().
                    {
   return impl_ != NULL;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (Input) private
bool Open (const std::string & rxfilename, bool * contents_binary = NULL) inline
Definition at line 26 of file kaldi-io-inl.h.
References Input::OpenInternal().
Referenced by RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), Input::Input(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), SequentialTableReaderScriptImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::Open(), RandomAccessTableReaderArchiveImplBase< Holder >::Open(), and kaldi::ReadScriptFile().
{
   return OpenInternal(rxfilename, true, binary);
 }
bool OpenInternal (const std::string & rxfilename, bool file_binary, bool * contents_binary) private
Definition at line 747 of file kaldi-io.cc.
References kaldi::ClassifyRxfilename(), Input::Close(), Input::impl_, kaldi::InitKaldiInputStream(), Input::IsOpen(), KALDI_WARN, kaldi::kFileInput, kaldi::kOffsetFileInput, kaldi::kPipeInput, kaldi::kStandardInput, InputImplBase::MyType(), InputImplBase::Open(), kaldi::PrintableRxfilename(), and InputImplBase::Stream().
Referenced by Input::Open(), and Input::OpenTextMode().
{
   InputType type = ClassifyRxfilename(rxfilename);
   if (IsOpen()) {
     // May have to close the stream first.
     if (type == kOffsetFileInput && impl_->MyType() == kOffsetFileInput) {
       // We want to use the same object to Open... this is in case
       // the files are the same, so we can just seek.
       if (!impl_->Open(rxfilename, file_binary)) {  // true is binary mode--
         // always open in binary.
         delete impl_;
         impl_ = NULL;
         return false;
       }
       // read the binary header, if requested.
       if (contents_binary != NULL)
         return InitKaldiInputStream(impl_->Stream(), contents_binary);
       else
         return true;
     } else {
       Close();
       // and fall through to code below which actually opens the file.
     }
   }
   if (type ==  kFileInput) {
     impl_ = new FileInputImpl();
   } else if (type == kStandardInput) {
     impl_ = new StandardInputImpl();
   } else if (type == kPipeInput) {
     impl_ = new PipeInputImpl();
   } else if (type == kOffsetFileInput) {
     impl_ = new OffsetFileInputImpl();
   } else {  // type == kNoInput
     KALDI_WARN << "Invalid input filename format "<<
         PrintableRxfilename(rxfilename);
     return false;
   }
   if (!impl_->Open(rxfilename, file_binary)) {  // true is binary mode--
     // always read in binary.
     delete impl_;
     impl_ = NULL;
     return false;
   }
   if (contents_binary != NULL)
     return InitKaldiInputStream(impl_->Stream(), contents_binary);
   else
     return true;
 }
bool OpenTextMode (const std::string & rxfilename) inline
Definition at line 30 of file kaldi-io-inl.h.
References Input::OpenInternal().
Referenced by SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), SequentialTableReaderArchiveImpl< Holder >::Open(), RandomAccessTableReaderArchiveImplBase< Holder >::Open(), PdfPrior::PdfPrior(), kaldi::ReadIntegerVectorSimple(), and kaldi::ReadIntegerVectorVectorSimple().
{
   return OpenInternal(rxfilename, false, NULL);
 }
std::istream & Stream ()
Definition at line 801 of file kaldi-io.cc.
References Input::impl_, Input::IsOpen(), KALDI_ERR, and InputImplBase::Stream().
Referenced by CopyExcludedFeats(), CopyIncludedFeats(), kaldi::GetUtterancePairs(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), Nnet::Init(), kaldi::InitAmGmmFromOld(), LinearTransform::InitData(), FixedAffineComponent::InitFromConfig(), FixedLinearComponent::InitFromString(), FixedAffineComponent::InitFromString(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), main(), SequentialTableReaderArchiveImpl< Holder >::Next(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), PdfPrior::PdfPrior(), kaldi::PrepareMap(), LangModelFst::Read(), Nnet::Read(), fst::ReadFstKaldi(), kaldi::ReadIntegerVectorSimple(), kaldi::ReadIntegerVectorVectorSimple(), kaldi::ReadKaldiObject(), kaldi::ReadNetwork(), ReadNetwork(), RandomAccessTableReaderArchiveImplBase< Holder >::ReadNextObject(), kaldi::ReadScriptFile(), kaldi::ReadSharedPhonesList(), kaldi::ReadSymbolList(), test_io(), TestAmDiagGmmAccsIO(), TestAmDiagGmmIO(), kaldi::TestBuildTreeStatsIo(), fst::TestContextFst(), kaldi::TestEventTypeIo(), kaldi::TestFmpe(), kaldi::TestGenRandContextDependency(), TestMllrAccsIO(), kaldi::TestSetOfNumbers(), TestSgmm2AccsIO(), TestSgmm2FmllrAccsIO(), TestSgmm2IO(), TestSgmmFmllrAccsIO(), TestSgmmIO(), TestUpdateAndAccsIO(), kaldi::UnitTestDiagGmm(), UnitTestEstimateDiagGmm(), UnitTestFullGmm(), kaldi::nnet2::UnitTestGenericComponentInternal(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), kaldi::UnitTestRegtreeFmllrDiagGmm(), and WordBoundaryInfo::WordBoundaryInfo().
{
   if (!IsOpen()) KALDI_ERR << "Input::Stream(), not open.";
   return impl_->Stream();
 }
Member Data Documentation
InputImplBase* impl_ private
Definition at line 232 of file kaldi-io.h.
Referenced by Input::Close(), Input::IsOpen(), Input::OpenInternal(), Input::Stream(), and Input::~Input().
The documentation for this class was generated from the following files:
util/kaldi-io.h
util/kaldi-io-inl.h
util/kaldi-io.cc