Kaldi: CuSparseMatrix< Real > Class Template Reference
CuSparseMatrix< Real > Class Template Reference
#include <matrix-common.h>
Public Member Functions
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
MatrixIndexT NumElements () const
template<typename OtherReal >
void CopyToMat (CuMatrixBase< OtherReal > *dest, MatrixTransposeType trans=kNoTrans) const
Real Sum () const
Real FrobeniusNorm () const
MatrixElement< Real > * Data ()
const MatrixElement< Real > * Data () const
CuSparseMatrix< Real > & operator= (const SparseMatrix< Real > &smat)
Copy from CPU-based matrix.
CuSparseMatrix< Real > & operator= (const CuSparseMatrix< Real > &smat)
Copy from possibly-GPU-based matrix.
template<typename OtherReal >
void CopyFromSmat (const SparseMatrix< OtherReal > &smat)
Copy from CPU-based matrix.
template<typename OtherReal >
void CopyToSmat (SparseMatrix< OtherReal > *smat) const
Copy to CPU-based matrix.
void CopyElementsToVec (CuVectorBase< Real > *vec) const
Copy elements to CuVector.
void Swap (SparseMatrix< Real > *smat)
Swap with CPU-based matrix.
void Swap (CuSparseMatrix< Real > *smat)
Swap with possibly-CPU-based matrix.
void SetRandn (BaseFloat zero_prob)
Sets up to a pseudo-randomly initialized matrix, with each element zero with probability zero_prob and else normally distributed- mostly for purposes of testing.
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
CuSparseMatrix (const SparseMatrix< Real > &smat)
~CuSparseMatrix ()
Protected Member Functions
const SparseMatrix< Real > & Mat () const
SparseMatrix< Real > & Mat ()
Private Attributes
std::vector< SparseVector< Real > > cpu_rows_
MatrixIndexT num_rows_
MatrixIndexT num_cols_
CuArray< MatrixElement< Real > > elements_
Friends
class CuMatrixBase< float >
class CuMatrixBase< double >
class CuMatrixBase< Real >
class CuVectorBase< float >
class CuVectorBase< double >
class CuVectorBase< Real >
Real TraceMatSmat (const CuMatrixBase< Real > &A, const CuSparseMatrix< Real > &B, MatrixTransposeType trans)
Detailed Description
template<typename Real>
class kaldi::CuSparseMatrix< Real >
Definition at line 70 of file matrix-common.h.
Constructor & Destructor Documentation
CuSparseMatrix (const SparseMatrix< Real > & smat) inline explicit
Definition at line 118 of file cu-sparse-matrix.h.
References CuSparseMatrix< Real >::CopyFromSmat().
{
     this->CopyFromSmat(smat);
   }
~CuSparseMatrix () inline
Definition at line 122 of file cu-sparse-matrix.h.
 { }
Member Function Documentation
void CopyElementsToVec (CuVectorBase< Real > * vec) const
Copy elements to CuVector.
It is the caller's responsibility to resize <*vec>.
Definition at line 210 of file cu-sparse-matrix.cc.
References CuVectorBase< Real >::CopyFromVec(), CuVectorBase< Real >::Data(), CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and kaldi::kUndefined.
{
   KALDI_ASSERT(vec != NULL);
   KALDI_ASSERT(this->NumElements() == vec->Dim());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     cublas_copy(GetCublasHandle(),
                 this->NumElements(),
                 &(this->elements_.Data()->weight),
                 static_cast<size_t>(sizeof(MatrixElement<Real>) / sizeof(Real)),
                 vec->Data(), 1);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vector<Real> tmp(this->NumElements(), kUndefined);
     Mat().CopyElementsToVec(&tmp);
     vec->CopyFromVec(tmp);
   }
 }
template void CopyFromSmat (const SparseMatrix< OtherReal > & smat)
Copy from CPU-based matrix.
We will add the transpose option later when it is necessary.
Definition at line 141 of file cu-sparse-matrix.cc.
References MatrixElement< Real >::column, SparseMatrix< Real >::Data(), rnnlm::i, rnnlm::j, SparseMatrix< Real >::NumCols(), SparseMatrix< Real >::NumRows(), MatrixElement< Real >::row, and MatrixElement< Real >::weight.
Referenced by CuSparseMatrix< Real >::CuSparseMatrix().
{
   num_rows_ = smat.NumRows();
   num_cols_ = smat.NumCols();
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0 || num_cols_ == 0) {
       elements_.Resize(0);
       return;
     }
     // We first prepare <elements_> on CPU, we then move it to GPU by calling
     // CopyFromVec. This piece of code should be changed if we change the data
     // structure later.
     std::vector<MatrixElement<Real> > cpu_elements;
     for (int32 i = 0; i < smat.NumRows(); ++i) {
       for (int32 j = 0; j < (smat.Data() + i)->NumElements(); ++j) {
         MatrixElement<Real> cpu_element;
         cpu_element.row = i;
         cpu_element.column = ((smat.Data() + i)->Data() + j)->first;
         cpu_element.weight = ((smat.Data() + i)->Data() + j)->second;
         cpu_elements.push_back(cpu_element);
       }
     }
     elements_.CopyFromVec(cpu_elements);
   } else
 #endif
   {
     this->Mat().CopyFromSmat(smat);
   }
 }
template void CopyToMat (CuMatrixBase< OtherReal > * dest, MatrixTransposeType trans = kNoTrans) const
Definition at line 391 of file cu-sparse-matrix.cc.
References CU1DBLOCK, CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::SetZero().
Referenced by GeneralMatrix::AddToMat(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< Real >::CopyFromGeneralMat(), GeneralMatrix::CopyToMat(), kaldi::UnitTestCuSparseMatrixCopyToSmat(), kaldi::UnitTestCuSparseMatrixFrobeniusNorm(), kaldi::UnitTestCuSparseMatrixSum(), kaldi::UnitTestCuSparseMatrixSwap(), and kaldi::UnitTestCuSparseMatrixTraceMatSmat().
{
   if (trans == kNoTrans) {
     KALDI_ASSERT(M->NumRows() == NumRows() && M->NumCols() == NumCols());
   } else {
     KALDI_ASSERT(M->NumRows() == NumCols() && M->NumCols() == NumRows());
   }
   M->SetZero();
   if (NumElements() == 0) {
     return;
   }
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU1DBLOCK, 1);
     dim3 dimGrid(n_blocks(this->NumElements(), CU1DBLOCK), 1);
     if (trans == kNoTrans) {
       cuda_copy_from_smat(dimGrid, dimBlock, M->Data(),
                           this->Data(), M->Dim(), this->NumElements());
     } else {
       cuda_copy_from_smat_trans(dimGrid, dimBlock, M->Data(),
                                 this->Data(), M->Dim(), this->NumElements());
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     reinterpret_cast<const SparseMatrix<Real>*>(this)->CopyToMat(&(M->Mat()),
                                                                  trans);
   }
 }
template void CopyToSmat (SparseMatrix< OtherReal > * smat) const
Copy to CPU-based matrix.
We will add the transpose option later when it is necessary.
Definition at line 181 of file cu-sparse-matrix.cc.
References SparseMatrix< Real >::CopyFromSmat(), rnnlm::i, and KALDI_ASSERT.
Referenced by CuSparseMatrix< Real >::Swap(), and kaldi::UnitTestCuSparseMatrixCopyToSmat().
{
   KALDI_ASSERT(smat != NULL);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     std::vector<MatrixElement<Real> > cpu_elements;
     elements_.CopyToVec(&cpu_elements);
     std::vector<std::vector<std::pair<MatrixIndexT, Real> > > pairs(num_rows_);
     for (int32 i = 0; i < cpu_elements.size(); ++i) {
       pairs[cpu_elements[i].row].push_back(
           std::make_pair(cpu_elements[i].column, cpu_elements[i].weight));
     }
     SparseMatrix<Real> tmp(num_cols_, pairs);
     smat->CopyFromSmat(tmp);
   } else
 #endif
   {
     smat->CopyFromSmat(this->Mat());
   }
 }
MatrixElement< Real > * Data ()
Definition at line 87 of file cu-sparse-matrix.cc.
Referenced by kaldi::TraceMatSmat().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (elements_.Dim() == 0)
       return NULL;
     else
       return elements_.Data();
   } else
 #endif
   {
     return NULL;
   }
 }
const MatrixElement< Real > * Data () const
Definition at line 102 of file cu-sparse-matrix.cc.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (elements_.Dim() == 0)
       return NULL;
     else
       return elements_.Data();
   } else
 #endif
   {
     return NULL;
   }
 }
Real FrobeniusNorm () const
Definition at line 73 of file cu-sparse-matrix.cc.
References kaldi::kUndefined, and CuVectorBase< Real >::Norm().
Referenced by kaldi::UnitTestCuSparseMatrixFrobeniusNorm().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuVector<Real> element_vec(this->NumElements(), kUndefined);
     this->CopyElementsToVec(&element_vec);
     return element_vec.Norm(2);
   } else
 #endif
   {
     return Mat().FrobeniusNorm();
   }
 }
const SparseMatrix<Real>& Mat () const inline protected
Definition at line 132 of file cu-sparse-matrix.h.
Referenced by CuSparseMatrix< Real >::operator=(), CuSparseMatrix< Real >::Swap(), and kaldi::TraceMatSmat().
{
     return *(reinterpret_cast<const SparseMatrix<Real>* >(this));
   }
SparseMatrix<Real>& Mat () inline protected
Definition at line 135 of file cu-sparse-matrix.h.
{
     return *(reinterpret_cast<SparseMatrix<Real>* >(this));
   }
MatrixIndexT NumCols () const inline
Definition at line 62 of file cu-sparse-matrix.h.
References CuSparseMatrix< Real >::num_cols_.
Referenced by GeneralMatrix::AddToMat(), kaldi::TraceMatSmat(), and kaldi::UnitTestCuSparseMatrixSwap().
 { return num_cols_; }
MatrixIndexT NumElements () const
Definition at line 45 of file cu-sparse-matrix.cc.
Referenced by kaldi::TraceMatSmat().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     return elements_.Dim();
   } else
 #endif
   {
     return Mat().NumElements();
   }
 }
MatrixIndexT NumRows () const inline
Definition at line 60 of file cu-sparse-matrix.h.
References CuSparseMatrix< Real >::num_rows_.
Referenced by GeneralMatrix::AddToMat(), kaldi::TraceMatSmat(), and kaldi::UnitTestCuSparseMatrixSwap().
 { return num_rows_; }
CuSparseMatrix< Real > & operator= (const SparseMatrix< Real > & smat)
Copy from CPU-based matrix.
Definition at line 117 of file cu-sparse-matrix.cc.
{
   this->CopyFromSmat(smat);
   return *this;
 }
CuSparseMatrix< Real > & operator= (const CuSparseMatrix< Real > & smat)
Copy from possibly-GPU-based matrix.
Definition at line 124 of file cu-sparse-matrix.cc.
References CuSparseMatrix< Real >::elements_, CuSparseMatrix< Real >::Mat(), CuSparseMatrix< Real >::num_cols_, and CuSparseMatrix< Real >::num_rows_.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     elements_ = smat.elements_;
     num_rows_ = smat.num_rows_;
     num_cols_ = smat.num_cols_;
   } else
 #endif
   {
     this->Mat() = smat.Mat();
   }
   return *this;
 }
void Read (std::istream & is, bool binary)
Definition at line 290 of file cu-sparse-matrix.cc.
References SparseMatrix< Real >::Read().
{
   SparseMatrix<Real> tmp;
   tmp.Read(is, binary);
   this->Swap(&tmp);
 }
void SetRandn (BaseFloat zero_prob)
Sets up to a pseudo-randomly initialized matrix, with each element zero with probability zero_prob and else normally distributed- mostly for purposes of testing.
Definition at line 274 of file cu-sparse-matrix.cc.
References SparseMatrix< Real >::SetRandn().
{
   if (num_rows_ == 0) return;
   // Use the CPU function for the moment, not efficient...
   SparseMatrix<Real> tmp(num_rows_, num_cols_);
   tmp.SetRandn(zero_prob);
   Swap(&tmp);
 }
Real Sum () const
Definition at line 57 of file cu-sparse-matrix.cc.
References kaldi::kUndefined, and CuVectorBase< Real >::Sum().
Referenced by kaldi::nnet3::ComputeObjectiveFunction(), and kaldi::UnitTestCuSparseMatrixSum().
{
   if (NumElements() == 0)
     return 0.0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuVector<Real> sum_vec(this->NumElements(), kUndefined);
     this->CopyElementsToVec(&sum_vec);
     return sum_vec.Sum();
   } else
 #endif
   {
     return Mat().Sum();
   }
 }
void Swap (SparseMatrix< Real > * smat)
Swap with CPU-based matrix.
Definition at line 232 of file cu-sparse-matrix.cc.
References CuSparseMatrix< Real >::CopyToSmat(), SparseMatrix< Real >::NumCols(), and SparseMatrix< Real >::NumRows().
Referenced by kaldi::UnitTestCuSparseMatrixSwap().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuSparseMatrix<Real> tmp(*smat);
     Swap(&tmp);
     tmp.CopyToSmat(smat);
   } else
 #endif
   {
     num_rows_ = smat->NumRows();
     num_cols_ = smat->NumCols();
     Mat().Swap(smat);
   }
 }
void Swap (CuSparseMatrix< Real > * smat)
Swap with possibly-CPU-based matrix.
Definition at line 248 of file cu-sparse-matrix.cc.
References CuSparseMatrix< Real >::elements_, CuSparseMatrix< Real >::Mat(), CuSparseMatrix< Real >::num_cols_, and CuSparseMatrix< Real >::num_rows_.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuArray<MatrixElement<Real> > tmp_elements(elements_);
     elements_ = smat->elements_;
     smat->elements_ = tmp_elements;
     MatrixIndexT tmp_dim = num_rows_;
     num_rows_ = smat->num_rows_;
     smat->num_rows_ = tmp_dim;
     tmp_dim = num_cols_;
     num_cols_ = smat->num_cols_;
     smat->num_cols_ = tmp_dim;
   } else
 #endif
   {
     Real dim = num_rows_;
     num_rows_ = smat->num_rows_;
     smat->num_rows_ = dim;
     dim = num_cols_;
     num_cols_ = smat->num_cols_;
     smat->num_cols_ = dim;
     Mat().Swap(&(smat->Mat()));
   }
 }
void Write (std::ostream & os, bool binary) const
Definition at line 283 of file cu-sparse-matrix.cc.
References SparseMatrix< Real >::Write().
{
   SparseMatrix<Real> tmp;
   CopyToSmat(&tmp);
   tmp.Write(os, binary);
 }
Friends And Related Function Documentation
friend class CuMatrixBase< double > friend
Definition at line 50 of file cu-sparse-matrix.h.
friend class CuMatrixBase< float > friend
Definition at line 49 of file cu-sparse-matrix.h.
friend class CuMatrixBase< Real > friend
Definition at line 51 of file cu-sparse-matrix.h.
friend class CuVectorBase< double > friend
Definition at line 53 of file cu-sparse-matrix.h.
friend class CuVectorBase< float > friend
Definition at line 52 of file cu-sparse-matrix.h.
friend class CuVectorBase< Real > friend
Definition at line 54 of file cu-sparse-matrix.h.
Real TraceMatSmat (const CuMatrixBase< Real > & A, const CuSparseMatrix< Real > & B, MatrixTransposeType trans) friend
Definition at line 300 of file cu-sparse-matrix.cc.
{
   if (A.NumCols() == 0) {
     KALDI_ASSERT(B.NumCols() == 0);
     return 0.0;
   }
   if (B.NumElements() == 0) {
     return 0.0;
   }
   Real result = 0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (trans == kTrans) {
       KALDI_ASSERT(A.NumRows() == B.NumRows() && A.NumCols() == B.NumCols());
     } else {
       KALDI_ASSERT(A.NumCols() == B.NumRows() && A.NumRows() == B.NumCols());
     }
     // The Sum() method in CuVector handles a bunch of logic, we use that to
     // comptue the trace.
     CuVector<Real> sum_vec(B.NumElements());
     Timer tim;
     dim3 dimBlock(CU1DBLOCK, 1);
     dim3 dimGrid(n_blocks(B.NumElements(), CU1DBLOCK), 1);
     if (trans == kNoTrans) {
       cuda_trace_mat_smat(dimGrid, dimBlock, A.Data(), B.Data(),
                           A.Dim(), B.NumElements(), sum_vec.Data());
     } else {
       cuda_trace_mat_smat_trans(dimGrid, dimBlock, A.Data(), B.Data(),
                                 A.Dim(), B.NumElements(), sum_vec.Data());
     }
     result = sum_vec.Sum();
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     result = TraceMatSmat(A.Mat(), B.Mat(), trans);
   }
   return result;
 }
Member Data Documentation
std::vector<SparseVector<Real> > cpu_rows_ private
Definition at line 142 of file cu-sparse-matrix.h.
CuArray<MatrixElement<Real> > elements_ private
Definition at line 151 of file cu-sparse-matrix.h.
Referenced by CuSparseMatrix< Real >::operator=(), and CuSparseMatrix< Real >::Swap().
MatrixIndexT num_cols_ private
Definition at line 145 of file cu-sparse-matrix.h.
Referenced by CuSparseMatrix< Real >::NumCols(), CuSparseMatrix< Real >::operator=(), and CuSparseMatrix< Real >::Swap().
MatrixIndexT num_rows_ private
Definition at line 144 of file cu-sparse-matrix.h.
Referenced by CuSparseMatrix< Real >::NumRows(), CuSparseMatrix< Real >::operator=(), and CuSparseMatrix< Real >::Swap().
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-sparse-matrix.h
cudamatrix/cu-sparse-matrix.cc