Kaldi: Output Class Reference
Output Class Reference
"Classes for opening streams"
#include <kaldi-io.h>
Public Member Functions
Output (const std::string &filename, bool binary, bool write_header=true)
Output ()
bool Open (const std::string &wxfilename, bool binary, bool write_header)
This opens the stream, with the given mode (binary or text).
bool IsOpen ()
std::ostream & Stream ()
bool Close ()
~Output ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (Output)
Private Attributes
OutputImplBase * impl_
std::string filename_
Detailed Description
Definition at line 122 of file kaldi-io.h.
Constructor & Destructor Documentation
Output (const std::string & filename, bool binary, bool write_header = true)
Definition at line 644 of file kaldi-io.cc.
References Output::impl_, KALDI_ERR, Output::Open(), and kaldi::PrintableWxfilename().
                                  :impl_(NULL) {
   if (!Open(wxfilename, binary, write_header)) {
     if (impl_) {
       delete impl_;
       impl_ = NULL;
     }
     KALDI_ERR << "Error opening output stream " <<
         PrintableWxfilename(wxfilename);
   }
 }
Output () inline
Definition at line 129 of file kaldi-io.h.
 : impl_(NULL) {}
~Output ()
Definition at line 667 of file kaldi-io.cc.
References kaldi::ClassifyWxfilename(), OutputImplBase::Close(), Output::filename_, Output::impl_, KALDI_ERR, kaldi::kFileOutput, and kaldi::PrintableWxfilename().
                 {
   if (impl_) {
     bool ok = impl_->Close();
     delete impl_;
     impl_ = NULL;
     if (!ok)
       KALDI_ERR << "Error closing output file "
                 << PrintableWxfilename(filename_)
                 << (ClassifyWxfilename(filename_) == kFileOutput ?
                     " (disk full?)" : "");
   }
 }
Member Function Documentation
bool Close ()
Definition at line 656 of file kaldi-io.cc.
References OutputImplBase::Close(), and Output::impl_.
Referenced by TableWriterArchiveImpl< Holder >::Close(), TableWriterBothImpl< Holder >::Close(), Nnet::Feedforward(), main(), Output::Open(), TableWriterBothImpl< Holder >::Open(), kaldi::TestEventTypeIo(), kaldi::TestGenRandContextDependency(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), kaldi::UnitTestReadScriptFile(), Nnet::Write(), TableWriterScriptImpl< Holder >::Write(), kaldi::WriteIntegerVectorSimple(), and kaldi::WriteIntegerVectorVectorSimple().
                    {
   if (!impl_) {
     return false;  // error to call Close if not open.
   } else {
     bool ans = impl_->Close();
     delete impl_;
     impl_ = NULL;
     return ans;
   }
 }
bool IsOpen () inline
Definition at line 38 of file kaldi-io-inl.h.
References Output::impl_.
Referenced by TableWriterArchiveImpl< Holder >::Close(), TableWriterBothImpl< Holder >::Close(), and Output::Open().
                     {
   return impl_ != NULL;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (Output) private
bool Open (const std::string & wxfilename, bool binary, bool write_header)
This opens the stream, with the given mode (binary or text).
It returns true on success and false on failure. However, it will throw if something was already open and could not be closed (to avoid this, call Close() first. if write_header == true and binary == true, it writes the Kaldi binary-mode header ('\0' then 'B'). You may call Open even if it is already open; it will close the existing stream and reopen (however if closing the old stream failed it will throw).
Definition at line 686 of file kaldi-io.cc.
References kaldi::ClassifyWxfilename(), Output::Close(), Output::filename_, Output::impl_, kaldi::InitKaldiOutputStream(), Output::IsOpen(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, kaldi::kFileOutput, kaldi::kPipeOutput, kaldi::kStandardOutput, OutputImplBase::Open(), kaldi::PrintableWxfilename(), and OutputImplBase::Stream().
Referenced by Nnet::Feedforward(), TableWriterArchiveImpl< Holder >::Open(), TableWriterBothImpl< Holder >::Open(), Output::Output(), TableWriterScriptImpl< Holder >::Write(), kaldi::WriteIntegerVectorSimple(), kaldi::WriteIntegerVectorVectorSimple(), and kaldi::WriteScriptFile().
{
   if (IsOpen()) {
     if (!Close()) {  // Throw here rather than return status, as it's an error
       // about something else: if the user wanted to avoid the exception he/she
       // could have called Close().
       KALDI_ERR << "Output::Open(), failed to close output stream: "
                 << PrintableWxfilename(filename_);
     }
   }
   filename_ = wxfn;
   OutputType type = ClassifyWxfilename(wxfn);
   KALDI_ASSERT(impl_ == NULL);
   if (type ==  kFileOutput) {
     impl_ = new FileOutputImpl();
   } else if (type == kStandardOutput) {
     impl_ = new StandardOutputImpl();
   } else if (type == kPipeOutput) {
     impl_ = new PipeOutputImpl();
   } else {  // type == kNoOutput
     KALDI_WARN << "Invalid output filename format "<<
         PrintableWxfilename(wxfn);
     return false;
   }
   if (!impl_->Open(wxfn, binary)) {
     delete impl_;
     impl_ = NULL;
     return false;  // failed to open.
   } else {  // successfully opened it.
     if (header) {
       InitKaldiOutputStream(impl_->Stream(), binary);
       bool ok = impl_->Stream().good();  // still OK?
       if (!ok) {
         delete impl_;
         impl_ = NULL;
         return false;
       }
       return true;
     } else {
       return true;
     }
   }
 }
std::ostream & Stream ()
Definition at line 680 of file kaldi-io.cc.
References Output::impl_, KALDI_ERR, and OutputImplBase::Stream().
Referenced by Nnet::Feedforward(), TableWriterArchiveImpl< Holder >::Flush(), TableWriterBothImpl< Holder >::Flush(), kaldi::InitAndOutputSgmm(), main(), kaldi::TestEventTypeIo(), kaldi::TestFmpe(), kaldi::TestGenRandContextDependency(), kaldi::nnet2::UnitTestGenericComponentInternal(), kaldi::UnitTestIoNew(), kaldi::UnitTestIoPipe(), kaldi::UnitTestIoStandard(), kaldi::UnitTestReadScriptFile(), Nnet::Write(), LangModelFst::Write(), TableWriterArchiveImpl< Holder >::Write(), TableWriterScriptImpl< Holder >::Write(), TableWriterBothImpl< Holder >::Write(), fst::WriteFstKaldi(), kaldi::WriteIntegerVectorSimple(), kaldi::WriteIntegerVectorVectorSimple(), kaldi::WriteKaldiObject(), and kaldi::WriteScriptFile().
                            {  // will throw if not open; else returns
   // stream.
   if (!impl_) KALDI_ERR << "Output::Stream() called but not open.";
   return impl_->Stream();
 }
Member Data Documentation
std::string filename_ private
Definition at line 159 of file kaldi-io.h.
Referenced by Output::Open(), and Output::~Output().
OutputImplBase* impl_ private
Definition at line 158 of file kaldi-io.h.
Referenced by Output::Close(), Output::IsOpen(), Output::Open(), Output::Output(), Output::Stream(), and Output::~Output().
The documentation for this class was generated from the following files:
util/kaldi-io.h
util/kaldi-io-inl.h
util/kaldi-io.cc