Kaldi: SgmmFmllrGlobalParams Class Reference
SgmmFmllrGlobalParams Class Reference
Global adaptation parameters.
#include <fmllr-sgmm.h>
Public Member Functions
void Init (const AmSgmm &sgmm, const Vector< BaseFloat > &state_occs)
void Write (std::ostream &out_stream, bool binary) const
void Read (std::istream &in_stream, bool binary)
bool IsEmpty () const
bool HasBasis () const
Public Attributes
Matrix< BaseFloat > pre_xform_
Pre-transform matrix. Dim is [D][D+1].
Matrix< BaseFloat > inv_xform_
Inverse of pre-transform. Dim is [D][D+1].
Vector< BaseFloat > mean_scatter_
Diagonal of mean-scatter matrix. Dim is [D].
std::vector< Matrix< BaseFloat > > fmllr_bases_
{W}_b. [b][d][d], dim is [B][D][D+1].
Detailed Description
Global adaptation parameters.
Definition at line 91 of file fmllr-sgmm.h.
Member Function Documentation
bool HasBasis () const inline
Definition at line 100 of file fmllr-sgmm.h.
References SgmmFmllrGlobalParams::fmllr_bases_.
Referenced by FmllrSgmmAccs::Update().
 { return fmllr_bases_.size() != 0; }
void Init (const AmSgmm & sgmm, const Vector< BaseFloat > & state_occs) inline
Definition at line 112 of file fmllr-sgmm.h.
References AmSgmm::ComputeFmllrPreXform(), SgmmFmllrGlobalParams::inv_xform_, SgmmFmllrGlobalParams::mean_scatter_, and SgmmFmllrGlobalParams::pre_xform_.
{
   sgmm.ComputeFmllrPreXform(state_occs, &pre_xform_, &inv_xform_,
                             &mean_scatter_);
 }
bool IsEmpty () const inline
Definition at line 96 of file fmllr-sgmm.h.
References VectorBase< Real >::Dim(), SgmmFmllrGlobalParams::inv_xform_, SgmmFmllrGlobalParams::mean_scatter_, MatrixBase< Real >::NumRows(), and SgmmFmllrGlobalParams::pre_xform_.
Referenced by FmllrSgmmAccs::Update().
{
     return (pre_xform_.NumRows() == 0 || inv_xform_.NumRows() == 0 ||
             mean_scatter_.Dim() == 0);
   }
void Read (std::istream & in_stream, bool binary)
Definition at line 122 of file fmllr-sgmm.cc.
References kaldi::ExpectToken(), SgmmFmllrGlobalParams::fmllr_bases_, rnnlm::i, SgmmFmllrGlobalParams::inv_xform_, KALDI_ERR, SgmmFmllrGlobalParams::mean_scatter_, SgmmFmllrGlobalParams::pre_xform_, Vector< Real >::Read(), Matrix< Real >::Read(), kaldi::ReadBasicType(), and kaldi::ReadToken().
Referenced by main().
{
   ExpectToken(in, binary, "<SGMM_FMLLR_GLOBAL_PARAMS>");
   ExpectToken(in, binary, "<PRE_XFORM>");
   pre_xform_.Read(in, binary);
   ExpectToken(in, binary, "<INV_XFORM>");
   inv_xform_.Read(in, binary);
   ExpectToken(in, binary, "<MEAN_SCATTER>");
   mean_scatter_.Read(in, binary);
   std::string token;
   ReadToken(in, binary, &token);
   if (token == "<FMLLR_BASIS>") {
     uint32 tmp;
     ReadBasicType(in, binary, &tmp);
     fmllr_bases_.resize(tmp);
     for (uint32 i = 0; i < tmp; i++) {
       fmllr_bases_[i].Read(in, binary);
     }
   } else {
     if (token != "</SGMM_FMLLR_GLOBAL_PARAMS>")
       KALDI_ERR << "Unexpected token '" << token << "' found.";
   }
 }
void Write (std::ostream & out_stream, bool binary) const
Definition at line 103 of file fmllr-sgmm.cc.
References SgmmFmllrGlobalParams::fmllr_bases_, rnnlm::i, SgmmFmllrGlobalParams::inv_xform_, SgmmFmllrGlobalParams::mean_scatter_, SgmmFmllrGlobalParams::pre_xform_, VectorBase< Real >::Write(), MatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by main().
{
   WriteToken(out, binary, "<SGMM_FMLLR_GLOBAL_PARAMS>");
   WriteToken(out, binary, "<PRE_XFORM>");
   pre_xform_.Write(out, binary);
   WriteToken(out, binary, "<INV_XFORM>");
   inv_xform_.Write(out, binary);
   WriteToken(out, binary, "<MEAN_SCATTER>");
   mean_scatter_.Write(out, binary);
   if (fmllr_bases_.size() != 0) {
     WriteToken(out, binary, "<FMLLR_BASIS>");
     uint32 tmp = static_cast<uint32>(fmllr_bases_.size());
     WriteBasicType(out, binary, tmp);
     for (uint32 i = 0; i < tmp; i++) {
       fmllr_bases_[i].Write(out, binary);
     }
   }
   WriteToken(out, binary, "</SGMM_FMLLR_GLOBAL_PARAMS>");
 }
Member Data Documentation
std::vector< Matrix<BaseFloat> > fmllr_bases_
{W}_b. [b][d][d], dim is [B][D][D+1].
Definition at line 109 of file fmllr-sgmm.h.
Referenced by kaldi::EstimateSgmmFmllrSubspace(), SgmmFmllrGlobalParams::HasBasis(), SgmmFmllrGlobalParams::Read(), FmllrSgmmAccs::Update(), and SgmmFmllrGlobalParams::Write().
Matrix<BaseFloat> inv_xform_
Inverse of pre-transform. Dim is [D][D+1].
Definition at line 105 of file fmllr-sgmm.h.
Referenced by kaldi::ApplyInvPreXformToChange(), kaldi::ApplyPreXformToGradient(), SgmmFmllrGlobalParams::Init(), SgmmFmllrGlobalParams::IsEmpty(), main(), SgmmFmllrGlobalParams::Read(), and SgmmFmllrGlobalParams::Write().
Vector<BaseFloat> mean_scatter_
Diagonal of mean-scatter matrix. Dim is [D].
Definition at line 107 of file fmllr-sgmm.h.
Referenced by kaldi::ApplyHessianXformToGradient(), kaldi::ApplyInvHessianXformToChange(), SgmmFmllrGlobalParams::Init(), SgmmFmllrGlobalParams::IsEmpty(), main(), SgmmFmllrGlobalParams::Read(), and SgmmFmllrGlobalParams::Write().
Matrix<BaseFloat> pre_xform_
Pre-transform matrix. Dim is [D][D+1].
Definition at line 103 of file fmllr-sgmm.h.
Referenced by kaldi::ApplyInvPreXformToChange(), kaldi::ApplyPreXformToGradient(), SgmmFmllrGlobalParams::Init(), SgmmFmllrGlobalParams::IsEmpty(), main(), SgmmFmllrGlobalParams::Read(), and SgmmFmllrGlobalParams::Write().
The documentation for this class was generated from the following files:
sgmm/fmllr-sgmm.h
sgmm/fmllr-sgmm.cc