Kaldi: SparseMatrix< Real > Class Template Reference
SparseMatrix< Real > Class Template Reference
%Matrix and vector classes
#include <matrix-common.h>
Public Member Functions
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
MatrixIndexT NumElements () const
Real Sum () const
Real FrobeniusNorm () const
template<class OtherReal >
void CopyToMat (MatrixBase< OtherReal > *other, MatrixTransposeType t=kNoTrans) const
void CopyElementsToVec (VectorBase< Real > *other) const
Copies the values of all the elements in SparseMatrix into a VectorBase object.
template<class OtherReal >
void CopyFromSmat (const SparseMatrix< OtherReal > &other)
Copies data from another sparse matrix.
void AddToMat (BaseFloat alpha, MatrixBase< Real > *other, MatrixTransposeType t=kNoTrans) const
Does *other = *other + alpha * *this.
SparseMatrix< Real > & operator= (const SparseMatrix< Real > &other)
SparseMatrix (const SparseMatrix< Real > &other)
void Swap (SparseMatrix< Real > *other)
SparseVector< Real > * Data ()
const SparseVector< Real > * Data () const
SparseMatrix (int32 dim, const std::vector< std::vector< std::pair< MatrixIndexT, Real > > > &pairs)
void SetRandn (BaseFloat zero_prob)
Sets up to a pseudo-randomly initialized matrix, with each element zero with probability zero_prob and else normally distributed- mostly for purposes of testing.
void Write (std::ostream &os, bool binary) const
void Read (std::istream &os, bool binary)
const SparseVector< Real > & Row (MatrixIndexT r) const
void SetRow (int32 r, const SparseVector< Real > &vec)
Sets row r to "vec"; makes sure it has the correct dimension.
void AppendSparseMatrixRows (std::vector< SparseMatrix< Real > > *inputs)
Sets *this to all the rows of *inputs appended together; this function is destructive of the inputs.
SparseMatrix ()
SparseMatrix (int32 num_rows, int32 num_cols)
void Resize (MatrixIndexT rows, MatrixIndexT cols, MatrixResizeType resize_type=kSetZero)
Resizes the matrix; analogous to Matrix::Resize().
Private Attributes
std::vector< SparseVector< Real > > rows_
Detailed Description
template<typename Real>
class kaldi::SparseMatrix< Real >
Definition at line 58 of file matrix-common.h.
Constructor & Destructor Documentation
SparseMatrix (const SparseMatrix< Real > & other) inline
Definition at line 152 of file sparse-matrix.h.
 { *this = other; }
SparseMatrix (int32 dim, const std::vector< std::vector< std::pair< MatrixIndexT, Real > > > & pairs)
Definition at line 541 of file sparse-matrix.cc.
References SparseMatrix< Real >::rows_.
                                                                      :
     rows_(pairs.size()) {
   MatrixIndexT num_rows = pairs.size();
   for (MatrixIndexT row = 0; row < num_rows; row++) {
     SparseVector<Real> svec(dim, pairs[row]);
     rows_[row].Swap(&svec);
   }
 }
SparseMatrix () inline
Definition at line 190 of file sparse-matrix.h.
 { }
SparseMatrix (int32 num_rows, int32 num_cols) inline
Definition at line 192 of file sparse-matrix.h.
 { Resize(num_rows, num_cols); }
Member Function Documentation
void AddToMat (BaseFloat alpha, MatrixBase< Real > * other, MatrixTransposeType t = kNoTrans) const
Does *other = *other + alpha * *this.
Definition at line 469 of file sparse-matrix.cc.
References MatrixBase< Real >::Data(), SparseVector< Real >::Data(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), SparseVector< Real >::NumElements(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by GeneralMatrix::AddToMat(), and kaldi::UnitTestSparseMatrixAddToMat().
{
   if (trans == kNoTrans) {
     MatrixIndexT num_rows = rows_.size();
     KALDI_ASSERT(other->NumRows() == num_rows);
     for (MatrixIndexT i = 0; i < num_rows; i++) {
       SubVector<Real> vec(*other, i);
       rows_[i].AddToVec(alpha, &vec);
     }
   } else {
     Real *other_col_data = other->Data();
     MatrixIndexT other_stride = other->Stride(),
         num_rows = NumRows(), num_cols = NumCols();
     KALDI_ASSERT(num_rows == other->NumCols() && num_cols == other->NumRows());
     for (MatrixIndexT row = 0; row < num_rows; row++, other_col_data++) {
       const SparseVector<Real> &svec = rows_[row];
       MatrixIndexT num_elems = svec.NumElements();
       const std::pair<MatrixIndexT, Real> *sdata = svec.Data();
       for (MatrixIndexT e = 0; e < num_elems; e++)
         other_col_data[sdata[e].first * other_stride] +=
             alpha * sdata[e].second;
     }
   }
 }
void AppendSparseMatrixRows (std::vector< SparseMatrix< Real > > * inputs)
Sets *this to all the rows of *inputs appended together; this function is destructive of the inputs.
Requires, obviously, that the inputs all have the same dimension (although some may be empty).
Definition at line 579 of file sparse-matrix.cc.
References KALDI_ASSERT, and KALDI_ERR.
Referenced by kaldi::AppendGeneralMatrixRows().
{
   rows_.clear();
   size_t num_rows = 0;
   typename std::vector<SparseMatrix<Real> >::iterator
       input_iter = inputs->begin(),
       input_end = inputs->end();
   for (; input_iter != input_end; ++input_iter)
     num_rows += input_iter->rows_.size();
   rows_.resize(num_rows);
   typename std::vector<SparseVector<Real> >::iterator
       row_iter = rows_.begin(),
       row_end = rows_.end();
   for (input_iter = inputs->begin(); input_iter != input_end; ++input_iter) {
     typename std::vector<SparseVector<Real> >::iterator
         input_row_iter = input_iter->rows_.begin(),
         input_row_end = input_iter->rows_.end();
     for (; input_row_iter != input_row_end; ++input_row_iter, ++row_iter)
       row_iter->Swap(&(*input_row_iter));
   }
   KALDI_ASSERT(row_iter == row_end);
   int32 num_cols = NumCols();
   for (row_iter = rows_.begin(); row_iter != row_end; ++row_iter) {
     if (row_iter->Dim() != num_cols)
       KALDI_ERR << "Appending rows with inconsistent dimensions, "
                 << row_iter->Dim() << " vs. " << num_cols;
   }
   inputs->clear();
 }
void CopyElementsToVec (VectorBase< Real > * other) const
Copies the values of all the elements in SparseMatrix into a VectorBase object.
Definition at line 384 of file sparse-matrix.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), rnnlm::i, rnnlm::j, and KALDI_ASSERT.
{
   KALDI_ASSERT(other->Dim() == NumElements());
   Real *dst_data = other->Data();
   int32 dst_index = 0;
   for (int32 i = 0; i < rows_.size(); ++i) {
     for (int32 j = 0; j < rows_[i].NumElements(); ++j) {
       dst_data[dst_index] =
           static_cast<Real>(rows_[i].GetElement(j).second);
       dst_index++;
     }
   }
 }
template void CopyFromSmat (const SparseMatrix< OtherReal > & other)
Copies data from another sparse matrix.
We will add the transpose option later when it is necessary.
Definition at line 399 of file sparse-matrix.cc.
References SparseMatrix< Real >::NumRows(), and SparseMatrix< Real >::Row().
Referenced by CuSparseMatrix< Real >::CopyToSmat().
{
   rows_.resize(other.NumRows());
   if (rows_.size() == 0) return;
   for (int32 r = 0; r < rows_.size(); ++r) {
     rows_[r].CopyFromSvec(other.Row(r));
   }
 }
template void CopyToMat (MatrixBase< OtherReal > * other, MatrixTransposeType t = kNoTrans) const
Definition at line 345 of file sparse-matrix.cc.
References MatrixBase< Real >::Data(), SparseVector< Real >::Data(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), SparseVector< Real >::NumElements(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::SetZero(), and MatrixBase< Real >::Stride().
Referenced by CuMatrixBase< Real >::CopyFromGeneralMat(), GeneralMatrix::CopyToMat(), GeneralMatrix::GetMatrix(), kaldi::UnitTestGeneralMatrix(), kaldi::UnitTestSparseMatrixAddToMat(), kaldi::UnitTestSparseMatrixFrobeniusNorm(), kaldi::UnitTestSparseMatrixSum(), and kaldi::UnitTestSparseMatrixTraceMatSmat().
{
   if (trans == kNoTrans) {
     MatrixIndexT num_rows = rows_.size();
     KALDI_ASSERT(other->NumRows() == num_rows);
     for (MatrixIndexT i = 0; i < num_rows; i++) {
       SubVector<OtherReal> vec(*other, i);
       rows_[i].CopyElementsToVec(&vec);
     }
   } else {
     OtherReal *other_col_data = other->Data();
     MatrixIndexT other_stride = other->Stride(),
         num_rows = NumRows(), num_cols = NumCols();
     KALDI_ASSERT(num_rows == other->NumCols() && num_cols == other->NumRows());
     other->SetZero();
     for (MatrixIndexT row = 0; row < num_rows; row++, other_col_data++) {
       const SparseVector<Real> &svec = rows_[row];
       MatrixIndexT num_elems = svec.NumElements();
       const std::pair<MatrixIndexT, Real> *sdata = svec.Data();
       for (MatrixIndexT e = 0; e < num_elems; e++)
         other_col_data[sdata[e].first * other_stride] = sdata[e].second;
     }
   }
 }
SparseVector< Real > * Data ()
Definition at line 307 of file sparse-matrix.cc.
Referenced by CuSparseMatrix< Real >::CopyFromSmat().
{
   if (rows_.empty())
     return NULL;
   else
     return rows_.data();
 }
const SparseVector< Real > * Data () const
Definition at line 315 of file sparse-matrix.cc.
{
   if (rows_.empty())
     return NULL;
   else
     return rows_.data();
 }
Real FrobeniusNorm () const
Definition at line 332 of file sparse-matrix.cc.
References rnnlm::i, and rnnlm::j.
Referenced by kaldi::UnitTestSparseMatrixFrobeniusNorm().
{
   Real squared_sum = 0;
   for (int32 i = 0; i < rows_.size(); ++i) {
     const std::pair<MatrixIndexT, Real> *row_data = rows_[i].Data();
     for (int32 j = 0; j < rows_[i].NumElements(); ++j) {
       squared_sum += row_data[j].second * row_data[j].second;
     }
   }
   return std::sqrt(squared_sum);
 }
MatrixIndexT NumCols () const
Definition at line 290 of file sparse-matrix.cc.
Referenced by CuSparseMatrix< Real >::CopyFromSmat(), kaldi::FilterSparseMatrixRows(), GeneralMatrix::GetMatrix(), GeneralMatrix::NumCols(), CuSparseMatrix< Real >::Swap(), kaldi::TraceMatSmat(), and kaldi::UnitTestCuSparseMatrixSwap().
{
   if (rows_.empty())
     return 0.0;
   else
     return rows_[0].Dim();
 }
MatrixIndexT NumElements () const
Definition at line 298 of file sparse-matrix.cc.
References rnnlm::i.
{
   int32 num_elements = 0;
   for (int32 i = 0; i < rows_.size(); ++i) {
     num_elements += rows_[i].NumElements();
   }
   return num_elements;
 }
MatrixIndexT NumRows () const
Definition at line 285 of file sparse-matrix.cc.
Referenced by CuSparseMatrix< Real >::CopyFromSmat(), SparseMatrix< Real >::CopyFromSmat(), GeneralMatrix::CopyToMat(), kaldi::FilterSparseMatrixRows(), GeneralMatrix::GetCompressedMatrix(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::NumRows(), CuSparseMatrix< Real >::Swap(), GeneralMatrix::SwapFullMatrix(), kaldi::TraceMatSmat(), GeneralMatrix::Type(), kaldi::UnitTestCuSparseMatrixSwap(), and GeneralMatrix::Write().
{
   return rows_.size();
 }
SparseMatrix< Real > & operator= (const SparseMatrix< Real > & other)
Definition at line 529 of file sparse-matrix.cc.
References SparseMatrix< Real >::rows_.
{
   rows_ = other.rows_;
   return *this;
 }
void Read (std::istream & os, bool binary)
Definition at line 440 of file sparse-matrix.cc.
References kaldi::ExpectToken(), KALDI_ASSERT, KALDI_ERR, and kaldi::ReadBasicType().
Referenced by CuSparseMatrix< Real >::Read(), and GeneralMatrix::Read().
{
   if (binary) {
     ExpectToken(is, binary, "SM");
     int32 num_rows;
     ReadBasicType(is, binary, &num_rows);
     KALDI_ASSERT(num_rows >= 0 && num_rows < 10000000);
     rows_.resize(num_rows);
     for (int32 row = 0; row < num_rows; row++)
       rows_[row].Read(is, binary);
   } else {
     std::string str;
     is >> str;
     if (str.substr(0, 5) != "rows=")
       KALDI_ERR << "Reading sparse matrix, expected 'rows=xxx', got " << str;
     std::string rows_str = str.substr(5, std::string::npos);
     std::istringstream rows_istr(rows_str);
     int32 num_rows = -1;
     rows_istr >> num_rows;
     if (num_rows < 0 || rows_istr.fail()) {
       KALDI_ERR << "Reading sparse vector, expected 'rows=[int]', got " << str;
     }
     rows_.resize(num_rows);
     for (int32 row = 0; row < num_rows; row++)
       rows_[row].Read(is, binary);
   }
 }
void Resize (MatrixIndexT rows, MatrixIndexT cols, MatrixResizeType resize_type = kSetZero)
Resizes the matrix; analogous to Matrix::Resize().
resize_type == kUndefined behaves the same as kSetZero.
Definition at line 560 of file sparse-matrix.cc.
References KALDI_ASSERT, kaldi::kCopyData, kaldi::kSetZero, and kaldi::kUndefined.
Referenced by GeneralMatrix::Clear(), kaldi::FilterSparseMatrixRows(), and SparseMatrix< BaseFloat >::SparseMatrix().
{
   KALDI_ASSERT(num_rows >= 0 && num_cols >= 0);
   if (resize_type == kSetZero || resize_type == kUndefined) {
     rows_.clear();
     Resize(num_rows, num_cols, kCopyData);
   } else {
     // Assume resize_type == kCopyData from here.
     int32 old_num_rows = rows_.size(), old_num_cols = NumCols();
     SparseVector<Real> initializer(num_cols);
     rows_.resize(num_rows, initializer);
     if (num_cols != old_num_cols)
       for (int32 row = 0; row < old_num_rows; row++)
         rows_[row].Resize(num_cols, kCopyData);
   }
 }
const SparseVector< Real > & Row (MatrixIndexT r) const
Definition at line 516 of file sparse-matrix.cc.
References KALDI_ASSERT.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::nnet3::ComputeAccuracy(), SparseMatrix< Real >::CopyFromSmat(), kaldi::FilterSparseMatrixRows(), and kaldi::TraceMatSmat().
{
   KALDI_ASSERT(static_cast<size_t>(r) < rows_.size());
   return rows_[r];
 }
void SetRandn (BaseFloat zero_prob)
Sets up to a pseudo-randomly initialized matrix, with each element zero with probability zero_prob and else normally distributed- mostly for purposes of testing.
Definition at line 553 of file sparse-matrix.cc.
Referenced by CuSparseMatrix< Real >::SetRandn(), kaldi::UnitTestCuSparseMatrixCopyToSmat(), kaldi::UnitTestCuSparseMatrixFrobeniusNorm(), kaldi::UnitTestCuSparseMatrixSum(), kaldi::UnitTestCuSparseMatrixSwap(), kaldi::UnitTestCuSparseMatrixTraceMatSmat(), kaldi::UnitTestGeneralMatrix(), kaldi::UnitTestSparseMatrixAddToMat(), kaldi::UnitTestSparseMatrixFrobeniusNorm(), kaldi::UnitTestSparseMatrixSum(), and kaldi::UnitTestSparseMatrixTraceMatSmat().
{
   MatrixIndexT num_rows = rows_.size();
   for (MatrixIndexT row = 0; row < num_rows; row++)
     rows_[row].SetRandn(zero_prob);
 }
void SetRow (int32 r, const SparseVector< Real > & vec)
Sets row r to "vec"; makes sure it has the correct dimension.
Definition at line 522 of file sparse-matrix.cc.
References SparseVector< Real >::Dim(), and KALDI_ASSERT.
Referenced by kaldi::FilterSparseMatrixRows().
{
   KALDI_ASSERT(static_cast<size_t>(r) < rows_.size() &&
                vec.Dim() == rows_[0].Dim());
   rows_[r] = vec;
 }
Real Sum () const
Definition at line 323 of file sparse-matrix.cc.
References rnnlm::i.
Referenced by kaldi::UnitTestSparseMatrixSum().
{
   Real sum = 0;
   for (int32 i = 0; i < rows_.size(); ++i) {
     sum += rows_[i].Sum();
   }
   return sum;
 }
void Swap (SparseMatrix< Real > * other)
Definition at line 536 of file sparse-matrix.cc.
References SparseMatrix< Real >::rows_.
Referenced by GeneralMatrix::Swap(), and GeneralMatrix::SwapSparseMatrix().
{
   rows_.swap(other->rows_);
 }
void Write (std::ostream & os, bool binary) const
Definition at line 416 of file sparse-matrix.cc.
References kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by CuSparseMatrix< Real >::Write(), and GeneralMatrix::Write().
{
   if (binary) {
     // Note: we can use the same marker for float and double SparseMatrix,
     // because internally we use WriteBasicType and ReadBasicType to read the
     // floats and doubles, and this will automatically take care of type
     // conversion.
     WriteToken(os, binary, "SM");
     int32 num_rows = rows_.size();
     WriteBasicType(os, binary, num_rows);
     for (int32 row = 0; row < num_rows; row++)
       rows_[row].Write(os, binary);
   } else {
     // The format is "rows=10 dim=20 [ 1 0.4  9 1.2 ] dim=20 [ 3 1.7 19 0.6 ] ..
     // not 100% efficient, but easy to work with, and we can re-use the
     // read/write code from SparseVector.
     int32 num_rows = rows_.size();
     os << "rows=" << num_rows << " ";
     for (int32 row = 0; row < num_rows; row++)
       rows_[row].Write(os, binary);
     os << "\n";  // Might make it a little more readable.
   }
 }
Member Data Documentation
std::vector<SparseVector<Real> > rows_ private
Definition at line 206 of file sparse-matrix.h.
Referenced by SparseMatrix< Real >::operator=(), SparseMatrix< Real >::SparseMatrix(), and SparseMatrix< Real >::Swap().
The documentation for this class was generated from the following files:
matrix/matrix-common.h
matrix/sparse-matrix.h
matrix/sparse-matrix.cc