Kaldi: BasisFmllrAccus Class Reference
BasisFmllrAccus Class Reference
Stats for fMLLR subspace estimation.
#include <basis-fmllr-diag-gmm.h>
Public Member Functions
BasisFmllrAccus ()
BasisFmllrAccus (int32 dim)
void ResizeAccus (int32 dim)
void Write (std::ostream &out_stream, bool binary) const
Routines for reading and writing stats.
void Read (std::istream &in_stream, bool binary, bool add=false)
void AccuGradientScatter (const AffineXformStats &spk_stats)
Accumulate gradient scatter for one (training) speaker.
Public Attributes
SpMatrix< BaseFloat > grad_scatter_
Gradient scatter. Dim is [(D+1)*D] [(D+1)*D].
int32 dim_
Feature dimension.
double beta_
Occupancy count.
Detailed Description
Stats for fMLLR subspace estimation.
This class is only to estimate the "basis", which is done in training time. Class BasisFmllrEstimate contains the functions that are used in test time. (see the function BasisFmllrCoefficients()).
Definition at line 73 of file basis-fmllr-diag-gmm.h.
Constructor & Destructor Documentation
BasisFmllrAccus () inline
Definition at line 76 of file basis-fmllr-diag-gmm.h.
 { }
BasisFmllrAccus (int32 dim) inline explicit
Definition at line 77 of file basis-fmllr-diag-gmm.h.
References BasisFmllrAccus::beta_, BasisFmllrAccus::dim_, and BasisFmllrAccus::ResizeAccus().
{
       dim_ = dim;
       beta_ = 0;
       ResizeAccus(dim);
   }
Member Function Documentation
void AccuGradientScatter (const AffineXformStats & spk_stats)
Accumulate gradient scatter for one (training) speaker.
To finish the process, we need to traverse the whole training set. Parallelization works if the speaker list is splitted, and stats are summed up by setting add=true in BasisFmllrEstimate:: ReadBasis. See section 5.2 of the paper.
Definition at line 91 of file basis-fmllr-diag-gmm.cc.
References MatrixBase< Real >::AddMat(), SpMatrix< Real >::AddVec2(), AffineXformStats::beta_, BasisFmllrAccus::beta_, VectorBase< Real >::CopyRowsFromMat(), rnnlm::d, BasisFmllrAccus::dim_, AffineXformStats::G_, BasisFmllrAccus::grad_scatter_, AffineXformStats::K_, MatrixBase< Real >::Row(), MatrixBase< Real >::Scale(), and MatrixBase< Real >::SetUnit().
{
   // Gradient of auxf w.r.t. xform_spk
   // Eq. (33)
   Matrix<double> grad_mat(dim_, dim_ + 1);
   grad_mat.SetUnit();
   grad_mat.Scale(spk_stats.beta_);
   grad_mat.AddMat(1.0, spk_stats.K_);
   for (int d = 0; d < dim_; ++d) {
       Matrix<double> G_d_mat(spk_stats.G_[d]);
        grad_mat.Row(d).AddVec(-1.0, G_d_mat.Row(d));
   }
   // Row stack of gradient matrix
   Vector<BaseFloat> grad_vec((dim_+1) * dim_);
   grad_vec.CopyRowsFromMat(grad_mat);
   // The amount of data beta_ is likely to be ZERO, especially
   // when silence-weight is set to be 0 and we are using the
   // per-utt mode.
   if (spk_stats.beta_ > 0) {
     beta_ += spk_stats.beta_;
     grad_scatter_.AddVec2(BaseFloat(1.0 / spk_stats.beta_), grad_vec);
   }
 }
void Read (std::istream & in_stream, bool binary, bool add = false)
Definition at line 66 of file basis-fmllr-diag-gmm.cc.
References BasisFmllrAccus::beta_, kaldi::ExpectToken(), BasisFmllrAccus::grad_scatter_, PackedMatrix< Real >::Read(), and kaldi::ReadBasicType().
{
   ExpectToken(is, binary, "<BASISFMLLRACCUS>");
   ExpectToken(is, binary, "<BETA>");
   double tmp_beta = 0;
   ReadBasicType(is, binary, &tmp_beta);
   if (add) {
     beta_ += tmp_beta;
   } else {
     beta_ = tmp_beta;
   }
   ExpectToken(is, binary, "<GRADSCATTER>");
   grad_scatter_.Read(is, binary, add);
   ExpectToken(is, binary, "</BASISFMLLRACCUS>");
 }
void ResizeAccus (int32 dim)
Definition at line 82 of file basis-fmllr-diag-gmm.cc.
References BasisFmllrAccus::grad_scatter_, KALDI_ERR, kaldi::kSetZero, and SpMatrix< Real >::Resize().
Referenced by BasisFmllrAccus::BasisFmllrAccus().
{
   if (dim <= 0) {
     KALDI_ERR << "Invalid feature dimension " << dim; // dim=0 is not allowed
   } else {
     // 'kSetZero' may not be necessary, but makes computation safe
     grad_scatter_.Resize((dim + 1) * dim, kSetZero);
   }
 }
void Write (std::ostream & out_stream, bool binary) const
Routines for reading and writing stats.
Definition at line 53 of file basis-fmllr-diag-gmm.cc.
References BasisFmllrAccus::beta_, BasisFmllrAccus::grad_scatter_, PackedMatrix< Real >::NumCols(), PackedMatrix< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<BASISFMLLRACCUS>");
   WriteToken(os, binary, "<BETA>");
   WriteBasicType(os, binary, beta_);
   if (!binary) os << '\n';
   if (grad_scatter_.NumCols() != 0) {
     WriteToken(os, binary, "<GRADSCATTER>");
     grad_scatter_.Write(os, binary);
   }
   WriteToken(os, binary, "</BASISFMLLRACCUS>");
 }
Member Data Documentation
double beta_
Occupancy count.
Definition at line 101 of file basis-fmllr-diag-gmm.h.
Referenced by BasisFmllrAccus::AccuGradientScatter(), BasisFmllrAccus::BasisFmllrAccus(), BasisFmllrEstimate::EstimateFmllrBasis(), BasisFmllrAccus::Read(), and BasisFmllrAccus::Write().
int32 dim_
Feature dimension.
Definition at line 99 of file basis-fmllr-diag-gmm.h.
Referenced by BasisFmllrAccus::AccuGradientScatter(), and BasisFmllrAccus::BasisFmllrAccus().
SpMatrix<BaseFloat> grad_scatter_
Gradient scatter. Dim is [(D+1)*D] [(D+1)*D].
Definition at line 97 of file basis-fmllr-diag-gmm.h.
Referenced by BasisFmllrAccus::AccuGradientScatter(), BasisFmllrEstimate::EstimateFmllrBasis(), BasisFmllrAccus::Read(), BasisFmllrAccus::ResizeAccus(), and BasisFmllrAccus::Write().
The documentation for this class was generated from the following files:
transform/basis-fmllr-diag-gmm.h
transform/basis-fmllr-diag-gmm.cc