Kaldi: MinimumBayesRisk Class Reference
MinimumBayesRisk Class Reference
The implementation of the Minimum Bayes Risk decoding method described in "Minimum Bayes Risk decoding and system combination based on a recursion for edit distance", Haihua Xu, Daniel Povey, Lidia Mangu and Jie Zhu, Computer Speech and Language, 2011 This is a slightly more principled way to do Minimum Bayes Risk (MBR) decoding than the standard "Confusion Network" method.
#include <sausages.h>
Classes
struct Arc
struct GammaCompare
Public Member Functions
MinimumBayesRisk (const CompactLattice &clat, bool do_mbr=true)
Initialize with compact lattice– any acoustic scaling etc., is assumed to have been done already.
MinimumBayesRisk (const CompactLattice &clat, const std::vector< int32 > &words, bool do_mbr=false)
const std::vector< int32 > & GetOneBest () const
const std::vector< std::pair
< BaseFloat, BaseFloat > > GetSausageTimes () const
const std::vector< std::pair
< BaseFloat, BaseFloat > > & GetOneBestTimes () const
const std::vector< BaseFloat > & GetOneBestConfidences () const
Outputs the confidences for the one-best transcript.
BaseFloat GetBayesRisk () const
Returns the expected WER over this sentence (assuming model correctness.
const std::vector< std::vector
< std::pair< int32, BaseFloat > > > & GetSausageStats () const
Private Member Functions
void PrepareLatticeAndInitStats (CompactLattice *clat)
void MbrDecode ()
Minimum-Bayes-Risk Decode. Top-level algorithm. Figure 6 of the paper.
double l (int32 a, int32 b)
The basic edit-distance function l(a,b), as in the paper.
int32 r (int32 q)
returns r_q, in one-based indexing, as in the paper.
double EditDistance (int32 N, int32 Q, Vector< double > &alpha, Matrix< double > &alpha_dash, Vector< double > &alpha_dash_arc)
Figure 4 of the paper; called from AccStats (Fig. 5)
void AccStats ()
Figure 5 of the paper. Outputs to gamma_ and L_.
Static Private Member Functions
static void RemoveEps (std::vector< int32 > *vec)
Removes epsilons (symbol 0) from a vector.
static void NormalizeEps (std::vector< int32 > *vec)
static BaseFloat delta ()
static void AddToMap (int32 i, double d, std::map< int32, double > *gamma)
Function used to increment map.
Private Attributes
bool do_mbr_
Boolean configuration parameter: if true, we actually update the hypothesis to do MBR decoding (if false, our output is the MAP decoded output, but we output the stats too).
std::vector< Arc > arcs_
Arcs in the topologically sorted acceptor form of the word-level lattice, with one final-state.
std::vector< std::vector< int32 > > pre_
For each node in the lattice, a list of arcs entering that node.
std::vector< int32 > state_times_
std::vector< int32 > R_
double L_
std::vector< std::vector
< std::pair< int32, BaseFloat > > > gamma_
std::vector< std::pair
< BaseFloat, BaseFloat > > times_
std::vector< std::pair
< BaseFloat, BaseFloat > > one_best_times_
std::vector< BaseFloat > one_best_confidences_
Detailed Description
The implementation of the Minimum Bayes Risk decoding method described in "Minimum Bayes Risk decoding and system combination based on a recursion for edit distance", Haihua Xu, Daniel Povey, Lidia Mangu and Jie Zhu, Computer Speech and Language, 2011 This is a slightly more principled way to do Minimum Bayes Risk (MBR) decoding than the standard "Confusion Network" method.
Note: MBR decoding aims to minimize the expected word error rate, assuming the lattice encodes the true uncertainty about what was spoken; standard Viterbi decoding gives the most likely utterance, which corresponds to minimizing the expected sentence error rate.
In addition to giving the MBR output, we also provide a way to get a "Confusion Network" or informally "sausage"-like structure. This is a linear sequence of bins, and in each bin, there is a distribution over words (or epsilon, meaning no word). This is useful for estimating confidence. Note: due to the way these sausages are made, typically there will be, between each bin representing a high-confidence word, a bin in which epsilon (no word) is the most likely word. Inside these bins is where we put possible insertions. This class does the word-level Minimum Bayes Risk computation, and gives you either the 1-best MBR output together with the expected Bayes Risk, or a sausage-like structure.
Definition at line 59 of file sausages.h.
Constructor & Destructor Documentation
MinimumBayesRisk (const CompactLattice & clat, bool do_mbr = true)
Initialize with compact lattice– any acoustic scaling etc., is assumed to have been done already.
This does the whole computation. You get the output with GetOneBest(), GetBayesRisk(), and GetSausageStats().
Definition at line 317 of file sausages.cc.
References fst::ConvertLattice(), fst::GetLinearSymbolSequence(), KALDI_ASSERT, MinimumBayesRisk::L_, MinimumBayesRisk::MbrDecode(), MinimumBayesRisk::PrepareLatticeAndInitStats(), MinimumBayesRisk::R_, fst::RemoveAlignmentsFromCompactLattice(), and words.
                                                                             :
     do_mbr_(do_mbr) {
   CompactLattice clat(clat_in); // copy.
   PrepareLatticeAndInitStats(&clat);
   // We don't need to look at clat.Start() or clat.Final(state):
   // we know clat.Start() == 0 since it's topologically sorted,
   // and clat.Final(state) is Zero() except for One() at the last-
   // numbered state, thanks to CreateSuperFinal and the topological
   // sorting.
   { // Now set R_ to one best in the FST.
     RemoveAlignmentsFromCompactLattice(&clat); // will be more efficient
     // in best-path if we do this.
     Lattice lat;
     ConvertLattice(clat, &lat); // convert from CompactLattice to Lattice.
     fst::VectorFst<fst::StdArc> fst;
     ConvertLattice(lat, &fst); // convert from lattice to normal FST.
     fst::VectorFst<fst::StdArc> fst_shortest_path;
     fst::ShortestPath(fst, &fst_shortest_path); // take shortest path of FST.
     std::vector<int32> alignment, words;
     fst::TropicalWeight weight;
     GetLinearSymbolSequence(fst_shortest_path, &alignment, &words, &weight);
     KALDI_ASSERT(alignment.empty()); // we removed the alignment.
     R_ = words;
     L_ = 0.0; // Set current edit-distance to 0 [just so we know
     // when we're on the 1st iter.]
   }
   MbrDecode();
 }
MinimumBayesRisk (const CompactLattice & clat, const std::vector< int32 > & words, bool do_mbr = false)
Definition at line 351 of file sausages.cc.
References MinimumBayesRisk::L_, MinimumBayesRisk::MbrDecode(), MinimumBayesRisk::PrepareLatticeAndInitStats(), MinimumBayesRisk::R_, and words.
                                                : do_mbr_(do_mbr) {
   CompactLattice clat(clat_in); // copy.
   PrepareLatticeAndInitStats(&clat);
   R_ = words;
   L_ = 0.0;
   MbrDecode();
 }
Member Function Documentation
void AccStats () private
Figure 5 of the paper. Outputs to gamma_ and L_.
Definition at line 133 of file sausages.cc.
References MinimumBayesRisk::AddToMap(), MinimumBayesRisk::arcs_, MinimumBayesRisk::delta(), MinimumBayesRisk::EditDistance(), kaldi::Exp(), MinimumBayesRisk::gamma_, rnnlm::i, KALDI_ERR, KALDI_VLOG, KALDI_WARN, MinimumBayesRisk::l(), MinimumBayesRisk::L_, MinimumBayesRisk::Arc::loglike, rnnlm::n, MinimumBayesRisk::pre_, MinimumBayesRisk::r(), MinimumBayesRisk::R_, VectorBase< Real >::SetZero(), MinimumBayesRisk::Arc::start_node, MinimumBayesRisk::state_times_, MinimumBayesRisk::times_, and MinimumBayesRisk::Arc::word.
Referenced by MinimumBayesRisk::MbrDecode().
{
   using std::map;
   int32 N = static_cast<int32>(pre_.size()) - 1,
       Q = static_cast<int32>(R_.size());
   Vector<double> alpha(N+1); // index (1...N)
   Matrix<double> alpha_dash(N+1, Q+1); // index (1...N, 0...Q)
   Vector<double> alpha_dash_arc(Q+1); // index 0...Q
   Matrix<double> beta_dash(N+1, Q+1); // index (1...N, 0...Q)
   Vector<double> beta_dash_arc(Q+1); // index 0...Q
   vector<char> b_arc(Q+1); // integer in {1,2,3}; index 1...Q
   vector<map<int32, double> > gamma(Q+1); // temp. form of gamma.
   // index 1...Q [word] -> occ.
   // The tau arrays below are the sums over words of the tau_b
   // and tau_e timing quantities mentioned in Appendix C of
   // the paper... we are using these to get averaged times for
   // the sausage bins, not specifically for the 1-best output.
   Vector<double> tau_b(Q+1), tau_e(Q+1);
   double Ltmp = EditDistance(N, Q, alpha, alpha_dash, alpha_dash_arc);
   if (L_ != 0 && Ltmp > L_) { // L_ != 0 is to rule out 1st iter.
     KALDI_WARN << "Edit distance increased: " << Ltmp << " > "
                << L_;
   }
   L_ = Ltmp;
   KALDI_VLOG(2) << "L = " << L_;
   // omit line 10: zero when initialized.
   beta_dash(N, Q) = 1.0; // Line 11.
   for (int32 n = N; n >= 2; n--) {
     for (size_t i = 0; i < pre_[n].size(); i++) {
       const Arc &arc = arcs_[pre_[n][i]];
       int32 s_a = arc.start_node, w_a = arc.word;
       BaseFloat p_a = arc.loglike;
       alpha_dash_arc(0) = alpha_dash(s_a, 0) + l(w_a, 0) + delta(); // line 14.
       for (int32 q = 1; q <= Q; q++) { // this loop == lines 15-18.
         int32 r_q = r(q);
         double a1 = alpha_dash(s_a, q-1) + l(w_a, r_q),
             a2 = alpha_dash(s_a, q) + l(w_a, 0) + delta(),
             a3 = alpha_dash_arc(q-1) + l(0, r_q);
         if (a1 <= a2) {
           if (a1 <= a3) { b_arc[q] = 1; alpha_dash_arc(q) = a1; }
           else { b_arc[q] = 3; alpha_dash_arc(q) = a3; }
         } else {
           if (a2 <= a3) { b_arc[q] = 2; alpha_dash_arc(q) = a2; }
           else { b_arc[q] = 3; alpha_dash_arc(q) = a3; }
         }
       }
       beta_dash_arc.SetZero(); // line 19.
       for (int32 q = Q; q >= 1; q--) {
         // line 21:
         beta_dash_arc(q) += Exp(alpha(s_a) + p_a - alpha(n)) * beta_dash(n, q);
         switch (static_cast<int>(b_arc[q])) { // lines 22 and 23:
           case 1:
             beta_dash(s_a, q-1) += beta_dash_arc(q);
             // next: gamma(q, w(a)) += beta_dash_arc(q)
             AddToMap(w_a, beta_dash_arc(q), &(gamma[q]));
             // next: accumulating times, see decl for tau_b,tau_e
             tau_b(q) += state_times_[s_a] * beta_dash_arc(q);
             tau_e(q) += state_times_[n] * beta_dash_arc(q);
             break;
           case 2:
             beta_dash(s_a, q) += beta_dash_arc(q);
             break;
           case 3:
             beta_dash_arc(q-1) += beta_dash_arc(q);
             // next: gamma(q, epsilon) += beta_dash_arc(q)
             AddToMap(0, beta_dash_arc(q), &(gamma[q]));
             // next: accumulating times, see decl for tau_b,tau_e
             // WARNING: there was an error in Appendix C.  If we followed
             // the instructions there the next line would say state_times_[sa], but
             // it would be wrong.  I will try to publish an erratum.
             tau_b(q) += state_times_[n] * beta_dash_arc(q);
             tau_e(q) += state_times_[n] * beta_dash_arc(q);
             break;
           default:
             KALDI_ERR << "Invalid b_arc value"; // error in code.
         }
       }
       beta_dash_arc(0) += Exp(alpha(s_a) + p_a - alpha(n)) * beta_dash(n, 0);
       beta_dash(s_a, 0) += beta_dash_arc(0); // line 26.
     }
   }
   beta_dash_arc.SetZero(); // line 29.
   for (int32 q = Q; q >= 1; q--) {
     beta_dash_arc(q) += beta_dash(1, q);
     beta_dash_arc(q-1) += beta_dash_arc(q);
     AddToMap(0, beta_dash_arc(q), &(gamma[q]));
     // the statements below are actually redundant because
     // state_times_[1] is zero.
     tau_b(q) += state_times_[1] * beta_dash_arc(q);
     tau_e(q) += state_times_[1] * beta_dash_arc(q);
   }
   for (int32 q = 1; q <= Q; q++) { // a check (line 35)
     double sum = 0.0;
     for (map<int32, double>::iterator iter = gamma[q].begin();
          iter != gamma[q].end(); ++iter) sum += iter->second;
     if (fabs(sum - 1.0) > 0.1)
       KALDI_WARN << "sum of gamma[" << q << ",s] is " << sum;
   }
   // The next part is where we take gamma, and convert
   // to the class member gamma_, which is using a different
   // data structure and indexed from zero, not one.
   gamma_.clear();
   gamma_.resize(Q);
   for (int32 q = 1; q <= Q; q++) {
     for (map<int32, double>::iterator iter = gamma[q].begin();
          iter != gamma[q].end(); ++iter)
       gamma_[q-1].push_back(std::make_pair(iter->first, static_cast<BaseFloat>(iter->second)));
     // sort gamma_[q-1] from largest to smallest posterior.
     GammaCompare comp;
     std::sort(gamma_[q-1].begin(), gamma_[q-1].end(), comp);
   }
   // We do the same conversion for the state times tau_b and tau_e:
   // they get turned into the times_ data member, which has zero-based
   // indexing.
   times_.clear();
   times_.resize(Q);
   for (int32 q = 1; q <= Q; q++) {
     times_[q-1].first = tau_b(q);
     times_[q-1].second = tau_e(q);
     if (times_[q-1].first > times_[q-1].second) // this is quite bad.
       KALDI_WARN << "Times out of order";
     if (q > 1 && times_[q-2].second > times_[q-1].first) {
       // We previously had a warning here, but now we'll just set both
       // those values to their average.  It's quite possible for this
       // condition to happen, but it seems like it would have a bad effect
       // on the downstream processing, so we fix it.
       double avg = 0.5 * (times_[q-2].second + times_[q-1].first);
       times_[q-2].second = times_[q-1].first = avg;
     }
   }
 }
static void AddToMap (int32 i, double d, std::map< int32, double > * gamma) inline static private
Function used to increment map.
Definition at line 136 of file sausages.h.
References rnnlm::d.
Referenced by MinimumBayesRisk::AccStats().
{
     if (d == 0) return;
     std::pair<const int32, double> pr(i, d);
     std::pair<std::map<int32, double>::iterator, bool> ret = gamma->insert(pr);
     if (!ret.second) // not inserted, so add to contents.
       ret.first->second += d;
   }
static BaseFloat delta () inline static private
Definition at line 132 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), and MinimumBayesRisk::EditDistance().
 { return 1.0e-05; } // A constant
double EditDistance (int32 N, int32 Q, Vector< double > & alpha, Matrix< double > & alpha_dash, Vector< double > & alpha_dash_arc) private
Figure 4 of the paper; called from AccStats (Fig. 5)
Definition at line 93 of file sausages.cc.
References MinimumBayesRisk::arcs_, MinimumBayesRisk::delta(), kaldi::Exp(), rnnlm::i, kaldi::kLogZeroDouble, MinimumBayesRisk::l(), kaldi::LogAdd(), MinimumBayesRisk::Arc::loglike, rnnlm::n, MinimumBayesRisk::pre_, MinimumBayesRisk::r(), MinimumBayesRisk::Arc::start_node, and MinimumBayesRisk::Arc::word.
Referenced by MinimumBayesRisk::AccStats().
{
   alpha(1) = 0.0; // = log(1).  Line 5.
   alpha_dash(1, 0) = 0.0; // Line 5.
   for (int32 q = 1; q <= Q; q++)
     alpha_dash(1, q) = alpha_dash(1, q-1) + l(0, r(q)); // Line 7.
   for (int32 n = 2; n <= N; n++) {
     double alpha_n = kLogZeroDouble;
     for (size_t i = 0; i < pre_[n].size(); i++) {
       const Arc &arc = arcs_[pre_[n][i]];
       alpha_n = LogAdd(alpha_n, alpha(arc.start_node) + arc.loglike);
     }
     alpha(n) = alpha_n; // Line 10.
     // Line 11 omitted: matrix was initialized to zero.
     for (size_t i = 0; i < pre_[n].size(); i++) {
       const Arc &arc = arcs_[pre_[n][i]];
       int32 s_a = arc.start_node, w_a = arc.word;
       BaseFloat p_a = arc.loglike;
       for (int32 q = 0; q <= Q; q++) {
         if (q == 0) {
           alpha_dash_arc(q) = // line 15.
               alpha_dash(s_a, q) + l(w_a, 0) + delta();
         } else {  // a1,a2,a3 are the 3 parts of min expression of line 17.
           int32 r_q = r(q);
           double a1 = alpha_dash(s_a, q-1) + l(w_a, r_q),
               a2 = alpha_dash(s_a, q) + l(w_a, 0) + delta(),
               a3 = alpha_dash_arc(q-1) + l(0, r_q);
           alpha_dash_arc(q) = std::min(a1, std::min(a2, a3));
         }
         // line 19:
         alpha_dash(n, q) += Exp(alpha(s_a) + p_a - alpha(n)) * alpha_dash_arc(q);
       }
     }
   }
   return alpha_dash(N, Q); // line 23.
 }
BaseFloat GetBayesRisk () const inline
Returns the expected WER over this sentence (assuming model correctness.
Definition at line 97 of file sausages.h.
References MinimumBayesRisk::L_.
Referenced by main().
 { return L_; }
const std::vector<int32>& GetOneBest () const inline
Definition at line 73 of file sausages.h.
References MinimumBayesRisk::R_.
Referenced by main().
                                              { // gets one-best (with no epsilons)
     return R_;
   }
const std::vector<BaseFloat>& GetOneBestConfidences () const inline
Outputs the confidences for the one-best transcript.
Definition at line 91 of file sausages.h.
References MinimumBayesRisk::one_best_confidences_.
Referenced by main().
{
     return one_best_confidences_;
   }
const std::vector<std::pair<BaseFloat, BaseFloat> >& GetOneBestTimes () const inline
Definition at line 84 of file sausages.h.
References MinimumBayesRisk::one_best_times_.
Referenced by main().
{
     return one_best_times_; // returns average (start,end) times for each bin corresponding
     // to an entry in the one-best output.  This is just the appropriate
     // subsequence of the times in SausageTimes().
   }
const std::vector<std::vector<std::pair<int32, BaseFloat> > >& GetSausageStats () const inline
Definition at line 99 of file sausages.h.
References MinimumBayesRisk::gamma_.
Referenced by main().
{
     return gamma_;
   }
const std::vector<std::pair<BaseFloat, BaseFloat> > GetSausageTimes () const inline
Definition at line 77 of file sausages.h.
References MinimumBayesRisk::times_.
Referenced by main().
{
     return times_; // returns average (start,end) times for each bin (each entry
     // of GetSausageStats()).  Note: if you want the times for the one best,
     // you can work out the one best yourself from the sausage stats and get the times
     // at the same time.
   }
double l (int32 a, int32 b) inline private
The basic edit-distance function l(a,b), as in the paper.
Definition at line 110 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), and MinimumBayesRisk::EditDistance().
 { return (a == b ? 0.0 : 1.0); }
void MbrDecode () private
Minimum-Bayes-Risk Decode. Top-level algorithm. Figure 6 of the paper.
Definition at line 27 of file sausages.cc.
References MinimumBayesRisk::AccStats(), MinimumBayesRisk::do_mbr_, MinimumBayesRisk::gamma_, rnnlm::j, KALDI_VLOG, KALDI_WARN, MinimumBayesRisk::NormalizeEps(), MinimumBayesRisk::one_best_confidences_, MinimumBayesRisk::one_best_times_, MinimumBayesRisk::R_, MinimumBayesRisk::RemoveEps(), and MinimumBayesRisk::times_.
Referenced by MinimumBayesRisk::MinimumBayesRisk().
{
   for (size_t counter = 0; ; counter++) {
     NormalizeEps(&R_);
     AccStats(); // writes to gamma_
     double delta_Q = 0.0; // change in objective function.
     one_best_times_.clear();
     one_best_confidences_.clear();
     // Caution: q in the line below is (q-1) in the algorithm
     // in the paper; both R_ and gamma_ are indexed by q-1.
     for (size_t q = 0; q < R_.size(); q++) {
       if (do_mbr_) { // This loop updates R_ [indexed same as gamma_].
         // gamma_[i] is sorted in reverse order so most likely one is first.
         const vector<pair<int32, BaseFloat> > &this_gamma = gamma_[q];
         double old_gamma = 0, new_gamma = this_gamma[0].second;
         int32 rq = R_[q], rhat = this_gamma[0].first; // rq: old word, rhat: new.
         for (size_t j = 0; j < this_gamma.size(); j++)
           if (this_gamma[j].first == rq) old_gamma = this_gamma[j].second;
         delta_Q += (old_gamma - new_gamma); // will be 0 or negative; a bound on
         // change in error.
         if (rq != rhat)
           KALDI_VLOG(2) << "Changing word " << rq << " to " << rhat;
         R_[q] = rhat;
       }
       if (R_[q] != 0) {
         one_best_times_.push_back(times_[q]);
         BaseFloat confidence = 0.0;
         for (int32 j = 0; j < gamma_[q].size(); j++)
           if (gamma_[q][j].first == R_[q]) confidence = gamma_[q][j].second;
         one_best_confidences_.push_back(confidence);
       }
     }
     KALDI_VLOG(2) << "Iter = " << counter << ", delta-Q = " << delta_Q;
     if (delta_Q == 0) break;
     if (counter > 100) {
       KALDI_WARN << "Iterating too many times in MbrDecode; stopping.";
       break;
     }
   }
   RemoveEps(&R_);
 }
void NormalizeEps (std::vector< int32 > * vec) static private
Definition at line 82 of file sausages.cc.
References rnnlm::i, and MinimumBayesRisk::RemoveEps().
Referenced by MinimumBayesRisk::MbrDecode().
{
   RemoveEps(vec);
   vec->resize(1 + vec->size() * 2);
   int32 s = vec->size();
   for (int32 i = s/2 - 1; i >= 0; i--) {
     (*vec)[i*2 + 1] = (*vec)[i];
     (*vec)[i*2 + 2] = 0;
   }
   (*vec)[0] = 0;
 }
void PrepareLatticeAndInitStats (CompactLattice * clat) private
Definition at line 268 of file sausages.cc.
References MinimumBayesRisk::arcs_, kaldi::CompactLatticeStateTimes(), fst::CreateSuperFinal(), MinimumBayesRisk::Arc::end_node, rnnlm::i, KALDI_ASSERT, KALDI_ERR, MinimumBayesRisk::Arc::loglike, rnnlm::n, MinimumBayesRisk::pre_, MinimumBayesRisk::Arc::start_node, MinimumBayesRisk::state_times_, and MinimumBayesRisk::Arc::word.
Referenced by MinimumBayesRisk::MinimumBayesRisk().
{
   KALDI_ASSERT(clat != NULL);
   CreateSuperFinal(clat); // Add super-final state to clat... this is
   // one of the requirements of the MBR algorithm, as mentioned in the
   // paper (i.e. just one final state).
   // Topologically sort the lattice, if not already sorted.
   kaldi::uint64 props = clat->Properties(fst::kFstProperties, false);
   if (!(props & fst::kTopSorted)) {
     if (fst::TopSort(clat) == false)
       KALDI_ERR << "Cycles detected in lattice.";
   }
   CompactLatticeStateTimes(*clat, &state_times_); // work out times of
   // the states in clat
   state_times_.push_back(0); // we'll convert to 1-based numbering.
   for (size_t i = state_times_.size()-1; i > 0; i--)
     state_times_[i] = state_times_[i-1];
   // Now we convert the information in "clat" into a special internal
   // format (pre_, post_ and arcs_) which allows us to access the
   // arcs preceding any given state.
   // Note: in our internal format the states will be numbered from 1,
   // which involves adding 1 to the OpenFst states.
   int32 N = clat->NumStates();
   pre_.resize(N+1);
   // Careful: "Arc" is a class-member struct, not an OpenFst type of arc as one
   // would normally assume.
   for (int32 n = 1; n <= N; n++) {
     for (fst::ArcIterator<CompactLattice> aiter(*clat, n-1);
          !aiter.Done();
          aiter.Next()) {
       const CompactLatticeArc &carc = aiter.Value();
       Arc arc; // in our local format.
       arc.word = carc.ilabel; // == carc.olabel
       arc.start_node = n;
       arc.end_node = carc.nextstate + 1; // convert to 1-based.
       arc.loglike = - (carc.weight.Weight().Value1() +
                        carc.weight.Weight().Value2());
       // loglike: sum graph/LM and acoustic cost, and negate to
       // convert to loglikes.  We assume acoustic scaling is already done.
       pre_[arc.end_node].push_back(arcs_.size()); // record index of this arc.
       arcs_.push_back(arc);
     }
   }
 }
int32 r (int32 q) inline private
returns r_q, in one-based indexing, as in the paper.
Definition at line 113 of file sausages.h.
References MinimumBayesRisk::R_.
Referenced by MinimumBayesRisk::AccStats(), and MinimumBayesRisk::EditDistance().
 { return R_[q-1]; }
void RemoveEps (std::vector< int32 > * vec) static private
Removes epsilons (symbol 0) from a vector.
Definition at line 75 of file sausages.cc.
Referenced by MinimumBayesRisk::MbrDecode(), and MinimumBayesRisk::NormalizeEps().
{
   Int32IsZero pred;
   vec->erase(std::remove_if (vec->begin(), vec->end(), pred),
              vec->end());
 }
Member Data Documentation
std::vector<Arc> arcs_ private
Arcs in the topologically sorted acceptor form of the word-level lattice, with one final-state.
Contains (word-symbol, log-likelihood on arc == negated cost). Indexed from zero.
Definition at line 159 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), MinimumBayesRisk::EditDistance(), and MinimumBayesRisk::PrepareLatticeAndInitStats().
bool do_mbr_ private
Boolean configuration parameter: if true, we actually update the hypothesis to do MBR decoding (if false, our output is the MAP decoded output, but we output the stats too).
Definition at line 154 of file sausages.h.
Referenced by MinimumBayesRisk::MbrDecode().
std::vector<std::vector<std::pair<int32, BaseFloat> > > gamma_ private
Definition at line 175 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), MinimumBayesRisk::GetSausageStats(), and MinimumBayesRisk::MbrDecode().
double L_ private
Definition at line 172 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), MinimumBayesRisk::GetBayesRisk(), and MinimumBayesRisk::MinimumBayesRisk().
std::vector<BaseFloat> one_best_confidences_ private
Definition at line 191 of file sausages.h.
Referenced by MinimumBayesRisk::GetOneBestConfidences(), and MinimumBayesRisk::MbrDecode().
std::vector<std::pair<BaseFloat, BaseFloat> > one_best_times_ private
Definition at line 186 of file sausages.h.
Referenced by MinimumBayesRisk::GetOneBestTimes(), and MinimumBayesRisk::MbrDecode().
std::vector<std::vector<int32> > pre_ private
For each node in the lattice, a list of arcs entering that node.
Indexed from 1 (first node == 1).
Definition at line 163 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), MinimumBayesRisk::EditDistance(), and MinimumBayesRisk::PrepareLatticeAndInitStats().
std::vector<int32> R_ private
Definition at line 168 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), MinimumBayesRisk::GetOneBest(), MinimumBayesRisk::MbrDecode(), MinimumBayesRisk::MinimumBayesRisk(), and MinimumBayesRisk::r().
std::vector<int32> state_times_ private
Definition at line 165 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), and MinimumBayesRisk::PrepareLatticeAndInitStats().
std::vector<std::pair<BaseFloat, BaseFloat> > times_ private
Definition at line 181 of file sausages.h.
Referenced by MinimumBayesRisk::AccStats(), MinimumBayesRisk::GetSausageTimes(), and MinimumBayesRisk::MbrDecode().
The documentation for this class was generated from the following files:
lat/sausages.h
lat/sausages.cc