Kaldi: VectorRandomizer Class Reference
VectorRandomizer Class Reference
Randomizes elements of a vector according to a mask.
#include <nnet-randomizer.h>
Public Member Functions
VectorRandomizer ()
VectorRandomizer (const NnetDataRandomizerOptions &conf)
void Init (const NnetDataRandomizerOptions &conf)
Set the randomizer parameters (size)
void AddData (const Vector< BaseFloat > &v)
Add data to randomization buffer.
bool IsFull ()
Returns true, when capacity is full.
int32 NumFrames ()
Number of frames stored inside the Randomizer.
void Randomize (const std::vector< int32 > &mask)
Randomize matrix row-order using mask.
bool Done ()
Returns true, if no more data for another mini-batch (after current one)
void Next ()
Sets cursor to next mini-batch.
const Vector< BaseFloat > & Value ()
Returns matrix-window with next mini-batch.
Private Attributes
Vector< BaseFloat > data_
Vector< BaseFloat > minibatch_
int32 data_begin_
Cursor to beginning of data (row index, moves as mini-batches are delivered)
int32 data_end_
Cursor past the end of data (row index)
NnetDataRandomizerOptions conf_
Detailed Description
Randomizes elements of a vector according to a mask.
Definition at line 104 of file nnet-randomizer.h.
Constructor & Destructor Documentation
VectorRandomizer () inline
Definition at line 106 of file nnet-randomizer.h.
 : data_begin_(0), data_end_(0) { }
VectorRandomizer (const NnetDataRandomizerOptions & conf) inline
Definition at line 107 of file nnet-randomizer.h.
References VectorRandomizer::Init().
 : data_begin_(0), data_end_(0) { Init(conf); }
Member Function Documentation
void AddData (const Vector< BaseFloat > & v)
Add data to randomization buffer.
Definition at line 103 of file nnet-randomizer.cc.
References VectorRandomizer::conf_, VectorRandomizer::data_, VectorRandomizer::data_begin_, VectorRandomizer::data_end_, VectorBase< Real >::Dim(), KALDI_ASSERT, NnetDataRandomizerOptions::randomizer_size, VectorBase< Real >::Range(), Vector< Real >::Resize(), and kaldi::nnet3::SetZero().
Referenced by main(), and UnitTestVectorRandomizer().
{
   // pre-allocate before 1st use
   if(data_.Dim() == 0) {
     data_.Resize(conf_.randomizer_size);
   }
   // optionally put previous left-over to front
   if (data_begin_ > 0) {
     KALDI_ASSERT(data_begin_ <= data_end_); // sanity check
     int32 leftover = data_end_ - data_begin_;
     KALDI_ASSERT(leftover < data_begin_); // no overlap
     if(leftover > 0) {
       data_.Range(0,leftover).CopyFromVec(data_.Range(data_begin_,leftover));
     }
     data_begin_ = 0; data_end_ = leftover;
     data_.Range(leftover,data_.Dim()-leftover).SetZero(); // zeroing the rest
   }
   // extend the buffer if necessary
   if(data_.Dim() < data_end_ + v.Dim()) {
     Vector<BaseFloat> data_aux(data_);
     data_.Resize(data_end_ + v.Dim() + 1000); // +1000 row surplus
     data_.Range(0,data_aux.Dim()).CopyFromVec(data_aux);
   }
   // copy the data
   data_.Range(data_end_,v.Dim()).CopyFromVec(v);
   data_end_ += v.Dim();
 }
bool Done () inline
Returns true, if no more data for another mini-batch (after current one)
Definition at line 121 of file nnet-randomizer.h.
References VectorRandomizer::conf_, VectorRandomizer::data_begin_, VectorRandomizer::data_end_, and NnetDataRandomizerOptions::minibatch_size.
Referenced by UnitTestVectorRandomizer().
 { return (data_end_ - data_begin_ < conf_.minibatch_size); }
void Init (const NnetDataRandomizerOptions & conf) inline
Set the randomizer parameters (size)
Definition at line 109 of file nnet-randomizer.h.
References VectorRandomizer::conf_.
Referenced by UnitTestVectorRandomizer(), and VectorRandomizer::VectorRandomizer().
 { conf_ = conf; }
bool IsFull () inline
Returns true, when capacity is full.
Definition at line 114 of file nnet-randomizer.h.
References VectorRandomizer::conf_, VectorRandomizer::data_begin_, VectorRandomizer::data_end_, and NnetDataRandomizerOptions::randomizer_size.
Referenced by UnitTestVectorRandomizer().
 { return ((data_begin_ == 0) && (data_end_ > conf_.randomizer_size )); }
void Next ()
Sets cursor to next mini-batch.
Definition at line 142 of file nnet-randomizer.cc.
References VectorRandomizer::conf_, VectorRandomizer::data_begin_, and NnetDataRandomizerOptions::minibatch_size.
Referenced by main(), and UnitTestVectorRandomizer().
{
   data_begin_ += conf_.minibatch_size;
 }
int32 NumFrames () inline
Number of frames stored inside the Randomizer.
Definition at line 116 of file nnet-randomizer.h.
References VectorRandomizer::data_end_.
Referenced by UnitTestVectorRandomizer().
 { return data_end_; }
void Randomize (const std::vector< int32 > & mask)
Randomize matrix row-order using mask.
Definition at line 130 of file nnet-randomizer.cc.
References VectorRandomizer::data_, VectorRandomizer::data_begin_, VectorRandomizer::data_end_, rnnlm::i, and KALDI_ASSERT.
Referenced by main(), and UnitTestVectorRandomizer().
{
   KALDI_ASSERT(data_begin_ == 0);
   KALDI_ASSERT(data_end_ > 0);
   KALDI_ASSERT(data_end_ == mask.size());
   // Use auxiliary buffer for unshuffled data
   Vector<BaseFloat> data_aux(data_);
   // randomize the data, mask is used to index elements in source vector
   for(int32 i = 0; i<mask.size(); i++) {
     data_(i) = data_aux(mask.at(i));
   }
 }
const Vector< BaseFloat > & Value ()
Returns matrix-window with next mini-batch.
Definition at line 146 of file nnet-randomizer.cc.
References VectorRandomizer::conf_, VectorBase< Real >::CopyFromVec(), VectorRandomizer::data_, VectorRandomizer::data_begin_, VectorRandomizer::data_end_, KALDI_ASSERT, kaldi::kUndefined, VectorRandomizer::minibatch_, NnetDataRandomizerOptions::minibatch_size, VectorBase< Real >::Range(), and Vector< Real >::Resize().
Referenced by main(), and UnitTestVectorRandomizer().
{
   KALDI_ASSERT(data_end_ - data_begin_ >= conf_.minibatch_size); // have data for minibatch
   minibatch_.Resize(conf_.minibatch_size,kUndefined);
   minibatch_.CopyFromVec(data_.Range(data_begin_,conf_.minibatch_size));
   return minibatch_;
 }
Member Data Documentation
NnetDataRandomizerOptions conf_ private
Definition at line 136 of file nnet-randomizer.h.
Referenced by VectorRandomizer::AddData(), VectorRandomizer::Done(), VectorRandomizer::Init(), VectorRandomizer::IsFull(), VectorRandomizer::Next(), and VectorRandomizer::Value().
Vector<BaseFloat> data_ private
Definition at line 128 of file nnet-randomizer.h.
Referenced by VectorRandomizer::AddData(), VectorRandomizer::Randomize(), and VectorRandomizer::Value().
int32 data_begin_ private
Cursor to beginning of data (row index, moves as mini-batches are delivered)
Definition at line 132 of file nnet-randomizer.h.
Referenced by VectorRandomizer::AddData(), VectorRandomizer::Done(), VectorRandomizer::IsFull(), VectorRandomizer::Next(), VectorRandomizer::Randomize(), and VectorRandomizer::Value().
int32 data_end_ private
Cursor past the end of data (row index)
Definition at line 134 of file nnet-randomizer.h.
Referenced by VectorRandomizer::AddData(), VectorRandomizer::Done(), VectorRandomizer::IsFull(), VectorRandomizer::NumFrames(), VectorRandomizer::Randomize(), and VectorRandomizer::Value().
Vector<BaseFloat> minibatch_ private
Definition at line 129 of file nnet-randomizer.h.
Referenced by VectorRandomizer::Value().
The documentation for this class was generated from the following files:
nnet/nnet-randomizer.h
nnet/nnet-randomizer.cc