Kaldi: AdditiveNoiseComponent Class Reference
AdditiveNoiseComponent Class Reference
This is a bit similar to dropout but adding (not multiplying) Gaussian noise with a given standard deviation.
#include <nnet-component.h>
Public Member Functions
void Init (int32 dim, BaseFloat noise_stddev)
AdditiveNoiseComponent (int32 dim, BaseFloat stddev)
AdditiveNoiseComponent ()
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Type () const
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Public Member Functions inherited from RandomComponent
void ResetGenerator ()
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual std::string Info () const
virtual ~Component ()
Private Attributes
int32 dim_
BaseFloat stddev_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Protected Attributes inherited from RandomComponent
CuRand< BaseFloat > random_generator_
Detailed Description
This is a bit similar to dropout but adding (not multiplying) Gaussian noise with a given standard deviation.
Definition at line 1635 of file nnet-component.h.
Constructor & Destructor Documentation
AdditiveNoiseComponent (int32 dim, BaseFloat stddev) inline
Definition at line 1638 of file nnet-component.h.
References AdditiveNoiseComponent::Init().
 { Init(dim, stddev); }
AdditiveNoiseComponent () inline
Definition at line 1639 of file nnet-component.h.
Referenced by AdditiveNoiseComponent::Copy().
 : dim_(0), stddev_(1.0) { }
Member Function Documentation
virtual void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const inline virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 1660 of file nnet-component.h.
                                                              { *in_deriv = out_deriv; }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1650 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1651 of file nnet-component.h.
 { return false; }
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 1652 of file nnet-component.h.
References AdditiveNoiseComponent::AdditiveNoiseComponent(), AdditiveNoiseComponent::dim_, and AdditiveNoiseComponent::stddev_.
{
     return new AdditiveNoiseComponent(dim_, stddev_);
   }
void Init (int32 dim, BaseFloat noise_stddev)
Definition at line 3667 of file nnet-component.cc.
References AdditiveNoiseComponent::dim_, and AdditiveNoiseComponent::stddev_.
Referenced by AdditiveNoiseComponent::AdditiveNoiseComponent(), and AdditiveNoiseComponent::InitFromString().
{
   dim_ = dim;
   stddev_ = stddev;
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 3637 of file nnet-component.cc.
References AdditiveNoiseComponent::Init(), KALDI_ERR, and kaldi::nnet2::ParseFromString().
Referenced by kaldi::nnet2::UnitTestAdditiveNoiseComponent().
{
   std::string orig_args(args);
   int32 dim;
   BaseFloat stddev = 1.0;
   bool ok = ParseFromString("dim", &args, &dim);
   ParseFromString("stddev", &args, &stddev);
   if (!ok || !args.empty() || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type AdditiveNoiseComponent: \""
               << orig_args << "\"";
   Init(dim, stddev);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1640 of file nnet-component.h.
References AdditiveNoiseComponent::dim_.
Referenced by AdditiveNoiseComponent::Propagate().
 { return dim_; }
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1641 of file nnet-component.h.
References AdditiveNoiseComponent::dim_.
 { return dim_; }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 3672 of file nnet-component.cc.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::CopyFromMat(), AdditiveNoiseComponent::InputDim(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), RandomComponent::random_generator_, kaldi::RandUniform(), and AdditiveNoiseComponent::stddev_.
{
   KALDI_ASSERT(in.NumCols() == this->InputDim());
   out->CopyFromMat(in);
   CuMatrix<BaseFloat> rand(in.NumRows(), in.NumCols());
   const_cast<CuRand<BaseFloat>&>(random_generator_).RandUniform(&rand);
   out->AddMat(stddev_, rand);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 3650 of file nnet-component.cc.
References AdditiveNoiseComponent::dim_, kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), kaldi::ReadBasicType(), and AdditiveNoiseComponent::stddev_.
{
   ExpectOneOrTwoTokens(is, binary, "<AdditiveNoiseComponent>", "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<Stddev>");
   ReadBasicType(is, binary, &stddev_);
   ExpectToken(is, binary, "</AdditiveNoiseComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1648 of file nnet-component.h.
 { return "AdditiveNoiseComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3658 of file nnet-component.cc.
References AdditiveNoiseComponent::dim_, AdditiveNoiseComponent::stddev_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<AdditiveNoiseComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<Stddev>");
   WriteBasicType(os, binary, stddev_);
   WriteToken(os, binary, "</AdditiveNoiseComponent>");
 }
Member Data Documentation
int32 dim_ private
Definition at line 1668 of file nnet-component.h.
Referenced by AdditiveNoiseComponent::Copy(), AdditiveNoiseComponent::Init(), AdditiveNoiseComponent::InputDim(), AdditiveNoiseComponent::OutputDim(), AdditiveNoiseComponent::Read(), and AdditiveNoiseComponent::Write().
BaseFloat stddev_ private
Definition at line 1669 of file nnet-component.h.
Referenced by AdditiveNoiseComponent::Copy(), AdditiveNoiseComponent::Init(), AdditiveNoiseComponent::Propagate(), AdditiveNoiseComponent::Read(), and AdditiveNoiseComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc