Kaldi: InputImplBase Class Reference
InputImplBase Class Reference abstract
Public Member Functions
virtual bool Open (const std::string &filename, bool binary)=0
virtual std::istream & Stream ()=0
virtual void Close ()=0
virtual InputType MyType ()=0
virtual ~InputImplBase ()
Detailed Description
Definition at line 343 of file kaldi-io.cc.
Constructor & Destructor Documentation
virtual ~InputImplBase () inline virtual
Definition at line 361 of file kaldi-io.cc.
 { }
Member Function Documentation
virtual void Close () pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
virtual InputType MyType () pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::OpenInternal().
virtual bool Open (const std::string & filename, bool binary) pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::OpenInternal().
virtual std::istream& Stream () pure virtual
Implemented in OffsetFileInputImpl, PipeInputImpl, StandardInputImpl, and FileInputImpl.
Referenced by Input::OpenInternal(), and Input::Stream().
The documentation for this class was generated from the following file:
util/kaldi-io.cc