Kaldi: SpliceMaxComponent Class Reference
SpliceMaxComponent Class Reference
This is as SpliceComponent but outputs the max of any of the inputs (taking the max across time).
#include <nnet-component.h>
Public Member Functions
SpliceMaxComponent ()
void Init (int32 dim, std::vector< int32 > context)
virtual std::string Type () const
virtual std::string Info () const
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (SpliceMaxComponent)
Private Attributes
int32 dim_
std::vector< int32 > context_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
This is as SpliceComponent but outputs the max of any of the inputs (taking the max across time).
Definition at line 1133 of file nnet-component.h.
Constructor & Destructor Documentation
SpliceMaxComponent () inline
Definition at line 1135 of file nnet-component.h.
Referenced by SpliceMaxComponent::Copy().
 { }  // called only prior to Read() or Init().
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 2944 of file nnet-component.cc.
References ChunkInfo::Check(), ChunkInfo::CheckSize(), ChunkInfo::ChunkSize(), SpliceMaxComponent::context_, ChunkInfo::GetIndex(), ChunkInfo::GetOffset(), SpliceMaxComponent::InputDim(), KALDI_ASSERT, ChunkInfo::NumChunks(), ChunkInfo::NumCols(), CuMatrixBase< Real >::NumCols(), ChunkInfo::NumRows(), CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
Referenced by kaldi::nnet2::BasicDebugTestForSpliceMax().
{
   in_info.Check();
   out_info.Check();
   in_info.CheckSize(in_value);
   out_info.CheckSize(out_deriv);
   in_deriv->Resize(in_info.NumRows(), in_info.NumCols());
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   int32 out_chunk_size = out_info.ChunkSize(),
          in_chunk_size = in_info.ChunkSize(),
                       dim = out_deriv.NumCols();
   KALDI_ASSERT(dim == InputDim());
   for (int32 chunk = 0; chunk < in_info.NumChunks(); chunk++) {
     CuSubMatrix<BaseFloat> in_deriv_chunk(*in_deriv,
                                         chunk * in_chunk_size,
                                         in_chunk_size,
                                         0, dim),
                          in_value_chunk(in_value,
                                         chunk * in_chunk_size,
                                         in_chunk_size,
                                         0, dim),
                         out_deriv_chunk(out_deriv,
                                         chunk * out_chunk_size,
                                         out_chunk_size,
                                         0, dim);
     for (int32 r = 0; r < out_deriv_chunk.NumRows(); r++) {
       int32 out_chunk_ind = r;
       int32 out_chunk_offset =
           out_info.GetOffset(out_chunk_ind);
       for (int32 c = 0; c < dim; c++) {
         int32 in_r_max = -1;
         BaseFloat max_input = -std::numeric_limits<BaseFloat>::infinity();
         for (int32 context_ind = 0;
              context_ind < context_.size(); context_ind++) {
           int32 in_r =
               in_info.GetIndex(out_chunk_offset + context_[context_ind]);
           BaseFloat input = in_value_chunk(in_r, c);
           if (input > max_input) {
             max_input = input;
             in_r_max = in_r;
           }
         }
         KALDI_ASSERT(in_r_max != -1);
         (*in_deriv)(in_r_max, c) += out_deriv_chunk(r, c);
       }
     }
   }
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1156 of file nnet-component.h.
 { return true; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1157 of file nnet-component.h.
 { return false; }
virtual std::vector<int32> Context () const inline virtual
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
The default implementation returns a vector (0), but a splicing layer might return e.g. (-2, -1, 0, 1, 2), but it doesn't have to be contiguous. Note : The context needed by the entire network is a function of the contexts needed by all the components. It is required that Context().front() <= 0 and Context().back() >= 0.
Reimplemented from Component.
Definition at line 1143 of file nnet-component.h.
References SpliceMaxComponent::context_.
 { return context_; }
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 3002 of file nnet-component.cc.
References SpliceMaxComponent::context_, SpliceMaxComponent::dim_, SpliceMaxComponent::Init(), and SpliceMaxComponent::SpliceMaxComponent().
{
   SpliceMaxComponent *ans = new SpliceMaxComponent();
   ans->Init(dim_, context_);
   return ans;
 }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 2858 of file nnet-component.cc.
References SpliceMaxComponent::context_, and Component::Info().
{
   std::stringstream stream;
   std::ostringstream os;
   std::copy(context_.begin(), context_.end(),
             std::ostream_iterator<int32>(os, " "));
   stream << Component::Info() << ", context=" << os.str();
   return stream.str();
 }
void Init (int32 dim, std::vector< int32 > context)
Definition at line 2867 of file nnet-component.cc.
References SpliceMaxComponent::context_, SpliceMaxComponent::dim_, and KALDI_ASSERT.
Referenced by kaldi::nnet2::BasicDebugTestForSpliceMax(), SpliceMaxComponent::Copy(), and SpliceMaxComponent::InitFromString().
{
   dim_ = dim;
   context_ = context;
   KALDI_ASSERT(dim_ > 0 && context_.front() <= 0 && context_.back() >= 0);
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 2876 of file nnet-component.cc.
References rnnlm::i, SpliceMaxComponent::Init(), KALDI_ASSERT, KALDI_ERR, kaldi::nnet2::ParseFromString(), and SpliceMaxComponent::Type().
{
   std::string orig_args(args);
   int32 dim, left_context, right_context;
   std::vector <int32> context;
   bool dim_ok = ParseFromString("dim", &args, &dim);
   bool context_ok = ParseFromString("context", &args, &context);
   bool left_right_context_ok = ParseFromString("left-context",
                                                &args, &left_context) &&
                                ParseFromString("right-context", &args,
                                                &right_context);
   if (!(dim_ok && (context_ok || left_right_context_ok)) ||
       !args.empty() || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   if (left_right_context_ok)  {
     KALDI_ASSERT(context.size() == 0);
     for (int32 i = -1 * left_context; i <= right_context; i++)
       context.push_back(i);
   }
   Init(dim, context);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1141 of file nnet-component.h.
References SpliceMaxComponent::dim_.
Referenced by SpliceMaxComponent::Backprop().
 { return dim_; }
KALDI_DISALLOW_COPY_AND_ASSIGN (SpliceMaxComponent) private
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1142 of file nnet-component.h.
References SpliceMaxComponent::dim_.
Referenced by kaldi::nnet2::BasicDebugTestForSpliceMax().
 { return dim_; }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 2900 of file nnet-component.cc.
References ChunkInfo::Check(), ChunkInfo::CheckSize(), ChunkInfo::ChunkSize(), SpliceMaxComponent::context_, CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyRows(), ChunkInfo::GetIndex(), ChunkInfo::GetOffset(), rnnlm::i, KALDI_ASSERT, CuMatrixBase< Real >::Max(), ChunkInfo::NumChunks(), and ChunkInfo::NumCols().
Referenced by kaldi::nnet2::BasicDebugTestForSpliceMax().
{
   in_info.Check();
   out_info.Check();
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   int32 in_chunk_size  = in_info.ChunkSize(),
         out_chunk_size = out_info.ChunkSize(),
         dim = in_info.NumCols();
   CuMatrix<BaseFloat> input_chunk_part(out_chunk_size, dim);
   for (int32 chunk = 0; chunk < in_info.NumChunks(); chunk++) {
     CuSubMatrix<BaseFloat> input_chunk(in,
                                      chunk * in_chunk_size, in_chunk_size,
                                      0, dim),
                         output_chunk(*out,
                                      chunk * out_chunk_size,
                                      out_chunk_size, 0, dim);
     for (int32 offset = 0; offset < context_.size(); offset++) {
       // computing the indices to copy into input_chunk_part from input_chunk
       // copy the rows of the input matrix which correspond to the current
       // context index
       std::vector<int32> input_chunk_inds(out_chunk_size);
       for (int32 i = 0; i < out_chunk_size; i++) {
         int32 out_chunk_ind  = i;
         int32 out_chunk_offset =
             out_info.GetOffset(out_chunk_ind);
         input_chunk_inds[i] =
             in_info.GetIndex(out_chunk_offset + context_[offset]);
       }
       CuArray<int32> cu_chunk_inds(input_chunk_inds);
       input_chunk_part.CopyRows(input_chunk, cu_chunk_inds);
       if (offset == 0)  {
         output_chunk.CopyFromMat(input_chunk_part);
       } else {
         output_chunk.Max(input_chunk_part);
       }
     }
   }
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 3008 of file nnet-component.cc.
References SpliceMaxComponent::context_, SpliceMaxComponent::dim_, kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), rnnlm::i, KALDI_ERR, kaldi::ReadBasicType(), kaldi::ReadIntegerVector(), and kaldi::ReadToken().
{
   ExpectOneOrTwoTokens(is, binary, "<SpliceMaxComponent>", "<Dim>");
   ReadBasicType(is, binary, &dim_);
   std::string token;
   ReadToken(is, false, &token);
   if (token == "<LeftContext>") {
     int32 left_context = 0, right_context = 0;
     std::vector<int32> context;
     ReadBasicType(is, binary, &left_context);
     ExpectToken(is, binary, "<RightContext>");
     ReadBasicType(is, binary, &right_context);
     for (int32 i = -1 * left_context; i <= right_context; i++)
       context.push_back(i);
     context_ = context;
   } else  if (token == "<Context>") {
     ReadIntegerVector(is, binary, &context_);
   } else  {
     KALDI_ERR << "Unknown token" << token << ", the model might be corrupted";
   }
   ExpectToken(is, binary, "</SpliceMaxComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1138 of file nnet-component.h.
Referenced by SpliceMaxComponent::InitFromString().
 { return "SpliceMaxComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3030 of file nnet-component.cc.
References SpliceMaxComponent::context_, SpliceMaxComponent::dim_, kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<SpliceMaxComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<Context>");
   WriteIntegerVector(os, binary, context_);
   WriteToken(os, binary, "</SpliceMaxComponent>");
 }
Member Data Documentation
std::vector<int32> context_ private
Definition at line 1164 of file nnet-component.h.
Referenced by SpliceMaxComponent::Backprop(), SpliceMaxComponent::Context(), SpliceMaxComponent::Copy(), SpliceMaxComponent::Info(), SpliceMaxComponent::Init(), SpliceMaxComponent::Propagate(), SpliceMaxComponent::Read(), and SpliceMaxComponent::Write().
int32 dim_ private
Definition at line 1163 of file nnet-component.h.
Referenced by SpliceMaxComponent::Copy(), SpliceMaxComponent::Init(), SpliceMaxComponent::InputDim(), SpliceMaxComponent::OutputDim(), SpliceMaxComponent::Read(), and SpliceMaxComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc