Kaldi: KaldiObjectHolder< KaldiType > Class Template Reference
KaldiObjectHolder< KaldiType > Class Template Reference
"Holder types"
KaldiObjectHolder works for Kaldi objects that have the "standard" Read and Write functions, and a copy constructor.
#include <kaldi-holder-inl.h>
Public Types
typedef KaldiType T
Public Member Functions
KaldiObjectHolder ()
void Clear ()
bool Read (std::istream &is)
const T & Value () const
~KaldiObjectHolder ()
Static Public Member Functions
static bool Write (std::ostream &os, bool binary, const T &t)
static bool IsReadInBinary ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (KaldiObjectHolder)
Private Attributes
T * t_
Detailed Description
template<class KaldiType>
class kaldi::KaldiObjectHolder< KaldiType >
KaldiObjectHolder works for Kaldi objects that have the "standard" Read and Write functions, and a copy constructor.
Definition at line 42 of file kaldi-holder-inl.h.
Member Typedef Documentation
typedef KaldiType T
Definition at line 44 of file kaldi-holder-inl.h.
Constructor & Destructor Documentation
KaldiObjectHolder () inline
Definition at line 46 of file kaldi-holder-inl.h.
 : t_(NULL) { }
~KaldiObjectHolder () inline
Definition at line 100 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
 { delete t_; }
Member Function Documentation
void Clear () inline
Definition at line 60 of file kaldi-holder-inl.h.
References KaldiObjectHolder< KaldiType >::t_.
                {
     if (t_) {
       delete t_;
       t_ = NULL;
     }
   }
static bool IsReadInBinary () inline static
Definition at line 92 of file kaldi-holder-inl.h.
 { return true; }
KALDI_DISALLOW_COPY_AND_ASSIGN (KaldiObjectHolder< KaldiType >) private
bool Read (std::istream & is) inline
Definition at line 68 of file kaldi-holder-inl.h.
References kaldi::InitKaldiInputStream(), kaldi::IsKaldiError(), KALDI_WARN, and KaldiObjectHolder< KaldiType >::t_.
{
     delete t_;
     t_ = new T;
     // Don't want any existing state to complicate the read functioN: get new
     // object.
     bool is_binary;
     if (!InitKaldiInputStream(is, &is_binary)) {
       KALDI_WARN << "Reading Table object, failed reading binary header\n";
       return false;
     }
     try {
       t_->Read(is, is_binary);
       return true;
     } catch(const std::exception &e) {
       KALDI_WARN << "Exception caught reading Table object ";
       if (!IsKaldiError(e.what())) { std::cerr << e.what(); }
       delete t_;
       t_ = NULL;
       return false;
     }
   }
const T& Value () const inline
Definition at line 94 of file kaldi-holder-inl.h.
References KALDI_ERR, and KaldiObjectHolder< KaldiType >::t_.
{
     // code error if !t_.
     if (!t_) KALDI_ERR << "KaldiObjectHolder::Value() called wrongly.";
     return *t_;
   }
static bool Write (std::ostream & os, bool binary, const T & t) inline static
Definition at line 48 of file kaldi-holder-inl.h.
References kaldi::InitKaldiOutputStream(), kaldi::IsKaldiError(), and KALDI_WARN.
{
     InitKaldiOutputStream(os, binary);  // Puts binary header if binary mode.
     try {
       t.Write(os, binary);
       return os.good();
     } catch(const std::exception &e) {
       KALDI_WARN << "Exception caught writing Table object: " << e.what();
       if (!IsKaldiError(e.what())) { std::cerr << e.what(); }
       return false;  // Write failure.
     }
   }
Member Data Documentation
T* t_ private
Definition at line 103 of file kaldi-holder-inl.h.
Referenced by KaldiObjectHolder< KaldiType >::Clear(), KaldiObjectHolder< KaldiType >::Read(), KaldiObjectHolder< KaldiType >::Value(), and KaldiObjectHolder< KaldiType >::~KaldiObjectHolder().
The documentation for this class was generated from the following file:
util/kaldi-holder-inl.h