Kaldi: ElementwiseProductComponent Class Reference
ElementwiseProductComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
void Init (int32 input_dim, int32 output_dim)
ElementwiseProductComponent (int32 input_dim, int32 output_dim)
virtual int32 Properties () const
Return bitmask of the component's properties.
ElementwiseProductComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
Component ()
virtual ~Component ()
Protected Attributes
int32 input_dim_
int32 output_dim_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 81 of file nnet-simple-component.h.
Constructor & Destructor Documentation
ElementwiseProductComponent (int32 input_dim, int32 output_dim) inline explicit
Definition at line 84 of file nnet-simple-component.h.
References ElementwiseProductComponent::Init().
{
     Init(input_dim, output_dim);
   }
ElementwiseProductComponent () inline
Definition at line 90 of file nnet-simple-component.h.
Referenced by ElementwiseProductComponent::Copy().
 : input_dim_(0), output_dim_(0) { }
Member Function Documentation
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 198 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, ElementwiseProductComponent::input_dim_, rnnlm::j, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::NumRows(), and ElementwiseProductComponent::output_dim_.
{
   if (!in_deriv)  return;
   int32 num_inputs = input_dim_ / output_dim_;
   for (int32 i = 0; i < num_inputs; i++)  {
     CuSubMatrix<BaseFloat> current_in_deriv(*in_deriv, 0, in_deriv->NumRows(),
                                             i * output_dim_,
                                             output_dim_);
     current_in_deriv.CopyFromMat(out_deriv);
     for (int32 j = 0; j < num_inputs; j++)  {
       if (i == j)
         continue;
       CuSubMatrix<BaseFloat> in_value_partition(in_value, 0,
                                                 in_value.NumRows(),
                                                 j * output_dim_,
                                                 output_dim_);
       current_in_deriv.MulElements(in_value_partition);
     }
   }
 }
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 105 of file nnet-simple-component.h.
References ElementwiseProductComponent::ElementwiseProductComponent(), ElementwiseProductComponent::input_dim_, and ElementwiseProductComponent::output_dim_.
                                   { return new ElementwiseProductComponent(input_dim_,
                                                               output_dim_); }
void Init (int32 input_dim, int32 output_dim)
Definition at line 162 of file nnet-simple-component.cc.
References ElementwiseProductComponent::input_dim_, KALDI_ASSERT, and ElementwiseProductComponent::output_dim_.
Referenced by ElementwiseProductComponent::ElementwiseProductComponent(), and ElementwiseProductComponent::InitFromConfig().
{
   input_dim_ = input_dim;
   output_dim_ = output_dim;
   KALDI_ASSERT(input_dim_ > 0 && output_dim_ >= 0);
   KALDI_ASSERT(input_dim_ > output_dim_);
   KALDI_ASSERT(input_dim_ % output_dim_ == 0);
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 170 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), ElementwiseProductComponent::Init(), KALDI_ERR, ElementwiseProductComponent::Type(), and ConfigLine::WholeLine().
{
   int32 input_dim = 0;
   int32 output_dim = 0;
   bool ok = cfl->GetValue("output-dim", &output_dim) &&
       cfl->GetValue("input-dim", &input_dim);
   if (!ok || cfl->HasUnusedValues() || output_dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(input_dim, output_dim);
 }
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 93 of file nnet-simple-component.h.
References ElementwiseProductComponent::input_dim_.
 { return input_dim_; }
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 94 of file nnet-simple-component.h.
References ElementwiseProductComponent::output_dim_.
 { return output_dim_; }
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Implements Component.
Definition at line 181 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, ElementwiseProductComponent::input_dim_, KALDI_ASSERT, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and ElementwiseProductComponent::output_dim_.
{
   KALDI_ASSERT(in.NumCols() == input_dim_);
   int32 num_inputs = input_dim_ / output_dim_;
   for (int32 i = 0; i < num_inputs; i++)  {
     CuSubMatrix<BaseFloat> current_in(in, 0, in.NumRows(),
                                       i * output_dim_, output_dim_);
     if (i == 0) {
       out->CopyFromMat(current_in);
     } else  {
       out->MulElements(current_in);
     }
   }
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 87 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropNeedsInput, and kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent|kBackpropNeedsInput;
   }
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 224 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), ElementwiseProductComponent::input_dim_, ElementwiseProductComponent::output_dim_, and kaldi::ReadBasicType().
{
   ExpectOneOrTwoTokens(is, binary, "<ElementwiseProductComponent>",
                        "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<OutputDim>");
   ReadBasicType(is, binary, &output_dim_);
   ExpectToken(is, binary, "</ElementwiseProductComponent>");
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 91 of file nnet-simple-component.h.
Referenced by ElementwiseProductComponent::InitFromConfig().
 { return "ElementwiseProductComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 233 of file nnet-simple-component.cc.
References ElementwiseProductComponent::input_dim_, ElementwiseProductComponent::output_dim_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<ElementwiseProductComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, output_dim_);
   WriteToken(os, binary, "</ElementwiseProductComponent>");
 }
Member Data Documentation
int32 input_dim_ protected
Definition at line 115 of file nnet-simple-component.h.
Referenced by ElementwiseProductComponent::Backprop(), ElementwiseProductComponent::Copy(), ElementwiseProductComponent::Init(), ElementwiseProductComponent::InputDim(), ElementwiseProductComponent::Propagate(), ElementwiseProductComponent::Read(), and ElementwiseProductComponent::Write().
int32 output_dim_ protected
Definition at line 116 of file nnet-simple-component.h.
Referenced by ElementwiseProductComponent::Backprop(), ElementwiseProductComponent::Copy(), ElementwiseProductComponent::Init(), ElementwiseProductComponent::OutputDim(), ElementwiseProductComponent::Propagate(), ElementwiseProductComponent::Read(), and ElementwiseProductComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc