Kaldi: ScaleComponent Class Reference
ScaleComponent Class Reference
#include <nnet-component.h>
Public Member Functions
ScaleComponent (int32 dim, BaseFloat scale)
ScaleComponent (const ScaleComponent &other)
ScaleComponent ()
virtual std::string Type () const
virtual Component * Copy () const
Copy component (deep copy).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
void Init (int32 dim, BaseFloat scale)
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual std::string Info () const
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Private Member Functions
ScaleComponent & operator= (const ScaleComponent &other)
Private Attributes
int32 dim_
BaseFloat scale_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
Definition at line 730 of file nnet-component.h.
Constructor & Destructor Documentation
ScaleComponent (int32 dim, BaseFloat scale) inline explicit
Definition at line 732 of file nnet-component.h.
 : dim_(dim), scale_(scale) { }
ScaleComponent (const ScaleComponent & other) inline explicit
Definition at line 733 of file nnet-component.h.
                                                       :
       dim_(other.dim_), scale_(other.scale_) { }
ScaleComponent () inline
Definition at line 735 of file nnet-component.h.
Referenced by ScaleComponent::Copy().
 : dim_(0), scale_(0.0) { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 867 of file nnet-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrix< Real >::Resize(), CuMatrixBase< Real >::Scale(), and ScaleComponent::scale_.
{
   in_deriv->Resize(out_deriv.NumRows(), out_deriv.NumCols(),
                    kUndefined);
   in_deriv->CopyFromMat(out_deriv);
   in_deriv->Scale(scale_);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 738 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 739 of file nnet-component.h.
 { return false; }
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 737 of file nnet-component.h.
References ScaleComponent::ScaleComponent().
 { return new ScaleComponent(*this); }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 916 of file nnet-component.cc.
References ScaleComponent::dim_, ScaleComponent::scale_, and ScaleComponent::Type().
{
   std::stringstream stream;
   stream << Type() << ", dim=" << dim_ << ", scale=" << scale_;
   return stream.str();
 }
void Init (int32 dim, BaseFloat scale)
Definition at line 881 of file nnet-component.cc.
References ScaleComponent::dim_, KALDI_ASSERT, and ScaleComponent::scale_.
Referenced by ScaleComponent::InitFromString(), and kaldi::nnet2::UnitTestScaleComponent().
{
   dim_ = dim;
   scale_ = scale;
   KALDI_ASSERT(dim_ > 0);
   KALDI_ASSERT(scale_ != 0.0);
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 888 of file nnet-component.cc.
References ScaleComponent::Init(), KALDI_ERR, and kaldi::nnet2::ParseFromString().
Referenced by kaldi::nnet2::UnitTestScaleComponent().
{
   std::string orig_args(args);
   int32 dim;
   BaseFloat scale;
   if (!ParseFromString("dim", &args, &dim))
     KALDI_ERR << "Dimension not specified for ScaleComponent in config file";
   if (!ParseFromString("scale", &args, &scale))
     KALDI_ERR << "Scale not specified for ScaleComponent in config file";
   Init(dim, scale);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 753 of file nnet-component.h.
References ScaleComponent::dim_.
 { return dim_; }
ScaleComponent& operator= (const ScaleComponent & other) private
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 754 of file nnet-component.h.
References ScaleComponent::dim_.
 { return dim_; }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 859 of file nnet-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::Scale(), and ScaleComponent::scale_.
{
   out->CopyFromMat(in);
   out->Scale(scale_);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 908 of file nnet-component.cc.
References ScaleComponent::dim_, kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), kaldi::ReadBasicType(), and ScaleComponent::scale_.
{
   ExpectOneOrTwoTokens(is, binary, "<ScaleComponent>", "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<Scale>");
   ReadBasicType(is, binary, &scale_);
   ExpectToken(is, binary, "</ScaleComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 736 of file nnet-component.h.
Referenced by ScaleComponent::Info().
 { return "ScaleComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 899 of file nnet-component.cc.
References ScaleComponent::dim_, ScaleComponent::scale_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<ScaleComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<Scale>");
   WriteBasicType(os, binary, scale_);
   WriteToken(os, binary, "</ScaleComponent>");
 }
Member Data Documentation
int32 dim_ private
Definition at line 766 of file nnet-component.h.
Referenced by ScaleComponent::Info(), ScaleComponent::Init(), ScaleComponent::InputDim(), ScaleComponent::OutputDim(), ScaleComponent::Read(), and ScaleComponent::Write().
BaseFloat scale_ private
Definition at line 767 of file nnet-component.h.
Referenced by ScaleComponent::Backprop(), ScaleComponent::Info(), ScaleComponent::Init(), ScaleComponent::Propagate(), ScaleComponent::Read(), and ScaleComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc