Kaldi: RandomAccessTableReaderUnsortedArchiveImpl< Holder > Class Template Reference
RandomAccessTableReaderUnsortedArchiveImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Member Functions
RandomAccessTableReaderUnsortedArchiveImpl ()
virtual bool Close ()
virtual bool HasKey (const std::string &key)
virtual const T & Value (const std::string &key)
virtual ~RandomAccessTableReaderUnsortedArchiveImpl ()
Public Member Functions inherited from RandomAccessTableReaderArchiveImplBase< Holder >
RandomAccessTableReaderArchiveImplBase ()
virtual bool Open (const std::string &rspecifier)
void ReadNextObject ()
virtual bool IsOpen () const
bool CloseInternal ()
~RandomAccessTableReaderArchiveImplBase ()
Public Member Functions inherited from RandomAccessTableReaderImplBase< Holder >
virtual ~RandomAccessTableReaderImplBase ()
Private Types
typedef Holder::T T
typedef unordered_map
< std::string, Holder
*, StringHasher > MapType
Private Member Functions
void HandlePendingDelete ()
bool FindKeyInternal (const std::string &key, const T **value_ptr=NULL)
Private Attributes
MapType map_
MapType::iterator to_delete_iter_
bool to_delete_iter_valid_
std::string first_deleted_string_
Additional Inherited Members
Public Types inherited from RandomAccessTableReaderArchiveImplBase< Holder >
typedef Holder::T T
Public Types inherited from RandomAccessTableReaderImplBase< Holder >
typedef Holder::T T
Protected Types inherited from RandomAccessTableReaderArchiveImplBase< Holder >
enum {
kUninitialized, kNoObject, kHaveObject, kEof,
kError
}
Protected Attributes inherited from RandomAccessTableReaderArchiveImplBase< Holder >
std::string cur_key_
Holder * holder_
std::string rspecifier_
std::string archive_rxfilename_
RspecifierOptions opts_
enum
kaldi::RandomAccessTableReaderArchiveImplBase:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::RandomAccessTableReaderUnsortedArchiveImpl< Holder >
Definition at line 1979 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef unordered_map<std::string, Holder*, StringHasher> MapType private
Definition at line 2115 of file kaldi-table-inl.h.
typedef Holder::T T private
Definition at line 1994 of file kaldi-table-inl.h.
Constructor & Destructor Documentation
RandomAccessTableReaderUnsortedArchiveImpl () inline
Definition at line 1997 of file kaldi-table-inl.h.
References RandomAccessTableReaderUnsortedArchiveImpl< Holder >::map_.
                                               : to_delete_iter_(map_.end()),
                                                 to_delete_iter_valid_(false) {
     map_.max_load_factor(0.5);  // make it quite empty -> quite efficient.
     // default seems to be 1.
   }
virtual ~RandomAccessTableReaderUnsortedArchiveImpl () inline virtual
Definition at line 2029 of file kaldi-table-inl.h.
References RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Close(), RandomAccessTableReaderArchiveImplBase< Holder >::IsOpen(), KALDI_ERR, and RandomAccessTableReaderArchiveImplBase< Holder >::rspecifier_.
{
     if (this->IsOpen())
       if (!Close())  // more specific warning will already have been printed.
         // we are in some kind of error state & user did not find out by
         // calling Close().
         KALDI_ERR << "Error closing RandomAccessTableReader: rspecifier is "
                   << rspecifier_;
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 2003 of file kaldi-table-inl.h.
References RandomAccessTableReaderArchiveImplBase< Holder >::CloseInternal(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::first_deleted_string_, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::map_, and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::to_delete_iter_valid_.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::~RandomAccessTableReaderUnsortedArchiveImpl().
{
     for (typename MapType::iterator iter = map_.begin();
         iter != map_.end();
         ++iter) {
       delete iter->second;
     }
     map_.clear();
     first_deleted_string_ = "";
     to_delete_iter_valid_ = false;
     return this->CloseInternal();
   }
bool FindKeyInternal (const std::string & key, const T ** value_ptr = NULL) inline private
Definition at line 2058 of file kaldi-table-inl.h.
References RandomAccessTableReaderArchiveImplBase< Holder >::archive_rxfilename_, RandomAccessTableReaderArchiveImplBase< Holder >::cur_key_, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::first_deleted_string_, RandomAccessTableReaderArchiveImplBase< Holder >::holder_, KALDI_ASSERT, KALDI_ERR, RandomAccessTableReaderArchiveImplBase< Holder >::kHaveObject, RandomAccessTableReaderArchiveImplBase< Holder >::kNoObject, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::map_, RspecifierOptions::once, RandomAccessTableReaderArchiveImplBase< Holder >::opts_, RandomAccessTableReaderArchiveImplBase< Holder >::ReadNextObject(), RandomAccessTableReaderArchiveImplBase< Holder >::rspecifier_, RandomAccessTableReaderArchiveImplBase< Holder >::state_, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::to_delete_iter_, and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::to_delete_iter_valid_.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HasKey(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Value().
{
     typename MapType::iterator iter = map_.find(key);
     if (iter != map_.end()) {  // Found in the map...
       if (value_ptr == NULL) {  // called from HasKey
         return true;  // this is all we have to do.
       } else {
         *value_ptr = &(iter->second->Value());
         if (opts_.once) {  // value won't be needed again, so mark
           // for deletion.
           to_delete_iter_ = iter;  // pending delete.
           KALDI_ASSERT(!to_delete_iter_valid_);
           to_delete_iter_valid_ = true;
         }
         return true;
       }
     }
     while (state_ == kNoObject) {
       ReadNextObject();
       if (state_ == kHaveObject) {  // Successfully read object.
         state_ = kNoObject;  // we are about to transfer ownership
         // of the object in holder_ to map_.
         // Insert it into map_.
         std::pair<typename MapType::iterator, bool> pr =
             map_.insert(typename MapType::value_type(cur_key_, holder_));
         if (!pr.second) {  // Was not inserted-- previous element w/ same key
           delete holder_;  // map was not changed, no ownership transferred.
           holder_ = NULL;
           KALDI_ERR << "Error in RandomAccessTableReader: duplicate key "
                     << cur_key_ << " in archive " << archive_rxfilename_;
         }
         holder_ = NULL;  // ownership transferred to map_.
         if (cur_key_ == key) {  // the one we wanted..
           if (value_ptr == NULL) {  // called from HasKey
             return true;
           } else {  // called from Value()
             *value_ptr = &(pr.first->second->Value());  // this gives us the
             // Value() from the Holder in the map.
             if (opts_.once) {  // mark for deletion, as won't be needed again.
               to_delete_iter_ = pr.first;
               KALDI_ASSERT(!to_delete_iter_valid_);
               to_delete_iter_valid_ = true;
             }
             return true;
           }
         }
       }
     }
     if (opts_.once && key == first_deleted_string_) {
       KALDI_ERR << "You specified the once (o) option but "
                 << "you are calling using key " << key
                 << " more than once: rspecifier is " << rspecifier_;
     }
     return false;  // We read the entire archive (or got to error state) and
     // didn't find it.
   }
void HandlePendingDelete () inline private
Definition at line 2038 of file kaldi-table-inl.h.
References RandomAccessTableReaderUnsortedArchiveImpl< Holder >::first_deleted_string_, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::map_, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::to_delete_iter_, and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::to_delete_iter_valid_.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HasKey(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Value().
{
     if (to_delete_iter_valid_) {
       to_delete_iter_valid_ = false;
       delete to_delete_iter_->second;  // Delete Holder object.
       if (first_deleted_string_.length() == 0)
         first_deleted_string_ = to_delete_iter_->first;
       map_.erase(to_delete_iter_);  // delete that element.
     }
   }
virtual bool HasKey (const std::string & key) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 2015 of file kaldi-table-inl.h.
References RandomAccessTableReaderUnsortedArchiveImpl< Holder >::FindKeyInternal(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HandlePendingDelete().
{
     HandlePendingDelete();
     return FindKeyInternal(key, NULL);
   }
virtual const T& Value (const std::string & key) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 2019 of file kaldi-table-inl.h.
References RandomAccessTableReaderArchiveImplBase< Holder >::archive_rxfilename_, RandomAccessTableReaderUnsortedArchiveImpl< Holder >::FindKeyInternal(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HandlePendingDelete(), KALDI_ERR, and kaldi::PrintableRxfilename().
{
     HandlePendingDelete();
     const T *ans_ptr = NULL;
     if (FindKeyInternal(key, &ans_ptr))
       return *ans_ptr;
     else
       KALDI_ERR << "Value() called but no such key " << key
                 << " in archive " << PrintableRxfilename(archive_rxfilename_);
     return *(const T*)NULL;  // keep compiler happy.
   }
Member Data Documentation
std::string first_deleted_string_ private
Definition at line 2121 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Close(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::FindKeyInternal(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HandlePendingDelete().
MapType map_ private
Definition at line 2116 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Close(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::FindKeyInternal(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HandlePendingDelete(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::RandomAccessTableReaderUnsortedArchiveImpl().
MapType::iterator to_delete_iter_ private
Definition at line 2118 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::FindKeyInternal(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HandlePendingDelete().
bool to_delete_iter_valid_ private
Definition at line 2119 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Close(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::FindKeyInternal(), and RandomAccessTableReaderUnsortedArchiveImpl< Holder >::HandlePendingDelete().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h