Kaldi: OptionalSumDescriptor Class Reference
OptionalSumDescriptor Class Reference
This is the case of class SumDescriptor, in which we contain just one term, and that term is optional (an IfDefined() expression).
#include <nnet-descriptor.h>
Public Member Functions
virtual void GetDependencies (const Index &ind, std::vector< Cindex > *dependencies) const
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
virtual bool IsComputable (const Index &ind, const CindexSet &cindex_set, std::vector< Cindex > *used_inputs) const
This function exists to enable us to manage optional dependencies, i.e.
virtual int32 Dim (const Nnet &nnet) const
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
virtual int32 Modulus () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
written form is: if required_ == true, "<written-form-of-src>" else "IfDefined(<written-form-of-src>)".
virtual SumDescriptor * Copy () const
OptionalSumDescriptor (SumDescriptor *src)
virtual ~OptionalSumDescriptor ()
Public Member Functions inherited from SumDescriptor
virtual ~SumDescriptor ()
Private Attributes
SumDescriptor * src_
Detailed Description
This is the case of class SumDescriptor, in which we contain just one term, and that term is optional (an IfDefined() expression).
That term is a general SumDescriptor.
Definition at line 330 of file nnet-descriptor.h.
Constructor & Destructor Documentation
OptionalSumDescriptor (SumDescriptor * src) inline
Definition at line 352 of file nnet-descriptor.h.
Referenced by OptionalSumDescriptor::Copy().
 : src_(src) { }
virtual ~OptionalSumDescriptor () inline virtual
Definition at line 353 of file nnet-descriptor.h.
References OptionalSumDescriptor::src_.
 { delete src_; }
Member Function Documentation
SumDescriptor * Copy () const virtual
Implements SumDescriptor.
Definition at line 229 of file nnet-descriptor.cc.
References SumDescriptor::Copy(), OptionalSumDescriptor::OptionalSumDescriptor(), and OptionalSumDescriptor::src_.
{
   return new OptionalSumDescriptor(src_->Copy());
 }
int32 Dim (const Nnet & nnet) const virtual
Implements SumDescriptor.
Definition at line 247 of file nnet-descriptor.cc.
References SumDescriptor::Dim(), and OptionalSumDescriptor::src_.
{
   return src_->Dim(nnet);
 }
void GetDependencies (const Index & ind, std::vector< Cindex > * dependencies) const virtual
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
The output list is not necessarily sorted, and this function doesn't make sure that it's unique.
Implements SumDescriptor.
Definition at line 233 of file nnet-descriptor.cc.
References SumDescriptor::GetDependencies(), and OptionalSumDescriptor::src_.
{
   src_->GetDependencies(ind, dependencies);
 }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
Implements SumDescriptor.
Definition at line 251 of file nnet-descriptor.cc.
References SumDescriptor::GetNodeDependencies(), and OptionalSumDescriptor::src_.
{
   src_->GetNodeDependencies(node_indexes);
 }
virtual bool IsComputable (const Index & ind, const CindexSet & cindex_set, std::vector< Cindex > * used_inputs) const inline virtual
This function exists to enable us to manage optional dependencies, i.e.
for making sense of expressions like (A + (B is present)) and (A if present; if not, B). Suppose we are trying to compute the index "ind", and the user represents that "cindex_set" is the set of Cindexes are available to the computation; then this function will return true if we can compute the expression given these inputs; and if so, will output to "used_inputs" the list of Cindexes that this expression will be a summation over.
Parameters
[in] ind The index that we want to compute at the output of the Descriptor.
[in] cindex_set The set of Cindexes that are available at the input of the Descriptor.
[out] used_inputs If non-NULL, if this function returns true then to this vector will be *appended* the inputs that will actually participate in the computation. Else (if non-NULL) it will be left unchanged.
Returns
Returns true if this output is computable given the provided inputs.
Implements SumDescriptor.
Definition at line 334 of file nnet-descriptor.h.
References SumDescriptor::IsComputable(), and OptionalSumDescriptor::src_.
{
       return src_->IsComputable(ind, cindex_set, used_inputs) || true;
   }
virtual int32 Modulus () const inline virtual
Implements SumDescriptor.
Definition at line 345 of file nnet-descriptor.h.
References SumDescriptor::Modulus(), and OptionalSumDescriptor::src_.
 { return src_->Modulus(); }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
written form is: if required_ == true, "<written-form-of-src>" else "IfDefined(<written-form-of-src>)".
Implements SumDescriptor.
Definition at line 239 of file nnet-descriptor.cc.
References OptionalSumDescriptor::src_, and SumDescriptor::WriteConfig().
{
   os << "IfDefined(";
   src_->WriteConfig(os, node_names);
   os << ")";
 }
Member Data Documentation
SumDescriptor* src_ private
Definition at line 355 of file nnet-descriptor.h.
Referenced by OptionalSumDescriptor::Copy(), OptionalSumDescriptor::Dim(), OptionalSumDescriptor::GetDependencies(), OptionalSumDescriptor::GetNodeDependencies(), OptionalSumDescriptor::IsComputable(), OptionalSumDescriptor::Modulus(), OptionalSumDescriptor::WriteConfig(), and OptionalSumDescriptor::~OptionalSumDescriptor().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc