Kaldi: Timer Class Reference
Timer Class Reference
#include <timer.h>
Public Member Functions
Timer ()
void Reset ()
double Elapsed ()
Returns time in seconds.
Private Attributes
struct timeval time_start_
struct timezone time_zone_
Detailed Description
Definition at line 58 of file timer.h.
Constructor & Destructor Documentation
Timer () inline
Definition at line 60 of file timer.h.
References Timer::Reset().
 { Reset(); }
Member Function Documentation
double Elapsed () inline
Returns time in seconds.
Definition at line 65 of file timer.h.
References Timer::time_start_, and Timer::time_zone_.
Referenced by CuVectorBase< Real >::Add(), CuMatrixBase< Real >::Add(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddElements(), CuMatrixBase< Real >::AddMat(), CuSpMatrix< Real >::AddMat2(), CuMatrixBase< Real >::AddMatBlock(), CuMatrixBase< Real >::AddMatBlocks(), CuBlockMatrix< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMat(), kaldi::AddMatMatBatched(), CuMatrixBase< Real >::AddMatMatDivMat(), CuMatrixBase< Real >::AddMatMatElements(), CuVectorBase< Real >::AddMatVec(), CuPackedMatrix< Real >::AddPacked(), CuMatrixBase< Real >::AddRowRanges(), CuVectorBase< Real >::AddSpVec(), CuPackedMatrix< Real >::AddToDiag(), CuMatrixBase< Real >::AddToDiag(), CuVectorBase< Real >::AddVec(), CuSpMatrix< Real >::AddVec2(), CuMatrixBase< Real >::AddVecMatPointMulVec(), CuMatrixBase< Real >::AddVecToCols(), CuMatrixBase< Real >::AddVecToRows(), CuVectorBase< Real >::AddVecVec(), CuMatrixBase< Real >::AddVecVec(), CuVectorBase< Real >::ApplyCeiling(), CuMatrixBase< Real >::ApplyCeiling(), CuVectorBase< Real >::ApplyExp(), CuMatrixBase< Real >::ApplyExp(), CuVectorBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyHeaviside(), CuVectorBase< Real >::ApplyLog(), CuMatrixBase< Real >::ApplyLog(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), CuVectorBase< Real >::ApplyPow(), CuMatrixBase< Real >::ApplyPow(), CuMatrixBase< Real >::ApplyPowAbs(), CuVectorBase< Real >::ApplySoftMax(), CuMatrixBase< Real >::ApplySoftMaxPerRow(), CuRand< Real >::BinarizeProbs(), kaldi::cu::Copy(), CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyColFromVec(), CuVectorBase< Real >::CopyDiagFromMat(), CuVectorBase< Real >::CopyDiagFromPacked(), CuSparseMatrix< Real >::CopyElementsToVec(), CuArray< T >::CopyFromArray(), CuSpMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuPackedMatrix< Real >::CopyFromPacked(), CuMatrixBase< Real >::CopyFromSp(), CuMatrixBase< Real >::CopyFromTp(), CuArray< T >::CopyFromVec(), CuVectorBase< Real >::CopyFromVec(), CuMatrixBase< Real >::CopyLowerToUpper(), CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), MatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), CuArray< T >::CopyToHost(), CuSparseMatrix< Real >::CopyToMat(), CuMatrixBase< Real >::CopyToMat(), CuPackedMatrix< Real >::CopyToPacked(), CuVectorBase< Real >::CopyToVec(), CuArray< T >::CopyToVec(), CuMatrixBase< Real >::CopyUpperToLower(), CuMatrix< Real >::Destroy(), CuMatrixBase< Real >::DiffSigmoid(), CuMatrixBase< Real >::DiffTanh(), CuMatrixBase< Real >::DiffXent(), CuMatrixBase< Real >::DivElements(), CuMatrixBase< Real >::DivRowsVec(), CuMatrixBase< Real >::EqualElementMask(), CuMatrixBase< Real >::FindRowMaxId(), CuMatrixBase< Real >::GroupMax(), CuMatrixBase< Real >::GroupMaxDeriv(), CuMatrixBase< Real >::GroupPnorm(), CuMatrixBase< Real >::GroupPnormDeriv(), CuVectorBase< Real >::InvertElements(), CuMatrixBase< Real >::InvertElements(), CuMatrixBase< Real >::Lookup(), main(), CuVectorBase< Real >::Max(), CuMatrixBase< Real >::Max(), CuVectorBase< Real >::Min(), CuMatrixBase< Real >::Min(), CuMatrixBase< Real >::MulColsVec(), CuVectorBase< Real >::MulElements(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsGroupMat(), CuMatrixBase< Real >::MulRowsVec(), CuVectorBase< Real >::MulTp(), CuVectorBase< Real >::Norm(), CuRand< Real >::RandGaussian(), kaldi::cu::Randomize(), CuRand< Real >::RandUniform(), kaldi::cu::RegularizeL1(), CuVectorBase< Real >::ReplaceValue(), CuArray< T >::Resize(), CuPackedMatrix< Real >::Resize(), CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuPackedMatrix< Real >::Scale(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), CuPackedMatrix< Real >::ScaleDiag(), CuVectorBase< Real >::Set(), CuArray< T >::Set(), CuMatrixBase< Real >::Set(), CuBlockMatrix< Real >::SetCudaData(), CuPackedMatrix< Real >::SetDiag(), CuPackedMatrix< Real >::SetZero(), CuVectorBase< Real >::SetZero(), CuArray< T >::SetZero(), CuMatrixBase< Real >::SetZero(), CuMatrixBase< Real >::SetZeroAboveDiag(), CuMatrixBase< Real >::Sigmoid(), CuMatrixBase< Real >::SoftHinge(), kaldi::cu::Splice(), CuVectorBase< Real >::Sum(), CuMatrixBase< Real >::SumColumnRanges(), CuMatrixBase< Real >::SymAddMat2(), CuMatrixBase< Real >::SymInvertPosDef(), CuMatrixBase< Real >::Tanh(), kaldi::TestCuFindRowMaxId(), kaldi::TestCuMatrixAddDiagVecMat(), kaldi::TestCuMatrixAddMat(), kaldi::TestCuMatrixAddMatBlocks(), kaldi::TestCuMatrixAddRowRanges(), kaldi::TestCuMatrixAddRows1(), kaldi::TestCuMatrixAddRows2(), kaldi::TestCuMatrixAddToRows(), kaldi::TestCuMatrixCholesky(), kaldi::TestCuMatrixCompObjfAndDeriv(), kaldi::TestCuMatrixCopyFromSp(), kaldi::TestCuMatrixCopyFromTp(), kaldi::TestCuMatrixCopyLowerToUpper(), kaldi::TestCuMatrixCopyRows1(), kaldi::TestCuMatrixCopyRows2(), kaldi::TestCuMatrixCopyToRows(), kaldi::TestCuMatrixCopyUpperToLower(), kaldi::TestCuMatrixGroupMax(), kaldi::TestCuMatrixGroupMaxDeriv(), kaldi::TestCuMatrixGroupPnorm(), kaldi::TestCuMatrixGroupPnormDeriv(), kaldi::TestCuMatrixHeaviside(), kaldi::TestCuMatrixLogSoftmax(), kaldi::TestCuMatrixLookup(), kaldi::TestCuMatrixMatMat(), kaldi::TestCuMatrixMatMatBatched(), kaldi::TestCuMatrixMulRowsGroupMat(), kaldi::TestCuMatrixResize(), kaldi::TestCuMatrixSetZeroAboveDiag(), kaldi::TestCuMatrixSigmoid(), kaldi::TestCuMatrixSoftmax(), kaldi::TestCuMatrixTraceMatMat(), kaldi::TestCuVectorAddColSumMat(), kaldi::TestCuVectorAddDiagMat2(), kaldi::TestCuVectorAddDiagMatMat(), kaldi::TestCuVectorAddRowSumMat(), kaldi::TestCuVectorSoftmax(), kaldi::TestCuVectorSum(), kaldi::TestCuVectorVecVecOne(), kaldi::TestSymInvertPosDef(), kaldi::TimerTest(), CuMatrixBase< Real >::Trace(), kaldi::TraceMatMat(), CuMatrix< Real >::Transpose(), kaldi::UnitTestAddColSumMatSpeed(), kaldi::UnitTestAddMatMatSpeed(), kaldi::UnitTestAddRowSumMatSpeed(), kaldi::UnitTestAddVecToColsSpeed(), kaldi::UnitTestAddVecToRowsSpeed(), kaldi::UnitTestCuSpMatrixCopyFromMat(), kaldi::UnitTestCuSpMatrixInvert(), kaldi::UnitTestExpSpeed(), kaldi::UnitTestLogSpeed(), kaldi::UnitTestPitchExtractionSpeed(), kaldi::UnitTestRealFftSpeed(), kaldi::UnitTestSplitRadixRealFftSpeed(), kaldi::UnitTestSvdSpeed(), and kaldi::VecVec().
                    {
     struct timeval time_end;
     gettimeofday(&time_end, &time_zone_);
     double t1, t2;
     t1 =  static_cast<double>(time_start_.tv_sec) +
           static_cast<double>(time_start_.tv_usec)/(1000*1000);
     t2 =  static_cast<double>(time_end.tv_sec) +
           static_cast<double>(time_end.tv_usec)/(1000*1000);
     return t2-t1;
   }
void Reset () inline
Definition at line 62 of file timer.h.
References Timer::time_start_, and Timer::time_zone_.
Referenced by Timer::Timer().
 { gettimeofday(&this->time_start_, &time_zone_); }
Member Data Documentation
struct timeval time_start_ private
Definition at line 77 of file timer.h.
Referenced by Timer::Elapsed(), and Timer::Reset().
struct timezone time_zone_ private
Definition at line 78 of file timer.h.
Referenced by Timer::Elapsed(), and Timer::Reset().
The documentation for this class was generated from the following file:
base/timer.h