Kaldi: LengthNormComponent Class Reference
LengthNormComponent Class Reference
Rescale the matrix-rows to have unit length (L2-norm).
#include <nnet-various.h>
Public Member Functions
LengthNormComponent (int32 dim_in, int32 dim_out)
~LengthNormComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if contains trainable parameters.
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Optionally print some additional info.
virtual std::string InfoGradient () const
Private Attributes
CuMatrix< BaseFloat > l2_aux_
auxiliary matrix for L2 norm computation,
CuVector< BaseFloat > row_scales_
normalization scale of each row,
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Member Functions inherited from Component
virtual void InitData (std::istream &is)
Initialize internal data of a component.
virtual void ReadData (std::istream &is, bool binary)
Reads the component content.
virtual void WriteData (std::ostream &os, bool binary) const
Writes the component content.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Rescale the matrix-rows to have unit length (L2-norm).
Definition at line 296 of file nnet-various.h.
Constructor & Destructor Documentation
LengthNormComponent (int32 dim_in, int32 dim_out) inline
Definition at line 298 of file nnet-various.h.
Referenced by LengthNormComponent::Copy().
     : Component(dim_in, dim_out)
   { }
~LengthNormComponent () inline
Definition at line 301 of file nnet-various.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 323 of file nnet-various.h.
References CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::MulRowsVec(), and LengthNormComponent::row_scales_.
{
     in_diff->CopyFromMat(out_diff);
     in_diff->MulRowsVec(row_scales_); // diff_by_x(s * x) = s,
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 304 of file nnet-various.h.
References LengthNormComponent::LengthNormComponent().
 { return new LengthNormComponent(*this); }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 305 of file nnet-various.h.
References Component::kLengthNormComponent.
 { return kLengthNormComponent; }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 307 of file nnet-various.h.
References CuVectorBase< Real >::AddColSumMat(), CuVectorBase< Real >::ApplyPow(), CuMatrixBase< Real >::CopyFromMat(), CuVectorBase< Real >::Dim(), CuVectorBase< Real >::InvertElements(), LengthNormComponent::l2_aux_, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumRows(), CuVector< Real >::Resize(), and LengthNormComponent::row_scales_.
{
     // resize vector when needed,
     if (row_scales_.Dim() != in.NumRows()) {
       row_scales_.Resize(in.NumRows());
     }
     // get the normalization scalars,
     l2_aux_ = in;
     l2_aux_.MulElements(l2_aux_); // x^2,
     row_scales_.AddColSumMat(1.0,l2_aux_,0.0); // sum_of_cols(x^2),
     row_scales_.ApplyPow(0.5); // L2norm = sqrt(sum_of_cols(x^2)),
     row_scales_.InvertElements(); // 1/L2norm,
     // compute the output,
     out->CopyFromMat(in);
     out->MulRowsVec(row_scales_); // re-normalize,
   }
Member Data Documentation
CuMatrix<BaseFloat> l2_aux_ private
auxiliary matrix for L2 norm computation,
Definition at line 330 of file nnet-various.h.
Referenced by LengthNormComponent::PropagateFnc().
CuVector<BaseFloat> row_scales_ private
normalization scale of each row,
Definition at line 331 of file nnet-various.h.
Referenced by LengthNormComponent::BackpropagateFnc(), and LengthNormComponent::PropagateFnc().
The documentation for this class was generated from the following file:
nnet/nnet-various.h