Kaldi: ClipGradientComponent Class Reference
ClipGradientComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
ClipGradientComponent (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, int32 num_clipped, int32 count)
ClipGradientComponent ()
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
void Init (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, int32 num_clipped, int32 count)
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Protected Attributes
int32 num_clipped_
int32 count_
Private Member Functions
ClipGradientComponent & operator= (const ClipGradientComponent &other)
Private Attributes
int32 dim_
BaseFloat clipping_threshold_
bool norm_based_clipping_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 915 of file nnet-simple-component.h.
Constructor & Destructor Documentation
ClipGradientComponent (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, int32 num_clipped, int32 count) inline
Definition at line 917 of file nnet-simple-component.h.
References ClipGradientComponent::Init().
{
     Init(dim, clipping_threshold, norm_based_clipping, num_clipped, count);}
ClipGradientComponent () inline
Definition at line 922 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Copy().
                          : dim_(0), clipping_threshold_(-1),
     norm_based_clipping_(false), num_clipped_(0), count_(0) { }
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from Component.
Definition at line 576 of file nnet-simple-component.cc.
References ClipGradientComponent::count_, KALDI_ASSERT, and ClipGradientComponent::num_clipped_.
{
   const ClipGradientComponent *other =
       dynamic_cast<const ClipGradientComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   count_ += alpha * other->count_;
   num_clipped_ += alpha * other->num_clipped_;
 }
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 521 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddDiagMat2(), CuMatrixBase< Real >::ApplyCeiling(), CuMatrixBase< Real >::ApplyFloor(), ClipGradientComponent::clipping_threshold_, CuMatrixBase< Real >::CopyFromMat(), ClipGradientComponent::count_, KALDI_ASSERT, kaldi::kNoTrans, CuMatrixBase< Real >::MulRowsVec(), ClipGradientComponent::norm_based_clipping_, ClipGradientComponent::num_clipped_, and CuMatrixBase< Real >::NumRows().
{
   // the following statement will do nothing if in_deriv and out_deriv have same
   // memory.
   in_deriv->CopyFromMat(out_deriv);
   ClipGradientComponent *to_update =
       dynamic_cast<ClipGradientComponent*>(to_update_in);
   KALDI_ASSERT(to_update != NULL);
   if (clipping_threshold_ > 0) {
     if (norm_based_clipping_) {
       // each row in the derivative matrix, which corresponds to one sample in
       // the mini-batch, is scaled to have a max-norm of clipping_threshold_
       CuVector<BaseFloat> clipping_scales(in_deriv->NumRows());
       clipping_scales.AddDiagMat2(pow(clipping_threshold_, -2), *in_deriv,
                                   kNoTrans, 0.0);
      // now clipping_scales contains the squared (norm of each row divided by
      //  clipping_threshold)
       int32 num_not_scaled = clipping_scales.ApplyFloor(1.0);
      // now clipping_scales contains min(1,
      //    squared-(norm/clipping_threshold))
       if (num_not_scaled != clipping_scales.Dim()) {
         clipping_scales.ApplyPow(-0.5);
         // now clipping_scales contains max(1,
         //       clipping_threshold/vector_norm)
         in_deriv->MulRowsVec(clipping_scales);
         to_update->num_clipped_ += (clipping_scales.Dim() - num_not_scaled);
        }
       to_update->count_ += clipping_scales.Dim();
     } else {
       // each element of the derivative matrix, is clipped to be below the
       // clipping_threshold_
       in_deriv->ApplyCeiling(clipping_threshold_);
       in_deriv->ApplyFloor(-1 * clipping_threshold_);
     }
   }
 }
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 939 of file nnet-simple-component.h.
References ClipGradientComponent::ClipGradientComponent(), ClipGradientComponent::clipping_threshold_, ClipGradientComponent::count_, ClipGradientComponent::dim_, ClipGradientComponent::norm_based_clipping_, and ClipGradientComponent::num_clipped_.
{
     return new ClipGradientComponent(dim_,
                                      clipping_threshold_,
                                      norm_based_clipping_,
                                      num_clipped_,
                                      count_);}
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Definition at line 475 of file nnet-simple-component.cc.
References ClipGradientComponent::clipping_threshold_, ClipGradientComponent::count_, ClipGradientComponent::dim_, ClipGradientComponent::norm_based_clipping_, ClipGradientComponent::num_clipped_, and ClipGradientComponent::Type().
{
   std::ostringstream stream;
   stream << Type() << ", dim=" << dim_
          << ", norm-based-clipping="
          << (norm_based_clipping_ ? "true" : "false")
          << ", clipping-threshold=" << clipping_threshold_
          << ", clipped-proportion="
          << (count_ > 0 ? static_cast<BaseFloat>(num_clipped_)/count_ : 0);
   return stream.str();
 }
void Init (int32 dim, BaseFloat clipping_threshold, bool norm_based_clipping, int32 num_clipped, int32 count)
Definition at line 486 of file nnet-simple-component.cc.
References ClipGradientComponent::clipping_threshold_, count, ClipGradientComponent::count_, ClipGradientComponent::dim_, KALDI_ASSERT, ClipGradientComponent::norm_based_clipping_, and ClipGradientComponent::num_clipped_.
Referenced by ClipGradientComponent::ClipGradientComponent(), and ClipGradientComponent::InitFromConfig().
{
   KALDI_ASSERT(clipping_threshold >= 0 && dim > 0);
   dim_ = dim;
   norm_based_clipping_ = norm_based_clipping;
   clipping_threshold_ = clipping_threshold;
   num_clipped_ = num_clipped;
   count_ = count;
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 499 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), ClipGradientComponent::Init(), KALDI_ERR, ClipGradientComponent::Type(), and ConfigLine::WholeLine().
{
   int32 dim = 0;
   bool ok = cfl->GetValue("dim", &dim);
   bool norm_based_clipping = false;
   BaseFloat clipping_threshold = 15.0;
   cfl->GetValue("clipping-threshold", &clipping_threshold);
   cfl->GetValue("norm-based-clipping", &norm_based_clipping);
   if (!ok || cfl->HasUnusedValues() ||
       clipping_threshold < 0 || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(dim, clipping_threshold, norm_based_clipping, 0, 0);
 }
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 925 of file nnet-simple-component.h.
References ClipGradientComponent::dim_.
 { return dim_; }
ClipGradientComponent& operator= (const ClipGradientComponent & other) private
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 926 of file nnet-simple-component.h.
References ClipGradientComponent::dim_.
 { return dim_; }
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Implements Component.
Definition at line 513 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::CopyFromMat().
{
   out->CopyFromMat(in);
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 933 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kLinearInInput, kaldi::nnet3::kPropagateInPlace, and kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent|kLinearInInput|kPropagateInPlace|kBackpropInPlace;
   }
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 443 of file nnet-simple-component.cc.
References ClipGradientComponent::clipping_threshold_, ClipGradientComponent::count_, ClipGradientComponent::dim_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), ClipGradientComponent::norm_based_clipping_, ClipGradientComponent::num_clipped_, and kaldi::ReadBasicType().
{
   // might not see the "<NaturalGradientAffineComponent>" part because
   // of how ReadNew() works.
   ExpectOneOrTwoTokens(is, binary, "<ClipGradientComponent>",
                        "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<ClippingThreshold>");
   ReadBasicType(is, binary, &clipping_threshold_);
   ExpectToken(is, binary, "<NormBasedClipping>");
   ReadBasicType(is, binary, &norm_based_clipping_);
   ExpectToken(is, binary, "<NumElementsClipped>");
   ReadBasicType(is, binary, &num_clipped_);
   ExpectToken(is, binary, "<NumElementsProcessed>");
   ReadBasicType(is, binary, &count_);
   ExpectToken(is, binary, "</ClipGradientComponent>");
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from Component.
Definition at line 571 of file nnet-simple-component.cc.
References ClipGradientComponent::count_, and ClipGradientComponent::num_clipped_.
{
   count_ *= scale;
   num_clipped_ *= scale;
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 931 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Info(), and ClipGradientComponent::InitFromConfig().
 { return "ClipGradientComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 460 of file nnet-simple-component.cc.
References ClipGradientComponent::clipping_threshold_, ClipGradientComponent::count_, ClipGradientComponent::dim_, ClipGradientComponent::norm_based_clipping_, ClipGradientComponent::num_clipped_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<ClipGradientComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<ClippingThreshold>");
   WriteBasicType(os, binary, clipping_threshold_);
   WriteToken(os, binary, "<NormBasedClipping>");
   WriteBasicType(os, binary, norm_based_clipping_);
   WriteToken(os, binary, "<NumElementsClipped>");
   WriteBasicType(os, binary, num_clipped_);
   WriteToken(os, binary, "<NumElementsProcessed>");
   WriteBasicType(os, binary, count_);
   WriteToken(os, binary, "</ClipGradientComponent>");
 }
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) are free to implement ZeroStats() also.
Reimplemented from Component.
Definition at line 566 of file nnet-simple-component.cc.
References ClipGradientComponent::count_, and ClipGradientComponent::num_clipped_.
{
   count_ = 0.0;
   num_clipped_ = 0.0;
 }
Member Data Documentation
BaseFloat clipping_threshold_ private
Definition at line 966 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Backprop(), ClipGradientComponent::Copy(), ClipGradientComponent::Info(), ClipGradientComponent::Init(), ClipGradientComponent::Read(), and ClipGradientComponent::Write().
int32 count_ protected
Definition at line 985 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Add(), ClipGradientComponent::Backprop(), ClipGradientComponent::Copy(), ClipGradientComponent::Info(), ClipGradientComponent::Init(), ClipGradientComponent::Read(), ClipGradientComponent::Scale(), ClipGradientComponent::Write(), and ClipGradientComponent::ZeroStats().
int32 dim_ private
Definition at line 965 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Copy(), ClipGradientComponent::Info(), ClipGradientComponent::Init(), ClipGradientComponent::InputDim(), ClipGradientComponent::OutputDim(), ClipGradientComponent::Read(), and ClipGradientComponent::Write().
bool norm_based_clipping_ private
Definition at line 970 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Backprop(), ClipGradientComponent::Copy(), ClipGradientComponent::Info(), ClipGradientComponent::Init(), ClipGradientComponent::Read(), and ClipGradientComponent::Write().
int32 num_clipped_ protected
Definition at line 984 of file nnet-simple-component.h.
Referenced by ClipGradientComponent::Add(), ClipGradientComponent::Backprop(), ClipGradientComponent::Copy(), ClipGradientComponent::Info(), ClipGradientComponent::Init(), ClipGradientComponent::Read(), ClipGradientComponent::Scale(), ClipGradientComponent::Write(), and ClipGradientComponent::ZeroStats().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc