Kaldi: CompressedMatrix Class Reference
CompressedMatrix Class Reference
%Matrix and vector classes
This class does lossy compression of a matrix.
#include <compressed-matrix.h>
Classes
struct GlobalHeader
struct PerColHeader
Public Member Functions
CompressedMatrix ()
~CompressedMatrix ()
template<typename Real >
CompressedMatrix (const MatrixBase< Real > &mat)
CompressedMatrix (const CompressedMatrix &mat, const MatrixIndexT row_offset, const MatrixIndexT num_rows, const MatrixIndexT col_offset, const MatrixIndexT num_cols)
Initializer that can be used to select part of an existing CompressedMatrix without un-compressing and re-compressing (note: unlike similar initializers for class Matrix, it doesn't point to the same memory location).
void * Data () const
template<typename Real >
void CopyFromMat (const MatrixBase< Real > &mat)
This will resize *this and copy the contents of mat to *this.
CompressedMatrix (const CompressedMatrix &mat)
CompressedMatrix & operator= (const CompressedMatrix &mat)
template<typename Real >
CompressedMatrix & operator= (const MatrixBase< Real > &mat)
template<typename Real >
void CopyToMat (MatrixBase< Real > *mat, MatrixTransposeType trans=kNoTrans) const
Copies contents to matrix.
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
MatrixIndexT NumRows () const
Returns number of rows (or zero for emtpy matrix).
MatrixIndexT NumCols () const
Returns number of columns (or zero for emtpy matrix).
template<typename Real >
void CopyRowToVec (MatrixIndexT row, VectorBase< Real > *v) const
Copies row #row of the matrix into vector v.
template<typename Real >
void CopyColToVec (MatrixIndexT col, VectorBase< Real > *v) const
Copies column #col of the matrix into vector v.
template<typename Real >
void CopyToMat (int32 row_offset, int32 column_offset, MatrixBase< Real > *dest) const
Copies submatrix of compressed matrix into matrix dest.
void Swap (CompressedMatrix *other)
void Clear ()
Static Private Member Functions
static void * AllocateData (int32 num_bytes)
static MatrixIndexT DataSize (const GlobalHeader &header)
template<typename Real >
static void CompressColumn (const GlobalHeader &global_header, const Real *data, MatrixIndexT stride, int32 num_rows, PerColHeader *header, unsigned char *byte_data)
template<typename Real >
static void ComputeColHeader (const GlobalHeader &global_header, const Real *data, MatrixIndexT stride, int32 num_rows, PerColHeader *header)
static uint16 FloatToUint16 (const GlobalHeader &global_header, float value)
static float Uint16ToFloat (const GlobalHeader &global_header, uint16 value)
static unsigned char FloatToChar (float p0, float p25, float p75, float p100, float value)
static float CharToFloat (float p0, float p25, float p75, float p100, unsigned char value)
Private Attributes
void * data_
Friends
class Matrix< float >
class Matrix< double >
Detailed Description
This class does lossy compression of a matrix.
It only supports copying to-from a KaldiMatrix. For large matrices, each element is compressed into about one byte, but there is a little overhead on top of that (globally, and also per column). The basic idea is for each column (in the normal configuration) we work out the values at the 0th, 25th, 50th and 100th percentiles and store them as 16-bit integers; we then encode each value in the column as a single byte, in 3 separate ranges with different linear encodings (0-25th, 25-50th, 50th-100th). If the matrix has 8 rows or fewer, we simply store all values as uint16.
Definition at line 45 of file compressed-matrix.h.
Constructor & Destructor Documentation
CompressedMatrix () inline
Definition at line 47 of file compressed-matrix.h.
 : data_(NULL) { }
~CompressedMatrix () inline
Definition at line 49 of file compressed-matrix.h.
References CompressedMatrix::Clear().
 { Clear(); }
CompressedMatrix (const MatrixBase< Real > & mat) inline
Definition at line 52 of file compressed-matrix.h.
References CompressedMatrix::CopyFromMat().
 : data_(NULL) { CopyFromMat(mat); }
CompressedMatrix (const CompressedMatrix & mat, const MatrixIndexT row_offset, const MatrixIndexT num_rows, const MatrixIndexT col_offset, const MatrixIndexT num_cols)
Initializer that can be used to select part of an existing CompressedMatrix without un-compressing and re-compressing (note: unlike similar initializers for class Matrix, it doesn't point to the same memory location).
Definition at line 133 of file compressed-matrix.cc.
References CompressedMatrix::AllocateData(), CompressedMatrix::CopyToMat(), CompressedMatrix::Data(), CompressedMatrix::data_, CompressedMatrix::DataSize(), CompressedMatrix::GlobalHeader::format, rnnlm::i, KALDI_ASSERT, KALDI_COMPILE_TIME_ASSERT, kaldi::kUndefined, CompressedMatrix::GlobalHeader::num_cols, CompressedMatrix::GlobalHeader::num_rows, CompressedMatrix::NumCols(), CompressedMatrix::NumRows(), and CompressedMatrix::Swap().
                                 : data_(NULL) {
   int32 old_num_rows = cmat.NumRows(), old_num_cols = cmat.NumCols();
   KALDI_ASSERT(row_offset < old_num_rows);
   KALDI_ASSERT(col_offset < old_num_cols);
   KALDI_ASSERT(row_offset >= 0);
   KALDI_ASSERT(col_offset >= 0);
   KALDI_ASSERT(row_offset + num_rows <= old_num_rows);
   KALDI_ASSERT(col_offset + num_cols <= old_num_cols);
   if (old_num_rows == 0) { return; }  // Zero-size matrix stored as zero pointer.
   if (num_rows == 0 || num_cols == 0) { return; }
   GlobalHeader new_global_header;
   KALDI_COMPILE_TIME_ASSERT(sizeof(new_global_header) == 20);
   GlobalHeader *old_global_header = reinterpret_cast<GlobalHeader*>(cmat.Data());
   new_global_header = *old_global_header;
   new_global_header.num_cols = num_cols;
   new_global_header.num_rows = num_rows;
   // We don't switch format from 1 -> 2 (in case of size reduction) yet; if this
   // is needed, we will do this below by creating a temporary Matrix.
   new_global_header.format = old_global_header->format;
   data_ = AllocateData(DataSize(new_global_header));  // allocate memory
   *(reinterpret_cast<GlobalHeader*>(data_)) = new_global_header;
   if (old_global_header->format == 1) {
     // Both have the format where we have a PerColHeader and then compress as
     // chars...
     PerColHeader *old_per_col_header =
         reinterpret_cast<PerColHeader*>(old_global_header + 1);
     unsigned char *old_byte_data =
         reinterpret_cast<unsigned char*>(old_per_col_header +
                                          old_global_header->num_cols);
     PerColHeader *new_per_col_header =
         reinterpret_cast<PerColHeader*>(
             reinterpret_cast<GlobalHeader*>(data_) + 1);
     memcpy(new_per_col_header, old_per_col_header + col_offset,
            sizeof(PerColHeader) * num_cols);
     unsigned char *new_byte_data =
         reinterpret_cast<unsigned char*>(new_per_col_header + num_cols);
     unsigned char *old_start_of_subcol =
         old_byte_data + row_offset + (col_offset * old_num_rows),
         *new_start_of_col = new_byte_data;
     for (int32 i = 0; i < num_cols; i++) {
       memcpy(new_start_of_col, old_start_of_subcol, num_rows);
       new_start_of_col += num_rows;
       old_start_of_subcol += old_num_rows;
     }
   } else {
     // both have the new format (2).
     KALDI_ASSERT(old_global_header->format == 2);
     const uint16 *old_data =
         reinterpret_cast<const uint16*>(old_global_header + 1);
     uint16 *new_data =
         reinterpret_cast<uint16*>(reinterpret_cast<GlobalHeader*>(data_) + 1);
     old_data += col_offset + (old_num_cols * row_offset);
     for (int32 row = 0; row < num_rows; row++) {
       memcpy(new_data, old_data, sizeof(uint16) * num_cols);
       new_data += num_cols;
       old_data += old_num_cols;
     }
   }
   if (num_rows < 8 && new_global_header.format == 1) {
     // format was 1 but we want it to be 2 -> create a temporary
     // Matrix (uncompress), re-compress, and swap.
     Matrix<float> temp(this->NumRows(), this->NumCols(),
                        kUndefined);
     this->CopyToMat(&temp);
     CompressedMatrix temp_cmat(temp);
     this->Swap(&temp_cmat);
   }
 }
CompressedMatrix (const CompressedMatrix & mat)
Definition at line 684 of file compressed-matrix.cc.
                                                              : data_(NULL) {
   *this = mat; // use assignment operator.
 }
Member Function Documentation
void * AllocateData (int32 num_bytes) static private
Definition at line 398 of file compressed-matrix.cc.
References KALDI_ASSERT, and KALDI_COMPILE_TIME_ASSERT.
Referenced by CompressedMatrix::CompressedMatrix(), CompressedMatrix::CopyFromMat(), CompressedMatrix::operator=(), and CompressedMatrix::Read().
{
   KALDI_ASSERT(num_bytes > 0);
   KALDI_COMPILE_TIME_ASSERT(sizeof(float) == 4);
   // round size up to nearest number of floats.
   return reinterpret_cast<void*>(new float[(num_bytes/3) + 4]);
 }
float CharToFloat (float p0, float p25, float p75, float p100, unsigned char value) inline static private
Definition at line 364 of file compressed-matrix.cc.
Referenced by CompressedMatrix::CopyColToVec(), CompressedMatrix::CopyRowToVec(), and CompressedMatrix::CopyToMat().
{
   if (value <= 64) {
     return p0 + (p25 - p0) * value * (1/64.0);
   } else if (value <= 192) {
     return p25 + (p75 - p25) * (value - 64) * (1/128.0);
   } else {
     return p75 + (p100 - p75) * (value - 192) * (1/63.0);
   }
 }
void Clear ()
Definition at line 677 of file compressed-matrix.cc.
References CompressedMatrix::data_.
Referenced by GeneralMatrix::Clear(), CompressedMatrix::operator=(), GeneralMatrix::Uncompress(), and CompressedMatrix::~CompressedMatrix().
{
   if (data_ != NULL) {
     delete [] static_cast<float*>(data_);
     data_ = NULL;
   }
 }
void CompressColumn (const GlobalHeader & global_header, const Real * data, MatrixIndexT stride, int32 num_rows, CompressedMatrix::PerColHeader * header, unsigned char * byte_data) static private
Definition at line 378 of file compressed-matrix.cc.
References CompressedMatrix::ComputeColHeader(), CompressedMatrix::FloatToChar(), rnnlm::i, CompressedMatrix::PerColHeader::percentile_0, CompressedMatrix::PerColHeader::percentile_100, CompressedMatrix::PerColHeader::percentile_25, CompressedMatrix::PerColHeader::percentile_75, and CompressedMatrix::Uint16ToFloat().
Referenced by CompressedMatrix::CopyFromMat().
{
   ComputeColHeader(global_header, data, stride,
                    num_rows, header);
   float p0 = Uint16ToFloat(global_header, header->percentile_0),
       p25 = Uint16ToFloat(global_header, header->percentile_25),
       p75 = Uint16ToFloat(global_header, header->percentile_75),
       p100 = Uint16ToFloat(global_header, header->percentile_100);
   for (int32 i = 0; i < num_rows; i++) {
     Real this_data = data[i * stride];
     byte_data[i] = FloatToChar(p0, p25, p75, p100, this_data);
   }
 }
void ComputeColHeader (const GlobalHeader & global_header, const Real * data, MatrixIndexT stride, int32 num_rows, CompressedMatrix::PerColHeader * header) static private
Definition at line 254 of file compressed-matrix.cc.
References CompressedMatrix::FloatToUint16(), rnnlm::i, KALDI_ASSERT, CompressedMatrix::PerColHeader::percentile_0, CompressedMatrix::PerColHeader::percentile_100, CompressedMatrix::PerColHeader::percentile_25, and CompressedMatrix::PerColHeader::percentile_75.
Referenced by CompressedMatrix::CompressColumn().
{
   KALDI_ASSERT(num_rows > 0);
   std::vector<Real> sdata(num_rows); // the sorted data.
   for (size_t i = 0, size = sdata.size(); i < size; i++)
     sdata[i] = data[i*stride];
   if (num_rows >= 5) {
     int quarter_nr = num_rows/4;
     // std::sort(sdata.begin(), sdata.end());
     // The elements at positions 0, quarter_nr,
     // 3*quarter_nr, and num_rows-1 need to be in sorted order.
     std::nth_element(sdata.begin(), sdata.begin() + quarter_nr, sdata.end());
     // Now, sdata.begin() + quarter_nr contains the element that would appear
     // in sorted order, in that position.
     std::nth_element(sdata.begin(), sdata.begin(), sdata.begin() + quarter_nr);
     // Now, sdata.begin() and sdata.begin() + quarter_nr contain the elements
     // that would appear at those positions in sorted order.
     std::nth_element(sdata.begin() + quarter_nr + 1,
                      sdata.begin() + (3*quarter_nr), sdata.end());
     // Now, sdata.begin(), sdata.begin() + quarter_nr, and sdata.begin() +
     // 3*quarter_nr, contain the elements that would appear at those positions
     // in sorted order.
     std::nth_element(sdata.begin() + (3*quarter_nr) + 1, sdata.end() - 1,
                      sdata.end());
     // Now, sdata.begin(), sdata.begin() + quarter_nr, and sdata.begin() +
     // 3*quarter_nr, and sdata.end() - 1, contain the elements that would appear
     // at those positions in sorted order.
     header->percentile_0 =
         std::min<uint16>(FloatToUint16(global_header, sdata[0]), 65532);
     header->percentile_25 =
         std::min<uint16>(
             std::max<uint16>(
                 FloatToUint16(global_header, sdata[quarter_nr]),
                 header->percentile_0 + static_cast<uint16>(1)), 65533);
     header->percentile_75 =
         std::min<uint16>(
             std::max<uint16>(
                 FloatToUint16(global_header, sdata[3*quarter_nr]),
                 header->percentile_25 + static_cast<uint16>(1)), 65534);
     header->percentile_100 = std::max<uint16>(
         FloatToUint16(global_header, sdata[num_rows-1]),
         header->percentile_75 + static_cast<uint16>(1));
   } else {  // handle this pathological case.
     std::sort(sdata.begin(), sdata.end());
     // Note: we know num_rows is at least 1.
     header->percentile_0 =
         std::min<uint16>(FloatToUint16(global_header, sdata[0]),
                          65532);
     if (num_rows > 1)
       header->percentile_25 =
           std::min<uint16>(
               std::max<uint16>(FloatToUint16(global_header, sdata[1]),
                                header->percentile_0 + 1), 65533);
     else
       header->percentile_25 = header->percentile_0 + 1;
     if (num_rows > 2)
       header->percentile_75 =
           std::min<uint16>(
               std::max<uint16>(FloatToUint16(global_header, sdata[2]),
                                header->percentile_25 + 1), 65534);
     else
       header->percentile_75 = header->percentile_25 + 1;
     if (num_rows > 3)
       header->percentile_100 =
           std::max<uint16>(FloatToUint16(global_header, sdata[3]),
                            header->percentile_75 + 1);
     else
       header->percentile_100 = header->percentile_75 + 1;
   }
 }
template void CopyColToVec (MatrixIndexT col, VectorBase< Real > * v) const
Copies column #col of the matrix into vector v.
Note: v must have same size as #rows.
Definition at line 572 of file compressed-matrix.cc.
References CompressedMatrix::CharToFloat(), VectorBase< Real >::Data(), CompressedMatrix::data_, VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, CompressedMatrix::NumCols(), CompressedMatrix::NumRows(), CompressedMatrix::PerColHeader::percentile_0, CompressedMatrix::PerColHeader::percentile_100, CompressedMatrix::PerColHeader::percentile_25, CompressedMatrix::PerColHeader::percentile_75, and CompressedMatrix::Uint16ToFloat().
Referenced by kaldi::UnitTestCompressedMatrix().
{
   KALDI_ASSERT(col < this->NumCols());
   KALDI_ASSERT(col >= 0);
   KALDI_ASSERT(v->Dim() == this->NumRows());
   GlobalHeader *h = reinterpret_cast<GlobalHeader*>(data_);
   if (h->format == 1) {  // format with per-col header.
     PerColHeader *per_col_header = reinterpret_cast<PerColHeader*>(h+1);
     unsigned char *byte_data = reinterpret_cast<unsigned char*>(per_col_header +
                                                                 h->num_cols);
     byte_data += col*h->num_rows;  // point to first value in the column we want
     per_col_header += col;
     float p0 = Uint16ToFloat(*h, per_col_header->percentile_0),
         p25 = Uint16ToFloat(*h, per_col_header->percentile_25),
         p75 = Uint16ToFloat(*h, per_col_header->percentile_75),
         p100 = Uint16ToFloat(*h, per_col_header->percentile_100);
     for (int32 i = 0; i < h->num_rows; i++, byte_data++) {
       float f = CharToFloat(p0, p25, p75, p100, *byte_data);
       (*v)(i) = f;
     }
   } else {
     KALDI_ASSERT(h->format == 2);  // uint16 format
     int32 num_rows = h->num_rows, num_cols = h->num_cols;
     const uint16 *col_data = reinterpret_cast<uint16*>(h + 1) + col;
     Real *v_data = v->Data();
     for (int32 r = 0; r < num_rows; r++)
       v_data[r] = Uint16ToFloat(*h, col_data[r * num_cols]);
   }
 }
template void CopyFromMat (const MatrixBase< Real > & mat)
This will resize *this and copy the contents of mat to *this.
Definition at line 42 of file compressed-matrix.cc.
References CompressedMatrix::AllocateData(), CompressedMatrix::CompressColumn(), MatrixBase< Real >::Data(), CompressedMatrix::data_, CompressedMatrix::DataSize(), CompressedMatrix::FloatToUint16(), CompressedMatrix::GlobalHeader::format, KALDI_ASSERT, KALDI_COMPILE_TIME_ASSERT, KALDI_ISFINITE, MatrixBase< Real >::Max(), MatrixBase< Real >::Min(), CompressedMatrix::GlobalHeader::min_value, CompressedMatrix::GlobalHeader::num_cols, CompressedMatrix::GlobalHeader::num_rows, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), CompressedMatrix::GlobalHeader::range, MatrixBase< Real >::RowData(), and MatrixBase< Real >::Stride().
Referenced by GeneralMatrix::Compress(), CompressedMatrix::CompressedMatrix(), CompressedAffineXformStats::CopyFromAffineXformStats(), CompressedMatrix::operator=(), kaldi::nnet2::PerturbTrainingExample(), CompressedMatrix::Read(), and kaldi::nnet2::TransformTrainingExample().
{
   if (data_ != NULL) {
     delete [] static_cast<float*>(data_);  // call delete [] because was allocated with new float[]
     data_ = NULL;
   }
   if (mat.NumRows() == 0) { return; }  // Zero-size matrix stored as zero pointer.
   GlobalHeader global_header;
   KALDI_COMPILE_TIME_ASSERT(sizeof(global_header) == 20);  // otherwise
   // something weird is happening and our code probably won't work or
   // won't be robust across platforms.
   // Below, the point of the "safety_margin" is that the minimum
   // and maximum values in the matrix shouldn't coincide with
   // the minimum and maximum ranges of the 16-bit range, because
   // this could cause certain problems in ComputeColHeader, where
   // we need to ensure that the percentile_0 through percentile_100
   // are in strictly increasing order.
   float min_value = mat.Min(), max_value = mat.Max();
   if (max_value == min_value)
     max_value = min_value + (1.0 + fabs(min_value)); // ensure it's strictly
                                                      // greater than min_value,
                                                      // even if matrix is
                                                      // constant.
   global_header.min_value = min_value;
   global_header.range = max_value - min_value;
   // We can't compress the matrix if there are inf's or nan's.
   // The caller should check for this first.
   KALDI_ASSERT(KALDI_ISFINITE(global_header.min_value) &&
                KALDI_ISFINITE(global_header.range));
   // Avoid division by zero if the matrix is just a constant:
   // make sure max_value > min_value.
   if (global_header.range <= 0.0)
     global_header.range = 1.0e-05;
   global_header.num_rows = mat.NumRows();
   global_header.num_cols = mat.NumCols();
   if (mat.NumRows() > 8) {
     global_header.format = 1;  // format where each row has a PerColHeader.
   } else {
     global_header.format = 2;  // format where all data is uint16.
   }
   int32 data_size = DataSize(global_header);
   data_ = AllocateData(data_size);
   *(reinterpret_cast<GlobalHeader*>(data_)) = global_header;
   if (global_header.format == 1) {
     PerColHeader *header_data =
         reinterpret_cast<PerColHeader*>(static_cast<char*>(data_) +
                                         sizeof(GlobalHeader));
     unsigned char *byte_data =
         reinterpret_cast<unsigned char*>(header_data + global_header.num_cols);
     const Real *matrix_data = mat.Data();
     for (int32 col = 0; col < global_header.num_cols; col++) {
       CompressColumn(global_header,
                      matrix_data + col, mat.Stride(),
                      global_header.num_rows,
                      header_data, byte_data);
       header_data++;
       byte_data += global_header.num_rows;
     }
   } else {
     uint16 *data = reinterpret_cast<uint16*>(static_cast<char*>(data_) +
                                              sizeof(GlobalHeader));
     int32 num_rows = mat.NumRows(), num_cols = mat.NumCols();
     for (int32 r = 0; r < num_rows; r++) {
       const Real *row_data = mat.RowData(r);
       for (int32 c = 0; c < num_cols; c++)
         data[c] = FloatToUint16(global_header, row_data[c]);
       data += num_cols;
     }
   }
 }
template void CopyRowToVec (MatrixIndexT row, VectorBase< Real > * v) const
Copies row #row of the matrix into vector v.
Note: v must have same size as #cols.
Definition at line 540 of file compressed-matrix.cc.
References CompressedMatrix::CharToFloat(), VectorBase< Real >::Data(), CompressedMatrix::data_, VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, CompressedMatrix::NumCols(), CompressedMatrix::NumRows(), and CompressedMatrix::Uint16ToFloat().
Referenced by kaldi::FilterCompressedMatrixRows(), and kaldi::UnitTestCompressedMatrix().
{
   KALDI_ASSERT(row < this->NumRows());
   KALDI_ASSERT(row >= 0);
   KALDI_ASSERT(v->Dim() == this->NumCols());
   GlobalHeader *h = reinterpret_cast<GlobalHeader*>(data_);
   if (h->format == 1) {  // format with per-col header.
     PerColHeader *per_col_header = reinterpret_cast<PerColHeader*>(h+1);
     unsigned char *byte_data = reinterpret_cast<unsigned char*>(per_col_header +
                                                                 h->num_cols);
     byte_data += row;  // point to first value we are interested in
     for (int32 i = 0; i < h->num_cols;
          i++, per_col_header++, byte_data += h->num_rows) {
       float p0 = Uint16ToFloat(*h, per_col_header->percentile_0),
           p25 = Uint16ToFloat(*h, per_col_header->percentile_25),
           p75 = Uint16ToFloat(*h, per_col_header->percentile_75),
           p100 = Uint16ToFloat(*h, per_col_header->percentile_100);
       float f = CharToFloat(p0, p25, p75, p100, *byte_data);
       (*v)(i) = f;
     }
   } else {
     KALDI_ASSERT(h->format == 2);  // uint16 format
     int32 num_cols = h->num_cols;
     const uint16 *row_data = reinterpret_cast<uint16*>(h + 1) + (num_cols * row);
     Real *v_data = v->Data();
     for (int32 c = 0; c < num_cols; c++)
       v_data[c] = Uint16ToFloat(*h, row_data[c]);
   }
 }
void CopyToMat (MatrixBase< Real > * mat, MatrixTransposeType trans = kNoTrans) const
Copies contents to matrix.
Note: mat must have the correct size. kNoTrans case uses a temporary.
Definition at line 486 of file compressed-matrix.cc.
References CompressedMatrix::CharToFloat(), MatrixBase< Real >::CopyFromMat(), CompressedMatrix::data_, CompressedMatrix::GlobalHeader::format, rnnlm::i, rnnlm::j, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CompressedMatrix::GlobalHeader::num_cols, CompressedMatrix::GlobalHeader::num_rows, MatrixBase< Real >::NumCols(), CompressedMatrix::NumCols(), MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), CompressedMatrix::PerColHeader::percentile_0, CompressedMatrix::PerColHeader::percentile_100, CompressedMatrix::PerColHeader::percentile_25, CompressedMatrix::PerColHeader::percentile_75, MatrixBase< Real >::RowData(), and CompressedMatrix::Uint16ToFloat().
Referenced by CompressedMatrix::CompressedMatrix(), MatrixBase< Real >::CopyFromMat(), CompressedAffineXformStats::CopyToAffineXformStats(), GeneralMatrix::CopyToMat(), kaldi::FilterCompressedMatrixRows(), GeneralMatrix::GetMatrix(), Matrix< Real >::Matrix(), Matrix< Real >::Read(), GeneralMatrix::Uncompress(), kaldi::UnitTestCompressedMatrix(), kaldi::UnitTestExtractCompressedMatrix(), and CompressedMatrix::Write().
{
   if (trans == kTrans) {
     Matrix<Real> temp(this->NumCols(), this->NumRows());
     CopyToMat(&temp, kNoTrans);
     mat->CopyFromMat(temp, kTrans);
     return;
   }
   if (data_ == NULL) {
     KALDI_ASSERT(mat->NumRows() == 0);
     KALDI_ASSERT(mat->NumCols() == 0);
     return;
   }
   GlobalHeader *h = reinterpret_cast<GlobalHeader*>(data_);
   int32 num_cols = h->num_cols, num_rows = h->num_rows;
   KALDI_ASSERT(mat->NumRows() == num_rows);
   KALDI_ASSERT(mat->NumCols() == num_cols);
   if (h->format == 1) {
     PerColHeader *per_col_header = reinterpret_cast<PerColHeader*>(h+1);
     unsigned char *byte_data = reinterpret_cast<unsigned char*>(per_col_header +
                                                                 h->num_cols);
     for (int32 i = 0; i < num_cols; i++, per_col_header++) {
       float p0 = Uint16ToFloat(*h, per_col_header->percentile_0),
           p25 = Uint16ToFloat(*h, per_col_header->percentile_25),
           p75 = Uint16ToFloat(*h, per_col_header->percentile_75),
           p100 = Uint16ToFloat(*h, per_col_header->percentile_100);
       for (int32 j = 0; j < num_rows; j++, byte_data++) {
         float f = CharToFloat(p0, p25, p75, p100, *byte_data);
         (*mat)(j, i) = f;
       }
     }
   } else {
     KALDI_ASSERT(h->format == 2);
     const uint16 *data = reinterpret_cast<const uint16*>(h + 1);
     for (int32 i = 0; i < num_rows; i++) {
       Real *row_data = mat->RowData(i);
       for (int32 j = 0; j < num_cols; j++)
         row_data[j] = Uint16ToFloat(*h, data[j]);
       data += num_cols;
     }
   }
 }
void CopyToMat (int32 row_offset, int32 column_offset, MatrixBase< Real > * dest) const
Copies submatrix of compressed matrix into matrix dest.
Submatrix starts at row row_offset and column column_offset and its size is defined by size of provided matrix dest
Definition at line 615 of file compressed-matrix.cc.
References CompressedMatrix::CharToFloat(), CompressedMatrix::data_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_PARANOID_ASSERT, CompressedMatrix::GlobalHeader::num_rows, MatrixBase< Real >::NumCols(), CompressedMatrix::NumCols(), MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), MatrixBase< Real >::RowData(), and CompressedMatrix::Uint16ToFloat().
{
   KALDI_PARANOID_ASSERT(row_offset < this->NumRows());
   KALDI_PARANOID_ASSERT(col_offset < this->NumCols());
   KALDI_PARANOID_ASSERT(row_offset >= 0);
   KALDI_PARANOID_ASSERT(col_offset >= 0);
   KALDI_ASSERT(row_offset+dest->NumRows() < this->NumRows());
   KALDI_ASSERT(col_offset+dest->NumCols() < this->NumCols());
   // everything is OK
   GlobalHeader *h = reinterpret_cast<GlobalHeader*>(data_);
   int32 num_rows = h->num_rows, num_cols = h->num_cols,
       tgt_cols = dest->NumCols(), tgt_rows = dest->NumRows();
   if (h->format == 1) {
     // format where we have a per-column header and use one byte per
     // element.
     PerColHeader *per_col_header = reinterpret_cast<PerColHeader*>(h+1);
     unsigned char *byte_data = reinterpret_cast<unsigned char*>(per_col_header +
                                                                 h->num_cols);
     unsigned char *start_of_subcol = byte_data+row_offset;  // skip appropriate
     // number of columns
     start_of_subcol += col_offset*num_rows;  // skip appropriate number of rows
     per_col_header += col_offset;  // skip the appropriate number of headers
     for (int32 i = 0;
          i < tgt_cols;
          i++, per_col_header++, start_of_subcol+=num_rows) {
       byte_data = start_of_subcol;
       float p0 = Uint16ToFloat(*h, per_col_header->percentile_0),
           p25 = Uint16ToFloat(*h, per_col_header->percentile_25),
           p75 = Uint16ToFloat(*h, per_col_header->percentile_75),
           p100 = Uint16ToFloat(*h, per_col_header->percentile_100);
       for (int32 j = 0; j < tgt_rows; j++, byte_data++) {
         float f = CharToFloat(p0, p25, p75, p100, *byte_data);
         (*dest)(j, i) = f;
       }
     }
   } else {
     KALDI_ASSERT(h->format == 2);
     const uint16 *data = reinterpret_cast<const uint16*>(h+1) + col_offset +
         (num_cols * row_offset);
     for (int32 row = 0; row < tgt_rows; row++) {
       Real *dest_row = dest->RowData(row);
       for (int32 col = 0; col < tgt_cols; col++)
         dest_row[col] = Uint16ToFloat(*h, data[col]);
       data += num_cols;
     }
   }
 }
void* Data () const inline
Definition at line 64 of file compressed-matrix.h.
References CompressedMatrix::data_.
Referenced by CompressedMatrix::CompressedMatrix().
 { return this->data_; }
MatrixIndexT DataSize (const GlobalHeader & header) static private
Definition at line 28 of file compressed-matrix.cc.
References CompressedMatrix::GlobalHeader::format, KALDI_ASSERT, CompressedMatrix::GlobalHeader::num_cols, and CompressedMatrix::GlobalHeader::num_rows.
Referenced by CompressedMatrix::CompressedMatrix(), CompressedMatrix::CopyFromMat(), CompressedMatrix::operator=(), CompressedMatrix::Read(), and CompressedMatrix::Write().
{
   // Returns size in bytes of the data.
   if (header.format == 1) {
     return sizeof(GlobalHeader) +
         header.num_cols * (sizeof(PerColHeader) + header.num_rows);
   } else {
     KALDI_ASSERT(header.format == 2) ;
     return sizeof(GlobalHeader) +
         2 * header.num_rows * header.num_cols;
   }
 }
unsigned char FloatToChar (float p0, float p25, float p75, float p100, float value) inline static private
Definition at line 331 of file compressed-matrix.cc.
Referenced by CompressedMatrix::CompressColumn().
                  {
   int ans;
   if (value < p25) {  // range [ p0, p25 ) covered by
     // characters 0 .. 64.  We round to the closest int.
     float f = (value - p0) / (p25 - p0);
     ans = static_cast<int>(f * 64 + 0.5);
     // Note: the checks on the next two lines
     // are necessary in pathological cases when all the elements in a row
     // are the same and the percentile_* values are separated by one.
     if (ans < 0) ans = 0;
     if (ans > 64) ans = 64;
   } else if (value < p75) {  // range [ p25, p75 )covered
     // by characters 64 .. 192.  We round to the closest int.
     float f = (value - p25) / (p75 - p25);
     ans = 64 + static_cast<int>(f * 128 + 0.5);
     if (ans < 64) ans = 64;
     if (ans > 192) ans = 192;
   } else {  // range [ p75, p100 ] covered by
     // characters 192 .. 255.  Note: this last range
     // has fewer characters than the left range, because
     // we go up to 255, not 256.
     float f = (value - p75) / (p100 - p75);
     ans = 192 + static_cast<int>(f * 63 + 0.5);
     if (ans < 192) ans = 192;
     if (ans > 255) ans = 255;
   }
   return static_cast<unsigned char>(ans);
 }
uint16 FloatToUint16 (const GlobalHeader & global_header, float value) inline static private
Definition at line 234 of file compressed-matrix.cc.
References CompressedMatrix::GlobalHeader::min_value, and CompressedMatrix::GlobalHeader::range.
Referenced by CompressedMatrix::ComputeColHeader(), and CompressedMatrix::CopyFromMat().
                  {
   float f = (value - global_header.min_value) /
       global_header.range;
   if (f > 1.0) f = 1.0;  // Note: this should not happen.
   if (f < 0.0) f = 0.0;  // Note: this should not happen.
   return static_cast<int>(f * 65535 + 0.499);  // + 0.499 is to
   // round to closest int; avoids bias.
 }
MatrixIndexT NumCols () const inline
Returns number of columns (or zero for emtpy matrix).
Definition at line 92 of file compressed-matrix.h.
References CompressedMatrix::data_.
Referenced by CompressedMatrix::CompressedMatrix(), CompressedMatrix::CopyColToVec(), CompressedMatrix::CopyRowToVec(), CompressedAffineXformStats::CopyToAffineXformStats(), CompressedMatrix::CopyToMat(), kaldi::FilterCompressedMatrixRows(), GeneralMatrix::GetMatrix(), main(), Matrix< Real >::Matrix(), NnetExample::NnetExample(), GeneralMatrix::NumCols(), Matrix< Real >::Read(), kaldi::UnitTestCompressedMatrix(), and CompressedMatrix::Write().
                                       { return (data_ == NULL) ? 0 :
       (*reinterpret_cast<GlobalHeader*>(data_)).num_cols; }
MatrixIndexT NumRows () const inline
Returns number of rows (or zero for emtpy matrix).
Definition at line 88 of file compressed-matrix.h.
References CompressedMatrix::data_.
Referenced by CompressedMatrix::CompressedMatrix(), CompressedMatrix::CopyColToVec(), CompressedMatrix::CopyRowToVec(), CompressedAffineXformStats::CopyToAffineXformStats(), CompressedMatrix::CopyToMat(), GeneralMatrix::CopyToMat(), kaldi::FilterCompressedMatrixRows(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), Matrix< Real >::Matrix(), NnetExample::NnetExample(), GeneralMatrix::NumRows(), Matrix< Real >::Read(), GeneralMatrix::SwapFullMatrix(), GeneralMatrix::SwapSparseMatrix(), GeneralMatrix::Type(), GeneralMatrix::Uncompress(), kaldi::UnitTestCompressedMatrix(), CompressedMatrix::Write(), and GeneralMatrix::Write().
                                       { return (data_ == NULL) ? 0 :
       (*reinterpret_cast<GlobalHeader*>(data_)).num_rows; }
CompressedMatrix & operator= (const CompressedMatrix & mat)
Definition at line 688 of file compressed-matrix.cc.
References CompressedMatrix::AllocateData(), CompressedMatrix::Clear(), CompressedMatrix::data_, and CompressedMatrix::DataSize().
{
   Clear(); // now this->data_ == NULL.
   if (mat.data_ != NULL) {
     MatrixIndexT data_size = DataSize(*static_cast<GlobalHeader*>(mat.data_));
     data_ = AllocateData(data_size);
     memcpy(static_cast<void*>(data_),
            static_cast<void*>(mat.data_),
            data_size);
   }
   return *this;
 }
CompressedMatrix & operator= (const MatrixBase< Real > & mat)
Definition at line 222 of file compressed-matrix.cc.
References CompressedMatrix::CopyFromMat().
{
   this->CopyFromMat(mat);
   return *this;
 }
void Read (std::istream & is, bool binary)
Definition at line 438 of file compressed-matrix.cc.
References CompressedMatrix::AllocateData(), CompressedMatrix::CopyFromMat(), CompressedMatrix::data_, CompressedMatrix::DataSize(), CompressedMatrix::GlobalHeader::format, KALDI_ERR, CompressedMatrix::GlobalHeader::num_cols, kaldi::Peek(), Matrix< Real >::Read(), and kaldi::ReadToken().
Referenced by CompressedAffineXformStats::Read(), NnetExample::Read(), GeneralMatrix::Read(), Matrix< Real >::Read(), and kaldi::UnitTestCompressedMatrix().
{
   if (data_ != NULL) {
     delete [] (static_cast<float*>(data_));
     data_ = NULL;
   }
   if (binary) {
     int peekval = Peek(is, binary);
     if (peekval == 'C') {
       std::string tok; // Should be CM (format 1) or CM2 (format 2)
       ReadToken(is, binary, &tok);
       GlobalHeader h;
       if (tok == "CM") { h.format = 1; }
       else if (tok == "CM2") { h.format = 2; }
       else {
         KALDI_ERR << "Unexpected token " << tok << ", expecting CM or CM2.";
       }
       // don't read the "format" -> hence + 4, - 4.
       is.read(reinterpret_cast<char*>(&h) + 4, sizeof(h) - 4);
       if (is.fail())
         KALDI_ERR << "Failed to read header";
       if (h.num_cols == 0) // empty matrix.
         return;
       int32 size = DataSize(h), remaining_size = size - sizeof(GlobalHeader);
       data_ = AllocateData(size);
       *(reinterpret_cast<GlobalHeader*>(data_)) = h;
       is.read(reinterpret_cast<char*>(data_) + sizeof(GlobalHeader),
               remaining_size);
     } else {
       // Assume that what we're reading is a regular Matrix.  This might be the
       // case if you changed your code, making a Matrix into a CompressedMatrix,
       // and you want back-compatibility for reading.
       Matrix<BaseFloat> M;
       M.Read(is, binary); // This will crash if it was not a Matrix.  This might happen,
                           // for instance, if the CompressedMatrix was written using the
                           // older code where we didn't write the token "CM", we just
                           // wrote the binary data directly.
       this->CopyFromMat(M);
     }
   } else {  // Text-mode read.
     Matrix<BaseFloat> temp;
     temp.Read(is, binary);
     this->CopyFromMat(temp);
   }
   if (is.fail())
     KALDI_ERR << "Failed to read data.";
 }
void Swap (CompressedMatrix * other) inline
Definition at line 113 of file compressed-matrix.h.
References CompressedMatrix::data_, and kaldi::swap().
Referenced by CompressedMatrix::CompressedMatrix(), NnetExample::NnetExample(), and GeneralMatrix::Swap().
 { std::swap(data_, other->data_); }
float Uint16ToFloat (const GlobalHeader & global_header, uint16 value) inline static private
Definition at line 245 of file compressed-matrix.cc.
References CompressedMatrix::GlobalHeader::min_value, and CompressedMatrix::GlobalHeader::range.
Referenced by CompressedMatrix::CompressColumn(), CompressedMatrix::CopyColToVec(), CompressedMatrix::CopyRowToVec(), and CompressedMatrix::CopyToMat().
                       {
   // the constant 1.52590218966964e-05 is 1/65535.
   return global_header.min_value
       + global_header.range * 1.52590218966964e-05F * value;
 }
void Write (std::ostream & os, bool binary) const
Definition at line 405 of file compressed-matrix.cc.
References CompressedMatrix::CopyToMat(), CompressedMatrix::data_, CompressedMatrix::DataSize(), CompressedMatrix::GlobalHeader::format, KALDI_ASSERT, KALDI_ERR, kaldi::kUndefined, CompressedMatrix::GlobalHeader::min_value, CompressedMatrix::GlobalHeader::num_cols, CompressedMatrix::GlobalHeader::num_rows, CompressedMatrix::NumCols(), CompressedMatrix::NumRows(), CompressedMatrix::GlobalHeader::range, MatrixBase< Real >::Write(), and kaldi::WriteToken().
Referenced by kaldi::UnitTestCompressedMatrix(), CompressedAffineXformStats::Write(), NnetExample::Write(), DiscriminativeNnetExample::Write(), and GeneralMatrix::Write().
{
   if (binary) {  // Binary-mode write:
     if (data_ != NULL) {
       GlobalHeader &h = *reinterpret_cast<GlobalHeader*>(data_);
       if (h.format == 1) {
         WriteToken(os, binary, "CM");
       } else {
         KALDI_ASSERT(h.format == 2);
         WriteToken(os, binary, "CM2");
       }
       MatrixIndexT size = DataSize(h);  // total size of data in data_
       // We don't write out the "int32 format", hence the + 4, - 4.
       os.write(reinterpret_cast<const char*>(data_) + 4, size - 4);
     } else {  // special case: where data_ == NULL, we treat it as an empty
       // matrix.
       WriteToken(os, binary, "CM");
       GlobalHeader h;
       h.range = h.min_value = 0.0;
       h.num_rows = h.num_cols = 0;
       os.write(reinterpret_cast<const char*>(&h), sizeof(h));
     }
   } else {
     // In text mode, just use the same format as a regular matrix.
     // This is not compressed.
     Matrix<BaseFloat> temp_mat(this->NumRows(), this->NumCols(),
                                kUndefined);
     this->CopyToMat(&temp_mat);
     temp_mat.Write(os, binary);
   }
   if (os.fail())
     KALDI_ERR << "Error writing compressed matrix to stream.";
 }
Friends And Related Function Documentation
friend class Matrix< double > friend
Definition at line 118 of file compressed-matrix.h.
friend class Matrix< float > friend
Definition at line 117 of file compressed-matrix.h.
Member Data Documentation
void* data_ private
Definition at line 167 of file compressed-matrix.h.
Referenced by CompressedMatrix::Clear(), CompressedMatrix::CompressedMatrix(), CompressedMatrix::CopyColToVec(), CompressedMatrix::CopyFromMat(), CompressedMatrix::CopyRowToVec(), CompressedMatrix::CopyToMat(), CompressedMatrix::Data(), CompressedMatrix::NumCols(), CompressedMatrix::NumRows(), CompressedMatrix::operator=(), CompressedMatrix::Read(), CompressedMatrix::Swap(), and CompressedMatrix::Write().
The documentation for this class was generated from the following files:
matrix/compressed-matrix.h
matrix/compressed-matrix.cc