Kaldi: StdVectorRandomizer< T > Class Template Reference
StdVectorRandomizer< T > Class Template Reference
Randomizes elements of a vector according to a mask.
#include <nnet-randomizer.h>
Public Member Functions
StdVectorRandomizer ()
StdVectorRandomizer (const NnetDataRandomizerOptions &conf)
void Init (const NnetDataRandomizerOptions &conf)
Set the randomizer parameters (size)
void AddData (const std::vector< T > &v)
Add data to randomization buffer.
bool IsFull ()
Returns true, when capacity is full.
int32 NumFrames ()
Number of frames stored inside the Randomizer.
void Randomize (const std::vector< int32 > &mask)
Randomize matrix row-order using mask.
bool Done ()
Returns true, if no more data for another mini-batch (after current one)
void Next ()
Sets cursor to next mini-batch.
const std::vector< T > & Value ()
Returns matrix-window with next mini-batch.
Private Attributes
std::vector< T > data_
std::vector< T > minibatch_
int32 data_begin_
Cursor to beginning of data (row index, moves as mini-batches are delivered)
int32 data_end_
Cursor past the end of data (row index)
NnetDataRandomizerOptions conf_
Detailed Description
template<typename T>
class kaldi::nnet1::StdVectorRandomizer< T >
Randomizes elements of a vector according to a mask.
Definition at line 142 of file nnet-randomizer.h.
Constructor & Destructor Documentation
StdVectorRandomizer () inline
Definition at line 144 of file nnet-randomizer.h.
 : data_begin_(0), data_end_(0) { }
StdVectorRandomizer (const NnetDataRandomizerOptions & conf) inline
Definition at line 145 of file nnet-randomizer.h.
References StdVectorRandomizer< T >::Init().
 : data_begin_(0), data_end_(0) { Init(conf); }
Member Function Documentation
void AddData (const std::vector< T > & v)
Add data to randomization buffer.
Definition at line 157 of file nnet-randomizer.cc.
References KALDI_ASSERT.
Referenced by main(), and UnitTestStdVectorRandomizer().
{
   // pre-allocate before 1st use
   if(data_.size() == 0) {
     data_.resize(conf_.randomizer_size);
   }
   // optionally put previous left-over to front
   if (data_begin_ > 0) {
     KALDI_ASSERT(data_begin_ <= data_end_); // sanity check
     int32 leftover = data_end_ - data_begin_;
     KALDI_ASSERT(leftover < data_begin_); // no overlap
     if(leftover > 0) {
       std::copy(data_.begin()+data_begin_, data_.begin()+data_begin_+leftover, data_.begin());
     }
     data_begin_ = 0; data_end_ = leftover;
     // cannot do this, we don't know default value of arbitrary type!
     // data_.RowRange(leftover,data_.NumRows()-leftover).SetZero(); // zeroing the rest
   }
   // extend the buffer if necessary
   if(data_.size() < data_end_ + v.size()) {
     data_.resize(data_end_ + v.size() + 1000); // +1000 row surplus
   }
   // copy the data
   std::copy(v.begin(), v.end(), data_.begin()+data_end_);
   data_end_ += v.size();
 }
bool Done () inline
Returns true, if no more data for another mini-batch (after current one)
Definition at line 159 of file nnet-randomizer.h.
References StdVectorRandomizer< T >::conf_, StdVectorRandomizer< T >::data_begin_, StdVectorRandomizer< T >::data_end_, and NnetDataRandomizerOptions::minibatch_size.
Referenced by UnitTestStdVectorRandomizer().
 { return (data_end_ - data_begin_ < conf_.minibatch_size); }
void Init (const NnetDataRandomizerOptions & conf) inline
Set the randomizer parameters (size)
Definition at line 147 of file nnet-randomizer.h.
References StdVectorRandomizer< T >::conf_.
Referenced by StdVectorRandomizer< T >::StdVectorRandomizer(), and UnitTestStdVectorRandomizer().
 { conf_ = conf; }
bool IsFull () inline
Returns true, when capacity is full.
Definition at line 152 of file nnet-randomizer.h.
References StdVectorRandomizer< T >::conf_, StdVectorRandomizer< T >::data_begin_, StdVectorRandomizer< T >::data_end_, and NnetDataRandomizerOptions::randomizer_size.
Referenced by UnitTestStdVectorRandomizer().
 { return ((data_begin_ == 0) && (data_end_ > conf_.randomizer_size )); }
void Next ()
Sets cursor to next mini-batch.
Definition at line 197 of file nnet-randomizer.cc.
Referenced by main(), and UnitTestStdVectorRandomizer().
{
   data_begin_ += conf_.minibatch_size;
 }
int32 NumFrames () inline
Number of frames stored inside the Randomizer.
Definition at line 154 of file nnet-randomizer.h.
References StdVectorRandomizer< T >::data_end_.
Referenced by UnitTestStdVectorRandomizer().
 { return data_end_; }
void Randomize (const std::vector< int32 > & mask)
Randomize matrix row-order using mask.
Definition at line 184 of file nnet-randomizer.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by main(), and UnitTestStdVectorRandomizer().
{
   KALDI_ASSERT(data_begin_ == 0);
   KALDI_ASSERT(data_end_ > 0);
   KALDI_ASSERT(data_end_ == mask.size());
   // Use auxiliary buffer for unshuffled data
   std::vector<T> data_aux(data_);
   // randomize the data, mask is used to index elements in source vector
   for(int32 i = 0; i<mask.size(); i++) {
     data_.at(i) = data_aux.at(mask.at(i));
   }
 }
const std::vector< T > & Value ()
Returns matrix-window with next mini-batch.
Definition at line 202 of file nnet-randomizer.cc.
References KALDI_ASSERT.
Referenced by main(), and UnitTestStdVectorRandomizer().
{
   KALDI_ASSERT(data_end_ - data_begin_ >= conf_.minibatch_size); // have data for minibatch
   minibatch_.resize(conf_.minibatch_size);
   typename std::vector<T>::iterator first = data_.begin() + data_begin_;
   typename std::vector<T>::iterator last  = data_.begin() + data_begin_ + conf_.minibatch_size; //not-copied
   std::copy(first, last, minibatch_.begin());
   return minibatch_;
 }
Member Data Documentation
NnetDataRandomizerOptions conf_ private
Definition at line 174 of file nnet-randomizer.h.
Referenced by StdVectorRandomizer< T >::Done(), StdVectorRandomizer< T >::Init(), and StdVectorRandomizer< T >::IsFull().
std::vector<T> data_ private
Definition at line 166 of file nnet-randomizer.h.
int32 data_begin_ private
Cursor to beginning of data (row index, moves as mini-batches are delivered)
Definition at line 170 of file nnet-randomizer.h.
Referenced by StdVectorRandomizer< T >::Done(), and StdVectorRandomizer< T >::IsFull().
int32 data_end_ private
Cursor past the end of data (row index)
Definition at line 172 of file nnet-randomizer.h.
Referenced by StdVectorRandomizer< T >::Done(), StdVectorRandomizer< T >::IsFull(), and StdVectorRandomizer< T >::NumFrames().
std::vector<T> minibatch_ private
Definition at line 167 of file nnet-randomizer.h.
The documentation for this class was generated from the following files:
nnet/nnet-randomizer.h
nnet/nnet-randomizer.cc