Kaldi: RectifiedLinearComponent Class Reference
RectifiedLinearComponent Class Reference
#include <nnet-component.h>
Public Member Functions
RectifiedLinearComponent (int32 dim)
RectifiedLinearComponent (const RectifiedLinearComponent &other)
RectifiedLinearComponent ()
virtual std::string Type () const
virtual Component * Copy () const
Copy component (deep copy).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Public Member Functions inherited from NonlinearComponent
void Init (int32 dim)
NonlinearComponent (int32 dim)
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void InitFromString (std::string args)
We implement InitFromString at this level.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
void Scale (BaseFloat scale)
void Add (BaseFloat alpha, const NonlinearComponent &other)
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
void SetDim (int32 dim)
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual std::string Info () const
virtual ~Component ()
Private Member Functions
RectifiedLinearComponent & operator= (const RectifiedLinearComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Protected Member Functions inherited from NonlinearComponent
void UpdateStats (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
Mutex mutex_
Detailed Description
Definition at line 676 of file nnet-component.h.
Constructor & Destructor Documentation
RectifiedLinearComponent (int32 dim) inline explicit
Definition at line 678 of file nnet-component.h.
 : NonlinearComponent(dim) { }
RectifiedLinearComponent (const RectifiedLinearComponent & other) inline explicit
Definition at line 679 of file nnet-component.h.
 : NonlinearComponent(other) { }
RectifiedLinearComponent () inline
Definition at line 680 of file nnet-component.h.
Referenced by RectifiedLinearComponent::Copy().
 { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 800 of file nnet-component.cc.
References CuMatrixBase< Real >::ApplyHeaviside(), CuMatrixBase< Real >::CopyFromMat(), kaldi::kUndefined, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrix< Real >::Resize(), and NonlinearComponent::UpdateStats().
{
   in_deriv->Resize(out_deriv.NumRows(), out_deriv.NumCols(),
                    kUndefined);
   in_deriv->CopyFromMat(out_value);
   in_deriv->ApplyHeaviside();
   // Now in_deriv(i, j) equals (out_value(i, j) > 0.0 ? 1.0 : 0.0),
   // which is the derivative of the nonlinearity (well, except at zero
   // where it's undefined).
   if (to_update != NULL)
     dynamic_cast<NonlinearComponent*>(to_update)->UpdateStats(out_value,
                                                               in_deriv);
   in_deriv->MulElements(out_deriv);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 683 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 684 of file nnet-component.h.
 { return true; }
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 682 of file nnet-component.h.
References RectifiedLinearComponent::RectifiedLinearComponent().
 { return new RectifiedLinearComponent(*this); }
RectifiedLinearComponent& operator= (const RectifiedLinearComponent & other) private
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 791 of file nnet-component.cc.
References CuMatrixBase< Real >::ApplyFloor(), and CuMatrixBase< Real >::CopyFromMat().
{
   // Apply rectified linear function (x >= 0 ? 1.0 : 0.0)
   out->CopyFromMat(in);
   out->ApplyFloor(0.0);
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 681 of file nnet-component.h.
 { return "RectifiedLinearComponent"; }
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc