Kaldi: PnormComponent Class Reference
PnormComponent Class Reference
#include <nnet-component.h>
Public Member Functions
void Init (int32 input_dim, int32 output_dim, BaseFloat p)
PnormComponent (int32 input_dim, int32 output_dim, BaseFloat p)
PnormComponent ()
virtual std::string Type () const
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Protected Attributes
int32 input_dim_
int32 output_dim_
BaseFloat p_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
Definition at line 514 of file nnet-component.h.
Constructor & Destructor Documentation
PnormComponent (int32 input_dim, int32 output_dim, BaseFloat p) inline explicit
Definition at line 517 of file nnet-component.h.
References PnormComponent::Init().
{
     Init(input_dim, output_dim, p);
   }
PnormComponent () inline
Definition at line 520 of file nnet-component.h.
Referenced by PnormComponent::Copy().
 : input_dim_(0), output_dim_(0), p_(0) { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 525 of file nnet-component.cc.
References CuMatrixBase< Real >::GroupPnormDeriv(), kaldi::kSetZero, CuMatrixBase< Real >::MulRowsGroupMat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), PnormComponent::p_, and CuMatrix< Real >::Resize().
{
   in_deriv->Resize(in_value.NumRows(), in_value.NumCols(), kSetZero);
   in_deriv->GroupPnormDeriv(in_value, out_value, p_);
   in_deriv->MulRowsGroupMat(out_deriv);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 537 of file nnet-component.h.
 { return true; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 538 of file nnet-component.h.
 { return true; }
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 539 of file nnet-component.h.
References PnormComponent::input_dim_, PnormComponent::output_dim_, PnormComponent::p_, and PnormComponent::PnormComponent().
                                   { return new PnormComponent(input_dim_,
                                                               output_dim_, p_); }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 559 of file nnet-component.cc.
References PnormComponent::input_dim_, PnormComponent::output_dim_, PnormComponent::p_, and PnormComponent::Type().
{
   std::stringstream stream;
   stream << Type() << ", input-dim = " << input_dim_
          << ", output-dim = " << output_dim_
      << ", p = " << p_;
   return stream.str();
 }
void Init (int32 input_dim, int32 output_dim, BaseFloat p)
Definition at line 489 of file nnet-component.cc.
References PnormComponent::input_dim_, KALDI_ASSERT, PnormComponent::output_dim_, and PnormComponent::p_.
Referenced by PnormComponent::InitFromString(), and PnormComponent::PnormComponent().
{
   input_dim_ = input_dim;
   output_dim_ = output_dim;
   if (input_dim_ == 0)
     input_dim_ = 10 * output_dim_; // default group size : 10
   p_ = p;
   KALDI_ASSERT(input_dim_ > 0 && output_dim_ >= 0 && p_ >= 0);
   KALDI_ASSERT(input_dim_ % output_dim_ == 0);
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 499 of file nnet-component.cc.
References PnormComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), and PnormComponent::Type().
Referenced by kaldi::nnet2::UnitTestPnormComponent().
{
   std::string orig_args(args);
   int32 input_dim = 0;
   int32 output_dim = 0;
   BaseFloat p = 2;
   bool ok = ParseFromString("output-dim", &args, &output_dim) &&
       ParseFromString("input-dim", &args, &input_dim);
   ParseFromString("p", &args, &p);
   if (!ok || !args.empty() || output_dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   Init(input_dim, output_dim, p);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 523 of file nnet-component.h.
References PnormComponent::input_dim_.
 { return input_dim_; }
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 524 of file nnet-component.h.
References PnormComponent::output_dim_.
 { return output_dim_; }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 514 of file nnet-component.cc.
References ChunkInfo::CheckSize(), CuMatrixBase< Real >::GroupPnorm(), KALDI_ASSERT, ChunkInfo::NumChunks(), and PnormComponent::p_.
{
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   out->GroupPnorm(in, p_);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 538 of file nnet-component.cc.
References kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), PnormComponent::input_dim_, PnormComponent::output_dim_, PnormComponent::p_, and kaldi::ReadBasicType().
{
   ExpectOneOrTwoTokens(is, binary, "<PnormComponent>", "<InputDim>");
   ReadBasicType(is, binary, &input_dim_);
   ExpectToken(is, binary, "<OutputDim>");
   ReadBasicType(is, binary, &output_dim_);
   ExpectToken(is, binary, "<P>");
   ReadBasicType(is, binary, &p_);
   ExpectToken(is, binary, "</PnormComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 521 of file nnet-component.h.
Referenced by PnormComponent::Info(), and PnormComponent::InitFromString().
 { return "PnormComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 548 of file nnet-component.cc.
References PnormComponent::input_dim_, PnormComponent::output_dim_, PnormComponent::p_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<PnormComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, input_dim_);
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, output_dim_);
   WriteToken(os, binary, "<P>");
   WriteBasicType(os, binary, p_);
   WriteToken(os, binary, "</PnormComponent>");
 }
Member Data Documentation
int32 input_dim_ protected
Definition at line 550 of file nnet-component.h.
Referenced by PnormComponent::Copy(), PnormComponent::Info(), PnormComponent::Init(), PnormComponent::InputDim(), PnormComponent::Read(), and PnormComponent::Write().
int32 output_dim_ protected
Definition at line 551 of file nnet-component.h.
Referenced by PnormComponent::Copy(), PnormComponent::Info(), PnormComponent::Init(), PnormComponent::OutputDim(), PnormComponent::Read(), and PnormComponent::Write().
BaseFloat p_ protected
Definition at line 552 of file nnet-component.h.
Referenced by PnormComponent::Backprop(), PnormComponent::Copy(), PnormComponent::Info(), PnormComponent::Init(), PnormComponent::Propagate(), PnormComponent::Read(), and PnormComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc