Kaldi: FixedBiasComponent Class Reference
FixedBiasComponent Class Reference
FixedBiasComponent applies a fixed per-element bias; it's similar to the AddShift component in the nnet1 setup (and only needed for nnet1 model conversion.
#include <nnet-component.h>
Public Member Functions
FixedBiasComponent ()
virtual std::string Type () const
virtual std::string Info () const
void Init (const CuVectorBase< BaseFloat > &scales)
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Protected Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedBiasComponent)
Protected Attributes
CuVector< BaseFloat > bias_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
FixedBiasComponent applies a fixed per-element bias; it's similar to the AddShift component in the nnet1 setup (and only needed for nnet1 model conversion.
Definition at line 1542 of file nnet-component.h.
Constructor & Destructor Documentation
FixedBiasComponent () inline
Definition at line 1544 of file nnet-component.h.
Referenced by FixedBiasComponent::Copy().
 { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 3499 of file nnet-component.cc.
{
   *in_deriv = out_deriv;
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1568 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1569 of file nnet-component.h.
 { return false; }
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 3509 of file nnet-component.cc.
References FixedBiasComponent::bias_, and FixedBiasComponent::FixedBiasComponent().
{
   FixedBiasComponent *ans = new FixedBiasComponent();
   ans->bias_ = bias_;
   return ans;
 }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 3480 of file nnet-component.cc.
References FixedBiasComponent::bias_, CuVectorBase< Real >::Dim(), Component::Info(), CuVectorBase< Real >::Sum(), and kaldi::VecVec().
{
   std::stringstream stream;
   BaseFloat bias_size = static_cast<BaseFloat>(bias_.Dim()),
       bias_mean = bias_.Sum() / bias_size,
       bias_stddev = std::sqrt(VecVec(bias_, bias_) / bias_size)
        - (bias_mean * bias_mean);
   stream << Component::Info() << ", bias-mean=" << bias_mean
          << ", bias-stddev=" << bias_stddev;
   return stream.str();
 }
void Init (const CuVectorBase< BaseFloat > & scales)
Definition at line 3460 of file nnet-component.cc.
References FixedBiasComponent::bias_, CuVectorBase< Real >::Dim(), and KALDI_ASSERT.
Referenced by kaldi::ConvertAddShiftComponent(), FixedBiasComponent::InitFromString(), and kaldi::nnet2::UnitTestFixedBiasComponent().
{
   KALDI_ASSERT(bias.Dim() != 0);
   bias_ = bias;
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 3465 of file nnet-component.cc.
References FixedBiasComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), kaldi::ReadKaldiObject(), and FixedBiasComponent::Type().
{
   std::string orig_args = args;
   std::string filename;
   bool ok = ParseFromString("bias", &args, &filename);
   if (!ok || !args.empty())
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   CuVector<BaseFloat> vec;
   ReadKaldiObject(filename, &vec);
   Init(vec);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1554 of file nnet-component.h.
References FixedBiasComponent::bias_, and CuVectorBase< Real >::Dim().
 { return bias_.Dim(); }
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedBiasComponent) protected
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1555 of file nnet-component.h.
References FixedBiasComponent::bias_, and CuVectorBase< Real >::Dim().
 { return bias_.Dim(); }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 3491 of file nnet-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), FixedBiasComponent::bias_, and CuMatrixBase< Real >::CopyFromMat().
{
   out->CopyFromMat(in);
   out->AddVecToRows(1.0, bias_, 1.0);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 3523 of file nnet-component.cc.
References FixedBiasComponent::bias_, kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), and CuVector< Real >::Read().
{
   ExpectOneOrTwoTokens(is, binary, "<FixedBiasComponent>", "<Bias>");
   bias_.Read(is, binary);
   ExpectToken(is, binary, "</FixedBiasComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1545 of file nnet-component.h.
Referenced by FixedBiasComponent::InitFromString().
 { return "FixedBiasComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3516 of file nnet-component.cc.
References FixedBiasComponent::bias_, CuVector< Real >::Write(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<FixedBiasComponent>");
   WriteToken(os, binary, "<Bias>");
   bias_.Write(os, binary);
   WriteToken(os, binary, "</FixedBiasComponent>");
 }
Member Data Documentation
CuVector<BaseFloat> bias_ protected
Definition at line 1575 of file nnet-component.h.
Referenced by FixedBiasComponent::Copy(), FixedBiasComponent::Info(), FixedBiasComponent::Init(), FixedBiasComponent::InputDim(), FixedBiasComponent::OutputDim(), FixedBiasComponent::Propagate(), FixedBiasComponent::Read(), and FixedBiasComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc