Kaldi: CuMatrixBase< Real > Class Template Reference
CuMatrixBase< Real > Class Template Reference
Matrix for CUDA computing.
#include <matrix-common.h>
Public Member Functions
void CopyCols (const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indexes)
Copies column r from column indexes[r] of src.
void AddCols (const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indices)
Add column indices[r] of src to column r.
void CopyRows (const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indexes)
Copies row r from row indexes[r] of src.
void CopyRows (const CuArray< const Real * > &src)
Copies row r of this matrix from an array of floats at the location given by src[r], where src[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (the point is: the data it points to should be on the GPU if we're using a GPU, and on a CPU otherwise).
void CopyToRows (const CuArray< Real * > &dst) const
For each row r of this matrix, copies it to the array of floats at the location given by dst[r], where dst[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (i.e.
void AddRows (Real alpha, const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indexes)
Does for each row r, this.Row(r) += alpha * src.row(indexes[r]).
void AddRows (Real alpha, const CuArray< const Real * > &src)
Does for each row r, this.Row(r) += alpha * src[r], treating src[r] as the beginning of a region of memory representing a vector of floats, of the same length as this.NumCols().
void AddToRows (Real alpha, const CuArray< Real * > &dst) const
For each row r of this matrix, adds it (times alpha) to the array of floats at the location given by dst[r], where dst[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (i.e.
void SumColumnRanges (const CuMatrixBase< Real > &src, const CuArray< Int32Pair > &indexes)
For each row r of this and for each column c, sets (*this)(r, c) to the sum src(r, j), where j ranges from indexes[c].first through indexes[c].second - 1.
void AddRowRanges (const CuMatrixBase< Real > &src, const CuArray< Int32Pair > &indexes)
For each row r of this and for each column c, do (*this)(r, c) += src(j, c), where j ranges from indexes[r].first through indexes[r].second - 1.
void AddToDiag (Real value)
Adds "value" to the diagonal elements of the matrix.
MatrixIndexT NumRows () const
Dimensions.
MatrixIndexT NumCols () const
MatrixIndexT Stride () const
::MatrixDim Dim () const
Real FrobeniusNorm () const
bool IsUnit (Real tol=0.001) const
bool ApproxEqual (const CuMatrixBase< Real > &other, float tol=0.01) const
True if ((*this)-other).FrobeniusNorm() <= tol * this->FrobeniusNorm()
MatrixIndexT SizeInBytes () const
Get size of matrix in bytes.
template<typename OtherReal >
void CopyFromMat (const MatrixBase< OtherReal > &src, MatrixTransposeType trans=kNoTrans)
void CopyFromGeneralMat (const GeneralMatrix &src, MatrixTransposeType trans=kNoTrans)
void CopyFromMat (const MatrixBase< Real > &src, MatrixTransposeType trans=kNoTrans)
void CopyFromSp (const CuSpMatrix< Real > &M)
template<typename OtherReal >
void CopyFromTp (const CuTpMatrix< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
template<typename OtherReal >
void CopyFromMat (const CuMatrixBase< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
template<typename OtherReal >
void CopyToMat (MatrixBase< OtherReal > *dst, MatrixTransposeType trans=kNoTrans) const
void CopyRowsFromVec (const CuVectorBase< Real > &v)
This function has two modes of operation.
void CopyRowsFromVec (const VectorBase< Real > &v)
Version of CopyRowsFromVec() that takes a CPU-based vector.
void CopyColFromVec (const CuVectorBase< Real > &v, const MatrixIndexT col)
Copy vector into specific column of matrix.
void Sigmoid (const CuMatrixBase< Real > &src)
Set each element to the sigmoid of the corresponding element of "src": element by element, x = 1 / (1 + exp(-x))
void SoftHinge (const CuMatrixBase< Real > &src)
Apply the function y = log(1 + exp(x)), to each element.
void GroupPnorm (const CuMatrixBase< Real > &src, Real pow)
Apply the function y(i) = (sum_{j = i*G}^{(i+1)*G-1} x_j ^ (power)) ^ (1 / p) where G = x.NumCols() / y.NumCols() must be an integer.
void GroupPnormDeriv (const CuMatrixBase< Real > &input, const CuMatrixBase< Real > &output, Real power)
Calculate derivatives for the GroupPnorm function above...
void GroupMax (const CuMatrixBase< Real > &src)
Apply the function y(i) = (max_{j = i*G}^{(i+1)*G-1} x_j where G = x.NumCols() / y.NumCols() must be an integer.
void GroupMaxDeriv (const CuMatrixBase< Real > &input, const CuMatrixBase< Real > &output)
Calculate derivatives for the GroupMax function above, where "input" is the input to the GroupMax function above (i.e.
void Tanh (const CuMatrixBase< Real > &src)
Compute the hyperbolic tangent (tanh) function; element by element, *this = tanh(src).
void DiffSigmoid (const CuMatrixBase< Real > &value, const CuMatrixBase< Real > &diff)
Differentiate backward through the sigmoid function.
void DiffTanh (const CuMatrixBase< Real > &value, const CuMatrixBase< Real > &diff)
Differentiate backward through the tanh function.
void DiffXent (const CuArray< int32 > &tgt, CuVector< Real > *log_post_tgt)
Differentiate the block [softmax+cross-entropy] : dE/da = posterior_mat - target_mat, 'E' is error function, 'a' is activation on softmax input.
void Cholesky (CuMatrixBase< Real > *inv_cholesky=NULL)
This function does sets *this to the Cholesky factor of *this (i.e.
void SymInvertPosDef ()
Inversion for positive definite symmetric matrices.
void ApplyPow (Real power)
Apply power to the absolute value of each element.
void ApplyPowAbs (Real power, bool include_sign=false)
void ApplyHeaviside ()
For each element, sets x = (x > 0 ? 1.0 : 0.0)
void ApplyFloor (Real floor_val)
void ApplyCeiling (Real ceiling_val)
void ApplyExp ()
void ApplySoftMaxPerRow (const CuMatrixBase< Real > &src)
Softmax nonlinearity Y = Softmax(X) : Yij = e^Xij / sum_k(e^Xik), done to each row for each row, the max value is first subtracted for good numerical stability.
void ApplyLogSoftMaxPerRow (const CuMatrixBase< Real > &src)
LogSoftmax nonlinearity Y = LogSoftmax(X) : Yij = Xij - log(sum_k(e^Xik)), done to each row for each row, the max value is first subtracted for good numerical stability.
void FindRowMaxId (CuArray< int32 > *id) const
Find the id of the maximal element for each row.
void SetZero ()
Math operations, some calling kernels.
void Set (Real value)
void Add (Real value)
void SetZeroAboveDiag ()
Zeroes all elements for which col > row.
void Scale (Real value)
void ApplyLog ()
void MulElements (const CuMatrixBase< Real > &A)
Multiply two matrices elementwise: C = C .* A.
void DivElements (const CuMatrixBase< Real > &A)
Divide two matrices elementwise: C = A ./ A.
void Max (const CuMatrixBase< Real > &A)
Do, elementwise, *this = max(*this, A).
void MulColsVec (const CuVectorBase< Real > &scale)
scale i'th column by scale[i]
void MulRowsVec (const CuVectorBase< Real > &scale)
scale i'th row by scale[i]
void MulRowsGroupMat (const CuMatrixBase< Real > &src)
divide each row into src.NumCols() groups, and then scale i'th row's jth group of elements by src[i, j].
void DivRowsVec (const CuVectorBase< Real > &div)
divide i'th row by scale[i]
void InvertElements ()
invert the matrix by elements.
void AddMat (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType trans=kNoTrans)
*this += alpha * A
void AddMatBlocks (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType trans=kNoTrans)
if A.NumRows() is multiple of (*this)->NumRows and A.NumCols() is multiple of (*this)->NumCols divide A into blocks of the same size as (*this) and add them to *this (times alpha)
void AddVecToCols (Real alpha, const CuVectorBase< Real > &col, Real beta=1.0)
(for each column c of *this), c = alpha * col + beta * c
void AddVecToRows (Real alpha, const CuVectorBase< Real > &row, Real beta=1.0)
(for each row r of *this), r = alpha * row + beta * r
void AddMatMat (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuMatrixBase< Real > &B, MatrixTransposeType transB, Real beta)
C = alpha * A(^T)*B(^T) + beta * C.
void AddVecVec (Real alpha, const CuVectorBase< Real > &x, const CuVectorBase< Real > &y)
A = alpha * x * y^T + A .
void AddMatMatDivMat (const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, const CuMatrixBase< Real > &C)
*this = a * b / c (by element; when c = 0, *this = a)
void SymAddMat2 (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transA, Real beta)
*this = beta * *this + alpha * M M^T, for symmetric matrices.
void AddMatBlock (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuBlockMatrix< Real > &B, MatrixTransposeType transB, Real beta)
This function is like AddMatMat but for where the second argument is of type CuBlockMatrix (a block-diagonal matrix of blocks).
void AddDiagVecMat (const Real alpha, const CuVectorBase< Real > &v, const CuMatrixBase< Real > &M, MatrixTransposeType transM, Real beta=1.0)
*this = beta * *this + alpha * diag(v) * M [or M^T].
void AddMatDiagVec (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transM, CuVectorBase< Real > &v, Real beta=1.0)
void AddMatMatElements (const Real alpha, const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, const Real beta)
*this = beta * *this + alpha * A .* B (.* element by element multiplication)
void AddVecMatPointMulVec (const Real alpha, const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, const Real beta, MatrixIndexT batch_index)
sc function element of vector multiply rows vector of matrix
void AddMatSp (const Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuSpMatrix< Real > &B, const Real beta)
this <– beta*this + alpha*A*B
void AddSpMat (const Real alpha, const CuSpMatrix< Real > &A, const CuMatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*SpA*B
void AddTpMat (const Real alpha, const CuTpMatrix< Real > &A, MatrixTransposeType transA, const CuMatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void AddMatTp (const Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuTpMatrix< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void CopyFromBlock (const CuBlockMatrix< Real > &B, MatrixTransposeType trans=kNoTrans)
void CopyLowerToUpper ()
void CopyUpperToLower ()
CuSubMatrix< Real > Range (const MatrixIndexT row_offset, const MatrixIndexT num_rows, const MatrixIndexT col_offset, const MatrixIndexT num_cols) const
CuSubMatrix< Real > RowRange (const MatrixIndexT row_offset, const MatrixIndexT num_rows) const
CuSubMatrix< Real > ColRange (const MatrixIndexT col_offset, const MatrixIndexT num_cols) const
const CuSubVector< Real > Row (MatrixIndexT i) const
CuSubVector< Real > Row (MatrixIndexT i)
CuValue< Real > operator() (MatrixIndexT r, MatrixIndexT c)
Real operator() (MatrixIndexT r, MatrixIndexT c) const
Real Sum () const
Real Max () const
proxy to MatrixBase::Max(), cuda not used
Real Min () const
proxy to MatrixBase::Min(), cuda not used
Real Trace (bool check_square=true) const
Return the trace. If check_square = true, will crash if matrix is not square.
void SetRandn ()
void SetRandUniform ()
void Write (std::ostream &os, bool binary) const
void AddElements (Real alpha, const std::vector< MatrixElement< Real > > &input)
void AddElements (Real alpha, const CuArray< Int32Pair > &indexes, const Real *input)
void Lookup (const std::vector< Int32Pair > &indexes, Real *output) const
void Lookup (const CuArray< Int32Pair > &indexes, Real *output) const
void EqualElementMask (const CuMatrixBase< Real > &mat, CuMatrix< Real > *mask) const
const Real * RowData (MatrixIndexT r) const
Get raw row pointer (const).
Real * RowData (MatrixIndexT r)
Get raw row pointer.
const Real * Data () const
Return data pointer (const).
Real * Data ()
Return data pointer.
const MatrixBase< Real > & Mat () const
MatrixBase< Real > & Mat ()
Protected Member Functions
CuMatrixBase ()
CuMatrixBase (Real *data, MatrixIndexT num_rows, MatrixIndexT num_cols, MatrixIndexT stride)
This constructor takes the #rows, #cols and stride; it's called from the constructor of CuSubMatrix.
Protected Attributes
Real * data_
GPU data pointer (or regular matrix data pointer,.
MatrixIndexT num_cols_
MatrixIndexT num_rows_
MatrixIndexT stride_
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (CuMatrixBase)
Friends
class CuMatrixBase< float >
class CuMatrixBase< double >
class CuVectorBase< float >
class CuVectorBase< double >
class VectorBase< Real >
class CuSpMatrix< Real >
class CuTpMatrix< float >
class CuTpMatrix< double >
class CuVectorBase< Real >
class CuSubMatrix< Real >
class CuRand< Real >
class CuSubVector< Real >
class CuBlockMatrix< Real >
class CuSparseMatrix< float >
class CuSparseMatrix< double >
class CuSparseMatrix< Real >
Real TraceMatMat (const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, MatrixTransposeType trans)
Real TraceMatSmat (const CuMatrixBase< Real > &A, const CuSparseMatrix< Real > &B, MatrixTransposeType trans)
void AddMatMatBatched (const Real alpha, std::vector< CuSubMatrix< Real > * > &C, const std::vector< CuSubMatrix< Real > * > &A, MatrixTransposeType transA, const std::vector< CuSubMatrix< Real > * > &B, MatrixTransposeType transB, const Real beta)
Does multiple matrix multiplications, executing them in parallel using cuBLAS's gemmBatched if we are using a GPU.
Detailed Description
template<typename Real>
class kaldi::CuMatrixBase< Real >
Matrix for CUDA computing.
Does the computation on the CUDA card when CUDA is compiled in and we have a suitable GPU (CuDevice::Instantiate().Enabled() == true); otherwise, does it on the CPU.
Definition at line 62 of file matrix-common.h.
Constructor & Destructor Documentation
CuMatrixBase () inline protected
Definition at line 594 of file cu-matrix.h.
 : data_(NULL), num_cols_(0), num_rows_(0), stride_(0) { }
CuMatrixBase (Real * data, MatrixIndexT num_rows, MatrixIndexT num_cols, MatrixIndexT stride) inline protected
This constructor takes the #rows, #cols and stride; it's called from the constructor of CuSubMatrix.
Definition at line 598 of file cu-matrix.h.
                                    :
   data_(data), num_cols_(num_cols), num_rows_(num_rows), stride_(stride) { }
Member Function Documentation
void Add (Real value)
Definition at line 531 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by TanhComponent::Backprop(), Xent::Eval(), LstmProjectedStreams::InitMatParam(), BLstmProjectedStreams::InitMatParam(), DropoutComponent::Propagate(), TanhComponent::StoreStats(), kaldi::TestCuMatrixCompObjfAndDeriv(), kaldi::UnitTestCuMatrixAdd(), kaldi::UnitTestCuMatrixAdd2(), kaldi::UnitTestCuMatrixEqualElementMask(), kaldi::UnitTestCuMatrixObjfDeriv(), and kaldi::UnitTestCuMatrixSetRandUniform().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add(dimGrid, dimBlock, data_, value, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().Add(value);
   }
 }
void AddCols (const CuMatrixBase< Real > & src, const CuArray< MatrixIndexT > & indices)
Add column indices[r] of src to column r.
As a special case, if indexes[i] == -1, skip column i indices.size() must equal this->NumCols(), all elements of "reorder" must be in [-1, src.NumCols()-1], and src.NumRows() must equal this.NumRows()
Definition at line 2182 of file cu-matrix.cc.
References CuArray< T >::Data(), CuMatrixBase< Real >::Data(), CuArray< T >::Dim(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by Convolutional1dComponent::Backprop(), ConvolutionalComponent::BackpropagateFnc(), and ConvolutionComponent::InderivPatchesToInderiv().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(indices.Dim() == NumCols());
     KALDI_ASSERT(NumRows() == src.NumRows());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_cols(dimGrid, dimBlock, data_, src.Data(), indices.Data(),
                   Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddCols(src.Mat(), indices.Data());
   }
 }
void AddDiagVecMat (const Real alpha, const CuVectorBase< Real > & v, const CuMatrixBase< Real > & M, MatrixTransposeType transM, Real beta = 1.0)
*this = beta * *this + alpha * diag(v) * M [or M^T].
The same as adding M but scaling each row M_i by v(i).
Definition at line 1133 of file cu-matrix.cc.
References CU2DBLOCK, CuVectorBase< Real >::Data(), CuMatrixBase< Real >::Data(), CuVectorBase< Real >::Dim(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::SameDim(), CuMatrixBase< Real >::Stride(), kaldi::swap(), and CuVectorBase< Real >::Vec().
Referenced by NormalizeComponent::Backprop(), SoftmaxComponent::Backprop(), OnlineNaturalGradient::ComputeWt1(), OnlinePreconditioner::ComputeWt1(), and kaldi::TestCuMatrixAddDiagVecMat().
                {
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (transM == kNoTrans) {
       KALDI_ASSERT(SameDim(*this, M));
     } else {
       KALDI_ASSERT(M.NumRows() == NumCols() && M.NumCols() == NumRows());
     }
     KALDI_ASSERT(v.Dim() == this->NumRows());
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(num_cols_, CU2DBLOCK),
                  n_blocks(num_rows_, CU2DBLOCK));
     MatrixIndexT M_row_stride = M.Stride(), M_col_stride = 1;
     if (transM == kTrans)
       std::swap(M_row_stride, M_col_stride);
     cuda_add_diag_vec_mat(dimGrid, dimBlock, alpha, data_, Dim(),
                           v.Data(), M.Data(), M_row_stride, M_col_stride, beta);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddDiagVecMat(alpha, v.Vec(), M.Mat(), transM, beta);
   }
 }
void AddElements (Real alpha, const std::vector< MatrixElement< Real > > & input)
Definition at line 2686 of file cu-matrix.cc.
References CU1DBLOCK, rnnlm::i, and KALDI_ASSERT.
Referenced by OnlineNaturalGradient::InitOrthonormalSpecial(), OnlinePreconditioner::InitOrthonormalSpecial(), and kaldi::UnitTestCuMatrixAddElements().
{
   // Checks the dimension.
   MatrixIndexT num_rows = this->num_rows_, num_cols = this->num_cols_;
   for (int32 i = 0; i < input.size(); ++i) {
     KALDI_ASSERT(input[i].row < num_rows && input[i].row >= 0 &&
                  input[i].column < num_cols && input[i].column >= 0);
   }
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     void *addr = CuDevice::Instantiate().Malloc(input.size() * sizeof(MatrixElement<Real>));
     CU_SAFE_CALL(cudaMemcpy(addr, input.data(),
                         input.size() * sizeof(MatrixElement<Real>),
                             cudaMemcpyHostToDevice));
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(input.size(), CU1DBLOCK));
     cuda_matrix_add_elements(dimGrid, dimBlock, this->data_, this->Dim(),
                              alpha, (MatrixElement<Real>*)addr, input.size());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().Free(addr);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     for (int32 i = 0; i < input.size(); i++) {
       (*this)(input[i].row, input[i].column) += alpha * input[i].weight;
     }
   }
 }
void AddElements (Real alpha, const CuArray< Int32Pair > & indexes, const Real * input)
Definition at line 2720 of file cu-matrix.cc.
References CU1DBLOCK, CuArray< T >::Data(), CuArray< T >::Dim(), Timer::Elapsed(), Int32Pair::first, rnnlm::i, KALDI_ASSERT, kaldi::kUndefined, and Int32Pair::second.
{
   if (indexes.Dim() == 0) return;
   KALDI_ASSERT(input != NULL);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CuVector<Real> tmp_vec(indexes.Dim(), kUndefined);
     CU_SAFE_CALL(cudaMemcpy(tmp_vec.Data(), input, indexes.Dim() * sizeof(Real),
                             cudaMemcpyHostToDevice));
     int dimBlock(CU1DBLOCK);
     int dimGrid = n_blocks(indexes.Dim(), CU1DBLOCK);
     cuda_matrix_add_indexed_values(dimGrid, dimBlock, this->Dim(), alpha,
                                    indexes.Data(), tmp_vec.Data(), indexes.Dim(), this->data_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     MatrixIndexT num_rows = this->num_rows_, num_cols = this->num_cols_;
     const Int32Pair *index = indexes.Data();
     for (int32 i = 0; i < indexes.Dim(); i++) {
       KALDI_ASSERT(index[i].first < num_rows && index[i].first >= 0 &&
                    index[i].second < num_cols && index[i].second >= 0);
       (*this)(index[i].first, index[i].second) += alpha * input[i];
     }
   }
 }
void AddMat (Real alpha, const CuMatrixBase< Real > & A, MatrixTransposeType trans = kNoTrans)
*this += alpha * A
Definition at line 881 of file cu-matrix.cc.
References CU2DBLOCK, CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by RepeatedAffineComponent::Add(), NaturalGradientAffineComponent::Add(), AffineComponent::Add(), BlockAffineComponent::Add(), ConvolutionComponent::Add(), Convolutional1dComponent::Add(), CuRand< Real >::AddGaussNoise(), GeneralMatrix::AddToMat(), CuMatrixBase< Real >::ApproxEqual(), SigmoidComponent::Backprop(), LogSoftmaxComponent::Backprop(), AveragePoolingComponent::BackpropagateFnc(), AveragePooling2DComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), Xent::Eval(), Mse::Eval(), NnetComputer::ExecuteCommand(), RepeatedAffineComponent::PerturbParams(), AffineComponent::PerturbParams(), BlockAffineComponent::PerturbParams(), ConvolutionComponent::PerturbParams(), Convolutional1dComponent::PerturbParams(), SumReduceComponent::Propagate(), AdditiveNoiseComponent::Propagate(), Rbm::RbmUpdate(), kaldi::UnitTestCuMatrixAddMat(), kaldi::UnitTestCuMatrixAddMatDiagVec(), kaldi::UnitTestCuMatrixAddMatMatElements(), kaldi::nnet3::UnitTestNnetInputDerivatives(), LinearTransform::Update(), AffineTransform::Update(), TCNProjectionComponent::Update(), TCNComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), LstmProjectedStreams::Update(), BLstmProjectedStreams::Update(), ConvolutionComponent::Update(), and Convolutional1dComponent::Update().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (transA == kNoTrans) {
       KALDI_ASSERT(A.NumRows() == num_rows_ && A.NumCols() == num_cols_);
     } else {
       KALDI_ASSERT(A.NumCols() == num_rows_ && A.NumRows() == num_cols_);
     }
     if (num_rows_ == 0) return;
     Timer tim;
     // This block dimension seems to work better than the
     // one from GetBlockSizesForSimpleMatrixOperation().
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(NumCols(), CU2DBLOCK),
                  n_blocks(NumRows(), CU2DBLOCK));
     cuda_add_mat(dimGrid, dimBlock, alpha, A.data_,
                  data_, Dim(), A.Stride(),
                  (transA == kTrans ? 1 : 0));
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddMat(alpha, A.Mat(), transA);
   }
 }
void AddMatBlock (Real alpha, const CuMatrixBase< Real > & A, MatrixTransposeType transA, const CuBlockMatrix< Real > & B, MatrixTransposeType transB, Real beta)
This function is like AddMatMat but for where the second argument is of type CuBlockMatrix (a block-diagonal matrix of blocks).
Definition at line 2614 of file cu-matrix.cc.
References CuMatrixBase< Real >::AddMatMat(), CuBlockMatrix< Real >::Block(), CU2DBLOCK, CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuBlockMatrix< Real >::NumBlocks(), CuBlockMatrix< Real >::NumCols(), CuMatrixBase< Real >::NumCols(), CuBlockMatrix< Real >::NumRows(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Stride(), and kaldi::swap().
Referenced by kaldi::UnitTestCuBlockMatrixAddMatBlock().
                {
   // Check dimensions
   int32 A_num_rows = A.NumRows(), A_num_cols = A.NumCols(),
       A_row_stride = A.Stride(), A_col_stride = 1,
       B_num_rows = B.NumRows(), B_num_cols = B.NumCols();
   if (transA == kTrans) {
     std::swap(A_num_rows, A_num_cols);
     std::swap(A_row_stride, A_col_stride);
   }
   if (transB == kTrans) {
     std::swap(B_num_rows, B_num_cols);
   }
   // At this point the {A,B}_{rows,cols} variables are
   // after any transposition.
   KALDI_ASSERT(NumRows() == A_num_rows && NumCols() == B_num_cols);
   KALDI_ASSERT(A_num_cols == B_num_rows);
   int32 B_num_blocks = B.NumBlocks();
   if (num_rows_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     MatrixDim this_dim = Dim();
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     // (x,y) indices will be (row of *this, block of B)
     dim3 dimGrid(n_blocks(num_rows_, CU2DBLOCK),
                  n_blocks(B_num_blocks, CU2DBLOCK));
     // caution: the use of x as the row-index is not good, but
     // this code is not much used, so I'm not updating it.a
     cuda_add_mat_blockmat(dimGrid, dimBlock, data_, this_dim, A.Data(),
                           A_num_rows, A_num_cols, A_row_stride, A_col_stride,
                           B.CuData(), B_num_blocks, alpha, beta,
                           (transB == kTrans ? 1 : 0));
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     // "row_offset" and "col_offset" are offsets into B (or into B^T, if
     // transB == kTrans).
     int32 row_offset = 0, col_offset = 0;
     for (int32 b = 0; b < B_num_blocks; b++) {
       const CuSubMatrix<Real> this_block = B.Block(b);
       int32 this_num_rows = this_block.NumRows(),
           this_num_cols = this_block.NumCols();
       if (transB == kTrans) std::swap(this_num_rows, this_num_cols);
       CuSubMatrix<Real> this_part(*this, 0, num_rows_,
                                   col_offset, this_num_cols);
       CuSubMatrix<Real> A_part = (transA == kNoTrans ?
                                   CuSubMatrix<Real>(A, 0, num_rows_,
                                                     row_offset, this_num_rows) :
                                   CuSubMatrix<Real>(A, row_offset, this_num_rows,
                                                     0, num_rows_));
       this_part.AddMatMat(alpha, A_part, transA, this_block, transB, beta);
       row_offset += this_num_rows;
       col_offset += this_num_cols;
     }
     // Note: the values being compared below are all after applying any
     // transposition to B.
     KALDI_ASSERT(row_offset == B_num_rows && col_offset == B_num_cols);
   }
 }
void AddMatBlocks (Real alpha, const CuMatrixBase< Real > & A, MatrixTransposeType trans = kNoTrans)
if A.NumRows() is multiple of (*this)->NumRows and A.NumCols() is multiple of (*this)->NumCols divide A into blocks of the same size as (*this) and add them to *this (times alpha)
Definition at line 912 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), rnnlm::i, rnnlm::j, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by kaldi::UnitTestCuMatrixAddMatBlocks(), ConvolutionComponent::Update(), and Convolutional1dComponent::Update().
{
   if (num_rows_ == 0 || num_cols_ == 0) return;
   int32 num_row_blocks, num_col_blocks;
   if (transA == kNoTrans) {
     KALDI_ASSERT(A.NumRows() % num_rows_ == 0 && A.NumCols() % num_cols_ == 0);
     num_row_blocks = A.Mat().NumRows() / num_rows_;
     num_col_blocks = A.Mat().NumCols() / num_cols_;
   } else {
     KALDI_ASSERT(A.NumRows() % num_cols_ == 0 && A.NumCols() % num_rows_ == 0);
     num_row_blocks = A.Mat().NumRows() / num_cols_;
     num_col_blocks = A.Mat().NumCols() / num_rows_;
   }
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_mat_blocks(dimGrid, dimBlock, alpha, A.data_, num_row_blocks,
                     num_col_blocks, data_, Dim(), A.Stride(),
                     (transA == kTrans ? 1 : 0));
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     int32 nr, nc;
     if (transA == kNoTrans) {
       nr = num_rows_;
       nc = num_cols_;
     } else {
       nr = num_cols_;
       nc = num_rows_;
     }
     for (int32 i = 0; i < num_row_blocks; i++) {
       for (int32 j = 0; j < num_col_blocks; j++) {
         Mat().AddMat(alpha, SubMatrix<Real>(A.Mat(), i * nr, nr, j * nc, nc),
                         transA);
       }
     }
   }
 }
void AddMatDiagVec (const Real alpha, const CuMatrixBase< Real > & M, MatrixTransposeType transM, CuVectorBase< Real > & v, Real beta = 1.0)
Definition at line 1166 of file cu-matrix.cc.
References CuVectorBase< Real >::Data(), CuMatrixBase< Real >::Data(), CuVectorBase< Real >::Dim(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::SameDim(), CuMatrixBase< Real >::Stride(), kaldi::swap(), and CuVectorBase< Real >::Vec().
                {
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (transM == kNoTrans) {
       KALDI_ASSERT(SameDim(*this, M));
     } else {
       KALDI_ASSERT(M.NumRows() == NumCols() && M.NumCols() == NumRows());
     }
     KALDI_ASSERT(v.Dim() == this->NumCols());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     MatrixIndexT M_row_stride = M.Stride(), M_col_stride = 1;
     if (transM == kTrans) std::swap(M_row_stride, M_col_stride);
     cuda_add_mat_diag_vec(dimGrid, dimBlock, alpha, data_, Dim(),
                           M.Data(), M_row_stride, M_col_stride, v.Data(),  beta);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddMatDiagVec(alpha, M.Mat(), transM, v.Vec(), beta);
   }
 }
void AddMatMat (Real alpha, const CuMatrixBase< Real > & A, MatrixTransposeType transA, const CuMatrixBase< Real > & B, MatrixTransposeType transB, Real beta)
C = alpha * A(^T)*B(^T) + beta * C.
Definition at line 1043 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, kaldi::kTrans, CuMatrixBase< Real >::Mat(), rnnlm::n, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by CuMatrixBase< Real >::AddMatBlock(), CuBlockMatrix< Real >::AddMatMat(), CuMatrixBase< BaseFloat >::AddMatSp(), CuMatrixBase< BaseFloat >::AddMatTp(), CuMatrixBase< BaseFloat >::AddSpMat(), CuMatrixBase< BaseFloat >::AddTpMat(), AffineComponent::Backprop(), FixedLinearComponent::Backprop(), FixedAffineComponent::Backprop(), LinearTransform::BackpropagateFnc(), AffineTransform::BackpropagateFnc(), TCNProjectionComponent::BackpropagateFnc(), ConvolutionalComponent::BackpropagateFnc(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), AffineComponent::CollapseWithNext(), AffineComponent::CollapseWithPrevious(), OnlineNaturalGradient::ComputeWt1(), OnlinePreconditioner::ComputeWt1(), kaldi::CuVectorUnitTestAddDiagMatMat(), OnlineNaturalGradient::InitOrthonormalSpecial(), OnlinePreconditioner::InitOrthonormalSpecial(), kaldi::nnet2::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), AffineComponent::Propagate(), DctComponent::Propagate(), FixedLinearComponent::Propagate(), FixedAffineComponent::Propagate(), KlHmm::PropagateFnc(), LinearTransform::PropagateFnc(), AffineTransform::PropagateFnc(), TCNProjectionComponent::PropagateFnc(), Rbm::PropagateFnc(), LstmProjectedStreams::PropagateFnc(), BLstmProjectedStreams::PropagateFnc(), Rbm::RbmUpdate(), Rbm::Reconstruct(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), kaldi::TestCuMatrixMatMat(), kaldi::UnitTestCuBlockMatrixAddMatMat(), kaldi::UnitTestCuCholesky(), kaldi::UnitTestCuMatrixAddMatMat(), kaldi::UnitTestCuMatrixSymAddMat2(), kaldi::UnitTestCuMatrixSymInvertPosDef(), kaldi::UnitTestCuSpMatrixInvert(), LinearTransform::Update(), AffineTransform::Update(), TCNProjectionComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), BlockAffineComponentPreconditioned::Update(), AffineComponent::UpdateSimple(), and BlockAffineComponent::UpdateSimple().
{
     // CUBLAS is col-major, cudamatrix is row-major, how to do the mapping?
     // keep trans..., just swap A&B matrices: A->B B->A
     MatrixIndexT m = ((transB==kTrans)? B.NumRows() : B.NumCols());
     MatrixIndexT n = ((transA==kTrans)? A.NumCols() : A.NumRows());
     MatrixIndexT k = ((transB==kTrans)? B.NumCols() : B.NumRows());
     MatrixIndexT k1 = ((transA==kTrans)? A.NumRows() : A.NumCols());
     KALDI_ASSERT(m == NumCols());
     KALDI_ASSERT(n == NumRows());
     KALDI_ASSERT(k == k1);
     if (m == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cublas_gemm(GetCublasHandle(),
                             (transB==kTrans? CUBLAS_OP_T:CUBLAS_OP_N),
                             (transA==kTrans? CUBLAS_OP_T:CUBLAS_OP_N),
                             m, n, k, alpha, B.data_, B.Stride(),
                             A.data_, A.Stride(), beta, data_, Stride()));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddMatMat(alpha, A.Mat(), transA, B.Mat(), transB, beta);
   }
 }
void AddMatMatDivMat (const CuMatrixBase< Real > & A, const CuMatrixBase< Real > & B, const CuMatrixBase< Real > & C)
*this = a * b / c (by element; when c = 0, *this = a)
Definition at line 958 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, and CuMatrixBase< Real >::Stride().
Referenced by DropoutComponent::Backprop().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(num_rows_ == A.num_rows_ && num_cols_ == A.num_cols_);
     KALDI_ASSERT(num_rows_ == B.num_rows_ && num_cols_ == B.num_cols_);
     KALDI_ASSERT(num_rows_ == C.num_rows_ && num_cols_ == C.num_cols_);
     if (num_rows_ == 0) return;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_mat_mat_div_mat(dimGrid, dimBlock, A.data_, B.data_, C.data_,
                              data_, Dim(), A.Stride(), B.Stride(), C.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddMatMatDivMat(A.Mat(), B.Mat(), C.Mat());
   }
 }
void AddMatMatElements (const Real alpha, const CuMatrixBase< Real > & A, const CuMatrixBase< Real > & B, const Real beta)
*this = beta * *this + alpha * A .* B (.* element by element multiplication)
Definition at line 1198 of file cu-matrix.cc.
References CuMatrixBase< Real >::Data(), Timer::Elapsed(), CuMatrixBase< Real >::Mat(), and CuMatrixBase< Real >::Stride().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_mat_mat_elements(dimGrid, dimBlock, this->data_, A.Data(),
                               B.Data(), Dim(), A.Stride(), B.Stride(), alpha, beta);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddMatMatElements(alpha, A.Mat(), B.Mat(), beta);
   }
 }
void AddMatSp (const Real alpha, const CuMatrixBase< Real > & A, MatrixTransposeType transA, const CuSpMatrix< Real > & B, const Real beta) inline
this <– beta*this + alpha*A*B
Definition at line 441 of file cu-matrix.h.
{
     CuMatrix<Real> M(B);
     return AddMatMat(alpha, A, transA, M, kNoTrans, beta);
   }
void AddMatTp (const Real alpha, const CuMatrixBase< Real > & A, MatrixTransposeType transA, const CuTpMatrix< Real > & B, MatrixTransposeType transB, const Real beta) inline
this <– beta*this + alpha*A*B.
Definition at line 468 of file cu-matrix.h.
Referenced by kaldi::UnitTestCuMatrixAddMatTp().
{
     CuMatrix<Real> M(B);
     return AddMatMat(alpha, A, transA, M, transB, beta);
   }
void AddRowRanges (const CuMatrixBase< Real > & src, const CuArray< Int32Pair > & indexes)
For each row r of this and for each column c, do (*this)(r, c) += src(j, c), where j ranges from indexes[r].first through indexes[r].second - 1.
In general indexes must be >= 0 and < src.NumRows(); but to represent an empty range you may use the pair (-1, -1) or any pair of numbers (i, j) such that i >= j.
Definition at line 2353 of file cu-matrix.cc.
References CuArray< T >::Data(), CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::data_, CuArray< T >::Dim(), CuMatrixBase< Real >::Dim(), Timer::Elapsed(), Int32Pair::first, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), Int32Pair::second, and CuMatrixBase< Real >::stride_.
Referenced by NnetComputer::ExecuteCommand(), and kaldi::UnitTestCuMatrixAddRowRanges().
{
   KALDI_ASSERT(static_cast<MatrixIndexT>(indexes.Dim()) == NumRows());
   KALDI_ASSERT(src.NumCols() == NumCols());
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_row_ranges(dimGrid, dimBlock,
                         data_, Dim(), src.Data(), src.Dim(), indexes.Data());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   { // Implement here for the CPU..
     int32 num_rows = this->num_rows_, num_cols = this->num_cols_,
           this_stride = this->stride_, src_stride = src.stride_;
     Real *data = this->data_;
     const Real *src_data = src.data_;
     const Int32Pair *indexes_data = indexes.Data();
     for (int32 row = 0; row < num_rows; row++) {
       int32 start_row = indexes_data[row].first,
           end_row = indexes_data[row].second;
       for (int32 col = 0; col < num_cols; col++) {
         Real sum = 0.0;
         for (int32 src_row = start_row; src_row < end_row; src_row++)
           sum += src_data[src_row * src_stride + col];
         data[row * this_stride + col] += sum;
       }
     }
   }
 }
void AddRows (Real alpha, const CuMatrixBase< Real > & src, const CuArray< MatrixIndexT > & indexes)
Does for each row r, this.Row(r) += alpha * src.row(indexes[r]).
If indexes[r] < 0, does not add anything. "reorder".size() must equal this->NumRows(), all elements of "reorder" must be in [0, src.NumRows()-1], and src.NumCols() must equal this.NumCols()
Definition at line 2247 of file cu-matrix.cc.
References CuArray< T >::Data(), CuMatrixBase< Real >::Data(), CuArray< T >::Dim(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::Stride().
Referenced by NnetComputer::ExecuteCommand().
{
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(static_cast<MatrixIndexT>(indexes.Dim()) == NumRows());
     KALDI_ASSERT(src.NumCols() == NumCols());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_rows(dimGrid, dimBlock, alpha,
                   data_, src.Data(), indexes.Data(), Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddRows(alpha, src.Mat(), indexes.Data());
   }
 }
void AddRows (Real alpha, const CuArray< const Real * > & src)
Does for each row r, this.Row(r) += alpha * src[r], treating src[r] as the beginning of a region of memory representing a vector of floats, of the same length as this.NumCols().
Definition at line 2272 of file cu-matrix.cc.
References CuArray< T >::Data(), CuArray< T >::Dim(), and KALDI_ASSERT.
{
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(static_cast<MatrixIndexT>(src.Dim()) == NumRows());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_rows(dimGrid, dimBlock, alpha, data_, src.Data(), Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddRows(alpha, src.Data());
   }
 }
void AddSpMat (const Real alpha, const CuSpMatrix< Real > & A, const CuMatrixBase< Real > & B, MatrixTransposeType transB, const Real beta) inline
this <– beta*this + alpha*SpA*B
Definition at line 450 of file cu-matrix.h.
{
     CuMatrix<Real> M(A);
     return AddMatMat(alpha, M, kNoTrans, B, transB, beta);
   }
void AddToDiag (Real value)
Adds "value" to the diagonal elements of the matrix.
The matrix *this does not have to be square.
Definition at line 553 of file cu-matrix.cc.
References CU1DBLOCK, rnnlm::d, and Timer::Elapsed().
Referenced by kaldi::nnet2::PreconditionDirections(), kaldi::TestCuMatrixCholesky(), and kaldi::UnitTestCuMatrixAddToDiag().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     Timer tim;
     // We'll create a fake matrix with "num_diag" rows, one
     // columnn, and a stride of "this_stride".  The y-value of
     // the grid/blocks corresponds to the row, in this kernel.
     MatrixIndexT num_diag = std::min(num_rows_, num_cols_),
         this_stride = stride_ + 1;
     dim3 dimBlock(1, CU1DBLOCK);
     dim3 dimGrid(1, n_blocks(num_diag, CU1DBLOCK));
     ::MatrixDim d = { num_diag, 1, this_stride };
     cuda_add(dimGrid, dimBlock, data_, value, d);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().AddToDiag(value);
   }
 }
void AddToRows (Real alpha, const CuArray< Real * > & dst) const
For each row r of this matrix, adds it (times alpha) to the array of floats at the location given by dst[r], where dst[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (i.e.
it should point to memory on the GPU if we're using a GPU, or on the CPU otherwise). If dst[r] is NULL, does not do anything for that row. Requires that none of the memory regions pointed to by the pointers in "dst" overlap (e.g. none of the pointers should be the same).
Definition at line 2293 of file cu-matrix.cc.
References CuArray< T >::Data(), CuArray< T >::Dim(), and KALDI_ASSERT.
Referenced by NnetComputer::ExecuteCommand(), and kaldi::UnitTestCuMatrixAddToRows().
{
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(static_cast<MatrixIndexT>(dst.Dim()) == NumRows());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_to_rows(dimGrid, dimBlock, alpha, dst.Data(), data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddToRows(alpha, dst.Data());
   }
 }
void AddTpMat (const Real alpha, const CuTpMatrix< Real > & A, MatrixTransposeType transA, const CuMatrixBase< Real > & B, MatrixTransposeType transB, const Real beta) inline
this <– beta*this + alpha*A*B.
Definition at line 459 of file cu-matrix.h.
Referenced by kaldi::UnitTestCuMatrixAddTpMat().
{
     CuMatrix<Real> M(A);
     return AddMatMat(alpha, M, transA, B, transB, beta);
   }
void AddVecMatPointMulVec (const Real alpha, const CuMatrixBase< Real > & A, const CuMatrixBase< Real > & B, const Real beta, MatrixIndexT batch_index)
sc function element of vector multiply rows vector of matrix
Definition at line 1220 of file cu-matrix.cc.
References CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
 {
     KALDI_ASSERT(NumRows() == B.NumRows());
     KALDI_ASSERT(NumCols() == B.NumCols());
     KALDI_ASSERT(Stride() == B.Stride());
     KALDI_ASSERT(batch_index < A.NumRows());
 #if HAVE_CUDA == 1
     if (CuDevice::Instantiate().Enabled())
     {
         Timer tim;
         dim3 dimGrid, dimBlock;
         GetBlockSizesForSimpleMatrixOperation(NumRows(),NumCols(),
                                               &dimGrid, &dimBlock);
         cuda_add_vec_mat_point_mul_vec(dimGrid, dimBlock, this->data_, A.Data(),
                                        B.Data(), Dim(), A.Dim(), B.Dim(), alpha, beta, batch_index);
         CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
     }
     else
 #endif
     {
         Mat().AddVecMatPointMulVec(alpha, A.Mat(), B.Mat(), beta, batch_index);
     }
 }
void AddVecToCols (Real alpha, const CuVectorBase< Real > & col, Real beta = 1.0)
(for each column c of *this), c = alpha * col + beta * c
Definition at line 984 of file cu-matrix.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ERR, and CuVectorBase< Real >::Vec().
Referenced by KlHmm::PropagateFnc(), and kaldi::UnitTestCuMatrixAddVecToCols().
{
   if (col.Dim() != NumRows()) {
     KALDI_ERR << "Non matching dimensions: Rows:" << NumRows() << " VectorDim:" << col.Dim();
   }
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_vec_to_cols(dimGrid, dimBlock, alpha, col.data_, beta,
                          data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     if (beta != 1.0) Mat().Scale(beta);
     Mat().AddVecToCols(alpha, col.Vec());
   }
 }
void AddVecToRows (Real alpha, const CuVectorBase< Real > & row, Real beta = 1.0)
(for each row r of *this), r = alpha * row + beta * r
Definition at line 1013 of file cu-matrix.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ERR, and CuVectorBase< Real >::Vec().
Referenced by SimpleSentenceAveragingComponent::BackpropagateFnc(), DecodableAmNnetParallel::Compute(), DecodableNnet2Online::ComputeForFrame(), NnetDecodableBase::DoNnetComputation(), PerElementOffsetComponent::Propagate(), ConvolutionComponent::Propagate(), FixedAffineComponent::Propagate(), FixedBiasComponent::Propagate(), Convolutional1dComponent::Propagate(), SimpleSentenceAveragingComponent::PropagateFnc(), AffineTransform::PropagateFnc(), TCNProjectionComponent::PropagateFnc(), Rbm::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), TCNComponent::PropagateFnc(), Convolutional2DComponent::PropagateFnc(), AddShift::PropagateFnc(), Rbm::Reconstruct(), PdfPrior::SubtractOnLogpost(), kaldi::UnitTestCuMatrixAddVecToRows(), and SentenceAveragingComponent::Update().
{
   if (row.Dim() != NumCols()) {
     KALDI_ERR << "Non matching dimensions: Cols:" << NumCols() << " VectorDim:" << row.Dim();
   }
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_add_vec_to_rows(dimGrid, dimBlock, alpha, row.data_, beta, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     if (beta != 1.0) Mat().Scale(beta);
     Mat().AddVecToRows(alpha, row.Vec());
   }
 }
void AddVecVec (Real alpha, const CuVectorBase< Real > & x, const CuVectorBase< Real > & y)
A = alpha * x * y^T + A .
Definition at line 1081 of file cu-matrix.cc.
References CuVectorBase< Real >::Data(), CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, rnnlm::n, and CuVectorBase< Real >::Vec().
Referenced by kaldi::UnitTestCuMatrixAddVecVec().
{
     MatrixIndexT m = y.Dim();
     MatrixIndexT n = x.Dim();
     KALDI_ASSERT(m == NumCols());
     KALDI_ASSERT(n == NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cublas_ger(GetCublasHandle(), m, n, alpha,
                  y.Data(), 1, x.Data(), 1, data_, Stride()));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().AddVecVec(alpha, x.Vec(), y.Vec());
   }
 }
void ApplyCeiling (Real ceiling_val)
Definition at line 2086 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by ClipGradientComponent::Backprop(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), and kaldi::UnitTestCuMatrixApplyCeiling().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_ceiling(dimGrid, dimBlock, data_, ceiling_val, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().ApplyCeiling(ceiling_val);
   }
 }
void ApplyExp ()
Definition at line 2049 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by LogSoftmaxComponent::Backprop(), and kaldi::UnitTestCuMatrixApplyExp().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_exp(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().ApplyExp();
   }
 }
void ApplyFloor (Real floor_val)
Definition at line 2068 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by ClipGradientComponent::Backprop(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), DecodableAmNnetParallel::Compute(), DecodableNnet2Online::ComputeForFrame(), main(), RectifiedLinearComponent::Propagate(), SoftmaxComponent::Propagate(), LogSoftmaxComponent::Propagate(), kaldi::TestCuMatrixCompObjfAndDeriv(), kaldi::UnitTestCuMatrixApplyFloor(), kaldi::UnitTestCuMatrixObjfDeriv(), and NnetLogprobTask::~NnetLogprobTask().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_floor(dimGrid, dimBlock, data_, floor_val, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().ApplyFloor(floor_val);
   }
 }
void ApplyHeaviside ()
For each element, sets x = (x > 0 ? 1.0 : 0.0)
Definition at line 2030 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by RectifiedLinearComponent::Backprop(), DropoutComponent::Propagate(), RectifiedLinearComponent::StoreStats(), kaldi::TestCuMatrixHeaviside(), and kaldi::UnitTestCuMatrixApplyHeaviside().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_heaviside(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().ApplyHeaviside();
   }
 }
void ApplyLog ()
Definition at line 615 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by DecodableAmNnetParallel::Compute(), DecodableNnet2Online::ComputeForFrame(), Xent::Eval(), main(), kaldi::TestCuMatrixCompObjfAndDeriv(), kaldi::UnitTestCuMatrixApplyLog(), kaldi::UnitTestCuMatrixObjfDeriv(), and NnetLogprobTask::~NnetLogprobTask().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_log(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().ApplyLog();
   }
 }
void ApplyLogSoftMaxPerRow (const CuMatrixBase< Real > & src)
LogSoftmax nonlinearity Y = LogSoftmax(X) : Yij = Xij - log(sum_k(e^Xik)), done to each row for each row, the max value is first subtracted for good numerical stability.
Definition at line 1418 of file cu-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), CU1DBLOCK, CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), kaldi::SameDim(), and CuMatrixBase< Real >::Stride().
Referenced by LogSoftmaxComponent::Propagate(), kaldi::TestCuMatrixLogSoftmax(), and kaldi::UnitTestCuLogSoftmax().
{
   KALDI_ASSERT(SameDim(*this, src));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     size_t dimBlock = src.num_cols_ > CU1DBLOCK ? CU1DBLOCK : src.num_cols_;
     size_t dimGrid = src.num_rows_;
     cuda_log_softmax_reduce(dimGrid, dimBlock,
                             data_, src.data_, Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     MatrixBase<Real> &mat(this->Mat());
     mat.CopyFromMat(src.Mat());
     for(MatrixIndexT r = 0; r < mat.NumRows(); r++) {
       mat.Row(r).ApplyLogSoftMax();
     }
   }
 }
void ApplyPow (Real power)
Apply power to the absolute value of each element.
If inlude_sign is true, the result will be multiplied with the sign of the input value. If the power is negative and the input to the power is zero, The output will be set zero. If include_sign is true, it will multiply the result by the sign of the input.
Definition at line 1994 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by TanhComponent::Backprop(), TanhComponent::StoreStats(), kaldi::UnitTestCuMatrixApplyPow(), kaldi::UnitTestCuMatrixSetRandn(), and kaldi::UnitTestCuMatrixSetRandUniform().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_pow(dimGrid, dimBlock, data_, power, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().ApplyPow(power);
   }
 }
void ApplyPowAbs (Real power, bool include_sign = false)
Definition at line 2012 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by PowerComponent::Backprop(), PowerComponent::Propagate(), and kaldi::UnitTestCuMatrixApplyPowAbs().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_apply_pow_abs(dimGrid, dimBlock, data_, power, include_sign, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().ApplyPowAbs(power, include_sign);
   }
 }
void ApplySoftMaxPerRow (const CuMatrixBase< Real > & src)
Softmax nonlinearity Y = Softmax(X) : Yij = e^Xij / sum_k(e^Xik), done to each row for each row, the max value is first subtracted for good numerical stability.
Definition at line 1395 of file cu-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), CU1DBLOCK, CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), kaldi::SameDim(), and CuMatrixBase< Real >::Stride().
Referenced by SoftmaxComponent::Propagate(), Softmax::PropagateFnc(), BlockSoftmax::PropagateFnc(), kaldi::TestCuMatrixSoftmax(), and kaldi::UnitTestCuSoftmax().
{
   KALDI_ASSERT(SameDim(*this, src));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     size_t dimBlock = src.num_cols_ > CU1DBLOCK ? CU1DBLOCK : src.num_cols_;
     size_t dimGrid = src.num_rows_;
     cuda_softmax_reduce(dimGrid, dimBlock, data_, src.data_, Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     MatrixBase<Real> &mat(this->Mat());
     mat.CopyFromMat(src.Mat());
     for(MatrixIndexT r = 0; r < mat.NumRows(); r++) {
       mat.Row(r).ApplySoftMax();
     }
   }
 }
bool ApproxEqual (const CuMatrixBase< Real > & other, float tol = 0.01) const
True if ((*this)-other).FrobeniusNorm() <= tol * this->FrobeniusNorm()
Definition at line 1747 of file cu-matrix.cc.
References CuMatrixBase< Real >::AddMat(), and CuMatrixBase< Real >::FrobeniusNorm().
Referenced by kaldi::UnitTestCuCholesky(), and kaldi::UnitTestCuCopy().
{
   CuMatrix<Real> diff(*this);
   diff.AddMat(-1.0, other);
   return (diff.FrobeniusNorm() <= tol * (*this).FrobeniusNorm());
 }
void Cholesky (CuMatrixBase< Real > * inv_cholesky = NULL)
This function does sets *this to the Cholesky factor of *this (i.e.
the C satisfying *this = C C^T), and sets "inv_cholesky" (if supplied) to its inverse. *this is treated as a symmetric matrix but only the lower triangle is accessed.
Definition at line 1598 of file cu-matrix.cc.
References TpMatrix< Real >::Cholesky(), CuMatrixBase< Real >::Cholesky(), CuSpMatrix< Real >::CopyFromMat(), CuTpMatrix< Real >::CopyFromTp(), CuMatrixBase< Real >::CopyFromTp(), TpMatrix< Real >::Invert(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTakeLower, kaldi::kTrans, kaldi::kUndefined, and CuMatrixBase< Real >::SymAddMat2().
Referenced by CuTpMatrix< Real >::Cholesky(), CuMatrixBase< Real >::Cholesky(), kaldi::TestCuMatrixCholesky(), kaldi::UnitTestCholesky(), and kaldi::UnitTestCuCholesky().
{
   KALDI_ASSERT(this->NumRows() == this->NumCols());
   const int32 block_size = 64;  // We can tune this.
 #if HAVE_CUDA == 1
   bool have_gpu = CuDevice::Instantiate().Enabled();
 #else
   bool have_gpu = false;
 #endif
   if (this->NumRows() == 0) {
     return;
   }
   if (inv_cholesky == NULL && this->NumRows() >= block_size * 2 && have_gpu) {
     // Even if the user did not request the inverse Cholesky, for large enough
     // matrices (on GPUs) it's going to be more efficient to compute it anyway
     // as the recursion depends on it.
     CuMatrix<Real> inv(this->NumRows(), this->NumCols());
     Cholesky(&inv);
     return;
   }
   if (this->NumRows() <= block_size || inv_cholesky == NULL || !have_gpu) {
     // Don't recurse: compute the Cholesky (and inverse Cholesky, if requested)
     // directly, on the CPu.
     int32 dim = this->NumRows();
     CuSpMatrix<Real> this_sp(dim, kUndefined);
     this_sp.CopyFromMat(*this, kTakeLower);
     SpMatrix<Real> this_sp_cpu(this_sp);
     TpMatrix<Real> C_cpu(dim);
     C_cpu.Cholesky(this_sp_cpu);
     CuTpMatrix<Real> C(C_cpu);
     this->CopyFromTp(C);
     if (inv_cholesky != NULL) {
       C_cpu.Invert();  // Get inverse Cholesky on CPU.
       C.CopyFromTp(C_cpu);
       inv_cholesky->CopyFromTp(C); // Copy inverse Cholesky from CPU.
     }
     return;
   }
   // At this point, if none of the other cases apply, we recurse.
   // The selection of dim1 is a heuristic.  We could also just take half.
   int32 tot_dim = this->NumRows();
   int32 dim1;
   // Break it up into a whole number of blocks, for better memory alignment.
   // The line below, setting dim1 can be decided on a heuristic basis: from
   // the point of view of correctness, it can really be any value
   // 0 < dim1 < tot_dim.
   dim1 = block_size * std::max<int32>(1, tot_dim / (2 * block_size));
   int32 dim2 = tot_dim - dim1;
   CuSubMatrix<Real> this_11(*this, 0, dim1, 0, dim1),
       this_12(*this, 0, dim1, dim1, dim2),
       this_21(*this, dim1, dim2, 0, dim1),
       this_22(*this, dim1, dim2, dim1, dim2);
   CuSubMatrix<Real> inv_11(*inv_cholesky, 0, dim1, 0, dim1),
       inv_12(*inv_cholesky, 0, dim1, dim1, dim2),
       inv_21(*inv_cholesky, dim1, dim2, 0, dim1),
       inv_22(*inv_cholesky, dim1, dim2, dim1, dim2);
   /*
     Here is the math on block-wise Cholesky.  We'll use a Matlab-like notation for blocks of a matrix,
     e.g. [ A B; C D ], and also for transposes, e.g. A' is the transpose of A.
     Let A be the input matrix; we want to compute both its Cholesky L and its inverse Cholesky, which
     we'll call M.
     OK. let  L = [ L11 0; L21 L22 ] be the Cholesky factor of A.
     We have A = L L' = [ L11 0; L21 L22 ] * [ L11' L21'; 0 L22' ].  Multiplying it out,
     if A = [ A11 A12; A21 A22 ]; then
     A11 = L11 L11',  A21 = L21 L11', A22 = L21 L21' + L22 L22', and A12 = A21'.
     We also want an expression for the inverse of L (we call this M).
     If M = [ M11 0; M21 M22 ], then it's not hard to see that
     M11 = inv(L11), M22 = inv(L22).
     We can work out M21 as follows.  We know that [ L11 0; L21 L22 ] [ M11 0; M21 M22 ] = [ I 0; 0 I ].
     Considering the zero on the bottom of the rhs, we have: L21 M11 + L22 M21 = 0, which gives us:
     M21 = - L22^{-1} L21 M11 = - M22 L21 M11.
     Next, we want expressions for L21 and L22.  From the equation A21 = L21 L11', we have:
     L21 = A21 inv(L11') = A21 M11'
     We can compute L22 and M22 recursively by doing Cholesky (and computing the inverse Cholesky)
     on the quantity T = (A22 - L21 L21').   [we give it the name T just for easy reference.]
     Computationally, we do this as follows:
     (1) Recurse to get L11 and M11.
     (2) Compute L21 = A21 M11'
     (3) Compute T = A22 - L21 L21'
     (4) Recurse on T to get L22 and M22.
     (5) Compute M21 = -M22 L21 M11.
     Next, we have to consider the in-place nature of the computation, since L overwrites A
     [M has its own storage, in "inv_cholesky"].
     We address this here:
     (1) is in-place [L11 replaces A11, M11 has its own storage].
     (2) L21 gets written where M21 belongs.
     (3) T replaces A22.
     (4) is in-place [L22 replaces T where A22 was, M22 has its own storage]
     (5):(a)  we first compute the transpose of (L21 M11) is done in the upper part of A/L,
     where A12 or L12 would be.  Define a temporary expression
     U = (L21 M11)' = M11' L21'; this goes where A12 or L12 would be.
     (b) copy L21 to where it should be, in *this.
     (c) Compute M21 = -M22 U', in the correct place for M21.
     (d) zero L12 and M12.  */
   // (1) compute L11 and M11.
   this_11.Cholesky(&inv_11);
   // (2) compute L21 = A21 M11'.  For now it's in the "wrong place", where M21 should be.
   inv_21.AddMatMat(1.0, this_21, kNoTrans, inv_11, kTrans, 0.0);
   // (3) compute T = A22 - L21 L21'.  Note: only the lower triangle of T will be valid, but
   //      that's OK because Cholesky will ignore the upper part.
   this_22.SymAddMat2(-1.0, inv_21, kNoTrans, 1.0);
   // (4) Recurse to compute L22 and M22.
   this_22.Cholesky(&inv_22);
   // (5)(a) compute U = M11' L21'.  We use the storage of this_12 for this.  Note that L21 is
   //        currently where M21 should be.
   this_12.AddMatMat(1.0, inv_11, kTrans, inv_21, kTrans, 0.0);
   // (5)(b) copy L21 to where it should be.
   this_21.CopyFromMat(inv_21);
   // (5)(c) compute M21 = -M22 U'.
   inv_21.AddMatMat(-1.0, inv_22, kNoTrans, this_12, kTrans, 0.0);
   // (5)(d) zero L12 and M12.
   this_12.SetZero();
   inv_12.SetZero();
 }
CuSubMatrix<Real> ColRange (const MatrixIndexT col_offset, const MatrixIndexT num_cols) const inline
Definition at line 492 of file cu-matrix.h.
Referenced by RepeatedAffineComponent::Backprop(), MaxpoolingComponent::Backprop(), BlockAffineComponent::Backprop(), ConvolutionComponent::Backprop(), Convolutional1dComponent::Backprop(), MaxPoolingComponent::BackpropagateFnc(), AveragePoolingComponent::BackpropagateFnc(), BlockSoftmax::BackpropagateFnc(), MaxPooling2DComponent::BackpropagateFnc(), AveragePooling2DComponent::BackpropagateFnc(), SentenceAveragingComponent::BackpropagateFnc(), ParallelComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), ConvolutionalComponent::BackpropagateFnc(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), MultiTaskLoss::Eval(), LstmProjectedStreams::InfoGradient(), BLstmProjectedStreams::InfoGradient(), RepeatedAffineComponent::Propagate(), MaxpoolingComponent::Propagate(), BlockAffineComponent::Propagate(), ConvolutionComponent::Propagate(), Convolutional1dComponent::Propagate(), AveragePoolingComponent::PropagateFnc(), MaxPoolingComponent::PropagateFnc(), BlockSoftmax::PropagateFnc(), MaxPooling2DComponent::PropagateFnc(), AveragePooling2DComponent::PropagateFnc(), SentenceAveragingComponent::PropagateFnc(), ParallelComponent::PropagateFnc(), FramePoolingComponent::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), Convolutional2DComponent::PropagateFnc(), LstmProjectedStreams::PropagateFnc(), BLstmProjectedStreams::PropagateFnc(), SentenceAveragingComponent::Update(), FramePoolingComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), ConvolutionComponent::Update(), and Convolutional1dComponent::Update().
{
     return CuSubMatrix<Real>(*this, 0, num_rows_, col_offset, num_cols);
   }
void CopyColFromVec (const CuVectorBase< Real > & v, const MatrixIndexT col)
Copy vector into specific column of matrix.
Definition at line 1973 of file cu-matrix.cc.
References CuVectorBase< Real >::Data(), CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by NaturalGradientRepeatedAffineComponent::Update().
{
   KALDI_ASSERT(v.Dim() == num_rows_ &&
                static_cast<UnsignedMatrixIndexT>(col) <
                static_cast<UnsignedMatrixIndexT>(num_cols_));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     cublas_copy(GetCublasHandle(),
                 v.Dim(), v.Data(), 1,
                 this->data_ + col, this->stride_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyColFromVec(v.Vec(), col);
   }
 }
void CopyCols (const CuMatrixBase< Real > & src, const CuArray< MatrixIndexT > & indexes)
Copies column r from column indexes[r] of src.
As a special case, if indexes[i] == -1, sets column i to zero indexes.size() must equal this->NumCols(), all elements of "reorder" must be in [-1, src.NumCols()-1], and src.NumRows() must equal this.NumRows()
Definition at line 2137 of file cu-matrix.cc.
References CuArray< T >::Data(), CuMatrixBase< Real >::Data(), CuArray< T >::Dim(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by SumGroupComponent::Backprop(), PermuteComponent::Backprop(), ConvolutionComponent::InputToInputPatches(), PermuteComponent::Propagate(), Convolutional1dComponent::Propagate(), ConvolutionalComponent::PropagateFnc(), and Convolutional1dComponent::Update().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(indices.Dim() == NumCols());
     KALDI_ASSERT(NumRows() == src.NumRows());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_copy_cols(dimGrid, dimBlock, data_, src.Data(), indices.Data(), Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyCols(src.Mat(), indices.Data());
   }
 }
void CopyFromBlock (const CuBlockMatrix< Real > & B, MatrixTransposeType trans = kNoTrans)
Definition at line 151 of file cu-matrix.cc.
References CuBlockMatrix< Real >::Block(), CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuBlockMatrix< Real >::NumBlocks(), CuBlockMatrix< Real >::NumCols(), CuMatrixBase< Real >::NumCols(), CuBlockMatrix< Real >::NumRows(), CuMatrixBase< Real >::NumRows(), and kaldi::nnet3::SetZero().
Referenced by CuMatrix< Real >::CuMatrix().
{
   this->SetZero();
   if (trans == kNoTrans) {
     KALDI_ASSERT(NumRows() == B.NumRows() && NumCols() == B.NumCols());
     int32 row_offset = 0, col_offset = 0;
     for (int32 b = 0; b < B.NumBlocks(); b++) {
       const CuMatrixBase<Real> &block = B.Block(b);
       int32 num_rows = block.NumRows(), num_cols = block.NumCols();
       CuSubMatrix<Real> this_block(*this, row_offset, num_rows,
                                    col_offset, num_cols);
       this_block.CopyFromMat(block);
       row_offset += num_rows;
       col_offset += num_cols;
     }
     KALDI_ASSERT(row_offset == NumRows() && col_offset == NumCols());
   } else {
     KALDI_ASSERT(NumRows() == B.NumCols() && NumCols() == B.NumRows());
     int32 row_offset = 0, col_offset = 0;
     for (int32 b = 0; b < B.NumBlocks(); b++) {
       const CuMatrixBase<Real> &block = B.Block(b);
       int32 num_rows = block.NumCols(), num_cols = block.NumRows();
       CuSubMatrix<Real> this_block(*this, row_offset, num_rows,
                                    col_offset, num_cols);
       this_block.CopyFromMat(block, kTrans);
       row_offset += num_rows;
       col_offset += num_cols;
     }
     KALDI_ASSERT(row_offset == NumRows() && col_offset == NumCols());
   }
 }
void CopyFromGeneralMat (const GeneralMatrix & src, MatrixTransposeType trans = kNoTrans)
Definition at line 2495 of file cu-matrix.cc.
References CuSparseMatrix< Real >::CopyToMat(), SparseMatrix< Real >::CopyToMat(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kSparseMatrix, and GeneralMatrix::Type().
Referenced by NnetComputer::AcceptInputs(), and kaldi::nnet3::ComputeObjectiveFunction().
{
   switch (src.Type()) {
     case kFullMatrix: {
       const Matrix<BaseFloat> &src_full_mat = src.GetFullMatrix();
       this->CopyFromMat(src_full_mat, trans);
       return;
     }
     case kCompressedMatrix: {
       Matrix<BaseFloat> mat;
       src.GetMatrix(&mat);
       this->CopyFromMat(mat, trans);
       return;
     }
     case kSparseMatrix: {
       const SparseMatrix<BaseFloat> &smat = src.GetSparseMatrix();
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         // only take this branch if we're actually using CUDA, or it would
         // entail a wasteful copy of the sparse matrix.
         CuSparseMatrix<BaseFloat> cu_smat(smat);
         cu_smat.CopyToMat(this, trans);
         return;
       }
 #endif
       smat.CopyToMat(&(Mat()), trans);
       return;
     }
     default:
       KALDI_ERR << "Invalid GeneralMatrix type.";
   }
 }
void CopyFromMat (const MatrixBase< OtherReal > & src, MatrixTransposeType trans = kNoTrans)
Definition at line 322 of file cu-matrix.cc.
Referenced by ElementwiseProductComponent::Backprop(), SumReduceComponent::Backprop(), TanhComponent::Backprop(), PowerComponent::Backprop(), RectifiedLinearComponent::Backprop(), ScaleComponent::Backprop(), SoftmaxComponent::Backprop(), LogSoftmaxComponent::Backprop(), FixedScaleComponent::Backprop(), FixedBiasComponent::Backprop(), NoOpComponent::Backprop(), ClipGradientComponent::Backprop(), PerElementScaleComponent::Backprop(), PerElementOffsetComponent::Backprop(), Softmax::BackpropagateFnc(), BlockSoftmax::BackpropagateFnc(), SentenceAveragingComponent::BackpropagateFnc(), ParallelComponent::BackpropagateFnc(), Dropout::BackpropagateFnc(), TCNComponent::BackpropagateFnc(), LengthNormComponent::BackpropagateFnc(), AddShift::BackpropagateFnc(), Rescale::BackpropagateFnc(), NnetOnlineComputer::Compute(), CuMatrixBase< Real >::CopyFromBlock(), CuBlockMatrix< Real >::CopyFromMat(), GeneralMatrix::CopyToMat(), CuMatrix< Real >::CuMatrix(), NnetComputer::ExecuteCommand(), Nnet::Feedforward(), NnetRescaler::FormatInput(), OnlineNaturalGradient::Init(), OnlinePreconditioner::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), main(), kaldi::nnet2::NnetComputation(), CuMatrix< BaseFloat >::operator=(), kaldi::nnet2::PreconditionDirections(), OnlinePreconditionerSimple::PreconditionDirections(), OnlineNaturalGradientSimple::PreconditionDirections(), kaldi::nnet2::PreconditionDirectionsAlphaRescaled(), ElementwiseProductComponent::Propagate(), SumReduceComponent::Propagate(), NormalizeComponent::Propagate(), PowerComponent::Propagate(), RectifiedLinearComponent::Propagate(), ScaleComponent::Propagate(), NoOpComponent::Propagate(), ClipGradientComponent::Propagate(), PerElementScaleComponent::Propagate(), PerElementOffsetComponent::Propagate(), SpliceMaxComponent::Propagate(), FixedScaleComponent::Propagate(), FixedBiasComponent::Propagate(), AdditiveNoiseComponent::Propagate(), KlHmm::PropagateFnc(), ParallelComponent::PropagateFnc(), TCNComponent::PropagateFnc(), Dropout::PropagateFnc(), LstmProjectedStreams::PropagateFnc(), LengthNormComponent::PropagateFnc(), AddShift::PropagateFnc(), BLstmProjectedStreams::PropagateFnc(), Rescale::PropagateFnc(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), LinearTransform::SetLinearity(), AffineTransform::SetLinearity(), kaldi::TestCuFindRowMaxId(), kaldi::TestSymInvertPosDef(), kaldi::UnitInvert(), kaldi::UnitTestCheck(), kaldi::UnitTestCholesky(), kaldi::UnitTestConstructor(), kaldi::UnitTestCopyFromMat(), kaldi::UnitTestCopySp(), kaldi::UnitTestCuCopy(), kaldi::UnitTestCuDiffSigmoid(), kaldi::UnitTestCuDiffTanh(), kaldi::UnitTestCuDiffXent(), kaldi::UnitTestCuFindRowMaxId(), kaldi::UnitTestCuLogSoftmax(), kaldi::UnitTestCuMatrixAddMat(), kaldi::UnitTestCuMatrixAddMatBlocks(), kaldi::UnitTestCuMatrixAddMatDiagVec(), kaldi::UnitTestCuMatrixAddMatMat(), kaldi::UnitTestCuMatrixAddMatMatBatched(), kaldi::UnitTestCuMatrixAddMatMatElements(), kaldi::UnitTestCuMatrixAddVecToCols(), kaldi::UnitTestCuMatrixAddVecToRows(), kaldi::UnitTestCuMatrixCopyCross(), kaldi::UnitTestCuMatrixCopyCross2(), kaldi::UnitTestCuMatrixCopyFromMat(), kaldi::UnitTestCuMatrixDivElements(), kaldi::UnitTestCuMatrixDivRowsVec(), kaldi::UnitTestCuMatrixGroupMaxDeriv(), kaldi::UnitTestCuMatrixGroupPnormDeriv(), kaldi::UnitTestCuMatrixInvertElements(), kaldi::UnitTestCuMatrixMax(), kaldi::UnitTestCuMatrixMulColsVec(), kaldi::UnitTestCuMatrixMulElements(), kaldi::UnitTestCuMatrixMulRowsGroupMat(), kaldi::UnitTestCuMatrixMulRowsVec(), kaldi::UnitTestCuSigmoid(), kaldi::UnitTestCuSoftmax(), kaldi::UnitTestCuTanh(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), kaldi::UnitTestInvert(), kaldi::UnitTestSwapCu2Cu(), kaldi::UnitTestSwapCu2M(), BlockAffineComponentPreconditioned::Update(), and MatrixRandomizer::Value().
{
   CuMatrix<OtherReal> temp(src);
   this->CopyFromMat(temp, trans);
 }
void CopyFromMat (const MatrixBase< Real > & src, MatrixTransposeType trans = kNoTrans)
Definition at line 294 of file cu-matrix.cc.
References MatrixBase< Real >::Data(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (trans == kNoTrans) {
       KALDI_ASSERT(src.NumRows() == num_rows_ && src.NumCols() == num_cols_);
       Timer tim;
       MatrixIndexT dst_pitch = stride_*sizeof(Real);
       MatrixIndexT src_pitch = src.Stride()*sizeof(Real);
       MatrixIndexT width = src.NumCols()*sizeof(Real);
       CU_SAFE_CALL(cudaMemcpy2D(data_, dst_pitch, src.Data(), src_pitch,
                                 width, src.NumRows(), cudaMemcpyHostToDevice));
       CuDevice::Instantiate().AccuProfile("CuMatrixBase::CopyFromMat(from CPU)",tim.Elapsed());
     } else {
       CuMatrix<Real> trans_mat(src); // Do the transpose on the GPU board.
       this->CopyFromMat(trans_mat, kTrans);
     }
   } else
 #endif
   {
     Mat().CopyFromMat(src, trans);
   }
 }
void CopyFromMat (const CuMatrixBase< OtherReal > & M, MatrixTransposeType trans = kNoTrans)
Definition at line 198 of file cu-matrix.cc.
References CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::data_, CuMatrixBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::num_rows_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
{
   if (sizeof(Real) == sizeof(OtherReal) &&
       static_cast<const void*>(M.Data()) ==
       static_cast<const void*>(this->Data())) {
     if (M.Data() == NULL)
       return;
     // CopyFromMat called on same data.  Nothing to do (except sanity checks)
     KALDI_ASSERT(trans == kNoTrans && M.NumRows() == NumRows() &&
                  M.NumCols() == NumCols() && M.Stride() == Stride());
     return;
   }
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (trans == kNoTrans) {
       KALDI_ASSERT(M.NumRows() == num_rows_ && M.NumCols() == num_cols_);
     } else {
       KALDI_ASSERT(M.NumCols() == num_rows_ && M.NumRows() == num_cols_);
     }
     if (M.num_rows_ == 0) return; // Nothing to do.
     Timer tim;
     if (sizeof(Real) == sizeof(OtherReal) && trans == kNoTrans ) {
       MatrixIndexT dst_pitch = stride_ * sizeof(Real);
       MatrixIndexT src_pitch = M.Stride() * sizeof(Real);
       MatrixIndexT width = M.NumCols() * sizeof(Real);
       CU_SAFE_CALL(cudaMemcpy2D(data_, dst_pitch, M.data_, src_pitch,
                                 width, M.num_rows_, cudaMemcpyDeviceToDevice));
     } else {
       dim3 dimGrid, dimBlock;
       GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                             &dimGrid, &dimBlock);
       if (trans == kNoTrans) {
         cuda_copy_from_mat(dimGrid, dimBlock, data_, M.data_, Dim(), M.Dim());
       } else {
         cuda_copy_from_mat_trans(dimGrid, dimBlock, data_, M.data_, Dim(), M.Dim());
       }
     }
     CuDevice::Instantiate().AccuProfile("CuMatrixBase::CopyFromMat(from other CuMatrixBase)", tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyFromMat(M.Mat(), trans);
   }
 }
void CopyFromSp (const CuSpMatrix< Real > & M)
Definition at line 338 of file cu-matrix.cc.
References CU2DBLOCK, CuPackedMatrix< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuSpMatrix< Real >::Mat(), and CuPackedMatrix< Real >::NumRows().
Referenced by CuMatrix< BaseFloat >::CuMatrix(), CuSpMatrix< Real >::Invert(), and kaldi::TestCuMatrixCopyFromSp().
{
   KALDI_ASSERT(num_rows_ == M.NumRows() && num_cols_ == num_rows_);
   if (num_rows_ == 0)
     return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(NumRows(), CU2DBLOCK),
                  n_blocks(NumRows(), CU2DBLOCK));
     cuda_copy_from_sp(dimGrid, dimBlock, M.Data(), data_, Dim());
     CuDevice::Instantiate().AccuProfile("CuMatrix::CopyFromSp",tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyFromSp(M.Mat());
   }
 }
template void CopyFromTp (const CuTpMatrix< OtherReal > & M, MatrixTransposeType trans = kNoTrans)
Definition at line 260 of file cu-matrix.cc.
References CU2DBLOCK, CuPackedMatrix< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, CuTpMatrix< Real >::Mat(), and CuPackedMatrix< Real >::NumRows().
Referenced by CuMatrixBase< Real >::Cholesky(), CuMatrix< BaseFloat >::CuMatrix(), CuTpMatrix< Real >::Invert(), kaldi::TestCuMatrixCopyFromTp(), and kaldi::UnitTestCuMatrixCopyFromTp().
{
   KALDI_ASSERT(num_rows_ == M.NumRows() && num_cols_ == num_rows_);
   if (num_rows_ == 0)
     return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(num_rows_, CU2DBLOCK),
                  n_blocks(num_rows_, CU2DBLOCK));
     if (trans == kNoTrans) {
       cuda_copy_from_tp(dimGrid, dimBlock, data_, M.Data(), Dim());
     } else {
       cuda_copy_from_tp_trans(dimGrid, dimBlock, data_, M.Data(), Dim());
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyFromTp(M.Mat(), trans);
   }
 }
void CopyLowerToUpper ()
Definition at line 2391 of file cu-matrix.cc.
References CU2DBLOCK, Timer::Elapsed(), and KALDI_ASSERT.
Referenced by kaldi::nnet2::PreconditionDirections(), kaldi::TestCuMatrixCopyLowerToUpper(), kaldi::UnitTestCuCholesky(), and kaldi::UnitTestCuMatrixCopyLowerToUpper().
{
   KALDI_ASSERT(num_cols_ == num_rows_);
   if (num_rows_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     int32 dim = num_rows_;
     dim3 dimGrid(n_blocks(dim, CU2DBLOCK),
                  n_blocks(dim, CU2DBLOCK));
     cuda_copy_low_upp(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyLowerToUpper();
   }
 }
void CopyRows (const CuMatrixBase< Real > & src, const CuArray< MatrixIndexT > & indexes)
Copies row r from row indexes[r] of src.
As a special case, if indexes[i] < 0, sets row i to zero "reorder".size() must equal this->NumRows(), and src.NumCols() must equal this.NumCols()
Definition at line 2159 of file cu-matrix.cc.
References CuArray< T >::Data(), CuMatrixBase< Real >::Data(), CuArray< T >::Dim(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::Stride().
Referenced by SpliceComponent::Backprop(), NnetComputer::ExecuteCommand(), DistributeComponent::Propagate(), and SpliceMaxComponent::Propagate().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(static_cast<MatrixIndexT>(indices.Dim()) == NumRows());
     KALDI_ASSERT(NumCols() == src.NumCols());
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_copy_rows(dimGrid, dimBlock, data_, src.Data(), indices.Data(),
                    Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyRows(src.Mat(), indices.Data());
   }
 }
void CopyRows (const CuArray< const Real * > & src)
Copies row r of this matrix from an array of floats at the location given by src[r], where src[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (the point is: the data it points to should be on the GPU if we're using a GPU, and on a CPU otherwise).
src.size() must equal this.NumRows(), and if any src[r] is NULL then this.Row(r) will be set to zero.
Definition at line 2204 of file cu-matrix.cc.
References CU2DBLOCK, CuArray< T >::Data(), CuArray< T >::Dim(), and KALDI_ASSERT.
{
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(static_cast<MatrixIndexT>(src.Dim()) == NumRows());
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(num_cols_, CU2DBLOCK),
                  n_blocks(num_rows_, CU2DBLOCK));
     cuda_copy_rows(dimGrid, dimBlock, data_, src.Data(), Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyRows(src.Data());
   }
 }
void CopyRowsFromVec (const CuVectorBase< Real > & v)
This function has two modes of operation.
If v.Dim() == NumRows() * NumCols(), then treats the vector as a row-by-row concatenation of a matrix and copies to *this. if v.Dim() == NumCols(), it sets each row of *this to a copy of v.
Definition at line 1905 of file cu-matrix.cc.
References CuVectorBase< Real >::Data(), CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ERR, and CuVectorBase< Real >::Vec().
Referenced by kaldi::CuVectorUnitTestCopyFromMat(), NnetOnlineComputer::Flush(), NnetRescaler::FormatInput(), RepeatedAffineComponent::Propagate(), FixedAffineComponent::Propagate(), AffineComponent::Propagate(), BlockAffineComponent::Propagate(), kaldi::UnitTestCuMatrixCopyRowsFromVec(), RepeatedAffineComponent::UnVectorize(), AffineComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), Convolutional1dComponent::UnVectorize(), and TCNComponent::Update().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     if (v.Dim() == num_rows_*num_cols_) {
       if (stride_ == num_cols_) {
         const Real* v_data = v.Data();
         CU_SAFE_CALL(cudaMemcpy(data_, v_data,
                                 sizeof(Real)*num_rows_*num_cols_,
                                 cudaMemcpyDeviceToDevice));
       } else {
         CU_SAFE_CALL(cudaMemcpy2D(data_, stride_ * sizeof(Real), v.Data(),
                                   num_cols_*sizeof(Real), num_cols_*sizeof(Real),
                                   num_rows_,
                                   cudaMemcpyDeviceToDevice));
       }
     } else if (v.Dim() == num_cols_) {
       dim3 dimGrid, dimBlock;
       GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                             &dimGrid, &dimBlock);
       cuda_copy_rows_from_vec(dimGrid, dimBlock, data_, this->Dim(), v.Data());
     } else {
       KALDI_ERR << "Wrong sized arguments";
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyRowsFromVec(v.Vec());
   }
 }
void CopyRowsFromVec (const VectorBase< Real > & v)
Version of CopyRowsFromVec() that takes a CPU-based vector.
Definition at line 1938 of file cu-matrix.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), Timer::Elapsed(), and KALDI_ERR.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     if (v.Dim() == num_rows_*num_cols_) {
       if (stride_ == num_cols_) {
         const Real* v_data = v.Data();
         cudaMemcpy(data_, v_data, sizeof(Real)*num_rows_*num_cols_, cudaMemcpyHostToDevice);
       } else {
         const Real *v_data = v.Data();
         for (MatrixIndexT r = 0; r < num_rows_; r++) {
           Real *row_data = RowData(r);
           cudaMemcpy(row_data, v_data, sizeof(Real)*num_cols_, cudaMemcpyHostToDevice);
           v_data += num_cols_;
         }
       }
     } else if (v.Dim() == num_cols_) {
       dim3 dimGrid, dimBlock;
       GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                             &dimGrid, &dimBlock);
       cuda_copy_rows_from_vec(dimGrid, dimBlock, this->data_, this->Dim(), v.Data());
       CU_SAFE_CALL(cudaGetLastError());
     } else {
       KALDI_ERR << "Wrong sized arguments";
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyRowsFromVec(v);
   }
 }
template void CopyToMat (MatrixBase< OtherReal > * dst, MatrixTransposeType trans = kNoTrans) const
Definition at line 398 of file cu-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyToMat(), MatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by NnetComputerFromEg::Compute(), CuMatrixBase< Real >::CopyToMat(), Nnet::GetGradient(), main(), kaldi::nnet1::MomentStatistics(), KlHmm::PropagateFnc(), kaldi::UnitInvert(), kaldi::UnitTestCholesky(), kaldi::UnitTestCuDiffSigmoid(), kaldi::UnitTestCuDiffTanh(), kaldi::UnitTestCuDiffXent(), kaldi::UnitTestCuMatrixAddMat(), kaldi::UnitTestCuMatrixAddMatBlocks(), kaldi::UnitTestCuMatrixAddMatMat(), kaldi::UnitTestCuMatrixAddVecToCols(), kaldi::UnitTestCuMatrixAddVecToRows(), kaldi::UnitTestCuMatrixAddVecVec(), kaldi::UnitTestCuMatrixDivElements(), kaldi::UnitTestCuMatrixDivRowsVec(), kaldi::UnitTestCuMatrixGroupMaxDeriv(), kaldi::UnitTestCuMatrixGroupPnormDeriv(), kaldi::UnitTestCuMatrixInvertElements(), kaldi::UnitTestCuMatrixMax(), kaldi::UnitTestCuMatrixMulColsVec(), kaldi::UnitTestCuMatrixMulElements(), kaldi::UnitTestCuMatrixMulRowsGroupMat(), kaldi::UnitTestCuMatrixMulRowsVec(), kaldi::UnitTestCuSigmoid(), kaldi::UnitTestCuTanh(), kaldi::UnitTestInvert(), kaldi::UnitTestMatrix(), UnitTestMatrixRandomizer(), kaldi::UnitTestSetZeroAboveDiag(), kaldi::UnitTestSwapCu2Cu(), and kaldi::UnitTestSwapCu2M().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (trans == kTrans || sizeof(OtherReal) != sizeof(Real)) {
       CuMatrix<OtherReal> this_trans(*this, trans);
       this_trans.CopyToMat(dst, kNoTrans);
     } else {
       KALDI_ASSERT(dst->NumRows() == NumRows() && dst->NumCols() == NumCols());
       if (num_rows_ == 0) return;
       Timer tim;
       MatrixIndexT src_pitch = stride_*sizeof(Real);
       MatrixIndexT dst_pitch = dst->Stride()*sizeof(Real);
       MatrixIndexT width = NumCols()*sizeof(Real);
       CU_SAFE_CALL(cudaMemcpy2D(dst->Data(), dst_pitch, this->data_, src_pitch,
                                 width, this->num_rows_, cudaMemcpyDeviceToHost));
       CuDevice::Instantiate().AccuProfile("CuMatrix::CopyToMatD2H",tim.Elapsed());
     }
   } else
   #endif
   {
     dst->CopyFromMat(Mat(), trans);
   }
 }
void CopyToRows (const CuArray< Real * > & dst) const
For each row r of this matrix, copies it to the array of floats at the location given by dst[r], where dst[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (i.e.
it should point to memory on the GPU if we're using a GPU, or on the CPU otherwise). If dst[r] is NULL, does not copy anywhere. Requires that none of the memory regions pointed to by the pointers in "dst" overlap (e.g. none of the pointers should be the same).
Definition at line 2225 of file cu-matrix.cc.
References CU2DBLOCK, CuArray< T >::Data(), CuArray< T >::Dim(), and KALDI_ASSERT.
Referenced by DistributeComponent::Backprop(), NnetComputer::ExecuteCommand(), and kaldi::UnitTestCuMatrixCopyToRows().
{
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(static_cast<MatrixIndexT>(dst.Dim()) == NumRows());
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(num_cols_, CU2DBLOCK),
                  n_blocks(num_rows_, CU2DBLOCK));
     cuda_copy_to_rows(dimGrid, dimBlock, dst.Data(), data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyToRows(dst.Data());
   }
 }
void CopyUpperToLower ()
Definition at line 2412 of file cu-matrix.cc.
References CU2DBLOCK, Timer::Elapsed(), and KALDI_ASSERT.
Referenced by kaldi::TestCuMatrixCopyUpperToLower(), and kaldi::UnitTestCuMatrixCopyUpperToLower().
{
   KALDI_ASSERT(num_cols_ == num_rows_);
   if (num_rows_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int32 dim = this->num_rows_;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(dim, CU2DBLOCK),
                  n_blocks(dim, CU2DBLOCK));
     cuda_copy_upp_low(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().CopyUpperToLower();
   }
 }
const Real* Data () const inline
Return data pointer (const).
Warning: may return a pointer to GPU memory. Use at your own risk.
Definition at line 573 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::AddCols(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), CuSpMatrix< Real >::AddMat2(), CuMatrixBase< Real >::AddMatBlock(), CuMatrixBase< Real >::AddMatDiagVec(), CuBlockMatrix< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMatElements(), CuVectorBase< Real >::AddMatVec(), CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::AddRows(), CuMatrixBase< Real >::AddVecMatPointMulVec(), NormalizeComponent::Backprop(), CuMatrix< Real >::CompObjfAndDeriv(), DistributeComponent::ComputeInputPointers(), kaldi::cu::Copy(), CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyCols(), CuVectorBase< Real >::CopyDiagFromMat(), CuTpMatrix< Real >::CopyFromMat(), CuSpMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyRows(), CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), CuSparseMatrix< Real >::CopyToMat(), CuMatrixBase< Real >::EqualElementMask(), NnetComputer::GetPointers(), CuMatrixBase< Real >::GroupMaxDeriv(), CuMatrixBase< Real >::GroupPnormDeriv(), CuTpMatrix< Real >::Invert(), kaldi::cu::Randomize(), kaldi::cu::RegularizeL1(), CuBlockMatrix< Real >::SetCudaData(), kaldi::cu::Splice(), CuMatrixBase< Real >::SumColumnRanges(), CuMatrixBase< Real >::SymAddMat2(), kaldi::TraceMatMat(), kaldi::TraceMatSmat(), and RepeatedAffineComponent::Update().
 { return data_; }
Real* Data () inline
Return data pointer.
Warning: may return a pointer to GPU memory. Use at your own risk.
Definition at line 576 of file cu-matrix.h.
 { return data_; }
void DiffSigmoid (const CuMatrixBase< Real > & value, const CuMatrixBase< Real > & diff)
Differentiate backward through the sigmoid function.
Here, "value" is the sigmoid output. Does, element-by-element, *this = diff * value * (1 - value).
Definition at line 1443 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), kaldi::SameDim(), and CuMatrixBase< Real >::Stride().
Referenced by SigmoidComponent::Backprop(), Sigmoid::BackpropagateFnc(), and kaldi::UnitTestCuDiffSigmoid().
{
   KALDI_ASSERT(SameDim(*this, value) && SameDim(*this, diff));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_diff_sigmoid(dimGrid, dimBlock, data_, diff.data_, value.data_, Dim(), diff.Stride(), value.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().DiffSigmoid(value.Mat(), diff.Mat());
   }
 }
void DiffTanh (const CuMatrixBase< Real > & value, const CuMatrixBase< Real > & diff)
Differentiate backward through the tanh function.
Here, "value" is the tanh output. Does, element-by-element, *this = diff * (1 - value^2).
Definition at line 1488 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), CuMatrixBase< Real >::Mat(), and CuMatrixBase< Real >::Stride().
Referenced by TanhComponent::Backprop(), Tanh::BackpropagateFnc(), and kaldi::UnitTestCuDiffTanh().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_diff_tanh(dimGrid, dimBlock, data_, diff.data_, value.data_, Dim(), diff.Stride(), value.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().DiffTanh(value.Mat(), diff.Mat());
   }
 }
void DiffXent (const CuArray< int32 > & tgt, CuVector< Real > * log_post_tgt)
Differentiate the block [softmax+cross-entropy] : dE/da = posterior_mat - target_mat, 'E' is error function, 'a' is activation on softmax input.
Interface: tgt ... index vector, encodes the matrix of targets net_out_or_diff ... before invocation net output, after diff dE/da log_post_tgt ... per-frame statistics for cross-entropy computations : log(sum_row(posterior_mat .* target_mat))
Definition at line 1568 of file cu-matrix.cc.
References CU2DBLOCK, CuArray< T >::Data(), CuVectorBase< Real >::data_, CuArray< T >::Dim(), Timer::Elapsed(), KALDI_ASSERT, kaldi::Log(), CuVector< Real >::Resize(), and CuVectorBase< Real >::Vec().
Referenced by kaldi::UnitTestCuDiffXent().
{
   KALDI_ASSERT(tgt.Dim() == num_rows_);
   log_post_tgt->Resize(tgt.Dim());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(1, CU2DBLOCK*8);
     dim3 dimGrid(1, n_blocks(tgt.Dim(), CU2DBLOCK*8));
     cuda_diff_xent(dimGrid, dimBlock, tgt.Data(), data_,
                    log_post_tgt->data_, Dim());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     MatrixIndexT num_rows = num_rows_;
     for(int32 r = 0; r < num_rows; r++) {
       int32 col_tgt = tgt.Data()[r];
       Real &value = Mat()(r, col_tgt);
       log_post_tgt->Vec()(r) = Log(value);
       value -= 1.0;
     }
   }
 }
::MatrixDim Dim () const inline
Definition at line 201 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::AddVecMatPointMulVec(), CuRand< Real >::BinarizeProbs(), CuMatrix< Real >::CompObjfAndDeriv(), kaldi::cu::Copy(), CuVectorBase< Real >::CopyColFromMat(), CuTpMatrix< Real >::CopyFromMat(), CuSpMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuSparseMatrix< Real >::CopyToMat(), CuTpMatrix< Real >::Invert(), CuRand< Real >::RandGaussian(), kaldi::cu::Randomize(), CuRand< Real >::RandUniform(), kaldi::cu::RegularizeL1(), CuBlockMatrix< Real >::SetCudaData(), kaldi::cu::Splice(), CuMatrixBase< Real >::SumColumnRanges(), kaldi::TraceMatMat(), and kaldi::TraceMatSmat().
{
     ::MatrixDim d = { num_rows_, num_cols_, stride_ };
     return d;
   }
void DivElements (const CuMatrixBase< Real > & A)
Divide two matrices elementwise: C = A ./ A.
Definition at line 661 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by kaldi::UnitTestCuMatrixDivElements().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(num_cols_ == A.NumCols());
     KALDI_ASSERT(num_rows_ == A.NumRows());
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_div_elements(dimGrid, dimBlock, data_, A.data_, Dim(), A.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().DivElements(A.Mat());
   }
 }
void DivRowsVec (const CuVectorBase< Real > & div)
divide i'th row by scale[i]
Definition at line 834 of file cu-matrix.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), VectorBase< Real >::InvertElements(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by kaldi::UnitTestCuMatrixDivRowsVec().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(div.Dim() == NumRows());
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_div_rows_vec(dimGrid, dimBlock, data_, div.data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vector<Real> temp(div.Vec()); // will copy.
     temp.InvertElements();
     Mat().MulRowsVec(temp);
   }
 }
void EqualElementMask (const CuMatrixBase< Real > & mat, CuMatrix< Real > * mask) const
Definition at line 2811 of file cu-matrix.cc.
References CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrix< Real >::Resize(), and CuMatrixBase< Real >::Stride().
Referenced by MaxpoolingComponent::Backprop(), MaxPoolingComponent::BackpropagateFnc(), and MaxPooling2DComponent::BackpropagateFnc().
{
   // Check the inputs:
   KALDI_ASSERT(mat.NumRows() == NumRows() && mat.NumCols() == NumCols());
   KALDI_ASSERT(mask != NULL);
   // Resizes the output matrix:
   mask->Resize(NumRows(), NumCols(), kSetZero);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_equal_element_mask(dimGrid, dimBlock, this->data_, mat.Data(),
                             mask->Data(), this->Dim(), mat.Stride(),
                             mask->Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     for (int32 r = 0; r < NumRows(); r++) {
       for (int32 c = 0; c < NumCols(); c++) {
         (*mask)(r,c) = ((*this)(r,c) ==  mat(r,c) ? 1.0 : 0.0);
       }
     }
   }
 }
void FindRowMaxId (CuArray< int32 > * id) const
Find the id of the maximal element for each row.
Definition at line 1508 of file cu-matrix.cc.
References CU1DBLOCK, rnnlm::d, CuArray< T >::Data(), CuVectorBase< Real >::data_, Timer::Elapsed(), and CuVectorBase< Real >::Set().
Referenced by kaldi::nnet3::ComputeAccuracy(), NnetUpdater::ComputeTotAccuracy(), Xent::Eval(), kaldi::TestCuFindRowMaxId(), and kaldi::UnitTestCuFindRowMaxId().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     // initialize the vectors
     CuVector<Real> max(num_rows_);
     max.Set(-1e21);
     id->Resize(num_rows_);
     id->Set(-1);
     MatrixDim d=Dim(); // only stride will be used!
     // process per 256 column blocks
     for (int32 block = 0; (block+1)*256 <= num_cols_; block++) {
       dim3 dimBlock(CU1DBLOCK, 1);
       dim3 dimGrid(1, num_rows_);
       int32 offset = block*CU1DBLOCK;
       cuda_find_row_max_id(dimGrid, dimBlock, data_ + offset,
                            max.data_, id->Data(), offset, d);
     }
     // process the remainder
     int32 div = num_cols_ / 256;
     int32 mod = num_cols_ % 256;
     if (mod != 0) {
       dim3 dimBlock(mod, 1);
       dim3 dimGrid(1, num_rows_);
       int32 offset=div*256;
       cuda_find_row_max_id(dimGrid, dimBlock, data_ + offset,
                            max.data_, id->Data(), offset, d);
     }
     // now we have the indices!
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     // allocate index buffer
     id->Resize(num_rows_);
     id->Set(-1);
     // find maxima
     MatrixIndexT num_rows = num_rows_, num_cols = num_cols_;
     for(MatrixIndexT r = 0; r < num_rows; r++) {
       Real max = -1e21;
       int32 max_id = -1;
       const Real *row_data = Mat().RowData(r);
       for(MatrixIndexT c = 0; c < num_cols; c++) {
         if (max < row_data[c]) {
           max = row_data[c];
           max_id = c;
         }
       }
       id->Data()[r] = max_id;
     }
   }
 }
Real FrobeniusNorm () const inline
Definition at line 206 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::ApproxEqual(), and kaldi::UnitTestCuSparseMatrixFrobeniusNorm().
 { return sqrt(TraceMatMat(*this, *this, kTrans)); }
void GroupMax (const CuMatrixBase< Real > & src)
Apply the function y(i) = (max_{j = i*G}^{(i+1)*G-1} x_j where G = x.NumCols() / y.NumCols() must be an integer.
[note: y corresponds to *this and x to src, so src.NumCols() / this->NumCols() must be an integer.
Definition at line 1310 of file cu-matrix.cc.
References CU2DBLOCK, CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by MaxoutComponent::Propagate(), kaldi::TestCuMatrixGroupMax(), and kaldi::UnitTestCuMatrixGroupMax().
{
   int group_size = src.NumCols() / this->NumCols();
   KALDI_ASSERT(src.NumCols() == this->NumCols() * group_size &&
                this->NumRows() == src.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(NumCols(), CU2DBLOCK),
                  n_blocks(NumRows(), CU2DBLOCK));
     cuda_group_max(dimGrid, dimBlock, this->data_, src.data_,
                    this->Dim(), src.Stride(), group_size);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().GroupMax(src.Mat());
   }
 }
void GroupMaxDeriv (const CuMatrixBase< Real > & input, const CuMatrixBase< Real > & output)
Calculate derivatives for the GroupMax function above, where "input" is the input to the GroupMax function above (i.e.
the "src" variable), and "output" is the result of the computation (i.e. the "this" of that function call), and *this must have the same dimension as "input". Each element of *this will be set to 1 if the corresponding input equals the output of the group, and 0 otherwise. The equals the function derivative where it is defined (it's not defined where multiple inputs in the group are equal to the output).
Definition at line 809 of file cu-matrix.cc.
References CU2DBLOCK, CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::Stride().
Referenced by MaxoutComponent::Backprop(), kaldi::TestCuMatrixGroupMaxDeriv(), and kaldi::UnitTestCuMatrixGroupMaxDeriv().
{
   KALDI_ASSERT(src2.NumCols() > 0);
   int group_size = this->NumCols() / src2.NumCols();
   KALDI_ASSERT(this->NumCols() == src2.NumCols() * group_size);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
    Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(NumCols(), CU2DBLOCK),
                  n_blocks(NumRows(), CU2DBLOCK));
     cuda_calc_group_max_deriv(dimGrid, dimBlock, this->data_,
                               src1.Data(), src2.Data(), Dim(),
                               src2.Stride(), group_size);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().GroupMaxDeriv(src1.Mat(), src2.Mat());
   }
 }
void GroupPnorm (const CuMatrixBase< Real > & src, Real pow)
Apply the function y(i) = (sum_{j = i*G}^{(i+1)*G-1} x_j ^ (power)) ^ (1 / p) where G = x.NumCols() / y.NumCols() must be an integer.
[note: y corresponds to *this and x to src, so src.NumCols() / this->NumCols() must be an integer.
Definition at line 1288 of file cu-matrix.cc.
References CU2DBLOCK, CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by PnormComponent::Propagate(), kaldi::TestCuMatrixGroupPnorm(), and kaldi::UnitTestCuMatrixGroupPnorm().
{
   int group_size = src.NumCols() / this->NumCols();
   KALDI_ASSERT(src.NumCols() == this->NumCols() * group_size &&
                this->NumRows() == src.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(NumCols(), CU2DBLOCK),
                  n_blocks(NumRows(), CU2DBLOCK));
     cuda_group_pnorm(dimGrid, dimBlock, this->data_, src.data_, this->Dim(),
                      src.Stride(), group_size, power);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().GroupPnorm(src.Mat(), power);
   }
 }
void GroupPnormDeriv (const CuMatrixBase< Real > & input, const CuMatrixBase< Real > & output, Real power)
Calculate derivatives for the GroupPnorm function above...
if "input" is the input to the GroupPnorm function above (i.e. the "src" variable), and "output" is the result of the computation (i.e. the "this" of that function call), and *this has the same dimension as "input", then it sets each element of *this to the derivative d(output-elem)/d(input-elem) for each element of "input", where "output-elem" is whichever element of output depends on that input element.
Definition at line 784 of file cu-matrix.cc.
References CU2DBLOCK, CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::Stride().
Referenced by PnormComponent::Backprop(), kaldi::TestCuMatrixGroupPnormDeriv(), and kaldi::UnitTestCuMatrixGroupPnormDeriv().
{
   KALDI_ASSERT(src2.NumCols() > 0);
   int group_size = this->NumCols() / src2.NumCols();
   KALDI_ASSERT(this->NumCols() == src2.NumCols() * group_size);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(NumCols(), CU2DBLOCK),
                  n_blocks(NumRows(), CU2DBLOCK));
     cuda_calc_pnorm_deriv(dimGrid, dimBlock, this->data_, src1.Data(),
                           src2.Data(), Dim(), src2.Stride(), group_size, power);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().GroupPnormDeriv(src1.Mat(), src2.Mat(), power);
   }
 }
void InvertElements ()
invert the matrix by elements.
Definition at line 859 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by kaldi::TestCuMatrixCompObjfAndDeriv(), NnetEnsembleTrainer::TrainOneMinibatch(), kaldi::UnitTestCuMatrixInvertElements(), and kaldi::UnitTestCuMatrixObjfDeriv().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_invert_elements(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().InvertElements();
   }
 }
bool IsUnit (Real tol = 0.001) const
Definition at line 578 of file cu-matrix.cc.
References KALDI_ASSERT, kaldi::kTrans, and kaldi::TraceMatMat().
Referenced by OnlineNaturalGradient::InitOrthonormalSpecial(), OnlinePreconditioner::InitOrthonormalSpecial(), kaldi::UnitTestCuMatrixSymInvertPosDef(), and kaldi::UnitTestCuSpMatrixInvert().
{
   // want to return:
   //FrobeniusNorm(*this - I) <= tol * NumRows(), i.e.:
   //sqrt (trace((*this - I)(*this-I)) <= tol * NumRows()
   //    trace((*this - I)(*this - I)) <= tol * NumRows()
   // trace(*this * *this) + trace(I) - 2 * trace(*this) <= tol * NumRows()
   // trace(*this * *this) + dim - 2*this.Trace() <= tol * NumRows()
   KALDI_ASSERT(this->NumRows() == this->NumCols());
   return (TraceMatMat(*this, *this, kTrans) + this->NumRows() - 2.0 * this->Trace() <=
           tol * this->NumRows());
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (CuMatrixBase< Real >) private
void Lookup (const std::vector< Int32Pair > & indexes, Real * output) const
Definition at line 2752 of file cu-matrix.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by NnetDiscriminativeUpdater::LatticeComputations(), kaldi::TestCuMatrixLookup(), and kaldi::UnitTestCuMatrixLookup().
{
   // Checks the dimension.
   MatrixIndexT num_rows = this->num_rows_, num_cols = this->num_cols_;
   for (int32 i = 0; i < indices.size(); ++i) {
     KALDI_ASSERT(indices[i].first < num_rows && indices[i].first >= 0 &&
                  indices[i].second < num_cols && indices[i].second >= 0);
   }
   if (indices.size() == 0) return;
   KALDI_ASSERT(output != NULL);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuArray<Int32Pair> cuda_indices(indices);
     Lookup(cuda_indices, output);
   } else
 #endif
   {
     for (int32 i = 0; i < indices.size(); i++) {
       output[i] = (*this)(indices[i].first, indices[i].second);
     }
   }
 }
void Lookup (const CuArray< Int32Pair > & indexes, Real * output) const
Definition at line 2777 of file cu-matrix.cc.
References CuArray< T >::CopyToHost(), CU1DBLOCK, CuArray< T >::Data(), CuArray< T >::Dim(), Timer::Elapsed(), Int32Pair::first, rnnlm::i, KALDI_ASSERT, and Int32Pair::second.
{
   int32 num_elements = indices.Dim();
   if (num_elements == 0) return;
   KALDI_ASSERT(output != NULL);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuArray<Real> cuda_output(num_elements);
     Timer tim;
     dim3 dimBlock(CU1DBLOCK, 1);
     dim3 dimGrid(n_blocks(num_elements, CU1DBLOCK), 1);
     cuda_matrix_lookup(dimGrid, dimBlock, this->data_, this->Dim(),
                        indices.Data(), num_elements, cuda_output.Data());
     CU_SAFE_CALL(cudaGetLastError());
     cuda_output.CopyToHost(output);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     MatrixIndexT num_rows = this->num_rows_, num_cols = this->num_cols_;
     const Int32Pair *index = indices.Data();
     for (int32 i = 0; i < num_elements; i++) {
       KALDI_ASSERT(index[i].first < num_rows && index[i].first >= 0 &&
                    index[i].second < num_cols && index[i].second >= 0);
       output[i] = (*this)(index[i].first, index[i].second);
     }
   }
 }
const MatrixBase<Real>& Mat () const inline
Definition at line 582 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::AddCols(), CuVectorBase< Real >::AddDiagMat2(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMat(), CuSpMatrix< Real >::AddMat2(), CuMatrixBase< Real >::AddMatBlocks(), CuMatrixBase< Real >::AddMatDiagVec(), CuMatrixBase< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMatDivMat(), CuMatrixBase< Real >::AddMatMatElements(), CuVectorBase< Real >::AddMatVec(), CuMatrixBase< Real >::AddRows(), GeneralMatrix::AddToMat(), CuMatrixBase< Real >::AddVecMatPointMulVec(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), CuMatrixBase< Real >::ApplySoftMaxPerRow(), kaldi::cu::Copy(), CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyCols(), CuTpMatrix< Real >::CopyFromMat(), CuSpMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyRows(), CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), CuSparseMatrix< Real >::CopyToMat(), GeneralMatrix::CopyToMat(), CuMatrixBase< Real >::DiffSigmoid(), CuMatrixBase< Real >::DiffTanh(), CuMatrixBase< Real >::DivElements(), CuMatrixBase< Real >::GroupMax(), CuMatrixBase< Real >::GroupMaxDeriv(), CuMatrixBase< Real >::GroupPnorm(), CuMatrixBase< Real >::GroupPnormDeriv(), CuMatrixBase< Real >::Max(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsGroupMat(), kaldi::cu::Randomize(), kaldi::cu::RegularizeL1(), CuMatrixBase< Real >::Sigmoid(), CuMatrixBase< Real >::SoftHinge(), kaldi::cu::Splice(), CuMatrixBase< Real >::SymAddMat2(), CuMatrixBase< Real >::Tanh(), kaldi::TraceMatMat(), and kaldi::TraceMatSmat().
{
     return *(reinterpret_cast<const MatrixBase<Real>* >(this));
   }
MatrixBase<Real>& Mat () inline
Definition at line 585 of file cu-matrix.h.
{
     return *(reinterpret_cast<MatrixBase<Real>* >(this));
   }
void Max (const CuMatrixBase< Real > & A)
Do, elementwise, *this = max(*this, A).
Definition at line 685 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by main(), SpliceMaxComponent::Propagate(), and kaldi::UnitTestCuMatrixMax().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(num_cols_ == A.NumCols());
     KALDI_ASSERT(num_rows_ == A.NumRows());
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_max(dimGrid, dimBlock, data_, A.data_, Dim(), A.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().Max(A.Mat());
   }
 }
Real Max () const
proxy to MatrixBase::Max(), cuda not used
Definition at line 2442 of file cu-matrix.cc.
References Timer::Elapsed(), kaldi::kUndefined, and MatrixBase< Real >::Max().
{
   Timer tim;
   // TODO rewrite in CUDA,
   Matrix<Real> tmp(NumRows(), NumCols(), kUndefined);
   CopyToMat(&tmp);
   Real ans = tmp.Max();
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   }
 #endif
   return ans;
 }
Real Min () const
proxy to MatrixBase::Min(), cuda not used
Definition at line 2458 of file cu-matrix.cc.
References Timer::Elapsed(), kaldi::kUndefined, and MatrixBase< Real >::Min().
Referenced by main().
{
   Timer tim;
   // TODO rewrite in CUDA,
   Matrix<Real> tmp(NumRows(), NumCols(), kUndefined);
   CopyToMat(&tmp);
   Real ans = tmp.Min();
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   }
 #endif
   return ans;
 }
void MulColsVec (const CuVectorBase< Real > & scale)
scale i'th column by scale[i]
Definition at line 710 of file cu-matrix.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by PerElementScaleComponent::Backprop(), FixedScaleComponent::Backprop(), Convolutional2DComponent::BackpropagateFnc(), Rescale::BackpropagateFnc(), PerElementScaleComponent::Propagate(), FixedScaleComponent::Propagate(), Rescale::PropagateFnc(), kaldi::UnitTestCuMatrixAddMatDiagVec(), kaldi::UnitTestCuMatrixMulColsVec(), and NnetLogprobTask::~NnetLogprobTask().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(scale.Dim() == NumCols());
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_mul_cols_vec(dimGrid, dimBlock, data_, scale.data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().MulColsVec(scale.Vec());
   }
 }
void MulElements (const CuMatrixBase< Real > & A)
Multiply two matrices elementwise: C = C .* A.
Definition at line 637 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by ElementwiseProductComponent::Backprop(), SigmoidComponent::Backprop(), TanhComponent::Backprop(), PowerComponent::Backprop(), RectifiedLinearComponent::Backprop(), SoftHingeComponent::Backprop(), SoftmaxComponent::Backprop(), Dropout::BackpropagateFnc(), kaldi::nnet1::ComputeStdDev(), Xent::Eval(), Mse::Eval(), ElementwiseProductComponent::Propagate(), DropoutComponent::Propagate(), KlHmm::PropagateFnc(), Dropout::PropagateFnc(), LengthNormComponent::PropagateFnc(), NnetEnsembleTrainer::TrainOneMinibatch(), kaldi::UnitTestCuMatrixAddMatMatElements(), kaldi::UnitTestCuMatrixMulElements(), kaldi::nnet1::UnitTestLengthNorm(), AffineTransform::Update(), FramePoolingComponent::Update(), ConvolutionalComponent::Update(), Rescale::Update(), and NaturalGradientPerElementScaleComponent::Update().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(num_cols_ == A.NumCols());
     KALDI_ASSERT(num_rows_ == A.NumRows());
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_mul_elements(dimGrid, dimBlock, data_, A.data_, Dim(), A.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().MulElements(A.Mat());
   }
 }
void MulRowsGroupMat (const CuMatrixBase< Real > & src)
divide each row into src.NumCols() groups, and then scale i'th row's jth group of elements by src[i, j].
Definition at line 761 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::Stride().
Referenced by MaxoutComponent::Backprop(), PnormComponent::Backprop(), and kaldi::UnitTestCuMatrixMulRowsGroupMat().
{
   KALDI_ASSERT(src.NumCols() > 0);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int group_size = this->NumCols() / src.NumCols();
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_mul_rows_group_mat(dimGrid, dimBlock, this->data_, src.data_,
                             this->Dim(), src.Stride(), group_size);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().MulRowsGroupMat(src.Mat());
   }
 }
void MulRowsVec (const CuVectorBase< Real > & scale)
scale i'th row by scale[i]
Definition at line 737 of file cu-matrix.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by NormalizeComponent::Backprop(), LogSoftmaxComponent::Backprop(), ClipGradientComponent::Backprop(), BlockSoftmax::BackpropagateFnc(), LengthNormComponent::BackpropagateFnc(), Xent::Eval(), Mse::Eval(), kaldi::nnet2::PreconditionDirections(), NormalizeComponent::Propagate(), LengthNormComponent::PropagateFnc(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), kaldi::UnitTestCuMatrixMulRowsVec(), AffineTransform::Update(), and ConvolutionalComponent::Update().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     KALDI_ASSERT(scale.Dim() == NumRows());
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_mul_rows_vec(dimGrid, dimBlock, data_, scale.data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().MulRowsVec(scale.Vec());
   }
 }
MatrixIndexT NumCols () const inline
Definition at line 196 of file cu-matrix.h.
Referenced by NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), NnetLdaStatsAccumulator::AccStatsFromOutput(), CuVectorBase< Real >::AddColSumMat(), MatrixRandomizer::AddData(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMat(), CuSpMatrix< Real >::AddMat2(), CuMatrixBase< Real >::AddMatBlock(), CuMatrixBase< Real >::AddMatBlocks(), CuMatrixBase< Real >::AddMatDiagVec(), CuBlockMatrix< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddMatVec(), CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::AddRows(), CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::AddVecMatPointMulVec(), NnetUpdater::Backprop(), SumReduceComponent::Backprop(), RepeatedAffineComponent::Backprop(), MaxoutComponent::Backprop(), MaxpoolingComponent::Backprop(), PnormComponent::Backprop(), NormalizeComponent::Backprop(), SigmoidComponent::Backprop(), TanhComponent::Backprop(), PowerComponent::Backprop(), RectifiedLinearComponent::Backprop(), SoftHingeComponent::Backprop(), ScaleComponent::Backprop(), SoftmaxComponent::Backprop(), LogSoftmaxComponent::Backprop(), SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), BlockAffineComponent::Backprop(), ConvolutionComponent::Backprop(), PermuteComponent::Backprop(), DctComponent::Backprop(), FixedLinearComponent::Backprop(), FixedAffineComponent::Backprop(), DropoutComponent::Backprop(), CompositeComponent::Backprop(), Convolutional1dComponent::Backprop(), Component::Backpropagate(), SentenceAveragingComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), ConvolutionalComponent::BackpropagateFnc(), ChunkInfo::CheckSize(), NnetComputerFromEg::Compute(), NnetOnlineComputer::Compute(), kaldi::nnet3::ComputeAccuracy(), NnetComputer::ComputeLastLayerDeriv(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet1::ComputeStdDev(), OnlineNaturalGradient::ComputeWt1(), OnlinePreconditioner::ComputeWt1(), ConvolutionComponent::ConvolutionComponent(), kaldi::cu::Copy(), CuVectorBase< Real >::CopyColFromMat(), CuVectorBase< Real >::CopyDiagFromMat(), CuMatrixBase< Real >::CopyFromBlock(), CuTpMatrix< Real >::CopyFromMat(), CuSpMatrix< Real >::CopyFromMat(), CuBlockMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyRows(), CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), CuSparseMatrix< Real >::CopyToMat(), CuMatrix< Real >::CuMatrix(), CuSubVector< Real >::CuSubVector(), CuTpMatrix< Real >::CuTpMatrix(), CuMatrixBase< Real >::DivElements(), CuMatrixBase< Real >::EqualElementMask(), Xent::Eval(), Mse::Eval(), MultiTaskLoss::Eval(), NnetComputer::ExecuteCommand(), Nnet::Feedforward(), Nnet::GetGradient(), Convolutional1dComponent::GetParameterDim(), LinearTransform::GetParams(), AffineTransform::GetParams(), TCNProjectionComponent::GetParams(), LstmProjectedStreams::GetParams(), TCNComponent::GetParams(), ConvolutionalComponent::GetParams(), Convolutional2DComponent::GetParams(), BLstmProjectedStreams::GetParams(), NnetComputer::GetPointers(), CuMatrixBase< Real >::GroupMax(), CuMatrixBase< Real >::GroupMaxDeriv(), CuMatrixBase< Real >::GroupPnorm(), CuMatrixBase< Real >::GroupPnormDeriv(), ConvolutionComponent::InderivPatchesToInderiv(), AffineComponent::Info(), AffineComponentPreconditioned::Info(), AffineComponentPreconditionedOnline::Info(), DctComponent::Info(), FixedLinearComponent::Info(), FixedAffineComponent::Info(), Convolutional1dComponent::Info(), OnlineNaturalGradient::Init(), OnlinePreconditioner::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), ConvolutionComponent::Init(), FixedAffineComponent::Init(), Convolutional1dComponent::Init(), LinearTransform::InitData(), OnlineNaturalGradient::InitOrthonormalSpecial(), OnlinePreconditioner::InitOrthonormalSpecial(), RepeatedAffineComponent::InputDim(), AffineComponent::InputDim(), BlockAffineComponent::InputDim(), FixedLinearComponent::InputDim(), FixedAffineComponent::InputDim(), Convolutional1dComponent::InputDim(), ConvolutionComponent::InputToInputPatches(), NnetDiscriminativeUpdater::LatticeComputations(), NnetComputer::MatrixStddev(), CuMatrixBase< Real >::Max(), kaldi::nnet1::MomentStatistics(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsGroupMat(), NnetComputer::NnetComputer(), RepeatedAffineComponent::NumParameters(), BlockAffineComponent::NumParameters(), ConvolutionComponent::NumParameters(), Convolutional1dComponent::NumParameters(), LinearTransform::NumParams(), AffineTransform::NumParams(), LstmProjectedStreams::NumParams(), TCNComponent::NumParams(), ConvolutionalComponent::NumParams(), Convolutional2DComponent::NumParams(), BLstmProjectedStreams::NumParams(), CuMatrix< BaseFloat >::operator=(), DctComponent::OutputDim(), kaldi::nnet2::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirections(), OnlinePreconditioner::PreconditionDirections(), kaldi::nnet2::PreconditionDirectionsAlpha(), kaldi::nnet2::PreconditionDirectionsAlphaRescaled(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::nnet3::PrintParameterStats(), NnetComputeProb::ProcessOutputs(), Nnet::Propagate(), DistributeComponent::Propagate(), ElementwiseProductComponent::Propagate(), Component::Propagate(), SumReduceComponent::Propagate(), RepeatedAffineComponent::Propagate(), NormalizeComponent::Propagate(), SpliceComponent::Propagate(), BlockAffineComponent::Propagate(), ConvolutionComponent::Propagate(), DctComponent::Propagate(), DropoutComponent::Propagate(), AdditiveNoiseComponent::Propagate(), CompositeComponent::Propagate(), Convolutional1dComponent::Propagate(), KlHmm::PropagateFnc(), SentenceAveragingComponent::PropagateFnc(), FramePoolingComponent::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), Dropout::PropagateFnc(), Convolutional2DComponent::PropagateFnc(), kaldi::cu::Randomize(), Rbm::RbmUpdate(), LinearTransform::ReadData(), AffineTransform::ReadData(), ConvolutionalComponent::ReadData(), Rbm::ReadData(), Rbm::Reconstruct(), kaldi::cu::RegularizeL1(), DctComponent::Reorder(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), Mse::Report(), NnetRescaler::RescaleComponent(), CuMatrixBase< BaseFloat >::Row(), OnlineNaturalGradient::SelfTest(), OnlinePreconditioner::SelfTest(), CuBlockMatrix< Real >::SetCudaData(), LinearTransform::SetLinearity(), AffineTransform::SetLinearity(), NaturalGradientRepeatedAffineComponent::SetNaturalGradientConfigs(), kaldi::cu::Splice(), SigmoidComponent::StoreStats(), NonlinearComponent::StoreStatsInternal(), PdfPrior::SubtractOnLogpost(), kaldi::TraceMatMat(), kaldi::TraceMatSmat(), kaldi::UnitTestCuMathCopy(), kaldi::UnitTestCuMathRandomize(), kaldi::UnitTestCuMathSplice(), kaldi::UnitTestCuTanh(), UnitTestMatrixRandomizer(), kaldi::nnet2::UnitTestNnetCompute(), kaldi::UnitTestSwapCu2Cu(), kaldi::UnitTestSwapCu2M(), RepeatedAffineComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), Convolutional1dComponent::UnVectorize(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), BlockAffineComponentPreconditioned::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), BlockAffineComponent::UpdateSimple(), NonlinearComponent::UpdateStats(), MatrixRandomizer::Value(), RepeatedAffineComponent::Vectorize(), BlockAffineComponent::Vectorize(), ConvolutionComponent::Vectorize(), Convolutional1dComponent::Vectorize(), and DctComponent::Write().
 { return num_cols_;  }
MatrixIndexT NumRows () const inline
Dimensions.
Definition at line 195 of file cu-matrix.h.
Referenced by NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), NnetLdaStatsAccumulator::AccStatsFromOutput(), CuMatrixBase< Real >::AddCols(), CuVectorBase< Real >::AddColSumMat(), MatrixRandomizer::AddData(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMat(), CuSpMatrix< Real >::AddMat2(), CuMatrixBase< Real >::AddMatBlock(), CuMatrixBase< Real >::AddMatBlocks(), CuMatrixBase< Real >::AddMatDiagVec(), CuBlockMatrix< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddMatVec(), CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::AddVecMatPointMulVec(), AffineComponent::AffineComponent(), DistributeComponent::Backprop(), NnetUpdater::Backprop(), ElementwiseProductComponent::Backprop(), SumReduceComponent::Backprop(), RepeatedAffineComponent::Backprop(), MaxoutComponent::Backprop(), MaxpoolingComponent::Backprop(), PnormComponent::Backprop(), NormalizeComponent::Backprop(), SigmoidComponent::Backprop(), TanhComponent::Backprop(), PowerComponent::Backprop(), RectifiedLinearComponent::Backprop(), SoftHingeComponent::Backprop(), ScaleComponent::Backprop(), SoftmaxComponent::Backprop(), LogSoftmaxComponent::Backprop(), AffineComponent::Backprop(), ClipGradientComponent::Backprop(), SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), BlockAffineComponent::Backprop(), SumGroupComponent::Backprop(), ConvolutionComponent::Backprop(), PermuteComponent::Backprop(), DctComponent::Backprop(), FixedLinearComponent::Backprop(), FixedAffineComponent::Backprop(), DropoutComponent::Backprop(), CompositeComponent::Backprop(), Convolutional1dComponent::Backprop(), Component::Backpropagate(), SimpleSentenceAveragingComponent::BackpropagateFnc(), BlockSoftmax::BackpropagateFnc(), TCNComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), ConvolutionalComponent::BackpropagateFnc(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), ChunkInfo::CheckSize(), NnetComputerFromEg::Compute(), NnetOnlineComputer::Compute(), DecodableAmNnetParallel::Compute(), kaldi::nnet3::ComputeAccuracy(), NnetComputer::ComputeLastLayerDeriv(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet1::ComputeStdDev(), NnetUpdater::ComputeTotAccuracy(), Convolutional1dComponent::Convolutional1dComponent(), ConvolutionComponent::ConvolutionComponent(), kaldi::cu::Copy(), CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyCols(), CuVectorBase< Real >::CopyDiagFromMat(), CuMatrixBase< Real >::CopyFromBlock(), CuTpMatrix< Real >::CopyFromMat(), CuSpMatrix< Real >::CopyFromMat(), CuBlockMatrix< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), CuSparseMatrix< Real >::CopyToMat(), CuMatrix< Real >::CuMatrix(), CuTpMatrix< Real >::CuTpMatrix(), DecodableAmNnet::DecodableAmNnet(), CuMatrixBase< Real >::DivElements(), CuMatrixBase< Real >::EqualElementMask(), Xent::Eval(), Mse::Eval(), MultiTaskLoss::Eval(), Nnet::Feedforward(), Nnet::GetGradient(), Convolutional1dComponent::GetParameterDim(), LinearTransform::GetParams(), AffineTransform::GetParams(), TCNProjectionComponent::GetParams(), LstmProjectedStreams::GetParams(), TCNComponent::GetParams(), ConvolutionalComponent::GetParams(), Convolutional2DComponent::GetParams(), BLstmProjectedStreams::GetParams(), NnetComputer::GetPointers(), AffineComponentPreconditioned::GetScalingFactor(), CuMatrixBase< Real >::GroupMax(), CuMatrixBase< Real >::GroupPnorm(), AffineComponent::Info(), AffineComponentPreconditioned::Info(), AffineComponentPreconditionedOnline::Info(), ConvolutionComponent::Info(), DctComponent::Info(), FixedLinearComponent::Info(), FixedAffineComponent::Info(), Convolutional1dComponent::Info(), OnlineNaturalGradient::Init(), OnlinePreconditioner::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), ConvolutionComponent::Init(), FixedAffineComponent::Init(), Convolutional1dComponent::Init(), LinearTransform::InitData(), FixedAffineComponent::InitFromConfig(), FixedLinearComponent::InitFromString(), FixedAffineComponent::InitFromString(), OnlineNaturalGradient::InitOrthonormalSpecial(), OnlinePreconditioner::InitOrthonormalSpecial(), NnetDiscriminativeUpdater::LatticeComputations(), main(), NnetComputer::MatrixStddev(), CuMatrixBase< Real >::Max(), kaldi::nnet1::MomentStatistics(), CuMatrixBase< Real >::MulElements(), NnetComputer::NnetComputer(), DecodableAmNnetParallel::NumFramesReady(), RepeatedAffineComponent::NumParameters(), BlockAffineComponent::NumParameters(), ConvolutionComponent::NumParameters(), Convolutional1dComponent::NumParameters(), LinearTransform::NumParams(), AffineTransform::NumParams(), LstmProjectedStreams::NumParams(), TCNComponent::NumParams(), ConvolutionalComponent::NumParams(), Convolutional2DComponent::NumParams(), BLstmProjectedStreams::NumParams(), NnetLogprobTask::operator()(), CuMatrix< BaseFloat >::operator=(), RepeatedAffineComponent::OutputDim(), AffineComponent::OutputDim(), BlockAffineComponent::OutputDim(), ConvolutionComponent::OutputDim(), DctComponent::OutputDim(), FixedLinearComponent::OutputDim(), FixedAffineComponent::OutputDim(), Convolutional1dComponent::OutputDim(), kaldi::nnet2::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirections(), OnlinePreconditioner::PreconditionDirections(), kaldi::nnet2::PreconditionDirectionsAlpha(), kaldi::nnet2::PreconditionDirectionsAlphaRescaled(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::nnet3::PrintParameterStats(), Nnet::Propagate(), DistributeComponent::Propagate(), NnetOnlineComputer::Propagate(), ElementwiseProductComponent::Propagate(), Component::Propagate(), SumReduceComponent::Propagate(), RepeatedAffineComponent::Propagate(), NormalizeComponent::Propagate(), SpliceComponent::Propagate(), BlockAffineComponent::Propagate(), ConvolutionComponent::Propagate(), DctComponent::Propagate(), AdditiveNoiseComponent::Propagate(), CompositeComponent::Propagate(), Convolutional1dComponent::Propagate(), KlHmm::PropagateFnc(), SimpleSentenceAveragingComponent::PropagateFnc(), SentenceAveragingComponent::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), TCNComponent::PropagateFnc(), Dropout::PropagateFnc(), Convolutional2DComponent::PropagateFnc(), LstmProjectedStreams::PropagateFnc(), LengthNormComponent::PropagateFnc(), BLstmProjectedStreams::PropagateFnc(), CuRand< Real >::RandGaussian(), kaldi::cu::Randomize(), CuRand< Real >::RandUniform(), Rbm::RbmUpdate(), LinearTransform::ReadData(), AffineTransform::ReadData(), ConvolutionalComponent::ReadData(), Rbm::ReadData(), Rbm::Reconstruct(), kaldi::cu::RegularizeL1(), DctComponent::Reorder(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), NnetRescaler::RescaleComponent(), LstmProjectedStreams::ResetLstmStreams(), OnlineNaturalGradient::SelfTest(), OnlinePreconditioner::SelfTest(), CuBlockMatrix< Real >::SetCudaData(), LinearTransform::SetLinearity(), AffineTransform::SetLinearity(), AffineComponent::SetParams(), ConvolutionComponent::SetParams(), Convolutional1dComponent::SetParams(), kaldi::cu::Splice(), SigmoidComponent::StoreStats(), NonlinearComponent::StoreStatsInternal(), CuMatrixBase< Real >::SumColumnRanges(), kaldi::TraceMatMat(), kaldi::TraceMatSmat(), kaldi::UnitTestCheck(), kaldi::UnitTestCuMathCopy(), kaldi::UnitTestCuMathRandomize(), kaldi::UnitTestCuMathSplice(), kaldi::UnitTestCuTanh(), UnitTestMatrixRandomizer(), kaldi::nnet2::UnitTestNnetCompute(), kaldi::nnet3::UnitTestPreconditionDirectionsOnline(), kaldi::nnet2::UnitTestPreconditionDirectionsOnline(), kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent(), kaldi::UnitTestSwapCu2Cu(), kaldi::UnitTestSwapCu2M(), RepeatedAffineComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), Convolutional1dComponent::UnVectorize(), LinearTransform::Update(), AffineTransform::Update(), SentenceAveragingComponent::Update(), TCNProjectionComponent::Update(), TCNComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), BlockAffineComponentPreconditioned::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), BlockAffineComponent::UpdateSimple(), NonlinearComponent::UpdateStats(), RepeatedAffineComponent::Vectorize(), BlockAffineComponent::Vectorize(), ConvolutionComponent::Vectorize(), Convolutional1dComponent::Vectorize(), DctComponent::Write(), and NnetLogprobTask::~NnetLogprobTask().
 { return num_rows_;  }
CuValue<Real> operator() (MatrixIndexT r, MatrixIndexT c) inline
Definition at line 509 of file cu-matrix.h.
{
     KALDI_PARANOID_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                           static_cast<UnsignedMatrixIndexT>(num_rows_) &&
                           static_cast<UnsignedMatrixIndexT>(c) <
                           static_cast<UnsignedMatrixIndexT>(num_cols_));
     return CuValue<Real>(data_ + r * stride_ + c);
   }
Real operator() (MatrixIndexT r, MatrixIndexT c) const inline
Definition at line 517 of file cu-matrix.h.
{
     KALDI_PARANOID_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                           static_cast<UnsignedMatrixIndexT>(num_rows_) &&
                           static_cast<UnsignedMatrixIndexT>(c) <
                           static_cast<UnsignedMatrixIndexT>(num_cols_));
     return CuValue<Real>(data_ + r * stride_ + c);  // will be casted to Real.
   }
CuSubMatrix<Real> Range (const MatrixIndexT row_offset, const MatrixIndexT num_rows, const MatrixIndexT col_offset, const MatrixIndexT num_cols) const inline
Definition at line 480 of file cu-matrix.h.
Referenced by CuBlockMatrix< Real >::AddMatMat(), NnetOnlineComputer::Compute(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), ConvolutionComponent::Init(), FixedAffineComponent::Init(), Convolutional1dComponent::Init(), NnetComputer::NnetComputer(), OnlineNaturalGradient::PreconditionDirections(), OnlinePreconditioner::PreconditionDirections(), NnetOnlineComputer::Propagate(), kaldi::UnitTestCuMatrixAddMat(), kaldi::UnitTestCuSubMatrix(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), and AffineComponent::Widen().
{
     return CuSubMatrix<Real>(*this, row_offset, num_rows,
                              col_offset, num_cols);
   }
const CuSubVector<Real> Row (MatrixIndexT i) const inline
Definition at line 497 of file cu-matrix.h.
Referenced by NnetOnlineComputer::Compute(), NnetDecodableBase::DoNnetComputation(), NnetComputer::NnetComputer(), LstmProjectedStreams::ResetLstmStreams(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::nnet2::UnitTestGenericComponentInternal(), kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent(), RepeatedAffineComponent::Update(), and NaturalGradientRepeatedAffineComponent::Update().
{
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                  static_cast<UnsignedMatrixIndexT>(num_rows_));
     return CuSubVector<Real>(data_ + (i * stride_), NumCols());
   }
CuSubVector<Real> Row (MatrixIndexT i) inline
Definition at line 503 of file cu-matrix.h.
{
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                  static_cast<UnsignedMatrixIndexT>(num_rows_));
     return CuSubVector<Real>(data_ + (i * stride_), NumCols());
   }
const Real* RowData (MatrixIndexT r) const inline
Get raw row pointer (const).
Warning: may return a pointer to GPU memory. Use at your own risk.
Definition at line 567 of file cu-matrix.h.
Referenced by CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), CuSubVector< Real >::CuSubVector(), kaldi::TestCuMatrixAddRows2(), kaldi::TestCuMatrixAddToRows(), kaldi::TestCuMatrixCopyRows2(), kaldi::TestCuMatrixCopyToRows(), kaldi::UnitTestCuMatrixAddRows(), and kaldi::UnitTestCuMatrixCopyRows().
 { return data_ + r * stride_; }
Real* RowData (MatrixIndexT r) inline
Get raw row pointer.
Warning: may return a pointer to GPU memory. Use at your own risk.
Definition at line 570 of file cu-matrix.h.
 { return data_ + r * stride_; }
CuSubMatrix<Real> RowRange (const MatrixIndexT row_offset, const MatrixIndexT num_rows) const inline
Definition at line 487 of file cu-matrix.h.
Referenced by MatrixRandomizer::AddData(), BlockAffineComponent::Backprop(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), NnetOnlineComputer::Propagate(), BlockAffineComponent::Propagate(), LstmProjectedStreams::PropagateFnc(), BLstmProjectedStreams::PropagateFnc(), RepeatedAffineComponent::Update(), and MatrixRandomizer::Value().
{
     return CuSubMatrix<Real>(*this, row_offset, num_rows,
                              0, num_cols_);
   }
void Scale (Real value)
Definition at line 593 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by TanhComponent::Backprop(), PowerComponent::Backprop(), ScaleComponent::Backprop(), LogSoftmaxComponent::Backprop(), AveragePoolingComponent::BackpropagateFnc(), AveragePooling2DComponent::BackpropagateFnc(), Dropout::BackpropagateFnc(), DecodableAmNnetParallel::Compute(), DecodableNnet2Online::ComputeForFrame(), NnetDecodableBase::DoNnetComputation(), MultiTaskLoss::Eval(), RepeatedAffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), BlockAffineComponent::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), OnlineNaturalGradient::InitDefault(), OnlinePreconditioner::InitDefault(), LstmProjectedStreams::InitMatParam(), BLstmProjectedStreams::InitMatParam(), main(), kaldi::nnet2::PreconditionDirectionsAlphaRescaled(), ScaleComponent::Propagate(), DropoutComponent::Propagate(), KlHmm::PropagateFnc(), Dropout::PropagateFnc(), Rbm::RbmUpdate(), RepeatedAffineComponent::Scale(), NaturalGradientAffineComponent::Scale(), AffineComponent::Scale(), BlockAffineComponent::Scale(), ConvolutionComponent::Scale(), Convolutional1dComponent::Scale(), TanhComponent::StoreStats(), kaldi::nnet3::TestSimpleComponentPropagateProperties(), kaldi::UnitTestCuMatrixAddMatDiagVec(), kaldi::UnitTestCuMatrixAddMatMatElements(), kaldi::UnitTestCuMatrixScale(), and Convolutional2DComponent::Update().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_scale(dimGrid, dimBlock, data_, value, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().Scale(value);
   }
 }
void Set (Real value)
Definition at line 480 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by SigmoidComponent::Backprop(), MaxpoolingComponent::Propagate(), MaxPoolingComponent::PropagateFnc(), MaxPooling2DComponent::PropagateFnc(), Dropout::PropagateFnc(), SigmoidComponent::StoreStats(), kaldi::UnitTestCuMatrixObjfDeriv(), kaldi::UnitTestCuMatrixSet(), and kaldi::nnet1::UnitTestMaxPoolingComponent().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_set_const(dimGrid, dimBlock, data_, value, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().Set(value);
   }
 }
void SetRandn ()
Definition at line 2531 of file cu-matrix.cc.
References CuRand< Real >::RandGaussian().
Referenced by kaldi::CuVectorUnitTestAddColSumMat(), kaldi::CuVectorUnitTestAddDiagMat2(), kaldi::CuVectorUnitTestAddDiagMatMat(), kaldi::CuVectorUnitTestAddMatVec(), kaldi::CuVectorUnitTestAddRowSumMat(), kaldi::CuVectorUnitTestCopyFromMat(), RepeatedAffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), BlockAffineComponent::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), FixedAffineComponent::InitFromConfig(), RepeatedAffineComponent::PerturbParams(), AffineComponent::PerturbParams(), BlockAffineComponent::PerturbParams(), ConvolutionComponent::PerturbParams(), Convolutional1dComponent::PerturbParams(), CuRand< Real >::RandGaussian(), kaldi::TestCuMatrixAddMat(), kaldi::TestCuMatrixAddMatBlocks(), kaldi::TestCuMatrixAddRowRanges(), kaldi::TestCuMatrixAddRows1(), kaldi::TestCuMatrixAddRows2(), kaldi::TestCuMatrixAddToRows(), kaldi::TestCuMatrixCompObjfAndDeriv(), kaldi::TestCuMatrixCopyLowerToUpper(), kaldi::TestCuMatrixCopyRows1(), kaldi::TestCuMatrixCopyRows2(), kaldi::TestCuMatrixCopyToRows(), kaldi::TestCuMatrixCopyUpperToLower(), kaldi::TestCuMatrixHeaviside(), kaldi::TestCuMatrixLogSoftmax(), kaldi::TestCuMatrixLookup(), kaldi::TestCuMatrixMatMatBatched(), kaldi::TestCuMatrixMulRowsGroupMat(), kaldi::TestCuMatrixSetZeroAboveDiag(), kaldi::TestCuMatrixSigmoid(), kaldi::TestCuMatrixSoftmax(), kaldi::TestCuMatrixTraceMatMat(), kaldi::TestCuVectorAddColSumMat(), kaldi::TestCuVectorAddDiagMat2(), kaldi::TestCuVectorAddDiagMatMat(), kaldi::TestCuVectorAddRowSumMat(), kaldi::nnet3::TestSimpleComponentDataDerivative(), kaldi::nnet3::TestSimpleComponentModelDerivative(), kaldi::nnet3::TestSimpleComponentPropagateProperties(), kaldi::UnitTestCuApproxEqual(), kaldi::UnitTestCuBlockMatrixAddMatBlock(), kaldi::UnitTestCuBlockMatrixAddMatMat(), kaldi::UnitTestCuCholesky(), kaldi::UnitTestCuMathCopy(), kaldi::UnitTestCuMathRandomize(), kaldi::UnitTestCuMathSplice(), kaldi::UnitTestCuMatrixAddCols(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestCuMatrixAddElements(), kaldi::UnitTestCuMatrixAddRows(), kaldi::UnitTestCuMatrixAddToRows(), kaldi::UnitTestCuMatrixCopyCols(), kaldi::UnitTestCuMatrixCopyCross(), kaldi::UnitTestCuMatrixCopyCross2(), kaldi::UnitTestCuMatrixCopyLowerToUpper(), kaldi::UnitTestCuMatrixCopyRows(), kaldi::UnitTestCuMatrixCopyToRows(), kaldi::UnitTestCuMatrixCopyUpperToLower(), kaldi::UnitTestCuMatrixIO(), kaldi::UnitTestCuMatrixLookup(), kaldi::UnitTestCuMatrixObjfDeriv(), kaldi::UnitTestCuMatrixSetRandn(), kaldi::UnitTestCuMatrixSetZeroAboveDiag(), kaldi::UnitTestCuMatrixSum(), kaldi::UnitTestCuMatrixSymAddMat2(), kaldi::UnitTestCuMatrixSymInvertPosDef(), kaldi::UnitTestCuMatrixTraceMatMat(), kaldi::UnitTestCuMatrixTranspose(), kaldi::UnitTestCuSparseMatrixFrobeniusNorm(), kaldi::UnitTestCuSparseMatrixSum(), kaldi::UnitTestCuSparseMatrixTraceMatSmat(), kaldi::UnitTestCuSpMatrixCopyFromMat(), kaldi::UnitTestCuSubMatrix(), kaldi::UnitTestCuTpMatrixCopyFromMat(), kaldi::nnet2::UnitTestFixedAffineComponent(), kaldi::nnet2::UnitTestFixedLinearComponent(), kaldi::nnet2::UnitTestGenericComponentInternal(), kaldi::UnitTestMatrix(), kaldi::nnet2::UnitTestNnetCompute(), kaldi::nnet3::UnitTestNnetCompute(), kaldi::nnet2::UnitTestNnetComputeChunked(), kaldi::nnet3::UnitTestNnetInputDerivatives(), kaldi::nnet3::UnitTestNnetModelDerivatives(), kaldi::nnet3::UnitTestNnetOptimizeWithOptions(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
   if (num_rows_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuRand<Real> tmp;
     tmp.RandGaussian(this);
   } else
 #endif
   {
     Mat().SetRandn();
   }
 }
void SetRandUniform ()
Definition at line 2545 of file cu-matrix.cc.
References CuRand< Real >::RandUniform().
Referenced by LstmProjectedStreams::InitMatParam(), BLstmProjectedStreams::InitMatParam(), CuRand< Real >::RandUniform(), kaldi::UnitTestCuMatrixEqualElementMask(), and kaldi::UnitTestCuMatrixSetRandUniform().
{
   if (num_rows_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     CuRand<Real> tmp;
     tmp.RandUniform(this);
   } else
 #endif
   {
     Mat().SetRandUniform();
   }
 }
void SetZero ()
Math operations, some calling kernels.
Definition at line 459 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by DistributeComponent::Backprop(), MaxPoolingComponent::BackpropagateFnc(), AveragePoolingComponent::BackpropagateFnc(), MaxPooling2DComponent::BackpropagateFnc(), AveragePooling2DComponent::BackpropagateFnc(), CopyComponent::BackpropagateFnc(), CuSparseMatrix< Real >::CopyToMat(), OnlineNaturalGradient::InitOrthonormalSpecial(), OnlinePreconditioner::InitOrthonormalSpecial(), AveragePoolingComponent::PropagateFnc(), AveragePooling2DComponent::PropagateFnc(), FramePoolingComponent::PropagateFnc(), LstmProjectedStreams::PropagateFnc(), Rbm::RbmUpdate(), RepeatedAffineComponent::SetZero(), AffineComponent::SetZero(), BlockAffineComponent::SetZero(), ConvolutionComponent::SetZero(), Convolutional1dComponent::SetZero(), and kaldi::TestCuMatrixCompObjfAndDeriv().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cudaMemset2D(data_, stride_ * sizeof(Real), 0,
                               num_cols_ * sizeof(Real), num_rows_ ));
     CuDevice::Instantiate().AccuProfile("CuMatrix::SetZero", tim.Elapsed());
   } else
 #endif
   {
     Mat().SetZero();
   }
 }
void SetZeroAboveDiag ()
Zeroes all elements for which col > row.
Definition at line 503 of file cu-matrix.cc.
References Timer::Elapsed(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and VectorBase< Real >::SetZero().
Referenced by kaldi::TestCuMatrixSetZeroAboveDiag(), kaldi::UnitTestCuMatrixSetZeroAboveDiag(), and kaldi::UnitTestSetZeroAboveDiag().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (num_rows_ == 0) return;
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_set_zero_above_diag(dimGrid, dimBlock, data_, Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     MatrixBase<Real> &mat = Mat();
     int32 num_rows = mat.NumRows(), num_cols = mat.NumCols();
     for (int32 r = 0; r + 1 < num_rows; r++) {
       SubVector<Real> vec(mat, r),
           vec_part(vec, r + 1, num_cols - (r + 1));
       vec_part.SetZero();
     }
   }
 }
void Sigmoid (const CuMatrixBase< Real > & src)
Set each element to the sigmoid of the corresponding element of "src": element by element, x = 1 / (1 + exp(-x))
Definition at line 1246 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), kaldi::SameDim(), and CuMatrixBase< Real >::Stride().
Referenced by SoftHingeComponent::Backprop(), SigmoidComponent::Propagate(), Sigmoid::PropagateFnc(), Rbm::PropagateFnc(), Rbm::Reconstruct(), kaldi::TestCuMatrixSigmoid(), kaldi::UnitTestCuMatrixSigmoid(), and kaldi::UnitTestCuSigmoid().
{
   KALDI_ASSERT(SameDim(*this, src));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_sigmoid(dimGrid, dimBlock, this->data_, src.data_, this->Dim(),
                  src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().Sigmoid(src.Mat());
   }
 }
MatrixIndexT SizeInBytes () const inline
Get size of matrix in bytes.
Definition at line 214 of file cu-matrix.h.
 { return num_rows_*stride_*sizeof(Real); }
void SoftHinge (const CuMatrixBase< Real > & src)
Apply the function y = log(1 + exp(x)), to each element.
Note: the derivative of this function is the sigmoid function. This is like a soft ReLU.
Definition at line 1267 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), kaldi::SameDim(), and CuMatrixBase< Real >::Stride().
Referenced by SoftHingeComponent::Propagate(), and kaldi::UnitTestCuMatrixSoftHinge().
{
   KALDI_ASSERT(SameDim(*this, src));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_soft_hinge(dimGrid, dimBlock, this->data_, src.data_, this->Dim(),
                     src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Mat().SoftHinge(src.Mat());
   }
 }
MatrixIndexT Stride () const inline
Definition at line 197 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::AddCols(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMat(), CuSpMatrix< Real >::AddMat2(), CuMatrixBase< Real >::AddMatBlock(), CuMatrixBase< Real >::AddMatBlocks(), CuMatrixBase< Real >::AddMatDiagVec(), CuBlockMatrix< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMatDivMat(), CuMatrixBase< Real >::AddMatMatElements(), CuVectorBase< Real >::AddMatVec(), CuMatrixBase< Real >::AddRows(), CuMatrixBase< Real >::AddVecMatPointMulVec(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), CuMatrixBase< Real >::ApplySoftMaxPerRow(), DistributeComponent::ComputeInputPointers(), CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyCols(), CuVectorBase< Real >::CopyDiagFromMat(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::CopyRows(), CuVectorBase< Real >::CopyRowsFromMat(), VectorBase< Real >::CopyRowsFromMat(), CuMatrixBase< Real >::DiffSigmoid(), CuMatrixBase< Real >::DiffTanh(), CuMatrixBase< Real >::DivElements(), CuMatrixBase< Real >::EqualElementMask(), NnetComputer::GetPointers(), CuMatrixBase< Real >::GroupMax(), CuMatrixBase< Real >::GroupMaxDeriv(), CuMatrixBase< Real >::GroupPnorm(), CuMatrixBase< Real >::GroupPnormDeriv(), CuMatrixBase< Real >::Max(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsGroupMat(), CuRand< Real >::RandGaussian(), CuRand< Real >::RandUniform(), kaldi::cu::RegularizeL1(), CuMatrixBase< Real >::Sigmoid(), CuMatrixBase< Real >::SoftHinge(), CuMatrixBase< Real >::SymAddMat2(), CuMatrixBase< Real >::Tanh(), kaldi::TraceMatMat(), kaldi::UnitTestCopySp(), and RepeatedAffineComponent::Update().
 { return stride_; }
Real Sum () const
Definition at line 2434 of file cu-matrix.cc.
References CuVectorBase< Real >::AddRowSumMat(), and CuVectorBase< Real >::Sum().
Referenced by kaldi::nnet1::CheckNanInf(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet1::ComputeStdDev(), Xent::Eval(), Mse::Eval(), kaldi::nnet3::PrintParameterStats(), NnetRescaler::RescaleComponent(), kaldi::UnitTestCuBlockMatrixAddMatMat(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestCuMatrixEqualElementMask(), kaldi::UnitTestCuMatrixSetRandn(), kaldi::UnitTestCuMatrixSetRandUniform(), kaldi::UnitTestCuMatrixSum(), kaldi::UnitTestCuMatrixTraceMatMat(), kaldi::UnitTestCuSparseMatrixSum(), kaldi::nnet3::UnitTestNnetCompute(), kaldi::nnet3::UnitTestNnetOptimizeWithOptions(), and FramePoolingComponent::Update().
{
   CuVector<Real> row_sum(NumCols());
   row_sum.AddRowSumMat(1.0, *this, 0.0);
   return row_sum.Sum();
 }
void SumColumnRanges (const CuMatrixBase< Real > & src, const CuArray< Int32Pair > & indexes)
For each row r of this and for each column c, sets (*this)(r, c) to the sum src(r, j), where j ranges from indexes[c].first through indexes[c].second - 1.
Definition at line 2315 of file cu-matrix.cc.
References CuArray< T >::Data(), CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::data_, CuArray< T >::Dim(), CuMatrixBase< Real >::Dim(), Timer::Elapsed(), Int32Pair::first, KALDI_ASSERT, CuMatrixBase< Real >::NumRows(), Int32Pair::second, and CuMatrixBase< Real >::stride_.
Referenced by SumGroupComponent::Propagate(), and kaldi::UnitTestCuMatrixSumColumnRanges().
{
   KALDI_ASSERT(static_cast<MatrixIndexT>(indices.Dim()) == NumCols());
   KALDI_ASSERT(NumRows() == src.NumRows());
   if (NumRows() == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_sum_column_ranges(dimGrid, dimBlock, data_, Dim(), src.Data(),
                            src.Dim(), indices.Data());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     int32 num_rows = this->num_rows_, num_cols = this->num_cols_,
        this_stride = this->stride_, src_stride = src.stride_;
     Real *data = this->data_;
     const Real *src_data = src.data_;
     const Int32Pair *indices_data = indices.Data();
     for (int32 row = 0; row < num_rows; row++) {
       for (int32 col = 0; col < num_cols; col++) {
         int32 start_col = indices_data[col].first,
                 end_col = indices_data[col].second;
         Real sum = 0.0;
         for (int32 src_col = start_col; src_col < end_col; src_col++)
           sum += src_data[row * src_stride + src_col];
         data[row * this_stride + col] = sum;
       }
     }
   }
 }
void SymAddMat2 (const Real alpha, const CuMatrixBase< Real > & M, MatrixTransposeType transA, Real beta)
*this = beta * *this + alpha * M M^T, for symmetric matrices.
It only updates the lower triangle of *this. It will leave the matrix asymmetric; if you need it symmetric as a regular matrix, do CopyLowerToUpper().
Definition at line 1105 of file cu-matrix.cc.
References CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, and CuMatrixBase< Real >::Stride().
Referenced by CuMatrixBase< Real >::Cholesky(), kaldi::nnet2::PreconditionDirections(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), kaldi::TestSymInvertPosDef(), kaldi::UnitTestCuCholesky(), kaldi::UnitTestCuMatrixSymAddMat2(), and kaldi::UnitTestCuMatrixSymInvertPosDef().
                {
   KALDI_ASSERT(num_rows_ == num_cols_ &&
                ((transA == kNoTrans && A.num_rows_ == num_rows_) ||
                 (transA == kTrans && A.num_cols_ == num_cols_)));
   if (num_rows_ == 0) return;
   KALDI_ASSERT(A.data_ != data_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     cublasOperation_t trans = (transA == kTrans ? CUBLAS_OP_N : CUBLAS_OP_T);
     MatrixIndexT A_other_dim = (transA == kNoTrans ? A.num_cols_ : A.num_rows_);
     CU_SAFE_CALL(cublas_syrk(GetCublasHandle(), CUBLAS_FILL_MODE_UPPER, trans,
                             num_rows_, A_other_dim, alpha, A.Data(),
                             A.Stride(), beta, this->data_, this->stride_));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().SymAddMat2(alpha, A.Mat(), transA, beta);
   }
 }
void SymInvertPosDef ()
Inversion for positive definite symmetric matrices.
Treats the input as symmetric but only reads the lower triangle. The output is symmetric.
Definition at line 1721 of file cu-matrix.cc.
References SpMatrix< Real >::AddTp2(), TpMatrix< Real >::Cholesky(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kTakeLower, kaldi::kTrans, kaldi::kUndefined, and PackedMatrix< Real >::NumRows().
Referenced by CuSpMatrix< Real >::Invert(), kaldi::nnet2::PreconditionDirections(), kaldi::TestSymInvertPosDef(), kaldi::UnitInvert(), kaldi::UnitTestCuMatrixSymInvertPosDef(), and kaldi::UnitTestInvert().
{
   KALDI_ASSERT(num_rows_ == num_cols_);
   if (num_rows_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CuMatrix<Real> inv_cholesky(num_rows_, num_rows_);
     this->Cholesky(&inv_cholesky);
     // note: SymAddMat2 only updates lower part of *this.
     this->SymAddMat2(1.0, inv_cholesky, kTrans, 0.0);
     this->CopyLowerToUpper();
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     SpMatrix<Real> temp_sp(this->Mat(), kTakeLower);
     TpMatrix<Real> C(temp_sp.NumRows(), kUndefined);
     C.Cholesky(temp_sp);
     C.Invert();
     temp_sp.AddTp2(1.0, C, kTrans, 0.0);
     this->Mat().CopyFromSp(temp_sp);
     // was previously just: CuSpMatrix::Invert().
   }
 }
void Tanh (const CuMatrixBase< Real > & src)
Compute the hyperbolic tangent (tanh) function; element by element, *this = tanh(src).
Definition at line 1465 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), kaldi::SameDim(), and CuMatrixBase< Real >::Stride().
Referenced by TanhComponent::Propagate(), Tanh::PropagateFnc(), and kaldi::UnitTestCuTanh().
{
   KALDI_ASSERT(SameDim(*this, src));
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimGrid, dimBlock;
     GetBlockSizesForSimpleMatrixOperation(NumRows(), NumCols(),
                                           &dimGrid, &dimBlock);
     cuda_tanh(dimGrid, dimBlock, this->data_, src.data_, this->Dim(), src.Stride());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Mat().Tanh(src.Mat());
   }
 }
Real Trace (bool check_square = true) const
Return the trace. If check_square = true, will crash if matrix is not square.
Definition at line 2474 of file cu-matrix.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, and kaldi::kUndefined.
Referenced by kaldi::CuVectorUnitTestCopyDiagFromMat().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     if (check_square) KALDI_ASSERT(this->num_rows_ == this->num_cols_);
     MatrixIndexT dim = std::min(this->num_rows_, this->num_cols_);
     CuVector<Real> tmp(1, kUndefined); // for result.
     int dimBlock(CU1DBLOCK);
     int dimGrid = 1;// only 1 block here. we have loops in each thread  //(n_blocks(dim_, CU1DBLOCK));
     cuda_vec_sum(dimGrid, dimBlock, data_, tmp.Data(), dim, Stride() + 1);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::Sum", tim.Elapsed());
     return tmp(0);
   } else
 #endif
   {
     return Mat().Trace(check_square);
   }
 }
void Write (std::ostream & os, bool binary) const
Definition at line 452 of file cu-matrix.cc.
References kaldi::kUndefined, and MatrixBase< Real >::Write().
Referenced by Nnet::Feedforward(), kaldi::UnitTestCuMatrixIO(), RepeatedAffineComponent::Write(), NaturalGradientAffineComponent::Write(), AffineComponent::Write(), AffineComponentPreconditioned::Write(), AffineComponentPreconditionedOnline::Write(), BlockAffineComponent::Write(), BlockAffineComponentPreconditioned::Write(), ConvolutionComponent::Write(), FixedLinearComponent::Write(), FixedAffineComponent::Write(), Convolutional1dComponent::Write(), Rbm::WriteAsNnet(), LinearTransform::WriteData(), AffineTransform::WriteData(), TCNProjectionComponent::WriteData(), LstmProjectedStreams::WriteData(), TCNComponent::WriteData(), ConvolutionalComponent::WriteData(), Convolutional2DComponent::WriteData(), Rbm::WriteData(), and BLstmProjectedStreams::WriteData().
{
   Matrix<Real> temp(this->num_rows_, this->num_cols_, kUndefined);
   this->CopyToMat(&temp);
   temp.Write(os, binary);
 }
Friends And Related Function Documentation
void AddMatMatBatched (const Real alpha, std::vector< CuSubMatrix< Real > * > & C, const std::vector< CuSubMatrix< Real > * > & A, MatrixTransposeType transA, const std::vector< CuSubMatrix< Real > * > & B, MatrixTransposeType transB, const Real beta) friend
Does multiple matrix multiplications, executing them in parallel using cuBLAS's gemmBatched if we are using a GPU.
Vectors A, B and C must have the same length; for each i, this function executes the matrix operation C[i] = alpha * A[i](^T)*B[i](^T) + beta * C[i].
Definition at line 1813 of file cu-matrix.cc.
{
     // the batch counts should be the same
     int32 batchCountA = static_cast<int32>(A.size()), batchCountB = static_cast<int32>(B.size()), batchCountC = static_cast<int32>(C.size());
     KALDI_ASSERT((batchCountA == batchCountB) && (batchCountB == batchCountC));
     int32 batchCount = batchCountA;
     if (batchCount == 0) return;
     // all elements must have the same num-rows, num-cols and stride
     for (int32 i = 0; i < batchCount-1; i++) {
       KALDI_ASSERT(A[i]->NumRows() == A[i+1]->NumRows());
       KALDI_ASSERT(A[i]->NumCols() == A[i+1]->NumCols());
       KALDI_ASSERT(A[i]->Stride() == A[i+1]->Stride());
       KALDI_ASSERT(B[i]->NumRows() == B[i+1]->NumRows());
       KALDI_ASSERT(B[i]->NumCols() == B[i+1]->NumCols());
       KALDI_ASSERT(B[i]->Stride() == B[i+1]->Stride());
       KALDI_ASSERT(C[i]->NumRows() == C[i+1]->NumRows());
       KALDI_ASSERT(C[i]->NumCols() == C[i+1]->NumCols());
       KALDI_ASSERT(C[i]->Stride() == C[i+1]->Stride());
     }
     // CUBLAS is col-major, cudamatrix is row-major, how to do the mapping?
     // keep trans..., just swap A&B matrices: A->B B->A
     MatrixIndexT m = ((transB==kTrans)? B[0]->NumRows() : B[0]->NumCols());
     MatrixIndexT n = ((transA==kTrans)? A[0]->NumCols() : A[0]->NumRows());
     MatrixIndexT k = ((transB==kTrans)? B[0]->NumCols() : B[0]->NumRows());
     MatrixIndexT k1 = ((transA==kTrans)? A[0]->NumRows() : A[0]->NumCols());
     KALDI_ASSERT(m == C[0]->NumCols());
     KALDI_ASSERT(n == C[0]->NumRows());
     KALDI_ASSERT(k == k1);
     if (m == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     // place all data (A[batchCount], B[batchCount], C[batchCount]) in memory together
     // in order to make only one call of cudaMemcpy
     Real **device_abc_array = (Real**)CuDevice::Instantiate().Malloc(3*batchCount*sizeof(Real*));
     const Real **device_a_array = const_cast<const Real**>(device_abc_array);
     const Real **device_b_array = const_cast<const Real**>(device_abc_array) + batchCount;
     Real **device_c_array = device_abc_array + 2 * batchCount;
     const Real **host_abc_array = new const Real*[3*batchCount];
     const Real **host_a_array = host_abc_array;
     const Real **host_b_array = host_abc_array + batchCount;
     const Real **host_c_array = host_abc_array + 2 * batchCount;
     for (int32 i = 0; i < batchCount; i++) {
       host_a_array[i] = A[i]->data_;
       host_b_array[i] = B[i]->data_;
       host_c_array[i] = C[i]->data_;
     }
     CU_SAFE_CALL(cudaMemcpy(device_abc_array, host_abc_array, 3*batchCount*sizeof(Real*), cudaMemcpyHostToDevice));
     CU_SAFE_CALL(cublas_gemmBatched(GetCublasHandle(),
                             (transB==kTrans? CUBLAS_OP_T:CUBLAS_OP_N),
                             (transA==kTrans? CUBLAS_OP_T:CUBLAS_OP_N),
                             m, n, k, alpha, device_b_array, B[0]->Stride(),
                             device_a_array, A[0]->Stride(), beta,
                             device_c_array, C[0]->Stride(), batchCount));
     CuDevice::Instantiate().Free(device_abc_array);
     delete[] host_abc_array;
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     for (int32 i = 0; i< batchCount; i++) {
       C[i]->Mat().AddMatMat(alpha, A[i]->Mat(), transA, B[i]->Mat(), transB, beta);
     }
   }
 }
friend class CuBlockMatrix< Real > friend
Definition at line 89 of file cu-matrix.h.
friend class CuMatrixBase< double > friend
Definition at line 78 of file cu-matrix.h.
friend class CuMatrixBase< float > friend
Definition at line 77 of file cu-matrix.h.
friend class CuRand< Real > friend
Definition at line 87 of file cu-matrix.h.
friend class CuSparseMatrix< double > friend
Definition at line 91 of file cu-matrix.h.
friend class CuSparseMatrix< float > friend
Definition at line 90 of file cu-matrix.h.
friend class CuSparseMatrix< Real > friend
Definition at line 92 of file cu-matrix.h.
friend class CuSpMatrix< Real > friend
Definition at line 82 of file cu-matrix.h.
friend class CuSubMatrix< Real > friend
Definition at line 86 of file cu-matrix.h.
friend class CuSubVector< Real > friend
Definition at line 88 of file cu-matrix.h.
friend class CuTpMatrix< double > friend
Definition at line 84 of file cu-matrix.h.
friend class CuTpMatrix< float > friend
Definition at line 83 of file cu-matrix.h.
friend class CuVectorBase< double > friend
Definition at line 80 of file cu-matrix.h.
friend class CuVectorBase< float > friend
Definition at line 79 of file cu-matrix.h.
friend class CuVectorBase< Real > friend
Definition at line 85 of file cu-matrix.h.
Real TraceMatMat (const CuMatrixBase< Real > & A, const CuMatrixBase< Real > & B, MatrixTransposeType trans) friend
Definition at line 1755 of file cu-matrix.cc.
Referenced by CuMatrixBase< BaseFloat >::FrobeniusNorm().
{
   if (A.num_rows_ == 0) {
     KALDI_ASSERT(B.num_rows_ == 0);
     return 0.0;
   }
   Real result = 0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (trans == kNoTrans) {
       KALDI_ASSERT(A.NumRows() == B.NumCols() && A.NumCols() == B.NumRows());
     } else {
       KALDI_ASSERT(A.NumRows() == B.NumRows() && A.NumCols() == B.NumCols());
     }
     if (A.NumRows() * A.NumCols() > 16384) {
       // This version in which we don't use a special-purpose kernel, but
       // do AddDiagMat on a temporary vector and returns its sum, seems to be
       // faster for larger matrices.  The cutoff is approximate and
       // we only looked at the time on square matrices, which
       // is what we test in cu-matrix-speed-test.cc.
       CuVector<Real> sum_vec(A.NumRows());
       sum_vec.AddDiagMatMat(1.0, A, kNoTrans,
                             B, trans, 0.0);
       return sum_vec.Sum();
     } else {
       Timer tim;
       // the sizes of result_vec must match what we
       // call the kernels with, in cu-kernels.cu
       CuVector<Real> result_vec(trans == kTrans ? 4 : 2, kUndefined);
       if (trans == kNoTrans) {
         cuda_trace_mat_mat(A.Data(), B.Data(), A.Dim(), B.Stride(), result_vec.Data());
       } else {
         cuda_trace_mat_mat_trans(A.Data(), B.Data(), A.Dim(), B.Stride(), result_vec.Data());
       }
       CU_SAFE_CALL(cudaGetLastError());
       Vector<Real> result_cpu(result_vec); // copying from CUDA faster than summing in CUDA.
       result = result_cpu.Sum();
       CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
     }
   } else
 #endif
   {
     result = TraceMatMat(A.Mat(), B.Mat(), trans);
   }
   return result;
 }
Real TraceMatSmat (const CuMatrixBase< Real > & A, const CuSparseMatrix< Real > & B, MatrixTransposeType trans) friend
Definition at line 300 of file cu-sparse-matrix.cc.
{
   if (A.NumCols() == 0) {
     KALDI_ASSERT(B.NumCols() == 0);
     return 0.0;
   }
   if (B.NumElements() == 0) {
     return 0.0;
   }
   Real result = 0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (trans == kTrans) {
       KALDI_ASSERT(A.NumRows() == B.NumRows() && A.NumCols() == B.NumCols());
     } else {
       KALDI_ASSERT(A.NumCols() == B.NumRows() && A.NumRows() == B.NumCols());
     }
     // The Sum() method in CuVector handles a bunch of logic, we use that to
     // comptue the trace.
     CuVector<Real> sum_vec(B.NumElements());
     Timer tim;
     dim3 dimBlock(CU1DBLOCK, 1);
     dim3 dimGrid(n_blocks(B.NumElements(), CU1DBLOCK), 1);
     if (trans == kNoTrans) {
       cuda_trace_mat_smat(dimGrid, dimBlock, A.Data(), B.Data(),
                           A.Dim(), B.NumElements(), sum_vec.Data());
     } else {
       cuda_trace_mat_smat_trans(dimGrid, dimBlock, A.Data(), B.Data(),
                                 A.Dim(), B.NumElements(), sum_vec.Data());
     }
     result = sum_vec.Sum();
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     result = TraceMatSmat(A.Mat(), B.Mat(), trans);
   }
   return result;
 }
friend class VectorBase< Real > friend
Definition at line 81 of file cu-matrix.h.
Member Data Documentation
Real* data_ protected
GPU data pointer (or regular matrix data pointer,.
if either CUDA was not compiled in or we could not acquire the device).
Definition at line 604 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::AddMatBlocks(), CuMatrixBase< Real >::AddMatMat(), CuMatrixBase< Real >::AddMatMatDivMat(), CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), CuMatrixBase< Real >::ApplySoftMaxPerRow(), CuRand< Real >::BinarizeProbs(), CuMatrixBase< Real >::CopyFromMat(), CuSubMatrix< Real >::CuSubMatrix(), CuMatrixBase< BaseFloat >::Data(), CuMatrixBase< Real >::DiffSigmoid(), CuMatrixBase< Real >::DiffTanh(), CuMatrixBase< Real >::DivElements(), CuMatrixBase< Real >::GroupMax(), CuMatrixBase< Real >::GroupPnorm(), CuMatrixBase< Real >::Max(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsGroupMat(), CuMatrixBase< BaseFloat >::operator()(), CuRand< Real >::RandGaussian(), CuRand< Real >::RandUniform(), CuMatrixBase< BaseFloat >::Row(), CuMatrixBase< BaseFloat >::RowData(), CuMatrixBase< Real >::Sigmoid(), CuMatrixBase< Real >::SoftHinge(), CuMatrixBase< Real >::SumColumnRanges(), CuMatrix< Real >::Swap(), CuMatrixBase< Real >::SymAddMat2(), and CuMatrixBase< Real >::Tanh().
MatrixIndexT num_cols_ protected
Definition at line 612 of file cu-matrix.h.
Referenced by CuRand< Real >::AddGaussNoise(), CuMatrixBase< Real >::AddMatMatDivMat(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), CuMatrixBase< Real >::ApplySoftMaxPerRow(), CuRand< Real >::BinarizeProbs(), CuSubMatrix< Real >::CuSubMatrix(), CuMatrixBase< BaseFloat >::Dim(), CuMatrixBase< BaseFloat >::NumCols(), CuMatrixBase< BaseFloat >::operator()(), CuRand< Real >::RandGaussian(), CuRand< Real >::RandUniform(), CuMatrixBase< BaseFloat >::RowRange(), CuMatrix< Real >::Swap(), and CuMatrixBase< Real >::SymAddMat2().
MatrixIndexT num_rows_ protected
Definition at line 613 of file cu-matrix.h.
Referenced by CuRand< Real >::AddGaussNoise(), CuMatrixBase< Real >::AddMatMatDivMat(), CuMatrixBase< Real >::ApplyLogSoftMaxPerRow(), CuMatrixBase< Real >::ApplySoftMaxPerRow(), CuRand< Real >::BinarizeProbs(), CuMatrixBase< BaseFloat >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), CuSubMatrix< Real >::CuSubMatrix(), CuMatrixBase< BaseFloat >::Dim(), CuMatrixBase< BaseFloat >::NumRows(), CuMatrixBase< BaseFloat >::operator()(), CuRand< Real >::RandGaussian(), CuRand< Real >::RandUniform(), CuMatrixBase< BaseFloat >::Row(), CuMatrixBase< BaseFloat >::SizeInBytes(), CuMatrix< Real >::Swap(), CuMatrixBase< Real >::SymAddMat2(), and kaldi::TraceMatMat().
MatrixIndexT stride_ protected
Definition at line 614 of file cu-matrix.h.
Referenced by CuMatrixBase< Real >::AddRowRanges(), CuRand< Real >::BinarizeProbs(), CuSubMatrix< Real >::CuSubMatrix(), CuMatrixBase< BaseFloat >::Dim(), CuMatrixBase< BaseFloat >::operator()(), CuMatrixBase< BaseFloat >::Row(), CuMatrixBase< BaseFloat >::RowData(), CuMatrixBase< BaseFloat >::SizeInBytes(), CuMatrixBase< BaseFloat >::Stride(), CuMatrixBase< Real >::SumColumnRanges(), and CuMatrix< Real >::Swap().
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-matrix.h
cudamatrix/cu-matrix.cc