Kaldi: TableWriterBothImpl< Holder > Class Template Reference
TableWriterBothImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from TableWriterImplBase< Holder >
typedef Holder::T T
Public Member Functions
virtual bool Open (const std::string &wspecifier)
virtual bool IsOpen () const
void MakeFilename (typename std::ostream::pos_type streampos, std::string *output) const
virtual bool Write (const std::string &key, const T &value)
virtual void Flush ()
virtual bool Close ()
TableWriterBothImpl ()
virtual ~TableWriterBothImpl ()
Public Member Functions inherited from TableWriterImplBase< Holder >
virtual ~TableWriterImplBase ()
TableWriterImplBase ()
Private Types
enum { kUninitialized, kOpen, kWriteError }
Private Attributes
Output archive_output_
Output script_output_
WspecifierOptions opts_
std::string archive_wxfilename_
std::string script_wxfilename_
std::string wspecifier_
enum
kaldi::TableWriterBothImpl:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::TableWriterBothImpl< Holder >
Definition at line 956 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef Holder::T T
Definition at line 958 of file kaldi-table-inl.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kUninitialized
kOpen
kWriteError
Definition at line 1127 of file kaldi-table-inl.h.
        {               // is stream open?
     kUninitialized,    // no
     kOpen,             // yes
     kWriteError,       // yes
   } state_;
Constructor & Destructor Documentation
TableWriterBothImpl () inline
Definition at line 1109 of file kaldi-table-inl.h.
 : state_(kUninitialized) {}
virtual ~TableWriterBothImpl () inline virtual
Definition at line 1113 of file kaldi-table-inl.h.
References TableWriterBothImpl< Holder >::Close(), TableWriterBothImpl< Holder >::IsOpen(), KALDI_ERR, and TableWriterBothImpl< Holder >::wspecifier_.
{
     if (!IsOpen()) return;
     else if (!Close())
       KALDI_ERR << "At TableWriter destructor: Write failed or stream close"
                    " failed: " << wspecifier_;
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 1096 of file kaldi-table-inl.h.
References TableWriterBothImpl< Holder >::archive_output_, Output::Close(), Output::IsOpen(), TableWriterBothImpl< Holder >::IsOpen(), KALDI_ERR, TableWriterBothImpl< Holder >::kUninitialized, TableWriterBothImpl< Holder >::kWriteError, TableWriterBothImpl< Holder >::script_output_, and TableWriterBothImpl< Holder >::state_.
Referenced by TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::~TableWriterBothImpl().
{
     if (!this->IsOpen())
       KALDI_ERR << "TableWriter: Close called on a stream that was not open.";
     bool close_success = true;
     if (archive_output_.IsOpen())
       if (!archive_output_.Close()) close_success = false;
     if (script_output_.IsOpen())
       if (!script_output_.Close()) close_success = false;
     bool ans = close_success && (state_ != kWriteError);
     state_ = kUninitialized;
     return ans;
   }
virtual void Flush () inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 1085 of file kaldi-table-inl.h.
References TableWriterBothImpl< Holder >::archive_output_, KALDI_WARN, TableWriterBothImpl< Holder >::kOpen, TableWriterBothImpl< Holder >::kWriteError, TableWriterBothImpl< Holder >::script_output_, TableWriterBothImpl< Holder >::state_, and Output::Stream().
Referenced by TableWriterBothImpl< Holder >::Write().
{
     switch (state_) {
       case kWriteError: case kOpen:
         archive_output_.Stream().flush();  // Don't check error status.
         script_output_.Stream().flush();  // Don't check error status.
         return;
       default:
         KALDI_WARN << "TableWriter: Flush called on not-open writer.";
     }
   }
virtual bool IsOpen () const inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 1000 of file kaldi-table-inl.h.
References KALDI_ERR, TableWriterBothImpl< Holder >::kOpen, TableWriterBothImpl< Holder >::kUninitialized, TableWriterBothImpl< Holder >::kWriteError, and TableWriterBothImpl< Holder >::state_.
Referenced by TableWriterBothImpl< Holder >::Close(), and TableWriterBothImpl< Holder >::~TableWriterBothImpl().
{
     switch (state_) {
       case kUninitialized: return false;
       case kOpen: case kWriteError: return true;
       default: KALDI_ERR << "IsOpen() called on TableWriter in invalid state.";
     }
     return false;
   }
void MakeFilename (typename std::ostream::pos_type streampos, std::string * output) const inline
Definition at line 1009 of file kaldi-table-inl.h.
References TableWriterBothImpl< Holder >::archive_wxfilename_, and KALDI_ASSERT.
Referenced by TableWriterBothImpl< Holder >::Write().
{
     std::ostringstream ss;
     ss << ':' << streampos;
     KALDI_ASSERT(ss.str() != ":-1");
     *output = archive_wxfilename_ + ss.str();
     // e.g. /some/file:12302.
     // Note that we warned if archive_wxfilename_ is not an actual filename;
     // the philosophy is we give the user rope and if they want to hang
     // themselves, with it, fine.
   }
virtual bool Open (const std::string & wspecifier) inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 960 of file kaldi-table-inl.h.
References TableWriterBothImpl< Holder >::archive_output_, TableWriterBothImpl< Holder >::archive_wxfilename_, WspecifierOptions::binary, kaldi::ClassifyWspecifier(), kaldi::ClassifyWxfilename(), Output::Close(), TableWriterBothImpl< Holder >::Close(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, kaldi::kBothWspecifier, kaldi::kFileOutput, TableWriterBothImpl< Holder >::kOpen, TableWriterBothImpl< Holder >::kUninitialized, TableWriterBothImpl< Holder >::kWriteError, Output::Open(), TableWriterBothImpl< Holder >::opts_, TableWriterBothImpl< Holder >::script_output_, TableWriterBothImpl< Holder >::script_wxfilename_, TableWriterBothImpl< Holder >::state_, and TableWriterBothImpl< Holder >::wspecifier_.
{
     switch (state_) {
       case kUninitialized:
         break;
       case kWriteError:
         KALDI_ERR << "TableWriter: opening stream, already open with write"
                      " error.";
       case kOpen: default:
         if (!Close())  // throw because this error may not have been previously
                        // detected by user.
           KALDI_ERR << "TableWriter: opening stream, error closing previously"
                        " open stream.";
     }
     wspecifier_ = wspecifier;
     WspecifierType ws = ClassifyWspecifier(wspecifier,
                                            &archive_wxfilename_,
                                            &script_wxfilename_,
                                            &opts_);
     KALDI_ASSERT(ws == kBothWspecifier);  // or wrongly called.
     if (ClassifyWxfilename(archive_wxfilename_) != kFileOutput)
       KALDI_WARN << "When writing to both archive and script, the script file "
           "will generally not be interpreted correctly unless the archive is "
           "an actual file: wspecifier = " << wspecifier;
     if (!archive_output_.Open(archive_wxfilename_, opts_.binary, false)) {
       // false means no binary header.
       state_ = kUninitialized;
       return false;
     }
     if (!script_output_.Open(script_wxfilename_, false, false)) {  // first
       // false means text mode: script files always text-mode.   second false
       //  means don't write header (doesn't matter for text mode).
       archive_output_.Close();  // Don't care about status: error anyway.
       state_ = kUninitialized;
       return false;
     }
     state_ = kOpen;
     return true;
   }
virtual bool Write (const std::string & key, const T & value) inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 1024 of file kaldi-table-inl.h.
References TableWriterBothImpl< Holder >::archive_output_, TableWriterBothImpl< Holder >::archive_wxfilename_, WspecifierOptions::binary, WspecifierOptions::flush, TableWriterBothImpl< Holder >::Flush(), kaldi::IsToken(), KALDI_ERR, KALDI_WARN, TableWriterBothImpl< Holder >::kOpen, TableWriterBothImpl< Holder >::kUninitialized, TableWriterBothImpl< Holder >::kWriteError, TableWriterBothImpl< Holder >::MakeFilename(), TableWriterBothImpl< Holder >::opts_, kaldi::PrintableWxfilename(), TableWriterBothImpl< Holder >::script_output_, TableWriterBothImpl< Holder >::script_wxfilename_, TableWriterBothImpl< Holder >::state_, and Output::Stream().
{
     switch (state_) {
       case kOpen: break;
       case kWriteError:
         // user should have known from the last
         // call to Write that there was a problem.  Warn about it.
         KALDI_WARN << "TableWriter: writing to non-open TableWriter object.";
         return false;
       case kUninitialized: default:
         KALDI_ERR << "TableWriter: Write called on invalid stream";
     }
     // state is now kOpen or kWriteError.
     if (!IsToken(key))  // e.g. empty string or has spaces...
       KALDI_ERR << "TableWriter: using invalid key " << key;
     std::ostream &archive_os = archive_output_.Stream();
     archive_os << key << ' ';
     typename std::ostream::pos_type archive_os_pos = archive_os.tellp();
     // position at start of Write() to archive.  We will record this in the
     // script file.
     std::string offset_rxfilename;  // rxfilename with offset into the archive,
     // e.g. some_archive_name.ark:431541423
     MakeFilename(archive_os_pos, &offset_rxfilename);
     // Write to the script file first.
     // The idea is that we want to get all the information possible into the
     // script file, to make it easier to unwind errors later.
     std::ostream &script_os = script_output_.Stream();
     script_output_.Stream() << key << ' ' << offset_rxfilename << '\n';
     if (!Holder::Write(archive_output_.Stream(), opts_.binary, value)) {
       KALDI_WARN << "TableWriter: write failure to"
                  << PrintableWxfilename(archive_wxfilename_);
       state_ = kWriteError;
       return false;
     }
     if (script_os.fail()) {
       KALDI_WARN << "TableWriter: write failure to script file detected: "
                  << PrintableWxfilename(script_wxfilename_);
       state_ = kWriteError;
       return false;
     }
     if (archive_os.fail()) {
       KALDI_WARN << "TableWriter: write failure to archive file detected: "
                  << PrintableWxfilename(archive_wxfilename_);
       state_ = kWriteError;
       return false;
     }
     if (state_ == kWriteError) return false;  // Even if this Write seems to
     // have succeeded, we fail because a previous Write failed and the archive
     // may be corrupted and unreadable.
     if (opts_.flush)
       Flush();
     return true;
   }
Member Data Documentation
Output archive_output_ private
Definition at line 1121 of file kaldi-table-inl.h.
Referenced by TableWriterBothImpl< Holder >::Close(), TableWriterBothImpl< Holder >::Flush(), TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::Write().
std::string archive_wxfilename_ private
Definition at line 1124 of file kaldi-table-inl.h.
Referenced by TableWriterBothImpl< Holder >::MakeFilename(), TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::Write().
WspecifierOptions opts_ private
Definition at line 1123 of file kaldi-table-inl.h.
Referenced by TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::Write().
Output script_output_ private
Definition at line 1122 of file kaldi-table-inl.h.
Referenced by TableWriterBothImpl< Holder >::Close(), TableWriterBothImpl< Holder >::Flush(), TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::Write().
std::string script_wxfilename_ private
Definition at line 1125 of file kaldi-table-inl.h.
Referenced by TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::Write().
enum { ... } state_
Referenced by TableWriterBothImpl< Holder >::Close(), TableWriterBothImpl< Holder >::Flush(), TableWriterBothImpl< Holder >::IsOpen(), TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::Write().
std::string wspecifier_ private
Definition at line 1126 of file kaldi-table-inl.h.
Referenced by TableWriterBothImpl< Holder >::Open(), and TableWriterBothImpl< Holder >::~TableWriterBothImpl().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h