Kaldi: KaldiErrorMessage Class Reference
KaldiErrorMessage Class Reference
"Functions relating to logging and error reporting"
#include <kaldi-error.h>
Public Member Functions
KaldiErrorMessage (const char *func, const char *file, int32 line)
std::ostream & stream ()
~KaldiErrorMessage () KALDI_NOEXCEPT(false)
Private Attributes
std::ostringstream ss_
Detailed Description
Definition at line 105 of file kaldi-error.h.
Constructor & Destructor Documentation
KaldiErrorMessage (const char * func, const char * file, int32 line)
Definition at line 184 of file kaldi-error.cc.
References kaldi::GetProgramName(), kaldi::GetShortFileName(), and KaldiErrorMessage::stream().
{
   this->stream() << "ERROR (" << GetProgramName() << func << "():"
                  << GetShortFileName(file) << ':' << line << ") ";
 }
~KaldiErrorMessage ()
Definition at line 190 of file kaldi-error.cc.
References KaldiErrorMessage::ss_.
{
   std::string str = ss_.str();
   while (!str.empty() && str[str.length() - 1] == '\n')
     str.resize(str.length() - 1);
   // (1) Print the message to stderr.
   fprintf(stderr, "%s\n", str.c_str());
   // (2) Throw an exception with the message, plus traceback info if available.
   if (!std::uncaught_exception()) {
 #ifdef HAVE_EXECINFO_H
     throw std::runtime_error(str + "\n\n[stack trace: ]\n" +
                              KaldiGetStackTrace() + "\n");
 #else
     throw std::runtime_error(str);
 #endif
   } else {
     abort();  // This may be temporary...
   }
 }
Member Function Documentation
std::ostream& stream () inline
Definition at line 108 of file kaldi-error.h.
References KaldiErrorMessage::ss_.
Referenced by KaldiErrorMessage::KaldiErrorMessage().
 { return ss_; }
Member Data Documentation
std::ostringstream ss_ private
Definition at line 111 of file kaldi-error.h.
Referenced by KaldiErrorMessage::stream(), and KaldiErrorMessage::~KaldiErrorMessage().
The documentation for this class was generated from the following files:
base/kaldi-error.h
base/kaldi-error.cc