Kaldi: PermuteComponent Class Reference
PermuteComponent Class Reference
PermuteComponent does a permutation of the dimensions (by default, a fixed random permutation, but it may be specified).
#include <nnet-component.h>
Public Member Functions
void Init (int32 dim)
void Init (const std::vector< int32 > &reorder)
PermuteComponent (int32 dim)
PermuteComponent (const std::vector< int32 > &reorder)
PermuteComponent ()
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual Component * Copy () const
Copy component (deep copy).
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Type () const
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual std::string Info () const
virtual ~Component ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (PermuteComponent)
Private Attributes
std::vector< int32 > reorder_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
PermuteComponent does a permutation of the dimensions (by default, a fixed random permutation, but it may be specified).
Useful in conjunction with block-diagonal transforms.
Definition at line 1320 of file nnet-component.h.
Constructor & Destructor Documentation
PermuteComponent (int32 dim) inline
Definition at line 1324 of file nnet-component.h.
References PermuteComponent::Init().
 { Init(dim); }
PermuteComponent (const std::vector< int32 > & reorder) inline
Definition at line 1325 of file nnet-component.h.
References PermuteComponent::Init().
 { Init(reorder); }
PermuteComponent () inline
Definition at line 1327 of file nnet-component.h.
Referenced by PermuteComponent::Copy().
 { } // e.g. prior to Read() or Init()
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 2403 of file nnet-component.cc.
References CuMatrixBase< Real >::CopyCols(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), PermuteComponent::OutputDim(), PermuteComponent::reorder_, and CuMatrix< Real >::Resize().
{
   in_deriv->Resize(out_deriv.NumRows(), out_deriv.NumCols());
   KALDI_ASSERT(out_deriv.NumCols() == OutputDim());
   // Note: if we were actually using this component type we could make the
   // CuArray a member variable for efficiency.
   CuArray<int32> cu_reorder(reorder_);
   in_deriv->CopyCols(out_deriv, cu_reorder);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1337 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1338 of file nnet-component.h.
 { return false; }
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 290 of file nnet-component.cc.
References PermuteComponent::PermuteComponent(), and PermuteComponent::reorder_.
{
   PermuteComponent *ans = new PermuteComponent();
   ans->reorder_ = reorder_;
   return ans;
 }
void Init (int32 dim)
Definition at line 2369 of file nnet-component.cc.
References rnnlm::i, KALDI_ASSERT, and PermuteComponent::reorder_.
Referenced by PermuteComponent::InitFromString(), and PermuteComponent::PermuteComponent().
{
   KALDI_ASSERT(dim > 0);
   reorder_.resize(dim);
   for (int32 i = 0; i < dim; i++) reorder_[i] = i;
   std::random_shuffle(reorder_.begin(), reorder_.end());
 }
void Init (const std::vector< int32 > & reorder)
Definition at line 295 of file nnet-component.cc.
References rnnlm::i, KALDI_ASSERT, and PermuteComponent::reorder_.
{
   reorder_ = reorder;
   KALDI_ASSERT(!reorder.empty());
   std::vector<int32> indexes(reorder);
   std::sort(indexes.begin(), indexes.end());
   for (int32 i = 0; i < static_cast<int32>(indexes.size()); i++)
     KALDI_ASSERT(i == indexes[i] && "Not a permutation");
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 2376 of file nnet-component.cc.
References PermuteComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), and PermuteComponent::Type().
{
   std::string orig_args(args);
   int32 dim;
   bool ok = ParseFromString("dim", &args, &dim);
   if (!ok || !args.empty() || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   Init(dim);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1329 of file nnet-component.h.
References PermuteComponent::reorder_.
 { return reorder_.size(); }
KALDI_DISALLOW_COPY_AND_ASSIGN (PermuteComponent) private
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1330 of file nnet-component.h.
References PermuteComponent::reorder_.
Referenced by PermuteComponent::Backprop().
 { return reorder_.size(); }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 2386 of file nnet-component.cc.
References ChunkInfo::CheckSize(), CuMatrixBase< Real >::CopyCols(), rnnlm::i, KALDI_ASSERT, ChunkInfo::NumChunks(), and PermuteComponent::reorder_.
{
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   std::vector<int32> reverse_reorder(reorder_.size());
   for (size_t i = 0; i < reorder_.size(); i++)
     reverse_reorder[reorder_[i]] = i;
   // Note: if we were actually using this component type we could make the
   // CuArray a member variable for efficiency.
   CuArray<int32> cu_reverse_reorder(reverse_reorder);
   out->CopyCols(in, cu_reverse_reorder);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 2356 of file nnet-component.cc.
References kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), kaldi::ReadIntegerVector(), and PermuteComponent::reorder_.
{
   ExpectOneOrTwoTokens(is, binary, "<PermuteComponent>", "<Reorder>");
   ReadIntegerVector(is, binary, &reorder_);
   ExpectToken(is, binary, "</PermuteComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1336 of file nnet-component.h.
Referenced by PermuteComponent::InitFromString().
 { return "PermuteComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 2362 of file nnet-component.cc.
References PermuteComponent::reorder_, kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<PermuteComponent>");
   WriteToken(os, binary, "<Reorder>");
   WriteIntegerVector(os, binary, reorder_);
   WriteToken(os, binary, "</PermuteComponent>");
 }
Member Data Documentation
std::vector<int32> reorder_ private
Definition at line 1354 of file nnet-component.h.
Referenced by PermuteComponent::Backprop(), PermuteComponent::Copy(), PermuteComponent::Init(), PermuteComponent::InputDim(), PermuteComponent::OutputDim(), PermuteComponent::Propagate(), PermuteComponent::Read(), and PermuteComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc