Kaldi: AddShift Class Reference
AddShift Class Reference
Adds shift to all the lines of the matrix (can be used for global mean normalization)
#include <nnet-various.h>
Public Member Functions
AddShift (int32 dim_in, int32 dim_out)
~AddShift ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
const CuVectorBase< BaseFloat > & GetShiftVec ()
void SetShiftVec (const CuVectorBase< BaseFloat > &shift_data)
void SetLearnRateCoef (float c)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Sets the training options to the component.
const NnetTrainOptions & GetTrainOptions () const
Gets the training options from the component.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
Protected Attributes
CuVector< BaseFloat > shift_data_
CuVector< BaseFloat > shift_data_grad_
BaseFloat learn_rate_coef_
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Detailed Description
Adds shift to all the lines of the matrix (can be used for global mean normalization)
Definition at line 340 of file nnet-various.h.
Constructor & Destructor Documentation
AddShift (int32 dim_in, int32 dim_out) inline
Definition at line 342 of file nnet-various.h.
Referenced by AddShift::Copy().
     : UpdatableComponent(dim_in, dim_out), shift_data_(dim_in), learn_rate_coef_(1.0)
   { }
~AddShift () inline
Definition at line 345 of file nnet-various.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 407 of file nnet-various.h.
References CuMatrixBase< Real >::CopyFromMat().
{
     //derivative of additive constant is zero...
     in_diff->CopyFromMat(out_diff);
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 348 of file nnet-various.h.
References AddShift::AddShift().
 { return new AddShift(*this); }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 387 of file nnet-various.h.
References CuVectorBase< Real >::CopyToVec(), Component::InputDim(), Vector< Real >::Resize(), and AddShift::shift_data_.
Referenced by kaldi::ConvertAddShiftComponent().
{
     wei_copy->Resize(InputDim());
     shift_data_.CopyToVec(wei_copy);
   }
const CuVectorBase<BaseFloat>& GetShiftVec () inline
Definition at line 424 of file nnet-various.h.
References AddShift::shift_data_.
{
     return shift_data_;
   }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 349 of file nnet-various.h.
References Component::kAddShift.
 { return kAddShift; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 392 of file nnet-various.h.
References kaldi::nnet1::MomentStatistics(), and AddShift::shift_data_.
{
     return std::string("\n  shift_data") + MomentStatistics(shift_data_);
   }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 396 of file nnet-various.h.
References AddShift::learn_rate_coef_, kaldi::nnet1::MomentStatistics(), AddShift::shift_data_grad_, and kaldi::nnet1::ToString().
{
     return std::string("\n  shift_data_grad") + MomentStatistics(shift_data_grad_) +
            ", lr-coef " + ToString(learn_rate_coef_);
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 351 of file nnet-various.h.
References Component::InputDim(), KALDI_ERR, kaldi::kSetZero, AddShift::learn_rate_coef_, kaldi::ReadBasicType(), kaldi::ReadToken(), CuVector< Real >::Resize(), CuVectorBase< Real >::Set(), and AddShift::shift_data_.
{
     // define options
     float init_param = 0.0;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<InitParam>") ReadBasicType(is, false, &init_param);
       else if (token == "<LearnRateCoef>") ReadBasicType(is, false, &learn_rate_coef_);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (InitParam)";
       is >> std::ws; // eat-up whitespace
     }
     // initialize
     shift_data_.Resize(InputDim(), kSetZero); // set to zero
     shift_data_.Set(init_param);
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 385 of file nnet-various.h.
References CuVectorBase< Real >::Dim(), and AddShift::shift_data_.
 { return shift_data_.Dim(); }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 401 of file nnet-various.h.
References CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::CopyFromMat(), and AddShift::shift_data_.
{
     out->CopyFromMat(in);
     //add the shift
     out->AddVecToRows(1.0, shift_data_, 1.0);
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 369 of file nnet-various.h.
References kaldi::ExpectToken(), AddShift::learn_rate_coef_, kaldi::Peek(), CuVector< Real >::Read(), kaldi::ReadBasicType(), and AddShift::shift_data_.
{
     // optional learning-rate coef,
     if ('<' == Peek(is, binary)) {
       ExpectToken(is, binary, "<LearnRateCoef>");
       ReadBasicType(is, binary, &learn_rate_coef_);
     }
     // read the shift data
     shift_data_.Read(is, binary);
   }
void SetLearnRateCoef (float c) inline
Definition at line 431 of file nnet-various.h.
References AddShift::learn_rate_coef_.
Referenced by main().
{
     learn_rate_coef_ = c;
   }
void SetShiftVec (const CuVectorBase< BaseFloat > & shift_data) inline
Definition at line 427 of file nnet-various.h.
References CuVectorBase< Real >::CopyFromVec(), CuVectorBase< Real >::Dim(), KALDI_ASSERT, and AddShift::shift_data_.
Referenced by main().
{
     KALDI_ASSERT(shift_data.Dim() == shift_data_.Dim());
     shift_data_.CopyFromVec(shift_data);
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 413 of file nnet-various.h.
References CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), Component::InputDim(), kaldi::kSetZero, NnetTrainOptions::learn_rate, AddShift::learn_rate_coef_, UpdatableComponent::opts_, CuVector< Real >::Resize(), AddShift::shift_data_, and AddShift::shift_data_grad_.
{
     // we use following hyperparameters from the option class
     const BaseFloat lr = opts_.learn_rate;
     // gradient
     shift_data_grad_.Resize(InputDim(), kSetZero); // reset
     shift_data_grad_.AddRowSumMat(1.0, diff, 0.0);
     // update
     shift_data_.AddVec(-lr*learn_rate_coef_, shift_data_grad_);
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 379 of file nnet-various.h.
References AddShift::learn_rate_coef_, AddShift::shift_data_, CuVector< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<LearnRateCoef>");
     WriteBasicType(os, binary, learn_rate_coef_);
     shift_data_.Write(os, binary);
   }
Member Data Documentation
BaseFloat learn_rate_coef_ protected
Definition at line 438 of file nnet-various.h.
Referenced by AddShift::InfoGradient(), AddShift::InitData(), AddShift::ReadData(), AddShift::SetLearnRateCoef(), AddShift::Update(), and AddShift::WriteData().
CuVector<BaseFloat> shift_data_ protected
Definition at line 436 of file nnet-various.h.
Referenced by AddShift::GetParams(), AddShift::GetShiftVec(), AddShift::Info(), AddShift::InitData(), AddShift::NumParams(), AddShift::PropagateFnc(), AddShift::ReadData(), AddShift::SetShiftVec(), AddShift::Update(), and AddShift::WriteData().
CuVector<BaseFloat> shift_data_grad_ protected
Definition at line 437 of file nnet-various.h.
Referenced by AddShift::InfoGradient(), and AddShift::Update().
The documentation for this class was generated from the following file:
nnet/nnet-various.h