Kaldi: Fbank Class Reference
Fbank Class Reference
FeatureExtraction
Class for computing mel-filterbank features; see Computing MFCC features for more information.
#include <feature-fbank.h>
Public Types
typedef FbankOptions Options
Public Member Functions
Fbank (const FbankOptions &opts)
~Fbank ()
int32 Dim () const
void Compute (const VectorBase< BaseFloat > &wave, BaseFloat vtln_warp, Matrix< BaseFloat > *output, Vector< BaseFloat > *wave_remainder=NULL)
Will throw exception on failure (e.g.
void Compute (const VectorBase< BaseFloat > &wave, BaseFloat vtln_warp, Matrix< BaseFloat > *output, Vector< BaseFloat > *wave_remainder=NULL) const
Const version of Compute()
Private Member Functions
void ComputeInternal (const VectorBase< BaseFloat > &wave, const MelBanks &mel_banks, Matrix< BaseFloat > *output, Vector< BaseFloat > *wave_remainder=NULL) const
const MelBanks * GetMelBanks (BaseFloat vtln_warp)
const MelBanks * GetMelBanks (BaseFloat vtln_warp, bool *must_delete) const
KALDI_DISALLOW_COPY_AND_ASSIGN (Fbank)
Private Attributes
FbankOptions opts_
BaseFloat log_energy_floor_
std::map< BaseFloat, MelBanks * > mel_banks_
FeatureWindowFunction feature_window_function_
SplitRadixRealFft< BaseFloat > * srfft_
Detailed Description
Class for computing mel-filterbank features; see Computing MFCC features for more information.
Definition at line 78 of file feature-fbank.h.
Member Typedef Documentation
typedef FbankOptions Options
Definition at line 101 of file feature-fbank.h.
Constructor & Destructor Documentation
Fbank (const FbankOptions & opts) explicit
Definition at line 26 of file feature-fbank.cc.
References FbankOptions::energy_floor, FbankOptions::frame_opts, Fbank::GetMelBanks(), kaldi::Log(), Fbank::log_energy_floor_, FrameExtractionOptions::PaddedWindowSize(), and Fbank::srfft_.
     : opts_(opts), feature_window_function_(opts.frame_opts), srfft_(NULL) {
   if (opts.energy_floor > 0.0)
     log_energy_floor_ = Log(opts.energy_floor);
   int32 padded_window_size = opts.frame_opts.PaddedWindowSize();
   if ((padded_window_size & (padded_window_size-1)) == 0)  // Is a power of two...
     srfft_ = new SplitRadixRealFft<BaseFloat>(padded_window_size);
   // We'll definitely need the filterbanks info for VTLN warping factor 1.0.
   // [note: this call caches it.]  The reason we call this here is to
   // improve the efficiency of the "const" version of Compute().
   GetMelBanks(1.0);
 }
~Fbank ()
Definition at line 41 of file feature-fbank.cc.
References Fbank::mel_banks_, and Fbank::srfft_.
               {
   for (std::map<BaseFloat, MelBanks*>::iterator iter = mel_banks_.begin();
       iter != mel_banks_.end();
       ++iter) {
     delete iter->second;
   }
   delete srfft_;
 }
Member Function Documentation
void Compute (const VectorBase< BaseFloat > & wave, BaseFloat vtln_warp, Matrix< BaseFloat > * output, Vector< BaseFloat > * wave_remainder = NULL)
Will throw exception on failure (e.g.
if file too short for even one frame). The output "wave_remainder" is the last frame or two of the waveform that it would be necessary to include in the next call to Compute for the same utterance. It is not exactly the un-processed part (it may have been partly processed), it's the start of the next window that we have not already processed.
Definition at line 81 of file feature-fbank.cc.
References Fbank::ComputeInternal(), and Fbank::GetMelBanks().
Referenced by main(), UnitTestHTKCompare1(), UnitTestHTKCompare2(), UnitTestHTKCompare3(), UnitTestHTKCompare4(), and UnitTestSimple().
{
   const MelBanks *this_mel_banks = GetMelBanks(vtln_warp);
   ComputeInternal(wave, *this_mel_banks, output, wave_remainder);
 }
void Compute (const VectorBase< BaseFloat > & wave, BaseFloat vtln_warp, Matrix< BaseFloat > * output, Vector< BaseFloat > * wave_remainder = NULL) const
Const version of Compute()
Definition at line 89 of file feature-fbank.cc.
References Fbank::ComputeInternal(), and Fbank::GetMelBanks().
{
   bool must_delete_mel_banks;
   const MelBanks *mel_banks = GetMelBanks(vtln_warp,
                                           &must_delete_mel_banks);
   ComputeInternal(wave, *mel_banks, output, wave_remainder);
   if (must_delete_mel_banks)
     delete mel_banks;
 }
void ComputeInternal (const VectorBase< BaseFloat > & wave, const MelBanks & mel_banks, Matrix< BaseFloat > * output, Vector< BaseFloat > * wave_remainder = NULL) const private
Definition at line 104 of file feature-fbank.cc.
References VectorBase< Real >::ApplyFloor(), VectorBase< Real >::ApplyLog(), MelBanks::Compute(), SplitRadixRealFft< Real >::Compute(), kaldi::ComputePowerSpectrum(), VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), FbankOptions::energy_floor, kaldi::ExtractWaveformRemainder(), kaldi::ExtractWindow(), Fbank::feature_window_function_, FbankOptions::frame_opts, FbankOptions::htk_compat, rnnlm::i, KALDI_ASSERT, kaldi::Log(), Fbank::log_energy_floor_, FbankOptions::mel_opts, MelBanksOptions::num_bins, kaldi::NumFrames(), Fbank::opts_, FbankOptions::raw_energy, kaldi::RealFft(), Matrix< Real >::Resize(), MatrixBase< Real >::Row(), Fbank::srfft_, FbankOptions::use_energy, FbankOptions::use_log_fbank, and kaldi::VecVec().
Referenced by Fbank::Compute().
{
   KALDI_ASSERT(output != NULL);
   // Get dimensions of output features
   int32 rows_out = NumFrames(wave.Dim(), opts_.frame_opts);
   int32 cols_out = opts_.mel_opts.num_bins + opts_.use_energy;
   if (rows_out == 0) {
     output->Resize(0, 0);
     if (wave_remainder != NULL)
       *wave_remainder = wave;
     return;
   }
   // Prepare the output buffer
   output->Resize(rows_out, cols_out);
   // Optionally extract the remainder for further processing
   if (wave_remainder != NULL)
     ExtractWaveformRemainder(wave, opts_.frame_opts, wave_remainder);
   // Buffers
   Vector<BaseFloat> window;  // windowed waveform.
   Vector<BaseFloat> mel_energies;
   std::vector<BaseFloat> temp_buffer;  // used by srfft.
   BaseFloat log_energy;
   // Compute all the freames, r is frame index..
   for (int32 r = 0; r < rows_out; r++) {
     // Cut the window, apply window function
     ExtractWindow(wave, r, opts_.frame_opts, feature_window_function_, &window,
                   (opts_.use_energy && opts_.raw_energy ? &log_energy : NULL));
     // Compute energy after window function (not the raw one)
     if (opts_.use_energy && !opts_.raw_energy)
       log_energy = Log(std::max(VecVec(window, window),
                                 std::numeric_limits<BaseFloat>::min()));
     if (srfft_ != NULL)  // Compute FFT using split-radix algorithm.
       srfft_->Compute(window.Data(), true, &temp_buffer);
     else  // An alternative algorithm that works for non-powers-of-two.
       RealFft(&window, true);
     // Convert the FFT into a power spectrum.
     ComputePowerSpectrum(&window);
     SubVector<BaseFloat> power_spectrum(window, 0, window.Dim()/2 + 1);
     // Sum with MelFiterbank over power spectrum
     mel_banks.Compute(power_spectrum, &mel_energies);
     if (opts_.use_log_fbank) {
       // avoid log of zero (which should be prevented anyway by dithering).
       mel_energies.ApplyFloor(std::numeric_limits<BaseFloat>::min());
       mel_energies.ApplyLog();  // take the log.
     }
     // Output buffers
     SubVector<BaseFloat> this_output(output->Row(r));
     SubVector<BaseFloat> this_fbank(this_output.Range((opts_.use_energy? 1 : 0),
                                                       opts_.mel_opts.num_bins));
     // Copy to output
     this_fbank.CopyFromVec(mel_energies);
     // Copy energy as first value
     if (opts_.use_energy) {
       if (opts_.energy_floor > 0.0 && log_energy < log_energy_floor_) {
         log_energy = log_energy_floor_;
       }
       this_output(0) = log_energy;
     }
     // HTK compat: Shift features, so energy is last value
     if (opts_.htk_compat && opts_.use_energy) {
       BaseFloat energy = this_output(0);
       for (int32 i = 0; i < opts_.mel_opts.num_bins; i++) {
         this_output(i) = this_output(i+1);
       }
       this_output(opts_.mel_opts.num_bins) = energy;
     }
   }
 }
int32 Dim () const inline
Definition at line 83 of file feature-fbank.h.
References FbankOptions::mel_opts, MelBanksOptions::num_bins, and Fbank::opts_.
 { return opts_.mel_opts.num_bins; }
const MelBanks * GetMelBanks (BaseFloat vtln_warp) private
Definition at line 50 of file feature-fbank.cc.
References FbankOptions::frame_opts, Fbank::mel_banks_, FbankOptions::mel_opts, and Fbank::opts_.
Referenced by Fbank::Compute(), and Fbank::Fbank().
{
   MelBanks *this_mel_banks = NULL;
   std::map<BaseFloat, MelBanks*>::iterator iter = mel_banks_.find(vtln_warp);
   if (iter == mel_banks_.end()) {
     this_mel_banks = new MelBanks(opts_.mel_opts,
                                   opts_.frame_opts,
                                   vtln_warp);
     mel_banks_[vtln_warp] = this_mel_banks;
   } else {
     this_mel_banks = iter->second;
   }
   return this_mel_banks;
 }
const MelBanks * GetMelBanks (BaseFloat vtln_warp, bool * must_delete) const private
Definition at line 64 of file feature-fbank.cc.
References FbankOptions::frame_opts, Fbank::mel_banks_, FbankOptions::mel_opts, and Fbank::opts_.
{
   MelBanks *this_mel_banks = NULL;
   std::map<BaseFloat, MelBanks*>::const_iterator iter =
       mel_banks_.find(vtln_warp);
   if (iter == mel_banks_.end()) {
     this_mel_banks = new MelBanks(opts_.mel_opts,
                                   opts_.frame_opts,
                                   vtln_warp);
     *must_delete = true;
   } else {
     this_mel_banks = iter->second;
     *must_delete = false;
   }
   return this_mel_banks;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (Fbank) private
Member Data Documentation
FeatureWindowFunction feature_window_function_ private
Definition at line 116 of file feature-fbank.h.
Referenced by Fbank::ComputeInternal().
BaseFloat log_energy_floor_ private
Definition at line 114 of file feature-fbank.h.
Referenced by Fbank::ComputeInternal(), and Fbank::Fbank().
std::map<BaseFloat, MelBanks*> mel_banks_ private
Definition at line 115 of file feature-fbank.h.
Referenced by Fbank::GetMelBanks(), and Fbank::~Fbank().
FbankOptions opts_ private
Definition at line 113 of file feature-fbank.h.
Referenced by Fbank::ComputeInternal(), Fbank::Dim(), and Fbank::GetMelBanks().
SplitRadixRealFft<BaseFloat>* srfft_ private
Definition at line 117 of file feature-fbank.h.
Referenced by Fbank::ComputeInternal(), Fbank::Fbank(), and Fbank::~Fbank().
The documentation for this class was generated from the following files:
feat/feature-fbank.h
feat/feature-fbank.cc