Kaldi: TidToTstateMapper Class Reference
TidToTstateMapper Class Reference
Public Types
typedef int32 Result
Public Member Functions
TidToTstateMapper (const TransitionModel &trans_model, const std::vector< int32 > &disambig_syms)
int32 operator() (int32 label) const
Private Attributes
const TransitionModel & trans_model_
const std::vector< int32 > & disambig_syms_
Detailed Description
Definition at line 409 of file hmm-utils.cc.
Member Typedef Documentation
typedef int32 Result
Definition at line 426 of file hmm-utils.cc.
Constructor & Destructor Documentation
TidToTstateMapper (const TransitionModel & trans_model, const std::vector< int32 > & disambig_syms) inline
Definition at line 422 of file hmm-utils.cc.
                                                           :
       trans_model_(trans_model),
       disambig_syms_(disambig_syms) { }
Member Function Documentation
int32 operator() (int32 label) const inline
Definition at line 427 of file hmm-utils.cc.
References TidToTstateMapper::disambig_syms_, TransitionModel::IsSelfLoop(), KALDI_ASSERT, KALDI_ERR, TransitionModel::NumTransitionIds(), TidToTstateMapper::trans_model_, and TransitionModel::TransitionIdToTransitionState().
{
     if (label == static_cast<int32>(fst::kNoLabel)) return -1;  // -1 -> -1
     else if (label >= 1 && label <= trans_model_.NumTransitionIds()) {
       if (trans_model_.IsSelfLoop(label))
         KALDI_ERR << "AddSelfLoops: graph already has self-loops.";
       return trans_model_.TransitionIdToTransitionState(label);
     } else {  // 0 or (presumably) disambiguation symbol.  Map to zero
       if (label != 0)
         KALDI_ASSERT(std::binary_search(disambig_syms_.begin(), disambig_syms_.end(), label));  // or invalid label
       return 0;
     }
   }
Member Data Documentation
const std::vector<int32>& disambig_syms_ private
Definition at line 442 of file hmm-utils.cc.
Referenced by TidToTstateMapper::operator()().
const TransitionModel& trans_model_ private
Definition at line 441 of file hmm-utils.cc.
Referenced by TidToTstateMapper::operator()().
The documentation for this class was generated from the following file:
hmm/hmm-utils.cc