Kaldi: CachingOptimizingCompiler Class Reference
CachingOptimizingCompiler Class Reference
This class enables you to do the compilation and optimization in one call, and also ensures that if the ComputationRequest is identical to the previous one, the compilation process is not repeated.
#include <nnet-optimize.h>
Public Member Functions
CachingOptimizingCompiler (const Nnet &nnet, const int32 capacity=20)
CachingOptimizingCompiler (const Nnet &nnet, const NnetOptimizeOptions &opt_config, const int32 capacity=20)
Note: nnet is retained as a const reference but opt_config is copied.
~CachingOptimizingCompiler ()
const NnetComputation * Compile (const ComputationRequest &request)
Does the compilation and returns a const pointer to the result, which is owned by this class, not the caller.
Private Types
typedef std::list< const
ComputationRequest * > AqType
typedef unordered_map< const
ComputationRequest
*, std::pair< NnetComputation
*, AqType::iterator >
, ComputationRequestHasher,
ComputationRequestPtrEqual > CacheType
Private Member Functions
void UpdateCache (const ComputationRequest *request, NnetComputation *computation)
void UpdateAccessQueue (CacheType::iterator &cit)
Private Attributes
const Nnet & nnet_
NnetOptimizeOptions opt_config_
AqType access_queue_
CacheType computation_cache_
int32 cache_capacity_
Detailed Description
This class enables you to do the compilation and optimization in one call, and also ensures that if the ComputationRequest is identical to the previous one, the compilation process is not repeated.
Definition at line 132 of file nnet-optimize.h.
Member Typedef Documentation
typedef std::list<const ComputationRequest*> AqType private
Definition at line 160 of file nnet-optimize.h.
typedef unordered_map<const ComputationRequest*, std::pair<NnetComputation*, AqType::iterator>, ComputationRequestHasher, ComputationRequestPtrEqual> CacheType private
Definition at line 168 of file nnet-optimize.h.
Constructor & Destructor Documentation
CachingOptimizingCompiler (const Nnet & nnet, const int32 capacity = 20) inline
Definition at line 134 of file nnet-optimize.h.
                                                      :
       nnet_(nnet), cache_capacity_(capacity) { }
CachingOptimizingCompiler (const Nnet & nnet, const NnetOptimizeOptions & opt_config, const int32 capacity = 20) inline
Note: nnet is retained as a const reference but opt_config is copied.
Definition at line 139 of file nnet-optimize.h.
                                                       :
       nnet_(nnet), opt_config_(opt_config), cache_capacity_(capacity) { }
~CachingOptimizingCompiler ()
Definition at line 439 of file nnet-optimize.cc.
References CachingOptimizingCompiler::computation_cache_.
{
   CacheType::const_iterator itr = computation_cache_.begin(),
       end = computation_cache_.end();
   for (; itr !=end; ++itr) {
     delete itr->first;
     delete itr->second.first;
   }
 }
Member Function Documentation
const NnetComputation * Compile (const ComputationRequest & request)
Does the compilation and returns a const pointer to the result, which is owned by this class, not the caller.
It calls ComputeCudaIndexes() for you, because you wouldn't be able to do this on a const object.
Definition at line 448 of file nnet-optimize.cc.
References ComputationChecker::Check(), CheckComputationOptions::check_rewrite, CachingOptimizingCompiler::computation_cache_, NnetComputation::ComputeCudaIndexes(), Compiler::CreateComputation(), kaldi::GetVerboseLevel(), KALDI_LOG, CachingOptimizingCompiler::nnet_, kaldi::nnet2::NnetComputation(), CachingOptimizingCompiler::opt_config_, kaldi::nnet3::Optimize(), ComputationRequest::Print(), NnetComputation::Print(), CachingOptimizingCompiler::UpdateAccessQueue(), and CachingOptimizingCompiler::UpdateCache().
Referenced by NnetLdaStatsAccumulator::AccStats(), NnetComputerFromEg::Compute(), NnetComputeProb::Compute(), NnetDecodableBase::DoNnetComputation(), and NnetTrainer::Train().
{
   NnetComputation *computation;
   ComputationRequest *request;
   // find computation in the cache
   CacheType::iterator cit = computation_cache_.find(&in_request);
   if (cit == computation_cache_.end()) {
     // if not found, compile and update cache
     request = new ComputationRequest;
     *request = in_request;
     Compiler compiler(*request, nnet_);
     CompilerOptions opts;
     computation = new NnetComputation;
     compiler.CreateComputation(opts, computation);
     int32 verbose_cutoff = 4;
     if (GetVerboseLevel() >= verbose_cutoff) {
       std::ostringstream os1;
       request->Print(os1);
       KALDI_LOG << "Computation request is " << os1.str();
       std::ostringstream os2;
       computation->Print(os2, nnet_);
       KALDI_LOG << "Generated computation is: " << os2.str();
     }
     { // some checking.
       CheckComputationOptions check_config;
       // we can do the rewrite check since it's before optimization.
       check_config.check_rewrite = true;
       ComputationChecker checker(check_config, nnet_, *computation);
       checker.Check();
     }
     Optimize(opt_config_, nnet_, *request, computation);
     if (GetVerboseLevel() >= verbose_cutoff) {
       std::ostringstream os;
       computation->Print(os, nnet_);
       KALDI_LOG << "Optimized computation is: " << os.str();
     }
     {  // check the computation again.
       CheckComputationOptions check_config;
       ComputationChecker checker(check_config, nnet_, *computation);
       checker.Check();
     }
     computation->ComputeCudaIndexes();
     UpdateCache(request, computation);
   } else {
     // if found, update access queue
     computation = cit->second.first;
     UpdateAccessQueue(cit);
   }
   return computation;
 }
void UpdateAccessQueue (CacheType::iterator & cit) private
Definition at line 431 of file nnet-optimize.cc.
References CachingOptimizingCompiler::access_queue_, CachingOptimizingCompiler::computation_cache_, and KALDI_ASSERT.
Referenced by CachingOptimizingCompiler::Compile().
{
   // exist, update access record by moving the accessed
   // request to the end of the access queue
   KALDI_ASSERT(cit != computation_cache_.end());
   access_queue_.splice(access_queue_.end(), access_queue_,
                        cit->second.second);
 }
void UpdateCache (const ComputationRequest * request, NnetComputation * computation) private
Definition at line 413 of file nnet-optimize.cc.
References CachingOptimizingCompiler::access_queue_, CachingOptimizingCompiler::cache_capacity_, CachingOptimizingCompiler::computation_cache_, and KALDI_ASSERT.
Referenced by CachingOptimizingCompiler::Compile().
{
   if (computation_cache_.size() == cache_capacity_) {
     // full, locate the least-recently-accessed request
     const CacheType::iterator it =
         computation_cache_.find(access_queue_.front());
     KALDI_ASSERT(it != computation_cache_.end());
     // purge the least-recently-accessed request
     delete it->first;
     delete it->second.first;
     computation_cache_.erase(it);
     access_queue_.pop_front();
   }
   AqType::iterator ait = access_queue_.insert(access_queue_.end(), request);
   computation_cache_.insert(std::make_pair(request,
                             std::make_pair(computation, ait)));
 }
Member Data Documentation
AqType access_queue_ private
Definition at line 161 of file nnet-optimize.h.
Referenced by CachingOptimizingCompiler::UpdateAccessQueue(), and CachingOptimizingCompiler::UpdateCache().
int32 cache_capacity_ private
Definition at line 181 of file nnet-optimize.h.
Referenced by CachingOptimizingCompiler::UpdateCache().
CacheType computation_cache_ private
Definition at line 169 of file nnet-optimize.h.
Referenced by CachingOptimizingCompiler::Compile(), CachingOptimizingCompiler::UpdateAccessQueue(), CachingOptimizingCompiler::UpdateCache(), and CachingOptimizingCompiler::~CachingOptimizingCompiler().
const Nnet& nnet_ private
Definition at line 151 of file nnet-optimize.h.
Referenced by CachingOptimizingCompiler::Compile().
NnetOptimizeOptions opt_config_ private
Definition at line 152 of file nnet-optimize.h.
Referenced by CachingOptimizingCompiler::Compile().
The documentation for this class was generated from the following files:
nnet3/nnet-optimize.h
nnet3/nnet-optimize.cc