Kaldi: DecodableAmNnetSimple Class Reference
DecodableAmNnetSimple Class Reference
#include <nnet-am-decodable-simple.h>
Public Member Functions
DecodableAmNnetSimple (const NnetSimpleComputationOptions &opts, const TransitionModel &trans_model, const AmNnetSimple &am_nnet, const MatrixBase< BaseFloat > &feats, const VectorBase< BaseFloat > *ivector=NULL, const MatrixBase< BaseFloat > *online_ivectors=NULL, int32 online_ivector_period=1)
This constructor takes features as input, and you can either supply a single iVector input, estimated in batch-mode ('ivector'), or 'online' iVectors ('online_ivectors' and 'online_ivector_period', or none at all.
virtual BaseFloat LogLikelihood (int32 frame, int32 transition_id)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Attributes
const TransitionModel & trans_model_
Additional Inherited Members
Private Member Functions inherited from NnetDecodableBase
NnetDecodableBase (const NnetSimpleComputationOptions &opts, const Nnet &nnet, const VectorBase< BaseFloat > &priors, const MatrixBase< BaseFloat > &feats, const VectorBase< BaseFloat > *ivector=NULL, const MatrixBase< BaseFloat > *online_ivectors=NULL, int32 online_ivector_period=1)
This constructor takes features as input, and you can either supply a single iVector input, estimated in batch-mode ('ivector'), or 'online' iVectors ('online_ivectors' and 'online_ivector_period', or none at all.
int32 NumFrames () const
int32 OutputDim () const
void GetOutputForFrame (int32 frame, VectorBase< BaseFloat > *output)
BaseFloat GetOutput (int32 subsampled_frame, int32 pdf_id)
Detailed Description
Definition at line 220 of file nnet-am-decodable-simple.h.
Constructor & Destructor Documentation
DecodableAmNnetSimple (const NnetSimpleComputationOptions & opts, const TransitionModel & trans_model, const AmNnetSimple & am_nnet, const MatrixBase< BaseFloat > & feats, const VectorBase< BaseFloat > * ivector = NULL, const MatrixBase< BaseFloat > * online_ivectors = NULL, int32 online_ivector_period = 1)
This constructor takes features as input, and you can either supply a single iVector input, estimated in batch-mode ('ivector'), or 'online' iVectors ('online_ivectors' and 'online_ivector_period', or none at all.
Note: it stores references to all arguments to the constructor, so don't delete them till this goes out of scope.
Parameters
[in] opts The options class. Warning: it includes an acoustic weight, whose default is 0.1; you may sometimes want to change this to 1.0.
[in] nnet The neural net that we're going to do the computation with
[in] priors Vector of priors– if supplied and nonempty, we subtract the log of these priors from the nnet output.
[in] feats The input feature matrix.
[in] ivector If you are using iVectors estimated in batch mode, a pointer to the iVector, else NULL.
[in] ivector If you are using iVectors estimated in batch mode, a pointer to the iVector, else NULL.
[in] online_ivectors If you are using iVectors estimated 'online' a pointer to the iVectors, else NULL.
[in] online_ivector_period If you are using iVectors estimated 'online' (i.e. if online_ivectors != NULL) gives the periodicity (in frames) with which the iVectors are estimated.
Definition at line 57 of file nnet-am-decodable-simple.cc.
                                 :
     NnetDecodableBase(opts, am_nnet.GetNnet(), am_nnet.Priors(),
                       feats, ivector, online_ivectors,
                       online_ivector_period),
     trans_model_(trans_model) { }
Member Function Documentation
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 263 of file nnet-am-decodable-simple.h.
References KALDI_ASSERT, and DecodableAmNnetSimple::NumFramesReady().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1);
   }
BaseFloat LogLikelihood (int32 frame, int32 index) virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 74 of file nnet-am-decodable-simple.cc.
References NnetDecodableBase::GetOutput(), DecodableAmNnetSimple::trans_model_, and TransitionModel::TransitionIdToPdf().
{
   int32 pdf_id = trans_model_.TransitionIdToPdf(transition_id);
   return GetOutput(frame, pdf_id);
 }
virtual int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 259 of file nnet-am-decodable-simple.h.
References NnetDecodableBase::NumFrames().
Referenced by DecodableAmNnetSimple::IsLastFrame().
 { return NumFrames(); }
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst.
Implements DecodableInterface.
Definition at line 261 of file nnet-am-decodable-simple.h.
References TransitionModel::NumTransitionIds(), and DecodableAmNnetSimple::trans_model_.
 { return trans_model_.NumTransitionIds(); }
Member Data Documentation
const TransitionModel& trans_model_ private
Definition at line 271 of file nnet-am-decodable-simple.h.
Referenced by DecodableAmNnetSimple::LogLikelihood(), and DecodableAmNnetSimple::NumIndices().
The documentation for this class was generated from the following files:
nnet3/nnet-am-decodable-simple.h
nnet3/nnet-am-decodable-simple.cc