Kaldi: Nnet Class Reference
Nnet Class Reference
#include <nnet-nnet.h>
Public Member Functions
Nnet ()
Nnet (const Nnet &other)
Nnet & operator= (const Nnet &other)
~Nnet ()
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass through the network.
void Backpropagate (const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass through the network.
void Feedforward (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass through the network, don't keep buffers (use it when not training)
void Feedforward (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out, bool binary, const std::string &filename)
int32 InputDim () const
Dimensionality on network input (input feature dim.)
int32 OutputDim () const
Dimensionality of network outputs (posteriors | bn-features | etc.)
int32 NumComponents () const
Returns number of components– think of this as similar to # of layers, but e.g.
const Component & GetComponent (int32 c) const
Component & GetComponent (int32 c)
void SetComponent (int32 c, Component *component)
Sets the c'th component to "component", taking ownership of the pointer and deleting the corresponding one that we own.
void AppendComponent (Component *dynamically_allocated_comp)
Appends this component to the components already in the neural net.
void AppendNnet (const Nnet &nnet_to_append)
Append another network to the current one (copy components).
void RemoveComponent (int32 c)
Remove component.
void RemoveLastComponent ()
const std::vector< CuMatrix
< BaseFloat > > & PropagateBuffer () const
Access to forward pass buffers.
const std::vector< CuMatrix
< BaseFloat > > & BackpropagateBuffer () const
Access to backward pass buffers.
int32 NumParams () const
Get the number of parameters in the network.
void GetParams (Vector< BaseFloat > *wei_copy) const
Get the network weights in a supervector.
void GetWeights (Vector< BaseFloat > *wei_copy) const
Get the network weights in a supervector.
void SetWeights (const Vector< BaseFloat > &wei_src)
Set the network weights from a supervector.
void GetGradient (Vector< BaseFloat > *grad_copy) const
Get the gradient stored in the network.
void SetDropoutRetention (BaseFloat r)
Set the dropout rate.
void ResetLstmStreams (const std::vector< int32 > &stream_reset_flag)
Reset streams in LSTM multi-stream training,.
void SetSeqLengths (const std::vector< int32 > &sequence_lengths)
set sequence length in LSTM multi-stream training
void Init (const std::string &config_file)
Initialize MLP from config.
void Read (const std::string &file)
Read the MLP from file (can add layers to exisiting instance of Nnet)
void Read (std::istream &in, bool binary)
Read the MLP from stream (can add layers to exisiting instance of Nnet)
void Write (const std::string &file, bool binary) const
Write MLP to file.
void Write (std::ostream &out, bool binary) const
Write MLP to stream.
std::string Info () const
Create string with human readable description of the nnet.
std::string InfoGradient () const
Create string with per-component gradient statistics.
std::string InfoPropagate () const
Create string with propagation-buffer statistics.
std::string InfoBackPropagate () const
Create string with back-propagation-buffer statistics.
void Check () const
Consistency check.
void Destroy ()
Relese the memory.
void SetTrainOptions (const NnetTrainOptions &opts)
Set training hyper-parameters to the network and its UpdatableComponent(s)
const NnetTrainOptions & GetTrainOptions () const
Get training hyper-parameters from the network.
Private Attributes
std::vector< Component * > components_
Vector which contains all the components composing the neural network, the components are for example: AffineTransform, Sigmoid, Softmax.
std::vector< CuMatrix
< BaseFloat > > propagate_buf_
buffers for forward pass
std::vector< CuMatrix
< BaseFloat > > backpropagate_buf_
buffers for backward pass
NnetTrainOptions opts_
Option class with hyper-parameters passed to UpdatableComponent(s)
Detailed Description
Definition at line 36 of file nnet-nnet.h.
Constructor & Destructor Documentation
Nnet () inline
Definition at line 38 of file nnet-nnet.h.
 {}
Nnet (const Nnet & other)
Definition at line 33 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::Check(), Nnet::components_, Component::Copy(), Nnet::GetComponent(), rnnlm::i, Nnet::NumComponents(), Nnet::opts_, Nnet::propagate_buf_, and Nnet::SetTrainOptions().
{
   // copy the components
   for(int32 i = 0; i < other.NumComponents(); i++) {
     components_.push_back(other.GetComponent(i).Copy());
   }
   // create empty buffers
   propagate_buf_.resize(NumComponents()+1);
   backpropagate_buf_.resize(NumComponents()+1);
   // copy train opts
   SetTrainOptions(other.opts_);
   Check();
 }
~Nnet ()
Definition at line 62 of file nnet-nnet.cc.
References Nnet::Destroy().
             {
   Destroy();
 }
Member Function Documentation
void AppendComponent (Component * dynamically_allocated_comp)
Appends this component to the components already in the neural net.
Takes ownership of the pointer
Definition at line 370 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::Check(), Nnet::components_, Nnet::NumComponents(), and Nnet::propagate_buf_.
Referenced by Nnet::AppendNnet(), Nnet::Init(), and main().
{
   // append,
   components_.push_back(dynamically_allocated_comp);
   // create training buffers,
   propagate_buf_.resize(NumComponents()+1);
   backpropagate_buf_.resize(NumComponents()+1);
   //
   Check();
 }
void AppendNnet (const Nnet & nnet_to_append)
Append another network to the current one (copy components).
Definition at line 380 of file nnet-nnet.cc.
References Nnet::AppendComponent(), Nnet::backpropagate_buf_, Nnet::Check(), Component::Copy(), Nnet::GetComponent(), rnnlm::i, Nnet::NumComponents(), and Nnet::propagate_buf_.
{
   // append,
   for(int32 i=0; i<nnet_to_append.NumComponents(); i++) {
     AppendComponent(nnet_to_append.GetComponent(i).Copy());
   }
   // create training buffers,
   propagate_buf_.resize(NumComponents()+1);
   backpropagate_buf_.resize(NumComponents()+1);
   //
   Check();
 }
void Backpropagate (const CuMatrixBase< BaseFloat > & out_diff, CuMatrix< BaseFloat > * in_diff)
Perform backward pass through the network.
Definition at line 89 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::components_, rnnlm::i, KALDI_ASSERT, Nnet::NumComponents(), Nnet::propagate_buf_, and UpdatableComponent::Update().
Referenced by main(), and SentenceAveragingComponent::Update().
{
   // Backpropagation
   //
   // 0 layers
   if (NumComponents() == 0) { (*in_diff) = out_diff; return; }
   KALDI_ASSERT((int32)propagate_buf_.size() == NumComponents()+1);
   KALDI_ASSERT((int32)backpropagate_buf_.size() == NumComponents()+1);
   // copy out_diff to last buffer
   backpropagate_buf_[NumComponents()] = out_diff;
   // backpropagate using buffers
   for (int32 i = NumComponents()-1; i >= 0; i--) {
     components_[i]->Backpropagate(propagate_buf_[i], propagate_buf_[i+1],
                             backpropagate_buf_[i+1], &backpropagate_buf_[i]);
     if (components_[i]->IsUpdatable()) {
       UpdatableComponent *uc = dynamic_cast<UpdatableComponent*>(components_[i]);
       uc->Update(propagate_buf_[i], backpropagate_buf_[i+1]);
     }
   }
   // eventually export the derivative
   if (NULL != in_diff) (*in_diff) = backpropagate_buf_[0];
   //
   // End of Backpropagation
 }
const std::vector<CuMatrix<BaseFloat> >& BackpropagateBuffer () const inline
Access to backward pass buffers.
Definition at line 85 of file nnet-nnet.h.
References Nnet::backpropagate_buf_.
{
     return backpropagate_buf_;
   }
void Check () const
Consistency check.
Definition at line 704 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::components_, Nnet::GetParams(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_ISINF, KALDI_ISNAN, Nnet::NumComponents(), Nnet::propagate_buf_, and VectorBase< Real >::Sum().
Referenced by Nnet::AppendComponent(), Nnet::AppendNnet(), Nnet::Init(), Nnet::Nnet(), Nnet::operator=(), Nnet::Read(), Nnet::RemoveComponent(), Nnet::SetComponent(), and Nnet::Write().
{
   // check we have correct number of buffers,
   KALDI_ASSERT(propagate_buf_.size() == NumComponents()+1);
   KALDI_ASSERT(backpropagate_buf_.size() == NumComponents()+1);
   // check dims,
   for (size_t i = 0; i + 1 < components_.size(); i++) {
     KALDI_ASSERT(components_[i] != NULL);
     int32 output_dim = components_[i]->OutputDim(),
       next_input_dim = components_[i+1]->InputDim();
     KALDI_ASSERT(output_dim == next_input_dim);
   }
   // check for nan/inf in network weights,
   Vector<BaseFloat> weights;
   GetParams(&weights);
   BaseFloat sum = weights.Sum();
   if(KALDI_ISINF(sum)) {
     KALDI_ERR << "'inf' in network parameters (weight explosion, try lower learning rate?)";
   }
   if(KALDI_ISNAN(sum)) {
     KALDI_ERR << "'nan' in network parameters (try lower learning rate?)";
   }
 }
void Destroy ()
Relese the memory.
Definition at line 728 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::components_, rnnlm::i, Nnet::NumComponents(), and Nnet::propagate_buf_.
Referenced by Nnet::operator=(), and Nnet::~Nnet().
                    {
   for(int32 i=0; i<NumComponents(); i++) {
     delete components_[i];
   }
   components_.resize(0);
   propagate_buf_.resize(0);
   backpropagate_buf_.resize(0);
 }
void Feedforward (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * out)
Perform forward pass through the network, don't keep buffers (use it when not training)
Definition at line 121 of file nnet-nnet.cc.
References Nnet::components_, CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), Nnet::NumComponents(), CuMatrixBase< Real >::NumRows(), Nnet::propagate_buf_, and CuMatrix< Real >::Resize().
Referenced by main().
{
   KALDI_ASSERT(NULL != out);
   if (NumComponents() == 0) {
     out->Resize(in.NumRows(), in.NumCols());
     out->CopyFromMat(in);
     return;
   }
   if (NumComponents() == 1) {
     components_[0]->Propagate(in, out);
     return;
   }
   // we need at least 2 input buffers
   KALDI_ASSERT(propagate_buf_.size() >= 2);
   // propagate by using exactly 2 auxiliary buffers
   int32 L = 0;
   components_[L]->Propagate(in, &propagate_buf_[L%2]);
   for(L++; L<=NumComponents()-2; L++) {
     components_[L]->Propagate(propagate_buf_[(L-1)%2], &propagate_buf_[L%2]);
   }
   components_[L]->Propagate(propagate_buf_[(L-1)%2], out);
   // release the buffers we don't need anymore
   propagate_buf_[0].Resize(0,0);
   propagate_buf_[1].Resize(0,0);
 }
void Feedforward (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * out, bool binary, const std::string & filename)
Definition at line 281 of file nnet-nnet.cc.
References Output::Close(), Nnet::components_, CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, KALDI_LOG, CuMatrixBase< Real >::NumCols(), Nnet::NumComponents(), CuMatrixBase< Real >::NumRows(), Output::Open(), Nnet::propagate_buf_, CuMatrix< Real >::Resize(), Output::Stream(), Nnet::Write(), CuMatrixBase< Real >::Write(), and kaldi::WriteToken().
 {
   KALDI_ASSERT(NULL != out);
   KALDI_LOG << filename;
   if (NumComponents() == 0) {
     out->Resize(in.NumRows(), in.NumCols());
     out->CopyFromMat(in);
     return;
   }
   if (NumComponents() == 1) {
     Output ot;
     ot.Open(filename, binary, false);
     WriteToken(ot.Stream(), binary, "<Layer0>");
     in.Write(ot.Stream(), binary);
     components_[0]->Propagate(in, out);
     WriteToken(ot.Stream(), binary, "<Layer1>");
     out->Write(ot.Stream(), binary);
     ot.Close();
     return;
   }
   // we need at least 2 input buffers
   KALDI_ASSERT(propagate_buf_.size() >= 2);
   // file to store data
   std::string file = filename+"/features.txt";
   // propagate by using exactly 2 auxiliary buffers
   Output ot;
   int32 L = 0;
   components_[L]->Propagate(in, &propagate_buf_[L%2]);
   ot.Open(file, binary, false);
   WriteToken(ot.Stream(), binary, "<Layer0>");
   in.Write(ot.Stream(), binary);
   for(L++; L<=NumComponents()-2; L++) {
     components_[L]->Propagate(propagate_buf_[(L-1)%2], &propagate_buf_[L%2]);
     WriteToken(ot.Stream(), binary, "<Layer"+ToString<int32>(L)+">");
     propagate_buf_[(L-1)%2].Write(ot.Stream(), binary);
   }
   WriteToken(ot.Stream(), binary, "<Layer"+ToString<int32>(L)+">");
   propagate_buf_[(L-1)%2].Write(ot.Stream(), binary);
   components_[L]->Propagate(propagate_buf_[(L-1)%2], out);
   WriteToken(ot.Stream(), binary, "<Layer"+ToString<int32>(L+1)+">");
   out->Write(ot.Stream(), binary);
   ot.Close();
   // release the buffers we don't need anymore
   propagate_buf_[0].Resize(0,0);
   propagate_buf_[1].Resize(0,0);
 }
const Component & GetComponent (int32 c) const
Definition at line 353 of file nnet-nnet.cc.
References Nnet::components_, and KALDI_ASSERT.
Referenced by Nnet::AppendNnet(), kaldi::ConvertNnet1ToNnet2(), Rbm::InitData(), main(), Nnet::Nnet(), Nnet::operator=(), Nnet::ResetLstmStreams(), Nnet::SetDropoutRetention(), Nnet::SetSeqLengths(), and Nnet::SetTrainOptions().
{
   KALDI_ASSERT(static_cast<size_t>(component) < components_.size());
   return *(components_[component]);
 }
Component & GetComponent (int32 c)
Definition at line 358 of file nnet-nnet.cc.
References Nnet::components_, and KALDI_ASSERT.
{
   KALDI_ASSERT(static_cast<size_t>(component) < components_.size());
   return *(components_[component]);
 }
void GetGradient (Vector< BaseFloat > * grad_copy) const
Get the gradient stored in the network.
Definition at line 485 of file nnet-nnet.cc.
References Nnet::components_, CuMatrixBase< Real >::CopyToMat(), CuVectorBase< Real >::CopyToVec(), CuVectorBase< Real >::Dim(), Component::kAffineTransform, KALDI_ASSERT, KALDI_ERR, rnnlm::n, CuMatrixBase< Real >::NumCols(), Nnet::NumParams(), CuMatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), Vector< Real >::Resize(), and Component::TypeToMarker().
{
   grad_copy->Resize(NumParams());
   int32 pos = 0;
   // copy the params
   for(int32 n=0; n<components_.size(); n++) {
     if(components_[n]->IsUpdatable()) {
       switch(components_[n]->GetType()) {
         case Component::kAffineTransform : {
           // get the weights from CuMatrix to Matrix
           const CuMatrixBase<BaseFloat>& cu_mat =
             dynamic_cast<AffineTransform*>(components_[n])->GetLinearityCorr();
           Matrix<BaseFloat> mat(cu_mat.NumRows(),cu_mat.NumCols());
           cu_mat.CopyToMat(&mat);
           // copy the the matrix row-by-row to the vector
           int32 mat_size = mat.NumRows()*mat.NumCols();
           grad_copy->Range(pos,mat_size).CopyRowsFromMat(mat);
           pos += mat_size;
           // get the biases from CuVector to Vector
           const CuVector<BaseFloat>& cu_vec =
             dynamic_cast<AffineTransform*>(components_[n])->GetBiasCorr();
           Vector<BaseFloat> vec(cu_vec.Dim());
           cu_vec.CopyToVec(&vec);
           // append biases to the supervector
           grad_copy->Range(pos,vec.Dim()).CopyFromVec(vec);
           pos += vec.Dim();
         } break;
         default :
           KALDI_ERR << "Unimplemented access to parameters "
                     << "of updatable component "
                     << Component::TypeToMarker(components_[n]->GetType());
       }
     }
   }
   KALDI_ASSERT(pos == NumParams());
 }
void GetParams (Vector< BaseFloat > * wei_copy) const
Get the network weights in a supervector.
Definition at line 406 of file nnet-nnet.cc.
References Nnet::components_, VectorBase< Real >::Dim(), UpdatableComponent::GetParams(), rnnlm::i, KALDI_ASSERT, Nnet::NumParams(), VectorBase< Real >::Range(), and Vector< Real >::Resize().
Referenced by Nnet::Check(), and SentenceAveragingComponent::GetParams().
{
   wei_copy->Resize(NumParams());
   int32 pos = 0;
   // copy the params
   for(int32 i=0; i<components_.size(); i++) {
     if(components_[i]->IsUpdatable()) {
       UpdatableComponent& c = dynamic_cast<UpdatableComponent&>(*components_[i]);
       Vector<BaseFloat> c_params;
       c.GetParams(&c_params);
       wei_copy->Range(pos,c_params.Dim()).CopyFromVec(c_params);
       pos += c_params.Dim();
     }
   }
   KALDI_ASSERT(pos == NumParams());
 }
const NnetTrainOptions& GetTrainOptions () const inline
Get training hyper-parameters from the network.
Definition at line 135 of file nnet-nnet.h.
References Nnet::opts_.
{
     return opts_;
   }
void GetWeights (Vector< BaseFloat > * wei_copy) const
Get the network weights in a supervector.
Definition at line 423 of file nnet-nnet.cc.
References Nnet::components_, VectorBase< Real >::Dim(), Component::kAffineTransform, KALDI_ASSERT, KALDI_ERR, rnnlm::n, MatrixBase< Real >::NumCols(), Nnet::NumParams(), MatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), Vector< Real >::Resize(), and Component::TypeToMarker().
{
   wei_copy->Resize(NumParams());
   int32 pos = 0;
   // copy the params
   for(int32 n=0; n<components_.size(); n++) {
     if(components_[n]->IsUpdatable()) {
       switch(components_[n]->GetType()) {
         case Component::kAffineTransform : {
           // copy weight matrix row-by-row to the vector
           Matrix<BaseFloat> mat(dynamic_cast<AffineTransform*>(components_[n])->GetLinearity());
           int32 mat_size = mat.NumRows()*mat.NumCols();
           wei_copy->Range(pos,mat_size).CopyRowsFromMat(mat);
           pos += mat_size;
           // append biases
           Vector<BaseFloat> vec(dynamic_cast<AffineTransform*>(components_[n])->GetBias());
           wei_copy->Range(pos,vec.Dim()).CopyFromVec(vec);
           pos += vec.Dim();
         } break;
         default :
           KALDI_ERR << "Unimplemented access to parameters "
                     << "of updatable component "
                     << Component::TypeToMarker(components_[n]->GetType());
       }
     }
   }
   KALDI_ASSERT(pos == NumParams());
 }
std::string Info () const
Create string with human readable description of the nnet.
Definition at line 637 of file nnet-nnet.cc.
References Nnet::components_, rnnlm::i, Nnet::InputDim(), Nnet::NumComponents(), Nnet::NumParams(), Nnet::OutputDim(), and Component::TypeToMarker().
Referenced by SentenceAveragingComponent::Info().
{
   // global info
   std::ostringstream ostr;
   ostr << "num-components " << NumComponents() << std::endl;
   ostr << "input-dim " << InputDim() << std::endl;
   ostr << "output-dim " << OutputDim() << std::endl;
   ostr << "number-of-parameters " << static_cast<float>(NumParams())/1e6
        << " millions" << std::endl;
   // topology & weight stats
   for (int32 i = 0; i < NumComponents(); i++) {
     ostr << "component " << i+1 << " : "
          << Component::TypeToMarker(components_[i]->GetType())
          << ", input-dim " << components_[i]->InputDim()
          << ", output-dim " << components_[i]->OutputDim()
          << ", " << components_[i]->Info() << std::endl;
   }
   return ostr.str();
 }
std::string InfoBackPropagate () const
Create string with back-propagation-buffer statistics.
Definition at line 685 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::components_, rnnlm::i, Component::kParallelComponent, kaldi::nnet1::MomentStatistics(), Nnet::NumComponents(), and Component::TypeToMarker().
Referenced by main().
{
   std::ostringstream ostr;
   // forward-pass buffer stats
   ostr << "### Backward propagation buffer content :\n";
   ostr << "[0] diff of <Input> " << MomentStatistics(backpropagate_buf_[0]) << std::endl;
   for (int32 i=0; i<NumComponents(); i++) {
     ostr << "["<<1+i<< "] diff-output of "
          << Component::TypeToMarker(components_[i]->GetType())
          << MomentStatistics(backpropagate_buf_[i+1]) << std::endl;
     // nested networks too...
     if (Component::kParallelComponent == components_[i]->GetType()) {
       ostr << dynamic_cast<ParallelComponent*>(components_[i])->InfoBackPropagate();
     }
   }
   return ostr.str();
 }
std::string InfoGradient () const
Create string with per-component gradient statistics.
Definition at line 656 of file nnet-nnet.cc.
References Nnet::components_, rnnlm::i, Nnet::NumComponents(), and Component::TypeToMarker().
Referenced by SentenceAveragingComponent::InfoGradient(), and main().
{
   std::ostringstream ostr;
   // gradient stats
   ostr << "### Gradient stats :\n";
   for (int32 i = 0; i < NumComponents(); i++) {
     ostr << "Component " << i+1 << " : "
          << Component::TypeToMarker(components_[i]->GetType())
          << ", " << components_[i]->InfoGradient() << std::endl;
   }
   return ostr.str();
 }
std::string InfoPropagate () const
Create string with propagation-buffer statistics.
Definition at line 668 of file nnet-nnet.cc.
References Nnet::components_, rnnlm::i, Component::kParallelComponent, kaldi::nnet1::MomentStatistics(), Nnet::NumComponents(), Nnet::propagate_buf_, and Component::TypeToMarker().
Referenced by main().
{
   std::ostringstream ostr;
   // forward-pass buffer stats
   ostr << "### Forward propagation buffer content :\n";
   ostr << "[0] output of <Input> " << MomentStatistics(propagate_buf_[0]) << std::endl;
   for (int32 i=0; i<NumComponents(); i++) {
     ostr << "["<<1+i<< "] output of "
          << Component::TypeToMarker(components_[i]->GetType())
          << MomentStatistics(propagate_buf_[i+1]) << std::endl;
     // nested networks too...
     if (Component::kParallelComponent == components_[i]->GetType()) {
       ostr << dynamic_cast<ParallelComponent*>(components_[i])->InfoPropagate();
     }
   }
   return ostr.str();
 }
void Init (const std::string & config_file)
Initialize MLP from config.
Definition at line 564 of file nnet-nnet.cc.
References Nnet::AppendComponent(), Nnet::Check(), Input::Close(), Component::Init(), KALDI_ASSERT, KALDI_VLOG, and Input::Stream().
Referenced by ParallelComponent::InitData(), SentenceAveragingComponent::InitData(), and main().
{
   Input in(file);
   std::istream &is = in.Stream();
   // do the initialization with config lines,
   std::string conf_line, token;
   while (!is.eof()) {
     KALDI_ASSERT(is.good());
     std::getline(is, conf_line); // get a line from config file,
     if (conf_line == "") continue;
     KALDI_VLOG(1) << conf_line;
     std::istringstream(conf_line) >> std::ws >> token; // get 1st token,
     if (token == "<NnetProto>" || token == "</NnetProto>") continue; // ignored tokens,
     AppendComponent(Component::Init(conf_line+"\n"));
     is >> std::ws;
   }
   // cleanup
   in.Close();
   Check();
 }
int32 InputDim () const
Dimensionality on network input (input feature dim.)
Definition at line 348 of file nnet-nnet.cc.
References Nnet::components_, and KALDI_ASSERT.
Referenced by Nnet::Info(), SentenceAveragingComponent::InitData(), and SentenceAveragingComponent::ReadData().
{
   KALDI_ASSERT(!components_.empty());
   return components_.front()->InputDim();
 }
int32 NumComponents () const inline
Returns number of components– think of this as similar to # of layers, but e.g.
the nonlinearity and the linear part count as separate components, so the number of components will be more than the number of layers.
Definition at line 61 of file nnet-nnet.h.
References Nnet::components_.
Referenced by Nnet::AppendComponent(), Nnet::AppendNnet(), Nnet::Backpropagate(), Nnet::Check(), kaldi::ConvertNnet1ToNnet2(), Nnet::Destroy(), Nnet::Feedforward(), Nnet::Info(), Nnet::InfoBackPropagate(), Nnet::InfoGradient(), Nnet::InfoPropagate(), main(), Nnet::Nnet(), Nnet::operator=(), Nnet::Propagate(), Nnet::Read(), Nnet::RemoveComponent(), Nnet::RemoveLastComponent(), Nnet::ResetLstmStreams(), Nnet::SetDropoutRetention(), Nnet::SetSeqLengths(), Nnet::SetTrainOptions(), and Nnet::Write().
 { return components_.size(); }
int32 NumParams () const
Get the number of parameters in the network.
Definition at line 522 of file nnet-nnet.cc.
References Nnet::components_, and rnnlm::n.
Referenced by Nnet::GetGradient(), Nnet::GetParams(), Nnet::GetWeights(), Nnet::Info(), SentenceAveragingComponent::NumParams(), and Nnet::SetWeights().
{
   int32 n_params = 0;
   for(int32 n=0; n<components_.size(); n++) {
     if(components_[n]->IsUpdatable()) {
       n_params += dynamic_cast<UpdatableComponent*>(components_[n])->NumParams();
     }
   }
   return n_params;
 }
Nnet & operator= (const Nnet & other)
Definition at line 46 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::Check(), Nnet::components_, Component::Copy(), Nnet::Destroy(), Nnet::GetComponent(), rnnlm::i, Nnet::NumComponents(), Nnet::opts_, Nnet::propagate_buf_, and Nnet::SetTrainOptions().
{
   Destroy();
   // copy the components
   for(int32 i = 0; i < other.NumComponents(); i++) {
     components_.push_back(other.GetComponent(i).Copy());
   }
   // create empty buffers
   propagate_buf_.resize(NumComponents()+1);
   backpropagate_buf_.resize(NumComponents()+1);
   // copy train opts
   SetTrainOptions(other.opts_);
   Check();
   return *this;
 }
int32 OutputDim () const
Dimensionality of network outputs (posteriors | bn-features | etc.)
Definition at line 343 of file nnet-nnet.cc.
References Nnet::components_, and KALDI_ASSERT.
Referenced by SentenceAveragingComponent::BackpropagateFnc(), Nnet::Info(), SentenceAveragingComponent::InitData(), main(), SentenceAveragingComponent::PropagateFnc(), SentenceAveragingComponent::ReadData(), and SentenceAveragingComponent::Update().
{
   KALDI_ASSERT(!components_.empty());
   return components_.back()->OutputDim();
 }
void Propagate (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * out)
Perform forward pass through the network.
Definition at line 67 of file nnet-nnet.cc.
References Nnet::components_, rnnlm::i, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), Nnet::NumComponents(), CuMatrixBase< Real >::NumRows(), and Nnet::propagate_buf_.
Referenced by main(), and SentenceAveragingComponent::PropagateFnc().
{
   KALDI_ASSERT(NULL != out);
   if (NumComponents() == 0) {
     (*out) = in; // copy
     return;
   }
   // we need at least L+1 input buffers
   KALDI_ASSERT((int32)propagate_buf_.size() >= NumComponents()+1);
   propagate_buf_[0].Resize(in.NumRows(), in.NumCols());
   propagate_buf_[0].CopyFromMat(in);
   for(int32 i=0; i<(int32)components_.size(); i++) {
     components_[i]->Propagate(propagate_buf_[i], &propagate_buf_[i+1]);
   }
   (*out) = propagate_buf_[components_.size()];
 }
const std::vector<CuMatrix<BaseFloat> >& PropagateBuffer () const inline
Access to forward pass buffers.
Definition at line 81 of file nnet-nnet.h.
References Nnet::propagate_buf_.
{
     return propagate_buf_;
   }
void Read (const std::string & file)
Read the MLP from file (can add layers to exisiting instance of Nnet)
Definition at line 585 of file nnet-nnet.cc.
References Input::Close(), KALDI_WARN, Nnet::NumComponents(), and Input::Stream().
Referenced by ParallelComponent::InitData(), Rbm::InitData(), SentenceAveragingComponent::InitData(), main(), ParallelComponent::ReadData(), and SentenceAveragingComponent::ReadData().
{
   bool binary;
   Input in(file, &binary);
   Read(in.Stream(), binary);
   in.Close();
   // Warn if the NN is empty
   if(NumComponents() == 0) {
     KALDI_WARN << "The network '" << file << "' is empty.";
   }
 }
void Read (std::istream & in, bool binary)
Read the MLP from stream (can add layers to exisiting instance of Nnet)
Definition at line 597 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::Check(), Nnet::components_, Component::InputDim(), KALDI_ERR, NnetTrainOptions::learn_rate, Nnet::NumComponents(), Nnet::opts_, Nnet::propagate_buf_, and Component::Read().
{
   // get the network layers from a factory
   Component *comp;
   while (NULL != (comp = Component::Read(is, binary))) {
     if (NumComponents() > 0 && components_.back()->OutputDim() != comp->InputDim()) {
       KALDI_ERR << "Dimensionality mismatch!"
                 << " Previous layer output:" << components_.back()->OutputDim()
                 << " Current layer input:" << comp->InputDim();
     }
     components_.push_back(comp);
   }
   // create empty buffers
   propagate_buf_.resize(NumComponents()+1);
   backpropagate_buf_.resize(NumComponents()+1);
   // reset learn rate
   opts_.learn_rate = 0.0;
   Check(); //check consistency (dims...)
 }
void RemoveComponent (int32 c)
Remove component.
Definition at line 392 of file nnet-nnet.cc.
References Nnet::backpropagate_buf_, Nnet::Check(), Nnet::components_, KALDI_ASSERT, Nnet::NumComponents(), and Nnet::propagate_buf_.
Referenced by main(), and Nnet::RemoveLastComponent().
{
   KALDI_ASSERT(component < NumComponents());
   // remove,
   Component* ptr = components_[component];
   components_.erase(components_.begin()+component);
   delete ptr;
   // create training buffers,
   propagate_buf_.resize(NumComponents()+1);
   backpropagate_buf_.resize(NumComponents()+1);
   //
   Check();
 }
void RemoveLastComponent () inline
Definition at line 78 of file nnet-nnet.h.
References Nnet::NumComponents(), and Nnet::RemoveComponent().
 { RemoveComponent(NumComponents()-1); }
void ResetLstmStreams (const std::vector< int32 > & stream_reset_flag)
Reset streams in LSTM multi-stream training,.
Definition at line 546 of file nnet-nnet.cc.
References Nnet::GetComponent(), Component::GetType(), Component::kLstmProjectedStreams, Nnet::NumComponents(), and LstmProjectedStreams::ResetLstmStreams().
{
   for (int32 c=0; c < NumComponents(); c++) {
     if (GetComponent(c).GetType() == Component::kLstmProjectedStreams) {
       LstmProjectedStreams& comp = dynamic_cast<LstmProjectedStreams&>(GetComponent(c));
       comp.ResetLstmStreams(stream_reset_flag);
     }
   }
 }
void SetComponent (int32 c, Component * component)
Sets the c'th component to "component", taking ownership of the pointer and deleting the corresponding one that we own.
Definition at line 363 of file nnet-nnet.cc.
References Nnet::Check(), Nnet::components_, and KALDI_ASSERT.
{
   KALDI_ASSERT(static_cast<size_t>(c) < components_.size());
   delete components_[c];
   components_[c] = component;
   Check(); // Check that all the dimensions still match up.
 }
void SetDropoutRetention (BaseFloat r)
Set the dropout rate.
Definition at line 533 of file nnet-nnet.cc.
References Nnet::GetComponent(), Dropout::GetDropoutRetention(), Component::GetType(), KALDI_LOG, Component::kDropout, Nnet::NumComponents(), and Dropout::SetDropoutRetention().
{
   for (int32 c=0; c < NumComponents(); c++) {
     if (GetComponent(c).GetType() == Component::kDropout) {
       Dropout& comp = dynamic_cast<Dropout&>(GetComponent(c));
       BaseFloat r_old = comp.GetDropoutRetention();
       comp.SetDropoutRetention(r);
       KALDI_LOG << "Setting dropout-retention in component " << c
                 << " from " << r_old << " to " << r;
     }
   }
 }
void SetSeqLengths (const std::vector< int32 > & sequence_lengths)
set sequence length in LSTM multi-stream training
Definition at line 555 of file nnet-nnet.cc.
References Nnet::GetComponent(), Component::GetType(), Component::kBLstmProjectedStreams, Nnet::NumComponents(), and BLstmProjectedStreams::SetSeqLengths().
{
   for (int32 c=0; c < NumComponents(); c++) {
     if (GetComponent(c).GetType() == Component::kBLstmProjectedStreams) {
       BLstmProjectedStreams& comp = dynamic_cast<BLstmProjectedStreams&>(GetComponent(c));
       comp.SetSeqLengths(sequence_lengths);
     }
   }
 }
void SetTrainOptions (const NnetTrainOptions & opts)
Set training hyper-parameters to the network and its UpdatableComponent(s)
Definition at line 738 of file nnet-nnet.cc.
References Nnet::GetComponent(), Component::IsUpdatable(), Nnet::NumComponents(), and Nnet::opts_.
Referenced by main(), Nnet::Nnet(), Nnet::operator=(), and SentenceAveragingComponent::SetTrainOptions().
{
   opts_ = opts;
   //set values to individual components
   for (int32 l=0; l<NumComponents(); l++) {
     if(GetComponent(l).IsUpdatable()) {
       dynamic_cast<UpdatableComponent&>(GetComponent(l)).SetTrainOptions(opts_);
     }
   }
 }
void SetWeights (const Vector< BaseFloat > & wei_src)
Set the network weights from a supervector.
Definition at line 452 of file nnet-nnet.cc.
References Nnet::components_, VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), AffineTransform::GetBias(), AffineTransform::GetLinearity(), Component::kAffineTransform, KALDI_ASSERT, KALDI_ERR, rnnlm::n, Nnet::NumParams(), MatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), AffineTransform::SetBias(), AffineTransform::SetLinearity(), and Component::TypeToMarker().
{
   KALDI_ASSERT(wei_src.Dim() == NumParams());
   int32 pos = 0;
   for(int32 n=0; n<components_.size(); n++) {
     if(components_[n]->IsUpdatable()) {
       switch(components_[n]->GetType()) {
         case Component::kAffineTransform : {
           // get the component
           AffineTransform* aff_t = dynamic_cast<AffineTransform*>(components_[n]);
           // we need weight matrix with original dimensions
           Matrix<BaseFloat> mat(aff_t->GetLinearity());
           int32 mat_size = mat.NumRows()*mat.NumCols();
           mat.CopyRowsFromVec(wei_src.Range(pos,mat_size));
           pos += mat_size;
           // get the bias vector
           Vector<BaseFloat> vec(aff_t->GetBias());
           vec.CopyFromVec(wei_src.Range(pos,vec.Dim()));
           pos += vec.Dim();
           // assign to the component
           aff_t->SetLinearity(CuMatrix<BaseFloat>(mat));
           aff_t->SetBias(CuVector<BaseFloat>(vec));
         } break;
         default :
           KALDI_ERR << "Unimplemented access to parameters "
                     << "of updatable component "
                     << Component::TypeToMarker(components_[n]->GetType());
       }
     }
   }
   KALDI_ASSERT(pos == NumParams());
 }
void Write (const std::string & file, bool binary) const
Write MLP to file.
Definition at line 618 of file nnet-nnet.cc.
References Output::Close(), and Output::Stream().
Referenced by Nnet::Feedforward(), main(), and SentenceAveragingComponent::WriteData().
{
   Output out(file, binary, true);
   Write(out.Stream(), binary);
   out.Close();
 }
void Write (std::ostream & out, bool binary) const
Write MLP to stream.
Definition at line 625 of file nnet-nnet.cc.
References Nnet::Check(), Nnet::components_, rnnlm::i, Nnet::NumComponents(), and kaldi::WriteToken().
{
   Check();
   WriteToken(os, binary, "<Nnet>");
   if(binary == false) os << std::endl;
   for(int32 i=0; i<NumComponents(); i++) {
     components_[i]->Write(os, binary);
   }
   WriteToken(os, binary, "</Nnet>");
   if(binary == false) os << std::endl;
 }
Member Data Documentation
std::vector<CuMatrix<BaseFloat> > backpropagate_buf_ private
buffers for backward pass
Definition at line 145 of file nnet-nnet.h.
Referenced by Nnet::AppendComponent(), Nnet::AppendNnet(), Nnet::Backpropagate(), Nnet::BackpropagateBuffer(), Nnet::Check(), Nnet::Destroy(), Nnet::InfoBackPropagate(), Nnet::Nnet(), Nnet::operator=(), Nnet::Read(), and Nnet::RemoveComponent().
std::vector<Component*> components_ private
Vector which contains all the components composing the neural network, the components are for example: AffineTransform, Sigmoid, Softmax.
Definition at line 142 of file nnet-nnet.h.
Referenced by Nnet::AppendComponent(), Nnet::Backpropagate(), Nnet::Check(), Nnet::Destroy(), Nnet::Feedforward(), Nnet::GetComponent(), Nnet::GetGradient(), Nnet::GetParams(), Nnet::GetWeights(), Nnet::Info(), Nnet::InfoBackPropagate(), Nnet::InfoGradient(), Nnet::InfoPropagate(), Nnet::InputDim(), Nnet::Nnet(), Nnet::NumComponents(), Nnet::NumParams(), Nnet::operator=(), Nnet::OutputDim(), Nnet::Propagate(), Nnet::Read(), Nnet::RemoveComponent(), Nnet::SetComponent(), Nnet::SetWeights(), and Nnet::Write().
NnetTrainOptions opts_ private
Option class with hyper-parameters passed to UpdatableComponent(s)
Definition at line 148 of file nnet-nnet.h.
Referenced by Nnet::GetTrainOptions(), Nnet::Nnet(), Nnet::operator=(), Nnet::Read(), and Nnet::SetTrainOptions().
std::vector<CuMatrix<BaseFloat> > propagate_buf_ private
buffers for forward pass
Definition at line 144 of file nnet-nnet.h.
Referenced by Nnet::AppendComponent(), Nnet::AppendNnet(), Nnet::Backpropagate(), Nnet::Check(), Nnet::Destroy(), Nnet::Feedforward(), Nnet::InfoPropagate(), Nnet::Nnet(), Nnet::operator=(), Nnet::Propagate(), Nnet::PropagateBuffer(), Nnet::Read(), and Nnet::RemoveComponent().
The documentation for this class was generated from the following files:
nnet/nnet-nnet.h
nnet/nnet-nnet.cc