Kaldi: BinarySumDescriptor Class Reference
BinarySumDescriptor Class Reference
BinarySumDescriptor can represent either A + B, or (A if defined, else B).
#include <nnet-descriptor.h>
Public Types
enum Operation { kSum, kFailover }
Public Member Functions
virtual void GetDependencies (const Index &ind, std::vector< Cindex > *dependencies) const
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
virtual bool IsComputable (const Index &ind, const CindexSet &cindex_set, std::vector< Cindex > *used_inputs) const
This function exists to enable us to manage optional dependencies, i.e.
virtual int32 Dim (const Nnet &nnet) const
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
virtual int32 Modulus () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
Written form is: if op_ == kSum then "Sum(<src1>, <src2>)"; if op_ == kFailover, then "Failover(<src1>, <src2>)" If you need more than binary operations, just use Sum(a, Sum(b, c)).
virtual SumDescriptor * Copy () const
BinarySumDescriptor (Operation op, SumDescriptor *src1, SumDescriptor *src2)
virtual ~BinarySumDescriptor ()
Public Member Functions inherited from SumDescriptor
virtual ~SumDescriptor ()
Private Attributes
Operation op_
SumDescriptor * src1_
SumDescriptor * src2_
Detailed Description
BinarySumDescriptor can represent either A + B, or (A if defined, else B).
Other expressions such as A + (B if defined, else zero), (A if defined, else zero) + (B if defined, else zero), and (A if defined, else B if defined, else zero) can be expressed using combinations of the two provided options for BinarySumDescriptor and the variant
Definition at line 392 of file nnet-descriptor.h.
Member Enumeration Documentation
enum Operation
Enumerator
kSum
kFailover
Definition at line 394 of file nnet-descriptor.h.
                  {
     kSum,  // A + B
     kFailover, // A if defined, else B.
   };
Constructor & Destructor Documentation
BinarySumDescriptor (Operation op, SumDescriptor * src1, SumDescriptor * src2) inline
Definition at line 415 of file nnet-descriptor.h.
Referenced by BinarySumDescriptor::Copy().
                                                                              :
       op_(op), src1_(src1), src2_(src2) {}
virtual ~BinarySumDescriptor () inline virtual
Definition at line 417 of file nnet-descriptor.h.
References BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
 { delete src1_; delete src2_; }
Member Function Documentation
SumDescriptor * Copy () const virtual
Implements SumDescriptor.
Definition at line 357 of file nnet-descriptor.cc.
References BinarySumDescriptor::BinarySumDescriptor(), SumDescriptor::Copy(), BinarySumDescriptor::op_, BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
{
   return new BinarySumDescriptor(op_, src1_->Copy(), src2_->Copy());
 }
int32 Dim (const Nnet & nnet) const virtual
Implements SumDescriptor.
Definition at line 338 of file nnet-descriptor.cc.
References SumDescriptor::Dim(), KALDI_ERR, BinarySumDescriptor::kSum, BinarySumDescriptor::op_, BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
{
   int32 dim1 = src1_->Dim(nnet), dim2 = src2_->Dim(nnet);
   if (dim1 != dim2)
     KALDI_ERR << "Neural net contains " << (op_ == kSum ? "Sum" : "Failover")
               << " expression with inconsistent dimension: " << dim1
               << " vs. " << dim2;
   return dim1;
 }
void GetDependencies (const Index & ind, std::vector< Cindex > * dependencies) const virtual
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
The output list is not necessarily sorted, and this function doesn't make sure that it's unique.
Implements SumDescriptor.
Definition at line 291 of file nnet-descriptor.cc.
References SumDescriptor::GetDependencies(), BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
{
   src1_->GetDependencies(ind, dependencies);
   src2_->GetDependencies(ind, dependencies);
 }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
Implements SumDescriptor.
Definition at line 347 of file nnet-descriptor.cc.
References SumDescriptor::GetNodeDependencies(), BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
{
   src1_->GetNodeDependencies(node_indexes);
   src2_->GetNodeDependencies(node_indexes);
 }
bool IsComputable (const Index & ind, const CindexSet & cindex_set, std::vector< Cindex > * used_inputs) const virtual
This function exists to enable us to manage optional dependencies, i.e.
for making sense of expressions like (A + (B is present)) and (A if present; if not, B). Suppose we are trying to compute the index "ind", and the user represents that "cindex_set" is the set of Cindexes are available to the computation; then this function will return true if we can compute the expression given these inputs; and if so, will output to "used_inputs" the list of Cindexes that this expression will be a summation over.
Parameters
[in] ind The index that we want to compute at the output of the Descriptor.
[in] cindex_set The set of Cindexes that are available at the input of the Descriptor.
[out] used_inputs If non-NULL, if this function returns true then to this vector will be *appended* the inputs that will actually participate in the computation. Else (if non-NULL) it will be left unchanged.
Returns
Returns true if this output is computable given the provided inputs.
Implements SumDescriptor.
Definition at line 297 of file nnet-descriptor.cc.
References SumDescriptor::IsComputable(), KALDI_ASSERT, KALDI_PARANOID_ASSERT, BinarySumDescriptor::kFailover, BinarySumDescriptor::kSum, BinarySumDescriptor::op_, BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
{
   KALDI_PARANOID_ASSERT(op_ == kSum || op_ == kFailover);
   std::vector<Cindex> src1_inputs, src2_inputs;
   bool r = (used_inputs != NULL);
   bool src1_computable = src1_->IsComputable(ind, cindex_set,
                                              r ? &src1_inputs: NULL),
       src2_computable = src2_->IsComputable(ind, cindex_set,
                                             r ? &src2_inputs : NULL);
   if (op_ == kSum) {
     if (src1_computable && src2_computable) {
       if (r) {
         used_inputs->insert(used_inputs->end(),
                             src1_inputs.begin(), src1_inputs.end());
         used_inputs->insert(used_inputs->end(),
                             src2_inputs.begin(), src2_inputs.end());
       }
       return true;
     } else {
       return false;
     }
   } else {
     KALDI_ASSERT(op_ == kFailover);
     if (src1_computable) {
       if (r)
         used_inputs->insert(used_inputs->end(),
                             src1_inputs.begin(), src1_inputs.end());
       return true;
     } else if (src2_computable) {
       if (r)
         used_inputs->insert(used_inputs->end(),
                             src2_inputs.begin(), src2_inputs.end());
       return true;
     } else {
       return false;
     }
   }
 }
int32 Modulus () const virtual
Implements SumDescriptor.
Definition at line 353 of file nnet-descriptor.cc.
References kaldi::Lcm(), SumDescriptor::Modulus(), BinarySumDescriptor::src1_, and BinarySumDescriptor::src2_.
{
   return Lcm(src1_->Modulus(), src2_->Modulus());
 }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Written form is: if op_ == kSum then "Sum(<src1>, <src2>)"; if op_ == kFailover, then "Failover(<src1>, <src2>)" If you need more than binary operations, just use Sum(a, Sum(b, c)).
Implements SumDescriptor.
Definition at line 361 of file nnet-descriptor.cc.
References KALDI_ASSERT, BinarySumDescriptor::kFailover, BinarySumDescriptor::kSum, BinarySumDescriptor::op_, BinarySumDescriptor::src1_, BinarySumDescriptor::src2_, and SumDescriptor::WriteConfig().
{
   KALDI_ASSERT(op_ == kSum || op_ == kFailover);
   if (op_ == kSum) os << "Sum(";
   if (op_ == kFailover) os << "Failover(";
   src1_->WriteConfig(os, node_names);
   os << ", ";
   src2_->WriteConfig(os, node_names);
   os << ")";
 }
Member Data Documentation
Operation op_ private
Definition at line 419 of file nnet-descriptor.h.
Referenced by BinarySumDescriptor::Copy(), BinarySumDescriptor::Dim(), BinarySumDescriptor::IsComputable(), and BinarySumDescriptor::WriteConfig().
SumDescriptor* src1_ private
Definition at line 420 of file nnet-descriptor.h.
Referenced by BinarySumDescriptor::Copy(), BinarySumDescriptor::Dim(), BinarySumDescriptor::GetDependencies(), BinarySumDescriptor::GetNodeDependencies(), BinarySumDescriptor::IsComputable(), BinarySumDescriptor::Modulus(), BinarySumDescriptor::WriteConfig(), and BinarySumDescriptor::~BinarySumDescriptor().
SumDescriptor* src2_ private
Definition at line 421 of file nnet-descriptor.h.
Referenced by BinarySumDescriptor::Copy(), BinarySumDescriptor::Dim(), BinarySumDescriptor::GetDependencies(), BinarySumDescriptor::GetNodeDependencies(), BinarySumDescriptor::IsComputable(), BinarySumDescriptor::Modulus(), BinarySumDescriptor::WriteConfig(), and BinarySumDescriptor::~BinarySumDescriptor().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc