Kaldi: SinusoidDetector Class Reference
SinusoidDetector Class Reference
FeatureExtraction
#include <sinusoid-detection.h>
Classes
struct InfoForBin
struct OptimizedInfo
Public Member Functions
SinusoidDetector (BaseFloat samp_freq, int32 num_samp)
BaseFloat DetectSinusoid (BaseFloat min_energy_change, const VectorBase< BaseFloat > &signal, Sinusoid *sinusoid)
Static Public Member Functions
static void QuadraticMaximizeEqualSpaced (BaseFloat y0, BaseFloat y1, BaseFloat y2, BaseFloat *x, BaseFloat *y)
static void QuadraticMaximize (BaseFloat x1, BaseFloat y0, BaseFloat y1, BaseFloat y2, BaseFloat *x, BaseFloat *y)
static BaseFloat QuadraticInterpolate (BaseFloat x1, BaseFloat y0, BaseFloat y1, BaseFloat y2, BaseFloat x)
Private Member Functions
void ComputeCoarseInfo (const Vector< BaseFloat > &fft, std::vector< InfoForBin > *info) const
void FindCandidateBins (BaseFloat min_energy, const std::vector< InfoForBin > &info, std::vector< int32 > *bins) const
void FindCandidateBins2 (BaseFloat min_energy, const std::vector< InfoForBin > &info, std::vector< int32 > *bins) const
void ComputeBinInfo (const VectorBase< BaseFloat > &signal, int32 bin, InfoForBin *info) const
BaseFloat OptimizeFrequency (const std::vector< InfoForBin > &info, int32 *bin_out, BaseFloat *offset_out) const
void FineOptimizeFrequency (const VectorBase< BaseFloat > &signal, int32 bin, BaseFloat offset, std::vector< InfoForBin > *info, OptimizedInfo *opt_info) const
void ComputeCoefficients ()
void SelfTest (const VectorBase< BaseFloat > &signal, const std::vector< InfoForBin > &info, BaseFloat final_freq, BaseFloat final_energy)
Static Private Member Functions
static void CreateCosAndSin (BaseFloat samp_freq, BaseFloat freq, VectorBase< BaseFloat > *cos, VectorBase< BaseFloat > *sin)
Private Attributes
BaseFloat samp_freq_
int32 num_samples_
int32 num_samples_padded_
SplitRadixRealFft< BaseFloat > fft_
BaseFloat factor1_
BaseFloat factor2_
Matrix< BaseFloat > cos_
Matrix< BaseFloat > sin_
Matrix< BaseFloat > M_
Matrix< BaseFloat > Minv_
Detailed Description
Definition at line 54 of file sinusoid-detection.h.
Constructor & Destructor Documentation
SinusoidDetector (BaseFloat samp_freq, int32 num_samp)
Definition at line 193 of file sinusoid-detection.cc.
References SinusoidDetector::ComputeCoefficients().
                                                     :
     samp_freq_(samp_freq),
     num_samples_(num_samp),
     num_samples_padded_(RoundUpToNearestPowerOfTwo(num_samp)),
     fft_(num_samples_padded_),
     factor1_(3.1),
     factor2_(1.42) {
   ComputeCoefficients();
 }
Member Function Documentation
void ComputeBinInfo (const VectorBase< BaseFloat > & signal, int32 bin, InfoForBin * info) const private
Definition at line 650 of file sinusoid-detection.cc.
References SinusoidDetector::cos_, SinusoidDetector::InfoForBin::cos_dot, rnnlm::d, SinusoidDetector::InfoForBin::energy, KALDI_ASSERT, SinusoidDetector::Minv_, MatrixBase< Real >::Row(), MatrixBase< Real >::RowData(), SinusoidDetector::sin_, SinusoidDetector::InfoForBin::sin_dot, SinusoidDetector::InfoForBin::valid, and kaldi::VecVec().
Referenced by SinusoidDetector::DetectSinusoid(), and SinusoidDetector::FineOptimizeFrequency().
{
   KALDI_ASSERT(!info->valid);  // or wasted time.
   info->valid = true;
   BaseFloat v1 = info->cos_dot = VecVec(cos_.Row(bin), signal);
   BaseFloat v2 = info->sin_dot = VecVec(sin_.Row(bin), signal);
   const BaseFloat *Minv_data = Minv_.RowData(bin);
   BaseFloat a = Minv_data[0], b = Minv_data[1], d = Minv_data[2];
   // compute \delta E = v' M^{-1} v.
   BaseFloat delta_e = v1 * v1 * a + v2 * v2 * d + 2 * v1 * v2 * b;
   info->energy = delta_e;
 }
void ComputeCoarseInfo (const Vector< BaseFloat > & fft, std::vector< InfoForBin > * info) const private
Definition at line 411 of file sinusoid-detection.cc.
References SinusoidDetector::InfoForBin::cos_dot, rnnlm::d, VectorBase< Real >::Data(), SinusoidDetector::InfoForBin::energy, SinusoidDetector::Minv_, SinusoidDetector::num_samples_padded_, MatrixBase< Real >::RowData(), SinusoidDetector::InfoForBin::sin_dot, and SinusoidDetector::InfoForBin::valid.
Referenced by SinusoidDetector::DetectSinusoid().
{
   info->resize(num_samples_padded_ * 2 + 1);  // 4 times resolution of FFT itself.
   const BaseFloat *fft_data = fft.Data();
   int32 num_bins = num_samples_padded_ / 2 + 1;
   for (int32 k = 0; k < num_bins; k++) {
     BaseFloat real, im;
     if (k == 0) {
       real = fft_data[0];
       im = 0.0;
     } else if (k == num_samples_padded_ / 2) {
       real = fft_data[1];
       im = 0.0;
     } else {
       real = fft_data[k * 2];
       im = fft_data[k * 2 + 1];
     }
     // v1 and v2 are the two components of the vector v in the math above.
     BaseFloat v1 = real, v2 = -im;
     // Minv_'s row indexes correspond to frequencies with 4 times more
     // resolution than the FFT bins.
     const BaseFloat *Minv_data = Minv_.RowData(k * 4);
     // The Matrix M^{-1} is of the form [a b; b d]
     BaseFloat a = Minv_data[0], b = Minv_data[1], d = Minv_data[2];
     // compute \delta E = v' M^{-1} v.
     BaseFloat delta_e = v1 * v1 * a + v2 * v2 * d + 2 * v1 * v2 * b;
     InfoForBin &this_info = (*info)[k * 4];
     this_info.valid = true;
     this_info.cos_dot = real;
     this_info.sin_dot = -im;
     this_info.energy = delta_e;
   }
 }
void ComputeCoefficients () private
Definition at line 449 of file sinusoid-detection.cc.
References SinusoidDetector::cos_, SinusoidDetector::CreateCosAndSin(), rnnlm::d, KALDI_ASSERT, kaldi::kUndefined, SinusoidDetector::M_, SinusoidDetector::Minv_, SinusoidDetector::num_samples_, SinusoidDetector::num_samples_padded_, Matrix< Real >::Resize(), SinusoidDetector::samp_freq_, SinusoidDetector::sin_, and kaldi::VecVec().
Referenced by SinusoidDetector::SinusoidDetector().
{
   int32 num_samp = num_samples_;
   int32 num_freq =  num_samples_padded_ * 2 + 1;
   cos_.Resize(num_freq, num_samp);
   sin_.Resize(num_freq, num_samp);
   Vector<BaseFloat> cc(num_freq), cs(num_freq);
   for (int32 k = 0; k < num_freq; k++) {
     BaseFloat freq = k * samp_freq_ / (num_samples_padded_ * 4);
     SubVector<BaseFloat> c(cos_, k), s(sin_, k);
     CreateCosAndSin(samp_freq_, freq, &c, &s);
     cc(k) = VecVec(c, c);
     cs(k) = VecVec(c, s);
   }
   M_.Resize(num_freq, 3, kUndefined);
   Minv_.Resize(num_freq, 3, kUndefined);
   for (int32 k = 0; k < num_freq; k++) {
     // Let the matrix M be [ a b; b d ].   [we don't write c because c == b].
     // We want to compute Minv_.
     BaseFloat a = cc(k), b = cs(k), d = num_samples_ - a;
     M_(k, 0) = a;
     M_(k, 1) = b;
     M_(k, 2) = d;
     if (k == 0 || k == num_freq - 1) {
       // this is a special case; it's not really the inverse of M but it will
       // give us the expression we want; it's like an inverse in just one dimension.
       Minv_(k, 0) = 1.0 / a;
       Minv_(k, 1) = 0.0;
       Minv_(k, 2) = 0.0;
     } else {
       BaseFloat inv_det = 1.0 / (a * d - b * b);
       // check for NaN and inf.
       KALDI_ASSERT(inv_det == inv_det && inv_det - inv_det == 0.0);
       // use: [a b;c d]^-1 = 1/(ad - bc) [d -b; -c a], special case where c = b.
       BaseFloat inv_a = d * inv_det, inv_b = -b * inv_det, inv_d = a * inv_det;
       Minv_(k, 0) = inv_a;
       Minv_(k, 1) = inv_b;
       Minv_(k, 2) = inv_d;
     }
   }
 }
void CreateCosAndSin (BaseFloat samp_freq, BaseFloat freq, VectorBase< BaseFloat > * cos, VectorBase< BaseFloat > * sin) static private
Definition at line 166 of file sinusoid-detection.cc.
References kaldi::ComplexMul(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), KALDI_ASSERT, and M_2PI.
Referenced by SinusoidDetector::ComputeCoefficients(), and SinusoidDetector::FineOptimizeFrequency().
{
   int32 dim = cos_vec->Dim(), batch_size = 100;
   KALDI_ASSERT(dim == sin_vec->Dim());
   BaseFloat *cos_data = cos_vec->Data(), *sin_data = sin_vec->Data();
   BaseFloat factor_real = cos(M_2PI * freq / samp_freq),
       factor_im = sin(M_2PI * freq / samp_freq);
   // process frames in batches of size "batch_size", after which we recompute
   // the starting point to prevent loss of accuracy due to drift.
   for (int32 b = 0; b * batch_size < dim; b++) {
     int32 t_offset = b * batch_size,
         t_end = std::min(dim, t_offset + batch_size);
     double phase = M_2PI * t_offset * freq / samp_freq;
     // treat x as a complex variable which initially is equal to amplitude * exp(i * phase),
     // but which gets multiplied by "factor" on each frame.
     BaseFloat x_real = cos(phase), x_im = sin(phase);
     for (int32 t = t_offset; t < t_end; t++) {
       cos_data[t] = x_real;
       sin_data[t] = x_im;
       ComplexMul(factor_real, factor_im, &x_real, &x_im);  // x *= factor.
     }
   }
 }
BaseFloat DetectSinusoid (BaseFloat min_energy_change, const VectorBase< BaseFloat > & signal, Sinusoid * sinusoid)
Definition at line 282 of file sinusoid-detection.cc.
References Sinusoid::amplitude, SinusoidDetector::OptimizedInfo::bin, SplitRadixRealFft< Real >::Compute(), SinusoidDetector::ComputeBinInfo(), SinusoidDetector::ComputeCoarseInfo(), SinusoidDetector::OptimizedInfo::cos_coeff, VectorBase< Real >::Dim(), SinusoidDetector::OptimizedInfo::energy, SinusoidDetector::fft_, SinusoidDetector::FindCandidateBins(), SinusoidDetector::FindCandidateBins2(), SinusoidDetector::FineOptimizeFrequency(), Sinusoid::freq, kaldi::GetVerboseLevel(), rnnlm::i, KALDI_ASSERT, KALDI_VLOG, VectorBase< Real >::Norm(), SinusoidDetector::num_samples_, SinusoidDetector::num_samples_padded_, SinusoidDetector::OptimizedInfo::offset, SinusoidDetector::OptimizeFrequency(), Sinusoid::phase, SinusoidDetector::samp_freq_, SinusoidDetector::SelfTest(), and SinusoidDetector::OptimizedInfo::sin_coeff.
Referenced by MultiSinusoidDetector::GetNextFrame(), kaldi::UnitTestSinusoidDetector(), and kaldi::UnitTestSinusoidDetectorNoisy().
{
   if (signal(0) == 0.0 && signal.Norm(2.0) == 0.0)
     return 0.0;
   KALDI_ASSERT(signal.Dim() == num_samples_);
   Vector<BaseFloat> fft(num_samples_padded_);
   fft.Range(0, num_samples_).CopyFromVec(signal);
   bool forward = true;
   fft_.Compute(fft.Data(), forward);
   std::vector<InfoForBin> info;
   ComputeCoarseInfo(fft, &info);
   // we now have info for the "coarse" bins.
   // each element b of "bins" will be a multiple of 4: it's possible
   // that the best frequency is in the range [b, b+4]
   std::vector<int32> bins;
   FindCandidateBins(min_energy, info, &bins);
   if (bins.empty())
     return 0.0;  // not enough energy in signal.
   for (size_t i = 0; i < bins.size(); i++) {
     int32 bin = bins[i];
     ComputeBinInfo(signal, bin, &(info[bin]));
   }
   std::vector<int32> bins2;
   FindCandidateBins2(min_energy, info, &bins2);
   for (size_t i = 0; i < bins2.size(); i++) {
     int32 bin = bins2[i];
     ComputeBinInfo(signal, bin, &(info[bin]));
   }
   // compute energy for the predicted-optimum point, which will usually be
   // between bins, with an offset.
   int32 bin;
   BaseFloat offset;
   BaseFloat opt_energy = OptimizeFrequency(info,  &bin, &offset);
   if (opt_energy == 0.0)
     return 0.0;
   BaseFloat max_freq = (bin + offset) * samp_freq_ / (num_samples_padded_ * 4);
   KALDI_VLOG(4) << "Best frequency based on interpolation is "
                 << max_freq << ", best energy is "
                 << opt_energy << ", bin is " << bin;
   OptimizedInfo final_info;
   FineOptimizeFrequency(signal, bin, offset, &info, &final_info);
   // the following while loop will rarely be accessed.
   while (final_info.offset == 0.0 && bin > 0) {
     bin--;
     FineOptimizeFrequency(signal, bin, 1.0, &info, &final_info);
   }
   // the following while loop will rarely be accessed.
   while (final_info.offset == 1.0 && bin < num_samples_padded_ * 2) {
     bin++;
     FineOptimizeFrequency(signal, bin, 0.0, &info, &final_info);
   }
   if (bin <= 1 || bin >= num_samples_padded_ * 2 - 2) {
     // If we're in the lowest or next-to-lowest bin, or the highest or
     // next-to-highest allowed bin (note, "bin" here is a range, and it can
     // never have the value num_samples_padded_ * 2), we tend to get more
     // estimation error than usual, so do another round of optimization.
     FineOptimizeFrequency(signal, bin, final_info.offset, &info, &final_info);
   }
   BaseFloat final_freq = (final_info.bin + final_info.offset) * samp_freq_ / (num_samples_padded_ * 4);
   KALDI_VLOG(4) << "Final optimized info is: freq " << final_freq
                 << ", cos coeff " << final_info.cos_coeff << ", sin coeff "
                 << final_info.sin_coeff << ", energy " << final_info.energy;
   if (GetVerboseLevel() > 1)
     SelfTest(signal, info, final_freq, final_info.energy);
   if (final_info.energy >= min_energy) {
     sinusoid->amplitude = std::sqrt(final_info.cos_coeff * final_info.cos_coeff
                                     + final_info.sin_coeff * final_info.sin_coeff);
     sinusoid->freq = final_freq;
     sinusoid->phase = -std::atan2(final_info.sin_coeff, final_info.cos_coeff);
     KALDI_VLOG(4) << "Phase is " << sinusoid->phase << ", amplitude is "
                   << sinusoid->amplitude << ", freq is " << sinusoid->freq;
     return final_info.energy;
   } else {
     return 0.0;
   }
 }
void FindCandidateBins (BaseFloat min_energy, const std::vector< InfoForBin > & info, std::vector< int32 > * bins) const private
Definition at line 602 of file sinusoid-detection.cc.
References SinusoidDetector::factor1_, KALDI_ASSERT, and SinusoidDetector::num_samples_padded_.
Referenced by SinusoidDetector::DetectSinusoid().
{
   int32 max_bin = num_samples_padded_ * 2;
   BaseFloat cutoff = min_energy;
   for (int32 k = 0; k <= max_bin; k += 4) {
     KALDI_ASSERT(info[k].valid);
     cutoff = std::max(cutoff, info[k].energy);
   }
   for (int32 k = 0; k < max_bin; k += 4) {
     BaseFloat energy_upper_bound =
         factor1_ * std::max(info[k].energy,
                             info[k+4].energy);
     if (energy_upper_bound >= cutoff)
       bins->push_back(k + 2);
   }
 }
void FindCandidateBins2 (BaseFloat min_energy, const std::vector< InfoForBin > & info, std::vector< int32 > * bins) const private
Definition at line 625 of file sinusoid-detection.cc.
References SinusoidDetector::factor2_, and SinusoidDetector::num_samples_padded_.
Referenced by SinusoidDetector::DetectSinusoid().
{
   int32 max_bin = num_samples_padded_ * 2;
   BaseFloat cutoff = min_energy;
   for (int32 k = 0; k <= max_bin; k += 2) {
     if (info[k].valid)
       cutoff = std::max(cutoff, info[k].energy);
   }
   for (int32 k = 0; k < max_bin; k += 2) {
     if (info[k].valid && info[k+2].valid) {
       BaseFloat energy_upper_bound =
           factor2_ * std::max(info[k].energy,
                               info[k+2].energy);
       if (energy_upper_bound >= cutoff)
         bins2->push_back(k + 1);
     }
   }
 }
void FineOptimizeFrequency (const VectorBase< BaseFloat > & signal, int32 bin, BaseFloat offset, std::vector< InfoForBin > * info, OptimizedInfo * opt_info) const private
Definition at line 497 of file sinusoid-detection.cc.
References SinusoidDetector::OptimizedInfo::bin, SinusoidDetector::ComputeBinInfo(), SinusoidDetector::OptimizedInfo::cos_coeff, SinusoidDetector::CreateCosAndSin(), rnnlm::d, SinusoidDetector::OptimizedInfo::energy, epsilon, KALDI_ASSERT, KALDI_VLOG, kaldi::kUndefined, SinusoidDetector::M_, SinusoidDetector::num_samples_, SinusoidDetector::num_samples_padded_, SinusoidDetector::OptimizedInfo::offset, SinusoidDetector::QuadraticInterpolate(), SinusoidDetector::QuadraticMaximize(), MatrixBase< Real >::RowData(), SinusoidDetector::samp_freq_, SinusoidDetector::OptimizedInfo::sin_coeff, and kaldi::VecVec().
Referenced by SinusoidDetector::DetectSinusoid().
{
   std::vector<InfoForBin> &info = *info_in;
   if (!info[bin].valid) ComputeBinInfo(signal, bin, &(info[bin]));
   if (!info[bin+1].valid) ComputeBinInfo(signal, bin+1, &(info[bin+1]));
   const BaseFloat epsilon = 0.02, delta = 0.001;
   // If the offset is very close to the edges of the bin, move it
   // closer to the center.  Otherwise we may have problems with the
   // steps below.  The initial offset is only used as a starting point
   // anyway, so this won't affect the final value much.
   if (bin_offset < epsilon)
     bin_offset = epsilon;
   if (bin_offset > 1.0 - epsilon)
     bin_offset = 1.0 - epsilon;
   KALDI_VLOG(4) << "Initial bin offset = " << bin_offset << ", bin = " << bin;
   // create cos and sin waves of the specified frequency.
   BaseFloat freq = (bin + bin_offset) * samp_freq_ / (num_samples_padded_ * 4);
   Vector<BaseFloat> c(num_samples_, kUndefined), s(num_samples_, kUndefined);
   CreateCosAndSin(samp_freq_, freq, &c, &s);
   // these a, b and d values are the elements of the M matrix at this frequency
   // "freq", i.e. the matrix M_f [ a b; b d ].  This will be invertible because
   // we have ensured that the frequency is not too close to zero or the Nyquist.
   BaseFloat a = VecVec(c, c), b = VecVec(c, s), d = num_samples_ - a;
   BaseFloat inv_det = 1.0 / (a * d - b * b);
   BaseFloat inv_a = d * inv_det, inv_b = -b * inv_det, inv_d = a * inv_det;
   BaseFloat v1 = VecVec(c, signal), v2 = VecVec(s, signal);
   BaseFloat delta_e = v1 * v1 * inv_a + v2 * v2 * inv_d + 2 * v1 * v2 * inv_b;
   KALDI_VLOG(4) << "Actual energy-change at frequency " << freq << " is "
                 << delta_e;
   // "freq" is frequency somewhere in the middle of the bin.
   BaseFloat final_offset, final_energy;
   QuadraticMaximize(bin_offset, info[bin].energy, delta_e, info[bin+1].energy,
                     &final_offset, &final_energy);
   KALDI_VLOG(4) << "After further optimizing, offset was " << final_offset
                 << " giving freq "
                 << ((bin+final_offset) * samp_freq_ / (num_samples_padded_*4))
                 << ", with energy " << final_energy;
   // Use interpolation (using a quadratic function) to get the entries of the M matrix
   // the the final, tuned frequency.  Interpolation on M is better than M^{-1}, as its
   // elements are much better behaved as the frequency varies.
   const BaseFloat *M_left_data = M_.RowData(bin),
       *M_right_data = M_.RowData(bin + 1);
   BaseFloat a_interp = QuadraticInterpolate(bin_offset, M_left_data[0], a, M_right_data[0],
                                             final_offset);
   BaseFloat b_interp = QuadraticInterpolate(bin_offset, M_left_data[1], b, M_right_data[1],
                                             final_offset);
   BaseFloat d_interp = QuadraticInterpolate(bin_offset, M_left_data[2], d, M_right_data[2],
                                             final_offset);
   // Now get the inverse of the M matrix at the final point.
   BaseFloat a_inv_interp, b_inv_interp, d_inv_interp;
   if ((bin == 0 && final_offset < delta) ||
       (bin == num_samples_padded_ * 2 && final_offset > 1.0 - delta)) {
     // If we're extremely close to zero or the Nyquist, we'll have trouble
     // inverting M; just invert in the 1st dimension (only have a cos
     // component).
     a_inv_interp = 1.0 / a_interp;
     b_inv_interp = 0.0;
     d_inv_interp = 0.0;
   } else {
     BaseFloat inv_det = 1.0 / (a_interp * d_interp - b_interp * b_interp);
     // check for NaN and inf.
     KALDI_ASSERT(inv_det == inv_det && inv_det - inv_det == 0.0);
     // use: [a b;c d]^-1 = 1/(ad - bc) [d -b; -c a], special case where c = b.
     a_inv_interp = d_interp * inv_det;
     b_inv_interp = -b_interp * inv_det;
     d_inv_interp = a_interp * inv_det;
   }
   BaseFloat v1_interp = QuadraticInterpolate(bin_offset, info[bin].cos_dot, v1,
                                              info[bin+1].cos_dot, final_offset);
   BaseFloat v2_interp = QuadraticInterpolate(bin_offset, info[bin].sin_dot, v2,
                                              info[bin+1].sin_dot, final_offset);
   opt_info->bin = bin;
   opt_info->offset = final_offset;
   // Recompute the energy-reduction using the more accurate interpolated values of
   // v1 and v2 (the dot-products of the cos and sin with the signal), and
   // of M.
   opt_info->energy = v1_interp * v1_interp * a_inv_interp +
       v2_interp * v2_interp * d_inv_interp +
       2 * v1_interp * v2_interp * b_inv_interp;
   // Compute the coefficients of the cos and sin in the optimal sinusoid, as
   // M^{-1} v.
   opt_info->cos_coeff = a_inv_interp * v1_interp + b_inv_interp * v2_interp;
   opt_info->sin_coeff = b_inv_interp * v1_interp + d_inv_interp * v2_interp;
 }
BaseFloat OptimizeFrequency (const std::vector< InfoForBin > & info, int32 * bin_out, BaseFloat * offset_out) const private
Definition at line 248 of file sinusoid-detection.cc.
References SinusoidDetector::num_samples_padded_, and SinusoidDetector::QuadraticMaximizeEqualSpaced().
Referenced by SinusoidDetector::DetectSinusoid().
{
   BaseFloat max_energy = 0.0;
   *bin_out = -1;
   int32 max_freq =  num_samples_padded_ * 2;
   // For each bin, we consider the frequency range [bin, bin+1, bin+2],
   // and if we have info for all those bins, do a quadratic interpolation to
   // find the maximum within the range.
   for (int32 bin = 0; bin + 2 <= max_freq; bin++) {
     if (info[bin].valid && info[bin+1].valid && info[bin+2].valid) {
       // First handle the left side of the bin.
       BaseFloat best_x, best_y;
       QuadraticMaximizeEqualSpaced(info[bin].energy, info[bin+1].energy,
                                    info[bin+2].energy, &best_x, &best_y);
       if (best_y > max_energy) {
         max_energy = best_y;
         if (best_x <= 1.0) {
           *bin_out = bin;
           *offset_out = best_x;
         } else {
           *bin_out = bin + 1;
           *offset_out = best_x - 1;
         }
       }
     }
   }
   return max_energy;
 }
BaseFloat QuadraticInterpolate (BaseFloat x1, BaseFloat y0, BaseFloat y1, BaseFloat y2, BaseFloat x) static
Definition at line 141 of file sinusoid-detection.cc.
References KALDI_ASSERT.
Referenced by SinusoidDetector::FineOptimizeFrequency().
                  {
   // Let the function be y = a x^2 + b x + c, and
   // suppose we have the values of y(0), y(x1) and y(1),
   // where 0 < x1 < 1.
   // We have y0 = c, y1 = x1^2 a + x1 b + c, and y2 = a + b + c,
   // so c = y0.
   // Also,  x1.y2 - y1 =  a (x1 - x1^2) + (x1 - 1) c, so
   // a = ( (x1 y2 - y1) - (x1 - 1) c) / (x1 - x1^2), and
   // b = y2 - a - c.
   KALDI_ASSERT(x1 >= 0.0 && x1 <= 1.0);
   if (x1 == 0.0) return y0;
   else if (x1 == 1.0) return y2;
   BaseFloat c = y0,
       a = (x1 * y2 - y1 - (x1 - 1.0) * c) / (x1 - x1*x1),
       b = y2 - a - c;
   return a * x * x + b * x + c;
 }
void QuadraticMaximize (BaseFloat x1, BaseFloat y0, BaseFloat y1, BaseFloat y2, BaseFloat * x, BaseFloat * y) static
Definition at line 96 of file sinusoid-detection.cc.
References kaldi::AssertEqual().
Referenced by SinusoidDetector::FineOptimizeFrequency(), and kaldi::UnitTestQuadraticMaximize().
{
   // Let the function be y = a x^2 + b x + c, and
   // suppose we have the values of y(0), y(x1) and y(1),
   // where 0 < x1 < 1.
   // We have y0 = c, y1 = x1^2 a + x1 b + c, and y2 = a + b + c,
   // so c = y0.
   // Also,  x1.y2 - y1 =  a (x1 - x1^2) + (x1 - 1) c, so
   // a = ( (x1 y2 - y1) - (x1 - 1) c) / (x1 - x1^2), and
   // b = y2 - a - c.
   BaseFloat c = y0,
       a = (x1 * y2 - y1 - (x1 - 1.0) * c) / (x1 - x1*x1),
       b = y2 - a - c;
   // TODO: remove these lines.
   AssertEqual(y1, a * x1 * x1 + b * x1 + c);
   AssertEqual(y2, a + b + c);
   if (a >= 0) {
     // The maximum of the function will occur at one of the end points.
     if (y0 > y2) {
       *x_max = 0;
       *y_max = y0;
     } else {
       *x_max = 1.0;
       *y_max = y2;
     }
   } else {
     // derivative y' = 2a x + b.  y' = 0 at x = -b / 2 a.
     BaseFloat x = -b / (2.0 * a);
     if (x <= 0.0) {
       *x_max = 0.0;
       *y_max = y0;
     } else if (x >= 1.0) {
       *x_max = 1.0;
       *y_max = y2;
     } else {
       *x_max = x;
       *y_max = a * x * x + b * x + c;
     }
   }
 }
void QuadraticMaximizeEqualSpaced (BaseFloat y0, BaseFloat y1, BaseFloat y2, BaseFloat * x, BaseFloat * y) static
Definition at line 59 of file sinusoid-detection.cc.
Referenced by SinusoidDetector::OptimizeFrequency(), and kaldi::UnitTestQuadraticMaximizeEqualSpaced().
{
   // Let the function be y = a x^2 + b x + c, and
   // suppose we have the values of y(0), y(1) and y(2).
   // We have y0 = c, y1 = a + b + c, and y2 = 4a + 2b + c,
   // so c = y0.
   // Also, y2 - 2 y1 = 2a - c, so
   // a = (y2 - 2 y1 + c) / 2, and
   // b = y1 - a - c.
   BaseFloat c = y0, a = y2 - 2 * y1 + c, b = y1 - a - c;
   if (a >= 0) {
     // The maximum of the function will occur at one of the end points.
     if (y0 > y2) {
       *x_max = 0;
       *y_max = y0;
     } else {
       *x_max = 2;
       *y_max = y2;
     }
   } else {
     // derivative y' = 2a x + b.  y' = 0 at x = -b / 2 a.
     BaseFloat x = -b / (2.0 * a);
     if (x <= 0.0) {
       *x_max = 0;
       *y_max = y0;
     } else if (x >= 2.0) {
       *x_max = 0;
       *y_max = y2;
     } else {
       *x_max = x;
       *y_max = a * x * x + b * x + c;
     }
   }
 }
void SelfTest (const VectorBase< BaseFloat > & signal, const std::vector< InfoForBin > & info, BaseFloat final_freq, BaseFloat final_energy) private
Definition at line 204 of file sinusoid-detection.cc.
References SinusoidDetector::factor1_, SinusoidDetector::factor2_, KALDI_WARN, SinusoidDetector::num_samples_, SinusoidDetector::num_samples_padded_, and SinusoidDetector::samp_freq_.
Referenced by SinusoidDetector::DetectSinusoid().
{
   int32 num_bins = num_samples_padded_ * 2 + 1;
   {
     BaseFloat cutoff = 0.0;
     for (int32 k = 0; k <= num_bins; k += 4)
       cutoff = std::max(cutoff, info[k].energy);
     BaseFloat energy_upper_bound = factor1_ * cutoff;
     if (final_energy > energy_upper_bound) {
       KALDI_WARN << "Self-testing failed [factor1]: "
                  << final_energy << " > " << energy_upper_bound
                  << ", num-samples is " << num_samples_
                  << ", freq/nyquist = "
                  << (final_freq / (samp_freq_ * 0.5))
                  << "- would require factor1 >= "
                  << (final_energy / cutoff);
     }
   }
   {
     BaseFloat cutoff = 0.0;
     for (int32 k = 0; k <= num_bins; k += 2)
       if (info[k].valid)
         cutoff = std::max(cutoff, info[k].energy);
     BaseFloat energy_upper_bound = factor2_ * cutoff;
     if (final_energy > energy_upper_bound) {
       KALDI_WARN << "Self-testing failed [factor2]: "
                  << final_energy << " > " << energy_upper_bound
                  << ", num-samples is " << num_samples_
                  << ", freq/nyquist = "
                  << (final_freq / (samp_freq_ * 0.5))
                  << "- would require factor2 >= "
                  << (final_energy / cutoff);
     }
   }
 }
Member Data Documentation
Matrix<BaseFloat> cos_ private
Definition at line 115 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeBinInfo(), and SinusoidDetector::ComputeCoefficients().
BaseFloat factor1_ private
Definition at line 100 of file sinusoid-detection.h.
Referenced by SinusoidDetector::FindCandidateBins(), and SinusoidDetector::SelfTest().
BaseFloat factor2_ private
Definition at line 109 of file sinusoid-detection.h.
Referenced by SinusoidDetector::FindCandidateBins2(), and SinusoidDetector::SelfTest().
SplitRadixRealFft<BaseFloat> fft_ private
Definition at line 98 of file sinusoid-detection.h.
Referenced by SinusoidDetector::DetectSinusoid().
Matrix<BaseFloat> M_ private
Definition at line 125 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeCoefficients(), and SinusoidDetector::FineOptimizeFrequency().
Matrix<BaseFloat> Minv_ private
Definition at line 130 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeBinInfo(), SinusoidDetector::ComputeCoarseInfo(), and SinusoidDetector::ComputeCoefficients().
int32 num_samples_ private
Definition at line 96 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeCoefficients(), SinusoidDetector::DetectSinusoid(), SinusoidDetector::FineOptimizeFrequency(), and SinusoidDetector::SelfTest().
int32 num_samples_padded_ private
Definition at line 97 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeCoarseInfo(), SinusoidDetector::ComputeCoefficients(), SinusoidDetector::DetectSinusoid(), SinusoidDetector::FindCandidateBins(), SinusoidDetector::FindCandidateBins2(), SinusoidDetector::FineOptimizeFrequency(), SinusoidDetector::OptimizeFrequency(), and SinusoidDetector::SelfTest().
BaseFloat samp_freq_ private
Definition at line 95 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeCoefficients(), SinusoidDetector::DetectSinusoid(), SinusoidDetector::FineOptimizeFrequency(), and SinusoidDetector::SelfTest().
Matrix<BaseFloat> sin_ private
Definition at line 118 of file sinusoid-detection.h.
Referenced by SinusoidDetector::ComputeBinInfo(), and SinusoidDetector::ComputeCoefficients().
The documentation for this class was generated from the following files:
feat/sinusoid-detection.h
feat/sinusoid-detection.cc