Kaldi: ScalarClusterable Class Reference
ScalarClusterable Class Reference
Classes and functions related to clustering
ScalarClusterable clusters scalars with x^2 loss.
#include <clusterable-classes.h>
Public Member Functions
ScalarClusterable ()
ScalarClusterable (BaseFloat x)
virtual std::string Type () const
Return a string that describes the inherited type.
virtual BaseFloat Objf () const
Return the objective function associated with the stats [assuming ML estimation].
virtual void SetZero ()
Set stats to empty.
virtual void Add (const Clusterable &other_in)
Add other stats.
virtual void Sub (const Clusterable &other_in)
Subtract other stats.
virtual Clusterable * Copy () const
Return a copy of this object.
virtual BaseFloat Normalizer () const
Return the normalizer (typically, count) associated with the stats.
virtual void Write (std::ostream &os, bool binary) const
Write data to stream.
virtual Clusterable * ReadNew (std::istream &is, bool binary) const
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
std::string Info ()
BaseFloat Mean ()
Public Member Functions inherited from Clusterable
virtual void Scale (BaseFloat f)
Scale the stats by a positive number f [not mandatory to supply this].
virtual ~Clusterable ()
virtual BaseFloat ObjfPlus (const Clusterable &other) const
Return the objective function of the combined object this + other.
virtual BaseFloat ObjfMinus (const Clusterable &other) const
Return the objective function of the subtracted object this - other.
virtual BaseFloat Distance (const Clusterable &other) const
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Private Member Functions
void Read (std::istream &is, bool binary)
Private Attributes
BaseFloat x_
BaseFloat x2_
BaseFloat count_
Detailed Description
ScalarClusterable clusters scalars with x^2 loss.
Definition at line 38 of file clusterable-classes.h.
Constructor & Destructor Documentation
ScalarClusterable () inline
Definition at line 40 of file clusterable-classes.h.
Referenced by ScalarClusterable::Copy(), and ScalarClusterable::ReadNew().
 : x_(0), x2_(0), count_(0) {}
ScalarClusterable (BaseFloat x) inline explicit
Definition at line 41 of file clusterable-classes.h.
 : x_(x), x2_(x*x), count_(1) {}
Member Function Documentation
void Add (const Clusterable & other) virtual
Add other stats.
Implements Clusterable.
Definition at line 78 of file clusterable-classes.cc.
References ScalarClusterable::count_, KALDI_ASSERT, Clusterable::Type(), ScalarClusterable::x2_, and ScalarClusterable::x_.
Referenced by ScalarClusterable::Copy(), and kaldi::TestAddToClustersOptimized().
{
   KALDI_ASSERT(other_in.Type() == "scalar");
   const ScalarClusterable *other =
       static_cast<const ScalarClusterable*>(&other_in);
   x_ += other->x_;
   x2_ += other->x2_;
   count_ += other->count_;
 }
Clusterable * Copy () const virtual
Return a copy of this object.
Implements Clusterable.
Definition at line 96 of file clusterable-classes.cc.
References ScalarClusterable::Add(), and ScalarClusterable::ScalarClusterable().
Referenced by kaldi::TestAddToClusters().
{
   ScalarClusterable *ans = new ScalarClusterable();
   ans->Add(*this);
   return ans;
 }
std::string Info ()
Definition at line 122 of file clusterable-classes.cc.
References ScalarClusterable::count_, ScalarClusterable::x2_, and ScalarClusterable::x_.
{
   std::stringstream str;
   if (count_ == 0) {
     str << "[empty]";
   } else {
     str << "[mean " << (x_ / count_) << ", var " << (x2_ / count_ -
         (x_ * x_ / (count_ * count_))) << "]";
   }
   return str.str();
 }
BaseFloat Mean () inline
Definition at line 57 of file clusterable-classes.h.
References ScalarClusterable::count_, and ScalarClusterable::x_.
Referenced by kaldi::TestAddToClusters().
 { return (count_ != 0 ? x_/count_ : 0.0); }
virtual BaseFloat Normalizer () const inline virtual
Return the normalizer (typically, count) associated with the stats.
Implements Clusterable.
Definition at line 48 of file clusterable-classes.h.
References ScalarClusterable::count_.
{
     return static_cast<BaseFloat>(count_);
   }
BaseFloat Objf () const virtual
Return the objective function associated with the stats [assuming ML estimation].
Implements Clusterable.
Definition at line 69 of file clusterable-classes.cc.
References ScalarClusterable::count_, KALDI_ASSERT, ScalarClusterable::x2_, and ScalarClusterable::x_.
Referenced by kaldi::TestDistance(), kaldi::TestObjfMinus(), kaldi::TestObjfPlus(), and kaldi::TestSumObjfAndSumNormalizer().
{
   if (count_ == 0) {
     return 0;
   } else {
     KALDI_ASSERT(count_ > 0);
     return -(x2_ - x_ * x_ / count_);
   }
 }
void Read (std::istream & is, bool binary) private
Definition at line 115 of file clusterable-classes.cc.
References ScalarClusterable::count_, kaldi::ExpectToken(), kaldi::ReadBasicType(), ScalarClusterable::x2_, and ScalarClusterable::x_.
Referenced by ScalarClusterable::ReadNew().
{
   ExpectToken(is, binary, "SCL");
   ReadBasicType(is, binary, &x_);
   ReadBasicType(is, binary, &x2_);
   ReadBasicType(is, binary, &count_);
 }
Clusterable * ReadNew (std::istream & os, bool binary) const virtual
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
Implements Clusterable.
Definition at line 109 of file clusterable-classes.cc.
References ScalarClusterable::Read(), and ScalarClusterable::ScalarClusterable().
{
   ScalarClusterable *sc = new ScalarClusterable();
   sc->Read(is, binary);
   return sc;
 }
virtual void SetZero () inline virtual
Set stats to empty.
Implements Clusterable.
Definition at line 44 of file clusterable-classes.h.
References ScalarClusterable::count_, ScalarClusterable::x2_, and ScalarClusterable::x_.
 { count_ = x_ = x2_ = 0.0; }
void Sub (const Clusterable & other) virtual
Subtract other stats.
Implements Clusterable.
Definition at line 87 of file clusterable-classes.cc.
References ScalarClusterable::count_, KALDI_ASSERT, Clusterable::Type(), ScalarClusterable::x2_, and ScalarClusterable::x_.
{
   KALDI_ASSERT(other_in.Type() == "scalar");
   const ScalarClusterable *other =
       static_cast<const ScalarClusterable*>(&other_in);
   x_ -= other->x_;
   x2_ -= other->x2_;
   count_ -= other->count_;
 }
virtual std::string Type () const inline virtual
Return a string that describes the inherited type.
Implements Clusterable.
Definition at line 42 of file clusterable-classes.h.
 { return "scalar"; }
void Write (std::ostream & os, bool binary) const virtual
Write data to stream.
Implements Clusterable.
Definition at line 102 of file clusterable-classes.cc.
References ScalarClusterable::count_, kaldi::WriteBasicType(), kaldi::WriteToken(), ScalarClusterable::x2_, and ScalarClusterable::x_.
{
   WriteToken(os, binary, "SCL");  // magic string.
   WriteBasicType(os, binary, x_);
   WriteBasicType(os, binary, x2_);
   WriteBasicType(os, binary, count_);
 }
Member Data Documentation
BaseFloat count_ private
Definition at line 61 of file clusterable-classes.h.
Referenced by ScalarClusterable::Add(), ScalarClusterable::Info(), ScalarClusterable::Mean(), ScalarClusterable::Normalizer(), ScalarClusterable::Objf(), ScalarClusterable::Read(), ScalarClusterable::SetZero(), ScalarClusterable::Sub(), and ScalarClusterable::Write().
BaseFloat x2_ private
Definition at line 60 of file clusterable-classes.h.
Referenced by ScalarClusterable::Add(), ScalarClusterable::Info(), ScalarClusterable::Objf(), ScalarClusterable::Read(), ScalarClusterable::SetZero(), ScalarClusterable::Sub(), and ScalarClusterable::Write().
BaseFloat x_ private
Definition at line 59 of file clusterable-classes.h.
Referenced by ScalarClusterable::Add(), ScalarClusterable::Info(), ScalarClusterable::Mean(), ScalarClusterable::Objf(), ScalarClusterable::Read(), ScalarClusterable::SetZero(), ScalarClusterable::Sub(), and ScalarClusterable::Write().
The documentation for this class was generated from the following files:
tree/clusterable-classes.h
tree/clusterable-classes.cc