Kaldi: ShiftedDeltaFeatures Class Reference
ShiftedDeltaFeatures Class Reference
FeatureExtraction
#include <feature-functions.h>
Public Member Functions
ShiftedDeltaFeatures (const ShiftedDeltaFeaturesOptions &opts)
void Process (const MatrixBase< BaseFloat > &input_feats, int32 frame, SubVector< BaseFloat > *output_frame) const
Private Attributes
ShiftedDeltaFeaturesOptions opts_
Vector< BaseFloat > scales_
Detailed Description
Definition at line 244 of file feature-functions.h.
Constructor & Destructor Documentation
ShiftedDeltaFeatures (const ShiftedDeltaFeaturesOptions & opts) explicit
Definition at line 269 of file feature-functions.cc.
References rnnlm::j, KALDI_ASSERT, Vector< Real >::Resize(), VectorBase< Real >::Scale(), ShiftedDeltaFeatures::scales_, and ShiftedDeltaFeaturesOptions::window.
                                           : opts_(opts) {
   KALDI_ASSERT(opts.window > 0 && opts.window < 1000);
   // Default window is 1.
   int32 window = opts.window;
   KALDI_ASSERT(window != 0);
   scales_.Resize(1 + 2*window);  // also zeros it.
   BaseFloat normalizer = 0.0;
   for (int32 j = -window; j <= window; j++) {
     normalizer += j*j;
     scales_(j + window) += static_cast<BaseFloat>(j);
   }
   scales_.Scale(1.0 / normalizer);
 }
Member Function Documentation
void Process (const MatrixBase< BaseFloat > & input_feats, int32 frame, SubVector< BaseFloat > * output_frame) const
Definition at line 285 of file feature-functions.cc.
References VectorBase< Real >::AddVec(), ShiftedDeltaFeaturesOptions::block_shift, VectorBase< Real >::Dim(), rnnlm::i, rnnlm::j, KALDI_ASSERT, ShiftedDeltaFeaturesOptions::num_blocks, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ShiftedDeltaFeatures::opts_, MatrixBase< Real >::Row(), ShiftedDeltaFeatures::scales_, and VectorBase< Real >::SetZero().
Referenced by kaldi::ComputeShiftedDeltas().
{
   KALDI_ASSERT(frame < input_feats.NumRows());
   int32 num_frames = input_feats.NumRows(),
       feat_dim = input_feats.NumCols();
   KALDI_ASSERT(static_cast<int32>(output_frame->Dim())
                == feat_dim * (opts_.num_blocks + 1));
   output_frame->SetZero();
   // The original features
   SubVector<BaseFloat> output(*output_frame, 0, feat_dim);
   output.AddVec(1.0, input_feats.Row(frame));
   // Concatenate the delta-blocks. Each block is block_shift
   // (usually 3) frames apart.
   for (int32 i = 0; i < opts_.num_blocks; i++) {
     int32 max_offset = (scales_.Dim() - 1) / 2;
     SubVector<BaseFloat> output(*output_frame, (i + 1) * feat_dim, feat_dim);
     for (int32 j = -max_offset; j <= max_offset; j++) {
       int32 offset_frame = frame + j + i * opts_.block_shift;
       if (offset_frame < 0) offset_frame = 0;
       else if (offset_frame >= num_frames)
         offset_frame = num_frames - 1;
       BaseFloat scale = scales_(j + max_offset);
       if (scale != 0.0)
         output.AddVec(scale, input_feats.Row(offset_frame));
     }
   }
 }
Member Data Documentation
ShiftedDeltaFeaturesOptions opts_ private
Definition at line 258 of file feature-functions.h.
Referenced by ShiftedDeltaFeatures::Process().
Vector<BaseFloat> scales_ private
Definition at line 259 of file feature-functions.h.
Referenced by ShiftedDeltaFeatures::Process(), and ShiftedDeltaFeatures::ShiftedDeltaFeatures().
The documentation for this class was generated from the following files:
feat/feature-functions.h
feat/feature-functions.cc