Kaldi: UpdatableComponent Class Reference
UpdatableComponent Class Reference abstract
Class UpdatableComponent is a Component which has trainable parameters and contains some global parameters for stochastic gradient descent (learning rate, L2 regularization constant).
#include <nnet-component.h>
Public Member Functions
UpdatableComponent (const UpdatableComponent &other)
void Init (BaseFloat learning_rate)
UpdatableComponent (BaseFloat learning_rate)
virtual void SetZero (bool treat_as_gradient)=0
Set parameters to zero, and if treat_as_gradient is true, we'll be treating this as a gradient so set the learning rate to 1 and make any other changes necessary (there's a variable we have to set for the MixtureProbComponent).
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual BaseFloat DotProduct (const UpdatableComponent &other) const =0
Here, "other" is a component of the same specific type.
virtual void PerturbParams (BaseFloat stddev)=0
We introduce a new virtual function that only applies to class UpdatableComponent.
virtual void Scale (BaseFloat scale)=0
This new virtual function scales the parameters by this amount.
virtual void Add (BaseFloat alpha, const UpdatableComponent &other)=0
This new virtual function adds the parameters of another updatable component, times some constant, to the current parameters.
void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
virtual std::string Info () const
virtual int32 GetParameterDim () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
Public Member Functions inherited from Component
Component ()
virtual std::string Type () const =0
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual void InitFromString (std::string args)=0
Initialize, typically from a line of a config file.
virtual int32 InputDim () const =0
Get size of input vectors.
virtual int32 OutputDim () const =0
Get size of output vectors.
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const =0
Perform forward pass propagation Input->Output.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const =0
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const =0
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)=0
virtual void Write (std::ostream &os, bool binary) const =0
Write component to stream.
virtual ~Component ()
Protected Attributes
BaseFloat learning_rate_
learning rate (0.0..0.01)
Private Member Functions
const UpdatableComponent & operator= (const UpdatableComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
Class UpdatableComponent is a Component which has trainable parameters and contains some global parameters for stochastic gradient descent (learning rate, L2 regularization constant).
This is a base-class for Components with parameters.
Definition at line 279 of file nnet-component.h.
Constructor & Destructor Documentation
UpdatableComponent (const UpdatableComponent & other) inline
Definition at line 281 of file nnet-component.h.
                                                      :
       learning_rate_(other.learning_rate_){ }
UpdatableComponent (BaseFloat learning_rate) inline
Definition at line 287 of file nnet-component.h.
References UpdatableComponent::Init().
{
     Init(learning_rate);
   }
UpdatableComponent () inline
Definition at line 297 of file nnet-component.h.
 : learning_rate_(0.001) { }
virtual ~UpdatableComponent () inline virtual
Definition at line 299 of file nnet-component.h.
 { }
Member Function Documentation
virtual void Add (BaseFloat alpha, const UpdatableComponent & other) pure virtual
This new virtual function adds the parameters of another updatable component, times some constant, to the current parameters.
Implemented in Convolutional1dComponent, BlockAffineComponent, and AffineComponent.
Referenced by Nnet::AddNnet(), and main().
virtual BaseFloat DotProduct (const UpdatableComponent & other) const pure virtual
Here, "other" is a component of the same specific type.
This function computes the dot product in parameters, and is computed while automatically adjusting learning rates; typically, one of the two will actually contain the gradient.
Implemented in Convolutional1dComponent, BlockAffineComponent, and AffineComponent.
Referenced by Nnet::ComponentDotProducts(), kaldi::nnet2::ComputeObjfAndGradient(), FastNnetCombiner::ComputeObjfAndGradient(), FisherComputationClass::operator()(), and kaldi::nnet2::UnitTestGenericComponentInternal().
virtual int32 GetParameterDim () const inline virtual
The following new virtual function returns the total dimension of the parameters in this class.
E.g. used for L-BFGS update
Reimplemented in Convolutional1dComponent, BlockAffineComponent, and AffineComponent.
Definition at line 333 of file nnet-component.h.
References KALDI_ASSERT.
Referenced by Nnet::GetParameterDim(), main(), Nnet::UnVectorize(), and Nnet::Vectorize().
 { KALDI_ASSERT(0); return 0; }
std::string Info () const virtual
Reimplemented from Component.
Reimplemented in Convolutional1dComponent, AffineComponentPreconditionedOnline, AffineComponentPreconditioned, and AffineComponent.
Definition at line 312 of file nnet-component.cc.
References Component::InputDim(), UpdatableComponent::LearningRate(), Component::OutputDim(), and Component::Type().
{
   std::stringstream stream;
   stream << Type() << ", input-dim=" << InputDim()
          << ", output-dim=" << OutputDim() << ", learning-rate="
          << LearningRate();
   return stream.str();
 }
void Init (BaseFloat learning_rate) inline
Definition at line 284 of file nnet-component.h.
References UpdatableComponent::learning_rate_.
Referenced by AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), BlockAffineComponent::Init(), Convolutional1dComponent::Init(), and UpdatableComponent::UpdatableComponent().
{
     learning_rate_ = learning_rate;
   }
BaseFloat LearningRate () const inline
Gets the learning rate of gradient descent.
Definition at line 323 of file nnet-component.h.
References UpdatableComponent::learning_rate_.
Referenced by kaldi::nnet2::CombineNnetsA(), Nnet::GetLearningRates(), UpdatableComponent::Info(), AffineComponent::Info(), AffineComponentPreconditioned::Info(), AffineComponentPreconditionedOnline::Info(), Convolutional1dComponent::Info(), and Nnet::ScaleLearningRates().
 { return learning_rate_; }
const UpdatableComponent& operator= (const UpdatableComponent & other) private
virtual void PerturbParams (BaseFloat stddev) pure virtual
We introduce a new virtual function that only applies to class UpdatableComponent.
This is used in testing.
Implemented in Convolutional1dComponent, BlockAffineComponent, and AffineComponent.
Referenced by main(), and kaldi::nnet2::UnitTestGenericComponentInternal().
virtual void Scale (BaseFloat scale) pure virtual
This new virtual function scales the parameters by this amount.
Implemented in Convolutional1dComponent, BlockAffineComponent, and AffineComponent.
Referenced by Nnet::AddNnet(), main(), NnetRescaler::RescaleComponent(), Nnet::Scale(), and Nnet::ScaleComponents().
void SetLearningRate (BaseFloat lrate) inline
Sets the learning rate of gradient descent.
Definition at line 321 of file nnet-component.h.
References UpdatableComponent::learning_rate_.
Referenced by kaldi::nnet2::CombineNnetsA(), Nnet::ScaleLearningRates(), Nnet::SetLearningRates(), AffineComponent::SetZero(), BlockAffineComponent::SetZero(), and Convolutional1dComponent::SetZero().
 {  learning_rate_ = lrate; }
virtual void SetZero (bool treat_as_gradient) pure virtual
Set parameters to zero, and if treat_as_gradient is true, we'll be treating this as a gradient so set the learning rate to 1 and make any other changes necessary (there's a variable we have to set for the MixtureProbComponent).
Implemented in Convolutional1dComponent, BlockAffineComponentPreconditioned, BlockAffineComponent, and AffineComponent.
Referenced by main(), and Nnet::SetZero().
virtual void UnVectorize (const VectorBase< BaseFloat > & params) inline virtual
Converts the parameters from vector form.
Reimplemented in BlockAffineComponent, and AffineComponent.
Definition at line 340 of file nnet-component.h.
References KALDI_ASSERT.
Referenced by Nnet::UnVectorize().
{
     KALDI_ASSERT(0);
   }
virtual void Vectorize (VectorBase< BaseFloat > * params) const inline virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented in BlockAffineComponent, and AffineComponent.
Definition at line 338 of file nnet-component.h.
References KALDI_ASSERT.
Referenced by main(), and Nnet::Vectorize().
 { KALDI_ASSERT(0); }
Member Data Documentation
BaseFloat learning_rate_ protected
learning rate (0.0..0.01)
Definition at line 345 of file nnet-component.h.
Referenced by AffineComponentPreconditionedOnline::AffineComponentPreconditionedOnline(), AffineComponent::Copy(), AffineComponentPreconditioned::Copy(), AffineComponentPreconditionedOnline::Copy(), BlockAffineComponent::Copy(), BlockAffineComponentPreconditioned::Copy(), Convolutional1dComponent::Copy(), AffineComponentPreconditioned::GetScalingFactor(), AffineComponentPreconditionedOnline::GetScalingFactor(), UpdatableComponent::Init(), AffineComponent::InitFromString(), AffineComponentPreconditioned::InitFromString(), AffineComponentPreconditionedOnline::InitFromString(), BlockAffineComponent::InitFromString(), BlockAffineComponentPreconditioned::InitFromString(), Convolutional1dComponent::InitFromString(), UpdatableComponent::LearningRate(), AffineComponent::Read(), AffineComponentPreconditioned::Read(), AffineComponentPreconditionedOnline::Read(), BlockAffineComponent::Read(), BlockAffineComponentPreconditioned::Read(), Convolutional1dComponent::Read(), UpdatableComponent::SetLearningRate(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), BlockAffineComponentPreconditioned::Update(), Convolutional1dComponent::Update(), AffineComponent::UpdateSimple(), BlockAffineComponent::UpdateSimple(), AffineComponent::Write(), AffineComponentPreconditioned::Write(), AffineComponentPreconditionedOnline::Write(), BlockAffineComponent::Write(), BlockAffineComponentPreconditioned::Write(), and Convolutional1dComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc