Kaldi: OnlineSpliceFrames Class Reference
OnlineSpliceFrames Class Reference
OnlineFeatureExtraction
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
OnlineSpliceFrames (const OnlineSpliceOptions &opts, OnlineFeatureInterface *src)
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Attributes
int32 left_context_
int32 right_context_
OnlineFeatureInterface * src_
Detailed Description
Definition at line 391 of file online-feature.h.
Constructor & Destructor Documentation
OnlineSpliceFrames (const OnlineSpliceOptions & opts, OnlineFeatureInterface * src) inline
Definition at line 411 of file online-feature.h.
                                                  :
       left_context_(opts.left_context), right_context_(opts.right_context),
       src_(src) { }
Member Function Documentation
virtual int32 Dim () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 396 of file online-feature.h.
References OnlineFeatureInterface::Dim(), OnlineSpliceFrames::left_context_, OnlineSpliceFrames::right_context_, and OnlineSpliceFrames::src_.
{
     return src_->Dim() * (1 + left_context_ + right_context_);
   }
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 383 of file online-feature.cc.
References OnlineFeatureInterface::Dim(), VectorBase< Real >::Dim(), OnlineFeatureInterface::GetFrame(), KALDI_ASSERT, OnlineSpliceFrames::left_context_, rnnlm::n, OnlineFeatureInterface::NumFramesReady(), OnlineSpliceFrames::NumFramesReady(), OnlineSpliceFrames::right_context_, and OnlineSpliceFrames::src_.
{
   KALDI_ASSERT(left_context_ >= 0 && right_context_ >= 0);
   KALDI_ASSERT(frame >= 0 && frame < NumFramesReady());
   int32 dim_in = src_->Dim();
   KALDI_ASSERT(feat->Dim() == dim_in * (1 + left_context_ + right_context_));
   int32 T = src_->NumFramesReady();
   for (int32 t2 = frame - left_context_; t2 <= frame + right_context_; t2++) {
     int32 t2_limited = t2;
     if (t2_limited < 0) t2_limited = 0;
     if (t2_limited >= T) t2_limited = T - 1;
     int32 n = t2 - (frame - left_context_);  // 0 for left-most frame,
                                              // increases to the right.
     SubVector<BaseFloat> part(*feat, n * dim_in, dim_in);
     src_->GetFrame(t2_limited, &part);
   }
 }
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 400 of file online-feature.h.
References OnlineFeatureInterface::IsLastFrame(), and OnlineSpliceFrames::src_.
{
     return src_->IsLastFrame(frame);
   }
int32 NumFramesReady () const virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 375 of file online-feature.cc.
References OnlineFeatureInterface::IsLastFrame(), OnlineFeatureInterface::NumFramesReady(), OnlineSpliceFrames::right_context_, and OnlineSpliceFrames::src_.
Referenced by OnlineSpliceFrames::GetFrame().
{
   int32 num_frames = src_->NumFramesReady();
   if (num_frames > 0 && src_->IsLastFrame(num_frames-1))
     return num_frames;
   else
     return std::max<int32>(0, num_frames - right_context_);
 }
Member Data Documentation
int32 left_context_ private
Definition at line 417 of file online-feature.h.
Referenced by OnlineSpliceFrames::Dim(), and OnlineSpliceFrames::GetFrame().
int32 right_context_ private
Definition at line 418 of file online-feature.h.
Referenced by OnlineSpliceFrames::Dim(), OnlineSpliceFrames::GetFrame(), and OnlineSpliceFrames::NumFramesReady().
OnlineFeatureInterface* src_ private
Definition at line 419 of file online-feature.h.
Referenced by OnlineSpliceFrames::Dim(), OnlineSpliceFrames::GetFrame(), OnlineSpliceFrames::IsLastFrame(), and OnlineSpliceFrames::NumFramesReady().
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc