Kaldi: Sigmoid Class Reference
Sigmoid Class Reference
#include <nnet-activation.h>
Public Member Functions
Sigmoid (int32 dim_in, int32 dim_out)
~Sigmoid ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if contains trainable parameters.
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Optionally print some additional info.
virtual std::string InfoGradient () const
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Member Functions inherited from Component
virtual void InitData (std::istream &is)
Initialize internal data of a component.
virtual void ReadData (std::istream &is, bool binary)
Reads the component content.
virtual void WriteData (std::ostream &os, bool binary) const
Writes the component content.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Definition at line 151 of file nnet-activation.h.
Constructor & Destructor Documentation
Sigmoid (int32 dim_in, int32 dim_out) inline
Definition at line 153 of file nnet-activation.h.
Referenced by Sigmoid::Copy().
     : Component(dim_in, dim_out)
   { }
~Sigmoid () inline
Definition at line 156 of file nnet-activation.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 167 of file nnet-activation.h.
References CuMatrixBase< Real >::DiffSigmoid().
{
     // ey = y(1-y)ex
     in_diff->DiffSigmoid(out, out_diff);
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 159 of file nnet-activation.h.
References Sigmoid::Sigmoid().
 { return new Sigmoid(*this); }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 160 of file nnet-activation.h.
References Component::kSigmoid.
 { return kSigmoid; }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 162 of file nnet-activation.h.
References CuMatrixBase< Real >::Sigmoid().
{
     // y = 1/(1+e^-x)
     out->Sigmoid(in);
   }
The documentation for this class was generated from the following file:
nnet/nnet-activation.h