Kaldi: NBestDecoder Class Reference
NBestDecoder Class Reference
Caution: this decoder was written essentially as testing code for lattice-faster-decoder, and is not very useful; it would be better to pipe the lattices from lattice-faster-decoder into lattice-to-nbest if you want an n-best list.
#include <nbest-decoder.h>
Classes
class TokenStore
Public Types
typedef fst::StdArc Arc
typedef Arc::Label Label
typedef Arc::StateId StateId
typedef Arc::Weight Weight
Public Member Functions
NBestDecoder (const fst::Fst< fst::StdArc > &fst, NBestDecoderOptions opts)
void SetOptions (const NBestDecoderOptions &opts)
~NBestDecoder ()
void Decode (DecodableInterface *decodable)
bool ReachedFinal ()
bool GetNBestLattice (fst::MutableFst< CompactLatticeArc > *fst_out, bool *was_final, int32 *nbest, BaseFloat *nbest_beam, bool use_final_probs=true)
Private Types
typedef TokenStore::Token Token
typedef TokenStore::SeqToken SeqToken
typedef HashList< StateId,
Token * > TokenHash
typedef TokenHash::Elem Elem
typedef unordered_set< StateId > StateQueue
Private Member Functions
BaseFloat GetCutoff (Elem *list_head, size_t *tok_count, BaseFloat *adaptive_beam, Elem **best_elem)
Gets the weight cutoff. Also counts the active tokens.
void PossiblyResizeHash (size_t num_toks)
BaseFloat PropagateEmitting (int32 frame)
void PropagateEpsilon (BaseFloat adaptive_beam)
void ClearToks (Elem *list)
Private Attributes
TokenHash toks_
const fst::Fst< fst::StdArc > & fst_
NBestDecoderOptions opts_
StateQueue queue_
std::vector< BaseFloat > tmp_array_
TokenStore token_store_
DecodableInterface * decodable_
Detailed Description
Caution: this decoder was written essentially as testing code for lattice-faster-decoder, and is not very useful; it would be better to pipe the lattices from lattice-faster-decoder into lattice-to-nbest if you want an n-best list.
We will likely eventually delete this from the trunk and leave it only in ^/branches/complete.
We are not planning to modify this decoder to support the "newer interface" with InitDecoding() and AdvanceDecoding().
Definition at line 68 of file nbest-decoder.h.
Member Typedef Documentation
typedef fst::StdArc Arc
Definition at line 72 of file nbest-decoder.h.
typedef TokenHash::Elem Elem private
Definition at line 498 of file nbest-decoder.h.
typedef Arc::Label Label
Definition at line 73 of file nbest-decoder.h.
typedef TokenStore::SeqToken SeqToken private
Definition at line 495 of file nbest-decoder.h.
typedef Arc::StateId StateId
Definition at line 74 of file nbest-decoder.h.
typedef unordered_set<StateId> StateQueue private
Definition at line 684 of file nbest-decoder.h.
typedef TokenStore::Token Token private
Definition at line 494 of file nbest-decoder.h.
typedef HashList<StateId, Token*> TokenHash private
Definition at line 497 of file nbest-decoder.h.
typedef Arc::Weight Weight
Definition at line 75 of file nbest-decoder.h.
Constructor & Destructor Documentation
NBestDecoder (const fst::Fst< fst::StdArc > & fst, NBestDecoderOptions opts) inline
Definition at line 78 of file nbest-decoder.h.
References NBestDecoder::decodable_, NBestDecoderOptions::hash_ratio, KALDI_ASSERT, NBestDecoderOptions::max_active, NBestDecoder::opts_, HashList< I, T >::SetSize(), and NBestDecoder::toks_.
                                         : fst_(fst), opts_(opts) {
     KALDI_ASSERT(opts_.hash_ratio >= 1.0);  // less doesn't make much sense.
     KALDI_ASSERT(opts_.max_active > 1);
     toks_.SetSize(1000);  // just so on the first frame we do something reasonable.
     decodable_ = NULL;
   }
~NBestDecoder () inline
Definition at line 88 of file nbest-decoder.h.
References HashList< I, T >::Clear(), NBestDecoder::TokenStore::Clear(), NBestDecoder::ClearToks(), NBestDecoder::decodable_, NBestDecoder::token_store_, and NBestDecoder::toks_.
                   {
     ClearToks(toks_.Clear());
     token_store_.Clear();
     decodable_ = NULL;
   }
Member Function Documentation
void ClearToks (Elem * list) inline private
Definition at line 698 of file nbest-decoder.h.
References HashList< I, T >::Delete(), NBestDecoder::TokenStore::DeleteTok(), NBestDecoder::token_store_, and NBestDecoder::toks_.
Referenced by NBestDecoder::Decode(), and NBestDecoder::~NBestDecoder().
{
     for (Elem *e = list, *e_tail; e != NULL; e = e_tail) {
       token_store_.DeleteTok(e->val);
       e_tail = e->tail;
       toks_.Delete(e);
     }
   }
void Decode (DecodableInterface * decodable) inline
Definition at line 94 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Token::c, NBestDecoder::TokenStore::Token::ca, HashList< I, T >::Clear(), NBestDecoder::ClearToks(), NBestDecoder::TokenStore::CreateTok(), NBestDecoder::decodable_, NBestDecoder::fst_, NBestDecoder::TokenStore::Token::I, NBestDecoder::TokenStore::Init(), HashList< I, T >::Insert(), DecodableInterface::IsLastFrame(), KALDI_ASSERT, NBestDecoderOptions::n_best, NBestDecoder::opts_, NBestDecoder::PropagateEmitting(), NBestDecoder::PropagateEpsilon(), NBestDecoder::token_store_, and NBestDecoder::toks_.
Referenced by main().
{
     decodable_ = decodable;
     // clean up from last time:
     ClearToks(toks_.Clear());
     token_store_.Init(decodable, &toks_, opts_.n_best);
     StateId start_state = fst_.Start();
     KALDI_ASSERT(start_state != fst::kNoStateId);
     Token *tok = token_store_.CreateTok(0, NULL);
     tok->c = Weight::One();
     tok->ca = Weight::One();
     tok->I = NULL;
     toks_.Insert(start_state, tok);
     PropagateEpsilon(std::numeric_limits<float>::max());
     for (int32 frame = 0; !decodable_->IsLastFrame(frame-1); frame++) {
       BaseFloat adaptive_beam = PropagateEmitting(frame);
       PropagateEpsilon(adaptive_beam);
     }
   }
BaseFloat GetCutoff (Elem * list_head, size_t * tok_count, BaseFloat * adaptive_beam, Elem ** best_elem) inline private
Gets the weight cutoff. Also counts the active tokens.
Definition at line 501 of file nbest-decoder.h.
References NBestDecoderOptions::beam, NBestDecoderOptions::beam_delta, count, NBestDecoderOptions::max_active, NBestDecoder::opts_, and NBestDecoder::tmp_array_.
Referenced by NBestDecoder::PropagateEmitting().
{
     BaseFloat best_weight = 1.0e+10;  // positive == high cost == bad.
     size_t count = 0;
     // find best token
     tmp_array_.clear();
     for (Elem *e = list_head; e != NULL; e = e->tail, count++) {
       BaseFloat w = static_cast<BaseFloat>(e->val->c.Value());
       tmp_array_.push_back(w); // ??check this - not always necessary
       if (w < best_weight) {
         best_weight = w;
         if (best_elem) *best_elem = e;
       }
     }
     if (tok_count != NULL) *tok_count = count;
     // compute adaptive beam
     if ((opts_.max_active == std::numeric_limits<int32>::max()) ||
         (tmp_array_.size() <= static_cast<size_t>(opts_.max_active))) {
       if (adaptive_beam != NULL) *adaptive_beam = opts_.beam;
       return best_weight + opts_.beam;
     } else {
       // the lowest elements (lowest costs, highest likes)
       // will be put in the left part of tmp_array.
       std::nth_element(tmp_array_.begin(),
                        tmp_array_.begin() + opts_.max_active,
                        tmp_array_.end());
       // return the tighter of the two beams.
       BaseFloat ans = std::min(best_weight + opts_.beam,
                                *(tmp_array_.begin() + opts_.max_active));
       if (adaptive_beam)
         *adaptive_beam = std::min(opts_.beam,
                                   ans - best_weight + opts_.beam_delta);
       return ans;
     }
   }
bool GetNBestLattice (fst::MutableFst< CompactLatticeArc > * fst_out, bool * was_final, int32 * nbest, BaseFloat * nbest_beam, bool use_final_probs = true) inline
Definition at line 123 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Token::c, NBestDecoder::TokenStore::Token::ca, HashList< I, T >::Clear(), NBestDecoder::TokenStore::CombineN(), NBestDecoder::TokenStore::CreateTok(), HashList< I, T >::Delete(), NBestDecoder::TokenStore::DeleteTok(), HashList< I, T >::Find(), NBestDecoder::fst_, rnnlm::i, NBestDecoder::TokenStore::Token::I, HashList< I, T >::Insert(), KALDI_ISINF, KALDI_WARN, NBestDecoder::TokenStore::Token::o, LatticeWeightTpl< BaseFloat >::One(), NBestDecoder::TokenStore::SeqToken::previous, NBestDecoder::TokenStore::Token::previous, NBestDecoder::ReachedFinal(), fst::RemoveEpsLocal(), fst::Times(), NBestDecoder::token_store_, and NBestDecoder::toks_.
Referenced by main().
{
     // GetNBestLattice gets the n-best decoding output. If "use_final_probs"
     // is true AND we reached a final state, it limits itself to final states;
     // otherwise it does not take into account final-probs.
     // fst_out will be empty (Start() == kNoStateId) if nothing was available.
     // It returns number of paths if it got output (thus, fst_out will be
     // nonempty), otherwise zero.
     int n_paths = 0;
     BaseFloat worst_final = 0.0,
         best_final = std::numeric_limits<BaseFloat>::infinity();
     *was_final = ReachedFinal();
     Elem *last_toks = toks_.Clear(); // P <- C , C = {}
     Token *tok = token_store_.CreateTok(0, NULL);
     StateId end_state = 1E9; // some imaginary super end state
     tok->c = Weight::Zero();
     tok->I = NULL;
     toks_.Insert(end_state, tok);
     Elem *best_e = toks_.Find(end_state);
     if (!(*was_final)) { // only look for best tokens in this frame
       for (Elem *e = last_toks, *e_tail; e != NULL; e = e_tail) {
         token_store_.CombineN(best_e, e->val);
         e_tail = e->tail;
         toks_.Delete(e);
       }
     } else { // find best tokens in final states
       for (Elem *e = last_toks, *e_tail; e != NULL; e = e_tail) {
         Token *source = e->val;
         Weight fw = use_final_probs ? fst_.Final(e->key) : Weight::One();
         if (fw != Weight::Zero()) {
           source->c = Times(source->c, fw);
           token_store_.CombineN(best_e, source);
         } else {
           token_store_.DeleteTok(source);
         }
         e_tail = e->tail;
         toks_.Delete(e);
       }
     }
     // start building output FST
     fst_out->DeleteStates();
     StateId start_state = fst_out->AddState();
     fst_out->SetStart(start_state);
     last_toks = toks_.Clear(); // just tokens in super end state this time
     if (last_toks->val == NULL) return false;  // No output.
     // go through tokens in imaginary super end state
     for (Elem *e = last_toks, *e_tail = NULL; e != NULL; e = e_tail) {
       Token *best_tok = e->val;
       BaseFloat amscore = best_tok->ca.Value(),
           lmscore = best_tok->c.Value() - amscore;
       if (KALDI_ISINF(amscore) || KALDI_ISINF(lmscore)) {
         KALDI_WARN << "infinity token! probably too narrow beam to retrieve n best";
         e_tail = e->tail;
         toks_.Delete(e);
         continue; // skip that token
       }
       LatticeWeight path_w(lmscore, amscore);
       CompactLatticeWeight path_weight(path_w, vector<int32>());
       std::vector<CompactLatticeArc*> arcs_reverse; // reverse order output arcs
       // outer loop for word tokens
       for (Token *tok = best_tok; tok != NULL; tok = tok->previous) {
         // inner loop for input label tokens
         std::vector<int32> str_rev, str;
         for (SeqToken *stok = tok->I; stok != NULL; stok = stok->previous) {
           str_rev.push_back(stok->i);
         }
         // reverse vector
         std::vector<int32>::reverse_iterator rit;
         for (rit = str_rev.rbegin(); rit < str_rev.rend(); ++rit)
           str.push_back(*rit);
         arcs_reverse.push_back(new CompactLatticeArc(
             tok->o, tok->o, CompactLatticeWeight(LatticeWeight::One(), str), 0));
         // no weight info (tok->c), no state info
       }
       token_store_.DeleteTok(best_tok);
       StateId cur_state = start_state;
       for (ssize_t i = static_cast<ssize_t>(arcs_reverse.size())-1; i >= 0; i--) {
         CompactLatticeArc *arc = arcs_reverse[i];
         arc->nextstate = fst_out->AddState();
         fst_out->AddArc(cur_state, *arc);
         cur_state = arc->nextstate;
         delete arc;
       }
       fst_out->SetFinal(cur_state, path_weight);
       e_tail = e->tail;
       toks_.Delete(e);
       n_paths++;
       BaseFloat p_score = amscore + lmscore;
       if (p_score > worst_final) worst_final = p_score;
       if (p_score < best_final) best_final = p_score;
     }
     if (nbest_beam) *nbest_beam = worst_final - best_final;
     if (nbest) *nbest = n_paths;
     RemoveEpsLocal(fst_out);
     return true;
   }
void PossiblyResizeHash (size_t num_toks) inline private
Definition at line 537 of file nbest-decoder.h.
References NBestDecoderOptions::hash_ratio, NBestDecoder::opts_, HashList< I, T >::SetSize(), HashList< I, T >::Size(), and NBestDecoder::toks_.
Referenced by NBestDecoder::PropagateEmitting().
{
     size_t new_sz = static_cast<size_t>(static_cast<BaseFloat>(num_toks)
                                         * opts_.hash_ratio);
     if (new_sz > toks_.Size()) {
       toks_.SetSize(new_sz);
     }
   }
BaseFloat PropagateEmitting (int32 frame) inline private
Definition at line 546 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Advance(), NBestDecoder::TokenStore::Token::c, HashList< I, T >::Clear(), NBestDecoder::TokenStore::CombineN(), NBestDecoder::decodable_, HashList< I, T >::Delete(), NBestDecoder::TokenStore::DeleteTok(), HashList< I, T >::Find(), NBestDecoder::fst_, NBestDecoder::GetCutoff(), HashList< I, T >::Insert(), DecodableInterface::LogLikelihood(), NBestDecoder::PossiblyResizeHash(), fst::Times(), NBestDecoder::token_store_, and NBestDecoder::toks_.
Referenced by NBestDecoder::Decode().
{
     Elem *last_toks = toks_.Clear(); // P <- C , C = {}
     size_t tok_cnt;
     BaseFloat adaptive_beam;
     Elem *best_elem = NULL;
     BaseFloat weight_cutoff = GetCutoff(last_toks, &tok_cnt,
                                         &adaptive_beam, &best_elem);
     PossiblyResizeHash(tok_cnt);  // This makes sure the hash is always big enough.
     // This is the cutoff we use after adding in the log-likes (i.e.
     // for the next frame).  This is a bound on the cutoff we will use
     // on the next frame.
     BaseFloat next_weight_cutoff = 1.0e+10;
     // First process the best token to get a hopefully
     // reasonably tight bound on the next cutoff.
     if (best_elem) {
       StateId state = best_elem->key;
       Token *tok = best_elem->val;
       for (fst::ArcIterator<fst::Fst<Arc> > aiter(fst_, state);
            !aiter.Done();
            aiter.Next()) {
         Arc arc = aiter.Value();
         if (arc.ilabel != 0) {  // propagate..
           arc.weight = Times(arc.weight,
                              Weight(- decodable_->LogLikelihood(frame, arc.ilabel)));
           BaseFloat new_weight = arc.weight.Value() + tok->c.Value();
           if (new_weight + adaptive_beam < next_weight_cutoff)
             next_weight_cutoff = new_weight + adaptive_beam;
         }
       }
     }
     // int32 n = 0, np = 0;
     // the tokens are now owned here, in last_toks, and the hash is empty.
     // 'owned' is a complex thing here; the point is we need to call DeleteElem
     // on each elem 'e' to let toks_ know we're done with them.
     for (Elem *e = last_toks, *e_tail; e != NULL; e = e_tail) {
       // for all (s,t) in P
       // n++;
       // because we delete "e" as we go.
       StateId state = e->key;
       Token *tok = e->val;
       if (tok->c.Value() < weight_cutoff) {  // not pruned.
         // np++;
         // KALDI_ASSERT(state == tok->arc_.nextstate);
         for (fst::ArcIterator<fst::Fst<Arc> > aiter(fst_, state);
              !aiter.Done(); aiter.Next()) {
           // for all a in A(state)
           Arc arc = aiter.Value();
           if (arc.ilabel != 0) {  // propagate only emitting
             Token *new_tok =
                 token_store_.Advance(tok, arc, frame, next_weight_cutoff);
             if (new_tok) {
               Elem *e_found = toks_.Find(arc.nextstate);
               if (e_found == NULL) {
                 toks_.Insert(arc.nextstate, new_tok);
               } else {
                 token_store_.CombineN(e_found, new_tok);
               }
             }
           }
         }
       }
       e_tail = e->tail; // several tokens with the same key can follow
       token_store_.DeleteTok(e->val);
       toks_.Delete(e);
     }
     //  std::cerr << n << ', ' << np << ', ' <<adaptive_beam<<' ';
     return adaptive_beam;
   }
void PropagateEpsilon (BaseFloat adaptive_beam) inline private
Definition at line 620 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Advance(), NBestDecoder::TokenStore::Token::c, NBestDecoder::TokenStore::CombineN(), HashList< I, T >::Find(), NBestDecoder::fst_, HashList< I, T >::GetList(), HashList< I, T >::Insert(), KALDI_ASSERT, NBestDecoder::queue_, NBestDecoder::token_store_, and NBestDecoder::toks_.
Referenced by NBestDecoder::Decode().
{
     // Processes nonemitting arcs for one frame.  Propagates within
     // cur_toks_.
     KALDI_ASSERT(queue_.empty());
     queue_.max_load_factor(1.0);
     float best_weight = 1.0e+10;
     for (const Elem *e = toks_.GetList(); e != NULL;  e = e->tail) {
       // queue_.push_back(e->key);
       queue_.insert(e->key);
       best_weight = std::min(best_weight, e->val->c.Value());
     }
     BaseFloat cutoff = best_weight + adaptive_beam;
     while (!queue_.empty()) {
       // StateId state = queue_.back();
       StateId state = *(queue_.begin());
       // queue_.pop_back();
       queue_.erase(queue_.begin());
       Elem *elem = toks_.Find(state);  // would segfault if state not
       // in toks_ but this can't happen.
       // we have to pop all tokens with the same state
       // this may create some unneccessary repetitions, since only the new token
       // needs to be forwarded, but I don't know yet how to solve this
       while (elem && elem->key == state) {
         Token *tok = elem->val;
         elem = elem->tail;
         if (tok->c.Value() > cutoff) {  // Don't bother processing successors.
           continue;
         }
         // KALDI_ASSERT(tok != NULL && state == tok->arc_.nextstate);
         KALDI_ASSERT(tok != NULL);
         for (fst::ArcIterator<fst::Fst<Arc> > aiter(fst_, state);
              !aiter.Done(); aiter.Next()) {
           // for all a in A(state)
           Arc arc = aiter.Value();
           if (arc.ilabel == 0) {  // propagate nonemitting only...
             Token *new_tok = token_store_.Advance(tok, arc, -1, cutoff); // -1:eps
             if (new_tok) {
               Elem *e_found = toks_.Find(arc.nextstate);
               if (e_found == NULL) {
                 toks_.Insert(arc.nextstate, new_tok);
                 // queue_.push_back(arc.nextstate);
                 queue_.insert(arc.nextstate); // might be pushed several times
               } else {
                 if (token_store_.CombineN(e_found, new_tok)) { // C was updated
                   // queue_.push_back(arc.nextstate);
                   queue_.insert(arc.nextstate);
                 }
               }
             }
           } // if nonemitting
         } // for Arciterator
       } // while
     }
   }
bool ReachedFinal () inline
Definition at line 113 of file nbest-decoder.h.
References NBestDecoder::fst_, HashList< I, T >::GetList(), fst::Times(), and NBestDecoder::toks_.
Referenced by NBestDecoder::GetNBestLattice().
                       {
     for (const Elem *e = toks_.GetList(); e != NULL; e = e->tail) {
       Weight this_weight = Times(e->val->c, fst_.Final(e->key));
       if (this_weight != Weight::Zero()) {
         return true;
       }
     }
     return false;
   }
void SetOptions (const NBestDecoderOptions & opts) inline
Definition at line 86 of file nbest-decoder.h.
References NBestDecoder::opts_.
 { opts_ = opts; }
Member Data Documentation
DecodableInterface* decodable_ private
Definition at line 690 of file nbest-decoder.h.
Referenced by NBestDecoder::Decode(), NBestDecoder::NBestDecoder(), NBestDecoder::PropagateEmitting(), and NBestDecoder::~NBestDecoder().
const fst::Fst<fst::StdArc>& fst_ private
Definition at line 682 of file nbest-decoder.h.
Referenced by NBestDecoder::Decode(), NBestDecoder::GetNBestLattice(), NBestDecoder::PropagateEmitting(), NBestDecoder::PropagateEpsilon(), and NBestDecoder::ReachedFinal().
NBestDecoderOptions opts_ private
Definition at line 683 of file nbest-decoder.h.
Referenced by NBestDecoder::Decode(), NBestDecoder::GetCutoff(), NBestDecoder::NBestDecoder(), NBestDecoder::PossiblyResizeHash(), and NBestDecoder::SetOptions().
StateQueue queue_ private
Definition at line 685 of file nbest-decoder.h.
Referenced by NBestDecoder::PropagateEpsilon().
std::vector<BaseFloat> tmp_array_ private
Definition at line 687 of file nbest-decoder.h.
Referenced by NBestDecoder::GetCutoff().
TokenStore token_store_ private
Definition at line 689 of file nbest-decoder.h.
Referenced by NBestDecoder::ClearToks(), NBestDecoder::Decode(), NBestDecoder::GetNBestLattice(), NBestDecoder::PropagateEmitting(), NBestDecoder::PropagateEpsilon(), and NBestDecoder::~NBestDecoder().
TokenHash toks_ private
Definition at line 681 of file nbest-decoder.h.
Referenced by NBestDecoder::ClearToks(), NBestDecoder::Decode(), NBestDecoder::GetNBestLattice(), NBestDecoder::NBestDecoder(), NBestDecoder::PossiblyResizeHash(), NBestDecoder::PropagateEmitting(), NBestDecoder::PropagateEpsilon(), NBestDecoder::ReachedFinal(), and NBestDecoder::~NBestDecoder().
The documentation for this class was generated from the following file:
decoder/nbest-decoder.h