Kaldi: AveragePoolingComponent Class Reference
AveragePoolingComponent Class Reference
AveragePoolingComponent : The input/output matrices are split to submatrices with width 'pool_stride_'.
#include <nnet-average-pooling-component.h>
Public Member Functions
AveragePoolingComponent (int32 dim_in, int32 dim_out)
~AveragePoolingComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if contains trainable parameters.
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Optionally print some additional info.
virtual std::string InfoGradient () const
Private Attributes
int32 pool_size_
int32 pool_step_
int32 pool_stride_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
AveragePoolingComponent : The input/output matrices are split to submatrices with width 'pool_stride_'.
The pooling is done over 3rd axis, of the set of 2d matrices. Our pooling supports overlaps, overlaps occur when (pool_step_ < pool_size_).
Definition at line 38 of file nnet-average-pooling-component.h.
Constructor & Destructor Documentation
AveragePoolingComponent (int32 dim_in, int32 dim_out) inline
Definition at line 40 of file nnet-average-pooling-component.h.
Referenced by AveragePoolingComponent::Copy().
     : Component(dim_in, dim_out), pool_size_(0), pool_step_(0), pool_stride_(0)
   { }
~AveragePoolingComponent () inline
Definition at line 43 of file nnet-average-pooling-component.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 116 of file nnet-average-pooling-component.h.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::ColRange(), Component::input_dim_, KALDI_ASSERT, AveragePoolingComponent::pool_size_, AveragePoolingComponent::pool_step_, AveragePoolingComponent::pool_stride_, CuMatrixBase< Real >::Scale(), and CuMatrixBase< Real >::SetZero().
{
     // useful dims
     int32 num_patches = input_dim_ / pool_stride_;
     int32 num_pools = 1 + (num_patches - pool_size_) / pool_step_;
     //
     // here we note how many diff matrices are summed for each input patch,
     std::vector<int32> patch_summands(num_patches, 0);
     // this metainfo will be used to divide diff of patches
     // used in more than one pool.
     //
     in_diff->SetZero(); // reset
     for(int32 q=0; q<num_pools; q++) { // sum
       for(int32 r=0; r<pool_size_; r++) {
         int32 p = r + q * pool_step_;
         CuSubMatrix<BaseFloat> tgt(in_diff->ColRange(p*pool_stride_, pool_stride_));
         CuSubMatrix<BaseFloat> src(out_diff.ColRange(q*pool_stride_, pool_stride_));
         tgt.AddMat(1.0, src);
         patch_summands[p] += 1;
       }
     }
     // divide diff by average-pooling-dim (derivative of averaging)
     in_diff->Scale(1.0 / pool_size_);
     // divide diff by #summands (compensate for patches used in more pools)
     for(int32 p=0; p<num_patches; p++) {
       CuSubMatrix<BaseFloat> tgt(in_diff->ColRange(p*pool_stride_, pool_stride_));
       KALDI_ASSERT(patch_summands[p] > 0); // patch at least in one pool
       tgt.Scale(1.0/patch_summands[p]);
     }
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 46 of file nnet-average-pooling-component.h.
References AveragePoolingComponent::AveragePoolingComponent().
 { return new AveragePoolingComponent(*this); }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 47 of file nnet-average-pooling-component.h.
References Component::kAveragePoolingComponent.
 { return kAveragePoolingComponent; }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Reimplemented from Component.
Definition at line 49 of file nnet-average-pooling-component.h.
References KALDI_ASSERT, KALDI_ERR, AveragePoolingComponent::pool_size_, AveragePoolingComponent::pool_step_, AveragePoolingComponent::pool_stride_, kaldi::ReadBasicType(), and kaldi::ReadToken().
{
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<PoolSize>") ReadBasicType(is, false, &pool_size_);
       else if (token == "<PoolStep>") ReadBasicType(is, false, &pool_step_);
       else if (token == "<PoolStride>") ReadBasicType(is, false, &pool_stride_);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (PoolSize|PoolStep|PoolStride)";
       is >> std::ws; // eat-up whitespace
     }
     // check
     KALDI_ASSERT(pool_size_ != 0 && pool_step_ != 0 && pool_stride_ != 0);
   }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 98 of file nnet-average-pooling-component.h.
References CuMatrixBase< Real >::ColRange(), Component::input_dim_, AveragePoolingComponent::pool_size_, AveragePoolingComponent::pool_step_, AveragePoolingComponent::pool_stride_, and CuMatrixBase< Real >::SetZero().
{
     // useful dims
     int32 num_patches = input_dim_ / pool_stride_;
     int32 num_pools = 1 + (num_patches - pool_size_) / pool_step_;
     // do the average-pooling (pools indexed by q)
     for (int32 q = 0; q < num_pools; q++) {
       // get output buffer of the pool
       CuSubMatrix<BaseFloat> pool(out->ColRange(q*pool_stride_, pool_stride_));
       pool.SetZero(); // reset
       for (int32 r = 0; r < pool_size_; r++) { // sum
         int32 p = r + q * pool_step_; // p = input patch
         pool.AddMat(1.0, in.ColRange(p*pool_stride_, pool_stride_));
       }
       pool.Scale(1.0 / pool_size_); // divide by #summands
     }
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 65 of file nnet-average-pooling-component.h.
References kaldi::ExpectToken(), Component::input_dim_, KALDI_ASSERT, Component::output_dim_, AveragePoolingComponent::pool_size_, AveragePoolingComponent::pool_step_, AveragePoolingComponent::pool_stride_, and kaldi::ReadBasicType().
{
     // pooling hyperparameters
     ExpectToken(is, binary, "<PoolSize>");
     ReadBasicType(is, binary, &pool_size_);
     ExpectToken(is, binary, "<PoolStep>");
     ReadBasicType(is, binary, &pool_step_);
     ExpectToken(is, binary, "<PoolStride>");
     ReadBasicType(is, binary, &pool_stride_);
     //
     // Sanity checks:
     //
     // number of patches:
     KALDI_ASSERT(input_dim_ % pool_stride_ == 0);
     int32 num_patches = input_dim_ / pool_stride_;
     // number of pools:
     KALDI_ASSERT((num_patches - pool_size_) % pool_step_ == 0);
     int32 num_pools = 1 + (num_patches - pool_size_) / pool_step_;
     // check output dim:
     KALDI_ASSERT(output_dim_ == num_pools * pool_stride_);
     //
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 88 of file nnet-average-pooling-component.h.
References AveragePoolingComponent::pool_size_, AveragePoolingComponent::pool_step_, AveragePoolingComponent::pool_stride_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     // pooling hyperparameters
     WriteToken(os, binary, "<PoolSize>");
     WriteBasicType(os, binary, pool_size_);
     WriteToken(os, binary, "<PoolStep>");
     WriteBasicType(os, binary, pool_step_);
     WriteToken(os, binary, "<PoolStride>");
     WriteBasicType(os, binary, pool_stride_);
   }
Member Data Documentation
int32 pool_size_ private
Definition at line 153 of file nnet-average-pooling-component.h.
Referenced by AveragePoolingComponent::BackpropagateFnc(), AveragePoolingComponent::InitData(), AveragePoolingComponent::PropagateFnc(), AveragePoolingComponent::ReadData(), and AveragePoolingComponent::WriteData().
int32 pool_step_ private
Definition at line 153 of file nnet-average-pooling-component.h.
Referenced by AveragePoolingComponent::BackpropagateFnc(), AveragePoolingComponent::InitData(), AveragePoolingComponent::PropagateFnc(), AveragePoolingComponent::ReadData(), and AveragePoolingComponent::WriteData().
int32 pool_stride_ private
Definition at line 153 of file nnet-average-pooling-component.h.
Referenced by AveragePoolingComponent::BackpropagateFnc(), AveragePoolingComponent::InitData(), AveragePoolingComponent::PropagateFnc(), AveragePoolingComponent::ReadData(), and AveragePoolingComponent::WriteData().
The documentation for this class was generated from the following file:
nnet/nnet-average-pooling-component.h