Kaldi: LangModelFst Class Reference
LangModelFst Class Reference
LanguageModel
Finite-state transducer language model.
#include <kaldi-lm.h>
Public Types
typedef fst::StdArc::Weight LmWeight
typedef fst::StdArc::StateId StateId
Public Member Functions
LangModelFst ()
LangModelFst (const LangModelFst &lm)
~LangModelFst ()
bool Read (std::istream &strm, const string &sourcename, GrammarType gtype, fst::SymbolTable *pst=NULL, bool useNaturalLog=true, const string startSent="<s>", const string endSent="</s>")
Reads a language model from an input stream.
bool Read (const string &rxfilename, GrammarType gtype, fst::SymbolTable *pst=0, bool useNaturalLog=true, const string startSent="<s>", const string endSent="</s>")
fst::SymbolTable * MutableInputSymbols ()
const fst::VectorFst
< fst::StdArc > * GetFst () const
fst::VectorFst< fst::StdArc > * GetFst ()
bool Write (const std::string &filename) const
Writes language model FST to named output file, return false on error.
Private Member Functions
fst::VectorFst< fst::StdArc > * ReadStream (std::istream &strm, const string &sourcename, GrammarType gtype, fst::SymbolTable *pst, bool useNaturalLog, const string startSent, const string endSent)
void ReadTxtString (std::istream &strm)
fst::StdArc::StateId ReadTxtLine (const string &inpline)
Private Attributes
fst::VectorFst< fst::StdArc > * pfst_
Detailed Description
Finite-state transducer language model.
LangModelFst is a standard vector FST that also provides Read() and Write() functions for file-based language models or text files defining strings and grammars.
Definition at line 61 of file kaldi-lm.h.
Member Typedef Documentation
typedef fst::StdArc::Weight LmWeight
Definition at line 63 of file kaldi-lm.h.
typedef fst::StdArc::StateId StateId
Definition at line 64 of file kaldi-lm.h.
Constructor & Destructor Documentation
LangModelFst () inline
Definition at line 67 of file kaldi-lm.h.
References LangModelFst::pfst_.
                  {
     pfst_ = new fst::VectorFst<fst::StdArc>;
   }
LangModelFst (const LangModelFst & lm) inline
Definition at line 71 of file kaldi-lm.h.
     : pfst_(lm.pfst_ ? new fst::VectorFst<fst::StdArc>(*(lm.pfst_)) : 0) {}
~LangModelFst () inline
Definition at line 74 of file kaldi-lm.h.
References LangModelFst::pfst_.
                   {
     delete pfst_;
   }
Member Function Documentation
const fst::VectorFst<fst::StdArc>* GetFst () const inline
Definition at line 121 of file kaldi-lm.h.
References LangModelFst::pfst_.
Referenced by kaldi::TestLmTableEvalScore(), and kaldi::TestLmTableReadWrite().
 {return pfst_;}
fst::VectorFst<fst::StdArc>* GetFst () inline
Definition at line 122 of file kaldi-lm.h.
References LangModelFst::pfst_.
 {return pfst_;}
fst::SymbolTable* MutableInputSymbols () inline
Definition at line 117 of file kaldi-lm.h.
References LangModelFst::pfst_.
{
     return pfst_->MutableInputSymbols();
   }
bool Read (std::istream & strm, const string & sourcename, GrammarType gtype, fst::SymbolTable * pst = NULL, bool useNaturalLog = true, const string startSent = "<s>", const string endSent = "</s>") inline
Reads a language model from an input stream.
Definition at line 79 of file kaldi-lm.h.
References LangModelFst::pfst_, and LangModelFst::ReadStream().
Referenced by kaldi::TestLmTableEvalScore(), and kaldi::TestLmTableReadWrite().
{
    delete pfst_;
     pfst_ = ReadStream(strm, sourcename,
                        gtype, pst,
                        useNaturalLog,
                        startSent, endSent);
     return(pfst_ ? true : false);
   }
bool Read (const string & rxfilename, GrammarType gtype, fst::SymbolTable * pst = 0, bool useNaturalLog = true, const string startSent = "<s>", const string endSent = "</s>") inline
Definition at line 95 of file kaldi-lm.h.
References KALDI_ERR, LangModelFst::pfst_, kaldi::PrintableRxfilename(), LangModelFst::ReadStream(), and Input::Stream().
{
     delete pfst_;
     if (rxfilename == "") {
       KALDI_ERR << "arpa2fst and similar programs no longer support empty filename "
                 << "for standard input; use '-'";
     }
     Input ki(rxfilename);
     pfst_ = ReadStream(ki.Stream(),
                        PrintableRxfilename(rxfilename),
                        gtype, pst,
                        useNaturalLog,
                        startSent, endSent);
     return(pfst_ ? true : false);
   }
fst::StdVectorFst * ReadStream (std::istream & strm, const string & sourcename, GrammarType gtype, fst::SymbolTable * pst, bool useNaturalLog, const string startSent, const string endSent) private
Definition at line 73 of file kaldi-lm.cc.
References KALDI_ERR, kaldi::kArpaLm, kaldi::kFst, kaldi::kTextString, LangModelFst::pfst_, LmTable::ReadFstFromLmFile(), and LangModelFst::ReadTxtString().
Referenced by LangModelFst::Read().
{
   if (gtype == kArpaLm || gtype == kTextString) {
     // always allocate local symbol table so we know we always have to delete it
     fst::SymbolTable *psyms = new fst::SymbolTable("lmInputSymbols");
     // initialize FST and reserve initial state
     // (we can retrieve it through Start())
     pfst_ = new fst::StdVectorFst;
     pfst_->SetStart(pfst_->AddState());
     // these will be added if not already there
     pst = pst ? pst : psyms;
     pst->AddSymbol("<eps>");
     pst->AddSymbol(startSent);
     pst->AddSymbol(endSent);
     // this creates reference-counted copies managed by fst
     pfst_->SetInputSymbols(pst);
     pfst_->SetOutputSymbols(pst);
     // so local objects are not needed anymore
     delete psyms;
     if (gtype == kArpaLm) {
       LmTable lmt;
       lmt.ReadFstFromLmFile(strm, pfst_, useNaturalLog, startSent, endSent);
     } else if (gtype== kTextString) {
       ReadTxtString(strm);
     }
   } else if (gtype == kFst) {
     // this is going to be reference-counted
     pfst_ = fst::StdVectorFst::Read(sourcename);
   } else {
     KALDI_ERR << "LangModelFst: unsupported grammar type";
   }
   return pfst_;
 }
LangModelFst::StateId ReadTxtLine (const string & inpline) private
Definition at line 33 of file kaldi-lm.cc.
References KALDI_ASSERT, and LangModelFst::pfst_.
Referenced by LangModelFst::ReadTxtString().
{
   KALDI_ASSERT(pfst_);
   KALDI_ASSERT(pfst_->InputSymbols());
   KALDI_ASSERT(pfst_->OutputSymbols());
   StateId dst = pfst_->Start(), src = pfst_->Start();
   // this will split on white spaces only
   string curwrd;  // Have a buffer string
   std::stringstream ss(inpline);  // Insert the string into a stream
   while (ss >> curwrd) {
     // add labels to symbol tables
     int64 ilab = pfst_->MutableInputSymbols()->AddSymbol(curwrd);
     int64 olab = pfst_->MutableOutputSymbols()->AddSymbol(curwrd);
     dst = pfst_->AddState();
     pfst_->AddArc(src, fst::StdArc(ilab, olab, 0, dst));
     // cerr << "  adding word " << curwrd << " from state " << src;
     // cerr << " to state " << dst <<endl;
     src = dst;
   }
   return dst;
 }
void ReadTxtString (std::istream & strm) private
Definition at line 57 of file kaldi-lm.cc.
References LangModelFst::pfst_, and LangModelFst::ReadTxtLine().
Referenced by LangModelFst::ReadStream().
{
   string inpline;
   StateId src, final = pfst_->AddState();
   while (getline(strm, inpline) && !strm.eof()) {
     // cerr << "ReadTxtString: read line " << inpline << endl;
     src = ReadTxtLine(inpline);
     // add arc from last state produced to final state
     pfst_->AddArc(src, fst::StdArc(0, 0, 0, final));
   }
   pfst_->SetFinal(final, fst::StdArc::Weight::One());
 }
bool Write (const std::string & filename) const inline
Writes language model FST to named output file, return false on error.
Definition at line 125 of file kaldi-lm.h.
References LangModelFst::pfst_, kaldi::PrintableWxfilename(), and Output::Stream().
Referenced by kaldi::TestLmTableReadWrite().
{
     // interpret "" as stdout for compatibility with OpenFst conventions.
     std::string wxfilename(filename == "" ? "-" : filename.c_str());
     bool write_binary = true, write_header = false;
     kaldi::Output ko(wxfilename, write_binary, write_header);
     fst::FstWriteOptions wopts(kaldi::PrintableWxfilename(wxfilename));
     return /* fst::Verify(*pfst_) && */
         pfst_->Write(ko.Stream(), wopts);
   }
Member Data Documentation
fst::VectorFst<fst::StdArc>* pfst_ private
Definition at line 136 of file kaldi-lm.h.
Referenced by LangModelFst::GetFst(), LangModelFst::LangModelFst(), LangModelFst::MutableInputSymbols(), LangModelFst::Read(), LangModelFst::ReadStream(), LangModelFst::ReadTxtLine(), LangModelFst::ReadTxtString(), LangModelFst::Write(), and LangModelFst::~LangModelFst().
The documentation for this class was generated from the following files:
lm/kaldi-lm.h
lm/kaldi-lm.cc