Kaldi: ContextDependency Class Reference
ContextDependency Class Reference
#include <context-dep.h>
Public Member Functions
virtual int32 ContextWidth () const
ContextWidth() returns the value N (e.g.
virtual int32 CentralPosition () const
Central position P of the phone context, in 0-based numbering, e.g.
virtual bool Compute (const std::vector< int32 > &phoneseq, int32 pdf_class, int32 *pdf_id) const
returns success or failure; outputs pdf to pdf_id For positions that were outside the sequence (due to end effects), put zero.
virtual int32 NumPdfs () const
NumPdfs() returns the number of acoustic pdfs (they are numbered 0.. NumPdfs()-1).
virtual
ContextDependencyInterface * Copy () const
Returns pointer to new object which is copy of current one.
void Read (std::istream &is, bool binary)
Read context-dependency object from disk; throws on error.
ContextDependency ()
ContextDependency (int32 N, int32 P, EventMap *to_pdf)
void Write (std::ostream &os, bool binary) const
~ContextDependency ()
const EventMap & ToPdfMap () const
virtual void GetPdfInfo (const std::vector< int32 > &phones, const std::vector< int32 > &num_pdf_classes, std::vector< std::vector< std::pair< int32, int32 > > > *pdf_info) const
GetPdfInfo returns a vector indexed by pdf-id, saying for each pdf which pairs of (phone, pdf-class) it can correspond to.
Public Member Functions inherited from ContextDependencyInterface
virtual ~ContextDependencyInterface ()
ContextDependencyInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (ContextDependency)
Private Attributes
int32 N_
int32 P_
EventMap * to_pdf_
Detailed Description
Definition at line 58 of file context-dep.h.
Constructor & Destructor Documentation
ContextDependency () inline
Definition at line 87 of file context-dep.h.
Referenced by ContextDependency::Copy().
 : N_(0), P_(0), to_pdf_(NULL) { }
ContextDependency (int32 N, int32 P, EventMap * to_pdf) inline
Definition at line 90 of file context-dep.h.
                                      :
       N_(N), P_(P), to_pdf_(to_pdf) { }
~ContextDependency () inline
Definition at line 95 of file context-dep.h.
References ContextDependency::to_pdf_.
 { delete to_pdf_; }
Member Function Documentation
virtual int32 CentralPosition () const inline virtual
Central position P of the phone context, in 0-based numbering, e.g.
P = 1 for typical triphone system. We have to see if we can do without this function.
Implements ContextDependencyInterface.
Definition at line 61 of file context-dep.h.
References ContextDependency::P_.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), kaldi::InitAmGmmFromOld(), and TrainingGraphCompiler::TrainingGraphCompiler().
 { return P_; }
bool Compute (const std::vector< int32 > & phoneseq, int32 pdf_class, int32 * pdf_id) const virtual
returns success or failure; outputs pdf to pdf_id For positions that were outside the sequence (due to end effects), put zero.
Naturally phoneseq[CentralPosition()] must be nonzero.
Implements ContextDependencyInterface.
Definition at line 26 of file context-dep.cc.
References rnnlm::i, KALDI_ASSERT, KALDI_COMPILE_TIME_ASSERT, kaldi::kPdfClass, EventMap::Map(), ContextDependency::N_, and ContextDependency::to_pdf_.
{
   KALDI_ASSERT(static_cast<int32>(phoneseq.size()) == N_);
   EventType  event_vec;
   event_vec.reserve(N_+1);
   event_vec.push_back(std::make_pair
                       (static_cast<EventKeyType>(kPdfClass),  // -1
                        static_cast<EventValueType>(pdf_class)));
   KALDI_COMPILE_TIME_ASSERT(kPdfClass < 0);  // or it would not be sorted.
   for (int32 i = 0;i < N_;i++) {
     event_vec.push_back(std::make_pair
                         (static_cast<EventKeyType>(i),
                          static_cast<EventValueType>(phoneseq[i])));
     KALDI_ASSERT(static_cast<EventAnswerType>(phoneseq[i]) >= 0);
   }
   KALDI_ASSERT(pdf_id != NULL);
   return to_pdf_->Map(event_vec, pdf_id);
 }
virtual int32 ContextWidth () const inline virtual
ContextWidth() returns the value N (e.g.
3 for triphone models) that says how many phones are considered for computing context.
Implements ContextDependencyInterface.
Definition at line 60 of file context-dep.h.
References ContextDependency::N_.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), kaldi::InitAmGmmFromOld(), and TrainingGraphCompiler::TrainingGraphCompiler().
 { return N_; }
virtual ContextDependencyInterface* Copy () const inline virtual
Returns pointer to new object which is copy of current one.
Implements ContextDependencyInterface.
Definition at line 78 of file context-dep.h.
References ContextDependency::ContextDependency(), EventMap::Copy(), ContextDependency::N_, ContextDependency::P_, and ContextDependency::to_pdf_.
{
     return new ContextDependency(N_, P_, to_pdf_->Copy());
   }
void GetPdfInfo (const std::vector< int32 > & phones, const std::vector< int32 > & num_pdf_classes, std::vector< std::vector< std::pair< int32, int32 > > > * pdf_info) const virtual
GetPdfInfo returns a vector indexed by pdf-id, saying for each pdf which pairs of (phone, pdf-class) it can correspond to.
(Usually just one). c.f. hmm/hmm-topology.h for meaning of pdf-class.
Implements ContextDependencyInterface.
Definition at line 181 of file context-dep.cc.
References rnnlm::i, kaldi::IsSortedAndUniq(), rnnlm::j, KALDI_ASSERT, KALDI_WARN, kaldi::kPdfClass, EventMap::MultiMap(), ContextDependency::NumPdfs(), ContextDependency::P_, kaldi::SortAndUniq(), and ContextDependency::to_pdf_.
Referenced by kaldi::TestGenRandContextDependency(), and kaldi::TestMonophoneContextDependency().
{
   EventType vec;
   KALDI_ASSERT(pdf_info != NULL);
   pdf_info->resize(NumPdfs());
   for (size_t i = 0 ; i < phones.size(); i++) {
     int32 phone = phones[i];
     vec.clear();
     vec.push_back(std::make_pair(static_cast<EventKeyType>(P_),
                                  static_cast<EventValueType>(phone)));
     // Now get length.
     KALDI_ASSERT(static_cast<size_t>(phone) < num_pdf_classes.size());
     EventAnswerType len = num_pdf_classes[phone];
     for (int32 pos = 0; pos < len; pos++) {
       vec.resize(2);
       vec[0] = std::make_pair(static_cast<EventKeyType>(P_),
                               static_cast<EventValueType>(phone));
       vec[1] = std::make_pair(kPdfClass, static_cast<EventValueType>(pos));
       std::sort(vec.begin(), vec.end());
       std::vector<EventAnswerType> pdfs;  // pdfs that can be at this pos as this phone.
       to_pdf_->MultiMap(vec, &pdfs);
       SortAndUniq(&pdfs);
       if (pdfs.empty()) {
         KALDI_WARN << "ContextDependency::GetPdfInfo, no pdfs returned for position "<< pos << " of phone " << phone << ".   Continuing but this is a serious error.";
       }
       for (size_t j = 0; j < pdfs.size(); j++) {
         KALDI_ASSERT(static_cast<size_t>(pdfs[j]) < pdf_info->size());
         (*pdf_info)[pdfs[j]].push_back(std::make_pair(phone, pos));
       }
     }
   }
   for (size_t i = 0; i < pdf_info->size(); i++) {
     std::sort( ((*pdf_info)[i]).begin(),  ((*pdf_info)[i]).end());
     KALDI_ASSERT(IsSortedAndUniq( ((*pdf_info)[i])));  // should have no dups.
   }
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (ContextDependency) private
virtual int32 NumPdfs () const inline virtual
NumPdfs() returns the number of acoustic pdfs (they are numbered 0.. NumPdfs()-1).
Implements ContextDependencyInterface.
Definition at line 70 of file context-dep.h.
References EventMap::MaxResult(), and ContextDependency::to_pdf_.
Referenced by ContextDependency::GetPdfInfo(), and kaldi::InitAndOutputSgmm().
{
     // this routine could be simplified to return to_pdf_->MaxResult()+1.  we're a
     // bit more paranoid than that.
     if (!to_pdf_) return 0;
     EventAnswerType max_result = to_pdf_->MaxResult();
     if (max_result < 0 ) return 0;
     else return (int32) max_result+1;
   }
void Read (std::istream & is, bool binary)
Read context-dependency object from disk; throws on error.
Definition at line 155 of file context-dep.cc.
References kaldi::ExpectToken(), KALDI_ERR, ContextDependency::N_, ContextDependency::P_, EventMap::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), and ContextDependency::to_pdf_.
Referenced by kaldi::InitAmGmmFromOld(), and kaldi::TestGenRandContextDependency().
{
   if (to_pdf_) {
     delete to_pdf_;
     to_pdf_ = NULL;
   }
   ExpectToken(is, binary, "ContextDependency");
   ReadBasicType(is, binary, &N_);
   ReadBasicType(is, binary, &P_);
   EventMap *to_pdf = NULL;
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "ToLength") {  // back-compat.
     EventMap *to_num_pdf_classes = EventMap::Read(is, binary);
     delete to_num_pdf_classes;
     ReadToken(is, binary, &token);
   }
   if (token == "ToPdf") {
     to_pdf = EventMap::Read(is , binary);
   } else {
     KALDI_ERR << "Got unexpected token " << token
               << " reading context-dependency object.";
   }
   ExpectToken(is, binary, "EndContextDependency");
   to_pdf_ = to_pdf;
 }
const EventMap& ToPdfMap () const inline
Definition at line 97 of file context-dep.h.
References ContextDependency::to_pdf_.
Referenced by kaldi::InitAmGmmFromOld(), kaldi::InitAndOutputSgmm(), and main().
 { return *to_pdf_; }
void Write (std::ostream & os, bool binary) const
Definition at line 145 of file context-dep.cc.
References ContextDependency::N_, ContextDependency::P_, ContextDependency::to_pdf_, EventMap::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by kaldi::TestGenRandContextDependency().
{
   WriteToken(os, binary, "ContextDependency");
   WriteBasicType(os, binary, N_);
   WriteBasicType(os, binary, P_);
   WriteToken(os, binary, "ToPdf");
   to_pdf_->Write(os, binary);
   WriteToken(os, binary, "EndContextDependency");
 }
Member Data Documentation
int32 N_ private
Definition at line 108 of file context-dep.h.
Referenced by ContextDependency::Compute(), ContextDependency::ContextWidth(), ContextDependency::Copy(), ContextDependency::Read(), and ContextDependency::Write().
int32 P_ private
Definition at line 109 of file context-dep.h.
Referenced by ContextDependency::CentralPosition(), ContextDependency::Copy(), ContextDependency::GetPdfInfo(), ContextDependency::Read(), and ContextDependency::Write().
EventMap* to_pdf_ private
Definition at line 110 of file context-dep.h.
Referenced by ContextDependency::Compute(), ContextDependency::Copy(), ContextDependency::GetPdfInfo(), ContextDependency::NumPdfs(), ContextDependency::Read(), ContextDependency::ToPdfMap(), ContextDependency::Write(), and ContextDependency::~ContextDependency().
The documentation for this class was generated from the following files:
tree/context-dep.h
tree/context-dep.cc