Kaldi: Convolutional2DComponent Class Reference
Convolutional2DComponent Class Reference
Convolutional2DComponent implements convolution over 2-axis (frequency and temporal) (i.e.
#include <nnet-convolutional-2d-component.h>
Public Member Functions
Convolutional2DComponent (int32 dim_in, int32 dim_out)
~Convolutional2DComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Sets the training options to the component.
const NnetTrainOptions & GetTrainOptions () const
Gets the training options from the component.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
Private Attributes
int32 fmap_x_len_
int32 fmap_y_len_
feature maps dimensions (for input x_ is usually splice and y_ is num of fbanks) shift for 2nd dim of a patch (i.e. frame length before splicing)
int32 filt_x_len_
int32 filt_y_len_
2D filter dimensions, x_ temporal, y_ spectral
int32 filt_x_step_
int32 filt_y_step_
2D shifts along temporal and spectral
int32 connect_fmap_
if connect_fmap_ = 1, then each fmap has num_filt
BaseFloat learn_rate_coef_
BaseFloat bias_learn_rate_coef_
CuMatrix< BaseFloat > filters_
row = vectorized rectangular filter
CuVector< BaseFloat > bias_
bias for each filter
CuMatrix< BaseFloat > filters_grad_
gradient of filters
CuVector< BaseFloat > bias_grad_
gradient of biases
std::vector< CuMatrix
< BaseFloat > > vectorized_feature_patches_
Buffer of reshaped inputs: 1row = vectorized rectangular feature patch, 1col = dim over speech frames, std::vector-dim = patch-position.
std::vector< CuMatrix
< BaseFloat > > feature_patch_diffs_
Buffer for backpropagation: derivatives in the domain of 'vectorized_feature_patches_', 1row = vectorized rectangular feature patch, 1col = dim over speech frames, std::vector-dim = patch-position.
CuVector< BaseFloat > in_diff_summands_
Auxiliary vector for compensating #summands when backpropagating.
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Convolutional2DComponent implements convolution over 2-axis (frequency and temporal) (i.e.
frequency axis in case we are the 1st component in NN). // We don't do convolution along temporal axis, which simplifies the // implementation (and was not helpful for Tara).
We assume the input featrues are spliced, i.e. each frame is in fact a set of stacked frames, where we can form patches which span over several frequency bands and time axes.
The convolution is done over whole axis with same filters, i.e. we don't use separate filters for different 'regions' of frequency axis.
In order to have a fast implementations, the filters are represented in vectorized form, where each rectangular filter corresponds to a row in a matrix, where all filters are stored. The features are then re-shaped to a set of matrices, where one matrix corresponds to single patch-position, where the filters get applied.
The type of convolution is controled by hyperparameters: x_patch_dim_,y_patch_dim_ ... temporal and frequency axes sizes of the patch (e.g. (9,9) for 9x9 2D filter) x_patch_step_,y_patch_step_ ... temporal and frequencey sizes of shifts in the convolution (e.g. (1,1) 2D filter with 1 step shift in both axes) x_patch_stride_,y_patch_stride_ ... dimension of the feature (maps if inside convolutional layer) (e.g. (11,32) for 32-band 11 frame spliced spectrogram patch) The type of convolution is controlled by hyperparameters: fmap_x_len_, fmap_y_len_ ... dimension of the feature (maps if inside convolutional layer) (e.g. (11,32) for 32-band 11 frame spliced spectrogram patch) filt_x_len_, filt_y_len_ ... temporal and frequency sizes of the filters (e.g. (9,9) for 9x9 2D filter) filt_x_step_, filt_y_step_ ... temporal and frequency sizes of the filters (e.g. (1,1) for 2D-filter, with 1 step shift in both axes)
Due to convolution same weights are used repeateadly, the final gradient is average of all position-specific gradients.
Definition at line 70 of file nnet-convolutional-2d-component.h.
Constructor & Destructor Documentation
Convolutional2DComponent (int32 dim_in, int32 dim_out) inline
Definition at line 72 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::Copy().
     : UpdatableComponent(dim_in, dim_out),
       fmap_x_len_(0), fmap_y_len_(0),
       filt_x_len_(0), filt_y_len_(0),
       filt_x_step_(0), filt_y_step_(0),
       connect_fmap_(0), learn_rate_coef_(1.0), bias_learn_rate_coef_(1.0)
   { }
~Convolutional2DComponent () inline
Definition at line 79 of file nnet-convolutional-2d-component.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 314 of file nnet-convolutional-2d-component.h.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::ColRange(), Convolutional2DComponent::connect_fmap_, CuVectorBase< Real >::Dim(), Convolutional2DComponent::feature_patch_diffs_, Convolutional2DComponent::filt_x_len_, Convolutional2DComponent::filt_x_step_, Convolutional2DComponent::filt_y_len_, Convolutional2DComponent::filt_y_step_, Convolutional2DComponent::filters_, Convolutional2DComponent::fmap_x_len_, Convolutional2DComponent::fmap_y_len_, rnnlm::i, Convolutional2DComponent::in_diff_summands_, Component::input_dim_, CuVectorBase< Real >::InvertElements(), rnnlm::j, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kSetZero, CuMatrixBase< Real >::MulColsVec(), rnnlm::n, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, CuVectorBase< Real >::Range(), and CuVector< Real >::Resize().
{
     // useful dims
     int32 num_input_fmaps = input_dim_ / (fmap_x_len_ * fmap_y_len_);
     int32 out_fmap_x_len = (fmap_x_len_ - filt_x_len_)/filt_x_step_ + 1;
     int32 out_fmap_y_len = (fmap_y_len_ - filt_y_len_)/filt_y_step_ + 1;
     int32 out_fmap_size = out_fmap_x_len * out_fmap_y_len;
     int32 num_output_fmaps = output_dim_ / (out_fmap_x_len * out_fmap_y_len);
     // this is total num_filters,
     // so each input_fmap has num_filters/num_input_fmaps
     int32 num_filters = filters_.NumRows();
     KALDI_ASSERT(num_filters == num_output_fmaps);
     // int32 filter_size = filt_x_len_*filt_y_len_;
     int32 num_frames = in.NumRows();
     for (int32 p = 0; p < out_fmap_size; p++) {
       feature_patch_diffs_[p].Resize(num_frames, filters_.NumCols(), kSetZero);
       CuSubMatrix<BaseFloat> out_diff_patch(out_diff.ColRange(p*num_filters, num_filters));
       feature_patch_diffs_[p].AddMatMat(1.0, out_diff_patch, kNoTrans, filters_, kNoTrans, 0.0);
     }
     // compute in_diff_summands_ once
     if (in_diff_summands_.Dim() == 0) {
       in_diff_summands_.Resize(in_diff->NumCols(), kSetZero);
       for (int32 m = 0; m < fmap_x_len_-filt_x_len_+1; m = m+filt_x_step_) {
         for (int32 n = 0; n < fmap_y_len_-filt_y_len_+1; n = n+filt_y_step_) {
           int32 st = 0;
           if (connect_fmap_ == 1) {
             st = (m * fmap_y_len_ + n) * num_input_fmaps;
           } else {
             st = m * fmap_y_len_ * num_input_fmaps + n;
           }
           for (int32 i = 0; i < filt_x_len_; i++) {
             for (int32 j = 0; j < filt_y_len_*num_input_fmaps; j++) {
               int32 c = 0;
               if (connect_fmap_ == 1) {
                 c = st + i * (num_input_fmaps * fmap_y_len_) + j;
               } else {
                 c = st + i * (num_input_fmaps * fmap_y_len_)
                        + (j / num_input_fmaps)
                        + (j % num_input_fmaps) * fmap_y_len_;
               }
               // add 1.0
               in_diff_summands_.Range(c, 1).Add(1.0);
             }
           }
         }
       }
       in_diff_summands_.InvertElements();
     }
     int32 out_fmap_cnt = 0;
     for (int32 m = 0; m < fmap_x_len_-filt_x_len_+1; m = m+filt_x_step_) {
       for (int32 n = 0; n< fmap_y_len_-filt_y_len_+1; n = n+filt_y_step_) {
         int32 st = 0;
         if (connect_fmap_ == 1) {
           st = (m * fmap_y_len_ + n) * num_input_fmaps;
         } else {
           st = m * fmap_y_len_ * num_input_fmaps + n;
         }
         for (int32 i = 0; i < filt_x_len_; i++) {
           for (int32 j = 0; j < filt_y_len_*num_input_fmaps; j++) {
             int32 c = 0;
             if (connect_fmap_ == 1) {
               c = st + i *(num_input_fmaps*fmap_y_len_)+j;
             } else {
               c = st + i * (num_input_fmaps * fmap_y_len_)
                      + (j / num_input_fmaps)
                      + (j % num_input_fmaps) * fmap_y_len_;
             }
             CuSubMatrix<BaseFloat> src(feature_patch_diffs_[out_fmap_cnt].ColRange(i*filt_y_len_*num_input_fmaps+j, 1));  // from which col
             CuSubMatrix<BaseFloat> tgt(in_diff->ColRange(c, 1));  // to which col?
             tgt.AddMat(1.0, src);
           }
         }
         out_fmap_cnt++;
       }
     }
     // compensate for summands
     in_diff->MulColsVec(in_diff_summands_);
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 82 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::Convolutional2DComponent().
 { return new Convolutional2DComponent(*this); }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 232 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_, CuVectorBase< Real >::Dim(), Convolutional2DComponent::filters_, CuMatrixBase< Real >::NumCols(), Convolutional2DComponent::NumParams(), CuMatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), and Vector< Real >::Resize().
{
     wei_copy->Resize(NumParams());
     int32 filters_num_elem = filters_.NumRows() * filters_.NumCols();
     wei_copy->Range(0, filters_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(filters_));
     wei_copy->Range(filters_num_elem, bias_.Dim()).CopyFromVec(Vector<BaseFloat>(bias_));
   }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 83 of file nnet-convolutional-2d-component.h.
References Component::kConvolutional2DComponent.
 { return kConvolutional2DComponent; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 239 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_, Convolutional2DComponent::filters_, and kaldi::nnet1::MomentStatistics().
{
     return std::string("\n  filters") + MomentStatistics(filters_) +
            "\n  bias" + MomentStatistics(bias_);
   }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 243 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_grad_, Convolutional2DComponent::bias_learn_rate_coef_, Convolutional2DComponent::filters_grad_, Convolutional2DComponent::learn_rate_coef_, kaldi::nnet1::MomentStatistics(), and kaldi::nnet1::ToString().
{
     return std::string("\n  filters_grad") + MomentStatistics(filters_grad_) +
            ", lr-coef " + ToString(learn_rate_coef_) +
            "\n  bias_grad" + MomentStatistics(bias_grad_) +
            ", lr-coef " + ToString(bias_learn_rate_coef_);
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 85 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_, Convolutional2DComponent::bias_learn_rate_coef_, Convolutional2DComponent::connect_fmap_, Convolutional2DComponent::filt_x_len_, Convolutional2DComponent::filt_x_step_, Convolutional2DComponent::filt_y_len_, Convolutional2DComponent::filt_y_step_, Convolutional2DComponent::filters_, Convolutional2DComponent::fmap_x_len_, Convolutional2DComponent::fmap_y_len_, rnnlm::i, Component::input_dim_, KALDI_ASSERT, KALDI_ERR, KALDI_LOG, Convolutional2DComponent::learn_rate_coef_, Component::output_dim_, kaldi::RandGauss(), kaldi::RandUniform(), kaldi::ReadBasicType(), and kaldi::ReadToken().
{
     // define options
     BaseFloat bias_mean = -2.0, bias_range = 2.0, param_stddev = 0.1;
     BaseFloat learn_rate_coef = 1.0, bias_learn_rate_coef = 1.0;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<ParamStddev>") ReadBasicType(is, false, &param_stddev);
       else if (token == "<BiasMean>")    ReadBasicType(is, false, &bias_mean);
       else if (token == "<BiasRange>")   ReadBasicType(is, false, &bias_range);
       else if (token == "<FmapXLen>")    ReadBasicType(is, false, &fmap_x_len_);
       else if (token == "<FmapYLen>")    ReadBasicType(is, false, &fmap_y_len_);
       else if (token == "<FiltXLen>")    ReadBasicType(is, false, &filt_x_len_);
       else if (token == "<FiltYLen>")    ReadBasicType(is, false, &filt_y_len_);
       else if (token == "<FiltXStep>")   ReadBasicType(is, false, &filt_x_step_);
       else if (token == "<FiltYStep>")   ReadBasicType(is, false, &filt_y_step_);
       else if (token == "<ConnectFmap>") ReadBasicType(is, false, &connect_fmap_);
       else if (token == "<LearnRateCoef>") ReadBasicType(is, false, &learn_rate_coef);
       else if (token == "<BiasLearnRateCoef>") ReadBasicType(is, false, &bias_learn_rate_coef);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (ParamStddev|BiasMean|BiasRange|FmapXLen|FmapYLen|FiltXLen|FiltYLen|FiltXStep|FiltYStep|ConnectFmap|LearnRateCoef|BiasLearnRateCoef)";
       is >> std::ws;  // eat-up whitespace
     }
     //
     // Sanity checks:
     //
     // input sanity checks
     // input_dim_ should be multiple of (fmap_x_len_ * fmap_y_len_)
     KALDI_ASSERT(input_dim_ % (fmap_x_len_ * fmap_y_len_) == 0);
     int32 num_input_fmaps = input_dim_ / (fmap_x_len_ * fmap_y_len_);
     KALDI_LOG << "num_input_fmaps " << num_input_fmaps;
     // check if step is in sync with fmap_len and filt_len
     KALDI_ASSERT((fmap_x_len_ - filt_x_len_) % (filt_x_step_) == 0);
     KALDI_ASSERT((fmap_y_len_ - filt_y_len_) % (filt_y_step_) == 0);
     int32 out_fmap_x_len = (fmap_x_len_ - filt_x_len_)/filt_x_step_ + 1;
     int32 out_fmap_y_len = (fmap_y_len_ - filt_y_len_)/filt_y_step_ + 1;
     //    int32 out_fmap_size = out_fmap_x_len*out_fmap_y_len;
     // output sanity checks
     KALDI_ASSERT(output_dim_ % (out_fmap_x_len * out_fmap_y_len)  == 0);
     int32 num_output_fmaps = output_dim_ / (out_fmap_x_len * out_fmap_y_len);
     KALDI_LOG << "num_output_fmaps " << num_output_fmaps;
     int32 num_filters = output_dim_/(out_fmap_x_len*out_fmap_y_len);
     KALDI_LOG << "num_filters " << num_filters;
     //
     // Initialize parameters
     //
     Matrix<BaseFloat> mat(num_filters, num_input_fmaps*filt_x_len_*filt_y_len_);
     for (int32 r = 0; r < num_filters; r++) {
       for (int32 c = 0; c < num_input_fmaps*filt_x_len_*filt_y_len_; c++) {
         // 0-mean Gauss with given std_dev
         mat(r, c) = param_stddev * RandGauss();
       }
     }
     filters_ = mat;
     //
     Vector<BaseFloat> vec(num_filters);
     for (int32 i = 0; i < num_filters; i++) {
       // +/- 1/2*bias_range from bias_mean:
       vec(i) = bias_mean + (RandUniform() - 0.5) * bias_range;
     }
     bias_ = vec;
     //
     learn_rate_coef_ = learn_rate_coef;
     bias_learn_rate_coef_ = bias_learn_rate_coef;
     //
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 228 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_, CuVectorBase< Real >::Dim(), Convolutional2DComponent::filters_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by Convolutional2DComponent::GetParams().
{
     return filters_.NumRows()*filters_.NumCols() + bias_.Dim();
   }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 250 of file nnet-convolutional-2d-component.h.
References CuMatrixBase< Real >::AddVecToRows(), Convolutional2DComponent::bias_, CuMatrixBase< Real >::ColRange(), Convolutional2DComponent::connect_fmap_, Convolutional2DComponent::feature_patch_diffs_, Convolutional2DComponent::filt_x_len_, Convolutional2DComponent::filt_x_step_, Convolutional2DComponent::filt_y_len_, Convolutional2DComponent::filt_y_step_, Convolutional2DComponent::filters_, Convolutional2DComponent::fmap_x_len_, Convolutional2DComponent::fmap_y_len_, rnnlm::i, Component::input_dim_, rnnlm::j, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, rnnlm::n, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, and Convolutional2DComponent::vectorized_feature_patches_.
{
     // useful dims
     int32 num_input_fmaps = input_dim_ / (fmap_x_len_ * fmap_y_len_);
     // int32 inp_fmap_size = fmap_x_len_ * fmap_y_len_;
     int32 out_fmap_x_len = (fmap_x_len_ - filt_x_len_)/filt_x_step_ + 1;
     int32 out_fmap_y_len = (fmap_y_len_ - filt_y_len_)/filt_y_step_ + 1;
     int32 out_fmap_size = out_fmap_x_len*out_fmap_y_len;
     int32 num_output_fmaps = output_dim_ / (out_fmap_x_len * out_fmap_y_len);
     // this is total num_filters,
     // so each input_fmap has size num_filters/num_input_fmaps
     int32 num_filters = filters_.NumRows();
     KALDI_ASSERT(num_filters == num_output_fmaps);
     // int32 filter_size = filt_x_len_*filt_y_len_;
     int32 num_frames = in.NumRows();
     // we will need the buffers
     if (vectorized_feature_patches_.size() == 0) {
       vectorized_feature_patches_.resize(out_fmap_size);
       feature_patch_diffs_.resize(out_fmap_size);
     }
     for (int32 p = 0; p < out_fmap_size; p++) {
       vectorized_feature_patches_[p].Resize(num_frames, filters_.NumCols());
     }
     // Checked for num_input_fmaps=1, check for num_inp_fmaps>1
     int32 out_fmap_cnt = 0;
     for (int32 m = 0; m < fmap_x_len_-filt_x_len_+1; m = m+filt_x_step_) {
       for (int32 n = 0; n < fmap_y_len_-filt_y_len_+1; n = n+filt_y_step_) {
     std::vector<int32> column_mask;
     int32 st = 0;
     if (connect_fmap_ == 1) {
       st = (m * fmap_y_len_ + n) * num_input_fmaps;
     } else {
       st = m * fmap_y_len_ * num_input_fmaps + n;
     }
     for (int32 i = 0; i < filt_x_len_; i++) {
       for (int32 j = 0; j < filt_y_len_*num_input_fmaps; j++) {
         int32 c = 0;
         if (connect_fmap_ == 1) {
           c = st + i * (num_input_fmaps*fmap_y_len_) + j;
         } else {
           c = st + i * (num_input_fmaps * fmap_y_len_)
                      + (j / num_input_fmaps)
                      + (j % num_input_fmaps) * fmap_y_len_;
         }
         column_mask.push_back(c);
       }
     }
     CuArray<int32> cu_column_mask(column_mask);
     vectorized_feature_patches_[out_fmap_cnt].CopyCols(in, cu_column_mask);
     out_fmap_cnt++;
       }
     }
     for (int32 p = 0; p < out_fmap_size; p++) {
       CuSubMatrix<BaseFloat> tgt(out->ColRange(p*num_filters, num_filters));
       tgt.AddVecToRows(1.0, bias_, 0.0);
       tgt.AddMatMat(1.0, vectorized_feature_patches_[p], kNoTrans, filters_, kTrans, 1.0);
     }
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 155 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_, Convolutional2DComponent::bias_learn_rate_coef_, Convolutional2DComponent::connect_fmap_, kaldi::ExpectToken(), Convolutional2DComponent::filt_x_len_, Convolutional2DComponent::filt_x_step_, Convolutional2DComponent::filt_y_len_, Convolutional2DComponent::filt_y_step_, Convolutional2DComponent::filters_, Convolutional2DComponent::fmap_x_len_, Convolutional2DComponent::fmap_y_len_, Component::input_dim_, KALDI_ASSERT, Convolutional2DComponent::learn_rate_coef_, Component::output_dim_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), and kaldi::ReadBasicType().
{
     ExpectToken(is, binary, "<LearnRateCoef>");
     ReadBasicType(is, binary, &learn_rate_coef_);
     ExpectToken(is, binary, "<BiasLearnRateCoef>");
     ReadBasicType(is, binary, &bias_learn_rate_coef_);
     // convolution hyperparameters
     ExpectToken(is, binary, "<FmapXLen>");
     ReadBasicType(is, binary, &fmap_x_len_);
     ExpectToken(is, binary, "<FmapYLen>");
     ReadBasicType(is, binary, &fmap_y_len_);
     ExpectToken(is, binary, "<FiltXLen>");
     ReadBasicType(is, binary, &filt_x_len_);
     ExpectToken(is, binary, "<FiltYLen>");
     ReadBasicType(is, binary, &filt_y_len_);
     ExpectToken(is, binary, "<FiltXStep>");
     ReadBasicType(is, binary, &filt_x_step_);
     ExpectToken(is, binary, "<FiltYStep>");
     ReadBasicType(is, binary, &filt_y_step_);
     ExpectToken(is, binary, "<ConnectFmap>");
     ReadBasicType(is, binary, &connect_fmap_);
     // trainable parameters
     ExpectToken(is, binary, "<Filters>");
     filters_.Read(is, binary);
     ExpectToken(is, binary, "<Bias>");
     bias_.Read(is, binary);
     //
     // Sanity checks:
     //
     // input sanity checks
     // input_dim_ should be multiple of (fmap_x_len_ * fmap_y_len_)
     KALDI_ASSERT(input_dim_ % (fmap_x_len_ * fmap_y_len_) == 0);
     // int32 num_input_fmaps = input_dim_ / (fmap_x_len_ * fmap_y_len_);
     // KALDI_LOG << "num_input_fmaps " << num_input_fmaps;
     // check if step is in sync with fmap_len and filt_len
     KALDI_ASSERT((fmap_x_len_ - filt_x_len_) % (filt_x_step_) == 0);
     KALDI_ASSERT((fmap_y_len_ - filt_y_len_) % (filt_y_step_) == 0);
     int32 out_fmap_x_len = (fmap_x_len_ - filt_x_len_)/filt_x_step_ + 1;
     int32 out_fmap_y_len = (fmap_y_len_ - filt_y_len_)/filt_y_step_ + 1;
     // output sanity checks
     KALDI_ASSERT(output_dim_ % (out_fmap_x_len * out_fmap_y_len)  == 0);
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 400 of file nnet-convolutional-2d-component.h.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), Convolutional2DComponent::bias_, Convolutional2DComponent::bias_grad_, Convolutional2DComponent::bias_learn_rate_coef_, CuMatrixBase< Real >::ColRange(), Convolutional2DComponent::filt_x_len_, Convolutional2DComponent::filt_x_step_, Convolutional2DComponent::filt_y_len_, Convolutional2DComponent::filt_y_step_, Convolutional2DComponent::filters_, Convolutional2DComponent::filters_grad_, Convolutional2DComponent::fmap_x_len_, Convolutional2DComponent::fmap_y_len_, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, NnetTrainOptions::learn_rate, Convolutional2DComponent::learn_rate_coef_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), UpdatableComponent::opts_, Component::output_dim_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), and Convolutional2DComponent::vectorized_feature_patches_.
{
     // useful dims
     int32 out_fmap_x_len = (fmap_x_len_ - filt_x_len_)/filt_x_step_ + 1;
     int32 out_fmap_y_len = (fmap_y_len_ - filt_y_len_)/filt_y_step_ + 1;
     int32 out_fmap_size = out_fmap_x_len*out_fmap_y_len;
     int32 num_output_fmaps = output_dim_ / (out_fmap_x_len * out_fmap_y_len);
     int32 num_filters = filters_.NumRows();  // this is total num_filters, so each input_fmap has num_filters/num_input_fmaps
     KALDI_ASSERT(num_filters == num_output_fmaps);
     // we use following hyperparameters from the option class
     const BaseFloat lr = opts_.learn_rate;
     /* NOT NOW:
     const BaseFloat mmt = opts_.momentum;
     const BaseFloat l2 = opts_.l2_penalty;
     const BaseFloat l1 = opts_.l1_penalty;
     */
     //
     // calculate the gradient
     //
     filters_grad_.Resize(filters_.NumRows(), filters_.NumCols(), kSetZero);
     bias_grad_.Resize(filters_.NumRows());
     for (int32 p = 0; p < out_fmap_size; p++) {
       CuSubMatrix<BaseFloat> diff_patch(diff.ColRange(p*num_filters, num_filters));
       filters_grad_.AddMatMat(1.0, diff_patch, kTrans, vectorized_feature_patches_[p], kNoTrans, 1.0);
       bias_grad_.AddRowSumMat(1.0, diff_patch, 1.0);
     }
     // scale
     filters_grad_.Scale(1.0/out_fmap_size);
     bias_grad_.Scale(1.0/out_fmap_size);
     //
     // update
     //
     filters_.AddMat(-lr*learn_rate_coef_, filters_grad_);
     bias_.AddVec(-lr*bias_learn_rate_coef_, bias_grad_);
     //
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 200 of file nnet-convolutional-2d-component.h.
References Convolutional2DComponent::bias_, Convolutional2DComponent::bias_learn_rate_coef_, Convolutional2DComponent::connect_fmap_, Convolutional2DComponent::filt_x_len_, Convolutional2DComponent::filt_x_step_, Convolutional2DComponent::filt_y_len_, Convolutional2DComponent::filt_y_step_, Convolutional2DComponent::filters_, Convolutional2DComponent::fmap_x_len_, Convolutional2DComponent::fmap_y_len_, Convolutional2DComponent::learn_rate_coef_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<LearnRateCoef>");
     WriteBasicType(os, binary, learn_rate_coef_);
     WriteToken(os, binary, "<BiasLearnRateCoef>");
     WriteBasicType(os, binary, bias_learn_rate_coef_);
     // convolution hyperparameters
     WriteToken(os, binary, "<FmapXLen>");
     WriteBasicType(os, binary, fmap_x_len_);
     WriteToken(os, binary, "<FmapYLen>");
     WriteBasicType(os, binary, fmap_y_len_);
     WriteToken(os, binary, "<FiltXLen>");
     WriteBasicType(os, binary, filt_x_len_);
     WriteToken(os, binary, "<FiltYLen>");
     WriteBasicType(os, binary, filt_y_len_);
     WriteToken(os, binary, "<FiltXStep>");
     WriteBasicType(os, binary, filt_x_step_);
     WriteToken(os, binary, "<FiltYStep>");
     WriteBasicType(os, binary, filt_y_step_);
     WriteToken(os, binary, "<ConnectFmap>");
     WriteBasicType(os, binary, connect_fmap_);
     // trainable parameters
     WriteToken(os, binary, "<Filters>");
     filters_.Write(os, binary);
     WriteToken(os, binary, "<Bias>");
     bias_.Write(os, binary);
   }
Member Data Documentation
CuVector<BaseFloat> bias_ private
bias for each filter
Definition at line 452 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::GetParams(), Convolutional2DComponent::Info(), Convolutional2DComponent::InitData(), Convolutional2DComponent::NumParams(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
CuVector<BaseFloat> bias_grad_ private
gradient of biases
Definition at line 455 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::InfoGradient(), and Convolutional2DComponent::Update().
BaseFloat bias_learn_rate_coef_ private
Definition at line 449 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::InfoGradient(), Convolutional2DComponent::InitData(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
int32 connect_fmap_ private
if connect_fmap_ = 1, then each fmap has num_filt
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), and Convolutional2DComponent::WriteData().
std::vector<CuMatrix<BaseFloat> > feature_patch_diffs_ private
Buffer for backpropagation: derivatives in the domain of 'vectorized_feature_patches_', 1row = vectorized rectangular feature patch, 1col = dim over speech frames, std::vector-dim = patch-position.
Definition at line 470 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), and Convolutional2DComponent::PropagateFnc().
int32 filt_x_len_ private
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
int32 filt_x_step_ private
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
int32 filt_y_len_ private
2D filter dimensions, x_ temporal, y_ spectral
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
int32 filt_y_step_ private
2D shifts along temporal and spectral
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
CuMatrix<BaseFloat> filters_ private
row = vectorized rectangular filter
Definition at line 451 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::GetParams(), Convolutional2DComponent::Info(), Convolutional2DComponent::InitData(), Convolutional2DComponent::NumParams(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
CuMatrix<BaseFloat> filters_grad_ private
gradient of filters
Definition at line 454 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::InfoGradient(), and Convolutional2DComponent::Update().
int32 fmap_x_len_ private
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
int32 fmap_y_len_ private
feature maps dimensions (for input x_ is usually splice and y_ is num of fbanks) shift for 2nd dim of a patch (i.e. frame length before splicing)
Definition at line 443 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), Convolutional2DComponent::InitData(), Convolutional2DComponent::PropagateFnc(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
CuVector<BaseFloat> in_diff_summands_ private
Auxiliary vector for compensating #summands when backpropagating.
Definition at line 473 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::BackpropagateFnc().
BaseFloat learn_rate_coef_ private
Definition at line 448 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::InfoGradient(), Convolutional2DComponent::InitData(), Convolutional2DComponent::ReadData(), Convolutional2DComponent::Update(), and Convolutional2DComponent::WriteData().
std::vector<CuMatrix<BaseFloat> > vectorized_feature_patches_ private
Buffer of reshaped inputs: 1row = vectorized rectangular feature patch, 1col = dim over speech frames, std::vector-dim = patch-position.
Definition at line 462 of file nnet-convolutional-2d-component.h.
Referenced by Convolutional2DComponent::PropagateFnc(), and Convolutional2DComponent::Update().
The documentation for this class was generated from the following file:
nnet/nnet-convolutional-2d-component.h