Kaldi: BiglmFasterDecoder::Token Class Reference
BiglmFasterDecoder::Token Class Reference
Public Member Functions
Token (const Arc &arc, Weight &ac_weight, Token *prev)
Token (const Arc &arc, Token *prev)
bool operator< (const Token &other)
~Token ()
Static Public Member Functions
static void TokenDelete (Token *tok)
Public Attributes
Arc arc_
Token * prev_
int32 ref_count_
Weight weight_
Detailed Description
Definition at line 194 of file biglm-faster-decoder.h.
Constructor & Destructor Documentation
Token (const Arc & arc, Weight & ac_weight, Token * prev) inline
Definition at line 203 of file biglm-faster-decoder.h.
References BiglmFasterDecoder::Token::ref_count_, fst::Times(), and BiglmFasterDecoder::Token::weight_.
                                                                 :
         arc_(arc), prev_(prev), ref_count_(1) {
       if (prev) {
         prev->ref_count_++;
         weight_ = Times(Times(prev->weight_, arc.weight), ac_weight);
       } else {
         weight_ = Times(arc.weight, ac_weight);
       }
     }
Token (const Arc & arc, Token * prev) inline
Definition at line 212 of file biglm-faster-decoder.h.
References BiglmFasterDecoder::Token::ref_count_, fst::Times(), and BiglmFasterDecoder::Token::weight_.
                                              :
         arc_(arc), prev_(prev), ref_count_(1) {
       if (prev) {
         prev->ref_count_++;
         weight_ = Times(prev->weight_, arc.weight);
       } else {
         weight_ = arc.weight;
       }
     }
~Token () inline
Definition at line 226 of file biglm-faster-decoder.h.
References KALDI_ASSERT, BiglmFasterDecoder::Token::prev_, BiglmFasterDecoder::Token::ref_count_, and BiglmFasterDecoder::Token::TokenDelete().
                     {
       KALDI_ASSERT(ref_count_ == 1);
       if (prev_ != NULL) TokenDelete(prev_);
     }
Member Function Documentation
bool operator< (const Token & other) inline
Definition at line 221 of file biglm-faster-decoder.h.
References BiglmFasterDecoder::Token::weight_.
{
       return weight_.Value() > other.weight_.Value();
       // This makes sense for log + tropical semiring.
     }
static void TokenDelete (Token * tok) inline static
Definition at line 230 of file biglm-faster-decoder.h.
References BiglmFasterDecoder::Token::ref_count_.
Referenced by BiglmFasterDecoder::ClearToks(), BiglmFasterDecoder::ProcessEmitting(), BiglmFasterDecoder::ProcessNonemitting(), and BiglmFasterDecoder::Token::~Token().
{
       if (tok->ref_count_ == 1) {
         delete tok;
       } else {
         tok->ref_count_--;
       }
     }
Member Data Documentation
Arc arc_
Definition at line 196 of file biglm-faster-decoder.h.
Referenced by BiglmFasterDecoder::ProcessEmitting().
Token* prev_
Definition at line 200 of file biglm-faster-decoder.h.
Referenced by BiglmFasterDecoder::GetBestPath(), and BiglmFasterDecoder::Token::~Token().
int32 ref_count_
Definition at line 201 of file biglm-faster-decoder.h.
Referenced by BiglmFasterDecoder::Token::Token(), BiglmFasterDecoder::Token::TokenDelete(), and BiglmFasterDecoder::Token::~Token().
Weight weight_
Definition at line 202 of file biglm-faster-decoder.h.
Referenced by BiglmFasterDecoder::GetBestPath(), BiglmFasterDecoder::Token::operator<(), BiglmFasterDecoder::ProcessEmitting(), BiglmFasterDecoder::ProcessNonemitting(), and BiglmFasterDecoder::Token::Token().
The documentation for this class was generated from the following file:
decoder/biglm-faster-decoder.h