Kaldi: TCNComponent Class Reference
TCNComponent Class Reference
#include <nnet-tcn-3way.h>
Public Member Functions
TCNComponent (int32 dim_in, int32 dim_out)
~TCNComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
const CuMatrixBase< BaseFloat > & GetCuMatrixBase (CuMatrix< BaseFloat > &cumatrix)
TCNComponent (int32 dim_in, int32 dim_out)
~TCNComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
const CuMatrixBase< BaseFloat > & GetCuMatrixBase (CuMatrix< BaseFloat > &cumatrix)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Sets the training options to the component.
const NnetTrainOptions & GetTrainOptions () const
Gets the training options from the component.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
Private Attributes
int32 wei_1_i1_
int32 wei_1_j1_
int32 wei_2_i2_
int32 wei_2_j2_
int32 input_dim_1_
int32 input_dim_2_
int32 output_dim_1_
int32 output_dim_2_
int32 dim_in_
int32 dim_out_
BaseFloat learn_rate_coef_
BaseFloat bias_learn_rate_coef_
CuMatrix< BaseFloat > mode_1_wei_
CuMatrix< BaseFloat > mode_2_wei_
CuMatrix< BaseFloat > bias_
CuMatrix< BaseFloat > mode_1_wei_grad_
CuMatrix< BaseFloat > mode_2_wei_grad_
CuMatrix< BaseFloat > bias_grad_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Definition at line 14 of file nnet-tcn-3way.h.
Constructor & Destructor Documentation
TCNComponent (int32 dim_in, int32 dim_out) inline
Definition at line 16 of file nnet-tcn-3way.h.
Referenced by TCNComponent::Copy().
     : UpdatableComponent(dim_in, dim_out),
       //initial dimension parameters
       dim_in_(dim_in),dim_out_(dim_out),
       wei_1_i1_(0.0),wei_2_i2_(0.0),wei_1_j1_(0.0),wei_2_j2_(0.0),
       input_dim_1_(0.0),input_dim_2_(0.0),
       output_dim_1_(0.0),output_dim_2_(0.0),
       //initial learning rate
       learn_rate_coef_(1.0), bias_learn_rate_coef_(1.0)
   { }
~TCNComponent () inline
Definition at line 26 of file nnet-tcn-3way.h.
   { }
TCNComponent (int32 dim_in, int32 dim_out) inline
Definition at line 16 of file nnet-tcn.h.
     : UpdatableComponent(dim_in, dim_out),
       //initial dimension parameters
       dim_in_(dim_in),dim_out_(dim_out),
       wei_1_i1_(0.0),wei_2_i2_(0.0),wei_1_j1_(0.0),wei_2_j2_(0.0),
       input_dim_1_(0.0),input_dim_2_(0.0),
       output_dim_1_(0.0),output_dim_2_(0.0),
       //initial learning rate
       learn_rate_coef_(1.0), bias_learn_rate_coef_(1.0)
   { }
~TCNComponent () inline
Definition at line 26 of file nnet-tcn.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 282 of file nnet-tcn-3way.h.
References CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumRows(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
   {
     int32 batch_size = in.NumRows();                  //get batch size
     // give initial size
     CuMatrix<BaseFloat> temp(batch_size, wei_1_i1_ * wei_2_j2_);
     CuMatrix<BaseFloat> input_diff(batch_size, wei_1_i1_ * wei_2_i2_);
     // reshape to std::vector
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_input_diff;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_output_diff;
     // w1_vec and w2_vec used to parallel
     std::vector< CuSubMatrix<BaseFloat>* > w1_vec;
     std::vector< CuSubMatrix<BaseFloat>* > w2_vec;
     CuSubMatrix<BaseFloat>* w1 = new CuSubMatrix<BaseFloat>(mode_1_wei_,0,wei_1_j1_,0,wei_1_i1_);
     CuSubMatrix<BaseFloat>* w2 = new CuSubMatrix<BaseFloat>(mode_2_wei_,0,wei_2_j2_,0,wei_2_i2_);
     // initial some vectors
     for(int32 i = 0; i < in.NumRows(); i++)
     {
        CuSubMatrix<BaseFloat> *temp_reshaped_temp = new CuSubMatrix<BaseFloat>(temp,i,wei_1_i1_,wei_2_j2_);               //i1 * j2
        CuSubMatrix<BaseFloat> *temp_reshaped_output_diff = new CuSubMatrix<BaseFloat>(out_diff,i,wei_1_j1_,wei_2_j2_);    //j1 * j2
        CuSubMatrix<BaseFloat> *temp_reshaped_input_diff = new CuSubMatrix<BaseFloat>(input_diff,i,wei_1_i1_,wei_2_i2_);   //i1 * i2
        w1_vec.push_back(w1);
        w2_vec.push_back(w2);
        reshaped_temp.push_back(temp_reshaped_temp);
        reshaped_output_diff.push_back(temp_reshaped_output_diff);
        reshaped_input_diff.push_back(temp_reshaped_input_diff);
     }
     AddMatMatBatched<BaseFloat>(1.0,reshaped_temp,w1_vec,kTrans,reshaped_output_diff,kNoTrans,0.0);
     AddMatMatBatched<BaseFloat>(1.0,reshaped_input_diff,reshaped_temp,kNoTrans,w2_vec,kNoTrans,0.0);
     in_diff->CopyFromMat(input_diff);
     // delete pointers
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp.begin(); i!=reshaped_temp.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_input_diff.begin(); i!=reshaped_input_diff.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_output_diff.begin(); i!=reshaped_output_diff.end(); ++i)
       delete *i;
     delete w1;
     delete w2;
   }
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 282 of file nnet-tcn.h.
References CuMatrixBase< Real >::CopyFromMat(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumRows(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
   {
     int32 batch_size = in.NumRows();                  //get batch size
     // give initial size
     CuMatrix<BaseFloat> temp(batch_size, wei_1_i1_ * wei_2_j2_);
     CuMatrix<BaseFloat> input_diff(batch_size, wei_1_i1_ * wei_2_i2_);
     // reshape to std::vector
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_input_diff;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_output_diff;
     // w1_vec and w2_vec used to parallel
     std::vector< CuSubMatrix<BaseFloat>* > w1_vec;
     std::vector< CuSubMatrix<BaseFloat>* > w2_vec;
     CuSubMatrix<BaseFloat>* w1 = new CuSubMatrix<BaseFloat>(mode_1_wei_,0,wei_1_j1_,0,wei_1_i1_);
     CuSubMatrix<BaseFloat>* w2 = new CuSubMatrix<BaseFloat>(mode_2_wei_,0,wei_2_j2_,0,wei_2_i2_);
     // initial some vectors
     for(int32 i = 0; i < in.NumRows(); i++)
     {
        CuSubMatrix<BaseFloat> *temp_reshaped_temp = new CuSubMatrix<BaseFloat>(temp,i,wei_1_i1_,wei_2_j2_);               //i1 * j2
        CuSubMatrix<BaseFloat> *temp_reshaped_output_diff = new CuSubMatrix<BaseFloat>(out_diff,i,wei_1_j1_,wei_2_j2_);    //j1 * j2
        CuSubMatrix<BaseFloat> *temp_reshaped_input_diff = new CuSubMatrix<BaseFloat>(input_diff,i,wei_1_i1_,wei_2_i2_);   //i1 * i2
        w1_vec.push_back(w1);
        w2_vec.push_back(w2);
        reshaped_temp.push_back(temp_reshaped_temp);
        reshaped_output_diff.push_back(temp_reshaped_output_diff);
        reshaped_input_diff.push_back(temp_reshaped_input_diff);
     }
     AddMatMatBatched<BaseFloat>(1.0,reshaped_temp,w1_vec,kTrans,reshaped_output_diff,kNoTrans,0.0);
     AddMatMatBatched<BaseFloat>(1.0,reshaped_input_diff,reshaped_temp,kNoTrans,w2_vec,kNoTrans,0.0);
     in_diff->CopyFromMat(input_diff);
     // delete pointers
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp.begin(); i!=reshaped_temp.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_input_diff.begin(); i!=reshaped_input_diff.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_output_diff.begin(); i!=reshaped_output_diff.end(); ++i)
       delete *i;
     delete w1;
     delete w2;
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 31 of file nnet-tcn-3way.h.
References TCNComponent::TCNComponent().
 { return new TCNComponent(*this); }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 31 of file nnet-tcn.h.
References TCNComponent::TCNComponent().
 { return new TCNComponent(*this); }
const CuMatrixBase<BaseFloat>& GetCuMatrixBase (CuMatrix< BaseFloat > & cumatrix) inline
Definition at line 434 of file nnet-tcn.h.
   {
     return cumatrix;
   }
const CuMatrixBase<BaseFloat>& GetCuMatrixBase (CuMatrix< BaseFloat > & cumatrix) inline
Definition at line 434 of file nnet-tcn-3way.h.
   {
     return cumatrix;
   }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 202 of file nnet-tcn.h.
References TCNComponent::bias_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumCols(), TCNComponent::NumParams(), CuMatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), and Vector< Real >::Resize().
{
     //make a stack memories for all weights
     wei_copy->Resize(NumParams());
     int32 weight_1_num_elem = mode_1_wei_.NumRows() * mode_1_wei_.NumCols();
     int32 weight_2_num_elem = mode_2_wei_.NumRows() * mode_2_wei_.NumCols();
     int32 bias_num_elem = bias_.NumRows() * bias_.NumCols();
     //Range(o,l) o:original l:length
     wei_copy->Range(0, weight_1_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(mode_1_wei_));
     wei_copy->Range(weight_1_num_elem, weight_2_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(mode_2_wei_));
     wei_copy->Range(weight_1_num_elem+weight_2_num_elem, bias_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(bias_));
   }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 202 of file nnet-tcn-3way.h.
References TCNComponent::bias_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumCols(), TCNComponent::NumParams(), CuMatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), and Vector< Real >::Resize().
{
     //make a stack memories for all weights
     wei_copy->Resize(NumParams());
     int32 weight_1_num_elem = mode_1_wei_.NumRows() * mode_1_wei_.NumCols();
     int32 weight_2_num_elem = mode_2_wei_.NumRows() * mode_2_wei_.NumCols();
     int32 bias_num_elem = bias_.NumRows() * bias_.NumCols();
     //Range(o,l) o:original l:length
     wei_copy->Range(0, weight_1_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(mode_1_wei_));
     wei_copy->Range(weight_1_num_elem, weight_2_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(mode_2_wei_));
     wei_copy->Range(weight_1_num_elem+weight_2_num_elem, bias_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(bias_));
   }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 32 of file nnet-tcn-3way.h.
References Component::scTCNComponent.
 { return scTCNComponent; }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 32 of file nnet-tcn.h.
References Component::scTCNComponent.
 { return scTCNComponent; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 214 of file nnet-tcn-3way.h.
References TCNComponent::bias_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, and kaldi::nnet1::MomentStatistics().
{
     //Optionally print some additional info
     return std::string("\n  mode_1_weights") + MomentStatistics(mode_1_wei_) +
            "\n  mode_2_weights" +  MomentStatistics(mode_2_wei_) +
            "\n  bias" + MomentStatistics(bias_);
   }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 214 of file nnet-tcn.h.
References TCNComponent::bias_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, and kaldi::nnet1::MomentStatistics().
{
     //Optionally print some additional info
     return std::string("\n  mode_1_weights") + MomentStatistics(mode_1_wei_) +
            "\n  mode_2_weights" +  MomentStatistics(mode_2_wei_) +
            "\n  bias" + MomentStatistics(bias_);
   }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 220 of file nnet-tcn-3way.h.
References TCNComponent::bias_grad_, TCNComponent::bias_learn_rate_coef_, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_grad_, TCNComponent::mode_2_wei_grad_, kaldi::nnet1::MomentStatistics(), and kaldi::nnet1::ToString().
{
     //Reimplemented from Component
     return std::string("\n  mode_1_grad") + MomentStatistics(mode_1_wei_grad_) +
            "\n  mode_2_grad" + MomentStatistics(mode_2_wei_grad_) +
            ", lr-coef " + ToString(learn_rate_coef_) +
            "\n  bias_grad" + MomentStatistics(bias_grad_) +
            ", lr-coef " + ToString(bias_learn_rate_coef_);
   }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 220 of file nnet-tcn.h.
References TCNComponent::bias_grad_, TCNComponent::bias_learn_rate_coef_, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_grad_, TCNComponent::mode_2_wei_grad_, kaldi::nnet1::MomentStatistics(), and kaldi::nnet1::ToString().
{
     //Reimplemented from Component
     return std::string("\n  mode_1_grad") + MomentStatistics(mode_1_wei_grad_) +
            "\n  mode_2_grad" + MomentStatistics(mode_2_wei_grad_) +
            ", lr-coef " + ToString(learn_rate_coef_) +
            "\n  bias_grad" + MomentStatistics(bias_grad_) +
            ", lr-coef " + ToString(bias_learn_rate_coef_);
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 34 of file nnet-tcn.h.
References TCNComponent::bias_, TCNComponent::bias_learn_rate_coef_, TCNComponent::dim_in_, TCNComponent::dim_out_, TCNComponent::input_dim_1_, TCNComponent::input_dim_2_, KALDI_ASSERT, KALDI_ERR, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, TCNComponent::output_dim_1_, TCNComponent::output_dim_2_, kaldi::RandGauss(), kaldi::RandUniform(), kaldi::ReadBasicType(), kaldi::ReadToken(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
{
     // define options
     BaseFloat bias_mean = -2.0, bias_range = 2.0, param_stddev = 0.1;//stddev
     BaseFloat learn_rate_coef = 1.0, bias_learn_rate_coef = 1.0;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
       /*if  (token == "<InputDim>")      ReadBasicType(is, false, &input_dim_);
       else if (token == "<OutputDim>")     ReadBasicType(is, false, &output_dim_);*/
       if (token == "<BiasMean>")      ReadBasicType(is, false, &bias_mean);
       else if (token == "<BiasRange>")     ReadBasicType(is, false, &bias_range);
       else if (token == "<ParamStddev>")   ReadBasicType(is, false, &param_stddev);
       else if (token == "<InputDim1>")       ReadBasicType(is, false, &input_dim_1_);
       else if (token == "<InputDim2>")       ReadBasicType(is, false, &input_dim_2_);
       else if (token == "<OutputDim1>")      ReadBasicType(is, false, &output_dim_1_);
       else if (token == "<OutputDim2>")      ReadBasicType(is, false, &output_dim_2_);
       //else if (token == "<LearnRateCoef>") ReadBasicType(is, false, &learn_rate_coef);
       //else if (token == "<BiasLearnRateCoef>") ReadBasicType(is, false, &bias_learn_rate_coef);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (ParamStddev|BiasMean|BiasRange|FmapXLen|FmapYLen|FiltXLen|FiltYLen|FiltXStep|FiltYStep|ConnectFmap|LearnRateCoef|BiasLearnRateCoef)";
       is >> std::ws;  // eat-up whitespace
     }
     /*
     KALDI_LOG<< "===================tokening is over==================";
     KALDI_LOG<< "dim_in_: " << dim_in_;
     KALDI_LOG<< "dim_out_: " << dim_out_;
     //KALDI_LOG<< "input_dim_: " << input_dim_;
     //KALDI_LOG<< "output_dim_: " << output_dim_;
     KALDI_LOG<< "input dimension for way 1: " << input_dim_1_;
     KALDI_LOG<< "input dimension for way 2: " << input_dim_2_;
     KALDI_LOG<< "output dimension for way 2: " << output_dim_1_;
     KALDI_LOG<< "output dimension for way 2: " << output_dim_2_;
     KALDI_LOG<< "BiasMean:" << bias_mean;
     KALDI_LOG<< "BiasRange: " << bias_range;
     KALDI_LOG<< "ParamStddev: " << param_stddev;
     */
     //===============================================================//
     //                      Sanity checks:                           //
     //===============================================================//
     // input sanity checks
     KALDI_ASSERT(dim_in_ == input_dim_1_ * input_dim_2_);
     // output sanity checks
     KALDI_ASSERT(dim_out_ == output_dim_1_ * output_dim_2_);
     //===============================================================//
     //                Initialize parameters                          //
     //===============================================================//
     //initial dimension parameters
     wei_1_i1_ = input_dim_1_;
     wei_1_j1_ = output_dim_1_;
     wei_2_i2_ = input_dim_2_;
     wei_2_j2_ = output_dim_2_;
     //initialize weights
     Matrix<BaseFloat> mat_w1(wei_1_j1_,wei_1_i1_);
     Matrix<BaseFloat> mat_w2(wei_2_j2_,wei_2_i2_);
     for (int32 r = 0; r < wei_1_j1_; r++) {
       for (int32 c = 0; c < wei_1_i1_; c++) {
         // 0-mean Gauss with given std_dev for weight 1
         mat_w1(r, c) = param_stddev * RandGauss();
       }
     }
     for (int32 r = 0; r < wei_2_j2_; r++) {
       for (int32 c = 0; c < wei_2_i2_; c++) {
         // 0-mean Gauss with given std_dev for weight 2
         mat_w2(r, c) = param_stddev * RandGauss();
       }
     }
     mode_1_wei_ = mat_w1;     //mode 1 product weight
     mode_2_wei_ = mat_w2;     //mode 2 product weight
     //initialize bias
     Matrix<BaseFloat> mat_b(wei_1_j1_,wei_2_j2_);
     for (int32 r = 0; r < wei_1_j1_; r++) {
       for (int32 c = 0; c< wei_2_j2_; c++) {
         // +/- 1/2*bias_range      from bias_mean:
         mat_b(r,c) = bias_mean + (RandUniform() - 0.5) * bias_range;
       }
     }
     bias_ = mat_b;
     learn_rate_coef_ = learn_rate_coef;
     bias_learn_rate_coef_ = bias_learn_rate_coef;
     //
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 34 of file nnet-tcn-3way.h.
References TCNComponent::bias_, TCNComponent::bias_learn_rate_coef_, TCNComponent::dim_in_, TCNComponent::dim_out_, TCNComponent::input_dim_1_, TCNComponent::input_dim_2_, KALDI_ASSERT, KALDI_ERR, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, TCNComponent::output_dim_1_, TCNComponent::output_dim_2_, kaldi::RandGauss(), kaldi::RandUniform(), kaldi::ReadBasicType(), kaldi::ReadToken(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
{
     // define options
     BaseFloat bias_mean = -2.0, bias_range = 2.0, param_stddev = 0.1;//stddev
     BaseFloat learn_rate_coef = 1.0, bias_learn_rate_coef = 1.0;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
       /*if  (token == "<InputDim>")      ReadBasicType(is, false, &input_dim_);
       else if (token == "<OutputDim>")     ReadBasicType(is, false, &output_dim_);*/
       if (token == "<BiasMean>")      ReadBasicType(is, false, &bias_mean);
       else if (token == "<BiasRange>")     ReadBasicType(is, false, &bias_range);
       else if (token == "<ParamStddev>")   ReadBasicType(is, false, &param_stddev);
       else if (token == "<InputDim1>")       ReadBasicType(is, false, &input_dim_1_);
       else if (token == "<InputDim2>")       ReadBasicType(is, false, &input_dim_2_);
       else if (token == "<OutputDim1>")      ReadBasicType(is, false, &output_dim_1_);
       else if (token == "<OutputDim2>")      ReadBasicType(is, false, &output_dim_2_);
       //else if (token == "<LearnRateCoef>") ReadBasicType(is, false, &learn_rate_coef);
       //else if (token == "<BiasLearnRateCoef>") ReadBasicType(is, false, &bias_learn_rate_coef);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (ParamStddev|BiasMean|BiasRange|FmapXLen|FmapYLen|FiltXLen|FiltYLen|FiltXStep|FiltYStep|ConnectFmap|LearnRateCoef|BiasLearnRateCoef)";
       is >> std::ws;  // eat-up whitespace
     }
     /*
     KALDI_LOG<< "===================tokening is over==================";
     KALDI_LOG<< "dim_in_: " << dim_in_;
     KALDI_LOG<< "dim_out_: " << dim_out_;
     //KALDI_LOG<< "input_dim_: " << input_dim_;
     //KALDI_LOG<< "output_dim_: " << output_dim_;
     KALDI_LOG<< "input dimension for way 1: " << input_dim_1_;
     KALDI_LOG<< "input dimension for way 2: " << input_dim_2_;
     KALDI_LOG<< "output dimension for way 2: " << output_dim_1_;
     KALDI_LOG<< "output dimension for way 2: " << output_dim_2_;
     KALDI_LOG<< "BiasMean:" << bias_mean;
     KALDI_LOG<< "BiasRange: " << bias_range;
     KALDI_LOG<< "ParamStddev: " << param_stddev;
     */
     //===============================================================//
     //                      Sanity checks:                           //
     //===============================================================//
     // input sanity checks
     KALDI_ASSERT(dim_in_ == input_dim_1_ * input_dim_2_);
     // output sanity checks
     KALDI_ASSERT(dim_out_ == output_dim_1_ * output_dim_2_);
     //===============================================================//
     //                Initialize parameters                          //
     //===============================================================//
     //initial dimension parameters
     wei_1_i1_ = input_dim_1_;
     wei_1_j1_ = output_dim_1_;
     wei_2_i2_ = input_dim_2_;
     wei_2_j2_ = output_dim_2_;
     //initialize weights
     Matrix<BaseFloat> mat_w1(wei_1_j1_,wei_1_i1_);
     Matrix<BaseFloat> mat_w2(wei_2_j2_,wei_2_i2_);
     for (int32 r = 0; r < wei_1_j1_; r++) {
       for (int32 c = 0; c < wei_1_i1_; c++) {
         // 0-mean Gauss with given std_dev for weight 1
         mat_w1(r, c) = param_stddev * RandGauss();
       }
     }
     for (int32 r = 0; r < wei_2_j2_; r++) {
       for (int32 c = 0; c < wei_2_i2_; c++) {
         // 0-mean Gauss with given std_dev for weight 2
         mat_w2(r, c) = param_stddev * RandGauss();
       }
     }
     mode_1_wei_ = mat_w1;     //mode 1 product weight
     mode_2_wei_ = mat_w2;     //mode 2 product weight
     //initialize bias
     Matrix<BaseFloat> mat_b(wei_1_j1_,wei_2_j2_);
     for (int32 r = 0; r < wei_1_j1_; r++) {
       for (int32 c = 0; c< wei_2_j2_; c++) {
         // +/- 1/2*bias_range      from bias_mean:
         mat_b(r,c) = bias_mean + (RandUniform() - 0.5) * bias_range;
       }
     }
     bias_ = mat_b;
     learn_rate_coef_ = learn_rate_coef;
     bias_learn_rate_coef_ = bias_learn_rate_coef;
     //
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 196 of file nnet-tcn.h.
References TCNComponent::bias_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
     return mode_1_wei_.NumRows() * mode_1_wei_.NumCols()\
            +mode_2_wei_.NumRows() * mode_2_wei_.NumCols()\
            +bias_.NumRows() * bias_.NumCols();
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 196 of file nnet-tcn-3way.h.
References TCNComponent::bias_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by TCNComponent::GetParams().
{
     return mode_1_wei_.NumRows() * mode_1_wei_.NumCols()\
            +mode_2_wei_.NumRows() * mode_2_wei_.NumCols()\
            +bias_.NumRows() * bias_.NumCols();
   }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 235 of file nnet-tcn-3way.h.
References CuMatrixBase< Real >::AddVecToRows(), TCNComponent::bias_, CuMatrixBase< Real >::CopyFromMat(), CuVectorBase< Real >::CopyRowsFromMat(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumRows(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
   {
      int32 batch_size = in.NumRows();        // get batch size
      // give initial size
      CuMatrix<BaseFloat> output(batch_size, wei_1_j1_ * wei_2_j2_);
      CuMatrix<BaseFloat> temp(batch_size, wei_1_j1_ * wei_2_i2_);
      // reshape to std::vector
      std::vector< CuSubMatrix<BaseFloat>* > reshaped_input;
      std::vector< CuSubMatrix<BaseFloat>* > reshaped_output;
      std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp;
      // w1_vec and w2_vec used to parallel
      std::vector< CuSubMatrix<BaseFloat>* > w1_vec;
      std::vector< CuSubMatrix<BaseFloat>* > w2_vec;
      CuSubMatrix<BaseFloat>* w1 = new CuSubMatrix<BaseFloat>(mode_1_wei_,0,wei_1_j1_,0,wei_1_i1_);
      CuSubMatrix<BaseFloat>* w2 = new CuSubMatrix<BaseFloat>(mode_2_wei_,0,wei_2_j2_,0,wei_2_i2_);
      // initial some vectors
      for(int32 i = 0; i < batch_size; i++)
      {
         CuSubMatrix<BaseFloat> *temp_reshaped_input = new CuSubMatrix<BaseFloat>(in,i,wei_1_i1_,wei_2_i2_);
         CuSubMatrix<BaseFloat> *temp_reshaped_temp = new CuSubMatrix<BaseFloat>(temp,i,wei_1_j1_,wei_2_i2_);
         CuSubMatrix<BaseFloat> *temp_reshaped_output = new CuSubMatrix<BaseFloat>(output,i,wei_1_j1_,wei_2_j2_);
         w1_vec.push_back(w1);
         w2_vec.push_back(w2);
         reshaped_input.push_back(temp_reshaped_input);
         reshaped_temp.push_back(temp_reshaped_temp);
         reshaped_output.push_back(temp_reshaped_output);
      }
      AddMatMatBatched<BaseFloat>(1.0,reshaped_temp,w1_vec,kNoTrans,reshaped_input,kNoTrans,0.0);
      AddMatMatBatched<BaseFloat>(1.0,reshaped_output,reshaped_temp,kNoTrans,w2_vec,kTrans,0.0);
      out->CopyFromMat(output);
      CuVector<BaseFloat> bias_vec(wei_1_j1_ * wei_2_j2_);
      bias_vec.CopyRowsFromMat(bias_);
      out->AddVecToRows(1.0,bias_vec,1.0);
      // delete pointers
      for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_input.begin(); i!=reshaped_input.end(); ++i)
        delete *i;
      for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_output.begin(); i!=reshaped_output.end(); ++i)
        delete *i;
      for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp.begin(); i!=reshaped_temp.end(); ++i)
        delete *i;
      delete w1;
      delete w2;
   }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 235 of file nnet-tcn.h.
References CuMatrixBase< Real >::AddVecToRows(), TCNComponent::bias_, CuMatrixBase< Real >::CopyFromMat(), CuVectorBase< Real >::CopyRowsFromMat(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, CuMatrixBase< Real >::NumRows(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
   {
      int32 batch_size = in.NumRows();        // get batch size
      // give initial size
      CuMatrix<BaseFloat> output(batch_size, wei_1_j1_ * wei_2_j2_);
      CuMatrix<BaseFloat> temp(batch_size, wei_1_j1_ * wei_2_i2_);
      // reshape to std::vector
      std::vector< CuSubMatrix<BaseFloat>* > reshaped_input;
      std::vector< CuSubMatrix<BaseFloat>* > reshaped_output;
      std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp;
      // w1_vec and w2_vec used to parallel
      std::vector< CuSubMatrix<BaseFloat>* > w1_vec;
      std::vector< CuSubMatrix<BaseFloat>* > w2_vec;
      CuSubMatrix<BaseFloat>* w1 = new CuSubMatrix<BaseFloat>(mode_1_wei_,0,wei_1_j1_,0,wei_1_i1_);
      CuSubMatrix<BaseFloat>* w2 = new CuSubMatrix<BaseFloat>(mode_2_wei_,0,wei_2_j2_,0,wei_2_i2_);
      // initial some vectors
      for(int32 i = 0; i < batch_size; i++)
      {
         CuSubMatrix<BaseFloat> *temp_reshaped_input = new CuSubMatrix<BaseFloat>(in,i,wei_1_i1_,wei_2_i2_);
         CuSubMatrix<BaseFloat> *temp_reshaped_temp = new CuSubMatrix<BaseFloat>(temp,i,wei_1_j1_,wei_2_i2_);
         CuSubMatrix<BaseFloat> *temp_reshaped_output = new CuSubMatrix<BaseFloat>(output,i,wei_1_j1_,wei_2_j2_);
         w1_vec.push_back(w1);
         w2_vec.push_back(w2);
         reshaped_input.push_back(temp_reshaped_input);
         reshaped_temp.push_back(temp_reshaped_temp);
         reshaped_output.push_back(temp_reshaped_output);
      }
      AddMatMatBatched<BaseFloat>(1.0,reshaped_temp,w1_vec,kNoTrans,reshaped_input,kNoTrans,0.0);
      AddMatMatBatched<BaseFloat>(1.0,reshaped_output,reshaped_temp,kNoTrans,w2_vec,kTrans,0.0);
      out->CopyFromMat(output);
      CuVector<BaseFloat> bias_vec(wei_1_j1_ * wei_2_j2_);
      bias_vec.CopyRowsFromMat(bias_);
      out->AddVecToRows(1.0,bias_vec,1.0);
      // delete pointers
      for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_input.begin(); i!=reshaped_input.end(); ++i)
        delete *i;
      for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_output.begin(); i!=reshaped_output.end(); ++i)
        delete *i;
      for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp.begin(); i!=reshaped_temp.end(); ++i)
        delete *i;
      delete w1;
      delete w2;
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 125 of file nnet-tcn-3way.h.
References TCNComponent::bias_, TCNComponent::bias_learn_rate_coef_, kaldi::ExpectToken(), TCNComponent::input_dim_1_, TCNComponent::input_dim_2_, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, TCNComponent::output_dim_1_, TCNComponent::output_dim_2_, CuMatrix< Real >::Read(), kaldi::ReadBasicType(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
{
     ExpectToken(is, binary, "<LearnRateCoef>");
     ReadBasicType(is, binary, &learn_rate_coef_);
     ExpectToken(is, binary, "<BiasLearnRateCoef>");
     ReadBasicType(is, binary, &bias_learn_rate_coef_);
     // input output dimension parameters
     ExpectToken(is, binary, "<InputDim1>");
     ReadBasicType(is, binary, &input_dim_1_);
     ExpectToken(is, binary, "<InputDim2>");
     ReadBasicType(is, binary, &input_dim_2_);
     ExpectToken(is, binary, "<OutputDim1>");
     ReadBasicType(is, binary, &output_dim_1_);
     ExpectToken(is, binary, "<OutputDim2>");
     ReadBasicType(is, binary, &output_dim_2_);
     // weight dimension parameters
     ExpectToken(is, binary, "<Wei1Col>");
     ReadBasicType(is, binary, &wei_1_i1_);
     ExpectToken(is, binary, "<Wei1Row>");
     ReadBasicType(is, binary, &wei_1_j1_);
     ExpectToken(is, binary, "<Wei2Col>");
     ReadBasicType(is, binary, &wei_2_i2_);
     ExpectToken(is, binary, "<Wei2Row>");
     ReadBasicType(is, binary, &wei_2_j2_);
     // trainable parameters
     ExpectToken(is, binary, "<Mode1Weight>");
     mode_1_wei_.Read(is, binary);
     ExpectToken(is, binary, "<Mode2Weight>");
     mode_2_wei_.Read(is, binary);
     ExpectToken(is, binary, "<Bias>");
     bias_.Read(is, binary);
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 125 of file nnet-tcn.h.
References TCNComponent::bias_, TCNComponent::bias_learn_rate_coef_, kaldi::ExpectToken(), TCNComponent::input_dim_1_, TCNComponent::input_dim_2_, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, TCNComponent::output_dim_1_, TCNComponent::output_dim_2_, CuMatrix< Real >::Read(), kaldi::ReadBasicType(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
{
     ExpectToken(is, binary, "<LearnRateCoef>");
     ReadBasicType(is, binary, &learn_rate_coef_);
     ExpectToken(is, binary, "<BiasLearnRateCoef>");
     ReadBasicType(is, binary, &bias_learn_rate_coef_);
     // input output dimension parameters
     ExpectToken(is, binary, "<InputDim1>");
     ReadBasicType(is, binary, &input_dim_1_);
     ExpectToken(is, binary, "<InputDim2>");
     ReadBasicType(is, binary, &input_dim_2_);
     ExpectToken(is, binary, "<OutputDim1>");
     ReadBasicType(is, binary, &output_dim_1_);
     ExpectToken(is, binary, "<OutputDim2>");
     ReadBasicType(is, binary, &output_dim_2_);
     // weight dimension parameters
     ExpectToken(is, binary, "<Wei1Col>");
     ReadBasicType(is, binary, &wei_1_i1_);
     ExpectToken(is, binary, "<Wei1Row>");
     ReadBasicType(is, binary, &wei_1_j1_);
     ExpectToken(is, binary, "<Wei2Col>");
     ReadBasicType(is, binary, &wei_2_i2_);
     ExpectToken(is, binary, "<Wei2Row>");
     ReadBasicType(is, binary, &wei_2_j2_);
     // trainable parameters
     ExpectToken(is, binary, "<Mode1Weight>");
     mode_1_wei_.Read(is, binary);
     ExpectToken(is, binary, "<Mode2Weight>");
     mode_2_wei_.Read(is, binary);
     ExpectToken(is, binary, "<Bias>");
     bias_.Read(is, binary);
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 328 of file nnet-tcn.h.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddRowSumMat(), TCNComponent::bias_, TCNComponent::bias_grad_, TCNComponent::bias_learn_rate_coef_, CuMatrixBase< Real >::CopyRowsFromVec(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, NnetTrainOptions::l1_penalty, NnetTrainOptions::l2_penalty, NnetTrainOptions::learn_rate, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_1_wei_grad_, TCNComponent::mode_2_wei_, TCNComponent::mode_2_wei_grad_, NnetTrainOptions::momentum, CuMatrixBase< Real >::NumRows(), UpdatableComponent::opts_, kaldi::cu::RegularizeL1(), CuMatrix< Real >::Resize(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
   {
     // we use following hyperparameters from the option class
     const BaseFloat lr = opts_.learn_rate * learn_rate_coef_;
     const BaseFloat lr_bias = opts_.learn_rate * bias_learn_rate_coef_;
     const BaseFloat mmt = opts_.momentum;
     const BaseFloat l2 = opts_.l2_penalty;
     const BaseFloat l1 = opts_.l1_penalty;
     // we will also need the number of frames in the mini-batch
     const int32 batch_size = in.NumRows();
     // give initial size
     mode_1_wei_grad_.Resize(wei_1_j1_, wei_1_i1_);
     mode_2_wei_grad_.Resize(wei_2_j2_, wei_2_i2_);
     bias_grad_.Resize(wei_1_j1_, wei_2_j2_);
     CuMatrix<BaseFloat> input(batch_size, wei_1_j1_ * wei_2_i2_);
     CuMatrix<BaseFloat> dif(batch_size, wei_1_j1_ * wei_2_j2_);
     CuMatrix<BaseFloat> temp_w1(batch_size, wei_1_j1_ * wei_2_i2_);
     CuMatrix<BaseFloat> temp_w2(batch_size, wei_2_j2_ * wei_1_i1_);
     CuMatrix<BaseFloat> w1_grad_batch(batch_size, wei_1_j1_ * wei_1_i1_);
     CuMatrix<BaseFloat> w2_grad_batch(batch_size, wei_2_j2_ * wei_2_i2_);
     // reshape to std::vector
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_input;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_diff;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp_w1;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp_w2;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_w1_grad_batch;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_w2_grad_batch;
     // w1_vec and w2_vec used to parallel
     std::vector< CuSubMatrix<BaseFloat>* > w1_vec;
     std::vector< CuSubMatrix<BaseFloat>* > w2_vec;
     CuSubMatrix<BaseFloat>* w1 = new CuSubMatrix<BaseFloat>(mode_1_wei_,0,wei_1_j1_,0,wei_1_i1_);
     CuSubMatrix<BaseFloat>* w2 = new CuSubMatrix<BaseFloat>(mode_2_wei_,0,wei_2_j2_,0,wei_2_i2_);
     // initial some vectors
     for(int32 i = 0; i < in.NumRows(); i++)
     {
        CuSubMatrix<BaseFloat> *temp_reshaped_input = new CuSubMatrix<BaseFloat>(in,i,wei_1_i1_,wei_2_i2_);
        CuSubMatrix<BaseFloat> *temp_reshaped_diff = new CuSubMatrix<BaseFloat>(diff,i,wei_1_j1_,wei_2_j2_);
        CuSubMatrix<BaseFloat> *temp_reshaped_temp_w1 = new CuSubMatrix<BaseFloat>(temp_w1,i,wei_1_j1_,wei_2_i2_);                  //j1 * i2
        CuSubMatrix<BaseFloat> *temp_reshaped_temp_w2 = new CuSubMatrix<BaseFloat>(temp_w2,i,wei_2_j2_,wei_1_i1_);                  //j2 * i1
        CuSubMatrix<BaseFloat> *temp_w1_grad_batch = new CuSubMatrix<BaseFloat>(w1_grad_batch,i,wei_1_j1_,wei_1_i1_);               //j1 * i1
        CuSubMatrix<BaseFloat> *temp_w2_grad_batch = new CuSubMatrix<BaseFloat>(w2_grad_batch,i,wei_2_j2_,wei_2_i2_);               //j2 * i2
        w1_vec.push_back(w1);
        w2_vec.push_back(w2);
        reshaped_input.push_back(temp_reshaped_input);
        reshaped_diff.push_back(temp_reshaped_diff);
        reshaped_temp_w1.push_back(temp_reshaped_temp_w1);
        reshaped_temp_w2.push_back(temp_reshaped_temp_w2);
        reshaped_w1_grad_batch.push_back(temp_w1_grad_batch);
        reshaped_w2_grad_batch.push_back(temp_w2_grad_batch);
     }
     // compute gradient
     // we have w1 and w2 gradient
     // compute w1 grad
     AddMatMatBatched<BaseFloat>(1.0,reshaped_temp_w1,reshaped_diff,kNoTrans,w2_vec,kNoTrans,0.0);
     AddMatMatBatched<BaseFloat>(1.0,reshaped_w1_grad_batch,reshaped_temp_w1,kNoTrans,reshaped_input,kTrans,0.0);
     CuVector<BaseFloat> w1_grad_vec_temp(wei_1_j1_ * wei_1_i1_);
     w1_grad_vec_temp.AddRowSumMat(1.0,w1_grad_batch);
     mode_1_wei_grad_.CopyRowsFromVec(w1_grad_vec_temp);
     mode_1_wei_grad_.AddMat(mmt,mode_1_wei_grad_);
     // compute w2 grad
     AddMatMatBatched<BaseFloat>(1.0,reshaped_temp_w2,reshaped_diff,kTrans,w1_vec,kNoTrans,0.0);
     AddMatMatBatched<BaseFloat>(1.0,reshaped_w2_grad_batch,reshaped_temp_w2,kNoTrans,reshaped_input,kNoTrans,0.0);
     CuVector<BaseFloat> w2_grad_vec_temp(wei_2_j2_ * wei_2_i2_);
     w2_grad_vec_temp.AddRowSumMat(1.0,w2_grad_batch);
     mode_2_wei_grad_.CopyRowsFromVec(w2_grad_vec_temp);
     mode_2_wei_grad_.AddMat(mmt,mode_2_wei_grad_);
     // bias
     CuVector<BaseFloat> bias_grad_vec_temp(wei_1_j1_ * wei_2_j2_);
     bias_grad_vec_temp.AddRowSumMat(1.0,diff);
     bias_grad_.CopyRowsFromVec(bias_grad_vec_temp);
     bias_grad_.AddMat(mmt,bias_grad_);
     // l2 regularization
     if (l2 != 0.0)
     {
       mode_1_wei_grad_.AddMat(-lr*l2*batch_size,mode_1_wei_grad_);
       mode_2_wei_grad_.AddMat(-lr*l2*batch_size,mode_2_wei_grad_);
     }
     // l1 regularization
     if (l1 != 0.0)
     {
       cu::RegularizeL1(&mode_1_wei_, &mode_1_wei_grad_, lr*l1*batch_size, lr);
       cu::RegularizeL1(&mode_2_wei_, &mode_2_wei_grad_, lr*l1*batch_size, lr);
     }
     // update
     mode_1_wei_.AddMat(-lr, mode_1_wei_grad_);
     mode_2_wei_.AddMat(-lr,mode_2_wei_grad_);
     bias_.AddMat(-lr_bias,bias_grad_);
     // delete pointers
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_input.begin(); i!=reshaped_input.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_diff.begin(); i!=reshaped_diff.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp_w1.begin(); i!=reshaped_temp_w1.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp_w2.begin(); i!=reshaped_temp_w2.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_w1_grad_batch.begin(); i!=reshaped_w1_grad_batch.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_w2_grad_batch.begin(); i!=reshaped_w2_grad_batch.end(); ++i)
       delete *i;
     delete w1;
     delete w2;
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 328 of file nnet-tcn-3way.h.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddRowSumMat(), TCNComponent::bias_, TCNComponent::bias_grad_, TCNComponent::bias_learn_rate_coef_, CuMatrixBase< Real >::CopyRowsFromVec(), rnnlm::i, kaldi::kNoTrans, kaldi::kTrans, NnetTrainOptions::l1_penalty, NnetTrainOptions::l2_penalty, NnetTrainOptions::learn_rate, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_1_wei_grad_, TCNComponent::mode_2_wei_, TCNComponent::mode_2_wei_grad_, NnetTrainOptions::momentum, CuMatrixBase< Real >::NumRows(), UpdatableComponent::opts_, kaldi::cu::RegularizeL1(), CuMatrix< Real >::Resize(), TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, and TCNComponent::wei_2_j2_.
   {
     // we use following hyperparameters from the option class
     const BaseFloat lr = opts_.learn_rate * learn_rate_coef_;
     const BaseFloat lr_bias = opts_.learn_rate * bias_learn_rate_coef_;
     const BaseFloat mmt = opts_.momentum;
     const BaseFloat l2 = opts_.l2_penalty;
     const BaseFloat l1 = opts_.l1_penalty;
     // we will also need the number of frames in the mini-batch
     const int32 batch_size = in.NumRows();
     // give initial size
     mode_1_wei_grad_.Resize(wei_1_j1_, wei_1_i1_);
     mode_2_wei_grad_.Resize(wei_2_j2_, wei_2_i2_);
     bias_grad_.Resize(wei_1_j1_, wei_2_j2_);
     CuMatrix<BaseFloat> input(batch_size, wei_1_j1_ * wei_2_i2_);
     CuMatrix<BaseFloat> dif(batch_size, wei_1_j1_ * wei_2_j2_);
     CuMatrix<BaseFloat> temp_w1(batch_size, wei_1_j1_ * wei_2_i2_);
     CuMatrix<BaseFloat> temp_w2(batch_size, wei_2_j2_ * wei_1_i1_);
     CuMatrix<BaseFloat> w1_grad_batch(batch_size, wei_1_j1_ * wei_1_i1_);
     CuMatrix<BaseFloat> w2_grad_batch(batch_size, wei_2_j2_ * wei_2_i2_);
     // reshape to std::vector
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_input;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_diff;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp_w1;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_temp_w2;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_w1_grad_batch;
     std::vector< CuSubMatrix<BaseFloat>* > reshaped_w2_grad_batch;
     // w1_vec and w2_vec used to parallel
     std::vector< CuSubMatrix<BaseFloat>* > w1_vec;
     std::vector< CuSubMatrix<BaseFloat>* > w2_vec;
     CuSubMatrix<BaseFloat>* w1 = new CuSubMatrix<BaseFloat>(mode_1_wei_,0,wei_1_j1_,0,wei_1_i1_);
     CuSubMatrix<BaseFloat>* w2 = new CuSubMatrix<BaseFloat>(mode_2_wei_,0,wei_2_j2_,0,wei_2_i2_);
     // initial some vectors
     for(int32 i = 0; i < in.NumRows(); i++)
     {
        CuSubMatrix<BaseFloat> *temp_reshaped_input = new CuSubMatrix<BaseFloat>(in,i,wei_1_i1_,wei_2_i2_);
        CuSubMatrix<BaseFloat> *temp_reshaped_diff = new CuSubMatrix<BaseFloat>(diff,i,wei_1_j1_,wei_2_j2_);
        CuSubMatrix<BaseFloat> *temp_reshaped_temp_w1 = new CuSubMatrix<BaseFloat>(temp_w1,i,wei_1_j1_,wei_2_i2_);                  //j1 * i2
        CuSubMatrix<BaseFloat> *temp_reshaped_temp_w2 = new CuSubMatrix<BaseFloat>(temp_w2,i,wei_2_j2_,wei_1_i1_);                  //j2 * i1
        CuSubMatrix<BaseFloat> *temp_w1_grad_batch = new CuSubMatrix<BaseFloat>(w1_grad_batch,i,wei_1_j1_,wei_1_i1_);               //j1 * i1
        CuSubMatrix<BaseFloat> *temp_w2_grad_batch = new CuSubMatrix<BaseFloat>(w2_grad_batch,i,wei_2_j2_,wei_2_i2_);               //j2 * i2
        w1_vec.push_back(w1);
        w2_vec.push_back(w2);
        reshaped_input.push_back(temp_reshaped_input);
        reshaped_diff.push_back(temp_reshaped_diff);
        reshaped_temp_w1.push_back(temp_reshaped_temp_w1);
        reshaped_temp_w2.push_back(temp_reshaped_temp_w2);
        reshaped_w1_grad_batch.push_back(temp_w1_grad_batch);
        reshaped_w2_grad_batch.push_back(temp_w2_grad_batch);
     }
     // compute gradient
     // we have w1 and w2 gradient
     // compute w1 grad
     AddMatMatBatched<BaseFloat>(1.0,reshaped_temp_w1,reshaped_diff,kNoTrans,w2_vec,kNoTrans,0.0);
     AddMatMatBatched<BaseFloat>(1.0,reshaped_w1_grad_batch,reshaped_temp_w1,kNoTrans,reshaped_input,kTrans,0.0);
     CuVector<BaseFloat> w1_grad_vec_temp(wei_1_j1_ * wei_1_i1_);
     w1_grad_vec_temp.AddRowSumMat(1.0,w1_grad_batch);
     mode_1_wei_grad_.CopyRowsFromVec(w1_grad_vec_temp);
     mode_1_wei_grad_.AddMat(mmt,mode_1_wei_grad_);
     // compute w2 grad
     AddMatMatBatched<BaseFloat>(1.0,reshaped_temp_w2,reshaped_diff,kTrans,w1_vec,kNoTrans,0.0);
     AddMatMatBatched<BaseFloat>(1.0,reshaped_w2_grad_batch,reshaped_temp_w2,kNoTrans,reshaped_input,kNoTrans,0.0);
     CuVector<BaseFloat> w2_grad_vec_temp(wei_2_j2_ * wei_2_i2_);
     w2_grad_vec_temp.AddRowSumMat(1.0,w2_grad_batch);
     mode_2_wei_grad_.CopyRowsFromVec(w2_grad_vec_temp);
     mode_2_wei_grad_.AddMat(mmt,mode_2_wei_grad_);
     // bias
     CuVector<BaseFloat> bias_grad_vec_temp(wei_1_j1_ * wei_2_j2_);
     bias_grad_vec_temp.AddRowSumMat(1.0,diff);
     bias_grad_.CopyRowsFromVec(bias_grad_vec_temp);
     bias_grad_.AddMat(mmt,bias_grad_);
     // l2 regularization
     if (l2 != 0.0)
     {
       mode_1_wei_grad_.AddMat(-lr*l2*batch_size,mode_1_wei_grad_);
       mode_2_wei_grad_.AddMat(-lr*l2*batch_size,mode_2_wei_grad_);
     }
     // l1 regularization
     if (l1 != 0.0)
     {
       cu::RegularizeL1(&mode_1_wei_, &mode_1_wei_grad_, lr*l1*batch_size, lr);
       cu::RegularizeL1(&mode_2_wei_, &mode_2_wei_grad_, lr*l1*batch_size, lr);
     }
     // update
     mode_1_wei_.AddMat(-lr, mode_1_wei_grad_);
     mode_2_wei_.AddMat(-lr,mode_2_wei_grad_);
     bias_.AddMat(-lr_bias,bias_grad_);
     // delete pointers
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_input.begin(); i!=reshaped_input.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_diff.begin(); i!=reshaped_diff.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp_w1.begin(); i!=reshaped_temp_w1.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_temp_w2.begin(); i!=reshaped_temp_w2.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_w1_grad_batch.begin(); i!=reshaped_w1_grad_batch.end(); ++i)
       delete *i;
     for(std::vector< CuSubMatrix<BaseFloat>* >::iterator i=reshaped_w2_grad_batch.begin(); i!=reshaped_w2_grad_batch.end(); ++i)
       delete *i;
     delete w1;
     delete w2;
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 160 of file nnet-tcn-3way.h.
References TCNComponent::bias_, TCNComponent::bias_learn_rate_coef_, TCNComponent::input_dim_1_, TCNComponent::input_dim_2_, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, TCNComponent::output_dim_1_, TCNComponent::output_dim_2_, TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, TCNComponent::wei_2_j2_, CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<LearnRateCoef>");
     WriteBasicType(os, binary, learn_rate_coef_);
     WriteToken(os, binary, "<BiasLearnRateCoef>");
     WriteBasicType(os, binary, bias_learn_rate_coef_);
     // input output dimension parameters
     WriteToken(os, binary, "<InputDim1>");
     WriteBasicType(os, binary, input_dim_1_);
     WriteToken(os, binary, "<InputDim2>");
     WriteBasicType(os, binary, input_dim_2_);
     WriteToken(os, binary, "<OutputDim1>");
     WriteBasicType(os, binary, output_dim_1_);
     WriteToken(os, binary, "<OutputDim2>");
     WriteBasicType(os, binary, output_dim_2_);
     // weight dimension parameters
     WriteToken(os, binary, "<Wei1Col>");
     WriteBasicType(os, binary, wei_1_i1_);
     WriteToken(os, binary, "<Wei1Row>");
     WriteBasicType(os, binary, wei_1_j1_);
     WriteToken(os, binary, "<Wei2Col>");
     WriteBasicType(os, binary, wei_2_i2_);
     WriteToken(os, binary, "<Wei2Row>");
     WriteBasicType(os, binary, wei_2_j2_);
     // trainable parameters
     WriteToken(os, binary, "<Mode1Weight>");
     mode_1_wei_.Write(os, binary);
     WriteToken(os, binary, "<Mode2Weight>");
     mode_2_wei_.Write(os, binary);
     WriteToken(os, binary, "<Bias>");
     bias_.Write(os, binary);
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 160 of file nnet-tcn.h.
References TCNComponent::bias_, TCNComponent::bias_learn_rate_coef_, TCNComponent::input_dim_1_, TCNComponent::input_dim_2_, TCNComponent::learn_rate_coef_, TCNComponent::mode_1_wei_, TCNComponent::mode_2_wei_, TCNComponent::output_dim_1_, TCNComponent::output_dim_2_, TCNComponent::wei_1_i1_, TCNComponent::wei_1_j1_, TCNComponent::wei_2_i2_, TCNComponent::wei_2_j2_, CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<LearnRateCoef>");
     WriteBasicType(os, binary, learn_rate_coef_);
     WriteToken(os, binary, "<BiasLearnRateCoef>");
     WriteBasicType(os, binary, bias_learn_rate_coef_);
     // input output dimension parameters
     WriteToken(os, binary, "<InputDim1>");
     WriteBasicType(os, binary, input_dim_1_);
     WriteToken(os, binary, "<InputDim2>");
     WriteBasicType(os, binary, input_dim_2_);
     WriteToken(os, binary, "<OutputDim1>");
     WriteBasicType(os, binary, output_dim_1_);
     WriteToken(os, binary, "<OutputDim2>");
     WriteBasicType(os, binary, output_dim_2_);
     // weight dimension parameters
     WriteToken(os, binary, "<Wei1Col>");
     WriteBasicType(os, binary, wei_1_i1_);
     WriteToken(os, binary, "<Wei1Row>");
     WriteBasicType(os, binary, wei_1_j1_);
     WriteToken(os, binary, "<Wei2Col>");
     WriteBasicType(os, binary, wei_2_i2_);
     WriteToken(os, binary, "<Wei2Row>");
     WriteBasicType(os, binary, wei_2_j2_);
     // trainable parameters
     WriteToken(os, binary, "<Mode1Weight>");
     mode_1_wei_.Write(os, binary);
     WriteToken(os, binary, "<Mode2Weight>");
     mode_2_wei_.Write(os, binary);
     WriteToken(os, binary, "<Bias>");
     bias_.Write(os, binary);
   }
Member Data Documentation
CuMatrix< BaseFloat > bias_ private
Definition at line 454 of file nnet-tcn-3way.h.
Referenced by TCNComponent::GetParams(), TCNComponent::Info(), TCNComponent::InitData(), TCNComponent::NumParams(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
CuMatrix< BaseFloat > bias_grad_ private
Definition at line 459 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InfoGradient(), and TCNComponent::Update().
BaseFloat bias_learn_rate_coef_ private
Definition at line 449 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InfoGradient(), TCNComponent::InitData(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
int32 dim_in_ private
Definition at line 446 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InitData().
int32 dim_out_ private
Definition at line 446 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InitData().
int32 input_dim_1_ private
Definition at line 444 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InitData(), TCNComponent::ReadData(), and TCNComponent::WriteData().
int32 input_dim_2_ private
Definition at line 444 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InitData(), TCNComponent::ReadData(), and TCNComponent::WriteData().
BaseFloat learn_rate_coef_ private
Definition at line 448 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InfoGradient(), TCNComponent::InitData(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
CuMatrix< BaseFloat > mode_1_wei_ private
Definition at line 452 of file nnet-tcn-3way.h.
Referenced by TCNComponent::BackpropagateFnc(), TCNComponent::GetParams(), TCNComponent::Info(), TCNComponent::InitData(), TCNComponent::NumParams(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
CuMatrix< BaseFloat > mode_1_wei_grad_ private
Definition at line 457 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InfoGradient(), and TCNComponent::Update().
CuMatrix< BaseFloat > mode_2_wei_ private
Definition at line 453 of file nnet-tcn-3way.h.
Referenced by TCNComponent::BackpropagateFnc(), TCNComponent::GetParams(), TCNComponent::Info(), TCNComponent::InitData(), TCNComponent::NumParams(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
CuMatrix< BaseFloat > mode_2_wei_grad_ private
Definition at line 458 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InfoGradient(), and TCNComponent::Update().
int32 output_dim_1_ private
Definition at line 445 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InitData(), TCNComponent::ReadData(), and TCNComponent::WriteData().
int32 output_dim_2_ private
Definition at line 445 of file nnet-tcn-3way.h.
Referenced by TCNComponent::InitData(), TCNComponent::ReadData(), and TCNComponent::WriteData().
int32 wei_1_i1_ private
Definition at line 441 of file nnet-tcn-3way.h.
Referenced by TCNComponent::BackpropagateFnc(), TCNComponent::InitData(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
int32 wei_1_j1_ private
Definition at line 441 of file nnet-tcn-3way.h.
Referenced by TCNComponent::BackpropagateFnc(), TCNComponent::InitData(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
int32 wei_2_i2_ private
Definition at line 441 of file nnet-tcn-3way.h.
Referenced by TCNComponent::BackpropagateFnc(), TCNComponent::InitData(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
int32 wei_2_j2_ private
Definition at line 441 of file nnet-tcn-3way.h.
Referenced by TCNComponent::BackpropagateFnc(), TCNComponent::InitData(), TCNComponent::PropagateFnc(), TCNComponent::ReadData(), TCNComponent::Update(), and TCNComponent::WriteData().
The documentation for this class was generated from the following files:
nnet/nnet-tcn-3way.h
nnet/nnet-tcn.h