Kaldi: OnlineAppendFeature Class Reference
OnlineAppendFeature Class Reference
OnlineFeatureExtraction
This online-feature class implements combination of two feature streams (such as pitch, plp) into one stream.
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
virtual ~OnlineAppendFeature ()
OnlineAppendFeature (OnlineFeatureInterface *src1, OnlineFeatureInterface *src2)
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Attributes
OnlineFeatureInterface * src1_
OnlineFeatureInterface * src2_
Detailed Description
This online-feature class implements combination of two feature streams (such as pitch, plp) into one stream.
Definition at line 516 of file online-feature.h.
Constructor & Destructor Documentation
virtual ~OnlineAppendFeature () inline virtual
Definition at line 530 of file online-feature.h.
 {  }
OnlineAppendFeature (OnlineFeatureInterface * src1, OnlineFeatureInterface * src2) inline
Definition at line 532 of file online-feature.h.
                                    : src1_(src1), src2_(src2) { }
Member Function Documentation
virtual int32 Dim () const inline virtual
Implements OnlineFeatureInterface.
Definition at line 518 of file online-feature.h.
References OnlineFeatureInterface::Dim(), OnlineAppendFeature::src1_, and OnlineAppendFeature::src2_.
Referenced by OnlineAppendFeature::GetFrame().
 { return src1_->Dim() + src2_->Dim(); }
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 495 of file online-feature.cc.
References OnlineFeatureInterface::Dim(), VectorBase< Real >::Dim(), OnlineAppendFeature::Dim(), OnlineFeatureInterface::GetFrame(), KALDI_ASSERT, OnlineAppendFeature::src1_, and OnlineAppendFeature::src2_.
{
   KALDI_ASSERT(feat->Dim() == Dim());
   SubVector<BaseFloat> feat1(*feat, 0, src1_->Dim());
   SubVector<BaseFloat> feat2(*feat, src1_->Dim(), src2_->Dim());
   src1_->GetFrame(frame, &feat1);
   src2_->GetFrame(frame, &feat2);
 };
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 520 of file online-feature.h.
References OnlineFeatureInterface::IsLastFrame(), OnlineAppendFeature::src1_, and OnlineAppendFeature::src2_.
{
     return (src1_->IsLastFrame(frame) || src2_->IsLastFrame(frame));
   }
virtual int32 NumFramesReady () const inline virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 524 of file online-feature.h.
References OnlineFeatureInterface::NumFramesReady(), OnlineAppendFeature::src1_, and OnlineAppendFeature::src2_.
{
     return std::min(src1_->NumFramesReady(), src2_->NumFramesReady());
   }
Member Data Documentation
OnlineFeatureInterface* src1_ private
Definition at line 536 of file online-feature.h.
Referenced by OnlineAppendFeature::Dim(), OnlineAppendFeature::GetFrame(), OnlineAppendFeature::IsLastFrame(), and OnlineAppendFeature::NumFramesReady().
OnlineFeatureInterface* src2_ private
Definition at line 537 of file online-feature.h.
Referenced by OnlineAppendFeature::Dim(), OnlineAppendFeature::GetFrame(), OnlineAppendFeature::IsLastFrame(), and OnlineAppendFeature::NumFramesReady().
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc