Kaldi: AmSgmm Class Reference
AmSgmm Class Reference
Class for definition of the subspace Gmm acoustic model.
#include <am-sgmm.h>
Public Member Functions
AmSgmm ()
void Read (std::istream &rIn, bool binary)
void Write (std::ostream &out, bool binary, SgmmWriteFlagsType write_params) const
void Check (bool show_properties=true)
Checks the various components for correct sizes.
void InitializeFromFullGmm (const FullGmm &gmm, int32 num_states, int32 phn_subspace_dim, int32 spk_subspace_dim)
Initializes the SGMM parameters from a full-covariance UBM.
void CopyFromSgmm (const AmSgmm &other, bool copy_normalizers)
Used to copy models (useful in update)
void CopyGlobalsInitVecs (const AmSgmm &other, int32 phn_subspace_dim, int32 spk_subspace_dim, int32 num_pdfs)
Copies the global parameters from the supplied model, but sets the state vectors to zero.
BaseFloat GaussianSelection (const SgmmGselectConfig &config, const VectorBase< BaseFloat > &data, std::vector< int32 > *gselect) const
Computes the top-scoring Gaussian indices (used for pruning of later stages of computation).
BaseFloat GaussianSelectionPreselect (const SgmmGselectConfig &config, const VectorBase< BaseFloat > &data, const std::vector< int32 > &preselect, std::vector< int32 > *gselect) const
As GaussianSelection, but limiting it to a provided list of preselected Gaussians (e.g.
void ComputePerFrameVars (const VectorBase< BaseFloat > &data, const std::vector< int32 > &gselect, const SgmmPerSpkDerivedVars &spk_vars, BaseFloat logdet_s, SgmmPerFrameDerivedVars *per_frame_vars) const
This needs to be called with each new frame of data, prior to accumulation or likelihood evaluation: it computes various pre-computed quantities.
void ComputePerSpkDerivedVars (SgmmPerSpkDerivedVars *vars) const
Computes the per-speaker derived vars; assumes vars->v_s is already set up.
BaseFloat LogLikelihood (const SgmmPerFrameDerivedVars &per_frame_vars, int32 state_index, BaseFloat log_prune=0.0) const
This does a likelihood computation for a given state using the top-scoring Gaussian components (in per_frame_vars).
BaseFloat ComponentPosteriors (const SgmmPerFrameDerivedVars &per_frame_vars, int32 state, Matrix< BaseFloat > *post) const
Similar to LogLikelihood() function above, but also computes the posterior probabilities for the top-scoring Gaussian components and all substates.
void SplitSubstates (const Vector< BaseFloat > &state_occupancies, int32 target_nsubstates, BaseFloat perturb, BaseFloat power, BaseFloat cond)
Increases the total number of substates based on the state occupancies.
void IncreasePhoneSpaceDim (int32 target_dim, const Matrix< BaseFloat > &norm_xform)
Functions for increasing the phonetic and speaker space dimensions.
void IncreaseSpkSpaceDim (int32 target_dim, const Matrix< BaseFloat > &norm_xform)
void ComputeDerivedVars ()
Computes (and initializes if necessary) derived vars...
void ComputeNormalizers ()
Computes the data-independent terms in the log-likelihood computation for each Gaussian component and all substates.
void ComputeNormalizersNormalized (const std::vector< std::vector< int32 > > &normalize_sets)
Computes the normalizers, while normalizing the weights to one among each of the sets in "normalize_sets": these sets should be disjoint and their union should be all the indices 0 ...
void ComputeFmllrPreXform (const Vector< BaseFloat > &state_occs, Matrix< BaseFloat > *xform, Matrix< BaseFloat > *inv_xform, Vector< BaseFloat > *diag_mean_scatter) const
Computes the LDA-like pre-transform and its inverse as well as the eigenvalues of the scatter of the means used in FMLLR estimation.
int32 NumPdfs () const
Various model dimensions.
int32 NumSubstates (int32 j) const
int32 NumGauss () const
int32 PhoneSpaceDim () const
int32 SpkSpaceDim () const
int32 FeatureDim () const
void RemoveSpeakerSpace ()
const FullGmm & full_ubm () const
Accessors.
const DiagGmm & diag_ubm () const
const Matrix< BaseFloat > & StateVectors (int32 state_index) const
const SpMatrix< BaseFloat > & GetInvCovars (int32 gauss_index) const
const Matrix< BaseFloat > & GetPhoneProjection (int32 gauss_index) const
template<typename Real >
void GetInvCovars (int32 gauss_index, SpMatrix< Real > *out) const
Templated accessors (used to accumulate in different precision)
template<typename Real >
void GetSubstateMean (int32 j, int32 m, int32 i, VectorBase< Real > *mean_out) const
template<typename Real >
void GetSubstateSpeakerMean (int32 state, int32 substate, int32 gauss, const SgmmPerSpkDerivedVars &spk, VectorBase< Real > *mean_out) const
template<typename Real >
void GetVarScaledSubstateSpeakerMean (int32 state, int32 substate, int32 gauss, const SgmmPerSpkDerivedVars &spk, VectorBase< Real > *mean_out) const
template<typename Real >
void GetNtransSigmaInv (std::vector< Matrix< Real > > *out) const
template<class Real >
void ComputeH (std::vector< SpMatrix< Real > > *H_i) const
Computes quantities H = M_i Sigma_i^{-1} M_i^T.
Private Member Functions
void ComputeNormalizersInternal (int32 num_threads, int32 thread, int32 *entropy_count, double *entropy_sum)
Compute a subset of normalizers; used in multi-threaded implementation.
void InitializeMw (int32 phn_subspace_dim, const Matrix< BaseFloat > &norm_xform)
Initializes the matrices M_ and w_.
void InitializeN (int32 spk_subspace_dim, const Matrix< BaseFloat > &norm_xform)
Initializes the matrices N_.
void InitializeVecs (int32 num_states)
Initializes the state-vectors.
void InitializeCovars ()
initializes the within-class covariances.
void ComputeSmoothingTermsFromModel (const std::vector< SpMatrix< BaseFloat > > &H, const Vector< BaseFloat > &state_occupancies, SpMatrix< BaseFloat > *H_sm, BaseFloat max_cond) const
KALDI_DISALLOW_COPY_AND_ASSIGN (AmSgmm)
Private Attributes
DiagGmm diag_ubm_
These contain the "background" model associated with the subspace GMM.
FullGmm full_ubm_
std::vector< SpMatrix
< BaseFloat > > SigmaInv_
Globally shared parameters of the subspace GMM.
std::vector< Matrix< BaseFloat > > M_
Phonetic-subspace projections. Dimension is [I][D][S].
std::vector< Matrix< BaseFloat > > N_
Speaker-subspace projections. Dimension is [I][D][T].
Matrix< BaseFloat > w_
Weight projection vectors. Dimension is [I][S].
std::vector< Matrix< BaseFloat > > v_
The parameters in a particular SGMM state.
std::vector< Vector< BaseFloat > > c_
c_{jm}, mixture weights. Dimension is [J][M_{j}]
std::vector< Matrix< BaseFloat > > n_
n_{jim}, per-Gaussian normalizer. Dimension is [J][I][M_{j}]
std::vector< Matrix< BaseFloat > > M_prior_
SpMatrix< BaseFloat > row_cov_inv_
SpMatrix< BaseFloat > col_cov_inv_
Friends
class ComputeNormalizersClass
class EbwAmSgmmUpdater
class MleAmSgmmUpdater
class MleSgmmSpeakerAccs
class AmSgmmFunctions
class MleAmSgmmUpdaterMulti
Detailed Description
Class for definition of the subspace Gmm acoustic model.
Definition at line 114 of file am-sgmm.h.
Constructor & Destructor Documentation
AmSgmm () inline
Definition at line 116 of file am-sgmm.h.
 {}
Member Function Documentation
void Check (bool show_properties = true)
Checks the various components for correct sizes.
With wrong sizes, assertion failure occurs. When the argument is set to true, dimensions of the various components are printed.
Definition at line 216 of file am-sgmm.cc.
References AmSgmm::c_, AmSgmm::diag_ubm_, FullGmm::Dim(), DiagGmm::Dim(), AmSgmm::FeatureDim(), AmSgmm::full_ubm_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_LOG, AmSgmm::M_, AmSgmm::n_, MatrixBase< Real >::NumCols(), FullGmm::NumGauss(), DiagGmm::NumGauss(), AmSgmm::NumGauss(), AmSgmm::NumPdfs(), MatrixBase< Real >::NumRows(), AmSgmm::NumSubstates(), AmSgmm::PhoneSpaceDim(), AmSgmm::SigmaInv_, AmSgmm::SpkSpaceDim(), AmSgmm::v_, and AmSgmm::w_.
{
   int32 num_states = NumPdfs(),
       num_gauss = NumGauss(),
       feat_dim = FeatureDim(),
       phn_dim = PhoneSpaceDim(),
       spk_dim = SpkSpaceDim();
   if (show_properties)
     KALDI_LOG << "AmSgmm: #states = " << num_states << ", #Gaussians = "
               << num_gauss << ", feature dim = " << feat_dim
               << ", phone-space dim =" << phn_dim
               << ", speaker-space dim =" << spk_dim;
   KALDI_ASSERT(num_states > 0 && num_gauss > 0 && feat_dim > 0 && phn_dim > 0);
   std::ostringstream debug_str;
   // First check the diagonal-covariance UBM.
   KALDI_ASSERT(diag_ubm_.NumGauss() == num_gauss);
   KALDI_ASSERT(diag_ubm_.Dim() == feat_dim);
   // Check the full-covariance UBM.
   KALDI_ASSERT(full_ubm_.NumGauss() == num_gauss);
   KALDI_ASSERT(full_ubm_.Dim() == feat_dim);
   // Check the globally-shared covariance matrices.
   KALDI_ASSERT(SigmaInv_.size() == static_cast<size_t>(num_gauss));
   for (int32 i = 0; i < num_gauss; i++) {
     KALDI_ASSERT(SigmaInv_[i].NumRows() == feat_dim &&
                  SigmaInv_[i](0, 0) > 0.0);  // or it wouldn't be +ve definite.
   }
   KALDI_ASSERT(M_.size() == static_cast<size_t>(num_gauss));
   for (int32 i = 0; i < num_gauss; i++) {
     KALDI_ASSERT(M_[i].NumRows() == feat_dim && M_[i].NumCols() == phn_dim);
   }
   KALDI_ASSERT(w_.NumRows() == num_gauss && w_.NumCols() == phn_dim);
   {  // check v, c.
     KALDI_ASSERT(v_.size() == static_cast<size_t>(num_states) &&
                  c_.size() == static_cast<size_t>(num_states));
     int32 nSubstatesTot = 0;
     for (int32 j = 0; j < num_states; j++) {
       int32 M_j = NumSubstates(j);
       nSubstatesTot += M_j;
       KALDI_ASSERT(M_j > 0 && v_[j].NumRows() == M_j &&
           c_[j].Dim() == M_j && v_[j].NumCols() == phn_dim);
     }
     debug_str << "Substates: "<< (nSubstatesTot) << ".  ";
   }
   // check n.
   if (n_.size() == 0) {
     debug_str << "Normalizers: no.  ";
   } else {
     debug_str << "Normalizers: yes.  ";
     KALDI_ASSERT(n_.size() == static_cast<size_t>(num_states));
     for (int32 j = 0; j < num_states; j++) {
       KALDI_ASSERT(n_[j].NumRows() == num_gauss &&
           n_[j].NumCols() == NumSubstates(j));
     }
   }
   if (show_properties)
     KALDI_LOG << "Subspace GMM model properties: " << debug_str.str();
 }
BaseFloat ComponentPosteriors (const SgmmPerFrameDerivedVars & per_frame_vars, int32 state, Matrix< BaseFloat > * post) const
Similar to LogLikelihood() function above, but also computes the posterior probabilities for the top-scoring Gaussian components and all substates.
Definition at line 447 of file am-sgmm.cc.
References MatrixBase< Real >::AddMatMat(), MatrixBase< Real >::ApplySoftMax(), SgmmPerFrameDerivedVars::gselect, rnnlm::i, KALDI_ASSERT, KALDI_ERR, kaldi::kNoTrans, kaldi::kTrans, AmSgmm::n_, SgmmPerFrameDerivedVars::nti, AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), Matrix< Real >::Resize(), MatrixBase< Real >::Row(), AmSgmm::v_, and SgmmPerFrameDerivedVars::zti.
Referenced by SgmmClusterable::Accumulate(), FmllrSgmmAccs::Accumulate(), MleAmSgmmAccs::Accumulate(), MleSgmmSpeakerAccs::Accumulate(), and kaldi::AccumulateForUtterance().
{
   KALDI_ASSERT(j < NumPdfs());
   if (post == NULL) KALDI_ERR << "NULL pointer passed as return argument.";
   const vector<int32> &gselect = per_frame_vars.gselect;
   int32 num_gselect = gselect.size();
   post->Resize(num_gselect, NumSubstates(j));
   // Eq.(37): log p(x(t), m, i|j) = z_{i}^T v_{jm} (for all substates)
   post->AddMatMat(1.0, per_frame_vars.zti, kNoTrans, v_[j], kTrans, 0.0);
   for (int32 ki = 0; ki < num_gselect; ki++) {
     int32 i = gselect[ki];
     // Eq. (37): log p(x(t), m, i|j) += n_{jim} + n_{i}(t) (for all substates)
     post->Row(ki).AddVec(1.0, n_[j].Row(i));
     post->Row(ki).Add(per_frame_vars.nti(ki));
   }
   // Eq. (38): log p(x(t)|j) = log \sum_{m, i} p(x(t), m, i|j)
   return post->ApplySoftMax();
 }
void ComputeDerivedVars ()
Computes (and initializes if necessary) derived vars...
for now this is just the normalizers "n" and the diagonal UBM.
Definition at line 651 of file am-sgmm.cc.
References AmSgmm::ComputeNormalizers(), DiagGmm::CopyFromFullGmm(), AmSgmm::diag_ubm_, FullGmm::Dim(), DiagGmm::Dim(), AmSgmm::full_ubm_, AmSgmm::n_, FullGmm::NumGauss(), and DiagGmm::NumGauss().
{
   if (n_.empty()) {
     ComputeNormalizers();
   }
   if (diag_ubm_.NumGauss() != full_ubm_.NumGauss()
       || diag_ubm_.Dim() != full_ubm_.Dim()) {
     diag_ubm_.CopyFromFullGmm(full_ubm_);
   }
 }
void ComputeFmllrPreXform (const Vector< BaseFloat > & state_occs, Matrix< BaseFloat > * xform, Matrix< BaseFloat > * inv_xform, Vector< BaseFloat > * diag_mean_scatter) const
Computes the LDA-like pre-transform and its inverse as well as the eigenvalues of the scatter of the means used in FMLLR estimation.
Definition at line 867 of file am-sgmm.cc.
References SpMatrix< Real >::AddMat2Sp(), MatrixBase< Real >::AddMatMat(), VectorBase< Real >::AddMatVec(), VectorBase< Real >::AddVec(), SpMatrix< Real >::AddVec2(), VectorBase< Real >::ApplyFloor(), VectorBase< Real >::ApplySoftMax(), AmSgmm::c_, TpMatrix< Real >::Cholesky(), MatrixBase< Real >::CopyFromMat(), MatrixBase< Real >::CopyFromTp(), VectorBase< Real >::Dim(), SpMatrix< Real >::Eig(), AmSgmm::FeatureDim(), rnnlm::i, TpMatrix< Real >::InvertDouble(), SpMatrix< Real >::InvertDouble(), SpMatrix< Real >::IsDiagonal(), SpMatrix< Real >::IsUnit(), rnnlm::j, KALDI_ASSERT, KALDI_WARN, kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, kaldi::kUndefined, AmSgmm::M_, rnnlm::n, AmSgmm::NumGauss(), AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), MatrixBase< Real >::Range(), Vector< Real >::Resize(), Matrix< Real >::Resize(), MatrixBase< Real >::Row(), VectorBase< Real >::Scale(), MatrixBase< Real >::SetUnit(), AmSgmm::SigmaInv_, VectorBase< Real >::Sum(), AmSgmm::v_, and AmSgmm::w_.
Referenced by SgmmFmllrGlobalParams::Init(), main(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), and TestSgmmPreXform().
{
   int32 num_states = NumPdfs(),
       num_gauss = NumGauss(),
       dim = FeatureDim();
   KALDI_ASSERT(state_occs.Dim() == num_states);
   BaseFloat total_occ = state_occs.Sum();
   // Degenerate case: unlikely to ever happen.
   if (total_occ == 0) {
     KALDI_WARN << "Zero probability (computing transform). Using unit "
                << "pre-transform";
     xform->Resize(dim, dim + 1, kUndefined);
     xform->SetUnit();
     inv_xform->Resize(dim, dim + 1, kUndefined);
     inv_xform->SetUnit();
     diag_mean_scatter->Resize(dim, kSetZero);
     return;
   }
   // Convert state occupancies to posteriors; Eq. (B.1)
   Vector<BaseFloat> state_posteriors(state_occs);
   state_posteriors.Scale(1/total_occ);
   Vector<BaseFloat> mu_jmi(dim), global_mean(dim);
   SpMatrix<BaseFloat> within_class_covar(dim), between_class_covar(dim);
   Vector<BaseFloat> gauss_weight(num_gauss);  // weights for within-class vars.
   Vector<BaseFloat> w_jm(num_gauss);
   BaseFloat substate_weight;
   for (int32 j = 0; j < num_states; j++) {
     for (int32 m = 0; m < NumSubstates(j); m++) {
       // Eq. (7): w_jm = softmax([w_{1}^T ... w_{D}^T] * v_{jm})
       w_jm.AddMatVec(1.0, w_, kNoTrans, v_[j].Row(m), 0.0);
       w_jm.ApplySoftMax();
       for (int32 i = 0; i < num_gauss; i++) {
         substate_weight = state_posteriors(j) * c_[j](m) * w_jm(i);
         mu_jmi.AddMatVec(1.0, M_[i], kNoTrans, v_[j].Row(m), 0.0);  // Eq. (6)
         // Eq. (B.3): \mu_avg = \sum_{jmi} p(j) c_{jm} w_{jmi} \mu_{jmi}
         global_mean.AddVec(substate_weight, mu_jmi);
         // \Sigma_B = \sum_{jmi} p(j) c_{jm} w_{jmi} \mu_{jmi} \mu_{jmi}^T
         between_class_covar.AddVec2(substate_weight, mu_jmi);  // Eq. (B.4)
         gauss_weight(i) += substate_weight;
       }
     }
   }
   between_class_covar.AddVec2(-1.0, global_mean);  // Eq. (B.4)
   for (int32 i = 0; i < num_gauss; i++) {
     SpMatrix<BaseFloat> Sigma(SigmaInv_[i]);
     Sigma.InvertDouble();
     // Eq. (B.2): \Sigma_W = \sum_{jmi} p(j) c_{jm} w_{jmi} \Sigma_i
     within_class_covar.AddSp(gauss_weight(i), Sigma);
   }
   TpMatrix<BaseFloat> tmpL(dim);
   Matrix<BaseFloat> tmpLInvFull(dim, dim);
   tmpL.Cholesky(within_class_covar);  // \Sigma_W = L L^T
   tmpL.InvertDouble();  // L^{-1}
   tmpLInvFull.CopyFromTp(tmpL);  // get as full matrix.
   // B := L^{-1} * \Sigma_B * L^{-T}
   SpMatrix<BaseFloat> tmpB(dim);
   tmpB.AddMat2Sp(1.0, tmpLInvFull, kNoTrans, between_class_covar, 0.0);
   Matrix<BaseFloat> U(dim, dim);
   diag_mean_scatter->Resize(dim);
   xform->Resize(dim, dim + 1);
   inv_xform->Resize(dim, dim + 1);
   tmpB.Eig(diag_mean_scatter, &U);  // Eq. (B.5): B = U D V^T
   int32 n;
   if ((n = diag_mean_scatter->ApplyFloor(1.0e-04)) != 0)
     KALDI_WARN << "Floored " << n << " elements of the mean-scatter matrix.";
   // Eq. (B.6): A_{pre} = U^T * L^{-1}
   SubMatrix<BaseFloat> Apre(*xform, 0, dim, 0, dim);
   Apre.AddMatMat(1.0, U, kTrans, tmpLInvFull, kNoTrans, 0.0);
 #ifdef KALDI_PARANOID
   {
     SpMatrix<BaseFloat> tmp(dim);
     tmp.AddMat2Sp(1.0, Apre, kNoTrans, within_class_covar, 0.0);
     KALDI_ASSERT(tmp.IsUnit(0.01));
   }
   {
     SpMatrix<BaseFloat> tmp(dim);
     tmp.AddMat2Sp(1.0, Apre, kNoTrans, between_class_covar, 0.0);
     KALDI_ASSERT(tmp.IsDiagonal(0.01));
   }
 #endif
   // Eq. (B.7): b_{pre} = - A_{pre} \mu_{avg}
   Vector<BaseFloat> b_pre(dim);
   b_pre.AddMatVec(-1.0, Apre, kNoTrans, global_mean, 0.0);
   for (int32 r = 0; r < dim; r++) {
     xform->Row(r)(dim) = b_pre(r);  // W_{pre} = [ A_{pre}, b_{pre} ]
   }
   // Eq. (B.8) & (B.9): W_{inv} = [ A_{pre}^{-1}, \mu_{avg} ]
   inv_xform->CopyFromMat(*xform);
   inv_xform->Range(0, dim, 0, dim).InvertDouble();
   for (int32 r = 0; r < dim; r++)
     inv_xform->Row(r)(dim) = global_mean(r);
 }  // End of ComputePreXform()
template void ComputeH (std::vector< SpMatrix< Real > > * H_i) const
Computes quantities H = M_i Sigma_i^{-1} M_i^T.
Definition at line 999 of file am-sgmm.cc.
References SpMatrix< Real >::AddMat2Sp(), rnnlm::i, KALDI_ASSERT, kaldi::kTrans, AmSgmm::M_, AmSgmm::NumGauss(), AmSgmm::PhoneSpaceDim(), and AmSgmm::SigmaInv_.
Referenced by AmSgmm::SplitSubstates(), EbwAmSgmmUpdater::Update(), and MleAmSgmmUpdater::Update().
{
   KALDI_ASSERT(NumGauss() != 0);
   (*H_i).resize(NumGauss());
   SpMatrix<BaseFloat> H_i_tmp(PhoneSpaceDim());
   for (int32 i = 0; i < NumGauss(); i++) {
     (*H_i)[i].Resize(PhoneSpaceDim());
     H_i_tmp.AddMat2Sp(1.0, M_[i], kTrans, SigmaInv_[i], 0.0);
     (*H_i)[i].CopyFromSp(H_i_tmp);
   }
 }
void ComputeNormalizers ()
Computes the data-independent terms in the log-likelihood computation for each Gaussian component and all substates.
Eq. (31)
Definition at line 692 of file am-sgmm.cc.
References kaldi::Exp(), KALDI_LOG, AmSgmm::n_, AmSgmm::NumPdfs(), and kaldi::RunMultiThreaded().
Referenced by AmSgmm::ComputeDerivedVars(), kaldi::InitAndOutputSgmm(), AmSgmm::Read(), TestSgmmFmllr(), UnitTestEstimateSgmm(), UnitTestSgmm(), EbwAmSgmmUpdater::Update(), and MleAmSgmmUpdater::Update().
{
   KALDI_LOG << "Computing normalizers";
   n_.resize(NumPdfs());
   int32 entropy_count = 0;
   double entropy_sum = 0.0;
   ComputeNormalizersClass c(this, &entropy_count, &entropy_sum);
   RunMultiThreaded(c);
   KALDI_LOG << "Entropy of weights in substates is "
             << (entropy_sum / entropy_count) << " over " << entropy_count
             << " substates, equivalent to perplexity of "
             << (Exp(entropy_sum /entropy_count));
   KALDI_LOG << "Done computing normalizers";
 }
void ComputeNormalizersInternal (int32 num_threads, int32 thread, int32 * entropy_count, double * entropy_sum) private
Compute a subset of normalizers; used in multi-threaded implementation.
Definition at line 708 of file am-sgmm.cc.
References MatrixBase< Real >::AddMatMat(), MatrixBase< Real >::AddMatSp(), AmSgmm::c_, kaldi::Exp(), AmSgmm::FeatureDim(), rnnlm::i, rnnlm::j, KALDI_ISFINITE, KALDI_LOG, KALDI_WARN, kaldi::kNoTrans, kaldi::kTrans, kaldi::Log(), AmSgmm::M_, M_PI, AmSgmm::n_, AmSgmm::NumGauss(), AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), MatrixBase< Real >::Row(), AmSgmm::SigmaInv_, AmSgmm::v_, kaldi::VecVec(), and AmSgmm::w_.
Referenced by ComputeNormalizersClass::operator()().
{
   BaseFloat DLog2pi = FeatureDim() * Log(2 * M_PI);
   Vector<BaseFloat> log_det_Sigma(NumGauss());
   for (int32 i = 0; i < NumGauss(); i++) {
     try {
       log_det_Sigma(i) = - SigmaInv_[i].LogPosDefDet();
     } catch(...) {
       if (thread == 0) // just for one thread, print errors [else, duplicates]
         KALDI_WARN << "Covariance is not positive definite, setting to unit";
       SigmaInv_[i].SetUnit();
       log_det_Sigma(i) = 0.0;
     }
   }
   int block_size = (NumPdfs() + num_threads-1) / num_threads;
   int j_start = thread * block_size, j_end = std::min(NumPdfs(), j_start + block_size);
   for (int32 j = j_start; j < j_end; j++) {
     Matrix<BaseFloat> log_w_jm(NumSubstates(j), NumGauss());
     n_[j].Resize(NumGauss(), NumSubstates(j));
     Matrix<BaseFloat> mu_jmi(NumSubstates(j), FeatureDim());
     Matrix<BaseFloat> SigmaInv_mu(NumSubstates(j), FeatureDim());
     // (in logs): w_jm = softmax([w_{k1}^T ... w_{kD}^T] * v_{jkm}) eq.(7)
     log_w_jm.AddMatMat(1.0, v_[j], kNoTrans, w_, kTrans, 0.0);
     for (int32 m = 0; m < NumSubstates(j); m++) {
       log_w_jm.Row(m).Add(-1.0 * log_w_jm.Row(m).LogSumExp());
       {  // DIAGNOSTIC CODE
         (*entropy_count)++;
         for (int32 i = 0; i < NumGauss(); i++) {
           (*entropy_sum) -= log_w_jm(m, i) * Exp(log_w_jm(m, i));
         }
       }
     }
     for (int32 i = 0; i < NumGauss(); i++) {
       // mu_jmi = M_{i} * v_{jm}
       mu_jmi.AddMatMat(1.0, v_[j], kNoTrans, M_[i], kTrans, 0.0);
       SigmaInv_mu.AddMatSp(1.0, mu_jmi, kNoTrans, SigmaInv_[i], 0.0);
       for (int32 m = 0; m < NumSubstates(j); m++) {
         // mu_{jmi} * \Sigma_{i}^{-1} * mu_{jmi}
         BaseFloat mu_SigmaInv_mu = VecVec(mu_jmi.Row(m), SigmaInv_mu.Row(m));
         BaseFloat logc = Log(c_[j](m));
         // Suggestion: Both mu_jmi and SigmaInv_mu could
         // have been computed at once for i,
         // if M[i] was concatenated to single matrix over i indices
         // eq.(31)
         n_[j](i, m) = logc + log_w_jm(m, i) - 0.5 * (log_det_Sigma(i) + DLog2pi
             + mu_SigmaInv_mu);
         {  // Mainly diagnostic code.  Not necessary.
           BaseFloat tmp = n_[j](i, m);
           if (!KALDI_ISFINITE(tmp)) {  // NaN or inf
             KALDI_LOG << "Warning: normalizer for j = " << j << ", m = " << m
                       << ", i = " << i << " is infinite or NaN " << tmp << "= "
                       << (logc) << "+" << (log_w_jm(m, i)) << "+" << (-0.5 *
                           log_det_Sigma(i)) << "+" << (-0.5 * DLog2pi)
                       << "+" << (mu_SigmaInv_mu) << ", setting to finite.";
             n_[j](i, m) = -1.0e+40;  // future work(arnab): get rid of magic number
           }
         }
       }
     }
   }
 }
void ComputeNormalizersNormalized (const std::vector< std::vector< int32 > > & normalize_sets)
Computes the normalizers, while normalizing the weights to one among each of the sets in "normalize_sets": these sets should be disjoint and their union should be all the indices 0 ...
I-1.
Definition at line 782 of file am-sgmm.cc.
References VectorBase< Real >::Add(), VectorBase< Real >::AddMatVec(), VectorBase< Real >::AddSpVec(), AmSgmm::c_, kaldi::Exp(), AmSgmm::FeatureDim(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ISFINITE, KALDI_LOG, KALDI_WARN, kaldi::kNoTrans, kaldi::Log(), VectorBase< Real >::LogSumExp(), AmSgmm::M_, M_PI, rnnlm::n, AmSgmm::n_, AmSgmm::NumGauss(), AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), AmSgmm::SigmaInv_, AmSgmm::v_, kaldi::VecVec(), and AmSgmm::w_.
{
   { // Check sets in normalize_sets are disjoint and cover all Gaussians.
     std::set<int32> all;
     for (int32 i = 0; i < normalize_sets.size(); i++)
       for (int32 j = 0; static_cast<size_t>(j) < normalize_sets[i].size(); j++) {
         int32 n = normalize_sets[i][j];
         KALDI_ASSERT(all.count(n) == 0 && n >= 0 && n < NumGauss());
         all.insert(n);
       }
     KALDI_ASSERT(all.size() == NumGauss());
   }
   KALDI_LOG << "Computing normalizers [normalized]";
   BaseFloat DLog2pi = FeatureDim() * Log(2 * M_PI);
   Vector<BaseFloat> mu_jmi(FeatureDim());
   Vector<BaseFloat> SigmaInv_mu(FeatureDim());
   Vector<BaseFloat> log_det_Sigma(NumGauss());
   for (int32 i = 0; i < NumGauss(); i++) {
     try {
       log_det_Sigma(i) = - SigmaInv_[i].LogPosDefDet();
     } catch(...) {
       KALDI_WARN << "Covariance is not positive definite, setting to unit";
       SigmaInv_[i].SetUnit();
       log_det_Sigma(i) = 0.0;
     }
   }
   n_.resize(NumPdfs());
   for (int32 j = 0; j < NumPdfs(); j++) {
     Vector<BaseFloat> log_w_jm(NumGauss());
     n_[j].Resize(NumGauss(), NumSubstates(j));
     for (int32 m = 0; m < NumSubstates(j); m++) {
       BaseFloat logc = Log(c_[j](m));
       // (in logs): w_jm = softmax([w_{k1}^T ... w_{kD}^T] * v_{jkm}) eq.(7)
       log_w_jm.AddMatVec(1.0, w_, kNoTrans, v_[j].Row(m), 0.0);
       log_w_jm.Add((-1.0) * log_w_jm.LogSumExp());
       for (int32 n = 0; n < normalize_sets.size(); n++) {
         const std::vector<int32> &this_set(normalize_sets[n]);
         double sum = 0.0;
         for (int32 p = 0; p < this_set.size(); p++)
           sum += Exp(log_w_jm(this_set[p]));
         double offset = -Log(sum);  // add "offset", to normalize weights.
         for (int32 p = 0; p < this_set.size(); p++)
           log_w_jm(this_set[p]) += offset;
       }
       for (int32 i = 0; i < NumGauss(); i++) {
         // mu_jmi = M_{i} * v_{jm}
         mu_jmi.AddMatVec(1.0, M_[i], kNoTrans, v_[j].Row(m), 0.0);
         // mu_{jmi} * \Sigma_{i}^{-1} * mu_{jmi}
         SigmaInv_mu.AddSpVec(1.0, SigmaInv_[i], mu_jmi, 0.0);
         BaseFloat mu_SigmaInv_mu = VecVec(mu_jmi, SigmaInv_mu);
         // Suggestion: Both mu_jmi and SigmaInv_mu could
         // have been computed at once  for i ,
         // if M[i] was concatenated to single matrix over i indeces
         // eq.(31)
         n_[j](i, m) = logc + log_w_jm(i) - 0.5 * (log_det_Sigma(i) + DLog2pi
             + mu_SigmaInv_mu);
         {  // Mainly diagnostic code.  Not necessary.
           BaseFloat tmp = n_[j](i, m);
           if (!KALDI_ISFINITE(tmp)) {  // NaN or inf
             KALDI_LOG << "Warning: normalizer for j = " << j << ", m = " << m
                       << ", i = " << i << " is infinite or NaN " << tmp << "= "
                       << (logc) << "+" << (log_w_jm(i)) << "+" << (-0.5 *
                           log_det_Sigma(i)) << "+" << (-0.5 * DLog2pi)
                       << "+" << (mu_SigmaInv_mu) << ", setting to finite.";
             n_[j](i, m) = -1.0e+40;  // future work(arnab): get rid of magic number
           }
         }
       }
     }
   }
   KALDI_LOG << "Done computing normalizers (normalized over subsets)";
 }
void ComputePerFrameVars (const VectorBase< BaseFloat > & data, const std::vector< int32 > & gselect, const SgmmPerSpkDerivedVars & spk_vars, BaseFloat logdet_s, SgmmPerFrameDerivedVars * per_frame_vars) const
This needs to be called with each new frame of data, prior to accumulation or likelihood evaluation: it computes various pre-computed quantities.
The 'logdet_s' term is the log determinant of the FMLLR transform, or 0.0 if no FMLLR is used or it's single-class fMLLR applied in the feature extraction, and we're not keeping track of it here.
Definition at line 389 of file am-sgmm.cc.
References VectorBase< Real >::AddSpVec(), VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), AmSgmm::FeatureDim(), SgmmPerFrameDerivedVars::gselect, rnnlm::i, KALDI_ASSERT, kaldi::kTrans, AmSgmm::M_, AmSgmm::n_, SgmmPerFrameDerivedVars::NeedsResizing(), SgmmPerFrameDerivedVars::nti, SgmmPerSpkDerivedVars::o_s, AmSgmm::PhoneSpaceDim(), SgmmPerFrameDerivedVars::Resize(), MatrixBase< Real >::Row(), AmSgmm::SigmaInv_, SgmmPerSpkDerivedVars::v_s, kaldi::VecVec(), SgmmPerFrameDerivedVars::xt, SgmmPerFrameDerivedVars::xti, and SgmmPerFrameDerivedVars::zti.
Referenced by kaldi::AccumulateForUtterance(), kaldi::AccumulateSgmmTreeStats(), DecodableAmSgmm::LogLikelihoodZeroBased(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmIncreaseDim(), TestSgmmInit(), TestSgmmIO(), TestSgmmSubstates(), and TestUpdateAndAccsIO().
{
   KALDI_ASSERT(!n_.empty() && "ComputeNormalizers() must be called.");
   if (per_frame_vars->NeedsResizing(gselect.size(),
                                     FeatureDim(),
                                     PhoneSpaceDim()))
     per_frame_vars->Resize(gselect.size(), FeatureDim(), PhoneSpaceDim());
   per_frame_vars->gselect = gselect;
   per_frame_vars->xt.CopyFromVec(data);
   for (int32 ki = 0, last = gselect.size(); ki < last; ki++) {
     int32 i = gselect[ki];
     per_frame_vars->xti.Row(ki).CopyFromVec(per_frame_vars->xt);
     if (spk_vars.v_s.Dim() != 0)
       per_frame_vars->xti.Row(ki).AddVec(-1.0, spk_vars.o_s.Row(i));
   }
   Vector<BaseFloat> SigmaInv_xt(FeatureDim());
   for (int32 ki = 0, last = gselect.size(); ki < last; ki++) {
     int32 i = gselect[ki];
     SigmaInv_xt.AddSpVec(1.0, SigmaInv_[i], per_frame_vars->xti.Row(ki), 0.0);
     // Eq (35): z_{i}(t) = M_{i}^{T} \Sigma_{i}^{-1} x_{i}(t)
     per_frame_vars->zti.Row(ki).AddMatVec(1.0, M_[i], kTrans, SigmaInv_xt, 0.0);
     // Eq.(36): n_{i}(t) = -0.5 x_{i}^{T} \Sigma_{i}^{-1} x_{i}(t)
     per_frame_vars->nti(ki) = -0.5 * VecVec(per_frame_vars->xti.Row(ki),
                                             SigmaInv_xt) + logdet_s;
   }
 }
void ComputePerSpkDerivedVars (SgmmPerSpkDerivedVars * vars) const
Computes the per-speaker derived vars; assumes vars->v_s is already set up.
Definition at line 1202 of file am-sgmm.cc.
References VectorBase< Real >::Dim(), AmSgmm::FeatureDim(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, AmSgmm::N_, AmSgmm::NumGauss(), SgmmPerSpkDerivedVars::o_s, Matrix< Real >::Resize(), MatrixBase< Real >::Row(), AmSgmm::SpkSpaceDim(), and SgmmPerSpkDerivedVars::v_s.
Referenced by main(), and kaldi::ProcessUtterance().
{
   KALDI_ASSERT(vars != NULL);
   if (vars->v_s.Dim() != 0) {
     KALDI_ASSERT(vars->v_s.Dim() == SpkSpaceDim());
     vars->o_s.Resize(NumGauss(), FeatureDim());
     int32 num_gauss = NumGauss();
     for (int32 i = 0; i < num_gauss; i++) {
       // Eqn. (32): o_i^{(s)} = N_i v^{(s)}
       vars->o_s.Row(i).AddMatVec(1.0, N_[i], kNoTrans, vars->v_s, 0.0);
     }
   } else {
     vars->o_s.Resize(0, 0);
   }
 }
void ComputeSmoothingTermsFromModel (const std::vector< SpMatrix< BaseFloat > > & H, const Vector< BaseFloat > & state_occupancies, SpMatrix< BaseFloat > * H_sm, BaseFloat max_cond) const private
Definition at line 1086 of file am-sgmm.cc.
References SpMatrix< Real >::AddSp(), VectorBase< Real >::AddVec(), AmSgmm::c_, VectorBase< Real >::Dim(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_LOG, KALDI_WARN, kaldi::kNoTrans, SpMatrix< Real >::LimitCondDouble(), AmSgmm::NumGauss(), AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), AmSgmm::PhoneSpaceDim(), SpMatrix< Real >::Resize(), PackedMatrix< Real >::Scale(), PackedMatrix< Real >::SetUnit(), VectorBase< Real >::SetZero(), PackedMatrix< Real >::SetZero(), AmSgmm::v_, and AmSgmm::w_.
Referenced by AmSgmm::SplitSubstates().
{
   int32 num_gauss = NumGauss();
   BaseFloat tot_sum = 0.0;
   KALDI_ASSERT(state_occupancies.Dim() == NumPdfs());
   Vector<BaseFloat> w_jm(num_gauss);
   H_sm->Resize(PhoneSpaceDim());
   H_sm->SetZero();
   Vector<BaseFloat> gamma_i(num_gauss);
   gamma_i.SetZero();
   for (int32 j = 0; j < NumPdfs(); j++) {
     int32 M_j = NumSubstates(j);
     KALDI_ASSERT(M_j > 0);
     for (int32 m = 0; m < M_j; m++) {
       w_jm.AddMatVec(1.0, w_, kNoTrans, v_[j].Row(m), 0.0);
       w_jm.ApplySoftMax();
       gamma_i.AddVec(state_occupancies(j) * c_[j](m), w_jm);
     }
   }
   BaseFloat sum = 0.0;
   for (int32 i = 0; i < num_gauss; i++) {
     if (gamma_i(i) > 0) {
       H_sm->AddSp(gamma_i(i), H[i]);
       sum += gamma_i(i);
     }
   }
   if (sum == 0.0) {
     KALDI_WARN << "Sum of counts is zero. ";
     // set to unit matrix--arbitrary non-singular matrix.. won't ever matter.
     H_sm->SetUnit();
   } else {
     H_sm->Scale(1.0 / sum);
     int32 tmp = H_sm->LimitCondDouble(max_cond);
     if (tmp > 0) {
       KALDI_WARN << "Limited " << (tmp) << " eigenvalues of H_sm";
     }
   }
   tot_sum += sum;
   KALDI_LOG << "ComputeSmoothingTermsFromModel: total count is " << tot_sum;
 }
void CopyFromSgmm (const AmSgmm & other, bool copy_normalizers)
Used to copy models (useful in update)
Definition at line 317 of file am-sgmm.cc.
References AmSgmm::c_, DiagGmm::CopyFromDiagGmm(), FullGmm::CopyFromFullGmm(), AmSgmm::diag_ubm_, AmSgmm::full_ubm_, KALDI_LOG, AmSgmm::M_, AmSgmm::N_, AmSgmm::n_, AmSgmm::SigmaInv_, AmSgmm::v_, and AmSgmm::w_.
Referenced by TestMultiSgmmEst().
{
   KALDI_LOG << "Copying AmSgmm";
   // Copy background GMMs
   diag_ubm_.CopyFromDiagGmm(other.diag_ubm_);
   full_ubm_.CopyFromFullGmm(other.full_ubm_);
   // Copy global params
   SigmaInv_ = other.SigmaInv_;
   M_ = other.M_;
   w_ = other.w_;
   N_ = other.N_;
   // Copy state-specific params, but only copy normalizers if requested.
   v_ = other.v_;
   c_ = other.c_;
   if (copy_normalizers) n_ = other.n_;
   KALDI_LOG << "Done.";
 }
void CopyGlobalsInitVecs (const AmSgmm & other, int32 phn_subspace_dim, int32 spk_subspace_dim, int32 num_pdfs)
Copies the global parameters from the supplied model, but sets the state vectors to zero.
Supports reducing the phonetic and speaker subspace dimensions.
Definition at line 339 of file am-sgmm.cc.
References DiagGmm::CopyFromDiagGmm(), FullGmm::CopyFromFullGmm(), MatrixBase< Real >::CopyFromMat(), AmSgmm::diag_ubm_, AmSgmm::FeatureDim(), AmSgmm::full_ubm_, rnnlm::i, AmSgmm::InitializeVecs(), KALDI_LOG, KALDI_WARN, kaldi::kNoTrans, AmSgmm::M_, AmSgmm::N_, DiagGmm::NumGauss(), AmSgmm::PhoneSpaceDim(), MatrixBase< Real >::Range(), Matrix< Real >::Resize(), AmSgmm::SigmaInv_, AmSgmm::SpkSpaceDim(), and AmSgmm::w_.
Referenced by kaldi::InitAndOutputSgmm().
{
   if (phn_subspace_dim < 1 || phn_subspace_dim > other.PhoneSpaceDim()) {
     KALDI_WARN << "Initial phone-subspace dimension must be in [1, "
         << other.PhoneSpaceDim() << "]. Changing from " << phn_subspace_dim
         << " to " << other.PhoneSpaceDim();
     phn_subspace_dim = other.PhoneSpaceDim();
   }
   if (spk_subspace_dim < 0 || spk_subspace_dim > other.SpkSpaceDim()) {
     KALDI_WARN << "Initial spk-subspace dimension must be in [1, "
                << other.SpkSpaceDim() << "]. Changing from " << spk_subspace_dim
                << " to " << other.SpkSpaceDim();
     spk_subspace_dim = other.SpkSpaceDim();
   }
   KALDI_LOG << "Initializing model";
   // Copy background GMMs
   diag_ubm_.CopyFromDiagGmm(other.diag_ubm_);
   full_ubm_.CopyFromFullGmm(other.full_ubm_);
   // Copy global params
   SigmaInv_ = other.SigmaInv_;
   int32 num_gauss = diag_ubm_.NumGauss(),
       data_dim = other.FeatureDim();
   M_.resize(num_gauss);
   w_.Resize(num_gauss, phn_subspace_dim);
   for (int32 i = 0; i < num_gauss; i++) {
     M_[i].Resize(data_dim, phn_subspace_dim);
     M_[i].CopyFromMat(other.M_[i].Range(0, data_dim, 0, phn_subspace_dim),
                       kNoTrans);
   }
   w_.CopyFromMat(other.w_.Range(0, num_gauss, 0, phn_subspace_dim), kNoTrans);
   if (spk_subspace_dim > 0) {
     N_.resize(num_gauss);
     for (int32 i = 0; i < num_gauss; i++) {
       N_[i].Resize(data_dim, spk_subspace_dim);
       N_[i].CopyFromMat(other.N_[i].Range(0, data_dim, 0, spk_subspace_dim),
                         kNoTrans);
     }
   } else {
     N_.clear();
   }
   InitializeVecs(num_pdfs);
 }
const DiagGmm& diag_ubm () const inline
Definition at line 229 of file am-sgmm.h.
References AmSgmm::diag_ubm_.
 { return diag_ubm_; }
int32 FeatureDim () const inline
Definition at line 223 of file am-sgmm.h.
References AmSgmm::M_.
Referenced by FmllrSgmmAccs::AccumulateForFmllrSubspace(), MleSgmmSpeakerAccs::AccumulateFromPosteriors(), kaldi::CalcFmllrStepSize(), AmSgmm::Check(), MleAmSgmmAccs::Check(), AmSgmm::ComputeFmllrPreXform(), MleAmSgmmUpdater::ComputeMPrior(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputePerFrameVars(), AmSgmm::ComputePerSpkDerivedVars(), AmSgmm::CopyGlobalsInitVecs(), FmllrSgmmAccs::FmllrObjGradient(), AmSgmm::GetNtransSigmaInv(), AmSgmm::GetSubstateMean(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm::IncreaseSpkSpaceDim(), DecodableAmSgmm::LogLikelihoodZeroBased(), main(), MleAmSgmmUpdater::MapUpdateM(), MleAmSgmmGlobalAccs::ResizeAccumulators(), MleAmSgmmAccs::ResizeAccumulators(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmIncreaseDim(), TestSgmmInit(), TestSgmmIO(), TestSgmmSubstates(), TestUpdateAndAccsIO(), EbwAmSgmmUpdater::UpdateM(), and AmSgmm::Write().
 { return M_[0].NumRows(); }
const FullGmm& full_ubm () const inline
Accessors.
Definition at line 228 of file am-sgmm.h.
References AmSgmm::full_ubm_.
Referenced by TestSgmmIncreaseDim(), and TestSgmmInit().
 { return full_ubm_; }
BaseFloat GaussianSelection (const SgmmGselectConfig & config, const VectorBase< BaseFloat > & data, std::vector< int32 > * gselect) const
Computes the top-scoring Gaussian indices (used for pruning of later stages of computation).
Returns frame log-likelihood given selected Gaussians from full UBM.
Definition at line 1217 of file am-sgmm.cc.
References FullGmm::ComponentLogLikelihood(), VectorBase< Real >::Data(), SgmmGselectConfig::diag_gmm_nbest, AmSgmm::diag_ubm_, VectorBase< Real >::Dim(), DiagGmm::Dim(), SgmmGselectConfig::full_gmm_nbest, AmSgmm::full_ubm_, rnnlm::i, KALDI_ASSERT, FullGmm::LogLikelihoods(), DiagGmm::LogLikelihoods(), FullGmm::NumGauss(), and DiagGmm::NumGauss().
Referenced by kaldi::AccumulateForUtterance(), DecodableAmSgmm::LogLikelihoodZeroBased(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmIncreaseDim(), TestSgmmInit(), TestSgmmIO(), TestSgmmSubstates(), and TestUpdateAndAccsIO().
{
   KALDI_ASSERT(diag_ubm_.NumGauss() != 0 &&
                diag_ubm_.NumGauss() == full_ubm_.NumGauss() &&
                diag_ubm_.Dim() == data.Dim());
   KALDI_ASSERT(config.diag_gmm_nbest > 0 && config.full_gmm_nbest > 0 &&
                config.full_gmm_nbest < config.diag_gmm_nbest);
   int32 num_gauss = diag_ubm_.NumGauss();
   std::vector< std::pair<BaseFloat, int32> > pruned_pairs;
   if (config.diag_gmm_nbest < num_gauss) {
     Vector<BaseFloat> loglikes(num_gauss);
     diag_ubm_.LogLikelihoods(data, &loglikes);
     Vector<BaseFloat> loglikes_copy(loglikes);
     BaseFloat *ptr = loglikes_copy.Data();
     std::nth_element(ptr, ptr+num_gauss-config.diag_gmm_nbest, ptr+num_gauss);
     BaseFloat thresh = ptr[num_gauss-config.diag_gmm_nbest];
     for (int32 g = 0; g < num_gauss; g++)
       if (loglikes(g) >= thresh)  // met threshold for diagonal phase.
         pruned_pairs.push_back(
             std::make_pair(full_ubm_.ComponentLogLikelihood(data, g), g));
   } else {
     Vector<BaseFloat> loglikes(num_gauss);
     full_ubm_.LogLikelihoods(data, &loglikes);
     for (int32 g = 0; g < num_gauss; g++)
       pruned_pairs.push_back(std::make_pair(loglikes(g), g));
   }
   KALDI_ASSERT(!pruned_pairs.empty());
   if (pruned_pairs.size() > static_cast<size_t>(config.full_gmm_nbest)) {
     std::nth_element(pruned_pairs.begin(),
                      pruned_pairs.end() - config.full_gmm_nbest,
                      pruned_pairs.end());
     pruned_pairs.erase(pruned_pairs.begin(),
                        pruned_pairs.end() - config.full_gmm_nbest);
   }
   Vector<BaseFloat> loglikes_tmp(pruned_pairs.size());  // for return value.
   KALDI_ASSERT(gselect != NULL);
   gselect->resize(pruned_pairs.size());
   // Make sure pruned Gaussians appear from best to worst.
   std::sort(pruned_pairs.begin(), pruned_pairs.end(),
             std::greater< std::pair<BaseFloat, int32> >());
   for (size_t i = 0; i < pruned_pairs.size(); i++) {
     loglikes_tmp(i) = pruned_pairs[i].first;
     (*gselect)[i] = pruned_pairs[i].second;
   }
   return loglikes_tmp.LogSumExp();
 }
BaseFloat GaussianSelectionPreselect (const SgmmGselectConfig & config, const VectorBase< BaseFloat > & data, const std::vector< int32 > & preselect, std::vector< int32 > * gselect) const
As GaussianSelection, but limiting it to a provided list of preselected Gaussians (e.g.
for gender dependency). The list "preselect" must be sorted and uniq.
Definition at line 1266 of file am-sgmm.cc.
References FullGmm::ComponentLogLikelihood(), VectorBase< Real >::Data(), SgmmGselectConfig::diag_gmm_nbest, AmSgmm::diag_ubm_, VectorBase< Real >::Dim(), DiagGmm::Dim(), SgmmGselectConfig::full_gmm_nbest, AmSgmm::full_ubm_, rnnlm::i, kaldi::IsSortedAndUniq(), KALDI_ASSERT, DiagGmm::LogLikelihoodsPreselect(), FullGmm::NumGauss(), and DiagGmm::NumGauss().
{
   KALDI_ASSERT(IsSortedAndUniq(preselect) && !preselect.empty());
   KALDI_ASSERT(diag_ubm_.NumGauss() != 0 &&
                diag_ubm_.NumGauss() == full_ubm_.NumGauss() &&
                diag_ubm_.Dim() == data.Dim());
   int32 num_preselect = preselect.size();
   KALDI_ASSERT(config.diag_gmm_nbest > 0 && config.full_gmm_nbest > 0 &&
                config.full_gmm_nbest < num_preselect);
   std::vector<std::pair<BaseFloat, int32> > pruned_pairs;
   if (config.diag_gmm_nbest < num_preselect) {
     Vector<BaseFloat> loglikes(num_preselect);
     diag_ubm_.LogLikelihoodsPreselect(data, preselect, &loglikes);
     Vector<BaseFloat> loglikes_copy(loglikes);
     BaseFloat *ptr = loglikes_copy.Data();
     std::nth_element(ptr, ptr+num_preselect-config.diag_gmm_nbest,
                      ptr+num_preselect);
     BaseFloat thresh = ptr[num_preselect-config.diag_gmm_nbest];
     for (int32 p = 0; p < num_preselect; p++) {
       if (loglikes(p) >= thresh) {  // met threshold for diagonal phase.
         int32 g = preselect[p];
         pruned_pairs.push_back(
             std::make_pair(full_ubm_.ComponentLogLikelihood(data, g), g));
       }
     }
   } else {
     for (int32 p = 0; p < num_preselect; p++) {
       int32 g = preselect[p];
       pruned_pairs.push_back(
           std::make_pair(full_ubm_.ComponentLogLikelihood(data, g), g));
     }
   }
   KALDI_ASSERT(!pruned_pairs.empty());
   if (pruned_pairs.size() > static_cast<size_t>(config.full_gmm_nbest)) {
     std::nth_element(pruned_pairs.begin(),
                      pruned_pairs.end() - config.full_gmm_nbest,
                      pruned_pairs.end());
     pruned_pairs.erase(pruned_pairs.begin(),
                        pruned_pairs.end() - config.full_gmm_nbest);
   }
   // Make sure pruned Gaussians appear from best to worst.
   std::sort(pruned_pairs.begin(), pruned_pairs.end(),
             std::greater<std::pair<BaseFloat, int32> >());
   Vector<BaseFloat> loglikes_tmp(pruned_pairs.size());  // for return value.
   KALDI_ASSERT(gselect != NULL);
   gselect->resize(pruned_pairs.size());
   for (size_t i = 0; i < pruned_pairs.size(); i++) {
     loglikes_tmp(i) = pruned_pairs[i].first;
     (*gselect)[i] = pruned_pairs[i].second;
   }
   return loglikes_tmp.LogSumExp();
 }
const SpMatrix<BaseFloat>& GetInvCovars (int32 gauss_index) const inline
Definition at line 234 of file am-sgmm.h.
References AmSgmm::SigmaInv_.
Referenced by kaldi::CalcFmllrStepSize(), and FmllrSgmmAccs::FmllrObjGradient().
{
     return SigmaInv_[gauss_index];
   }
void GetInvCovars (int32 gauss_index, SpMatrix< Real > * out) const inline
Templated accessors (used to accumulate in different precision)
Definition at line 334 of file am-sgmm.h.
References SpMatrix< Real >::CopyFromSp(), kaldi::kUndefined, SpMatrix< Real >::Resize(), and AmSgmm::SigmaInv_.
{
   out->Resize(SigmaInv_[gauss_index].NumRows(), kUndefined);
   out->CopyFromSp(SigmaInv_[gauss_index]);
 }
template void GetNtransSigmaInv (std::vector< Matrix< Real > > * out) const
Definition at line 976 of file am-sgmm.cc.
References MatrixBase< Real >::CopyFromMat(), MatrixBase< Real >::CopyFromSp(), AmSgmm::FeatureDim(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, AmSgmm::N_, AmSgmm::NumGauss(), AmSgmm::SigmaInv_, and AmSgmm::SpkSpaceDim().
Referenced by MleSgmmSpeakerAccs::MleSgmmSpeakerAccs().
{
   KALDI_ASSERT(SpkSpaceDim() > 0 &&
       "Cannot compute N^{T} \\Sigma_{i}^{-1} without speaker projections.");
   out->resize(NumGauss());
   Matrix<Real> tmpcov(FeatureDim(), FeatureDim());
   Matrix<Real> tmp_n(FeatureDim(), SpkSpaceDim());
   for (int32 i = 0; i < NumGauss(); i++) {
     tmpcov.CopyFromSp(SigmaInv_[i]);
     tmp_n.CopyFromMat(N_[i]);
     (*out)[i].Resize(SpkSpaceDim(), FeatureDim());
     (*out)[i].AddMatMat(1.0, tmp_n, kTrans, tmpcov, kNoTrans, 0.0);
   }
 }
const Matrix<BaseFloat>& GetPhoneProjection (int32 gauss_index) const inline
Definition at line 237 of file am-sgmm.h.
References AmSgmm::M_.
Referenced by MleAmSgmmGlobalAccs::AddAccumulators().
{
     return M_[gauss_index];
   }
void GetSubstateMean (int32 j, int32 m, int32 i, VectorBase< Real > * mean_out) const inline
Definition at line 341 of file am-sgmm.h.
References VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), AmSgmm::FeatureDim(), KALDI_ASSERT, kaldi::kNoTrans, AmSgmm::M_, AmSgmm::NumGauss(), AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), and AmSgmm::v_.
Referenced by MleAmSgmmAccs::AccumulateFromPosteriors(), MleSgmmSpeakerAccs::AccumulateFromPosteriors(), MleAmSgmmGlobalAccs::AddAccumulators(), and AmSgmm::GetSubstateSpeakerMean().
{
   KALDI_ASSERT(mean_out != NULL);
   KALDI_ASSERT(j < NumPdfs() && m < NumSubstates(j) && i < NumGauss());
   KALDI_ASSERT(mean_out->Dim() == FeatureDim());
   Vector<BaseFloat> mean_tmp(FeatureDim());
   mean_tmp.AddMatVec(1.0, M_[i], kNoTrans, v_[j].Row(m), 0.0);
   mean_out->CopyFromVec(mean_tmp);
 }
void GetSubstateSpeakerMean (int32 state, int32 substate, int32 gauss, const SgmmPerSpkDerivedVars & spk, VectorBase< Real > * mean_out) const inline
Definition at line 353 of file am-sgmm.h.
References VectorBase< Real >::AddVec(), VectorBase< Real >::Dim(), AmSgmm::GetSubstateMean(), SgmmPerSpkDerivedVars::o_s, MatrixBase< Real >::Row(), and SgmmPerSpkDerivedVars::v_s.
Referenced by AmSgmm::GetVarScaledSubstateSpeakerMean().
{
   GetSubstateMean(j, m, i, mean_out);
   if (spk.v_s.Dim() != 0)  // have speaker adaptation...
     mean_out->AddVec(1.0, spk.o_s.Row(i));
 }
void GetVarScaledSubstateSpeakerMean (int32 state, int32 substate, int32 gauss, const SgmmPerSpkDerivedVars & spk, VectorBase< Real > * mean_out) const
Definition at line 362 of file am-sgmm.h.
References VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), AmSgmm::GetSubstateSpeakerMean(), and AmSgmm::SigmaInv_.
Referenced by FmllrSgmmAccs::AccumulateFromPosteriors().
{
   Vector<BaseFloat> tmp_mean(mean_out->Dim()), tmp_mean2(mean_out->Dim());
   GetSubstateSpeakerMean(j, m, i, spk, &tmp_mean);
   tmp_mean2.AddSpVec(1.0, SigmaInv_[i], tmp_mean, 0.0);
   mean_out->CopyFromVec(tmp_mean2);
 }
void IncreasePhoneSpaceDim (int32 target_dim, const Matrix< BaseFloat > & norm_xform)
Functions for increasing the phonetic and speaker space dimensions.
The argument norm_xform is a LDA-like feature normalizing transform, computed by the ComputeFeatureNormalizer function.
Definition at line 561 of file am-sgmm.cc.
References MatrixBase< Real >::CopyFromMat(), AmSgmm::FeatureDim(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, KALDI_LOG, KALDI_WARN, AmSgmm::M_, MatrixBase< Real >::NumCols(), AmSgmm::NumGauss(), AmSgmm::NumPdfs(), MatrixBase< Real >::NumRows(), AmSgmm::PhoneSpaceDim(), MatrixBase< Real >::Range(), Matrix< Real >::Resize(), AmSgmm::v_, and AmSgmm::w_.
{
   KALDI_ASSERT(!M_.empty());
   int32 initial_dim = PhoneSpaceDim(),
       feat_dim = FeatureDim();
   KALDI_ASSERT(norm_xform.NumRows() == feat_dim);
   if (target_dim < initial_dim)
     KALDI_ERR << "You asked to increase phn dim to a value lower than the "
               << " current dimension, " << target_dim << " < " << initial_dim;
   if (target_dim > initial_dim + feat_dim) {
     KALDI_WARN << "Cannot increase phone subspace dimensionality from "
                << initial_dim << " to " << target_dim << ", increasing to "
                << initial_dim + feat_dim;
     target_dim = initial_dim + feat_dim;
   }
   if (initial_dim < target_dim) {
     Matrix<BaseFloat> tmp_M(feat_dim, initial_dim);
     for (int32 i = 0; i < NumGauss(); i++) {
       tmp_M.CopyFromMat(M_[i]);
       M_[i].Resize(feat_dim, target_dim);
       M_[i].Range(0, feat_dim, 0, tmp_M.NumCols()).CopyFromMat(tmp_M);
       M_[i].Range(0, feat_dim, tmp_M.NumCols(),
           target_dim - tmp_M.NumCols()).CopyFromMat(norm_xform.Range(0,
               feat_dim, 0, target_dim-tmp_M.NumCols()));
     }
     Matrix<BaseFloat> tmp_w = w_;
     w_.Resize(tmp_w.NumRows(), target_dim);
     w_.Range(0, tmp_w.NumRows(), 0, tmp_w.NumCols()).CopyFromMat(tmp_w);
     for (int32 j = 0; j < NumPdfs(); j++) {
       // Resize v[j]
       Matrix<BaseFloat> tmp_v_j = v_[j];
       v_[j].Resize(tmp_v_j.NumRows(), target_dim);
       v_[j].Range(0, tmp_v_j.NumRows(), 0, tmp_v_j.NumCols()).CopyFromMat(
           tmp_v_j);
     }
     KALDI_LOG << "Phone subspace dimensionality increased from " <<
         initial_dim << " to " << target_dim;
   } else {
     KALDI_LOG << "Phone subspace dimensionality unchanged, since target " <<
         "dimension (" << target_dim << ") <= initial dimansion (" <<
         initial_dim << ")";
   }
 }
void IncreaseSpkSpaceDim (int32 target_dim, const Matrix< BaseFloat > & norm_xform)
Definition at line 609 of file am-sgmm.cc.
References MatrixBase< Real >::CopyFromMat(), AmSgmm::FeatureDim(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_LOG, KALDI_WARN, AmSgmm::N_, MatrixBase< Real >::NumCols(), AmSgmm::NumGauss(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Range(), and AmSgmm::SpkSpaceDim().
{
   int32 initial_dim = SpkSpaceDim(),
       feat_dim = FeatureDim();
   KALDI_ASSERT(norm_xform.NumRows() == feat_dim);
   if (N_.size() == 0)
     N_.resize(NumGauss());
   if (target_dim < initial_dim)
     KALDI_ERR << "You asked to increase spk dim to a value lower than the "
               << " current dimension, " << target_dim << " < " << initial_dim;
   if (target_dim > initial_dim + feat_dim) {
     KALDI_WARN << "Cannot increase speaker subspace dimensionality from "
                << initial_dim << " to " << target_dim << ", increasing to "
                << initial_dim + feat_dim;
     target_dim = initial_dim + feat_dim;
   }
   if (initial_dim < target_dim) {
     int32 dim_change = target_dim - initial_dim;
     Matrix<BaseFloat> tmp_N((initial_dim != 0) ? feat_dim : 0,
                             initial_dim);
     for (int32 i = 0; i < NumGauss(); i++) {
       if (initial_dim != 0) tmp_N.CopyFromMat(N_[i]);
       N_[i].Resize(feat_dim, target_dim);
       if (initial_dim != 0) {
         N_[i].Range(0, feat_dim, 0, tmp_N.NumCols()).CopyFromMat(tmp_N);
       }
       N_[i].Range(0, feat_dim, tmp_N.NumCols(), dim_change).CopyFromMat(
           norm_xform.Range(0, feat_dim, 0, dim_change));
     }
     KALDI_LOG << "Speaker subspace dimensionality increased from " <<
         initial_dim << " to " << target_dim;
   } else {
     KALDI_LOG << "Speaker subspace dimensionality unchanged, since target " <<
         "dimension (" << target_dim << ") <= initial dimansion (" <<
         initial_dim << ")";
   }
 }
void InitializeCovars () private
initializes the within-class covariances.
Definition at line 1074 of file am-sgmm.cc.
References FullGmm::Dim(), AmSgmm::full_ubm_, rnnlm::i, FullGmm::inv_covars(), FullGmm::NumGauss(), and AmSgmm::SigmaInv_.
Referenced by AmSgmm::InitializeFromFullGmm().
{
   std::vector< SpMatrix<BaseFloat> > &inv_covars(full_ubm_.inv_covars());
   int32 num_gauss = full_ubm_.NumGauss();
   int32 dim = full_ubm_.Dim();
   SigmaInv_.resize(num_gauss);
   for (int32 i = 0; i < num_gauss; i++) {
     SigmaInv_[i].Resize(dim);
     SigmaInv_[i].CopyFromSp(inv_covars[i]);
   }
 }
void InitializeFromFullGmm (const FullGmm & gmm, int32 num_states, int32 phn_subspace_dim, int32 spk_subspace_dim)
Initializes the SGMM parameters from a full-covariance UBM.
Definition at line 283 of file am-sgmm.cc.
References AmSgmm::c_, kaldi::ComputeFeatureNormalizer(), FullGmm::CopyFromFullGmm(), DiagGmm::CopyFromFullGmm(), AmSgmm::diag_ubm_, FullGmm::Dim(), AmSgmm::full_ubm_, AmSgmm::InitializeCovars(), AmSgmm::InitializeMw(), AmSgmm::InitializeN(), AmSgmm::InitializeVecs(), KALDI_LOG, KALDI_WARN, AmSgmm::N_, Matrix< Real >::Resize(), AmSgmm::SigmaInv_, AmSgmm::v_, and AmSgmm::w_.
Referenced by TestSgmmFmllr(), UnitTestEstimateSgmm(), and UnitTestSgmm().
{
   full_ubm_.CopyFromFullGmm(full_gmm);
   diag_ubm_.CopyFromFullGmm(full_gmm);
   if (phn_subspace_dim < 1 || phn_subspace_dim > full_gmm.Dim() + 1) {
     KALDI_WARN << "Initial phone-subspace dimension must be in [1, "
                << full_gmm.Dim() + 1 << "]. Changing from " << phn_subspace_dim
                << " to " << full_gmm.Dim() + 1;
     phn_subspace_dim = full_gmm.Dim() + 1;
   }
   if (spk_subspace_dim < 0 || spk_subspace_dim > full_gmm.Dim()) {
     KALDI_WARN << "Initial spk-subspace dimension must be in [1, "
                << full_gmm.Dim() << "]. Changing from " << spk_subspace_dim
                << " to " << full_gmm.Dim();
     spk_subspace_dim = full_gmm.Dim();
   }
   w_.Resize(0, 0);
   N_.clear();
   c_.clear();
   v_.clear();
   SigmaInv_.clear();
   KALDI_LOG << "Initializing model";
   Matrix<BaseFloat> norm_xform;
   ComputeFeatureNormalizer(full_gmm, &norm_xform);
   InitializeMw(phn_subspace_dim, norm_xform);
   if (spk_subspace_dim > 0) InitializeN(spk_subspace_dim, norm_xform);
   InitializeVecs(num_states);
   KALDI_LOG << "Initializing variances";
   InitializeCovars();
 }
void InitializeMw (int32 phn_subspace_dim, const Matrix< BaseFloat > & norm_xform) private
Initializes the matrices M_ and w_.
Definition at line 1018 of file am-sgmm.cc.
References MatrixBase< Real >::CopyColFromVec(), FullGmm::Dim(), AmSgmm::full_ubm_, FullGmm::GetComponentMean(), rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, AmSgmm::M_, MatrixBase< Real >::NumCols(), FullGmm::NumGauss(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Range(), Matrix< Real >::Resize(), and AmSgmm::w_.
Referenced by AmSgmm::InitializeFromFullGmm().
{
   int32 ddim = full_ubm_.Dim();
   KALDI_ASSERT(phn_subspace_dim <= ddim + 1);
   KALDI_ASSERT(phn_subspace_dim <= norm_xform.NumCols() + 1);
   KALDI_ASSERT(ddim <= norm_xform.NumRows());
   Vector<BaseFloat> mean(ddim);
   int32 num_gauss = full_ubm_.NumGauss();
   w_.Resize(num_gauss, phn_subspace_dim);
   M_.resize(num_gauss);
   for (int32 i = 0; i < num_gauss; i++) {
     full_ubm_.GetComponentMean(i, &mean);
     Matrix<BaseFloat> &thisM(M_[i]);
     thisM.Resize(ddim, phn_subspace_dim);
     // Eq. (27): M_{i} = [ \bar{\mu}_{i} (J)_{1:D, 1:(S-1)}]
     thisM.CopyColFromVec(mean, 0);
     thisM.Range(0, ddim, 1, phn_subspace_dim-1).CopyFromMat(
         norm_xform.Range(0, ddim, 0, phn_subspace_dim-1), kNoTrans);
   }
 }
void InitializeN (int32 spk_subspace_dim, const Matrix< BaseFloat > & norm_xform) private
Initializes the matrices N_.
Definition at line 1041 of file am-sgmm.cc.
References FullGmm::Dim(), AmSgmm::full_ubm_, rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, AmSgmm::N_, MatrixBase< Real >::NumCols(), FullGmm::NumGauss(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Range().
Referenced by AmSgmm::InitializeFromFullGmm().
{
   int32 ddim = full_ubm_.Dim();
   KALDI_ASSERT(spk_subspace_dim <= ddim);
   KALDI_ASSERT(spk_subspace_dim <= norm_xform.NumCols());
   KALDI_ASSERT(ddim <= norm_xform.NumRows());
   int32 num_gauss = full_ubm_.NumGauss();
   N_.resize(num_gauss);
   for (int32 i = 0; i < num_gauss; i++) {
     N_[i].Resize(ddim, spk_subspace_dim);
     // Eq. (28): N_{i} = [ (J)_{1:D, 1:T)}]
     N_[i].CopyFromMat(norm_xform.Range(0, ddim, 0, spk_subspace_dim), kNoTrans);
   }
 }
void InitializeVecs (int32 num_states) private
Initializes the state-vectors.
Definition at line 1058 of file am-sgmm.cc.
References AmSgmm::c_, rnnlm::j, KALDI_ASSERT, AmSgmm::PhoneSpaceDim(), and AmSgmm::v_.
Referenced by AmSgmm::CopyGlobalsInitVecs(), and AmSgmm::InitializeFromFullGmm().
{
   KALDI_ASSERT(num_states >= 0);
   int32 phn_subspace_dim = PhoneSpaceDim();
   KALDI_ASSERT(phn_subspace_dim > 0 && "Initialize M and w first.");
   v_.resize(num_states);
   c_.resize(num_states);
   for (int32 j = 0; j < num_states; j++) {
     v_[j].Resize(1, phn_subspace_dim);
     c_[j].Resize(1);
     v_[j](0, 0) = 1.0;  // Eq. (26): v_{j1} = [1 0 0 ... 0]
     c_[j](0) = 1.0;     // Eq. (25): c_{j1} = 1.0
   }
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (AmSgmm) private
BaseFloat LogLikelihood (const SgmmPerFrameDerivedVars & per_frame_vars, int32 state_index, BaseFloat log_prune = 0.0) const
This does a likelihood computation for a given state using the top-scoring Gaussian components (in per_frame_vars).
If the log_prune parameter is nonzero (e.g. 5.0), the LogSumExp() stage is pruned, which is a significant speedup... smaller values are faster.
Definition at line 422 of file am-sgmm.cc.
References VectorBase< Real >::Add(), VectorBase< Real >::AddMatVec(), VectorBase< Real >::AddVec(), SgmmPerFrameDerivedVars::gselect, rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, AmSgmm::n_, SgmmPerFrameDerivedVars::nti, AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), MatrixBase< Real >::Row(), AmSgmm::v_, and SgmmPerFrameDerivedVars::zti.
Referenced by DecodableAmSgmm::LogLikelihoodZeroBased(), TestSgmmFmllrAccsIO(), TestSgmmIncreaseDim(), TestSgmmInit(), TestSgmmIO(), and TestSgmmSubstates().
{
   KALDI_ASSERT(j < NumPdfs());
   const vector<int32> &gselect = per_frame_vars.gselect;
   // Eq.(37): log p(x(t), m, i|j)  [indexed by j, ki]
   // Although the extra memory allocation of storing this as a
   // matrix might seem unnecessary, we save time in the LogSumExp()
   // via more effective pruning.
   Matrix<BaseFloat> logp_x(gselect.size(), NumSubstates(j));
   for (int32 ki = 0, last = gselect.size();  ki < last; ki++) {
     SubVector<BaseFloat> logp_xi(logp_x, ki);
     int32 i = gselect[ki];
     // for all substates, compute z_{i}^T v_{jm}
     logp_xi.AddMatVec(1.0, v_[j], kNoTrans, per_frame_vars.zti.Row(ki), 0.0);
     logp_xi.AddVec(1.0, n_[j].Row(i));  // for all substates, add n_{jim}
     logp_xi.Add(per_frame_vars.nti(ki));  // for all substates, add n_{i}(t)
   }
   // Eq. (38): log p(x(t)|j) = log \sum_{m, i} p(x(t), m, i|j)
   return logp_x.LogSumExp(log_prune);
 }
int32 NumGauss () const inline
Definition at line 220 of file am-sgmm.h.
References AmSgmm::M_.
Referenced by kaldi::CalcFmllrStepSize(), AmSgmm::Check(), MleAmSgmmAccs::Check(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeH(), MleAmSgmmUpdater::ComputeMPrior(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputePerSpkDerivedVars(), AmSgmm::ComputeSmoothingTermsFromModel(), FmllrSgmmAccs::FmllrObjGradient(), AmSgmm::GetNtransSigmaInv(), AmSgmm::GetSubstateMean(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm::IncreaseSpkSpaceDim(), main(), MleAmSgmmUpdater::MapUpdateM(), MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), SgmmClusterable::Objf(), MleAmSgmmGlobalAccs::ResizeAccumulators(), MleAmSgmmAccs::ResizeAccumulators(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmIncreaseDim(), TestSgmmInit(), TestSgmmIO(), TestSgmmSubstates(), TestUpdateAndAccsIO(), EbwAmSgmmUpdater::UpdateM(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), and AmSgmm::Write().
 { return M_.size(); }
int32 NumPdfs () const inline
Various model dimensions.
Definition at line 218 of file am-sgmm.h.
References AmSgmm::c_.
Referenced by MleAmSgmmGlobalAccs::AddAccumulators(), AmSgmm::Check(), MleAmSgmmAccs::Check(), AmSgmm::ComponentPosteriors(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeNormalizers(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputeSmoothingTermsFromModel(), AmSgmm::GetSubstateMean(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm::LogLikelihood(), main(), DecodableAmSgmm::ResetLogLikeCache(), MleAmSgmmAccs::ResizeAccumulators(), AmSgmm::SplitSubstates(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmInit(), TestSgmmPreXform(), TestSgmmSubstates(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), and AmSgmm::Write().
 { return c_.size(); }
int32 NumSubstates (int32 j) const inline
Definition at line 219 of file am-sgmm.h.
References AmSgmm::c_, and rnnlm::j.
Referenced by FmllrSgmmAccs::AccumulateFromPosteriors(), MleAmSgmmAccs::AccumulateFromPosteriors(), MleSgmmSpeakerAccs::AccumulateFromPosteriors(), MleAmSgmmGlobalAccs::AddAccumulators(), AmSgmm::Check(), MleAmSgmmAccs::Check(), AmSgmm::ComponentPosteriors(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), MleAmSgmmUpdater::ComputeQ(), MleAmSgmmUpdater::ComputeSMeans(), MleAmSgmmUpdater::ComputeSmoothingTerms(), AmSgmm::ComputeSmoothingTermsFromModel(), AmSgmm::GetSubstateMean(), AmSgmm::LogLikelihood(), main(), MleAmSgmmUpdater::MapUpdateM(), MleAmSgmmUpdater::RenormalizeN(), MleAmSgmmUpdater::RenormalizeV(), MleAmSgmmAccs::ResizeAccumulators(), AmSgmm::SplitSubstates(), MleAmSgmmUpdater::UpdateM(), MleAmSgmmUpdater::UpdateN(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), EbwAmSgmmUpdater::UpdateSubstateWeights(), MleAmSgmmUpdater::UpdateSubstateWeights(), MleAmSgmmUpdater::UpdateVars(), MleAmSgmmUpdater::UpdateWParallel(), MleAmSgmmUpdater::UpdateWParallelGetStats(), and MleAmSgmmUpdater::UpdateWSequential().
 { return c_[j].Dim(); }
int32 PhoneSpaceDim () const inline
Definition at line 221 of file am-sgmm.h.
References MatrixBase< Real >::NumCols(), and AmSgmm::w_.
Referenced by AmSgmm::Check(), MleAmSgmmAccs::Check(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeH(), MleAmSgmmUpdater::ComputeMPrior(), AmSgmm::ComputePerFrameVars(), AmSgmm::ComputeSmoothingTermsFromModel(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::IncreasePhoneSpaceDim(), kaldi::InitAndOutputSgmm(), AmSgmm::InitializeVecs(), main(), MleAmSgmmUpdater::MapUpdateM(), MleAmSgmmGlobalAccs::ResizeAccumulators(), MleAmSgmmAccs::ResizeAccumulators(), AmSgmm::SplitSubstates(), TestSgmmFmllrAccsIO(), TestSgmmFmllrSubspace(), TestSgmmIncreaseDim(), TestSgmmInit(), TestSgmmIO(), TestUpdateAndAccsIO(), EbwAmSgmmUpdater::UpdateM(), and MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal().
 { return w_.NumCols(); }
void Read (std::istream & rIn, bool binary)
Definition at line 39 of file am-sgmm.cc.
References AmSgmm::c_, AmSgmm::col_cov_inv_, AmSgmm::ComputeNormalizers(), AmSgmm::diag_ubm_, kaldi::ExpectToken(), AmSgmm::full_ubm_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, AmSgmm::M_, AmSgmm::M_prior_, AmSgmm::N_, AmSgmm::n_, FullGmm::Read(), PackedMatrix< Real >::Read(), DiagGmm::Read(), Matrix< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), AmSgmm::row_cov_inv_, AmSgmm::SigmaInv_, AmSgmm::v_, and AmSgmm::w_.
Referenced by main().
{
   int32 num_states, feat_dim, num_gauss;
   std::string token;
   ExpectToken(in_stream, binary, "<SGMM>");
   ExpectToken(in_stream, binary, "<NUMSTATES>");
   ReadBasicType(in_stream, binary, &num_states);
   ExpectToken(in_stream, binary, "<DIMENSION>");
   ReadBasicType(in_stream, binary, &feat_dim);
   KALDI_ASSERT(num_states > 0 && feat_dim > 0);
   ReadToken(in_stream, binary, &token);
   while (token != "</SGMM>") {
     if (token == "<DIAG_UBM>") {
       diag_ubm_.Read(in_stream, binary);
     } else if (token == "<FULL_UBM>") {
       full_ubm_.Read(in_stream, binary);
     } else if (token == "<SigmaInv>") {
       ExpectToken(in_stream, binary, "<NUMGaussians>");
       ReadBasicType(in_stream, binary, &num_gauss);
       SigmaInv_.resize(num_gauss);
       for (int32 i = 0; i < num_gauss; i++) {
         SigmaInv_[i].Read(in_stream, binary);
       }
     } else if (token == "<M>") {
       ExpectToken(in_stream, binary, "<NUMGaussians>");
       ReadBasicType(in_stream, binary, &num_gauss);
       M_.resize(num_gauss);
       for (int32 i = 0; i < num_gauss; i++) {
         M_[i].Read(in_stream, binary);
       }
     } else if (token == "<N>") {
       ExpectToken(in_stream, binary, "<NUMGaussians>");
       ReadBasicType(in_stream, binary, &num_gauss);
       N_.resize(num_gauss);
       for (int32 i = 0; i < num_gauss; i++) {
         N_[i].Read(in_stream, binary);
       }
     } else if (token == "<w>") {
       w_.Read(in_stream, binary);
     } else if (token == "<v>") {
       v_.resize(num_states);
       for (int32 j = 0; j < num_states; j++) {
         v_[j].Read(in_stream, binary);
       }
     } else if (token == "<c>") {
       c_.resize(num_states);
       for (int32 j = 0; j < num_states; j++) {
         c_[j].Read(in_stream, binary);
       }
     } else if (token == "<n>") {
       n_.resize(num_states);
       for (int32 j = 0; j < num_states; j++) {
         n_[j].Read(in_stream, binary);
       }
       // The following are the Gaussian prior parameters for MAP adaptation of M
       // They may be moved to somewhere else eventually.
     } else if (token == "<M_Prior>") {
       ExpectToken(in_stream, binary, "<NUMGaussians>");
       ReadBasicType(in_stream, binary, &num_gauss);
       M_prior_.resize(num_gauss);
       for (int32 i = 0; i < num_gauss; i++) {
         M_prior_[i].Read(in_stream, binary);
       }
     } else if (token == "<Row_Cov_Inv>") {
       row_cov_inv_.Read(in_stream, binary);
     } else if (token == "<Col_Cov_Inv>") {
       col_cov_inv_.Read(in_stream, binary);
     } else {
       KALDI_ERR << "Unexpected token '" << token << "' in model file ";
     }
     ReadToken(in_stream, binary, &token);
   }
   if (n_.empty()) {
     ComputeNormalizers();
   }
 }
void RemoveSpeakerSpace () inline
Definition at line 225 of file am-sgmm.h.
References AmSgmm::N_.
 { N_.clear(); }
int32 SpkSpaceDim () const inline
Definition at line 222 of file am-sgmm.h.
References AmSgmm::N_.
Referenced by MleSgmmSpeakerAccs::AccumulateFromPosteriors(), AmSgmm::Check(), MleAmSgmmAccs::Check(), AmSgmm::ComputePerSpkDerivedVars(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::GetNtransSigmaInv(), AmSgmm::IncreaseSpkSpaceDim(), kaldi::InitAndOutputSgmm(), main(), MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), MleAmSgmmGlobalAccs::ResizeAccumulators(), MleAmSgmmAccs::ResizeAccumulators(), and TestSgmmInit().
 { return (N_.size() > 0) ? N_[0].NumCols() : 0; }
void SplitSubstates (const Vector< BaseFloat > & state_occupancies, int32 target_nsubstates, BaseFloat perturb, BaseFloat power, BaseFloat cond)
Increases the total number of substates based on the state occupancies.
Definition at line 482 of file am-sgmm.cc.
References kaldi::_RandGauss(), VectorBase< Real >::AddSpVec(), SpMatrix< Real >::ApplyPow(), AmSgmm::c_, AmSgmm::ComputeH(), AmSgmm::ComputeSmoothingTermsFromModel(), VectorBase< Real >::Dim(), rnnlm::j, KALDI_ASSERT, KALDI_LOG, KALDI_WARN, AmSgmm::n_, SubstateCounter::num_substates, AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), AmSgmm::PhoneSpaceDim(), Vector< Real >::Resize(), Matrix< Real >::Resize(), and AmSgmm::v_.
{
   // power == p in document.  target_nsubstates == T in document.
   KALDI_ASSERT(state_occupancies.Dim() == NumPdfs());
   int32 tot_n_substates_old = 0;
   int32 phn_dim = PhoneSpaceDim();
   std::priority_queue<SubstateCounter> substate_counts;
   vector< SpMatrix<BaseFloat> > H_i;
   SpMatrix<BaseFloat> sqrt_H_sm;
   Vector<BaseFloat> rand_vec(phn_dim), v_shift(phn_dim);
   for (int32 j = 0; j < NumPdfs(); j++) {
     BaseFloat gamma_p = pow(state_occupancies(j), power);
     substate_counts.push(SubstateCounter(j, NumSubstates(j), gamma_p));
     tot_n_substates_old += NumSubstates(j);
   }
   if (target_nsubstates <= tot_n_substates_old || tot_n_substates_old == 0) {
     KALDI_WARN << "Cannot split from " << (tot_n_substates_old) <<
         " to " << (target_nsubstates) << " substates.";
     return;
   }
   ComputeH(&H_i);  // set up that array.
   ComputeSmoothingTermsFromModel(H_i, state_occupancies, &sqrt_H_sm, max_cond);
   H_i.clear();
   sqrt_H_sm.ApplyPow(-0.5);
   for (int32 n_states = tot_n_substates_old;
        n_states < target_nsubstates; n_states++) {
     SubstateCounter state_to_split = substate_counts.top();
     substate_counts.pop();
     state_to_split.num_substates++;
     substate_counts.push(state_to_split);
   }
   while (!substate_counts.empty()) {
     int32 j = substate_counts.top().state_index;
     int32 tgt_n_substates_j = substate_counts.top().num_substates;
     int32 n_substates_j     = NumSubstates(j);
     substate_counts.pop();
     if (n_substates_j == tgt_n_substates_j) continue;
     // Resize v[j] and c[j] to fit new substates
     Matrix<BaseFloat> tmp_v_j(v_[j]);
     v_[j].Resize(tgt_n_substates_j, phn_dim);
     v_[j].Range(0, n_substates_j, 0, phn_dim).CopyFromMat(tmp_v_j);
     tmp_v_j.Resize(0, 0);
     Vector<BaseFloat> tmp_c_j(c_[j]);
     c_[j].Resize(tgt_n_substates_j);
     c_[j].Range(0, n_substates_j).CopyFromVec(tmp_c_j);
     tmp_c_j.Resize(0);
     // Keep splitting substates until obtaining the desired number
     for (; n_substates_j < tgt_n_substates_j; n_substates_j++) {
       int32 split_substate = std::max_element(c_[j].Data(), c_[j].Data()
           + n_substates_j) - c_[j].Data();
       // c_{jkm} := c_{jmk}' := c_{jkm} / 2
       c_[j](split_substate) = c_[j](n_substates_j) = c_[j](split_substate) / 2;
       // v_{jkm} := +/- split_perturb * H_k^{(sm)}^{-0.5} * rand_vec
       std::generate(rand_vec.Data(), rand_vec.Data() + rand_vec.Dim(),
                     _RandGauss);
       v_shift.AddSpVec(perturb, sqrt_H_sm, rand_vec, 0.0);
       v_[j].Row(n_substates_j).CopyFromVec(v_[j].Row(split_substate));
       v_[j].Row(n_substates_j).AddVec(1.0, v_shift);
       v_[j].Row(split_substate).AddVec((-1.0), v_shift);
     }
   }
   KALDI_LOG << "Getting rid of normalizers as they will no longer be valid";
   n_.clear();
   KALDI_LOG << "Split " << (tot_n_substates_old) << " substates to "
       << (target_nsubstates);
 }
const Matrix<BaseFloat>& StateVectors (int32 state_index) const inline
Definition at line 231 of file am-sgmm.h.
References AmSgmm::v_.
Referenced by MleAmSgmmAccs::AccumulateFromPosteriors(), and MleAmSgmmGlobalAccs::AddAccumulators().
{
     return v_[state_index];
   }
void Write (std::ostream & out, bool binary, SgmmWriteFlagsType write_params) const
Definition at line 119 of file am-sgmm.cc.
References AmSgmm::c_, AmSgmm::col_cov_inv_, AmSgmm::diag_ubm_, AmSgmm::FeatureDim(), AmSgmm::full_ubm_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_WARN, kaldi::kSgmmBackgroundGmms, kaldi::kSgmmGlobalParams, kaldi::kSgmmNormalizers, kaldi::kSgmmStateParams, AmSgmm::M_, AmSgmm::M_prior_, AmSgmm::N_, AmSgmm::n_, AmSgmm::NumGauss(), AmSgmm::NumPdfs(), PackedMatrix< Real >::NumRows(), AmSgmm::row_cov_inv_, AmSgmm::SigmaInv_, AmSgmm::v_, AmSgmm::w_, FullGmm::Write(), PackedMatrix< Real >::Write(), DiagGmm::Write(), MatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by kaldi::InitAndOutputSgmm(), main(), and TestSgmmIO().
{
   int32 num_states = NumPdfs(),
       feat_dim = FeatureDim(),
       num_gauss = NumGauss();
   WriteToken(out_stream, binary, "<SGMM>");
   if (!binary) out_stream << "\n";
   WriteToken(out_stream, binary, "<NUMSTATES>");
   WriteBasicType(out_stream, binary, num_states);
   WriteToken(out_stream, binary, "<DIMENSION>");
   WriteBasicType(out_stream, binary, feat_dim);
   if (!binary) out_stream << "\n";
   if (write_params & kSgmmBackgroundGmms) {
     WriteToken(out_stream, binary, "<DIAG_UBM>");
     diag_ubm_.Write(out_stream, binary);
     WriteToken(out_stream, binary, "<FULL_UBM>");
     full_ubm_.Write(out_stream, binary);
   }
   if (write_params & kSgmmGlobalParams) {
     WriteToken(out_stream, binary, "<SigmaInv>");
     WriteToken(out_stream, binary, "<NUMGaussians>");
     WriteBasicType(out_stream, binary, num_gauss);
     if (!binary) out_stream << "\n";
     for (int32 i = 0; i < num_gauss; i++) {
       SigmaInv_[i].Write(out_stream, binary);
     }
     WriteToken(out_stream, binary, "<M>");
     WriteToken(out_stream, binary, "<NUMGaussians>");
     WriteBasicType(out_stream, binary, num_gauss);
     if (!binary) out_stream << "\n";
     for (int32 i = 0; i < num_gauss; i++) {
       M_[i].Write(out_stream, binary);
     }
     if (N_.size() != 0) {
       WriteToken(out_stream, binary, "<N>");
       WriteToken(out_stream, binary, "<NUMGaussians>");
       WriteBasicType(out_stream, binary, num_gauss);
       if (!binary) out_stream << "\n";
       for (int32 i = 0; i < num_gauss; i++) {
         N_[i].Write(out_stream, binary);
       }
     }
     WriteToken(out_stream, binary, "<w>");
     w_.Write(out_stream, binary);
     // The following are the Gaussian prior parameters for MAP adaptation of M.
     // They may be moved to somewhere else eventually.
     if (M_prior_.size() != 0) {
       WriteToken(out_stream, binary, "<M_Prior>");
       WriteToken(out_stream, binary, "<NUMGaussians>");
       WriteBasicType(out_stream, binary, num_gauss);
       if (!binary) out_stream << "\n";
       for (int32 i = 0; i < num_gauss; i++) {
         M_prior_[i].Write(out_stream, binary);
       }
       KALDI_ASSERT(row_cov_inv_.NumRows() != 0 &&
                    "Empty row covariance for MAP prior");
       WriteToken(out_stream, binary, "<Row_Cov_Inv>");
       if (!binary) out_stream << "\n";
       row_cov_inv_.Write(out_stream, binary);
       KALDI_ASSERT(col_cov_inv_.NumRows() != 0 &&
                    "Empty column covariance for MAP prior");
       WriteToken(out_stream, binary, "<Col_Cov_Inv>");
       if (!binary) out_stream << "\n";
       col_cov_inv_.Write(out_stream, binary);
     }
     // end priors for MAP adaptation
   }
   if (write_params & kSgmmStateParams) {
     WriteToken(out_stream, binary, "<v>");
     for (int32 j = 0; j < num_states; j++) {
       v_[j].Write(out_stream, binary);
     }
     WriteToken(out_stream, binary, "<c>");
     for (int32 j = 0; j < num_states; j++) {
       c_[j].Write(out_stream, binary);
     }
   }
   if (write_params & kSgmmNormalizers) {
     WriteToken(out_stream, binary, "<n>");
     if (n_.empty())
       KALDI_WARN << "Not writing normalizers since they are not present.";
     else
       for (int32 j = 0; j < num_states; j++)
         n_[j].Write(out_stream, binary);
   }
   WriteToken(out_stream, binary, "</SGMM>");
 }
Friends And Related Function Documentation
friend class AmSgmmFunctions friend
Definition at line 329 of file am-sgmm.h.
friend class ComputeNormalizersClass friend
Definition at line 268 of file am-sgmm.h.
friend class EbwAmSgmmUpdater friend
Definition at line 326 of file am-sgmm.h.
friend class MleAmSgmmUpdater friend
Definition at line 327 of file am-sgmm.h.
friend class MleAmSgmmUpdaterMulti friend
Definition at line 330 of file am-sgmm.h.
friend class MleSgmmSpeakerAccs friend
Definition at line 328 of file am-sgmm.h.
Member Data Documentation
std::vector< Vector<BaseFloat> > c_ private
c_{jm}, mixture weights. Dimension is [J][M_{j}]
Definition at line 312 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputeSmoothingTermsFromModel(), AmSgmm::CopyFromSgmm(), AmSgmm::InitializeFromFullGmm(), AmSgmm::InitializeVecs(), AmSgmm::NumPdfs(), AmSgmm::NumSubstates(), AmSgmm::Read(), AmSgmm::SplitSubstates(), EbwAmSgmmUpdater::UpdateSubstateWeights(), MleAmSgmmUpdater::UpdateSubstateWeights(), and AmSgmm::Write().
SpMatrix<BaseFloat> col_cov_inv_ private
Definition at line 323 of file am-sgmm.h.
Referenced by MleAmSgmmUpdater::ComputeMPrior(), MleAmSgmmUpdater::MapUpdateM(), AmSgmm::Read(), and AmSgmm::Write().
DiagGmm diag_ubm_ private
These contain the "background" model associated with the subspace GMM.
Definition at line 290 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmm::ComputeDerivedVars(), AmSgmm::CopyFromSgmm(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::diag_ubm(), AmSgmm::GaussianSelection(), AmSgmm::GaussianSelectionPreselect(), AmSgmm::InitializeFromFullGmm(), AmSgmm::Read(), and AmSgmm::Write().
FullGmm full_ubm_ private
Definition at line 291 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmm::ComputeDerivedVars(), AmSgmm::CopyFromSgmm(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::full_ubm(), AmSgmm::GaussianSelection(), AmSgmm::GaussianSelectionPreselect(), AmSgmm::InitializeCovars(), AmSgmm::InitializeFromFullGmm(), AmSgmm::InitializeMw(), AmSgmm::InitializeN(), AmSgmm::Read(), and AmSgmm::Write().
std::vector< Matrix<BaseFloat> > M_ private
Phonetic-subspace projections. Dimension is [I][D][S].
Definition at line 301 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeH(), MleAmSgmmUpdater::ComputeMPrior(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputePerFrameVars(), MleAmSgmmUpdater::ComputeSMeans(), AmSgmm::CopyFromSgmm(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::FeatureDim(), AmSgmm::GetPhoneProjection(), AmSgmm::GetSubstateMean(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm::InitializeMw(), MleAmSgmmUpdater::MapUpdateM(), AmSgmm::NumGauss(), AmSgmm::Read(), MleAmSgmmUpdater::RenormalizeV(), EbwAmSgmmUpdater::UpdateM(), MleAmSgmmUpdater::UpdateM(), and AmSgmm::Write().
std::vector< Matrix<BaseFloat> > M_prior_ private
Definition at line 321 of file am-sgmm.h.
Referenced by MleAmSgmmUpdater::ComputeMPrior(), MleAmSgmmUpdater::MapUpdateM(), AmSgmm::Read(), and AmSgmm::Write().
std::vector< Matrix<BaseFloat> > N_ private
Speaker-subspace projections. Dimension is [I][D][T].
Definition at line 303 of file am-sgmm.h.
Referenced by AmSgmm::ComputePerSpkDerivedVars(), AmSgmm::CopyFromSgmm(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::GetNtransSigmaInv(), AmSgmm::IncreaseSpkSpaceDim(), AmSgmm::InitializeFromFullGmm(), AmSgmm::InitializeN(), MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), AmSgmm::Read(), AmSgmm::RemoveSpeakerSpace(), MleAmSgmmUpdater::RenormalizeN(), AmSgmm::SpkSpaceDim(), EbwAmSgmmUpdater::UpdateN(), MleAmSgmmUpdater::UpdateN(), and AmSgmm::Write().
std::vector< Matrix<BaseFloat> > n_ private
n_{jim}, per-Gaussian normalizer. Dimension is [J][I][M_{j}]
Definition at line 314 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmm::ComponentPosteriors(), AmSgmm::ComputeDerivedVars(), AmSgmm::ComputeNormalizers(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputePerFrameVars(), AmSgmm::CopyFromSgmm(), AmSgmm::LogLikelihood(), AmSgmm::Read(), AmSgmm::SplitSubstates(), and AmSgmm::Write().
SpMatrix<BaseFloat> row_cov_inv_ private
Definition at line 322 of file am-sgmm.h.
Referenced by MleAmSgmmUpdater::ComputeMPrior(), MleAmSgmmUpdater::MapUpdateM(), AmSgmm::Read(), and AmSgmm::Write().
std::vector< SpMatrix<BaseFloat> > SigmaInv_ private
Globally shared parameters of the subspace GMM.
The various quantities are: I = number of Gaussians, D = data dimension, S = phonetic subspace dimension, T = speaker subspace dimension, J = number of states, M_{j} = number of substates of state j. Inverse within-class (full) covariances; dim is [I][D][D].
Definition at line 299 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeH(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), AmSgmm::ComputePerFrameVars(), AmSgmm::CopyFromSgmm(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::GetInvCovars(), AmSgmm::GetNtransSigmaInv(), AmSgmm::GetVarScaledSubstateSpeakerMean(), AmSgmm::InitializeCovars(), AmSgmm::InitializeFromFullGmm(), MleAmSgmmUpdater::MapUpdateM(), MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), AmSgmm::Read(), EbwAmSgmmUpdater::UpdateM(), MleAmSgmmUpdater::UpdateM(), EbwAmSgmmUpdater::UpdateN(), MleAmSgmmUpdater::UpdateN(), EbwAmSgmmUpdater::UpdateVars(), MleAmSgmmUpdater::UpdateVars(), and AmSgmm::Write().
std::vector< Matrix<BaseFloat> > v_ private
The parameters in a particular SGMM state.
v_{jm}, per-state phonetic-subspace vectors. Dimension is [J][M_{j}][S].
Definition at line 310 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmm::ComponentPosteriors(), AmSgmmFunctions::ComputeDistances(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), EbwAmSgmmUpdater::ComputePhoneVecStats(), MleAmSgmmUpdater::ComputeQ(), MleAmSgmmUpdater::ComputeSMeans(), AmSgmm::ComputeSmoothingTermsFromModel(), AmSgmm::CopyFromSgmm(), AmSgmm::GetSubstateMean(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm::InitializeFromFullGmm(), AmSgmm::InitializeVecs(), AmSgmm::LogLikelihood(), AmSgmm::Read(), MleAmSgmmUpdater::RenormalizeV(), AmSgmm::SplitSubstates(), AmSgmm::StateVectors(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdateWParallel(), MleAmSgmmUpdater::UpdateWParallelGetStats(), MleAmSgmmUpdater::UpdateWSequential(), and AmSgmm::Write().
Matrix<BaseFloat> w_ private
Weight projection vectors. Dimension is [I][S].
Definition at line 305 of file am-sgmm.h.
Referenced by AmSgmm::Check(), AmSgmm::ComputeFmllrPreXform(), AmSgmm::ComputeNormalizersInternal(), AmSgmm::ComputeNormalizersNormalized(), EbwAmSgmmUpdater::ComputePhoneVecStats(), AmSgmm::ComputeSmoothingTermsFromModel(), AmSgmm::CopyFromSgmm(), AmSgmm::CopyGlobalsInitVecs(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm::InitializeFromFullGmm(), AmSgmm::InitializeMw(), AmSgmm::PhoneSpaceDim(), AmSgmm::Read(), MleAmSgmmUpdater::RenormalizeV(), MleAmSgmmUpdater::UpdatePhoneVectorsChecked(), MleAmSgmmUpdater::UpdatePhoneVectorsCheckedFromClusterableInternal(), EbwAmSgmmUpdater::UpdatePhoneVectorsInternal(), MleAmSgmmUpdater::UpdatePhoneVectorsInternal(), EbwAmSgmmUpdater::UpdateWParallel(), MleAmSgmmUpdater::UpdateWParallel(), MleAmSgmmUpdater::UpdateWSequential(), and AmSgmm::Write().
The documentation for this class was generated from the following files:
sgmm/am-sgmm.h
sgmm/am-sgmm.cc