Kaldi: ForwardingDescriptor Class Reference
ForwardingDescriptor Class Reference abstract
#include <nnet-descriptor.h>
Public Member Functions
virtual Cindex MapToInput (const Index &output) const =0
virtual int32 Dim (const Nnet &nnet) const =0
virtual ForwardingDescriptor * Copy () const =0
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const =0
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const =0
This function appends to "node_indexes" all the node indexes.
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (ForwardingDescriptor)
Detailed Description
Definition at line 94 of file nnet-descriptor.h.
Constructor & Destructor Documentation
virtual ~ForwardingDescriptor () inline virtual
Definition at line 122 of file nnet-descriptor.h.
 { }
ForwardingDescriptor () inline
Definition at line 123 of file nnet-descriptor.h.
 { }
Member Function Documentation
virtual ForwardingDescriptor* Copy () const pure virtual
Implemented in ReplaceIndexForwardingDescriptor, RoundingForwardingDescriptor, SwitchingForwardingDescriptor, OffsetForwardingDescriptor, and SimpleForwardingDescriptor.
Referenced by OffsetForwardingDescriptor::Copy(), RoundingForwardingDescriptor::Copy(), ReplaceIndexForwardingDescriptor::Copy(), and SimpleSumDescriptor::Copy().
virtual int32 Dim (const Nnet & nnet) const pure virtual
Implemented in ReplaceIndexForwardingDescriptor, RoundingForwardingDescriptor, SwitchingForwardingDescriptor, OffsetForwardingDescriptor, and SimpleForwardingDescriptor.
Referenced by OffsetForwardingDescriptor::Dim(), RoundingForwardingDescriptor::Dim(), ReplaceIndexForwardingDescriptor::Dim(), and SimpleSumDescriptor::Dim().
virtual void GetNodeDependencies (std::vector< int32 > * node_indexes) const pure virtual
This function appends to "node_indexes" all the node indexes.
Implemented in ReplaceIndexForwardingDescriptor, RoundingForwardingDescriptor, SwitchingForwardingDescriptor, OffsetForwardingDescriptor, and SimpleForwardingDescriptor.
Referenced by OffsetForwardingDescriptor::GetNodeDependencies(), RoundingForwardingDescriptor::GetNodeDependencies(), ReplaceIndexForwardingDescriptor::GetNodeDependencies(), and SimpleSumDescriptor::GetNodeDependencies().
KALDI_DISALLOW_COPY_AND_ASSIGN (ForwardingDescriptor) private
virtual Cindex MapToInput (const Index & output) const pure virtual
Implemented in ReplaceIndexForwardingDescriptor, RoundingForwardingDescriptor, SwitchingForwardingDescriptor, OffsetForwardingDescriptor, and SimpleForwardingDescriptor.
Referenced by SimpleSumDescriptor::GetDependencies(), SimpleSumDescriptor::IsComputable(), OffsetForwardingDescriptor::MapToInput(), RoundingForwardingDescriptor::MapToInput(), and ReplaceIndexForwardingDescriptor::MapToInput().
virtual int32 Modulus () const inline virtual
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
It returns the smallest modulus to which this descriptor is invariant; the lowest common multiple of all descriptors in the network gives you the modulus for the whole network.
Reimplemented in RoundingForwardingDescriptor, SwitchingForwardingDescriptor, and OffsetForwardingDescriptor.
Definition at line 111 of file nnet-descriptor.h.
Referenced by OffsetForwardingDescriptor::Modulus(), and SimpleSumDescriptor::Modulus().
 { return 1; }
virtual void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const pure virtual
Implemented in ReplaceIndexForwardingDescriptor, RoundingForwardingDescriptor, SwitchingForwardingDescriptor, OffsetForwardingDescriptor, and SimpleForwardingDescriptor.
Referenced by OffsetForwardingDescriptor::WriteConfig(), RoundingForwardingDescriptor::WriteConfig(), ReplaceIndexForwardingDescriptor::WriteConfig(), and SimpleSumDescriptor::WriteConfig().
The documentation for this class was generated from the following file:
nnet3/nnet-descriptor.h