Kaldi: LinearTransform Class Reference
LinearTransform Class Reference
#include <nnet-linear-transform.h>
Public Member Functions
LinearTransform (int32 dim_in, int32 dim_out)
~LinearTransform ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
const CuMatrixBase< BaseFloat > & GetLinearity ()
Accessors to the component parameters.
void SetLinearity (const CuMatrixBase< BaseFloat > &linearity)
const CuMatrixBase< BaseFloat > & GetLinearityCorr ()
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Sets the training options to the component.
const NnetTrainOptions & GetTrainOptions () const
Gets the training options from the component.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
Private Attributes
CuMatrix< BaseFloat > linearity_
CuMatrix< BaseFloat > linearity_corr_
BaseFloat learn_rate_coef_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Definition at line 32 of file nnet-linear-transform.h.
Constructor & Destructor Documentation
LinearTransform (int32 dim_in, int32 dim_out) inline
Definition at line 34 of file nnet-linear-transform.h.
Referenced by LinearTransform::Copy().
     : UpdatableComponent(dim_in, dim_out),
       linearity_(dim_out, dim_in), linearity_corr_(dim_out, dim_in), learn_rate_coef_(1.0)
   { }
~LinearTransform () inline
Definition at line 38 of file nnet-linear-transform.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 125 of file nnet-linear-transform.h.
References CuMatrixBase< Real >::AddMatMat(), kaldi::kNoTrans, and LinearTransform::linearity_.
{
     // multiply error derivative by weights
     in_diff->AddMatMat(1.0, out_diff, kNoTrans, linearity_, kNoTrans, 0.0);
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 41 of file nnet-linear-transform.h.
References LinearTransform::LinearTransform().
 { return new LinearTransform(*this); }
const CuMatrixBase<BaseFloat>& GetLinearity () inline
Accessors to the component parameters.
Definition at line 155 of file nnet-linear-transform.h.
References LinearTransform::linearity_.
{
     return linearity_;
   }
const CuMatrixBase<BaseFloat>& GetLinearityCorr () inline
Definition at line 165 of file nnet-linear-transform.h.
References LinearTransform::linearity_corr_.
{
     return linearity_corr_;
   }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 106 of file nnet-linear-transform.h.
References LinearTransform::linearity_, CuMatrixBase< Real >::NumCols(), LinearTransform::NumParams(), CuMatrixBase< Real >::NumRows(), VectorBase< Real >::Range(), and Vector< Real >::Resize().
{
     wei_copy->Resize(NumParams());
     int32 linearity_num_elem = linearity_.NumRows() * linearity_.NumCols();
     wei_copy->Range(0,linearity_num_elem).CopyRowsFromMat(Matrix<BaseFloat>(linearity_));
   }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 42 of file nnet-linear-transform.h.
References Component::kLinearTransform.
 { return kLinearTransform; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 112 of file nnet-linear-transform.h.
References LinearTransform::linearity_, and kaldi::nnet1::MomentStatistics().
{
     return std::string("\n  linearity") + MomentStatistics(linearity_);
   }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 115 of file nnet-linear-transform.h.
References LinearTransform::learn_rate_coef_, LinearTransform::linearity_corr_, kaldi::nnet1::MomentStatistics(), and kaldi::nnet1::ToString().
{
     return std::string("\n  linearity_grad") + MomentStatistics(linearity_corr_) +
            ", lr-coef " + ToString(learn_rate_coef_);
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 44 of file nnet-linear-transform.h.
References Input::Close(), Component::input_dim_, KALDI_ASSERT, KALDI_ERR, KALDI_LOG, LinearTransform::learn_rate_coef_, LinearTransform::linearity_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, kaldi::RandGauss(), CuMatrix< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), CuMatrix< Real >::Resize(), and Input::Stream().
{
     // define options
     float param_stddev = 0.1;
     float learn_rate_coef = 1.0;
     std::string read_matrix_file;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<ParamStddev>") ReadBasicType(is, false, &param_stddev);
       else if (token == "<LearnRateCoef>") ReadBasicType(is, false, &learn_rate_coef);
       else if (token == "<ReadMatrix>") ReadToken(is, false, &read_matrix_file);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                      << " (ParamStddev|ReadMatrix|LearnRateCoef)";
       is >> std::ws; // eat-up whitespace
     }
     //
     // initialize
     //
     if (read_matrix_file != "") { // load from file,
       bool binary;
       Input in(read_matrix_file, &binary);
       linearity_.Read(in.Stream(), binary);
       in.Close();
       KALDI_LOG << "Loaded <LinearTransform> matrix from file : " << read_matrix_file;
     } else { // random initialization,
       linearity_.Resize(output_dim_, input_dim_);
       for (int32 r=0; r<output_dim_; r++) {
         for (int32 c=0; c<input_dim_; c++) {
           linearity_(r,c) = param_stddev * RandGauss(); // 0-mean Gauss with given std_dev
         }
       }
     }
     //
     learn_rate_coef_ = learn_rate_coef;
     //
     // check dims,
     KALDI_ASSERT(linearity_.NumRows() == output_dim_);
     KALDI_ASSERT(linearity_.NumCols() == input_dim_);
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 104 of file nnet-linear-transform.h.
References LinearTransform::linearity_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by LinearTransform::GetParams().
 { return linearity_.NumRows()*linearity_.NumCols(); }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 120 of file nnet-linear-transform.h.
References CuMatrixBase< Real >::AddMatMat(), kaldi::kNoTrans, kaldi::kTrans, and LinearTransform::linearity_.
{
     // multiply by weights^t
     out->AddMatMat(1.0, in, kNoTrans, linearity_, kTrans, 0.0);
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 87 of file nnet-linear-transform.h.
References kaldi::ExpectToken(), Component::input_dim_, KALDI_ASSERT, LinearTransform::learn_rate_coef_, LinearTransform::linearity_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, CuMatrix< Real >::Read(), and kaldi::ReadBasicType().
{
     // learning-rate coefficien
     ExpectToken(is, binary, "<LearnRateCoef>");
     ReadBasicType(is, binary, &learn_rate_coef_);
     // weights
     linearity_.Read(is, binary);
     KALDI_ASSERT(linearity_.NumRows() == output_dim_);
     KALDI_ASSERT(linearity_.NumCols() == input_dim_);
   }
void SetLinearity (const CuMatrixBase< BaseFloat > & linearity) inline
Definition at line 159 of file nnet-linear-transform.h.
References CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, LinearTransform::linearity_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
     KALDI_ASSERT(linearity.NumRows() == linearity_.NumRows());
     KALDI_ASSERT(linearity.NumCols() == linearity_.NumCols());
     linearity_.CopyFromMat(linearity);
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 132 of file nnet-linear-transform.h.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::AddMatMat(), kaldi::kNoTrans, kaldi::kTrans, NnetTrainOptions::l1_penalty, NnetTrainOptions::l2_penalty, NnetTrainOptions::learn_rate, LinearTransform::learn_rate_coef_, LinearTransform::linearity_, LinearTransform::linearity_corr_, NnetTrainOptions::momentum, CuMatrixBase< Real >::NumRows(), UpdatableComponent::opts_, and kaldi::cu::RegularizeL1().
{
     // we use following hyperparameters from the option class
     const BaseFloat lr = opts_.learn_rate;
     const BaseFloat mmt = opts_.momentum;
     const BaseFloat l2 = opts_.l2_penalty;
     const BaseFloat l1 = opts_.l1_penalty;
     // we will also need the number of frames in the mini-batch
     const int32 num_frames = input.NumRows();
     // compute gradient (incl. momentum)
     linearity_corr_.AddMatMat(1.0, diff, kTrans, input, kNoTrans, mmt);
     // l2 regularization
     if (l2 != 0.0) {
       linearity_.AddMat(-lr*l2*num_frames, linearity_);
     }
     // l1 regularization
     if (l1 != 0.0) {
       cu::RegularizeL1(&linearity_, &linearity_corr_, lr*l1*num_frames, lr);
     }
     // update
     linearity_.AddMat(-lr*learn_rate_coef_, linearity_corr_);
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 98 of file nnet-linear-transform.h.
References LinearTransform::learn_rate_coef_, LinearTransform::linearity_, CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<LearnRateCoef>");
     WriteBasicType(os, binary, learn_rate_coef_);
     linearity_.Write(os, binary);
   }
Member Data Documentation
BaseFloat learn_rate_coef_ private
Definition at line 174 of file nnet-linear-transform.h.
Referenced by LinearTransform::InfoGradient(), LinearTransform::InitData(), LinearTransform::ReadData(), LinearTransform::Update(), and LinearTransform::WriteData().
CuMatrix<BaseFloat> linearity_ private
Definition at line 171 of file nnet-linear-transform.h.
Referenced by LinearTransform::BackpropagateFnc(), LinearTransform::GetLinearity(), LinearTransform::GetParams(), LinearTransform::Info(), LinearTransform::InitData(), LinearTransform::NumParams(), LinearTransform::PropagateFnc(), LinearTransform::ReadData(), LinearTransform::SetLinearity(), LinearTransform::Update(), and LinearTransform::WriteData().
CuMatrix<BaseFloat> linearity_corr_ private
Definition at line 172 of file nnet-linear-transform.h.
Referenced by LinearTransform::GetLinearityCorr(), LinearTransform::InfoGradient(), and LinearTransform::Update().
The documentation for this class was generated from the following file:
nnet/nnet-linear-transform.h