Kaldi: TpMatrix< Real > Class Template Reference
TpMatrix< Real > Class Template Reference
%Matrix and vector classes
Packed symetric matrix class.
#include <matrix-common.h>
Public Member Functions
TpMatrix ()
TpMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
TpMatrix (const TpMatrix< Real > &orig)
TpMatrix (const CuTpMatrix< Real > &cu)
Copy constructor from CUDA TpMatrix This is defined in ../cudamatrix/cu-tp-matrix.cc.
template<typename OtherReal >
TpMatrix (const TpMatrix< OtherReal > &orig)
Real operator() (MatrixIndexT r, MatrixIndexT c) const
Real & operator() (MatrixIndexT r, MatrixIndexT c)
void Cholesky (const SpMatrix< Real > &orig)
void Invert ()
void InvertDouble ()
void Swap (TpMatrix< Real > *other)
Shallow swap.
Real Determinant ()
Returns the determinant of the matrix (product of diagonals)
void CopyFromMat (const MatrixBase< Real > &M, MatrixTransposeType Trans=kNoTrans)
CopyFromMat copies the lower triangle of M into *this (or the upper triangle, if Trans == kTrans).
void CopyFromMat (const CuTpMatrix< Real > &other)
This is implemented in ../cudamatrix/cu-tp-matrix.cc.
void CopyFromTp (const TpMatrix< Real > &other)
CopyFromTp copies another triangular matrix into this one.
template<typename OtherReal >
void CopyFromTp (const TpMatrix< OtherReal > &other)
void AddTp (const Real alpha, const TpMatrix< Real > &M)
AddTp does *this += alpha * M.
TpMatrix< Real > & operator= (const TpMatrix< Real > &other)
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type=kSetZero)
Public Member Functions inherited from PackedMatrix< Real >
PackedMatrix ()
PackedMatrix (MatrixIndexT r, MatrixResizeType resize_type=kSetZero)
PackedMatrix (const PackedMatrix< Real > &orig)
template<typename OtherReal >
PackedMatrix (const PackedMatrix< OtherReal > &orig)
void SetZero ()
void SetUnit ()
< Set to zero
void SetRandn ()
< Set to unit matrix.
Real Trace () const
< Set to random values of a normal distribution
PackedMatrix< Real > & operator= (const PackedMatrix< Real > &other)
~PackedMatrix ()
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type=kSetZero)
Set packed matrix to a specified size (can be zero).
void AddToDiag (const Real r)
void ScaleDiag (const Real alpha)
void SetDiag (const Real alpha)
template<typename OtherReal >
void CopyFromPacked (const PackedMatrix< OtherReal > &orig)
template<typename OtherReal >
void CopyFromVec (const SubVector< OtherReal > &orig)
CopyFromVec just interprets the vector as having the same layout as the packed matrix.
Real * Data ()
const Real * Data () const
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
size_t SizeInBytes () const
Real operator() (MatrixIndexT r, MatrixIndexT c) const
Real & operator() (MatrixIndexT r, MatrixIndexT c)
Real Max () const
Real Min () const
void Scale (Real c)
void Read (std::istream &in, bool binary, bool add=false)
void Write (std::ostream &out, bool binary) const
void Destroy ()
void Swap (PackedMatrix< Real > *other)
Swaps the contents of *this and *other. Shallow swap.
void Swap (Matrix< Real > *other)
Friends
class CuTpMatrix< float >
class CuTpMatrix< double >
Additional Inherited Members
Protected Member Functions inherited from PackedMatrix< Real >
void AddPacked (const Real alpha, const PackedMatrix< Real > &M)
Protected Attributes inherited from PackedMatrix< Real >
Real * data_
MatrixIndexT num_rows_
Detailed Description
template<typename Real>
class kaldi::TpMatrix< Real >
Packed symetric matrix class.
Definition at line 55 of file matrix-common.h.
Constructor & Destructor Documentation
TpMatrix () inline
Definition at line 40 of file tp-matrix.h.
 : PackedMatrix<Real>() {}
TpMatrix (MatrixIndexT r, MatrixResizeType resize_type = kSetZero) inline explicit
Definition at line 41 of file tp-matrix.h.
       : PackedMatrix<Real>(r, resize_type) {}
TpMatrix (const TpMatrix< Real > & orig) inline
Definition at line 43 of file tp-matrix.h.
 : PackedMatrix<Real>(orig) {}
TpMatrix (const CuTpMatrix< Real > & cu) explicit
Copy constructor from CUDA TpMatrix This is defined in ../cudamatrix/cu-tp-matrix.cc.
Definition at line 112 of file cu-tp-matrix.cc.
References CuPackedMatrix< Real >::NumRows().
{
   this->Resize(cu.NumRows());
   this->CopyFromMat(cu);
 }
TpMatrix (const TpMatrix< OtherReal > & orig) inline explicit
Definition at line 50 of file tp-matrix.h.
       : PackedMatrix<Real>(orig) {}
Member Function Documentation
void AddTp (const Real alpha, const TpMatrix< Real > & M) inline
AddTp does *this += alpha * M.
Definition at line 113 of file tp-matrix.h.
{
     this->AddPacked(alpha, M);
   }
void Cholesky (const SpMatrix< Real > & orig)
Definition at line 88 of file tp-matrix.cc.
References kaldi::cblas_Xdot(), rnnlm::d, PackedMatrix< Real >::Data(), rnnlm::j, KALDI_ASSERT, KALDI_WARN, rnnlm::n, PackedMatrix< Real >::NumRows(), and kaldi::nnet3::SetZero().
Referenced by SpMatrix< Real >::ApplyFloor(), CuMatrixBase< Real >::Cholesky(), kaldi::CholeskyUnitTestTr(), IvectorExtractorStats::CommitStatsForW(), Fmpe::ComputeC(), kaldi::ComputeFeatureNormalizer(), kaldi::ComputeFeatureNormalizingTransform(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), Sgmm2Project::ComputeLdaTransform(), kaldi::ComputeNormalizingTransform(), FastNnetCombiner::ComputePreconditioner(), LdaEstimate::Estimate(), BasisFmllrEstimate::EstimateFmllrBasis(), FeatureTransformEstimate::EstimateInternal(), SpMatrix< Real >::IsPosDef(), SpMatrix< Real >::LogPosDefDet(), main(), SgmmClusterable::Objf(), FullGmm::Perturb(), CompressedAffineXformStats::PrepareOneG(), rand_posdef_spmatrix(), kaldi::unittest::RandPosdefSpMatrix(), RandPosdefSpMatrix(), kaldi::RandPosdefSpMatrix(), MleAmSgmmUpdaterMulti::RenormalizeV(), MleAmSgmm2Updater::RenormalizeV(), MleAmSgmmUpdater::RenormalizeV(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), kaldi::SolveDoubleQuadraticMatrixProblem(), FullGmm::Split(), CuMatrixBase< Real >::SymInvertPosDef(), kaldi::UnitTestCuTpMatrixCholesky(), kaldi::UnitTestPldaEstimation(), and PldaUnsupervisedAdaptor::UpdatePlda().
{
   KALDI_ASSERT(orig.NumRows() == this->NumRows());
   MatrixIndexT n = this->NumRows();
   this->SetZero();
   Real *data = this->data_, *jdata = data;  // start of j'th row of matrix.
   const Real *orig_jdata = orig.Data(); // start of j'th row of matrix.
   for (MatrixIndexT j = 0; j < n; j++, jdata += j, orig_jdata += j) {
     Real *kdata = data; // start of k'th row of matrix.
     Real d(0.0);
     for (MatrixIndexT k = 0; k < j; k++, kdata += k) {
       Real s = cblas_Xdot(k, kdata, 1, jdata, 1);
       // (*this)(j, k) = s = (orig(j, k) - s)/(*this)(k, k);
       jdata[k] = s = (orig_jdata[k] - s)/kdata[k];
       d = d + s*s;
     }
     // d = orig(j, j) - d;
     d = orig_jdata[j] - d;
     if (d >= 0.0) {
       // (*this)(j, j) = std::sqrt(d);
       jdata[j] = std::sqrt(d);
     } else {
       KALDI_WARN << "Cholesky decomposition failed. Maybe matrix "
           "is not positive definite. Throwing error";
       throw std::runtime_error("Cholesky decomposition failed.");
     }
   }
 }
void CopyFromMat (const MatrixBase< Real > & M, MatrixTransposeType Trans = kNoTrans)
CopyFromMat copies the lower triangle of M into *this (or the upper triangle, if Trans == kTrans).
Definition at line 118 of file tp-matrix.cc.
References MatrixBase< Real >::Data(), rnnlm::i, rnnlm::j, KALDI_ASSERT, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and MatrixBase< Real >::Stride().
Referenced by kaldi::UnitTestCuTpMatrixCopyFromMat(), and kaldi::UnitTestSymAddMat2().
{
   if (Trans == kNoTrans) {
     KALDI_ASSERT(this->NumRows() == M.NumRows() && M.NumRows() == M.NumCols());
     MatrixIndexT D = this->NumRows();
     const Real *in_i = M.Data();
     MatrixIndexT stride = M.Stride();
     Real *out_i = this->data_;
     for (MatrixIndexT i = 0; i < D; i++, in_i += stride, out_i += i)
       for (MatrixIndexT j = 0; j <= i; j++)
         out_i[j] = in_i[j];
   } else {
     KALDI_ASSERT(this->NumRows() == M.NumRows() && M.NumRows() == M.NumCols());
     MatrixIndexT D = this->NumRows();
     const Real *in_i = M.Data();
     MatrixIndexT stride = M.Stride();
     Real *out_i = this->data_;
     for (MatrixIndexT i = 0; i < D; i++, in_i++, out_i += i) {
       for (MatrixIndexT j = 0; j <= i; j++)
         out_i[j] = in_i[stride*j];
     }
   }
 }
void CopyFromMat (const CuTpMatrix< Real > & other)
This is implemented in ../cudamatrix/cu-tp-matrix.cc.
Definition at line 120 of file cu-tp-matrix.cc.
References CuPackedMatrix< Real >::CopyToPacked().
{
   other.CopyToPacked(this);
 }
void CopyFromTp (const TpMatrix< Real > & other) inline
CopyFromTp copies another triangular matrix into this one.
Definition at line 104 of file tp-matrix.h.
Referenced by Fmpe::ComputeC(), FeatureTransformEstimate::EstimateInternal(), and kaldi::UnitTestTpInvert().
{
     PackedMatrix<Real>::CopyFromPacked(other);
   }
void CopyFromTp (const TpMatrix< OtherReal > & other) inline
Definition at line 108 of file tp-matrix.h.
{
     PackedMatrix<Real>::CopyFromPacked(other);
   }
Real Determinant ()
Returns the determinant of the matrix (product of diagonals)
Definition at line 71 of file tp-matrix.cc.
References rnnlm::i.
{
   double   det = 1.0;
   for (MatrixIndexT i = 0; i<this->NumRows(); i++) {
     det *= (*this)(i, i);
   }
   return static_cast<Real>(det);
 }
void Invert ()
Definition at line 31 of file tp-matrix.cc.
References kaldi::clapack_Xtptri(), and KALDI_ERR.
Referenced by SpMatrix< Real >::ApplyFloor(), CuMatrixBase< Real >::Cholesky(), kaldi::CholeskyUnitTestTr(), Sgmm2Project::ComputeLdaTransform(), kaldi::ComputeNormalizingTransform(), FastNnetCombiner::ComputePreconditioner(), TpMatrix< BaseFloat >::InvertDouble(), main(), MleAmSgmmUpdaterMulti::RenormalizeV(), MleAmSgmm2Updater::RenormalizeV(), MleAmSgmmUpdater::RenormalizeV(), OnlineNaturalGradient::ReorthogonalizeXt1(), OnlinePreconditioner::ReorthogonalizeXt1(), kaldi::SolveDoubleQuadraticMatrixProblem(), kaldi::UnitTestPldaEstimation(), kaldi::UnitTestTpInvert(), and PldaUnsupervisedAdaptor::UpdatePlda().
{
   // these are CLAPACK types
   KaldiBlasInt result;
   KaldiBlasInt rows = static_cast<int>(this->num_rows_);
   // clapack call
   // NOTE: Even though "U" is for upper, lapack assumes column-wise storage
   // of the data. We have a row-wise storage, therefore, we need to "invert"
   clapack_Xtptri(&rows, this->data_, &result);
   if (result < 0) {
     KALDI_ERR << "Call to CLAPACK stptri_ function failed";
   } else if (result > 0) {
     KALDI_ERR << "Matrix is singular";
   }
 }
void InvertDouble () inline
Definition at line 83 of file tp-matrix.h.
Referenced by kaldi::ComputeFeatureNormalizer(), kaldi::ComputeFeatureNormalizingTransform(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), and BasisFmllrEstimate::EstimateFmllrBasis().
                       {
     TpMatrix<double> dmat(*this);
     dmat.Invert();
     (*this).CopyFromTp(dmat);
   }
Real operator() (MatrixIndexT r, MatrixIndexT c) const inline
Definition at line 53 of file tp-matrix.h.
{
     if (static_cast<UnsignedMatrixIndexT>(c) >
         static_cast<UnsignedMatrixIndexT>(r)) {
       KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(c) <
                    static_cast<UnsignedMatrixIndexT>(this->num_rows_));
       return 0;
     }
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                  static_cast<UnsignedMatrixIndexT>(this->num_rows_));
     // c<=r now so don't have to check c.
     return *(this->data_ + (r*(r+1)) / 2 + c);
     // Duplicating code from PackedMatrix.h
   }
Real& operator() (MatrixIndexT r, MatrixIndexT c) inline
Definition at line 67 of file tp-matrix.h.
{
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(r) <
                  static_cast<UnsignedMatrixIndexT>(this->num_rows_));
     KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(c) <=
                  static_cast<UnsignedMatrixIndexT>(r) &&
                  "you cannot access the upper triangle of TpMatrix using "
                  "a non-const matrix object.");
     return *(this->data_ + (r*(r+1)) / 2 + c);
     // Duplicating code from PackedMatrix.h
   }
TpMatrix<Real>& operator= (const TpMatrix< Real > & other) inline
Definition at line 117 of file tp-matrix.h.
{
     PackedMatrix<Real>::operator=(other);
     return *this;
   }
void Resize (MatrixIndexT nRows, MatrixResizeType resize_type = kSetZero) inline
Definition at line 124 of file tp-matrix.h.
Referenced by Fmpe::ComputeC(), FastNnetCombiner::ComputePreconditioner(), and FeatureTransformEstimate::EstimateInternal().
{
     PackedMatrix<Real>::Resize(nRows, resize_type);
   }
void Swap (TpMatrix< Real > * other)
Shallow swap.
Definition at line 81 of file tp-matrix.cc.
References PackedMatrix< Real >::data_, PackedMatrix< Real >::num_rows_, and kaldi::swap().
{
   std::swap(this->data_, other->data_);
   std::swap(this->num_rows_, other->num_rows_);
 }
Friends And Related Function Documentation
friend class CuTpMatrix< double > friend
Definition at line 38 of file tp-matrix.h.
friend class CuTpMatrix< float > friend
Definition at line 37 of file tp-matrix.h.
The documentation for this class was generated from the following files:
matrix/matrix-common.h
matrix/tp-matrix.h
matrix/tp-matrix.cc
cudamatrix/cu-tp-matrix.cc