Kaldi: DecodableMatrixMappedOffset Class Reference
DecodableMatrixMappedOffset Class Reference
This decodable class returns log-likes stored in a matrix; it supports repeatedly writing to the matrix and setting a time-offset representing the frame-index of the first row of the matrix.
#include <decodable-matrix.h>
Public Member Functions
DecodableMatrixMappedOffset (const TransitionModel &tm)
virtual int32 NumFramesReady ()
int32 FirstAvailableFrame ()
void AcceptLoglikes (Matrix< BaseFloat > *loglikes, int32 frames_to_discard)
void InputIsFinished ()
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual BaseFloat LogLikelihood (int32 frame, int32 tid)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
virtual ~DecodableMatrixMappedOffset ()
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableMatrixMappedOffset)
Private Attributes
const TransitionModel & trans_model_
Matrix< BaseFloat > loglikes_
int32 frame_offset_
bool input_is_finished_
Detailed Description
This decodable class returns log-likes stored in a matrix; it supports repeatedly writing to the matrix and setting a time-offset representing the frame-index of the first row of the matrix.
It's intended for use in multi-threaded decoding; mutex and semaphores are not included. External code will call SetLoglikes() each time more log-likelihods are available. If you try to access a log-likelihood that's no longer available because the frame index is less than the current offset, it is of course an error.
Definition at line 95 of file decodable-matrix.h.
Constructor & Destructor Documentation
DecodableMatrixMappedOffset (const TransitionModel & tm) inline
Definition at line 97 of file decodable-matrix.h.
                                                         :
       trans_model_(tm), frame_offset_(0), input_is_finished_(false) { }
virtual ~DecodableMatrixMappedOffset () inline virtual
Definition at line 159 of file decodable-matrix.h.
 { }
Member Function Documentation
void AcceptLoglikes (Matrix< BaseFloat > * loglikes, int32 frames_to_discard) inline
Definition at line 115 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::frame_offset_, KALDI_ASSERT, DecodableMatrixMappedOffset::loglikes_, MatrixBase< Real >::NumCols(), TransitionModel::NumPdfs(), MatrixBase< Real >::NumRows(), Matrix< Real >::Resize(), MatrixBase< Real >::RowRange(), Matrix< Real >::Swap(), and DecodableMatrixMappedOffset::trans_model_.
{
     if (loglikes->NumRows() == 0) return;
     KALDI_ASSERT(loglikes->NumCols() == trans_model_.NumPdfs());
     KALDI_ASSERT(frames_to_discard <= loglikes_.NumRows() &&
                  frames_to_discard >= 0);
     if (frames_to_discard == loglikes_.NumRows()) {
       loglikes_.Swap(loglikes);
       loglikes->Resize(0, 0);
     } else {
       int32 old_rows_kept = loglikes_.NumRows() - frames_to_discard,
           new_num_rows = old_rows_kept + loglikes->NumRows();
       Matrix<BaseFloat> new_loglikes(new_num_rows, loglikes->NumCols());
       new_loglikes.RowRange(0, old_rows_kept).CopyFromMat(
           loglikes_.RowRange(frames_to_discard, old_rows_kept));
       new_loglikes.RowRange(old_rows_kept, loglikes->NumRows()).CopyFromMat(
           *loglikes);
       loglikes_.Swap(&new_loglikes);
     }
     frame_offset_ += frames_to_discard;
   }
int32 FirstAvailableFrame () inline
Definition at line 105 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::frame_offset_.
 { return frame_offset_; }
void InputIsFinished () inline
Definition at line 137 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::input_is_finished_.
 { input_is_finished_ = true; }
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frames are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). Caution: the behavior of this function in an online setting is being changed somewhat. In future it may return false in cases where we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. The plan in future is to rely more on NumFramesReady(), and in future, IsLastFrame() would always return false in an online-decoding setting, and would only return true in a decoding-from-matrix setting where we want to allow the last delta or LDA features to be flushed out for compatibility with the baseline setup.
Implements DecodableInterface.
Definition at line 143 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::input_is_finished_, KALDI_ASSERT, and DecodableMatrixMappedOffset::NumFramesReady().
{
     KALDI_ASSERT(frame < NumFramesReady());
     return (frame == NumFramesReady() - 1 && input_is_finished_);
   }
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableMatrixMappedOffset) private
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Implements DecodableInterface.
Definition at line 148 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::frame_offset_, KALDI_ASSERT, DecodableMatrixMappedOffset::loglikes_, MatrixBase< Real >::NumRows(), DecodableMatrixMappedOffset::trans_model_, and TransitionModel::TransitionIdToPdf().
{
     int32 index = frame - frame_offset_;
     KALDI_ASSERT(index >= 0 && index < loglikes_.NumRows());
     return loglikes_(index, trans_model_.TransitionIdToPdf(tid));
   }
virtual int32 NumFramesReady () inline virtual
Definition at line 102 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::frame_offset_, DecodableMatrixMappedOffset::loglikes_, and MatrixBase< Real >::NumRows().
Referenced by DecodableMatrixMappedOffset::IsLastFrame().
 { return frame_offset_ + loglikes_.NumRows(); }
virtual int32 NumFramesReady () const inline virtual
The call NumFramesReady() will return the number of frames currently available for this decodable object.
This is for use in setups where you don't want the decoder to block while waiting for input. This is newly added as of Jan 2014, and I hope, going forward, to rely on this mechanism more than IsLastFrame to know when to stop decoding.
Reimplemented from DecodableInterface.
Definition at line 139 of file decodable-matrix.h.
References DecodableMatrixMappedOffset::frame_offset_, DecodableMatrixMappedOffset::loglikes_, and MatrixBase< Real >::NumRows().
{
     return loglikes_.NumRows() + frame_offset_;
   }
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst.
Implements DecodableInterface.
Definition at line 156 of file decodable-matrix.h.
References TransitionModel::NumTransitionIds(), and DecodableMatrixMappedOffset::trans_model_.
 { return trans_model_.NumTransitionIds(); }
Member Data Documentation
int32 frame_offset_ private
Definition at line 163 of file decodable-matrix.h.
Referenced by DecodableMatrixMappedOffset::AcceptLoglikes(), DecodableMatrixMappedOffset::FirstAvailableFrame(), DecodableMatrixMappedOffset::LogLikelihood(), and DecodableMatrixMappedOffset::NumFramesReady().
bool input_is_finished_ private
Definition at line 164 of file decodable-matrix.h.
Referenced by DecodableMatrixMappedOffset::InputIsFinished(), and DecodableMatrixMappedOffset::IsLastFrame().
Matrix<BaseFloat> loglikes_ private
Definition at line 162 of file decodable-matrix.h.
Referenced by DecodableMatrixMappedOffset::AcceptLoglikes(), DecodableMatrixMappedOffset::LogLikelihood(), and DecodableMatrixMappedOffset::NumFramesReady().
const TransitionModel& trans_model_ private
Definition at line 161 of file decodable-matrix.h.
Referenced by DecodableMatrixMappedOffset::AcceptLoglikes(), DecodableMatrixMappedOffset::LogLikelihood(), and DecodableMatrixMappedOffset::NumIndices().
The documentation for this class was generated from the following file:
decoder/decodable-matrix.h