Kaldi: PerElementOffsetComponent Class Reference
PerElementOffsetComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
PerElementOffsetComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
PerElementOffsetComponent (const PerElementOffsetComponent &other)
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev)
void Init (std::string vector_filename)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Protected Member Functions
const PerElementOffsetComponent & operator= (const PerElementOffsetComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
CuVector< BaseFloat > offsets_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Definition at line 1124 of file nnet-simple-component.h.
Constructor & Destructor Documentation
PerElementOffsetComponent () inline
Definition at line 1132 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Copy().
 { } // use Init to really initialize.
PerElementOffsetComponent (const PerElementOffsetComponent & other) explicit
Definition at line 1812 of file nnet-simple-component.cc.
                                                :
     UpdatableComponent(component),
     offsets_(component.offsets_) { }
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from Component.
Definition at line 1804 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddVec(), KALDI_ASSERT, and PerElementOffsetComponent::offsets_.
{
   const PerElementOffsetComponent *other =
       dynamic_cast<const PerElementOffsetComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   offsets_.AddVec(alpha, other->offsets_);
 }
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 1903 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::CopyFromMat(), UpdatableComponent::learning_rate_, and PerElementOffsetComponent::offsets_.
{
   PerElementOffsetComponent *to_update =
       dynamic_cast<PerElementOffsetComponent*>(to_update_in);
   if (in_deriv) {
     // Propagate the derivative back to the input.
     in_deriv->CopyFromMat(out_deriv);
   }
   if (to_update != NULL)
     to_update->offsets_.AddRowSumMat(to_update->learning_rate_, out_deriv);
 }
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 1841 of file nnet-simple-component.cc.
References UpdatableComponent::is_gradient_, UpdatableComponent::learning_rate_, PerElementOffsetComponent::offsets_, and PerElementOffsetComponent::PerElementOffsetComponent().
{
   PerElementOffsetComponent *ans = new PerElementOffsetComponent();
   ans->learning_rate_ = learning_rate_;
   ans->offsets_ = offsets_;
   ans->is_gradient_ = is_gradient_;
   return ans;
 }
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 1849 of file nnet-simple-component.cc.
References PerElementOffsetComponent::offsets_, and kaldi::VecVec().
{
   const PerElementOffsetComponent *other =
       dynamic_cast<const PerElementOffsetComponent*>(&other_in);
   return VecVec(offsets_, other->offsets_);
 }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 1832 of file nnet-simple-component.cc.
References UpdatableComponent::Info(), CuVectorBase< Real >::Max(), CuVectorBase< Real >::Min(), PerElementOffsetComponent::offsets_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info()
          << ", offsets-min=" << offsets_.Min()
          << ", offsets-max=" << offsets_.Max();
   PrintParameterStats(stream, "offsets", offsets_, true);
   return stream.str();
 }
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev)
Definition at line 1856 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Add(), KALDI_ASSERT, PerElementOffsetComponent::offsets_, CuVector< Real >::Resize(), CuVectorBase< Real >::Scale(), and CuVectorBase< Real >::SetRandn().
Referenced by PerElementOffsetComponent::InitFromConfig().
{
   KALDI_ASSERT(dim > 0 && param_stddev >= 0.0);
   offsets_.Resize(dim);
   offsets_.SetRandn();
   offsets_.Scale(param_stddev);
   offsets_.Add(param_mean);
 }
void Init (std::string vector_filename)
Definition at line 1866 of file nnet-simple-component.cc.
References CuVectorBase< Real >::CopyFromVec(), CuVectorBase< Real >::Dim(), PerElementOffsetComponent::offsets_, kaldi::ReadKaldiObject(), and CuVector< Real >::Resize().
{
   CuVector<BaseFloat> vec;
   ReadKaldiObject(vector_filename, &vec); // will abort on failure.
   offsets_.Resize(vec.Dim());
   offsets_.CopyFromVec(vec);
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 1873 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), PerElementOffsetComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), PerElementOffsetComponent::InputDim(), KALDI_ASSERT, KALDI_ERR, and ConfigLine::UnusedValues().
{
   std::string vector_filename;
   int32 dim = -1;
   InitLearningRatesFromConfig(cfl);
   if (cfl->GetValue("vector", &vector_filename)) {
     Init(vector_filename);
     if (cfl->GetValue("dim", &dim))
       KALDI_ASSERT(dim == InputDim() &&
                    "input-dim mismatch vs. vector.");
   } else {
     if(!cfl->GetValue("dim", &dim))
       KALDI_ERR << "'dim' not provided in the config line.";
     BaseFloat param_mean = 0.0, param_stddev = 0.0;
     cfl->GetValue("param-mean", &param_mean);
     cfl->GetValue("param-stddev", &param_stddev);
     Init(dim, param_mean, param_stddev);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
 }
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 1126 of file nnet-simple-component.h.
References CuVectorBase< Real >::Dim(), and PerElementOffsetComponent::offsets_.
Referenced by PerElementOffsetComponent::InitFromConfig(), and PerElementOffsetComponent::NumParameters().
 { return offsets_.Dim(); }
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 1941 of file nnet-simple-component.cc.
References PerElementOffsetComponent::InputDim().
{
   return InputDim();
 }
const PerElementOffsetComponent& operator= (const PerElementOffsetComponent & other) protected
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 1127 of file nnet-simple-component.h.
References CuVectorBase< Real >::Dim(), and PerElementOffsetComponent::offsets_.
 { return offsets_.Dim(); }
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 1826 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddVec(), CuVectorBase< Real >::Dim(), kaldi::kUndefined, PerElementOffsetComponent::offsets_, and CuVectorBase< Real >::SetRandn().
{
   CuVector<BaseFloat> temp_offsets(offsets_.Dim(), kUndefined);
   temp_offsets.SetRandn();
   offsets_.AddVec(stddev, temp_offsets);
 }
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Implements Component.
Definition at line 1895 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::CopyFromMat(), and PerElementOffsetComponent::offsets_.
{
   out->CopyFromMat(in);
   out->AddVecToRows(1.0, offsets_);
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1134 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kPropagateInPlace, kaldi::nnet3::kSimpleComponent, and kaldi::nnet3::kUpdatableComponent.
{
     return kSimpleComponent|kUpdatableComponent|
            kBackpropInPlace|kPropagateInPlace;
   }
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 1923 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, PerElementOffsetComponent::offsets_, CuVector< Real >::Read(), kaldi::ReadBasicType(), and UpdatableComponent::ReadUpdatableCommon().
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate
   ExpectToken(is, binary, "<Offsets>");
   offsets_.Read(is, binary);
   ExpectToken(is, binary, "<IsGradient>");
   ReadBasicType(is, binary, &is_gradient_);
   ExpectToken(is, binary, "</PerElementOffsetComponent>");
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from Component.
Definition at line 1799 of file nnet-simple-component.cc.
References PerElementOffsetComponent::offsets_, and CuVectorBase< Real >::Scale().
{
   offsets_.Scale(scale);
 }
void SetZero (bool treat_as_gradient) virtual
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
Implements UpdatableComponent.
Definition at line 1817 of file nnet-simple-component.cc.
References UpdatableComponent::is_gradient_, UpdatableComponent::learning_rate_, PerElementOffsetComponent::offsets_, and CuVectorBase< Real >::SetZero().
{
   if (treat_as_gradient) {
     learning_rate_ = 1.0;  // don't call SetLearningRate, that would apply the
                            // learning rate factor.
     is_gradient_ = true;
   }
   offsets_.SetZero();
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1133 of file nnet-simple-component.h.
 { return "PerElementOffsetComponent"; }
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 1949 of file nnet-simple-component.cc.
References CuVectorBase< Real >::CopyFromVec(), and PerElementOffsetComponent::offsets_.
{
   offsets_.CopyFromVec(params);
 }
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 1945 of file nnet-simple-component.cc.
References VectorBase< Real >::CopyFromVec(), and PerElementOffsetComponent::offsets_.
{
   params->CopyFromVec(offsets_);
 }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 1932 of file nnet-simple-component.cc.
References UpdatableComponent::is_gradient_, PerElementOffsetComponent::offsets_, CuVector< Real >::Write(), kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<Offsets>");
   offsets_.Write(os, binary);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   WriteToken(os, binary, "</PerElementOffsetComponent>");
 }
Member Data Documentation
CuVector<BaseFloat> offsets_ protected
Definition at line 1176 of file nnet-simple-component.h.
Referenced by PerElementOffsetComponent::Add(), PerElementOffsetComponent::Backprop(), PerElementOffsetComponent::Copy(), PerElementOffsetComponent::DotProduct(), PerElementOffsetComponent::Info(), PerElementOffsetComponent::Init(), PerElementOffsetComponent::InputDim(), PerElementOffsetComponent::OutputDim(), PerElementOffsetComponent::PerturbParams(), PerElementOffsetComponent::Propagate(), PerElementOffsetComponent::Read(), PerElementOffsetComponent::Scale(), PerElementOffsetComponent::SetZero(), PerElementOffsetComponent::UnVectorize(), PerElementOffsetComponent::Vectorize(), and PerElementOffsetComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc