Kaldi: DecodableAmDiagGmmScaled Class Reference
DecodableAmDiagGmmScaled Class Reference
#include <decodable-am-diag-gmm.h>
Public Member Functions
DecodableAmDiagGmmScaled (const AmDiagGmm &am, const TransitionModel &tm, const Matrix< BaseFloat > &feats, BaseFloat scale, BaseFloat log_sum_exp_prune=-1.0)
DecodableAmDiagGmmScaled (const AmDiagGmm &am, const TransitionModel &tm, BaseFloat scale, BaseFloat log_sum_exp_prune, Matrix< BaseFloat > *feats)
virtual BaseFloat LogLikelihood (int32 frame, int32 tid)
Returns the log likelihood, which will be negated in the decoder.
virtual int32 NumIndices () const
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
const TransitionModel * TransModel ()
virtual ~DecodableAmDiagGmmScaled ()
Public Member Functions inherited from DecodableAmDiagGmmUnmapped
DecodableAmDiagGmmUnmapped (const AmDiagGmm &am, const Matrix< BaseFloat > &feats, BaseFloat log_sum_exp_prune=-1.0)
If you set log_sum_exp_prune to a value greater than 0 it will prune in the LogSumExp operation (larger = more exact); I suggest 5.
virtual int32 NumFramesReady () const
The call NumFramesReady() will return the number of frames currently available for this decodable object.
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
Public Member Functions inherited from DecodableInterface
virtual ~DecodableInterface ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmDiagGmmScaled)
Private Attributes
const TransitionModel & trans_model_
BaseFloat scale_
Matrix< BaseFloat > * delete_feats_
Additional Inherited Members
Protected Member Functions inherited from DecodableAmDiagGmmUnmapped
void ResetLogLikeCache ()
virtual BaseFloat LogLikelihoodZeroBased (int32 frame, int32 state_index)
Protected Attributes inherited from DecodableAmDiagGmmUnmapped
const AmDiagGmm & acoustic_model_
const Matrix< BaseFloat > & feature_matrix_
int32 previous_frame_
BaseFloat log_sum_exp_prune_
std::vector
< LikelihoodCacheRecord > log_like_cache_
Detailed Description
Definition at line 121 of file decodable-am-diag-gmm.h.
Constructor & Destructor Documentation
DecodableAmDiagGmmScaled (const AmDiagGmm & am, const TransitionModel & tm, const Matrix< BaseFloat > & feats, BaseFloat scale, BaseFloat log_sum_exp_prune = -1.0) inline
Definition at line 123 of file decodable-am-diag-gmm.h.
                                                               :
       DecodableAmDiagGmmUnmapped(am, feats, log_sum_exp_prune), trans_model_(tm),
       scale_(scale), delete_feats_(NULL) {}
DecodableAmDiagGmmScaled (const AmDiagGmm & am, const TransitionModel & tm, BaseFloat scale, BaseFloat log_sum_exp_prune, Matrix< BaseFloat > * feats) inline
Definition at line 133 of file decodable-am-diag-gmm.h.
                                                     :
       DecodableAmDiagGmmUnmapped(am, *feats, log_sum_exp_prune),
       trans_model_(tm),  scale_(scale), delete_feats_(feats) {}
virtual ~DecodableAmDiagGmmScaled () inline virtual
Definition at line 151 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmScaled::delete_feats_.
{
     delete delete_feats_;
   }
Member Function Documentation
KALDI_DISALLOW_COPY_AND_ASSIGN (DecodableAmDiagGmmScaled) private
virtual BaseFloat LogLikelihood (int32 frame, int32 index) inline virtual
Returns the log likelihood, which will be negated in the decoder.
The "frame" starts from zero. You should verify that IsLastFrame(frame-1) returns false before calling this.
Reimplemented from DecodableAmDiagGmmUnmapped.
Definition at line 142 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmUnmapped::LogLikelihoodZeroBased(), DecodableAmDiagGmmScaled::scale_, DecodableAmDiagGmmScaled::trans_model_, and TransitionModel::TransitionIdToPdf().
{
     return scale_*LogLikelihoodZeroBased(frame,
                                          trans_model_.TransitionIdToPdf(tid));
   }
virtual int32 NumIndices () const inline virtual
Returns the number of states in the acoustic model (they will be indexed one-based, i.e.
from 1 to NumIndices(); this is for compatibility with OpenFst.
Reimplemented from DecodableAmDiagGmmUnmapped.
Definition at line 147 of file decodable-am-diag-gmm.h.
References TransitionModel::NumTransitionIds(), and DecodableAmDiagGmmScaled::trans_model_.
 { return trans_model_.NumTransitionIds(); }
const TransitionModel* TransModel () inline
Definition at line 149 of file decodable-am-diag-gmm.h.
References DecodableAmDiagGmmScaled::trans_model_.
 { return &trans_model_; }
Member Data Documentation
Matrix<BaseFloat>* delete_feats_ private
Definition at line 158 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmScaled::~DecodableAmDiagGmmScaled().
BaseFloat scale_ private
Definition at line 157 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmScaled::LogLikelihood().
const TransitionModel& trans_model_ private
Definition at line 156 of file decodable-am-diag-gmm.h.
Referenced by DecodableAmDiagGmmScaled::LogLikelihood(), DecodableAmDiagGmmScaled::NumIndices(), and DecodableAmDiagGmmScaled::TransModel().
The documentation for this class was generated from the following file:
gmm/decodable-am-diag-gmm.h