Kaldi: FeatureTransformEstimateMulti Class Reference
FeatureTransformEstimateMulti Class Reference
#include <get-feature-transform.h>
Public Member Functions
void Estimate (const FeatureTransformEstimateOptions &opts, const std::vector< std::vector< int32 > > &indexes, Matrix< BaseFloat > *M) const
This is as FeatureTransformEstimate, but for use in nnet-get-feature-transform-multi.cc, see the usage message of that program for a description of what it does.
Public Member Functions inherited from FeatureTransformEstimate
void Estimate (const FeatureTransformEstimateOptions &opts, Matrix< BaseFloat > *M, TpMatrix< BaseFloat > *within_cholesky) const
Estimates the LDA transform matrix m.
Public Member Functions inherited from LdaEstimate
LdaEstimate ()
void Init (int32 num_classes, int32 dimension)
Allocates memory for accumulators.
int32 NumClasses () const
Returns the number of classes.
int32 Dim () const
Returns the dimensionality of the feature vectors.
void ZeroAccumulators ()
Sets all accumulators to zero.
void Scale (BaseFloat f)
Scales all accumulators.
double TotCount ()
Return total count of the data.
void Accumulate (const VectorBase< BaseFloat > &data, int32 class_id, BaseFloat weight=1.0)
Accumulates data.
void Estimate (const LdaEstimateOptions &opts, Matrix< BaseFloat > *M, Matrix< BaseFloat > *Mfull=NULL) const
Estimates the LDA transform matrix m.
void Read (std::istream &in_stream, bool binary, bool add)
void Write (std::ostream &out_stream, bool binary) const
Private Member Functions
void EstimateTransformPart (const FeatureTransformEstimateOptions &opts, const std::vector< int32 > &indexes, const SpMatrix< double > &total_covar, const SpMatrix< double > &between_covar, const Vector< double > &mean, Matrix< BaseFloat > *M) const
Additional Inherited Members
Protected Member Functions inherited from LdaEstimate
void GetStats (SpMatrix< double > *total_covar, SpMatrix< double > *between_covar, Vector< double > *total_mean, double *sum) const
Extract a more processed form of the stats.
LdaEstimate & operator= (const LdaEstimate &other)
Static Protected Member Functions inherited from FeatureTransformEstimate
static void EstimateInternal (const FeatureTransformEstimateOptions &opts, const SpMatrix< double > &total_covar, const SpMatrix< double > &between_covar, const Vector< double > &mean, Matrix< BaseFloat > *M, TpMatrix< BaseFloat > *C)
Static Protected Member Functions inherited from LdaEstimate
static void AddMeanOffset (const VectorBase< double > &total_mean, Matrix< BaseFloat > *projection)
This function modifies the LDA matrix so that it also subtracts the mean feature value.
Protected Attributes inherited from LdaEstimate
Vector< double > zero_acc_
Matrix< double > first_acc_
SpMatrix< double > total_second_acc_
Detailed Description
Definition at line 157 of file get-feature-transform.h.
Member Function Documentation
void Estimate (const FeatureTransformEstimateOptions & opts, const std::vector< std::vector< int32 > > & indexes, Matrix< BaseFloat > * M) const
This is as FeatureTransformEstimate, but for use in nnet-get-feature-transform-multi.cc, see the usage message of that program for a description of what it does.
Definition at line 164 of file get-feature-transform.cc.
References count, LdaEstimate::Dim(), FeatureTransformEstimateMulti::EstimateTransformPart(), LdaEstimate::GetStats(), rnnlm::i, kaldi::IsSortedAndUniq(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::Range(), FeatureTransformEstimateOptions::remove_offset, and Matrix< Real >::Resize().
Referenced by main().
{
   int32 input_dim = Dim(), output_dim = 0, num_transforms = indexes.size();
   for (int32 i = 0; i < num_transforms; i++) { // some input-checking.
     KALDI_ASSERT(indexes[i].size() > 0);
     std::vector<int32> this_indexes(indexes[i]);
     std::sort(this_indexes.begin(), this_indexes.end());
     KALDI_ASSERT(IsSortedAndUniq(this_indexes)); // check for duplicates.
     KALDI_ASSERT(this_indexes.front() >= 0);
     KALDI_ASSERT(this_indexes.back() < input_dim);
     output_dim += this_indexes.size();
   }
   int32 input_dim_ext = (opts.remove_offset ? input_dim + 1 : input_dim);
   M->Resize(output_dim, input_dim_ext);
   double count;
   Vector<double> total_mean;
   SpMatrix<double> total_covar, between_covar;
   GetStats(&total_covar, &between_covar, &total_mean, &count);
   int32 cur_output_index = 0;
   for (int32 i = 0; i < num_transforms; i++) {
     Matrix<BaseFloat> M_tmp;
     EstimateTransformPart(opts, indexes[i], total_covar, between_covar,
                           total_mean, &M_tmp);
     int32 this_output_dim = indexes[i].size();
     M->Range(cur_output_index, this_output_dim, 0, M->NumCols()).
         CopyFromMat(M_tmp);
     cur_output_index += this_output_dim;
   }
 }
void EstimateTransformPart (const FeatureTransformEstimateOptions & opts, const std::vector< int32 > & indexes, const SpMatrix< double > & total_covar, const SpMatrix< double > & between_covar, const Vector< double > & mean, Matrix< BaseFloat > * M) const private
Definition at line 129 of file get-feature-transform.cc.
References SpMatrix< Real >::AddMat2Sp(), MatrixBase< Real >::AddMatMat(), VectorBase< Real >::AddMatVec(), FeatureTransformEstimateOptions::dim, LdaEstimate::Dim(), FeatureTransformEstimate::EstimateInternal(), rnnlm::i, kaldi::kCopyData, kaldi::kNoTrans, MatrixBase< Real >::NumCols(), and Matrix< Real >::Resize().
Referenced by FeatureTransformEstimateMulti::Estimate().
{
   int32 full_dim = Dim(), proj_dim = indexes.size();
   Matrix<double> transform(proj_dim, full_dim); // projects from full to projected dim.
   for (int32 i = 0; i < proj_dim; i++)
     transform(i, indexes[i]) = 1.0;
   SpMatrix<double> total_covar_proj(proj_dim), between_covar_proj(proj_dim);
   Vector<double> mean_proj(proj_dim);
   total_covar_proj.AddMat2Sp(1.0, transform, kNoTrans, total_covar, 0.0);
   between_covar_proj.AddMat2Sp(1.0, transform, kNoTrans, between_covar, 0.0);
   mean_proj.AddMatVec(1.0, transform, kNoTrans, mean, 0.0);
   Matrix<BaseFloat> M_proj;
   FeatureTransformEstimateOptions opts_tmp(opts);
   opts_tmp.dim = proj_dim;
   EstimateInternal(opts_tmp, total_covar_proj, between_covar_proj, mean_proj,
                    &M_proj, NULL);
   if (M_proj.NumCols() == proj_dim + 1) { // Extend transform to add the extra "1" that we
                                           // use to handle mean shifts..
     transform.Resize(proj_dim + 1, full_dim + 1, kCopyData);
     transform(proj_dim, full_dim) = 1.0;
   }
   M->Resize(proj_dim, transform.NumCols());
   // Produce output..
   M->AddMatMat(1.0, M_proj, kNoTrans, Matrix<BaseFloat>(transform),
                kNoTrans, 0.0);
 }
The documentation for this class was generated from the following files:
nnet2/get-feature-transform.h
nnet2/get-feature-transform.cc