Kaldi: SentenceAveragingComponent Class Reference
SentenceAveragingComponent Class Reference
Deprecated, keeping it as Katka Zmolikova used it in JSALT 2015.
#include <nnet-sentence-averaging-component.h>
Public Member Functions
SentenceAveragingComponent (int32 dim_in, int32 dim_out)
~SentenceAveragingComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
void SetTrainOptions (const NnetTrainOptions &opts)
Sets the training options to the component.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters.
const NnetTrainOptions & GetTrainOptions () const
Gets the training options from the component.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
Private Attributes
Nnet nnet_
float learn_rate_factor_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Deprecated, keeping it as Katka Zmolikova used it in JSALT 2015.
Definition at line 114 of file nnet-sentence-averaging-component.h.
Constructor & Destructor Documentation
SentenceAveragingComponent (int32 dim_in, int32 dim_out) inline
Definition at line 116 of file nnet-sentence-averaging-component.h.
Referenced by SentenceAveragingComponent::Copy().
     : UpdatableComponent(dim_in, dim_out), learn_rate_factor_(100.0)
   { }
~SentenceAveragingComponent () inline
Definition at line 119 of file nnet-sentence-averaging-component.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 180 of file nnet-sentence-averaging-component.h.
References CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), SentenceAveragingComponent::nnet_, CuMatrixBase< Real >::NumCols(), and Nnet::OutputDim().
{
     if (in_diff == NULL) return;
     int32 num_inputs = in.NumCols(),
       nnet_outputs = nnet_.OutputDim();
     in_diff->CopyFromMat(out_diff.ColRange(nnet_outputs,num_inputs));
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 122 of file nnet-sentence-averaging-component.h.
References SentenceAveragingComponent::SentenceAveragingComponent().
 { return new SentenceAveragingComponent(*this); }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 159 of file nnet-sentence-averaging-component.h.
References Nnet::GetParams(), SentenceAveragingComponent::nnet_, SentenceAveragingComponent::NumParams(), and Vector< Real >::Resize().
 { wei_copy->Resize(NumParams()); nnet_.GetParams(wei_copy); }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 123 of file nnet-sentence-averaging-component.h.
References Component::kSentenceAveragingComponent.
 { return kSentenceAveragingComponent; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 160 of file nnet-sentence-averaging-component.h.
References Nnet::Info(), and SentenceAveragingComponent::nnet_.
 { return std::string("nested_network {\n") + nnet_.Info() + "}\n"; }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 161 of file nnet-sentence-averaging-component.h.
References Nnet::InfoGradient(), and SentenceAveragingComponent::nnet_.
 { return std::string("nested_gradient {\n") + nnet_.InfoGradient() + "}\n"; }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 125 of file nnet-sentence-averaging-component.h.
References Nnet::Init(), Nnet::InputDim(), Component::InputDim(), KALDI_ASSERT, KALDI_ERR, SentenceAveragingComponent::learn_rate_factor_, SentenceAveragingComponent::nnet_, Nnet::OutputDim(), Component::OutputDim(), Nnet::Read(), kaldi::ReadBasicType(), and kaldi::ReadToken().
{
     // define options
     std::string nested_nnet_filename;
     std::string nested_nnet_proto;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<NestedNnetFilename>") ReadToken(is, false, &nested_nnet_filename);
       else if (token == "<NestedNnetProto>") ReadToken(is, false, &nested_nnet_proto);
       else if (token == "<LearnRateFactor>") ReadBasicType(is, false, &learn_rate_factor_);
       else KALDI_ERR << "Unknown token " << token << " Typo in config?";
       is >> std::ws; // eat-up whitespace
     }
     // initialize (read already prepared nnet from file)
     KALDI_ASSERT((nested_nnet_proto != "") ^ (nested_nnet_filename != "")); //xor
     if (nested_nnet_filename != "") nnet_.Read(nested_nnet_filename);
     if (nested_nnet_proto != "") nnet_.Init(nested_nnet_proto);
     // check dims of nested nnet
     KALDI_ASSERT(InputDim() == nnet_.InputDim());
     KALDI_ASSERT(OutputDim() == nnet_.OutputDim() + InputDim());
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 158 of file nnet-sentence-averaging-component.h.
References SentenceAveragingComponent::nnet_, and Nnet::NumParams().
Referenced by SentenceAveragingComponent::GetParams().
 { return nnet_.NumParams(); }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 163 of file nnet-sentence-averaging-component.h.
References CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::ColRange(), SentenceAveragingComponent::nnet_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Nnet::OutputDim(), and Nnet::Propagate().
{
     // Get NN output
     CuMatrix<BaseFloat> out_nnet;
     nnet_.Propagate(in, &out_nnet);
     // Get the average row (averaging over the time axis):
     // averaging corresponds to extraction of constant vector code for single sentence,
     int32 num_inputs = in.NumCols(),
       nnet_outputs = nnet_.OutputDim(),
       num_frames = out_nnet.NumRows();
     CuVector<BaseFloat> average_row(nnet_outputs);
     average_row.AddRowSumMat(1.0/num_frames, out_nnet, 0.0);
     // Forwarding sentence codes along with input features
     out->ColRange(0,nnet_outputs).AddVecToRows(1.0, average_row, 0.0);
     out->ColRange(nnet_outputs,num_inputs).CopyFromMat(in);
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 148 of file nnet-sentence-averaging-component.h.
References Nnet::InputDim(), Component::InputDim(), KALDI_ASSERT, SentenceAveragingComponent::nnet_, Nnet::OutputDim(), Component::OutputDim(), and Nnet::Read().
{
     nnet_.Read(is, binary);
     KALDI_ASSERT(nnet_.InputDim() == InputDim());
     KALDI_ASSERT(nnet_.OutputDim() + InputDim() == OutputDim());
   }
void SetTrainOptions (const NnetTrainOptions & opts) inline virtual
Sets the training options to the component.
Reimplemented from UpdatableComponent.
Definition at line 207 of file nnet-sentence-averaging-component.h.
References NnetTrainOptions::learn_rate, SentenceAveragingComponent::learn_rate_factor_, SentenceAveragingComponent::nnet_, UpdatableComponent::opts_, Nnet::SetTrainOptions(), and UpdatableComponent::SetTrainOptions().
{
     UpdatableComponent::SetTrainOptions(opts_);
     // Pass the train options to the nnet
     NnetTrainOptions o(opts);
     //o.learn_rate *= 100; // GOOD
     //o.learn_rate *= 1000; // BAD
     o.learn_rate *= learn_rate_factor_;
     nnet_.SetTrainOptions(opts_);
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 188 of file nnet-sentence-averaging-component.h.
References CuVectorBase< Real >::AddRowSumMat(), CuMatrixBase< Real >::AddVecToRows(), Nnet::Backpropagate(), CuMatrixBase< Real >::ColRange(), SentenceAveragingComponent::nnet_, CuMatrixBase< Real >::NumRows(), and Nnet::OutputDim().
{
     int32 nnet_outputs = nnet_.OutputDim(),
       num_frames = diff.NumRows();
     // Passing the derivative into the nested network. The loss derivative is averaged:
     // single frame from nested network influenced all the frames in the main network,
     // so to get the derivative w.r.t. single frame from nested network we sum derivatives
     // of all frames from main network (and scale by 1/Nframes constant).
     //
     // In fact all the frames from nested network influenced all the input frames to main nnet,
     // so the loss derivarive w.r.t. nested network output is same for all frames in sentence.
     CuVector<BaseFloat> average_diff(nnet_outputs);
     average_diff.AddRowSumMat(1.0/num_frames, diff.ColRange(0,nnet_outputs), 0.0);
     CuMatrix<BaseFloat> nnet_out_diff(num_frames, nnet_outputs);
     nnet_out_diff.AddVecToRows(1.0, average_diff, 0.0);
     //
     nnet_.Backpropagate(nnet_out_diff, NULL);
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 154 of file nnet-sentence-averaging-component.h.
References SentenceAveragingComponent::nnet_, and Nnet::Write().
{
     nnet_.Write(os, binary);
   }
Member Data Documentation
float learn_rate_factor_ private
Definition at line 219 of file nnet-sentence-averaging-component.h.
Referenced by SentenceAveragingComponent::InitData(), and SentenceAveragingComponent::SetTrainOptions().
Nnet nnet_ private
Definition at line 218 of file nnet-sentence-averaging-component.h.
Referenced by SentenceAveragingComponent::BackpropagateFnc(), SentenceAveragingComponent::GetParams(), SentenceAveragingComponent::Info(), SentenceAveragingComponent::InfoGradient(), SentenceAveragingComponent::InitData(), SentenceAveragingComponent::NumParams(), SentenceAveragingComponent::PropagateFnc(), SentenceAveragingComponent::ReadData(), SentenceAveragingComponent::SetTrainOptions(), SentenceAveragingComponent::Update(), and SentenceAveragingComponent::WriteData().
The documentation for this class was generated from the following file:
nnet/nnet-sentence-averaging-component.h