Kaldi: TrivialFactorWeightFst< A, F > Class Template Reference
TrivialFactorWeightFst< A, F > Class Template Reference
FactorWeightFst takes as template parameter a FactorIterator as defined above.
#include <trivial-factor-weight.h>
Public Types
typedef A Arc
typedef A::Weight Weight
typedef A::StateId StateId
typedef CacheState< A > State
typedef
TrivialFactorWeightFstImpl< A,
F > Impl
Public Member Functions
TrivialFactorWeightFst (const Fst< A > &fst)
TrivialFactorWeightFst (const Fst< A > &fst, const TrivialFactorWeightOptions< A > &opts)
TrivialFactorWeightFst (const TrivialFactorWeightFst< A, F > &fst, bool copy)
virtual TrivialFactorWeightFst
< A, F > * Copy (bool copy=false) const
virtual void InitStateIterator (StateIteratorData< A > *data) const
virtual void InitArcIterator (StateId s, ArcIteratorData< A > *data) const
Private Member Functions
Impl * GetImpl () const
void operator= (const TrivialFactorWeightFst< A, F > &fst)
Friends
class ArcIterator< TrivialFactorWeightFst< A, F > >
class StateIterator< TrivialFactorWeightFst< A, F > >
Detailed Description
template<class A, class F>
class fst::TrivialFactorWeightFst< A, F >
FactorWeightFst takes as template parameter a FactorIterator as defined above.
The result of weight factoring is a transducer equivalent to the input whose path weights have been factored according to the FactorIterator. States and transitions will be added as necessary. This algorithm differs from the one implemented in FactorWeightFst in that it does not attempt to push the extra weight forward to the next state: it uses a sequence of "extra" intermediate state, and outputs the remaining weight right away. This ensures that it will always succeed, even for Gallic representations of FSTs that have cycles with more output than input symbols. Note that the code below was modified from factor-weight.h by just search-and-replacing "FactorWeight" by "TrivialFactorWeight".
Definition at line 339 of file trivial-factor-weight.h.
Member Typedef Documentation
typedef A Arc
Definition at line 344 of file trivial-factor-weight.h.
typedef TrivialFactorWeightFstImpl<A, F> Impl
Definition at line 353 of file trivial-factor-weight.h.
typedef CacheState<A> State
Definition at line 351 of file trivial-factor-weight.h.
typedef A::StateId StateId
Definition at line 346 of file trivial-factor-weight.h.
typedef A::Weight Weight
Definition at line 345 of file trivial-factor-weight.h.
Constructor & Destructor Documentation
TrivialFactorWeightFst (const Fst< A > & fst) inline
Definition at line 355 of file trivial-factor-weight.h.
       : ImplToFst<Impl>(new Impl(fst, TrivialFactorWeightOptions<A>())) {}
TrivialFactorWeightFst (const Fst< A > & fst, const TrivialFactorWeightOptions< A > & opts) inline
Definition at line 358 of file trivial-factor-weight.h.
       : ImplToFst<Impl>(new Impl(fst, opts)) {}
TrivialFactorWeightFst (const TrivialFactorWeightFst< A, F > & fst, bool copy) inline
Definition at line 362 of file trivial-factor-weight.h.
       : ImplToFst<Impl>(fst, copy) {}
Member Function Documentation
virtual TrivialFactorWeightFst<A, F>* Copy (bool copy = false) const inline virtual
Definition at line 366 of file trivial-factor-weight.h.
{
     return new TrivialFactorWeightFst<A, F>(*this, copy);
   }
Impl* GetImpl () const inline private
Definition at line 378 of file trivial-factor-weight.h.
Referenced by ArcIterator< TrivialFactorWeightFst< A, F > >::ArcIterator(), and TrivialFactorWeightFst< A, F >::InitArcIterator().
 { return ImplToFst<Impl>::GetImpl(); }
virtual void InitArcIterator (StateId s, ArcIteratorData< A > * data) const inline virtual
Definition at line 372 of file trivial-factor-weight.h.
References TrivialFactorWeightFst< A, F >::GetImpl(), and TrivialFactorWeightFstImpl< A, F >::InitArcIterator().
{
     GetImpl()->InitArcIterator(s, data);
   }
void InitStateIterator (StateIteratorData< A > * data) const inline virtual
Definition at line 412 of file trivial-factor-weight.h.
 {
   data->base = new StateIterator< TrivialFactorWeightFst<A, F> >(*this);
 }
void operator= (const TrivialFactorWeightFst< A, F > & fst) private
Friends And Related Function Documentation
friend class ArcIterator< TrivialFactorWeightFst< A, F > > friend
Definition at line 341 of file trivial-factor-weight.h.
friend class StateIterator< TrivialFactorWeightFst< A, F > > friend
Definition at line 342 of file trivial-factor-weight.h.
The documentation for this class was generated from the following file:
fstext/trivial-factor-weight.h