Kaldi: LmFstConverter Class Reference
LmFstConverter Class Reference
LanguageModel
Definition of internal representation for language model.
#include <kaldi-lmtable.h>
Public Member Functions
LmFstConverter ()
~LmFstConverter ()
void UseNaturalLog (bool use_natural)
void AddArcsForNgramProb (int ilev, int maxlev, float prob, float bow, std::vector< string > &ngs, fst::StdVectorFst *fst, const string startSent, const string endSent)
float ConvertArpaLogProbToWeight (float lp)
bool IsFinal (fst::StdVectorFst *pfst, StateId s)
void ConnectUnusedStates (fst::StdVectorFst *pfst)
Private Types
typedef fst::StdArc::Weight LmWeight
typedef fst::StdArc::StateId StateId
typedef unordered_map< StateId,
StateId > BackoffStateMap
typedef unordered_map
< std::string, StateId,
StringHasher > HistStateMap
Private Member Functions
StateId AddStateFromSymb (const std::vector< string > &ngramString, int kstart, int kend, fst::StdVectorFst *pfst, bool &newly_added)
StateId FindState (const std::string str)
Private Attributes
bool use_natural_log_
BackoffStateMap backoff_state_
HistStateMap hist_state_
Detailed Description
Definition of internal representation for language model.
Provides a unified interface to various toolkits such as IRSTLM. Also contains a basic implementation for reading ARPA files which does not require an external library.Helper methods to convert toolkit internal representations into FST.
Definition at line 67 of file kaldi-lmtable.h.
Member Typedef Documentation
typedef unordered_map<StateId, StateId> BackoffStateMap private
Definition at line 71 of file kaldi-lmtable.h.
typedef unordered_map<std::string, StateId, StringHasher> HistStateMap private
Definition at line 72 of file kaldi-lmtable.h.
typedef fst::StdArc::Weight LmWeight private
Definition at line 68 of file kaldi-lmtable.h.
typedef fst::StdArc::StateId StateId private
Definition at line 69 of file kaldi-lmtable.h.
Constructor & Destructor Documentation
LmFstConverter () inline
Definition at line 76 of file kaldi-lmtable.h.
 : use_natural_log_(true) {}
~LmFstConverter () inline
Definition at line 78 of file kaldi-lmtable.h.
 {}
Member Function Documentation
void AddArcsForNgramProb (int ilev, int maxlev, float prob, float bow, std::vector< string > & ngs, fst::StdVectorFst * fst, const string startSent, const string endSent)
Definition at line 90 of file kaldi-lmtable.cc.
References LmFstConverter::AddStateFromSymb(), LmFstConverter::backoff_state_, LmFstConverter::ConvertArpaLogProbToWeight(), rnnlm::i, LmFstConverter::IsFinal(), and KALDI_ERR.
Referenced by LmTable::ReadFstFromLmFile().
{
   fst::StdArc::StateId src, dst, dbo;
   std::string curwrd = ngram[1];
   if (curwrd == "<eps>") {
     KALDI_ERR << "The word <eps> is not allowed as a word in an ARPA LM.";
   }
   int64 ilab, olab;
   LmWeight prob = ConvertArpaLogProbToWeight(logProb);
   LmWeight bow  = ConvertArpaLogProbToWeight(logBow);
   bool newSrc, newDbo, newDst = false;
   if (ngram_order >= 2) {
     // General case works from N down to 2-grams
     src = AddStateFromSymb(ngram, ngram_order, 2, fst, newSrc);
     if (ngram_order != max_ngram_order) {
       // add all intermediate levels from 2 to current
       // last ones will be current backoff source and destination
       for (int i = 2; i <= ngram_order; i++) {
         dst = AddStateFromSymb(ngram, i,   1, fst, newDst);
         dbo = AddStateFromSymb(ngram, i-1, 1, fst, newDbo);
         backoff_state_[dst] = dbo;
       }
     } else {
       // add all intermediate levels from 2 to current
       // last ones will be current backoff source and destination
       for (int i = 2; i <= ngram_order; i++) {
         dst = AddStateFromSymb(ngram, i-1, 1, fst, newDst);
         dbo = AddStateFromSymb(ngram, i-2, 1, fst, newDbo);
         backoff_state_[dst] = dbo;
       }
     }
   } else {
     // special case for 1-grams: start from 0-gram
     if (curwrd.compare(startSent) != 0) {
       src = AddStateFromSymb(ngram, 0, 1, fst, newSrc);
     } else {
       // extra special case if in addition we are at beginning of sentence
       // starts from initial state and has no cost
       src = fst->Start();
       prob = fst::StdArc::Weight::One();
     }
     dst = AddStateFromSymb(ngram, 1, 1, fst, newDst);
     dbo = AddStateFromSymb(ngram, 0, 1, fst, newDbo);
     backoff_state_[dst] = dbo;
   }
   // state is final if last word is end of sentence
   if (curwrd.compare(endSent) == 0) {
     fst->SetFinal(dst, fst::StdArc::Weight::One());
   }
   // add labels to symbol tables
   ilab = fst->MutableInputSymbols()->AddSymbol(curwrd);
   olab = fst->MutableOutputSymbols()->AddSymbol(curwrd);
   // add arc with weight "prob" between source and destination states
   // cerr << "n-gram prob, fstAddArc: src "<< src << " dst " << dst;
   // cerr << " lab " << ilab << endl;
   fst->AddArc(src, fst::StdArc(ilab, olab, prob, dst));
   // add backoffs to any newly created destination state
   // but only if non-final
   if (!IsFinal(fst, dst) && newDst && dbo != dst) {
     ilab = olab = 0;
     // cerr << "backoff, fstAddArc: src "<< src << " dst " << dst;
     // cerr << " lab " << ilab << endl;
     fst->AddArc(dst, fst::StdArc(ilab, olab, bow, dbo));
   }
 }
LmFstConverter::StateId AddStateFromSymb (const std::vector< string > & ngramString, int kstart, int kend, fst::StdVectorFst * pfst, bool & newly_added) private
Definition at line 35 of file kaldi-lmtable.cc.
References LmFstConverter::FindState(), and LmFstConverter::hist_state_.
Referenced by LmFstConverter::AddArcsForNgramProb().
{
   fst::StdArc::StateId sid;
   std::string separator;
   separator.resize(1);
   separator[0] = '\0';
   std::string hist;
   if (kstart == 0) {
     hist.append(separator);
   } else {
     for (int k = kstart; k >= kend; k--) {
       hist.append(ngramString[k]);
       hist.append(separator);
     }
   }
   newly_added = false;
   sid = FindState(hist);
   if (sid < 0) {
     sid = pfst->AddState();
     hist_state_[hist] = sid;
     newly_added = true;
     //cerr << "Created state " << sid << " for " << hist << endl;
   } else {
     //cerr << "State symbol " << hist << " already exists" << endl;
   }
   return sid;
 }
void ConnectUnusedStates (fst::StdVectorFst * pfst)
Definition at line 69 of file kaldi-lmtable.cc.
References LmFstConverter::backoff_state_, and LmFstConverter::IsFinal().
Referenced by LmTable::ReadFstFromLmFile().
{
   // go through all states with a recorded backoff destination
   // and find out any that has no output arcs and is not final
   unsigned int connected = 0;
   // cerr << "ConnectUnusedStates has recorded "<<backoff_state_.size()<<" states.\n";
   for (BackoffStateMap::iterator bkit = backoff_state_.begin(); bkit != backoff_state_.end(); ++bkit) {
     // add an output arc to its backoff destination recorded in backoff_
     fst::StdArc::StateId src = bkit->first, dst = bkit->second;
     if (pfst->NumArcs(src)==0 && !IsFinal(pfst, src)) {
       // cerr << "ConnectUnusedStates: adding arc from "<<src<<" to "<<dst<<endl;
       // epsilon arc with no cost
       pfst->AddArc(src,
                    fst::StdArc(0, 0, fst::StdArc::Weight::One(), dst));
       connected++;
     }
   }
   cerr << "Connected " << connected << " states without outgoing arcs." << endl;
 }
float ConvertArpaLogProbToWeight (float lp) inline
Definition at line 91 of file kaldi-lmtable.h.
References LmFstConverter::use_natural_log_.
Referenced by LmFstConverter::AddArcsForNgramProb().
{
     if ( use_natural_log_ ) {
       // convert from arpa base 10 log to natural base, then to cost
       return -2.302585*lp;
     } else {
       // keep original base but convert to cost
       return -lp;
     }
   }
StateId FindState (const std::string str) inline private
Definition at line 115 of file kaldi-lmtable.h.
References LmFstConverter::hist_state_.
Referenced by LmFstConverter::AddStateFromSymb().
{
     HistStateMap::const_iterator it = hist_state_.find(str);
      if (it == hist_state_.end()) return -1;
      else return it->second;
   }
bool IsFinal (fst::StdVectorFst * pfst, StateId s) inline
Definition at line 101 of file kaldi-lmtable.h.
Referenced by LmFstConverter::AddArcsForNgramProb(), and LmFstConverter::ConnectUnusedStates().
{
     return(pfst->Final(s) != fst::StdArc::Weight::Zero());
   }
void UseNaturalLog (bool use_natural) inline
Definition at line 80 of file kaldi-lmtable.h.
References LmFstConverter::use_natural_log_.
Referenced by LmTable::ReadFstFromLmFile().
 { use_natural_log_ = use_natural; }
Member Data Documentation
BackoffStateMap backoff_state_ private
Definition at line 122 of file kaldi-lmtable.h.
Referenced by LmFstConverter::AddArcsForNgramProb(), and LmFstConverter::ConnectUnusedStates().
HistStateMap hist_state_ private
Definition at line 123 of file kaldi-lmtable.h.
Referenced by LmFstConverter::AddStateFromSymb(), and LmFstConverter::FindState().
bool use_natural_log_ private
Definition at line 121 of file kaldi-lmtable.h.
Referenced by LmFstConverter::ConvertArpaLogProbToWeight(), and LmFstConverter::UseNaturalLog().
The documentation for this class was generated from the following files:
lm/kaldi-lmtable.h
lm/kaldi-lmtable.cc