Kaldi: CuArray< T > Class Template Reference
CuArray< T > Class Template Reference
std::vector equivalent for CUDA computing.
#include <cu-array.h>
Public Member Functions
CuArray ()
Default Constructor.
CuArray (MatrixIndexT dim, MatrixResizeType resize_type=kSetZero)
Constructor with memory initialisation.
CuArray (const std::vector< T > &src)
Constructor from CPU-based int vector.
CuArray (const CuArray< T > &src)
Copy constructor.
~CuArray ()
Destructor.
MatrixIndexT Dim () const
Return the vector dimension.
const T * Data () const
Get raw pointer.
T * Data ()
void Resize (MatrixIndexT dim, MatrixResizeType resize_type=kSetZero)
Allocate the memory.
void Destroy ()
Deallocate the memory and set dim_ and data_ to zero.
void CopyFromVec (const std::vector< T > &src)
This function resizes if needed.
void CopyFromArray (const CuArray< T > &src)
This function resizes if needed.
void CopyToVec (std::vector< T > *dst) const
This function resizes *dst if needed.
void CopyToHost (T *dst) const
Version of the above function that copies contents to a host array.
void SetZero ()
Sets the memory for the object to zero, via memset.
void Set (const T &value)
Set to a constant value.
CuArray< T > & operator= (const CuArray< T > &in)
CuArray< T > & operator= (const std::vector< T > &in)
template<>
void Set (const int32 &value)
Private Types
typedef CuArray< T > ThisType
Private Attributes
MatrixIndexT dim_
dimension of the vector
T * data_
GPU data pointer (if GPU not available, will point to CPU memory).
Detailed Description
template<typename T>
class kaldi::CuArray< T >
std::vector equivalent for CUDA computing.
This class is mostly intended as a CUDA-based mirror of a std::vector object that lives on the CPU. We don't call constructors, initializers, etc., on the GPU.
Definition at line 37 of file cu-array.h.
Member Typedef Documentation
typedef CuArray<T> ThisType private
Definition at line 38 of file cu-array.h.
Constructor & Destructor Documentation
CuArray () inline
Default Constructor.
Definition at line 42 of file cu-array.h.
 : dim_(0), data_(NULL) {  }
CuArray (MatrixIndexT dim, MatrixResizeType resize_type = kSetZero) inline explicit
Constructor with memory initialisation.
resize_type may be kSetZero or kUndefined.
Definition at line 46 of file cu-array.h.
                                                                                 :
     dim_(0), data_(NULL) { Resize(dim, resize_type); }
CuArray (const std::vector< T > & src) inline explicit
Constructor from CPU-based int vector.
Definition at line 50 of file cu-array.h.
                                               :
     dim_(0), data_(NULL) { CopyFromVec(src); }
CuArray (const CuArray< T > & src) inline
Copy constructor.
We don't make this explicit because we want to be able to create a std::vector<CuArray>.
Definition at line 55 of file cu-array.h.
                                    :
    dim_(0), data_(NULL) { CopyFromArray(src); }
~CuArray () inline
Destructor.
Definition at line 59 of file cu-array.h.
 { Destroy(); }
Member Function Documentation
void CopyFromArray (const CuArray< T > & src)
This function resizes if needed.
Definition at line 212 of file cu-array-inl.h.
References CuArray< T >::data_, CuArray< T >::Dim(), Timer::Elapsed(), and kaldi::kUndefined.
Referenced by CuArray< MatrixElement< Real > >::CuArray(), and CuArray< MatrixElement< Real > >::operator=().
{
   this->Resize(src.Dim(), kUndefined);
   if (dim_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cudaMemcpy(this->data_, src.data_, dim_ * sizeof(T),
                             cudaMemcpyDeviceToDevice));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     memcpy(this->data_, src.data_, dim_ * sizeof(T));
   }
 }
void CopyFromVec (const std::vector< T > & src)
This function resizes if needed.
Note: copying to GPU is done via memcpy, and any constructors or assignment operators are not called.
Definition at line 96 of file cu-array-inl.h.
References Timer::Elapsed(), and kaldi::kUndefined.
Referenced by PermuteComponent::ComputeReverseColumnMap(), CuArray< MatrixElement< Real > >::CuArray(), NnetComputer::GetPointers(), PermuteComponent::Init(), CuArray< MatrixElement< Real > >::operator=(), MatrixRandomizer::Randomize(), PermuteComponent::Read(), kaldi::UnitTestCuDiffXent(), kaldi::UnitTestCuMathCopy(), kaldi::UnitTestCuMathRandomize(), and kaldi::UnitTestCuMathSplice().
{
   Resize(src.size(), kUndefined);
   if (src.empty()) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cudaMemcpy(data_, &src.front(), src.size()*sizeof(T), cudaMemcpyHostToDevice));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     memcpy(data_, &src.front(), src.size()*sizeof(T));
   }
 }
void CopyToHost (T * dst) const
Version of the above function that copies contents to a host array.
This function requires *dst to be allocated before calling. The allocated size should be dim_ * sizeof(T)
Definition at line 133 of file cu-array-inl.h.
References Timer::Elapsed(), and KALDI_ASSERT.
Referenced by CuMatrixBase< Real >::Lookup(), and kaldi::UnitTestCuArray().
{
   if (dim_ == 0) return;
   KALDI_ASSERT(dst != NULL);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cudaMemcpy(dst, Data(), dim_ * sizeof(T), cudaMemcpyDeviceToHost));
     CuDevice::Instantiate().AccuProfile("CuArray::CopyToVecD2H", tim.Elapsed());
   } else
 #endif
   {
     memcpy(dst, data_, dim_ * sizeof(T));
   }
 }
void CopyToVec (std::vector< T > * dst) const
This function resizes *dst if needed.
On resize of "dst", the STL vector may call copy-constructors, initializers, and assignment operators for existing objects (which will be overwritten), but the copy from GPU to CPU is done via memcpy. So be very careful calling this function if your objects are more than plain structs.
Definition at line 114 of file cu-array-inl.h.
References Timer::Elapsed().
Referenced by PermuteComponent::ComputeReverseColumnMap(), kaldi::nnet1::CountCorrectFramesWeighted(), SumGroupComponent::GetSizes(), PermuteComponent::Info(), kaldi::TestCuFindRowMaxId(), kaldi::UnitTestCuArray(), kaldi::UnitTestCuFindRowMaxId(), PermuteComponent::Write(), Splice::WriteData(), and CopyComponent::WriteData().
{
   if (static_cast<MatrixIndexT>(dst->size()) != dim_) {
     dst->resize(dim_);
   }
   if (dim_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cudaMemcpy(&dst->front(), Data(), dim_ * sizeof(T), cudaMemcpyDeviceToHost));
     CuDevice::Instantiate().AccuProfile("CuArray::CopyToVecD2H", tim.Elapsed());
   } else
 #endif
   {
     memcpy(&dst->front(), data_, dim_ * sizeof(T));
   }
 }
const T* Data () const inline
Get raw pointer.
Definition at line 65 of file cu-array.h.
Referenced by CuMatrixBase< Real >::AddCols(), CuMatrixBase< Real >::AddElements(), CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::AddRows(), CuMatrixBase< Real >::AddToRows(), kaldi::cu::Copy(), CuMatrixBase< Real >::CopyCols(), CuMatrixBase< Real >::CopyRows(), CuMatrixBase< Real >::CopyToRows(), CuMatrixBase< Real >::DiffXent(), CuMatrixBase< Real >::FindRowMaxId(), CuMatrixBase< Real >::Lookup(), kaldi::cu::Randomize(), kaldi::cu::Splice(), and CuMatrixBase< Real >::SumColumnRanges().
 { return data_; }
T* Data () inline
Definition at line 67 of file cu-array.h.
 { return data_; }
void Destroy ()
Deallocate the memory and set dim_ and data_ to zero.
Does not call any destructors of the objects stored.
Definition at line 78 of file cu-array-inl.h.
Referenced by CuArray< MatrixElement< Real > >::~CuArray().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (data_ != NULL) {
       CuDevice::Instantiate().Free(this->data_);
     }
   } else
 #endif
   {
     if (data_ != NULL)
       free(data_);
   }
   dim_ = 0;
   data_ = NULL;
 }
MatrixIndexT Dim () const inline
Return the vector dimension.
Definition at line 62 of file cu-array.h.
Referenced by CuMatrixBase< Real >::AddCols(), CuMatrixBase< Real >::AddElements(), CuMatrixBase< Real >::AddRowRanges(), CuMatrixBase< Real >::AddRows(), CuMatrixBase< Real >::AddToRows(), PermuteComponent::ComputeReverseColumnMap(), kaldi::cu::Copy(), CuMatrixBase< Real >::CopyCols(), CuArray< T >::CopyFromArray(), CuMatrixBase< Real >::CopyRows(), CuMatrixBase< Real >::CopyToRows(), kaldi::nnet1::CountCorrectFramesWeighted(), CuMatrixBase< Real >::DiffXent(), PermuteComponent::Info(), Splice::InitData(), PermuteComponent::InputDim(), CuMatrixBase< Real >::Lookup(), PermuteComponent::OutputDim(), kaldi::cu::Randomize(), Splice::ReadData(), kaldi::cu::Splice(), CuMatrixBase< Real >::SumColumnRanges(), kaldi::UnitTestCuArray(), Splice::WriteData(), and CopyComponent::WriteData().
 { return dim_;  }
CuArray<T>& operator= (const CuArray< T > & in) inline
Definition at line 105 of file cu-array.h.
{
     this->CopyFromArray(in); return *this;
   }
CuArray<T>& operator= (const std::vector< T > & in) inline
Definition at line 109 of file cu-array.h.
{
     this->CopyFromVec(in); return *this;
   }
void Resize (MatrixIndexT dim, MatrixResizeType resize_type = kSetZero)
Allocate the memory.
resize_type may be kSetZero or kUndefined. kCopyData not yet supported (can be implemented if needed).
Definition at line 39 of file cu-array-inl.h.
References Timer::Elapsed(), KALDI_ASSERT, KALDI_ERR, kaldi::kSetZero, kaldi::kUndefined, and kaldi::nnet3::SetZero().
Referenced by PermuteComponent::ComputeReverseColumnMap(), CuArray< MatrixElement< Real > >::CuArray(), and kaldi::UnitTestCuArray().
{
   KALDI_ASSERT((resize_type == kSetZero || resize_type == kUndefined) && dim >= 0);
   if (dim_ == dim) {
     if (resize_type == kSetZero)
       SetZero();
     return;
   }
   Destroy();
   if (dim == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     this->data_ = static_cast<T*>(CuDevice::Instantiate().Malloc(dim * sizeof(T)));
     this->dim_ = dim;
     if (resize_type == kSetZero) this->SetZero();
     CuDevice::Instantiate().AccuProfile("CuArray::Resize", tim.Elapsed());
   } else
 #endif
   {
     data_ = static_cast<T*>(malloc(dim * sizeof(T)));
     // We allocate with malloc because we don't want constructors being called.
     // We basically ignore memory alignment issues here-- we assume the malloc
     // implementation is forgiving enough that it will automatically align on
     // sensible boundaries.
     if (data_ == 0)
       KALDI_ERR << "Memory allocation failed when initializing CuVector "
                 << "with dimension " << dim << " object size in bytes: "
                 << sizeof(T);
   }
   dim_ = dim;
   if (resize_type == kSetZero)
     SetZero();
 }
void Set (const T & value) inline
Set to a constant value.
Note: any copying is done as if using memcpy, and assignment operators or destructors are not called. This is NOT IMPLEMENTED YET except for T == int32 (the current implementation will just crash).
Definition at line 183 of file cu-array-inl.h.
References KALDI_ERR.
Referenced by kaldi::UnitTestCuArray().
{
   // This is not implemented yet, we'll do so if it's needed.
   KALDI_ERR << "CuArray<T>::Set not implemented yet for this type.";
 }
void Set (const int32 & value) inline
Definition at line 189 of file cu-array-inl.h.
References CU2DBLOCK, rnnlm::d, Timer::Elapsed(), and rnnlm::i.
{
   if (dim_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK);
     dim3 dimGrid(n_blocks(Dim(), CU2DBLOCK));
     ::MatrixDim d = { 1, Dim(), Dim() };
     cudaI32_set_const(dimGrid, dimBlock, data_, value, d);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     for (int32 i = 0; i < dim_; i++)
       data_[i] = value;
   }
 }
void SetZero ()
Sets the memory for the object to zero, via memset.
You should verify that this makes sense for type T.
Definition at line 150 of file cu-array-inl.h.
References Timer::Elapsed().
{
   if (dim_ == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     CU_SAFE_CALL(cudaMemset(data_, 0, dim_ * sizeof(T)));
     CuDevice::Instantiate().AccuProfile("CuArray::SetZero", tim.Elapsed());
   } else
 #endif
   {
     memset(static_cast<void*>(data_), 0, dim_ * sizeof(T));
   }
 }
Member Data Documentation
T* data_ private
GPU data pointer (if GPU not available, will point to CPU memory).
Definition at line 115 of file cu-array.h.
Referenced by CuArray< T >::CopyFromArray(), and CuArray< MatrixElement< Real > >::Data().
MatrixIndexT dim_ private
dimension of the vector
Definition at line 114 of file cu-array.h.
Referenced by CuArray< MatrixElement< Real > >::Dim().
The documentation for this class was generated from the following files:
cudamatrix/cu-array.h
cudamatrix/cu-array-inl.h