Kaldi: DiscTrainParallelClass Class Reference
DiscTrainParallelClass Class Reference
Public Member Functions
DiscTrainParallelClass (const AmNnet &am_nnet, const TransitionModel &tmodel, const NnetDiscriminativeUpdateOptions &opts, bool store_separate_gradients, DiscriminativeExamplesRepository *repository, Nnet *nnet_to_update, NnetDiscriminativeStats *stats)
DiscTrainParallelClass (const DiscTrainParallelClass &other)
void operator() ()
~DiscTrainParallelClass ()
Public Member Functions inherited from MultiThreadable
virtual ~MultiThreadable ()
Private Attributes
const AmNnet & am_nnet_
const TransitionModel & tmodel_
const
NnetDiscriminativeUpdateOptions & opts_
bool store_separate_gradients_
DiscriminativeExamplesRepository * repository_
Nnet * nnet_to_update_
Nnet * nnet_to_update_orig_
NnetDiscriminativeStats * stats_ptr_
NnetDiscriminativeStats stats_
Additional Inherited Members
Static Public Member Functions inherited from MultiThreadable
static void * run (void *m_in)
Public Attributes inherited from MultiThreadable
int32 thread_id_
int32 num_threads_
Detailed Description
Definition at line 103 of file nnet-compute-discriminative-parallel.cc.
Constructor & Destructor Documentation
DiscTrainParallelClass (const AmNnet & am_nnet, const TransitionModel & tmodel, const NnetDiscriminativeUpdateOptions & opts, bool store_separate_gradients, DiscriminativeExamplesRepository * repository, Nnet * nnet_to_update, NnetDiscriminativeStats * stats) inline
Definition at line 107 of file nnet-compute-discriminative-parallel.cc.
                                                         :
       am_nnet_(am_nnet), tmodel_(tmodel), opts_(opts),
       store_separate_gradients_(store_separate_gradients),
       repository_(repository),
       nnet_to_update_(nnet_to_update),
       nnet_to_update_orig_(nnet_to_update),
       stats_ptr_(stats) { }
DiscTrainParallelClass (const DiscTrainParallelClass & other) inline
Definition at line 123 of file nnet-compute-discriminative-parallel.cc.
References DiscTrainParallelClass::nnet_to_update_, Nnet::SetZero(), and DiscTrainParallelClass::store_separate_gradients_.
                                                              :
   am_nnet_(other.am_nnet_), tmodel_(other.tmodel_), opts_(other.opts_),
   store_separate_gradients_(other.store_separate_gradients_),
   repository_(other.repository_), nnet_to_update_(other.nnet_to_update_),
   nnet_to_update_orig_(other.nnet_to_update_orig_),
   stats_ptr_(other.stats_ptr_) {
     if (store_separate_gradients_) {
       // To ensure correctness, we work on separate copies of the gradient
       // object, which we'll sum at the end.  This is used for exact gradient
       // computation.
       if (other.nnet_to_update_ != NULL) {
         nnet_to_update_ = new Nnet(*(other.nnet_to_update_));
         // our "nnet_to_update_" variable is a copy of the neural network
         // we are to update (presumably a gradient).  If we don't set these
         // to zero we would end up adding multiple copies of the any initial
         // gradient that "nnet_to_update_" contained when we initialize
         // the first instance of the class.
         nnet_to_update_->SetZero(true);
       } else { // support case where we don't really need a gradient.
         nnet_to_update_ = NULL;
       }
     }
   }
~DiscTrainParallelClass () inline
Definition at line 163 of file nnet-compute-discriminative-parallel.cc.
References NnetDiscriminativeStats::Add(), Nnet::AddNnet(), DiscTrainParallelClass::nnet_to_update_, DiscTrainParallelClass::nnet_to_update_orig_, DiscTrainParallelClass::stats_, and DiscTrainParallelClass::stats_ptr_.
{
     if (nnet_to_update_orig_ != nnet_to_update_) {
       // This branch is only taken if this instance of the class is
       // one of the multiple instances allocated inside the RunMultiThreaded
       // template function, *and* store_separate_gradients_ has been set to true.
       // In the typical hogwild case, we don't do this.
       nnet_to_update_orig_->AddNnet(1.0, *nnet_to_update_);
       delete nnet_to_update_;
     }
     stats_ptr_->Add(stats_);
   }
Member Function Documentation
void operator() () inline virtual
Implements MultiThreadable.
Definition at line 147 of file nnet-compute-discriminative-parallel.cc.
References DiscTrainParallelClass::am_nnet_, NnetDiscriminativeUpdateOptions::criterion, kaldi::GetVerboseLevel(), KALDI_VLOG, DiscTrainParallelClass::nnet_to_update_, kaldi::nnet2::NnetDiscriminativeUpdate(), DiscTrainParallelClass::opts_, NnetDiscriminativeStats::Print(), DiscriminativeExamplesRepository::ProvideExample(), DiscTrainParallelClass::repository_, DiscTrainParallelClass::stats_, MultiThreadable::thread_id_, and DiscTrainParallelClass::tmodel_.
                       {
     DiscriminativeNnetExample *example;
     while ((example = repository_->ProvideExample()) != NULL) {
       // This is a function call to a function defined in
       // nnet-compute-discriminative.h
       NnetDiscriminativeUpdate(am_nnet_, tmodel_, opts_,
                                *example, nnet_to_update_, &stats_);
       delete example;
       if (GetVerboseLevel() > 3) {
         KALDI_VLOG(3) << "Printing local stats for thread " << thread_id_;
         stats_.Print(opts_.criterion);
       }
     }
   }
Member Data Documentation
const AmNnet& am_nnet_ private
Definition at line 175 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::operator()().
Nnet* nnet_to_update_ private
Definition at line 180 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::DiscTrainParallelClass(), DiscTrainParallelClass::operator()(), and DiscTrainParallelClass::~DiscTrainParallelClass().
Nnet* nnet_to_update_orig_ private
Definition at line 181 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::~DiscTrainParallelClass().
const NnetDiscriminativeUpdateOptions& opts_ private
Definition at line 177 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::operator()().
DiscriminativeExamplesRepository* repository_ private
Definition at line 179 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::operator()().
NnetDiscriminativeStats stats_ private
Definition at line 183 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::operator()(), and DiscTrainParallelClass::~DiscTrainParallelClass().
NnetDiscriminativeStats* stats_ptr_ private
Definition at line 182 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::~DiscTrainParallelClass().
bool store_separate_gradients_ private
Definition at line 178 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::DiscTrainParallelClass().
const TransitionModel& tmodel_ private
Definition at line 176 of file nnet-compute-discriminative-parallel.cc.
Referenced by DiscTrainParallelClass::operator()().
The documentation for this class was generated from the following file:
nnet2/nnet-compute-discriminative-parallel.cc