Kaldi: Matrix< Real > Class Template Reference
Matrix< Real > Class Template Reference
%Matrix and vector classes
A class for storing matrices.
#include <kaldi-matrix.h>
Public Member Functions
Matrix ()
Empty constructor.
Matrix (const MatrixIndexT r, const MatrixIndexT c, MatrixResizeType resize_type=kSetZero)
Basic constructor.
template<typename OtherReal >
Matrix (const CuMatrixBase< OtherReal > &cu, MatrixTransposeType trans=kNoTrans)
Copy constructor from CUDA matrix This is defined in ../cudamatrix/cu-matrix.h.
void Swap (Matrix< Real > *other)
Swaps the contents of *this and *other. Shallow swap.
void Swap (CuMatrix< Real > *mat)
Defined in ../cudamatrix/cu-matrix.cc.
Matrix (const MatrixBase< Real > &M, MatrixTransposeType trans=kNoTrans)
Constructor from any MatrixBase.
Matrix (const Matrix< Real > &M)
Same as above, but need to avoid default copy constructor.
template<typename OtherReal >
Matrix (const MatrixBase< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy constructor: as above, but from another type.
template<typename OtherReal >
Matrix (const SpMatrix< OtherReal > &M)
Copy constructor taking SpMatrix...
Matrix (const CompressedMatrix &C)
Constructor from CompressedMatrix.
template<typename OtherReal >
Matrix (const TpMatrix< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy constructor taking TpMatrix...
void Read (std::istream &in, bool binary, bool add=false)
read from stream.
void RemoveRow (MatrixIndexT i)
Remove a specified row.
void Transpose ()
Transpose the matrix.
~Matrix ()
Distructor to free matrices.
void Resize (const MatrixIndexT r, const MatrixIndexT c, MatrixResizeType resize_type=kSetZero)
Sets matrix to a specified size (zero is OK as long as both r and c are zero).
Matrix< Real > & operator= (const MatrixBase< Real > &other)
Assignment operator that takes MatrixBase.
Matrix< Real > & operator= (const Matrix< Real > &other)
Assignment operator. Needed for inclusion in std::vector.
Public Member Functions inherited from MatrixBase< Real >
MatrixIndexT NumRows () const
Returns number of rows (or zero for emtpy matrix).
MatrixIndexT NumCols () const
Returns number of columns (or zero for emtpy matrix).
MatrixIndexT Stride () const
Stride (distance in memory between each row). Will be >= NumCols.
size_t SizeInBytes () const
Returns size in bytes of the data held by the matrix.
const Real * Data () const
Gives pointer to raw data (const).
Real * Data ()
Gives pointer to raw data (non-const).
Real * RowData (MatrixIndexT i)
Returns pointer to data for one row (non-const)
const Real * RowData (MatrixIndexT i) const
Returns pointer to data for one row (const)
Real & operator() (MatrixIndexT r, MatrixIndexT c)
Indexing operator, non-const (only checks sizes if compiled with -DKALDI_PARANOID)
Real & Index (MatrixIndexT r, MatrixIndexT c)
Indexing operator, provided for ease of debugging (gdb doesn't work with parenthesis operator).
const Real operator() (MatrixIndexT r, MatrixIndexT c) const
Indexing operator, const (only checks sizes if compiled with -DKALDI_PARANOID)
void SetZero ()
Sets matrix to zero.
void Set (Real)
Sets all elements to a specific value.
void SetUnit ()
Sets to zero, except ones along diagonal [for non-square matrices too].
void SetRandn ()
Sets to random values of a normal distribution.
void SetRandUniform ()
Sets to numbers uniformly distributed on (0, 1)
template<typename OtherReal >
void CopyFromMat (const MatrixBase< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy given matrix. (no resize is done).
void CopyFromMat (const CompressedMatrix &M)
Copy from compressed matrix.
template<typename OtherReal >
void CopyFromSp (const SpMatrix< OtherReal > &M)
Copy given spmatrix. (no resize is done).
template<typename OtherReal >
void CopyFromTp (const TpMatrix< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy given tpmatrix. (no resize is done).
template<typename OtherReal >
void CopyFromMat (const CuMatrixBase< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy from CUDA matrix. Implemented in ../cudamatrix/cu-matrix.h.
void CopyRowsFromVec (const VectorBase< Real > &v)
This function has two modes of operation.
void CopyRowsFromVec (const CuVectorBase< Real > &v)
This version of CopyRowsFromVec is implemented in ../cudamatrix/cu-vector.cc.
template<typename OtherReal >
void CopyRowsFromVec (const VectorBase< OtherReal > &v)
void CopyColsFromVec (const VectorBase< Real > &v)
Copies vector into matrix, column-by-column.
void CopyColFromVec (const VectorBase< Real > &v, const MatrixIndexT col)
Copy vector into specific column of matrix.
void CopyRowFromVec (const VectorBase< Real > &v, const MatrixIndexT row)
Copy vector into specific row of matrix.
void CopyDiagFromVec (const VectorBase< Real > &v)
Copy vector into diagonal of matrix.
const SubVector< Real > Row (MatrixIndexT i) const
Return specific row of matrix [const].
SubVector< Real > Row (MatrixIndexT i)
Return specific row of matrix.
SubMatrix< Real > Range (const MatrixIndexT row_offset, const MatrixIndexT num_rows, const MatrixIndexT col_offset, const MatrixIndexT num_cols) const
Return a sub-part of matrix.
SubMatrix< Real > RowRange (const MatrixIndexT row_offset, const MatrixIndexT num_rows) const
SubMatrix< Real > ColRange (const MatrixIndexT col_offset, const MatrixIndexT num_cols) const
Real Sum () const
Returns sum of all elements in matrix.
Real Trace (bool check_square=true) const
Returns trace of matrix.
Real Max () const
Returns maximum element of matrix.
Real Min () const
Returns minimum element of matrix.
void MulElements (const MatrixBase< Real > &A)
Element by element multiplication with a given matrix.
void DivElements (const MatrixBase< Real > &A)
Divide each element by the corresponding element of a given matrix.
void Scale (Real alpha)
Multiply each element with a scalar value.
void Max (const MatrixBase< Real > &A)
Set, element-by-element, *this = max(*this, A)
void MulColsVec (const VectorBase< Real > &scale)
Equivalent to (*this) = (*this) * diag(scale).
void MulRowsVec (const VectorBase< Real > &scale)
Equivalent to (*this) = diag(scale) * (*this).
void MulRowsGroupMat (const MatrixBase< Real > &src)
Divide each row into src.NumCols() equal groups, and then scale i'th row's j'th group of elements by src(i, j).
Real LogDet (Real *det_sign=NULL) const
Returns logdet of matrix.
void Invert (Real *log_det=NULL, Real *det_sign=NULL, bool inverse_needed=true)
matrix inverse.
void InvertDouble (Real *LogDet=NULL, Real *det_sign=NULL, bool inverse_needed=true)
matrix inverse [double].
void InvertElements ()
Inverts all the elements of the matrix.
void Transpose ()
Transpose the matrix.
void CopyCols (const MatrixBase< Real > &src, const MatrixIndexT *indices)
Copies column r from column indices[r] of src.
void CopyRows (const MatrixBase< Real > &src, const MatrixIndexT *indices)
Copies row r from row indices[r] of src (does nothing As a special case, if indexes[i] == -1, sets row i to zero.
void AddCols (const MatrixBase< Real > &src, const MatrixIndexT *indices)
Add column indices[r] of src to column r.
void CopyRows (const Real *const *src)
Copies row r of this matrix from an array of floats at the location given by src[r].
void CopyToRows (Real *const *dst) const
Copies row r of this matrix to the array of floats at the location given by dst[r].
void AddRows (Real alpha, const MatrixBase< Real > &src, const MatrixIndexT *indexes)
Does for each row r, this.Row(r) += alpha * src.row(indexes[r]).
void AddRows (Real alpha, const Real *const *src)
Does for each row r, this.Row(r) += alpha * src[r], treating src[r] as the beginning of a region of memory representing a vector of floats, of the same length as this.NumCols().
void AddToRows (Real alpha, Real *const *dst) const
For each row r of this matrix, adds it (times alpha) to the array of floats at the location given by dst[r].
void ApplyFloor (Real floor_val)
Applies floor to all matrix elements.
void ApplyCeiling (Real ceiling_val)
Applies floor to all matrix elements.
void ApplyLog ()
Calculates log of all the matrix elemnts.
void ApplyExp ()
Exponentiate each of the elements.
void ApplyPow (Real power)
Applies power to all matrix elements.
void ApplyPowAbs (Real power, bool include_sign=false)
Apply power to the absolute value of each element.
void ApplyHeaviside ()
Applies the Heaviside step function (x > 0 ? 1 : 0) to all matrix elements Note: in general you can make different choices for x = 0, but for now please leave it as it (i.e.
void Eig (MatrixBase< Real > *P, VectorBase< Real > *eigs_real, VectorBase< Real > *eigs_imag) const
Eigenvalue Decomposition of a square NxN matrix into the form (*this) = P D P^{-1}.
bool Power (Real pow)
The Power method attempts to take the matrix to a power using a method that works in general for fractional and negative powers.
void DestructiveSvd (VectorBase< Real > *s, MatrixBase< Real > *U, MatrixBase< Real > *Vt)
Singular value decomposition Major limitations: For nonsquare matrices, we assume m>=n (NumRows >= NumCols), and we return the "skinny" Svd, i.e.
void Svd (VectorBase< Real > *s, MatrixBase< Real > *U, MatrixBase< Real > *Vt) const
Compute SVD (*this) = U diag(s) Vt.
void Svd (VectorBase< Real > *s) const
Compute SVD but only retain the singular values.
Real MinSingularValue () const
Returns smallest singular value.
void TestUninitialized () const
Real Cond () const
Returns condition number by computing Svd.
bool IsSymmetric (Real cutoff=1.0e-05) const
Returns true if matrix is Symmetric.
bool IsDiagonal (Real cutoff=1.0e-05) const
Returns true if matrix is Diagonal.
bool IsUnit (Real cutoff=1.0e-05) const
Returns true if the matrix is all zeros, except for ones on diagonal.
bool IsZero (Real cutoff=1.0e-05) const
Returns true if matrix is all zeros.
Real FrobeniusNorm () const
Frobenius norm, which is the sqrt of sum of square elements.
bool ApproxEqual (const MatrixBase< Real > &other, float tol=0.01) const
Returns true if ((*this)-other).FrobeniusNorm() <= tol * (*this).FrobeniusNorm().
bool Equal (const MatrixBase< Real > &other) const
Tests for exact equality. It's usually preferable to use ApproxEqual.
Real LargestAbsElem () const
largest absolute value.
Real LogSumExp (Real prune=-1.0) const
Returns log(sum(exp())) without exp overflow If prune > 0.0, it uses a pruning beam, discarding terms less than (max - prune).
Real ApplySoftMax ()
Apply soft-max to the collection of all elements of the matrix and return normalizer (log sum of exponentials).
void Sigmoid (const MatrixBase< Real > &src)
Set each element to the sigmoid of the corresponding element of "src".
void SoftHinge (const MatrixBase< Real > &src)
Set each element to y = log(1 + exp(x))
void GroupPnorm (const MatrixBase< Real > &src, Real power)
Apply the function y(i) = (sum_{j = i*G}^{(i+1)*G-1} x_j^(power))^(1 / p).
void GroupPnormDeriv (const MatrixBase< Real > &input, const MatrixBase< Real > &output, Real power)
Calculate derivatives for the GroupPnorm function above...
void GroupMax (const MatrixBase< Real > &src)
Apply the function y(i) = (max_{j = i*G}^{(i+1)*G-1} x_j Requires src.NumRows() == this->NumRows() and src.NumCols() % this->NumCols() == 0.
void GroupMaxDeriv (const MatrixBase< Real > &input, const MatrixBase< Real > &output)
Calculate derivatives for the GroupMax function above, where "input" is the input to the GroupMax function above (i.e.
void Tanh (const MatrixBase< Real > &src)
Set each element to the tanh of the corresponding element of "src".
void DiffSigmoid (const MatrixBase< Real > &value, const MatrixBase< Real > &diff)
void DiffTanh (const MatrixBase< Real > &value, const MatrixBase< Real > &diff)
void SymPosSemiDefEig (VectorBase< Real > *s, MatrixBase< Real > *P, Real check_thresh=0.001)
Uses Svd to compute the eigenvalue decomposition of a symmetric positive semi-definite matrix: (*this) = rP * diag(rS) * rP^T, with rP an orthogonal matrix so rP^{-1} = rP^T.
void Add (const Real alpha)
Add a scalar to each element.
void AddToDiag (const Real alpha)
Add a scalar to each diagonal element.
template<typename OtherReal >
void AddVecVec (const Real alpha, const VectorBase< OtherReal > &a, const VectorBase< OtherReal > &b)
*this += alpha * a * b^T
template<typename OtherReal >
void AddVecToRows (const Real alpha, const VectorBase< OtherReal > &v)
[each row of *this] += alpha * v
template<typename OtherReal >
void AddVecToCols (const Real alpha, const VectorBase< OtherReal > &v)
[each col of *this] += alpha * v
void AddMat (const Real alpha, const MatrixBase< Real > &M, MatrixTransposeType transA=kNoTrans)
*this += alpha * M [or M^T]
void SymAddMat2 (const Real alpha, const MatrixBase< Real > &M, MatrixTransposeType transA, Real beta)
*this = beta * *this + alpha * M M^T, for symmetric matrices.
void AddDiagVecMat (const Real alpha, const VectorBase< Real > &v, const MatrixBase< Real > &M, MatrixTransposeType transM, Real beta=1.0)
*this = beta * *this + alpha * diag(v) * M [or M^T].
void AddMatDiagVec (const Real alpha, const MatrixBase< Real > &M, MatrixTransposeType transM, VectorBase< Real > &v, Real beta=1.0)
*this = beta * *this + alpha * M [or M^T] * diag(v) The same as adding M but scaling each column M_j by v(j).
void AddMatMatElements (const Real alpha, const MatrixBase< Real > &A, const MatrixBase< Real > &B, const Real beta)
*this = beta * *this + alpha * A .* B (.* element by element multiplication)
void AddVecMatPointMulVec (const Real alpha, const MatrixBase< Real > &A, const MatrixBase< Real > &B, const Real beta, MatrixIndexT batch_index)
sc function element of vector multiply rows vector of matrix
template<typename OtherReal >
void AddSp (const Real alpha, const SpMatrix< OtherReal > &S)
*this += alpha * S
void AddMatMat (const Real alpha, const MatrixBase< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
void AddMatMatDivMat (const MatrixBase< Real > &A, const MatrixBase< Real > &B, const MatrixBase< Real > &C)
*this = a * b / c (by element; when c = 0, *this = a)
void AddMatSmat (const Real alpha, const MatrixBase< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
A version of AddMatMat specialized for when the second argument contains a lot of zeroes.
void AddSmatMat (const Real alpha, const MatrixBase< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
A version of AddMatMat specialized for when the first argument contains a lot of zeroes.
void AddMatMatMat (const Real alpha, const MatrixBase< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const MatrixBase< Real > &C, MatrixTransposeType transC, const Real beta)
this <– beta*this + alpha*A*B*C.
void AddSpMat (const Real alpha, const SpMatrix< Real > &A, const MatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*SpA*B.
void AddTpMat (const Real alpha, const TpMatrix< Real > &A, MatrixTransposeType transA, const MatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void AddMatSp (const Real alpha, const MatrixBase< Real > &A, MatrixTransposeType transA, const SpMatrix< Real > &B, const Real beta)
this <– beta*this + alpha*A*B.
void AddSpMatSp (const Real alpha, const SpMatrix< Real > &A, const MatrixBase< Real > &B, MatrixTransposeType transB, const SpMatrix< Real > &C, const Real beta)
this <– beta*this + alpha*A*B*C.
void AddMatTp (const Real alpha, const MatrixBase< Real > &A, MatrixTransposeType transA, const TpMatrix< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void AddTpTp (const Real alpha, const TpMatrix< Real > &A, MatrixTransposeType transA, const TpMatrix< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void AddSpSp (const Real alpha, const SpMatrix< Real > &A, const SpMatrix< Real > &B, const Real beta)
this <– beta*this + alpha*A*B.
void CopyLowerToUpper ()
Copy lower triangle to upper triangle (symmetrize)
void CopyUpperToLower ()
Copy upper triangle to lower triangle (symmetrize)
void OrthogonalizeRows ()
This function orthogonalizes the rows of a matrix using the Gram-Schmidt process.
void Read (std::istream &in, bool binary, bool add=false)
stream read.
void Write (std::ostream &out, bool binary) const
write to stream.
void LapackGesvd (VectorBase< Real > *s, MatrixBase< Real > *U, MatrixBase< Real > *Vt)
template<>
void AddVecVec (const float alpha, const VectorBase< float > &ra, const VectorBase< float > &rb)
template<>
void AddVecVec (const double alpha, const VectorBase< double > &ra, const VectorBase< double > &rb)
template<>
void AddVecVec (const float alpha, const VectorBase< float > &a, const VectorBase< float > &rb)
template<>
void AddVecVec (const double alpha, const VectorBase< double > &a, const VectorBase< double > &rb)
template<>
void CopyFromSp (const SpMatrix< float > &M)
template<>
void CopyFromSp (const SpMatrix< double > &M)
Private Member Functions
void Destroy ()
Deallocates memory and sets to empty matrix (dimension 0, 0).
void Init (const MatrixIndexT r, const MatrixIndexT c)
Init assumes the current class contents are invalid (i.e.
Additional Inherited Members
Protected Member Functions inherited from MatrixBase< Real >
MatrixBase (Real *data, MatrixIndexT cols, MatrixIndexT rows, MatrixIndexT stride)
Initializer, callable only from child.
MatrixBase ()
Initializer, callable only from child.
~MatrixBase ()
Real * Data_workaround () const
A workaround that allows SubMatrix to get a pointer to non-const data for const Matrix.
Protected Attributes inherited from MatrixBase< Real >
Real * data_
data memory area
MatrixIndexT num_cols_
these atributes store the real matrix size as it is stored in memory including memalignment
MatrixIndexT num_rows_
< Number of columns
MatrixIndexT stride_
< Number of rows
Detailed Description
template<typename Real>
class kaldi::Matrix< Real >
A class for storing matrices.
Definition at line 742 of file kaldi-matrix.h.
Constructor & Destructor Documentation
Matrix ()
Empty constructor.
Definition at line 29 of file kaldi-matrix-inl.h.
 : MatrixBase<Real>(NULL, 0, 0, 0) { }
Matrix (const MatrixIndexT r, const MatrixIndexT c, MatrixResizeType resize_type = kSetZero) inline
Basic constructor.
Sets to zero by default. if set_zero == false, memory contents are undefined.
Definition at line 750 of file kaldi-matrix.h.
                                                  :
       MatrixBase<Real>() { Resize(r, c, resize_type); }
Matrix (const CuMatrixBase< OtherReal > & cu, MatrixTransposeType trans = kNoTrans) explicit
Copy constructor from CUDA matrix This is defined in ../cudamatrix/cu-matrix.h.
Definition at line 798 of file cu-matrix.h.
References kaldi::kNoTrans.
{
   if (trans == kNoTrans) Init(M.NumRows(), M.NumCols());
   else Init(M.NumCols(), M.NumRows());
   M.CopyToMat(this, trans);
 }
Matrix (const MatrixBase< Real > & M, MatrixTransposeType trans = kNoTrans) explicit
Constructor from any MatrixBase.
Can also copy with transpose. Allocates new memory.
Definition at line 612 of file kaldi-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::num_cols_, MatrixBase< Real >::num_rows_, and Matrix< Real >::Resize().
     : MatrixBase<Real>() {
   if (trans == kNoTrans) {
     Resize(M.num_rows_, M.num_cols_);
     this->CopyFromMat(M);
   } else {
     Resize(M.num_cols_, M.num_rows_);
     this->CopyFromMat(M, kTrans);
   }
 }
Matrix (const Matrix< Real > & M)
Same as above, but need to avoid default copy constructor.
Definition at line 626 of file kaldi-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), MatrixBase< Real >::num_cols_, MatrixBase< Real >::num_rows_, and Matrix< Real >::Resize().
                                            :
     MatrixBase<Real>() {
   Resize(M.num_rows_, M.num_cols_);
   this->CopyFromMat(M);
 }
Matrix (const MatrixBase< OtherReal > & M, MatrixTransposeType trans = kNoTrans) explicit
Copy constructor: as above, but from another type.
Copy constructor from another type.
Definition at line 635 of file kaldi-matrix.cc.
References MatrixBase< Real >::CopyFromMat(), kaldi::kNoTrans, kaldi::kTrans, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and Matrix< Real >::Resize().
                                                 : MatrixBase<Real>() {
   if (trans == kNoTrans) {
     Resize(M.NumRows(), M.NumCols());
     this->CopyFromMat(M);
   } else {
     Resize(M.NumCols(), M.NumRows());
     this->CopyFromMat(M, kTrans);
   }
 }
Matrix (const SpMatrix< OtherReal > & M) inline explicit
Copy constructor taking SpMatrix...
It is symmetric, so no option for transpose, and NumRows == Cols
Definition at line 783 of file kaldi-matrix.h.
                                                  : MatrixBase<Real>() {
     Resize(M.NumRows(), M.NumRows(), kUndefined);
     this->CopyFromSp(M);
   }
Matrix (const CompressedMatrix< Real > & C) explicit
Constructor from CompressedMatrix.
Definition at line 1900 of file kaldi-matrix.cc.
References CompressedMatrix::CopyToMat(), kaldi::kUndefined, CompressedMatrix::NumCols(), CompressedMatrix::NumRows(), and Matrix< Real >::Resize().
                                              : MatrixBase<Real>() {
   Resize(M.NumRows(), M.NumCols(), kUndefined);
   M.CopyToMat(this);
 }
Matrix (const TpMatrix< OtherReal > & M, MatrixTransposeType trans = kNoTrans) inline explicit
Copy constructor taking TpMatrix...
Definition at line 793 of file kaldi-matrix.h.
                                                         : MatrixBase<Real>() {
     if (trans == kNoTrans) {
       Resize(M.NumRows(), M.NumCols(), kUndefined);
       this->CopyFromTp(M);
     } else {
       Resize(M.NumCols(), M.NumRows(), kUndefined);
       this->CopyFromTp(M, kTrans);
     }
   }
~Matrix () inline
Distructor to free matrices.
Definition at line 816 of file kaldi-matrix.h.
 { Destroy(); }
Member Function Documentation
void Destroy () private
Deallocates memory and sets to empty matrix (dimension 0, 0).
Definition at line 999 of file kaldi-matrix.cc.
Referenced by Matrix< BaseFloat >::~Matrix().
{
   // we need to free the data block if it was defined
   if (NULL != MatrixBase<Real>::data_)
     KALDI_MEMALIGN_FREE( MatrixBase<Real>::data_);
   MatrixBase<Real>::data_ = NULL;
   MatrixBase<Real>::num_rows_ = MatrixBase<Real>::num_cols_
       = MatrixBase<Real>::stride_ = 0;
 }
void Init (const MatrixIndexT r, const MatrixIndexT c) inline private
Init assumes the current class contents are invalid (i.e.
junk or have already been freed), and it sets the matrix to newly allocated memory with the specified number of rows and columns. r == c == 0 is acceptable. The data memory contents will be undefined.
Definition at line 655 of file kaldi-matrix.cc.
References KALDI_ASSERT.
{
   if (rows * cols == 0) {
     KALDI_ASSERT(rows == 0 && cols == 0);
     this->num_rows_ = 0;
     this->num_cols_ = 0;
     this->stride_ = 0;
     this->data_ = NULL;
     return;
   }
   KALDI_ASSERT(rows > 0 && cols > 0);
   // initialize some helping vars
   MatrixIndexT skip;
   MatrixIndexT real_cols;
   size_t size;
   void *data;  // aligned memory block
   void *temp;  // memory block to be really freed
   // compute the size of skip and real cols
   skip = ((16 / sizeof(Real)) - cols % (16 / sizeof(Real)))
       % (16 / sizeof(Real));
   real_cols = cols + skip;
   size = static_cast<size_t>(rows) * static_cast<size_t>(real_cols)
       * sizeof(Real);
   // allocate the memory and set the right dimensions and parameters
   if (NULL != (data = KALDI_MEMALIGN(16, size, &temp))) {
     MatrixBase<Real>::data_        = static_cast<Real *> (data);
     MatrixBase<Real>::num_rows_      = rows;
     MatrixBase<Real>::num_cols_      = cols;
     MatrixBase<Real>::stride_  = real_cols;
   } else {
     throw std::bad_alloc();
   }
 }
Matrix<Real>& operator= (const MatrixBase< Real > & other) inline
Assignment operator that takes MatrixBase.
Definition at line 830 of file kaldi-matrix.h.
{
     if (MatrixBase<Real>::NumRows() != other.NumRows() ||
         MatrixBase<Real>::NumCols() != other.NumCols())
       Resize(other.NumRows(), other.NumCols(), kUndefined);
     MatrixBase<Real>::CopyFromMat(other);
     return *this;
   }
Matrix<Real>& operator= (const Matrix< Real > & other) inline
Assignment operator. Needed for inclusion in std::vector.
Definition at line 839 of file kaldi-matrix.h.
{
     if (MatrixBase<Real>::NumRows() != other.NumRows() ||
         MatrixBase<Real>::NumCols() != other.NumCols())
       Resize(other.NumRows(), other.NumCols(), kUndefined);
     MatrixBase<Real>::CopyFromMat(other);
     return *this;
   }
void Read (std::istream & in, bool binary, bool add = false)
read from stream.
Definition at line 1297 of file kaldi-matrix.cc.
References CompressedMatrix::CopyToMat(), rnnlm::i, rnnlm::j, KALDI_ERR, KALDI_STRCASECMP, KALDI_WARN, MatrixBase< Real >::num_cols_, MatrixBase< Real >::num_rows_, MatrixBase< Real >::NumCols(), CompressedMatrix::NumCols(), MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), kaldi::Peek(), CompressedMatrix::Read(), Matrix< Real >::Read(), kaldi::ReadBasicType(), and kaldi::ReadToken().
Referenced by main(), kaldi::operator>>(), AffineXformStats::Read(), CompressedAffineXformStats::Read(), LogisticRegression::Read(), CompressedMatrix::Read(), AccumFullGmm::Read(), LdaEstimate::Read(), SgmmFmllrGlobalParams::Read(), Sgmm2FmllrGlobalParams::Read(), GaussClusterable::Read(), FmpeStats::Read(), Plda::Read(), AccumDiagGmm::Read(), AmSgmm::Read(), FullGmm::Read(), MleAmSgmm2Accs::Read(), DiagGmm::Read(), DiscriminativeNnetExample::Read(), Fmpe::Read(), OnlineCmvnState::Read(), AmSgmm2::Read(), GeneralMatrix::Read(), IvectorExtractor::Read(), IvectorExtractorStats::Read(), MatrixBase< Real >::Read(), CuMatrix< Real >::Read(), Matrix< Real >::Read(), KlHmm::ReadData(), kaldi::TypeThreeUsage(), kaldi::UnitTestCompressedMatrix(), kaldi::UnitTestComputeGPE(), kaldi::UnitTestIo(), and kaldi::UnitTestIoCross().
{
   if (add) {
     Matrix<Real> tmp;
     tmp.Read(is, binary, false);  // read without adding.
     if (this->num_rows_ == 0) this->Resize(tmp.num_rows_, tmp.num_cols_);
     else {
       if (this->num_rows_ != tmp.num_rows_ || this->num_cols_ != tmp.num_cols_) {
         if (tmp.num_rows_ == 0) return;  // do nothing in this case.
         else KALDI_ERR << "Matrix::Read, size mismatch "
                        << this->num_rows_ <<  ", " << this->num_cols_
                        << " vs. " << tmp.num_rows_ << ", " << tmp.num_cols_;
       }
     }
     this->AddMat(1.0, tmp);
     return;
   }
   // now assume add == false.
   MatrixIndexT pos_at_start = is.tellg();
   std::ostringstream specific_error;
   if (binary) {  // Read in binary mode.
     int peekval = Peek(is, binary);
     if (peekval == 'C') {
       // This code enable us to read CompressedMatrix as a regular matrix.
       CompressedMatrix compressed_mat;
       compressed_mat.Read(is, binary); // at this point, add == false.
       this->Resize(compressed_mat.NumRows(), compressed_mat.NumCols());
       compressed_mat.CopyToMat(this);
       return;
     }
     const char *my_token =  (sizeof(Real) == 4 ? "FM" : "DM");
     char other_token_start = (sizeof(Real) == 4 ? 'D' : 'F');
     if (peekval == other_token_start) {  // need to instantiate the other type to read it.
       typedef typename OtherReal<Real>::Real OtherType;  // if Real == float, OtherType == double, and vice versa.
       Matrix<OtherType> other(this->num_rows_, this->num_cols_);
       other.Read(is, binary, false);  // add is false at this point anyway.
       this->Resize(other.NumRows(), other.NumCols());
       this->CopyFromMat(other);
       return;
     }
     std::string token;
     ReadToken(is, binary, &token);
     if (token != my_token) {
       specific_error << ": Expected token " << my_token << ", got " << token;
       goto bad;
     }
     int32 rows, cols;
     ReadBasicType(is, binary, &rows);  // throws on error.
     ReadBasicType(is, binary, &cols);  // throws on error.
     if ((MatrixIndexT)rows != this->num_rows_ || (MatrixIndexT)cols != this->num_cols_) {
       this->Resize(rows, cols);
     }
     if (this->Stride() == this->NumCols() && rows*cols!=0) {
       is.read(reinterpret_cast<char*>(this->Data()),
               sizeof(Real)*rows*cols);
       if (is.fail()) goto bad;
     } else {
       for (MatrixIndexT i = 0; i < (MatrixIndexT)rows; i++) {
         is.read(reinterpret_cast<char*>(this->RowData(i)), sizeof(Real)*cols);
         if (is.fail()) goto bad;
       }
     }
     if (is.eof()) return;
     if (is.fail()) goto bad;
     return;
   } else {  // Text mode.
     std::string str;
     is >> str; // get a token
     if (is.fail()) { specific_error << ": Expected \"[\", got EOF"; goto bad; }
     // if ((str.compare("DM") == 0) || (str.compare("FM") == 0)) {  // Back compatibility.
     // is >> str;  // get #rows
     //  is >> str;  // get #cols
     //  is >> str;  // get "["
     // }
     if (str == "[]") { Resize(0, 0); return; } // Be tolerant of variants.
     else if (str != "[") {
       specific_error << ": Expected \"[\", got \"" << str << '"';
       goto bad;
     }
     // At this point, we have read "[".
     std::vector<std::vector<Real>* > data;
     std::vector<Real> *cur_row = new std::vector<Real>;
     while (1) {
       int i = is.peek();
       if (i == -1) { specific_error << "Got EOF while reading matrix data"; goto cleanup; }
       else if (static_cast<char>(i) == ']') {  // Finished reading matrix.
         is.get();  // eat the "]".
         i = is.peek();
         if (static_cast<char>(i) == '\r') {
           is.get();
           is.get();  // get \r\n (must eat what we wrote)
         } else if (static_cast<char>(i) == '\n') { is.get(); } // get \n (must eat what we wrote)
         if (is.fail()) {
           KALDI_WARN << "After end of matrix data, read error.";
           // we got the data we needed, so just warn for this error.
         }
         // Now process the data.
         if (!cur_row->empty()) data.push_back(cur_row);
         else delete(cur_row);
         if (data.empty()) { this->Resize(0, 0); return; }
         else {
           int32 num_rows = data.size(), num_cols = data[0]->size();
           this->Resize(num_rows, num_cols);
           for (int32 i = 0; i < num_rows; i++) {
             if (static_cast<int32>(data[i]->size()) != num_cols) {
               specific_error << "Matrix has inconsistent #cols: " << num_cols
                              << " vs." << data[i]->size() << " (processing row"
                              << i;
               goto cleanup;
             }
             for (int32 j = 0; j < num_cols; j++)
               (*this)(i, j) = (*(data[i]))[j];
             delete data[i];
           }
         }
         return;
       } else if (static_cast<char>(i) == '\n' || static_cast<char>(i) == ';') {
         // End of matrix row.
         is.get();
         if (cur_row->size() != 0) {
           data.push_back(cur_row);
           cur_row = new std::vector<Real>;
           cur_row->reserve(data.back()->size());
         }
       } else if ( (i >= '0' && i <= '9') || i == '-' ) {  // A number...
         Real r;
         is >> r;
         if (is.fail()) {
           specific_error << "Stream failure/EOF while reading matrix data.";
           goto cleanup;
         }
         cur_row->push_back(r);
       } else if (isspace(i)) {
         is.get();  // eat the space and do nothing.
       } else {  // NaN or inf or error.
         std::string str;
         is >> str;
         if (!KALDI_STRCASECMP(str.c_str(), "inf") ||
             !KALDI_STRCASECMP(str.c_str(), "infinity")) {
           cur_row->push_back(std::numeric_limits<Real>::infinity());
           KALDI_WARN << "Reading infinite value into matrix.";
         } else if (!KALDI_STRCASECMP(str.c_str(), "nan")) {
           cur_row->push_back(std::numeric_limits<Real>::quiet_NaN());
           KALDI_WARN << "Reading NaN value into matrix.";
         } else {
           specific_error << "Expecting numeric matrix data, got " << str;
           goto cleanup;
         }
       }
     }
     // Note, we never leave the while () loop before this
     // line (we return from it.)
  cleanup: // We only reach here in case of error in the while loop above.
     delete cur_row;
     for (size_t i = 0; i < data.size(); i++)
       delete data[i];
     // and then go on to "bad" below, where we print error.
   }
 bad:
   KALDI_ERR << "Failed to read matrix from stream.  " << specific_error.str()
             << " File position at start is "
             << pos_at_start << ", currently " << is.tellg();
 }
void RemoveRow (MatrixIndexT i)
Remove a specified row.
Definition at line 989 of file kaldi-matrix.cc.
References rnnlm::j, and KALDI_ASSERT.
Referenced by FullGmm::Merge(), DiagGmm::Merge(), DiagGmm::RemoveComponent(), FullGmm::RemoveComponent(), and kaldi::UnitTestRemoveRow().
{
   KALDI_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                static_cast<UnsignedMatrixIndexT>(MatrixBase<Real>::num_rows_)
                && "Access out of matrix");
   for (MatrixIndexT j = i + 1; j <  MatrixBase<Real>::num_rows_; j++)
     MatrixBase<Real>::Row(j-1).CopyFromVec( MatrixBase<Real>::Row(j));
   MatrixBase<Real>::num_rows_--;
 }
void Resize (const MatrixIndexT r, const MatrixIndexT c, MatrixResizeType resize_type = kSetZero)
Sets matrix to a specified size (zero is OK as long as both r and c are zero).
The value of the new data depends on resize_type: -if kSetZero, the new data will be zero -if kUndefined, the new data will be undefined -if kCopyData, the new data will be the same as the old data in any shared positions, and zero elsewhere. This function takes time proportional to the number of data elements.
Definition at line 692 of file kaldi-matrix.cc.
References kaldi::kCopyData, kaldi::kSetZero, kaldi::kUndefined, MatrixBase< Real >::Range(), MatrixBase< Real >::SetZero(), kaldi::nnet3::SetZero(), and Matrix< Real >::Swap().
Referenced by DecodableMatrixMappedOffset::AcceptLoglikes(), OnlinePitchFeatureImpl::AcceptWaveform(), LdaEstimate::AddMeanOffset(), kaldi::nnet2::AppendDiscriminativeExamples(), kaldi::AppendFeats(), kaldi::AppendVectorToFeats(), Sgmm2Project::ApplyProjection(), WaveData::Clear(), SgmmPerSpkDerivedVars::Clear(), Sgmm2PerSpkDerivedVars::Clear(), GeneralMatrix::Clear(), SphinxMatrixHolder< kFeatDim >::Clear(), AmSgmm2::ComponentLogLikes(), AmSgmm::ComponentPosteriors(), kaldi::ComposeTransforms(), GeneralMatrix::Compress(), NnetComputerFromEg::Compute(), Spectrogram::Compute(), kaldi::ComputeAmGmmFeatureDeriv(), kaldi::ComputeAndProcessKaldiPitch(), SinusoidDetector::ComputeCoefficients(), kaldi::ComputeDeltas(), IvectorExtractor::ComputeDerivedVars(), kaldi::ComputeFeatureNormalizer(), kaldi::ComputeFeatureNormalizingTransform(), Fmpe::ComputeFeatures(), AmSgmm::ComputeFmllrPreXform(), AmSgmm2::ComputeFmllrPreXform(), DecodableNnet2Online::ComputeForFrame(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), Plp::ComputeInternal(), kaldi::ComputeKaldiPitch(), kaldi::ComputeKaldiPitchFirstPass(), Sgmm2Project::ComputeLdaTransform(), kaldi::ComputePca(), AmSgmm::ComputePerSpkDerivedVars(), AmSgmm2::ComputePerSpkDerivedVars(), Sgmm2Project::ComputeProjection(), kaldi::ComputeShiftedDeltas(), Fmpe::ComputeStddevs(), BasisFmllrEstimate::ComputeTransform(), kaldi::ConcatFeats(), FmllrRawAccs::ConvertToPerRowStats(), CompressedAffineXformStats::CopyFromAffineXformStats(), AmSgmm::CopyGlobalsInitVecs(), kaldi::DetectSinusoids(), DiscriminativeExampleSplitter::DoExcise(), NnetDecodableBase::DoNnetComputation(), LdaEstimate::Estimate(), FeatureTransformEstimateMulti::Estimate(), FeatureTransformEstimate::EstimateInternal(), kaldi::EstimateIvectorsOnline(), FeatureTransformEstimateMulti::EstimateTransformPart(), kaldi::FilterCompressedMatrixRows(), kaldi::FilterMatrixRows(), FmllrRawAccs::FmllrRawAccs(), Fmpe::Fmpe(), kaldi::nnet2::FormatNnetInput(), FullGmm::GetCovarsAndMeans(), kaldi::GetFeatDeriv(), LogisticRegression::GetLogPosteriors(), GeneralMatrix::GetMatrix(), FullGmm::GetMeans(), DiagGmm::GetMeans(), OnlineCmvn::GetMostRecentCachedFrame(), IvectorExtractorStats::GetOrthogonalIvectorTransform(), kaldi::GetOutput(), PldaEstimator::GetOutput(), OnlineCmvn::GetState(), DiagGmm::GetVars(), RegtreeFmllrDiagGmm::GetXformMatrix(), AmSgmm::IncreasePhoneSpaceDim(), AmSgmm2::IncreasePhoneSpaceDim(), AmSgmm2::IncreaseSpkSpaceDim(), kaldi::IncreaseTransformDimension(), AffineXformStats::Init(), LdaEstimate::Init(), FmpeStats::Init(), kaldi::InitCmvnStats(), OnlinePreconditionerSimple::InitDefault(), OnlineNaturalGradientSimple::InitDefault(), kaldi::InitFmllr(), AmSgmm::InitializeFromFullGmm(), AmSgmm2::InitializeFromFullGmm(), AmSgmm::InitializeMw(), AmSgmm2::InitializeMw(), AmSgmm2::InitializeNu(), kaldi::InitIdftBases(), IvectorExtractor::IvectorExtractor(), IvectorExtractorStats::IvectorExtractorStats(), MatrixBase< Real >::LapackGesvd(), kaldi::nnet2::LatticeToDiscriminativeExample(), AffineComponent::LimitRank(), DiagGmm::LogLikelihoods(), main(), Matrix< BaseFloat >::Matrix(), Matrix< Real >::Matrix(), FullGmm::Merge(), DiagGmm::Merge(), FullGmm::MergePreselect(), Mfcc::Mfcc(), LogisticRegression::MixUp(), kaldi::nnet2::NnetComputationChunked(), LimitRankClass::operator()(), Matrix< BaseFloat >::operator=(), kaldi::ProcessPitch(), AffineXformStats::Read(), WaveData::Read(), AmSgmm2::Read(), SphinxMatrixHolder< kFeatDim >::Read(), NnetExampleBackgroundReader::ReadExamples(), kaldi::ReadHtk(), AmSgmm2::RemoveSpeakerSpace(), DiagGmmNormal::Resize(), FullGmmNormal::Resize(), FullGmm::Resize(), DiagGmm::Resize(), SgmmPerFrameDerivedVars::Resize(), AccumFullGmm::Resize(), AccumDiagGmm::Resize(), Sgmm2PerFrameDerivedVars::Resize(), MleAmSgmm2Accs::ResizeAccumulators(), kaldi::ReverseFrames(), KlHmm::SetStats(), LogisticRegression::SetWeights(), kaldi::SpliceFrames(), FullGmm::Split(), DiagGmm::Split(), AmSgmm::SplitSubstates(), CuMatrix< Real >::Swap(), TestSgmm2Fmllr(), TestSgmmFmllr(), LogisticRegression::Train(), kaldi::UnitTestAddMat2(), kaldi::UnitTestDelay(), UnitTestEstimateSgmm(), UnitTestEstimateSgmm2(), kaldi::UnitTestIo(), UnitTestMleAmDiagGmm(), kaldi::UnitTestPieces(), kaldi::UnitTestResize(), kaldi::UnitTestTransposeScatter(), kaldi::nnet2::UpdateHash(), UpdateWClass::UpdateWClass(), and UpdateWParallelClass::UpdateWParallelClass().
{
   // the next block uses recursion to handle what we have to do if
   // resize_type == kCopyData.
   if (resize_type == kCopyData) {
     if (this->data_ == NULL || rows == 0) resize_type = kSetZero;  // nothing to copy.
     else if (rows == this->num_rows_ && cols == this->num_cols_) { return; } // nothing to do.
     else {
       // set tmp to a matrix of the desired size; if new matrix
       // is bigger in some dimension, zero it.
       MatrixResizeType new_resize_type =
           (rows > this->num_rows_ || cols > this->num_cols_) ? kSetZero : kUndefined;
       Matrix<Real> tmp(rows, cols, new_resize_type);
       MatrixIndexT rows_min = std::min(rows, this->num_rows_),
           cols_min = std::min(cols, this->num_cols_);
       tmp.Range(0, rows_min, 0, cols_min).
           CopyFromMat(this->Range(0, rows_min, 0, cols_min));
       tmp.Swap(this);
       // and now let tmp go out of scope, deleting what was in *this.
       return;
     }
   }
   // At this point, resize_type == kSetZero or kUndefined.
   if (MatrixBase<Real>::data_ != NULL) {
     if (rows == MatrixBase<Real>::num_rows_
         && cols == MatrixBase<Real>::num_cols_) {
       if (resize_type == kSetZero)
         this->SetZero();
       return;
     }
     else
       Destroy();
   }
   Init(rows, cols);
   if (resize_type == kSetZero) MatrixBase<Real>::SetZero();
 }
void Swap (Matrix< Real > * other)
Swaps the contents of *this and *other. Shallow swap.
Definition at line 2022 of file kaldi-matrix.cc.
References MatrixBase< Real >::data_, MatrixBase< Real >::num_cols_, MatrixBase< Real >::num_rows_, MatrixBase< Real >::stride_, and kaldi::swap().
Referenced by DecodableMatrixMappedOffset::AcceptLoglikes(), MatrixExponential< Real >::BackpropTaylor(), DecodableAmNnet::DecodableAmNnet(), NnetExampleBackgroundReader::GetNextMinibatch(), Matrix< Real >::Resize(), GeneralMatrix::Swap(), CuMatrix< Real >::Swap(), GeneralMatrix::SwapFullMatrix(), and kaldi::UnitTestIvectorExtractor().
{
   std::swap(this->data_, other->data_);
   std::swap(this->num_cols_, other->num_cols_);
   std::swap(this->num_rows_, other->num_rows_);
   std::swap(this->stride_, other->stride_);
 }
void Swap (CuMatrix< Real > * mat)
Defined in ../cudamatrix/cu-matrix.cc.
Definition at line 2569 of file cu-matrix.cc.
References CuMatrix< Real >::Swap().
 { mat->Swap(this); }
void Transpose ()
Transpose the matrix.
Works for non-square matrices as well as square ones.
Definition at line 1929 of file kaldi-matrix.cc.
References kaldi::kTrans.
Referenced by kaldi::ComputePca(), BasisFmllrEstimate::ComputeTransform(), kaldi::CuVectorUnitTestCopyDiagFromMat(), BasisFmllrEstimate::EstimateFmllrBasis(), kaldi::UnitTestAddDiagVecMat(), kaldi::UnitTestAddMat2Sp(), kaldi::UnitTestAddMatSmat(), kaldi::UnitTestSymAddMat2(), kaldi::UnitTestTranspose(), kaldi::UnitTestVecmul(), and MlltAccs::Update().
{
   if (this->num_rows_ != this->num_cols_) {
     Matrix<Real> tmp(*this, kTrans);
     Resize(this->num_cols_, this->num_rows_);
     this->CopyFromMat(tmp);
   } else {
     (static_cast<MatrixBase<Real>&>(*this)).Transpose();
   }
 }
The documentation for this class was generated from the following files:
matrix/kaldi-matrix.h
matrix/kaldi-matrix-inl.h
matrix/kaldi-matrix.cc
cudamatrix/cu-matrix.cc
cudamatrix/cu-matrix.h