Kaldi: OffsetFileInputImpl Class Reference
OffsetFileInputImpl Class Reference
Public Member Functions
bool Seek (size_t offset)
virtual bool Open (const std::string &rxfilename, bool binary)
virtual std::istream & Stream ()
virtual void Close ()
virtual InputType MyType ()
virtual ~OffsetFileInputImpl ()
Public Member Functions inherited from InputImplBase
virtual ~InputImplBase ()
Static Public Member Functions
static void SplitFilename (const std::string &rxfilename, std::string *filename, size_t *offset)
Private Attributes
std::string filename_
bool binary_
std::ifstream is_
Detailed Description
Definition at line 536 of file kaldi-io.cc.
Constructor & Destructor Documentation
virtual ~OffsetFileInputImpl () inline virtual
Definition at line 633 of file kaldi-io.cc.
{
     // Stream will automatically be closed, and we don't care about
     // whether it fails.
   }
Member Function Documentation
virtual void Close () inline virtual
Implements InputImplBase.
Definition at line 623 of file kaldi-io.cc.
References OffsetFileInputImpl::is_, and KALDI_ERR.
{
     if (!is_.is_open())
       KALDI_ERR << "FileInputImpl::Close(), file is not open.";
     // I believe this error can only arise from coding error.
     is_.close();
     // Don't check status.
   }
virtual InputType MyType () inline virtual
Implements InputImplBase.
Definition at line 631 of file kaldi-io.cc.
References kaldi::kOffsetFileInput.
 { return kOffsetFileInput; }
virtual bool Open (const std::string & rxfilename, bool binary) inline virtual
Implements InputImplBase.
Definition at line 582 of file kaldi-io.cc.
References OffsetFileInputImpl::binary_, OffsetFileInputImpl::filename_, OffsetFileInputImpl::is_, MapOsPath, OffsetFileInputImpl::Seek(), and OffsetFileInputImpl::SplitFilename().
{
     if (is_.is_open()) {
       // We are opening when we have an already-open file.
       // We may have to seek within this file, or else close it and
       // open a different one.
       std::string tmp_filename;
       size_t offset;
       SplitFilename(rxfilename, &tmp_filename, &offset);
       if (tmp_filename == filename_ && binary == binary_) {  // Just seek
         is_.clear();  // clear fail bit, etc.
         return Seek(offset);
       } else {
         is_.close();  // don't bother checking error status of is_.
         filename_ = tmp_filename;
         is_.open(MapOsPath(filename_).c_str(),
                  binary ? std::ios_base::in | std::ios_base::binary
                         : std::ios_base::in);
         if (!is_.is_open()) return false;
         else
           return Seek(offset);
       }
     } else {
       size_t offset;
       SplitFilename(rxfilename, &filename_, &offset);
       binary_ = binary;
       is_.open(MapOsPath(filename_).c_str(),
                 binary ? std::ios_base::in | std::ios_base::binary
                       : std::ios_base::in);
       if (!is_.is_open()) return false;
       else
         return Seek(offset);
     }
   }
bool Seek (size_t offset) inline
Definition at line 558 of file kaldi-io.cc.
References rnnlm::i, and OffsetFileInputImpl::is_.
Referenced by OffsetFileInputImpl::Open().
{
     size_t cur_pos = is_.tellg();
     if (cur_pos == offset) return true;
     else if (cur_pos<offset && cur_pos+100 > offset) {
       // We're close enough that it may be faster to just
       // read that data, rather than seek.
       for (size_t i = cur_pos; i < offset; i++)
         is_.get();
       return (is_.tellg() == std::streampos(offset));
     }
     // Try to actually seek.
     is_.seekg(offset, std::ios_base::beg);
     if (is_.fail()) {  // failbit or badbit is set [error happened]
       is_.close();
       return false;  // failure.
     } else {
       is_.clear();  // Clear any failure bits (e.g. eof).
       return true;  // success.
     }
   }
static void SplitFilename (const std::string & rxfilename, std::string * filename, size_t * offset) inline static
Definition at line 542 of file kaldi-io.cc.
References kaldi::ConvertStringToInteger(), KALDI_ASSERT, and KALDI_ERR.
Referenced by OffsetFileInputImpl::Open().
{
     size_t pos = rxfilename.find_last_of(':');
     KALDI_ASSERT(pos != std::string::npos);  // would indicate error in calling
     // code, as the filename is supposed to be of the correct form at this
     // point.
     *filename = std::string(rxfilename, 0, pos);
     std::string number(rxfilename, pos+1);
     bool ans = ConvertStringToInteger(number, offset);
     if (!ans)
       KALDI_ERR << "Cannot get offset from filename " << rxfilename
                 << " (possibly you compiled in 32-bit and have a >32-bit"
                 << " byte offset into a file; you'll have to compile 64-bit.";
   }
virtual std::istream& Stream () inline virtual
Implements InputImplBase.
Definition at line 616 of file kaldi-io.cc.
References OffsetFileInputImpl::is_, and KALDI_ERR.
{
     if (!is_.is_open())
       KALDI_ERR << "FileInputImpl::Stream(), file is not open.";
     // I believe this error can only arise from coding error.
     return is_;
   }
Member Data Documentation
bool binary_ private
Definition at line 639 of file kaldi-io.cc.
Referenced by OffsetFileInputImpl::Open().
std::string filename_ private
Definition at line 638 of file kaldi-io.cc.
Referenced by OffsetFileInputImpl::Open().
std::ifstream is_ private
Definition at line 640 of file kaldi-io.cc.
Referenced by OffsetFileInputImpl::Close(), OffsetFileInputImpl::Open(), OffsetFileInputImpl::Seek(), and OffsetFileInputImpl::Stream().
The documentation for this class was generated from the following file:
util/kaldi-io.cc