Kaldi: CuRand< Real > Class Template Reference
CuRand< Real > Class Template Reference
#include <cu-common.h>
Public Member Functions
CuRand ()
~CuRand ()
void SeedGpu (MatrixIndexT state_size)
on demand seeding of all the buffers
void RandUniform (CuMatrixBase< Real > *tgt)
fill with numbers drawn from uniform distribution on [0, 1]
void RandGaussian (CuMatrixBase< Real > *tgt)
fill with normal random numbers
void RandGaussian (CuVectorBase< Real > *tgt)
void BinarizeProbs (const CuMatrix< Real > &probs, CuMatrix< Real > *states)
align probabilities to discrete 0/1 states (use uniform samplig)
void AddGaussNoise (CuMatrix< Real > *tgt, Real gscale=1.0)
add gaussian noise to each element
Private Member Functions
void SeedBuffer (MatrixIndexT state_size, uint32 **tgt)
seed one buffer on the GPU.
Private Attributes
uint32 * z1_
Inner state of the ``grid-like'' random number generator.
uint32 * z2_
uint32 * z3_
uint32 * z4_
int32 state_size_
size of the buffers
CuMatrix< Real > tmp_
auxiliary matrix
Detailed Description
template<typename Real>
class kaldi::CuRand< Real >
Definition at line 89 of file cu-common.h.
Constructor & Destructor Documentation
CuRand () inline
Definition at line 36 of file cu-rand.h.
 : z1_(NULL), z2_(NULL), z3_(NULL), z4_(NULL), state_size_(0) { }
~CuRand ()
Definition at line 63 of file cu-rand.cc.
                       {
   SeedBuffer(0, &z1_);
   SeedBuffer(0, &z2_);
   SeedBuffer(0, &z3_);
   SeedBuffer(0, &z4_);
 }
Member Function Documentation
void AddGaussNoise (CuMatrix< Real > * tgt, Real gscale = 1.0)
add gaussian noise to each element
Definition at line 182 of file cu-rand.cc.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::num_cols_, and CuMatrixBase< Real >::num_rows_.
{
   tmp_.Resize(tgt->num_rows_, tgt->num_cols_);
   RandGaussian(&tmp_);
   tgt->AddMat(gscale, tmp_);
 }
void BinarizeProbs (const CuMatrix< Real > & probs, CuMatrix< Real > * states)
align probabilities to discrete 0/1 states (use uniform samplig)
Definition at line 144 of file cu-rand.cc.
References CU2DBLOCK, CuMatrixBase< Real >::data_, CuMatrixBase< Real >::Dim(), Timer::Elapsed(), kaldi::kUndefined, CuMatrix< Real >::Mat(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, kaldi::RandUniform(), CuMatrix< Real >::Resize(), and CuMatrixBase< Real >::stride_.
Referenced by Dropout::PropagateFnc().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     // optionally re-seed the inner state
     // (this is done in host, for good performance it is better to avoid re-seeding)
     int32 tgt_size = probs.num_rows_ * probs.stride_;
     if (tgt_size != state_size_) SeedGpu(tgt_size);
     // prepare the output matrix
     if (states != &probs)
       states->Resize(probs.num_rows_, probs.num_cols_, kUndefined);
     // prepare the temporary matrix of uniform random numbers (0,1)
     tmp_.Resize(probs.num_rows_, probs.num_cols_, kUndefined);
     RandUniform(&tmp_);
     // use the uniform random numbers to compute discrete 0/1 states
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(states->num_cols_, CU2DBLOCK), n_blocks(states->num_rows_, CU2DBLOCK));
     cuda_binarize_probs(dimGrid, dimBlock, states->data_, probs.data_, tmp_.data_, states->Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     for(int32 r=0; r<states->num_rows_; r++) {
       for(int32 c=0; c<states->num_cols_; c++) {
         states->Mat()(r, c) = ((kaldi::RandUniform() < probs.Mat()(r, c))? 1 : 0 );
       }
     }
   }
 }
void RandGaussian (CuMatrixBase< Real > * tgt)
fill with normal random numbers
Definition at line 96 of file cu-rand.cc.
References CU2DBLOCK, CuMatrixBase< Real >::data_, CuMatrixBase< Real >::Dim(), Timer::Elapsed(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::SetRandn(), and CuMatrixBase< Real >::Stride().
Referenced by CuPackedMatrix< Real >::SetRandn(), CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int32 tgt_size = tgt->NumRows() * tgt->Stride();
     if (tgt_size == 0)
       return;
     if (tgt_size > state_size_) SeedGpu(tgt_size);
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(tgt->num_cols_, CU2DBLOCK), n_blocks(tgt->num_rows_, CU2DBLOCK));
     cuda_gauss_rand(dimGrid, dimBlock, tgt->data_, z1_, z2_, z3_, z4_, tgt->Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     tgt->SetRandn();
   }
 }
void RandGaussian (CuVectorBase< Real > * tgt)
Definition at line 120 of file cu-rand.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), CuVectorBase< Real >::Dim(), Timer::Elapsed(), and CuVectorBase< Real >::Vec().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int32 tgt_size = tgt->Dim();
     if (tgt_size != state_size_) SeedGpu(tgt_size);
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(tgt->Dim(), CU1DBLOCK));
     cuda_vec_gauss_rand(dimGrid, dimBlock, tgt->Data(), z1_, z2_, z3_, z4_, tgt->Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     tgt->Vec().SetRandn();
   }
 }
void RandUniform (CuMatrixBase< Real > * tgt)
fill with numbers drawn from uniform distribution on [0, 1]
Definition at line 72 of file cu-rand.cc.
References CU2DBLOCK, CuMatrixBase< Real >::data_, CuMatrixBase< Real >::Dim(), Timer::Elapsed(), CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::SetRandUniform(), and CuMatrixBase< Real >::Stride().
Referenced by CuMatrixBase< Real >::SetRandUniform().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int32 tgt_size = tgt->NumRows() * tgt->Stride();
     if (tgt_size != state_size_) SeedGpu(tgt_size);
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     dim3 dimGrid(n_blocks(tgt->num_cols_, CU2DBLOCK), n_blocks(tgt->num_rows_, CU2DBLOCK));
     cuda_rand(dimGrid, dimBlock, tgt->data_, z1_, z2_, z3_, z4_, tgt->Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     tgt->SetRandUniform();
   }
 }
void SeedBuffer (MatrixIndexT state_size, uint32 ** tgt) private
seed one buffer on the GPU.
If state_size == 0, just frees any existing buffers.
Definition at line 42 of file cu-rand.cc.
References rnnlm::i, and kaldi::RandInt().
{
 #if HAVE_CUDA == 1
   CuDevice &device = CuDevice::Instantiate();
   if (device.Enabled()) {
     if (*tgt != NULL) {
       device.Free(*tgt);
       *tgt = NULL;
     }
     if (state_size == 0) return; // Nothing to do.
     std::vector<uint32> temp_rand_data(state_size);
     for(MatrixIndexT i = 0; i < state_size; i++)
       temp_rand_data[i] = RandInt(128, RAND_MAX);
     int32 state_size_in_bytes = state_size * sizeof(uint32);
     *tgt = static_cast<uint32*>(device.Malloc(state_size_in_bytes));
     CU_SAFE_CALL(cudaMemcpy(*tgt, &(temp_rand_data[0]),
                             state_size_in_bytes, cudaMemcpyHostToDevice));
   }
 #endif
 }
void SeedGpu (MatrixIndexT state_size)
on demand seeding of all the buffers
Definition at line 31 of file cu-rand.cc.
References KALDI_ASSERT.
Referenced by RandomComponent::ResetGenerator().
{
   KALDI_ASSERT(state_size >= 0);
   state_size_ = state_size;
   SeedBuffer(state_size, &z1_);
   SeedBuffer(state_size, &z2_);
   SeedBuffer(state_size, &z3_);
   SeedBuffer(state_size, &z4_);
 }
Member Data Documentation
int32 state_size_ private
size of the buffers
Definition at line 71 of file cu-rand.h.
CuMatrix<Real> tmp_ private
auxiliary matrix
Definition at line 73 of file cu-rand.h.
uint32* z1_ private
Inner state of the ``grid-like'' random number generator.
Definition at line 70 of file cu-rand.h.
uint32 * z2_ private
Definition at line 70 of file cu-rand.h.
uint32 * z3_ private
Definition at line 70 of file cu-rand.h.
uint32 * z4_ private
Definition at line 70 of file cu-rand.h.
The documentation for this class was generated from the following files:
cudamatrix/cu-common.h
cudamatrix/cu-rand.h
cudamatrix/cu-rand.cc