Kaldi: MleSgmmSpeakerAccs Class Reference
MleSgmmSpeakerAccs Class Reference
Class for the accumulators required to update the speaker vectors v_s.
#include <estimate-am-sgmm.h>
Public Member Functions
MleSgmmSpeakerAccs (const AmSgmm &model, BaseFloat rand_prune_=1.0e-05)
Initialize the object. Error if speaker subspace not set up.
void Clear ()
Clear the statistics.
BaseFloat Accumulate (const AmSgmm &model, const SgmmPerFrameDerivedVars &frame_vars, int32 state_index, BaseFloat weight)
Accumulate statistics. Returns per-frame log-likelihood.
BaseFloat AccumulateFromPosteriors (const AmSgmm &model, const SgmmPerFrameDerivedVars &frame_vars, const Matrix< BaseFloat > &posteriors, int32 state_index)
Accumulate statistics, given posteriors.
void Update (BaseFloat min_count, Vector< BaseFloat > *v_s, BaseFloat *objf_impr_out, BaseFloat *count_out)
Update speaker vector.
Private Attributes
Vector< double > y_s_
Statistics for speaker adaptation (vectors), stored per-speaker.
Vector< double > gamma_s_
gamma_{i}^{(s)}. Per-speaker counts for each Gaussian. Dimension is [I]
std::vector< SpMatrix< double > > H_spk_
The following variable does not change per speaker.
std::vector< Matrix< double > > NtransSigmaInv_
N_i^T {i}^{-1}. Needed for y^{(s)}.
BaseFloat rand_prune_
small constant to randomly prune tiny posteriors
Detailed Description
Class for the accumulators required to update the speaker vectors v_s.
Note: if you have multiple speakers you will want to initialize this just once and call Clear() after you're done with each speaker, rather than creating a new object for each speaker, since the initialization function does nontrivial work.
Definition at line 379 of file estimate-am-sgmm.h.
Constructor & Destructor Documentation
MleSgmmSpeakerAccs (const AmSgmm & model, BaseFloat rand_prune_ = 1.0e-05)
Initialize the object. Error if speaker subspace not set up.
Definition at line 2014 of file estimate-am-sgmm.cc.
References MleSgmmSpeakerAccs::gamma_s_, AmSgmm::GetNtransSigmaInv(), MleSgmmSpeakerAccs::H_spk_, rnnlm::i, KALDI_ASSERT, kaldi::kTrans, AmSgmm::N_, MleSgmmSpeakerAccs::NtransSigmaInv_, AmSgmm::NumGauss(), Vector< Real >::Resize(), AmSgmm::SigmaInv_, AmSgmm::SpkSpaceDim(), and MleSgmmSpeakerAccs::y_s_.
     : rand_prune_(prune) {
   KALDI_ASSERT(model.SpkSpaceDim() != 0);
   H_spk_.resize(model.NumGauss());
   for (int32 i = 0; i < model.NumGauss(); i++) {
     // Eq. (82): H_{i}^{spk} = N_{i}^T \Sigma_{i}^{-1} N_{i}
     H_spk_[i].Resize(model.SpkSpaceDim());
     H_spk_[i].AddMat2Sp(1.0, Matrix<double>(model.N_[i]),
                         kTrans, SpMatrix<double>(model.SigmaInv_[i]), 0.0);
   }
   model.GetNtransSigmaInv(&NtransSigmaInv_);
   gamma_s_.Resize(model.NumGauss());
   y_s_.Resize(model.SpkSpaceDim());
 }
Member Function Documentation
BaseFloat Accumulate (const AmSgmm & model, const SgmmPerFrameDerivedVars & frame_vars, int32 state_index, BaseFloat weight)
Accumulate statistics. Returns per-frame log-likelihood.
Definition at line 2038 of file estimate-am-sgmm.cc.
References MleSgmmSpeakerAccs::AccumulateFromPosteriors(), AmSgmm::ComponentPosteriors(), and MatrixBase< Real >::Scale().
Referenced by kaldi::AccumulateForUtterance().
{
   // Calculate Gaussian posteriors and collect statistics
   Matrix<BaseFloat> posteriors;
   BaseFloat log_like = model.ComponentPosteriors(frame_vars, j, &posteriors);
   posteriors.Scale(weight);
   AccumulateFromPosteriors(model, frame_vars, posteriors, j);
   return log_like;
 }
BaseFloat AccumulateFromPosteriors (const AmSgmm & model, const SgmmPerFrameDerivedVars & frame_vars, const Matrix< BaseFloat > & posteriors, int32 state_index)
Accumulate statistics, given posteriors.
Returns total count accumulated, which may differ from posteriors.Sum() due to randomized pruning.
Definition at line 2051 of file estimate-am-sgmm.cc.
References VectorBase< Real >::AddMatVec(), VectorBase< Real >::AddVec(), AmSgmm::FeatureDim(), MleSgmmSpeakerAccs::gamma_s_, AmSgmm::GetSubstateMean(), SgmmPerFrameDerivedVars::gselect, rnnlm::i, KALDI_ASSERT, kaldi::kNoTrans, MleSgmmSpeakerAccs::NtransSigmaInv_, AmSgmm::NumSubstates(), MleSgmmSpeakerAccs::rand_prune_, kaldi::RandPrune(), AmSgmm::SpkSpaceDim(), SgmmPerFrameDerivedVars::xt, and MleSgmmSpeakerAccs::y_s_.
Referenced by MleSgmmSpeakerAccs::Accumulate(), and kaldi::AccumulateForUtterance().
{
   double tot_count = 0.0;
   int32 feature_dim = model.FeatureDim(),
       spk_space_dim = model.SpkSpaceDim();
   KALDI_ASSERT(spk_space_dim != 0);
   const vector<int32> &gselect = frame_vars.gselect;
   // Intermediate variables
   Vector<double> xt_jmi(feature_dim), mu_jmi(feature_dim),
       zt_jmi(spk_space_dim);
   int32 num_substates = model.NumSubstates(j);
   for (int32 ki = 0; ki < static_cast<int32>(gselect.size()); ki++) {
     int32 i = gselect[ki];
     for (int32 m = 0; m < num_substates; m++) {
       // Eq. (39): gamma_{jmi}(t) = p (j, m, i|t)
       BaseFloat gammat_jmi = RandPrune(posteriors(ki, m), rand_prune_);
       if (gammat_jmi != 0.0) {
         tot_count += gammat_jmi;
         model.GetSubstateMean(j, m, i, &mu_jmi);
         xt_jmi.CopyFromVec(frame_vars.xt);
         xt_jmi.AddVec(-1.0, mu_jmi);
         // Eq. (48): z{jmi}(t) = N_{i}^{T} \Sigma_{i}^{-1} x_{jmi}(t)
         zt_jmi.AddMatVec(1.0, NtransSigmaInv_[i], kNoTrans, xt_jmi, 0.0);
         // Eq. (49): \gamma_{i}^{(s)} = \sum_{t\in\Tau(s), j, m} gamma_{jmi}
         gamma_s_(i) += gammat_jmi;
         // Eq. (50): y^{(s)} = \sum_{t, j, m, i} gamma_{jmi}(t) z_{jmi}(t)
         y_s_.AddVec(gammat_jmi, zt_jmi);
       }
     }
   }
   return tot_count;
 }
void Clear ()
Clear the statistics.
Definition at line 2031 of file estimate-am-sgmm.cc.
References MleSgmmSpeakerAccs::gamma_s_, VectorBase< Real >::SetZero(), and MleSgmmSpeakerAccs::y_s_.
Referenced by main().
{
   y_s_.SetZero();
   gamma_s_.SetZero();
 }
void Update (BaseFloat min_count, Vector< BaseFloat > * v_s, BaseFloat * objf_impr_out, BaseFloat * count_out)
Update speaker vector.
If v_s was empty, will assume it started as zero and will resize it to the speaker-subspace size.
Definition at line 2087 of file estimate-am-sgmm.cc.
References SpMatrix< Real >::AddSp(), VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), MleSgmmSpeakerAccs::gamma_s_, MleSgmmSpeakerAccs::H_spk_, rnnlm::i, KALDI_ASSERT, KALDI_LOG, KALDI_WARN, Vector< Real >::Resize(), kaldi::SolveQuadraticProblem(), VectorBase< Real >::Sum(), and MleSgmmSpeakerAccs::y_s_.
Referenced by main().
{
   double tot_gamma = gamma_s_.Sum();
   KALDI_ASSERT(y_s_.Dim() != 0);
   int32 T = y_s_.Dim();  // speaker-subspace dim.
   int32 num_gauss = gamma_s_.Dim();
   if (v_s->Dim() != T) v_s->Resize(T);  // will set it to zero.
   if (tot_gamma < min_count) {
     KALDI_WARN << "Updating speaker vectors, count is " << tot_gamma
                << " < " << min_count << "not updating.";
     if (objf_impr_out) *objf_impr_out = 0.0;
     if (count_out) *count_out = 0.0;
     return;
   }
   // Eq. (84): H^{(s)} = \sum_{i} \gamma_{i}(s) H_{i}^{spk}
   SpMatrix<double> H_s(T);
   for (int32 i = 0; i < num_gauss; i++)
     H_s.AddSp(gamma_s_(i), H_spk_[i]);
   // Don't make these options to SolveQuadraticProblem configurable...
   // they really don't make a difference at all unless the matrix in
   // question is singular, which wouldn't happen in this case.
   Vector<double> v_s_dbl(*v_s);
   double tot_objf_impr =
       SolveQuadraticProblem(H_s, y_s_, SolverOptions("v_s"), &v_s_dbl);
   v_s->CopyFromVec(v_s_dbl);
   KALDI_LOG << "*Objf impr for speaker vector is " << (tot_objf_impr / tot_gamma)
             << " over " << (tot_gamma) << " frames.";
   if (objf_impr_out) *objf_impr_out = tot_objf_impr;
   if (count_out) *count_out = tot_gamma;
 }
Member Data Documentation
Vector<double> gamma_s_ private
gamma_{i}^{(s)}. Per-speaker counts for each Gaussian. Dimension is [I]
Definition at line 412 of file estimate-am-sgmm.h.
Referenced by MleSgmmSpeakerAccs::AccumulateFromPosteriors(), MleSgmmSpeakerAccs::Clear(), MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), and MleSgmmSpeakerAccs::Update().
std::vector< SpMatrix<double> > H_spk_ private
The following variable does not change per speaker.
Eq. (82): H_{i}^{spk} = N_{i}^T {i}^{-1} N_{i}
Definition at line 416 of file estimate-am-sgmm.h.
Referenced by MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), and MleSgmmSpeakerAccs::Update().
std::vector< Matrix<double> > NtransSigmaInv_ private
N_i^T {i}^{-1}. Needed for y^{(s)}.
Definition at line 419 of file estimate-am-sgmm.h.
Referenced by MleSgmmSpeakerAccs::AccumulateFromPosteriors(), and MleSgmmSpeakerAccs::MleSgmmSpeakerAccs().
BaseFloat rand_prune_ private
small constant to randomly prune tiny posteriors
Definition at line 422 of file estimate-am-sgmm.h.
Referenced by MleSgmmSpeakerAccs::AccumulateFromPosteriors().
Vector<double> y_s_ private
Statistics for speaker adaptation (vectors), stored per-speaker.
Per-speaker stats for vectors, y^{(s)}. Dimension [T].
Definition at line 410 of file estimate-am-sgmm.h.
Referenced by MleSgmmSpeakerAccs::AccumulateFromPosteriors(), MleSgmmSpeakerAccs::Clear(), MleSgmmSpeakerAccs::MleSgmmSpeakerAccs(), and MleSgmmSpeakerAccs::Update().
The documentation for this class was generated from the following files:
sgmm/estimate-am-sgmm.h
sgmm/estimate-am-sgmm.cc