Kaldi: Rbm Class Reference
Rbm Class Reference
#include <nnet-rbm.h>
Public Member Functions
Rbm (int32 dim_in, int32 dim_out)
~Rbm ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void Reconstruct (const CuMatrixBase< BaseFloat > &hid_state, CuMatrix< BaseFloat > *vis_probs)
void RbmUpdate (const CuMatrixBase< BaseFloat > &pos_vis, const CuMatrixBase< BaseFloat > &pos_hid, const CuMatrixBase< BaseFloat > &neg_vis, const CuMatrixBase< BaseFloat > &neg_hid)
RbmNodeType VisType () const
RbmNodeType HidType () const
void WriteAsNnet (std::ostream &os, bool binary) const
Public Member Functions inherited from RbmBase
RbmBase (int32 dim_in, int32 dim_out)
void SetRbmTrainOptions (const RbmTrainOptions &opts)
Set training hyper-parameters to the network and its UpdatableComponent(s)
const RbmTrainOptions & GetRbmTrainOptions () const
Get training hyper-parameters from the network.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if contains trainable parameters.
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Optionally print some additional info.
virtual std::string InfoGradient () const
Protected Attributes
CuMatrix< BaseFloat > vis_hid_
Matrix with neuron weights.
CuVector< BaseFloat > vis_bias_
Vector with biases.
CuVector< BaseFloat > hid_bias_
Vector with biases.
CuMatrix< BaseFloat > vis_hid_corr_
Matrix for linearity updates.
CuVector< BaseFloat > vis_bias_corr_
Vector for bias updates.
CuVector< BaseFloat > hid_bias_corr_
Vector for bias updates.
RbmNodeType vis_type_
RbmNodeType hid_type_
Protected Attributes inherited from RbmBase
RbmTrainOptions rbm_opts_
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Additional Inherited Members
Public Types inherited from RbmBase
enum RbmNodeType { Bernoulli, Gaussian }
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Detailed Description
Definition at line 89 of file nnet-rbm.h.
Constructor & Destructor Documentation
Rbm (int32 dim_in, int32 dim_out) inline
Definition at line 91 of file nnet-rbm.h.
Referenced by Rbm::Copy().
    : RbmBase(dim_in, dim_out)
   { }
~Rbm () inline
Definition at line 94 of file nnet-rbm.h.
   { }
Member Function Documentation
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 97 of file nnet-rbm.h.
References Rbm::Rbm().
 { return new Rbm(*this); }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 98 of file nnet-rbm.h.
References Component::kRbm.
 { return kRbm; }
RbmNodeType HidType () const inline virtual
Implements RbmBase.
Definition at line 375 of file nnet-rbm.h.
References Rbm::hid_type_.
Referenced by Rbm::WriteAsNnet().
{
     return hid_type_;
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Reimplemented from Component.
Definition at line 100 of file nnet-rbm.h.
References RbmBase::Bernoulli, rnnlm::d, CuVectorBase< Real >::Dim(), RbmBase::Gaussian, Nnet::GetComponent(), Rbm::hid_bias_, Rbm::hid_type_, rnnlm::i, Component::input_dim_, Component::InputDim(), KALDI_ASSERT, KALDI_ERR, KALDI_LOG, kaldi::Log(), Component::output_dim_, kaldi::RandGauss(), kaldi::RandUniform(), Nnet::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), VectorBase< Real >::Scale(), Rbm::vis_bias_, Rbm::vis_hid_, and Rbm::vis_type_.
{
     // define options
     std::string vis_type;
     std::string hid_type;
     float vis_bias_mean = 0.0, vis_bias_range = 0.0,
           hid_bias_mean = 0.0, hid_bias_range = 0.0,
           param_stddev = 0.1;
     std::string vis_bias_cmvn_file; // initialize biases to logit(p_active)
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<VisibleType>") ReadToken(is, false, &vis_type);
       else if (token == "<HiddenType>") ReadToken(is, false, &hid_type);
       else if (token == "<VisibleBiasMean>") ReadBasicType(is, false, &vis_bias_mean);
       else if (token == "<VisibleBiasRange>") ReadBasicType(is, false, &vis_bias_range);
       else if (token == "<HiddenBiasMean>") ReadBasicType(is, false, &hid_bias_mean);
       else if (token == "<HiddenBiasRange>") ReadBasicType(is, false, &hid_bias_range);
       else if (token == "<ParamStddev>") ReadBasicType(is, false, &param_stddev);
       else if (token == "<VisibleBiasCmvnFilename>") ReadToken(is, false, &vis_bias_cmvn_file);
       else KALDI_ERR << "Unknown token " << token << " Typo in config?";
       is >> std::ws; // eat-up whitespace
     }
     //
     // initialize
     //
     if (vis_type == "bern" || vis_type == "Bernoulli") vis_type_ = RbmBase::Bernoulli;
     else if (vis_type == "gauss" || vis_type == "Gaussian") vis_type_ = RbmBase::Gaussian;
     else KALDI_ERR << "Wrong <VisibleType>" << vis_type;
     //
     if (hid_type == "bern" || hid_type == "Bernoulli") hid_type_ = RbmBase::Bernoulli;
     else if (hid_type == "gauss" || hid_type == "Gaussian") hid_type_ = RbmBase::Gaussian;
     else KALDI_ERR << "Wrong <HiddenType>" << hid_type;
     // visible-hidden connections
     Matrix<BaseFloat> mat(output_dim_, input_dim_);
     for (int32 r=0; r<output_dim_; r++) {
       for (int32 c=0; c<input_dim_; c++) {
         mat(r,c) = param_stddev * RandGauss(); // 0-mean Gauss with given std_dev
       }
     }
     vis_hid_ = mat;
     // hidden-bias
     Vector<BaseFloat> vec(output_dim_);
     for (int32 i=0; i<output_dim_; i++) {
       // +/- 1/2*bias_range from bias_mean:
       vec(i) = hid_bias_mean + (RandUniform() - 0.5) * hid_bias_range;
     }
     hid_bias_ = vec;
     // visible-bias
     if (vis_bias_cmvn_file == "") {
       Vector<BaseFloat> vec2(input_dim_);
       for (int32 i=0; i<input_dim_; i++) {
         // +/- 1/2*bias_range from bias_mean:
         vec2(i) = vis_bias_mean + (RandUniform() - 0.5) * vis_bias_range;
       }
       vis_bias_ = vec2;
     } else {
       KALDI_LOG << "Initializing from <VisibleBiasCmvnFilename> " << vis_bias_cmvn_file;
       Nnet cmvn;
       cmvn.Read(vis_bias_cmvn_file);
       // getting probablity that neuron fires:
       Vector<BaseFloat> p(dynamic_cast<AddShift&>(cmvn.GetComponent(0)).GetShiftVec());
       p.Scale(-1.0);
       // compute logit:
       Vector<BaseFloat> logit_p(p.Dim());
       for(int32 d = 0; d < p.Dim(); d++) {
         if(p(d) < 0.0001) p(d) = 0.0001;
         if(p(d) > 0.9999) p(d) = 0.9999;
         logit_p(d) = Log(p(d)) - Log(1.0 - p(d));
       }
       vis_bias_ = logit_p;
       KALDI_ASSERT(vis_bias_.Dim() == InputDim());
     }
     //
   }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 222 of file nnet-rbm.h.
References CuMatrixBase< Real >::AddMatMat(), CuMatrixBase< Real >::AddVecToRows(), RbmBase::Bernoulli, Rbm::hid_bias_, Rbm::hid_type_, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Sigmoid(), and Rbm::vis_hid_.
{
     // pre-fill with bias
     out->AddVecToRows(1.0, hid_bias_, 0.0);
     // multiply by weights^t
     out->AddMatMat(1.0, in, kNoTrans, vis_hid_, kTrans, 1.0);
     // optionally apply sigmoid
     if (hid_type_ == RbmBase::Bernoulli) {
       out->Sigmoid(*out);
     }
   }
void RbmUpdate (const CuMatrixBase< BaseFloat > & pos_vis, const CuMatrixBase< BaseFloat > & pos_hid, const CuMatrixBase< BaseFloat > & neg_vis, const CuMatrixBase< BaseFloat > & neg_hid) inline virtual
Implements RbmBase.
Definition at line 254 of file nnet-rbm.h.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), kaldi::nnet1::CheckNanInf(), kaldi::nnet1::ComputeStdDev(), CuVectorBase< Real >::Dim(), RbmBase::Gaussian, Rbm::hid_bias_, Rbm::hid_bias_corr_, Component::input_dim_, KALDI_ASSERT, KALDI_WARN, kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, RbmTrainOptions::l2_penalty, RbmTrainOptions::learn_rate, RbmTrainOptions::momentum, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, RbmBase::rbm_opts_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), CuVectorBase< Real >::SetZero(), CuMatrixBase< Real >::SetZero(), Rbm::vis_bias_, Rbm::vis_bias_corr_, Rbm::vis_hid_, Rbm::vis_hid_corr_, and Rbm::vis_type_.
{
     // dims
     KALDI_ASSERT(pos_vis.NumRows() == pos_hid.NumRows() &&
            pos_vis.NumRows() == neg_vis.NumRows() &&
            pos_vis.NumRows() == neg_hid.NumRows() &&
            pos_vis.NumCols() == neg_vis.NumCols() &&
            pos_hid.NumCols() == neg_hid.NumCols() &&
            pos_vis.NumCols() == input_dim_ &&
            pos_hid.NumCols() == output_dim_);
     // lazy initialization of buffers
     if ( vis_hid_corr_.NumRows() != vis_hid_.NumRows() ||
          vis_hid_corr_.NumCols() != vis_hid_.NumCols() ||
          vis_bias_corr_.Dim()    != vis_bias_.Dim()    ||
          hid_bias_corr_.Dim()    != hid_bias_.Dim()     ){
       vis_hid_corr_.Resize(vis_hid_.NumRows(),vis_hid_.NumCols(),kSetZero);
       vis_bias_corr_.Resize(vis_bias_.Dim(), kSetZero);
       hid_bias_corr_.Resize(hid_bias_.Dim(), kSetZero);
     }
     // ANTI-WEIGHT-EXPLOSION PROTECTION (Gaussian-Bernoulli RBM)
     // in the following section we detect that the weights in Gaussian-Bernoulli RBM
     // are about to explode. The weight explosion is caused by large variance of the
     // reconstructed data, which causes a feed-back loop that keeps increasing the weights.
     //
     // To avoid explosion, the variance of the visible-data and reconstructed-data
     // should be about the same. The model is particularly sensitive at the very
     // beginning of the CD-1 training.
     //
     // We compute variance of a)input mini-batch b)reconstruction.
     // When the ratio b)/a) is larger than 2, we:
     // 1. scale down the weights and biases by b)/a) (for next mini-batch b)/a) gets 1.0)
     // 2. shrink learning rate by 0.9x
     // 3. reset the momentum buffer
     //
     // Also a warning message is put to log. Note that in later stage
     // the learning-rate returns to its original value.
     //
     // An alternative approach is to use smaller values in weight-matrix initialization.
     //
     if (vis_type_ == RbmBase::Gaussian) {
       // check the data have no nan/inf:
       CheckNanInf(pos_vis,"pos_vis");
       CheckNanInf(pos_hid,"pos_hid");
       CheckNanInf(neg_vis,"neg_vis");
       CheckNanInf(neg_hid,"pos_hid");
       // get standard deviations of pos_vis and neg_vis:
       BaseFloat pos_vis_std = ComputeStdDev(pos_vis);
       BaseFloat neg_vis_std = ComputeStdDev(neg_vis);
       // monitor the standard deviation mismatch : data vs. reconstruction
       if (pos_vis_std * 2 < neg_vis_std) {
         // 1) scale-down the weights and biases
         BaseFloat scale = pos_vis_std / neg_vis_std;
         vis_hid_.Scale(scale);
         vis_bias_.Scale(scale);
         hid_bias_.Scale(scale);
         // 2) reduce the learning rate
         rbm_opts_.learn_rate *= 0.9;
         // 3) reset the momentum buffers
         vis_hid_corr_.SetZero();
         vis_bias_corr_.SetZero();
         hid_bias_corr_.SetZero();
         KALDI_WARN << "Mismatch between pos_vis and neg_vis variances, "
                    << "danger of weight explosion. a) Reducing weights with scale " << scale
                    << " b) Lowering learning rate to " << rbm_opts_.learn_rate
                    << " [pos_vis_std:" << pos_vis_std
                    << ",neg_vis_std:" << neg_vis_std << "]";
         return; /* i.e. don't update weights with current stats, as the update would be too BIG */
       }
     }
     //
     // End of weight-explosion check
     //  We use these training hyper-parameters
     //
     const BaseFloat lr = rbm_opts_.learn_rate;
     const BaseFloat mmt = rbm_opts_.momentum;
     const BaseFloat l2 = rbm_opts_.l2_penalty;
     //  UPDATE vishid matrix
     //
     //  vishidinc = momentum*vishidinc + ...
     //              epsilonw*( (posprods-negprods)/numcases - weightcost*vishid);
     //
     //  vishidinc[t] = -(epsilonw/numcases)*negprods + momentum*vishidinc[t-1]
     //                 +(epsilonw/numcases)*posprods
     //                 -(epsilonw*weightcost)*vishid[t-1]
     //
     BaseFloat N = static_cast<BaseFloat>(pos_vis.NumRows());
     vis_hid_corr_.AddMatMat(-lr/N, neg_hid, kTrans, neg_vis, kNoTrans, mmt);
     vis_hid_corr_.AddMatMat(+lr/N, pos_hid, kTrans, pos_vis, kNoTrans, 1.0);
     vis_hid_corr_.AddMat(-lr*l2, vis_hid_);
     vis_hid_.AddMat(1.0, vis_hid_corr_);
     //  UPDATE visbias vector
     //
     //  visbiasinc = momentum*visbiasinc + (epsilonvb/numcases)*(posvisact-negvisact);
     //
     vis_bias_corr_.AddRowSumMat(-lr/N, neg_vis, mmt);
     vis_bias_corr_.AddRowSumMat(+lr/N, pos_vis, 1.0);
     vis_bias_.AddVec(1.0, vis_bias_corr_, 1.0);
     //  UPDATE hidbias vector
     //
     // hidbiasinc = momentum*hidbiasinc + (epsilonhb/numcases)*(poshidact-neghidact);
     //
     hid_bias_corr_.AddRowSumMat(-lr/N, neg_hid, mmt);
     hid_bias_corr_.AddRowSumMat(+lr/N, pos_hid, 1.0);
     hid_bias_.AddVec(1.0, hid_bias_corr_, 1.0);
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 178 of file nnet-rbm.h.
References RbmBase::Bernoulli, CuVectorBase< Real >::Dim(), RbmBase::Gaussian, Rbm::hid_bias_, Rbm::hid_type_, Component::input_dim_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), kaldi::ReadToken(), Rbm::vis_bias_, Rbm::vis_hid_, and Rbm::vis_type_.
{
     std::string vis_node_type, hid_node_type;
     ReadToken(is, binary, &vis_node_type);
     ReadToken(is, binary, &hid_node_type);
     if(vis_node_type == "bern") {
       vis_type_ = RbmBase::Bernoulli;
     } else if(vis_node_type == "gauss") {
       vis_type_ = RbmBase::Gaussian;
     }
     if(hid_node_type == "bern") {
       hid_type_ = RbmBase::Bernoulli;
     } else if(hid_node_type == "gauss") {
       hid_type_ = RbmBase::Gaussian;
     }
     vis_hid_.Read(is, binary);
     vis_bias_.Read(is, binary);
     hid_bias_.Read(is, binary);
     KALDI_ASSERT(vis_hid_.NumRows() == output_dim_);
     KALDI_ASSERT(vis_hid_.NumCols() == input_dim_);
     KALDI_ASSERT(vis_bias_.Dim() == input_dim_);
     KALDI_ASSERT(hid_bias_.Dim() == output_dim_);
   }
void Reconstruct (const CuMatrixBase< BaseFloat > & hid_state, CuMatrix< BaseFloat > * vis_probs) inline virtual
Implements RbmBase.
Definition at line 234 of file nnet-rbm.h.
References CuMatrixBase< Real >::AddMatMat(), CuMatrixBase< Real >::AddVecToRows(), RbmBase::Bernoulli, Component::input_dim_, KALDI_ERR, kaldi::kNoTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, CuMatrix< Real >::Resize(), CuMatrixBase< Real >::Sigmoid(), Rbm::vis_bias_, Rbm::vis_hid_, and Rbm::vis_type_.
{
     // check the dim
     if (output_dim_ != hid_state.NumCols()) {
       KALDI_ERR << "Nonmatching dims, component:" << output_dim_ << " data:" << hid_state.NumCols();
     }
     // optionally allocate buffer
     if (input_dim_ != vis_probs->NumCols() || hid_state.NumRows() != vis_probs->NumRows()) {
       vis_probs->Resize(hid_state.NumRows(), input_dim_);
     }
     // pre-fill with bias
     vis_probs->AddVecToRows(1.0, vis_bias_, 0.0);
     // multiply by weights
     vis_probs->AddMatMat(1.0, hid_state, kNoTrans, vis_hid_, kNoTrans, 1.0);
     // optionally apply sigmoid
     if (vis_type_ == RbmBase::Bernoulli) {
       vis_probs->Sigmoid(*vis_probs);
     }
   }
RbmNodeType VisType () const inline virtual
Implements RbmBase.
Definition at line 371 of file nnet-rbm.h.
References Rbm::vis_type_.
{
     return vis_type_;
   }
void WriteAsNnet (std::ostream & os, bool binary) const inline virtual
Implements RbmBase.
Definition at line 379 of file nnet-rbm.h.
References RbmBase::Bernoulli, Rbm::hid_bias_, Rbm::HidType(), Component::InputDim(), Component::kAffineTransform, Component::kSigmoid, Component::OutputDim(), Component::TypeToMarker(), Rbm::vis_hid_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     //header
     WriteToken(os,binary,Component::TypeToMarker(Component::kAffineTransform));
     WriteBasicType(os,binary,OutputDim());
     WriteBasicType(os,binary,InputDim());
     if(!binary) os << "\n";
     //data
     vis_hid_.Write(os,binary);
     hid_bias_.Write(os,binary);
     //optionally sigmoid activation
     if(HidType() == Bernoulli) {
       WriteToken(os,binary,Component::TypeToMarker(Component::kSigmoid));
       WriteBasicType(os,binary,OutputDim());
       WriteBasicType(os,binary,OutputDim());
     }
     if(!binary) os << "\n";
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 204 of file nnet-rbm.h.
References RbmBase::Bernoulli, RbmBase::Gaussian, Rbm::hid_bias_, Rbm::hid_type_, KALDI_ERR, Rbm::vis_bias_, Rbm::vis_hid_, Rbm::vis_type_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), and kaldi::WriteToken().
{
     switch (vis_type_) {
       case Bernoulli : WriteToken(os,binary,"bern"); break;
       case Gaussian  : WriteToken(os,binary,"gauss"); break;
       default : KALDI_ERR << "Unknown type " << vis_type_;
     }
     switch (hid_type_) {
       case Bernoulli : WriteToken(os,binary,"bern"); break;
       case Gaussian  : WriteToken(os,binary,"gauss"); break;
       default : KALDI_ERR << "Unknown type " << hid_type_;
     }
     vis_hid_.Write(os, binary);
     vis_bias_.Write(os, binary);
     hid_bias_.Write(os, binary);
   }
Member Data Documentation
CuVector<BaseFloat> hid_bias_ protected
Vector with biases.
Definition at line 400 of file nnet-rbm.h.
Referenced by Rbm::InitData(), Rbm::PropagateFnc(), Rbm::RbmUpdate(), Rbm::ReadData(), Rbm::WriteAsNnet(), and Rbm::WriteData().
CuVector<BaseFloat> hid_bias_corr_ protected
Vector for bias updates.
Definition at line 404 of file nnet-rbm.h.
Referenced by Rbm::RbmUpdate().
RbmNodeType hid_type_ protected
Definition at line 407 of file nnet-rbm.h.
Referenced by Rbm::HidType(), Rbm::InitData(), Rbm::PropagateFnc(), Rbm::ReadData(), and Rbm::WriteData().
CuVector<BaseFloat> vis_bias_ protected
Vector with biases.
Definition at line 399 of file nnet-rbm.h.
Referenced by Rbm::InitData(), Rbm::RbmUpdate(), Rbm::ReadData(), Rbm::Reconstruct(), and Rbm::WriteData().
CuVector<BaseFloat> vis_bias_corr_ protected
Vector for bias updates.
Definition at line 403 of file nnet-rbm.h.
Referenced by Rbm::RbmUpdate().
CuMatrix<BaseFloat> vis_hid_ protected
Matrix with neuron weights.
Definition at line 398 of file nnet-rbm.h.
Referenced by Rbm::InitData(), Rbm::PropagateFnc(), Rbm::RbmUpdate(), Rbm::ReadData(), Rbm::Reconstruct(), Rbm::WriteAsNnet(), and Rbm::WriteData().
CuMatrix<BaseFloat> vis_hid_corr_ protected
Matrix for linearity updates.
Definition at line 402 of file nnet-rbm.h.
Referenced by Rbm::RbmUpdate().
RbmNodeType vis_type_ protected
Definition at line 406 of file nnet-rbm.h.
Referenced by Rbm::InitData(), Rbm::RbmUpdate(), Rbm::ReadData(), Rbm::Reconstruct(), Rbm::VisType(), and Rbm::WriteData().
The documentation for this class was generated from the following file:
nnet/nnet-rbm.h