Kaldi: DctComponent Class Reference
DctComponent Class Reference
Discrete cosine transform.
#include <nnet-component.h>
Public Member Functions
DctComponent ()
virtual std::string Type () const
virtual std::string Info () const
void Init (int32 dim, int32 dct_dim, bool reorder, int32 keep_dct_dim=0)
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Private Member Functions
void Reorder (CuMatrixBase< BaseFloat > *mat, bool reverse) const
KALDI_DISALLOW_COPY_AND_ASSIGN (DctComponent)
Private Attributes
int32 dim_
bool reorder_
CuMatrix< BaseFloat > dct_mat_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
Discrete cosine transform.
TODO: modify this Component so that it supports only keeping a subset
Definition at line 1361 of file nnet-component.h.
Constructor & Destructor Documentation
DctComponent () inline
Definition at line 1363 of file nnet-component.h.
References DctComponent::dim_.
Referenced by DctComponent::Copy().
 { dim_ = 0; }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 3139 of file nnet-component.cc.
References DctComponent::dct_mat_, DctComponent::dim_, KALDI_ASSERT, kaldi::kNoTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), DctComponent::OutputDim(), DctComponent::Reorder(), DctComponent::reorder_, and CuMatrix< Real >::Resize().
{
   KALDI_ASSERT(out_deriv.NumCols() == OutputDim());
   int32 dct_dim = dct_mat_.NumCols(),
         dct_keep_dim = dct_mat_.NumRows(),
         num_chunks = dim_ / dct_dim,
         num_rows = out_deriv.NumRows();
   in_deriv->Resize(num_rows, dim_);
   CuMatrix<BaseFloat> out_deriv_tmp;
   if (reorder_) {
     out_deriv_tmp = out_deriv;
     Reorder(&out_deriv_tmp, false);
   }
   for (int32 chunk = 0; chunk < num_chunks; chunk++) {
     CuSubMatrix<BaseFloat> in_deriv_mat(*in_deriv,
                                       0, num_rows, dct_dim * chunk, dct_dim),
                         out_deriv_mat(reorder_ ? out_deriv_tmp : out_deriv,
                                       0, num_rows, dct_keep_dim * chunk, dct_keep_dim);
     // Note: in the reverse direction the DCT matrix is transposed.  This is
     // normal when computing derivatives; the necessity for the transpose is
     // obvious if you consider what happens when the input and output dims
     // differ.
     in_deriv_mat.AddMatMat(1.0, out_deriv_mat, kNoTrans,
                            dct_mat_, kNoTrans, 0.0);
   }
   if (reorder_)
     Reorder(in_deriv, true);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1387 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1388 of file nnet-component.h.
 { return false; }
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 3177 of file nnet-component.cc.
References DctComponent::dct_mat_, DctComponent::DctComponent(), DctComponent::dim_, and DctComponent::reorder_.
{
   DctComponent *ans = new DctComponent();
   ans->dct_mat_ = dct_mat_;
   ans->dim_ = dim_;
   ans->reorder_ = reorder_;
   return ans;
 }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 3039 of file nnet-component.cc.
References DctComponent::dct_mat_, Component::Info(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   std::stringstream stream;
   stream << Component::Info() << ", dct_dim=" << dct_mat_.NumCols();
   if (dct_mat_.NumCols() != dct_mat_.NumRows())
     stream << ", dct_keep_dim=" << dct_mat_.NumRows();
   return stream.str();
 }
void Init (int32 dim, int32 dct_dim, bool reorder, int32 keep_dct_dim = 0)
Definition at line 3048 of file nnet-component.cc.
References kaldi::ComputeDctMatrix(), DctComponent::dct_mat_, DctComponent::dim_, KALDI_ASSERT, DctComponent::reorder_, and CuMatrix< Real >::Resize().
Referenced by DctComponent::InitFromString(), DctComponent::Read(), and kaldi::nnet2::UnitTestDctComponent().
{
   int dct_keep_dim_ = (dct_keep_dim > 0) ? dct_keep_dim : dct_dim;
   KALDI_ASSERT(dim > 0 && dct_dim > 0);
   KALDI_ASSERT(dim % dct_dim == 0); // dct_dim must divide dim.
   KALDI_ASSERT(dct_dim >= dct_keep_dim_);
   dim_ = dim;
   dct_mat_.Resize(dct_keep_dim_, dct_dim);
   reorder_ = reorder;
   Matrix<BaseFloat> dct_mat(dct_keep_dim_, dct_dim);
   ComputeDctMatrix(&dct_mat);
   dct_mat_ = dct_mat;
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 3064 of file nnet-component.cc.
References DctComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), and DctComponent::Type().
Referenced by kaldi::nnet2::UnitTestDctComponent().
{
   std::string orig_args(args);
   int32 dim, dct_dim, dct_keep_dim = 0;
   bool reorder = false;
   bool ok = ParseFromString("dim", &args, &dim);
   ok = ParseFromString("dct-dim", &args, &dct_dim) && ok;
   ok = ParseFromString("reorder", &args, &reorder) && ok;
   ParseFromString("dct-keep-dim", &args, &dct_keep_dim);
   if (!ok || !args.empty() || dim <= 0 || dct_dim <= 0 || dct_keep_dim < 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   Init(dim, dct_dim, reorder, dct_keep_dim);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1373 of file nnet-component.h.
References DctComponent::dim_.
Referenced by DctComponent::Propagate().
 { return dim_; }
KALDI_DISALLOW_COPY_AND_ASSIGN (DctComponent) private
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1374 of file nnet-component.h.
References DctComponent::dct_mat_, DctComponent::dim_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by DctComponent::Backprop().
 { return dct_mat_.NumRows() * (dim_ / dct_mat_.NumCols()); }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 3106 of file nnet-component.cc.
References CuMatrixBase< Real >::AddMatMat(), ChunkInfo::CheckSize(), DctComponent::dct_mat_, DctComponent::dim_, DctComponent::InputDim(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, ChunkInfo::NumCols(), CuMatrixBase< Real >::NumCols(), ChunkInfo::NumRows(), CuMatrixBase< Real >::NumRows(), DctComponent::Reorder(), and DctComponent::reorder_.
{
   KALDI_ASSERT(in.NumCols() == InputDim());
   int32 dct_dim = dct_mat_.NumCols(),
         dct_keep_dim = dct_mat_.NumRows(),
         num_rows = in.NumRows(),
         num_chunks = dim_ / dct_dim;
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(num_rows == out_info.NumRows());
   KALDI_ASSERT(num_chunks * dct_keep_dim == out_info.NumCols());
   CuMatrix<BaseFloat> in_tmp;
   if (reorder_) {
     in_tmp = in;
     Reorder(&in_tmp, false);
   }
   for (int32 chunk = 0; chunk < num_chunks; chunk++) {
     CuSubMatrix<BaseFloat> in_mat(reorder_ ? in_tmp : in,
                                 0, num_rows, dct_dim * chunk, dct_dim),
                         out_mat(*out,
                                 0, num_rows, dct_keep_dim * chunk, dct_keep_dim);
     out_mat.AddMatMat(1.0, in_mat, kNoTrans, dct_mat_, kTrans, 0.0);
   }
   if (reorder_)
     Reorder(out, true);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 3200 of file nnet-component.cc.
References DctComponent::dim_, kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), DctComponent::Init(), KALDI_ASSERT, KALDI_ERR, kaldi::ReadBasicType(), kaldi::ReadToken(), and DctComponent::reorder_.
{
   ExpectOneOrTwoTokens(is, binary, "<DctComponent>", "<Dim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<DctDim>");
   int32 dct_dim;
   ReadBasicType(is, binary, &dct_dim);
   ExpectToken(is, binary, "<Reorder>");
   ReadBasicType(is, binary, &reorder_);
   int32 dct_keep_dim = dct_dim;
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "<DctKeepDim>") {
     ReadBasicType(is, binary, &dct_keep_dim);
     ExpectToken(is, binary, "</DctComponent>");
   } else if (token != "</DctComponent>") {
     KALDI_ERR << "Expected token \"</DctComponent>\", got instead \""
               << token << "\".";
   }
   KALDI_ASSERT(dct_dim > 0 && dim_ > 0 && dim_ % dct_dim == 0);
   Init(dim_, dct_dim, reorder_, dct_keep_dim);
   //idct_mat_.Resize(dct_keep_dim, dct_dim);
   //ComputeDctMatrix(&dct_mat_);
 }
void Reorder (CuMatrixBase< BaseFloat > * mat, bool reverse) const private
Definition at line 3080 of file nnet-component.cc.
References CuVectorBase< Real >::CopyFromVec(), DctComponent::dct_mat_, DctComponent::dim_, rnnlm::i, rnnlm::j, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and kaldi::swap().
Referenced by DctComponent::Backprop(), and DctComponent::Propagate().
{
   // reorders into contiguous blocks of dize "dct_dim_", assuming that
   // such blocks were interlaced before.  if reverse==true, does the
   // reverse.
   int32 dct_dim = dct_mat_.NumCols(),
       dct_keep_dim = dct_mat_.NumRows(),
       block_size_in = dim_ / dct_dim,
       block_size_out = dct_keep_dim;
   //This does not necesarily needs to be true anymore -- output must be reordered as well, but the dimension differs...
   //KALDI_ASSERT(mat->NumCols() == dim_);
   if (reverse) std::swap(block_size_in, block_size_out);
   CuVector<BaseFloat> temp(mat->NumCols());
   for (int32 i = 0; i < mat->NumRows(); i++) {
     CuSubVector<BaseFloat> row(*mat, i);
     int32 num_blocks_in = block_size_out;
     for (int32 b = 0; b < num_blocks_in; b++) {
       for (int32 j = 0; j < block_size_in; j++) {
         temp(j * block_size_out + b) = row(b * block_size_in + j);
       }
     }
     row.CopyFromVec(temp);
   }
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1364 of file nnet-component.h.
Referenced by DctComponent::InitFromString().
 { return "DctComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3185 of file nnet-component.cc.
References DctComponent::dct_mat_, DctComponent::dim_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), DctComponent::reorder_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<DctComponent>");
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<DctDim>");
   int32 dct_dim = dct_mat_.NumCols();
   WriteBasicType(os, binary, dct_dim);
   WriteToken(os, binary, "<Reorder>");
   WriteBasicType(os, binary, reorder_);
   WriteToken(os, binary, "<DctKeepDim>");
   int32 dct_keep_dim = dct_mat_.NumRows();
   WriteBasicType(os, binary, dct_keep_dim);
   WriteToken(os, binary, "</DctComponent>");
 }
Member Data Documentation
CuMatrix<BaseFloat> dct_mat_ private
Definition at line 1405 of file nnet-component.h.
Referenced by DctComponent::Backprop(), DctComponent::Copy(), DctComponent::Info(), DctComponent::Init(), DctComponent::OutputDim(), DctComponent::Propagate(), DctComponent::Reorder(), and DctComponent::Write().
int32 dim_ private
Definition at line 1394 of file nnet-component.h.
Referenced by DctComponent::Backprop(), DctComponent::Copy(), DctComponent::DctComponent(), DctComponent::Init(), DctComponent::InputDim(), DctComponent::OutputDim(), DctComponent::Propagate(), DctComponent::Read(), DctComponent::Reorder(), and DctComponent::Write().
bool reorder_ private
Definition at line 1396 of file nnet-component.h.
Referenced by DctComponent::Backprop(), DctComponent::Copy(), DctComponent::Init(), DctComponent::Propagate(), DctComponent::Read(), and DctComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc