Kaldi: RandomComponent Class Reference
RandomComponent Class Reference
#include <nnet-component.h>
Public Member Functions
void ResetGenerator ()
Public Member Functions inherited from Component
Component ()
virtual std::string Type () const =0
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual void InitFromString (std::string args)=0
Initialize, typically from a line of a config file.
virtual int32 InputDim () const =0
Get size of input vectors.
virtual int32 OutputDim () const =0
Get size of output vectors.
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const =0
Perform forward pass propagation Input->Output.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const =0
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const =0
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)=0
virtual void Write (std::ostream &os, bool binary) const =0
Write component to stream.
virtual std::string Info () const
virtual ~Component ()
Protected Attributes
CuRand< BaseFloat > random_generator_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
Definition at line 1080 of file nnet-component.h.
Member Function Documentation
void ResetGenerator () inline
Definition at line 1086 of file nnet-component.h.
References RandomComponent::random_generator_, and CuRand< Real >::SeedGpu().
Referenced by Nnet::ResetGenerators(), and kaldi::nnet2::UnitTestGenericComponentInternal().
 { random_generator_.SeedGpu(0); }
Member Data Documentation
CuRand<BaseFloat> random_generator_ protected
Definition at line 1088 of file nnet-component.h.
Referenced by DropoutComponent::Propagate(), AdditiveNoiseComponent::Propagate(), and RandomComponent::ResetGenerator().
The documentation for this class was generated from the following file:
nnet2/nnet-component.h