Kaldi: ConstArpaLmDeterministicFst Class Reference
ConstArpaLmDeterministicFst Class Reference
This class wraps a ConstArpaLm format language model with the interface defined in DeterministicOnDemandFst.
#include <const-arpa-lm.h>
Public Types
typedef fst::StdArc::Weight Weight
typedef fst::StdArc::StateId StateId
typedef fst::StdArc::Label Label
Public Types inherited from DeterministicOnDemandFst< fst::StdArc >
typedef fst::StdArc::StateId StateId
typedef fst::StdArc::Weight Weight
typedef fst::StdArc::Label Label
Public Member Functions
ConstArpaLmDeterministicFst (const ConstArpaLm &lm)
virtual StateId Start ()
virtual Weight Final (StateId s)
virtual bool GetArc (StateId s, Label ilabel, fst::StdArc *oarc)
Note: ilabel must not be epsilon.
Public Member Functions inherited from DeterministicOnDemandFst< fst::StdArc >
virtual ~DeterministicOnDemandFst ()
Private Types
typedef unordered_map
< std::vector< Label >
, StateId, VectorHasher< Label > > MapType
Private Attributes
StateId start_state_
MapType wseq_to_state_
std::vector< std::vector< Label > > state_to_wseq_
const ConstArpaLm & lm_
Detailed Description
This class wraps a ConstArpaLm format language model with the interface defined in DeterministicOnDemandFst.
Definition at line 390 of file const-arpa-lm.h.
Member Typedef Documentation
typedef fst::StdArc::Label Label
Definition at line 395 of file const-arpa-lm.h.
typedef unordered_map<std::vector<Label>, StateId, VectorHasher<Label> > MapType private
Definition at line 411 of file const-arpa-lm.h.
typedef fst::StdArc::StateId StateId
Definition at line 394 of file const-arpa-lm.h.
typedef fst::StdArc::Weight Weight
Definition at line 393 of file const-arpa-lm.h.
Constructor & Destructor Documentation
ConstArpaLmDeterministicFst (const ConstArpaLm & lm) explicit
Definition at line 1004 of file const-arpa-lm.cc.
References ConstArpaLm::BosSymbol(), ConstArpaLmDeterministicFst::lm_, ConstArpaLmDeterministicFst::start_state_, ConstArpaLmDeterministicFst::state_to_wseq_, and ConstArpaLmDeterministicFst::wseq_to_state_.
                            : lm_(lm) {
   // Creates a history state for <s>.
   std::vector<Label> bos_state(1, lm_.BosSymbol());
   state_to_wseq_.push_back(bos_state);
   wseq_to_state_[bos_state] = 0;
   start_state_ = 0;
 }
Member Function Documentation
fst::StdArc::Weight Final (StateId s) virtual
Implements DeterministicOnDemandFst< fst::StdArc >.
Definition at line 1013 of file const-arpa-lm.cc.
References ConstArpaLm::EosSymbol(), ConstArpaLm::GetNgramLogprob(), KALDI_ASSERT, ConstArpaLmDeterministicFst::lm_, logprob, and ConstArpaLmDeterministicFst::state_to_wseq_.
{
   // At this point, we should have created the state.
   KALDI_ASSERT(static_cast<size_t>(s) < state_to_wseq_.size());
   const std::vector<Label>& wseq = state_to_wseq_[s];
   float logprob = lm_.GetNgramLogprob(lm_.EosSymbol(), wseq);
   return Weight(-logprob);
 }
bool GetArc (StateId s, Label ilabel, fst::StdArc * oarc) virtual
Note: ilabel must not be epsilon.
Implements DeterministicOnDemandFst< fst::StdArc >.
Definition at line 1021 of file const-arpa-lm.cc.
References ConstArpaLm::GetNgramLogprob(), ConstArpaLm::HistoryStateExists(), KALDI_ASSERT, ConstArpaLmDeterministicFst::lm_, logprob, ConstArpaLm::NgramOrder(), ConstArpaLmDeterministicFst::state_to_wseq_, and ConstArpaLmDeterministicFst::wseq_to_state_.
{
   // At this point, we should have created the state.
   KALDI_ASSERT(static_cast<size_t>(s) < state_to_wseq_.size());
   std::vector<Label> wseq = state_to_wseq_[s];
   float logprob = lm_.GetNgramLogprob(ilabel, wseq);
   if (logprob == std::numeric_limits<float>::min()) {
     return false;
   }
   // Locates the next state in ConstArpaLm. Note that OOV and backoff have been
   // taken care of in ConstArpaLm.
   wseq.push_back(ilabel);
   while (wseq.size() >= lm_.NgramOrder()) {
     // History state has at most lm_.NgramOrder() -1 words in the state.
     wseq.erase(wseq.begin(), wseq.begin() + 1);
   }
   while (!lm_.HistoryStateExists(wseq)) {
     KALDI_ASSERT(wseq.size() > 0);
     wseq.erase(wseq.begin(), wseq.begin() + 1);
   }
   std::pair<const std::vector<Label>, StateId> wseq_state_pair(
       wseq, static_cast<Label>(state_to_wseq_.size()));
   // Attemps to insert the current <wseq_state_pair>. If the pair already exists
   // then it returns false.
   typedef MapType::iterator IterType;
   std::pair<IterType, bool> result = wseq_to_state_.insert(wseq_state_pair);
   // If the pair was just inserted, then also add it to <state_to_wseq_>.
   if (result.second == true)
     state_to_wseq_.push_back(wseq);
   // Creates the arc.
   oarc->ilabel = ilabel;
   oarc->olabel = ilabel;
   oarc->nextstate = result.first->second;
   oarc->weight = Weight(-logprob);
   return true;
 }
virtual StateId Start () inline virtual
Implements DeterministicOnDemandFst< fst::StdArc >.
Definition at line 401 of file const-arpa-lm.h.
References ConstArpaLmDeterministicFst::start_state_.
 { return start_state_; }
Member Data Documentation
const ConstArpaLm& lm_ private
Definition at line 415 of file const-arpa-lm.h.
Referenced by ConstArpaLmDeterministicFst::ConstArpaLmDeterministicFst(), ConstArpaLmDeterministicFst::Final(), and ConstArpaLmDeterministicFst::GetArc().
StateId start_state_ private
Definition at line 412 of file const-arpa-lm.h.
Referenced by ConstArpaLmDeterministicFst::ConstArpaLmDeterministicFst(), and ConstArpaLmDeterministicFst::Start().
std::vector<std::vector<Label> > state_to_wseq_ private
Definition at line 414 of file const-arpa-lm.h.
Referenced by ConstArpaLmDeterministicFst::ConstArpaLmDeterministicFst(), ConstArpaLmDeterministicFst::Final(), and ConstArpaLmDeterministicFst::GetArc().
MapType wseq_to_state_ private
Definition at line 413 of file const-arpa-lm.h.
Referenced by ConstArpaLmDeterministicFst::ConstArpaLmDeterministicFst(), and ConstArpaLmDeterministicFst::GetArc().
The documentation for this class was generated from the following files:
lm/const-arpa-lm.h
lm/const-arpa-lm.cc