Kaldi: SimpleForwardingDescriptor Class Reference
SimpleForwardingDescriptor Class Reference
#include <nnet-descriptor.h>
Public Member Functions
virtual Cindex MapToInput (const Index &index) const
virtual int32 Dim (const Nnet &nnet) const
virtual ForwardingDescriptor * Copy () const
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" all the node indexes.
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
SimpleForwardingDescriptor (int32 src_node)
virtual ~SimpleForwardingDescriptor ()
Public Member Functions inherited from ForwardingDescriptor
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Attributes
int32 src_node_
Detailed Description
Definition at line 129 of file nnet-descriptor.h.
Constructor & Destructor Documentation
SimpleForwardingDescriptor (int32 src_node) inline
Definition at line 142 of file nnet-descriptor.h.
References KALDI_ASSERT.
Referenced by SimpleForwardingDescriptor::Copy().
                                             : src_node_(src_node) {
     KALDI_ASSERT(src_node >= 0);
   }
virtual ~SimpleForwardingDescriptor () inline virtual
Definition at line 145 of file nnet-descriptor.h.
 { }
Member Function Documentation
ForwardingDescriptor * Copy () const virtual
Implements ForwardingDescriptor.
Definition at line 87 of file nnet-descriptor.cc.
References SimpleForwardingDescriptor::SimpleForwardingDescriptor(), and SimpleForwardingDescriptor::src_node_.
{
   return new SimpleForwardingDescriptor(src_node_);
 }
int32 Dim (const Nnet & nnet) const virtual
Implements ForwardingDescriptor.
Definition at line 79 of file nnet-descriptor.cc.
References NetworkNode::Dim(), Nnet::GetNode(), and SimpleForwardingDescriptor::src_node_.
{
   return nnet.GetNode(src_node_).Dim(nnet);
 }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" all the node indexes.
Implements ForwardingDescriptor.
Definition at line 91 of file nnet-descriptor.cc.
References SimpleForwardingDescriptor::src_node_.
{
   node_indexes->push_back(src_node_);
 }
Cindex MapToInput (const Index & index) const virtual
Implements ForwardingDescriptor.
Definition at line 83 of file nnet-descriptor.cc.
References SimpleForwardingDescriptor::src_node_.
{
   return Cindex(src_node_, index);
 }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Implements ForwardingDescriptor.
Definition at line 96 of file nnet-descriptor.cc.
References kaldi::nnet3::IsValidName(), KALDI_ASSERT, and SimpleForwardingDescriptor::src_node_.
{
   KALDI_ASSERT(static_cast<size_t>(src_node_) < node_names.size() &&
                IsValidName(node_names[src_node_]));
   os << node_names[src_node_];
 }
Member Data Documentation
int32 src_node_ private
Definition at line 147 of file nnet-descriptor.h.
Referenced by SimpleForwardingDescriptor::Copy(), SimpleForwardingDescriptor::Dim(), SimpleForwardingDescriptor::GetNodeDependencies(), SimpleForwardingDescriptor::MapToInput(), and SimpleForwardingDescriptor::WriteConfig().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc