Kaldi: KaldiWarnMessage Class Reference
KaldiWarnMessage Class Reference
"Functions relating to logging and error reporting"
#include <kaldi-error.h>
Public Member Functions
std::ostream & stream ()
KaldiWarnMessage (const char *func, const char *file, int32 line)
~KaldiWarnMessage ()
Private Attributes
std::ostringstream ss_
Detailed Description
Definition at line 72 of file kaldi-error.h.
Constructor & Destructor Documentation
KaldiWarnMessage (const char * func, const char * file, int32 line)
Definition at line 150 of file kaldi-error.cc.
References kaldi::GetProgramName(), kaldi::GetShortFileName(), and KaldiWarnMessage::stream().
{
   this->stream() << "WARNING (" << GetProgramName() << func << "():"
                  << GetShortFileName(file) << ':' << line << ") ";
 }
~KaldiWarnMessage ()
Definition at line 156 of file kaldi-error.cc.
References KaldiWarnMessage::ss_.
{
   std::string str = ss_.str();
   while (!str.empty() && str[str.length() - 1] == '\n')
     str.resize(str.length() - 1);
   fprintf(stderr, "%s\n", str.c_str());
 }
Member Function Documentation
std::ostream& stream () inline
Definition at line 74 of file kaldi-error.h.
References KaldiWarnMessage::ss_.
Referenced by KaldiWarnMessage::KaldiWarnMessage().
 { return ss_; }
Member Data Documentation
std::ostringstream ss_ private
Definition at line 78 of file kaldi-error.h.
Referenced by KaldiWarnMessage::stream(), and KaldiWarnMessage::~KaldiWarnMessage().
The documentation for this class was generated from the following files:
base/kaldi-error.h
base/kaldi-error.cc