Kaldi: SumGroupComponent Class Reference
SumGroupComponent Class Reference
#include <nnet-component.h>
Public Member Functions
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
void Init (const std::vector< int32 > &sizes)
void GetSizes (std::vector< int32 > *sizes) const
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
SumGroupComponent ()
virtual std::string Type () const
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual std::string Info () const
virtual ~Component ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (SumGroupComponent)
Private Attributes
CuArray< Int32Pair > indexes_
CuArray< int32 > reverse_indexes_
int32 input_dim_
int32 output_dim_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
Definition at line 1274 of file nnet-component.h.
Constructor & Destructor Documentation
SumGroupComponent () inline
Definition at line 1284 of file nnet-component.h.
Referenced by SumGroupComponent::Copy().
 { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 2504 of file nnet-component.cc.
References CuMatrixBase< Real >::CopyCols(), SumGroupComponent::InputDim(), CuMatrixBase< Real >::NumRows(), CuMatrix< Real >::Resize(), and SumGroupComponent::reverse_indexes_.
{
   in_deriv->Resize(out_deriv.NumRows(), InputDim());
   in_deriv->CopyCols(out_deriv, reverse_indexes_);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1286 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1287 of file nnet-component.h.
 { return false; }
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 2448 of file nnet-component.cc.
References SumGroupComponent::indexes_, SumGroupComponent::input_dim_, SumGroupComponent::output_dim_, SumGroupComponent::reverse_indexes_, and SumGroupComponent::SumGroupComponent().
{
   SumGroupComponent *ans = new SumGroupComponent();
   ans->indexes_ = indexes_;
   ans->reverse_indexes_ = reverse_indexes_;
   ans->input_dim_ = input_dim_;
   ans->output_dim_ = output_dim_;
   return ans;
 }
void GetSizes (std::vector< int32 > * sizes) const
Definition at line 2471 of file nnet-component.cc.
References CuArray< T >::CopyToVec(), rnnlm::i, SumGroupComponent::indexes_, and KALDI_ASSERT.
Referenced by SoftmaxComponent::MixUp(), and SumGroupComponent::Write().
{
   std::vector<Int32Pair> indexes;
   indexes_.CopyToVec(&indexes);
   sizes->resize(indexes.size());
   for (size_t i = 0; i < indexes.size(); i++) {
     (*sizes)[i] = indexes[i].second - indexes[i].first;
     if (i == 0) { KALDI_ASSERT(indexes[i].first == 0); }
     else { KALDI_ASSERT(indexes[i].first == indexes[i-1].second); }
     KALDI_ASSERT(indexes[i].second > indexes[i].first);
     (*sizes)[i] = indexes[i].second - indexes[i].first;
   }
 }
void Init (const std::vector< int32 > & sizes)
Definition at line 2418 of file nnet-component.cc.
References rnnlm::i, SumGroupComponent::indexes_, SumGroupComponent::input_dim_, rnnlm::j, KALDI_ASSERT, SumGroupComponent::output_dim_, and SumGroupComponent::reverse_indexes_.
Referenced by SumGroupComponent::InitFromString(), SoftmaxComponent::MixUp(), SumGroupComponent::Read(), and kaldi::nnet2::UnitTestSumGroupComponent().
{
   KALDI_ASSERT(!sizes.empty());
   std::vector<Int32Pair> cpu_vec(sizes.size());
   std::vector<int32> reverse_cpu_vec;
   int32 cur_index = 0;
   for (size_t i = 0; i < sizes.size(); i++) {
     KALDI_ASSERT(sizes[i] > 0);
     cpu_vec[i].first = cur_index;
     cpu_vec[i].second = cur_index + sizes[i];
     cur_index += sizes[i];
     for (int32 j = cpu_vec[i].first; j < cpu_vec[i].second; j++)
       reverse_cpu_vec.push_back(i);
   }
   this->indexes_ = cpu_vec;
   this->reverse_indexes_ = reverse_cpu_vec;
   this->input_dim_ = cur_index;
   this->output_dim_ = sizes.size();
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 2437 of file nnet-component.cc.
References SumGroupComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), and SumGroupComponent::Type().
Referenced by kaldi::nnet2::UnitTestSumGroupComponent().
{
   std::string orig_args(args);
   std::vector<int32> sizes;
   bool ok = ParseFromString("sizes", &args, &sizes);
   if (!ok || !args.empty() || sizes.empty())
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   this->Init(sizes);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1276 of file nnet-component.h.
References SumGroupComponent::input_dim_.
Referenced by SumGroupComponent::Backprop().
 { return input_dim_; }
KALDI_DISALLOW_COPY_AND_ASSIGN (SumGroupComponent) private
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1277 of file nnet-component.h.
References SumGroupComponent::output_dim_.
 { return output_dim_; }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 2493 of file nnet-component.cc.
References ChunkInfo::CheckSize(), SumGroupComponent::indexes_, KALDI_ASSERT, ChunkInfo::NumChunks(), and CuMatrixBase< Real >::SumColumnRanges().
{
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   out->SumColumnRanges(in, indexes_);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 2457 of file nnet-component.cc.
References kaldi::nnet2::ExpectOneOrTwoTokens(), SumGroupComponent::Init(), KALDI_ERR, kaldi::ReadIntegerVector(), and kaldi::ReadToken().
{
   ExpectOneOrTwoTokens(is, binary, "<SumGroupComponent>", "<Sizes>");
   std::vector<int32> sizes;
   ReadIntegerVector(is, binary, &sizes);
   std::string token;
   ReadToken(is, binary, &token);
   if (!(token == "<SumGroupComponent>" ||
         token == "</SumGroupComponent>")) {
     KALDI_ERR << "Expected </SumGroupComponent>, got " << token;
   }
   this->Init(sizes);
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1285 of file nnet-component.h.
Referenced by SumGroupComponent::InitFromString().
 { return "SumGroupComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 2484 of file nnet-component.cc.
References SumGroupComponent::GetSizes(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<SumGroupComponent>");
   WriteToken(os, binary, "<Sizes>");
   std::vector<int32> sizes;
   this->GetSizes(&sizes);
   WriteIntegerVector(os, binary, sizes);
   WriteToken(os, binary, "</SumGroupComponent>");
 }
Member Data Documentation
CuArray<Int32Pair> indexes_ private
Definition at line 1309 of file nnet-component.h.
Referenced by SumGroupComponent::Copy(), SumGroupComponent::GetSizes(), SumGroupComponent::Init(), and SumGroupComponent::Propagate().
int32 input_dim_ private
Definition at line 1312 of file nnet-component.h.
Referenced by SumGroupComponent::Copy(), SumGroupComponent::Init(), and SumGroupComponent::InputDim().
int32 output_dim_ private
Definition at line 1313 of file nnet-component.h.
Referenced by SumGroupComponent::Copy(), SumGroupComponent::Init(), and SumGroupComponent::OutputDim().
CuArray<int32> reverse_indexes_ private
Definition at line 1311 of file nnet-component.h.
Referenced by SumGroupComponent::Backprop(), SumGroupComponent::Copy(), and SumGroupComponent::Init().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc