Kaldi: CopyComponent Class Reference
CopyComponent Class Reference
Rearrange the matrix columns according to the indices in copy_from_indices_.
#include <nnet-various.h>
Public Member Functions
CopyComponent (int32 dim_in, int32 dim_out)
~CopyComponent ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
std::string Info () const
Optionally print some additional info.
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
virtual bool IsUpdatable () const
Check if contains trainable parameters.
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string InfoGradient () const
Protected Attributes
CuArray< int32 > copy_from_indices_
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Static Private Member Functions
static int32 op_increase (int32 i)
static int32 op_decrease (int32 i)
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Detailed Description
Rearrange the matrix columns according to the indices in copy_from_indices_.
Definition at line 155 of file nnet-various.h.
Constructor & Destructor Documentation
CopyComponent (int32 dim_in, int32 dim_out) inline
Definition at line 157 of file nnet-various.h.
Referenced by CopyComponent::Copy().
     : Component(dim_in, dim_out)
   { }
~CopyComponent () inline
Definition at line 160 of file nnet-various.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 273 of file nnet-various.h.
References KALDI_WARN, and CuMatrixBase< Real >::SetZero().
{
     static bool warning_displayed = false;
     if (!warning_displayed) {
       KALDI_WARN << __func__ << "Not implemented!";
       warning_displayed = true;
     }
     in_diff->SetZero();
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 163 of file nnet-various.h.
References CopyComponent::CopyComponent().
 { return new CopyComponent(*this); }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 164 of file nnet-various.h.
References Component::kCopy.
 { return kCopy; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 258 of file nnet-various.h.
{
     /*
     std::ostringstream ostr;
     ostr << "\n  copy_from_indices " << copy_from_indices_;
     std::string str = ostr.str();
     str.erase(str.end()-1);
     return str;
     */
     return "";
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Reimplemented from Component.
Definition at line 166 of file nnet-various.h.
References CopyComponent::copy_from_indices_, rnnlm::i, Component::InputDim(), rnnlm::j, KALDI_ASSERT, KALDI_ERR, CopyComponent::op_decrease(), Component::OutputDim(), kaldi::ReadIntegerVector(), kaldi::ReadToken(), and kaldi::SplitStringToIntegers().
{
     // define options
     std::vector<int32> copy_from_indices;
     std::vector<std::vector<int32> > build_vector;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
        if (token == "<ReadVector>") {
         ReadIntegerVector(is, false, &copy_from_indices);
       } else if (token == "<BuildVector>") {
         // <BuildVector> 1:1:1000 1:1:1000 1 2 3 1:10 </BuildVector> [matlab indexing]
         // read the colon-separated-lists:
         while (!is.eof()) {
           std::string colon_sep_list_or_end;
           ReadToken(is, false, &colon_sep_list_or_end);
           if (colon_sep_list_or_end == "</BuildVector>") break;
           std::vector<int32> v;
           SplitStringToIntegers(colon_sep_list_or_end, ":", false, &v);
           build_vector.push_back(v);
         }
       } else {
         KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                   << " (ReadVector|BuildVector)";
       }
       is >> std::ws; // eat-up whitespace
     }
     // build the vector, using <BuildVector> ... </BuildVector> inputs
     if (build_vector.size() > 0) {
       for (int32 i=0; i<build_vector.size(); i++) {
         switch (build_vector[i].size()) {
           case 1:
             copy_from_indices.push_back(build_vector[i][0]);
             break;
           case 2: { // assuming step 1
             int32 min=build_vector[i][0], max=build_vector[i][1];
             KALDI_ASSERT(min <= max);
             for (int32 j=min; j<=max; j++) {
               copy_from_indices.push_back(j);
             }}
             break;
           case 3: { // step can be negative -> flipped min/max
             int32 min=build_vector[i][0], step=build_vector[i][1], max=build_vector[i][2];
             KALDI_ASSERT((min <= max && step > 0) || (min >= max && step < 0));
             for (int32 j=min; j<=max; j += step) {
               copy_from_indices.push_back(j);
             }}
             break;
           case 0:
           default:
             KALDI_ERR << "Error parsing <BuildVector>";
         }
       }
     }
     // decrease by 1
     std::vector<int32>& v = copy_from_indices;
     std::transform(v.begin(), v.end(), v.begin(), op_decrease);
     // copy to GPU
     copy_from_indices_ = copy_from_indices;
     // check range
     for (int32 i=0; i<copy_from_indices.size(); i++) {
       KALDI_ASSERT(copy_from_indices[i] >= 0);
       KALDI_ASSERT(copy_from_indices[i] < InputDim());
     }
     // check dim
     KALDI_ASSERT(copy_from_indices_.Dim() == OutputDim());
   }
static int32 op_decrease (int32 i) inline static private
Definition at line 288 of file nnet-various.h.
References rnnlm::i.
Referenced by CopyComponent::InitData(), and CopyComponent::ReadData().
 { return --i; }
static int32 op_increase (int32 i) inline static private
Definition at line 287 of file nnet-various.h.
References rnnlm::i.
Referenced by CopyComponent::WriteData().
 { return ++i; }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 269 of file nnet-various.h.
References kaldi::cu::Copy(), and CopyComponent::copy_from_indices_.
{
     cu::Copy(in,copy_from_indices_,out);
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 237 of file nnet-various.h.
References CopyComponent::copy_from_indices_, KALDI_ASSERT, CopyComponent::op_decrease(), Component::OutputDim(), and kaldi::ReadIntegerVector().
{
     std::vector<int32> copy_from_indices;
     ReadIntegerVector(is, binary, &copy_from_indices);
     // -1 from each element
     std::vector<int32>& v = copy_from_indices;
     std::transform(v.begin(), v.end(), v.begin(), op_decrease);
     //
     copy_from_indices_ = copy_from_indices;
     KALDI_ASSERT(copy_from_indices_.Dim() == OutputDim());
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 248 of file nnet-various.h.
References CopyComponent::copy_from_indices_, CuArray< T >::CopyToVec(), CuArray< T >::Dim(), CopyComponent::op_increase(), and kaldi::WriteIntegerVector().
{
     std::vector<int32> copy_from_indices(copy_from_indices_.Dim());
     copy_from_indices_.CopyToVec(&copy_from_indices);
     // +1 to each element
     std::vector<int32>& v = copy_from_indices;
     std::transform(v.begin(), v.end(), v.begin(), op_increase);
     //
     WriteIntegerVector(os, binary, copy_from_indices);
   }
Member Data Documentation
CuArray<int32> copy_from_indices_ protected
Definition at line 284 of file nnet-various.h.
Referenced by CopyComponent::InitData(), CopyComponent::PropagateFnc(), CopyComponent::ReadData(), and CopyComponent::WriteData().
The documentation for this class was generated from the following file:
nnet/nnet-various.h