Kaldi: Semaphore Class Reference
Semaphore Class Reference
#include <kaldi-semaphore.h>
Public Member Functions
Semaphore (int32 initValue=0)
~Semaphore ()
bool TryWait ()
Returns true if Wait() goes through.
void Wait ()
decrease the counter
void Signal ()
increase the counter
int32 GetValue ()
returns the counter value, zero means no resources, the Wait() will block
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (Semaphore)
Private Attributes
int32 counter_
the semaphore counter, 0 means block on Wait()
pthread_mutex_t mutex_
pthread_cond_t cond_
Detailed Description
Definition at line 28 of file kaldi-semaphore.h.
Constructor & Destructor Documentation
Semaphore (int32 initValue = 0)
Definition at line 28 of file kaldi-semaphore.cc.
References Semaphore::cond_, Semaphore::counter_, KALDI_ERR, and Semaphore::mutex_.
{
   counter_ = initValue;
   if (pthread_mutex_init(&mutex_, NULL) != 0) {
     KALDI_ERR << "Cannot initialize pthread mutex";
   }
   if (pthread_cond_init(&cond_, NULL) != 0) {
     KALDI_ERR << "Cannot initialize pthread conditional variable";
   }
 }
~Semaphore ()
Definition at line 40 of file kaldi-semaphore.cc.
References Semaphore::cond_, KALDI_ERR, and Semaphore::mutex_.
                       {
   if (pthread_mutex_destroy(&mutex_) != 0) {
     KALDI_ERR << "Cannot destroy pthread mutex";
   }
   if (pthread_cond_destroy(&cond_) != 0) {
     KALDI_ERR << "Cannot destroy pthread conditional variable";
   }
 }
Member Function Documentation
int32 GetValue () inline
returns the counter value, zero means no resources, the Wait() will block
Definition at line 41 of file kaldi-semaphore.h.
References Semaphore::counter_.
                    {
     return counter_;
   }
KALDI_DISALLOW_COPY_AND_ASSIGN (Semaphore) private
void Signal ()
increase the counter
Definition at line 83 of file kaldi-semaphore.cc.
References Semaphore::cond_, Semaphore::counter_, KALDI_ERR, and Semaphore::mutex_.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), ExamplesRepository::AcceptExamples(), DiscriminativeExamplesRepository::ExamplesDone(), ExamplesRepository::ExamplesDone(), NnetExampleBackgroundReader::GetNextMinibatch(), NnetExampleBackgroundReader::NnetExampleBackgroundReader(), DiscriminativeExamplesRepository::ProvideExample(), ExamplesRepository::ProvideExamples(), NnetExampleBackgroundReader::ReadExamples(), and TaskSequencer< C >::RunTask().
{
   int32 ret = 0;
   ret |= pthread_mutex_lock(&mutex_);
   counter_++;
   ret |= pthread_cond_signal(&cond_);
   ret |= pthread_mutex_unlock(&mutex_);
   if (ret != 0) {
     KALDI_ERR << "Error in pthreads";
   }
 }
bool TryWait ()
Returns true if Wait() goes through.
Definition at line 51 of file kaldi-semaphore.cc.
References Semaphore::counter_, KALDI_ERR, and Semaphore::mutex_.
{
   int32 ret = 0;
   bool try_wait_succeeded = false;
   ret |= pthread_mutex_lock(&mutex_);
   if (counter_ > 0) {
     counter_--;
     try_wait_succeeded = true;
   }
   ret |= pthread_mutex_unlock(&mutex_);
   if (ret != 0) {
     KALDI_ERR << "Error in pthreads";
   }
   return try_wait_succeeded;
 }
void Wait ()
decrease the counter
Definition at line 68 of file kaldi-semaphore.cc.
References Semaphore::cond_, Semaphore::counter_, KALDI_ERR, and Semaphore::mutex_.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), ExamplesRepository::AcceptExamples(), DiscriminativeExamplesRepository::ExamplesDone(), ExamplesRepository::ExamplesDone(), NnetExampleBackgroundReader::GetNextMinibatch(), DiscriminativeExamplesRepository::ProvideExample(), ExamplesRepository::ProvideExamples(), NnetExampleBackgroundReader::ReadExamples(), and TaskSequencer< C >::Run().
                      {
   int32 ret = 0;
   ret |= pthread_mutex_lock(&mutex_);
   while (counter_ <= 0) {
     ret |= pthread_cond_wait(&cond_, &mutex_);
   }
   counter_--;
   ret |= pthread_mutex_unlock(&mutex_);
   if (ret != 0) {
     KALDI_ERR << "Error in pthreads";
   }
 }
Member Data Documentation
pthread_cond_t cond_ private
Definition at line 49 of file kaldi-semaphore.h.
Referenced by Semaphore::Semaphore(), Semaphore::Signal(), Semaphore::Wait(), and Semaphore::~Semaphore().
int32 counter_ private
the semaphore counter, 0 means block on Wait()
Definition at line 46 of file kaldi-semaphore.h.
Referenced by Semaphore::GetValue(), Semaphore::Semaphore(), Semaphore::Signal(), Semaphore::TryWait(), and Semaphore::Wait().
pthread_mutex_t mutex_ private
Definition at line 48 of file kaldi-semaphore.h.
Referenced by Semaphore::Semaphore(), Semaphore::Signal(), Semaphore::TryWait(), Semaphore::Wait(), and Semaphore::~Semaphore().
The documentation for this class was generated from the following files:
thread/kaldi-semaphore.h
thread/kaldi-semaphore.cc