Kaldi: SequentialTableReaderArchiveImpl< Holder > Class Template Reference
SequentialTableReaderArchiveImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from SequentialTableReaderImplBase< Holder >
typedef Holder::T T
Public Member Functions
SequentialTableReaderArchiveImpl ()
virtual bool Open (const std::string &rspecifier)
virtual void Next ()
virtual bool IsOpen () const
virtual bool Done () const
virtual std::string Key ()
const T & Value ()
virtual void FreeCurrent ()
virtual bool Close ()
virtual ~SequentialTableReaderArchiveImpl ()
Public Member Functions inherited from SequentialTableReaderImplBase< Holder >
SequentialTableReaderImplBase ()
virtual ~SequentialTableReaderImplBase ()
Private Types
enum {
kUninitialized, kFileStart, kEof, kError,
kHaveObject, kFreedObject
}
Private Attributes
Input input_
Holder holder_
std::string key_
std::string rspecifier_
std::string archive_rxfilename_
RspecifierOptions opts_
enum
kaldi::SequentialTableReaderArchiveImpl:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::SequentialTableReaderArchiveImpl< Holder >
Definition at line 323 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef Holder::T T
Definition at line 326 of file kaldi-table-inl.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kUninitialized
kFileStart
kEof
kError
kHaveObject
kFreedObject
Definition at line 518 of file kaldi-table-inl.h.
        {  //  [The state of the reading process]        [does holder_ [is input_
     //                                                     have object]   open]
     kUninitialized,  // Uninitialized or closed.                  no         no
     kFileStart,      // [state we use internally: just opened.]   no         yes
     kEof,     // We did Next() and found eof in archive           no         no
     kError,   // Some other error                                 no         no
     kHaveObject,  // We read the key and the object after it.     yes        yes
     kFreedObject,  // The user called FreeCurrent().              no         yes
   } state_;
Constructor & Destructor Documentation
SequentialTableReaderArchiveImpl () inline
Definition at line 328 of file kaldi-table-inl.h.
 : state_(kUninitialized) { }
virtual ~SequentialTableReaderArchiveImpl () inline virtual
Definition at line 495 of file kaldi-table-inl.h.
References SequentialTableReaderArchiveImpl< Holder >::archive_rxfilename_, SequentialTableReaderArchiveImpl< Holder >::holder_, KALDI_ERR, KALDI_WARN, SequentialTableReaderArchiveImpl< Holder >::kError, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, SequentialTableReaderArchiveImpl< Holder >::opts_, RspecifierOptions::permissive, kaldi::PrintableRxfilename(), and SequentialTableReaderArchiveImpl< Holder >::state_.
{
     if (state_ == kError) {
       if (opts_.permissive)
         KALDI_WARN << "Error detected closing TableReader for archive "
                    << PrintableRxfilename(archive_rxfilename_)
                    << " but ignoring "
                    << "it as permissive mode specified.";
       else
         KALDI_ERR << "TableReader: error detected closing archive "
                   << PrintableRxfilename(archive_rxfilename_);
     }
     // If you don't want this exception to be thrown you can
     // call Close() and check the status.
     if (state_ == kHaveObject)
       holder_.Clear();
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 473 of file kaldi-table-inl.h.
References SequentialTableReaderArchiveImpl< Holder >::archive_rxfilename_, Input::Close(), SequentialTableReaderArchiveImpl< Holder >::holder_, SequentialTableReaderArchiveImpl< Holder >::input_, Input::IsOpen(), SequentialTableReaderArchiveImpl< Holder >::IsOpen(), KALDI_ERR, KALDI_WARN, SequentialTableReaderArchiveImpl< Holder >::kError, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, SequentialTableReaderArchiveImpl< Holder >::kUninitialized, SequentialTableReaderArchiveImpl< Holder >::opts_, RspecifierOptions::permissive, kaldi::PrintableRxfilename(), and SequentialTableReaderArchiveImpl< Holder >::state_.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Open().
{
     if (!this->IsOpen())
       KALDI_ERR << "Close() called on TableReader twice or otherwise wrongly.";
     if (input_.IsOpen())
       input_.Close();
     if (state_ == kHaveObject)
       holder_.Clear();
     bool ans;
     if (opts_.permissive) {
       ans = true;  // always return success.
       if (state_ == kError)
         KALDI_WARN << "Error detected closing TableReader for archive "
                    << PrintableRxfilename(archive_rxfilename_)
                    << " but ignoring "
                    << "it as permissive mode specified.";
     } else {
       ans = (state_ != kError);  // If error state, user should detect it.
     }
     state_ = kUninitialized;
     return ans;
   }
virtual bool Done () const inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 431 of file kaldi-table-inl.h.
References KALDI_ERR, SequentialTableReaderArchiveImpl< Holder >::kEof, SequentialTableReaderArchiveImpl< Holder >::kError, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, and SequentialTableReaderArchiveImpl< Holder >::state_.
{
     switch (state_) {
       case kHaveObject:
         return false;
       case kEof: case kError:
         return true;  // Error-state counts as Done(), but destructor
         // will fail (unless you check the status with Close()).
       default:
         KALDI_ERR << "Done() called on TableReader object at the wrong time.";
         return false;
     }
   }
virtual void FreeCurrent () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 464 of file kaldi-table-inl.h.
References SequentialTableReaderArchiveImpl< Holder >::holder_, KALDI_WARN, SequentialTableReaderArchiveImpl< Holder >::kFreedObject, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, and SequentialTableReaderArchiveImpl< Holder >::state_.
{
     if (state_ == kHaveObject) {
       holder_.Clear();
       state_ = kFreedObject;
     } else {
       KALDI_WARN << "TableReader: FreeCurernt called at the wrong time.";
     }
   }
virtual bool IsOpen () const inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 421 of file kaldi-table-inl.h.
References KALDI_ERR, SequentialTableReaderArchiveImpl< Holder >::kEof, SequentialTableReaderArchiveImpl< Holder >::kError, SequentialTableReaderArchiveImpl< Holder >::kFreedObject, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, SequentialTableReaderArchiveImpl< Holder >::kUninitialized, and SequentialTableReaderArchiveImpl< Holder >::state_.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close().
{
     switch (state_) {
       case kEof: case kError: case kHaveObject: case kFreedObject: return true;
       case kUninitialized: return false;
       default: KALDI_ERR << "IsOpen() called on invalid object.";  // kFileStart
         // is not valid state for user to call something on.
         return false;
     }
   }
virtual std::string Key () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 444 of file kaldi-table-inl.h.
References KALDI_ERR, SequentialTableReaderArchiveImpl< Holder >::key_, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, and SequentialTableReaderArchiveImpl< Holder >::state_.
{
     // Valid to call this whenever Done() returns false
     switch (state_) {
       case kHaveObject: break;  // only valid case.
       default:
         // coding error.
         KALDI_ERR << "Key() called on TableReader object at the wrong time.";
     }
     return key_;
   }
virtual void Next () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 371 of file kaldi-table-inl.h.
References SequentialTableReaderArchiveImpl< Holder >::archive_rxfilename_, kaldi::CharToString(), SequentialTableReaderArchiveImpl< Holder >::holder_, SequentialTableReaderArchiveImpl< Holder >::input_, KALDI_ERR, KALDI_WARN, SequentialTableReaderArchiveImpl< Holder >::kEof, SequentialTableReaderArchiveImpl< Holder >::kError, SequentialTableReaderArchiveImpl< Holder >::key_, SequentialTableReaderArchiveImpl< Holder >::kFileStart, SequentialTableReaderArchiveImpl< Holder >::kFreedObject, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, kaldi::PrintableRxfilename(), SequentialTableReaderArchiveImpl< Holder >::state_, and Input::Stream().
Referenced by SequentialTableReaderArchiveImpl< Holder >::Open().
                       {
     switch (state_) {
       case kHaveObject:
         holder_.Clear();
         break;
       case kFileStart: case kFreedObject:
         break;
       default:
         KALDI_ERR << "TableReader: Next() called wrongly.";
     }
     std::istream &is = input_.Stream();
     is.clear();  // Clear any fail bits that may have been set... just in case
     // this happened in the Read function.
     is >> key_;  // This eats up any leading whitespace and gets the string.
     if (is.eof()) {
       state_ = kEof;
       return;
     }
     if (is.fail()) {  // This shouldn't really happen, barring file-system
                       // errors.
       KALDI_WARN << "Error reading archive "
                  << PrintableRxfilename(archive_rxfilename_);
       state_ = kError;
       return;
     }
     int c;
     if ((c = is.peek()) != ' ' && c != '\t' && c != '\n') {  // We expect a
                                                      // space ' ' after the key.
       // We also allow tab [which is consumed] and newline [which is not], just
       // so we can read archives generated by scripts that may not be fully
       // aware of how this format works.
       KALDI_WARN << "Invalid archive file format: expected space after key "
                  << key_ << ", got character "
                  << CharToString(static_cast<char>(is.peek())) << ", reading "
                  << PrintableRxfilename(archive_rxfilename_);
       state_ = kError;
       return;
     }
     if (c != '\n') is.get();  // Consume the space or tab.
     if (holder_.Read(is)) {
       state_ = kHaveObject;
       return;
     } else {
       KALDI_WARN << "Object read failed, reading archive "
                  << PrintableRxfilename(archive_rxfilename_);
       state_ = kError;
       return;
     }
   }
virtual bool Open (const std::string & rspecifier) inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 330 of file kaldi-table-inl.h.
References SequentialTableReaderArchiveImpl< Holder >::archive_rxfilename_, kaldi::ClassifyRspecifier(), Input::Close(), SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::input_, KALDI_ASSERT, KALDI_ERR, KALDI_WARN, kaldi::kArchiveRspecifier, SequentialTableReaderArchiveImpl< Holder >::kEof, SequentialTableReaderArchiveImpl< Holder >::kError, SequentialTableReaderArchiveImpl< Holder >::kFileStart, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, SequentialTableReaderArchiveImpl< Holder >::kUninitialized, SequentialTableReaderArchiveImpl< Holder >::Next(), Input::Open(), Input::OpenTextMode(), SequentialTableReaderArchiveImpl< Holder >::opts_, RspecifierOptions::permissive, kaldi::PrintableRxfilename(), SequentialTableReaderArchiveImpl< Holder >::rspecifier_, and SequentialTableReaderArchiveImpl< Holder >::state_.
{
     if (state_ != kUninitialized) {
       if (!Close()) {  // call Close() yourself to suppress this exception.
         if (opts_.permissive)
           KALDI_WARN << "TableReader::Open, error closing previous input "
               "(only warning, since permissive mode).";
         else
           KALDI_ERR << "TableReader::Open, error closing previous input.";
       }
     }
     rspecifier_ = rspecifier;
     RspecifierType rs = ClassifyRspecifier(rspecifier,
                                            &archive_rxfilename_,
                                            &opts_);
     KALDI_ASSERT(rs == kArchiveRspecifier);
     bool ans;
     // NULL means don't expect binary-mode header
     if (Holder::IsReadInBinary())
       ans = input_.Open(archive_rxfilename_, NULL);
     else
       ans = input_.OpenTextMode(archive_rxfilename_);
     if (!ans) {  // header.
       KALDI_WARN << "TableReader: failed to open stream "
                  << PrintableRxfilename(archive_rxfilename_);
       state_ = kUninitialized;  // Failure on Open
       return false;  // User should print the error message.
     }
     state_ = kFileStart;
     Next();
     if (state_ == kError) {
       KALDI_WARN << "Error beginning to read archive file (wrong filename?): "
                  << PrintableRxfilename(archive_rxfilename_);
       input_.Close();
       state_ = kUninitialized;
       return false;
     }
     KALDI_ASSERT(state_ == kHaveObject || state_ == kEof);
     return true;
   }
const T& Value () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 454 of file kaldi-table-inl.h.
References SequentialTableReaderArchiveImpl< Holder >::holder_, KALDI_ERR, SequentialTableReaderArchiveImpl< Holder >::kHaveObject, and SequentialTableReaderArchiveImpl< Holder >::state_.
                    {
     switch (state_) {
       case kHaveObject:
         break;  // only valid case.
       default:
         // coding error.
         KALDI_ERR << "Value() called on TableReader object at the wrong time.";
     }
     return holder_.Value();
   }
Member Data Documentation
std::string archive_rxfilename_ private
Definition at line 516 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Next(), SequentialTableReaderArchiveImpl< Holder >::Open(), and SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl().
Holder holder_ private
Definition at line 513 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::FreeCurrent(), SequentialTableReaderArchiveImpl< Holder >::Next(), SequentialTableReaderArchiveImpl< Holder >::Value(), and SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl().
Input input_ private
Definition at line 512 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Next(), and SequentialTableReaderArchiveImpl< Holder >::Open().
std::string key_ private
Definition at line 514 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Key(), and SequentialTableReaderArchiveImpl< Holder >::Next().
RspecifierOptions opts_ private
Definition at line 517 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Open(), and SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl().
std::string rspecifier_ private
Definition at line 515 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderArchiveImpl< Holder >::Open().
enum { ... } state_
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close(), SequentialTableReaderArchiveImpl< Holder >::Done(), SequentialTableReaderArchiveImpl< Holder >::FreeCurrent(), SequentialTableReaderArchiveImpl< Holder >::IsOpen(), SequentialTableReaderArchiveImpl< Holder >::Key(), SequentialTableReaderArchiveImpl< Holder >::Next(), SequentialTableReaderArchiveImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::Value(), and SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h