Kaldi: NaturalGradientPerElementScaleComponent Class Reference
NaturalGradientPerElementScaleComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
NaturalGradientPerElementScaleComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
NaturalGradientPerElementScaleComponent (const NaturalGradientPerElementScaleComponent &other)
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev, int32 rank, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_minibatch)
void Init (std::string vector_filename, int32 rank, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_minibatch)
Public Member Functions inherited from PerElementScaleComponent
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
PerElementScaleComponent ()
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
PerElementScaleComponent (const PerElementScaleComponent &other)
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev)
void Init (std::string vector_filename)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Private Member Functions
virtual void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const
NaturalGradientPerElementScaleComponent & operator= (const NaturalGradientPerElementScaleComponent &other)
Private Attributes
BaseFloat max_change_per_minibatch_
OnlineNaturalGradient preconditioner_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from PerElementScaleComponent
virtual void UpdateSimple (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const PerElementScaleComponent & operator= (const PerElementScaleComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from PerElementScaleComponent
CuVector< BaseFloat > scales_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Detailed Description
Definition at line 1183 of file nnet-simple-component.h.
Constructor & Destructor Documentation
NaturalGradientPerElementScaleComponent () inline
Definition at line 1190 of file nnet-simple-component.h.
Referenced by NaturalGradientPerElementScaleComponent::Copy().
 { } // use Init to really initialize.
NaturalGradientPerElementScaleComponent (const NaturalGradientPerElementScaleComponent & other) explicit
Definition at line 2857 of file nnet-simple-component.cc.
                                                          :
     PerElementScaleComponent(other),
     max_change_per_minibatch_(other.max_change_per_minibatch_),
     preconditioner_(other.preconditioner_) { }
Member Function Documentation
Component * Copy () const virtual
Copies component (deep copy).
Reimplemented from PerElementScaleComponent.
Definition at line 2866 of file nnet-simple-component.cc.
References NaturalGradientPerElementScaleComponent::NaturalGradientPerElementScaleComponent().
{
   return new NaturalGradientPerElementScaleComponent(*this);
 }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from PerElementScaleComponent.
Definition at line 2772 of file nnet-simple-component.cc.
References OnlineNaturalGradient::GetAlpha(), OnlineNaturalGradient::GetNumSamplesHistory(), OnlineNaturalGradient::GetRank(), OnlineNaturalGradient::GetUpdatePeriod(), PerElementScaleComponent::Info(), NaturalGradientPerElementScaleComponent::max_change_per_minibatch_, and NaturalGradientPerElementScaleComponent::preconditioner_.
{
   std::ostringstream stream;
   stream << PerElementScaleComponent::Info()
          << ", rank=" << preconditioner_.GetRank()
          << ", update-period=" << preconditioner_.GetUpdatePeriod()
          << ", num-samples-history=" << preconditioner_.GetNumSamplesHistory()
          << ", alpha=" << preconditioner_.GetAlpha()
          << ", max-change-per-minibatch=" << max_change_per_minibatch_;
   return stream.str();
 }
void Init (int32 dim, BaseFloat param_mean, BaseFloat param_stddev, int32 rank, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_minibatch)
Definition at line 2825 of file nnet-simple-component.cc.
References PerElementScaleComponent::Init(), KALDI_WARN, NaturalGradientPerElementScaleComponent::max_change_per_minibatch_, NaturalGradientPerElementScaleComponent::preconditioner_, OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
Referenced by NaturalGradientPerElementScaleComponent::InitFromConfig().
{
   PerElementScaleComponent::Init(dim, param_mean,
                                  param_stddev);
   preconditioner_.SetRank(rank);
   preconditioner_.SetUpdatePeriod(update_period);
   preconditioner_.SetNumSamplesHistory(num_samples_history);
   preconditioner_.SetAlpha(alpha);
   max_change_per_minibatch_ = max_change_per_minibatch;
   if (max_change_per_minibatch > 0.0)
     KALDI_WARN << "You are setting a positive max_change_per_minibatch for "
                << "NaturalGradientPerElementScaleComponent. But the per-component "
                << "gradient clipping mechansim has been removed. Instead it's currently "
                << "done at the whole model level.";
 }
void Init (std::string vector_filename, int32 rank, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_minibatch)
Definition at line 2844 of file nnet-simple-component.cc.
References PerElementScaleComponent::Init(), NaturalGradientPerElementScaleComponent::max_change_per_minibatch_, NaturalGradientPerElementScaleComponent::preconditioner_, OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
{
   PerElementScaleComponent::Init(vector_filename);
   preconditioner_.SetRank(rank);
   preconditioner_.SetUpdatePeriod(update_period);
   preconditioner_.SetNumSamplesHistory(num_samples_history);
   preconditioner_.SetAlpha(alpha);
   max_change_per_minibatch_ = max_change_per_minibatch;
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Reimplemented from PerElementScaleComponent.
Definition at line 2783 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), NaturalGradientPerElementScaleComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), KALDI_ASSERT, KALDI_ERR, NaturalGradientPerElementScaleComponent::Type(), and ConfigLine::WholeLine().
{
   // First set various configuration values that have defaults.
   int32 rank = 8,  // Use a small rank because in this case the amount of memory
                    // for the preconditioner actually exceeds the memory for the
                    // parameters (by "rank").
       update_period = 10;
   // the max_change_per_minibatch is the maximum amount of parameter-change, in 2-norm,
   // that we allow per minibatch; if change is greater than that, we scale down
   // the parameter-change.  It has the same purpose as the max-change-per-sample in
   // the NaturalGradientAffineComponent.
   BaseFloat num_samples_history = 2000.0, alpha = 4.0,
       max_change_per_minibatch = 0.0;
   cfl->GetValue("rank", &rank);
   cfl->GetValue("update-period", &update_period);
   cfl->GetValue("num-samples-history", &num_samples_history);
   cfl->GetValue("alpha", &alpha);
   cfl->GetValue("max-change-per-minibatch", &max_change_per_minibatch);
   InitLearningRatesFromConfig(cfl);
   std::string filename;
   // Accepts "scales" config (for filename) or "dim" -> random init, for testing.
   if (cfl->GetValue("scales", &filename)) {
     if (cfl->HasUnusedValues())
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     Init(filename, rank, update_period, num_samples_history,
          alpha, max_change_per_minibatch);
   } else {
     BaseFloat param_mean = 1.0, param_stddev = 0.0;
     cfl->GetValue("param-mean", &param_mean);
     cfl->GetValue("param-stddev", &param_stddev);
     int32 dim;
     if (!cfl->GetValue("dim", &dim) || cfl->HasUnusedValues())
       KALDI_ERR << "Invalid initializer for layer of type "
                 << Type() << ": \"" << cfl->WholeLine() << "\"";
     KALDI_ASSERT(dim > 0);
     Init(dim, param_mean, param_stddev, rank, update_period,
          num_samples_history, alpha, max_change_per_minibatch);
   }
 }
const NaturalGradientPerElementScaleComponent& operator= (const NaturalGradientPerElementScaleComponent & other) private
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Reimplemented from PerElementScaleComponent.
Definition at line 2726 of file nnet-simple-component.cc.
References kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, NaturalGradientPerElementScaleComponent::max_change_per_minibatch_, NaturalGradientPerElementScaleComponent::preconditioner_, CuVector< Real >::Read(), kaldi::ReadBasicType(), UpdatableComponent::ReadUpdatableCommon(), PerElementScaleComponent::scales_, OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
{
   ReadUpdatableCommon(is, binary);  // Read the opening tag and learning rate
   ExpectToken(is, binary, "<Params>");
   scales_.Read(is, binary);
   ExpectToken(is, binary, "<IsGradient>");
   ReadBasicType(is, binary, &is_gradient_);
   int32 rank, update_period;
   ExpectToken(is, binary, "<Rank>");
   ReadBasicType(is, binary, &rank);
   preconditioner_.SetRank(rank);
   ExpectToken(is, binary, "<UpdatePeriod>");
   ReadBasicType(is, binary, &update_period);
   preconditioner_.SetUpdatePeriod(update_period);
   BaseFloat num_samples_history, alpha;
   ExpectToken(is, binary, "<NumSamplesHistory>");
   ReadBasicType(is, binary, &num_samples_history);
   preconditioner_.SetNumSamplesHistory(num_samples_history);
   ExpectToken(is, binary, "<Alpha>");
   ReadBasicType(is, binary, &alpha);
   preconditioner_.SetAlpha(alpha);
   ExpectToken(is, binary, "<MaxChangePerMinibatch>");
   ReadBasicType(is, binary, &max_change_per_minibatch_);
   ExpectToken(is, binary, "</NaturalGradientPerElementScaleComponent>");
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Reimplemented from PerElementScaleComponent.
Definition at line 1191 of file nnet-simple-component.h.
Referenced by NaturalGradientPerElementScaleComponent::InitFromConfig().
{
     return "NaturalGradientPerElementScaleComponent";
   }
void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) private virtual
Reimplemented from PerElementScaleComponent.
Definition at line 2870 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), CuVectorBase< Real >::Dim(), UpdatableComponent::learning_rate_, CuMatrixBase< Real >::MulElements(), OnlineNaturalGradient::PreconditionDirections(), NaturalGradientPerElementScaleComponent::preconditioner_, and PerElementScaleComponent::scales_.
{
   CuMatrix<BaseFloat> derivs_per_frame(in_value);
   derivs_per_frame.MulElements(out_deriv);
   // the non-natural-gradient update would just do
   // scales_.AddRowSumMat(learning_rate_, derivs_per_frame).
   BaseFloat scale;
   preconditioner_.PreconditionDirections(&derivs_per_frame, NULL, &scale);
   CuVector<BaseFloat> delta_scales(scales_.Dim());
   delta_scales.AddRowSumMat(scale * learning_rate_, derivs_per_frame);
   scales_.AddVec(1.0, delta_scales);
 }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Reimplemented from PerElementScaleComponent.
Definition at line 2752 of file nnet-simple-component.cc.
References OnlineNaturalGradient::GetAlpha(), OnlineNaturalGradient::GetNumSamplesHistory(), OnlineNaturalGradient::GetRank(), OnlineNaturalGradient::GetUpdatePeriod(), UpdatableComponent::is_gradient_, NaturalGradientPerElementScaleComponent::max_change_per_minibatch_, NaturalGradientPerElementScaleComponent::preconditioner_, PerElementScaleComponent::scales_, CuVector< Real >::Write(), kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write the opening tag and learning rate
   WriteToken(os, binary, "<Params>");
   scales_.Write(os, binary);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   WriteToken(os, binary, "<Rank>");
   WriteBasicType(os, binary, preconditioner_.GetRank());
   WriteToken(os, binary, "<UpdatePeriod>");
   WriteBasicType(os, binary, preconditioner_.GetUpdatePeriod());
   WriteToken(os, binary, "<NumSamplesHistory>");
   WriteBasicType(os, binary, preconditioner_.GetNumSamplesHistory());
   WriteToken(os, binary, "<Alpha>");
   WriteBasicType(os, binary, preconditioner_.GetAlpha());
   WriteToken(os, binary, "<MaxChangePerMinibatch>");
   WriteBasicType(os, binary, max_change_per_minibatch_);
   WriteToken(os, binary, "</NaturalGradientPerElementScaleComponent>");
 }
Member Data Documentation
BaseFloat max_change_per_minibatch_ private
Definition at line 1214 of file nnet-simple-component.h.
Referenced by NaturalGradientPerElementScaleComponent::Info(), NaturalGradientPerElementScaleComponent::Init(), NaturalGradientPerElementScaleComponent::Read(), and NaturalGradientPerElementScaleComponent::Write().
OnlineNaturalGradient preconditioner_ private
Definition at line 1221 of file nnet-simple-component.h.
Referenced by NaturalGradientPerElementScaleComponent::Info(), NaturalGradientPerElementScaleComponent::Init(), NaturalGradientPerElementScaleComponent::Read(), NaturalGradientPerElementScaleComponent::Update(), and NaturalGradientPerElementScaleComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc