Kaldi: Convolutional1dComponent Class Reference
Convolutional1dComponent Class Reference
Convolutional1dComponent implements convolution over frequency axis.
#include <nnet-simple-component.h>
Public Member Functions
Convolutional1dComponent ()
Convolutional1dComponent (const Convolutional1dComponent &component)
Convolutional1dComponent (const CuMatrixBase< BaseFloat > &filter_params, const CuVectorBase< BaseFloat > &bias_params, BaseFloat learning_rate)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update_in, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
void SetParams (const VectorBase< BaseFloat > &bias, const MatrixBase< BaseFloat > &filter)
const CuVector< BaseFloat > & BiasParams ()
const CuMatrix< BaseFloat > & LinearParams ()
void Init (int32 input_dim, int32 output_dim, int32 patch_dim, int32 patch_step, int32 patch_stride, BaseFloat param_stddev, BaseFloat bias_stddev)
void Init (int32 patch_dim, int32 patch_step, int32 patch_stride, std::string matrix_filename)
void Resize (int32 input_dim, int32 output_dim)
void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Private Member Functions
const Convolutional1dComponent & operator= (const Convolutional1dComponent &other)
Static Private Member Functions
static void ReverseIndexes (const std::vector< int32 > &forward_indexes, int32 input_dim, std::vector< std::vector< int32 > > *backward_indexes)
static void RearrangeIndexes (const std::vector< std::vector< int32 > > &in, std::vector< std::vector< int32 > > *out)
Private Attributes
int32 patch_dim_
int32 patch_step_
int32 patch_stride_
CuMatrix< BaseFloat > filter_params_
CuVector< BaseFloat > bias_params_
bool is_gradient_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Detailed Description
Convolutional1dComponent implements convolution over frequency axis.
We assume the input featrues are spliced, i.e. each frame is in fact a set of stacked frames, where we can form patches which span over several frequency bands and whole time axis. A patch is the instance of a filter on a group of frequency bands and whole time axis. Shifts of the filter generate patches.
The convolution is done over whole axis with same filter coefficients, i.e. we don't use separate filters for different 'regions' of frequency axis. Due to convolution, same weights are used repeateadly, the final gradient is a sum of all position-specific gradients (the sum was found better than averaging).
In order to have a fast implementations, the filters are represented in vectorized form, where each rectangular filter corresponds to a row in a matrix, where all the filters are stored. The features are then re-shaped to a set of matrices, where one matrix corresponds to single patch-position, where all the filters get applied.
The type of convolution is controled by hyperparameters: patch_dim_ ... frequency axis size of the patch patch_step_ ... size of shift in the convolution patch_stride_ ... shift for 2nd dim of a patch (i.e. frame length before splicing) For instance, for a convolutional component after raw input, if the input is 36-dim fbank feature with delta of order 2 and spliced using +/- 5 frames of contexts, the convolutional component takes the input as a 36 x 33 image. The patch_stride_ should be configured 36. If patch_step_ and patch_dim_ are configured 1 and 7, the Convolutional1dComponent creates a 2D filter of 7 x 33, such that the convolution is actually done only along the frequency axis. Specifically, the convolutional output along the frequency axis is (36 - 7) / 1 + 1 = 30, and the convolutional output along the temporal axis is 33 - 33 + 1 = 1, resulting in an output image of 30 x 1, which is called a feature map in ConvNet. Then if the output-dim is set 3840, the constructor would know there should be 3840 / 30 = 128 distinct filters, which will create 128 feature maps of 30 x 1 for one frame of input. The feature maps are vectorized as a 3840-dim row vector in the output matrix of this component. For details on progatation of Convolutional1dComponent, check the function definition.
Definition at line 1493 of file nnet-simple-component.h.
Constructor & Destructor Documentation
Convolutional1dComponent ()
Definition at line 3555 of file nnet-simple-component.cc.
Referenced by Convolutional1dComponent::Copy().
                                                   :
     UpdatableComponent(),
     patch_dim_(0), patch_step_(0), patch_stride_(0), is_gradient_(false) {}
Convolutional1dComponent (const Convolutional1dComponent & component)
Definition at line 3559 of file nnet-simple-component.cc.
                                                                                            :
     UpdatableComponent(component),
     filter_params_(component.filter_params_),
     bias_params_(component.bias_params_),
     is_gradient_(component.is_gradient_) {}
Convolutional1dComponent (const CuMatrixBase< BaseFloat > & filter_params, const CuVectorBase< BaseFloat > & bias_params, BaseFloat learning_rate)
Definition at line 3565 of file nnet-simple-component.cc.
References CuVectorBase< Real >::Dim(), Convolutional1dComponent::is_gradient_, KALDI_ASSERT, CuMatrixBase< Real >::NumRows(), and UpdatableComponent::SetLearningRate().
                                                                            :
     filter_params_(filter_params),
     bias_params_(bias_params) {
   SetLearningRate(learning_rate);
   KALDI_ASSERT(filter_params.NumRows() == bias_params.Dim() &&
                bias_params.Dim() != 0);
   is_gradient_ = false;
 }
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from Component.
Definition at line 3798 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, and KALDI_ASSERT.
{
   const Convolutional1dComponent *other =
       dynamic_cast<const Convolutional1dComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   filter_params_.AddMat(alpha, other->filter_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Buffer for backpropagation: derivatives in the domain of 'patches_', 1row = vectorized rectangular feature patches, 1col = dim over speech frames,
Implements Component.
Definition at line 3865 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddCols(), CuMatrixBase< Real >::ColRange(), rnnlm::d, Convolutional1dComponent::filter_params_, Convolutional1dComponent::InputDim(), kaldi::kNoTrans, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, Convolutional1dComponent::RearrangeIndexes(), Convolutional1dComponent::ReverseIndexes(), and Convolutional1dComponent::Update().
{
   Convolutional1dComponent *to_update = dynamic_cast<Convolutional1dComponent*>(to_update_in);
   int32 num_splice = InputDim() / patch_stride_;
   int32 num_patches = 1 + (patch_stride_ - patch_dim_) / patch_step_;
   int32 num_filters = filter_params_.NumRows();
   int32 num_frames = out_deriv.NumRows();
   int32 filter_dim = filter_params_.NumCols();
   CuMatrix<BaseFloat> patches_deriv(num_frames, filter_dim * num_patches, kSetZero);
   //
   // backpropagate to vector of matrices
   // (corresponding to position of a filter)
   //
   std::vector<CuSubMatrix<BaseFloat>* > patch_deriv_batch, out_deriv_batch,
           filter_params_batch;
   CuSubMatrix<BaseFloat>* filter_params_elem = new CuSubMatrix<BaseFloat>(
                   filter_params_, 0, filter_params_.NumRows(), 0,
                   filter_params_.NumCols());
   // form batch in vector container
   for (int32 p = 0; p < num_patches; p++) {
     // form batch in vector container. for filter_params_batch, all elements
     // point to the same copy filter_params_elem
     patch_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(patches_deriv.ColRange(
                                     p * filter_dim, filter_dim)));
     out_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(out_deriv.ColRange(
                                     p * num_filters, num_filters)));
     filter_params_batch.push_back(filter_params_elem);
   }
   AddMatMatBatched<BaseFloat>(1.0, patch_deriv_batch, out_deriv_batch, kNoTrans,
                               filter_params_batch, kNoTrans, 0.0);
   // release memory
   delete filter_params_elem;
   for (int32 p = 0; p < num_patches; p++) {
     delete patch_deriv_batch[p];
     delete out_deriv_batch[p];
   }
   // sum the derivatives into in_deriv
   std::vector<int32> column_map(filter_dim * num_patches);
   for (int32 p = 0, index = 0; p < num_patches; p++) {
     for (int32 s = 0; s < num_splice; s++) {
       for (int32 d = 0; d < patch_dim_; d++, index++) {
         column_map[index] = p * patch_step_ + s * patch_stride_ + d;
       }
     }
   }
   if (in_deriv) {
     std::vector<std::vector<int32> > reversed_column_map;
     ReverseIndexes(column_map, InputDim(), &reversed_column_map);
     std::vector<std::vector<int32> > rearranged_column_map;
     RearrangeIndexes(reversed_column_map, &rearranged_column_map);
     for (int32 p = 0; p < rearranged_column_map.size(); p++) {
       CuArray<int32> cu_cols(rearranged_column_map[p]);
       in_deriv->AddCols(patches_deriv, cu_cols);
     }
   }
   if (to_update != NULL) {
     // Next update the model (must do this 2nd so the derivatives we propagate
     // are accurate, in case this == to_update_in.)
     to_update->Update(debug_info, in_value, out_deriv);
   }
 }
const CuVector<BaseFloat>& BiasParams () inline
Definition at line 1543 of file nnet-simple-component.h.
References Convolutional1dComponent::bias_params_.
 { return bias_params_; }
Component * Copy () const virtual
Copies component (deep copy).
Implements Component.
Definition at line 4002 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::Convolutional1dComponent(), Convolutional1dComponent::filter_params_, Convolutional1dComponent::is_gradient_, UpdatableComponent::learning_rate_, Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, and Convolutional1dComponent::patch_stride_.
{
   Convolutional1dComponent *ans = new Convolutional1dComponent();
   ans->learning_rate_ = learning_rate_;
   ans->patch_dim_ = patch_dim_;
   ans->patch_step_ = patch_step_;
   ans->patch_stride_ = patch_stride_;
   ans->filter_params_ = filter_params_;
   ans->bias_params_ = bias_params_;
   ans->is_gradient_ = is_gradient_;
   return ans;
 }
BaseFloat DotProduct (const UpdatableComponent & other) const virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implements UpdatableComponent.
Definition at line 3995 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, kaldi::kTrans, kaldi::TraceMatMat(), and kaldi::VecVec().
{
   const Convolutional1dComponent *other =
       dynamic_cast<const Convolutional1dComponent*>(&other_in);
   return TraceMatMat(filter_params_, other->filter_params_, kTrans)
          + VecVec(bias_params_, other->bias_params_);
 }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from UpdatableComponent.
Definition at line 3646 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, UpdatableComponent::Info(), Convolutional1dComponent::InputDim(), Convolutional1dComponent::OutputDim(), Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, and kaldi::nnet3::PrintParameterStats().
{
   std::ostringstream stream;
   int32 num_splice = InputDim() / patch_stride_;
   int32 filter_dim = num_splice * patch_dim_;
   int32 num_patches = 1 + (patch_stride_ - patch_dim_) / patch_step_;
   int32 num_filters = OutputDim() / num_patches;
   stream << UpdatableComponent::Info()
          << ", num-splice=" << num_splice
          << ", num-patches=" << num_patches
          << ", num-filters=" << num_filters
          << ", filter-dim=" << filter_dim;
   PrintParameterStats(stream, "filter-params", filter_params_);
   PrintParameterStats(stream, "bias-params", bias_params_, true);
   return stream.str();
 }
void Init (int32 input_dim, int32 output_dim, int32 patch_dim, int32 patch_step, int32 patch_stride, BaseFloat param_stddev, BaseFloat bias_stddev)
Definition at line 3591 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, KALDI_ASSERT, Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
Referenced by Convolutional1dComponent::InitFromConfig().
{
   patch_dim_ = patch_dim;
   patch_step_ = patch_step;
   patch_stride_ = patch_stride;
   int32 num_splice = input_dim / patch_stride;
   int32 filter_dim = num_splice * patch_dim;
   int32 num_patches = 1 + (patch_stride - patch_dim) / patch_step;
   int32 num_filters = output_dim / num_patches;
   KALDI_ASSERT(input_dim % patch_stride == 0);
   KALDI_ASSERT((patch_stride - patch_dim) % patch_step == 0);
   KALDI_ASSERT(output_dim % num_patches == 0);
   filter_params_.Resize(num_filters, filter_dim);
   bias_params_.Resize(num_filters);
   KALDI_ASSERT(param_stddev >= 0.0 && bias_stddev >= 0.0);
   filter_params_.SetRandn();
   filter_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
 }
void Init (int32 patch_dim, int32 patch_step, int32 patch_stride, std::string matrix_filename)
Definition at line 3615 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyFromMat(), Convolutional1dComponent::filter_params_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, CuMatrixBase< Real >::Range(), kaldi::ReadKaldiObject(), CuVector< Real >::Resize(), and CuMatrix< Real >::Resize().
{
   patch_dim_ = patch_dim;
   patch_step_ = patch_step;
   patch_stride_ = patch_stride;
   CuMatrix<BaseFloat> mat;
   ReadKaldiObject(matrix_filename, &mat);
   KALDI_ASSERT(mat.NumCols() >= 2);
   int32 filter_dim = mat.NumCols() - 1, num_filters = mat.NumRows();
   filter_params_.Resize(num_filters, filter_dim);
   bias_params_.Resize(num_filters);
   filter_params_.CopyFromMat(mat.Range(0, num_filters, 0, filter_dim));
   bias_params_.CopyColFromMat(mat, filter_dim);
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Implements Component.
Definition at line 3664 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), Convolutional1dComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), Convolutional1dComponent::InputDim(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, Convolutional1dComponent::OutputDim(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   KALDI_WARN << "Convolutional1dComponent has been deprecated."
              << " Please use ConvolutionComponent.";
   bool ok = true;
   std::string matrix_filename;
   int32 input_dim = -1, output_dim = -1;
   int32 patch_dim = -1, patch_step = -1, patch_stride = -1;
   InitLearningRatesFromConfig(cfl);
   ok = ok && cfl->GetValue("patch-dim", &patch_dim);
   ok = ok && cfl->GetValue("patch-step", &patch_step);
   ok = ok && cfl->GetValue("patch-stride", &patch_stride);
   if (cfl->GetValue("matrix", &matrix_filename)) {
     // initialize from prefined parameter matrix
     Init(patch_dim, patch_step, patch_stride, matrix_filename);
     if (cfl->GetValue("input-dim", &input_dim))
       KALDI_ASSERT(input_dim == InputDim() &&
                "input-dim mismatch vs. matrix.");
     if (cfl->GetValue("output-dim", &output_dim))
       KALDI_ASSERT(output_dim == OutputDim() &&
                "output-dim mismatch vs. matrix.");
   } else {
     ok = ok && cfl->GetValue("input-dim", &input_dim);
     ok = ok && cfl->GetValue("output-dim", &output_dim);
     // initialize from configuration
     BaseFloat param_stddev = 1.0 / std::sqrt(input_dim), bias_stddev = 1.0;
     cfl->GetValue("param-stddev", &param_stddev);
     cfl->GetValue("bias-stddev", &bias_stddev);
     Init(input_dim, output_dim, patch_dim, patch_step, patch_stride,
          param_stddev, bias_stddev);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
int32 InputDim () const virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 3577 of file nnet-simple-component.cc.
References Convolutional1dComponent::filter_params_, CuMatrixBase< Real >::NumCols(), Convolutional1dComponent::patch_dim_, and Convolutional1dComponent::patch_stride_.
Referenced by Convolutional1dComponent::Backprop(), Convolutional1dComponent::Info(), Convolutional1dComponent::InitFromConfig(), Convolutional1dComponent::Propagate(), and Convolutional1dComponent::Update().
{
   int32 filter_dim = filter_params_.NumCols();
   int32 num_splice = filter_dim / patch_dim_;
   return patch_stride_ * num_splice;
 }
const CuMatrix<BaseFloat>& LinearParams () inline
Definition at line 1544 of file nnet-simple-component.h.
References Convolutional1dComponent::filter_params_.
 { return filter_params_; }
int32 NumParameters () const virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented from UpdatableComponent.
Definition at line 4031 of file nnet-simple-component.cc.
References Convolutional1dComponent::filter_params_, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
Referenced by Convolutional1dComponent::UnVectorize(), and Convolutional1dComponent::Vectorize().
{
   return (filter_params_.NumCols() + 1) * filter_params_.NumRows();
 }
const Convolutional1dComponent& operator= (const Convolutional1dComponent & other) private
int32 OutputDim () const virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 3584 of file nnet-simple-component.cc.
References Convolutional1dComponent::filter_params_, CuMatrixBase< Real >::NumRows(), Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, and Convolutional1dComponent::patch_stride_.
Referenced by Convolutional1dComponent::Info(), and Convolutional1dComponent::InitFromConfig().
{
   int32 num_filters = filter_params_.NumRows();
   int32 num_patches = 1 + (patch_stride_ - patch_dim_) / patch_step_;
   return num_patches * num_filters;
 }
void PerturbParams (BaseFloat stddev) virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implements UpdatableComponent.
Definition at line 4014 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, CuVectorBase< Real >::SetRandn(), and CuMatrixBase< Real >::SetRandn().
{
   CuMatrix<BaseFloat> temp_filter_params(filter_params_);
   temp_filter_params.SetRandn();
   filter_params_.AddMat(stddev, temp_filter_params);
   CuVector<BaseFloat> temp_bias_params(bias_params_);
   temp_bias_params.SetRandn();
   bias_params_.AddVec(stddev, temp_bias_params);
 }
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Buffer of reshaped inputs: 1row = vectorized rectangular feature patches 1col = dim over speech frames,
Implements Component.
Definition at line 3726 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddVecToRows(), Convolutional1dComponent::bias_params_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyCols(), rnnlm::d, Convolutional1dComponent::filter_params_, Convolutional1dComponent::InputDim(), kaldi::kNoTrans, kaldi::kTrans, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, and Convolutional1dComponent::patch_stride_.
{
   // dims
   int32 num_splice = InputDim() / patch_stride_;
   int32 num_patches = 1 + (patch_stride_ - patch_dim_) / patch_step_;
   int32 num_filters = filter_params_.NumRows();
   int32 num_frames = in.NumRows();
   int32 filter_dim = filter_params_.NumCols();
   CuMatrix<BaseFloat> patches(num_frames, filter_dim * num_patches, kUndefined);
   // column_map is indexed by the column-index of "patches",
   // and the value is the corresponding column-index of "in".
   std::vector<int32> column_map(filter_dim * num_patches);
   // build-up a column selection map
   for (int32 p = 0, index = 0; p < num_patches; p++) {
     for (int32 s = 0; s < num_splice; s++) {
         for (int32 d = 0; d < patch_dim_; d++, index++) {
         column_map[index] = p * patch_step_ + s * patch_stride_ + d;
       }
     }
   }
   CuArray<int32> cu_cols(column_map);
   patches.CopyCols(in, cu_cols);
   //
   // compute filter activations
   //
   std::vector<CuSubMatrix<BaseFloat>* > tgt_batch, patch_batch, filter_params_batch;
   CuSubMatrix<BaseFloat>* filter_params_elem = new CuSubMatrix<BaseFloat>(
                   filter_params_, 0, filter_params_.NumRows(), 0,
                   filter_params_.NumCols());
   // form batch in vector container
   for (int32 p = 0; p < num_patches; p++) {
     // form batch in vector container. for filter_params_batch, all elements
     // point to the same copy filter_params_elem
     tgt_batch.push_back(new CuSubMatrix<BaseFloat>(out->ColRange(p * num_filters,
                                     num_filters)));
     patch_batch.push_back(new CuSubMatrix<BaseFloat>(patches.ColRange(p * filter_dim,
                                     filter_dim)));
     filter_params_batch.push_back(filter_params_elem);
     tgt_batch[p]->AddVecToRows(1.0, bias_params_, 1.0); // add bias
   }
   // apply all filters
   AddMatMatBatched<BaseFloat>(1.0, tgt_batch, patch_batch, kNoTrans,
                               filter_params_batch, kTrans, 1.0);
   // release memory
   delete filter_params_elem;
   for (int32 p = 0; p < num_patches; p++) {
     delete tgt_batch[p];
     delete patch_batch[p];
   }
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 1509 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropAdds, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateAdds, kaldi::nnet3::kSimpleComponent, and kaldi::nnet3::kUpdatableComponent.
{
     return kSimpleComponent|kUpdatableComponent|kBackpropNeedsInput|
             kBackpropAdds|kPropagateAdds;
   }
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Implements Component.
Definition at line 3955 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, kaldi::nnet3::ExpectToken(), Convolutional1dComponent::filter_params_, Convolutional1dComponent::is_gradient_, KALDI_ASSERT, Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), and UpdatableComponent::ReadUpdatableCommon().
{
   ReadUpdatableCommon(is, binary);  // Read opening tag and learning rate.
   ExpectToken(is, binary, "<PatchDim>");
   ReadBasicType(is, binary, &patch_dim_);
   ExpectToken(is, binary, "<PatchStep>");
   ReadBasicType(is, binary, &patch_step_);
   ExpectToken(is, binary, "<PatchStride>");
   ReadBasicType(is, binary, &patch_stride_);
   ExpectToken(is, binary, "<FilterParams>");
   filter_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   std::string tok;
   ReadToken(is, binary, &tok);
   if (tok == "<IsGradient>") {
     ReadBasicType(is, binary, &is_gradient_);
     ExpectToken(is, binary, "</Convolutional1dComponent>");
   } else {
     is_gradient_ = false;
     KALDI_ASSERT(tok == "</Convolutional1dComponent>");
   }
 }
void RearrangeIndexes (const std::vector< std::vector< int32 > > & in, std::vector< std::vector< int32 > > * out) static private
Definition at line 3846 of file nnet-simple-component.cc.
References rnnlm::i, and rnnlm::j.
Referenced by Convolutional1dComponent::Backprop().
{
   int32 D = in.size();
   int32 L = 0;
   for (int32 i = 0; i < D; i++)
     if (in[i].size() > L)
       L = in[i].size();
   out->resize(L);
   for (int32 i = 0; i < L; i++)
     (*out)[i].resize(D, -1);
   for (int32 i = 0; i < D; i++) {
     for (int32 j = 0; j < in[i].size(); j++) {
       (*out)[j][i] = in[i][j];
     }
   }
 }
void Resize (int32 input_dim, int32 output_dim)
Definition at line 3632 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, KALDI_ASSERT, Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, CuVector< Real >::Resize(), and CuMatrix< Real >::Resize().
{
   KALDI_ASSERT(input_dim > 0 && output_dim > 0);
   int32 num_splice = input_dim / patch_stride_;
   int32 filter_dim = num_splice * patch_dim_;
   int32 num_patches = 1 + (patch_stride_ - patch_dim_) / patch_step_;
   int32 num_filters = output_dim / num_patches;
   KALDI_ASSERT(input_dim % patch_stride_ == 0);
   KALDI_ASSERT((patch_stride_ - patch_dim_) % patch_step_ == 0);
   KALDI_ASSERT(output_dim % num_patches == 0);
   filter_params_.Resize(num_filters, filter_dim);
   bias_params_.Resize(num_filters);
 }
void ReverseIndexes (const std::vector< int32 > & forward_indexes, int32 input_dim, std::vector< std::vector< int32 > > * backward_indexes) static private
Definition at line 3818 of file nnet-simple-component.cc.
References rnnlm::i, rnnlm::j, and KALDI_ASSERT.
Referenced by Convolutional1dComponent::Backprop().
{
   int32 i, size = forward_indexes.size();
   int32 reserve_size = 2 + size / input_dim;
   backward_indexes->resize(input_dim);
   std::vector<std::vector<int32> >::iterator iter = backward_indexes->begin(),
     end = backward_indexes->end();
   for (; iter != end; ++iter)
     iter->reserve(reserve_size);
   for (int32 j = 0; j < forward_indexes.size(); j++) {
     i = forward_indexes[j];
     KALDI_ASSERT(i < input_dim);
     (*backward_indexes)[i].push_back(j);
   }
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from Component.
Definition at line 3792 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, CuVectorBase< Real >::Scale(), and CuMatrixBase< Real >::Scale().
{
   filter_params_.Scale(scale);
   bias_params_.Scale(scale);
 }
void SetParams (const VectorBase< BaseFloat > & bias, const MatrixBase< BaseFloat > & filter)
Definition at line 4024 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, CuVectorBase< Real >::Dim(), Convolutional1dComponent::filter_params_, KALDI_ASSERT, and CuMatrixBase< Real >::NumRows().
{
   bias_params_ = bias;
   filter_params_ = filter;
   KALDI_ASSERT(bias_params_.Dim() == filter_params_.NumRows());
 }
void SetZero (bool treat_as_gradient) virtual
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
Implements UpdatableComponent.
Definition at line 3945 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, Convolutional1dComponent::is_gradient_, UpdatableComponent::learning_rate_, CuVectorBase< Real >::SetZero(), and CuMatrixBase< Real >::SetZero().
{
   if (treat_as_gradient) {
     learning_rate_ = 1.0;  // don't call SetLearningRate, that would apply the
                            // learning rate factor.
     is_gradient_ = true;
   }
   filter_params_.SetZero();
   bias_params_.SetZero();
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 1508 of file nnet-simple-component.h.
 { return "Convolutional1dComponent"; }
void UnVectorize (const VectorBase< BaseFloat > & params) virtual
Converts the parameters from vector form.
Reimplemented from UpdatableComponent.
Definition at line 4127 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, CuVectorBase< Real >::CopyFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), VectorBase< Real >::Dim(), CuVectorBase< Real >::Dim(), Convolutional1dComponent::filter_params_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), Convolutional1dComponent::NumParameters(), CuMatrixBase< Real >::NumRows(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params.Dim() == this->NumParameters());
   int32 num_filter_params = filter_params_.NumCols() * filter_params_.NumRows();
   filter_params_.CopyRowsFromVec(params.Range(0, num_filter_params));
   bias_params_.CopyFromVec(params.Range(num_filter_params, bias_params_.Dim()));
 }
void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv)
Buffer of reshaped inputs: 1row = vectorized rectangular feature patches 1col = dim over speech frames,
Definition at line 4036 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuMatrixBase< Real >::AddMatBlocks(), CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), Convolutional1dComponent::bias_params_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyCols(), rnnlm::d, Convolutional1dComponent::filter_params_, Convolutional1dComponent::InputDim(), kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, kaldi::kUndefined, UpdatableComponent::learning_rate_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, CuVector< Real >::Resize(), and CuMatrix< Real >::Resize().
Referenced by Convolutional1dComponent::Backprop().
{
   // useful dims
   int32 num_patches = 1 + (patch_stride_ - patch_dim_) / patch_step_;
   int32 num_filters = filter_params_.NumRows();
   int32 filter_dim = filter_params_.NumCols();
   int32 num_frames = in_value.NumRows();
   int32 num_splice = InputDim() / patch_stride_;
   CuMatrix<BaseFloat> filters_grad;
   CuVector<BaseFloat> bias_grad;
   CuMatrix<BaseFloat> patches(num_frames, filter_dim * num_patches, kUndefined);
   std::vector<int32> column_map(filter_dim * num_patches);
   for (int32 p = 0, index = 0; p < num_patches; p++) {
     for (int32 s = 0; s < num_splice; s++) {
       for (int32 d = 0; d < patch_dim_; d++, index++) {
         column_map[index] = p * patch_step_ + s * patch_stride_ + d;
       }
     }
   }
   CuArray<int32> cu_cols(column_map);
   patches.CopyCols(in_value, cu_cols);
   //
   // calculate the gradient
   //
   filters_grad.Resize(num_filters, filter_dim, kSetZero); // reset
   bias_grad.Resize(num_filters, kSetZero); // reset
   //
   // use all the patches
   //
   // create a single large matrix holding the smaller matrices
   // from the vector container filters_grad_batch along the rows
   CuMatrix<BaseFloat> filters_grad_blocks_batch(
                   num_patches * filters_grad.NumRows(), filters_grad.NumCols());
   std::vector<CuSubMatrix<BaseFloat>* > filters_grad_batch, diff_patch_batch,
           patch_batch;
   for (int32 p = 0; p < num_patches; p++) {
     // form batch in vector container
     filters_grad_batch.push_back(new CuSubMatrix<BaseFloat>(
                             filters_grad_blocks_batch.RowRange(
                                     p * filters_grad.NumRows(),
                                     filters_grad.NumRows())));
     diff_patch_batch.push_back(new CuSubMatrix<BaseFloat>(out_deriv.ColRange(
                                     p * num_filters, num_filters)));
     patch_batch.push_back(new CuSubMatrix<BaseFloat>(patches.ColRange(
                                     p * filter_dim, filter_dim)));
   }
   AddMatMatBatched<BaseFloat>(1.0, filters_grad_batch, diff_patch_batch, kTrans, patch_batch,
                               kNoTrans, 1.0);
   // add the row blocks together to filters_grad
   filters_grad.AddMatBlocks(1.0, filters_grad_blocks_batch);
   // create a matrix holding the col blocks sum of out_deriv
   CuMatrix<BaseFloat> out_deriv_col_blocks_sum(out_deriv.NumRows(), num_filters);
   // add the col blocks together to out_deriv_col_blocks_sum
   out_deriv_col_blocks_sum.AddMatBlocks(1.0, out_deriv);
   bias_grad.AddRowSumMat(1.0, out_deriv_col_blocks_sum, 1.0);
   // release memory
   for (int32 p = 0; p < num_patches; p++) {
     delete filters_grad_batch[p];
     delete diff_patch_batch[p];
     delete patch_batch[p];
   }
   //
   // update
   //
   filter_params_.AddMat(learning_rate_, filters_grad);
   bias_params_.AddVec(learning_rate_, bias_grad);
 }
void Vectorize (VectorBase< BaseFloat > * params) const virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented from UpdatableComponent.
Definition at line 4121 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, VectorBase< Real >::Dim(), CuVectorBase< Real >::Dim(), Convolutional1dComponent::filter_params_, KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), Convolutional1dComponent::NumParameters(), CuMatrixBase< Real >::NumRows(), and VectorBase< Real >::Range().
{
   KALDI_ASSERT(params->Dim() == this->NumParameters());
   int32 num_filter_params = filter_params_.NumCols() * filter_params_.NumRows();
   params->Range(0, num_filter_params).CopyRowsFromMat(filter_params_);
   params->Range(num_filter_params, bias_params_.Dim()).CopyFromVec(bias_params_);
 }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3978 of file nnet-simple-component.cc.
References Convolutional1dComponent::bias_params_, Convolutional1dComponent::filter_params_, Convolutional1dComponent::is_gradient_, Convolutional1dComponent::patch_dim_, Convolutional1dComponent::patch_step_, Convolutional1dComponent::patch_stride_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write opening tag and learning rate
   WriteToken(os, binary, "<PatchDim>");
   WriteBasicType(os, binary, patch_dim_);
   WriteToken(os, binary, "<PatchStep>");
   WriteBasicType(os, binary, patch_step_);
   WriteToken(os, binary, "<PatchStride>");
   WriteBasicType(os, binary, patch_stride_);
   WriteToken(os, binary, "<FilterParams>");
   filter_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   WriteToken(os, binary, "</Convolutional1dComponent>");
 }
Member Data Documentation
CuVector<BaseFloat> bias_params_ private
Definition at line 1572 of file nnet-simple-component.h.
Referenced by Convolutional1dComponent::Add(), Convolutional1dComponent::BiasParams(), Convolutional1dComponent::Copy(), Convolutional1dComponent::DotProduct(), Convolutional1dComponent::Info(), Convolutional1dComponent::Init(), Convolutional1dComponent::PerturbParams(), Convolutional1dComponent::Propagate(), Convolutional1dComponent::Read(), Convolutional1dComponent::Resize(), Convolutional1dComponent::Scale(), Convolutional1dComponent::SetParams(), Convolutional1dComponent::SetZero(), Convolutional1dComponent::UnVectorize(), Convolutional1dComponent::Update(), Convolutional1dComponent::Vectorize(), and Convolutional1dComponent::Write().
CuMatrix<BaseFloat> filter_params_ private
Definition at line 1571 of file nnet-simple-component.h.
Referenced by Convolutional1dComponent::Add(), Convolutional1dComponent::Backprop(), Convolutional1dComponent::Copy(), Convolutional1dComponent::DotProduct(), Convolutional1dComponent::Info(), Convolutional1dComponent::Init(), Convolutional1dComponent::InputDim(), Convolutional1dComponent::LinearParams(), Convolutional1dComponent::NumParameters(), Convolutional1dComponent::OutputDim(), Convolutional1dComponent::PerturbParams(), Convolutional1dComponent::Propagate(), Convolutional1dComponent::Read(), Convolutional1dComponent::Resize(), Convolutional1dComponent::Scale(), Convolutional1dComponent::SetParams(), Convolutional1dComponent::SetZero(), Convolutional1dComponent::UnVectorize(), Convolutional1dComponent::Update(), Convolutional1dComponent::Vectorize(), and Convolutional1dComponent::Write().
bool is_gradient_ private
Definition at line 1573 of file nnet-simple-component.h.
Referenced by Convolutional1dComponent::Convolutional1dComponent(), Convolutional1dComponent::Copy(), Convolutional1dComponent::Read(), Convolutional1dComponent::SetZero(), and Convolutional1dComponent::Write().
int32 patch_dim_ private
Definition at line 1560 of file nnet-simple-component.h.
Referenced by Convolutional1dComponent::Backprop(), Convolutional1dComponent::Copy(), Convolutional1dComponent::Info(), Convolutional1dComponent::Init(), Convolutional1dComponent::InputDim(), Convolutional1dComponent::OutputDim(), Convolutional1dComponent::Propagate(), Convolutional1dComponent::Read(), Convolutional1dComponent::Resize(), Convolutional1dComponent::Update(), and Convolutional1dComponent::Write().
int32 patch_step_ private
Definition at line 1561 of file nnet-simple-component.h.
Referenced by Convolutional1dComponent::Backprop(), Convolutional1dComponent::Copy(), Convolutional1dComponent::Info(), Convolutional1dComponent::Init(), Convolutional1dComponent::OutputDim(), Convolutional1dComponent::Propagate(), Convolutional1dComponent::Read(), Convolutional1dComponent::Resize(), Convolutional1dComponent::Update(), and Convolutional1dComponent::Write().
int32 patch_stride_ private
Definition at line 1562 of file nnet-simple-component.h.
Referenced by Convolutional1dComponent::Backprop(), Convolutional1dComponent::Copy(), Convolutional1dComponent::Info(), Convolutional1dComponent::Init(), Convolutional1dComponent::InputDim(), Convolutional1dComponent::OutputDim(), Convolutional1dComponent::Propagate(), Convolutional1dComponent::Read(), Convolutional1dComponent::Resize(), Convolutional1dComponent::Update(), and Convolutional1dComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc