Kaldi: ComputationAnalysis Class Reference
ComputationAnalysis Class Reference
This class performs various kinds of specific analysis on top of what class Analyzer gives you immediately.
#include <nnet-analyze.h>
Public Member Functions
ComputationAnalysis (const NnetComputation &computation, const Analyzer &analyzer)
This class stores the const references provided to its constructor -> be careful about changing them or deallocating them during the lifetime of this object.
int32 FirstAccess (int32 s) const
If the matrix underlying submatrix 's' is an input then this returns -1; otherwise it returns the first command (read or write) that is not an allocation command, that accesses any part of 's' [note: deallocation does not count as a read or write operation].
int32 LastAccess (int32 s) const
If the matrix underlying submatrix 's' is an output then this returns num-commands; otherwise it returns the last non-deallocation command that accesses any part of submatrix 's'; if there is no such command it returns -1.
int32 LastWriteAccess (int32 s) const
Returns the last command-index that accesses any part of submatrix 's' as a write operation, or -1 if there is no such operation.
int32 DataInvalidatedCommand (int32 c, int32 s) const
Returns (the first command-index after 'c' that any part of submatrix 's' is written to); or if there is no such command, then (the command-index of the command that deallocates the matrix underlying s); or if there is no such command, then the total number of commands.
int32 FirstMatrixAccess (int32 m) const
If matrix 'm' is an input then this returns -1; otherwise it returns the first command (read or write) that is not an allocation command, that accesses any part of 'm' [note: deallocation does not count as a read or write operation].
int32 LastMatrixAccess (int32 m) const
If matrix 'm' is an output then this returns num-commands; otherwise it returns the last non-deallocation command that accesses any part of matrix 'm'; if there is no such command it returns -1.
Private Attributes
const NnetComputation & computation_
const Analyzer & analyzer_
Detailed Description
This class performs various kinds of specific analysis on top of what class Analyzer gives you immediately.
It mostly contains special-purpose things what were needed by class VariableMergingOptimizer (see nnet-optimize.h, and the extended comment above class VariableMergingOptimizer). Be careful about the meaninhg of 'access'- read the comments carefully.
Definition at line 305 of file nnet-analyze.h.
Constructor & Destructor Documentation
ComputationAnalysis (const NnetComputation & computation, const Analyzer & analyzer) inline
This class stores the const references provided to its constructor -> be careful about changing them or deallocating them during the lifetime of this object.
Definition at line 310 of file nnet-analyze.h.
                                                : computation_(computation),
                                                  analyzer_(analyzer) { }
Member Function Documentation
int32 DataInvalidatedCommand (int32 c, int32 s) const
Returns (the first command-index after 'c' that any part of submatrix 's' is written to); or if there is no such command, then (the command-index of the command that deallocates the matrix underlying s); or if there is no such command, then the total number of commands.
s must be >0 (i.e. not the empty submatrix).
Definition at line 1135 of file nnet-analyze.cc.
References ComputationAnalysis::analyzer_, ComputationVariables::AppendVariablesForSubmatrix(), NnetComputation::commands, ComputationAnalysis::computation_, KALDI_ASSERT, kaldi::nnet3::kReadAccess, Analyzer::matrix_accesses, NnetComputation::submatrices, Analyzer::variable_accesses, and Analyzer::variables.
Referenced by VariableMergingOptimizer::MayBeMerged(), and kaldi::nnet3::UnitTestNnetAnalyze().
{
   KALDI_ASSERT(static_cast<size_t>(c) < computation_.commands.size());
   KALDI_ASSERT(static_cast<size_t>(s) < computation_.submatrices.size() && s>0);
   int32 matrix_index = computation_.submatrices[s].matrix_index;
   int32 ans = analyzer_.matrix_accesses[matrix_index].deallocate_command;
   if (ans == -1)
     ans = static_cast<int32>(computation_.commands.size());
   std::vector<int32> variable_indexes;
   analyzer_.variables.AppendVariablesForSubmatrix(s, &variable_indexes);
   std::vector<int32>::const_iterator iter = variable_indexes.begin(),
           end = variable_indexes.end();
   for (; iter != end; ++iter) {
     int32 v = *iter;
     const std::vector<Access> &accesses = analyzer_.variable_accesses[v];
     std::vector<Access>::const_iterator access_iter = accesses.begin(),
         access_end = accesses.end();
     for (; access_iter != access_end; ++access_iter) {
       int32 command_index = access_iter->command_index;
       if (command_index > c &&
           access_iter->access_type != kReadAccess) {
         ans = std::min(ans, command_index);
       }
     }
   }
   return ans;
 }
int32 FirstAccess (int32 s) const
If the matrix underlying submatrix 's' is an input then this returns -1; otherwise it returns the first command (read or write) that is not an allocation command, that accesses any part of 's' [note: deallocation does not count as a read or write operation].
If there is no such command, it returns num_commands. s must be >0 (i.e. not the empty submatrix).
Definition at line 1001 of file nnet-analyze.cc.
References ComputationAnalysis::analyzer_, ComputationVariables::AppendVariablesForSubmatrix(), NnetComputation::commands, ComputationAnalysis::computation_, KALDI_ASSERT, kaldi::nnet3::kAllocMatrixFromOther, kaldi::nnet3::kAllocMatrixFromOtherZeroed, kaldi::nnet3::kAllocMatrixUndefined, kaldi::nnet3::kAllocMatrixZeroed, Analyzer::matrix_accesses, NnetComputation::submatrices, Analyzer::variable_accesses, and Analyzer::variables.
Referenced by kaldi::nnet3::ConvertAdditionToAssignment(), VariableMergingOptimizer::MayBeMerged(), and kaldi::nnet3::UnitTestNnetAnalyze().
{
   KALDI_ASSERT(static_cast<size_t>(s) < computation_.submatrices.size() && s>0);
   int32 matrix_index = computation_.submatrices[s].matrix_index;
   if (analyzer_.matrix_accesses[matrix_index].is_input)
     return -1;
   int32 ans = computation_.commands.size();
   std::vector<int32> variable_indexes;
   analyzer_.variables.AppendVariablesForSubmatrix(s, &variable_indexes);
   std::vector<int32>::const_iterator iter = variable_indexes.begin(),
           end = variable_indexes.end();
   for (; iter != end; ++iter) {
     int32 v = *iter;
     const std::vector<Access> &accesses = analyzer_.variable_accesses[v];
     std::vector<Access>::const_iterator access_iter = accesses.begin(),
         access_end = accesses.end();
     for (; access_iter != access_end; ++access_iter) {
       int32 command_index = access_iter->command_index;
       CommandType command_type =
           computation_.commands[command_index].command_type;
       // The following two command types are not considered writes or reads,
       // so they should not even appear in this list.
       KALDI_ASSERT(command_type != kAllocMatrixUndefined &&
                    command_type != kAllocMatrixFromOther);
       if (command_type != kAllocMatrixZeroed &&
           command_type != kAllocMatrixFromOtherZeroed) {
         ans = std::min(ans, command_index);
         break;  // break from access_iter loop (an optimization)
       }
     }
   }
   return ans;
 }
int32 FirstMatrixAccess (int32 m) const
If matrix 'm' is an input then this returns -1; otherwise it returns the first command (read or write) that is not an allocation command, that accesses any part of 'm' [note: deallocation does not count as a read or write operation].
If there is no such command, it returns num_commands. m must be >0 (i.e. not the empty matrix).
Definition at line 1035 of file nnet-analyze.cc.
References ComputationAnalysis::analyzer_, NnetComputation::commands, ComputationAnalysis::computation_, KALDI_ASSERT, NnetComputation::matrices, and Analyzer::matrix_accesses.
Referenced by VariableMergingOptimizer::DoMergeCommon().
{
   KALDI_ASSERT(static_cast<size_t>(m) < computation_.matrices.size() && m > 0);
   if (analyzer_.matrix_accesses[m].is_input)
     return -1;
   int32 ans = computation_.commands.size();
   const std::vector<Access> &accesses =
       analyzer_.matrix_accesses[m].accesses;
   std::vector<Access>::const_iterator access_iter = accesses.begin(),
       access_end = accesses.end();
   for (; access_iter != access_end; ++access_iter) {
     int32 command_index = access_iter->command_index;
     if (command_index != analyzer_.matrix_accesses[m].allocate_command) {
       ans = std::min(ans, command_index);
       break;  // break from access_iter loop (an optimization)
     }
   }
   return ans;
 }
int32 LastAccess (int32 s) const
If the matrix underlying submatrix 's' is an output then this returns num-commands; otherwise it returns the last non-deallocation command that accesses any part of submatrix 's'; if there is no such command it returns -1.
s must be >0 (i.e. not the empty submatrix).
Definition at line 1073 of file nnet-analyze.cc.
References ComputationAnalysis::analyzer_, ComputationVariables::AppendVariablesForSubmatrix(), NnetComputation::commands, ComputationAnalysis::computation_, KALDI_ASSERT, kaldi::nnet3::kDeallocMatrix, Analyzer::matrix_accesses, NnetComputation::submatrices, Analyzer::variable_accesses, and Analyzer::variables.
Referenced by VariableMergingOptimizer::MayBeMerged(), and kaldi::nnet3::UnitTestNnetAnalyze().
{
   KALDI_ASSERT(static_cast<size_t>(s) < computation_.submatrices.size() && s>0);
   int32 matrix_index = computation_.submatrices[s].matrix_index;
   if (analyzer_.matrix_accesses[matrix_index].is_output)
     return computation_.commands.size();
   int32 ans = -1;
   std::vector<int32> variable_indexes;
   analyzer_.variables.AppendVariablesForSubmatrix(s, &variable_indexes);
   std::vector<int32>::const_iterator iter = variable_indexes.begin(),
       end = variable_indexes.end();
   for (; iter != end; ++iter) {
     int32 v = *iter;
     const std::vector<Access> &accesses = analyzer_.variable_accesses[v];
     // Go through the variable accesses in reverse order (of command index)
     std::vector<Access>::const_reverse_iterator access_iter = accesses.rbegin(),
         access_end = accesses.rend();
     for (; access_iter != access_end; ++access_iter) {
       int32 command_index = access_iter->command_index;
       CommandType command_type =
           computation_.commands[command_index].command_type;
       // deallocation command should not be listed here.
       KALDI_ASSERT(command_type != kDeallocMatrix);
       ans = std::max(ans, command_index);
       break;  // break from access_iter loop (an optimization)
     }
   }
   return ans;
 }
int32 LastMatrixAccess (int32 m) const
If matrix 'm' is an output then this returns num-commands; otherwise it returns the last non-deallocation command that accesses any part of matrix 'm'; if there is no such command it returns -1.
m must be >0 (i.e. not the empty matrix).
Definition at line 1055 of file nnet-analyze.cc.
References ComputationAnalysis::analyzer_, NnetComputation::commands, ComputationAnalysis::computation_, KALDI_ASSERT, NnetComputation::matrices, and Analyzer::matrix_accesses.
Referenced by VariableMergingOptimizer::DoMergeCommon().
{
   KALDI_ASSERT(static_cast<size_t>(m) < computation_.matrices.size() && m > 0);
   if (analyzer_.matrix_accesses[m].is_output)
     return computation_.commands.size();
   int32 ans = -1;
   const std::vector<Access> &accesses =
       analyzer_.matrix_accesses[m].accesses;
   std::vector<Access>::const_reverse_iterator access_iter = accesses.rbegin(),
       access_end = accesses.rend();
   for (; access_iter != access_end; ++access_iter) {
     int32 command_index = access_iter->command_index;
     ans = std::max(ans, command_index);
     break;  // break from access_iter loop (an optimization)
   }
   return ans;
 }
int32 LastWriteAccess (int32 s) const
Returns the last command-index that accesses any part of submatrix 's' as a write operation, or -1 if there is no such operation.
Not: deallocation does not count as a write operation. s must be >0 (i.e. not the empty submatrix).
Definition at line 1103 of file nnet-analyze.cc.
References ComputationAnalysis::analyzer_, ComputationVariables::AppendVariablesForSubmatrix(), NnetComputation::commands, ComputationAnalysis::computation_, KALDI_ASSERT, kaldi::nnet3::kDeallocMatrix, kaldi::nnet3::kReadAccess, Analyzer::matrix_accesses, NnetComputation::submatrices, Analyzer::variable_accesses, and Analyzer::variables.
Referenced by VariableMergingOptimizer::MayBeMerged(), and kaldi::nnet3::UnitTestNnetAnalyze().
{
   KALDI_ASSERT(static_cast<size_t>(s) < computation_.submatrices.size() && s>0);
   int32 matrix_index = computation_.submatrices[s].matrix_index;
   if (analyzer_.matrix_accesses[matrix_index].is_output)
     return computation_.commands.size();
   int32 ans = -1;
   std::vector<int32> variable_indexes;
   analyzer_.variables.AppendVariablesForSubmatrix(s, &variable_indexes);
   std::vector<int32>::const_iterator iter = variable_indexes.begin(),
       end = variable_indexes.end();
   for (; iter != end; ++iter) {
     int32 v = *iter;
     const std::vector<Access> &accesses = analyzer_.variable_accesses[v];
     // Go through the variable accesses in reverse order (of command index)
     std::vector<Access>::const_reverse_iterator access_iter = accesses.rbegin(),
         access_end = accesses.rend();
     for (; access_iter != access_end; ++access_iter) {
       int32 command_index = access_iter->command_index;
       CommandType command_type =
           computation_.commands[command_index].command_type;
       // deallocation command should not be listed here.
       KALDI_ASSERT(command_type != kDeallocMatrix);
       if (access_iter->access_type != kReadAccess) {
         // If this operation is of type kWriteAccess or kReadWriteAccess
         ans = std::max(ans, command_index);
         break;  // break from access_iter loop (an optimization)
       }
     }
   }
   return ans;
 }
Member Data Documentation
const Analyzer& analyzer_ private
Definition at line 358 of file nnet-analyze.h.
Referenced by ComputationAnalysis::DataInvalidatedCommand(), ComputationAnalysis::FirstAccess(), ComputationAnalysis::FirstMatrixAccess(), ComputationAnalysis::LastAccess(), ComputationAnalysis::LastMatrixAccess(), and ComputationAnalysis::LastWriteAccess().
const NnetComputation& computation_ private
Definition at line 357 of file nnet-analyze.h.
Referenced by ComputationAnalysis::DataInvalidatedCommand(), ComputationAnalysis::FirstAccess(), ComputationAnalysis::FirstMatrixAccess(), ComputationAnalysis::LastAccess(), ComputationAnalysis::LastMatrixAccess(), and ComputationAnalysis::LastWriteAccess().
The documentation for this class was generated from the following files:
nnet3/nnet-analyze.h
nnet3/nnet-analyze.cc