Kaldi: NonlinearComponent Class Reference
NonlinearComponent Class Reference
This kind of Component is a base-class for things like sigmoid, softmax and ReLU: nonlinearities that don't change the dimension.
#include <nnet-component-itf.h>
Public Member Functions
void Init (int32 dim)
NonlinearComponent (int32 dim)
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void InitFromConfig (ConfigLine *cfl)
We implement InitFromConfig at this level.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
Public Member Functions inherited from Component
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const =0
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const =0
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
virtual std::string Type () const =0
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual int32 Properties () const =0
Return bitmask of the component's properties.
virtual Component * Copy () const =0
Copies component (deep copy).
Component ()
virtual ~Component ()
Protected Member Functions
void StoreStatsInternal (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes
int32 dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
Mutex mutex_
Friends
class NormalizationComponent
class SigmoidComponent
class TanhComponent
class SoftmaxComponent
class LogSoftmaxComponent
class RectifiedLinearComponent
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
This kind of Component is a base-class for things like sigmoid, softmax and ReLU: nonlinearities that don't change the dimension.
It takes care of storing statistics on the average activations and derivatives encountered during training.
Definition at line 427 of file nnet-component-itf.h.
Constructor & Destructor Documentation
NonlinearComponent (int32 dim) inline explicit
Definition at line 430 of file nnet-component-itf.h.
References NonlinearComponent::Init().
 { Init(dim); }
NonlinearComponent () inline
Definition at line 431 of file nnet-component-itf.h.
 : dim_(0) { } // e.g. prior to Read().
NonlinearComponent (const NonlinearComponent & other) explicit
Definition at line 349 of file nnet-component-itf.cc.
                                                                      :
     dim_(other.dim_), value_sum_(other.value_sum_), deriv_sum_(other.deriv_sum_),
     count_(other.count_) { }
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from Component.
Definition at line 278 of file nnet-component-itf.cc.
References CuVectorBase< Real >::AddVec(), NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::Dim(), KALDI_ASSERT, CuVector< Real >::Resize(), and NonlinearComponent::value_sum_.
{
   const NonlinearComponent *other =
       dynamic_cast<const NonlinearComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   if (value_sum_.Dim() == 0 && other->value_sum_.Dim() != 0)
     value_sum_.Resize(other->value_sum_.Dim());
   if (deriv_sum_.Dim() == 0 && other->deriv_sum_.Dim() != 0)
     deriv_sum_.Resize(other->deriv_sum_.Dim());
   if (other->value_sum_.Dim() != 0)
     value_sum_.AddVec(alpha, other->value_sum_);
   if (other->deriv_sum_.Dim() != 0)
     deriv_sum_.AddVec(alpha, other->deriv_sum_);
   count_ += alpha * other->count_;
 }
double Count () const inline
Definition at line 458 of file nnet-component-itf.h.
References NonlinearComponent::count_.
 { return count_; }
const CuVector<double>& DerivSum () const inline
Definition at line 456 of file nnet-component-itf.h.
References NonlinearComponent::deriv_sum_.
 { return deriv_sum_; }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Reimplemented in NormalizeComponent.
Definition at line 252 of file nnet-component-itf.cc.
References NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::Dim(), NonlinearComponent::dim_, NonlinearComponent::InputDim(), KALDI_ASSERT, NonlinearComponent::OutputDim(), VectorBase< Real >::Scale(), kaldi::nnet3::SummarizeVector(), Component::Type(), and NonlinearComponent::value_sum_.
Referenced by NormalizeComponent::Info().
{
   std::stringstream stream;
   KALDI_ASSERT(InputDim() == OutputDim());  // always the case
   stream << Type() << ", dim=" << InputDim();
   if (count_ > 0 && value_sum_.Dim() == dim_ &&  deriv_sum_.Dim() == dim_) {
     stream << ", count=" << std::setprecision(3) << count_
            << std::setprecision(6);
     Vector<double> value_avg_dbl(value_sum_);
     Vector<BaseFloat> value_avg(value_avg_dbl);
     value_avg.Scale(1.0 / count_);
     stream << ", value-avg=" << SummarizeVector(value_avg);
     Vector<double> deriv_avg_dbl(deriv_sum_);
     Vector<BaseFloat> deriv_avg(deriv_avg_dbl);
     deriv_avg.Scale(1.0 / count_);
     stream << ", deriv-avg=" << SummarizeVector(deriv_avg);
   }
   return stream.str();
 }
void Init (int32 dim) inline
Definition at line 429 of file nnet-component-itf.h.
References NonlinearComponent::count_, and NonlinearComponent::dim_.
Referenced by NonlinearComponent::InitFromConfig(), and NonlinearComponent::NonlinearComponent().
 { dim_ = dim; count_ = 0.0; }
void InitFromConfig (ConfigLine * cfl) virtual
We implement InitFromConfig at this level.
Implements Component.
Reimplemented in NormalizeComponent.
Definition at line 353 of file nnet-component-itf.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), NonlinearComponent::Init(), KALDI_ERR, Component::Type(), and ConfigLine::WholeLine().
{
   int32 dim;
   bool ok = cfl->GetValue("dim", &dim);
   if (!ok || cfl->HasUnusedValues() || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(dim);
 }
virtual int32 InputDim () const inline virtual
Returns input-dimension of this component.
Implements Component.
Definition at line 434 of file nnet-component-itf.h.
References NonlinearComponent::dim_.
Referenced by NonlinearComponent::Info(), and NonlinearComponent::StoreStatsInternal().
 { return dim_; }
const NonlinearComponent& operator= (const NonlinearComponent & other) protected
virtual int32 OutputDim () const inline virtual
Returns output-dimension of this component.
Implements Component.
Definition at line 435 of file nnet-component-itf.h.
References NonlinearComponent::dim_.
Referenced by NonlinearComponent::Info().
 { return dim_; }
void Read (std::istream & is, bool binary) virtual
We implement Read at this level as it just needs the Type().
Implements Component.
Reimplemented in NormalizeComponent.
Definition at line 293 of file nnet-component-itf.cc.
References NonlinearComponent::count_, NonlinearComponent::deriv_sum_, NonlinearComponent::dim_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), KALDI_ASSERT, CuVector< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), CuVectorBase< Real >::Scale(), Component::Type(), and NonlinearComponent::value_sum_.
{
   std::ostringstream ostr_beg, ostr_end;
   ostr_beg << "<" << Type() << ">"; // e.g. "<SigmoidComponent>"
   ostr_end << "</" << Type() << ">"; // e.g. "</SigmoidComponent>"
   ExpectOneOrTwoTokens(is, binary, ostr_beg.str(), "<Dim>");
   ReadBasicType(is, binary, &dim_); // Read dimension.
   std::string tok; // TODO: remove back-compatibility code.
   ReadToken(is, binary, &tok);
   if (tok == "<ValueSum>") {
     // this branch is for back compatibility.  TODO: delete it
     // after Dec 2015.
     value_sum_.Read(is, binary);
     ExpectToken(is, binary, "<DerivSum>");
     deriv_sum_.Read(is, binary);
     ExpectToken(is, binary, "<Count>");
     ReadBasicType(is, binary, &count_);
     ExpectToken(is, binary, ostr_end.str());
   } else {
     // The new format is more readable as we write values that are normalized by
     // the count.
     KALDI_ASSERT(tok == "<ValueAvg>");
     value_sum_.Read(is, binary);
     ExpectToken(is, binary, "<DerivAvg>");
     deriv_sum_.Read(is, binary);
     ExpectToken(is, binary, "<Count>");
     ReadBasicType(is, binary, &count_);
     value_sum_.Scale(count_);
     deriv_sum_.Scale(count_);
     ExpectToken(is, binary, ostr_end.str());
   }
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from Component.
Definition at line 272 of file nnet-component-itf.cc.
References NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::Scale(), and NonlinearComponent::value_sum_.
{
   value_sum_.Scale(scale);
   deriv_sum_.Scale(scale);
   count_ *= scale;
 }
void StoreStatsInternal (const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > * deriv = NULL) protected
Definition at line 217 of file nnet-component-itf.cc.
References CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::Dim(), NonlinearComponent::InputDim(), KALDI_ASSERT, Mutex::Lock(), NonlinearComponent::mutex_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuVector< Real >::Resize(), CuVectorBase< Real >::SetZero(), Mutex::Unlock(), and NonlinearComponent::value_sum_.
Referenced by SigmoidComponent::StoreStats(), TanhComponent::StoreStats(), RectifiedLinearComponent::StoreStats(), and SoftmaxComponent::StoreStats().
{
   KALDI_ASSERT(out_value.NumCols() == InputDim());
   // Check we have the correct dimensions.
   if (value_sum_.Dim() != InputDim() ||
       (deriv != NULL && deriv_sum_.Dim() != InputDim())) {
     mutex_.Lock();
     if (value_sum_.Dim() != InputDim()) {
       value_sum_.Resize(InputDim());
       count_ = 0.0;
     }
     if (deriv != NULL && deriv_sum_.Dim() != InputDim()) {
       deriv_sum_.Resize(InputDim());
       count_ = 0.0;
       value_sum_.SetZero();
     }
     mutex_.Unlock();
   }
   count_ += out_value.NumRows();
   CuVector<BaseFloat> temp(InputDim());
   temp.AddRowSumMat(1.0, out_value, 0.0);
   value_sum_.AddVec(1.0, temp);
   if (deriv != NULL) {
     temp.AddRowSumMat(1.0, *deriv, 0.0);
     deriv_sum_.AddVec(1.0, temp);
   }
 }
const CuVector<double>& ValueSum () const inline
Definition at line 455 of file nnet-component-itf.h.
References NonlinearComponent::value_sum_.
 { return value_sum_; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Reimplemented in NormalizeComponent.
Definition at line 325 of file nnet-component-itf.cc.
References VectorBase< Real >::CopyFromVec(), NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::Dim(), NonlinearComponent::dim_, kaldi::kUndefined, Vector< Real >::Resize(), VectorBase< Real >::Scale(), Component::Type(), NonlinearComponent::value_sum_, VectorBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   std::ostringstream ostr_beg, ostr_end;
   ostr_beg << "<" << Type() << ">"; // e.g. "<SigmoidComponent>"
   ostr_end << "</" << Type() << ">"; // e.g. "</SigmoidComponent>"
   WriteToken(os, binary, ostr_beg.str());
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   // Write the values and derivatives in a count-normalized way, for
   // greater readability in text form.
   WriteToken(os, binary, "<ValueAvg>");
   Vector<BaseFloat> temp(value_sum_);
   if (count_ != 0.0) temp.Scale(1.0 / count_);
   temp.Write(os, binary);
   WriteToken(os, binary, "<DerivAvg>");
   temp.Resize(deriv_sum_.Dim(), kUndefined);
   temp.CopyFromVec(deriv_sum_);
   if (count_ != 0.0) temp.Scale(1.0 / count_);
   temp.Write(os, binary);
   WriteToken(os, binary, "<Count>");
   WriteBasicType(os, binary, count_);
   WriteToken(os, binary, ostr_end.str());
 }
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) are free to implement ZeroStats() also.
Reimplemented from Component.
Definition at line 246 of file nnet-component-itf.cc.
References NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::SetZero(), and NonlinearComponent::value_sum_.
{
   value_sum_.SetZero();
   deriv_sum_.SetZero();
   count_ = 0.0;
 }
Friends And Related Function Documentation
friend class LogSoftmaxComponent friend
Definition at line 465 of file nnet-component-itf.h.
friend class NormalizationComponent friend
Definition at line 461 of file nnet-component-itf.h.
friend class RectifiedLinearComponent friend
Definition at line 466 of file nnet-component-itf.h.
friend class SigmoidComponent friend
Definition at line 462 of file nnet-component-itf.h.
friend class SoftmaxComponent friend
Definition at line 464 of file nnet-component-itf.h.
friend class TanhComponent friend
Definition at line 463 of file nnet-component-itf.h.
Member Data Documentation
double count_ protected
Definition at line 481 of file nnet-component-itf.h.
Referenced by NonlinearComponent::Add(), NonlinearComponent::Count(), NonlinearComponent::Info(), NormalizeComponent::Init(), NonlinearComponent::Init(), NormalizeComponent::Read(), NonlinearComponent::Read(), NonlinearComponent::Scale(), NonlinearComponent::StoreStatsInternal(), NormalizeComponent::Write(), NonlinearComponent::Write(), and NonlinearComponent::ZeroStats().
CuVector<double> deriv_sum_ protected
Definition at line 478 of file nnet-component-itf.h.
Referenced by NonlinearComponent::Add(), NonlinearComponent::DerivSum(), NonlinearComponent::Info(), NormalizeComponent::Read(), NonlinearComponent::Read(), NonlinearComponent::Scale(), NonlinearComponent::StoreStatsInternal(), NormalizeComponent::Write(), NonlinearComponent::Write(), and NonlinearComponent::ZeroStats().
int32 dim_ protected
Definition at line 476 of file nnet-component-itf.h.
Referenced by NonlinearComponent::Info(), NormalizeComponent::Init(), NonlinearComponent::Init(), NonlinearComponent::InputDim(), NonlinearComponent::OutputDim(), NormalizeComponent::Read(), NonlinearComponent::Read(), NormalizeComponent::Write(), and NonlinearComponent::Write().
Mutex mutex_ protected
Definition at line 483 of file nnet-component-itf.h.
Referenced by NonlinearComponent::StoreStatsInternal().
CuVector<double> value_sum_ protected
Definition at line 477 of file nnet-component-itf.h.
Referenced by NonlinearComponent::Add(), NonlinearComponent::Info(), NormalizeComponent::Read(), NonlinearComponent::Read(), NonlinearComponent::Scale(), NonlinearComponent::StoreStatsInternal(), NonlinearComponent::ValueSum(), NormalizeComponent::Write(), NonlinearComponent::Write(), and NonlinearComponent::ZeroStats().
The documentation for this class was generated from the following files:
nnet3/nnet-component-itf.h
nnet3/nnet-component-itf.cc