Kaldi: SimpleSumDescriptor Class Reference
SimpleSumDescriptor Class Reference
#include <nnet-descriptor.h>
Public Member Functions
virtual void GetDependencies (const Index &ind, std::vector< Cindex > *dependencies) const
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
virtual bool IsComputable (const Index &ind, const CindexSet &cindex_set, std::vector< Cindex > *used_inputs) const
This function exists to enable us to manage optional dependencies, i.e.
virtual int32 Dim (const Nnet &nnet) const
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
virtual int32 Modulus () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
written form is: if required_ == true, "<written-form-of-src>" else "IfDefined(<written-form-of-src>)".
virtual SumDescriptor * Copy () const
SimpleSumDescriptor (ForwardingDescriptor *src)
virtual ~SimpleSumDescriptor ()
Public Member Functions inherited from SumDescriptor
virtual ~SumDescriptor ()
Private Attributes
ForwardingDescriptor * src_
Detailed Description
Definition at line 360 of file nnet-descriptor.h.
Constructor & Destructor Documentation
SimpleSumDescriptor (ForwardingDescriptor * src) inline
Definition at line 379 of file nnet-descriptor.h.
Referenced by SimpleSumDescriptor::Copy().
 : src_(src) { }
virtual ~SimpleSumDescriptor () inline virtual
Definition at line 380 of file nnet-descriptor.h.
References SimpleSumDescriptor::src_.
 { delete src_; }
Member Function Documentation
SumDescriptor * Copy () const virtual
Implements SumDescriptor.
Definition at line 256 of file nnet-descriptor.cc.
References ForwardingDescriptor::Copy(), SimpleSumDescriptor::SimpleSumDescriptor(), and SimpleSumDescriptor::src_.
{
   return new SimpleSumDescriptor(src_->Copy());
 }
int32 Dim (const Nnet & nnet) const virtual
Implements SumDescriptor.
Definition at line 282 of file nnet-descriptor.cc.
References ForwardingDescriptor::Dim(), and SimpleSumDescriptor::src_.
{
   return src_->Dim(nnet);
 }
void GetDependencies (const Index & ind, std::vector< Cindex > * dependencies) const virtual
Given an Index at the output of this Descriptor, append to "dependencies" a list of Cindexes that describes what inputs we potentially depend on.
The output list is not necessarily sorted, and this function doesn't make sure that it's unique.
Implements SumDescriptor.
Definition at line 260 of file nnet-descriptor.cc.
References ForwardingDescriptor::MapToInput(), and SimpleSumDescriptor::src_.
{
   dependencies->push_back(src_->MapToInput(ind));
 }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
Implements SumDescriptor.
Definition at line 286 of file nnet-descriptor.cc.
References ForwardingDescriptor::GetNodeDependencies(), and SimpleSumDescriptor::src_.
{
   src_->GetNodeDependencies(node_indexes);
 }
bool IsComputable (const Index & ind, const CindexSet & cindex_set, std::vector< Cindex > * used_inputs) const virtual
This function exists to enable us to manage optional dependencies, i.e.
for making sense of expressions like (A + (B is present)) and (A if present; if not, B). Suppose we are trying to compute the index "ind", and the user represents that "cindex_set" is the set of Cindexes are available to the computation; then this function will return true if we can compute the expression given these inputs; and if so, will output to "used_inputs" the list of Cindexes that this expression will be a summation over.
Parameters
[in] ind The index that we want to compute at the output of the Descriptor.
[in] cindex_set The set of Cindexes that are available at the input of the Descriptor.
[out] used_inputs If non-NULL, if this function returns true then to this vector will be *appended* the inputs that will actually participate in the computation. Else (if non-NULL) it will be left unchanged.
Returns
Returns true if this output is computable given the provided inputs.
Implements SumDescriptor.
Definition at line 265 of file nnet-descriptor.cc.
References ForwardingDescriptor::MapToInput(), and SimpleSumDescriptor::src_.
{
   Cindex c = src_->MapToInput(ind);
   bool src_present  = cindex_set(c);
   if (src_present && used_inputs != NULL)
     used_inputs->push_back(c);
   return src_present;
 }
virtual int32 Modulus () const inline virtual
Implements SumDescriptor.
Definition at line 372 of file nnet-descriptor.h.
References ForwardingDescriptor::Modulus(), and SimpleSumDescriptor::src_.
 { return src_->Modulus(); }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
written form is: if required_ == true, "<written-form-of-src>" else "IfDefined(<written-form-of-src>)".
Implements SumDescriptor.
Definition at line 276 of file nnet-descriptor.cc.
References SimpleSumDescriptor::src_, and ForwardingDescriptor::WriteConfig().
{
   src_->WriteConfig(os, node_names);
 }
Member Data Documentation
ForwardingDescriptor* src_ private
Definition at line 382 of file nnet-descriptor.h.
Referenced by SimpleSumDescriptor::Copy(), SimpleSumDescriptor::Dim(), SimpleSumDescriptor::GetDependencies(), SimpleSumDescriptor::GetNodeDependencies(), SimpleSumDescriptor::IsComputable(), SimpleSumDescriptor::Modulus(), SimpleSumDescriptor::WriteConfig(), and SimpleSumDescriptor::~SimpleSumDescriptor().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc