Kaldi: RoundingForwardingDescriptor Class Reference
RoundingForwardingDescriptor Class Reference
For use in clockwork RNNs and the like, this forwarding-descriptor rounds the time-index t down to the the closest t' <= t that is an exact multiple of t_modulus_.
#include <nnet-descriptor.h>
Public Member Functions
virtual Cindex MapToInput (const Index &ind) const
virtual int32 Dim (const Nnet &nnet) const
virtual ForwardingDescriptor * Copy () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" all the node indexes.
RoundingForwardingDescriptor (ForwardingDescriptor *src, int32 t_modulus)
virtual ~RoundingForwardingDescriptor ()
Public Member Functions inherited from ForwardingDescriptor
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Attributes
ForwardingDescriptor * src_
int32 t_modulus_
Detailed Description
For use in clockwork RNNs and the like, this forwarding-descriptor rounds the time-index t down to the the closest t' <= t that is an exact multiple of t_modulus_.
Definition at line 205 of file nnet-descriptor.h.
Constructor & Destructor Documentation
RoundingForwardingDescriptor (ForwardingDescriptor * src, int32 t_modulus) inline
Definition at line 221 of file nnet-descriptor.h.
Referenced by RoundingForwardingDescriptor::Copy().
                                                :
       src_(src), t_modulus_(t_modulus) { }
virtual ~RoundingForwardingDescriptor () inline virtual
Definition at line 225 of file nnet-descriptor.h.
References RoundingForwardingDescriptor::src_.
 { delete src_; }
Member Function Documentation
ForwardingDescriptor * Copy () const virtual
Implements ForwardingDescriptor.
Definition at line 184 of file nnet-descriptor.cc.
References ForwardingDescriptor::Copy(), RoundingForwardingDescriptor::RoundingForwardingDescriptor(), RoundingForwardingDescriptor::src_, and RoundingForwardingDescriptor::t_modulus_.
{
   return new RoundingForwardingDescriptor(src_->Copy(), t_modulus_);
 }
virtual int32 Dim (const Nnet & nnet) const inline virtual
Implements ForwardingDescriptor.
Definition at line 208 of file nnet-descriptor.h.
References ForwardingDescriptor::Dim(), and RoundingForwardingDescriptor::src_.
 { return src_->Dim(nnet); }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" all the node indexes.
Implements ForwardingDescriptor.
Definition at line 169 of file nnet-descriptor.cc.
References ForwardingDescriptor::GetNodeDependencies(), and RoundingForwardingDescriptor::src_.
{
   src_->GetNodeDependencies(node_indexes);
 }
Cindex MapToInput (const Index & ind) const virtual
Implements ForwardingDescriptor.
Definition at line 174 of file nnet-descriptor.cc.
References KALDI_ASSERT, ForwardingDescriptor::MapToInput(), RoundingForwardingDescriptor::src_, and RoundingForwardingDescriptor::t_modulus_.
{
   KALDI_ASSERT(t_modulus_ >= 1);
   Cindex ans = src_->MapToInput(ind);
   int32 mod = ans.second.t % t_modulus_;
   if (mod < 0)
     mod += t_modulus_;
   ans.second.t -= mod;
   return ans;
 }
virtual int32 Modulus () const inline virtual
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
It returns the smallest modulus to which this descriptor is invariant; the lowest common multiple of all descriptors in the network gives you the modulus for the whole network.
Reimplemented from ForwardingDescriptor.
Definition at line 214 of file nnet-descriptor.h.
References RoundingForwardingDescriptor::t_modulus_.
 { return t_modulus_; }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Implements ForwardingDescriptor.
Definition at line 188 of file nnet-descriptor.cc.
References RoundingForwardingDescriptor::src_, RoundingForwardingDescriptor::t_modulus_, and ForwardingDescriptor::WriteConfig().
{
   os << "Round(";
   src_->WriteConfig(os, node_names);
   os << ", " << t_modulus_ << ")";
 }
Member Data Documentation
ForwardingDescriptor* src_ private
Definition at line 227 of file nnet-descriptor.h.
Referenced by RoundingForwardingDescriptor::Copy(), RoundingForwardingDescriptor::Dim(), RoundingForwardingDescriptor::GetNodeDependencies(), RoundingForwardingDescriptor::MapToInput(), RoundingForwardingDescriptor::WriteConfig(), and RoundingForwardingDescriptor::~RoundingForwardingDescriptor().
int32 t_modulus_ private
Definition at line 228 of file nnet-descriptor.h.
Referenced by RoundingForwardingDescriptor::Copy(), RoundingForwardingDescriptor::MapToInput(), RoundingForwardingDescriptor::Modulus(), and RoundingForwardingDescriptor::WriteConfig().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc