Kaldi: GaussClusterable Class Reference
GaussClusterable Class Reference
Classes and functions related to clustering
GaussClusterable wraps Gaussian statistics in a form accessible to generic clustering algorithms.
#include <clusterable-classes.h>
Public Member Functions
GaussClusterable ()
GaussClusterable (int32 dim, BaseFloat var_floor)
GaussClusterable (const Vector< BaseFloat > &x_stats, const Vector< BaseFloat > &x2_stats, BaseFloat var_floor, BaseFloat count)
virtual std::string Type () const
Return a string that describes the inherited type.
void AddStats (const VectorBase< BaseFloat > &vec, BaseFloat weight=1.0)
virtual BaseFloat Objf () const
Return the objective function associated with the stats [assuming ML estimation].
virtual void SetZero ()
Set stats to empty.
virtual void Add (const Clusterable &other_in)
Add other stats.
virtual void Sub (const Clusterable &other_in)
Subtract other stats.
virtual BaseFloat Normalizer () const
Return the normalizer (typically, count) associated with the stats.
virtual Clusterable * Copy () const
Return a copy of this object.
virtual void Scale (BaseFloat f)
Scale the stats by a positive number f [not mandatory to supply this].
virtual void Write (std::ostream &os, bool binary) const
Write data to stream.
virtual Clusterable * ReadNew (std::istream &is, bool binary) const
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
virtual ~GaussClusterable ()
BaseFloat count () const
SubVector< double > x_stats () const
SubVector< double > x2_stats () const
Public Member Functions inherited from Clusterable
virtual ~Clusterable ()
virtual BaseFloat ObjfPlus (const Clusterable &other) const
Return the objective function of the combined object this + other.
virtual BaseFloat ObjfMinus (const Clusterable &other) const
Return the objective function of the subtracted object this - other.
virtual BaseFloat Distance (const Clusterable &other) const
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Private Member Functions
void Read (std::istream &is, bool binary)
Private Attributes
double count_
Matrix< double > stats_
double var_floor_
Detailed Description
GaussClusterable wraps Gaussian statistics in a form accessible to generic clustering algorithms.
Definition at line 69 of file clusterable-classes.h.
Constructor & Destructor Documentation
GaussClusterable () inline
Definition at line 71 of file clusterable-classes.h.
Referenced by GaussClusterable::Copy(), and GaussClusterable::ReadNew().
 : count_(0.0), var_floor_(0.0) {}
GaussClusterable (int32 dim, BaseFloat var_floor) inline
Definition at line 72 of file clusterable-classes.h.
                                                   :
       count_(0.0), stats_(2, dim), var_floor_(var_floor) {}
GaussClusterable (const Vector< BaseFloat > & x_stats, const Vector< BaseFloat > & x2_stats, BaseFloat var_floor, BaseFloat count) inline
Definition at line 111 of file clusterable-classes.h.
References MatrixBase< Real >::Row(), and GaussClusterable::stats_.
                                                                                :
     count_(count), stats_(2, x_stats.Dim()), var_floor_(var_floor) {
   stats_.Row(0).CopyFromVec(x_stats);
   stats_.Row(1).CopyFromVec(x2_stats);
 }
virtual ~GaussClusterable () inline virtual
Definition at line 90 of file clusterable-classes.h.
 {}
Member Function Documentation
void Add (const Clusterable & other) virtual
Add other stats.
Implements Clusterable.
Definition at line 144 of file clusterable-classes.cc.
References MatrixBase< Real >::AddMat(), GaussClusterable::count_, KALDI_ASSERT, GaussClusterable::stats_, and Clusterable::Type().
{
   KALDI_ASSERT(other_in.Type() == "gauss");
   const GaussClusterable *other =
       static_cast<const GaussClusterable*>(&other_in);
   count_ += other->count_;
   stats_.AddMat(1.0, other->stats_);
 }
void AddStats (const VectorBase< BaseFloat > & vec, BaseFloat weight = 1.0)
Definition at line 137 of file clusterable-classes.cc.
References GaussClusterable::count_, MatrixBase< Real >::Row(), and GaussClusterable::stats_.
Referenced by kaldi::GenRandStats().
{
   count_ += weight;
   stats_.Row(0).AddVec(weight, vec);
   stats_.Row(1).AddVec2(weight, vec);
 }
Clusterable * Copy () const virtual
Return a copy of this object.
Implements Clusterable.
Definition at line 160 of file clusterable-classes.cc.
References GaussClusterable::GaussClusterable(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), GaussClusterable::stats_, and GaussClusterable::var_floor_.
{
   KALDI_ASSERT(stats_.NumRows() == 2);
   GaussClusterable *ans = new GaussClusterable(stats_.NumCols(), var_floor_);
   ans->Add(*this);
   return ans;
 }
BaseFloat count () const inline
Definition at line 92 of file clusterable-classes.h.
References GaussClusterable::count_.
Referenced by kaldi::ClusterGaussiansToUbm(), DiagGmm::DiagGmm(), kaldi::InitAmGmm(), and DiagGmm::MergeKmeans().
 { return count_; }
virtual BaseFloat Normalizer () const inline virtual
Return the normalizer (typically, count) associated with the stats.
Implements Clusterable.
Definition at line 85 of file clusterable-classes.h.
References GaussClusterable::count_.
 { return count_; }
BaseFloat Objf () const virtual
Return the objective function associated with the stats [assuming ML estimation].
Implements Clusterable.
Definition at line 193 of file clusterable-classes.cc.
References GaussClusterable::count_, rnnlm::d, KALDI_ISNAN, KALDI_WARN, M_LOG_2PI, MatrixBase< Real >::NumCols(), GaussClusterable::stats_, VectorBase< Real >::SumLog(), and GaussClusterable::var_floor_.
{
   if (count_ <= 0.0) {
     if (count_ < -0.1) {
       KALDI_WARN << "GaussClusterable::Objf(), count is negative " << count_;
     }
     return 0.0;
   } else {
     size_t dim = stats_.NumCols();
     Vector<double> vars(dim);
     double objf_per_frame = 0.0;
     for (size_t d = 0; d < dim; d++) {
       double mean(stats_(0, d) / count_), var = stats_(1, d) / count_ - mean
           * mean, floored_var = std::max(var, var_floor_);
       vars(d) = floored_var;
       objf_per_frame += -0.5 * var / floored_var;
     }
     objf_per_frame += -0.5 * (vars.SumLog() + M_LOG_2PI * dim);
     if (KALDI_ISNAN(objf_per_frame)) {
       KALDI_WARN << "GaussClusterable::Objf(), objf is NaN";
       return 0.0;
     }
     // KALDI_VLOG(2) << "count = " << count_ << ", objf_per_frame = "<< objf_per_frame
     //   << ", returning " << (objf_per_frame*count_) << ", floor = " << var_floor_;
     return objf_per_frame * count_;
   }
 }
void Read (std::istream & is, bool binary) private
Definition at line 186 of file clusterable-classes.cc.
References GaussClusterable::count_, kaldi::ExpectToken(), Matrix< Real >::Read(), kaldi::ReadBasicType(), GaussClusterable::stats_, and GaussClusterable::var_floor_.
Referenced by GaussClusterable::ReadNew().
{
   ExpectToken(is, binary, "GCL");  // magic string.
   ReadBasicType(is, binary, &count_);
   ReadBasicType(is, binary, &var_floor_);
   stats_.Read(is, binary);
 }
Clusterable * ReadNew (std::istream & os, bool binary) const virtual
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
Implements Clusterable.
Definition at line 180 of file clusterable-classes.cc.
References GaussClusterable::GaussClusterable(), and GaussClusterable::Read().
{
   GaussClusterable *gc = new GaussClusterable();
   gc->Read(is, binary);
   return gc;
 }
void Scale (BaseFloat f) virtual
Scale the stats by a positive number f [not mandatory to supply this].
Reimplemented from Clusterable.
Definition at line 167 of file clusterable-classes.cc.
References GaussClusterable::count_, KALDI_ASSERT, MatrixBase< Real >::Scale(), and GaussClusterable::stats_.
{
   KALDI_ASSERT(f >= 0.0);
   count_ *= f;
   stats_.Scale(f);
 }
void SetZero () inline virtual
Set stats to empty.
Implements Clusterable.
Definition at line 106 of file clusterable-classes.h.
References GaussClusterable::count_, MatrixBase< Real >::SetZero(), and GaussClusterable::stats_.
{
   count_ = 0;
   stats_.SetZero();
 }
void Sub (const Clusterable & other) virtual
Subtract other stats.
Implements Clusterable.
Definition at line 152 of file clusterable-classes.cc.
References MatrixBase< Real >::AddMat(), GaussClusterable::count_, KALDI_ASSERT, GaussClusterable::stats_, and Clusterable::Type().
{
   KALDI_ASSERT(other_in.Type() == "gauss");
   const GaussClusterable *other =
       static_cast<const GaussClusterable*>(&other_in);
   count_ -= other->count_;
   stats_.AddMat(-1.0, other->stats_);
 }
virtual std::string Type () const inline virtual
Return a string that describes the inherited type.
Implements Clusterable.
Definition at line 79 of file clusterable-classes.h.
 {  return "gauss"; }
void Write (std::ostream & os, bool binary) const virtual
Write data to stream.
Implements Clusterable.
Definition at line 173 of file clusterable-classes.cc.
References GaussClusterable::count_, GaussClusterable::stats_, GaussClusterable::var_floor_, MatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "GCL");  // magic string.
   WriteBasicType(os, binary, count_);
   WriteBasicType(os, binary, var_floor_);
   stats_.Write(os, binary);
 }
SubVector<double> x2_stats () const inline
Definition at line 95 of file clusterable-classes.h.
References MatrixBase< Real >::Row(), and GaussClusterable::stats_.
Referenced by kaldi::ClusterGaussiansToUbm(), DiagGmm::DiagGmm(), and DiagGmm::MergeKmeans().
 { return stats_.Row(1); }
SubVector<double> x_stats () const inline
Definition at line 94 of file clusterable-classes.h.
References MatrixBase< Real >::Row(), and GaussClusterable::stats_.
Referenced by kaldi::ClusterGaussiansToUbm(), DiagGmm::DiagGmm(), and DiagGmm::MergeKmeans().
 { return stats_.Row(0); }
Member Data Documentation
double count_ private
Definition at line 97 of file clusterable-classes.h.
Referenced by GaussClusterable::Add(), GaussClusterable::AddStats(), GaussClusterable::count(), GaussClusterable::Normalizer(), GaussClusterable::Objf(), GaussClusterable::Read(), GaussClusterable::Scale(), GaussClusterable::SetZero(), GaussClusterable::Sub(), and GaussClusterable::Write().
Matrix<double> stats_ private
Definition at line 98 of file clusterable-classes.h.
Referenced by GaussClusterable::Add(), GaussClusterable::AddStats(), GaussClusterable::Copy(), GaussClusterable::GaussClusterable(), GaussClusterable::Objf(), GaussClusterable::Read(), GaussClusterable::Scale(), GaussClusterable::SetZero(), GaussClusterable::Sub(), GaussClusterable::Write(), GaussClusterable::x2_stats(), and GaussClusterable::x_stats().
double var_floor_ private
Definition at line 99 of file clusterable-classes.h.
Referenced by GaussClusterable::Copy(), GaussClusterable::Objf(), GaussClusterable::Read(), and GaussClusterable::Write().
The documentation for this class was generated from the following files:
tree/clusterable-classes.h
tree/clusterable-classes.cc