Kaldi: Plp Class Reference
Plp Class Reference
FeatureExtraction
Class for computing PLP features.
#include <feature-plp.h>
Public Types
typedef PlpOptions Options
Public Member Functions
Plp (const PlpOptions &opts)
~Plp ()
int32 Dim () const
void Compute (const VectorBase< BaseFloat > &wave, BaseFloat vtln_warp, Matrix< BaseFloat > *output, Vector< BaseFloat > *wave_remainder=NULL)
Will throw exception on failure (e.g.
void Compute (const VectorBase< BaseFloat > &wave, BaseFloat vtln_warp, Matrix< BaseFloat > *output, Vector< BaseFloat > *wave_remainder=NULL) const
Const version of Compute()
Private Member Functions
void ComputeInternal (const VectorBase< BaseFloat > &wave, const MelBanks &mel_banks, const Vector< BaseFloat > &equal_loudness, Matrix< BaseFloat > *output, Vector< BaseFloat > *wave_remainder=NULL) const
const MelBanks * GetMelBanks (BaseFloat vtln_warp)
const MelBanks * GetMelBanks (BaseFloat vtln_warp, bool *must_delete) const
const Vector< BaseFloat > * GetEqualLoudness (BaseFloat vtln_warp)
const Vector< BaseFloat > * GetEqualLoudness (BaseFloat vtln_warp, const MelBanks &mel_banks, bool *must_delete) const
KALDI_DISALLOW_COPY_AND_ASSIGN (Plp)
Private Attributes
PlpOptions opts_
Vector< BaseFloat > lifter_coeffs_
Matrix< BaseFloat > idft_bases_
BaseFloat log_energy_floor_
std::map< BaseFloat, MelBanks * > mel_banks_
std::map< BaseFloat, Vector
< BaseFloat > * > equal_loudness_
FeatureWindowFunction feature_window_function_
SplitRadixRealFft< BaseFloat > * srfft_
Detailed Description
Class for computing PLP features.
See Computing PLP features where documentation will eventually be added.
Definition at line 98 of file feature-plp.h.
Member Typedef Documentation
typedef PlpOptions Options
Definition at line 117 of file feature-plp.h.
Constructor & Destructor Documentation
Plp (const PlpOptions & opts) explicit
Definition at line 27 of file feature-plp.cc.
References PlpOptions::cepstral_lifter, kaldi::ComputeLifterCoeffs(), PlpOptions::energy_floor, PlpOptions::frame_opts, Plp::GetMelBanks(), Plp::idft_bases_, kaldi::InitIdftBases(), Plp::lifter_coeffs_, kaldi::Log(), Plp::log_energy_floor_, PlpOptions::lpc_order, PlpOptions::mel_opts, MelBanksOptions::num_bins, PlpOptions::num_ceps, Plp::opts_, FrameExtractionOptions::PaddedWindowSize(), Vector< Real >::Resize(), and Plp::srfft_.
     : opts_(opts), feature_window_function_(opts.frame_opts), srfft_(NULL) {
   if (opts.cepstral_lifter != 0.0) {
     lifter_coeffs_.Resize(opts.num_ceps);
     ComputeLifterCoeffs(opts.cepstral_lifter, &lifter_coeffs_);
   }
   InitIdftBases(opts_.lpc_order + 1, opts_.mel_opts.num_bins + 2,
                 &idft_bases_);
   if (opts.energy_floor > 0.0)
     log_energy_floor_ = Log(opts.energy_floor);
   int32 padded_window_size = opts.frame_opts.PaddedWindowSize();
   if ((padded_window_size & (padded_window_size-1)) == 0)  // Is a power of two...
     srfft_ = new SplitRadixRealFft<BaseFloat>(padded_window_size);
   // We'll definitely need the filterbanks info for VTLN warping factor 1.0.
   // [note: this call caches it.]  The reason we call this here is to
   // improve the efficiency of the "const" version of Compute().
   GetMelBanks(1.0);
 }
~Plp ()
Definition at line 49 of file feature-plp.cc.
References Plp::equal_loudness_, Plp::mel_banks_, and Plp::srfft_.
           {
   for (std::map<BaseFloat, MelBanks*>::iterator iter = mel_banks_.begin();
       iter != mel_banks_.end();
       ++iter)
     delete iter->second;
   for (std::map<BaseFloat,
                 Vector<BaseFloat>* >::iterator iter = equal_loudness_.begin();
       iter != equal_loudness_.end();
       ++iter)
     delete iter->second;
    delete srfft_;
 }
Member Function Documentation
void Compute (const VectorBase< BaseFloat > & wave, BaseFloat vtln_warp, Matrix< BaseFloat > * output, Vector< BaseFloat > * wave_remainder = NULL)
Will throw exception on failure (e.g.
if file too short for even one frame). The output "wave_remainder" is the last frame or two of the waveform that it would be necessary to include in the next call to Compute for the same utterance. It is not exactly the un-processed part (it may have been partly processed), it's the start of the next window that we have not already processed. Will throw exception on failure (e.g. if file too short for even one frame).
Definition at line 128 of file feature-plp.cc.
References Plp::ComputeInternal(), Plp::GetEqualLoudness(), and Plp::GetMelBanks().
Referenced by main(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlinePlp(), UnitTestHTKCompare1(), and UnitTestSimple().
{
   const MelBanks *mel_banks = GetMelBanks(vtln_warp);
   const Vector<BaseFloat> *equal_loudness = GetEqualLoudness(vtln_warp);
   ComputeInternal(wave, *mel_banks,
                   *equal_loudness,
                   output, wave_remainder);
 }
void Compute (const VectorBase< BaseFloat > & wave, BaseFloat vtln_warp, Matrix< BaseFloat > * output, Vector< BaseFloat > * wave_remainder = NULL) const
Const version of Compute()
Definition at line 139 of file feature-plp.cc.
References Plp::ComputeInternal(), Plp::GetEqualLoudness(), and Plp::GetMelBanks().
{
   bool must_delete_mel_banks, must_delete_equal_loudness;
   const MelBanks *mel_banks = GetMelBanks(vtln_warp,
                                                &must_delete_mel_banks);
   const Vector<BaseFloat> *equal_loudness
       = GetEqualLoudness(vtln_warp, *mel_banks,
                          &must_delete_equal_loudness);
   ComputeInternal(wave, *mel_banks, *equal_loudness,
                   output, wave_remainder);
   if (must_delete_mel_banks)
     delete mel_banks;
   if (must_delete_equal_loudness)
     delete equal_loudness;
 }
void ComputeInternal (const VectorBase< BaseFloat > & wave, const MelBanks & mel_banks, const Vector< BaseFloat > & equal_loudness, Matrix< BaseFloat > * output, Vector< BaseFloat > * wave_remainder = NULL) const private
Definition at line 160 of file feature-plp.cc.
References VectorBase< Real >::AddMatVec(), VectorBase< Real >::ApplyPow(), PlpOptions::cepstral_lifter, PlpOptions::cepstral_scale, PlpOptions::compress_factor, MelBanks::Compute(), SplitRadixRealFft< Real >::Compute(), kaldi::ComputeLpc(), kaldi::ComputePowerSpectrum(), VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), PlpOptions::energy_floor, kaldi::ExtractWaveformRemainder(), kaldi::ExtractWindow(), Plp::feature_window_function_, PlpOptions::frame_opts, PlpOptions::htk_compat, rnnlm::i, Plp::idft_bases_, KALDI_ASSERT, kaldi::kNoTrans, Plp::lifter_coeffs_, kaldi::Log(), Plp::log_energy_floor_, kaldi::Lpc2Cepstrum(), PlpOptions::lpc_order, PlpOptions::mel_opts, VectorBase< Real >::MulElements(), MelBanksOptions::num_bins, PlpOptions::num_ceps, kaldi::NumFrames(), Plp::opts_, PlpOptions::raw_energy, kaldi::RealFft(), Matrix< Real >::Resize(), MatrixBase< Real >::Row(), VectorBase< Real >::Scale(), Plp::srfft_, PlpOptions::use_energy, and kaldi::VecVec().
Referenced by Plp::Compute().
{
   KALDI_ASSERT(output != NULL);
   int32 rows_out = NumFrames(wave.Dim(), opts_.frame_opts),
       cols_out = opts_.num_ceps;
   if (rows_out == 0) {
     output->Resize(0, 0);
     if (wave_remainder != NULL)
       *wave_remainder = wave;
     return;
   }
   output->Resize(rows_out, cols_out);
   if (wave_remainder != NULL)
     ExtractWaveformRemainder(wave, opts_.frame_opts, wave_remainder);
   Vector<BaseFloat> window;  // windowed waveform.
   int32 num_mel_bins = opts_.mel_opts.num_bins;
   Vector<BaseFloat> mel_energies(num_mel_bins);
   Vector<BaseFloat> mel_energies_duplicated(num_mel_bins+2);
   Vector<BaseFloat> autocorr_coeffs(opts_.lpc_order+1);
   Vector<BaseFloat> lpc_coeffs(opts_.lpc_order);
   Vector<BaseFloat> raw_cepstrum(opts_.lpc_order);  // not including C0,
   // and size may differ from final size.
   Vector<BaseFloat> final_cepstrum(opts_.num_ceps);
   std::vector<BaseFloat> temp_buffer;  // used by srfft.
   KALDI_ASSERT(opts_.num_ceps <= opts_.lpc_order+1);  // our num-ceps includes C0.
   for (int32 r = 0; r < rows_out; r++) {  // r is frame index..
     BaseFloat log_energy;
     ExtractWindow(wave, r, opts_.frame_opts,
                   feature_window_function_, &window,
                   (opts_.use_energy && opts_.raw_energy ? &log_energy : NULL));
     if (opts_.use_energy && !opts_.raw_energy)
       log_energy = Log(std::max(VecVec(window, window),
                                 std::numeric_limits<BaseFloat>::min()));
     if (srfft_ != NULL)  // Compute FFT using split-radix algorithm.
       srfft_->Compute(window.Data(), true, &temp_buffer);
     else  // An alternative algorithm that works for non-powers-of-two.
       RealFft(&window, true);
     // Convert the FFT into a power spectrum.
     ComputePowerSpectrum(&window);  // elements 0 ... window.Dim()/2
     SubVector<BaseFloat> power_spectrum(window, 0, window.Dim()/2 + 1);
     mel_banks.Compute(power_spectrum, &mel_energies);
     mel_energies.MulElements(equal_loudness);
     mel_energies.ApplyPow(opts_.compress_factor);
     // duplicate first and last elements.
     {
       SubVector<BaseFloat> v(mel_energies_duplicated, 1, num_mel_bins);
       v.CopyFromVec(mel_energies);
     }
     mel_energies_duplicated(0) = mel_energies(0);
     mel_energies_duplicated(num_mel_bins+1) = mel_energies(num_mel_bins-1);
     autocorr_coeffs.AddMatVec(1.0, idft_bases_, kNoTrans,
                               mel_energies_duplicated,  0.0);
     BaseFloat energy = ComputeLpc(autocorr_coeffs, &lpc_coeffs);
     energy = std::max(energy,
                       std::numeric_limits<BaseFloat>::min());
     Lpc2Cepstrum(opts_.lpc_order, lpc_coeffs.Data(), raw_cepstrum.Data());
     {
       SubVector<BaseFloat> dst(final_cepstrum, 1, opts_.num_ceps-1);
       SubVector<BaseFloat> src(raw_cepstrum, 0, opts_.num_ceps-1);
       dst.CopyFromVec(src);
       final_cepstrum(0) = energy;
     }
     if (opts_.cepstral_lifter != 0.0)
       final_cepstrum.MulElements(lifter_coeffs_);
     if (opts_.cepstral_scale != 1.0)
       final_cepstrum.Scale(opts_.cepstral_scale);
     if (opts_.use_energy) {
       if (opts_.energy_floor > 0.0 && log_energy < log_energy_floor_)
         log_energy = log_energy_floor_;
       final_cepstrum(0) = log_energy;
     }
     if (opts_.htk_compat) {
       BaseFloat energy = final_cepstrum(0);
       for (int32 i = 0; i < opts_.num_ceps-1; i++)
         final_cepstrum(i) = final_cepstrum(i+1);
       // if (!opts_.use_energy)
         // energy *= M_SQRT2;  // scale on C0 (actually removing scale
       // we previously added that's part of one common definition of
       // cosine transform.)
       final_cepstrum(opts_.num_ceps-1)  = energy;
     }
     output->Row(r).CopyFromVec(final_cepstrum);
     // std::cout << "FIN" << final_cepstrum;
   }
 }
int32 Dim () const inline
Definition at line 103 of file feature-plp.h.
References PlpOptions::num_ceps, and Plp::opts_.
 { return opts_.num_ceps; }
const Vector< BaseFloat > * GetEqualLoudness (BaseFloat vtln_warp) private
Definition at line 94 of file feature-plp.cc.
References Plp::equal_loudness_, kaldi::GetEqualLoudnessVector(), and Plp::GetMelBanks().
Referenced by Plp::Compute().
{
   const MelBanks *this_mel_banks = GetMelBanks(vtln_warp);
   Vector<BaseFloat> *ans = NULL;
   std::map<BaseFloat, Vector<BaseFloat>*>::iterator iter
       = equal_loudness_.find(vtln_warp);
   if (iter == equal_loudness_.end()) {
     ans = new Vector<BaseFloat>;
     GetEqualLoudnessVector(*this_mel_banks, ans);
     equal_loudness_[vtln_warp] = ans;
   } else {
     ans = iter->second;
   }
   return ans;
 }
const Vector< BaseFloat > * GetEqualLoudness (BaseFloat vtln_warp, const MelBanks & mel_banks, bool * must_delete) const private
Definition at line 110 of file feature-plp.cc.
References Plp::equal_loudness_, and kaldi::GetEqualLoudnessVector().
{
   Vector<BaseFloat> *ans = NULL;
   std::map<BaseFloat, Vector<BaseFloat>*>::const_iterator iter
       = equal_loudness_.find(vtln_warp);
   if (iter == equal_loudness_.end()) {
     ans = new Vector<BaseFloat>;
     GetEqualLoudnessVector(mel_banks, ans);
     *must_delete = true;
   } else {
     ans = iter->second;
     *must_delete = false;
   }
   return ans;
 }
const MelBanks * GetMelBanks (BaseFloat vtln_warp) private
Definition at line 64 of file feature-plp.cc.
References PlpOptions::frame_opts, Plp::mel_banks_, PlpOptions::mel_opts, and Plp::opts_.
Referenced by Plp::Compute(), Plp::GetEqualLoudness(), and Plp::Plp().
{
   MelBanks *this_mel_banks = NULL;
   std::map<BaseFloat, MelBanks*>::iterator iter = mel_banks_.find(vtln_warp);
   if (iter == mel_banks_.end()) {
     this_mel_banks = new MelBanks(opts_.mel_opts,
                                   opts_.frame_opts,
                                   vtln_warp);
     mel_banks_[vtln_warp] = this_mel_banks;
   } else {
     this_mel_banks = iter->second;
   }
   return this_mel_banks;
 }
const MelBanks * GetMelBanks (BaseFloat vtln_warp, bool * must_delete) const private
Definition at line 78 of file feature-plp.cc.
References PlpOptions::frame_opts, Plp::mel_banks_, PlpOptions::mel_opts, and Plp::opts_.
{
   MelBanks *this_mel_banks = NULL;
   std::map<BaseFloat, MelBanks*>::const_iterator iter =
       mel_banks_.find(vtln_warp);
   if (iter == mel_banks_.end()) {
     this_mel_banks = new MelBanks(opts_.mel_opts,
                                   opts_.frame_opts,
                                   vtln_warp);
     *must_delete = true;
   } else {
     this_mel_banks = iter->second;
     *must_delete = false;
   }
   return this_mel_banks;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (Plp) private
Member Data Documentation
std::map<BaseFloat, Vector<BaseFloat>* > equal_loudness_ private
Definition at line 145 of file feature-plp.h.
Referenced by Plp::GetEqualLoudness(), and Plp::~Plp().
FeatureWindowFunction feature_window_function_ private
Definition at line 146 of file feature-plp.h.
Referenced by Plp::ComputeInternal().
Matrix<BaseFloat> idft_bases_ private
Definition at line 142 of file feature-plp.h.
Referenced by Plp::ComputeInternal(), and Plp::Plp().
Vector<BaseFloat> lifter_coeffs_ private
Definition at line 141 of file feature-plp.h.
Referenced by Plp::ComputeInternal(), and Plp::Plp().
BaseFloat log_energy_floor_ private
Definition at line 143 of file feature-plp.h.
Referenced by Plp::ComputeInternal(), and Plp::Plp().
std::map<BaseFloat, MelBanks*> mel_banks_ private
Definition at line 144 of file feature-plp.h.
Referenced by Plp::GetMelBanks(), and Plp::~Plp().
PlpOptions opts_ private
Definition at line 140 of file feature-plp.h.
Referenced by Plp::ComputeInternal(), Plp::Dim(), Plp::GetMelBanks(), and Plp::Plp().
SplitRadixRealFft<BaseFloat>* srfft_ private
Definition at line 147 of file feature-plp.h.
Referenced by Plp::ComputeInternal(), Plp::Plp(), and Plp::~Plp().
The documentation for this class was generated from the following files:
feat/feature-plp.h
feat/feature-plp.cc