Kaldi: LstmProjectedStreams Class Reference
LstmProjectedStreams Class Reference
#include <nnet-lstm-projected-streams.h>
Public Member Functions
LstmProjectedStreams (int32 input_dim, int32 output_dim)
~LstmProjectedStreams ()
Component * Copy () const
Copy component (deep copy).
ComponentType GetType () const
Get Type Identification of the component.
void InitData (std::istream &is)
Initialize internal data of a component.
void ReadData (std::istream &is, bool binary)
Reads the component content.
void WriteData (std::ostream &os, bool binary) const
Writes the component content.
int32 NumParams () const
Number of trainable parameters.
void GetParams (Vector< BaseFloat > *wei_copy) const
std::string Info () const
Optionally print some additional info.
std::string InfoGradient () const
void ResetLstmStreams (const std::vector< int32 > &stream_reset_flag)
void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)
Abstract interface for propagation/backpropagation.
void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)
Backward pass transformation (to be implemented by descending class...)
void Update (const CuMatrixBase< BaseFloat > &input, const CuMatrixBase< BaseFloat > &diff)
Compute gradient and update parameters.
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (int32 input_dim, int32 output_dim)
virtual ~UpdatableComponent ()
bool IsUpdatable () const
Check if contains trainable parameters.
virtual void SetTrainOptions (const NnetTrainOptions &opts)
Sets the training options to the component.
const NnetTrainOptions & GetTrainOptions () const
Gets the training options from the component.
Public Member Functions inherited from Component
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
Static Public Member Functions
static void InitMatParam (CuMatrix< BaseFloat > &m, float scale)
static void InitVecParam (CuVector< BaseFloat > &v, float scale)
Static Public Member Functions inherited from Component
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Private Attributes
int32 ncell_
int32 nrecur_
recurrent projection layer dim
int32 nstream_
CuMatrix< BaseFloat > prev_nnet_state_
BaseFloat clip_gradient_
CuMatrix< BaseFloat > w_gifo_x_
CuMatrix< BaseFloat > w_gifo_x_corr_
CuMatrix< BaseFloat > w_gifo_r_
CuMatrix< BaseFloat > w_gifo_r_corr_
CuVector< BaseFloat > bias_
CuVector< BaseFloat > bias_corr_
CuVector< BaseFloat > peephole_i_c_
CuVector< BaseFloat > peephole_f_c_
CuVector< BaseFloat > peephole_o_c_
CuVector< BaseFloat > peephole_i_c_corr_
CuVector< BaseFloat > peephole_f_c_corr_
CuVector< BaseFloat > peephole_o_c_corr_
CuMatrix< BaseFloat > w_r_m_
CuMatrix< BaseFloat > w_r_m_corr_
CuMatrix< BaseFloat > propagate_buf_
CuMatrix< BaseFloat > backpropagate_buf_
Additional Inherited Members
Public Types inherited from Component
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Static Public Attributes inherited from Component
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Attributes inherited from UpdatableComponent
NnetTrainOptions opts_
Option-class with training hyper-parameters.
Protected Attributes inherited from Component
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Detailed Description
Definition at line 45 of file nnet-lstm-projected-streams.h.
Constructor & Destructor Documentation
LstmProjectedStreams (int32 input_dim, int32 output_dim) inline
Definition at line 47 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::Copy().
                                                           :
     UpdatableComponent(input_dim, output_dim),
     ncell_(0),
     nrecur_(output_dim),
     nstream_(0),
     clip_gradient_(0.0)
     //, dropout_rate_(0.0)
   { }
~LstmProjectedStreams () inline
Definition at line 56 of file nnet-lstm-projected-streams.h.
   { }
Member Function Documentation
void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) inline virtual
Backward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 418 of file nnet-lstm-projected-streams.h.
References CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::ApplyCeiling(), CuMatrixBase< Real >::ApplyCeiling(), CuVectorBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyFloor(), LstmProjectedStreams::backpropagate_buf_, LstmProjectedStreams::bias_corr_, LstmProjectedStreams::clip_gradient_, CuMatrixBase< Real >::ColRange(), kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, NnetTrainOptions::momentum, LstmProjectedStreams::ncell_, LstmProjectedStreams::nrecur_, LstmProjectedStreams::nstream_, CuMatrixBase< Real >::NumRows(), UpdatableComponent::opts_, LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_f_c_corr_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_i_c_corr_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::peephole_o_c_corr_, LstmProjectedStreams::propagate_buf_, CuMatrix< Real >::Resize(), CuMatrixBase< Real >::RowRange(), LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_r_corr_, LstmProjectedStreams::w_gifo_x_, LstmProjectedStreams::w_gifo_x_corr_, LstmProjectedStreams::w_r_m_, and LstmProjectedStreams::w_r_m_corr_.
{
     int DEBUG = 0;
     int32 T = in.NumRows() / nstream_;
     int32 S = nstream_;
     // disassemble propagated buffer into neurons
     CuSubMatrix<BaseFloat> YG(propagate_buf_.ColRange(0*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YI(propagate_buf_.ColRange(1*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YF(propagate_buf_.ColRange(2*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YO(propagate_buf_.ColRange(3*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YC(propagate_buf_.ColRange(4*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YH(propagate_buf_.ColRange(5*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YM(propagate_buf_.ColRange(6*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YR(propagate_buf_.ColRange(7*ncell_, nrecur_));
     // 0:dummy, [1,T] frames, T+1 backward pass history
     backpropagate_buf_.Resize((T+2)*S, 7 * ncell_ + nrecur_, kSetZero);
     // disassemble backpropagate buffer into neurons
     CuSubMatrix<BaseFloat> DG(backpropagate_buf_.ColRange(0*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DI(backpropagate_buf_.ColRange(1*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DF(backpropagate_buf_.ColRange(2*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DO(backpropagate_buf_.ColRange(3*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DC(backpropagate_buf_.ColRange(4*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DH(backpropagate_buf_.ColRange(5*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DM(backpropagate_buf_.ColRange(6*ncell_, ncell_));
     CuSubMatrix<BaseFloat> DR(backpropagate_buf_.ColRange(7*ncell_, nrecur_));
     CuSubMatrix<BaseFloat> DGIFO(backpropagate_buf_.ColRange(0, 4*ncell_));
     // projection layer to LSTM output is not recurrent, so backprop it all in once
     DR.RowRange(1*S,T*S).CopyFromMat(out_diff);
     for (int t = T; t >= 1; t--) {
       CuSubMatrix<BaseFloat> y_g(YG.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_i(YI.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_f(YF.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_o(YO.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_c(YC.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_h(YH.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_m(YM.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_r(YR.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_g(DG.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_i(DI.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_f(DF.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_o(DO.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_c(DC.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_h(DH.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_m(DM.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> d_r(DR.RowRange(t*S,S));
       // r
       //   Version 1 (precise gradients):
       //   backprop error from g(t+1), i(t+1), f(t+1), o(t+1) to r(t)
       d_r.AddMatMat(1.0, DGIFO.RowRange((t+1)*S,S), kNoTrans, w_gifo_r_, kNoTrans, 1.0);
       /*
       //   Version 2 (Alex Graves' PhD dissertation):
       //   only backprop g(t+1) to r(t)
       CuSubMatrix<BaseFloat> w_g_r_(w_gifo_r_.RowRange(0, ncell_));
       d_r.AddMatMat(1.0, DG.RowRange((t+1)*S,S), kNoTrans, w_g_r_, kNoTrans, 1.0);
       */
       /*
       //   Version 3 (Felix Gers' PhD dissertation):
       //   truncate gradients of g(t+1), i(t+1), f(t+1), o(t+1) once they leak out memory block
       //   CEC(with forget connection) is the only "error-bridge" through time
       */
       // r -> m
       d_m.AddMatMat(1.0, d_r, kNoTrans, w_r_m_, kNoTrans, 0.0);
       // m -> h via output gate
       d_h.AddMatMatElements(1.0, d_m, y_o, 0.0);
       d_h.DiffTanh(y_h, d_h);
       // o
       d_o.AddMatMatElements(1.0, d_m, y_h, 0.0);
       d_o.DiffSigmoid(y_o, d_o);
       // c
       // 1. diff from h(t)
       // 2. diff from c(t+1) (via forget-gate between CEC)
       // 3. diff from i(t+1) (via peephole)
       // 4. diff from f(t+1) (via peephole)
       // 5. diff from o(t)   (via peephole, not recurrent)
       d_c.AddMat(1.0, d_h);
       d_c.AddMatMatElements(1.0, DC.RowRange((t+1)*S,S), YF.RowRange((t+1)*S,S), 1.0);
       d_c.AddMatDiagVec(1.0, DI.RowRange((t+1)*S,S), kNoTrans, peephole_i_c_, 1.0);
       d_c.AddMatDiagVec(1.0, DF.RowRange((t+1)*S,S), kNoTrans, peephole_f_c_, 1.0);
       d_c.AddMatDiagVec(1.0, d_o                   , kNoTrans, peephole_o_c_, 1.0);
       // f
       d_f.AddMatMatElements(1.0, d_c, YC.RowRange((t-1)*S,S), 0.0);
       d_f.DiffSigmoid(y_f, d_f);
       // i
       d_i.AddMatMatElements(1.0, d_c, y_g, 0.0);
       d_i.DiffSigmoid(y_i, d_i);
       // c -> g via input gate
       d_g.AddMatMatElements(1.0, d_c, y_i, 0.0);
       d_g.DiffTanh(y_g, d_g);
       // debug info
       if (DEBUG) {
         std::cerr << "backward-pass frame " << t << "\n";
         std::cerr << "derivative wrt input r " << d_r;
         std::cerr << "derivative wrt input m " << d_m;
         std::cerr << "derivative wrt input h " << d_h;
         std::cerr << "derivative wrt input o " << d_o;
         std::cerr << "derivative wrt input c " << d_c;
         std::cerr << "derivative wrt input f " << d_f;
         std::cerr << "derivative wrt input i " << d_i;
         std::cerr << "derivative wrt input g " << d_g;
       }
     }
     // g,i,f,o -> x, do it all in once
     in_diff->AddMatMat(1.0, DGIFO.RowRange(1*S,T*S), kNoTrans, w_gifo_x_, kNoTrans, 0.0);
     //if (dropout_rate_ != 0.0) {
     //  in_diff->MulElements(dropout_mask_);
     //}
     // calculate delta
     const BaseFloat mmt = opts_.momentum;
     // weight x -> g, i, f, o
     w_gifo_x_corr_.AddMatMat(1.0, DGIFO.RowRange(1*S,T*S), kTrans,
                                   in                     , kNoTrans, mmt);
     // recurrent weight r -> g, i, f, o
     w_gifo_r_corr_.AddMatMat(1.0, DGIFO.RowRange(1*S,T*S), kTrans,
                                   YR.RowRange(0*S,T*S)   , kNoTrans, mmt);
     // bias of g, i, f, o
     bias_corr_.AddRowSumMat(1.0, DGIFO.RowRange(1*S,T*S), mmt);
     // recurrent peephole c -> i
     peephole_i_c_corr_.AddDiagMatMat(1.0, DI.RowRange(1*S,T*S), kTrans,
                                           YC.RowRange(0*S,T*S), kNoTrans, mmt);
     // recurrent peephole c -> f
     peephole_f_c_corr_.AddDiagMatMat(1.0, DF.RowRange(1*S,T*S), kTrans,
                                           YC.RowRange(0*S,T*S), kNoTrans, mmt);
     // peephole c -> o
     peephole_o_c_corr_.AddDiagMatMat(1.0, DO.RowRange(1*S,T*S), kTrans,
                                           YC.RowRange(1*S,T*S), kNoTrans, mmt);
     w_r_m_corr_.AddMatMat(1.0, DR.RowRange(1*S,T*S), kTrans,
                                YM.RowRange(1*S,T*S), kNoTrans, mmt);
     if (clip_gradient_ > 0.0) {
       w_gifo_x_corr_.ApplyFloor(-clip_gradient_);
       w_gifo_x_corr_.ApplyCeiling(clip_gradient_);
       w_gifo_r_corr_.ApplyFloor(-clip_gradient_);
       w_gifo_r_corr_.ApplyCeiling(clip_gradient_);
       bias_corr_.ApplyFloor(-clip_gradient_);
       bias_corr_.ApplyCeiling(clip_gradient_);
       w_r_m_corr_.ApplyFloor(-clip_gradient_);
       w_r_m_corr_.ApplyCeiling(clip_gradient_);
       peephole_i_c_corr_.ApplyFloor(-clip_gradient_);
       peephole_i_c_corr_.ApplyCeiling(clip_gradient_);
       peephole_f_c_corr_.ApplyFloor(-clip_gradient_);
       peephole_f_c_corr_.ApplyCeiling(clip_gradient_);
       peephole_o_c_corr_.ApplyFloor(-clip_gradient_);
       peephole_o_c_corr_.ApplyCeiling(clip_gradient_);
     }
     if (DEBUG) {
       std::cerr << "gradients(with optional momentum): \n";
       std::cerr << "w_gifo_x_corr_ " << w_gifo_x_corr_;
       std::cerr << "w_gifo_r_corr_ " << w_gifo_r_corr_;
       std::cerr << "bias_corr_ " << bias_corr_;
       std::cerr << "w_r_m_corr_ " << w_r_m_corr_;
       std::cerr << "peephole_i_c_corr_ " << peephole_i_c_corr_;
       std::cerr << "peephole_f_c_corr_ " << peephole_f_c_corr_;
       std::cerr << "peephole_o_c_corr_ " << peephole_o_c_corr_;
     }
   }
Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 59 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::LstmProjectedStreams().
 { return new LstmProjectedStreams(*this); }
void GetParams (Vector< BaseFloat > * wei_copy) const inline virtual
Implements UpdatableComponent.
Definition at line 189 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::bias_, CuVectorBase< Real >::Dim(), CuMatrixBase< Real >::NumCols(), LstmProjectedStreams::NumParams(), CuMatrixBase< Real >::NumRows(), LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_o_c_, VectorBase< Real >::Range(), Vector< Real >::Resize(), LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_x_, and LstmProjectedStreams::w_r_m_.
{
     wei_copy->Resize(NumParams());
     int32 offset, len;
     offset = 0;  len = w_gifo_x_.NumRows() * w_gifo_x_.NumCols();
     wei_copy->Range(offset, len).CopyRowsFromMat(w_gifo_x_);
     offset += len; len = w_gifo_r_.NumRows() * w_gifo_r_.NumCols();
     wei_copy->Range(offset, len).CopyRowsFromMat(w_gifo_r_);
     offset += len; len = bias_.Dim();
     wei_copy->Range(offset, len).CopyFromVec(bias_);
     offset += len; len = peephole_i_c_.Dim();
     wei_copy->Range(offset, len).CopyFromVec(peephole_i_c_);
     offset += len; len = peephole_f_c_.Dim();
     wei_copy->Range(offset, len).CopyFromVec(peephole_f_c_);
     offset += len; len = peephole_o_c_.Dim();
     wei_copy->Range(offset, len).CopyFromVec(peephole_o_c_);
     offset += len; len = w_r_m_.NumRows() * w_r_m_.NumCols();
     wei_copy->Range(offset, len).CopyRowsFromMat(w_r_m_);
     return;
   }
ComponentType GetType () const inline virtual
Get Type Identification of the component.
Implements Component.
Definition at line 60 of file nnet-lstm-projected-streams.h.
References Component::kLstmProjectedStreams.
 { return kLstmProjectedStreams; }
std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented from Component.
Definition at line 218 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::bias_, kaldi::nnet1::MomentStatistics(), LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_x_, and LstmProjectedStreams::w_r_m_.
{
     return std::string("  ") +
       "\n  w_gifo_x_  "   + MomentStatistics(w_gifo_x_) +
       "\n  w_gifo_r_  "   + MomentStatistics(w_gifo_r_) +
       "\n  bias_  "     + MomentStatistics(bias_) +
       "\n  peephole_i_c_  " + MomentStatistics(peephole_i_c_) +
       "\n  peephole_f_c_  " + MomentStatistics(peephole_f_c_) +
       "\n  peephole_o_c_  " + MomentStatistics(peephole_o_c_) +
       "\n  w_r_m_  "    + MomentStatistics(w_r_m_);
   }
std::string InfoGradient () const inline virtual
Reimplemented from Component.
Definition at line 229 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::backpropagate_buf_, LstmProjectedStreams::bias_corr_, CuMatrixBase< Real >::ColRange(), kaldi::nnet1::MomentStatistics(), LstmProjectedStreams::ncell_, LstmProjectedStreams::nrecur_, LstmProjectedStreams::peephole_f_c_corr_, LstmProjectedStreams::peephole_i_c_corr_, LstmProjectedStreams::peephole_o_c_corr_, LstmProjectedStreams::propagate_buf_, LstmProjectedStreams::w_gifo_r_corr_, LstmProjectedStreams::w_gifo_x_corr_, and LstmProjectedStreams::w_r_m_corr_.
{
     // disassemble forward-propagation buffer into different neurons,
     const CuSubMatrix<BaseFloat> YG(propagate_buf_.ColRange(0*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YI(propagate_buf_.ColRange(1*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YF(propagate_buf_.ColRange(2*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YO(propagate_buf_.ColRange(3*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YC(propagate_buf_.ColRange(4*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YH(propagate_buf_.ColRange(5*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YM(propagate_buf_.ColRange(6*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> YR(propagate_buf_.ColRange(7*ncell_, nrecur_));
     // disassemble backpropagate buffer into different neurons,
     const CuSubMatrix<BaseFloat> DG(backpropagate_buf_.ColRange(0*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DI(backpropagate_buf_.ColRange(1*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DF(backpropagate_buf_.ColRange(2*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DO(backpropagate_buf_.ColRange(3*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DC(backpropagate_buf_.ColRange(4*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DH(backpropagate_buf_.ColRange(5*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DM(backpropagate_buf_.ColRange(6*ncell_, ncell_));
     const CuSubMatrix<BaseFloat> DR(backpropagate_buf_.ColRange(7*ncell_, nrecur_));
     return std::string("  ") +
       "\n  Gradients:" +
       "\n  w_gifo_x_corr_  "   + MomentStatistics(w_gifo_x_corr_) +
       "\n  w_gifo_r_corr_  "   + MomentStatistics(w_gifo_r_corr_) +
       "\n  bias_corr_  "     + MomentStatistics(bias_corr_) +
       "\n  peephole_i_c_corr_  " + MomentStatistics(peephole_i_c_corr_) +
       "\n  peephole_f_c_corr_  " + MomentStatistics(peephole_f_c_corr_) +
       "\n  peephole_o_c_corr_  " + MomentStatistics(peephole_o_c_corr_) +
       "\n  w_r_m_corr_  "    + MomentStatistics(w_r_m_corr_) +
       "\n  Forward-pass:" +
       "\n  YG  " + MomentStatistics(YG) +
       "\n  YI  " + MomentStatistics(YI) +
       "\n  YF  " + MomentStatistics(YF) +
       "\n  YC  " + MomentStatistics(YC) +
       "\n  YH  " + MomentStatistics(YH) +
       "\n  YO  " + MomentStatistics(YO) +
       "\n  YM  " + MomentStatistics(YM) +
       "\n  YR  " + MomentStatistics(YR) +
       "\n  Backward-pass:" +
       "\n  DG  " + MomentStatistics(DG) +
       "\n  DI  " + MomentStatistics(DI) +
       "\n  DF  " + MomentStatistics(DF) +
       "\n  DC  " + MomentStatistics(DC) +
       "\n  DH  " + MomentStatistics(DH) +
       "\n  DO  " + MomentStatistics(DO) +
       "\n  DM  " + MomentStatistics(DM) +
       "\n  DR  " + MomentStatistics(DR);
   }
void InitData (std::istream & is) inline virtual
Initialize internal data of a component.
Implements UpdatableComponent.
Definition at line 76 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::bias_, LstmProjectedStreams::bias_corr_, LstmProjectedStreams::clip_gradient_, LstmProjectedStreams::InitMatParam(), LstmProjectedStreams::InitVecParam(), Component::input_dim_, KALDI_ASSERT, KALDI_ERR, kaldi::kSetZero, kaldi::kUndefined, LstmProjectedStreams::ncell_, LstmProjectedStreams::nrecur_, LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_f_c_corr_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_i_c_corr_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::peephole_o_c_corr_, kaldi::ReadBasicType(), kaldi::ReadToken(), CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_r_corr_, LstmProjectedStreams::w_gifo_x_, LstmProjectedStreams::w_gifo_x_corr_, LstmProjectedStreams::w_r_m_, and LstmProjectedStreams::w_r_m_corr_.
{
     // define options
     float param_scale = 0.02;
     // parse config
     std::string token;
     while (!is.eof()) {
       ReadToken(is, false, &token);
       if (token == "<CellDim>")
         ReadBasicType(is, false, &ncell_);
       else if (token == "<ClipGradient>")
         ReadBasicType(is, false, &clip_gradient_);
       //else if (token == "<DropoutRate>")
       //  ReadBasicType(is, false, &dropout_rate_);
       else if (token == "<ParamScale>")
         ReadBasicType(is, false, &param_scale);
       else KALDI_ERR << "Unknown token " << token << ", a typo in config?"
                << " (CellDim|ClipGradient|ParamScale)";
                //<< " (CellDim|ClipGradient|DropoutRate|ParamScale)";
       is >> std::ws;
     }
     // init weight and bias (Uniform)
     w_gifo_x_.Resize(4*ncell_, input_dim_, kUndefined);
     w_gifo_r_.Resize(4*ncell_, nrecur_, kUndefined);
     w_r_m_.Resize(nrecur_, ncell_, kUndefined);
     InitMatParam(w_gifo_x_, param_scale);
     InitMatParam(w_gifo_r_, param_scale);
     InitMatParam(w_r_m_, param_scale);
     bias_.Resize(4*ncell_, kUndefined);
     peephole_i_c_.Resize(ncell_, kUndefined);
     peephole_f_c_.Resize(ncell_, kUndefined);
     peephole_o_c_.Resize(ncell_, kUndefined);
     InitVecParam(bias_, param_scale);
     InitVecParam(peephole_i_c_, param_scale);
     InitVecParam(peephole_f_c_, param_scale);
     InitVecParam(peephole_o_c_, param_scale);
     // init delta buffers
     w_gifo_x_corr_.Resize(4*ncell_, input_dim_, kSetZero);
     w_gifo_r_corr_.Resize(4*ncell_, nrecur_, kSetZero);
     bias_corr_.Resize(4*ncell_, kSetZero);
     peephole_i_c_corr_.Resize(ncell_, kSetZero);
     peephole_f_c_corr_.Resize(ncell_, kSetZero);
     peephole_o_c_corr_.Resize(ncell_, kSetZero);
     w_r_m_corr_.Resize(nrecur_, ncell_, kSetZero);
     KALDI_ASSERT(clip_gradient_ >= 0.0);
   }
static void InitMatParam (CuMatrix< BaseFloat > & m, float scale) inline static
Definition at line 62 of file nnet-lstm-projected-streams.h.
References CuMatrixBase< Real >::Add(), CuMatrixBase< Real >::Scale(), and CuMatrixBase< Real >::SetRandUniform().
Referenced by LstmProjectedStreams::InitData().
{
     m.SetRandUniform();  // uniform in [0, 1]
     m.Add(-0.5);         // uniform in [-0.5, 0.5]
     m.Scale(2 * scale);  // uniform in [-scale, +scale]
   }
static void InitVecParam (CuVector< BaseFloat > & v, float scale) inline static
Definition at line 68 of file nnet-lstm-projected-streams.h.
References CuVectorBase< Real >::Dim(), rnnlm::i, and kaldi::RandUniform().
Referenced by LstmProjectedStreams::InitData().
{
     Vector<BaseFloat> tmp(v.Dim());
     for (int i=0; i < tmp.Dim(); i++) {
       tmp(i) = (RandUniform() - 0.5) * 2 * scale;
     }
     v = tmp;
   }
int32 NumParams () const inline virtual
Number of trainable parameters.
Implements UpdatableComponent.
Definition at line 179 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::bias_, CuVectorBase< Real >::Dim(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_x_, and LstmProjectedStreams::w_r_m_.
Referenced by LstmProjectedStreams::GetParams().
{
     return ( w_gifo_x_.NumRows() * w_gifo_x_.NumCols() +
          w_gifo_r_.NumRows() * w_gifo_r_.NumCols() +
          bias_.Dim() +
          peephole_i_c_.Dim() +
          peephole_f_c_.Dim() +
          peephole_o_c_.Dim() +
          w_r_m_.NumRows() * w_r_m_.NumCols() );
   }
void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) inline virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implements Component.
Definition at line 296 of file nnet-lstm-projected-streams.h.
References CuMatrixBase< Real >::AddMatMat(), LstmProjectedStreams::bias_, CuMatrixBase< Real >::ColRange(), CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, KALDI_LOG, kaldi::kNoTrans, kaldi::kSetZero, kaldi::kTrans, LstmProjectedStreams::ncell_, LstmProjectedStreams::nrecur_, LstmProjectedStreams::nstream_, CuMatrixBase< Real >::NumRows(), LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::prev_nnet_state_, LstmProjectedStreams::propagate_buf_, CuMatrix< Real >::Resize(), CuMatrixBase< Real >::RowRange(), CuMatrixBase< Real >::SetZero(), LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_x_, and LstmProjectedStreams::w_r_m_.
{
     int DEBUG = 0;
     static bool do_stream_reset = false;
     if (nstream_ == 0) {
       do_stream_reset = true;
       nstream_ = 1; // Karel: we are in nnet-forward, so 1 stream,
       prev_nnet_state_.Resize(nstream_, 7*ncell_ + 1*nrecur_, kSetZero);
       KALDI_LOG << "Running nnet-forward with per-utterance LSTM-state reset";
     }
     if (do_stream_reset) prev_nnet_state_.SetZero();
     KALDI_ASSERT(nstream_ > 0);
     KALDI_ASSERT(in.NumRows() % nstream_ == 0);
     int32 T = in.NumRows() / nstream_;
     int32 S = nstream_;
     // 0:forward pass history, [1, T]:current sequence, T+1:dummy
     propagate_buf_.Resize((T+2)*S, 7 * ncell_ + nrecur_, kSetZero);
     propagate_buf_.RowRange(0*S,S).CopyFromMat(prev_nnet_state_);
     // disassemble entire neuron activation buffer into different neurons
     CuSubMatrix<BaseFloat> YG(propagate_buf_.ColRange(0*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YI(propagate_buf_.ColRange(1*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YF(propagate_buf_.ColRange(2*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YO(propagate_buf_.ColRange(3*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YC(propagate_buf_.ColRange(4*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YH(propagate_buf_.ColRange(5*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YM(propagate_buf_.ColRange(6*ncell_, ncell_));
     CuSubMatrix<BaseFloat> YR(propagate_buf_.ColRange(7*ncell_, nrecur_));
     CuSubMatrix<BaseFloat> YGIFO(propagate_buf_.ColRange(0, 4*ncell_));
     // x -> g, i, f, o, not recurrent, do it all in once
     YGIFO.RowRange(1*S,T*S).AddMatMat(1.0, in, kNoTrans, w_gifo_x_, kTrans, 0.0);
     //if (dropout_rate_ != 0.0) {
     //  dropout_mask_.Resize(in.NumRows(), 4*ncell_, kUndefined);
     //  dropout_mask_.SetRandUniform();   // [0,1]
     //  dropout_mask_.Add(-dropout_rate_);  // [-dropout_rate, 1-dropout_rate_],
     //  dropout_mask_.ApplyHeaviside();   // -tive -> 0.0, +tive -> 1.0
     //  YGIFO.RowRange(1*S,T*S).MulElements(dropout_mask_);
     //}
     // bias -> g, i, f, o
     YGIFO.RowRange(1*S,T*S).AddVecToRows(1.0, bias_);
     for (int t = 1; t <= T; t++) {
       // multistream buffers for current time-step
       CuSubMatrix<BaseFloat> y_g(YG.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_i(YI.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_f(YF.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_o(YO.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_c(YC.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_h(YH.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_m(YM.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_r(YR.RowRange(t*S,S));
       CuSubMatrix<BaseFloat> y_gifo(YGIFO.RowRange(t*S,S));
       // r(t-1) -> g, i, f, o
       y_gifo.AddMatMat(1.0, YR.RowRange((t-1)*S,S), kNoTrans, w_gifo_r_, kTrans,  1.0);
       // c(t-1) -> i(t) via peephole
       y_i.AddMatDiagVec(1.0, YC.RowRange((t-1)*S,S), kNoTrans, peephole_i_c_, 1.0);
       // c(t-1) -> f(t) via peephole
       y_f.AddMatDiagVec(1.0, YC.RowRange((t-1)*S,S), kNoTrans, peephole_f_c_, 1.0);
       // i, f sigmoid squashing
       y_i.Sigmoid(y_i);
       y_f.Sigmoid(y_f);
       // g tanh squashing
       y_g.Tanh(y_g);
       // g -> c
       y_c.AddMatMatElements(1.0, y_g, y_i, 0.0);
       // c(t-1) -> c(t) via forget-gate
       y_c.AddMatMatElements(1.0, YC.RowRange((t-1)*S,S), y_f, 1.0);
       y_c.ApplyFloor(-50);   // optional clipping of cell activation
       y_c.ApplyCeiling(50);  // google paper Interspeech2014: LSTM for LVCSR
       // h tanh squashing
       y_h.Tanh(y_c);
       // c(t) -> o(t) via peephole (non-recurrent) & o squashing
       y_o.AddMatDiagVec(1.0, y_c, kNoTrans, peephole_o_c_, 1.0);
       // o sigmoid squashing
       y_o.Sigmoid(y_o);
       // h -> m via output gate
       y_m.AddMatMatElements(1.0, y_h, y_o, 0.0);
       // m -> r
       y_r.AddMatMat(1.0, y_m, kNoTrans, w_r_m_, kTrans, 0.0);
       if (DEBUG) {
         std::cerr << "forward-pass frame " << t << "\n";
         std::cerr << "activation of g: " << y_g;
         std::cerr << "activation of i: " << y_i;
         std::cerr << "activation of f: " << y_f;
         std::cerr << "activation of o: " << y_o;
         std::cerr << "activation of c: " << y_c;
         std::cerr << "activation of h: " << y_h;
         std::cerr << "activation of m: " << y_m;
         std::cerr << "activation of r: " << y_r;
       }
     }
     // recurrent projection layer is also feed-forward as LSTM output
     out->CopyFromMat(YR.RowRange(1*S,T*S));
     // now the last frame state becomes previous network state for next batch
     prev_nnet_state_.CopyFromMat(propagate_buf_.RowRange(T*S,S));
   }
void ReadData (std::istream & is, bool binary) inline virtual
Reads the component content.
Reimplemented from Component.
Definition at line 130 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::bias_, LstmProjectedStreams::bias_corr_, LstmProjectedStreams::clip_gradient_, kaldi::ExpectToken(), Component::input_dim_, kaldi::kSetZero, LstmProjectedStreams::ncell_, LstmProjectedStreams::nrecur_, LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_f_c_corr_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_i_c_corr_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::peephole_o_c_corr_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), kaldi::ReadBasicType(), CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_r_corr_, LstmProjectedStreams::w_gifo_x_, LstmProjectedStreams::w_gifo_x_corr_, LstmProjectedStreams::w_r_m_, and LstmProjectedStreams::w_r_m_corr_.
{
     ExpectToken(is, binary, "<CellDim>");
     ReadBasicType(is, binary, &ncell_);
     ExpectToken(is, binary, "<ClipGradient>");
     ReadBasicType(is, binary, &clip_gradient_);
     //ExpectToken(is, binary, "<DropoutRate>");
     //ReadBasicType(is, binary, &dropout_rate_);
     w_gifo_x_.Read(is, binary);
     w_gifo_r_.Read(is, binary);
     bias_.Read(is, binary);
     peephole_i_c_.Read(is, binary);
     peephole_f_c_.Read(is, binary);
     peephole_o_c_.Read(is, binary);
     w_r_m_.Read(is, binary);
     // init delta buffers
     w_gifo_x_corr_.Resize(4*ncell_, input_dim_, kSetZero);
     w_gifo_r_corr_.Resize(4*ncell_, nrecur_, kSetZero);
     bias_corr_.Resize(4*ncell_, kSetZero);
     peephole_i_c_corr_.Resize(ncell_, kSetZero);
     peephole_f_c_corr_.Resize(ncell_, kSetZero);
     peephole_o_c_corr_.Resize(ncell_, kSetZero);
     w_r_m_corr_.Resize(nrecur_, ncell_, kSetZero);
   }
void ResetLstmStreams (const std::vector< int32 > & stream_reset_flag) inline
Definition at line 279 of file nnet-lstm-projected-streams.h.
References KALDI_ASSERT, KALDI_LOG, kaldi::kSetZero, LstmProjectedStreams::ncell_, LstmProjectedStreams::nrecur_, LstmProjectedStreams::nstream_, CuMatrixBase< Real >::NumRows(), LstmProjectedStreams::prev_nnet_state_, CuMatrix< Real >::Resize(), and CuMatrixBase< Real >::Row().
Referenced by Nnet::ResetLstmStreams().
{
     // allocate prev_nnet_state_ if not done yet,
     if (nstream_ == 0) {
       // Karel: we just got number of streams! (before the 1st batch comes)
       nstream_ = stream_reset_flag.size();
       prev_nnet_state_.Resize(nstream_, 7*ncell_ + 1*nrecur_, kSetZero);
       KALDI_LOG << "Running training with " << nstream_ << " streams.";
     }
     // reset flag: 1 - reset stream network state
     KALDI_ASSERT(prev_nnet_state_.NumRows() == stream_reset_flag.size());
     for (int s = 0; s < stream_reset_flag.size(); s++) {
       if (stream_reset_flag[s] == 1) {
         prev_nnet_state_.Row(s).SetZero();
       }
     }
   }
void Update (const CuMatrixBase< BaseFloat > & input, const CuMatrixBase< BaseFloat > & diff) inline virtual
Compute gradient and update parameters.
Implements UpdatableComponent.
Definition at line 602 of file nnet-lstm-projected-streams.h.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), LstmProjectedStreams::bias_, LstmProjectedStreams::bias_corr_, NnetTrainOptions::learn_rate, UpdatableComponent::opts_, LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_f_c_corr_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_i_c_corr_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::peephole_o_c_corr_, LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_r_corr_, LstmProjectedStreams::w_gifo_x_, LstmProjectedStreams::w_gifo_x_corr_, LstmProjectedStreams::w_r_m_, and LstmProjectedStreams::w_r_m_corr_.
{
     const BaseFloat lr  = opts_.learn_rate;
     w_gifo_x_.AddMat(-lr, w_gifo_x_corr_);
     w_gifo_r_.AddMat(-lr, w_gifo_r_corr_);
     bias_.AddVec(-lr, bias_corr_, 1.0);
     peephole_i_c_.AddVec(-lr, peephole_i_c_corr_, 1.0);
     peephole_f_c_.AddVec(-lr, peephole_f_c_corr_, 1.0);
     peephole_o_c_.AddVec(-lr, peephole_o_c_corr_, 1.0);
     w_r_m_.AddMat(-lr, w_r_m_corr_);
 //    /*
 //      Here we deal with the famous "vanishing & exploding difficulties" in RNN learning.
 //
 //      *For gradients vanishing*
 //      LSTM architecture introduces linear CEC as the "error bridge" across long time distance
 //      solving vanishing problem.
 //
 //      *For gradients exploding*
 //      LSTM is still vulnerable to gradients explosing in BPTT(with large weight & deep time expension).
 //      To prevent this, we tried L2 regularization, which didn't work well
 //
 //      Our approach is a *modified* version of Max Norm Regularization:
 //      For each nonlinear neuron,
 //      1. fan-in weights & bias model a seperation hyper-plane: W x + b = 0
 //      2. squashing function models a differentiable nonlinear slope around this hyper-plane.
 //
 //      Conventional max norm regularization scale W to keep its L2 norm bounded,
 //      As a modification, we scale down large (W & b) *simultaneously*, this:
 //      1. keeps all fan-in weights small, prevents gradients from exploding during backward-pass.
 //      2. keeps the location of the hyper-plane unchanged, so we don't wipe out already learned knowledge.
 //      3. shrinks the "normal" of the hyper-plane, smooths the nonlinear slope, improves generalization.
 //      4. makes the network *well-conditioned* (weights are constrained in a reasonible range).
 //
 //      We've observed faster convergence and performance gain by doing this.
 //    */
 //
 //    int DEBUG = 0;
 //    BaseFloat max_norm = 1.0;   // weights with large L2 norm may cause exploding in deep BPTT expensions
 //                  // TODO: move this config to opts_
 //    CuMatrix<BaseFloat> L2_gifo_x(w_gifo_x_);
 //    CuMatrix<BaseFloat> L2_gifo_r(w_gifo_r_);
 //    L2_gifo_x.MulElements(w_gifo_x_);
 //    L2_gifo_r.MulElements(w_gifo_r_);
 //
 //    CuVector<BaseFloat> L2_norm_gifo(L2_gifo_x.NumRows());
 //    L2_norm_gifo.AddColSumMat(1.0, L2_gifo_x, 0.0);
 //    L2_norm_gifo.AddColSumMat(1.0, L2_gifo_r, 1.0);
 //    L2_norm_gifo.Range(1*ncell_, ncell_).AddVecVec(1.0, peephole_i_c_, peephole_i_c_, 1.0);
 //    L2_norm_gifo.Range(2*ncell_, ncell_).AddVecVec(1.0, peephole_f_c_, peephole_f_c_, 1.0);
 //    L2_norm_gifo.Range(3*ncell_, ncell_).AddVecVec(1.0, peephole_o_c_, peephole_o_c_, 1.0);
 //    L2_norm_gifo.ApplyPow(0.5);
 //
 //    CuVector<BaseFloat> shrink(L2_norm_gifo);
 //    shrink.Scale(1.0/max_norm);
 //    shrink.ApplyFloor(1.0);
 //    shrink.InvertElements();
 //
 //    w_gifo_x_.MulRowsVec(shrink);
 //    w_gifo_r_.MulRowsVec(shrink);
 //    bias_.MulElements(shrink);
 //
 //    peephole_i_c_.MulElements(shrink.Range(1*ncell_, ncell_));
 //    peephole_f_c_.MulElements(shrink.Range(2*ncell_, ncell_));
 //    peephole_o_c_.MulElements(shrink.Range(3*ncell_, ncell_));
 //
 //    if (DEBUG) {
 //      if (shrink.Min() < 0.95) {   // we dont want too many trivial logs here
 //        std::cerr << "gifo shrinking coefs: " << shrink;
 //      }
 //    }
 //
   }
void WriteData (std::ostream & os, bool binary) const inline virtual
Writes the component content.
Reimplemented from Component.
Definition at line 160 of file nnet-lstm-projected-streams.h.
References LstmProjectedStreams::bias_, LstmProjectedStreams::clip_gradient_, LstmProjectedStreams::ncell_, LstmProjectedStreams::peephole_f_c_, LstmProjectedStreams::peephole_i_c_, LstmProjectedStreams::peephole_o_c_, LstmProjectedStreams::w_gifo_r_, LstmProjectedStreams::w_gifo_x_, LstmProjectedStreams::w_r_m_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
     WriteToken(os, binary, "<CellDim>");
     WriteBasicType(os, binary, ncell_);
     WriteToken(os, binary, "<ClipGradient>");
     WriteBasicType(os, binary, clip_gradient_);
     //WriteToken(os, binary, "<DropoutRate>");
     //WriteBasicType(os, binary, dropout_rate_);
     w_gifo_x_.Write(os, binary);
     w_gifo_r_.Write(os, binary);
     bias_.Write(os, binary);
     peephole_i_c_.Write(os, binary);
     peephole_f_c_.Write(os, binary);
     peephole_o_c_.Write(os, binary);
     w_r_m_.Write(os, binary);
   }
Member Data Documentation
CuMatrix<BaseFloat> backpropagate_buf_ private
Definition at line 723 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), and LstmProjectedStreams::InfoGradient().
CuVector<BaseFloat> bias_ private
Definition at line 702 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuVector<BaseFloat> bias_corr_ private
Definition at line 703 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
BaseFloat clip_gradient_ private
Definition at line 687 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::WriteData().
int32 ncell_ private
Definition at line 680 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::ResetLstmStreams(), and LstmProjectedStreams::WriteData().
int32 nrecur_ private
recurrent projection layer dim
Definition at line 681 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::ResetLstmStreams().
int32 nstream_ private
Definition at line 682 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::PropagateFnc(), and LstmProjectedStreams::ResetLstmStreams().
CuVector<BaseFloat> peephole_f_c_ private
Definition at line 708 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuVector<BaseFloat> peephole_f_c_corr_ private
Definition at line 712 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
CuVector<BaseFloat> peephole_i_c_ private
Definition at line 707 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuVector<BaseFloat> peephole_i_c_corr_ private
Definition at line 711 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
CuVector<BaseFloat> peephole_o_c_ private
Definition at line 709 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuVector<BaseFloat> peephole_o_c_corr_ private
Definition at line 713 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
CuMatrix<BaseFloat> prev_nnet_state_ private
Definition at line 684 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::PropagateFnc(), and LstmProjectedStreams::ResetLstmStreams().
CuMatrix<BaseFloat> propagate_buf_ private
Definition at line 720 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), and LstmProjectedStreams::PropagateFnc().
CuMatrix<BaseFloat> w_gifo_r_ private
Definition at line 698 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuMatrix<BaseFloat> w_gifo_r_corr_ private
Definition at line 699 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
CuMatrix<BaseFloat> w_gifo_x_ private
Definition at line 694 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuMatrix<BaseFloat> w_gifo_x_corr_ private
Definition at line 695 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
CuMatrix<BaseFloat> w_r_m_ private
Definition at line 716 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::GetParams(), LstmProjectedStreams::Info(), LstmProjectedStreams::InitData(), LstmProjectedStreams::NumParams(), LstmProjectedStreams::PropagateFnc(), LstmProjectedStreams::ReadData(), LstmProjectedStreams::Update(), and LstmProjectedStreams::WriteData().
CuMatrix<BaseFloat> w_r_m_corr_ private
Definition at line 717 of file nnet-lstm-projected-streams.h.
Referenced by LstmProjectedStreams::BackpropagateFnc(), LstmProjectedStreams::InfoGradient(), LstmProjectedStreams::InitData(), LstmProjectedStreams::ReadData(), and LstmProjectedStreams::Update().
The documentation for this class was generated from the following file:
nnet/nnet-lstm-projected-streams.h