Kaldi: TableWriterArchiveImpl< Holder > Class Template Reference
TableWriterArchiveImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from TableWriterImplBase< Holder >
typedef Holder::T T
Public Member Functions
virtual bool Open (const std::string &wspecifier)
virtual bool IsOpen () const
virtual bool Write (const std::string &key, const T &value)
virtual void Flush ()
virtual bool Close ()
TableWriterArchiveImpl ()
virtual ~TableWriterArchiveImpl ()
Public Member Functions inherited from TableWriterImplBase< Holder >
virtual ~TableWriterImplBase ()
TableWriterImplBase ()
Private Types
enum { kUninitialized, kOpen, kWriteError }
Private Attributes
Output output_
WspecifierOptions opts_
std::string wspecifier_
std::string archive_wxfilename_
enum
kaldi::TableWriterArchiveImpl:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::TableWriterArchiveImpl< Holder >
Definition at line 661 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef Holder::T T
Definition at line 663 of file kaldi-table-inl.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kUninitialized
kOpen
kWriteError
Definition at line 786 of file kaldi-table-inl.h.
        {               // is stream open?
     kUninitialized,    // no
     kOpen,             // yes
     kWriteError,       // yes
   } state_;
Constructor & Destructor Documentation
TableWriterArchiveImpl () inline
Definition at line 771 of file kaldi-table-inl.h.
 : state_(kUninitialized) {}
virtual ~TableWriterArchiveImpl () inline virtual
Definition at line 774 of file kaldi-table-inl.h.
References TableWriterArchiveImpl< Holder >::Close(), TableWriterArchiveImpl< Holder >::IsOpen(), KALDI_ERR, and TableWriterArchiveImpl< Holder >::wspecifier_.
{
     if (!IsOpen()) return;
     else if (!Close())
       KALDI_ERR << "At TableWriter destructor: Write failed or stream close "
                 << "failed: wspecifier is "<<  wspecifier_;
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 750 of file kaldi-table-inl.h.
References Output::Close(), Output::IsOpen(), TableWriterArchiveImpl< Holder >::IsOpen(), KALDI_ERR, KALDI_WARN, TableWriterArchiveImpl< Holder >::kUninitialized, TableWriterArchiveImpl< Holder >::kWriteError, TableWriterArchiveImpl< Holder >::output_, TableWriterArchiveImpl< Holder >::state_, and TableWriterArchiveImpl< Holder >::wspecifier_.
Referenced by TableWriterArchiveImpl< Holder >::Open(), and TableWriterArchiveImpl< Holder >::~TableWriterArchiveImpl().
{
     if (!this->IsOpen() || !output_.IsOpen())
       KALDI_ERR << "TableWriter: Close called on a stream that was not open."
                 << this->IsOpen() << ", " << output_.IsOpen();
     bool close_success = output_.Close();
     if (!close_success) {
       KALDI_WARN << "TableWriter: error closing stream: wspecifier is "
                  << wspecifier_;
       state_ = kUninitialized;
       return false;
     }
     if (state_ == kWriteError) {
       KALDI_WARN << "TableWriter: closing writer in error state: wspecifier is "
                  << wspecifier_;
       state_ = kUninitialized;
       return false;
     }
     state_ = kUninitialized;
     return true;
   }
virtual void Flush () inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 740 of file kaldi-table-inl.h.
References KALDI_WARN, TableWriterArchiveImpl< Holder >::kOpen, TableWriterArchiveImpl< Holder >::kWriteError, TableWriterArchiveImpl< Holder >::output_, TableWriterArchiveImpl< Holder >::state_, and Output::Stream().
Referenced by TableWriterArchiveImpl< Holder >::Write().
{
     switch (state_) {
       case kWriteError: case kOpen:
         output_.Stream().flush();  // Don't check error status.
         return;
       default:
         KALDI_WARN << "TableWriter: Flush called on not-open writer.";
     }
   }
virtual bool IsOpen () const inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 697 of file kaldi-table-inl.h.
References KALDI_ERR, TableWriterArchiveImpl< Holder >::kOpen, TableWriterArchiveImpl< Holder >::kUninitialized, TableWriterArchiveImpl< Holder >::kWriteError, and TableWriterArchiveImpl< Holder >::state_.
Referenced by TableWriterArchiveImpl< Holder >::Close(), and TableWriterArchiveImpl< Holder >::~TableWriterArchiveImpl().
{
     switch (state_) {
       case kUninitialized: return false;
       case kOpen: case kWriteError: return true;
       default: KALDI_ERR << "IsOpen() called on TableWriter in invalid state.";
     }
     return false;
   }
virtual bool Open (const std::string & wspecifier) inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 665 of file kaldi-table-inl.h.
References TableWriterArchiveImpl< Holder >::archive_wxfilename_, WspecifierOptions::binary, kaldi::ClassifyWspecifier(), TableWriterArchiveImpl< Holder >::Close(), KALDI_ASSERT, KALDI_ERR, kaldi::kArchiveWspecifier, TableWriterArchiveImpl< Holder >::kOpen, TableWriterArchiveImpl< Holder >::kUninitialized, TableWriterArchiveImpl< Holder >::kWriteError, Output::Open(), TableWriterArchiveImpl< Holder >::opts_, TableWriterArchiveImpl< Holder >::output_, TableWriterArchiveImpl< Holder >::state_, and TableWriterArchiveImpl< Holder >::wspecifier_.
{
     switch (state_) {
       case kUninitialized:
         break;
       case kWriteError:
         KALDI_ERR << "TableWriter: opening stream, already open with write"
                      " error.";
       case kOpen: default:
         if (!Close())  // throw because this error may not have been previously
           // detected by the user.
           KALDI_ERR << "TableWriter: opening stream, error closing previously"
                        " open stream.";
     }
     wspecifier_ = wspecifier;
     WspecifierType ws = ClassifyWspecifier(wspecifier,
                                            &archive_wxfilename_,
                                            NULL,
                                            &opts_);
     KALDI_ASSERT(ws == kArchiveWspecifier);  // or wrongly called.
     if (output_.Open(archive_wxfilename_, opts_.binary, false)) {  // false
                                                       // means no binary header.
       state_ = kOpen;
       return true;
     } else {
       // stream will not be open.  User will report this error
       // (we return bool), so don't bother printing anything.
       state_ = kUninitialized;
       return false;
     }
   }
virtual bool Write (const std::string & key, const T & value) inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 708 of file kaldi-table-inl.h.
References TableWriterArchiveImpl< Holder >::archive_wxfilename_, WspecifierOptions::binary, WspecifierOptions::flush, TableWriterArchiveImpl< Holder >::Flush(), kaldi::IsToken(), KALDI_ERR, KALDI_WARN, TableWriterArchiveImpl< Holder >::kOpen, TableWriterArchiveImpl< Holder >::kUninitialized, TableWriterArchiveImpl< Holder >::kWriteError, TableWriterArchiveImpl< Holder >::opts_, TableWriterArchiveImpl< Holder >::output_, kaldi::PrintableWxfilename(), TableWriterArchiveImpl< Holder >::state_, and Output::Stream().
{
     switch (state_) {
       case kOpen: break;
       case kWriteError:
         // user should have known from the last
         // call to Write that there was a problem.
         KALDI_WARN << "TableWriter: attempting to write to invalid stream.";
         return false;
       case kUninitialized: default:
         KALDI_ERR << "TableWriter: Write called on invalid stream";
     }
     // state is now kOpen or kWriteError.
     if (!IsToken(key))  // e.g. empty string or has spaces...
       KALDI_ERR << "TableWriter: using invalid key " << key;
     output_.Stream() << key << ' ';
     if (!Holder::Write(output_.Stream(), opts_.binary, value)) {
       KALDI_WARN << "TableWriter: write failure to "
                  << PrintableWxfilename(archive_wxfilename_);
       state_ = kWriteError;
       return false;
     }
     if (state_ == kWriteError) return false;  // Even if this Write seems to
     // have succeeded, we fail because a previous Write failed and the archive
     // may be corrupted and unreadable.
     if (opts_.flush)
       Flush();
     return true;
   }
Member Data Documentation
std::string archive_wxfilename_ private
Definition at line 785 of file kaldi-table-inl.h.
Referenced by TableWriterArchiveImpl< Holder >::Open(), and TableWriterArchiveImpl< Holder >::Write().
WspecifierOptions opts_ private
Definition at line 783 of file kaldi-table-inl.h.
Referenced by TableWriterArchiveImpl< Holder >::Open(), and TableWriterArchiveImpl< Holder >::Write().
Output output_ private
Definition at line 782 of file kaldi-table-inl.h.
Referenced by TableWriterArchiveImpl< Holder >::Close(), TableWriterArchiveImpl< Holder >::Flush(), TableWriterArchiveImpl< Holder >::Open(), and TableWriterArchiveImpl< Holder >::Write().
enum { ... } state_
Referenced by TableWriterArchiveImpl< Holder >::Close(), TableWriterArchiveImpl< Holder >::Flush(), TableWriterArchiveImpl< Holder >::IsOpen(), TableWriterArchiveImpl< Holder >::Open(), and TableWriterArchiveImpl< Holder >::Write().
std::string wspecifier_ private
Definition at line 784 of file kaldi-table-inl.h.
Referenced by TableWriterArchiveImpl< Holder >::Close(), TableWriterArchiveImpl< Holder >::Open(), and TableWriterArchiveImpl< Holder >::~TableWriterArchiveImpl().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h