Kaldi: ChunkInfo Class Reference
ChunkInfo Class Reference
ChunkInfo is a class whose purpose is to describe the structure of matrices holding features.
#include <nnet-component.h>
Public Member Functions
ChunkInfo ()
ChunkInfo (int32 feat_dim, int32 num_chunks, int32 first_offset, int32 last_offset)
ChunkInfo (int32 feat_dim, int32 num_chunks, const std::vector< int32 > offsets)
int32 GetIndex (int32 offset) const
int32 GetOffset (int32 index) const
void MakeOffsetsContiguous ()
int32 ChunkSize () const
int32 NumChunks () const
int32 NumRows () const
Returns the number of rows that we expect the feature matrix to have.
int32 NumCols () const
Returns the number of columns that we expect the feature matrix to have.
void CheckSize (const CuMatrixBase< BaseFloat > &mat) const
Checks that the matrix has the size we expect, and die if not.
void Check () const
Checks that the data in the ChunkInfo is valid, and die if not.
Private Attributes
int32 feat_dim_
int32 num_chunks_
int32 first_offset_
int32 last_offset_
std::vector< int32 > offsets_
Detailed Description
ChunkInfo is a class whose purpose is to describe the structure of matrices holding features.
This is useful mostly in training time. The main reason why we have this is to support efficient training for networks which we have splicing components that splice in a non-contiguous way, e.g. frames -5, 0 and 5. We also have in mind future extensibility to convnets which might have similar issues. This class describes the structure of a minibatch of features, or of a single contiguous block of features. Examples are as follows, and offsets is empty if not mentioned: When decoding, at input to the network: feat_dim = 13, num_chunks = 1, first_offset = 0, last_offset = 691 and in the middle of the network (assuming splicing is +-7): feat_dim = 1024, num_chunks = 1, first_offset = 7, last_offset = 684 When training, at input to the network: feat_dim = 13, num_chunks = 512, first_offset = 0, last_offset= 14 and in the middle of the network: feat_dim = 1024, num_chunks = 512, first_offset = 7, last_offset = 7 The only situation where offsets would be nonempty would be if we do splicing with gaps in. E.g. suppose at network input we splice +-2 frames (contiguous) and somewhere in the middle we splice frames {-5, 0, 5}, then we would have the following while training At input to the network: feat_dim = 13, num_chunks = 512, first_offset = 0, last_offset = 14 After the first hidden layer: feat_dim = 1024, num_chunks = 512, first_offset = 2, last_offset = 12, offsets = {2, 10, 12} At the output of the last hidden layer (after the {-5, 0, 5} splice): feat_dim = 1024, num_chunks = 512, first_offset = 7, last_offset = 7 (the decoding setup would still look pretty normal, so we don't give an example).
Definition at line 72 of file nnet-component.h.
Constructor & Destructor Documentation
ChunkInfo () inline
Definition at line 74 of file nnet-component.h.
       : feat_dim_(0), num_chunks_(0),
         first_offset_(0), last_offset_(0),
         offsets_() { }
ChunkInfo (int32 feat_dim, int32 num_chunks, int32 first_offset, int32 last_offset) inline
Definition at line 79 of file nnet-component.h.
References ChunkInfo::Check().
       : feat_dim_(feat_dim), num_chunks_(num_chunks),
         first_offset_(first_offset), last_offset_(last_offset),
         offsets_() { Check(); }
ChunkInfo (int32 feat_dim, int32 num_chunks, const std::vector< int32 > offsets) inline
Definition at line 85 of file nnet-component.h.
References ChunkInfo::Check(), ChunkInfo::first_offset_, ChunkInfo::last_offset_, and ChunkInfo::offsets_.
       : feat_dim_(feat_dim), num_chunks_(num_chunks),
         first_offset_(offsets.front()), last_offset_(offsets.back()),
         offsets_(offsets) { if (last_offset_ - first_offset_ + 1 == offsets_.size())
                               offsets_.clear();
           Check(); }
Member Function Documentation
void Check () const
Checks that the data in the ChunkInfo is valid, and die if not.
Definition at line 2596 of file nnet-component.cc.
References ChunkInfo::feat_dim_, ChunkInfo::first_offset_, KALDI_ASSERT, ChunkInfo::last_offset_, ChunkInfo::num_chunks_, ChunkInfo::NumRows(), and ChunkInfo::offsets_.
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), ChunkInfo::ChunkInfo(), ChunkInfo::MakeOffsetsContiguous(), SpliceComponent::Propagate(), and SpliceMaxComponent::Propagate().
{
   // Checking sanity of the ChunkInfo object
   KALDI_ASSERT((feat_dim_ > 0) && (num_chunks_ > 0));
   if (! offsets_.empty()) {
     KALDI_ASSERT((first_offset_ == offsets_.front()) &&
                  (last_offset_ == offsets_.back()));
   } else  {
     KALDI_ASSERT((first_offset_ >= 0) && (last_offset_ >= first_offset_));
     // asserting the chunk is not contiguous, as offsets is not empty
     KALDI_ASSERT ( last_offset_ - first_offset_ + 1 > offsets_.size() );
   }
   KALDI_ASSERT(NumRows() % num_chunks_ == 0);
 }
void CheckSize (const CuMatrixBase< BaseFloat > & mat) const
Checks that the matrix has the size we expect, and die if not.
Definition at line 2612 of file nnet-component.cc.
References KALDI_ASSERT, ChunkInfo::NumCols(), CuMatrixBase< Real >::NumCols(), ChunkInfo::NumRows(), and CuMatrixBase< Real >::NumRows().
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), MaxoutComponent::Propagate(), MaxpoolingComponent::Propagate(), PnormComponent::Propagate(), SigmoidComponent::Propagate(), TanhComponent::Propagate(), PowerComponent::Propagate(), SoftHingeComponent::Propagate(), SoftmaxComponent::Propagate(), LogSoftmaxComponent::Propagate(), AffineComponent::Propagate(), SpliceComponent::Propagate(), SpliceMaxComponent::Propagate(), BlockAffineComponent::Propagate(), SumGroupComponent::Propagate(), PermuteComponent::Propagate(), DctComponent::Propagate(), FixedLinearComponent::Propagate(), FixedAffineComponent::Propagate(), DropoutComponent::Propagate(), and Convolutional1dComponent::Propagate().
{
   KALDI_ASSERT((mat.NumRows()  ==  NumRows()) && (mat.NumCols() == NumCols()));
 }
int32 ChunkSize () const inline
Definition at line 115 of file nnet-component.h.
References ChunkInfo::num_chunks_, and ChunkInfo::NumRows().
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), SpliceComponent::Propagate(), and SpliceMaxComponent::Propagate().
 { return NumRows() / num_chunks_; }
int32 GetIndex (int32 offset) const
Definition at line 2572 of file nnet-component.cc.
References ChunkInfo::first_offset_, KALDI_ASSERT, ChunkInfo::last_offset_, and ChunkInfo::offsets_.
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), SpliceComponent::Propagate(), and SpliceMaxComponent::Propagate().
{
   if (offsets_.empty()) {  // if data is contiguous
     KALDI_ASSERT((offset <= last_offset_) && (offset >= first_offset_));
     return offset - first_offset_;
   } else  {
     std::vector<int32>::const_iterator iter =
         std::lower_bound(offsets_.begin(), offsets_.end(), offset);
     // make sure offset is present in the vector
     KALDI_ASSERT(iter != offsets_.end() && *iter == offset);
     return static_cast<int32>(iter - offsets_.begin());
   }
 }
int32 GetOffset (int32 index) const
Definition at line 2585 of file nnet-component.cc.
References ChunkInfo::first_offset_, KALDI_ASSERT, ChunkInfo::last_offset_, and ChunkInfo::offsets_.
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), SpliceComponent::Propagate(), and SpliceMaxComponent::Propagate().
{
   if (offsets_.empty()) { // if data is contiguous
     int32 offset = index + first_offset_;  // just offset by the first_offset_
     KALDI_ASSERT((offset <= last_offset_) && (offset >= first_offset_));
     return offset;
   } else  {
     KALDI_ASSERT((index >= 0) && (index < offsets_.size()));
     return offsets_[index];
   }
 }
void MakeOffsetsContiguous () inline
Definition at line 111 of file nnet-component.h.
References ChunkInfo::Check(), and ChunkInfo::offsets_.
 { offsets_.clear(); Check(); }
int32 NumChunks () const inline
Definition at line 118 of file nnet-component.h.
References ChunkInfo::num_chunks_.
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), MaxoutComponent::Propagate(), MaxpoolingComponent::Propagate(), PnormComponent::Propagate(), SigmoidComponent::Propagate(), TanhComponent::Propagate(), PowerComponent::Propagate(), SoftHingeComponent::Propagate(), SoftmaxComponent::Propagate(), LogSoftmaxComponent::Propagate(), AffineComponent::Propagate(), SpliceComponent::Propagate(), SpliceMaxComponent::Propagate(), BlockAffineComponent::Propagate(), SumGroupComponent::Propagate(), PermuteComponent::Propagate(), FixedLinearComponent::Propagate(), FixedAffineComponent::Propagate(), DropoutComponent::Propagate(), and Convolutional1dComponent::Propagate().
 { return num_chunks_; }
int32 NumCols () const inline
Returns the number of columns that we expect the feature matrix to have.
Definition at line 126 of file nnet-component.h.
References ChunkInfo::feat_dim_.
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), ChunkInfo::CheckSize(), Component::Propagate(), SpliceComponent::Propagate(), SpliceMaxComponent::Propagate(), DctComponent::Propagate(), and kaldi::nnet2::UnitTestGenericComponentInternal().
 { return feat_dim_; }
int32 NumRows () const inline
Returns the number of rows that we expect the feature matrix to have.
Definition at line 121 of file nnet-component.h.
References ChunkInfo::first_offset_, ChunkInfo::last_offset_, ChunkInfo::num_chunks_, and ChunkInfo::offsets_.
Referenced by SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), ChunkInfo::Check(), ChunkInfo::CheckSize(), ChunkInfo::ChunkSize(), Component::Propagate(), DctComponent::Propagate(), and kaldi::nnet2::UnitTestGenericComponentInternal().
{
     return num_chunks_ * (!offsets_.empty() ? offsets_.size() :
                                          last_offset_ - first_offset_ + 1); }
Member Data Documentation
int32 feat_dim_ private
Definition at line 135 of file nnet-component.h.
Referenced by ChunkInfo::Check(), and ChunkInfo::NumCols().
int32 first_offset_ private
Definition at line 137 of file nnet-component.h.
Referenced by ChunkInfo::Check(), ChunkInfo::ChunkInfo(), ChunkInfo::GetIndex(), ChunkInfo::GetOffset(), and ChunkInfo::NumRows().
int32 last_offset_ private
Definition at line 140 of file nnet-component.h.
Referenced by ChunkInfo::Check(), ChunkInfo::ChunkInfo(), ChunkInfo::GetIndex(), ChunkInfo::GetOffset(), and ChunkInfo::NumRows().
int32 num_chunks_ private
Definition at line 136 of file nnet-component.h.
Referenced by ChunkInfo::Check(), ChunkInfo::ChunkSize(), ChunkInfo::NumChunks(), and ChunkInfo::NumRows().
std::vector<int32> offsets_ private
Definition at line 141 of file nnet-component.h.
Referenced by ChunkInfo::Check(), ChunkInfo::ChunkInfo(), ChunkInfo::GetIndex(), ChunkInfo::GetOffset(), ChunkInfo::MakeOffsetsContiguous(), and ChunkInfo::NumRows().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc