Kaldi: SgmmClusterable Class Reference
SgmmClusterable Class Reference
This header defines an object that can be used to create decision trees using a form of SGMM statistics.
#include <sgmm-clusterable.h>
Public Member Functions
SgmmClusterable (const AmSgmm &sgmm, const std::vector< SpMatrix< double > > &H)
virtual std::string Type () const
Return a string that describes the inherited type.
void Accumulate (const SgmmPerFrameDerivedVars &frame_vars, int32 j, BaseFloat weight)
compare with the Accumulate function of MleAmSgmmAccs Note: the pdf-index j, relating to the original SGMM in sgmm_, is only needed to select the right vector to compute Gaussian-level alignments with.
virtual BaseFloat Objf () const
Return the objective function associated with the stats [assuming ML estimation].
virtual void SetZero ()
Set stats to empty.
virtual void Add (const Clusterable &other_in)
Add other stats.
virtual void Sub (const Clusterable &other_in)
Subtract other stats.
virtual BaseFloat Normalizer () const
Return the normalizer (typically, count) associated with the stats.
virtual Clusterable * Copy () const
Return a copy of this object.
virtual void Scale (BaseFloat f)
Scale the stats by a positive number f [not mandatory to supply this].
virtual void Write (std::ostream &os, bool binary) const
Write data to stream.
virtual Clusterable * ReadNew (std::istream &is, bool binary) const
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
virtual ~SgmmClusterable ()
const Vector< double > & gamma () const
const Vector< double > & y () const
Public Member Functions inherited from Clusterable
virtual ~Clusterable ()
virtual BaseFloat ObjfPlus (const Clusterable &other) const
Return the objective function of the combined object this + other.
virtual BaseFloat ObjfMinus (const Clusterable &other) const
Return the objective function of the subtracted object this - other.
virtual BaseFloat Distance (const Clusterable &other) const
Return the objective function decrease from merging the two clusters, negated to be a positive number (or zero).
Private Member Functions
void ComputeH ()
Private Attributes
const AmSgmm & sgmm_
const std::vector< SpMatrix
< double > > & H_
Vector< double > gamma_
Vector< double > y_
SpMatrix< double > my_H_
Detailed Description
This header defines an object that can be used to create decision trees using a form of SGMM statistics.
It is analogous to the GaussClusterable object, but uses the SGMM. The auxiliary function it uses is related to the normal SGMM auxiliary function, but for efficiency it uses a simpler model on the weights, which is equivalent to assuming the weights w_{ji} [there no index m since we assume one mixture per state!] are directly estimated using ML, instead of being computed from v_j and w_i as in the actual SGMM.
Definition at line 41 of file sgmm-clusterable.h.
Constructor & Destructor Documentation
SgmmClusterable (const AmSgmm & sgmm, const std::vector< SpMatrix< double > > & H) inline
Definition at line 43 of file sgmm-clusterable.h.
Referenced by SgmmClusterable::Copy(), and SgmmClusterable::ReadNew().
                                                          : // H can be empty vector
       // at initialization.  Used to cache something from the model.
       sgmm_(sgmm),
       H_(H),
       gamma_(sgmm.NumGauss()),
       y_(sgmm.PhoneSpaceDim()) { }
virtual ~SgmmClusterable () inline virtual
Definition at line 69 of file sgmm-clusterable.h.
 {}
Member Function Documentation
void Accumulate (const SgmmPerFrameDerivedVars & frame_vars, int32 j, BaseFloat weight)
compare with the Accumulate function of MleAmSgmmAccs Note: the pdf-index j, relating to the original SGMM in sgmm_, is only needed to select the right vector to compute Gaussian-level alignments with.
Definition at line 26 of file sgmm-clusterable.cc.
References VectorBase< Real >::AddVec(), AmSgmm::ComponentPosteriors(), SgmmClusterable::gamma(), SgmmClusterable::gamma_, SgmmPerFrameDerivedVars::gselect, rnnlm::i, KALDI_ASSERT, SgmmClusterable::my_H_, MatrixBase< Real >::NumCols(), PackedMatrix< Real >::NumRows(), SpMatrix< Real >::Resize(), MatrixBase< Real >::Row(), MatrixBase< Real >::Scale(), SgmmClusterable::sgmm_, SgmmClusterable::y_, and SgmmPerFrameDerivedVars::zti.
                       {
   Matrix<BaseFloat> post;
   KALDI_ASSERT(weight >= 0.0); // Doesn't make sense to use negative weights here.
   // Compute Gaussian-level posteriors.
   // Note: "post" is indexed by Gaussian-selection index.
   sgmm_.ComponentPosteriors(per_frame_vars, j, &post);
   if (weight != 1.0) post.Scale(weight);
   const std::vector<int32> &gselect = per_frame_vars.gselect;
   for (int32 ki = 0; ki < gselect.size(); ki++) {
     int32 i = gselect[ki];
     BaseFloat gamma = 0.0;  // Sum the weight over all the vectors (index m) in
     // the state.  In sensible cases there should be just one vector per state
     // at the point where we do this, though.
     for (int32 m = 0; m < post.NumCols(); m++) gamma += post(ki, m);
     gamma_(i) += gamma;
     y_.AddVec(gamma, per_frame_vars.zti.Row(ki));
   }
   // Invalidate my_H_, if present, since it's not efficient to
   // keep it updated during accumulation.
   if (my_H_.NumRows() != 0)
     my_H_.Resize(0);
 }
void Add (const Clusterable & other) virtual
Add other stats.
Implements Clusterable.
Definition at line 129 of file sgmm-clusterable.cc.
References SpMatrix< Real >::AddSp(), VectorBase< Real >::AddVec(), SgmmClusterable::ComputeH(), SgmmClusterable::gamma_, SgmmClusterable::H_, SgmmClusterable::my_H_, PackedMatrix< Real >::NumRows(), SpMatrix< Real >::Resize(), and SgmmClusterable::y_.
{
   const SgmmClusterable *other =
       static_cast<const SgmmClusterable*>(&other_in);
   gamma_.AddVec(1.0, other->gamma_);
   y_.AddVec(1.0, other->y_);
   if (!H_.empty()) { // we need to compute my_H_.
     if (my_H_.NumRows() != 0 && other->my_H_.NumRows() != 0)
       my_H_.AddSp(1.0, other->my_H_);
     else {
       my_H_.Resize(0);
       ComputeH();
     }
   }
 }
void ComputeH () private
Definition at line 266 of file sgmm-clusterable.cc.
References SpMatrix< Real >::AddSp(), VectorBase< Real >::Dim(), SgmmClusterable::gamma(), SgmmClusterable::gamma_, SgmmClusterable::H_, rnnlm::i, KALDI_ASSERT, SgmmClusterable::my_H_, PackedMatrix< Real >::NumRows(), and SpMatrix< Real >::Resize().
Referenced by SgmmClusterable::Add(), SgmmClusterable::Copy(), SgmmClusterable::ReadNew(), and SgmmClusterable::Sub().
{
   // We're computing my_H_, as a weighted sum of H_, with gamma_ as the
   // weights.
   KALDI_ASSERT(!H_.empty() && my_H_.NumRows() == 0); // Invalid to call this if H_ empty,
   // or my_H_ already set up.
   my_H_.Resize(H_[0].NumRows()); // will initialize to zero.
   KALDI_ASSERT(static_cast<int32>(H_.size()) == gamma_.Dim());
   for (int32 i = 0; i < gamma_.Dim(); i++) {
     double gamma = gamma_(i);
     if (gamma > 0.0) my_H_.AddSp(gamma, H_[i]);
   }
 }
Clusterable * Copy () const virtual
Return a copy of this object.
Implements Clusterable.
Definition at line 163 of file sgmm-clusterable.cc.
References SgmmClusterable::ComputeH(), SpMatrix< Real >::CopyFromSp(), VectorBase< Real >::CopyFromVec(), SgmmClusterable::gamma_, SgmmClusterable::H_, SgmmClusterable::my_H_, PackedMatrix< Real >::NumRows(), SpMatrix< Real >::Resize(), SgmmClusterable::sgmm_, SgmmClusterable::SgmmClusterable(), and SgmmClusterable::y_.
Referenced by SgmmClusterable::Objf().
{
   SgmmClusterable *ans = new SgmmClusterable(sgmm_, H_);
   ans->gamma_.CopyFromVec(gamma_);
   ans->y_.CopyFromVec(y_);
   if (!H_.empty()) {
     if (my_H_.NumRows() == 0.0) ans->ComputeH();
     else {
       ans->my_H_.Resize(my_H_.NumRows());
       ans->my_H_.CopyFromSp(my_H_);
     }
   }
   return ans;
 }
const Vector<double>& gamma () const inline
Definition at line 71 of file sgmm-clusterable.h.
References SgmmClusterable::gamma_.
Referenced by SgmmClusterable::Accumulate(), SgmmClusterable::ComputeH(), and SgmmClusterable::Objf().
 { return gamma_; }
BaseFloat Normalizer () const virtual
Return the normalizer (typically, count) associated with the stats.
Implements Clusterable.
Definition at line 159 of file sgmm-clusterable.cc.
References SgmmClusterable::gamma_, and VectorBase< Real >::Sum().
{
   return gamma_.Sum();
 }
BaseFloat Objf () const virtual
Return the objective function associated with the stats [assuming ML estimation].
Implements Clusterable.
Definition at line 52 of file sgmm-clusterable.cc.
References VectorBase< Real >::AddTpVec(), TpMatrix< Real >::Cholesky(), SgmmClusterable::Copy(), VectorBase< Real >::Dim(), SgmmClusterable::gamma(), SgmmClusterable::gamma_, SgmmClusterable::H_, rnnlm::i, KALDI_ASSERT, KALDI_VLOG, kaldi::kNoTrans, kaldi::Log(), SgmmClusterable::my_H_, AmSgmm::NumGauss(), PackedMatrix< Real >::NumRows(), SgmmClusterable::Objf(), SgmmClusterable::sgmm_, kaldi::SolveQuadraticProblem(), VectorBase< Real >::Sum(), kaldi::VecVec(), and SgmmClusterable::y_.
Referenced by SgmmClusterable::Objf().
{
   // Objective function consists of the expected log-likelihood of
   // a weight (assuming we estimate the weights directly as parameters
   // instead of the whole subspace thing on the weights), plus
   // the auxiliary function improvement we would get from estimating
   // the state vector v_j starting from zero.  Note: zero is an
   // arbitrary starting point-- we could use any value as long as
   // we were consistent.
   KALDI_ASSERT(static_cast<int32>(H_.size()) == sgmm_.NumGauss());
   if (my_H_.NumRows() == 0.0) {
     SgmmClusterable *s = static_cast<SgmmClusterable*>(this->Copy()); // will
     // set up my_H_, which we need.
     BaseFloat ans = s->Objf();
     delete s;
     return ans;
   }
   double ans = 0.0;
   double tot_gamma = gamma_.Sum(), tot_gamma2 = 0.0;
   if (tot_gamma == 0.0) return 0.0;
   int32 I = gamma_.Dim();
   for (int32 i = 0; i < I; i++) {
     double gamma = gamma_(i);
     if (gamma > 0.0) { // Note: should not be negative-- if it is, due to
       double prob = gamma / tot_gamma;
       if (prob > 0.0) { // Note: prob could be zero due to underflow-- this
         // happened! [we can get tiny values due to floating-point roundoff
         // while subtracting clusterable objects].
         ans += gamma * Log(gamma / tot_gamma);
       }
     }
     tot_gamma2 += gamma;
   }
   if (tot_gamma2 == 0.0)
     return 0.0; // No positive elements... maybe small negative ones were from
   // round off.
   // objf improvement is y^T H^{-1} y.
   // We'll try to compute this using Cholesky, first, which is more
   // efficient; if this fails or appears to lead to big values,
   // we'll back off to a more efficient SVD-based implementation.
   try {
     TpMatrix<double> C(my_H_.NumRows());
     C.Cholesky(my_H_);
     C.Invert();
     for (int32 i = 0; i < C.NumRows(); i++)
       if (fabs(C(i, i)) > 100.0) {
         KALDI_VLOG(3) << "Condion-number probably bad: element is "
                       << C(i, i);
         throw std::runtime_error("Bad condition number"); // back off to SVD.
       }
     // Note: assuming things are well preconditioned, the elements
     // C(i,i) should be of the rough magnitude 1/sqrt(count).
     Vector<double> yC(C.NumRows());
     // Note: if we decompose H = C C^T, then the line below
     // does yC = C^{-1} y.  Note: we are computing the inner
     // product y^T H^{-1} y.  H^{-1} = C^{-T} C^{-1}, so
     // y^T H^{-1} y = y^T C^{-T} C^{-1} y = yC^T yC.
     yC.AddTpVec(1.0, C, kNoTrans, y_, 0.0);
     ans += 0.5 * VecVec(yC, yC);
   } catch (...) { // Choleksy threw, or we detected bad condition.
     // we'll do this using an SVD-based implementation that will
     // deal with non-invertible matrices.
     KALDI_VLOG(3) << "Backing off to SVD-based objective computation.";
     Vector<double> v(y_.Dim()); // Initialized automatically to zero.
     ans += SolveQuadraticProblem(my_H_, y_, SolverOptions(), &v); // The objective function
     // change from estimating this vector.
   }
   return ans;
 }
Clusterable * ReadNew (std::istream & os, bool binary) const virtual
Read data from a stream and return the corresponding object (const function; it's a class member because we need access to the vtable so generic code can read derived types).
Implements Clusterable.
Definition at line 189 of file sgmm-clusterable.cc.
References SgmmClusterable::ComputeH(), SgmmClusterable::gamma_, SgmmClusterable::H_, Vector< Real >::Read(), SgmmClusterable::sgmm_, SgmmClusterable::SgmmClusterable(), and SgmmClusterable::y_.
{
   SgmmClusterable *ans = new SgmmClusterable(sgmm_, H_);
   ans->gamma_.Read(is, binary);
   ans->y_.Read(is, binary);
   if (!H_.empty()) ans->ComputeH();
   return ans;
 }
void Scale (BaseFloat f) virtual
Scale the stats by a positive number f [not mandatory to supply this].
Reimplemented from Clusterable.
Definition at line 177 of file sgmm-clusterable.cc.
References SgmmClusterable::gamma_, KALDI_ASSERT, SgmmClusterable::my_H_, PackedMatrix< Real >::NumRows(), PackedMatrix< Real >::Scale(), VectorBase< Real >::Scale(), and SgmmClusterable::y_.
{
   KALDI_ASSERT(f >= 0.0);
   gamma_.Scale(f);
   y_.Scale(f);
   if (my_H_.NumRows() != 0) my_H_.Scale(f);
 }
void SetZero () virtual
Set stats to empty.
Implements Clusterable.
Definition at line 123 of file sgmm-clusterable.cc.
References SgmmClusterable::gamma_, SgmmClusterable::my_H_, VectorBase< Real >::SetZero(), PackedMatrix< Real >::SetZero(), and SgmmClusterable::y_.
{
   gamma_.SetZero();
   y_.SetZero();
   my_H_.SetZero(); // Should work even if empty.
 }
void Sub (const Clusterable & other) virtual
Subtract other stats.
Implements Clusterable.
Definition at line 144 of file sgmm-clusterable.cc.
References SpMatrix< Real >::AddSp(), VectorBase< Real >::AddVec(), SgmmClusterable::ComputeH(), SgmmClusterable::gamma_, SgmmClusterable::H_, SgmmClusterable::my_H_, PackedMatrix< Real >::NumRows(), SpMatrix< Real >::Resize(), and SgmmClusterable::y_.
{
   const SgmmClusterable *other =
       static_cast<const SgmmClusterable*>(&other_in);
   gamma_.AddVec(-1.0, other->gamma_);
   y_.AddVec(-1.0, other->y_);
   if (!H_.empty()) {
     if (my_H_.NumRows() != 0 && other->my_H_.NumRows() != 0)
       my_H_.AddSp(-1.0, other->my_H_);
     else {
       my_H_.Resize(0);
       ComputeH();
     }
   }
 }
virtual std::string Type () const inline virtual
Return a string that describes the inherited type.
Implements Clusterable.
Definition at line 50 of file sgmm-clusterable.h.
 { return "sgmm"; }
void Write (std::ostream & os, bool binary) const virtual
Write data to stream.
Implements Clusterable.
Definition at line 184 of file sgmm-clusterable.cc.
References SgmmClusterable::gamma_, VectorBase< Real >::Write(), and SgmmClusterable::y_.
{
   gamma_.Write(os, binary);
   y_.Write(os, binary);
 }
const Vector<double>& y () const inline
Definition at line 72 of file sgmm-clusterable.h.
References SgmmClusterable::y_.
 { return y_; }
Member Data Documentation
Vector<double> gamma_ private
Definition at line 80 of file sgmm-clusterable.h.
Referenced by SgmmClusterable::Accumulate(), SgmmClusterable::Add(), SgmmClusterable::ComputeH(), SgmmClusterable::Copy(), SgmmClusterable::gamma(), SgmmClusterable::Normalizer(), SgmmClusterable::Objf(), SgmmClusterable::ReadNew(), SgmmClusterable::Scale(), SgmmClusterable::SetZero(), SgmmClusterable::Sub(), and SgmmClusterable::Write().
const std::vector< SpMatrix<double> >& H_ private
Definition at line 78 of file sgmm-clusterable.h.
Referenced by SgmmClusterable::Add(), SgmmClusterable::ComputeH(), SgmmClusterable::Copy(), SgmmClusterable::Objf(), SgmmClusterable::ReadNew(), and SgmmClusterable::Sub().
SpMatrix<double> my_H_ private
Definition at line 85 of file sgmm-clusterable.h.
Referenced by SgmmClusterable::Accumulate(), SgmmClusterable::Add(), SgmmClusterable::ComputeH(), SgmmClusterable::Copy(), SgmmClusterable::Objf(), SgmmClusterable::Scale(), SgmmClusterable::SetZero(), and SgmmClusterable::Sub().
const AmSgmm& sgmm_ private
Definition at line 76 of file sgmm-clusterable.h.
Referenced by SgmmClusterable::Accumulate(), SgmmClusterable::Copy(), SgmmClusterable::Objf(), and SgmmClusterable::ReadNew().
Vector<double> y_ private
Definition at line 82 of file sgmm-clusterable.h.
Referenced by SgmmClusterable::Accumulate(), SgmmClusterable::Add(), SgmmClusterable::Copy(), SgmmClusterable::Objf(), SgmmClusterable::ReadNew(), SgmmClusterable::Scale(), SgmmClusterable::SetZero(), SgmmClusterable::Sub(), SgmmClusterable::Write(), and SgmmClusterable::y().
The documentation for this class was generated from the following files:
sgmm/sgmm-clusterable.h
sgmm/sgmm-clusterable.cc