Kaldi: NormalizeComponent Class Reference
NormalizeComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
void Init (int32 dim, BaseFloat target_rms)
NormalizeComponent (int32 dim, BaseFloat target_rms=1.0)
NormalizeComponent (const NormalizeComponent &other)
virtual int32 Properties () const
Return bitmask of the component's properties.
NormalizeComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void InitFromConfig (ConfigLine *cfl)
We implement InitFromConfig at this level.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
Public Member Functions inherited from NonlinearComponent
void Init (int32 dim)
NonlinearComponent (int32 dim)
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Private Member Functions
NormalizeComponent & operator= (const NormalizeComponent &other)
Private Attributes
BaseFloat target_rms_
Static Private Attributes
static const BaseFloat kNormFloor = pow(2.0, -66)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from NonlinearComponent
void StoreStatsInternal (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
Mutex mutex_
Detailed Description
Definition at line 119 of file nnet-simple-component.h.
Constructor & Destructor Documentation
NormalizeComponent (int32 dim, BaseFloat target_rms = 1.0) inline explicit
Definition at line 124 of file nnet-simple-component.h.
References NormalizeComponent::Init().
 { Init(dim, target_rms); }
NormalizeComponent (const NormalizeComponent & other) inline explicit
Definition at line 125 of file nnet-simple-component.h.
                                                               : NonlinearComponent(other),
     target_rms_(other.target_rms_) { }
NormalizeComponent () inline
Definition at line 131 of file nnet-simple-component.h.
Referenced by NormalizeComponent::Copy().
 : target_rms_(1.0) { }
Member Function Documentation
void Backprop (const std::string & debug_info, const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrixBase< BaseFloat > * in_deriv) const virtual
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
Parameters
[in] debug_info The component name, to be printed out in any warning messages.
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in_value The matrix that was given as input to the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsInput == 0.
[in] out_value The matrix that was output from the Propagate function. Will be ignored (and may be empty) if Properties()&kBackpropNeedsOutput == 0
[in] out_deriv The derivative at the output of this component.
[out] to_update If model update is desired, the Component to be updated, else NULL. Does not have to be identical to this.
[out] in_deriv The derivative at the input of this component, if needed (else NULL). If Properties()&kBackpropInPlace, may be the same matrix as out_deriv. If Properties()&kBackpropAdds, this is added to by the Backprop routine, else it is set. The component code chooses which mode to work in, based on convenience.
Implements Component.
Definition at line 365 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddDiagMat2(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::Data(), NormalizeComponent::kNormFloor, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and NormalizeComponent::target_rms_.
{
   if (!in_deriv)  return;
   CuVector<BaseFloat> dot_products(out_deriv.NumRows());
   dot_products.AddDiagMatMat(1.0, out_deriv, kNoTrans, in_value, kTrans, 0.0);
   CuVector<BaseFloat> in_norm(in_value.NumRows());
   // dscaled == D * target_rms^2.
   BaseFloat d_scaled = (in_value.NumCols() * target_rms_ * target_rms_);
   in_norm.AddDiagMat2(1.0 / d_scaled,
                       in_value, kNoTrans, 0.0);
   in_norm.ApplyFloor(kNormFloor);
   in_norm.ApplyPow(-0.5);
   if (in_deriv) {
     if (in_deriv->Data() != out_deriv.Data())
       in_deriv->AddDiagVecMat(1.0, in_norm, out_deriv, kNoTrans, 0.0);
     else
       in_deriv->MulRowsVec(in_norm);
   }
   in_norm.ReplaceValue(1.0 / sqrt(kNormFloor), 0.0);
   in_norm.ApplyPow(3.0);
   dot_products.MulElements(in_norm);
   in_deriv->AddDiagVecMat(-1.0 / d_scaled,
                           dot_products, in_value,
                           kNoTrans, 1.0);
 }
virtual Component* Copy () const inline virtual
Copies component (deep copy).
Implements Component.
Definition at line 134 of file nnet-simple-component.h.
References NormalizeComponent::NormalizeComponent().
 { return new NormalizeComponent(*this); }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from NonlinearComponent.
Definition at line 317 of file nnet-simple-component.cc.
References NonlinearComponent::Info(), and NormalizeComponent::target_rms_.
{
   std::ostringstream stream;
   stream << NonlinearComponent::Info();
   stream << ", target-rms=" << target_rms_;
   return stream.str();
 }
void Init (int32 dim, BaseFloat target_rms)
Definition at line 246 of file nnet-simple-component.cc.
References NonlinearComponent::count_, NonlinearComponent::dim_, KALDI_ASSERT, and NormalizeComponent::target_rms_.
Referenced by NormalizeComponent::InitFromConfig(), and NormalizeComponent::NormalizeComponent().
{
   KALDI_ASSERT(dim > 0);
   KALDI_ASSERT(target_rms > 0);
   dim_ = dim;
   count_ = 0.0;
   target_rms_ = target_rms;
 }
void InitFromConfig (ConfigLine * cfl) virtual
We implement InitFromConfig at this level.
Reimplemented from NonlinearComponent.
Definition at line 254 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), NormalizeComponent::Init(), KALDI_ERR, NormalizeComponent::Type(), and ConfigLine::WholeLine().
{
   int32 dim = 0;
   BaseFloat target_rms = 1.0;
   bool ok = cfl->GetValue("dim", &dim);
   cfl->GetValue("target-rms", &target_rms);
   if (!ok || cfl->HasUnusedValues() || dim <= 0 || target_rms <= 0.0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << cfl->WholeLine() << "\"";
   Init(dim, target_rms);
 }
NormalizeComponent& operator= (const NormalizeComponent & other) private
void Propagate (const ComponentPrecomputedIndexes * indexes, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Propagate function.
Parameters
[in] indexes A pointer to some information output by this class's PrecomputeIndexes function (will be NULL for simple components, i.e. those that don't do things like splicing).
[in] in The input to this component. Num-columns == InputDim().
[out] out The output of this component. Num-columns == OutputDim(). Note: output of this component will be added to the initial value of "out" if Properties()&kPropagateAdds != 0; otherwise the output will be set and the initial value ignored. Each Component chooses whether it is more convenient implementation-wise to add or set, and the calling code has to deal with it.
Implements Component.
Definition at line 331 of file nnet-simple-component.cc.
References CuVectorBase< Real >::AddDiagMat2(), CuMatrixBase< Real >::CopyFromMat(), NormalizeComponent::kNormFloor, kaldi::kNoTrans, CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and NormalizeComponent::target_rms_.
{
   CuVector<BaseFloat> in_norm(in.NumRows());
   BaseFloat d_scaled = (in.NumCols() * target_rms_ * target_rms_);
   in_norm.AddDiagMat2(1.0 / d_scaled,
                       in, kNoTrans, 0.0);
   in_norm.ApplyFloor(kNormFloor);
   in_norm.ApplyPow(-0.5);
   out->CopyFromMat(in);
   out->MulRowsVec(in_norm);
 }
virtual int32 Properties () const inline virtual
Return bitmask of the component's properties.
These properties depend only on the component's type. See enum ComponentProperties.
Implements Component.
Definition at line 127 of file nnet-simple-component.h.
References kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNeedsInput, kaldi::nnet3::kPropagateInPlace, and kaldi::nnet3::kSimpleComponent.
{
     return kSimpleComponent|kBackpropNeedsInput|kPropagateInPlace|
         kBackpropInPlace;
   }
void Read (std::istream & is, bool binary) virtual
We implement Read at this level as it just needs the Type().
Reimplemented from NonlinearComponent.
Definition at line 264 of file nnet-simple-component.cc.
References NonlinearComponent::count_, NonlinearComponent::deriv_sum_, NonlinearComponent::dim_, kaldi::nnet3::ExpectOneOrTwoTokens(), kaldi::nnet3::ExpectToken(), KALDI_ASSERT, CuVector< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), CuVectorBase< Real >::Scale(), NormalizeComponent::target_rms_, NormalizeComponent::Type(), and NonlinearComponent::value_sum_.
{
   std::ostringstream ostr_beg, ostr_end;
   ostr_beg << "<" << Type() << ">";
   ostr_end << "</" << Type() << ">";
   ExpectOneOrTwoTokens(is, binary, ostr_beg.str(), "<Dim>");
   ReadBasicType(is, binary, &dim_); // Read dimension.
   std::string tok; // TODO: remove back-compatibility code.
   ReadToken(is, binary, &tok);
   // read target_rms_ if it is available.
   if (tok == "<TargetRms>") {
     ReadBasicType(is, binary, &target_rms_);
     ReadToken(is, binary, &tok);
   }
   // The new format is more readable as we write values that are normalized by
   // the count.
   KALDI_ASSERT(tok == "<ValueAvg>");
   value_sum_.Read(is, binary);
   ExpectToken(is, binary, "<DerivAvg>");
   deriv_sum_.Read(is, binary);
   ExpectToken(is, binary, "<Count>");
   ReadBasicType(is, binary, &count_);
   value_sum_.Scale(count_);
   deriv_sum_.Scale(count_);
   ExpectToken(is, binary, ostr_end.str());
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Implements Component.
Definition at line 132 of file nnet-simple-component.h.
Referenced by NormalizeComponent::InitFromConfig(), NormalizeComponent::Read(), and NormalizeComponent::Write().
 { return "NormalizeComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Reimplemented from NonlinearComponent.
Definition at line 291 of file nnet-simple-component.cc.
References VectorBase< Real >::CopyFromVec(), NonlinearComponent::count_, NonlinearComponent::deriv_sum_, CuVectorBase< Real >::Dim(), NonlinearComponent::dim_, kaldi::kUndefined, Vector< Real >::Resize(), VectorBase< Real >::Scale(), NormalizeComponent::target_rms_, NormalizeComponent::Type(), NonlinearComponent::value_sum_, VectorBase< Real >::Write(), kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   std::ostringstream ostr_beg, ostr_end;
   ostr_beg << "<" << Type() << ">";
   ostr_end << "</" << Type() << ">";
   WriteToken(os, binary, ostr_beg.str());
   WriteToken(os, binary, "<Dim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<TargetRms>");
   WriteBasicType(os, binary, target_rms_);
   // Write the values and derivatives in a count-normalized way, for
   // greater readability in text form.
   WriteToken(os, binary, "<ValueAvg>");
   Vector<BaseFloat> temp(value_sum_);
   if (count_ != 0.0) temp.Scale(1.0 / count_);
   temp.Write(os, binary);
   WriteToken(os, binary, "<DerivAvg>");
   temp.Resize(deriv_sum_.Dim(), kUndefined);
   temp.CopyFromVec(deriv_sum_);
   if (count_ != 0.0) temp.Scale(1.0 / count_);
   temp.Write(os, binary);
   WriteToken(os, binary, "<Count>");
   WriteBasicType(os, binary, count_);
   WriteToken(os, binary, ostr_end.str());
 }
Member Data Documentation
const BaseFloat kNormFloor = pow(2.0, -66) static private
Definition at line 155 of file nnet-simple-component.h.
Referenced by NormalizeComponent::Backprop(), and NormalizeComponent::Propagate().
BaseFloat target_rms_ private
Definition at line 156 of file nnet-simple-component.h.
Referenced by NormalizeComponent::Backprop(), NormalizeComponent::Info(), NormalizeComponent::Init(), NormalizeComponent::Propagate(), NormalizeComponent::Read(), and NormalizeComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc