Kaldi: VariableMergingOptimizer Class Reference
VariableMergingOptimizer Class Reference
This class is responsible for merging matrices, although you probably want to access it via the the function VariableMergingOptimization().
#include <nnet-optimize-utils.h>
Public Member Functions
VariableMergingOptimizer (const NnetOptimizeOptions &config, const Nnet &nnet, const ComputationRequest &request, NnetComputation *computation)
bool MergeVariables ()
Private Member Functions
std::pair< bool, bool > MayBeMerged (int32 command, int32 s1, int32 s2) const
This function returns a pair of bools saying whether we can do a (left and/or right) merge respectively, based on the conditions defined in the header.
void DoLeftMerge (int32 command_index, int32 s1, int32 s2)
void DoRightMerge (int32 command_index, int32 s1, int32 s2)
void DoMergeCommon (int32 command_index, int32 m_to_keep, int32 m_to_discard)
void MarkAsDirty (int32 s)
Marks the variables underlying submatrix 's' as dirty.
void Initialize ()
Private Attributes
const NnetOptimizeOptions & config_
const Nnet & nnet_
const ComputationRequest & request_
NnetComputation * computation_
Analyzer analyzer_
std::vector< std::vector< int32 > > matrix_to_submatrix_
std::vector< bool > variable_dirty_
bool already_called_merge_variables_
Detailed Description
This class is responsible for merging matrices, although you probably want to access it via the the function VariableMergingOptimization().
We identify pairs of submatrices which can potentially be merged into a single submatrix.
Suppose there are two different submatrices s1 != s2 that are submatrices of different respective matrices m1 != m2, and somewhere in the computation we have a command C, which is one of: (a) the assignment command "s2 = s1", or (b) a propagate command with s1 as input and s2 as output, with a component that supports propagate in place, or (c) a backprop command with s1 as output-deriv and s2 as input-deriv, with a component that supports backprop in place.
Then the triple (C, s1, s2) is a candidate for merging. We support two types of merging: 'right merging', in which we delete s1 and use s2 instead; and 'left merging' in which we delete s2 and use s1 instead. The two types of merging may seem to be the same thing, but remember that in general s1 and s2 may be sub-matrices of larger matrices.
Note: the following
Define last-access(submatrix) as: If matrix-of(submatrix) is an output, then num-commands, otherwise the last command that accesses that submatrix for either read or write. [note: deallocation does not count as a read or write operation].
Define first-access(submatrix) as: If matrix-of(submatrix) is an input, then -1, otherwise the first command that is *not* an allocation command that accessed that submatrix for either read or write.
Define last-write-access(submatrix) as the last command-index that accessed the submatrix in a write operation, or -1 if there is no such command (this could happen for inputs).
Define data-invalidated-command(c, submatrix) as the first command-index after 'c' that 'submatrix' is written to; or if there is no such command, then the command index of the deallocation command for 'submatrix'; or if this does not exist, then num-commands.
The conditions that must be satisfied for both left and right merges:
It cannot be the case that m1 and m2 are both inputs, or that they are both outputs. [condition c1]
If either m1 or m2 is an input or an output, then s1 must be the entirety of m1 and s2 must be the entirety of m2 (this is because inputs and outputs must be whole matrices). [condition c2]
If we are left-merging (deleting s2,m2), then s2 must be the entirety of m2. [condition c3]
If we are right-merging (deleting s1,m1), then s1 must be the entirety of m1. [condition c4]
None of the the variables underlying s1 and s2 may be marked as 'dirty' (implying that they were the subjects of a previous merge during the lifetime of this class) [condition c5]
If the command C is case (a), i.e. an assignment operation, then the following conditions must apply:
first-access(s2) == C
last-write-access(s1) < C
last-access(s1) < data-invalidated-command(C, s2) Otherwise (cases (b) and (c), in-place propagate or backprop), we insist that:
first-access(s2) == C
last-access(s1) == C Note: in either case, these conditions imply that s2 is not an input and s1 is not an output.
The sequence of things we have to do for a right-merge (in which we delete s1,m1) is as follows:
All submatrices that reference m1, make them reference m2 instead. [later we'll renumber so that there are no duplicates.]
If m1 was an input, replace it as an input with m2 and remove the command that allocated m2.
If it was an assignment [case (a)], replace the assignment command with a no-op.
If both m1 and m2 have commands that allocate them, keep only the allocation command for m2, and make sure that it zeroes the data (we can later change to undefined if allowed) and that it's before the first non-allocation access of m1. Otherwise remove any allocation commands (the merged variable is an input).
If both m1 and m2 have commands that deallocate them, keep only the deallocation command for m2, and make sure that it's after the last access of m1 (otherwise delete any deallocation command, because m2 must be an output). [note: previously we kept the later of the 2 commands, but this had the effect of making inaccurate the Analyzer info for a matrix (m2) that might later be used.
The sequence of things we have to do for a right-merge (in which we delete s1,m1) is as follows:
All submatrices that reference m2, make them reference m1 instead. [later we'll renumber so that there are no duplicates.]
If m2 was an output, replace it as an output with m1 and remove the command that deallocated m1. ... the last three bullet-points, regarding removing the assignment command, and allocation and deallocation, are the same as for a left-merge, except swap m1 and m2.
At the end when we call RemoveOrphanMatrices(), the renumbering code will automatically detect that there are duplicate submatrices, and will merge them, as well as removing the now-unused matrix indexes. After merging, we will mark the variables (i.e. row-ranges) underlying s1 and s2 as being "dirty" so they can no longer be merged during the lifetime of this class.
Definition at line 133 of file nnet-optimize-utils.h.
Constructor & Destructor Documentation
VariableMergingOptimizer (const NnetOptimizeOptions & config, const Nnet & nnet, const ComputationRequest & request, NnetComputation * computation)
Definition at line 693 of file nnet-optimize-utils.cc.
References VariableMergingOptimizer::analyzer_, VariableMergingOptimizer::computation_, kaldi::nnet3::ComputeMatrixToSubmatrix(), Analyzer::Init(), VariableMergingOptimizer::matrix_to_submatrix_, ComputationVariables::NumVariables(), VariableMergingOptimizer::variable_dirty_, and Analyzer::variables.
                                  :
     config_(config), nnet_(nnet), request_(request),
     computation_(computation),
     already_called_merge_variables_(false) {
   analyzer_.Init(nnet, *computation);
   ComputeMatrixToSubmatrix(*computation_, &matrix_to_submatrix_);
   variable_dirty_.resize(analyzer_.variables.NumVariables(), false);
 }
Member Function Documentation
void DoLeftMerge (int32 command_index, int32 s1, int32 s2) private
Definition at line 900 of file nnet-optimize-utils.cc.
References VariableMergingOptimizer::analyzer_, NnetComputation::commands, VariableMergingOptimizer::computation_, VariableMergingOptimizer::DoMergeCommon(), kaldi::nnet3::GetSubMatrixOfSubMatrix(), KALDI_ASSERT, kaldi::nnet3::kNoOperation, VariableMergingOptimizer::MarkAsDirty(), Analyzer::matrix_accesses, VariableMergingOptimizer::matrix_to_submatrix_, VariableMergingOptimizer::nnet_, kaldi::nnet3::ReplaceInOutput(), and NnetComputation::submatrices.
Referenced by VariableMergingOptimizer::MergeVariables().
{
   // Prevent further optimizations touching s1 or s2 (we can
   // try again in a later round of optimization, with a new
   // instance of this class).
   MarkAsDirty(s1);
   MarkAsDirty(s2);
   int32 m1 = computation_->submatrices[s1].matrix_index,
       m2 = computation_->submatrices[s2].matrix_index;
   KALDI_ASSERT(m1 != m2 && m1 > 0 && m2 > 0);
   { // modify submatrices for submatrices of m2 to effectively be sub-matrices of
     // s1 instead (they will refer to m1 as the matrix_index).
     std::vector<int32>::const_iterator iter = matrix_to_submatrix_[m2].begin(),
         end = matrix_to_submatrix_[m2].end();
     for (; iter != end; ++iter) {
       int32 submatrix_index = *iter;
       KALDI_ASSERT(computation_->submatrices[submatrix_index].matrix_index==m2);
       computation_->submatrices[submatrix_index] =
           GetSubMatrixOfSubMatrix(*computation_, submatrix_index, s1);
     }
   }
   const std::vector<MatrixAccesses> &matrix_accesses = analyzer_.matrix_accesses;
   // - If m2 was an output, replace it as an input with m1.
   bool replaced = ReplaceInOutput(nnet_, m2, m1, computation_);
   KALDI_ASSERT(replaced == matrix_accesses[m2].is_output);
   if (replaced) {  // Remove the command that deallocates m1.
     int32 dealloc_command = matrix_accesses[m1].deallocate_command;
     KALDI_ASSERT(dealloc_command != -1);
     computation_->commands[dealloc_command].command_type =
         kNoOperation;
   }
   // we keep matrix m1 (so m1 is m_to_keep, m2 is m_to_discard).
   DoMergeCommon(command_index, m1, m2);
 }
void DoMergeCommon (int32 command_index, int32 m_to_keep, int32 m_to_discard) private
Definition at line 839 of file nnet-optimize-utils.cc.
References VariableMergingOptimizer::analyzer_, NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::command_type, NnetComputation::commands, VariableMergingOptimizer::computation_, ComputationAnalysis::FirstMatrixAccess(), KALDI_ASSERT, kaldi::nnet3::kAllocMatrixFromOther, kaldi::nnet3::kAllocMatrixFromOtherZeroed, kaldi::nnet3::kAllocMatrixUndefined, kaldi::nnet3::kAllocMatrixZeroed, kaldi::nnet3::kMatrixCopy, kaldi::nnet3::kNoOperation, ComputationAnalysis::LastMatrixAccess(), and Analyzer::matrix_accesses.
Referenced by VariableMergingOptimizer::DoLeftMerge(), and VariableMergingOptimizer::DoRightMerge().
{
   ComputationAnalysis analysis(*computation_, analyzer_);
   NnetComputation::Command &c = computation_->commands[command_index];
   const std::vector<MatrixAccesses> &matrix_accesses =
       analyzer_.matrix_accesses;
   //  - If it was case (a), replace the assignment command with a no-op.
   if (c.command_type == kMatrixCopy) {
     // remove the command.
     c.command_type = kNoOperation;
     c.arg1 = -1;
     c.arg2 = -1;
   }
   //   - If both m_to_keep and m_to_discard have commands that deallocate them,
   //    keep only the allocation command for m_to_keep, and make sure it's after
   //    the last access of m_to_discard (otherwise delete any deallocation
   //    command).
   int32 dealloc_keep = matrix_accesses[m_to_keep].deallocate_command,
       dealloc_discard = matrix_accesses[m_to_discard].deallocate_command;
   if (dealloc_keep != -1 && dealloc_discard != -1) {
     KALDI_ASSERT(analysis.LastMatrixAccess(m_to_discard) < dealloc_keep);
     computation_->commands[dealloc_discard].command_type = kNoOperation;
   } else {
     if (dealloc_keep != -1)
       computation_->commands[dealloc_keep].command_type =
           kNoOperation;
     if (dealloc_discard != -1)
       computation_->commands[dealloc_discard].command_type =
           kNoOperation;
   }
   //   - If both m_to_keep and m_to_discard have commands that allocate them,
   //     keep only the allocation command for m_to_keep and make sure it's
   //     before the first access of m_to_discard.
   //     (otherwise delete any allocation command).
   int32 alloc_keep = matrix_accesses[m_to_keep].allocate_command,
       alloc_discard = matrix_accesses[m_to_discard].allocate_command;
   if (alloc_keep != -1 && alloc_discard != -1) {
     KALDI_ASSERT(analysis.FirstMatrixAccess(m_to_discard) > alloc_keep);
     NnetComputation::Command
         &keep_alloc_command = computation_->commands[alloc_keep],
         &discard_alloc_command = computation_->commands[alloc_discard];
     discard_alloc_command.command_type = kNoOperation;
     if (keep_alloc_command.command_type == kAllocMatrixUndefined) {
       keep_alloc_command.command_type = kAllocMatrixZeroed;
     } else if (keep_alloc_command.command_type == kAllocMatrixFromOther) {
       keep_alloc_command.command_type = kAllocMatrixFromOtherZeroed;
     }
   } else {
     if (alloc_keep != -1)
       computation_->commands[alloc_keep].command_type =
           kNoOperation;
     if (alloc_discard != -1)
       computation_->commands[alloc_discard].command_type =
           kNoOperation;
   }
 }
void DoRightMerge (int32 command_index, int32 s1, int32 s2) private
Definition at line 803 of file nnet-optimize-utils.cc.
References VariableMergingOptimizer::analyzer_, NnetComputation::commands, VariableMergingOptimizer::computation_, VariableMergingOptimizer::DoMergeCommon(), kaldi::nnet3::GetSubMatrixOfSubMatrix(), KALDI_ASSERT, kaldi::nnet3::kNoOperation, VariableMergingOptimizer::MarkAsDirty(), Analyzer::matrix_accesses, VariableMergingOptimizer::matrix_to_submatrix_, VariableMergingOptimizer::nnet_, kaldi::nnet3::ReplaceInInput(), and NnetComputation::submatrices.
Referenced by VariableMergingOptimizer::MergeVariables().
{
   // Prevent further optimizations touching s1 or s2 (we can
   // try again in a later round of optimization, with a new
   // instance of this class).
   MarkAsDirty(s1);
   MarkAsDirty(s2);
   int32 m1 = computation_->submatrices[s1].matrix_index,
       m2 = computation_->submatrices[s2].matrix_index;
   KALDI_ASSERT(m1 != m2 && m1 > 0 && m2 > 0);
   { // modify submatrices for submatrices of m1 to effectively be sub-matrices of
     // s2 instead (they will refer to m2 as the matrix_index).
     std::vector<int32>::const_iterator iter = matrix_to_submatrix_[m1].begin(),
         end = matrix_to_submatrix_[m1].end();
     for (; iter != end; ++iter) {
       int32 submatrix_index = *iter;
       KALDI_ASSERT(computation_->submatrices[submatrix_index].matrix_index==m1);
       computation_->submatrices[submatrix_index] =
           GetSubMatrixOfSubMatrix(*computation_, submatrix_index, s2);
     }
   }
   const std::vector<MatrixAccesses> &matrix_accesses = analyzer_.matrix_accesses;
   // - If m1 was an input, replace it as an input with m2
   bool replaced = ReplaceInInput(nnet_, m1, m2, computation_);
   KALDI_ASSERT(replaced == matrix_accesses[m1].is_input);
   if (replaced) {  // Remove the command that allocates m2.
     int32 alloc_command = matrix_accesses[m2].allocate_command;
     KALDI_ASSERT(alloc_command != -1);
     computation_->commands[alloc_command].command_type =
         kNoOperation;
   }
   // we keep matrix m2 (so m2 is m_to_keep, m1 is m_to_discard).
   DoMergeCommon(command_index, m2, m1);
 }
void Initialize () private
void MarkAsDirty (int32 s) private
Marks the variables underlying submatrix 's' as dirty.
Definition at line 791 of file nnet-optimize-utils.cc.
References VariableMergingOptimizer::analyzer_, ComputationVariables::AppendVariablesForSubmatrix(), KALDI_ASSERT, VariableMergingOptimizer::variable_dirty_, and Analyzer::variables.
Referenced by VariableMergingOptimizer::DoLeftMerge(), and VariableMergingOptimizer::DoRightMerge().
{
   std::vector<int32> variable_indexes;
   analyzer_.variables.AppendVariablesForSubmatrix(s, &variable_indexes);
   std::vector<int32>::const_iterator iter = variable_indexes.begin(),
       end = variable_indexes.end();
   for (; iter != end; ++iter) {
     int32 v = *iter;
     KALDI_ASSERT(static_cast<size_t>(v) < variable_dirty_.size());
     variable_dirty_[v] = true;
   }
 }
std::pair< bool, bool > MayBeMerged (int32 command, int32 s1, int32 s2) const private
This function returns a pair of bools saying whether we can do a (left and/or right) merge respectively, based on the conditions defined in the header.
Note: if one of the variables underlying s1 or s2 is marked as 'dirty' due to a previous merge, this function will return (false,false). The terms left-merge and right-merge are defined in the extended comment above this class. Note: left_merge will always be false if config.allow_left_merge == false, and the same respectively for right_merge.
Parameters
command [in] The command-index that assigns s2 := s1 or does a forward or backprop with s1 as the input and s2 as the output
s1 [in] A submatrix-index s1 > 0.
s2 [in] A submatrix-index s2 > 0
Definition at line 939 of file nnet-optimize-utils.cc.
References NnetOptimizeOptions::allow_left_merge, NnetOptimizeOptions::allow_right_merge, VariableMergingOptimizer::analyzer_, ComputationVariables::AppendVariablesForSubmatrix(), NnetComputation::commands, VariableMergingOptimizer::computation_, VariableMergingOptimizer::config_, ComputationAnalysis::DataInvalidatedCommand(), ComputationAnalysis::FirstAccess(), MatrixAccesses::is_input, MatrixAccesses::is_output, NnetComputation::IsWholeMatrix(), KALDI_ASSERT, kaldi::nnet3::kMatrixCopy, ComputationAnalysis::LastAccess(), ComputationAnalysis::LastWriteAccess(), Analyzer::matrix_accesses, NnetComputation::submatrices, VariableMergingOptimizer::variable_dirty_, and Analyzer::variables.
Referenced by VariableMergingOptimizer::MergeVariables().
{
   KALDI_ASSERT(s1 > 0 && s2 > 0 && static_cast<size_t>(command_index) <
                computation_->commands.size());
   if (!config_.allow_left_merge && !config_.allow_right_merge)
     return std::pair<bool,bool>(false,false);
   int32 m1 = computation_->submatrices[s1].matrix_index,
       m2 = computation_->submatrices[s2].matrix_index;
   // we can't merge two different submatrices of the same matrix.
   if (m1 == m2) return std::pair<bool,bool>(false,false);
   std::vector<int32> variable_indexes;
   analyzer_.variables.AppendVariablesForSubmatrix(s1, &variable_indexes);
   analyzer_.variables.AppendVariablesForSubmatrix(s2, &variable_indexes);
   std::vector<int32>::iterator iter = variable_indexes.begin(),
       end = variable_indexes.end();
   // condition c5:
   for (; iter != end; ++iter)
     if (variable_dirty_[*iter])
       return std::pair<bool,bool>(false,false);
   const std::vector<MatrixAccesses> &matrix_accesses = analyzer_.matrix_accesses;
   const MatrixAccesses &m1_access = matrix_accesses[m1],
       &m2_access = matrix_accesses[m2];
   // condition c1:
   if ((m1_access.is_input && m2_access.is_input) ||
       (m1_access.is_output && m2_access.is_output))
     return std::pair<bool,bool>(false,false);
   // condition c2:
   if ((m1_access.is_input || m1_access.is_output ||
        m2_access.is_input || m2_access.is_output) &&
       (!computation_->IsWholeMatrix(s1) ||
        !computation_->IsWholeMatrix(s2)))
     return std::pair<bool,bool>(false,false);
   bool left = config_.allow_left_merge,
       right = config_.allow_right_merge;
   // condition c3:
   if (!computation_->IsWholeMatrix(s2)) left = false;
   if (!computation_->IsWholeMatrix(s1)) right = false;
   if (!left && !right)  // save some time.
     return std::pair<bool,bool>(false,false);
   bool is_assignment = (computation_->commands[command_index].command_type ==
                         kMatrixCopy);
   ComputationAnalysis analysis(*computation_, analyzer_);
   if (is_assignment) {
     if (analysis.FirstAccess(s2) == command_index &&
         analysis.LastWriteAccess(s1) < command_index &&
         analysis.LastAccess(s1) <
         analysis.DataInvalidatedCommand(command_index, s2)) {
       return std::pair<bool,bool>(left, right);  // possible success.
     }
   } else {
     if (analysis.FirstAccess(s2) == command_index &&
         analysis.LastAccess(s1) == command_index) {
       return std::pair<bool,bool>(left, right);  // possible success.
     }
   }
   // failure.
   return std::pair<bool,bool>(false,false);
 }
bool MergeVariables ()
Definition at line 706 of file nnet-optimize-utils.cc.
References VariableMergingOptimizer::already_called_merge_variables_, NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::arg3, NnetComputation::Command::arg4, NnetComputation::Command::arg5, NnetComputation::Command::arg6, NnetOptimizeOptions::backprop_in_place, NnetComputation::Command::command_type, NnetComputation::commands, VariableMergingOptimizer::computation_, VariableMergingOptimizer::config_, VariableMergingOptimizer::DoLeftMerge(), VariableMergingOptimizer::DoRightMerge(), Nnet::GetComponent(), KALDI_ASSERT, kaldi::nnet3::kBackprop, kaldi::nnet3::kBackpropInPlace, kaldi::nnet3::kBackpropNoModelUpdate, kaldi::nnet3::kMatrixCopy, kaldi::nnet3::kPropagate, kaldi::nnet3::kPropagateInPlace, VariableMergingOptimizer::MayBeMerged(), VariableMergingOptimizer::nnet_, NnetOptimizeOptions::optimize, NnetOptimizeOptions::propagate_in_place, Component::Properties(), NnetOptimizeOptions::remove_assignments, kaldi::nnet3::RemoveNoOps(), and kaldi::nnet3::RenumberComputation().
Referenced by kaldi::nnet3::VariableMergingOptimization().
{
   KALDI_ASSERT(!already_called_merge_variables_);
   already_called_merge_variables_ = true;
   if (!config_.optimize)
     return false;
   bool merged = false;
   int32 num_commands = computation_->commands.size();
   for (int32 command_index = 0; command_index < num_commands;
        command_index++) {
     // This loop looks for pairs of sub-matrix indexes s1,s2 that we could
     // potentially merge into a single variable.
     const NnetComputation::Command &c =
         computation_->commands[command_index];
     int32 s1 = -1, s2 = -1;
     if (c.command_type == kMatrixCopy &&
         config_.remove_assignments) {
       s2 = c.arg1;  // s2 is the written-to matrix.
       s1 = c.arg2;
     } else if (c.command_type == kPropagate &&
                config_.propagate_in_place) {
       const Component *component = nnet_.GetComponent(c.arg1);
       if (component->Properties() & kPropagateInPlace) {
         s1 = c.arg3;
         s2 = c.arg4;  // s2 is the written-to matrix.
       }
     } else if ((c.command_type == kBackprop ||
                 c.command_type == kBackpropNoModelUpdate) &&
                config_.backprop_in_place) {
       const Component *component = nnet_.GetComponent(c.arg1);
       if (component->Properties() & kBackpropInPlace) {
         s1 = c.arg5;
         s2 = c.arg6;  // s2 is the written-to matrix.
         if (s1 == c.arg3 || s2 == c.arg3 || s1 == c.arg4 || s2 == c.arg4) {
           // we don't think this should ever happen, but just out of an
           // abundance of caution: if either of these submatrix indexes are the
           // input-value or output-value args to Backprop, don't do the optimization.
           s1 = -1;
           s2 = -1;
         }
       }
     }
     if (s1 > 0 && s2 > 0) {
       std::pair<bool,bool> p = MayBeMerged(command_index, s1, s2);
       if (p.first) {
         DoLeftMerge(command_index, s1, s2);
         merged = true;
       } else if (p.second) {
         DoRightMerge(command_index, s1, s2);
         merged = true;
       }
     }
   }
   if (merged) {
     RenumberComputation(computation_);
     RemoveNoOps(computation_);
   }
   return merged;
 }
Member Data Documentation
bool already_called_merge_variables_ private
Definition at line 196 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::MergeVariables().
Analyzer analyzer_ private
Definition at line 187 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::DoLeftMerge(), VariableMergingOptimizer::DoMergeCommon(), VariableMergingOptimizer::DoRightMerge(), VariableMergingOptimizer::MarkAsDirty(), VariableMergingOptimizer::MayBeMerged(), and VariableMergingOptimizer::VariableMergingOptimizer().
NnetComputation* computation_ private
Definition at line 185 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::DoLeftMerge(), VariableMergingOptimizer::DoMergeCommon(), VariableMergingOptimizer::DoRightMerge(), VariableMergingOptimizer::MayBeMerged(), VariableMergingOptimizer::MergeVariables(), and VariableMergingOptimizer::VariableMergingOptimizer().
const NnetOptimizeOptions& config_ private
Definition at line 182 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::MayBeMerged(), and VariableMergingOptimizer::MergeVariables().
std::vector<std::vector<int32> > matrix_to_submatrix_ private
Definition at line 190 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::DoLeftMerge(), VariableMergingOptimizer::DoRightMerge(), and VariableMergingOptimizer::VariableMergingOptimizer().
const Nnet& nnet_ private
Definition at line 183 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::DoLeftMerge(), VariableMergingOptimizer::DoRightMerge(), and VariableMergingOptimizer::MergeVariables().
const ComputationRequest& request_ private
Definition at line 184 of file nnet-optimize-utils.h.
std::vector<bool> variable_dirty_ private
Definition at line 194 of file nnet-optimize-utils.h.
Referenced by VariableMergingOptimizer::MarkAsDirty(), VariableMergingOptimizer::MayBeMerged(), and VariableMergingOptimizer::VariableMergingOptimizer().
The documentation for this class was generated from the following files:
nnet3/nnet-optimize-utils.h
nnet3/nnet-optimize-utils.cc