Kaldi: AmSgmmFunctions Class Reference
AmSgmmFunctions Class Reference
Class for misc functions that need access to SGMM private variables.
#include <am-sgmm.h>
Static Public Member Functions
static void ComputeDistances (const AmSgmm &model, const Vector< BaseFloat > &state_occs, MatrixBase< BaseFloat > *dists)
Computes matrix of approximated K-L divergences, of size [#states x #states], as described in "State-Level Data Borrowing for Low-Resource Speech Recognition based on Subspace GMMs", by Yanmin Qian et.
Detailed Description
Class for misc functions that need access to SGMM private variables.
Definition at line 405 of file am-sgmm.h.
Member Function Documentation
void ComputeDistances (const AmSgmm & model, const Vector< BaseFloat > & state_occs, MatrixBase< BaseFloat > * dists) static
Computes matrix of approximated K-L divergences, of size [#states x #states], as described in "State-Level Data Borrowing for Low-Resource Speech Recognition based on Subspace GMMs", by Yanmin Qian et.
al, Interspeech 2011. Model must have one substate per state.
Definition at line 1363 of file am-sgmm.cc.
References SpMatrix< Real >::AddMat2Sp(), SpMatrix< Real >::AddSp(), VectorBase< Real >::AddVec(), rnnlm::i, KALDI_ASSERT, KALDI_WARN, kaldi::kTrans, AmSgmm::M_, MatrixBase< Real >::NumCols(), AmSgmm::NumGauss(), AmSgmm::NumPdfs(), MatrixBase< Real >::NumRows(), AmSgmm::NumSubstates(), AmSgmm::PhoneSpaceDim(), AmSgmm::SigmaInv_, AmSgmm::v_, and kaldi::VecSpVec().
Referenced by main().
{
   int32 num_states = model.NumPdfs(),
       phn_space_dim = model.PhoneSpaceDim(),
       num_gauss = model.NumGauss();
   KALDI_ASSERT(dists != NULL && dists->NumRows() == num_states
                && dists->NumCols() == num_states);
   Vector<double> prior(state_occs);
   KALDI_ASSERT(prior.Sum() != 0.0);
   prior.Scale(1.0 / prior.Sum());  // Normalize.
   SpMatrix<BaseFloat> H(phn_space_dim);  // The same as H_sm in some other code.
   for (int32 i = 0; i < num_gauss; i++) {
     SpMatrix<BaseFloat> Hi(phn_space_dim);
     Hi.AddMat2Sp(1.0, model.M_[i], kTrans, model.SigmaInv_[i], 0.0);
     H.AddSp(prior(i), Hi);
   }
   bool warned = false;
   for (int32 j1 = 0; j1 < num_states; ++j1) {
     if (model.NumSubstates(j1) != 1 && !warned) {
       KALDI_WARN << "ComputeDistances() can only give meaningful output if you "
                  << "have one substate per state.";
       warned = true;
     }
     for (int32 j2 = 0; j2 <= j1; ++j2) {
       Vector<BaseFloat> v_diff(model.v_[j1].Row(0));
       v_diff.AddVec(-1.0, model.v_[j2].Row(0));
       (*dists)(j1, j2) = (*dists)(j2, j1) = VecSpVec(v_diff, H, v_diff);
     }
   }
 }
The documentation for this class was generated from the following files:
sgmm/am-sgmm.h
sgmm/am-sgmm.cc