Kaldi: SequentialTableReaderScriptImpl< Holder > Class Template Reference
SequentialTableReaderScriptImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from SequentialTableReaderImplBase< Holder >
typedef Holder::T T
Public Member Functions
SequentialTableReaderScriptImpl ()
virtual bool Open (const std::string &rspecifier)
virtual bool IsOpen () const
virtual bool Done () const
virtual std::string Key ()
const T & Value ()
void FreeCurrent ()
void Next ()
virtual bool Close ()
virtual ~SequentialTableReaderScriptImpl ()
Public Member Functions inherited from SequentialTableReaderImplBase< Holder >
SequentialTableReaderImplBase ()
virtual ~SequentialTableReaderImplBase ()
Private Types
enum StateType {
kUninitialized, kEof, kError, kHaveScpLine,
kLoadSucceeded, kLoadFailed, kFileStart
}
Private Member Functions
bool LoadCurrent ()
void NextScpLine ()
Private Attributes
Input script_input_
Input data_input_
Holder holder_
bool binary_
std::string key_
std::string rspecifier_
std::string script_rxfilename_
RspecifierOptions opts_
std::string data_rxfilename_
enum
kaldi::SequentialTableReaderScriptImpl::StateType state_
Detailed Description
template<class Holder>
class kaldi::SequentialTableReaderScriptImpl< Holder >
Definition at line 60 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef Holder::T T
Definition at line 63 of file kaldi-table-inl.h.
Member Enumeration Documentation
enum StateType private
Enumerator
kUninitialized
kEof
kError
kHaveScpLine
kLoadSucceeded
kLoadFailed
kFileStart
Definition at line 294 of file kaldi-table-inl.h.
                  {
     //       [The state of the reading process]    [does holder_ [is script_inp_
     //                                                      have object]   open]
     kUninitialized,  // Uninitialized or closed.                   no         no
     kEof,     // We did Next() and found eof in script file.       no         no
     kError,   // Some other error                                 no         yes
     kHaveScpLine,  // Just called Open() or Next() and have a     no         yes
     // line of the script file but no data.
     kLoadSucceeded,  // Called LoadCurrent() and it succeeded.   yes         yes
     kLoadFailed,  // Called LoadCurrent() and it failed,          no         yes
     // or the user called FreeCurrent().. note,
     // if when called by user we are in this state,
     // it means the user called FreeCurrent().
     kFileStart,        // [state we only use internally]          no         yes
   } state_;
Constructor & Destructor Documentation
SequentialTableReaderScriptImpl () inline
Definition at line 65 of file kaldi-table-inl.h.
 : state_(kUninitialized) { }
virtual ~SequentialTableReaderScriptImpl () inline virtual
Definition at line 214 of file kaldi-table-inl.h.
References SequentialTableReaderScriptImpl< Holder >::holder_, KALDI_ERR, SequentialTableReaderScriptImpl< Holder >::kError, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, kaldi::PrintableRxfilename(), SequentialTableReaderScriptImpl< Holder >::script_rxfilename_, and SequentialTableReaderScriptImpl< Holder >::state_.
{
     if (state_ == kError)
       KALDI_ERR << "TableReader: reading script file failed: from scp "
                 << PrintableRxfilename(script_rxfilename_);
     // If you don't want this exception to be thrown you can
     // call Close() and check the status.
     if (state_ == kLoadSucceeded)
       holder_.Clear();
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 187 of file kaldi-table-inl.h.
References Input::Close(), SequentialTableReaderScriptImpl< Holder >::data_input_, SequentialTableReaderScriptImpl< Holder >::holder_, SequentialTableReaderScriptImpl< Holder >::IsOpen(), Input::IsOpen(), KALDI_ERR, KALDI_WARN, SequentialTableReaderScriptImpl< Holder >::kError, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, SequentialTableReaderScriptImpl< Holder >::kUninitialized, SequentialTableReaderScriptImpl< Holder >::opts_, RspecifierOptions::permissive, SequentialTableReaderScriptImpl< Holder >::script_input_, and SequentialTableReaderScriptImpl< Holder >::state_.
Referenced by SequentialTableReaderScriptImpl< Holder >::Open().
{
     // Close() will succeed if the stream was not in an error
     // state.  To clean up, it also closes the Input objects if
     // they're open.
     if (script_input_.IsOpen())
       script_input_.Close();
     if (data_input_.IsOpen())
       data_input_.Close();
     if (state_ == kLoadSucceeded)
       holder_.Clear();
     if (!this->IsOpen())
       KALDI_ERR << "Close() called on input that was not open.";
     StateType old_state = state_;
     state_ = kUninitialized;
     if (old_state == kError) {
       if (opts_.permissive) {
         KALDI_WARN << "Close() called on scp file with read error, ignoring the"
             " error because permissive mode specified.";
         return true;
       } else {
         return false;  // User will do something with the error status.
       }
     } else {
       return true;
     }
   }
virtual bool Done () const inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 116 of file kaldi-table-inl.h.
References KALDI_ERR, SequentialTableReaderScriptImpl< Holder >::kEof, SequentialTableReaderScriptImpl< Holder >::kError, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, and SequentialTableReaderScriptImpl< Holder >::state_.
Referenced by SequentialTableReaderScriptImpl< Holder >::Next().
{
     switch (state_) {
       case kHaveScpLine: return false;
       case kLoadSucceeded: case kLoadFailed: return false;
         // These cases are because we want LoadCurrent()
         // to be callable after Next() and to not change the Done() status
         // [only Next() should change the Done() status].
       case kEof: case kError: return true;  // Error condition, like Eof, counts
         // as Done(); the destructor/Close() will inform the user of the error.
       default: KALDI_ERR << "Done() called on TableReader object at the wrong"
                             " time.";
         return false;
     }
   }
void FreeCurrent () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 163 of file kaldi-table-inl.h.
References SequentialTableReaderScriptImpl< Holder >::holder_, KALDI_WARN, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, and SequentialTableReaderScriptImpl< Holder >::state_.
                      {
     if (state_ == kLoadSucceeded) {
       holder_.Clear();
       state_ = kLoadFailed;
     } else {
       KALDI_WARN << "TableReader: FreeCurrent called at the wrong time.";
     }
   }
virtual bool IsOpen () const inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 104 of file kaldi-table-inl.h.
References KALDI_ERR, SequentialTableReaderScriptImpl< Holder >::kEof, SequentialTableReaderScriptImpl< Holder >::kError, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, SequentialTableReaderScriptImpl< Holder >::kUninitialized, and SequentialTableReaderScriptImpl< Holder >::state_.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close().
{
     switch (state_) {
       case kEof: case kError: case kHaveScpLine: case kLoadSucceeded:
       case kLoadFailed: return true;
       case kUninitialized:  return false;
       default: KALDI_ERR << "IsOpen() called on invalid object.";  // kFileStart
                                                                  // is not valid
         // state for user to call something on.
         return false;
     }
   }
virtual std::string Key () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 131 of file kaldi-table-inl.h.
References KALDI_ERR, SequentialTableReaderScriptImpl< Holder >::key_, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, and SequentialTableReaderScriptImpl< Holder >::state_.
{
     // Valid to call this whenever Done() returns false.
     switch (state_) {
       case kHaveScpLine: case kLoadSucceeded: case kLoadFailed: break;
       default:
         // coding error.
         KALDI_ERR << "Key() called on TableReader object at the wrong time.";
     }
     return key_;
   }
bool LoadCurrent () inline private
Definition at line 224 of file kaldi-table-inl.h.
References SequentialTableReaderScriptImpl< Holder >::data_input_, SequentialTableReaderScriptImpl< Holder >::data_rxfilename_, SequentialTableReaderScriptImpl< Holder >::holder_, KALDI_ERR, KALDI_WARN, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, Input::Open(), Input::OpenTextMode(), kaldi::PrintableRxfilename(), SequentialTableReaderScriptImpl< Holder >::state_, and Input::Stream().
Referenced by SequentialTableReaderScriptImpl< Holder >::Next(), and SequentialTableReaderScriptImpl< Holder >::Value().
                      {
     // Attempts to load object whose rxfilename is on the current scp line.
     if (state_ != kHaveScpLine)
       KALDI_ERR << "TableReader: LoadCurrent() called at the wrong time.";
     bool ans;
     // note, NULL means it doesn't read the binary-mode header
     if (Holder::IsReadInBinary()) {
       ans = data_input_.Open(data_rxfilename_, NULL);
     } else {
       ans = data_input_.OpenTextMode(data_rxfilename_);
     }
     if (!ans) {
       // May want to make this warning a VLOG at some point
       KALDI_WARN << "TableReader: failed to open file "
                  << PrintableRxfilename(data_rxfilename_);
       state_ = kLoadFailed;
       return false;
     } else {
       if (holder_.Read(data_input_.Stream())) {
         state_ = kLoadSucceeded;
         return true;
       } else {  // holder_ will not contain data.
         KALDI_WARN << "TableReader: failed to load object from "
                    << PrintableRxfilename(data_rxfilename_);
         state_ = kLoadFailed;
         return false;
       }
     }
   }
void Next () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 171 of file kaldi-table-inl.h.
References SequentialTableReaderScriptImpl< Holder >::Done(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), SequentialTableReaderScriptImpl< Holder >::opts_, and RspecifierOptions::permissive.
Referenced by SequentialTableReaderScriptImpl< Holder >::Open().
               {
     while (1) {
       NextScpLine();
       if (Done()) return;
       if (opts_.permissive) {
         // Permissive mode means, when reading scp files, we treat keys whose
         // scp entry cannot be read as nonexistent.  This means trying to read.
         if (LoadCurrent()) return;  // Success.
         // else try the next scp line.
       } else {
         return;  // We go the next key; Value() will crash if we can't
         // read the scp line.
       }
     }
   }
void NextScpLine () inline private
Definition at line 255 of file kaldi-table-inl.h.
References Input::Close(), SequentialTableReaderScriptImpl< Holder >::data_input_, SequentialTableReaderScriptImpl< Holder >::data_rxfilename_, SequentialTableReaderScriptImpl< Holder >::holder_, Input::IsOpen(), KALDI_ERR, SequentialTableReaderScriptImpl< Holder >::kEof, SequentialTableReaderScriptImpl< Holder >::kError, SequentialTableReaderScriptImpl< Holder >::key_, SequentialTableReaderScriptImpl< Holder >::kFileStart, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, SequentialTableReaderScriptImpl< Holder >::script_input_, kaldi::SplitStringOnFirstSpace(), SequentialTableReaderScriptImpl< Holder >::state_, and Input::Stream().
Referenced by SequentialTableReaderScriptImpl< Holder >::Next().
                      {
     switch (state_) {
       case kLoadSucceeded: holder_.Clear(); break;
       case kHaveScpLine: case kLoadFailed: case kFileStart: break;
       default:
         // No other states are valid to call Next() from.
         KALDI_ERR << "Reading script file: Next called wrongly.";
     }
     std::string line;
     if (getline(script_input_.Stream(), line)) {
       SplitStringOnFirstSpace(line, &key_, &data_rxfilename_);
       if (!key_.empty() && !data_rxfilename_.empty()) {
         // Got a valid line.
         state_ = kHaveScpLine;
       } else {
         // Got an invalid line.
         state_ = kError;  // we can't make sense of this
         // scp file and will now die.
       }
     } else {
       state_ = kEof;  // nothing more in the scp file.
       // Might as well close the input streams as don't need them.
       script_input_.Close();
       if (data_input_.IsOpen())
         data_input_.Close();
     }
   }
virtual bool Open (const std::string & rspecifier) inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 67 of file kaldi-table-inl.h.
References kaldi::ClassifyRspecifier(), SequentialTableReaderScriptImpl< Holder >::Close(), Input::Close(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, SequentialTableReaderScriptImpl< Holder >::kEof, SequentialTableReaderScriptImpl< Holder >::kError, SequentialTableReaderScriptImpl< Holder >::kFileStart, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, kaldi::kScriptRspecifier, SequentialTableReaderScriptImpl< Holder >::kUninitialized, SequentialTableReaderScriptImpl< Holder >::Next(), Input::Open(), SequentialTableReaderScriptImpl< Holder >::opts_, RspecifierOptions::permissive, kaldi::PrintableRxfilename(), SequentialTableReaderScriptImpl< Holder >::rspecifier_, SequentialTableReaderScriptImpl< Holder >::script_input_, SequentialTableReaderScriptImpl< Holder >::script_rxfilename_, and SequentialTableReaderScriptImpl< Holder >::state_.
{
     if (state_ != kUninitialized)
       if (!Close())  // call Close() yourself to suppress this exception.
         KALDI_ERR << "TableReader::Open, error closing previous input: "
                   << "rspecifier was " << rspecifier_;
     bool binary;
     rspecifier_ = rspecifier;
     RspecifierType rs = ClassifyRspecifier(rspecifier, &script_rxfilename_,
                                            &opts_);
     KALDI_ASSERT(rs == kScriptRspecifier);
     if (!script_input_.Open(script_rxfilename_, &binary)) {  // Failure on Open
       KALDI_WARN << "Failed to open script file "
                  << PrintableRxfilename(script_rxfilename_);
       state_ = kUninitialized;
       return false;
     } else {  // Open succeeded.
       if (binary) {  // script file should not be binary file..
         state_ = kError;  // bad script file.
         script_input_.Close();
         return false;
       } else {
         state_ = kFileStart;
         Next();
         if (state_ == kError) {
           script_input_.Close();
           return false;
         }
         if (opts_.permissive) {  // Next() will have preloaded.
           KALDI_ASSERT(state_ == kLoadSucceeded || state_ == kEof);
         } else {
           KALDI_ASSERT(state_ == kHaveScpLine || state_ == kEof);
         }
         return true;  // Success.
       }
     }
   }
const T& Value () inline virtual
Implements SequentialTableReaderImplBase< Holder >.
Definition at line 141 of file kaldi-table-inl.h.
References SequentialTableReaderScriptImpl< Holder >::data_rxfilename_, SequentialTableReaderScriptImpl< Holder >::holder_, KALDI_ERR, SequentialTableReaderScriptImpl< Holder >::kHaveScpLine, SequentialTableReaderScriptImpl< Holder >::kLoadFailed, SequentialTableReaderScriptImpl< Holder >::kLoadSucceeded, SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), kaldi::PrintableRxfilename(), and SequentialTableReaderScriptImpl< Holder >::state_.
                    {
     StateType orig_state = state_;
     if (state_ == kHaveScpLine) LoadCurrent();  // Takes
     // state_ to kLoadSucceeded or kLoadFailed.
     if (state_ == kLoadFailed) {  // this can happen due to
       // a file listed in an scp file not existing, or
       // read failure, failure of a command, etc.
       if (orig_state == kHaveScpLine)
         KALDI_ERR << "TableReader: failed to load object from "
                   << PrintableRxfilename(data_rxfilename_)
                   << " (to suppress this error, add the permissive "
                   << "(p, ) option to the rspecifier.";
       else  // orig_state_ was kLoadFailed, which only could have happened
         // if the user called FreeCurrent().
         KALDI_ERR << "TableReader: you called Value() after FreeCurrent().";
     } else if (state_ != kLoadSucceeded) {
       // This would be a coding error.
       KALDI_ERR << "TableReader: Value() called at the wrong time.";
     }
     return holder_.Value();
   }
Member Data Documentation
bool binary_ private
Definition at line 288 of file kaldi-table-inl.h.
Input data_input_ private
Definition at line 285 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), and SequentialTableReaderScriptImpl< Holder >::NextScpLine().
std::string data_rxfilename_ private
Definition at line 293 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), and SequentialTableReaderScriptImpl< Holder >::Value().
Holder holder_ private
Definition at line 287 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderScriptImpl< Holder >::FreeCurrent(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), SequentialTableReaderScriptImpl< Holder >::Value(), and SequentialTableReaderScriptImpl< Holder >::~SequentialTableReaderScriptImpl().
std::string key_ private
Definition at line 289 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Key(), and SequentialTableReaderScriptImpl< Holder >::NextScpLine().
RspecifierOptions opts_ private
Definition at line 292 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderScriptImpl< Holder >::Next(), and SequentialTableReaderScriptImpl< Holder >::Open().
std::string rspecifier_ private
Definition at line 290 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Open().
Input script_input_ private
Definition at line 284 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), and SequentialTableReaderScriptImpl< Holder >::Open().
std::string script_rxfilename_ private
Definition at line 291 of file kaldi-table-inl.h.
Referenced by SequentialTableReaderScriptImpl< Holder >::Open(), and SequentialTableReaderScriptImpl< Holder >::~SequentialTableReaderScriptImpl().
enum kaldi::SequentialTableReaderScriptImpl::StateType state_ private
Referenced by SequentialTableReaderScriptImpl< Holder >::Close(), SequentialTableReaderScriptImpl< Holder >::Done(), SequentialTableReaderScriptImpl< Holder >::FreeCurrent(), SequentialTableReaderScriptImpl< Holder >::IsOpen(), SequentialTableReaderScriptImpl< Holder >::Key(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), SequentialTableReaderScriptImpl< Holder >::NextScpLine(), SequentialTableReaderScriptImpl< Holder >::Open(), SequentialTableReaderScriptImpl< Holder >::Value(), and SequentialTableReaderScriptImpl< Holder >::~SequentialTableReaderScriptImpl().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h