Kaldi: TableWriterScriptImpl< Holder > Class Template Reference
TableWriterScriptImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from TableWriterImplBase< Holder >
typedef Holder::T T
Public Member Functions
TableWriterScriptImpl ()
virtual bool Open (const std::string &wspecifier)
virtual bool IsOpen () const
virtual bool Close ()
virtual bool Write (const std::string &key, const T &value)
virtual void Flush ()
virtual ~TableWriterScriptImpl ()
Public Member Functions inherited from TableWriterImplBase< Holder >
virtual ~TableWriterImplBase ()
TableWriterImplBase ()
Private Types
enum { kUninitialized, kReadScript, kNotReadScript }
Private Member Functions
bool LookupFilename (const std::string &key, std::string *wxfilename)
Private Attributes
WspecifierOptions opts_
std::string wspecifier_
std::string script_rxfilename_
std::vector< std::pair
< std::string, std::string > > script_
size_t last_found_
enum
kaldi::TableWriterScriptImpl:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::TableWriterScriptImpl< Holder >
Definition at line 804 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef Holder::T T
Definition at line 806 of file kaldi-table-inl.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kUninitialized
kReadScript
kNotReadScript
Definition at line 945 of file kaldi-table-inl.h.
        {
     kUninitialized,
     kReadScript,
     kNotReadScript,  // read of script failed.
   } state_;
Constructor & Destructor Documentation
TableWriterScriptImpl () inline
Definition at line 808 of file kaldi-table-inl.h.
 : last_found_(0), state_(kUninitialized) {}
virtual ~TableWriterScriptImpl () inline virtual
Definition at line 900 of file kaldi-table-inl.h.
{
     // Nothing to do in destructor.
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 848 of file kaldi-table-inl.h.
References TableWriterScriptImpl< Holder >::IsOpen(), KALDI_ERR, TableWriterScriptImpl< Holder >::kUninitialized, TableWriterScriptImpl< Holder >::last_found_, TableWriterScriptImpl< Holder >::script_, and TableWriterScriptImpl< Holder >::state_.
{
     if (!IsOpen())
       KALDI_ERR << "Close() called on TableWriter that was not open.";
     state_ = kUninitialized;
     last_found_ = 0;
     script_.clear();
     return true;
   }
virtual void Flush () inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 897 of file kaldi-table-inl.h.
 { }
virtual bool IsOpen () const inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 846 of file kaldi-table-inl.h.
References TableWriterScriptImpl< Holder >::kReadScript, and TableWriterScriptImpl< Holder >::state_.
Referenced by TableWriterScriptImpl< Holder >::Close(), and TableWriterScriptImpl< Holder >::Write().
 {  return (state_ == kReadScript);  }
bool LookupFilename (const std::string & key, std::string * wxfilename) inline private
Definition at line 907 of file kaldi-table-inl.h.
References TableWriterScriptImpl< Holder >::last_found_, and TableWriterScriptImpl< Holder >::script_.
Referenced by TableWriterScriptImpl< Holder >::Write().
{
     // First, an optimization: if we're going consecutively, this will
     // make the lookup very fast.
     last_found_++;
     if (last_found_ < script_.size() && script_[last_found_].first == key) {
       *wxfilename = script_[last_found_].second;
       return true;
     }
     std::pair<std::string, std::string> pr(key, "");  // Important that ""
     // compares less than or equal to any string, so lower_bound points to the
     // element that has the same key.
     typedef typename std::vector<std::pair<std::string, std::string> >
                      ::const_iterator IterType;
     IterType iter = std::lower_bound(script_.begin(), script_.end(), pr);
     if (iter != script_.end() && iter->first == key) {
       last_found_ = iter - script_.begin();
       *wxfilename = iter->second;
       return true;
     } else {
       return false;
     }
   }
virtual bool Open (const std::string & wspecifier) inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 810 of file kaldi-table-inl.h.
References kaldi::ClassifyWspecifier(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_WARN, TableWriterScriptImpl< Holder >::kNotReadScript, TableWriterScriptImpl< Holder >::kReadScript, kaldi::kScriptWspecifier, TableWriterScriptImpl< Holder >::kUninitialized, TableWriterScriptImpl< Holder >::opts_, kaldi::PrintableRxfilename(), kaldi::ReadScriptFile(), TableWriterScriptImpl< Holder >::script_, TableWriterScriptImpl< Holder >::script_rxfilename_, TableWriterScriptImpl< Holder >::state_, and TableWriterScriptImpl< Holder >::wspecifier_.
{
     switch (state_) {
       case kReadScript:
         KALDI_ERR << " Opening already open TableWriter: call Close first.";
       case kUninitialized: case kNotReadScript:
         break;
     }
     wspecifier_ = wspecifier;
     WspecifierType ws = ClassifyWspecifier(wspecifier,
                                            NULL,
                                            &script_rxfilename_,
                                            &opts_);
     KALDI_ASSERT(ws == kScriptWspecifier);  // or wrongly called.
     KALDI_ASSERT(script_.empty());  // no way it could be nonempty at this poin.
     if (!ReadScriptFile(script_rxfilename_,
                          true,  // print any warnings
                          &script_)) {  // error reading script file or invalid
                                        // format
       state_ = kNotReadScript;
       return false;  // no need to print further warnings.  user gets the error.
     }
     std::sort(script_.begin(), script_.end());
     for (size_t i = 0; i+1 < script_.size(); i++) {
       if (script_[i].first.compare(script_[i+1].first) >= 0) {
         // script[i] not < script[i+1] in lexical order...
         KALDI_WARN << "Script file " << PrintableRxfilename(script_rxfilename_)
                    << " contains duplicate key " << script_[i].first;
         state_ = kNotReadScript;
         return false;
       }
     }
     state_ = kReadScript;
     return true;
   }
virtual bool Write (const std::string & key, const T & value) inline virtual
Implements TableWriterImplBase< Holder >.
Definition at line 859 of file kaldi-table-inl.h.
References WspecifierOptions::binary, Output::Close(), TableWriterScriptImpl< Holder >::IsOpen(), kaldi::IsToken(), KALDI_ERR, KALDI_WARN, TableWriterScriptImpl< Holder >::LookupFilename(), Output::Open(), TableWriterScriptImpl< Holder >::opts_, WspecifierOptions::permissive, kaldi::PrintableRxfilename(), kaldi::PrintableWxfilename(), TableWriterScriptImpl< Holder >::script_rxfilename_, and Output::Stream().
{
     if (!IsOpen())
       KALDI_ERR << "TableWriter: Write called on invalid stream";
     if (!IsToken(key))  // e.g. empty string or has spaces...
       KALDI_ERR << "TableWriter: using invalid key " << key;
     std::string wxfilename;
     if (!LookupFilename(key, &wxfilename)) {
       if (opts_.permissive) {
         return true;  // In permissive mode, it's as if we're writing to
                      // /dev/null for missing keys.
       } else {
         KALDI_WARN << "TableWriter: script file "
                    << PrintableRxfilename(script_rxfilename_)
                    << " has no entry for key " <<key;
         return false;
       }
     }
     Output output;
     if (!output.Open(wxfilename, opts_.binary, false)) {
       // Open in the text/binary mode (on Windows) given by member var. "binary"
       // (obtained from wspecifier), but do not put the binary-mode header (it
       // will be written, if needed, by the Holder::Write function.)
       KALDI_WARN << "TableWriter: failed to open stream: "
                  << PrintableWxfilename(wxfilename);
       return false;
     }
     if (!Holder::Write(output.Stream(), opts_.binary, value)
         || !output.Close()) {
       KALDI_WARN << "TableWriter: failed to write data to "
                  << PrintableWxfilename(wxfilename);
       return false;
     }
     return true;
   }
Member Data Documentation
size_t last_found_ private
Definition at line 943 of file kaldi-table-inl.h.
Referenced by TableWriterScriptImpl< Holder >::Close(), and TableWriterScriptImpl< Holder >::LookupFilename().
WspecifierOptions opts_ private
Definition at line 931 of file kaldi-table-inl.h.
Referenced by TableWriterScriptImpl< Holder >::Open(), and TableWriterScriptImpl< Holder >::Write().
std::vector<std::pair<std::string, std::string> > script_ private
Definition at line 942 of file kaldi-table-inl.h.
Referenced by TableWriterScriptImpl< Holder >::Close(), TableWriterScriptImpl< Holder >::LookupFilename(), and TableWriterScriptImpl< Holder >::Open().
std::string script_rxfilename_ private
Definition at line 933 of file kaldi-table-inl.h.
Referenced by TableWriterScriptImpl< Holder >::Open(), and TableWriterScriptImpl< Holder >::Write().
enum { ... } state_
Referenced by TableWriterScriptImpl< Holder >::Close(), TableWriterScriptImpl< Holder >::IsOpen(), and TableWriterScriptImpl< Holder >::Open().
std::string wspecifier_ private
Definition at line 932 of file kaldi-table-inl.h.
Referenced by TableWriterScriptImpl< Holder >::Open().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h