Kaldi: GeneralMatrix Class Reference
GeneralMatrix Class Reference
%Matrix and vector classes
This class is a wrapper that enables you to store a matrix in one of three forms: either as a Matrix<BaseFloat>, or a CompressedMatrix, or a SparseMatrix<BaseFloat>.
#include <sparse-matrix.h>
Public Member Functions
GeneralMatrixType Type () const
void Compress ()
void Uncompress ()
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Note: if you write a compressed matrix in text form, it will be read as a regular full matrix.
const SparseMatrix< BaseFloat > & GetSparseMatrix () const
Returns the contents as a SparseMatrix.
void SwapSparseMatrix (SparseMatrix< BaseFloat > *smat)
Swaps the with the given SparseMatrix.
const CompressedMatrix & GetCompressedMatrix () const
Returns the contents as a compressed matrix.
const Matrix< BaseFloat > & GetFullMatrix () const
Returns the contents as a Matrix<BaseFloat>.
void GetMatrix (Matrix< BaseFloat > *mat) const
Outputs the contents as a matrix.
void SwapFullMatrix (Matrix< BaseFloat > *mat)
Swaps the with the given Matrix.
void CopyToMat (MatrixBase< BaseFloat > *mat, MatrixTransposeType trans=kNoTrans) const
Copies contents, regardless of type, to "mat", which must be correctly sized.
void CopyToMat (CuMatrixBase< BaseFloat > *cu_mat, MatrixTransposeType trans=kNoTrans) const
Copies contents, regardless of type, to "cu_mat", which must be correctly sized.
void AddToMat (BaseFloat alpha, MatrixBase< BaseFloat > *mat, MatrixTransposeType trans=kNoTrans) const
Adds alpha times *this to mat.
void AddToMat (BaseFloat alpha, CuMatrixBase< BaseFloat > *cu_mat, MatrixTransposeType trans=kNoTrans) const
Adds alpha times *this to cu_mat.
GeneralMatrix & operator= (const MatrixBase< BaseFloat > &mat)
Assignment from regular matrix.
GeneralMatrix & operator= (const CompressedMatrix &mat)
Assignment from compressed matrix.
GeneralMatrix & operator= (const SparseMatrix< BaseFloat > &smat)
Assignment from SparseMatrix<BaseFloat>
MatrixIndexT NumRows () const
MatrixIndexT NumCols () const
GeneralMatrix (const MatrixBase< BaseFloat > &mat)
GeneralMatrix (const CompressedMatrix &cmat)
GeneralMatrix (const SparseMatrix< BaseFloat > &smat)
GeneralMatrix ()
GeneralMatrix & operator= (const GeneralMatrix &other)
GeneralMatrix (const GeneralMatrix &other)
void Clear ()
void Swap (GeneralMatrix *other)
Private Attributes
Matrix< BaseFloat > mat_
CompressedMatrix cmat_
SparseMatrix< BaseFloat > smat_
Detailed Description
This class is a wrapper that enables you to store a matrix in one of three forms: either as a Matrix<BaseFloat>, or a CompressedMatrix, or a SparseMatrix<BaseFloat>.
It handles the I/O for you, i.e. you read and write a single object type. It is useful for neural-net training targets which might be sparse or not, and might be compressed or not.
Definition at line 227 of file sparse-matrix.h.
Constructor & Destructor Documentation
GeneralMatrix (const MatrixBase< BaseFloat > & mat) inline explicit
Definition at line 300 of file sparse-matrix.h.
 { *this = mat; }
GeneralMatrix (const CompressedMatrix & cmat) inline explicit
Definition at line 302 of file sparse-matrix.h.
 { *this = cmat; }
GeneralMatrix (const SparseMatrix< BaseFloat > & smat) inline explicit
Definition at line 304 of file sparse-matrix.h.
 { *this = smat; }
GeneralMatrix () inline
Definition at line 306 of file sparse-matrix.h.
 { }
GeneralMatrix (const GeneralMatrix & other) inline
Definition at line 310 of file sparse-matrix.h.
 { *this = other; }
Member Function Documentation
void AddToMat (BaseFloat alpha, MatrixBase< BaseFloat > * mat, MatrixTransposeType trans = kNoTrans) const
Adds alpha times *this to mat.
Definition at line 1034 of file sparse-matrix.cc.
References MatrixBase< Real >::AddMat(), SparseMatrix< Real >::AddToMat(), GeneralMatrix::cmat_, KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kSparseMatrix, GeneralMatrix::mat_, GeneralMatrix::smat_, and GeneralMatrix::Type().
{
   switch (this->Type()) {
     case kFullMatrix: {
       mat->AddMat(alpha, mat_, trans);
       break;
     }
     case kSparseMatrix: {
       smat_.AddToMat(alpha, mat, trans);
       break;
     }
     case kCompressedMatrix: {
       Matrix<BaseFloat> temp_mat(cmat_);
       mat->AddMat(alpha, temp_mat, trans);
       break;
     }
     default:
       KALDI_ERR << "Invalid general-matrix type.";
   }
 }
void AddToMat (BaseFloat alpha, CuMatrixBase< BaseFloat > * cu_mat, MatrixTransposeType trans = kNoTrans) const
Adds alpha times *this to cu_mat.
Implemented in ../cudamatrix/cu-sparse-matrix.cc
Definition at line 441 of file cu-sparse-matrix.cc.
References CuMatrixBase< Real >::AddMat(), MatrixBase< Real >::AddMat(), SparseMatrix< Real >::AddToMat(), GeneralMatrix::cmat_, CuSparseMatrix< Real >::CopyToMat(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kNoTrans, kaldi::kSparseMatrix, kaldi::kUndefined, CuMatrixBase< Real >::Mat(), GeneralMatrix::mat_, CuSparseMatrix< Real >::NumCols(), CuSparseMatrix< Real >::NumRows(), GeneralMatrix::smat_, and GeneralMatrix::Type().
{
   switch (Type()) {
     case kFullMatrix: {
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         CuMatrix<BaseFloat> cu_copy(mat_);
         cu_mat->AddMat(alpha, cu_copy);
         break;
       }
 #endif
       cu_mat->Mat().AddMat(alpha, mat_);
       break;
     }
     case kSparseMatrix: {
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         // TODO: we could make this more efficient by
         // implementing an AddSmat function in class CuMatrixBase.
         CuSparseMatrix<BaseFloat> sparse_cu_mat(smat_);
         CuMatrix<BaseFloat> cu_temp(
             trans == kNoTrans ? sparse_cu_mat.NumRows() :
                                 sparse_cu_mat.NumCols(),
             trans == kNoTrans ? sparse_cu_mat.NumCols() :
                                 sparse_cu_mat.NumRows(),
             kUndefined);
         sparse_cu_mat.CopyToMat(&cu_temp, trans);
         cu_mat->AddMat(alpha, cu_temp, kNoTrans);
         break;
       }
 #endif
       smat_.AddToMat(alpha, &(cu_mat->Mat()), trans);
       break;
     }
     case kCompressedMatrix: {
       Matrix<BaseFloat> mat(cmat_);
 #if HAVE_CUDA == 1
       if (CuDevice::Instantiate().Enabled()) {
         CuMatrix<BaseFloat> cu_mat_copy(mat);
         cu_mat->AddMat(alpha, cu_mat_copy, trans);
         break;
       }
 #endif
       cu_mat->Mat().AddMat(alpha, mat, trans);
       break;
     }
     default:
       KALDI_ERR << "Invalid GeneralMatrix type.";
   }
 }
void Clear ()
Definition at line 646 of file sparse-matrix.cc.
References CompressedMatrix::Clear(), GeneralMatrix::cmat_, GeneralMatrix::mat_, SparseMatrix< Real >::Resize(), Matrix< Real >::Resize(), and GeneralMatrix::smat_.
Referenced by kaldi::AppendGeneralMatrixRows(), kaldi::FilterGeneralMatrixRows(), GeneralMatrix::operator=(), GeneralMatrix::Read(), and kaldi::UnitTestGeneralMatrix().
{
   mat_.Resize(0, 0);
   cmat_.Clear();
   smat_.Resize(0, 0);
 }
void Compress ()
Definition at line 708 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, CompressedMatrix::CopyFromMat(), GeneralMatrix::mat_, MatrixBase< Real >::NumRows(), and Matrix< Real >::Resize().
Referenced by kaldi::nnet3::GenerateSimpleNnetTrainingExample(), and kaldi::UnitTestGeneralMatrix().
{
   if (mat_.NumRows() != 0) {
     cmat_.CopyFromMat(mat_);
     mat_.Resize(0, 0);
   }
 }
void CopyToMat (MatrixBase< BaseFloat > * mat, MatrixTransposeType trans = kNoTrans) const
Copies contents, regardless of type, to "mat", which must be correctly sized.
See also GetMatrix(), which will size its output for you.
Definition at line 736 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, MatrixBase< Real >::CopyFromMat(), CompressedMatrix::CopyToMat(), SparseMatrix< Real >::CopyToMat(), KALDI_ASSERT, GeneralMatrix::mat_, MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), and GeneralMatrix::smat_.
Referenced by kaldi::AppendGeneralMatrixRows(), and GeneralMatrix::CopyToMat().
{
   if (mat_.NumRows() !=0) {
     mat->CopyFromMat(mat_, trans);
   } else if (cmat_.NumRows() != 0) {
     cmat_.CopyToMat(mat, trans);
   } else if (smat_.NumRows() != 0) {
     smat_.CopyToMat(mat, trans);
   } else {
     KALDI_ASSERT(mat->NumRows() == 0);
   }
 }
void CopyToMat (CuMatrixBase< BaseFloat > * cu_mat, MatrixTransposeType trans = kNoTrans) const
Copies contents, regardless of type, to "cu_mat", which must be correctly sized.
Implemented in ../cudamatrix/cu-sparse-matrix.cc
Definition at line 351 of file cu-sparse-matrix.cc.
References GeneralMatrix::cmat_, CuMatrixBase< Real >::CopyFromMat(), CuSparseMatrix< Real >::CopyToMat(), GeneralMatrix::CopyToMat(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kNoTrans, kaldi::kSparseMatrix, kaldi::kTrans, CuMatrixBase< Real >::Mat(), GeneralMatrix::mat_, GeneralMatrix::smat_, CuMatrix< Real >::Swap(), and GeneralMatrix::Type().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     switch (Type()) {
       case kFullMatrix: {
         cu_mat->CopyFromMat(mat_);
         break;
       }
       case kSparseMatrix: {
         CuSparseMatrix<BaseFloat> smat(smat_);
         smat.CopyToMat(cu_mat, trans);
         break;
       }
       case kCompressedMatrix: {
         Matrix<BaseFloat> mat(cmat_);
         if (trans == kNoTrans) {
           cu_mat->CopyFromMat(mat);
           break;
         } else {
           CuMatrix<BaseFloat> temp_cu;
           temp_cu.Swap(&mat);
           cu_mat->CopyFromMat(temp_cu, kTrans);
           break;
         }
       }
       default:
         KALDI_ERR << "Invalid GeneralMatrix type.";
     }
     return;
   } else
 #endif
   {
     CopyToMat(&(cu_mat->Mat()), trans);
   }
 }
const CompressedMatrix & GetCompressedMatrix () const
Returns the contents as a compressed matrix.
This will only work if Type() returns kCompressedMatrix, or NumRows() == 0; otherwise it will crash.
Definition at line 761 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, KALDI_ERR, GeneralMatrix::mat_, MatrixBase< Real >::NumRows(), SparseMatrix< Real >::NumRows(), and GeneralMatrix::smat_.
Referenced by kaldi::FilterGeneralMatrixRows().
{
   if (mat_.NumRows() != 0 || smat_.NumRows() != 0)
     KALDI_ERR << "GetCompressedMatrix called on GeneralMatrix of wrong type.";
   return cmat_;
 }
const Matrix< BaseFloat > & GetFullMatrix () const
Returns the contents as a Matrix<BaseFloat>.
This will only work if Type() returns kFullMatrix, or NumRows() == 0; otherwise it will crash.
Definition at line 767 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, KALDI_ERR, GeneralMatrix::mat_, CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), and GeneralMatrix::smat_.
Referenced by kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< Real >::CopyFromGeneralMat(), and kaldi::FilterGeneralMatrixRows().
{
   if (smat_.NumRows() != 0 || cmat_.NumRows() != 0)
     KALDI_ERR << "GetFullMatrix called on GeneralMatrix of wrong type.";
   return mat_;
 }
void GetMatrix (Matrix< BaseFloat > * mat) const
Outputs the contents as a matrix.
This will work regardless of Type(). Sizes its output, unlike CopyToMat().
Definition at line 722 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, CompressedMatrix::CopyToMat(), SparseMatrix< Real >::CopyToMat(), kaldi::kUndefined, GeneralMatrix::mat_, CompressedMatrix::NumCols(), SparseMatrix< Real >::NumCols(), MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), Matrix< Real >::Resize(), and GeneralMatrix::smat_.
Referenced by kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< Real >::CopyFromGeneralMat(), kaldi::nnet3::ExampleApproxEqual(), NnetIo::operator==(), and kaldi::UnitTestGeneralMatrix().
{
   if (mat_.NumRows() !=0) {
     *mat = mat_;
   } else if (cmat_.NumRows() != 0) {
     mat->Resize(cmat_.NumRows(), cmat_.NumCols(), kUndefined);
     cmat_.CopyToMat(mat);
   } else if (smat_.NumRows() != 0) {
     mat->Resize(smat_.NumRows(), smat_.NumCols(), kUndefined);
     smat_.CopyToMat(mat);
   } else {
     mat->Resize(0, 0);
   }
 }
const SparseMatrix< BaseFloat > & GetSparseMatrix () const
Returns the contents as a SparseMatrix.
This will only work if Type() returns kSparseMatrix, or NumRows() == 0; otherwise it will crash.
Definition at line 749 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, KALDI_ERR, GeneralMatrix::mat_, MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), and GeneralMatrix::smat_.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< Real >::CopyFromGeneralMat(), and kaldi::FilterGeneralMatrixRows().
{
   if (mat_.NumRows() != 0 || cmat_.NumRows() != 0)
     KALDI_ERR << "GetSparseMatrix called on GeneralMatrix of wrong type.";
   return smat_;
 }
MatrixIndexT NumCols () const
Definition at line 697 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, MatrixBase< Real >::NumCols(), CompressedMatrix::NumCols(), SparseMatrix< Real >::NumCols(), and GeneralMatrix::smat_.
Referenced by NnetComputer::AcceptInputs(), NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::AppendGeneralMatrixRows(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet3::GetIoSizes(), NnetIo::operator==(), NnetComputeProb::ProcessOutputs(), and kaldi::UnitTestGeneralMatrix().
{
   MatrixIndexT r = smat_.NumCols();
   if (r != 0)
     return r;
   r = cmat_.NumCols();
   if (r != 0)
     return r;
   return mat_.NumCols();
 }
MatrixIndexT NumRows () const
Definition at line 687 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), and GeneralMatrix::smat_.
Referenced by NnetComputer::AcceptInputs(), NnetLdaStatsAccumulator::AccStatsFromOutput(), kaldi::AppendGeneralMatrixRows(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), kaldi::nnet3::FilterExample(), kaldi::FilterGeneralMatrixRows(), kaldi::nnet3::GetIoSizes(), NnetIo::operator==(), kaldi::UnitTestGeneralMatrix(), and NnetIo::Write().
{
   MatrixIndexT r = smat_.NumRows();
   if (r != 0)
     return r;
   r = cmat_.NumRows();
   if (r != 0)
     return r;
   return mat_.NumRows();
 }
GeneralMatrix & operator= (const MatrixBase< BaseFloat > & mat)
Assignment from regular matrix.
Definition at line 652 of file sparse-matrix.cc.
References GeneralMatrix::Clear(), and GeneralMatrix::mat_.
{
   Clear();
   mat_ = mat;
   return *this;
 }
GeneralMatrix & operator= (const CompressedMatrix & mat)
Assignment from compressed matrix.
Definition at line 658 of file sparse-matrix.cc.
References GeneralMatrix::Clear(), and GeneralMatrix::cmat_.
{
   Clear();
   cmat_ = cmat;
   return *this;
 }
GeneralMatrix & operator= (const SparseMatrix< BaseFloat > & smat)
Assignment from SparseMatrix<BaseFloat>
Definition at line 664 of file sparse-matrix.cc.
References GeneralMatrix::Clear(), and GeneralMatrix::smat_.
{
   Clear();
   smat_ = smat;
   return *this;
 }
GeneralMatrix & operator= (const GeneralMatrix & other)
Definition at line 670 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, and GeneralMatrix::smat_.
{
   mat_ = gmat.mat_;
   smat_ = gmat.smat_;
   cmat_ = gmat.cmat_;
   return *this;
 }
void Read (std::istream & is, bool binary)
Note: if you write a compressed matrix in text form, it will be read as a regular full matrix.
Definition at line 790 of file sparse-matrix.cc.
References GeneralMatrix::Clear(), GeneralMatrix::cmat_, GeneralMatrix::mat_, CompressedMatrix::Read(), SparseMatrix< Real >::Read(), Matrix< Real >::Read(), and GeneralMatrix::smat_.
Referenced by NnetIo::Read(), and kaldi::UnitTestGeneralMatrix().
{
   Clear();
   if (binary) {
     int peekval = is.peek();
     if (peekval == 'C') {
       // Token CM for compressed matrix
       cmat_.Read(is, binary);
     } else if (peekval == 'S') {
       // Token SM for sparse matrix
       smat_.Read(is, binary);
     } else {
       mat_.Read(is, binary);
     }
   } else {
     // note: in text mode we will only ever read regular
     // or sparse matrices, because the compressed-matrix format just
     // gets written as a regular matrix in text mode.
     is >> std::ws;  // Eat up white space.
     int peekval = is.peek();
     if (peekval == 'r') {  // sparse format starts rows=[int].
       smat_.Read(is, binary);
     } else {
       mat_.Read(is, binary);
     }
   }
 }
void Swap (GeneralMatrix * other)
Definition at line 1101 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, GeneralMatrix::smat_, CompressedMatrix::Swap(), SparseMatrix< Real >::Swap(), and Matrix< Real >::Swap().
Referenced by NnetIo::Swap().
{
   mat_.Swap(&(other->mat_));
   cmat_.Swap(&(other->cmat_));
   smat_.Swap(&(other->smat_));
 }
void SwapFullMatrix (Matrix< BaseFloat > * mat)
Swaps the with the given Matrix.
This will only work if Type() returns kFullMatrix, or NumRows() == 0.
Definition at line 774 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, KALDI_ERR, GeneralMatrix::mat_, CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), GeneralMatrix::smat_, and Matrix< Real >::Swap().
Referenced by kaldi::AppendGeneralMatrixRows(), and kaldi::FilterGeneralMatrixRows().
{
   if (cmat_.NumRows() != 0 || smat_.NumRows() != 0)
     KALDI_ERR << "SwapMatrix called on GeneralMatrix of wrong type.";
   mat->Swap(&mat_);
 }
void SwapSparseMatrix (SparseMatrix< BaseFloat > * smat)
Swaps the with the given SparseMatrix.
This will only work if Type() returns kSparseMatrix, or NumRows() == 0.
Definition at line 755 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, KALDI_ERR, GeneralMatrix::mat_, MatrixBase< Real >::NumRows(), CompressedMatrix::NumRows(), GeneralMatrix::smat_, and SparseMatrix< Real >::Swap().
Referenced by kaldi::AppendGeneralMatrixRows(), kaldi::FilterGeneralMatrixRows(), and kaldi::UnitTestGeneralMatrix().
{
   if (mat_.NumRows() != 0 || cmat_.NumRows() != 0)
     KALDI_ERR << "GetSparseMatrix called on GeneralMatrix of wrong type.";
   smat->Swap(&smat_);
 }
GeneralMatrixType Type () const
Definition at line 678 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kSparseMatrix, CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), and GeneralMatrix::smat_.
Referenced by NnetLdaStatsAccumulator::AccStatsFromOutput(), GeneralMatrix::AddToMat(), kaldi::nnet3::ComputeAccuracy(), kaldi::nnet3::ComputeObjectiveFunction(), CuMatrixBase< Real >::CopyFromGeneralMat(), GeneralMatrix::CopyToMat(), and kaldi::FilterGeneralMatrixRows().
{
   if (smat_.NumRows() != 0)
     return kSparseMatrix;
   else if (cmat_.NumRows() != 0)
     return kCompressedMatrix;
   else
     return kFullMatrix;
 }
void Uncompress ()
Definition at line 715 of file sparse-matrix.cc.
References CompressedMatrix::Clear(), GeneralMatrix::cmat_, CompressedMatrix::CopyToMat(), GeneralMatrix::mat_, and CompressedMatrix::NumRows().
{
   if (cmat_.NumRows() != 0) {
     cmat_.CopyToMat(&mat_);
     cmat_.Clear();
   }
 }
void Write (std::ostream & os, bool binary) const
Definition at line 780 of file sparse-matrix.cc.
References GeneralMatrix::cmat_, GeneralMatrix::mat_, CompressedMatrix::NumRows(), SparseMatrix< Real >::NumRows(), GeneralMatrix::smat_, CompressedMatrix::Write(), SparseMatrix< Real >::Write(), and MatrixBase< Real >::Write().
Referenced by kaldi::UnitTestGeneralMatrix(), and NnetIo::Write().
{
   if (smat_.NumRows() != 0) {
     smat_.Write(os, binary);
   } else if (cmat_.NumRows() != 0) {
     cmat_.Write(os, binary);
   } else {
     mat_.Write(os, binary);
   }
 }
Member Data Documentation
CompressedMatrix cmat_ private
Definition at line 320 of file sparse-matrix.h.
Referenced by GeneralMatrix::AddToMat(), GeneralMatrix::Clear(), GeneralMatrix::Compress(), GeneralMatrix::CopyToMat(), GeneralMatrix::GetCompressedMatrix(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), GeneralMatrix::NumCols(), GeneralMatrix::NumRows(), GeneralMatrix::operator=(), GeneralMatrix::Read(), GeneralMatrix::Swap(), GeneralMatrix::SwapFullMatrix(), GeneralMatrix::SwapSparseMatrix(), GeneralMatrix::Type(), GeneralMatrix::Uncompress(), and GeneralMatrix::Write().
Matrix<BaseFloat> mat_ private
Definition at line 319 of file sparse-matrix.h.
Referenced by GeneralMatrix::AddToMat(), GeneralMatrix::Clear(), GeneralMatrix::Compress(), GeneralMatrix::CopyToMat(), GeneralMatrix::GetCompressedMatrix(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), GeneralMatrix::NumCols(), GeneralMatrix::NumRows(), GeneralMatrix::operator=(), GeneralMatrix::Read(), GeneralMatrix::Swap(), GeneralMatrix::SwapFullMatrix(), GeneralMatrix::SwapSparseMatrix(), GeneralMatrix::Uncompress(), and GeneralMatrix::Write().
SparseMatrix<BaseFloat> smat_ private
Definition at line 321 of file sparse-matrix.h.
Referenced by GeneralMatrix::AddToMat(), GeneralMatrix::Clear(), GeneralMatrix::CopyToMat(), GeneralMatrix::GetCompressedMatrix(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), GeneralMatrix::NumCols(), GeneralMatrix::NumRows(), GeneralMatrix::operator=(), GeneralMatrix::Read(), GeneralMatrix::Swap(), GeneralMatrix::SwapFullMatrix(), GeneralMatrix::SwapSparseMatrix(), GeneralMatrix::Type(), and GeneralMatrix::Write().
The documentation for this class was generated from the following files:
matrix/sparse-matrix.h
matrix/sparse-matrix.cc
cudamatrix/cu-sparse-matrix.cc