Kaldi: OnlineDeltaFeature Class Reference
OnlineDeltaFeature Class Reference
OnlineFeatureExtraction
#include <online-feature.h>
Public Member Functions
virtual int32 Dim () const
virtual bool IsLastFrame (int32 frame) const
Returns true if this is the last frame.
virtual int32 NumFramesReady () const
returns the feature dimension.
virtual void GetFrame (int32 frame, VectorBase< BaseFloat > *feat)
Gets the feature vector for this frame.
OnlineDeltaFeature (const DeltaFeaturesOptions &opts, OnlineFeatureInterface *src)
Public Member Functions inherited from OnlineFeatureInterface
virtual ~OnlineFeatureInterface ()
Virtual destructor.
Private Attributes
OnlineFeatureInterface * src_
DeltaFeaturesOptions opts_
DeltaFeatures delta_features_
Detailed Description
Definition at line 454 of file online-feature.h.
Constructor & Destructor Documentation
OnlineDeltaFeature (const DeltaFeaturesOptions & opts, OnlineFeatureInterface * src)
Definition at line 468 of file online-feature.cc.
                                                                    :
     src_(src), opts_(opts), delta_features_(opts) { }
Member Function Documentation
int32 Dim () const virtual
Implements OnlineFeatureInterface.
Definition at line 425 of file online-feature.cc.
References OnlineFeatureInterface::Dim(), OnlineDeltaFeature::opts_, DeltaFeaturesOptions::order, and OnlineDeltaFeature::src_.
Referenced by OnlineDeltaFeature::GetFrame().
{
   int32 src_dim = src_->Dim();
   return src_dim * (1 + opts_.order);
 }
void GetFrame (int32 frame, VectorBase< BaseFloat > * feat) virtual
Gets the feature vector for this frame.
Before calling this for a given frame, it is assumed that you called NumFramesReady() and it returned a number greater than "frame". Otherwise this call will likely crash with an assert failure. This function is not declared const, in case there is some kind of caching going on, but most of the time it shouldn't modify the class.
Implements OnlineFeatureInterface.
Definition at line 441 of file online-feature.cc.
References OnlineDeltaFeature::delta_features_, OnlineFeatureInterface::Dim(), VectorBase< Real >::Dim(), OnlineDeltaFeature::Dim(), OnlineFeatureInterface::GetFrame(), KALDI_ASSERT, OnlineFeatureInterface::NumFramesReady(), OnlineDeltaFeature::NumFramesReady(), OnlineDeltaFeature::opts_, DeltaFeaturesOptions::order, DeltaFeatures::Process(), OnlineDeltaFeature::src_, and DeltaFeaturesOptions::window.
{
   KALDI_ASSERT(frame >= 0 && frame < NumFramesReady());
   KALDI_ASSERT(feat->Dim() == Dim());
   // We'll produce a temporary matrix containing the features we want to
   // compute deltas on, but truncated to the necessary context.
   int32 context = opts_.order * opts_.window;
   int32 left_frame = frame - context,
       right_frame = frame + context,
       src_frames_ready = src_->NumFramesReady();
   if (left_frame < 0) left_frame = 0;
   if (right_frame >= src_frames_ready)
     right_frame = src_frames_ready - 1;
   KALDI_ASSERT(right_frame >= left_frame);
   int32 temp_num_frames = right_frame + 1 - left_frame,
       src_dim = src_->Dim();
   Matrix<BaseFloat> temp_src(temp_num_frames, src_dim);
   for (int32 t = left_frame; t <= right_frame; t++) {
     SubVector<BaseFloat> temp_row(temp_src, t - left_frame);
     src_->GetFrame(t, &temp_row);
   }
   int32 temp_t = frame - left_frame;  // temp_t is the offset of frame "frame"
                                       // within temp_src
   delta_features_.Process(temp_src, temp_t, feat);
 }
virtual bool IsLastFrame (int32 frame) const inline virtual
Returns true if this is the last frame.
Frame indices are zero-based, so the first frame is zero. IsLastFrame(-1) will return false, unless the file is empty (which is a case that I'm not sure all the code will handle, so be careful). This function may return false for some frame if we haven't yet decided to terminate decoding, but later true if we decide to terminate decoding. This function exists mainly to correctly handle end effects in feature extraction, and is not a mechanism to determine how many frames are in the decodable object (as it used to be, and for backward compatibility, still is, in the Decodable interface).
Implements OnlineFeatureInterface.
Definition at line 461 of file online-feature.h.
References OnlineFeatureInterface::IsLastFrame(), and OnlineDeltaFeature::src_.
{
     return src_->IsLastFrame(frame);
   }
int32 NumFramesReady () const virtual
returns the feature dimension.
Returns the total number of frames, since the start of the utterance, that are now available. In an online-decoding context, this will likely increase with time as more data becomes available.
Implements OnlineFeatureInterface.
Definition at line 430 of file online-feature.cc.
References OnlineFeatureInterface::IsLastFrame(), OnlineFeatureInterface::NumFramesReady(), OnlineDeltaFeature::opts_, DeltaFeaturesOptions::order, OnlineDeltaFeature::src_, and DeltaFeaturesOptions::window.
Referenced by OnlineDeltaFeature::GetFrame().
{
   int32 num_frames = src_->NumFramesReady(),
       context = opts_.order * opts_.window;
   // "context" is the number of frames on the left or (more relevant
   // here) right which we need in order to produce the output.
   if (num_frames > 0 && src_->IsLastFrame(num_frames-1))
     return num_frames;
   else
     return std::max<int32>(0, num_frames - context);
 }
Member Data Documentation
DeltaFeatures delta_features_ private
Definition at line 478 of file online-feature.h.
Referenced by OnlineDeltaFeature::GetFrame().
DeltaFeaturesOptions opts_ private
Definition at line 477 of file online-feature.h.
Referenced by OnlineDeltaFeature::Dim(), OnlineDeltaFeature::GetFrame(), and OnlineDeltaFeature::NumFramesReady().
OnlineFeatureInterface* src_ private
Definition at line 476 of file online-feature.h.
Referenced by OnlineDeltaFeature::Dim(), OnlineDeltaFeature::GetFrame(), OnlineDeltaFeature::IsLastFrame(), and OnlineDeltaFeature::NumFramesReady().
The documentation for this class was generated from the following files:
feat/online-feature.h
feat/online-feature.cc