Kaldi: SgmmGauPost Class Reference
SgmmGauPost Class Reference
indexed by time.
#include <am-sgmm.h>
Public Member Functions
SgmmGauPost (size_t i)
SgmmGauPost ()
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Detailed Description
indexed by time.
Definition at line 389 of file am-sgmm.h.
Constructor & Destructor Documentation
SgmmGauPost (size_t i) inline explicit
Definition at line 393 of file am-sgmm.h.
 : std::vector<SgmmGauPostElement>(i) {}
SgmmGauPost () inline
Definition at line 394 of file am-sgmm.h.
 {}
Member Function Documentation
void Read (std::istream & is, bool binary)
Definition at line 1343 of file am-sgmm.cc.
References kaldi::ExpectToken(), rnnlm::i, KALDI_ASSERT, kaldi::ReadBasicType(), and kaldi::ReadIntegerVector().
{
   ExpectToken(is, binary, "<SgmmGauPost>");
   int32 T;
   ReadBasicType(is, binary, &T);
   KALDI_ASSERT(T >= 0);
   this->resize(T);
   for (int32 t = 0; t < T; t++) {
     ExpectToken(is, binary, "<gselect>");
     ReadIntegerVector(is, binary, &((*this)[t].gselect));
     ExpectToken(is, binary, "<tids>");
     ReadIntegerVector(is, binary, &((*this)[t].tids));
     size_t sz = (*this)[t].tids.size();
     (*this)[t].posteriors.resize(sz);
     for (size_t i = 0; i < sz; i++)
       (*this)[t].posteriors[i].Read(is, binary);
   }
   ExpectToken(is, binary, "</SgmmGauPost>");
 }
void Write (std::ostream & os, bool binary) const
Definition at line 1326 of file am-sgmm.cc.
References rnnlm::i, KALDI_ASSERT, kaldi::WriteBasicType(), kaldi::WriteIntegerVector(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<SgmmGauPost>");
   int32 T = this->size();
   WriteBasicType(os, binary, T);
   for (int32 t = 0; t < T; t++) {
     WriteToken(os, binary, "<gselect>");
     WriteIntegerVector(os, binary, (*this)[t].gselect);
     WriteToken(os, binary, "<tids>");
     WriteIntegerVector(os, binary, (*this)[t].tids);
     KALDI_ASSERT((*this)[t].tids.size() == (*this)[t].posteriors.size());
     for (size_t i = 0; i < (*this)[t].posteriors.size(); i++) {
       (*this)[t].posteriors[i].Write(os, binary);
     }
   }
   WriteToken(os, binary, "</SgmmGauPost>");
 }
The documentation for this class was generated from the following files:
sgmm/am-sgmm.h
sgmm/am-sgmm.cc