Kaldi: AccumulateMultiThreadedClass Class Reference
AccumulateMultiThreadedClass Class Reference
Public Member Functions
AccumulateMultiThreadedClass (const DiagGmm &diag_gmm, const MatrixBase< BaseFloat > &data, const VectorBase< BaseFloat > &frame_weights, AccumDiagGmm *accum, double *tot_like)
AccumulateMultiThreadedClass (const AccumulateMultiThreadedClass &other)
void operator() ()
~AccumulateMultiThreadedClass ()
Public Member Functions inherited from MultiThreadable
virtual ~MultiThreadable ()
Private Attributes
const DiagGmm & diag_gmm_
const MatrixBase< BaseFloat > & data_
const VectorBase< BaseFloat > & frame_weights_
AccumDiagGmm * dest_accum_
AccumDiagGmm accum_
double * tot_like_ptr_
double tot_like_
Additional Inherited Members
Static Public Member Functions inherited from MultiThreadable
static void * run (void *m_in)
Public Attributes inherited from MultiThreadable
int32 thread_id_
int32 num_threads_
Detailed Description
Definition at line 486 of file mle-diag-gmm.cc.
Constructor & Destructor Documentation
AccumulateMultiThreadedClass (const DiagGmm & diag_gmm, const MatrixBase< BaseFloat > & data, const VectorBase< BaseFloat > & frame_weights, AccumDiagGmm * accum, double * tot_like) inline
Definition at line 488 of file mle-diag-gmm.cc.
                                                 :
       diag_gmm_(diag_gmm), data_(data),
       frame_weights_(frame_weights), dest_accum_(accum),
       tot_like_ptr_(tot_like), tot_like_(0.0) { }
AccumulateMultiThreadedClass (const AccumulateMultiThreadedClass & other) inline
Definition at line 496 of file mle-diag-gmm.cc.
References AccumulateMultiThreadedClass::data_, VectorBase< Real >::Dim(), AccumulateMultiThreadedClass::frame_weights_, KALDI_ASSERT, and MatrixBase< Real >::NumRows().
                                                                          :
     diag_gmm_(other.diag_gmm_), data_(other.data_),
     frame_weights_(other.frame_weights_), dest_accum_(other.dest_accum_),
     accum_(diag_gmm_, dest_accum_->Flags()), tot_like_ptr_(other.tot_like_ptr_),
     tot_like_(0.0) {
     KALDI_ASSERT(data_.NumRows() == frame_weights_.Dim());
   }
~AccumulateMultiThreadedClass () inline
Definition at line 519 of file mle-diag-gmm.cc.
References AccumulateMultiThreadedClass::accum_, AccumDiagGmm::Add(), AccumulateMultiThreadedClass::dest_accum_, AccumDiagGmm::Dim(), AccumulateMultiThreadedClass::tot_like_, and AccumulateMultiThreadedClass::tot_like_ptr_.
{
     if (accum_.Dim() != 0) { // if our accumulator is set up (this is not true
       // for the single object we use to initialize the others)
       dest_accum_->Add(1.0, accum_);
       *tot_like_ptr_ += tot_like_;
     }
   }
Member Function Documentation
void operator() () inline virtual
Implements MultiThreadable.
Definition at line 503 of file mle-diag-gmm.cc.
References AccumulateMultiThreadedClass::accum_, AccumDiagGmm::AccumulateFromDiag(), AccumulateMultiThreadedClass::data_, AccumulateMultiThreadedClass::diag_gmm_, AccumulateMultiThreadedClass::frame_weights_, KALDI_VLOG, MultiThreadable::num_threads_, MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), MultiThreadable::thread_id_, and AccumulateMultiThreadedClass::tot_like_.
                       {
     int32 num_frames = data_.NumRows(), num_threads = num_threads_,
         block_size = (num_frames + num_threads - 1) / num_threads,
         block_start = block_size * thread_id_,
         block_end = std::min(num_frames, block_start + block_size);
     tot_like_ = 0.0;
     double tot_weight = 0.0;
     for (int32 t = block_start; t < block_end; t++) {
       tot_like_ += frame_weights_(t) *
           accum_.AccumulateFromDiag(diag_gmm_, data_.Row(t), frame_weights_(t));
       tot_weight += frame_weights_(t);
     }
     KALDI_VLOG(3) << "Thread " << thread_id_ << " saw average likeliood/frame "
                   << (tot_like_ / tot_weight) << " over " << tot_weight
                   << " (weighted) frames.";
   }
Member Data Documentation
AccumDiagGmm accum_ private
Definition at line 531 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::operator()(), and AccumulateMultiThreadedClass::~AccumulateMultiThreadedClass().
const MatrixBase<BaseFloat>& data_ private
Definition at line 528 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::AccumulateMultiThreadedClass(), and AccumulateMultiThreadedClass::operator()().
AccumDiagGmm* dest_accum_ private
Definition at line 530 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::~AccumulateMultiThreadedClass().
const DiagGmm& diag_gmm_ private
Definition at line 527 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::operator()().
const VectorBase<BaseFloat>& frame_weights_ private
Definition at line 529 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::AccumulateMultiThreadedClass(), and AccumulateMultiThreadedClass::operator()().
double tot_like_ private
Definition at line 533 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::operator()(), and AccumulateMultiThreadedClass::~AccumulateMultiThreadedClass().
double* tot_like_ptr_ private
Definition at line 532 of file mle-diag-gmm.cc.
Referenced by AccumulateMultiThreadedClass::~AccumulateMultiThreadedClass().
The documentation for this class was generated from the following file:
gmm/mle-diag-gmm.cc