Kaldi: CuVector< Real > Class Template Reference
CuVector< Real > Class Template Reference
#include <matrix-common.h>
Public Member Functions
CuVector ()
CuVector (MatrixIndexT dim, MatrixResizeType t=kSetZero)
CuVector (const CuVectorBase< Real > &v)
CuVector (const VectorBase< Real > &v)
CuVector (const CuVector< Real > &v)
template<typename OtherReal >
CuVector (const CuVectorBase< OtherReal > &v)
template<typename OtherReal >
CuVector (const VectorBase< OtherReal > &v)
void Resize (MatrixIndexT dim, MatrixResizeType t=kSetZero)
Allocate the memory.
~CuVector ()
CuVector< Real > & operator= (const CuVectorBase< Real > &other)
CuVector< Real > & operator= (const CuVector< Real > &other)
CuVector< Real > & operator= (const VectorBase< Real > &other)
void Read (std::istream &is, bool binary)
I/O.
void Write (std::ostream &is, bool binary) const
void Swap (Vector< Real > *vec)
Public Member Functions inherited from CuVectorBase< Real >
MatrixIndexT Dim () const
Dimensions.
Real * Data ()
Returns a pointer to the start of the vector's data.
const Real * Data () const
Returns a pointer to the start of the vector's data (const).
void CopyFromVec (const CuVectorBase< Real > &src)
Copy functions; these will crash if the dimension do not match.
template<typename OtherReal >
void CopyFromVec (const CuVectorBase< OtherReal > &M)
template<typename OtherReal >
void CopyFromVec (const VectorBase< OtherReal > &src)
template<typename OtherReal >
void CopyToVec (VectorBase< OtherReal > *dst) const
void CopyRowsFromMat (const CuMatrixBase< Real > &M)
void CopyRowsFromMat (const MatrixBase< Real > &M)
void SetZero ()
Math operations.
void Set (Real value)
void Add (Real value)
void Scale (Real value)
void AddVec (Real alpha, const CuVectorBase< Real > &vec, Real beta=1.0)
template<typename OtherReal >
void AddVec (Real alpha, const CuVectorBase< OtherReal > &vec, Real beta=1.0)
void AddRowSumMat (Real alpha, const CuMatrixBase< Real > &mat, Real beta=1.0)
Sum the rows of the matrix, add to vector.
void AddColSumMat (Real alpha, const CuMatrixBase< Real > &mat, Real beta=1.0)
Sum the columns of the matrix, add to vector.
void AddTpVec (const Real alpha, const CuTpMatrix< Real > &M, const MatrixTransposeType trans, const CuVectorBase< Real > &v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
void MulTp (const CuTpMatrix< Real > &M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
bool ApproxEqual (const CuVectorBase< Real > &other, float tol=0.01) const
void InvertElements ()
void ApplySoftMax ()
void ApplyExp ()
void ApplyLog ()
MatrixIndexT ApplyFloor (Real floor_val)
MatrixIndexT ApplyCeiling (Real ceiling_val)
void ApplyPow (Real power)
Real Sum () const
void SetRandn ()
CuSubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l)
const CuSubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l) const
void CopyColFromMat (const CuMatrixBase< Real > &mat, MatrixIndexT col)
template<typename OtherReal >
void CopyColFromMat (const CuMatrixBase< OtherReal > &mat, MatrixIndexT col)
void AddMatVec (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType trans, const CuVectorBase< Real > &v, const Real beta)
void AddVecVec (Real alpha, const CuVectorBase< Real > &v, const CuVectorBase< Real > &r, Real beta)
void AddSpVec (const Real alpha, const CuSpMatrix< Real > &S, const CuVectorBase< Real > &v, const Real beta)
void AddDiagMat2 (Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType trans, Real beta)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
void AddDiagMatMat (Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transM, const CuMatrixBase< Real > &N, MatrixTransposeType transN, Real beta=1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
CuValue< Real > operator() (MatrixIndexT i)
Real Norm (Real p)
Real operator() (MatrixIndexT i) const
void CopyDiagFromPacked (const CuPackedMatrix< Real > &M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
void CopyDiagFromMat (const CuMatrix< Real > &M)
Extracts the diagonal of a matrix.
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
void ReplaceValue (Real orig, Real changed)
void MulElements (const CuVectorBase< Real > &v)
template<>
void CopyColFromMat (const CuMatrixBase< float > &mat, MatrixIndexT col)
template<>
void CopyColFromMat (const CuMatrixBase< double > &mat, MatrixIndexT col)
template<>
void CopyFromVec (const CuVectorBase< float > &src)
template<>
void CopyFromVec (const CuVectorBase< double > &src)
template<>
void CopyFromVec (const CuVectorBase< float > &src)
template<>
void CopyFromVec (const CuVectorBase< double > &src)
Private Member Functions
void Destroy ()
Friends
class CuVectorBase< float >
class CuVectorBase< double >
class CuMatrixBase< Real >
class CuPackedMatrix< Real >
class CuSpMatrix< Real >
class CuTpMatrix< Real >
Additional Inherited Members
Protected Member Functions inherited from CuVectorBase< Real >
const VectorBase< Real > & Vec () const
VectorBase< Real > & Vec ()
CuVectorBase ()
Default constructor: make it protected so the user cannot instantiate this class.
Protected Attributes inherited from CuVectorBase< Real >
Real * data_
GPU data pointer (or regular data pointer if CUDA is not compiled in or we have no GPU).
MatrixIndexT dim_
dimension of the vector
Detailed Description
template<typename Real>
class kaldi::CuVector< Real >
Definition at line 66 of file matrix-common.h.
Constructor & Destructor Documentation
CuVector () inline
Definition at line 230 of file cu-vector.h.
 { }
CuVector (MatrixIndexT dim, MatrixResizeType t = kSetZero) inline
Definition at line 231 of file cu-vector.h.
 { Resize(dim, t); }
CuVector (const CuVectorBase< Real > & v)
Definition at line 829 of file cu-vector.cc.
References CuVectorBase< Real >::Dim().
{
   this->Resize(v.Dim());
   this->CopyFromVec(v);
 }
CuVector (const VectorBase< Real > & v)
Definition at line 835 of file cu-vector.cc.
References VectorBase< Real >::dim_.
{
   this->Resize(v.dim_);
   this->CopyFromVec(v);
 }
CuVector (const CuVector< Real > & v) inline explicit
Definition at line 236 of file cu-vector.h.
                                              : CuVectorBase<Real>() {
     Resize(v.Dim(), kUndefined);
     this->CopyFromVec(v);
   }
CuVector (const CuVectorBase< OtherReal > & v) inline explicit
Definition at line 242 of file cu-vector.h.
                                                       : CuVectorBase<Real>() {
     Resize(v.Dim(), kUndefined);
     this->CopyFromVec(v);
   }
CuVector (const VectorBase< OtherReal > & v) inline explicit
Definition at line 248 of file cu-vector.h.
                                                     : CuVectorBase<Real>() {
     Resize(v.Dim(), kUndefined);
     this->CopyFromVec(Vector<Real>(v));
   }
~CuVector () inline
Definition at line 256 of file cu-vector.h.
 { Destroy(); }
Member Function Documentation
void Destroy () private
Definition at line 903 of file cu-vector.cc.
Referenced by CuVector< BaseFloat >::~CuVector().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->data_ != NULL)
       CuDevice::Instantiate().Free(this->data_);
   } else
 #endif
   {
     if (this->data_ != NULL) KALDI_MEMALIGN_FREE(this->data_);
   }
   this->data_ = NULL;
   this->dim_ = 0;
 }
CuVector<Real>& operator= (const CuVectorBase< Real > & other) inline
Definition at line 258 of file cu-vector.h.
{
     Resize(other.Dim(), kUndefined);
     this->CopyFromVec(other);
     return *this;
   }
CuVector<Real>& operator= (const CuVector< Real > & other) inline
Definition at line 264 of file cu-vector.h.
{
     Resize(other.Dim(), kUndefined);
     this->CopyFromVec(other);
     return *this;
   }
CuVector<Real>& operator= (const VectorBase< Real > & other) inline
Definition at line 269 of file cu-vector.h.
{
     Resize(other.Dim());
     this->CopyFromVec(other);
     return *this;
   }
void Read (std::istream & is, bool binary)
I/O.
Definition at line 811 of file cu-vector.cc.
References Vector< Real >::Read().
Referenced by NormalizeComponent::Read(), NonlinearComponent::Read(), RepeatedAffineComponent::Read(), NaturalGradientAffineComponent::Read(), AffineComponent::Read(), AffineComponentPreconditioned::Read(), AffineComponentPreconditionedOnline::Read(), PerElementScaleComponent::Read(), PerElementOffsetComponent::Read(), NaturalGradientPerElementScaleComponent::Read(), BlockAffineComponent::Read(), BlockAffineComponentPreconditioned::Read(), ConvolutionComponent::Read(), FixedAffineComponent::Read(), FixedScaleComponent::Read(), FixedBiasComponent::Read(), Convolutional1dComponent::Read(), AffineTransform::ReadData(), TCNProjectionComponent::ReadData(), LstmProjectedStreams::ReadData(), ConvolutionalComponent::ReadData(), Convolutional2DComponent::ReadData(), BLstmProjectedStreams::ReadData(), Rbm::ReadData(), AddShift::ReadData(), Rescale::ReadData(), and kaldi::UnitTestCuVectorIO().
{
   Vector<Real> temp;
   temp.Read(is, binary);
   Destroy();
   Swap(&temp);
 }
void Resize (MatrixIndexT dim, MatrixResizeType t = kSetZero)
Allocate the memory.
Definition at line 841 of file cu-vector.cc.
References Timer::Elapsed(), KALDI_ASSERT, kaldi::kSetZero, kaldi::kUndefined, and kaldi::nnet3::SetZero().
Referenced by NonlinearComponent::Add(), SimpleSentenceAveragingComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), CuVector< BaseFloat >::CuVector(), CuMatrixBase< Real >::DiffXent(), Xent::Eval(), RepeatedAffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), PerElementScaleComponent::Init(), PerElementOffsetComponent::Init(), BlockAffineComponent::Init(), ConvolutionComponent::Init(), FixedAffineComponent::Init(), Convolutional1dComponent::Init(), LstmProjectedStreams::InitData(), BLstmProjectedStreams::InitData(), AddShift::InitData(), Rescale::InitData(), AffineComponent::LimitRank(), SoftmaxComponent::MixUp(), CuVector< BaseFloat >::operator=(), SimpleSentenceAveragingComponent::PropagateFnc(), LengthNormComponent::PropagateFnc(), Rbm::RbmUpdate(), LstmProjectedStreams::ReadData(), BLstmProjectedStreams::ReadData(), NaturalGradientAffineComponent::Resize(), AffineComponent::Resize(), AffineComponentPreconditionedOnline::Resize(), Convolutional1dComponent::Resize(), NonlinearComponent::SetDim(), NonlinearComponent::StoreStatsInternal(), TCNProjectionComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), AddShift::Update(), Rescale::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), NonlinearComponent::UpdateStats(), and AffineComponent::Widen().
{
   KALDI_ASSERT(t == kSetZero || t == kUndefined); // Others not implemented
   // yet.
   if (this->dim_ == dim) {
     this->SetZero();
     return;
   }
   if (this->dim_ != 0)
     this->Destroy();
   if (dim == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     this->data_ = static_cast<Real*>(CuDevice::Instantiate().Malloc(dim * sizeof(Real)));
     this->dim_ = dim;
     if (t == kSetZero) this->SetZero();
     CuDevice::Instantiate().AccuProfile("CuVector::Resize", tim.Elapsed());
   } else
 #endif
   {
     Vector<Real> vec(dim);
     this->Swap(&vec);
   }
 }
void Swap (Vector< Real > * vec)
Definition at line 867 of file cu-vector.cc.
References VectorBase< Real >::data_, VectorBase< Real >::dim_, kaldi::kUndefined, Vector< Real >::Resize(), kaldi::swap(), and Vector< Real >::Swap().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->dim_ == 0) {
       if (vec->dim_ != 0) {
         // *this is empty, but vec is nonempty.
         Resize(vec->dim_, kUndefined);
         this->CopyFromVec(*vec);
         vec->Resize(0);
       }
       // else both are empty.
     } else { // *this is nonempty.
       if (vec->dim_ != 0) {
         // Both *this and *vec are nonempty.  Recurse to simpler cases.
         // this could be done more efficiently in the case where
         // the size does not change.
         Vector<Real> temp;
         this->Swap(&temp); // now temp is full, *this is empty.
         vec->Swap(&temp); // now vec has data from *this, temp has
         // data from vec.
         Swap(vec); // copy data in vec to *this, which is now empty.
       } else { // *this is full but *vec is empty.
         vec->Resize(this->dim_, kUndefined);
         this->CopyToVec(vec);
         this->Destroy();
       }
     }
   } else
 #endif
   {
     std::swap(vec->data_, this->data_);
     std::swap(vec->dim_, this->dim_);
   }
 }
void Write (std::ostream & is, bool binary) const
Definition at line 821 of file cu-vector.cc.
References kaldi::kUndefined, and VectorBase< Real >::Write().
Referenced by kaldi::UnitTestCuVectorIO(), NonlinearComponent::Write(), RepeatedAffineComponent::Write(), NaturalGradientAffineComponent::Write(), AffineComponent::Write(), AffineComponentPreconditioned::Write(), AffineComponentPreconditionedOnline::Write(), PerElementScaleComponent::Write(), PerElementOffsetComponent::Write(), NaturalGradientPerElementScaleComponent::Write(), BlockAffineComponent::Write(), BlockAffineComponentPreconditioned::Write(), ConvolutionComponent::Write(), FixedAffineComponent::Write(), FixedScaleComponent::Write(), FixedBiasComponent::Write(), Convolutional1dComponent::Write(), Rbm::WriteAsNnet(), AffineTransform::WriteData(), TCNProjectionComponent::WriteData(), LstmProjectedStreams::WriteData(), ConvolutionalComponent::WriteData(), Convolutional2DComponent::WriteData(), Rbm::WriteData(), BLstmProjectedStreams::WriteData(), AddShift::WriteData(), and Rescale::WriteData().
{
   Vector<BaseFloat> temp(this->dim_, kUndefined);
   this->CopyToVec(&temp);
   temp.Write(os, binary);
 }
Friends And Related Function Documentation
friend class CuMatrixBase< Real > friend
Definition at line 224 of file cu-vector.h.
friend class CuPackedMatrix< Real > friend
Definition at line 225 of file cu-vector.h.
friend class CuSpMatrix< Real > friend
Definition at line 226 of file cu-vector.h.
friend class CuTpMatrix< Real > friend
Definition at line 227 of file cu-vector.h.
friend class CuVectorBase< double > friend
Definition at line 223 of file cu-vector.h.
friend class CuVectorBase< float > friend
Definition at line 222 of file cu-vector.h.
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-vector.h
cudamatrix/cu-vector.cc