Kaldi: WaveData Class Reference
WaveData Class Reference
This class's purpose is to read in Wave files.
#include <wave-reader.h>
Public Member Functions
WaveData (BaseFloat samp_freq, const MatrixBase< BaseFloat > &data)
WaveData ()
void Read (std::istream &is)
Read() will throw on error.
void Write (std::ostream &os) const
Write() will throw on error. os should be opened in binary mode.
const Matrix< BaseFloat > & Data () const
BaseFloat SampFreq () const
BaseFloat Duration () const
void CopyFrom (const WaveData &other)
void Clear ()
Private Member Functions
uint32 ReadUint32 (std::istream &is, bool swap)
uint16 ReadUint16 (std::istream &is, bool swap)
Static Private Member Functions
static void Expect4ByteTag (std::istream &is, const char *expected)
static void Read4ByteTag (std::istream &is, char *dest)
static void WriteUint32 (std::ostream &os, int32 i)
static void WriteUint16 (std::ostream &os, int16 i)
Private Attributes
Matrix< BaseFloat > data_
BaseFloat samp_freq_
Static Private Attributes
static const uint32 kBlockSize = 1024 * 1024
Detailed Description
This class's purpose is to read in Wave files.
Definition at line 60 of file wave-reader.h.
Constructor & Destructor Documentation
WaveData (BaseFloat samp_freq, const MatrixBase< BaseFloat > & data) inline
Definition at line 62 of file wave-reader.h.
       : data_(data), samp_freq_(samp_freq) {}
WaveData () inline
Definition at line 65 of file wave-reader.h.
 : samp_freq_(0.0) {}
Member Function Documentation
void Clear () inline
Definition at line 90 of file wave-reader.h.
References WaveData::data_, Matrix< Real >::Resize(), and WaveData::samp_freq_.
Referenced by WaveHolder::Clear().
                {
     data_.Resize(0, 0);
     samp_freq_ = 0.0;
   }
void CopyFrom (const WaveData & other) inline
Definition at line 85 of file wave-reader.h.
References MatrixBase< Real >::CopyFromMat(), WaveData::data_, and WaveData::samp_freq_.
Referenced by WaveHolder::Copy(), and WaveHolder::operator=().
{
     samp_freq_ = other.samp_freq_;
     data_.CopyFromMat(other.data_);
   }
const Matrix<BaseFloat>& Data () const inline
Definition at line 78 of file wave-reader.h.
References WaveData::data_.
Referenced by main(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), kaldi::TestOnlineTransform(), UnitTestHTKCompare1(), UnitTestHTKCompare2(), UnitTestHTKCompare3(), UnitTestHTKCompare4(), UnitTestHTKCompare5(), UnitTestHTKCompare6(), and UnitTestReadWave().
 { return data_; }
BaseFloat Duration () const inline
Definition at line 83 of file wave-reader.h.
References WaveData::data_, MatrixBase< Real >::NumCols(), and WaveData::samp_freq_.
Referenced by main().
 { return data_.NumCols() / samp_freq_; }
void Expect4ByteTag (std::istream & is, const char * expected) static private
Definition at line 34 of file wave-reader.cc.
References KALDI_ERR.
Referenced by WaveData::Read().
{
   char tmp[5];
   tmp[4] = '\0';
   is.read(tmp, 4);
   if (is.fail())
     KALDI_ERR << "WaveData: expected " << expected << ", failed to read anything";
   if (strcmp(tmp, expected))
     KALDI_ERR << "WaveData: expected " << expected << ", got " << tmp;
 }
void Read (std::istream & is)
Read() will throw on error.
It's valid to call Read() more than once– in this case it will destroy what was there before. "is" should be opened in binary mode.
Definition at line 109 of file wave-reader.cc.
References WaveData::data_, WaveData::Expect4ByteTag(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, KALDI_SWAP2, KALDI_SWAP4, KALDI_WARN, WaveData::kBlockSize, WaveData::Read4ByteTag(), WaveData::ReadUint16(), WaveData::ReadUint32(), Matrix< Real >::Resize(), WaveData::samp_freq_, and kaldi::swap().
Referenced by main(), WaveHolder::Read(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), kaldi::TestOnlineTransform(), kaldi::UnitTestDiffSampleRate(), UnitTestHTKCompare1(), UnitTestHTKCompare2(), UnitTestHTKCompare3(), UnitTestHTKCompare4(), UnitTestHTKCompare5(), UnitTestHTKCompare6(), kaldi::UnitTestKeele(), kaldi::UnitTestKeeleNccfBallast(), kaldi::UnitTestPenaltyFactor(), kaldi::UnitTestPitchExtractionSpeed(), kaldi::UnitTestPitchExtractorCompareKeele(), kaldi::UnitTestProcess(), and UnitTestReadWave().
{
   data_.Resize(0, 0);  // clear the data.
   char tmp[5];
   tmp[4] = '\0';
   Read4ByteTag(is, &tmp[0]);
   bool is_rifx = false;
   if (!strcmp(tmp, "RIFX"))
     is_rifx = true;
   else if (strcmp(tmp, "RIFF"))
     KALDI_ERR << "WaveData: expected RIFF or RIFX, got " << tmp;
 #ifdef __BIG_ENDIAN__
   bool swap = !is_rifx;
 #else
   bool swap = is_rifx;
 #endif
   uint32 riff_chunk_size = ReadUint32(is, swap);
   Expect4ByteTag(is, "WAVE");
   uint32 riff_chunk_read = 0;
   riff_chunk_read += 4;  // WAVE included in riff_chunk_size.
   Expect4ByteTag(is, "fmt ");
   uint32 subchunk1_size = ReadUint32(is, swap);
   uint16 audio_format = ReadUint16(is, swap),
       num_channels = ReadUint16(is, swap);
   uint32 sample_rate = ReadUint32(is, swap),
       byte_rate = ReadUint32(is, swap),
       block_align = ReadUint16(is, swap),
       bits_per_sample = ReadUint16(is, swap);
   uint32 fmt_chunk_read = 16;
   if (audio_format == 1) {
     if (subchunk1_size < 16) {
       KALDI_ERR << "WaveData: expect PCM format data to have fmt chunk of at least size 16.";
     }
   } else if (audio_format == 0xFFFE) {  // WAVE_FORMAT_EXTENSIBLE
     uint16 extra_size = ReadUint16(is, swap);
     if (subchunk1_size < 40 || extra_size < 22) {
       KALDI_ERR << "WaveData: malformed WAVE_FORMAT_EXTENSIBLE format data.";
     }
     ReadUint16(is, swap);  // Unused for PCM.
     ReadUint32(is, swap);  // Channel map: we do not care.
     uint32 guid1 = ReadUint32(is, swap),
            guid2 = ReadUint32(is, swap),
            guid3 = ReadUint32(is, swap),
            guid4 = ReadUint32(is, swap);
     fmt_chunk_read = 40;
     // Support only KSDATAFORMAT_SUBTYPE_PCM for now. Interesting formats:
     // ("00000001-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_PCM)
     // ("00000003-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_IEEE_FLOAT)
     // ("00000006-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_ALAW)
     // ("00000007-0000-0010-8000-00aa00389b71", KSDATAFORMAT_SUBTYPE_MULAW)
     if (guid1 != 0x00000001 || guid2 != 0x00100000 ||
         guid3 != 0xAA000080 || guid4 != 0x719B3800) {
       KALDI_ERR << "WaveData: unknown/unsupported WAVE_FORMAT_EXTENSIBLE format.";
     }
   } else {
     KALDI_ERR << "WaveData: can read only PCM data, format id in file is: "
               << audio_format;
   }
   for (uint32 i = fmt_chunk_read; i < subchunk1_size; i++) is.get();  // use up extra data.
   if (num_channels <= 0)
     KALDI_ERR << "WaveData: no channels present";
   samp_freq_ = static_cast<BaseFloat>(sample_rate);
   if (bits_per_sample != 8 && bits_per_sample != 16 && bits_per_sample != 32)
     KALDI_ERR << "WaveData: bits_per_sample is " << bits_per_sample;
   if (byte_rate != sample_rate * bits_per_sample/8 * num_channels)
     KALDI_ERR << "Unexpected byte rate " << byte_rate << " vs. "
               << sample_rate <<" * " << (bits_per_sample/8)
               << " * " << num_channels;
   if (block_align != num_channels * bits_per_sample/8)
     KALDI_ERR << "Unexpected block_align: " << block_align << " vs. "
               << num_channels << " * " << (bits_per_sample/8);
   riff_chunk_read += 8 + subchunk1_size;
   // size of what we just read, 4 bytes for "fmt " + 4
   // for subchunk1_size + subchunk1_size itself.
   // We support an optional "fact" chunk (which is useless but which
   // we encountered), and then a single "data" chunk.
   char next_chunk_name[4];
   Read4ByteTag(is, next_chunk_name);
   riff_chunk_read += 4;
   // Skip any subchunks between "fmt" and "data".  Usually there will
   // be a single "fact" subchunk, but on Windows there can also be a
   // "list" subchunk.
   while (strncmp(next_chunk_name, "data", 4) != 0) {
     // We will just ignore the data in these chunks.
     uint32 chunk_sz = ReadUint32(is, swap);
     if (chunk_sz != 4 && strncmp(next_chunk_name, "fact", 4) == 0)
       KALDI_WARN << "Expected fact chunk to be 4 bytes long.";
     for (uint32 i = 0; i < chunk_sz; i++)
       is.get();
     riff_chunk_read += 4 + chunk_sz;  // for chunk_sz (4) + chunk contents (chunk-sz)
     // Now read the next chunk name.
     Read4ByteTag(is, next_chunk_name);
     riff_chunk_read += 4;
   }
   if (strncmp(next_chunk_name, "data", 4))
     KALDI_ERR << "WaveData: expected data chunk, got instead "
               << next_chunk_name;
   uint32 data_chunk_size = ReadUint32(is, swap);
   riff_chunk_read += 4;
   if (std::abs(static_cast<int64>(riff_chunk_read) +
                static_cast<int64>(data_chunk_size) -
                static_cast<int64>(riff_chunk_size)) > 1) {
     // we allow the size to be off by one without warning, because there is a
     // weirdness in the format of RIFF files that means that the input may
     // sometimes be padded with 1 unused byte to make the total size even.
     KALDI_WARN << "Expected " << riff_chunk_size << " bytes in RIFF chunk, but "
                << "after first data block there will be " << riff_chunk_read
                << " + " << data_chunk_size << " bytes "
                << "(we do not support reading multiple data chunks).";
   }
   std::vector<char*> data_pointer_vec;
   std::vector<int> data_size_vec;
   uint32 num_bytes_read = 0;
   for (int32 remain_chunk_size = data_chunk_size; remain_chunk_size > 0;
        remain_chunk_size -= kBlockSize) {
     int32 this_block_size = remain_chunk_size;
     if (kBlockSize < remain_chunk_size)
       this_block_size = kBlockSize;
     char *block_data_vec = new char[this_block_size];
     is.read(block_data_vec, this_block_size);
     num_bytes_read += is.gcount();
     data_size_vec.push_back(is.gcount());
     data_pointer_vec.push_back(block_data_vec);
     if (num_bytes_read < this_block_size)
       break;
   }
   std::vector<char> chunk_data_vec(num_bytes_read);
   uint32 data_address = 0;
   for (int i = 0; i < data_pointer_vec.size(); i++) {
     memcpy(&(chunk_data_vec[data_address]), data_pointer_vec[i],
            data_size_vec[i]);
     delete[] data_pointer_vec[i];
     data_address += data_size_vec[i];
   }
   char *data_ptr = &(chunk_data_vec[0]);
   if (num_bytes_read == 0 && num_bytes_read != data_chunk_size) {
     KALDI_ERR << "WaveData: failed to read data chunk (read no bytes)";
   } else if (num_bytes_read != data_chunk_size) {
     KALDI_ASSERT(num_bytes_read < data_chunk_size);
     KALDI_WARN << "Read fewer bytes than specified in the header: "
                << num_bytes_read << " < " << data_chunk_size;
   }
   if (data_chunk_size == 0)
     KALDI_ERR << "WaveData: empty file (no data)";
   uint32 num_samp = num_bytes_read / block_align;
   data_.Resize(num_channels, num_samp);
   for (uint32 i = 0; i < num_samp; i++) {
     for (uint32 j = 0; j < num_channels; j++) {
       switch (bits_per_sample) {
         case 8:
           data_(j, i) = *data_ptr;
           data_ptr++;
           break;
         case 16:
           {
             int16 k = *reinterpret_cast<uint16*>(data_ptr);
             if (swap)
               KALDI_SWAP2(k);
             data_(j, i) =  k;
             data_ptr += 2;
             break;
           }
         case 32:
           {
             int32 k = *reinterpret_cast<uint32*>(data_ptr);
             if (swap)
               KALDI_SWAP4(k);
             data_(j, i) =  k;
             data_ptr += 4;
             break;
           }
         default:
           KALDI_ERR << "bits per sample is " << bits_per_sample;  // already checked this.
       }
     }
   }
 }
void Read4ByteTag (std::istream & is, char * dest) static private
Definition at line 72 of file wave-reader.cc.
References KALDI_ERR.
Referenced by WaveData::Read().
{
   is.read(dest, 4);
   if (is.fail())
     KALDI_ERR << "WaveData: expected 4-byte chunk-name, got read errror";
 }
uint16 ReadUint16 (std::istream & is, bool swap) private
Definition at line 58 of file wave-reader.cc.
References KALDI_ERR, and KALDI_SWAP2.
Referenced by WaveData::Read().
{
   union {
     char result[2];
     int16 ans;
   } u;
   is.read(u.result, 2);
   if (swap)
     KALDI_SWAP2(u.result);
   if (is.fail())
     KALDI_ERR << "WaveData: unexpected end of file.";
   return u.ans;
 }
uint32 ReadUint32 (std::istream & is, bool swap) private
Definition at line 44 of file wave-reader.cc.
References KALDI_ERR, and KALDI_SWAP4.
Referenced by WaveData::Read().
{
   union {
     char result[4];
     uint32 ans;
   } u;
   is.read(u.result, 4);
   if (swap)
     KALDI_SWAP4(u.result);
   if (is.fail())
     KALDI_ERR << "WaveData: unexpected end of file.";
   return u.ans;
 }
BaseFloat SampFreq () const inline
Definition at line 80 of file wave-reader.h.
References WaveData::samp_freq_.
Referenced by main(), kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), and kaldi::TestOnlineTransform().
 { return samp_freq_; }
void Write (std::ostream & os) const
Write() will throw on error. os should be opened in binary mode.
Definition at line 316 of file wave-reader.cc.
References MatrixBase< Real >::Data(), WaveData::data_, rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_ERR, KALDI_SWAP2, KALDI_WARN, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), WaveData::samp_freq_, MatrixBase< Real >::Stride(), WaveData::WriteUint16(), and WaveData::WriteUint32().
Referenced by main(), and WaveHolder::Write().
{
   os << "RIFF";
   if (data_.NumRows() == 0)
     KALDI_ERR << "Error: attempting to write empty WAVE file";
   int32 num_chan = data_.NumRows(),
       num_samp = data_.NumCols(),
       bytes_per_samp = 2;
   int32 subchunk2size = (num_chan * num_samp * bytes_per_samp);
   int32 chunk_size = 36 + subchunk2size;
   WriteUint32(os, chunk_size);
   os << "WAVE";
   os << "fmt ";
   WriteUint32(os, 16);
   WriteUint16(os, 1);
   WriteUint16(os, num_chan);
   KALDI_ASSERT(samp_freq_ > 0);
   WriteUint32(os, static_cast<int32>(samp_freq_));
   WriteUint32(os, static_cast<int32>(samp_freq_) * num_chan * bytes_per_samp);
   WriteUint16(os, num_chan * bytes_per_samp);
   WriteUint16(os, 8 * bytes_per_samp);
   os << "data";
   WriteUint32(os, subchunk2size);
   const BaseFloat *data_ptr = data_.Data();
   int32 stride = data_.Stride();
   int num_clipped = 0;
   for (int32 i = 0; i < num_samp; i++) {
     for (int32 j = 0; j < num_chan; j++) {
       int32 elem = static_cast<int32>(trunc(data_ptr[j * stride + i]));
       int16 elem_16 = static_cast<int16>(elem);
       if (elem < std::numeric_limits<int16>::min()) {
         elem_16 = std::numeric_limits<int16>::min();
         ++num_clipped;
       } else if (elem > std::numeric_limits<int16>::max()) {
         elem_16 = std::numeric_limits<int16>::max();
         ++num_clipped;
       }
 #ifdef __BIG_ENDIAN__
       KALDI_SWAP2(elem_16);
 #endif
       os.write(reinterpret_cast<char*>(&elem_16), 2);
     }
   }
   if (os.fail())
     KALDI_ERR << "Error writing wave data to stream.";
   if (num_clipped > 0)
     KALDI_WARN << "WARNING: clipped " << num_clipped
                << " samples out of total " << num_chan * num_samp
                << ". Reduce volume?";
 }
void WriteUint16 (std::ostream & os, int16 i) static private
Definition at line 93 of file wave-reader.cc.
References rnnlm::i, KALDI_ERR, and KALDI_SWAP2.
Referenced by WaveData::Write().
{
   union {
     char buf[2];
     int16 i;
   } u;
   u.i = i;
 #ifdef __BIG_ENDIAN__
   KALDI_SWAP2(u.buf);
 #endif
   os.write(u.buf, 2);
   if (os.fail())
     KALDI_ERR << "WaveData: error writing to stream.";
 }
void WriteUint32 (std::ostream & os, int32 i) static private
Definition at line 79 of file wave-reader.cc.
References rnnlm::i, KALDI_ERR, and KALDI_SWAP4.
Referenced by WaveData::Write().
{
   union {
     char buf[4];
     int i;
   } u;
   u.i = i;
 #ifdef __BIG_ENDIAN__
   KALDI_SWAP4(u.buf);
 #endif
   os.write(u.buf, 4);
   if (os.fail())
     KALDI_ERR << "WaveData: error writing to stream.";
 }
Member Data Documentation
Matrix<BaseFloat> data_ private
Definition at line 97 of file wave-reader.h.
Referenced by WaveData::Clear(), WaveData::CopyFrom(), WaveData::Data(), WaveData::Duration(), WaveData::Read(), and WaveData::Write().
const uint32 kBlockSize = 1024 * 1024 static private
Definition at line 96 of file wave-reader.h.
Referenced by WaveData::Read().
BaseFloat samp_freq_ private
Definition at line 98 of file wave-reader.h.
Referenced by WaveData::Clear(), WaveData::CopyFrom(), WaveData::Duration(), WaveData::Read(), WaveData::SampFreq(), and WaveData::Write().
The documentation for this class was generated from the following files:
feat/wave-reader.h
feat/wave-reader.cc