Kaldi: Mutex Class Reference
Mutex Class Reference
This class encapsulates mutex to ensure exclusive access to some critical section which manipulates shared resources.
#include <kaldi-mutex.h>
Public Member Functions
Mutex ()
~Mutex ()
void Lock ()
bool TryLock ()
Try to lock the mutex without waiting for it.
void Unlock ()
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (Mutex)
Private Attributes
pthread_mutex_t mutex_
Detailed Description
This class encapsulates mutex to ensure exclusive access to some critical section which manipulates shared resources.
Note.: The mutex MUST BE UNLOCKED from the SAME THREAD which has locked it!
Definition at line 36 of file kaldi-mutex.h.
Constructor & Destructor Documentation
Mutex ()
Definition at line 30 of file kaldi-mutex.cc.
References KALDI_ERR, and Mutex::mutex_.
              {
   int ret;
   if ((ret = pthread_mutex_init(&mutex_, NULL)) != 0)
     KALDI_ERR << "Cannot initialize pthread mutex, error is: "
               << strerror(ret);
 }
~Mutex ()
Definition at line 38 of file kaldi-mutex.cc.
References KALDI_ERR, KALDI_WARN, and Mutex::mutex_.
               {
   int ret;
   if ( (ret = pthread_mutex_destroy(&mutex_)) != 0) {
     if (ret != 16) {
       KALDI_ERR << "Cannot destroy pthread mutex, error is: "
                 << strerror(ret);
     } else {
       KALDI_WARN << "Error destroying pthread mutex; ignoring it as it could be "
                  << "a known issue that affects Haswell processors, see "
                  << "https://sourceware.org/bugzilla/show_bug.cgi?id=16657 "
                  << "If your processor is not Haswell and you see this message, "
                  << "it could be a bug in Kaldi.  However it could be that "
                  << "multi-threaded code terminated messily.";
     }
   }
 }
Member Function Documentation
KALDI_DISALLOW_COPY_AND_ASSIGN (Mutex) private
void Lock ()
Definition at line 56 of file kaldi-mutex.cc.
References KALDI_ERR, and Mutex::mutex_.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), IvectorExtractorStats::CommitStatsForM(), IvectorExtractorStats::CommitStatsForPrior(), IvectorExtractorStats::CommitStatsForSigma(), IvectorExtractorStats::CommitStatsForWPoint(), DiscriminativeExamplesRepository::ExamplesDone(), IvectorExtractorStats::FlushCache(), OnlineNaturalGradient::PreconditionDirections(), OnlinePreconditioner::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), DiscriminativeExamplesRepository::ProvideExample(), NonlinearComponent::StoreStatsInternal(), kaldi::TestMutex(), and NonlinearComponent::UpdateStats().
                  {
   int ret;
   if ((ret = pthread_mutex_lock(&mutex_)) != 0)
     KALDI_ERR << "Error on locking pthread mutex, error is: "
               << strerror(ret);
 }
bool TryLock ()
Try to lock the mutex without waiting for it.
Returns: true when lock successfull, false when mutex was already locked
Definition at line 64 of file kaldi-mutex.cc.
References KALDI_ERR, and Mutex::mutex_.
Referenced by OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), and kaldi::TestMutex().
                     {
   int32 ret = pthread_mutex_trylock(&mutex_);
   bool lock_succeeded = false;
   switch (ret) {
     case 0: lock_succeeded = true; break;
     case EBUSY: lock_succeeded = false; break;
     default: KALDI_ERR << "Error on try-locking pthread mutex, error is: "
                        << strerror(ret);
   }
   return lock_succeeded;
 }
void Unlock ()
Definition at line 77 of file kaldi-mutex.cc.
References KALDI_ERR, and Mutex::mutex_.
Referenced by DiscriminativeExamplesRepository::AcceptExample(), IvectorExtractorStats::CommitStatsForM(), IvectorExtractorStats::CommitStatsForPrior(), IvectorExtractorStats::CommitStatsForSigma(), IvectorExtractorStats::CommitStatsForWPoint(), DiscriminativeExamplesRepository::ExamplesDone(), IvectorExtractorStats::FlushCache(), OnlineNaturalGradient::PreconditionDirections(), OnlinePreconditioner::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), DiscriminativeExamplesRepository::ProvideExample(), NonlinearComponent::StoreStatsInternal(), kaldi::TestMutex(), and NonlinearComponent::UpdateStats().
                    {
   int ret;
   if ((ret = pthread_mutex_unlock(&mutex_)) != 0)
     KALDI_ERR << "Error on unlocking pthread mutex, error is: "
               << strerror(ret);
 }
Member Data Documentation
pthread_mutex_t mutex_ private
Definition at line 53 of file kaldi-mutex.h.
Referenced by Mutex::Lock(), Mutex::Mutex(), Mutex::TryLock(), Mutex::Unlock(), and Mutex::~Mutex().
The documentation for this class was generated from the following files:
thread/kaldi-mutex.h
thread/kaldi-mutex.cc