Kaldi: IvectorExtractorUtteranceStats Class Reference
IvectorExtractorUtteranceStats Class Reference
These are the stats for a particular utterance, i.e.
#include <ivector-extractor.h>
Public Member Functions
IvectorExtractorUtteranceStats (int32 num_gauss, int32 feat_dim, bool need_2nd_order_stats)
void AccStats (const MatrixBase< BaseFloat > &feats, const Posterior &post)
void Scale (double scale)
double NumFrames ()
Protected Attributes
Vector< double > gamma_
Matrix< double > X_
std::vector< SpMatrix< double > > S_
Friends
class IvectorExtractor
class IvectorExtractorStats
Detailed Description
These are the stats for a particular utterance, i.e.
the sufficient stats for estimating an iVector (if need_2nd_order_stats == true, we can also estimate the variance of the model; these 2nd order stats are not needed if we just need the iVector.
Definition at line 79 of file ivector-extractor.h.
Constructor & Destructor Documentation
IvectorExtractorUtteranceStats (int32 num_gauss, int32 feat_dim, bool need_2nd_order_stats) inline
Definition at line 81 of file ivector-extractor.h.
References rnnlm::i, and IvectorExtractorUtteranceStats::S_.
                                                            :
       gamma_(num_gauss), X_(num_gauss, feat_dim) {
     if (need_2nd_order_stats) {
       S_.resize(num_gauss);
       for (int32 i = 0; i < num_gauss; i++)
         S_[i].Resize(feat_dim);
     }
   }
Member Function Documentation
void AccStats (const MatrixBase< BaseFloat > & feats, const Posterior & post)
Definition at line 751 of file ivector-extractor.cc.
References SpMatrix< Real >::AddVec2(), IvectorExtractorUtteranceStats::gamma_, rnnlm::i, KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), IvectorExtractorUtteranceStats::S_, PackedMatrix< Real >::SetZero(), and IvectorExtractorUtteranceStats::X_.
Referenced by IvectorExtractorStats::AccStatsForUtterance(), IvectorExtractTask::operator()(), and kaldi::TestIvectorExtraction().
{
   typedef std::vector<std::pair<int32, BaseFloat> > VecType;
   int32 num_frames = feats.NumRows(),
       num_gauss = X_.NumRows(),
       feat_dim = feats.NumCols();
   KALDI_ASSERT(X_.NumCols() == feat_dim);
   KALDI_ASSERT(feats.NumRows() == static_cast<int32>(post.size()));
   bool update_variance = (!S_.empty());
   SpMatrix<double> outer_prod(feat_dim);
   for (int32 t = 0; t < num_frames; t++) {
     SubVector<BaseFloat> frame(feats, t);
     const VecType &this_post(post[t]);
     if (update_variance) {
       outer_prod.SetZero();
       outer_prod.AddVec2(1.0, frame);
     }
     for (VecType::const_iterator iter = this_post.begin();
          iter != this_post.end(); ++iter) {
       int32 i = iter->first; // Gaussian index.
       KALDI_ASSERT(i >= 0 && i < num_gauss &&
                    "Out-of-range Gaussian (mismatched posteriors?)");
       double weight = iter->second;
       gamma_(i) += weight;
       X_.Row(i).AddVec(weight, frame);
       if (update_variance)
         S_[i].AddSp(weight, outer_prod);
     }
   }
 }
double NumFrames () inline
Definition at line 96 of file ivector-extractor.h.
References IvectorExtractorUtteranceStats::gamma_, and VectorBase< Real >::Sum().
Referenced by kaldi::TestIvectorExtraction().
 { return gamma_.Sum(); }
void Scale (double scale)
Definition at line 783 of file ivector-extractor.cc.
References IvectorExtractorUtteranceStats::gamma_, rnnlm::i, IvectorExtractorUtteranceStats::S_, MatrixBase< Real >::Scale(), VectorBase< Real >::Scale(), and IvectorExtractorUtteranceStats::X_.
{
   gamma_.Scale(scale);
   X_.Scale(scale);
   for (size_t i = 0; i < S_.size(); i++)
     S_[i].Scale(scale);
 }
Friends And Related Function Documentation
friend class IvectorExtractor friend
Definition at line 99 of file ivector-extractor.h.
friend class IvectorExtractorStats friend
Definition at line 100 of file ivector-extractor.h.
Member Data Documentation
Vector<double> gamma_ protected
Definition at line 101 of file ivector-extractor.h.
Referenced by IvectorExtractorUtteranceStats::AccStats(), IvectorExtractorStats::CommitStatsForM(), IvectorExtractorStats::CommitStatsForWPoint(), IvectorExtractor::GetAcousticAuxf(), IvectorExtractor::GetAcousticAuxfGconst(), IvectorExtractor::GetAcousticAuxfMean(), IvectorExtractor::GetAcousticAuxfVariance(), IvectorExtractor::GetAcousticAuxfWeight(), IvectorExtractor::GetAuxf(), IvectorExtractor::GetIvectorDistMean(), IvectorExtractor::GetIvectorDistWeight(), IvectorExtractorUtteranceStats::NumFrames(), and IvectorExtractorUtteranceStats::Scale().
std::vector<SpMatrix<double> > S_ protected
Definition at line 103 of file ivector-extractor.h.
Referenced by IvectorExtractorUtteranceStats::AccStats(), IvectorExtractorStats::CommitStatsForSigma(), IvectorExtractor::GetAcousticAuxfVariance(), IvectorExtractorUtteranceStats::IvectorExtractorUtteranceStats(), and IvectorExtractorUtteranceStats::Scale().
Matrix<double> X_ protected
Definition at line 102 of file ivector-extractor.h.
Referenced by IvectorExtractorUtteranceStats::AccStats(), IvectorExtractorStats::CommitStatsForM(), IvectorExtractor::GetAcousticAuxfMean(), IvectorExtractor::GetAcousticAuxfVariance(), IvectorExtractor::GetIvectorDistMean(), and IvectorExtractorUtteranceStats::Scale().
The documentation for this class was generated from the following files:
ivector/ivector-extractor.h
ivector/ivector-extractor.cc