Kaldi: FixedScaleComponent Class Reference
FixedScaleComponent Class Reference
FixedScaleComponent applies a fixed per-element scale; it's similar to the Rescale component in the nnet1 setup (and only needed for nnet1 model conversion).
#include <nnet-component.h>
Public Member Functions
FixedScaleComponent ()
virtual std::string Type () const
virtual std::string Info () const
void Init (const CuVectorBase< BaseFloat > &scales)
virtual void InitFromString (std::string args)
Initialize, typically from a line of a config file.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Protected Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedScaleComponent)
Protected Attributes
CuVector< BaseFloat > scales_
Friends
class AffineComponent
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Detailed Description
FixedScaleComponent applies a fixed per-element scale; it's similar to the Rescale component in the nnet1 setup (and only needed for nnet1 model conversion).
Definition at line 1501 of file nnet-component.h.
Constructor & Destructor Documentation
FixedScaleComponent () inline
Definition at line 1503 of file nnet-component.h.
Referenced by FixedScaleComponent::Copy().
 { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 3429 of file nnet-component.cc.
References CuMatrixBase< Real >::MulColsVec(), and FixedScaleComponent::scales_.
{
   *in_deriv = out_deriv;
   in_deriv->MulColsVec(scales_);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 1527 of file nnet-component.h.
 { return false; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 1528 of file nnet-component.h.
 { return false; }
Component * Copy () const virtual
Copy component (deep copy).
Implements Component.
Definition at line 3440 of file nnet-component.cc.
References FixedScaleComponent::FixedScaleComponent(), and FixedScaleComponent::scales_.
{
   FixedScaleComponent *ans = new FixedScaleComponent();
   ans->scales_ = scales_;
   return ans;
 }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 3410 of file nnet-component.cc.
References CuVectorBase< Real >::Dim(), Component::Info(), FixedScaleComponent::scales_, CuVectorBase< Real >::Sum(), and kaldi::VecVec().
{
   std::stringstream stream;
   BaseFloat scales_size = static_cast<BaseFloat>(scales_.Dim()),
       scales_mean = scales_.Sum() / scales_size,
       scales_stddev = std::sqrt(VecVec(scales_, scales_) / scales_size
        - (scales_mean * scales_mean));
   stream << Component::Info() << ", scales-mean=" << scales_mean
          << ", scales-stddev=" << scales_stddev;
   return stream.str();
 }
void Init (const CuVectorBase< BaseFloat > & scales)
Definition at line 3390 of file nnet-component.cc.
References CuVectorBase< Real >::Dim(), KALDI_ASSERT, and FixedScaleComponent::scales_.
Referenced by kaldi::ConvertRescaleComponent(), FixedScaleComponent::InitFromString(), and kaldi::nnet2::UnitTestFixedScaleComponent().
{
   KALDI_ASSERT(scales.Dim() != 0);
   scales_ = scales;
 }
void InitFromString (std::string args) virtual
Initialize, typically from a line of a config file.
The "args" will contain any parameters that need to be passed to the Component, e.g. dimensions.
Implements Component.
Definition at line 3395 of file nnet-component.cc.
References FixedScaleComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), kaldi::ReadKaldiObject(), and FixedScaleComponent::Type().
{
   std::string orig_args = args;
   std::string filename;
   bool ok = ParseFromString("scales", &args, &filename);
   if (!ok || !args.empty())
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   CuVector<BaseFloat> vec;
   ReadKaldiObject(filename, &vec);
   Init(vec);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Implements Component.
Definition at line 1513 of file nnet-component.h.
References CuVectorBase< Real >::Dim(), and FixedScaleComponent::scales_.
Referenced by AffineComponent::CollapseWithNext().
 { return scales_.Dim(); }
KALDI_DISALLOW_COPY_AND_ASSIGN (FixedScaleComponent) protected
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Implements Component.
Definition at line 1514 of file nnet-component.h.
References CuVectorBase< Real >::Dim(), and FixedScaleComponent::scales_.
 { return scales_.Dim(); }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 3421 of file nnet-component.cc.
References CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::MulColsVec(), and FixedScaleComponent::scales_.
{
   out->CopyFromMat(in);
   out->MulColsVec(scales_);
 }
void Read (std::istream & is, bool binary) virtual
Implements Component.
Definition at line 3454 of file nnet-component.cc.
References kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), CuVector< Real >::Read(), and FixedScaleComponent::scales_.
{
   ExpectOneOrTwoTokens(is, binary, "<FixedScaleComponent>", "<Scales>");
   scales_.Read(is, binary);
   ExpectToken(is, binary, "</FixedScaleComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 1504 of file nnet-component.h.
Referenced by FixedScaleComponent::InitFromString().
 { return "FixedScaleComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Implements Component.
Definition at line 3447 of file nnet-component.cc.
References FixedScaleComponent::scales_, CuVector< Real >::Write(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<FixedScaleComponent>");
   WriteToken(os, binary, "<Scales>");
   scales_.Write(os, binary);
   WriteToken(os, binary, "</FixedScaleComponent>");
 }
Friends And Related Function Documentation
friend class AffineComponent friend
Definition at line 1534 of file nnet-component.h.
Member Data Documentation
CuVector<BaseFloat> scales_ protected
Definition at line 1535 of file nnet-component.h.
Referenced by FixedScaleComponent::Backprop(), AffineComponent::CollapseWithNext(), FixedScaleComponent::Copy(), FixedScaleComponent::Info(), FixedScaleComponent::Init(), FixedScaleComponent::InputDim(), FixedScaleComponent::OutputDim(), FixedScaleComponent::Propagate(), FixedScaleComponent::Read(), and FixedScaleComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc