Kaldi: NBestDecoder::TokenStore Class Reference
NBestDecoder::TokenStore Class Reference
Classes
struct SeqToken
class Token
Public Types
typedef HashList< StateId,
Token * > TokenHash
typedef TokenHash::Elem Elem
Public Member Functions
void Init (DecodableInterface *decodable, TokenHash *toks, int32 n_best)
void DeleteSeq (SeqToken *seq)
SeqToken * NewSeq ()
SeqToken * CreateSeq (Label input, SeqToken *prev)
void DeleteTok (Token *tok)
Token * CreateTok (Label output, Token *prev)
Token * Combine (Token *tok1, Token *tok2)
bool CombineN (Elem *head, Token *new_tok)
Token * Advance (Token *source, Arc &arc, int32 frame, BaseFloat cutoff)
void Clear ()
TokenStore ()
~TokenStore ()
Private Attributes
Token * free_t_head_
std::vector< Token * > allocated_t_
SeqToken * free_st_head_
std::vector< SeqToken * > allocated_s_
DecodableInterface * decodable_
TokenHash * toks_
int32 n_best_
Static Private Attributes
static const size_t allocate_block_size_ = 8192
Detailed Description
Definition at line 238 of file nbest-decoder.h.
Member Typedef Documentation
typedef TokenHash::Elem Elem
Definition at line 275 of file nbest-decoder.h.
typedef HashList<StateId, Token*> TokenHash
Definition at line 274 of file nbest-decoder.h.
Constructor & Destructor Documentation
TokenStore () inline
Definition at line 474 of file nbest-decoder.h.
References NBestDecoder::TokenStore::free_st_head_, and NBestDecoder::TokenStore::free_t_head_.
                  {
       free_t_head_ = NULL;
       free_st_head_ = NULL;
     }
~TokenStore () inline
Definition at line 478 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Clear().
                   {
       Clear();
     }
Member Function Documentation
Token* Advance (Token * source, Arc & arc, int32 frame, BaseFloat cutoff) inline
Definition at line 436 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Token::c, NBestDecoder::TokenStore::Token::ca, NBestDecoder::TokenStore::CreateSeq(), NBestDecoder::TokenStore::CreateTok(), NBestDecoder::TokenStore::decodable_, NBestDecoder::TokenStore::Token::I, DecodableInterface::LogLikelihood(), NBestDecoder::TokenStore::Token::o, NBestDecoder::TokenStore::Token::previous, and fst::Times().
Referenced by NBestDecoder::PropagateEmitting(), and NBestDecoder::PropagateEpsilon().
{
       // compute new weight
       Weight w = Times(source->c, arc.weight);
       Weight amscore = Weight::One();
       if (arc.ilabel > 0) { // emitting arc
         amscore = Weight(- decodable_->LogLikelihood(frame, arc.ilabel));
         w = Times(w, amscore);
       }
       Weight wa = Times(source->ca, amscore);
       if (w.Value() > cutoff) {  // prune
         return NULL;
       }
       // create new token
       Token *tok;
       if (arc.olabel > 0) { // create new token
         // find or create corresponding Token
         tok = CreateTok(arc.olabel, source); // "new" Token
         tok->I = CreateSeq(arc.ilabel, NULL); // new sequence I starts
       } else { // append sequence I
         tok = CreateTok(source->o, source->previous); // copy previous Token
         tok->I = CreateSeq(arc.ilabel, source->I);
       }
       tok->c = w;
       tok->ca = wa;
       return tok;
     }
void Clear () inline
Definition at line 464 of file nbest-decoder.h.
References NBestDecoder::TokenStore::allocated_s_, NBestDecoder::TokenStore::allocated_t_, NBestDecoder::TokenStore::free_st_head_, NBestDecoder::TokenStore::free_t_head_, and rnnlm::i.
Referenced by NBestDecoder::TokenStore::Init(), NBestDecoder::~NBestDecoder(), and NBestDecoder::TokenStore::~TokenStore().
                  {
       // check that all seq tokens are freed
       for (size_t i = 0; i < allocated_t_.size(); i++) delete[] allocated_t_[i];
       allocated_t_.clear();
       free_t_head_ = NULL;
       // check that all seq tokens are freed
       for (size_t i = 0; i < allocated_s_.size(); i++) delete[] allocated_s_[i];
       allocated_s_.clear();
       free_st_head_ = NULL;
     }
Token* Combine (Token * tok1, Token * tok2) inline
Definition at line 379 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Token::c, NBestDecoder::TokenStore::DeleteTok(), and KALDI_ASSERT.
                                                     { // Viterbi version
       KALDI_ASSERT(tok1);
       if (!tok2) return tok1;
       if (tok1 == tok2) return tok1;
       if (tok1->c.Value() < tok2->c.Value()) {
         DeleteTok(tok2);
         return tok1;
       } else {
         DeleteTok(tok1);
         return tok2;
       }
     }
bool CombineN (Elem * head, Token * new_tok) inline
Definition at line 392 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Token::c, count, NBestDecoder::TokenStore::DeleteTok(), NBestDecoder::TokenStore::Token::Equal(), HashList< I, T >::InsertMore(), NBestDecoder::TokenStore::n_best_, and NBestDecoder::TokenStore::toks_.
Referenced by NBestDecoder::GetNBestLattice(), NBestDecoder::PropagateEmitting(), and NBestDecoder::PropagateEpsilon().
                                                      { // n-best version
       if (!new_tok) return false;
       Elem *e = head;
       StateId state = e->key;
       BaseFloat new_weight = static_cast<BaseFloat>(new_tok->c.Value());
       size_t count = 0;
       BaseFloat worst_weight = 0.0;  // small == low cost
       Elem *worst_elem = NULL;
       do {
         count++;
         Token *tok = e->val;
         if (tok == new_tok) { return false; }
         BaseFloat w = static_cast<BaseFloat>(tok->c.Value());
         if (w > worst_weight) {
           worst_weight = w;
           worst_elem = e;
         }
         if (tok->Equal(new_tok)) { // if they have the same output sequence
           if (w < new_weight) {
             DeleteTok(new_tok);
             return false;
           } else {
             DeleteTok(tok);
             e->val = new_tok;
             return true;
           }
         }
         e = e->tail;
       } while ( (e != NULL) && (e->key == state) );
       // if we are here, no Token with the same output sequence was found
       if (count < n_best_) {
         toks_->InsertMore(state, new_tok);
         return true;
       } else {
         if (worst_weight < new_weight) {
           DeleteTok(new_tok);
           return false;
         } else {
           DeleteTok(worst_elem->val);
           worst_elem->val = new_tok;
           return true;
         }
       }
     }
SeqToken* CreateSeq (Label input, SeqToken * prev) inline
Definition at line 313 of file nbest-decoder.h.
References NBestDecoder::TokenStore::SeqToken::i, NBestDecoder::TokenStore::NewSeq(), NBestDecoder::TokenStore::SeqToken::previous, and NBestDecoder::TokenStore::SeqToken::refs.
Referenced by NBestDecoder::TokenStore::Advance().
{
       SeqToken *tmp = NULL;
       if (input > 0) {
         tmp = NewSeq();
         tmp->i = input;
         tmp->previous = prev;
         if (prev) {
           prev->refs++;
         }
       } else {
         if (prev) {
           tmp = prev;
           if (prev) { // prev->previous?
             prev->refs++;
           }
         }
       }
       return tmp;
     }
Token* CreateTok (Label output, Token * prev) inline
Definition at line 349 of file nbest-decoder.h.
References NBestDecoder::TokenStore::allocate_block_size_, NBestDecoder::TokenStore::allocated_t_, NBestDecoder::TokenStore::Token::c, NBestDecoder::TokenStore::free_t_head_, NBestDecoder::TokenStore::Token::hash, rnnlm::i, NBestDecoder::TokenStore::Token::I, NBestDecoder::TokenStore::Token::o, NBestDecoder::TokenStore::Token::previous, and NBestDecoder::TokenStore::Token::refs.
Referenced by NBestDecoder::TokenStore::Advance(), NBestDecoder::Decode(), and NBestDecoder::GetNBestLattice().
{
       // new token: either take from linked list or extend list
       Token *tmp;
       if (free_t_head_) {  // take from free list
         tmp = free_t_head_;
         free_t_head_ = free_t_head_->previous;
       } else {  // make new entries in free list
         tmp = new Token[allocate_block_size_];
         for (size_t i = 0; i + 1 < allocate_block_size_; i++) {
           tmp[i].previous = tmp + i + 1;
         }
         tmp[allocate_block_size_ - 1].previous = NULL;
         allocated_t_.push_back(tmp);
         free_t_head_ = tmp->previous;
       }
       // initialize data
       tmp->refs = 1;
       tmp->c = Weight::Zero();
       tmp->I = NULL;
       tmp->o = output;
       tmp->previous = prev;
       if (prev) {
         prev->refs++;
         tmp->hash = prev->hash * 97 + static_cast<unsigned>(output);
       } else {
         tmp->hash = static_cast<unsigned>(output);
       }
       return tmp;
     }
void DeleteSeq (SeqToken * seq) inline
Definition at line 283 of file nbest-decoder.h.
References NBestDecoder::TokenStore::free_st_head_, NBestDecoder::TokenStore::SeqToken::previous, and NBestDecoder::TokenStore::SeqToken::refs.
Referenced by NBestDecoder::TokenStore::DeleteTok().
{
       // delete seq token: either decrease reference count or put to linked list
       seq->refs--;
       if (seq->refs > 0) return;
       // really kill sequence token
       // clean up unused sequence tokens recursively backwards
       if (seq->previous != NULL) DeleteSeq(seq->previous);
       // save the unused sequence token in linked list (abusing *previous)
       seq->previous = free_st_head_;
       free_st_head_ = seq;
     }
void DeleteTok (Token * tok) inline
Definition at line 333 of file nbest-decoder.h.
References NBestDecoder::TokenStore::DeleteSeq(), NBestDecoder::TokenStore::free_t_head_, NBestDecoder::TokenStore::Token::I, NBestDecoder::TokenStore::Token::previous, and NBestDecoder::TokenStore::Token::refs.
Referenced by NBestDecoder::ClearToks(), NBestDecoder::TokenStore::Combine(), NBestDecoder::TokenStore::CombineN(), NBestDecoder::GetNBestLattice(), and NBestDecoder::PropagateEmitting().
{
       // delete token: either decrease reference count or put to linked list
       tok->refs--;
       if (tok->refs > 0) return;
       // really kill token
       // clean up unused tokens recursively backwards
       if (tok->previous != NULL) {
         DeleteTok(tok->previous);
       }
       if (tok->I != NULL) { // delete sequence I
         DeleteSeq(tok->I);
       }
       // save the unused token in linked list (abusing *previous)
       tok->previous = free_t_head_;
       free_t_head_ = tok;
     }
void Init (DecodableInterface * decodable, TokenHash * toks, int32 n_best) inline
Definition at line 276 of file nbest-decoder.h.
References NBestDecoder::TokenStore::Clear(), NBestDecoder::TokenStore::decodable_, NBestDecoder::TokenStore::n_best_, and NBestDecoder::TokenStore::toks_.
Referenced by NBestDecoder::Decode().
{
       Clear();
       n_best_ = n_best;
       decodable_ = decodable;
       toks_ = toks;
     }
SeqToken* NewSeq () inline
Definition at line 294 of file nbest-decoder.h.
References NBestDecoder::TokenStore::allocate_block_size_, NBestDecoder::TokenStore::allocated_s_, NBestDecoder::TokenStore::free_st_head_, rnnlm::i, NBestDecoder::TokenStore::SeqToken::previous, and NBestDecoder::TokenStore::SeqToken::refs.
Referenced by NBestDecoder::TokenStore::CreateSeq().
{
       // new seq token: either take from linked list or extend list
       SeqToken *tmp;
       if (free_st_head_) {  // take from free list
         tmp = free_st_head_;
         free_st_head_ = free_st_head_->previous;
       } else {  // make new entries in free list
         tmp = new SeqToken[allocate_block_size_];
         for (size_t i = 0; i + 1 < allocate_block_size_; i++) {
           tmp[i].previous = tmp + i + 1;
         }
         tmp[allocate_block_size_ - 1].previous = NULL;
         allocated_s_.push_back(tmp);
         free_st_head_ = tmp->previous;
       }
       // initialize new sequence token (append or start new sequence)
       tmp->refs = 1;
       return tmp;
     }
Member Data Documentation
const size_t allocate_block_size_ = 8192 static private
Definition at line 492 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::CreateTok(), and NBestDecoder::TokenStore::NewSeq().
std::vector<SeqToken*> allocated_s_ private
Definition at line 487 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::Clear(), and NBestDecoder::TokenStore::NewSeq().
std::vector<Token*> allocated_t_ private
Definition at line 484 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::Clear(), and NBestDecoder::TokenStore::CreateTok().
DecodableInterface* decodable_ private
Definition at line 488 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::Advance(), and NBestDecoder::TokenStore::Init().
SeqToken* free_st_head_ private
Definition at line 486 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::Clear(), NBestDecoder::TokenStore::DeleteSeq(), NBestDecoder::TokenStore::NewSeq(), and NBestDecoder::TokenStore::TokenStore().
Token* free_t_head_ private
Definition at line 483 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::Clear(), NBestDecoder::TokenStore::CreateTok(), NBestDecoder::TokenStore::DeleteTok(), and NBestDecoder::TokenStore::TokenStore().
int32 n_best_ private
Definition at line 490 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::CombineN(), and NBestDecoder::TokenStore::Init().
TokenHash* toks_ private
Definition at line 489 of file nbest-decoder.h.
Referenced by NBestDecoder::TokenStore::CombineN(), and NBestDecoder::TokenStore::Init().
The documentation for this class was generated from the following file:
decoder/nbest-decoder.h