Kaldi: SwitchingForwardingDescriptor Class Reference
SwitchingForwardingDescriptor Class Reference
#include <nnet-descriptor.h>
Public Member Functions
virtual Cindex MapToInput (const Index &ind) const
virtual int32 Dim (const Nnet &nnet) const
virtual ForwardingDescriptor * Copy () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" all the node indexes.
SwitchingForwardingDescriptor (std::vector< ForwardingDescriptor * > &src)
virtual ~SwitchingForwardingDescriptor ()
Public Member Functions inherited from ForwardingDescriptor
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Attributes
std::vector
< ForwardingDescriptor * > src_
Detailed Description
Definition at line 176 of file nnet-descriptor.h.
Constructor & Destructor Documentation
SwitchingForwardingDescriptor (std::vector< ForwardingDescriptor * > & src) inline
Definition at line 192 of file nnet-descriptor.h.
Referenced by SwitchingForwardingDescriptor::Copy().
                                                                       :
       src_(src) { }
virtual ~SwitchingForwardingDescriptor () inline virtual
Definition at line 194 of file nnet-descriptor.h.
References kaldi::DeletePointers(), and SwitchingForwardingDescriptor::src_.
 { DeletePointers(&src_); }
Member Function Documentation
ForwardingDescriptor * Copy () const virtual
Implements ForwardingDescriptor.
Definition at line 148 of file nnet-descriptor.cc.
References rnnlm::i, SwitchingForwardingDescriptor::src_, and SwitchingForwardingDescriptor::SwitchingForwardingDescriptor().
{
   std::vector<ForwardingDescriptor*> src_copy(src_.size());
   for (size_t i = 0; i < src_.size(); i++)
     src_copy[i] = src_[i]->Copy();
   return new SwitchingForwardingDescriptor(src_copy);
 }
virtual int32 Dim (const Nnet & nnet) const inline virtual
Implements ForwardingDescriptor.
Definition at line 179 of file nnet-descriptor.h.
References SwitchingForwardingDescriptor::src_.
 { return src_[0]->Dim(nnet); }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" all the node indexes.
Implements ForwardingDescriptor.
Definition at line 133 of file nnet-descriptor.cc.
References rnnlm::i, and SwitchingForwardingDescriptor::src_.
{
   for (size_t i = 0; i < src_.size(); i++)
     src_[i]->GetNodeDependencies(node_indexes);
 }
Cindex MapToInput (const Index & ind) const virtual
Implements ForwardingDescriptor.
Definition at line 139 of file nnet-descriptor.cc.
References KALDI_ASSERT, SwitchingForwardingDescriptor::src_, and Index::t.
{
   KALDI_ASSERT(!src_.empty());
   int32 size = src_.size(), mod = ind.t % size;
   // next line gets "mathematical" modulus, not broken "C" modulus.
   if (mod < 0) mod += size;
   return src_[mod]->MapToInput(ind);
 }
int32 Modulus () const virtual
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
It returns the smallest modulus to which this descriptor is invariant; the lowest common multiple of all descriptors in the network gives you the modulus for the whole network.
Reimplemented from ForwardingDescriptor.
Definition at line 373 of file nnet-descriptor.cc.
References rnnlm::i, kaldi::Lcm(), and SwitchingForwardingDescriptor::src_.
{
   int32 ans = src_.size();;
   for (int32 i = 0; i < src_.size(); i++)
     ans = Lcm(ans, src_[i]->Modulus());
   return ans;
 }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Implements ForwardingDescriptor.
Definition at line 156 of file nnet-descriptor.cc.
References rnnlm::i, KALDI_ASSERT, and SwitchingForwardingDescriptor::src_.
{
   KALDI_ASSERT(!src_.empty());
   os << "Switch(";
   for (size_t i = 0; i < src_.size(); i++) {
     src_[i]->WriteConfig(os, node_names);
     if (i + 1 < src_.size())
       os << ", ";
   }
   os << ")";
 }
Member Data Documentation
std::vector<ForwardingDescriptor*> src_ private
Definition at line 197 of file nnet-descriptor.h.
Referenced by SwitchingForwardingDescriptor::Copy(), SwitchingForwardingDescriptor::Dim(), SwitchingForwardingDescriptor::GetNodeDependencies(), SwitchingForwardingDescriptor::MapToInput(), SwitchingForwardingDescriptor::Modulus(), SwitchingForwardingDescriptor::WriteConfig(), and SwitchingForwardingDescriptor::~SwitchingForwardingDescriptor().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc