Kaldi: NormalizeComponent Class Reference
NormalizeComponent Class Reference
#include <nnet-component.h>
Public Member Functions
NormalizeComponent (int32 dim)
NormalizeComponent (const NormalizeComponent &other)
NormalizeComponent ()
virtual std::string Type () const
virtual Component * Copy () const
Copy component (deep copy).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Public Member Functions inherited from NonlinearComponent
void Init (int32 dim)
NonlinearComponent (int32 dim)
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void InitFromString (std::string args)
We implement InitFromString at this level.
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
void Scale (BaseFloat scale)
void Add (BaseFloat alpha, const NonlinearComponent &other)
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
void SetDim (int32 dim)
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual std::string Info () const
virtual ~Component ()
Private Member Functions
NormalizeComponent & operator= (const NormalizeComponent &other)
Static Private Attributes
static const BaseFloat kNormFloor = pow(2.0, -66)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Protected Member Functions inherited from NonlinearComponent
void UpdateStats (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
Mutex mutex_
Detailed Description
Definition at line 555 of file nnet-component.h.
Constructor & Destructor Documentation
NormalizeComponent (int32 dim) inline explicit
Definition at line 557 of file nnet-component.h.
 : NonlinearComponent(dim) { }
NormalizeComponent (const NormalizeComponent & other) inline explicit
Definition at line 558 of file nnet-component.h.
 : NonlinearComponent(other) { }
NormalizeComponent () inline
Definition at line 559 of file nnet-component.h.
Referenced by NormalizeComponent::Copy().
 { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 608 of file nnet-component.cc.
References CuVectorBase< Real >::AddDiagMat2(), CuVectorBase< Real >::AddDiagMatMat(), CuMatrixBase< Real >::AddDiagVecMat(), NormalizeComponent::kNormFloor, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
{
   in_deriv->Resize(out_deriv.NumRows(), out_deriv.NumCols());
   CuVector<BaseFloat> in_norm(in_value.NumRows());
   in_norm.AddDiagMat2(1.0 / in_value.NumCols(),
                       in_value, kNoTrans, 0.0);
   in_norm.ApplyFloor(kNormFloor);
   in_norm.ApplyPow(-0.5);
   in_deriv->AddDiagVecMat(1.0, in_norm, out_deriv, kNoTrans, 0.0);
   in_norm.ReplaceValue(1.0 / sqrt(kNormFloor), 0.0);
   in_norm.ApplyPow(3.0);
   CuVector<BaseFloat> dot_products(in_deriv->NumRows());
   dot_products.AddDiagMatMat(1.0, out_deriv, kNoTrans, in_value, kTrans, 0.0);
   dot_products.MulElements(in_norm);
   in_deriv->AddDiagVecMat(-1.0 / in_value.NumCols(), dot_products, in_value, kNoTrans, 1.0);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 562 of file nnet-component.h.
 { return true; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 563 of file nnet-component.h.
 { return false; }
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 561 of file nnet-component.h.
References NormalizeComponent::NormalizeComponent().
 { return new NormalizeComponent(*this); }
NormalizeComponent& operator= (const NormalizeComponent & other) private
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 572 of file nnet-component.cc.
References CuVectorBase< Real >::AddDiagMat2(), CuMatrixBase< Real >::CopyFromMat(), NormalizeComponent::kNormFloor, kaldi::kNoTrans, CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   out->CopyFromMat(in);
   CuVector<BaseFloat> in_norm(in.NumRows());
   in_norm.AddDiagMat2(1.0 / in.NumCols(),
                       in, kNoTrans, 0.0);
   in_norm.ApplyFloor(kNormFloor);
   in_norm.ApplyPow(-0.5);
   out->MulRowsVec(in_norm);
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 560 of file nnet-component.h.
 { return "NormalizeComponent"; }
Member Data Documentation
const BaseFloat kNormFloor = pow(2.0, -66) static private
Definition at line 578 of file nnet-component.h.
Referenced by NormalizeComponent::Backprop(), and NormalizeComponent::Propagate().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc