Kaldi: NaturalGradientAffineComponent Class Reference
NaturalGradientAffineComponent Class Reference
Keywords: natural gradient descent, NG-SGD, naturalgradient.
#include <nnet-simple-component.h>
Public Member Functions
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev, BaseFloat bias_mean, int32 rank_in, int32 rank_out, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_sample)
void Init (int32 rank_in, int32 rank_out, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_sample, std::string matrix_filename)
NaturalGradientAffineComponent ()
virtual void Resize (int32 input_dim, int32 output_dim)
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual Component * Copy () const
Copies component (deep copy).
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
NaturalGradientAffineComponent (const NaturalGradientAffineComponent &other)
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Public Member Functions inherited from AffineComponent
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
AffineComponent ()
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
virtual void SetParams (const VectorBase< BaseFloat > &bias, const MatrixBase< BaseFloat > &linear)
const CuVector< BaseFloat > & BiasParams ()
const CuMatrix< BaseFloat > & LinearParams ()
AffineComponent (const AffineComponent &other)
AffineComponent (const CuMatrixBase< BaseFloat > &linear_params, const CuVectorBase< BaseFloat > &bias_params, BaseFloat learning_rate)
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev)
void Init (std::string matrix_filename)
Component * CollapseWithNext (const AffineComponent &next) const
Component * CollapseWithNext (const FixedAffineComponent &next) const
Component * CollapseWithNext (const FixedScaleComponent &next) const
Component * CollapseWithPrevious (const FixedAffineComponent &prev) const
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Private Member Functions
NaturalGradientAffineComponent & operator= (const NaturalGradientAffineComponent &)
void SetNaturalGradientConfigs ()
virtual void Update (const std::string &debug_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
Private Attributes
int32 rank_in_
int32 rank_out_
int32 update_period_
BaseFloat num_samples_history_
BaseFloat alpha_
OnlineNaturalGradient preconditioner_in_
OnlineNaturalGradient preconditioner_out_
BaseFloat max_change_per_sample_
double update_count_
double active_scaling_count_
double max_change_scale_stats_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from AffineComponent
virtual void UpdateSimple (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const AffineComponent & operator= (const AffineComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from AffineComponent
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Detailed Description
Keywords: natural gradient descent, NG-SGD, naturalgradient.
For the top-level of the natural gradient code look here, and also in nnet-precondition-online.h. NaturalGradientAffineComponent is a version of AffineComponent that has a non-(multiple of unit) learning-rate matrix. See nnet-precondition-online.h for a description of the technique. It is described, under the name Online NG-SGD, in the paper "Parallel training of DNNs with Natural Gradient and Parameter Averaging" (ICLR workshop, 2015) by Daniel Povey, Xiaohui Zhang and Sanjeev Khudanpur.
Definition at line 628 of file nnet-simple-component.h.
Constructor & Destructor Documentation
NaturalGradientAffineComponent ()
Definition at line 1956 of file nnet-simple-component.cc.
Referenced by NaturalGradientAffineComponent::Copy().
                                                               :
     max_change_per_sample_(0.0),
     update_count_(0.0), active_scaling_count_(0.0),
     max_change_scale_stats_(0.0) { }
NaturalGradientAffineComponent (const NaturalGradientAffineComponent & other) explicit
Definition at line 2181 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::SetNaturalGradientConfigs().
                                                 :
     AffineComponent(other),
     rank_in_(other.rank_in_),
     rank_out_(other.rank_out_),
     update_period_(other.update_period_),
     num_samples_history_(other.num_samples_history_),
     alpha_(other.alpha_),
     preconditioner_in_(other.preconditioner_in_),
     preconditioner_out_(other.preconditioner_out_),
     max_change_per_sample_(other.max_change_per_sample_),
     update_count_(other.update_count_),
     active_scaling_count_(other.active_scaling_count_),
     max_change_scale_stats_(other.max_change_scale_stats_) {
   SetNaturalGradientConfigs();
 }
Member Function Documentation
void Add (BaseFloat alpha, const Component & other) virtual
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
– a NonlinearComponent it relates to adding stats Otherwise it should do nothing.
Reimplemented from AffineComponent.
Definition at line 2265 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddVec(), AffineComponent::bias_params_, KALDI_ASSERT, AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_scale_stats_, and NaturalGradientAffineComponent::update_count_.
{
   const NaturalGradientAffineComponent *other =
       dynamic_cast<const NaturalGradientAffineComponent*>(&other_in);
   KALDI_ASSERT(other != NULL);
   update_count_ += alpha * other->update_count_;
   max_change_scale_stats_ += alpha * other->max_change_scale_stats_;
   active_scaling_count_ += alpha * other->active_scaling_count_;
   linear_params_.AddMat(alpha, other->linear_params_);
   bias_params_.AddVec(alpha, other->bias_params_);
 }
Component * Copy () const virtual
Copies component (deep copy).
Reimplemented from AffineComponent.
Definition at line 2177 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::NaturalGradientAffineComponent().
{
   return new NaturalGradientAffineComponent(*this);
 }
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from AffineComponent.
Definition at line 2158 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, NaturalGradientAffineComponent::alpha_, AffineComponent::bias_params_, UpdatableComponent::Info(), AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_per_sample_, NaturalGradientAffineComponent::max_change_scale_stats_, NaturalGradientAffineComponent::num_samples_history_, kaldi::nnet3::PrintParameterStats(), NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, NaturalGradientAffineComponent::update_count_, and NaturalGradientAffineComponent::update_period_.
{
   std::ostringstream stream;
   stream << UpdatableComponent::Info();
   PrintParameterStats(stream, "linear-params", linear_params_);
   PrintParameterStats(stream, "bias", bias_params_, true);
   stream << ", rank-in=" << rank_in_
          << ", rank-out=" << rank_out_
          << ", num_samples_history=" << num_samples_history_
          << ", update_period=" << update_period_
          << ", alpha=" << alpha_
          << ", max-change-per-sample=" << max_change_per_sample_;
   if (update_count_ > 0.0 && max_change_per_sample_ > 0.0) {
     stream << ", avg-scaling-factor=" << max_change_scale_stats_ / update_count_
            << ", active-scaling-portion="
            << active_scaling_count_ / update_count_;
   }
   return stream.str();
 }
void Init (int32 input_dim, int32 output_dim, BaseFloat param_stddev, BaseFloat bias_stddev, BaseFloat bias_mean, int32 rank_in, int32 rank_out, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_sample)
Definition at line 2095 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, CuVectorBase< Real >::Add(), NaturalGradientAffineComponent::alpha_, AffineComponent::bias_params_, UpdatableComponent::is_gradient_, KALDI_ASSERT, KALDI_WARN, AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_per_sample_, NaturalGradientAffineComponent::max_change_scale_stats_, NaturalGradientAffineComponent::num_samples_history_, NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), CuVectorBase< Real >::SetRandn(), CuMatrixBase< Real >::SetRandn(), NaturalGradientAffineComponent::update_count_, and NaturalGradientAffineComponent::update_period_.
Referenced by NaturalGradientAffineComponent::InitFromConfig().
{
   linear_params_.Resize(output_dim, input_dim);
   bias_params_.Resize(output_dim);
   KALDI_ASSERT(output_dim > 0 && input_dim > 0 && param_stddev >= 0.0 &&
                bias_stddev >= 0.0);
   linear_params_.SetRandn(); // sets to random normally distributed noise.
   linear_params_.Scale(param_stddev);
   bias_params_.SetRandn();
   bias_params_.Scale(bias_stddev);
   bias_params_.Add(bias_mean);
   rank_in_ = rank_in;
   rank_out_ = rank_out;
   update_period_ = update_period;
   num_samples_history_ = num_samples_history;
   alpha_ = alpha;
   SetNaturalGradientConfigs();
   if (max_change_per_sample > 0.0)
     KALDI_WARN << "You are setting a positive max_change_per_sample for "
                << "NaturalGradientAffineComponent. But the per-component "
                << "gradient clipping mechansim has been removed. Instead it's currently "
                << "done at the whole model level.";
   max_change_per_sample_ = max_change_per_sample;
   is_gradient_ = false;  // not configurable; there's no reason you'd want this
   update_count_ = 0.0;
   active_scaling_count_ = 0.0;
   max_change_scale_stats_ = 0.0;
 }
void Init (int32 rank_in, int32 rank_out, int32 update_period, BaseFloat num_samples_history, BaseFloat alpha, BaseFloat max_change_per_sample, std::string matrix_filename)
Definition at line 2068 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, NaturalGradientAffineComponent::alpha_, AffineComponent::bias_params_, CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyFromMat(), UpdatableComponent::is_gradient_, KALDI_ASSERT, AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_per_sample_, NaturalGradientAffineComponent::max_change_scale_stats_, NaturalGradientAffineComponent::num_samples_history_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Range(), NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, kaldi::ReadKaldiObject(), CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), NaturalGradientAffineComponent::update_count_, and NaturalGradientAffineComponent::update_period_.
{
   rank_in_ = rank_in;
   rank_out_ = rank_out;
   update_period_ = update_period;
   num_samples_history_ = num_samples_history;
   alpha_ = alpha;
   SetNaturalGradientConfigs();
   KALDI_ASSERT(max_change_per_sample >= 0.0);
   max_change_per_sample_ = max_change_per_sample;
   CuMatrix<BaseFloat> mat;
   ReadKaldiObject(matrix_filename, &mat); // will abort on failure.
   KALDI_ASSERT(mat.NumCols() >= 2);
   int32 input_dim = mat.NumCols() - 1, output_dim = mat.NumRows();
   linear_params_.Resize(output_dim, input_dim);
   bias_params_.Resize(output_dim);
   linear_params_.CopyFromMat(mat.Range(0, output_dim, 0, input_dim));
   bias_params_.CopyColFromMat(mat, input_dim);
   is_gradient_ = false;  // not configurable; there's no reason you'd want this
   update_count_ = 0.0;
   active_scaling_count_ = 0.0;
   max_change_scale_stats_ = 0.0;
 }
void InitFromConfig (ConfigLine * cfl) virtual
Initialize, from a ConfigLine object.
Parameters
[in] cfl A ConfigLine containing any parameters that are needed for initialization. For example: "dim=100 param-stddev=0.1"
Reimplemented from AffineComponent.
Definition at line 2013 of file nnet-simple-component.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), NaturalGradientAffineComponent::Init(), UpdatableComponent::InitLearningRatesFromConfig(), AffineComponent::InputDim(), KALDI_ASSERT, KALDI_ERR, AffineComponent::OutputDim(), ConfigLine::UnusedValues(), and ConfigLine::WholeLine().
{
   bool ok = true;
   std::string matrix_filename;
   BaseFloat num_samples_history = 2000.0, alpha = 4.0,
       max_change_per_sample = 0.0;
   int32 input_dim = -1, output_dim = -1, rank_in = 20, rank_out = 80,
       update_period = 4;
   InitLearningRatesFromConfig(cfl);
   cfl->GetValue("num-samples-history", &num_samples_history);
   cfl->GetValue("alpha", &alpha);
   cfl->GetValue("max-change-per-sample", &max_change_per_sample);
   cfl->GetValue("rank-in", &rank_in);
   cfl->GetValue("rank-out", &rank_out);
   cfl->GetValue("update-period", &update_period);
   if (cfl->GetValue("matrix", &matrix_filename)) {
     Init(rank_in, rank_out, update_period,
          num_samples_history, alpha, max_change_per_sample,
          matrix_filename);
     if (cfl->GetValue("input-dim", &input_dim))
       KALDI_ASSERT(input_dim == InputDim() &&
                    "input-dim mismatch vs. matrix.");
     if (cfl->GetValue("output-dim", &output_dim))
       KALDI_ASSERT(output_dim == OutputDim() &&
                    "output-dim mismatch vs. matrix.");
   } else {
     ok = ok && cfl->GetValue("input-dim", &input_dim);
     ok = ok && cfl->GetValue("output-dim", &output_dim);
     BaseFloat param_stddev = 1.0 / std::sqrt(input_dim),
         bias_stddev = 1.0, bias_mean = 0.0;
     cfl->GetValue("param-stddev", &param_stddev);
     cfl->GetValue("bias-stddev", &bias_stddev);
     cfl->GetValue("bias-mean", &bias_mean);
     Init(input_dim, output_dim, param_stddev,
          bias_stddev, bias_mean, rank_in, rank_out, update_period,
          num_samples_history, alpha, max_change_per_sample);
   }
   if (cfl->HasUnusedValues())
     KALDI_ERR << "Could not process these elements in initializer: "
               << cfl->UnusedValues();
   if (!ok)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
NaturalGradientAffineComponent& operator= (const NaturalGradientAffineComponent &) private
void Read (std::istream & is, bool binary) virtual
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
Reimplemented from AffineComponent.
Definition at line 1976 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, NaturalGradientAffineComponent::alpha_, AffineComponent::bias_params_, kaldi::nnet3::ExpectToken(), UpdatableComponent::is_gradient_, KALDI_ERR, AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_per_sample_, NaturalGradientAffineComponent::max_change_scale_stats_, NaturalGradientAffineComponent::num_samples_history_, NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, CuVector< Real >::Read(), CuMatrix< Real >::Read(), kaldi::ReadBasicType(), kaldi::ReadToken(), UpdatableComponent::ReadUpdatableCommon(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), NaturalGradientAffineComponent::update_count_, and NaturalGradientAffineComponent::update_period_.
{
   ReadUpdatableCommon(is, binary);  // Read the opening tag and learning rate
   ExpectToken(is, binary, "<LinearParams>");
   linear_params_.Read(is, binary);
   ExpectToken(is, binary, "<BiasParams>");
   bias_params_.Read(is, binary);
   ExpectToken(is, binary, "<RankIn>");
   ReadBasicType(is, binary, &rank_in_);
   ExpectToken(is, binary, "<RankOut>");
   ReadBasicType(is, binary, &rank_out_);
   ExpectToken(is, binary, "<UpdatePeriod>");
   ReadBasicType(is, binary, &update_period_);
   ExpectToken(is, binary, "<NumSamplesHistory>");
   ReadBasicType(is, binary, &num_samples_history_);
   ExpectToken(is, binary, "<Alpha>");
   ReadBasicType(is, binary, &alpha_);
   ExpectToken(is, binary, "<MaxChangePerSample>");
   ReadBasicType(is, binary, &max_change_per_sample_);
   ExpectToken(is, binary, "<IsGradient>");
   ReadBasicType(is, binary, &is_gradient_);
   std::string token;
   ReadToken(is, binary, &token);
   if (token == "<UpdateCount>") {
     ReadBasicType(is, binary, &update_count_);
     ExpectToken(is, binary, "<ActiveScalingCount>");
     ReadBasicType(is, binary, &active_scaling_count_);
     ExpectToken(is, binary, "<MaxChangeScaleStats>");
     ReadBasicType(is, binary, &max_change_scale_stats_);
     ReadToken(is, binary, &token);
   }
   if (token != "<NaturalGradientAffineComponent>" &&
       token != "</NaturalGradientAffineComponent>")
     KALDI_ERR << "Expected <NaturalGradientAffineComponent> or "
               << "</NaturalGradientAffineComponent>, got " << token;
   SetNaturalGradientConfigs();
 }
void Resize (int32 input_dim, int32 output_dim) virtual
Reimplemented from AffineComponent.
Definition at line 1962 of file nnet-simple-component.cc.
References AffineComponent::bias_params_, KALDI_ASSERT, AffineComponent::linear_params_, NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, CuVector< Real >::Resize(), CuMatrix< Real >::Resize(), and NaturalGradientAffineComponent::SetNaturalGradientConfigs().
{
   KALDI_ASSERT(input_dim > 1 && output_dim > 1);
   if (rank_in_ >= input_dim) rank_in_ = input_dim - 1;
   if (rank_out_ >= output_dim) rank_out_ = output_dim - 1;
   bias_params_.Resize(output_dim);
   linear_params_.Resize(output_dim, input_dim);
   OnlineNaturalGradient temp;
   preconditioner_in_ = temp;
   preconditioner_out_ = temp;
   SetNaturalGradientConfigs();
 }
void Scale (BaseFloat scale) virtual
This virtual function when called by.
by "scale" when called by an UpdatableComponent.
Reimplemented from AffineComponent.
Definition at line 2257 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, AffineComponent::bias_params_, AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_scale_stats_, CuVectorBase< Real >::Scale(), CuMatrixBase< Real >::Scale(), and NaturalGradientAffineComponent::update_count_.
{
   update_count_ *= scale;
   max_change_scale_stats_ *= scale;
   active_scaling_count_ *= scale;
   linear_params_.Scale(scale);
   bias_params_.Scale(scale);
 }
void SetNaturalGradientConfigs () private
Definition at line 2057 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::alpha_, NaturalGradientAffineComponent::num_samples_history_, NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, OnlineNaturalGradient::SetAlpha(), OnlineNaturalGradient::SetNumSamplesHistory(), OnlineNaturalGradient::SetRank(), OnlineNaturalGradient::SetUpdatePeriod(), and NaturalGradientAffineComponent::update_period_.
Referenced by NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::NaturalGradientAffineComponent(), NaturalGradientAffineComponent::Read(), and NaturalGradientAffineComponent::Resize().
{
   preconditioner_in_.SetRank(rank_in_);
   preconditioner_in_.SetNumSamplesHistory(num_samples_history_);
   preconditioner_in_.SetAlpha(alpha_);
   preconditioner_in_.SetUpdatePeriod(update_period_);
   preconditioner_out_.SetRank(rank_out_);
   preconditioner_out_.SetNumSamplesHistory(num_samples_history_);
   preconditioner_out_.SetAlpha(alpha_);
   preconditioner_out_.SetUpdatePeriod(update_period_);
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Reimplemented from AffineComponent.
Definition at line 630 of file nnet-simple-component.h.
 { return "NaturalGradientAffineComponent"; }
void Update (const std::string & debug_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) private virtual
Reimplemented from AffineComponent.
Definition at line 2198 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMatMat(), CuVectorBase< Real >::AddMatVec(), AffineComponent::bias_params_, CuVectorBase< Real >::CopyColFromMat(), kaldi::kNoTrans, kaldi::kTrans, kaldi::kUndefined, UpdatableComponent::learning_rate_, AffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), OnlineNaturalGradient::PreconditionDirections(), NaturalGradientAffineComponent::preconditioner_in_, NaturalGradientAffineComponent::preconditioner_out_, CuMatrixBase< Real >::Range(), CuMatrix< Real >::Resize(), and NaturalGradientAffineComponent::update_count_.
{
   CuMatrix<BaseFloat> in_value_temp;
   in_value_temp.Resize(in_value.NumRows(),
                        in_value.NumCols() + 1, kUndefined);
   in_value_temp.Range(0, in_value.NumRows(),
                       0, in_value.NumCols()).CopyFromMat(in_value);
   // Add the 1.0 at the end of each row "in_value_temp"
   in_value_temp.Range(0, in_value.NumRows(),
                       in_value.NumCols(), 1).Set(1.0);
   CuMatrix<BaseFloat> out_deriv_temp(out_deriv);
   CuMatrix<BaseFloat> row_products(2,
                                    in_value.NumRows());
   CuSubVector<BaseFloat> in_row_products(row_products, 0),
       out_row_products(row_products, 1);
   // These "scale" values get will get multiplied into the learning rate (faster
   // than having the matrices scaled inside the preconditioning code).
   BaseFloat in_scale, out_scale;
   preconditioner_in_.PreconditionDirections(&in_value_temp, &in_row_products,
                                             &in_scale);
   preconditioner_out_.PreconditionDirections(&out_deriv_temp, &out_row_products,
                                              &out_scale);
   // "scale" is a scaling factor coming from the PreconditionDirections calls
   // (it's faster to have them output a scaling factor than to have them scale
   // their outputs).
   BaseFloat scale = in_scale * out_scale;
   CuSubMatrix<BaseFloat> in_value_precon_part(in_value_temp,
                                               0, in_value_temp.NumRows(),
                                               0, in_value_temp.NumCols() - 1);
   // this "precon_ones" is what happens to the vector of 1's representing
   // offsets, after multiplication by the preconditioner.
   CuVector<BaseFloat> precon_ones(in_value_temp.NumRows());
   precon_ones.CopyColFromMat(in_value_temp, in_value_temp.NumCols() - 1);
   BaseFloat local_lrate = scale * learning_rate_;
   update_count_ += 1.0;
   bias_params_.AddMatVec(local_lrate, out_deriv_temp, kTrans,
                          precon_ones, 1.0);
   linear_params_.AddMatMat(local_lrate, out_deriv_temp, kTrans,
                            in_value_precon_part, kNoTrans, 1.0);
 }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Reimplemented from AffineComponent.
Definition at line 2128 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, NaturalGradientAffineComponent::alpha_, AffineComponent::bias_params_, UpdatableComponent::is_gradient_, AffineComponent::linear_params_, NaturalGradientAffineComponent::max_change_per_sample_, NaturalGradientAffineComponent::max_change_scale_stats_, NaturalGradientAffineComponent::num_samples_history_, NaturalGradientAffineComponent::rank_in_, NaturalGradientAffineComponent::rank_out_, NaturalGradientAffineComponent::update_count_, NaturalGradientAffineComponent::update_period_, CuVector< Real >::Write(), CuMatrixBase< Real >::Write(), kaldi::WriteBasicType(), kaldi::WriteToken(), and UpdatableComponent::WriteUpdatableCommon().
{
   WriteUpdatableCommon(os, binary);  // Write the opening tag and learning rate
   WriteToken(os, binary, "<LinearParams>");
   linear_params_.Write(os, binary);
   WriteToken(os, binary, "<BiasParams>");
   bias_params_.Write(os, binary);
   WriteToken(os, binary, "<RankIn>");
   WriteBasicType(os, binary, rank_in_);
   WriteToken(os, binary, "<RankOut>");
   WriteBasicType(os, binary, rank_out_);
   WriteToken(os, binary, "<UpdatePeriod>");
   WriteBasicType(os, binary, update_period_);
   WriteToken(os, binary, "<NumSamplesHistory>");
   WriteBasicType(os, binary, num_samples_history_);
   WriteToken(os, binary, "<Alpha>");
   WriteBasicType(os, binary, alpha_);
   WriteToken(os, binary, "<MaxChangePerSample>");
   WriteBasicType(os, binary, max_change_per_sample_);
   WriteToken(os, binary, "<IsGradient>");
   WriteBasicType(os, binary, is_gradient_);
   WriteToken(os, binary, "<UpdateCount>");
   WriteBasicType(os, binary, update_count_);
   WriteToken(os, binary, "<ActiveScalingCount>");
   WriteBasicType(os, binary, active_scaling_count_);
   WriteToken(os, binary, "<MaxChangeScaleStats>");
   WriteBasicType(os, binary, max_change_scale_stats_);
   WriteToken(os, binary, "</NaturalGradientAffineComponent>");
 }
void ZeroStats () virtual
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
Other components that store other types of statistics (e.g. regarding gradient clipping) are free to implement ZeroStats() also.
Reimplemented from Component.
Definition at line 2251 of file nnet-simple-component.cc.
References NaturalGradientAffineComponent::active_scaling_count_, NaturalGradientAffineComponent::max_change_scale_stats_, and NaturalGradientAffineComponent::update_count_.
{
   update_count_ = 0.0;
   max_change_scale_stats_ = 0.0;
   active_scaling_count_ = 0.0;
 }
Member Data Documentation
double active_scaling_count_ private
Definition at line 688 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Add(), NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::Scale(), NaturalGradientAffineComponent::Write(), and NaturalGradientAffineComponent::ZeroStats().
BaseFloat alpha_ private
Definition at line 666 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Write().
BaseFloat max_change_per_sample_ private
Definition at line 681 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), and NaturalGradientAffineComponent::Write().
double max_change_scale_stats_ private
Definition at line 693 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Add(), NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::Scale(), NaturalGradientAffineComponent::Write(), and NaturalGradientAffineComponent::ZeroStats().
BaseFloat num_samples_history_ private
Definition at line 665 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Write().
OnlineNaturalGradient preconditioner_in_ private
Definition at line 668 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Resize(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Update().
OnlineNaturalGradient preconditioner_out_ private
Definition at line 670 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Resize(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Update().
int32 rank_in_ private
Definition at line 662 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::Resize(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Write().
int32 rank_out_ private
Definition at line 663 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::Resize(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Write().
double update_count_ private
Definition at line 684 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Add(), NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::Scale(), NaturalGradientAffineComponent::Update(), NaturalGradientAffineComponent::Write(), and NaturalGradientAffineComponent::ZeroStats().
int32 update_period_ private
Definition at line 664 of file nnet-simple-component.h.
Referenced by NaturalGradientAffineComponent::Info(), NaturalGradientAffineComponent::Init(), NaturalGradientAffineComponent::Read(), NaturalGradientAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientAffineComponent::Write().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc