Kaldi: Mse Class Reference
Mse Class Reference
#include <nnet-loss.h>
Public Member Functions
Mse ()
~Mse ()
void Eval (const VectorBase< BaseFloat > &frame_weights, const CuMatrixBase< BaseFloat > &net_out, const CuMatrixBase< BaseFloat > &target, CuMatrix< BaseFloat > *diff)
Evaluate mean square error using target-matrix,.
void Eval (const VectorBase< BaseFloat > &frame_weights, const CuMatrixBase< BaseFloat > &net_out, const Posterior &target, CuMatrix< BaseFloat > *diff)
Evaluate mean square error using target-posteior,.
std::string Report ()
Generate string with error report.
BaseFloat AvgLoss ()
Get loss value (frame average),.
Public Member Functions inherited from LossItf
LossItf ()
virtual ~LossItf ()
Private Attributes
double frames_
double loss_
double frames_progress_
double loss_progress_
std::vector< float > loss_vec_
CuVector< BaseFloat > frame_weights_
CuMatrix< BaseFloat > tgt_mat_
CuMatrix< BaseFloat > diff_pow_2_
Detailed Description
Definition at line 112 of file nnet-loss.h.
Constructor & Destructor Documentation
Mse () inline
Definition at line 114 of file nnet-loss.h.
         : frames_(0.0), loss_(0.0),
           frames_progress_(0.0), loss_progress_(0.0) { }
~Mse () inline
Definition at line 116 of file nnet-loss.h.
 { }
Member Function Documentation
BaseFloat AvgLoss () inline virtual
Get loss value (frame average),.
Implements LossItf.
Definition at line 134 of file nnet-loss.h.
References Mse::frames_, and Mse::loss_.
                       {
     return loss_ / frames_;
   }
void Eval (const VectorBase< BaseFloat > & frame_weights, const CuMatrixBase< BaseFloat > & net_out, const CuMatrixBase< BaseFloat > & target, CuMatrix< BaseFloat > * diff) virtual
Evaluate mean square error using target-matrix,.
Implements LossItf.
Definition at line 183 of file nnet-loss.cc.
References CuMatrixBase< Real >::AddMat(), Mse::diff_pow_2_, VectorBase< Real >::Dim(), Mse::frame_weights_, Mse::frames_, Mse::frames_progress_, KALDI_ASSERT, KALDI_ISFINITE, KALDI_VLOG, Mse::loss_, Mse::loss_progress_, Mse::loss_vec_, CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsVec(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), VectorBase< Real >::Sum(), and CuMatrixBase< Real >::Sum().
Referenced by Mse::Eval().
{
   // check inputs,
   KALDI_ASSERT(net_out.NumCols() == target.NumCols());
   KALDI_ASSERT(net_out.NumRows() == target.NumRows());
   KALDI_ASSERT(net_out.NumRows() == frame_weights.Dim());
   KALDI_ASSERT(KALDI_ISFINITE(frame_weights.Sum()));
   KALDI_ASSERT(KALDI_ISFINITE(net_out.Sum()));
   KALDI_ASSERT(KALDI_ISFINITE(target.Sum()));
   int32 num_frames = frame_weights.Sum();
   KALDI_ASSERT(num_frames >= 0.0);
   // get frame_weights to GPU,
   frame_weights_ = frame_weights;
   //compute derivative w.r.t. neural nerwork outputs
   *diff = net_out; // y
   diff->AddMat(-1.0,target); // (y - t)
   diff->MulRowsVec(frame_weights_); // weighting,
   // Compute MeanSquareError loss of mini-batch
   diff_pow_2_ = *diff;
   diff_pow_2_.MulElements(diff_pow_2_); // (y - t)^2
   diff_pow_2_.MulRowsVec(frame_weights_); // w*(y - t)^2
   double mean_square_error = 0.5 * diff_pow_2_.Sum(); // sum the matrix,
   KALDI_ASSERT(KALDI_ISFINITE(mean_square_error));
   // accumulate
   loss_ += mean_square_error;
   frames_ += num_frames;
   // progressive loss reporting
   {
     static const int32 progress_step = 3600*100; // 1h
     frames_progress_ += num_frames;
     loss_progress_ += mean_square_error;
     if (frames_progress_ > progress_step) {
       KALDI_VLOG(1) << "ProgressLoss[last "
                     << static_cast<int>(frames_progress_/100/3600) << "h of "
                     << static_cast<int>(frames_/100/3600) << "h]: "
                     << loss_progress_/frames_progress_ << " (Mse)";
       // store
       loss_vec_.push_back(loss_progress_/frames_progress_);
       // reset
       frames_progress_ = 0;
       loss_progress_ = 0.0;
     }
   }
 }
void Eval (const VectorBase< BaseFloat > & frame_weights, const CuMatrixBase< BaseFloat > & net_out, const Posterior & target, CuMatrix< BaseFloat > * diff) virtual
Evaluate mean square error using target-posteior,.
Implements LossItf.
Definition at line 239 of file nnet-loss.cc.
References Mse::Eval(), KALDI_ASSERT, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), kaldi::nnet1::PosteriorToMatrix(), and Mse::tgt_mat_.
{
   int32 num_frames = net_out.NumRows(),
     num_nn_outputs = net_out.NumCols();
   KALDI_ASSERT(num_frames == post.size());
   // convert posterior to matrix,
   PosteriorToMatrix(post, num_nn_outputs, &tgt_mat_);
   // call the other eval function,
   Eval(frame_weights, net_out, tgt_mat_, diff);
 }
std::string Report () virtual
Generate string with error report.
Implements LossItf.
Definition at line 255 of file nnet-loss.cc.
References Mse::diff_pow_2_, Mse::frames_, Mse::loss_, Mse::loss_vec_, and CuMatrixBase< Real >::NumCols().
                       {
   // compute root mean square,
   int32 num_tgt = diff_pow_2_.NumCols();
   BaseFloat root_mean_square = sqrt(loss_/frames_/num_tgt);
   // build the message,
   std::ostringstream oss;
   oss << "AvgLoss: " << loss_/frames_ << " (Mse), "
       << "[RMS " << root_mean_square << ", frames " << frames_ << "]" << std::endl;
   oss << "progress: [";
   std::copy(loss_vec_.begin(),loss_vec_.end(),std::ostream_iterator<float>(oss," "));
   oss << "]" << std::endl;
   return oss.str();
 }
Member Data Documentation
CuMatrix<BaseFloat> diff_pow_2_ private
Definition at line 148 of file nnet-loss.h.
Referenced by Mse::Eval(), and Mse::Report().
CuVector<BaseFloat> frame_weights_ private
Definition at line 146 of file nnet-loss.h.
Referenced by Mse::Eval().
double frames_ private
Definition at line 139 of file nnet-loss.h.
Referenced by Mse::AvgLoss(), Mse::Eval(), and Mse::Report().
double frames_progress_ private
Definition at line 142 of file nnet-loss.h.
Referenced by Mse::Eval().
double loss_ private
Definition at line 140 of file nnet-loss.h.
Referenced by Mse::AvgLoss(), Mse::Eval(), and Mse::Report().
double loss_progress_ private
Definition at line 143 of file nnet-loss.h.
Referenced by Mse::Eval().
std::vector<float> loss_vec_ private
Definition at line 144 of file nnet-loss.h.
Referenced by Mse::Eval(), and Mse::Report().
CuMatrix<BaseFloat> tgt_mat_ private
Definition at line 147 of file nnet-loss.h.
Referenced by Mse::Eval().
The documentation for this class was generated from the following files:
nnet/nnet-loss.h
nnet/nnet-loss.cc