Kaldi: KaldiVlogMessage Class Reference
KaldiVlogMessage Class Reference
"Functions relating to logging and error reporting"
#include <kaldi-error.h>
Public Member Functions
KaldiVlogMessage (const char *func, const char *file, int32 line, int32 verbose_level)
std::ostream & stream ()
~KaldiVlogMessage ()
Private Attributes
std::ostringstream ss_
Detailed Description
Definition at line 92 of file kaldi-error.h.
Constructor & Destructor Documentation
KaldiVlogMessage (const char * func, const char * file, int32 line, int32 verbose_level)
Definition at line 178 of file kaldi-error.cc.
References kaldi::GetProgramName(), kaldi::GetShortFileName(), and KaldiVlogMessage::stream().
{
   this->stream() << "VLOG[" << verbose << "] (" << GetProgramName() << func
                  << "():" << GetShortFileName(file) << ':' << line << ") ";
 }
~KaldiVlogMessage () inline
Definition at line 97 of file kaldi-error.h.
References KaldiVlogMessage::ss_.
 { fprintf(stderr, "%s\n", ss_.str().c_str()); }
Member Function Documentation
std::ostream& stream () inline
Definition at line 96 of file kaldi-error.h.
References KaldiVlogMessage::ss_.
Referenced by KaldiVlogMessage::KaldiVlogMessage().
 { return ss_; }
Member Data Documentation
std::ostringstream ss_ private
Definition at line 99 of file kaldi-error.h.
Referenced by KaldiVlogMessage::stream(), and KaldiVlogMessage::~KaldiVlogMessage().
The documentation for this class was generated from the following files:
base/kaldi-error.h
base/kaldi-error.cc