Kaldi: UpdatableComponent Class Reference
UpdatableComponent Class Reference abstract
Class UpdatableComponent is a Component which has trainable parameters; it extends the interface of Component.
#include <nnet-component-itf.h>
Public Member Functions
UpdatableComponent (const UpdatableComponent &other)
virtual void SetZero (bool treat_as_gradient)=0
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual BaseFloat DotProduct (const UpdatableComponent &other) const =0
Computes dot-product between parameters of two instances of a Component.
virtual void PerturbParams (BaseFloat stddev)=0
This function is to be used in testing.
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
Public Member Functions inherited from Component
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const =0
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const =0
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
virtual std::string Type () const =0
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual void InitFromConfig (ConfigLine *cfl)=0
Initialize, from a ConfigLine object.
virtual int32 InputDim () const =0
Returns input-dimension of this component.
virtual int32 OutputDim () const =0
Returns output-dimension of this component.
virtual int32 Properties () const =0
Return bitmask of the component's properties.
virtual Component * Copy () const =0
Copies component (deep copy).
virtual void Read (std::istream &is, bool binary)=0
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const =0
Write component to stream.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
Component ()
virtual ~Component ()
Protected Member Functions
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Private Member Functions
const UpdatableComponent & operator= (const UpdatableComponent &other)
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Detailed Description
Class UpdatableComponent is a Component which has trainable parameters; it extends the interface of Component.
This is a base-class for Components with parameters. See comment by declaration of kUpdatableComponent.
Definition at line 345 of file nnet-component-itf.h.
Constructor & Destructor Documentation
UpdatableComponent (const UpdatableComponent & other) inline
Definition at line 347 of file nnet-component-itf.h.
                                                      :
       learning_rate_(other.learning_rate_),
       learning_rate_factor_(other.learning_rate_factor_),
       is_gradient_(other.is_gradient_) { }
UpdatableComponent () inline
Definition at line 357 of file nnet-component-itf.h.
                       : learning_rate_(0.001), learning_rate_factor_(1.0),
                         is_gradient_(false) { }
virtual ~UpdatableComponent () inline virtual
Definition at line 360 of file nnet-component-itf.h.
 { }
Member Function Documentation
virtual BaseFloat DotProduct (const UpdatableComponent & other) const pure virtual
Computes dot-product between parameters of two instances of a Component.
Can be used for computing parameter-norm of an UpdatableComponent.
Implemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, PerElementOffsetComponent, PerElementScaleComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Referenced by kaldi::nnet3::ComponentDotProducts(), kaldi::nnet3::DotProduct(), CompositeComponent::DotProduct(), kaldi::nnet3::NnetParametersAreIdentical(), NnetComputer::ParameterStddev(), kaldi::nnet3::TestNnetComponentUpdatable(), kaldi::nnet3::TestNnetComponentVectorizeUnVectorize(), and kaldi::nnet3::TestSimpleComponentModelDerivative().
std::string Info () const virtual
Returns some text-form information about this component, for diagnostics.
Starts with the type of the component. E.g. "SigmoidComponent dim=900", although most components will have much more info.
Reimplemented from Component.
Reimplemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, NaturalGradientPerElementScaleComponent, PerElementOffsetComponent, PerElementScaleComponent, NaturalGradientAffineComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Definition at line 205 of file nnet-component-itf.cc.
References Component::InputDim(), UpdatableComponent::is_gradient_, UpdatableComponent::learning_rate_factor_, UpdatableComponent::LearningRate(), Component::OutputDim(), and Component::Type().
Referenced by AffineComponent::Info(), RepeatedAffineComponent::Info(), BlockAffineComponent::Info(), NaturalGradientAffineComponent::Info(), PerElementScaleComponent::Info(), PerElementOffsetComponent::Info(), ConvolutionComponent::Info(), Convolutional1dComponent::Info(), kaldi::nnet3::TestNnetComponentUpdatable(), and kaldi::nnet3::TestNnetComponentVectorizeUnVectorize().
{
   std::stringstream stream;
   stream << Type() << ", input-dim=" << InputDim()
          << ", output-dim=" << OutputDim() << ", learning-rate="
          << LearningRate();
   if (is_gradient_)
     stream << ", is-gradient=true";
   if (learning_rate_factor_ != 1.0)
     stream << ", learning-rate-factor=" << learning_rate_factor_;
   return stream.str();
 }
void InitLearningRatesFromConfig (ConfigLine * cfl) protected
Definition at line 148 of file nnet-component-itf.cc.
References ConfigLine::GetValue(), KALDI_ERR, UpdatableComponent::learning_rate_, UpdatableComponent::learning_rate_factor_, and ConfigLine::WholeLine().
Referenced by AffineComponent::InitFromConfig(), RepeatedAffineComponent::InitFromConfig(), BlockAffineComponent::InitFromConfig(), NaturalGradientAffineComponent::InitFromConfig(), PerElementScaleComponent::InitFromConfig(), PerElementOffsetComponent::InitFromConfig(), NaturalGradientPerElementScaleComponent::InitFromConfig(), ConvolutionComponent::InitFromConfig(), and Convolutional1dComponent::InitFromConfig().
{
   cfl->GetValue("learning-rate", &learning_rate_);
   cfl->GetValue("learning-rate-factor", &learning_rate_factor_);
   if (learning_rate_ < 0.0 || learning_rate_factor_ < 0.0)
     KALDI_ERR << "Bad initializer " << cfl->WholeLine();
 }
BaseFloat LearningRate () const inline
Gets the learning rate of gradient descent.
Note: if you call SetLearningRate(x), and learning_rate_factor_ != 1.0, a different value than x will returned.
Definition at line 378 of file nnet-component-itf.h.
References UpdatableComponent::learning_rate_.
Referenced by UpdatableComponent::Info(), and CompositeComponent::SetLearningRate().
 { return learning_rate_; }
virtual int32 NumParameters () const inline virtual
The following new virtual function returns the total dimension of the parameters in this class.
Reimplemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, PerElementOffsetComponent, PerElementScaleComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Definition at line 384 of file nnet-component-itf.h.
References KALDI_ASSERT.
Referenced by NnetCombiner::ComputeUpdatableComponentDims(), kaldi::nnet3::NumParameters(), CompositeComponent::NumParameters(), NnetComputer::ParameterStddev(), kaldi::nnet3::TestNnetComponentUpdatable(), kaldi::nnet3::TestNnetComponentVectorizeUnVectorize(), CompositeComponent::UnVectorize(), kaldi::nnet3::UnVectorizeNnet(), CompositeComponent::Vectorize(), and kaldi::nnet3::VectorizeNnet().
 { KALDI_ASSERT(0); return 0; }
const UpdatableComponent& operator= (const UpdatableComponent & other) private
virtual void PerturbParams (BaseFloat stddev) pure virtual
This function is to be used in testing.
It adds unit noise times "stddev" to the parameters of the component.
Implemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, PerElementOffsetComponent, PerElementScaleComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Referenced by kaldi::nnet3::PerturbParams(), CompositeComponent::PerturbParams(), and kaldi::nnet3::TestSimpleComponentModelDerivative().
void ReadUpdatableCommon (std::istream & is, bool binary) protected
Definition at line 156 of file nnet-component-itf.cc.
References UpdatableComponent::is_gradient_, KALDI_ERR, UpdatableComponent::learning_rate_, UpdatableComponent::learning_rate_factor_, kaldi::ReadBasicType(), kaldi::ReadToken(), and Component::Type().
Referenced by AffineComponent::Read(), RepeatedAffineComponent::Read(), BlockAffineComponent::Read(), NaturalGradientAffineComponent::Read(), PerElementScaleComponent::Read(), PerElementOffsetComponent::Read(), NaturalGradientPerElementScaleComponent::Read(), ConvolutionComponent::Read(), Convolutional1dComponent::Read(), and CompositeComponent::Read().
{
   std::ostringstream opening_tag;
   opening_tag << '<' << this->Type() << '>';
   std::string token;
   ReadToken(is, binary, &token);
   if (token == opening_tag.str()) {
     // if the first token is the opening tag, then
     // ignore it and get the next tag.
     ReadToken(is, binary, &token);
   }
   if (token == "<LearningRateFactor>") {
     ReadBasicType(is, binary, &learning_rate_factor_);
     ReadToken(is, binary, &token);
   } else {
     learning_rate_factor_ = 1.0;
   }
   if (token == "<IsGradient>") {
     ReadBasicType(is, binary, &is_gradient_);
     ReadToken(is, binary, &token);
   } else {
     is_gradient_ = false;
   }
   if (token == "<LearningRate>") {
     ReadBasicType(is, binary, &learning_rate_);
   } else {
     KALDI_ERR << "Expected token <LearningRate>, got "
               << token;
   }
 }
virtual void SetLearningRate (BaseFloat lrate) inline virtual
Sets the learning rate of gradient descent.
Reimplemented in CompositeComponent.
Definition at line 371 of file nnet-component-itf.h.
References UpdatableComponent::learning_rate_, and UpdatableComponent::learning_rate_factor_.
Referenced by AffineComponent::AffineComponent(), Convolutional1dComponent::Convolutional1dComponent(), ConvolutionComponent::ConvolutionComponent(), kaldi::nnet3::SetLearningRate(), and CompositeComponent::SetLearningRate().
{
     learning_rate_ = lrate * learning_rate_factor_;
   }
virtual void SetZero (bool treat_as_gradient) pure virtual
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
Implemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, PerElementOffsetComponent, PerElementScaleComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Referenced by kaldi::nnet3::SetZero(), CompositeComponent::SetZero(), kaldi::nnet3::TestNnetComponentUpdatable(), kaldi::nnet3::TestNnetComponentVectorizeUnVectorize(), and kaldi::nnet3::TestSimpleComponentModelDerivative().
virtual void UnVectorize (const VectorBase< BaseFloat > & params) inline virtual
Converts the parameters from vector form.
Reimplemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, PerElementOffsetComponent, PerElementScaleComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Definition at line 391 of file nnet-component-itf.h.
References KALDI_ASSERT.
Referenced by kaldi::nnet3::TestNnetComponentVectorizeUnVectorize(), CompositeComponent::UnVectorize(), and kaldi::nnet3::UnVectorizeNnet().
{
     KALDI_ASSERT(0);
   }
virtual void Vectorize (VectorBase< BaseFloat > * params) const inline virtual
Turns the parameters into vector form.
We put the vector form on the CPU, because in the kinds of situations where we do this, we'll tend to use too much memory for the GPU.
Reimplemented in CompositeComponent, Convolutional1dComponent, ConvolutionComponent, PerElementOffsetComponent, PerElementScaleComponent, BlockAffineComponent, RepeatedAffineComponent, and AffineComponent.
Definition at line 389 of file nnet-component-itf.h.
References KALDI_ASSERT.
Referenced by kaldi::nnet3::TestNnetComponentVectorizeUnVectorize(), CompositeComponent::Vectorize(), and kaldi::nnet3::VectorizeNnet().
 { KALDI_ASSERT(0); }
void WriteUpdatableCommon (std::ostream & is, bool binary) const protected
Definition at line 186 of file nnet-component-itf.cc.
References UpdatableComponent::is_gradient_, UpdatableComponent::learning_rate_, UpdatableComponent::learning_rate_factor_, Component::Type(), kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by AffineComponent::Write(), RepeatedAffineComponent::Write(), BlockAffineComponent::Write(), NaturalGradientAffineComponent::Write(), PerElementScaleComponent::Write(), PerElementOffsetComponent::Write(), NaturalGradientPerElementScaleComponent::Write(), ConvolutionComponent::Write(), Convolutional1dComponent::Write(), and CompositeComponent::Write().
{
   std::ostringstream opening_tag;
   opening_tag << '<' << this->Type() << '>';
   std::string token;
   WriteToken(os, binary, opening_tag.str());
   if (learning_rate_factor_ != 1.0) {
     WriteToken(os, binary, "<LearningRateFactor>");
     WriteBasicType(os, binary, learning_rate_factor_);
   }
   if (is_gradient_) {
     WriteToken(os, binary, "<IsGradient>");
     WriteBasicType(os, binary, is_gradient_);
   }
   WriteToken(os, binary, "<LearningRate>");
   WriteBasicType(os, binary, learning_rate_);
 }
Member Data Documentation
bool is_gradient_ protected
True if this component is to be treated as a gradient rather than as parameters.
Its main effect is that we disable any natural-gradient update and just compute the standard gradient.
Definition at line 414 of file nnet-component-itf.h.
Referenced by AffineComponent::Backprop(), PerElementScaleComponent::Backprop(), PerElementScaleComponent::Copy(), PerElementOffsetComponent::Copy(), UpdatableComponent::Info(), NaturalGradientAffineComponent::Init(), AffineComponent::Read(), RepeatedAffineComponent::Read(), BlockAffineComponent::Read(), NaturalGradientAffineComponent::Read(), PerElementScaleComponent::Read(), PerElementOffsetComponent::Read(), NaturalGradientPerElementScaleComponent::Read(), CompositeComponent::Read(), UpdatableComponent::ReadUpdatableCommon(), AffineComponent::SetZero(), RepeatedAffineComponent::SetZero(), BlockAffineComponent::SetZero(), PerElementScaleComponent::SetZero(), PerElementOffsetComponent::SetZero(), NaturalGradientRepeatedAffineComponent::Update(), AffineComponent::Write(), RepeatedAffineComponent::Write(), BlockAffineComponent::Write(), NaturalGradientAffineComponent::Write(), PerElementScaleComponent::Write(), PerElementOffsetComponent::Write(), NaturalGradientPerElementScaleComponent::Write(), and UpdatableComponent::WriteUpdatableCommon().
BaseFloat learning_rate_ protected
learning rate (typically 0.0..0.01)
Definition at line 409 of file nnet-component-itf.h.
Referenced by BlockAffineComponent::Backprop(), PerElementOffsetComponent::Backprop(), PerElementScaleComponent::Copy(), PerElementOffsetComponent::Copy(), Convolutional1dComponent::Copy(), UpdatableComponent::InitLearningRatesFromConfig(), UpdatableComponent::LearningRate(), CompositeComponent::Read(), UpdatableComponent::ReadUpdatableCommon(), UpdatableComponent::SetLearningRate(), AffineComponent::SetZero(), RepeatedAffineComponent::SetZero(), BlockAffineComponent::SetZero(), PerElementScaleComponent::SetZero(), PerElementOffsetComponent::SetZero(), ConvolutionComponent::SetZero(), Convolutional1dComponent::SetZero(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), NaturalGradientAffineComponent::Update(), NaturalGradientPerElementScaleComponent::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), AffineComponent::UpdateSimple(), PerElementScaleComponent::UpdateSimple(), and UpdatableComponent::WriteUpdatableCommon().
BaseFloat learning_rate_factor_ protected
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
Definition at line 410 of file nnet-component-itf.h.
Referenced by UpdatableComponent::Info(), UpdatableComponent::InitLearningRatesFromConfig(), CompositeComponent::Read(), UpdatableComponent::ReadUpdatableCommon(), UpdatableComponent::SetLearningRate(), and UpdatableComponent::WriteUpdatableCommon().
The documentation for this class was generated from the following files:
nnet3/nnet-component-itf.h
nnet3/nnet-component-itf.cc