Kaldi: OffsetForwardingDescriptor Class Reference
OffsetForwardingDescriptor Class Reference
#include <nnet-descriptor.h>
Public Member Functions
virtual Cindex MapToInput (const Index &ind) const
virtual int32 Dim (const Nnet &nnet) const
virtual ForwardingDescriptor * Copy () const
virtual void WriteConfig (std::ostream &os, const std::vector< std::string > &node_names) const
virtual int32 Modulus () const
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
virtual void GetNodeDependencies (std::vector< int32 > *node_indexes) const
This function appends to "node_indexes" all the node indexes.
OffsetForwardingDescriptor (ForwardingDescriptor *src, Index offset)
virtual ~OffsetForwardingDescriptor ()
Public Member Functions inherited from ForwardingDescriptor
virtual ~ForwardingDescriptor ()
ForwardingDescriptor ()
Private Attributes
ForwardingDescriptor * src_
Index offset_
Detailed Description
Definition at line 150 of file nnet-descriptor.h.
Constructor & Destructor Documentation
OffsetForwardingDescriptor (ForwardingDescriptor * src, Index offset) inline
Definition at line 165 of file nnet-descriptor.h.
Referenced by OffsetForwardingDescriptor::Copy().
                                           : src_(src), offset_(offset) { }
virtual ~OffsetForwardingDescriptor () inline virtual
Definition at line 168 of file nnet-descriptor.h.
References OffsetForwardingDescriptor::src_.
 { delete src_; }
Member Function Documentation
ForwardingDescriptor * Copy () const virtual
Implements ForwardingDescriptor.
Definition at line 116 of file nnet-descriptor.cc.
References ForwardingDescriptor::Copy(), OffsetForwardingDescriptor::offset_, OffsetForwardingDescriptor::OffsetForwardingDescriptor(), and OffsetForwardingDescriptor::src_.
{
   return new OffsetForwardingDescriptor(src_->Copy(), offset_);
 }
virtual int32 Dim (const Nnet & nnet) const inline virtual
Implements ForwardingDescriptor.
Definition at line 153 of file nnet-descriptor.h.
References ForwardingDescriptor::Dim(), and OffsetForwardingDescriptor::src_.
 { return src_->Dim(nnet); }
void GetNodeDependencies (std::vector< int32 > * node_indexes) const virtual
This function appends to "node_indexes" all the node indexes.
Implements ForwardingDescriptor.
Definition at line 104 of file nnet-descriptor.cc.
References ForwardingDescriptor::GetNodeDependencies(), and OffsetForwardingDescriptor::src_.
{
   src_->GetNodeDependencies(node_indexes);
 }
Cindex MapToInput (const Index & ind) const virtual
Implements ForwardingDescriptor.
Definition at line 109 of file nnet-descriptor.cc.
References ForwardingDescriptor::MapToInput(), OffsetForwardingDescriptor::offset_, and OffsetForwardingDescriptor::src_.
{
   Cindex answer = src_->MapToInput(ind);
   answer.second = answer.second + offset_;
   return answer;
 }
virtual int32 Modulus () const inline virtual
This function is for use in things like clockwork RNNs, where shifting the time of the inputs and outputs of the network by some multiple integer n would leave things the same, but shifting by non-multiples would change the network structure.
It returns the smallest modulus to which this descriptor is invariant; the lowest common multiple of all descriptors in the network gives you the modulus for the whole network.
Reimplemented from ForwardingDescriptor.
Definition at line 160 of file nnet-descriptor.h.
References ForwardingDescriptor::Modulus(), and OffsetForwardingDescriptor::src_.
 { return src_->Modulus(); }
void WriteConfig (std::ostream & os, const std::vector< std::string > & node_names) const virtual
Implements ForwardingDescriptor.
Definition at line 120 of file nnet-descriptor.cc.
References KALDI_ASSERT, Index::n, OffsetForwardingDescriptor::offset_, OffsetForwardingDescriptor::src_, Index::t, ForwardingDescriptor::WriteConfig(), and Index::x.
{
   KALDI_ASSERT(offset_.n == 0);
   os << "Offset(";
   src_->WriteConfig(os, node_names);
   os << ", " << offset_.t;
   if (offset_.x != 0)
     os << ", " << offset_.x;
   os << ")";
 }
Member Data Documentation
Index offset_ private
Definition at line 171 of file nnet-descriptor.h.
Referenced by OffsetForwardingDescriptor::Copy(), OffsetForwardingDescriptor::MapToInput(), and OffsetForwardingDescriptor::WriteConfig().
ForwardingDescriptor* src_ private
Definition at line 170 of file nnet-descriptor.h.
Referenced by OffsetForwardingDescriptor::Copy(), OffsetForwardingDescriptor::Dim(), OffsetForwardingDescriptor::GetNodeDependencies(), OffsetForwardingDescriptor::MapToInput(), OffsetForwardingDescriptor::Modulus(), OffsetForwardingDescriptor::WriteConfig(), and OffsetForwardingDescriptor::~OffsetForwardingDescriptor().
The documentation for this class was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc