Kaldi: KaldiRnnlmWrapper Class Reference
KaldiRnnlmWrapper Class Reference
#include <kaldi-rnnlm.h>
Public Member Functions
KaldiRnnlmWrapper (const KaldiRnnlmWrapperOpts &opts, const std::string &unk_prob_rspecifier, const std::string &word_symbol_table_rxfilename, const std::string &rnnlm_rxfilename)
int32 GetHiddenLayerSize () const
int32 GetEos () const
BaseFloat GetLogProb (int32 word, const std::vector< int32 > &wseq, const std::vector< BaseFloat > &context_in, std::vector< BaseFloat > *context_out)
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (KaldiRnnlmWrapper)
Private Attributes
rnnlm::CRnnLM rnnlm_
std::vector< std::string > label_to_word_
int32 eos_
Detailed Description
Definition at line 47 of file kaldi-rnnlm.h.
Constructor & Destructor Documentation
KaldiRnnlmWrapper (const KaldiRnnlmWrapperOpts & opts, const std::string & unk_prob_rspecifier, const std::string & word_symbol_table_rxfilename, const std::string & rnnlm_rxfilename)
Definition at line 28 of file kaldi-rnnlm.cc.
References KaldiRnnlmWrapper::eos_, KaldiRnnlmWrapperOpts::eos_symbol, rnnlm::i, KALDI_ERR, KaldiRnnlmWrapper::label_to_word_, CRnnLM::restoreNet(), KaldiRnnlmWrapper::rnnlm_, CRnnLM::setRandSeed(), CRnnLM::setRnnLMFile(), CRnnLM::setUnkPenalty(), CRnnLM::setUnkSym(), and KaldiRnnlmWrapperOpts::unk_symbol.
{
   rnnlm_.setRnnLMFile(rnnlm_rxfilename);
   rnnlm_.setRandSeed(1);
   rnnlm_.setUnkSym(opts.unk_symbol);
   rnnlm_.setUnkPenalty(unk_prob_rspecifier);
   rnnlm_.restoreNet();
   // Reads symbol table.
   fst::SymbolTable *word_symbols = NULL;
   if (!(word_symbols =
         fst::SymbolTable::ReadText(word_symbol_table_rxfilename))) {
     KALDI_ERR << "Could not read symbol table from file "
         << word_symbol_table_rxfilename;
   }
   label_to_word_.resize(word_symbols->NumSymbols() + 1);
   for (int32 i = 0; i < label_to_word_.size() - 1; ++i) {
     label_to_word_[i] = word_symbols->Find(i);
     if (label_to_word_[i] == "") {
       KALDI_ERR << "Could not find word for integer " << i << "in the word "
           << "symbol table, mismatched symbol table or you have discoutinuous "
           << "integers in your symbol table?";
     }
   }
   label_to_word_[label_to_word_.size() - 1] = opts.eos_symbol;
   eos_ = label_to_word_.size() - 1;
 }
Member Function Documentation
int32 GetEos () const inline
Definition at line 56 of file kaldi-rnnlm.h.
References KaldiRnnlmWrapper::eos_.
Referenced by RnnlmDeterministicFst::Final().
 { return eos_; }
int32 GetHiddenLayerSize () const inline
Definition at line 54 of file kaldi-rnnlm.h.
References CRnnLM::getHiddenLayerSize(), and KaldiRnnlmWrapper::rnnlm_.
Referenced by RnnlmDeterministicFst::GetArc(), and RnnlmDeterministicFst::RnnlmDeterministicFst().
 { return rnnlm_.getHiddenLayerSize(); }
BaseFloat GetLogProb (int32 word, const std::vector< int32 > & wseq, const std::vector< BaseFloat > & context_in, std::vector< BaseFloat > * context_out)
Definition at line 59 of file kaldi-rnnlm.cc.
References CRnnLM::computeConditionalLogprob(), rnnlm::i, KALDI_ASSERT, KaldiRnnlmWrapper::label_to_word_, and KaldiRnnlmWrapper::rnnlm_.
Referenced by RnnlmDeterministicFst::Final(), and RnnlmDeterministicFst::GetArc().
{
   std::vector<std::string> wseq_symbols(wseq.size());
   for (int32 i = 0; i < wseq_symbols.size(); ++i) {
     KALDI_ASSERT(wseq[i] < label_to_word_.size());
     wseq_symbols[i] = label_to_word_[wseq[i]];
   }
   return rnnlm_.computeConditionalLogprob(label_to_word_[word], wseq_symbols,
                                           context_in, context_out);
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (KaldiRnnlmWrapper) private
Member Data Documentation
int32 eos_ private
Definition at line 65 of file kaldi-rnnlm.h.
Referenced by KaldiRnnlmWrapper::GetEos(), and KaldiRnnlmWrapper::KaldiRnnlmWrapper().
std::vector<std::string> label_to_word_ private
Definition at line 64 of file kaldi-rnnlm.h.
Referenced by KaldiRnnlmWrapper::GetLogProb(), and KaldiRnnlmWrapper::KaldiRnnlmWrapper().
rnnlm::CRnnLM rnnlm_ private
Definition at line 63 of file kaldi-rnnlm.h.
Referenced by KaldiRnnlmWrapper::GetHiddenLayerSize(), KaldiRnnlmWrapper::GetLogProb(), and KaldiRnnlmWrapper::KaldiRnnlmWrapper().
The documentation for this class was generated from the following files:
lm/kaldi-rnnlm.h
lm/kaldi-rnnlm.cc