Kaldi: RandomAccessTableReaderScriptImpl< Holder > Class Template Reference
RandomAccessTableReaderScriptImpl< Holder > Class Template Reference
"Implementation classes for Table types"
#include <kaldi-table-inl.h>
Public Types
typedef Holder::T T
Public Types inherited from RandomAccessTableReaderImplBase< Holder >
typedef Holder::T T
Public Member Functions
RandomAccessTableReaderScriptImpl ()
virtual bool Open (const std::string &rspecifier)
virtual bool IsOpen () const
virtual bool Close ()
virtual bool HasKey (const std::string &key)
virtual const T & Value (const std::string &key)
virtual ~RandomAccessTableReaderScriptImpl ()
Public Member Functions inherited from RandomAccessTableReaderImplBase< Holder >
virtual ~RandomAccessTableReaderImplBase ()
Private Types
enum {
kUninitialized, kNotReadScript, kNotHaveObject, kHaveObject,
kGaveObject
}
Private Member Functions
virtual bool HasKeyInternal (const std::string &key, bool preload)
void MakeTombstone (const std::string &key)
bool LookupKey (const std::string &key, size_t *script_offset)
Private Attributes
Input input_
RspecifierOptions opts_
std::string rspecifier_
std::string script_rxfilename_
std::string current_key_
Holder holder_
std::vector< std::pair
< std::string, std::string > > script_
size_t last_found_
enum
kaldi::RandomAccessTableReaderScriptImpl:: { ... } state_
Detailed Description
template<class Holder>
class kaldi::RandomAccessTableReaderScriptImpl< Holder >
Definition at line 1263 of file kaldi-table-inl.h.
Member Typedef Documentation
typedef Holder::T T
Definition at line 1266 of file kaldi-table-inl.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
kUninitialized
kNotReadScript
kNotHaveObject
kHaveObject
kGaveObject
Definition at line 1490 of file kaldi-table-inl.h.
        {  //           [Do we have          [Does holder_
     //                script_ set up?]      contain object?]
     kUninitialized,  //     no                     no
     kNotReadScript,  //     no                     no
     kNotHaveObject,  //     yes                    no
     kHaveObject,   //     yes                    yes
     kGaveObject,   //     yes                    yes
     // [kGaveObject is as kHaveObject but we note that the
     //  user has already read it; this is for checking that
     // if "once" is specified, the user actually only reads
     // it once.
   } state_;
Constructor & Destructor Documentation
RandomAccessTableReaderScriptImpl () inline
Definition at line 1268 of file kaldi-table-inl.h.
 : last_found_(0), state_(kUninitialized) {}
virtual ~RandomAccessTableReaderScriptImpl () inline virtual
Definition at line 1372 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::holder_, RandomAccessTableReaderScriptImpl< Holder >::kGaveObject, RandomAccessTableReaderScriptImpl< Holder >::kHaveObject, and RandomAccessTableReaderScriptImpl< Holder >::state_.
{
     if (state_ == kHaveObject || state_ == kGaveObject)
       holder_.Clear();
   }
Member Function Documentation
virtual bool Close () inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 1321 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::current_key_, RandomAccessTableReaderScriptImpl< Holder >::holder_, RandomAccessTableReaderScriptImpl< Holder >::IsOpen(), KALDI_ERR, RandomAccessTableReaderScriptImpl< Holder >::kUninitialized, RandomAccessTableReaderScriptImpl< Holder >::last_found_, RandomAccessTableReaderScriptImpl< Holder >::script_, and RandomAccessTableReaderScriptImpl< Holder >::state_.
{
     if (!IsOpen())
       KALDI_ERR << "Close() called on RandomAccessTableReader that was not"
                    " open.";
     holder_.Clear();
     state_ = kUninitialized;
     last_found_ = 0;
     script_.clear();
     current_key_ = "";
     // This one cannot fail because any errors of a "global"
     // nature would have been detected when we did Open().
     // With archives it's different.
     return true;
   }
virtual bool HasKey (const std::string & key) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 1336 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::opts_, and RspecifierOptions::permissive.
{
     bool preload = opts_.permissive;
     // In permissive mode, we have to check that we can read
     // the scp entry before we assert that the key is there.
     return HasKeyInternal(key, preload);
   }
virtual bool HasKeyInternal (const std::string & key, bool preload) inline private virtual
Definition at line 1384 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::current_key_, RandomAccessTableReaderScriptImpl< Holder >::holder_, RandomAccessTableReaderScriptImpl< Holder >::input_, kaldi::IsToken(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, RandomAccessTableReaderScriptImpl< Holder >::kGaveObject, RandomAccessTableReaderScriptImpl< Holder >::kHaveObject, RandomAccessTableReaderScriptImpl< Holder >::kNotHaveObject, RandomAccessTableReaderScriptImpl< Holder >::kNotReadScript, RandomAccessTableReaderScriptImpl< Holder >::kUninitialized, RandomAccessTableReaderScriptImpl< Holder >::LookupKey(), RspecifierOptions::once, Input::Open(), RandomAccessTableReaderScriptImpl< Holder >::opts_, kaldi::PrintableRxfilename(), RandomAccessTableReaderScriptImpl< Holder >::rspecifier_, RandomAccessTableReaderScriptImpl< Holder >::script_, RandomAccessTableReaderScriptImpl< Holder >::state_, and Input::Stream().
Referenced by RandomAccessTableReaderScriptImpl< Holder >::HasKey(), and RandomAccessTableReaderScriptImpl< Holder >::Value().
{
     switch (state_) {
       case kUninitialized: case kNotReadScript:
         KALDI_ERR << "HasKey called on RandomAccessTableReader object that is"
                      " not open.";
       case kHaveObject: case kGaveObject:
         if (key == current_key_)
           return true;
         break;
       default: break;
     }
     KALDI_ASSERT(IsToken(key));
     size_t key_pos = 0;  // set to zero to suppress warning
     bool ans = LookupKey(key, &key_pos);
     if (!ans) {
       return false;
     } else {
       // First do a check regarding the "once" option.
       if (opts_.once && script_[key_pos].second == "") {  // A "tombstone";
         // user is asking about already-read key.
         KALDI_ERR << "HasKey called on key whose value was already read, and "
             " you specified the \"once\" option (o, ): try removing o, or "
             "adding no, : rspecifier is " << rspecifier_;
       }
       if (!preload) {
         return true;  // we have the key.
       } else {  // preload specified, so we have to pre-load the object before
               // returning true.
         if (!input_.Open(script_[key_pos].second)) {
           KALDI_WARN << "Error opening stream "
                      << PrintableRxfilename(script_[key_pos].second);
           return false;
         } else {
           // Make sure holder empty.
           if (state_ == kHaveObject || state_ == kGaveObject)
             holder_.Clear();
           if (holder_.Read(input_.Stream())) {
             state_ = kHaveObject;
             current_key_ = key;
             return true;
           } else {
             KALDI_WARN << "Error reading object from "
                 "stream " << PrintableRxfilename(script_[key_pos].second);
             state_ = kNotHaveObject;
             return false;
           }
         }
       }
     }
   }
virtual bool IsOpen () const inline virtual
Definition at line 1316 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::kGaveObject, RandomAccessTableReaderScriptImpl< Holder >::kHaveObject, RandomAccessTableReaderScriptImpl< Holder >::kNotHaveObject, and RandomAccessTableReaderScriptImpl< Holder >::state_.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Close(), and RandomAccessTableReaderScriptImpl< Holder >::Value().
{
     return  (state_ == kNotHaveObject || state_ == kHaveObject ||
              state_ == kGaveObject);
   }
bool LookupKey (const std::string & key, size_t * script_offset) inline private
Definition at line 1441 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::last_found_, and RandomAccessTableReaderScriptImpl< Holder >::script_.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), and RandomAccessTableReaderScriptImpl< Holder >::MakeTombstone().
{
     // First, an optimization: if we're going consecutively, this will
     // make the lookup very fast.  Since we may call HasKey and then
     // Value(), which both may look up the key, we test if either the
     // current or next position are correct.
     if (last_found_ < script_.size() && script_[last_found_].first == key) {
       *script_offset = last_found_;
       return true;
     }
     last_found_++;
     if (last_found_ < script_.size() && script_[last_found_].first == key) {
       *script_offset = last_found_;
       return true;
     }
     std::pair<std::string, std::string> pr(key, "");  // Important that ""
     // compares less than or equal to any string, so lower_bound points to the
     // element that has the same key.
     typedef typename std::vector<std::pair<std::string, std::string> >
                      ::const_iterator IterType;
     IterType iter = std::lower_bound(script_.begin(), script_.end(), pr);
     if (iter != script_.end() && iter->first == key) {
       last_found_ = *script_offset = iter - script_.begin();
       return true;
     } else {
       return false;
     }
   }
void MakeTombstone (const std::string & key) inline private
Definition at line 1434 of file kaldi-table-inl.h.
References KALDI_ERR, RandomAccessTableReaderScriptImpl< Holder >::LookupKey(), and RandomAccessTableReaderScriptImpl< Holder >::script_.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Value().
{
     size_t offset;
     if (!LookupKey(key, &offset))
       KALDI_ERR << "RandomAccessTableReader object in inconsistent state.";
     else
       script_[offset].second = "";
   }
virtual bool Open (const std::string & rspecifier) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 1270 of file kaldi-table-inl.h.
References kaldi::ClassifyRspecifier(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, KALDI_WARN, RandomAccessTableReaderScriptImpl< Holder >::kGaveObject, RandomAccessTableReaderScriptImpl< Holder >::kHaveObject, RandomAccessTableReaderScriptImpl< Holder >::kNotHaveObject, RandomAccessTableReaderScriptImpl< Holder >::kNotReadScript, kaldi::kScriptRspecifier, RandomAccessTableReaderScriptImpl< Holder >::kUninitialized, RandomAccessTableReaderScriptImpl< Holder >::opts_, kaldi::PrintableRxfilename(), kaldi::ReadScriptFile(), RandomAccessTableReaderScriptImpl< Holder >::rspecifier_, RandomAccessTableReaderScriptImpl< Holder >::script_, RandomAccessTableReaderScriptImpl< Holder >::script_rxfilename_, RspecifierOptions::sorted, and RandomAccessTableReaderScriptImpl< Holder >::state_.
{
     switch (state_) {
       case kNotHaveObject: case kHaveObject: case kGaveObject:
         KALDI_ERR << " Opening already open RandomAccessTableReader:"
                      " call Close first.";
       case kUninitialized: case kNotReadScript:
         break;
     }
     rspecifier_ = rspecifier;
     RspecifierType rs = ClassifyRspecifier(rspecifier,
                                            &script_rxfilename_,
                                            &opts_);
     KALDI_ASSERT(rs == kScriptRspecifier);  // or wrongly called.
     KALDI_ASSERT(script_.empty());  // no way it could be nonempty at this point
     if (!ReadScriptFile(script_rxfilename_,
                         true,  // print any warnings
                         &script_)) {  // error reading script file or invalid
                                       // format
       state_ = kNotReadScript;
       return false;  // no need to print further warnings.  user gets the error.
     }
     rspecifier_ = rspecifier;
     // If opts_.sorted, the user has asserted that the keys are already sorted.
     // Although we could easily sort them, we want to let the user know of this
     // mistake.  This same mistake could have serious effects if used with an
     // archive rather than a script.
     if (!opts_.sorted)
       std::sort(script_.begin(), script_.end());
     for (size_t i = 0; i+1 < script_.size(); i++) {
       if (script_[i].first.compare(script_[i+1].first) >= 0) {
         // script[i] not < script[i+1] in lexical order...
         bool same = (script_[i].first == script_[i+1].first);
         KALDI_WARN << "Script file " << PrintableRxfilename(script_rxfilename_)
                    << (same ? " contains duplicate key: " :
                        " is not sorted (remove s, option or add ns, option):"
                        " key is ") << script_[i].first;
         state_ = kNotReadScript;
         return false;
       }
     }
     state_ = kNotHaveObject;
     return true;
   }
virtual const T& Value (const std::string & key) inline virtual
Implements RandomAccessTableReaderImplBase< Holder >.
Definition at line 1346 of file kaldi-table-inl.h.
References RandomAccessTableReaderScriptImpl< Holder >::current_key_, RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::holder_, RandomAccessTableReaderScriptImpl< Holder >::IsOpen(), KALDI_ASSERT, KALDI_ERR, RandomAccessTableReaderScriptImpl< Holder >::kGaveObject, RandomAccessTableReaderScriptImpl< Holder >::kHaveObject, RandomAccessTableReaderScriptImpl< Holder >::MakeTombstone(), RspecifierOptions::once, RandomAccessTableReaderScriptImpl< Holder >::opts_, RandomAccessTableReaderScriptImpl< Holder >::rspecifier_, and RandomAccessTableReaderScriptImpl< Holder >::state_.
{
     if (!IsOpen())
       KALDI_ERR << "Value() called on non-open object.";
     if (!((state_ == kHaveObject || state_ == kGaveObject)
           && key == current_key_)) {  // Not already stored...
       bool has_key = HasKeyInternal(key, true);  // preload.
       if (!has_key)
         KALDI_ERR << "Could not get item for key " << key
                   << ", rspecifier is " << rspecifier_ << "[to ignore this, "
                   << "add the p, (permissive) option to the rspecifier.";
       KALDI_ASSERT(state_ == kHaveObject && key == current_key_);
     }
     if (state_ == kHaveObject) {
       state_ = kGaveObject;
       if (opts_.once) MakeTombstone(key);  // make sure that future lookups fail
       return holder_.Value();
     } else {  // state_ == kGaveObject
       if (opts_.once)
         KALDI_ERR << "Value called twice for the same key and ,o (once) option "
                   << "is used: rspecifier is " << rspecifier_;
       return holder_.Value();
     }
   }
Member Data Documentation
std::string current_key_ private
Definition at line 1477 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Close(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), and RandomAccessTableReaderScriptImpl< Holder >::Value().
Holder holder_ private
Definition at line 1478 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Close(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::Value(), and RandomAccessTableReaderScriptImpl< Holder >::~RandomAccessTableReaderScriptImpl().
Input input_ private
Definition at line 1470 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal().
size_t last_found_ private
Definition at line 1488 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Close(), and RandomAccessTableReaderScriptImpl< Holder >::LookupKey().
RspecifierOptions opts_ private
Definition at line 1472 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::HasKey(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::Open(), and RandomAccessTableReaderScriptImpl< Holder >::Value().
std::string rspecifier_ private
Definition at line 1473 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::Open(), and RandomAccessTableReaderScriptImpl< Holder >::Value().
std::vector<std::pair<std::string, std::string> > script_ private
Definition at line 1487 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Close(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::LookupKey(), RandomAccessTableReaderScriptImpl< Holder >::MakeTombstone(), and RandomAccessTableReaderScriptImpl< Holder >::Open().
std::string script_rxfilename_ private
Definition at line 1475 of file kaldi-table-inl.h.
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Open().
enum { ... } state_
Referenced by RandomAccessTableReaderScriptImpl< Holder >::Close(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), RandomAccessTableReaderScriptImpl< Holder >::IsOpen(), RandomAccessTableReaderScriptImpl< Holder >::Open(), RandomAccessTableReaderScriptImpl< Holder >::Value(), and RandomAccessTableReaderScriptImpl< Holder >::~RandomAccessTableReaderScriptImpl().
The documentation for this class was generated from the following file:
util/kaldi-table-inl.h