Kaldi: PowerComponent Class Reference
PowerComponent Class Reference
Take the absoute values of an input vector to a power.
#include <nnet-component.h>
Public Member Functions
void Init (int32 dim, BaseFloat power=2)
PowerComponent (int32 dim, BaseFloat power=2)
PowerComponent ()
virtual std::string Type () const
virtual void InitFromString (std::string args)
We implement InitFromString at this level.
virtual int32 InputDim () const
Get size of input vectors.
virtual int32 OutputDim () const
Get size of output vectors.
virtual void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Perform forward pass propagation Input->Output.
virtual void Backprop (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrix< BaseFloat > *in_deriv) const
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
virtual bool BackpropNeedsInput () const
virtual bool BackpropNeedsOutput () const
virtual Component * Copy () const
Copy component (deep copy).
virtual void Read (std::istream &is, bool binary)
We implement Read at this level as it just needs the Type().
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Public Member Functions inherited from NonlinearComponent
void Init (int32 dim)
NonlinearComponent (int32 dim)
NonlinearComponent ()
NonlinearComponent (const NonlinearComponent &other)
void Scale (BaseFloat scale)
void Add (BaseFloat alpha, const NonlinearComponent &other)
const CuVector< double > & ValueSum () const
const CuVector< double > & DerivSum () const
double Count () const
void SetDim (int32 dim)
Public Member Functions inherited from Component
Component ()
virtual int32 Index () const
Returns the index in the sequence of layers in the neural net; intended only to be used in debugging information.
virtual void SetIndex (int32 index)
virtual std::vector< int32 > Context () const
Return a vector describing the temporal context this component requires for each frame of output, as a sorted list.
void Propagate (const ChunkInfo &in_info, const ChunkInfo &out_info, const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out) const
A non-virtual propagate function that first resizes output if necessary.
virtual ~Component ()
Private Attributes
int32 dim_
BaseFloat power_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream.
static Component * NewFromString (const std::string &initializer_line)
Initialize the Component from one line that will contain first the type, e.g.
static Component * NewComponentOfType (const std::string &type)
Return a new Component of the given type e.g.
Protected Member Functions inherited from NonlinearComponent
void UpdateStats (const CuMatrixBase< BaseFloat > &out_value, const CuMatrixBase< BaseFloat > *deriv=NULL)
const NonlinearComponent & operator= (const NonlinearComponent &other)
Protected Attributes inherited from NonlinearComponent
int32 dim_
CuVector< double > value_sum_
CuVector< double > deriv_sum_
double count_
Mutex mutex_
Detailed Description
Take the absoute values of an input vector to a power.
The derivative for zero input will be treated as zero.
Definition at line 637 of file nnet-component.h.
Constructor & Destructor Documentation
PowerComponent (int32 dim, BaseFloat power = 2) inline explicit
Definition at line 640 of file nnet-component.h.
References PowerComponent::Init().
{
     Init(dim, power);
   }
PowerComponent () inline
Definition at line 643 of file nnet-component.h.
Referenced by PowerComponent::Copy().
 : dim_(0), power_(2) { }
Member Function Documentation
void Backprop (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_value, const CuMatrixBase< BaseFloat > & out_deriv, Component * to_update, CuMatrix< BaseFloat > * in_deriv) const virtual
Perform backward pass propagation of the derivative, and also either update the model (if to_update == this) or update another model or compute the model derivative (otherwise).
Note: in_value and out_value are the values of the input and output of the component, and these may be dummy variables if respectively BackpropNeedsInput() or BackpropNeedsOutput() return false for that component (not all components need these).
num_chunks lets us treat the input matrix as contiguous-in-time chunks of equal size; it only matters if splicing is involved.
Implements Component.
Definition at line 748 of file nnet-component.cc.
References CuMatrixBase< Real >::ApplyPowAbs(), CuMatrixBase< Real >::CopyFromMat(), CuMatrixBase< Real >::MulElements(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), PowerComponent::power_, CuMatrix< Real >::Resize(), and CuMatrixBase< Real >::Scale().
{
   in_deriv->Resize(in_value.NumRows(), in_value.NumCols());
   // in scalar terms: in_deriv += p * in_value^(p-1) * out_deriv
   in_deriv->CopyFromMat(in_value);
   in_deriv->ApplyPowAbs(power_ - 1.0, true);
   in_deriv->Scale(power_);
   in_deriv->MulElements(out_deriv);
 }
virtual bool BackpropNeedsInput () const inline virtual
Reimplemented from Component.
Definition at line 660 of file nnet-component.h.
 { return true; }
virtual bool BackpropNeedsOutput () const inline virtual
Reimplemented from Component.
Definition at line 661 of file nnet-component.h.
 { return true; }
virtual Component* Copy () const inline virtual
Copy component (deep copy).
Implements Component.
Definition at line 662 of file nnet-component.h.
References PowerComponent::dim_, PowerComponent::power_, and PowerComponent::PowerComponent().
 { return new PowerComponent(dim_, power_); }
std::string Info () const virtual
Reimplemented from Component.
Definition at line 784 of file nnet-component.cc.
References PowerComponent::dim_, PowerComponent::power_, and PowerComponent::Type().
{
   std::stringstream stream;
   stream << Type() << ", dim = " << dim_
      << ", power = " << power_;
   return stream.str();
 }
void Init (int32 dim, BaseFloat power = 2)
Definition at line 714 of file nnet-component.cc.
References PowerComponent::dim_, KALDI_ASSERT, and PowerComponent::power_.
Referenced by PowerComponent::InitFromString(), and PowerComponent::PowerComponent().
{
   dim_ = dim;
   power_ = power;
   KALDI_ASSERT(dim > 0 && power >= 0);
 }
void InitFromString (std::string args) virtual
We implement InitFromString at this level.
Reimplemented from NonlinearComponent.
Definition at line 720 of file nnet-component.cc.
References PowerComponent::Init(), KALDI_ERR, kaldi::nnet2::ParseFromString(), and PowerComponent::Type().
{
   std::string orig_args(args);
   int32 dim;
   BaseFloat power = 2.0;
   ParseFromString("power", &args, &power); // Optional.
   // Accept either "dim" or "input-dim" to specify the input dim.
   // "input-dim" is the canonical one; "dim" simplifies the testing code.
   bool ok = (ParseFromString("dim", &args, &dim) ||
              ParseFromString("input-dim", &args, &dim));
   if (!ok || !args.empty() || dim <= 0)
     KALDI_ERR << "Invalid initializer for layer of type "
               << Type() << ": \"" << orig_args << "\"";
   Init(dim, power);
 }
virtual int32 InputDim () const inline virtual
Get size of input vectors.
Reimplemented from NonlinearComponent.
Definition at line 646 of file nnet-component.h.
References PowerComponent::dim_.
 { return dim_; }
virtual int32 OutputDim () const inline virtual
Get size of output vectors.
Reimplemented from NonlinearComponent.
Definition at line 647 of file nnet-component.h.
References PowerComponent::dim_.
 { return dim_; }
void Propagate (const ChunkInfo & in_info, const ChunkInfo & out_info, const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) const virtual
Perform forward pass propagation Input->Output.
Each row is one frame or training example. Interpreted as "num_chunks" equally sized chunks of frames; this only matters for layers that do things like context splicing. Typically this variable will either be 1 (when we're processing a single contiguous chunk of data) or will be the same as in.NumFrames(), but other values are possible if some layers do splicing.
Implements Component.
Definition at line 735 of file nnet-component.cc.
References CuMatrixBase< Real >::ApplyPowAbs(), ChunkInfo::CheckSize(), CuMatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, ChunkInfo::NumChunks(), and PowerComponent::power_.
{
   in_info.CheckSize(in);
   out_info.CheckSize(*out);
   KALDI_ASSERT(in_info.NumChunks() == out_info.NumChunks());
   // Apply power operation to each element of the input...
   out->CopyFromMat(in);
   out->ApplyPowAbs(power_);
 }
void Read (std::istream & is, bool binary) virtual
We implement Read at this level as it just needs the Type().
Reimplemented from NonlinearComponent.
Definition at line 763 of file nnet-component.cc.
References PowerComponent::dim_, kaldi::nnet2::ExpectOneOrTwoTokens(), kaldi::ExpectToken(), PowerComponent::power_, and kaldi::ReadBasicType().
{
   ExpectOneOrTwoTokens(is, binary, "<PowerComponent>", "<InputDim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<OutputDim>");
   ReadBasicType(is, binary, &dim_);
   ExpectToken(is, binary, "<Power>");
   ReadBasicType(is, binary, &power_);
   ExpectToken(is, binary, "</PowerComponent>");
 }
virtual std::string Type () const inline virtual
Implements Component.
Definition at line 644 of file nnet-component.h.
Referenced by PowerComponent::Info(), and PowerComponent::InitFromString().
 { return "PowerComponent"; }
void Write (std::ostream & os, bool binary) const virtual
Write component to stream.
Reimplemented from NonlinearComponent.
Definition at line 773 of file nnet-component.cc.
References PowerComponent::dim_, PowerComponent::power_, kaldi::WriteBasicType(), and kaldi::WriteToken().
{
   WriteToken(os, binary, "<PowerComponent>");
   WriteToken(os, binary, "<InputDim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<OutputDim>");
   WriteBasicType(os, binary, dim_);
   WriteToken(os, binary, "<Power>");
   WriteBasicType(os, binary, power_);
   WriteToken(os, binary, "</PowerComponent>");
 }
Member Data Documentation
int32 dim_ private
Definition at line 672 of file nnet-component.h.
Referenced by PowerComponent::Copy(), PowerComponent::Info(), PowerComponent::Init(), PowerComponent::InputDim(), PowerComponent::OutputDim(), PowerComponent::Read(), and PowerComponent::Write().
BaseFloat power_ private
Definition at line 673 of file nnet-component.h.
Referenced by PowerComponent::Backprop(), PowerComponent::Copy(), PowerComponent::Info(), PowerComponent::Init(), PowerComponent::Propagate(), PowerComponent::Read(), and PowerComponent::Write().
The documentation for this class was generated from the following files:
nnet2/nnet-component.h
nnet2/nnet-component.cc