Kaldi: CuVectorBase< Real > Class Template Reference
CuVectorBase< Real > Class Template Reference
Vector for CUDA computing.
#include <matrix-common.h>
Public Member Functions
MatrixIndexT Dim () const
Dimensions.
Real * Data ()
Returns a pointer to the start of the vector's data.
const Real * Data () const
Returns a pointer to the start of the vector's data (const).
void CopyFromVec (const CuVectorBase< Real > &src)
Copy functions; these will crash if the dimension do not match.
template<typename OtherReal >
void CopyFromVec (const CuVectorBase< OtherReal > &M)
template<typename OtherReal >
void CopyFromVec (const VectorBase< OtherReal > &src)
template<typename OtherReal >
void CopyToVec (VectorBase< OtherReal > *dst) const
void CopyRowsFromMat (const CuMatrixBase< Real > &M)
void CopyRowsFromMat (const MatrixBase< Real > &M)
void SetZero ()
Math operations.
void Set (Real value)
void Add (Real value)
void Scale (Real value)
void AddVec (Real alpha, const CuVectorBase< Real > &vec, Real beta=1.0)
template<typename OtherReal >
void AddVec (Real alpha, const CuVectorBase< OtherReal > &vec, Real beta=1.0)
void AddRowSumMat (Real alpha, const CuMatrixBase< Real > &mat, Real beta=1.0)
Sum the rows of the matrix, add to vector.
void AddColSumMat (Real alpha, const CuMatrixBase< Real > &mat, Real beta=1.0)
Sum the columns of the matrix, add to vector.
void AddTpVec (const Real alpha, const CuTpMatrix< Real > &M, const MatrixTransposeType trans, const CuVectorBase< Real > &v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
void MulTp (const CuTpMatrix< Real > &M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
bool ApproxEqual (const CuVectorBase< Real > &other, float tol=0.01) const
void InvertElements ()
void ApplySoftMax ()
void ApplyExp ()
void ApplyLog ()
MatrixIndexT ApplyFloor (Real floor_val)
MatrixIndexT ApplyCeiling (Real ceiling_val)
void ApplyPow (Real power)
Real Sum () const
void SetRandn ()
CuSubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l)
const CuSubVector< Real > Range (const MatrixIndexT o, const MatrixIndexT l) const
void CopyColFromMat (const CuMatrixBase< Real > &mat, MatrixIndexT col)
template<typename OtherReal >
void CopyColFromMat (const CuMatrixBase< OtherReal > &mat, MatrixIndexT col)
void AddMatVec (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType trans, const CuVectorBase< Real > &v, const Real beta)
void AddVecVec (Real alpha, const CuVectorBase< Real > &v, const CuVectorBase< Real > &r, Real beta)
void AddSpVec (const Real alpha, const CuSpMatrix< Real > &S, const CuVectorBase< Real > &v, const Real beta)
void AddDiagMat2 (Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType trans, Real beta)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
void AddDiagMatMat (Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transM, const CuMatrixBase< Real > &N, MatrixTransposeType transN, Real beta=1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
CuValue< Real > operator() (MatrixIndexT i)
Real Norm (Real p)
Real operator() (MatrixIndexT i) const
void CopyDiagFromPacked (const CuPackedMatrix< Real > &M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
void CopyDiagFromMat (const CuMatrix< Real > &M)
Extracts the diagonal of a matrix.
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
void ReplaceValue (Real orig, Real changed)
void MulElements (const CuVectorBase< Real > &v)
template<>
void CopyColFromMat (const CuMatrixBase< float > &mat, MatrixIndexT col)
template<>
void CopyColFromMat (const CuMatrixBase< double > &mat, MatrixIndexT col)
template<>
void CopyFromVec (const CuVectorBase< float > &src)
template<>
void CopyFromVec (const CuVectorBase< double > &src)
template<>
void CopyFromVec (const CuVectorBase< float > &src)
template<>
void CopyFromVec (const CuVectorBase< double > &src)
Protected Member Functions
const VectorBase< Real > & Vec () const
VectorBase< Real > & Vec ()
CuVectorBase ()
Default constructor: make it protected so the user cannot instantiate this class.
Protected Attributes
Real * data_
GPU data pointer (or regular data pointer if CUDA is not compiled in or we have no GPU).
MatrixIndexT dim_
dimension of the vector
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (CuVectorBase)
Friends
class CuVectorBase< float >
class CuVectorBase< double >
class CuMatrixBase< Real >
class MatrixBase< Real >
class CuPackedMatrix< Real >
class CuSpMatrix< Real >
class CuTpMatrix< Real >
class CuRand< Real >
template<typename OtherReal >
OtherReal VecVec (const CuVectorBase< OtherReal > &v1, const CuVectorBase< OtherReal > &v2)
void cu::Splice (const CuMatrixBase< Real > &src, const CuArray< int32 > &frame_offsets, CuMatrixBase< Real > *tgt)
Detailed Description
template<typename Real>
class kaldi::CuVectorBase< Real >
Vector for CUDA computing.
Definition at line 64 of file matrix-common.h.
Constructor & Destructor Documentation
CuVectorBase () inline protected
Default constructor: make it protected so the user cannot instantiate this class.
Definition at line 210 of file cu-vector.h.
 : data_(NULL), dim_(0) { }
Member Function Documentation
void Add (Real value)
Definition at line 995 of file cu-vector.cc.
References CU1DBLOCK, rnnlm::d, and Timer::Elapsed().
Referenced by BlockSoftmax::BackpropagateFnc(), RepeatedAffineComponent::Init(), BlockAffineComponent::Init(), NaturalGradientAffineComponent::Init(), PerElementScaleComponent::Init(), and PerElementOffsetComponent::Init().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU1DBLOCK);
     dim3 dimGrid(n_blocks(Dim(), CU1DBLOCK));
     ::MatrixDim d = { 1, Dim(), Dim() };
     cuda_add(dimGrid, dimBlock, data_, value, d);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().Add(value);
   }
 }
void AddColSumMat (Real alpha, const CuMatrixBase< Real > & mat, Real beta = 1.0)
Sum the columns of the matrix, add to vector.
Definition at line 1128 of file cu-vector.cc.
References KALDI_ASSERT, kaldi::kNoTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuVectorBase< Real >::Set().
Referenced by LogSoftmaxComponent::Backprop(), BlockSoftmax::BackpropagateFnc(), kaldi::CuVectorUnitTestAddColSumMat(), Xent::Eval(), KlHmm::PropagateFnc(), LengthNormComponent::PropagateFnc(), kaldi::TestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::nnet1::UnitTestLengthNorm(), AffineTransform::Update(), and ConvolutionalComponent::Update().
{
   KALDI_ASSERT(mat.NumRows() == Dim());
   CuVector<Real> ones(mat.NumCols());
   ones.Set(1.0);
   this->AddMatVec(alpha, mat, kNoTrans, ones, beta);
 }
void AddDiagMat2 (Real alpha, const CuMatrixBase< Real > & M, MatrixTransposeType trans, Real beta)
Add the diagonal of a matrix times itself: *this = diag(M M^T) + beta * *this (if trans == kNoTrans), or *this = diag(M^T M) + beta * *this (if trans == kTrans).
Definition at line 522 of file cu-vector.cc.
References kaldi::kNoTrans, kaldi::kTrans, and CuMatrixBase< Real >::Mat().
Referenced by NormalizeComponent::Backprop(), ClipGradientComponent::Backprop(), kaldi::CuVectorUnitTestAddDiagMat2(), AffineComponentPreconditioned::GetScalingFactor(), OnlineNaturalGradient::PreconditionDirections(), OnlinePreconditioner::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), NormalizeComponent::Propagate(), and kaldi::TestCuVectorAddDiagMat2().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     MatrixTransposeType other_trans = (trans == kTrans ? kNoTrans : kTrans);
     this->AddDiagMatMat(alpha, M, trans,
                         M, other_trans, beta);
   } else
 #endif
   {
     Vec().AddDiagMat2(alpha, M.Mat(), trans, beta);
   }
 }
void AddDiagMatMat (Real alpha, const CuMatrixBase< Real > & M, MatrixTransposeType transM, const CuMatrixBase< Real > & N, MatrixTransposeType transN, Real beta = 1.0)
Add the diagonal of a matrix product: *this = diag(M N), assuming the "trans" arguments are both kNoTrans; for transpose arguments, it behaves as you would expect.
Definition at line 538 of file cu-vector.cc.
References CU1DBLOCK, CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Stride(), and kaldi::swap().
Referenced by NormalizeComponent::Backprop(), SoftmaxComponent::Backprop(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), kaldi::CuVectorUnitTestAddDiagMatMat(), kaldi::nnet2::PreconditionDirections(), kaldi::TestCuVectorAddDiagMatMat(), kaldi::TraceMatMat(), kaldi::nnet2::UnitTestPreconditionDirectionsOnline(), kaldi::nnet3::UnitTestPreconditionDirectionsOnline(), and PerElementScaleComponent::UpdateSimple().
                {
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     MatrixIndexT dim = this->dim_,
         M_col_dim = (transM == kTrans ? M.NumRows() : M.NumCols()),
         N_row_dim = (transN == kTrans ? N.NumCols() : N.NumRows());
     KALDI_ASSERT(M_col_dim == N_row_dim); // this is the dimension we sum over
     MatrixIndexT M_row_stride = M.Stride(), M_col_stride = 1;
     if (transM == kTrans) std::swap(M_row_stride, M_col_stride);
     MatrixIndexT N_row_stride = N.Stride(), N_col_stride = 1;
     if (transN == kTrans) std::swap(N_row_stride, N_col_stride);
     if (dim_ == 0) return;
     // This kernel can take a variable grid dimension, it makes use
     // of the extra threads by partitioning each vector-vector dot
     // product into multiple pieces.
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim,CU1DBLOCK));
     int threads_per_element = 1;
     // dimGridLimit may be any power of two between 1 and 256 inclusive; it was
     // determined empirically based on speed tests.
     int dimGridLimit = (transM == kNoTrans && transN == kTrans ? 2048 :
                         (transM == kTrans && transN == kNoTrans ? 16 : 32));
     while (M_col_dim > 10 * threads_per_element &&
            dimGrid < dimGridLimit && threads_per_element < 256) {
       threads_per_element *= 2;
       dimGrid = n_blocks(dim * threads_per_element, CU1DBLOCK);
     }
     cuda_add_diag_mat_mat(dimGrid, dimBlock, alpha, data_, dim,
                           M.Data(), M_col_dim, M_row_stride, M_col_stride,
                           N.Data(), N_row_stride, N_col_stride,
                           threads_per_element, beta);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().AddDiagMatMat(alpha, M.Mat(), transM, N.Mat(), transN, beta);
   }
 }
void AddMatVec (const Real alpha, const CuMatrixBase< Real > & M, MatrixTransposeType trans, const CuVectorBase< Real > & v, const Real beta)
Definition at line 433 of file cu-vector.cc.
References CuVectorBase< Real >::Data(), CuMatrixBase< Real >::Data(), CuVectorBase< Real >::dim_, Timer::Elapsed(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Stride(), and CuVectorBase< Real >::Vec().
Referenced by AffineComponent::CollapseWithNext(), AffineComponent::CollapseWithPrevious(), kaldi::CuVectorUnitTestAddMatVec(), kaldi::nnet2::UnitTestGenericComponentInternal(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), and AffineComponentPreconditionedOnline::Update().
{
   KALDI_ASSERT((trans == kNoTrans && M.NumCols() == v.dim_ && M.NumRows() == dim_) ||
                (trans == kTrans && M.NumRows() == v.dim_ && M.NumCols() == dim_));
   KALDI_ASSERT(&v != this);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     // Everything is backwards in CuBlas.  We need to reverse rows, columns,
     // transpose-ness.
     CU_SAFE_CALL(cublas_gemv(GetCublasHandle(),
                             (trans==kTrans? CUBLAS_OP_N:CUBLAS_OP_T),
                             M.NumCols(), M.NumRows(), alpha, M.Data(),
                             M.Stride(), v.Data(), 1, beta, data_, 1));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().AddMatVec(alpha,M.Mat(),trans,v.Vec(),beta);
   }
 }
void AddRowSumMat (Real alpha, const CuMatrixBase< Real > & mat, Real beta = 1.0)
Sum the rows of the matrix, add to vector.
Definition at line 1115 of file cu-vector.cc.
References KALDI_ASSERT, kaldi::kTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuVectorBase< Real >::Set().
Referenced by BlockAffineComponent::Backprop(), PerElementOffsetComponent::Backprop(), SimpleSentenceAveragingComponent::BackpropagateFnc(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), kaldi::CuVectorUnitTestAddRowSumMat(), SimpleSentenceAveragingComponent::PropagateFnc(), SentenceAveragingComponent::PropagateFnc(), Rbm::RbmUpdate(), NonlinearComponent::StoreStatsInternal(), CuMatrixBase< Real >::Sum(), kaldi::TestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), AffineTransform::Update(), SentenceAveragingComponent::Update(), TCNProjectionComponent::Update(), TCNComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), AddShift::Update(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), Rescale::Update(), NaturalGradientPerElementScaleComponent::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), AffineComponent::UpdateSimple(), BlockAffineComponent::UpdateSimple(), and NonlinearComponent::UpdateStats().
{
   KALDI_ASSERT(mat.NumCols() == Dim());
   if (Dim() == 0)
     return;
   CuVector<Real> ones(mat.NumRows());
   ones.Set(1.0);
   this->AddMatVec(alpha, mat, kTrans, ones, beta);
 }
void AddSpVec (const Real alpha, const CuSpMatrix< Real > & S, const CuVectorBase< Real > & v, const Real beta)
Definition at line 462 of file cu-vector.cc.
References CuVectorBase< Real >::Data(), CuPackedMatrix< Real >::Data(), CuVectorBase< Real >::dim_, Timer::Elapsed(), KALDI_ASSERT, CuSpMatrix< Real >::Mat(), CuPackedMatrix< Real >::NumCols(), CuPackedMatrix< Real >::NumRows(), and CuVectorBase< Real >::Vec().
Referenced by kaldi::CuVectorUnitTestAddSpVec(), and kaldi::nnet2::UnitTestPreconditionDirections().
{
   KALDI_ASSERT(M.NumCols() == v.dim_ && M.NumRows() == dim_);
   KALDI_ASSERT(&v != this);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     // Note: in our opinion the CuSpMatrix represents a lower-triangular matrix, but
     // in CUBLAS, for some stupid reason, everything is reversed.
     CU_SAFE_CALL(cublas_spmv(GetCublasHandle(), CUBLAS_FILL_MODE_UPPER, Dim(),
                             alpha, M.Data(), v.Data(), 1, beta, data_, 1));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().AddSpVec(alpha,M.Mat(),v.Vec(),beta);
   }
 }
void AddTpVec (const Real alpha, const CuTpMatrix< Real > & M, const MatrixTransposeType trans, const CuVectorBase< Real > & v, const Real beta)
Add triangular matrix times vector: this <– beta*this + alpha*M*v.
Works even if rv == *this.
Definition at line 588 of file cu-vector.cc.
References CuVectorBase< Real >::dim_, KALDI_ASSERT, CuTpMatrix< Real >::Mat(), CuVectorBase< Real >::MulTp(), CuPackedMatrix< Real >::NumRows(), and CuVectorBase< Real >::Vec().
Referenced by kaldi::UnitTestCuVectorAddTp(), and kaldi::UnitTestCuVectorAddTpVec().
{
   KALDI_ASSERT(dim_ == v.dim_ && dim_ == M.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     if (beta == 0.0) {
       if (&v != this) CopyFromVec(v);
       MulTp(M, trans);
       if (alpha != 1.0) Scale(alpha);
     } else {
       CuVector<Real> tmp(v);
       tmp.MulTp(M, trans);
       if (beta != 1.0) Scale(beta);  // *this <-- beta * *this
       AddVec(alpha, tmp, 1.0);          // *this += alpha * M * v
     }
   } else
 #endif
   {
     Vec().AddTpVec(alpha, M.Mat(), trans, v.Vec(), beta);
   }
 }
void AddVec (Real alpha, const CuVectorBase< Real > & vec, Real beta = 1.0)
Definition at line 1075 of file cu-vector.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by NonlinearComponent::Add(), RepeatedAffineComponent::Add(), NaturalGradientAffineComponent::Add(), AffineComponent::Add(), PerElementScaleComponent::Add(), PerElementOffsetComponent::Add(), BlockAffineComponent::Add(), ConvolutionComponent::Add(), Convolutional1dComponent::Add(), CuVectorBase< Real >::ApproxEqual(), SoftmaxComponent::Backprop(), kaldi::CuVectorUnitTestAddDiagMatMat(), kaldi::CuVectorUnitTestAddVec(), kaldi::CuVectorUnitTestAddVecCross(), RepeatedAffineComponent::PerturbParams(), AffineComponent::PerturbParams(), PerElementScaleComponent::PerturbParams(), PerElementOffsetComponent::PerturbParams(), BlockAffineComponent::PerturbParams(), ConvolutionComponent::PerturbParams(), Convolutional1dComponent::PerturbParams(), Rbm::RbmUpdate(), NonlinearComponent::StoreStatsInternal(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestCuVectorAddVec(), AffineTransform::Update(), TCNProjectionComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), AddShift::Update(), NaturalGradientRepeatedAffineComponent::Update(), Rescale::Update(), LstmProjectedStreams::Update(), BLstmProjectedStreams::Update(), NaturalGradientPerElementScaleComponent::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), and NonlinearComponent::UpdateStats().
{
   KALDI_ASSERT(vec.Dim() == Dim());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int32 dim = this->dim_;
     Real *data = this->data_;
     const Real *vec_data = vec.data_;
     if (beta != 1.0) CU_SAFE_CALL(cuda_scal(GetCublasHandle(), dim, beta, data, 1));
     if (alpha != 0.0) CU_SAFE_CALL(cuda_axpy(GetCublasHandle(), dim, alpha, vec_data, 1, data, 1));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     if (beta != 1.0) Vec().Scale(beta);
     Vec().AddVec(alpha, vec.Vec());
   }
 }
void AddVec (Real alpha, const CuVectorBase< OtherReal > & vec, Real beta = 1.0)
Definition at line 1099 of file cu-vector.cc.
{
   // We could implement this directly, without using a temporary-- this can
   // be done later, when we have time.
   CuVector<Real> temp(vec);
   this->AddVec(alpha, temp, beta);
 }
void AddVecVec (Real alpha, const CuVectorBase< Real > & v, const CuVectorBase< Real > & r, Real beta)
Definition at line 487 of file cu-vector.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), CuVectorBase< Real >::dim_, Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by SoftmaxComponent::Backprop(), and kaldi::CuVectorUnitTestAddVecVec().
{
   KALDI_ASSERT((dim_ == v.dim_ && dim_ == r.dim_));
   KALDI_ASSERT(this != &v && this != &r);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     cuda_add_vec_vec(dimGrid, dimBlock, alpha, data_, v.Data(), r.Data(), beta, dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::AddVecVec", tim.Elapsed());
   } else
 #endif
   {
     Vec().AddVecVec(alpha, v.Vec(), r.Vec(), beta);
   }
 }
MatrixIndexT ApplyCeiling (Real ceiling_val)
Definition at line 343 of file cu-vector.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), Timer::Elapsed(), kaldi::kUndefined, and CuVectorBase< Real >::Sum().
Referenced by LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), and kaldi::CuVectorUnitTestApplyCeiling().
{
   MatrixIndexT num_ceiled = 0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return 0;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     CuVector<float> count_vec(dim_, kUndefined);
     cuda_vec_apply_ceiling(dimGrid, dimBlock, data_, ceiling_val, count_vec.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     num_ceiled = count_vec.Sum();
     CuDevice::Instantiate().AccuProfile("CuVectorBase::ApplyFloor", tim.Elapsed());
   } else
 #endif
   {
     num_ceiled = Vec().ApplyCeiling(ceiling_val);
   }
   return num_ceiled;
 }
void ApplyExp ()
Definition at line 390 of file cu-vector.cc.
References CU1DBLOCK, and Timer::Elapsed().
Referenced by kaldi::CuVectorUnitTestApplyExp().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     cuda_vec_apply_exp(dimGrid, dimBlock, data_, dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::ApplyExp", tim.Elapsed());
   } else
 #endif
   {
     Vec().ApplyExp();
   }
 }
MatrixIndexT ApplyFloor (Real floor_val)
Definition at line 318 of file cu-vector.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), Timer::Elapsed(), kaldi::kUndefined, and CuVectorBase< Real >::Sum().
Referenced by LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), kaldi::CuVectorUnitTestApplyFloor(), AffineTransform::Update(), and ConvolutionalComponent::Update().
{
   MatrixIndexT num_floored = 0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return 0;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     CuVector<float> count_vec(dim_, kUndefined);
     cuda_vec_apply_floor(dimGrid, dimBlock, data_, floor_val, count_vec.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     num_floored = count_vec.Sum();
     CuDevice::Instantiate().AccuProfile("CuVectorBase::ApplyFloor", tim.Elapsed());
   } else
 #endif
   {
     num_floored = Vec().ApplyFloor(floor_val);
   }
   return num_floored;
 }
void ApplyLog ()
Definition at line 410 of file cu-vector.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), Timer::Elapsed(), and KALDI_ERR.
Referenced by kaldi::CuVectorUnitTestApplyLog(), DecodableNnet2Online::DecodableNnet2Online(), and NnetDecodableBase::NnetDecodableBase().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     CuVector<Real> flag(1);
     cuda_vec_apply_log(dimGrid, dimBlock, data_, flag.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     if (flag(0) > 0)
       KALDI_ERR << "Trying to take log of a negative number.";
     CuDevice::Instantiate().AccuProfile("CuVectorBase::ApplyLog", tim.Elapsed());
   } else
 #endif
   {
     Vec().ApplyLog();
   }
 }
void ApplyPow (Real power)
Definition at line 367 of file cu-vector.cc.
References CU1DBLOCK, and Timer::Elapsed().
Referenced by kaldi::CuVectorUnitTestApplyPow(), AffineComponentPreconditionedOnline::GetScalingFactor(), LengthNormComponent::PropagateFnc(), kaldi::nnet1::UnitTestLengthNorm(), and AffineTransform::Update().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     // for this particular kernel, x is #rows, y is #cols.  so
     // fake matrix with 1 row, Dim() cols.
     dim3 dimBlock(CU1DBLOCK, 1);
     dim3 dimGrid(n_blocks(Dim(), CU1DBLOCK), 1);
     ::MatrixDim fake_matrix_dim = { 1, Dim(), 1 };
     // num_cols is Dim(), num_rows is 1, stride is 1 (it's a don't-care).
     cuda_apply_pow(dimGrid, dimBlock, data_, power, fake_matrix_dim);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::ApplyFloor", tim.Elapsed());
   } else
 #endif
   {
     Vec().ApplyPow(power);
   }
 }
void ApplySoftMax ()
Definition at line 299 of file cu-vector.cc.
References CU1DBLOCK, and Timer::Elapsed().
Referenced by kaldi::CuVectorUnitTestApplySoftMax(), and kaldi::TestCuVectorSoftmax().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     size_t dimBlock = dim_ > CU1DBLOCK ? CU1DBLOCK : dim_; // for cuda_softmax_reduce function, dimBlock value is fixed min(CU1DBLOCK, dim) , represent CU1DBLOCK threads reduce a row at the same time.
     size_t dimGrid = 1;       // dimGrid value represent the number of rows
     ::MatrixDim dim = { 1, this->dim_, this->dim_};
     cuda_softmax_reduce(dimGrid, dimBlock, data_, data_, dim, this->dim_);//actually dim is not stride...
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().ApplySoftMax();
   }
 }
bool ApproxEqual (const CuVectorBase< Real > & other, float tol = 0.01) const
Definition at line 510 of file cu-vector.cc.
References CuVectorBase< Real >::AddVec(), CuVectorBase< Real >::dim_, KALDI_ASSERT, KALDI_ERR, and kaldi::VecVec().
Referenced by kaldi::nnet2::UnitTestPreconditionDirections().
{
   if (dim_ != other.dim_) KALDI_ERR << "ApproxEqual: size mismatch "
                                     << dim_ << " vs. " << other.dim_;
   KALDI_ASSERT(tol >= 0.0);
   CuVector<Real> tmp(*this);
   tmp.AddVec(-1.0, other);
   BaseFloat tmp_norm = sqrt(VecVec(tmp, tmp)), this_norm = sqrt(VecVec(*this, *this));
   return tmp_norm <= static_cast<Real>(tol) * this_norm;
 }
void CopyColFromMat (const CuMatrixBase< float > & mat, MatrixIndexT col)
Definition at line 99 of file cu-vector.cc.
References CU1DBLOCK, CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   KALDI_ASSERT(col < mat.NumCols());
   KALDI_ASSERT(dim_ == mat.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     cuda_copy_col_from_mat_df(dimGrid, dimBlock, data_, col, mat.Data(), mat.Dim(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::CopyColFromMat", tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyColFromMat(mat.Mat(), col);
   }
 }
void CopyColFromMat (const CuMatrixBase< double > & mat, MatrixIndexT col)
Definition at line 121 of file cu-vector.cc.
References CU1DBLOCK, CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   KALDI_ASSERT(col < mat.NumCols());
   KALDI_ASSERT(dim_ == mat.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_,CU1DBLOCK));
     cuda_copy_col_from_mat_fd(dimGrid, dimBlock, data_, col, mat.Data(), mat.Dim(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::CopyColFromMat", tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyColFromMat(mat.Mat(), col);
   }
 }
void CopyColFromMat (const CuMatrixBase< Real > & mat, MatrixIndexT col)
Definition at line 80 of file cu-vector.cc.
References CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by kaldi::CuVectorUnitTestCopyFromMat(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), ConvolutionComponent::Init(), FixedAffineComponent::Init(), Convolutional1dComponent::Init(), kaldi::UnitTestCuMatrixAddDiagVecMat(), NaturalGradientRepeatedAffineComponent::Update(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), and BlockAffineComponentPreconditioned::Update().
{
   KALDI_ASSERT(col < mat.NumCols());
   KALDI_ASSERT(dim_ == mat.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     cublas_copy(GetCublasHandle(),
                 this->dim_, mat.Data() + col, mat.Stride(), this->data_, 1);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::CopyColFromMat", tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyColFromMat(mat.Mat(),col);
   }
 }
void CopyColFromMat (const CuMatrixBase< OtherReal > & mat, MatrixIndexT col)
void CopyDiagFromMat (const CuMatrix< Real > & M)
Extracts the diagonal of a matrix.
Definition at line 1036 of file cu-vector.cc.
References CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuMatrix< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrixBase< Real >::Stride().
Referenced by kaldi::CuVectorUnitTestAddDiagMatMat(), and kaldi::CuVectorUnitTestCopyDiagFromMat().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(dim_ == std::min(M.NumRows(), M.NumCols()));
     Timer tim;
     CU_SAFE_CALL(cublas_copy(GetCublasHandle(), dim_, M.Data(), M.Stride() + 1,
                             data_, 1));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyDiagFromMat(M.Mat());
   }
 }
void CopyDiagFromPacked (const CuPackedMatrix< Real > & M)
Extracts the diagonal of a packed matrix M; works for Sp or Tp.
Definition at line 1015 of file cu-vector.cc.
References CU1DBLOCK, CuPackedMatrix< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuPackedMatrix< Real >::Mat(), and CuPackedMatrix< Real >::NumRows().
Referenced by kaldi::CuVectorUnitTestCopyDiagFromPacked(), CuPackedMatrix< Real >::Trace(), and kaldi::TraceSpSp().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(dim_ == M.NumRows());
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(Dim(), CU1DBLOCK));
     cuda_vec_copy_diag_from_packed(dimGrid, dimBlock, data_, M.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyDiagFromPacked(M.Mat());
   }
 }
void CopyFromVec (const CuVectorBase< Real > & src)
Copy functions; these will crash if the dimension do not match.
The operator = in class CuVector will also change the sizes for you.
Definition at line 919 of file cu-vector.cc.
References CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), CuVectorBase< Real >::dim_, Timer::Elapsed(), and KALDI_ASSERT.
Referenced by CuSparseMatrix< Real >::CopyElementsToVec(), CuVectorBase< Real >::CopyFromVec(), CuVector< BaseFloat >::CuVector(), kaldi::CuVectorUnitTestCopyCross(), kaldi::CuVectorUnitTestCopyCross2(), PerElementScaleComponent::Init(), PerElementOffsetComponent::Init(), SoftmaxComponent::MixUp(), CuVector< BaseFloat >::operator=(), OnlinePreconditionerSimple::PreconditionDirections(), OnlineNaturalGradientSimple::PreconditionDirections(), DctComponent::Reorder(), AffineTransform::SetBias(), Rescale::SetScaleVec(), AddShift::SetShiftVec(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestCuMatrixAddVecToCols(), kaldi::UnitTestCuMatrixAddVecToRows(), kaldi::UnitTestCuMatrixAddVecVec(), kaldi::UnitTestCuMatrixDivRowsVec(), kaldi::UnitTestCuMatrixMulColsVec(), kaldi::UnitTestCuMatrixMulRowsVec(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), kaldi::UnitTestCuVectorAddTpVec(), kaldi::UnitTestCuVectorAddVec(), kaldi::UnitTestCuVectorCopyFromVec(), kaldi::UnitTestCuVectorInvertElements(), kaldi::UnitTestCuVectorMulTp(), RepeatedAffineComponent::UnVectorize(), AffineComponent::UnVectorize(), PerElementScaleComponent::UnVectorize(), PerElementOffsetComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), and Convolutional1dComponent::UnVectorize().
{
   KALDI_ASSERT(src.Dim() == dim_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     CU_SAFE_CALL(cudaMemcpy(data_, src.data_, src.dim_ * sizeof(Real), cudaMemcpyDeviceToDevice));
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     memcpy(static_cast<void*>(data_), static_cast<void*>(src.data_),
            dim_ * sizeof(Real));
   }
 }
void CopyFromVec (const CuVectorBase< OtherReal > & M)
Definition at line 340 of file cu-vector.h.
{
   v.CopyToVec(&this);
 }
void CopyFromVec (const VectorBase< OtherReal > & src)
Definition at line 756 of file cu-vector.cc.
References CuVectorBase< Real >::CopyFromVec(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and kaldi::kUndefined.
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (sizeof(Real) != sizeof(OtherReal)) {
       CuVector<OtherReal> temp(dim_, kUndefined);
       temp.CopyFromVec(src);
       this->CopyFromVec(temp);
     } else {
       KALDI_ASSERT(src.Dim() == dim_);
       if (dim_ == 0) return;
       Timer tim;
       CU_SAFE_CALL(cudaMemcpy(data_, src.Data(), src.Dim()*sizeof(Real), cudaMemcpyHostToDevice));
       CuDevice::Instantiate().AccuProfile("CuVector::CopyFromVecH2D",tim.Elapsed());
     }
   } else
   #endif
   {
     Vec().CopyFromVec(src);
   }
 }
void CopyFromVec< float > (const CuVectorBase< float > & src)
void CopyFromVec< double > (const CuVectorBase< double > & src)
void CopyFromVec (const CuVectorBase< float > & src)
Definition at line 715 of file cu-vector.cc.
References CU2DBLOCK, CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
{
   KALDI_ASSERT(src.Dim() == dim_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU2DBLOCK);
     int dimGrid(n_blocks(dim_, CU2DBLOCK));
     cuda_copy_from_vec_df(dimGrid, dimBlock, data_, src.data_, dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyFromVec(src.Vec());
   }
 }
void CopyFromVec (const CuVectorBase< double > & src)
Definition at line 735 of file cu-vector.cc.
References CU1DBLOCK, CuVectorBase< Real >::data_, CuVectorBase< Real >::Dim(), Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
{
   KALDI_ASSERT(src.Dim() == dim_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_, CU1DBLOCK));
     cuda_copy_from_vec_fd(dimGrid, dimBlock, data_, src.data_, dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyFromVec(src.Vec());
   }
 }
void CopyRowsFromMat (const CuMatrixBase< Real > & M)
Definition at line 141 of file cu-vector.cc.
References CuMatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, CuMatrixBase< Real >::Mat(), CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::RowData(), and CuMatrixBase< Real >::Stride().
Referenced by kaldi::CuVectorUnitTestCopyFromMat(), and TCNComponent::PropagateFnc().
{
   KALDI_ASSERT(dim_ == mat.NumCols() * mat.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     if (mat.Stride() == mat.NumCols() && mat.NumRows() != 0) {
       CU_SAFE_CALL(cudaMemcpy(data_, mat.Data(), sizeof(Real)*dim_,
                               cudaMemcpyDeviceToDevice));
     } else {
       Real* vec_data = data_;
       for (MatrixIndexT r = 0; r < mat.NumRows(); r++) {
         CU_SAFE_CALL(cudaMemcpy(vec_data, mat.RowData(r),
                                 sizeof(Real) * mat.NumCols(),
                                 cudaMemcpyDeviceToDevice));
         vec_data += mat.NumCols();
       }
     }
     CuDevice::Instantiate().AccuProfile("CuVectorBase::CopyRowsFromMat", tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyRowsFromMat(mat.Mat());
   }
 }
void CopyRowsFromMat (const MatrixBase< Real > & M)
Definition at line 193 of file cu-vector.cc.
References MatrixBase< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::RowData(), and MatrixBase< Real >::Stride().
{
   KALDI_ASSERT(dim_ == mat.NumCols() * mat.NumRows());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     if (mat.Stride() == mat.NumCols()) {
       CU_SAFE_CALL(cudaMemcpy(data_, mat.Data(), sizeof(Real)*dim_,
                               cudaMemcpyHostToDevice));
     } else {
       Real* vec_data = data_;
       for (MatrixIndexT r = 0; r < mat.NumRows(); r++) {
         CU_SAFE_CALL(cudaMemcpy(vec_data, mat.RowData(r),
                                 sizeof(Real) * mat.NumCols(),
                                 cudaMemcpyHostToDevice));
         vec_data += mat.NumCols();
       }
     }
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().CopyRowsFromMat(mat);
   }
 }
template void CopyToVec (VectorBase< OtherReal > * dst) const
Definition at line 788 of file cu-vector.cc.
References VectorBase< Real >::CopyFromVec(), CuVectorBase< Real >::CopyToVec(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), Timer::Elapsed(), and KALDI_ASSERT.
Referenced by CuVectorBase< Real >::CopyToVec(), kaldi::nnet1::CountCorrectFramesWeighted(), Nnet::GetGradient(), AddShift::GetParams(), Rescale::GetParams(), kaldi::nnet1::MomentStatistics(), CuVectorBase< Real >::Sum(), kaldi::UnitTestCuDiffXent(), kaldi::UnitTestCuVectorAddColSumMat(), kaldi::UnitTestCuVectorAddColSumMatLarge(), kaldi::UnitTestCuVectorAddRowSumMat(), kaldi::UnitTestCuVectorAddRowSumMatLarge(), kaldi::UnitTestCuVectorAddTpVec(), kaldi::UnitTestCuVectorAddVec(), kaldi::UnitTestCuVectorInvertElements(), kaldi::UnitTestCuVectorMulTp(), kaldi::UnitTestMulTp(), and kaldi::UnitTestVector().
{
   KALDI_ASSERT(dim_ == dst->Dim());
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (sizeof(Real) != sizeof(OtherReal)) {
       CuVector<OtherReal> temp(*this);
       temp.CopyToVec(dst);
     } else {
       if (dim_ == 0) return;
       Timer tim;
       CU_SAFE_CALL(cudaMemcpy(dst->Data(), this->data_,
                               sizeof(Real) * dim_, cudaMemcpyDeviceToHost));
       CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
     }
   } else
 #endif
   {
     dst->CopyFromVec(this->Vec());
   }
 }
Real* Data () inline
Returns a pointer to the start of the vector's data.
Definition at line 70 of file cu-vector.h.
Referenced by CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMatDiagVec(), CuVectorBase< Real >::AddMatVec(), CuVectorBase< Real >::AddSpVec(), CuSpMatrix< Real >::AddVec2(), CuVectorBase< Real >::AddVecVec(), CuMatrixBase< Real >::AddVecVec(), CuVectorBase< Real >::ApplyCeiling(), CuVectorBase< Real >::ApplyFloor(), CuVectorBase< Real >::ApplyLog(), CuMatrix< Real >::CompObjfAndDeriv(), CuMatrixBase< Real >::CopyColFromVec(), CuSparseMatrix< Real >::CopyElementsToVec(), MatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), CuVectorBase< Real >::Max(), CuVectorBase< Real >::Min(), CuVectorBase< Real >::MulElements(), CuRand< Real >::RandGaussian(), CuVectorBase< Real >::Sum(), CuMatrixBase< Real >::Trace(), kaldi::TraceMatMat(), and kaldi::VecVec().
 { return data_; }
const Real* Data () const inline
Returns a pointer to the start of the vector's data (const).
Definition at line 72 of file cu-vector.h.
 { return data_; }
MatrixIndexT Dim () const inline
Dimensions.
Definition at line 67 of file cu-vector.h.
Referenced by NonlinearComponent::Add(), CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMatDiagVec(), NnetStats::AddStatsFromNnet(), CuVectorBase< Real >::AddVec(), CuSpMatrix< Real >::AddVec2(), CuMatrixBase< Real >::AddVecToCols(), CuMatrixBase< Real >::AddVecToRows(), CuMatrixBase< Real >::AddVecVec(), AffineComponent::AffineComponent(), Convolutional2DComponent::BackpropagateFnc(), Convolutional1dComponent::Convolutional1dComponent(), ConvolutionComponent::ConvolutionComponent(), CuMatrixBase< Real >::CopyColFromVec(), CuSparseMatrix< Real >::CopyElementsToVec(), CuVectorBase< Real >::CopyFromVec(), MatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), kaldi::nnet1::CountCorrectFramesWeighted(), CuVector< Real >::CuVector(), CuVector< BaseFloat >::CuVector(), DecodableNnet2Online::DecodableNnet2Online(), CuMatrixBase< Real >::DivRowsVec(), NnetDecodableBase::DoNnetComputation(), Nnet::GetGradient(), AffineTransform::GetParams(), TCNProjectionComponent::GetParams(), LstmProjectedStreams::GetParams(), ConvolutionalComponent::GetParams(), Convolutional2DComponent::GetParams(), BLstmProjectedStreams::GetParams(), AffineComponentPreconditionedOnline::GetScalingFactor(), NonlinearComponent::Info(), AffineComponent::Info(), AffineComponentPreconditioned::Info(), AffineComponentPreconditionedOnline::Info(), FixedAffineComponent::Info(), FixedScaleComponent::Info(), FixedBiasComponent::Info(), Convolutional1dComponent::Info(), PerElementScaleComponent::Init(), PerElementOffsetComponent::Init(), FixedScaleComponent::Init(), FixedBiasComponent::Init(), Rbm::InitData(), LstmProjectedStreams::InitVecParam(), BLstmProjectedStreams::InitVecParam(), PerElementScaleComponent::InputDim(), PerElementOffsetComponent::InputDim(), FixedScaleComponent::InputDim(), FixedBiasComponent::InputDim(), SoftmaxComponent::MixUp(), kaldi::nnet1::MomentStatistics(), CuMatrixBase< Real >::MulColsVec(), CuMatrixBase< Real >::MulRowsVec(), RepeatedAffineComponent::NumParameters(), BlockAffineComponent::NumParameters(), AffineTransform::NumParams(), TCNProjectionComponent::NumParams(), LstmProjectedStreams::NumParams(), ConvolutionalComponent::NumParams(), Convolutional2DComponent::NumParams(), BLstmProjectedStreams::NumParams(), AddShift::NumParams(), Rescale::NumParams(), CuVector< BaseFloat >::operator=(), PerElementScaleComponent::OutputDim(), PerElementOffsetComponent::OutputDim(), FixedScaleComponent::OutputDim(), FixedBiasComponent::OutputDim(), PerElementScaleComponent::PerturbParams(), PerElementOffsetComponent::PerturbParams(), kaldi::nnet3::PrintParameterStats(), RepeatedAffineComponent::Propagate(), LengthNormComponent::PropagateFnc(), CuRand< Real >::RandGaussian(), Rbm::RbmUpdate(), AffineTransform::ReadData(), ConvolutionalComponent::ReadData(), Rbm::ReadData(), AffineTransform::SetBias(), AffineComponent::SetParams(), ConvolutionComponent::SetParams(), Convolutional1dComponent::SetParams(), Rescale::SetScaleVec(), AddShift::SetShiftVec(), NonlinearComponent::StoreStatsInternal(), PdfPrior::SubtractOnLogpost(), RepeatedAffineComponent::UnVectorize(), BlockAffineComponent::UnVectorize(), ConvolutionComponent::UnVectorize(), Convolutional1dComponent::UnVectorize(), RepeatedAffineComponent::Update(), NaturalGradientRepeatedAffineComponent::Update(), NaturalGradientPerElementScaleComponent::Update(), NonlinearComponent::UpdateStats(), RepeatedAffineComponent::Vectorize(), BlockAffineComponent::Vectorize(), ConvolutionComponent::Vectorize(), Convolutional1dComponent::Vectorize(), kaldi::VecVec(), NormalizeComponent::Write(), and NonlinearComponent::Write().
 { return dim_;  }
void InvertElements ()
Definition at line 1141 of file cu-vector.cc.
References CU1DBLOCK, rnnlm::d, and Timer::Elapsed().
Referenced by Convolutional2DComponent::BackpropagateFnc(), kaldi::CuVectorUnitTestInvertElements(), LengthNormComponent::PropagateFnc(), kaldi::UnitTestCuVectorInvertElements(), AffineTransform::Update(), and ConvolutionalComponent::Update().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU1DBLOCK, 1);
     dim3 dimGrid(n_blocks(dim_, CU1DBLOCK));
     MatrixDim d = {1, dim_, dim_};
     cuda_invert_elements(dimGrid, dimBlock, data_, d);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().InvertElements();
   }
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (CuVectorBase< Real >) private
Real Max () const
Returns the maximum value of any element, or -infinity for the empty vector.
Definition at line 655 of file cu-vector.cc.
References CuVectorBase< Real >::Data(), and Timer::Elapsed().
Referenced by kaldi::CuVectorUnitTestMax(), PerElementScaleComponent::Info(), and PerElementOffsetComponent::Info().
{
   Real result = 0.0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) {  // max of an empty set is -infinity.
       return -std::numeric_limits<Real>::infinity();
     }
     Timer tim;
     CuVector<Real> ans(1);
     cuda_vec_max(data_, ans.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     result = ans(0);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     result = (this->Vec()).Max();
   }
   return result;
 }
Real Min () const
Returns the minimum value of any element, or +infinity for the empty vector.
Definition at line 633 of file cu-vector.cc.
References CuVectorBase< Real >::Data(), and Timer::Elapsed().
Referenced by kaldi::CuVectorUnitTestMin(), PerElementScaleComponent::Info(), and PerElementOffsetComponent::Info().
{
   Real result = 0.0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) {  // min of an empty set is infinity.
       return std::numeric_limits<Real>::infinity();
     }
     Timer tim;
     CuVector<Real> ans(1);
     cuda_vec_min(data_, ans.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     result = ans(0);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     result = (this->Vec()).Min();
   }
   return result;
 }
void MulElements (const CuVectorBase< Real > & v)
Definition at line 695 of file cu-vector.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), CuVectorBase< Real >::dim_, Timer::Elapsed(), KALDI_ASSERT, and CuVectorBase< Real >::Vec().
Referenced by kaldi::CuVectorUnitTestInvertElements(), Xent::Eval(), AffineComponentPreconditionedOnline::GetScalingFactor(), and kaldi::UnitTestVector().
{
   KALDI_ASSERT(dim_ == v.dim_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_, CU1DBLOCK));
     cuda_vec_mul_elements(dimGrid, dimBlock, data_, v.Data(), dim_);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile("CuVectorBase::MulElements", tim.Elapsed());
   } else
 #endif
   {
     Vec().MulElements(v.Vec());
   }
 }
void MulTp (const CuTpMatrix< Real > & M, const MatrixTransposeType trans)
Multiplies this vector by lower-triangular marix: *this <– *this *M.
Definition at line 616 of file cu-vector.cc.
References CuPackedMatrix< Real >::Data(), Timer::Elapsed(), KALDI_ASSERT, kaldi::kTrans, CuTpMatrix< Real >::Mat(), and CuPackedMatrix< Real >::NumRows().
Referenced by CuVectorBase< Real >::AddTpVec(), kaldi::UnitTestCuVectorMulTp(), and kaldi::UnitTestMulTp().
{
   KALDI_ASSERT(M.NumRows() == dim_);
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     cublas_tpmv(GetCublasHandle(), (trans==kTrans? CUBLAS_OP_N:CUBLAS_OP_T),
                 M.NumRows(), M.Data(), data_, 1);
     CuDevice::Instantiate().AccuProfile("CuVectorBase::MulTp", tim.Elapsed());
   } else
 #endif
   {
     Vec().MulTp(M.Mat(), trans);
   }
 }
Real Norm (Real p)
Definition at line 168 of file cu-vector.cc.
References Timer::Elapsed(), KALDI_ASSERT, and KALDI_ERR.
Referenced by kaldi::CuVectorUnitTestNorm(), and CuSparseMatrix< Real >::FrobeniusNorm().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     Real ans;
     KALDI_ASSERT(p == 1.0 || p == 2.0);
     if (dim_ == 0) return 0.0;
     if (p == 1.0) {
       cublas_asum(GetCublasHandle(), dim_, data_, 1, &ans);
     } else {
       cublas_nrm2(GetCublasHandle(), dim_, data_, 1, &ans);
     }
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
     if (ans != ans) {
       KALDI_ERR << "NaN in norm " << *this;
     }
     return ans;
   } else
 #endif
   {
     return Vec().Norm(p);
   }
 }
CuValue<Real> operator() (MatrixIndexT i) inline
Definition at line 166 of file cu-vector.h.
{
     KALDI_PARANOID_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                           static_cast<UnsignedMatrixIndexT>(dim_));
     return CuValue<Real>(data_ + i);
   }
Real operator() (MatrixIndexT i) const inline
Definition at line 174 of file cu-vector.h.
{
     KALDI_PARANOID_ASSERT(static_cast<UnsignedMatrixIndexT>(i) <
                           static_cast<UnsignedMatrixIndexT>(dim_));
     return CuValue<Real>(data_ + i); // will be casted to Real.
   }
CuSubVector<Real> Range (const MatrixIndexT o, const MatrixIndexT l) inline
Definition at line 130 of file cu-vector.h.
Referenced by Convolutional2DComponent::BackpropagateFnc(), kaldi::UnitTestCuSubVector(), BlockAffineComponentPreconditioned::Update(), and AffineComponent::Widen().
{
     return CuSubVector<Real>(*this, o, l);
   }
const CuSubVector<Real> Range (const MatrixIndexT o, const MatrixIndexT l) const inline
Definition at line 134 of file cu-vector.h.
{
     return CuSubVector<Real>(*this, o, l);
   }
void ReplaceValue (Real orig, Real changed)
Definition at line 677 of file cu-vector.cc.
References CU1DBLOCK, and Timer::Elapsed().
Referenced by kaldi::UnitTestCuVectorReplaceValue().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (dim_ == 0) return;
     Timer tim;
     int dimBlock(CU1DBLOCK);
     int dimGrid(n_blocks(dim_, CU1DBLOCK));
     cuda_replace_value(dimGrid, dimBlock, data_, dim_, orig, changed);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().ReplaceValue(orig, changed);
   }
 }
void Scale (Real value)
Definition at line 1054 of file cu-vector.cc.
References CU1DBLOCK, rnnlm::d, and Timer::Elapsed().
Referenced by BlockSoftmax::BackpropagateFnc(), kaldi::CuVectorUnitTestAddDiagMatMat(), kaldi::CuVectorUnitTestScale(), RepeatedAffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), PerElementScaleComponent::Init(), PerElementOffsetComponent::Init(), BlockAffineComponent::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), main(), kaldi::nnet2::PreconditionDirections(), Rbm::RbmUpdate(), NormalizeComponent::Read(), NonlinearComponent::Read(), NonlinearComponent::Scale(), RepeatedAffineComponent::Scale(), NaturalGradientAffineComponent::Scale(), AffineComponent::Scale(), PerElementScaleComponent::Scale(), PerElementOffsetComponent::Scale(), BlockAffineComponent::Scale(), ConvolutionComponent::Scale(), Convolutional1dComponent::Scale(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestVector(), AffineTransform::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), and NnetLogprobTask::~NnetLogprobTask().
{
   #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (Dim() == 0 ) return;
     Timer tim;
     dim3 dimBlock(CU1DBLOCK);
     dim3 dimGrid(n_blocks(Dim(), CU1DBLOCK));
     ::MatrixDim d = { 1, Dim(), Dim() };
     cuda_scale(dimGrid, dimBlock, data_, value, d);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
   #endif
   {
     Vec().Scale(value);
   }
 }
void Set (Real value)
Definition at line 973 of file cu-vector.cc.
References CU1DBLOCK, rnnlm::d, and Timer::Elapsed().
Referenced by CuVectorBase< Real >::AddColSumMat(), CuVectorBase< Real >::AddRowSumMat(), kaldi::CuVectorUnitTestSum(), CuMatrixBase< Real >::FindRowMaxId(), AddShift::InitData(), Rescale::InitData(), kaldi::TestCuVectorVecVecOne(), kaldi::nnet1::UnitTestLengthNorm(), and kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU1DBLOCK);
     dim3 dimGrid(n_blocks(Dim(), CU1DBLOCK));
     ::MatrixDim d = { 1, Dim(), Dim() };
     cuda_set_const(dimGrid, dimBlock, data_, value, d);
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     Vec().Set(value);
   }
 }
void SetRandn ()
Definition at line 253 of file cu-vector.cc.
References CuRand< Real >::RandGaussian().
Referenced by kaldi::CuVectorUnitTestAddDiagMat2(), kaldi::CuVectorUnitTestAddDiagMatMat(), kaldi::CuVectorUnitTestAddMatVec(), kaldi::CuVectorUnitTestAddSpVec(), kaldi::CuVectorUnitTestAddVec(), kaldi::CuVectorUnitTestAddVecCross(), kaldi::CuVectorUnitTestAddVecExtra(), kaldi::CuVectorUnitTestAddVecVec(), kaldi::CuVectorUnitTestApplyCeiling(), kaldi::CuVectorUnitTestApplyExp(), kaldi::CuVectorUnitTestApplyFloor(), kaldi::CuVectorUnitTestApplyLog(), kaldi::CuVectorUnitTestApplyPow(), kaldi::CuVectorUnitTestApplySoftMax(), kaldi::CuVectorUnitTestApproxEqual(), kaldi::CuVectorUnitTestCopyCross(), kaldi::CuVectorUnitTestCopyCross2(), kaldi::CuVectorUnitTestInvertElements(), kaldi::CuVectorUnitTestMax(), kaldi::CuVectorUnitTestMin(), kaldi::CuVectorUnitTestScale(), kaldi::CuVectorUnitTestVecVec(), RepeatedAffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), PerElementScaleComponent::Init(), PerElementOffsetComponent::Init(), BlockAffineComponent::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), FixedScaleComponent::InitFromConfig(), FixedBiasComponent::InitFromConfig(), RepeatedAffineComponent::PerturbParams(), AffineComponent::PerturbParams(), PerElementScaleComponent::PerturbParams(), PerElementOffsetComponent::PerturbParams(), BlockAffineComponent::PerturbParams(), ConvolutionComponent::PerturbParams(), Convolutional1dComponent::PerturbParams(), kaldi::TestCuMatrixAddDiagVecMat(), kaldi::TestCuVectorAddColSumMat(), kaldi::TestCuVectorAddDiagMat2(), kaldi::TestCuVectorAddDiagMatMat(), kaldi::TestCuVectorAddRowSumMat(), kaldi::TestCuVectorSoftmax(), kaldi::TestCuVectorSum(), kaldi::TestCuVectorVecVecOne(), kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestCuMatrixAddMatDiagVec(), kaldi::UnitTestCuMatrixCopyRowsFromVec(), kaldi::UnitTestCuSubVector(), kaldi::UnitTestCuVectorIO(), kaldi::nnet2::UnitTestFixedBiasComponent(), kaldi::nnet2::UnitTestFixedScaleComponent(), kaldi::nnet2::UnitTestGenericComponentInternal(), and kaldi::UnitTestVector().
{
   if (dim_ == 0) return;
   CuRand<Real> tmp;
   tmp.RandGaussian(this);
 }
void SetZero ()
Math operations.
Definition at line 937 of file cu-vector.cc.
References Timer::Elapsed(), and KALDI_ASSERT.
Referenced by Rbm::RbmUpdate(), RepeatedAffineComponent::SetZero(), AffineComponent::SetZero(), PerElementScaleComponent::SetZero(), PerElementOffsetComponent::SetZero(), BlockAffineComponent::SetZero(), ConvolutionComponent::SetZero(), Convolutional1dComponent::SetZero(), NonlinearComponent::StoreStatsInternal(), NonlinearComponent::UpdateStats(), and NonlinearComponent::ZeroStats().
{
   if (dim_==0 || data_==NULL) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     KALDI_ASSERT(dim_>=0);
     KALDI_ASSERT(data_!=NULL);
     Timer tim;
     CU_SAFE_CALL(cudaMemset(data_, 0, dim_*sizeof(Real)));
     CuDevice::Instantiate().AccuProfile("CuVector::SetZero",tim.Elapsed());
   } else
 #endif
   {
     Vec().SetZero();
   }
 }
Real Sum () const
Definition at line 261 of file cu-vector.cc.
References CuVectorBase< Real >::CopyToVec(), CU1DBLOCK, CuVectorBase< Real >::Data(), Timer::Elapsed(), kaldi::kUndefined, and VectorBase< Real >::Sum().
Referenced by CuVectorBase< Real >::ApplyCeiling(), CuVectorBase< Real >::ApplyFloor(), kaldi::CuVectorUnitTestCopyDiagFromMat(), Xent::Eval(), AffineComponentPreconditionedOnline::GetScalingFactor(), FixedScaleComponent::Info(), FixedBiasComponent::Info(), main(), SoftmaxComponent::MixUp(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), kaldi::nnet3::PrintParameterStats(), CuSparseMatrix< Real >::Sum(), CuMatrixBase< Real >::Sum(), kaldi::TestCuVectorSum(), CuPackedMatrix< Real >::Trace(), kaldi::UnitTestCuMatrixAddDiagVecMat(), and NnetLogprobTask::~NnetLogprobTask().
{
   if (dim_ == 0)
     return 0.0;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     int max_threads = 2048;
     // This is the smallest block of consecutive vector elements, which
     // its sum will save at the partial vector.
     int block_size = (dim_ + max_threads - 1) / max_threads;
     if (block_size > 3) {
       int dimBlock(CU1DBLOCK);
       int dimGrid(n_blocks(max_threads, CU1DBLOCK));
       CuVector<Real> g(dimGrid);
       cuda_pvec_sum(dimGrid, dimBlock, data_, g.Data(), dim_, block_size);
       CU_SAFE_CALL(cudaGetLastError());
       Vector<Real> tmp(dimGrid);
       g.CopyToVec(&tmp);
       CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
       return tmp.Sum();
     } else {
       if (dim_ == 0) return 0.0;
       CuVector<Real> tmp(1, kUndefined);
       int dimBlock(CU1DBLOCK);
       int dimGrid = 1; // only 1 block here. we have loops in each thread.
       cuda_vec_sum(dimGrid, dimBlock, data_, tmp.Data(), dim_, 1);
       CU_SAFE_CALL(cudaGetLastError());
       CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
       return tmp(0);
     }
   } else
 #endif
   {
     return Vec().Sum();
   }
 }
const VectorBase<Real>& Vec () const inline protected
Definition at line 201 of file cu-vector.h.
Referenced by CuMatrixBase< Real >::AddDiagVecMat(), CuMatrixBase< Real >::AddMatDiagVec(), CuVectorBase< Real >::AddMatVec(), CuVectorBase< Real >::AddSpVec(), CuVectorBase< Real >::AddTpVec(), CuVectorBase< Real >::AddVec(), CuSpMatrix< Real >::AddVec2(), CuMatrixBase< Real >::AddVecToCols(), CuMatrixBase< Real >::AddVecToRows(), CuVectorBase< Real >::AddVecVec(), CuMatrixBase< Real >::AddVecVec(), CuMatrixBase< Real >::CopyColFromVec(), CuVectorBase< Real >::CopyFromVec(), MatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::CopyRowsFromVec(), CuMatrixBase< Real >::DiffXent(), CuMatrixBase< Real >::DivRowsVec(), CuMatrixBase< Real >::MulColsVec(), CuVectorBase< Real >::MulElements(), CuMatrixBase< Real >::MulRowsVec(), CuRand< Real >::RandGaussian(), and kaldi::VecVec().
{
     return *(reinterpret_cast<const VectorBase<Real>* >(this));
   }
VectorBase<Real>& Vec () inline protected
Definition at line 204 of file cu-vector.h.
{
     return *(reinterpret_cast<VectorBase<Real>* >(this));
   }
Friends And Related Function Documentation
void cu::Splice (const CuMatrixBase< Real > & src, const CuArray< int32 > & frame_offsets, CuMatrixBase< Real > * tgt) friend
friend class CuMatrixBase< Real > friend
Definition at line 52 of file cu-vector.h.
friend class CuPackedMatrix< Real > friend
Definition at line 54 of file cu-vector.h.
friend class CuRand< Real > friend
Definition at line 64 of file cu-vector.h.
friend class CuSpMatrix< Real > friend
Definition at line 55 of file cu-vector.h.
friend class CuTpMatrix< Real > friend
Definition at line 56 of file cu-vector.h.
friend class CuVectorBase< double > friend
Definition at line 51 of file cu-vector.h.
friend class CuVectorBase< float > friend
Definition at line 50 of file cu-vector.h.
friend class MatrixBase< Real > friend
Definition at line 53 of file cu-vector.h.
OtherReal VecVec (const CuVectorBase< OtherReal > & v1, const CuVectorBase< OtherReal > & v2) friend
Member Data Documentation
Real* data_ protected
GPU data pointer (or regular data pointer if CUDA is not compiled in or we have no GPU).
Definition at line 212 of file cu-vector.h.
Referenced by CuVectorBase< Real >::AddVec(), CuMatrixBase< Real >::AddVecToCols(), CuMatrixBase< Real >::AddVecToRows(), CuVectorBase< Real >::CopyFromVec(), CuVectorBase< BaseFloat >::Data(), CuMatrixBase< Real >::DiffXent(), CuMatrixBase< Real >::DivRowsVec(), CuMatrixBase< Real >::FindRowMaxId(), CuMatrixBase< Real >::MulColsVec(), CuMatrixBase< Real >::MulRowsVec(), and CuVectorBase< BaseFloat >::operator()().
MatrixIndexT dim_ protected
dimension of the vector
Definition at line 214 of file cu-vector.h.
Referenced by CuVectorBase< Real >::AddMatVec(), CuVectorBase< Real >::AddSpVec(), CuVectorBase< Real >::AddTpVec(), CuVectorBase< Real >::AddVecVec(), CuVectorBase< Real >::ApproxEqual(), CuVectorBase< Real >::CopyFromVec(), CuVectorBase< BaseFloat >::Dim(), CuVectorBase< Real >::MulElements(), and CuVectorBase< BaseFloat >::operator()().
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-vector.h
cudamatrix/cu-vector.cc