Kaldi: NaturalGradientRepeatedAffineComponent Class Reference
NaturalGradientRepeatedAffineComponent Class Reference
#include <nnet-simple-component.h>
Public Member Functions
NaturalGradientRepeatedAffineComponent ()
virtual std::string Type () const
Returns a string such as "SigmoidComponent", describing the type of the object.
virtual Component * Copy () const
Copies component (deep copy).
NaturalGradientRepeatedAffineComponent (const NaturalGradientRepeatedAffineComponent &other)
Public Member Functions inherited from RepeatedAffineComponent
virtual int32 InputDim () const
Returns input-dimension of this component.
virtual int32 OutputDim () const
Returns output-dimension of this component.
virtual std::string Info () const
Returns some text-form information about this component, for diagnostics.
virtual void InitFromConfig (ConfigLine *cfl)
Initialize, from a ConfigLine object.
RepeatedAffineComponent ()
virtual int32 Properties () const
Return bitmask of the component's properties.
virtual void Propagate (const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out) const
Propagate function.
virtual void Backprop (const std::string &debug_info, const ComponentPrecomputedIndexes *indexes, const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &, const CuMatrixBase< BaseFloat > &out_deriv, Component *to_update, CuMatrixBase< BaseFloat > *in_deriv) const
Backprop function; depending on which of the arguments 'to_update' and 'in_deriv' are non-NULL, this can compute input-data derivatives and/or perform model update.
virtual void Read (std::istream &is, bool binary)
Read function (used after we know the type of the Component); accepts input that is missing the token that describes the component type, in case it has already been consumed.
virtual void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual void Scale (BaseFloat scale)
This virtual function when called by.
virtual void Add (BaseFloat alpha, const Component &other)
This virtual function when called by – an UpdatableComponent adds the parameters of another updatable component, times some constant, to the current parameters.
virtual void SetZero (bool treat_as_gradient)
Sets parameters to zero, and if treat_as_gradient is true, sets is_gradient_ to true and sets learning_rate_ to 1, ignoring learning_rate_factor_.
virtual void PerturbParams (BaseFloat stddev)
This function is to be used in testing.
virtual BaseFloat DotProduct (const UpdatableComponent &other) const
Computes dot-product between parameters of two instances of a Component.
virtual int32 NumParameters () const
The following new virtual function returns the total dimension of the parameters in this class.
virtual void Vectorize (VectorBase< BaseFloat > *params) const
Turns the parameters into vector form.
virtual void UnVectorize (const VectorBase< BaseFloat > &params)
Converts the parameters from vector form.
const CuVector< BaseFloat > & BiasParams ()
const CuMatrix< BaseFloat > & LinearParams ()
RepeatedAffineComponent (const RepeatedAffineComponent &other)
void Init (int32 input_dim, int32 output_dim, int32 num_repeats, BaseFloat param_stddev, BaseFloat bias_mean, BaseFloat bias_stddev)
Public Member Functions inherited from UpdatableComponent
UpdatableComponent (const UpdatableComponent &other)
UpdatableComponent ()
virtual ~UpdatableComponent ()
virtual void SetLearningRate (BaseFloat lrate)
Sets the learning rate of gradient descent.
BaseFloat LearningRate () const
Gets the learning rate of gradient descent.
Public Member Functions inherited from Component
virtual void StoreStats (const CuMatrixBase< BaseFloat > &out_value)
This function may store stats on average activation values, and for some component types, the average value of the derivative of the nonlinearity.
virtual void ZeroStats ()
Components that provide an implementation of StoreStats should also provide an implementation of ZeroStats(), to set those stats to zero.
virtual void GetInputIndexes (const MiscComputationInfo &misc_info, const Index &output_index, std::vector< Index > *desired_indexes) const
This function only does something interesting for non-simple Components.
virtual bool IsComputable (const MiscComputationInfo &misc_info, const Index &output_index, const IndexSet &input_index_set, std::vector< Index > *used_inputs) const
This function only does something interesting for non-simple Components, and it exists to make it possible to manage optionally-required inputs.
virtual void ReorderIndexes (std::vector< Index > *input_indexes, std::vector< Index > *output_indexes) const
This function only does something interesting for non-simple Components.
virtual
ComponentPrecomputedIndexes * PrecomputeIndexes (const MiscComputationInfo &misc_info, const std::vector< Index > &input_indexes, const std::vector< Index > &output_indexes, bool need_backprop) const
This function only returns non-NULL for non-simple Components (and may still return NULL for non-simple Compoennts).
Component ()
virtual ~Component ()
Private Member Functions
virtual void Update (const CuMatrixBase< BaseFloat > &in_value, const CuMatrixBase< BaseFloat > &out_deriv)
const
NaturalGradientRepeatedAffineComponent & operator= (const NaturalGradientRepeatedAffineComponent &other)
virtual void SetNaturalGradientConfigs ()
Private Attributes
OnlineNaturalGradient preconditioner_in_
Additional Inherited Members
Static Public Member Functions inherited from Component
static Component * ReadNew (std::istream &is, bool binary)
Read component from stream (works out its type). Dies on error.
static Component * NewComponentOfType (const std::string &type)
Returns a new Component of the given type e.g.
Protected Member Functions inherited from RepeatedAffineComponent
const RepeatedAffineComponent & operator= (const RepeatedAffineComponent &other)
Protected Member Functions inherited from UpdatableComponent
void InitLearningRatesFromConfig (ConfigLine *cfl)
void ReadUpdatableCommon (std::istream &is, bool binary)
void WriteUpdatableCommon (std::ostream &is, bool binary) const
Protected Attributes inherited from RepeatedAffineComponent
CuMatrix< BaseFloat > linear_params_
CuVector< BaseFloat > bias_params_
int32 num_repeats_
Protected Attributes inherited from UpdatableComponent
BaseFloat learning_rate_
learning rate (typically 0.0..0.01)
BaseFloat learning_rate_factor_
learning rate factor (normally 1.0, but can be set to another < value so that when < you call SetLearningRate(), that value will be scaled by this factor.
bool is_gradient_
True if this component is to be treated as a gradient rather than as parameters.
Detailed Description
Definition at line 459 of file nnet-simple-component.h.
Constructor & Destructor Documentation
NaturalGradientRepeatedAffineComponent () inline
Definition at line 462 of file nnet-simple-component.h.
Referenced by NaturalGradientRepeatedAffineComponent::Copy().
 { }
NaturalGradientRepeatedAffineComponent (const NaturalGradientRepeatedAffineComponent & other) explicit
Definition at line 1252 of file nnet-simple-component.cc.
                                                         :
     RepeatedAffineComponent(other),
     preconditioner_in_(other.preconditioner_in_) { }
Member Function Documentation
Component * Copy () const virtual
Copies component (deep copy).
Reimplemented from RepeatedAffineComponent.
Definition at line 1258 of file nnet-simple-component.cc.
References NaturalGradientRepeatedAffineComponent::NaturalGradientRepeatedAffineComponent().
{
   return new NaturalGradientRepeatedAffineComponent(*this);
 }
const NaturalGradientRepeatedAffineComponent& operator= (const NaturalGradientRepeatedAffineComponent & other) private
void SetNaturalGradientConfigs () private virtual
Reimplemented from RepeatedAffineComponent.
Definition at line 1241 of file nnet-simple-component.cc.
References RepeatedAffineComponent::linear_params_, CuMatrixBase< Real >::NumCols(), NaturalGradientRepeatedAffineComponent::preconditioner_in_, OnlineNaturalGradient::SetRank(), and OnlineNaturalGradient::SetUpdatePeriod().
{
   int32 rank_in = 40;
   int32 input_dim = linear_params_.NumCols();
   if (rank_in > input_dim / 2)
     rank_in = input_dim / 2;
   if (rank_in < 1)
     rank_in = 1;
   preconditioner_in_.SetRank(rank_in);
   preconditioner_in_.SetUpdatePeriod(4);
 }
virtual std::string Type () const inline virtual
Returns a string such as "SigmoidComponent", describing the type of the object.
Reimplemented from RepeatedAffineComponent.
Definition at line 465 of file nnet-simple-component.h.
{
     return "NaturalGradientRepeatedAffineComponent";
   }
void Update (const CuMatrixBase< BaseFloat > & in_value, const CuMatrixBase< BaseFloat > & out_deriv) private virtual
Reimplemented from RepeatedAffineComponent.
Definition at line 1262 of file nnet-simple-component.cc.
References CuMatrixBase< Real >::AddMat(), CuVectorBase< Real >::AddRowSumMat(), CuVectorBase< Real >::AddVec(), RepeatedAffineComponent::bias_params_, CuMatrixBase< Real >::ColRange(), CuVectorBase< Real >::CopyColFromMat(), CuMatrixBase< Real >::CopyColFromVec(), kaldi::DeletePointers(), CuVectorBase< Real >::Dim(), rnnlm::i, UpdatableComponent::is_gradient_, kaldi::kNoTrans, kaldi::kTrans, UpdatableComponent::learning_rate_, RepeatedAffineComponent::linear_params_, RepeatedAffineComponent::num_repeats_, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), OnlineNaturalGradient::PreconditionDirections(), NaturalGradientRepeatedAffineComponent::preconditioner_in_, and CuMatrixBase< Real >::Row().
{
   int32 block_rows = linear_params_.NumRows();
   int32 block_cols = linear_params_.NumCols();
   std::vector<CuSubMatrix<BaseFloat> *> in_value_batch,
       out_deriv_batch, linear_params_deriv_batch;
   // params_deriv_repeated as as linear_params_deriv_repeated below,
   // but with an extra column which will come in useful when dealing with
   // the biases.
   CuMatrix<BaseFloat> params_deriv_repeated(
       block_rows * num_repeats_, block_cols + 1);
   CuSubMatrix<BaseFloat> linear_params_deriv_repeated(
       params_deriv_repeated, 0, params_deriv_repeated.NumRows(),
       0, block_cols);
   // params_deriv will becomes the derivative w.r.t the parameters,
   // with the derivative w.r.t. the bias as the last column.
   CuSubMatrix<BaseFloat> params_deriv(params_deriv_repeated, 0, block_rows,
                                       0, block_cols + 1);
   for (int i = 0; i < num_repeats_; i++) {
     in_value_batch.push_back(new CuSubMatrix<BaseFloat>(in_value.ColRange(
         i * block_cols, block_cols)));
     out_deriv_batch.push_back(new CuSubMatrix<BaseFloat>(out_deriv.ColRange(
         i * block_rows, block_rows)));
     linear_params_deriv_batch.push_back(
         new CuSubMatrix<BaseFloat>(linear_params_deriv_repeated.RowRange(
             i * block_rows, block_rows)));
   }
   AddMatMatBatched<BaseFloat>(1.0,
                               linear_params_deriv_batch,
                               out_deriv_batch, kTrans,
                               in_value_batch, kNoTrans, 0.0);
   { // sum up the repeated blocks of pieces of derivative (from
     // linear_params_deriv_repeated) into the first block
     // of linear_params_deriv_repeated.  We do this without
     // the use of loops by means of a little fakery, viewing
     // linear_params_deriv_repeated as a matrix with a larger stride than it
     // really has to sum up its rows.  This may generate some spurious
     // valgrind/memcheck warnings due to accessing the memory in between rows
     // of a matrix that has been allocated using cudaMallocPitch.
     // view linear_params_deriv_repeated as a matrix where each row
     // corresponds to one repeat.
     // usage of linear_params_deriv_repeated.Stride() instead of
     // linear_params_.Stride() is important here. CUDA does not guarantee
     // that two matrices of the same number of columns
     // (linear_params_deriv_repeated and linear_params_) have the same stride.
     // i.e., we cannot reliably do:
     // KALDI_ASSERT(linear_params_.Stride() == linear_params_deriv_repeated.Stride())
     int32 size_as_vector =
         (linear_params_.NumRows() - 1) * linear_params_deriv_repeated.Stride() +
         linear_params_.NumCols(),
         stride_as_matrix = linear_params_.NumRows() * linear_params_deriv_repeated.Stride();
     CuSubMatrix<BaseFloat> linear_params_deriv_repeated_as_mat(
         linear_params_deriv_repeated.Data(), num_repeats_,
         size_as_vector, stride_as_matrix);
     // add all remaining rows to the first row of
     // linear_params_deriv_repeated_as_mat [i.e. add all but the 1st block to the 1st block]
     if (num_repeats_ > 1)
       linear_params_deriv_repeated_as_mat.Row(0).AddRowSumMat(
           1.0, linear_params_deriv_repeated_as_mat.RowRange(1,
                                                             num_repeats_ - 1));
   }
   CuVector<BaseFloat> repeated_bias_deriv(
       num_repeats_ * bias_params_.Dim());
   { // deal with the derivative w.r.t. the bias.
     repeated_bias_deriv.AddRowSumMat(1.0, out_deriv, 0.0);
     CuSubMatrix<BaseFloat> bias_deriv_mat(repeated_bias_deriv.Data(),
                                           num_repeats_, bias_params_.Dim(), // num rows, num cols
                                           bias_params_.Dim()); // stride
     // Add all but the first row of bias_deriv_mat, to the first row.
     if (num_repeats_ > 1)
       bias_deriv_mat.Row(0).AddRowSumMat(
           1.0, bias_deriv_mat.RowRange(1, num_repeats_ - 1));
     // copy the summed bias-derivative to the last column of the matrix
     // 'params_deriv'.
     params_deriv.CopyColFromVec(bias_deriv_mat.Row(0), block_cols);
   }
   BaseFloat scale = 1.0;
   if (!is_gradient_) {
     // Only apply the preconditioning/natural-gradient if we're not computing
     // the exact gradient.
     preconditioner_in_.PreconditionDirections(&params_deriv, NULL, &scale);
   }
   linear_params_.AddMat(learning_rate_ * scale,
                         params_deriv.ColRange(0, block_cols));
   // there is no function to add a column of a matrix to a vector, so use a
   // temporary vector [re-using some memory we already allocated.]
   CuSubVector<BaseFloat> bias_direction(repeated_bias_deriv.Data(),
                                         bias_params_.Dim());
   bias_direction.CopyColFromMat(params_deriv, block_cols);
   bias_params_.AddVec(learning_rate_ * scale, bias_direction);
   DeletePointers(&in_value_batch);
   DeletePointers(&out_deriv_batch);
   DeletePointers(&linear_params_deriv_batch);
 }
Member Data Documentation
OnlineNaturalGradient preconditioner_in_ private
Definition at line 492 of file nnet-simple-component.h.
Referenced by NaturalGradientRepeatedAffineComponent::SetNaturalGradientConfigs(), and NaturalGradientRepeatedAffineComponent::Update().
The documentation for this class was generated from the following files:
nnet3/nnet-simple-component.h
nnet3/nnet-simple-component.cc