Kaldi: CuMatrix< Real > Class Template Reference
CuMatrix< Real > Class Template Reference
This class represents a matrix that's stored on the GPU if we have one, and in memory if not.
#include <matrix-common.h>
Public Member Functions
CuMatrix ()
CuMatrix (MatrixIndexT rows, MatrixIndexT cols, MatrixResizeType resize_type=kSetZero)
Constructor with memory initialisation.
CuMatrix (const CuMatrix< Real > &other, MatrixTransposeType trans=kNoTrans)
CuMatrix (const CuBlockMatrix< Real > &other, MatrixTransposeType trans=kNoTrans)
CuMatrix (const CuMatrixBase< Real > &other, MatrixTransposeType trans=kNoTrans)
template<typename OtherReal >
CuMatrix (const MatrixBase< OtherReal > &other, MatrixTransposeType trans=kNoTrans)
CuMatrix (const CuSpMatrix< Real > &M)
Copy constructor taking SpMatrix...
template<typename OtherReal >
CuMatrix (const CuTpMatrix< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy constructor taking TpMatrix...
template<typename OtherReal >
CuMatrix (const CuMatrixBase< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
Copy constructor: as above, but from another type.
CuMatrix< Real > & operator= (const CuMatrixBase< Real > &other)
CuMatrix< Real > & operator= (const CuMatrix< Real > &other)
CuMatrix< Real > & operator= (const MatrixBase< Real > &other)
void Transpose ()
void Resize (MatrixIndexT rows, MatrixIndexT cols, MatrixResizeType resize_type=kSetZero)
Allocate the memory.
void Swap (Matrix< Real > *mat)
void Swap (CuMatrix< Real > *mat)
template<typename OtherReal >
void Swap (CuMatrix< OtherReal > *mat)
void Read (std::istream &is, bool binary)
I/O functions.
~CuMatrix ()
Destructor.
const Matrix< Real > & Mat () const
Matrix< Real > & Mat ()
void CompObjfAndDeriv (const std::vector< MatrixElement< Real > > &elements, const CuMatrix< Real > &A, Real *tot_objf, Real *tot_weight)
Here, A is interpreted as a matrix of probabilities, and "elements" as a list of posteriors (possibly zero-one), and "*this" as a matrix of derivatives w.r.t.
Public Member Functions inherited from CuMatrixBase< Real >
void CopyCols (const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indexes)
Copies column r from column indexes[r] of src.
void AddCols (const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indices)
Add column indices[r] of src to column r.
void CopyRows (const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indexes)
Copies row r from row indexes[r] of src.
void CopyRows (const CuArray< const Real * > &src)
Copies row r of this matrix from an array of floats at the location given by src[r], where src[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (the point is: the data it points to should be on the GPU if we're using a GPU, and on a CPU otherwise).
void CopyToRows (const CuArray< Real * > &dst) const
For each row r of this matrix, copies it to the array of floats at the location given by dst[r], where dst[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (i.e.
void AddRows (Real alpha, const CuMatrixBase< Real > &src, const CuArray< MatrixIndexT > &indexes)
Does for each row r, this.Row(r) += alpha * src.row(indexes[r]).
void AddRows (Real alpha, const CuArray< const Real * > &src)
Does for each row r, this.Row(r) += alpha * src[r], treating src[r] as the beginning of a region of memory representing a vector of floats, of the same length as this.NumCols().
void AddToRows (Real alpha, const CuArray< Real * > &dst) const
For each row r of this matrix, adds it (times alpha) to the array of floats at the location given by dst[r], where dst[r] is assumed to be obtained from the RowData() function of another CuMatrix, or from CuVector::Data() (i.e.
void SumColumnRanges (const CuMatrixBase< Real > &src, const CuArray< Int32Pair > &indexes)
For each row r of this and for each column c, sets (*this)(r, c) to the sum src(r, j), where j ranges from indexes[c].first through indexes[c].second - 1.
void AddRowRanges (const CuMatrixBase< Real > &src, const CuArray< Int32Pair > &indexes)
For each row r of this and for each column c, do (*this)(r, c) += src(j, c), where j ranges from indexes[r].first through indexes[r].second - 1.
void AddToDiag (Real value)
Adds "value" to the diagonal elements of the matrix.
MatrixIndexT NumRows () const
Dimensions.
MatrixIndexT NumCols () const
MatrixIndexT Stride () const
::MatrixDim Dim () const
Real FrobeniusNorm () const
bool IsUnit (Real tol=0.001) const
bool ApproxEqual (const CuMatrixBase< Real > &other, float tol=0.01) const
True if ((*this)-other).FrobeniusNorm() <= tol * this->FrobeniusNorm()
MatrixIndexT SizeInBytes () const
Get size of matrix in bytes.
template<typename OtherReal >
void CopyFromMat (const MatrixBase< OtherReal > &src, MatrixTransposeType trans=kNoTrans)
void CopyFromGeneralMat (const GeneralMatrix &src, MatrixTransposeType trans=kNoTrans)
void CopyFromMat (const MatrixBase< Real > &src, MatrixTransposeType trans=kNoTrans)
void CopyFromSp (const CuSpMatrix< Real > &M)
template<typename OtherReal >
void CopyFromTp (const CuTpMatrix< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
template<typename OtherReal >
void CopyFromMat (const CuMatrixBase< OtherReal > &M, MatrixTransposeType trans=kNoTrans)
template<typename OtherReal >
void CopyToMat (MatrixBase< OtherReal > *dst, MatrixTransposeType trans=kNoTrans) const
void CopyRowsFromVec (const CuVectorBase< Real > &v)
This function has two modes of operation.
void CopyRowsFromVec (const VectorBase< Real > &v)
Version of CopyRowsFromVec() that takes a CPU-based vector.
void CopyColFromVec (const CuVectorBase< Real > &v, const MatrixIndexT col)
Copy vector into specific column of matrix.
void Sigmoid (const CuMatrixBase< Real > &src)
Set each element to the sigmoid of the corresponding element of "src": element by element, x = 1 / (1 + exp(-x))
void SoftHinge (const CuMatrixBase< Real > &src)
Apply the function y = log(1 + exp(x)), to each element.
void GroupPnorm (const CuMatrixBase< Real > &src, Real pow)
Apply the function y(i) = (sum_{j = i*G}^{(i+1)*G-1} x_j ^ (power)) ^ (1 / p) where G = x.NumCols() / y.NumCols() must be an integer.
void GroupPnormDeriv (const CuMatrixBase< Real > &input, const CuMatrixBase< Real > &output, Real power)
Calculate derivatives for the GroupPnorm function above...
void GroupMax (const CuMatrixBase< Real > &src)
Apply the function y(i) = (max_{j = i*G}^{(i+1)*G-1} x_j where G = x.NumCols() / y.NumCols() must be an integer.
void GroupMaxDeriv (const CuMatrixBase< Real > &input, const CuMatrixBase< Real > &output)
Calculate derivatives for the GroupMax function above, where "input" is the input to the GroupMax function above (i.e.
void Tanh (const CuMatrixBase< Real > &src)
Compute the hyperbolic tangent (tanh) function; element by element, *this = tanh(src).
void DiffSigmoid (const CuMatrixBase< Real > &value, const CuMatrixBase< Real > &diff)
Differentiate backward through the sigmoid function.
void DiffTanh (const CuMatrixBase< Real > &value, const CuMatrixBase< Real > &diff)
Differentiate backward through the tanh function.
void DiffXent (const CuArray< int32 > &tgt, CuVector< Real > *log_post_tgt)
Differentiate the block [softmax+cross-entropy] : dE/da = posterior_mat - target_mat, 'E' is error function, 'a' is activation on softmax input.
void Cholesky (CuMatrixBase< Real > *inv_cholesky=NULL)
This function does sets *this to the Cholesky factor of *this (i.e.
void SymInvertPosDef ()
Inversion for positive definite symmetric matrices.
void ApplyPow (Real power)
Apply power to the absolute value of each element.
void ApplyPowAbs (Real power, bool include_sign=false)
void ApplyHeaviside ()
For each element, sets x = (x > 0 ? 1.0 : 0.0)
void ApplyFloor (Real floor_val)
void ApplyCeiling (Real ceiling_val)
void ApplyExp ()
void ApplySoftMaxPerRow (const CuMatrixBase< Real > &src)
Softmax nonlinearity Y = Softmax(X) : Yij = e^Xij / sum_k(e^Xik), done to each row for each row, the max value is first subtracted for good numerical stability.
void ApplyLogSoftMaxPerRow (const CuMatrixBase< Real > &src)
LogSoftmax nonlinearity Y = LogSoftmax(X) : Yij = Xij - log(sum_k(e^Xik)), done to each row for each row, the max value is first subtracted for good numerical stability.
void FindRowMaxId (CuArray< int32 > *id) const
Find the id of the maximal element for each row.
void SetZero ()
Math operations, some calling kernels.
void Set (Real value)
void Add (Real value)
void SetZeroAboveDiag ()
Zeroes all elements for which col > row.
void Scale (Real value)
void ApplyLog ()
void MulElements (const CuMatrixBase< Real > &A)
Multiply two matrices elementwise: C = C .* A.
void DivElements (const CuMatrixBase< Real > &A)
Divide two matrices elementwise: C = A ./ A.
void Max (const CuMatrixBase< Real > &A)
Do, elementwise, *this = max(*this, A).
void MulColsVec (const CuVectorBase< Real > &scale)
scale i'th column by scale[i]
void MulRowsVec (const CuVectorBase< Real > &scale)
scale i'th row by scale[i]
void MulRowsGroupMat (const CuMatrixBase< Real > &src)
divide each row into src.NumCols() groups, and then scale i'th row's jth group of elements by src[i, j].
void DivRowsVec (const CuVectorBase< Real > &div)
divide i'th row by scale[i]
void InvertElements ()
invert the matrix by elements.
void AddMat (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType trans=kNoTrans)
*this += alpha * A
void AddMatBlocks (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType trans=kNoTrans)
if A.NumRows() is multiple of (*this)->NumRows and A.NumCols() is multiple of (*this)->NumCols divide A into blocks of the same size as (*this) and add them to *this (times alpha)
void AddVecToCols (Real alpha, const CuVectorBase< Real > &col, Real beta=1.0)
(for each column c of *this), c = alpha * col + beta * c
void AddVecToRows (Real alpha, const CuVectorBase< Real > &row, Real beta=1.0)
(for each row r of *this), r = alpha * row + beta * r
void AddMatMat (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuMatrixBase< Real > &B, MatrixTransposeType transB, Real beta)
C = alpha * A(^T)*B(^T) + beta * C.
void AddVecVec (Real alpha, const CuVectorBase< Real > &x, const CuVectorBase< Real > &y)
A = alpha * x * y^T + A .
void AddMatMatDivMat (const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, const CuMatrixBase< Real > &C)
*this = a * b / c (by element; when c = 0, *this = a)
void SymAddMat2 (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transA, Real beta)
*this = beta * *this + alpha * M M^T, for symmetric matrices.
void AddMatBlock (Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuBlockMatrix< Real > &B, MatrixTransposeType transB, Real beta)
This function is like AddMatMat but for where the second argument is of type CuBlockMatrix (a block-diagonal matrix of blocks).
void AddDiagVecMat (const Real alpha, const CuVectorBase< Real > &v, const CuMatrixBase< Real > &M, MatrixTransposeType transM, Real beta=1.0)
*this = beta * *this + alpha * diag(v) * M [or M^T].
void AddMatDiagVec (const Real alpha, const CuMatrixBase< Real > &M, MatrixTransposeType transM, CuVectorBase< Real > &v, Real beta=1.0)
void AddMatMatElements (const Real alpha, const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, const Real beta)
*this = beta * *this + alpha * A .* B (.* element by element multiplication)
void AddVecMatPointMulVec (const Real alpha, const CuMatrixBase< Real > &A, const CuMatrixBase< Real > &B, const Real beta, MatrixIndexT batch_index)
sc function element of vector multiply rows vector of matrix
void AddMatSp (const Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuSpMatrix< Real > &B, const Real beta)
this <– beta*this + alpha*A*B
void AddSpMat (const Real alpha, const CuSpMatrix< Real > &A, const CuMatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*SpA*B
void AddTpMat (const Real alpha, const CuTpMatrix< Real > &A, MatrixTransposeType transA, const CuMatrixBase< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void AddMatTp (const Real alpha, const CuMatrixBase< Real > &A, MatrixTransposeType transA, const CuTpMatrix< Real > &B, MatrixTransposeType transB, const Real beta)
this <– beta*this + alpha*A*B.
void CopyFromBlock (const CuBlockMatrix< Real > &B, MatrixTransposeType trans=kNoTrans)
void CopyLowerToUpper ()
void CopyUpperToLower ()
CuSubMatrix< Real > Range (const MatrixIndexT row_offset, const MatrixIndexT num_rows, const MatrixIndexT col_offset, const MatrixIndexT num_cols) const
CuSubMatrix< Real > RowRange (const MatrixIndexT row_offset, const MatrixIndexT num_rows) const
CuSubMatrix< Real > ColRange (const MatrixIndexT col_offset, const MatrixIndexT num_cols) const
const CuSubVector< Real > Row (MatrixIndexT i) const
CuSubVector< Real > Row (MatrixIndexT i)
CuValue< Real > operator() (MatrixIndexT r, MatrixIndexT c)
Real operator() (MatrixIndexT r, MatrixIndexT c) const
Real Sum () const
Real Max () const
proxy to MatrixBase::Max(), cuda not used
Real Min () const
proxy to MatrixBase::Min(), cuda not used
Real Trace (bool check_square=true) const
Return the trace. If check_square = true, will crash if matrix is not square.
void SetRandn ()
void SetRandUniform ()
void Write (std::ostream &os, bool binary) const
void AddElements (Real alpha, const std::vector< MatrixElement< Real > > &input)
void AddElements (Real alpha, const CuArray< Int32Pair > &indexes, const Real *input)
void Lookup (const std::vector< Int32Pair > &indexes, Real *output) const
void Lookup (const CuArray< Int32Pair > &indexes, Real *output) const
void EqualElementMask (const CuMatrixBase< Real > &mat, CuMatrix< Real > *mask) const
const Real * RowData (MatrixIndexT r) const
Get raw row pointer (const).
Real * RowData (MatrixIndexT r)
Get raw row pointer.
const Real * Data () const
Return data pointer (const).
Real * Data ()
Return data pointer.
const MatrixBase< Real > & Mat () const
MatrixBase< Real > & Mat ()
Private Member Functions
void Destroy ()
Additional Inherited Members
Protected Member Functions inherited from CuMatrixBase< Real >
CuMatrixBase ()
CuMatrixBase (Real *data, MatrixIndexT num_rows, MatrixIndexT num_cols, MatrixIndexT stride)
This constructor takes the #rows, #cols and stride; it's called from the constructor of CuSubMatrix.
Protected Attributes inherited from CuMatrixBase< Real >
Real * data_
GPU data pointer (or regular matrix data pointer,.
MatrixIndexT num_cols_
MatrixIndexT num_rows_
MatrixIndexT stride_
Detailed Description
template<typename Real>
class kaldi::CuMatrix< Real >
This class represents a matrix that's stored on the GPU if we have one, and in memory if not.
Definition at line 63 of file matrix-common.h.
Constructor & Destructor Documentation
CuMatrix () inline
Definition at line 626 of file cu-matrix.h.
 { }
CuMatrix (MatrixIndexT rows, MatrixIndexT cols, MatrixResizeType resize_type = kSetZero) inline
Constructor with memory initialisation.
Definition at line 629 of file cu-matrix.h.
{
     Resize(rows, cols, resize_type);
   }
CuMatrix (const CuMatrix< Real > & other, MatrixTransposeType trans = kNoTrans)
Definition at line 368 of file cu-matrix.cc.
References kaldi::kNoTrans, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   if (trans == kNoTrans)
     this->Resize(other.NumRows(), other.NumCols(), kUndefined);
   else
     this->Resize(other.NumCols(), other.NumRows(), kUndefined);
   this->CopyFromMat(other, trans);
 }
CuMatrix (const CuBlockMatrix< Real > & other, MatrixTransposeType trans = kNoTrans) explicit
Definition at line 195 of file cu-matrix.cc.
References CuMatrixBase< Real >::CopyFromBlock(), kaldi::kNoTrans, kaldi::kTrans, kaldi::kUndefined, CuBlockMatrix< Real >::NumCols(), CuBlockMatrix< Real >::NumRows(), and CuMatrix< Real >::Resize().
                                                     : CuMatrixBase<Real>() {
   if (trans == kNoTrans) {
     Resize(B.NumRows(), B.NumCols(), kUndefined);
     this->CopyFromBlock(B);
   } else {
     Resize(B.NumCols(), B.NumRows(), kUndefined);
     this->CopyFromBlock(B, kTrans);
   }
 }
CuMatrix (const CuMatrixBase< Real > & other, MatrixTransposeType trans = kNoTrans) explicit
Definition at line 377 of file cu-matrix.cc.
References kaldi::kNoTrans, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), and CuMatrixBase< Real >::NumRows().
{
   if (trans == kNoTrans)
     this->Resize(other.NumRows(), other.NumCols(), kUndefined);
   else
     this->Resize(other.NumCols(), other.NumRows(), kUndefined);
   this->CopyFromMat(other, trans);
 }
CuMatrix (const MatrixBase< OtherReal > & other, MatrixTransposeType trans = kNoTrans) explicit
Definition at line 388 of file cu-matrix.cc.
References kaldi::kNoTrans, kaldi::kUndefined, MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
{
   if (trans == kNoTrans)
     this->Resize(other.NumRows(), other.NumCols(), kUndefined);
   else
     this->Resize(other.NumCols(), other.NumRows(), kUndefined);
   this->CopyFromMat(other, trans);
 }
CuMatrix (const CuSpMatrix< Real > & M) inline explicit
Copy constructor taking SpMatrix...
Definition at line 650 of file cu-matrix.h.
                                                : CuMatrixBase<Real>() {
     Resize(M.NumRows(), M.NumRows(), kUndefined);
     this->CopyFromSp(M);
   }
CuMatrix (const CuTpMatrix< OtherReal > & M, MatrixTransposeType trans = kNoTrans) inline explicit
Copy constructor taking TpMatrix...
Definition at line 657 of file cu-matrix.h.
                                                           : CuMatrixBase<Real>() {
     Resize(M.NumCols(), M.NumRows(), kUndefined);
     this->CopyFromTp(M, trans);
   }
CuMatrix (const CuMatrixBase< OtherReal > & M, MatrixTransposeType trans = kNoTrans) explicit
Copy constructor: as above, but from another type.
Copy constructor from another type.
Definition at line 2577 of file cu-matrix.cc.
References CuMatrixBase< Real >::CopyFromMat(), kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
                                                     : CuMatrixBase<Real>() {
   if (trans == kNoTrans) {
     Resize(M.NumRows(), M.NumCols());
     this->CopyFromMat(M);
   } else {
     Resize(M.NumCols(), M.NumRows());
     this->CopyFromMat(M, kTrans);
   }
 }
~CuMatrix () inline
Destructor.
Definition at line 702 of file cu-matrix.h.
 { Destroy(); }
Member Function Documentation
void CompObjfAndDeriv (const std::vector< MatrixElement< Real > > & elements, const CuMatrix< Real > & A, Real * tot_objf, Real * tot_weight)
Here, A is interpreted as a matrix of probabilities, and "elements" as a list of posteriors (possibly zero-one), and "*this" as a matrix of derivatives w.r.t.
the log-probs. This function does: for each element { row, column, weight } indexed i in the vector "elements", let x(i) = A(row(i), column(i)); then it does (*this)(row(i), column(i)) += weight(i) / x(i), and *tot_objf = weight(i) * log(x(i)), and *tot_weight = weight(i) Preconditions: A must be strictly positive, and no (row, column) pair may be repeated within "elements"
Definition at line 1352 of file cu-matrix.cc.
References CU1DBLOCK, CuVectorBase< Real >::Data(), CuMatrixBase< Real >::Data(), CuMatrixBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, KALDI_WARN, kaldi::kUndefined, and kaldi::Log().
Referenced by NnetUpdater::ComputeObjfAndDeriv(), NnetDiscriminativeUpdater::LatticeComputations(), kaldi::TestCuMatrixCompObjfAndDeriv(), and kaldi::UnitTestCuMatrixObjfDeriv().
{
   { // check the input.
     typedef typename std::vector<MatrixElement<Real> >::const_iterator Iter;
     MatrixIndexT num_rows = this->num_rows_, num_cols = this->num_cols_;
     for (Iter iter = sv_labels.begin(); iter != sv_labels.end(); ++iter) {
       KALDI_ASSERT(iter->row < num_rows && iter->row >= 0 &&
                    iter->column < num_cols && iter->column >= 0);
     }
   }
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (sv_labels.empty()) {
       KALDI_WARN << "Empty supervision labels";
       *tot_objf = 0.0;
       *tot_weight = 0.0;
       return;
     }
     void *addr = CuDevice::Instantiate().Malloc(sv_labels.size() * sizeof(MatrixElement<Real>));
     CU_SAFE_CALL(cudaMemcpy(addr, sv_labels.data(), sv_labels.size() * sizeof(MatrixElement<Real>), cudaMemcpyHostToDevice));
     Timer tim;
     CuVector<Real> tmp(2, kUndefined);
     int dimBlock(CU1DBLOCK);
     int dimGrid = 1; // only 1 block here. we have loops in each thread.
     cuda_comp_obj_deriv(dimGrid, dimBlock, (MatrixElement<Real>*)addr,
                         sv_labels.size(), output.Data(), output.Dim(),
                         this->Data(), this->Dim(), tmp.Data());
     Vector<Real> tmp_cpu(tmp);
     *tot_objf = tmp_cpu(0);
     *tot_weight = tmp_cpu(1);
     CuDevice::Instantiate().Free(addr);
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     *tot_objf = 0.0;
     *tot_weight = 0.0;
     for(int32 i = 0; i<sv_labels.size(); i++) {
       int32 m = sv_labels[i].row, label = sv_labels[i].column;
       Real weight = sv_labels[i].weight;
       //KALDI_ASSERT(label >= 0 && label < nnet_.OutputDim());
       Real this_prob = output(m, label);
       KALDI_ASSERT(this_prob >= 0.99e-20); // we floored to 1.0e-20 in SoftmaxLayer.
       *tot_objf += weight * Log(this_prob);
       *tot_weight += weight;
       (*this)(m, label) += weight / this_prob;
     }
   }
 }
void Destroy () private
Definition at line 94 of file cu-matrix.cc.
References Timer::Elapsed().
Referenced by CuMatrix< BaseFloat >::~CuMatrix().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->data_ != NULL) {
       Timer tim;
       CuDevice::Instantiate().Free(this->data_);
       CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
     }
   } else
 #endif
   {
     if (this->data_ != NULL) KALDI_MEMALIGN_FREE(this->data_);
   }
   this->data_ = NULL;
   this->num_rows_ = 0;
   this->num_cols_ = 0;
   this->stride_ = 0;
 }
const Matrix<Real>& Mat () const inline
Definition at line 704 of file cu-matrix.h.
Referenced by CuRand< Real >::BinarizeProbs(), and CuVectorBase< Real >::CopyDiagFromMat().
{
     return *(reinterpret_cast<const Matrix<Real>* >(this));
   }
Matrix<Real>& Mat () inline
Definition at line 707 of file cu-matrix.h.
{
     return *(reinterpret_cast<Matrix<Real>* >(this));
   }
CuMatrix<Real>& operator= (const CuMatrixBase< Real > & other) inline
Definition at line 668 of file cu-matrix.h.
{
     this->Resize(other.NumRows(), other.NumCols(), kUndefined);
     this->CopyFromMat(other);
     return *this;
   }
CuMatrix<Real>& operator= (const CuMatrix< Real > & other) inline
Definition at line 674 of file cu-matrix.h.
{
     this->Resize(other.NumRows(), other.NumCols(), kUndefined);
     this->CopyFromMat(other);
     return *this;
   }
CuMatrix<Real>& operator= (const MatrixBase< Real > & other) inline
Definition at line 680 of file cu-matrix.h.
{
     this->Resize(other.NumRows(), other.NumCols(), kUndefined);
     this->CopyFromMat(other);
     return *this;
   }
void Read (std::istream & is, bool binary)
I/O functions.
Definition at line 454 of file cu-matrix.cc.
References Matrix< Real >::Read().
Referenced by LinearTransform::InitData(), FixedAffineComponent::InitFromConfig(), FixedLinearComponent::InitFromString(), FixedAffineComponent::InitFromString(), RepeatedAffineComponent::Read(), NaturalGradientAffineComponent::Read(), AffineComponent::Read(), AffineComponentPreconditioned::Read(), AffineComponentPreconditionedOnline::Read(), BlockAffineComponent::Read(), BlockAffineComponentPreconditioned::Read(), ConvolutionComponent::Read(), FixedLinearComponent::Read(), FixedAffineComponent::Read(), Convolutional1dComponent::Read(), kaldi::nnet1::ReadCuMatrixFromString(), LinearTransform::ReadData(), AffineTransform::ReadData(), TCNProjectionComponent::ReadData(), TCNComponent::ReadData(), LstmProjectedStreams::ReadData(), ConvolutionalComponent::ReadData(), Convolutional2DComponent::ReadData(), BLstmProjectedStreams::ReadData(), Rbm::ReadData(), and kaldi::UnitTestCuMatrixIO().
{
   Matrix<Real> temp;
   temp.Read(is, binary);
   Destroy();
   Swap(&temp);
 }
void Resize (MatrixIndexT rows, MatrixIndexT cols, MatrixResizeType resize_type = kSetZero)
Allocate the memory.
Definition at line 48 of file cu-matrix.cc.
References Timer::Elapsed(), KALDI_ASSERT, kaldi::kSetZero, kaldi::kUndefined, and kaldi::nnet3::SetZero().
Referenced by NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), MatrixRandomizer::AddData(), MaxoutComponent::Backprop(), MaxpoolingComponent::Backprop(), PnormComponent::Backprop(), NormalizeComponent::Backprop(), SigmoidComponent::Backprop(), TanhComponent::Backprop(), PowerComponent::Backprop(), RectifiedLinearComponent::Backprop(), SoftHingeComponent::Backprop(), ScaleComponent::Backprop(), SoftmaxComponent::Backprop(), LogSoftmaxComponent::Backprop(), AffineComponent::Backprop(), SpliceComponent::Backprop(), SpliceMaxComponent::Backprop(), BlockAffineComponent::Backprop(), SumGroupComponent::Backprop(), PermuteComponent::Backprop(), DctComponent::Backprop(), FixedLinearComponent::Backprop(), FixedAffineComponent::Backprop(), DropoutComponent::Backprop(), Convolutional1dComponent::Backprop(), Component::Backpropagate(), LstmProjectedStreams::BackpropagateFnc(), BLstmProjectedStreams::BackpropagateFnc(), CuRand< Real >::BinarizeProbs(), AffineComponent::CollapseWithNext(), AffineComponent::CollapseWithPrevious(), NnetOnlineComputer::Compute(), DecodableAmNnetParallel::Compute(), NnetComputer::ComputeLastLayerDeriv(), NnetUpdater::ComputeObjfAndDeriv(), CuMatrix< BaseFloat >::CuMatrix(), CuMatrix< Real >::CuMatrix(), NnetDecodableBase::DoNnetComputation(), CuMatrixBase< Real >::EqualElementMask(), MultiTaskLoss::Eval(), Nnet::Feedforward(), NnetOnlineComputer::Flush(), NnetRescaler::FormatInput(), NnetComputer::GetOutputDestructive(), RepeatedAffineComponent::Init(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), BlockAffineComponent::Init(), DctComponent::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), LinearTransform::InitData(), LstmProjectedStreams::InitData(), BLstmProjectedStreams::InitData(), OnlineNaturalGradient::InitDefault(), OnlinePreconditioner::InitDefault(), NnetDiscriminativeUpdater::LatticeComputations(), main(), NnetComputer::NnetComputer(), NnetLogprobTask::operator()(), CuMatrix< BaseFloat >::operator=(), NnetOnlineComputer::Propagate(), Component::Propagate(), KlHmm::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), Dropout::PropagateFnc(), LstmProjectedStreams::PropagateFnc(), BLstmProjectedStreams::PropagateFnc(), Rbm::RbmUpdate(), LstmProjectedStreams::ReadData(), BLstmProjectedStreams::ReadData(), Rbm::Reconstruct(), LstmProjectedStreams::ResetLstmStreams(), NaturalGradientAffineComponent::Resize(), AffineComponent::Resize(), AffineComponentPreconditionedOnline::Resize(), Convolutional1dComponent::Resize(), kaldi::UnitTestCuSparseMatrixSwap(), kaldi::nnet3::UnitTestNnetInputDerivatives(), kaldi::nnet3::UnitTestNnetModelDerivatives(), TCNProjectionComponent::Update(), TCNComponent::Update(), ConvolutionalComponent::Update(), Convolutional2DComponent::Update(), NaturalGradientAffineComponent::Update(), AffineComponentPreconditioned::Update(), AffineComponentPreconditionedOnline::Update(), ConvolutionComponent::Update(), Convolutional1dComponent::Update(), MatrixRandomizer::Value(), and AffineComponent::Widen().
{
   // This code does not currently support the other resize_type options.
   KALDI_ASSERT(resize_type == kSetZero || resize_type == kUndefined);
   if (rows * cols == 0) KALDI_ASSERT(rows == 0 && cols == 0);
   if (this->num_rows_ == rows && this->num_cols_ == cols) {
     if (resize_type == kSetZero) this->SetZero();
     return;
   }
   if (this->num_rows_ != 0)
     this->Destroy();
   if (rows == 0) return;
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     Timer tim;
     MatrixIndexT row_bytes = cols * sizeof(Real);
     size_t pitch;
     this->data_ = static_cast<Real*>(CuDevice::Instantiate().MallocPitch(
         row_bytes, rows, &pitch));
     this->num_rows_ = rows;
     this->num_cols_ = cols;
     this->stride_ = pitch / sizeof(Real);
     if (resize_type == kSetZero) this->SetZero();
     CuDevice::Instantiate().AccuProfile("CuMatrix::Resize", tim.Elapsed());
   } else
 #endif
   { // Let the initializer of Matrix<Real> handle the allocation,
     // and then just do Swap which will switch the pointers.
     // This wastes a few instructions but is simple to code.
     Matrix<Real> mat(rows, cols, resize_type);
     this->Swap(&mat);
   }
 }
void Swap (Matrix< Real > * mat)
Definition at line 123 of file cu-matrix.cc.
References MatrixBase< Real >::data_, kaldi::kUndefined, MatrixBase< Real >::num_cols_, MatrixBase< Real >::num_rows_, Matrix< Real >::Resize(), MatrixBase< Real >::stride_, kaldi::swap(), and Matrix< Real >::Swap().
Referenced by NnetDiscriminativeUpdater::Backprop(), DecodableNnet2Online::ComputeForFrame(), kaldi::nnet3::ComputeObjectiveFunction(), GeneralMatrix::CopyToMat(), NnetDecodableBase::DoNnetComputation(), OnlineNaturalGradient::Init(), OnlinePreconditioner::Init(), main(), OnlineNaturalGradient::PreconditionDirectionsInternal(), OnlinePreconditioner::PreconditionDirectionsInternal(), NnetRescaler::Rescale(), Matrix< Real >::Swap(), kaldi::UnitTestSwapCu2Cu(), and kaldi::UnitTestSwapCu2M().
{
 #if HAVE_CUDA == 1
   if (CuDevice::Instantiate().Enabled()) {
     if (this->num_rows_ == 0) {
       if (mat->num_rows_ != 0) {
         // *this is empty, but mat is nonempty.
         this->Resize(mat->num_rows_, mat->num_cols_, kUndefined);
         this->CopyFromMat(*mat);
         mat->Resize(0, 0);
       }
       // else both are empty.
     } else { // *this is nonempty.
       if (mat->num_rows_ != 0) {
         // Both *this and *mat are nonempty.  Recurse to simpler cases.
         // this could be done more efficiently in the case where
         // the size does not change.
         Matrix<Real> temp;
         this->Swap(&temp); // now temp is full, *this is empty.
         mat->Swap(&temp); // now mat has data from *this, temp has
         // data from mat.
         this->Swap(&temp); // copy data in mat to *this, which is now empty.
       } else { // *this is full but *mat is empty.
         mat->Resize(this->num_rows_, this->num_cols_, kUndefined);
         this->CopyToMat(mat);
         this->Destroy();
       }
     }
   } else
 #endif
   {
     std::swap(mat->data_, this->data_);
     std::swap(mat->num_cols_, this->num_cols_);
     std::swap(mat->num_rows_, this->num_rows_);
     std::swap(mat->stride_, this->stride_);
   }
 }
void Swap (CuMatrix< Real > * mat)
Definition at line 114 of file cu-matrix.cc.
References CuMatrixBase< Real >::data_, CuMatrixBase< Real >::num_cols_, CuMatrixBase< Real >::num_rows_, CuMatrixBase< Real >::stride_, and kaldi::swap().
{
   std::swap(mat->data_, this->data_);
   std::swap(mat->num_cols_, this->num_cols_);
   std::swap(mat->num_rows_, this->num_rows_);
   std::swap(mat->stride_, this->stride_);
 }
void Swap (CuMatrix< OtherReal > * mat)
void Transpose ()
Definition at line 2599 of file cu-matrix.cc.
References CU2DBLOCK, Timer::Elapsed(), and kaldi::kTrans.
Referenced by kaldi::UnitTestCuMatrixAddDiagVecMat(), kaldi::UnitTestCuMatrixSymAddMat2(), kaldi::UnitTestCuMatrixSymInvertPosDef(), and kaldi::UnitTestCuMatrixTranspose().
{
   if (this->num_rows_ == 0)
     return;
 #if HAVE_CUDA == 1
   if (this->num_rows_ == this->num_cols_ && CuDevice::Instantiate().Enabled()) {
     Timer tim;
     dim3 dimBlock(CU2DBLOCK, CU2DBLOCK);
     // (x,y) indices will be (row of *this, col of *this)
     dim3 dimGrid(n_blocks(this->num_rows_, CU2DBLOCK),
                  n_blocks(this->num_cols_, CU2DBLOCK));
     cuda_transpose_matrix(dimGrid, dimBlock, this->data_, this->Dim());
     CU_SAFE_CALL(cudaGetLastError());
     CuDevice::Instantiate().AccuProfile(__func__, tim.Elapsed());
   } else
 #endif
   {
     CuMatrix<Real> tmp(*this, kTrans);
     *this = tmp;
   }
 }
The documentation for this class was generated from the following files:
matrix/matrix-common.h
cudamatrix/cu-matrix.h
cudamatrix/cu-matrix.cc