Kaldi: tree/context-dep-test.cc File Reference
context-dep-test.cc File Reference
#include "tree/context-dep.h"
#include "tree/clusterable-classes.h"
#include "util/kaldi-io.h"
Namespaces
kaldi
Functions
void TestContextDep ()
void TestMonophoneContextDependency ()
void TestGenRandContextDependency ()
int main ()
Function Documentation
int main ()
Definition at line 132 of file context-dep-test.cc.
References rnnlm::i, kaldi::TestContextDep(), kaldi::TestGenRandContextDependency(), and kaldi::TestMonophoneContextDependency().
            {
   for (size_t i = 0;i < 10;i++) {
     kaldi::TestContextDep();
     kaldi::TestGenRandContextDependency();  // Also tests I/O of ContextDependency
     kaldi::TestMonophoneContextDependency();
   }
 }