Kaldi: bin/copy-tree.cc File Reference
copy-tree.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/hmm-topology.h"
#include "tree/context-dep.h"
#include "tree/clusterable-classes.h"
#include "util/text-utils.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file copy-tree.cc.
References ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), and kaldi::WriteKaldiObject().
{
   using namespace kaldi;
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Copy decision tree (possibly changing binary/text format)\n"
         "Usage:  copy-tree [--binary=false] <tree-in> <tree-out>\n";
     bool binary = true;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string tree_in_filename = po.GetArg(1),
         tree_out_filename = po.GetArg(2);
     ContextDependency ctx_dep;
     ReadKaldiObject(tree_in_filename, &ctx_dep);
     WriteKaldiObject(ctx_dep, tree_out_filename, binary);
     KALDI_LOG << "Copied tree";
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }