Kaldi: bin/copy-vector.cc File Reference
copy-vector.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-vector.h"
#include "transform/transform-common.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file copy-vector.cc.
References kaldi::ClassifyRspecifier(), kaldi::ClassifyWspecifier(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, kaldi::kCopyData, SequentialTableReader< Holder >::Key(), kaldi::kNoRspecifier, kaldi::kNoWspecifier, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), Vector< Real >::Resize(), Output::Stream(), SequentialTableReader< Holder >::Value(), VectorBase< Real >::Write(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Copy vectors, or archives of vectors (e.g. transition-accs; speaker vectors)\n"
         "\n"
         "Usage: copy-vector [options] (<vector-in-rspecifier>|<vector-in-rxfilename>) (<vector-out-wspecifier>|<vector-out-wxfilename>)\n"
         " e.g.: copy-vector --binary=false 1.mat -\n"
         "   copy-vector ark:2.trans ark,t:-\n"
         "see also: dot-weights, append-vector-to-feats\n";
     bool binary = true;
     int32 change_dim = -1;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write in binary mode (only "
                 "relevant if output is a wxfilename)");
     po.Register("change_dim", &change_dim,
                 "Use this option to truncate or zero-pad the vectors.");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string vector_in_fn = po.GetArg(1),
         vector_out_fn = po.GetArg(2);
     // all these "fn"'s are either rspecifiers or filenames.
     bool in_is_rspecifier =
         (ClassifyRspecifier(vector_in_fn, NULL, NULL)
          != kNoRspecifier),
         out_is_wspecifier =
         (ClassifyWspecifier(vector_out_fn, NULL, NULL, NULL)
          != kNoWspecifier);
     if (in_is_rspecifier != out_is_wspecifier)
       KALDI_ERR << "Cannot mix archives with regular files (copying vectors)";
     if (!in_is_rspecifier) {
       Vector<BaseFloat> vec;
       ReadKaldiObject(vector_in_fn, &vec);
       Output ko(vector_out_fn, binary);
       if (change_dim >= 0) vec.Resize(change_dim, kCopyData);
       vec.Write(ko.Stream(), binary);
       KALDI_LOG << "Copied vector to " << vector_out_fn;
       return 0;
     } else {
       int num_done = 0;
       BaseFloatVectorWriter writer(vector_out_fn);
       SequentialBaseFloatVectorReader reader(vector_in_fn);
       if (change_dim < 0) {
         for (; !reader.Done(); reader.Next(), num_done++)
           writer.Write(reader.Key(), reader.Value());
         KALDI_LOG << "Copied " << num_done << " vectors.";
       } else {
         for (; !reader.Done(); reader.Next(), num_done++) {
           Vector<BaseFloat> vec (reader.Value());
           vec.Resize(change_dim, kCopyData);
           writer.Write(reader.Key(), reader.Value());
         }
         KALDI_LOG << "Copied " << num_done << " vectors, setting dim to "
                   << change_dim;
       }
       return (num_done != 0 ? 0 : 1);
     }
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }