var dir_f8ba563c7c64fffab9da0ebf98c94aa9 =
[
    [ "feature-fbank-test.cc", "feature-fbank-test_8cc.html", "feature-fbank-test_8cc" ],
    [ "feature-fbank.cc", "feature-fbank_8cc.html", null ],
    [ "feature-fbank.h", "feature-fbank_8h.html", null ],
    [ "feature-functions-test.cc", "feature-functions-test_8cc.html", "feature-functions-test_8cc" ],
    [ "feature-functions.cc", "feature-functions_8cc.html", "feature-functions_8cc" ],
    [ "feature-functions.h", "feature-functions_8h.html", "feature-functions_8h" ],
    [ "feature-mfcc-test.cc", "feature-mfcc-test_8cc.html", "feature-mfcc-test_8cc" ],
    [ "feature-mfcc.cc", "feature-mfcc_8cc.html", null ],
    [ "feature-mfcc.h", "feature-mfcc_8h.html", null ],
    [ "feature-plp-test.cc", "feature-plp-test_8cc.html", "feature-plp-test_8cc" ],
    [ "feature-plp.cc", "feature-plp_8cc.html", null ],
    [ "feature-plp.h", "feature-plp_8h.html", null ],
    [ "feature-sdc-test.cc", "feature-sdc-test_8cc.html", "feature-sdc-test_8cc" ],
    [ "feature-spectrogram.cc", "feature-spectrogram_8cc.html", null ],
    [ "feature-spectrogram.h", "feature-spectrogram_8h.html", null ],
    [ "mel-computations.cc", "mel-computations_8cc.html", "mel-computations_8cc" ],
    [ "mel-computations.h", "mel-computations_8h.html", "mel-computations_8h" ],
    [ "online-feature-test.cc", "online-feature-test_8cc.html", "online-feature-test_8cc" ],
    [ "online-feature.cc", "online-feature_8cc.html", null ],
    [ "online-feature.h", "online-feature_8h.html", "online-feature_8h" ],
    [ "pitch-functions-test.cc", "pitch-functions-test_8cc.html", "pitch-functions-test_8cc" ],
    [ "pitch-functions.cc", "pitch-functions_8cc.html", "pitch-functions_8cc" ],
    [ "pitch-functions.h", "pitch-functions_8h.html", "pitch-functions_8h" ],
    [ "resample-test.cc", "resample-test_8cc.html", "resample-test_8cc" ],
    [ "resample.cc", "resample_8cc.html", null ],
    [ "resample.h", "resample_8h.html", null ],
    [ "signal-test.cc", "signal-test_8cc.html", "signal-test_8cc" ],
    [ "signal.cc", "signal_8cc.html", "signal_8cc" ],
    [ "signal.h", "signal_8h.html", "signal_8h" ],
    [ "sinusoid-detection-test.cc", "sinusoid-detection-test_8cc.html", "sinusoid-detection-test_8cc" ],
    [ "sinusoid-detection.cc", "sinusoid-detection_8cc.html", "sinusoid-detection_8cc" ],
    [ "sinusoid-detection.h", "sinusoid-detection_8h.html", "sinusoid-detection_8h" ],
    [ "wave-reader.cc", "wave-reader_8cc.html", null ],
    [ "wave-reader.h", "wave-reader_8h.html", "wave-reader_8h" ]
];