var dir_239a7dd904d2aab447226d2a529adf46 =
[
    [ "init-ubm.cc", "init-ubm_8cc.html", "init-ubm_8cc" ],
    [ "sgmm-acc-fmllrbasis-ali.cc", "sgmm-acc-fmllrbasis-ali_8cc.html", "sgmm-acc-fmllrbasis-ali_8cc" ],
    [ "sgmm-acc-stats-ali.cc", "sgmm-acc-stats-ali_8cc.html", "sgmm-acc-stats-ali_8cc" ],
    [ "sgmm-acc-stats-gpost.cc", "sgmm-acc-stats-gpost_8cc.html", "sgmm-acc-stats-gpost_8cc" ],
    [ "sgmm-acc-stats.cc", "sgmm-acc-stats_8cc.html", "sgmm-acc-stats_8cc" ],
    [ "sgmm-acc-stats2.cc", "sgmm-acc-stats2_8cc.html", "sgmm-acc-stats2_8cc" ],
    [ "sgmm-acc-tree-stats.cc", "sgmm-acc-tree-stats_8cc.html", "sgmm-acc-tree-stats_8cc" ],
    [ "sgmm-align-compiled.cc", "sgmm-align-compiled_8cc.html", "sgmm-align-compiled_8cc" ],
    [ "sgmm-build-tree.cc", "sgmm-build-tree_8cc.html", "sgmm-build-tree_8cc" ],
    [ "sgmm-calc-distances.cc", "sgmm-calc-distances_8cc.html", "sgmm-calc-distances_8cc" ],
    [ "sgmm-cluster-phones.cc", "sgmm-cluster-phones_8cc.html", "sgmm-cluster-phones_8cc" ],
    [ "sgmm-comp-prexform.cc", "sgmm-comp-prexform_8cc.html", "sgmm-comp-prexform_8cc" ],
    [ "sgmm-copy.cc", "sgmm-copy_8cc.html", "sgmm-copy_8cc" ],
    [ "sgmm-decode-faster.cc", "sgmm-decode-faster_8cc.html", "sgmm-decode-faster_8cc" ],
    [ "sgmm-est-ebw.cc", "sgmm-est-ebw_8cc.html", "sgmm-est-ebw_8cc" ],
    [ "sgmm-est-fmllr-gpost.cc", "sgmm-est-fmllr-gpost_8cc.html", "sgmm-est-fmllr-gpost_8cc" ],
    [ "sgmm-est-fmllr.cc", "sgmm-est-fmllr_8cc.html", "sgmm-est-fmllr_8cc" ],
    [ "sgmm-est-fmllrbasis.cc", "sgmm-est-fmllrbasis_8cc.html", "sgmm-est-fmllrbasis_8cc" ],
    [ "sgmm-est-multi.cc", "sgmm-est-multi_8cc.html", "sgmm-est-multi_8cc" ],
    [ "sgmm-est-spkvecs-gpost.cc", "sgmm-est-spkvecs-gpost_8cc.html", "sgmm-est-spkvecs-gpost_8cc" ],
    [ "sgmm-est-spkvecs.cc", "sgmm-est-spkvecs_8cc.html", "sgmm-est-spkvecs_8cc" ],
    [ "sgmm-est.cc", "sgmm-est_8cc.html", "sgmm-est_8cc" ],
    [ "sgmm-gselect.cc", "sgmm-gselect_8cc.html", "sgmm-gselect_8cc" ],
    [ "sgmm-info.cc", "sgmm-info_8cc.html", "sgmm-info_8cc" ],
    [ "sgmm-init-from-tree-stats.cc", "sgmm-init-from-tree-stats_8cc.html", "sgmm-init-from-tree-stats_8cc" ],
    [ "sgmm-init.cc", "sgmm-init_8cc.html", "sgmm-init_8cc" ],
    [ "sgmm-latgen-faster.cc", "sgmm-latgen-faster_8cc.html", "sgmm-latgen-faster_8cc" ],
    [ "sgmm-latgen-simple.cc", "sgmm-latgen-simple_8cc.html", "sgmm-latgen-simple_8cc" ],
    [ "sgmm-mixup.cc", "sgmm-mixup_8cc.html", "sgmm-mixup_8cc" ],
    [ "sgmm-normalize.cc", "sgmm-normalize_8cc.html", "sgmm-normalize_8cc" ],
    [ "sgmm-post-to-gpost.cc", "sgmm-post-to-gpost_8cc.html", "sgmm-post-to-gpost_8cc" ],
    [ "sgmm-rescore-lattice.cc", "sgmm-rescore-lattice_8cc.html", "sgmm-rescore-lattice_8cc" ],
    [ "sgmm-sum-accs.cc", "sgmm-sum-accs_8cc.html", "sgmm-sum-accs_8cc" ],
    [ "sgmm-sum-tree-stats.cc", "sgmm-sum-tree-stats_8cc.html", "sgmm-sum-tree-stats_8cc" ],
    [ "sgmm-write-ubm.cc", "sgmm-write-ubm_8cc.html", "sgmm-write-ubm_8cc" ]
];