Kaldi: bin/duplicate-matrix.cc File Reference
duplicate-matrix.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
#include "transform/transform-common.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file duplicate-matrix.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), rnnlm::i, KALDI_ERR, KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Copy tables of BaseFloat matrices, from one input to possibly multiple outputs,\n"
         "with each element of the input written too all outputs.\n"
         "\n"
         "Usage: duplicate-matrix [options] <matrix-rspecifier> <matrix-wspecifier1> [<matrix-wspecifier2> ...]\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string matrix_rspecifier = po.GetArg(1);
     SequentialBaseFloatMatrixReader matrix_reader(matrix_rspecifier);
     std::vector<BaseFloatMatrixWriter> writers(po.NumArgs() - 1);
     for (size_t i = 0; i < writers.size(); i++)
       if (!writers[i].Open(po.GetArg(i + 1)))
         KALDI_ERR << "Error opening table for writing with wspecifier \""
                   <<  po.GetArg(i + 1) << '"';
     int32 num_done = 0;
     for (; !matrix_reader.Done(); matrix_reader.Next(), num_done++)
       for (size_t i = 0; i < writers.size(); i++)
         writers[i].Write(matrix_reader.Key(), matrix_reader.Value());
     KALDI_LOG << "Copied " << num_done << " matrices to "
               << writers.size() << " outputs.";
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }