Kaldi: tree/event-map-test.cc File Reference
event-map-test.cc File Reference
#include "tree/event-map.h"
#include "util/kaldi-io.h"
#include <map>
Namespaces
kaldi
Functions
void TestEventMap ()
void TestEventTypeIo (bool binary)
EventMap * RandomEventMap (const std::vector< EventKeyType > &keys)
void TestEventMapIo (bool binary)
void TestEventMapPrune ()
void TestEventMapMapValues ()
int main ()
Variables
const int32 kMaxVal = 20
Function Documentation
int main ()
Definition at line 318 of file event-map-test.cc.
References rnnlm::i, kaldi::TestEventMap(), kaldi::TestEventMapIo(), kaldi::TestEventMapMapValues(), kaldi::TestEventMapPrune(), and kaldi::TestEventTypeIo().
            {
   using namespace kaldi;
   TestEventTypeIo(false);
   TestEventTypeIo(true);
   TestEventMapIo(false);
   TestEventMapIo(true);
   for (int32 i = 0; i <  10; i++) {
     TestEventMap();
     TestEventMapPrune();
     TestEventMapMapValues();
   }
 }