Kaldi: transform/fmllr-diag-gmm-test.cc File Reference
fmllr-diag-gmm-test.cc File Reference
#include "util/common-utils.h"
#include "gmm/diag-gmm.h"
#include "transform/fmllr-diag-gmm.h"
Namespaces
kaldi
Functions
void InitRandomGmm (DiagGmm *gmm_in)
void UnitTestFmllrDiagGmm ()
void UnitTestFmllrDiagGmmDiagonal ()
void UnitTestFmllrDiagGmmOffset ()
int main ()
Function Documentation
int main ()
Definition at line 227 of file fmllr-diag-gmm-test.cc.
References rnnlm::i, kaldi::UnitTestFmllrDiagGmm(), kaldi::UnitTestFmllrDiagGmmDiagonal(), and kaldi::UnitTestFmllrDiagGmmOffset().
            {
   for (int i = 0; i < 2; i++) {  // did more iterations when first testing...
     kaldi::UnitTestFmllrDiagGmmOffset();
     kaldi::UnitTestFmllrDiagGmmDiagonal();
     kaldi::UnitTestFmllrDiagGmm();
   }
   std::cout << "Test OK.\n";
 }