Kaldi: featbin/fmpe-copy.cc File Reference
fmpe-copy.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "transform/fmpe.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 24 of file fmpe-copy.cc.
References ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), FmpeOptions::Register(), Output::Stream(), and Fmpe::Write().
{
   using namespace kaldi;
   try {
     const char *usage =
         "Copy fMPE transform\n"
         "Usage: fmpe-copy [options...] <fmpe-in> <fmpe-out>\n"
         "E.g. fmpe-copy --binary=false 1.fmpe text.fmpe\n";
     ParseOptions po(usage);
     FmpeOptions opts;
     bool binary = true;
     po.Register("binary", &binary, "If true, output fMPE object in binary mode.");
     opts.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string fmpe_rxfilename = po.GetArg(1),
         fmpe_wxfilename = po.GetArg(2);
     Fmpe fmpe;
     ReadKaldiObject(fmpe_rxfilename, &fmpe);
     Output ko(fmpe_wxfilename, binary);
     fmpe.Write(ko.Stream(), binary);
     KALDI_LOG << "Copyied fMPE object to " << fmpe_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }