Kaldi: fstbin/fstdeterminizestar.cc File Reference
fstdeterminizestar.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fst/fstlib.h"
#include "fstext/determinize-star.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
#include <signal.h>
Functions
void signal_handler (int)
int main (int argc, char *argv[])
Variables
bool debug_location = false
Function Documentation
int main (int argc, char * argv[])
Definition at line 62 of file fstdeterminizestar.cc.
References kaldi::ClassifyRspecifier(), debug_location, fst::DeterminizeStar(), fst::DeterminizeStarInLog(), SequentialTableReader< Holder >::Done(), SequentialTableReader< Holder >::FreeCurrent(), ParseOptions::GetOptArg(), KALDI_WARN, SequentialTableReader< Holder >::Key(), kaldi::kNoRspecifier, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadFstKaldi(), ParseOptions::Register(), signal_handler(), SequentialTableReader< Holder >::Value(), TableWriter< Holder >::Write(), and fst::WriteFstKaldi().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     const char *usage =
         "Removes epsilons and determinizes in one step\n"
         "\n"
         "Usage:  fstdeterminizestar [in.fst [out.fst] ]\n"
         "\n"
         "See also: fstdeterminizelog, lattice-determinize\n";
     float delta = kDelta;
     int max_states = -1;
     bool use_log = false;
     ParseOptions po(usage);
     po.Register("use-log", &use_log, "Determinize in log semiring.");
     po.Register("delta", &delta, "Delta value used to determine equivalence of weights.");
     po.Register("max-states", &max_states, "Maximum number of states in determinized FST before it will abort.");
     po.Read(argc, argv);
     if (po.NumArgs() > 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string fst_in_str = po.GetOptArg(1),
         fst_out_str = po.GetOptArg(2);
     // This enables us to get traceback info from determinization that is
     // not seeming to terminate.
 #ifndef _MSC_VER
     signal(SIGUSR1, signal_handler);
 #endif
     if (ClassifyRspecifier(fst_in_str, NULL, NULL) == kNoRspecifier) {
       // Normal case: just files.
       VectorFst<StdArc> *fst = ReadFstKaldi(fst_in_str);
       ArcSort(fst, ILabelCompare<StdArc>());  // improves speed.
       if (use_log) {
         DeterminizeStarInLog(fst, delta, &debug_location, max_states);
       } else {
         VectorFst<StdArc> det_fst;
         DeterminizeStar(*fst, &det_fst, delta, &debug_location, max_states);
         *fst = det_fst;  // will do shallow copy and then det_fst goes
         // out of scope anyway.
       }
       WriteFstKaldi(*fst, fst_out_str);
       delete fst;
     } else { // Dealing with archives.
       SequentialTableReader<VectorFstHolder> fst_reader(fst_in_str);
       TableWriter<VectorFstHolder> fst_writer(fst_out_str);
       for (; !fst_reader.Done(); fst_reader.Next()) {
         std::string key = fst_reader.Key();
         VectorFst<StdArc> fst(fst_reader.Value());
         fst_reader.FreeCurrent();
         ArcSort(&fst, ILabelCompare<StdArc>()); // improves speed.
         try {
           if (use_log) {
             DeterminizeStarInLog(&fst, delta, &debug_location, max_states);
           } else {
             VectorFst<StdArc> det_fst;
             DeterminizeStar(fst, &det_fst, delta, &debug_location, max_states);
             fst = det_fst;  // will do shallow copy and then det_fst goes out
             // of scope anyway.
           }
           fst_writer.Write(key, fst);
         } catch (const std::runtime_error e) {
           KALDI_WARN << "Error during determinization for key " << key;
         }
       }
     }
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }
void signal_handler (int)
Definition at line 56 of file fstdeterminizestar.cc.
References debug_location.
Referenced by main().
{
   debug_location = true;
 }
Variable Documentation
bool debug_location = false
Definition at line 55 of file fstdeterminizestar.cc.
Referenced by main(), and signal_handler().