Kaldi: fstbin/fstminimizeencoded.cc File Reference
fstminimizeencoded.cc File Reference
#include "base/kaldi-common.h"
#include "util/kaldi-io.h"
#include "util/parse-options.h"
#include "util/text-utils.h"
#include "fst/fstlib.h"
#include "fstext/determinize-star.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file fstminimizeencoded.cc.
References ParseOptions::GetOptArg(), fst::MinimizeEncoded(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), fst::ReadFstKaldi(), ParseOptions::Register(), and fst::WriteFstKaldi().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     const char *usage =
         "Minimizes FST after encoding [similar to fstminimize, but no weight-pushing]\n"
         "\n"
         "Usage:  fstminimizeencoded [in.fst [out.fst] ]\n";
     float delta = kDelta;
     ParseOptions po(usage);
     po.Register("delta", &delta, "Delta likelihood used for quantization of weights");
     po.Read(argc, argv);
     if (po.NumArgs() > 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string fst_in_filename = po.GetOptArg(1),
         fst_out_filename = po.GetOptArg(2);
     VectorFst<StdArc> *fst = ReadFstKaldi(fst_in_filename);
     MinimizeEncoded(fst, delta);
     WriteFstKaldi(*fst, fst_out_filename);
     delete fst;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
   return 0;
 }