Kaldi: fstbin/fstpropfinal.cc File Reference
fstpropfinal.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fst/fstlib.h"
#include "fstext/determinize-star.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
#include <signal.h>
Functions
void signal_handler (int)
int main (int argc, char *argv[])
Variables
bool debug_location = false
Function Documentation
int main (int argc, char * argv[])
Definition at line 73 of file fstpropfinal.cc.
References kaldi::ConvertStringToInteger(), ParseOptions::GetOptArg(), KALDI_ERR, KALDI_WARN, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), fst::PropagateFinal(), ParseOptions::Read(), fst::ReadFstKaldi(), and fst::WriteFstKaldi().
{
   try {
     using namespace kaldi;
     using namespace fst;
     using kaldi::int32;
     const char *usage =
         "Propagates final-states through phi transitions\n"
         "\n"
         "Usage:  fstpropfinal phi-label [in.fst [out.fst] ]\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() > 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string phi_str = po.GetOptArg(1),
         fst_in_str = po.GetOptArg(2),
         fst_out_str = po.GetOptArg(3);
     int32 phi_label;
     if (!ConvertStringToInteger(phi_str, &phi_label)
         || phi_label < 0)
       KALDI_ERR << "Bad phi label " << phi_label;
     if (phi_label == 0)
       KALDI_WARN  << "Phi_label == 0, may not be a good idea.";
     VectorFst<StdArc> *fst = ReadFstKaldi(fst_in_str);
     PropagateFinal(phi_label, fst);
     WriteFstKaldi(*fst, fst_out_str);
     delete fst;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }
void signal_handler (int)
Definition at line 67 of file fstpropfinal.cc.
References debug_location.
{
   debug_location = true;
 }
Variable Documentation
bool debug_location = false
Definition at line 66 of file fstpropfinal.cc.
Referenced by signal_handler().