Kaldi: fstbin/fsts-to-transcripts.cc File Reference
fsts-to-transcripts.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fstext/fstext-utils.h"
#include "fstext/kaldi-fst-io.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file fsts-to-transcripts.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), ParseOptions::GetOptArg(), KALDI_ERR, KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     using namespace fst;
     typedef kaldi::int32 int32;
     typedef kaldi::uint64 uint64;
     const char *usage =
         "Reads a table of FSTs; for each element, finds the best path and prints out the\n"
         "output-symbol sequence (if --output-side=true), or input-symbol sequence "
         "otherwise.\n"
         "\n"
         "Usage: fsts-to-transcripts [options] <fsts-rspecifier> <transcriptions-wspecifier>\n"
         " e.g.: fsts-to-transcripts ark:train.fsts ark,t:train.text\n";
     ParseOptions po(usage);
     bool output_side = true;
     po.Register("output-side", &output_side, "If true, extract the symbols on "
                 "the output side of the FSTs, else the input side.");
     po.Read(argc, argv);
     if (po.NumArgs() < 2 || po.NumArgs() > 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string fst_rspecifier = po.GetArg(1),
         transcript_wspecifier = po.GetOptArg(2);
     SequentialTableReader<VectorFstHolder> fst_reader(fst_rspecifier);
     Int32VectorWriter transcript_writer(transcript_wspecifier);
     int32 n_done = 0, n_err = 0;
     for (; !fst_reader.Done(); fst_reader.Next()) {
       std::string key = fst_reader.Key();
       const VectorFst<StdArc> &fst = fst_reader.Value();
       VectorFst<StdArc> shortest_path;
       ShortestPath(fst, &shortest_path); // the OpenFst algorithm ShortestPath.
       if (shortest_path.NumStates() == 0) {
         KALDI_WARN << "Input FST (after shortest path) was empty.  Producing no "
                    << "output for key " << key;
         n_err++;
         continue;
       }
       std::vector<int32> transcript;
       bool ans;
       if (output_side) ans = fst::GetLinearSymbolSequence<StdArc, int32>(
               shortest_path, NULL, &transcript, NULL);
       else ans = fst::GetLinearSymbolSequence<StdArc, int32>(
           shortest_path, &transcript, NULL, NULL);
       if (!ans) {
         KALDI_ERR << "GetLinearSymbolSequence returned false (code error);";
       }
       transcript_writer.Write(key, transcript);
       n_done++;
     }
     KALDI_LOG << "Converted " << n_done << " FSTs, " << n_err << " with errors";
     return (n_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }