Kaldi: featbin/get-full-lda-mat.cc File Reference
get-full-lda-mat.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
#include "transform/transform-common.h"
Namespaces
kaldi
Functions
void IncreaseTransformDimension (int32 new_dimension, Matrix< BaseFloat > *mat)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 54 of file get-full-lda-mat.cc.
References ParseOptions::GetArg(), ParseOptions::GetOptArg(), KALDI_ASSERT, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     const char *usage =
         "This is a special-purpose program to be used in \"predictive SGMMs\".\n"
         "It takes in an LDA+MLLT matrix, and the original \"full\" LDA matrix\n"
         "as output by the --write-full-matrix option of est-lda; and it writes\n"
         "out a \"full\" LDA+MLLT matrix formed by the LDA+MLLT matrix plus the\n"
         "remaining rows of the \"full\" LDA matrix; and also writes out its inverse\n"
         "Usage: get-full-lda-mat [options] <lda-mllt-rxfilename> <full-lda-rxfilename> "
         "<full-lda-mllt-wxfilename> [<inv-full-lda-mllt-wxfilename>]\n"
         "E.g.: get-full-lda-mat final.mat full.mat full_lda_mllt.mat full_lda_mllt_inv.mat\n";
     bool binary = true;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write in binary mode (only relevant if output is a wxfilename)");
     po.Read(argc, argv);
     if (po.NumArgs() < 3 || po.NumArgs() > 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string lda_mllt_rxfilename = po.GetArg(1),
         full_lda_rxfilename = po.GetArg(2),
         full_lda_mllt_wxfilename = po.GetArg(3),
         inv_full_lda_mllt_wxfilename = po.GetOptArg(4);
     Matrix<BaseFloat> lda_mllt;
     ReadKaldiObject(lda_mllt_rxfilename, &lda_mllt);
     Matrix<BaseFloat> full_lda;
     ReadKaldiObject(full_lda_rxfilename, &full_lda);
     KALDI_ASSERT(full_lda.NumCols() == lda_mllt.NumCols());
     KALDI_ASSERT(full_lda.NumRows() == full_lda.NumCols());
     Matrix<BaseFloat> full_lda_mllt(full_lda);
     full_lda_mllt.Range(0, lda_mllt.NumRows(),
                         0, lda_mllt.NumCols()).CopyFromMat(lda_mllt);
     WriteKaldiObject(full_lda_mllt, full_lda_mllt_wxfilename, binary);
     if (po.NumArgs() != 3) {
       full_lda_mllt.Invert();
       WriteKaldiObject(full_lda_mllt, inv_full_lda_mllt_wxfilename, binary);
     }
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }