Kaldi: gmmbin/gmm-init-trans.cc File Reference
gmm-init-trans.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "hmm/hmm-topology.h"
#include "hmm/transition-model.h"
#include "tree/build-tree.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file gmm-init-trans.cc.
References ParseOptions::GetArg(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), Output::Stream(), and TransitionModel::Write().
{
   try {
     using namespace kaldi;
     using kaldi::int32;
     const char *usage =
         "Initialize transition model given topo, tree and GMM (used for format conversion from HTK)\n"
         "Usage:  gmm-init-trans <topology-in> <gmm-in> <tree-in> <model-out>\n";
     bool binary = true;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string topo_filename = po.GetArg(1);
     std::string gmm_filename = po.GetArg(2);
     std::string tree_filename = po.GetArg(3);
     std::string model_out_filename = po.GetArg(4);
     // Read toppology.
     HmmTopology topo;
     ReadKaldiObject(topo_filename, &topo);
     // Read model.
     AmDiagGmm am_gmm;
     ReadKaldiObject(gmm_filename, &am_gmm);
     // Now the tree
     ContextDependency ctx_dep;
     ReadKaldiObject(tree_filename, &ctx_dep);
     TransitionModel trans_model(ctx_dep, topo);
     {  // Write transition-model and GMM to one file in the normal Kaldi way.
       Output out(model_out_filename, binary);
       trans_model.Write(out.Stream(), binary);
       am_gmm.Write(out.Stream(), binary);
     }
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }