Kaldi: gmmbin/gmm-acc-stats-ali.cc File Reference
gmm-acc-stats-ali.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "gmm/am-diag-gmm.h"
#include "hmm/transition-model.h"
#include "gmm/mle-am-diag-gmm.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 30 of file gmm-acc-stats-ali.cc.
References TransitionModel::Accumulate(), AccumAmDiagGmm::AccumulateForGmm(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), RandomAccessTableReader< Holder >::HasKey(), rnnlm::i, AccumAmDiagGmm::Init(), TransitionModel::InitStats(), KALDI_LOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), kaldi::kGmmAll, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), AmDiagGmm::Read(), ParseOptions::Read(), TransitionModel::Read(), ParseOptions::Register(), MatrixBase< Real >::Row(), Output::Stream(), Input::Stream(), TransitionModel::TransitionIdToPdf(), RandomAccessTableReader< Holder >::Value(), SequentialTableReader< Holder >::Value(), AccumAmDiagGmm::Write(), and VectorBase< Real >::Write().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
         "Accumulate stats for GMM training.\n"
         "Usage:  gmm-acc-stats-ali [options] <model-in> <feature-rspecifier> "
         "<alignments-rspecifier> <stats-out>\n"
         "e.g.:\n gmm-acc-stats-ali 1.mdl scp:train.scp ark:1.ali 1.acc\n";
     ParseOptions po(usage);
     bool binary = true;
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_filename = po.GetArg(1),
         feature_rspecifier = po.GetArg(2),
         alignments_rspecifier = po.GetArg(3),
         accs_wxfilename = po.GetArg(4);
     AmDiagGmm am_gmm;
     TransitionModel trans_model;
     {
       bool binary;
       Input ki(model_filename, &binary);
       trans_model.Read(ki.Stream(), binary);
       am_gmm.Read(ki.Stream(), binary);
     }
     Vector<double> transition_accs;
     trans_model.InitStats(&transition_accs);
     AccumAmDiagGmm gmm_accs;
     gmm_accs.Init(am_gmm, kGmmAll);
     double tot_like = 0.0;
     kaldi::int64 tot_t = 0;
     SequentialBaseFloatMatrixReader feature_reader(feature_rspecifier);
     RandomAccessInt32VectorReader alignments_reader(alignments_rspecifier);
     int32 num_done = 0, num_err = 0;
     for (; !feature_reader.Done(); feature_reader.Next()) {
       std::string key = feature_reader.Key();
       if (!alignments_reader.HasKey(key)) {
         KALDI_WARN << "No alignment for utterance " << key;
         num_err++;
       } else {
         const Matrix<BaseFloat> &mat = feature_reader.Value();
         const std::vector<int32> &alignment = alignments_reader.Value(key);
         if (alignment.size() != mat.NumRows()) {
           KALDI_WARN << "Alignments has wrong size " << (alignment.size())
                      << " vs. " << (mat.NumRows());
           num_err++;
           continue;
         }
         num_done++;
         BaseFloat tot_like_this_file = 0.0;
         for (size_t i = 0; i < alignment.size(); i++) {
           int32 tid = alignment[i],  // transition identifier.
               pdf_id = trans_model.TransitionIdToPdf(tid);
           trans_model.Accumulate(1.0, tid, &transition_accs);
           tot_like_this_file += gmm_accs.AccumulateForGmm(am_gmm, mat.Row(i),
                                                           pdf_id, 1.0);
         }
         tot_like += tot_like_this_file;
         tot_t += alignment.size();
         if (num_done % 50 == 0) {
           KALDI_LOG << "Processed " << num_done << " utterances; for utterance "
                     << key << " avg. like is "
                     << (tot_like_this_file/alignment.size())
                     << " over " << alignment.size() <<" frames.";
         }
       }
     }
     KALDI_LOG << "Done " << num_done << " files, " << num_err
               << " with errors.";
     KALDI_LOG << "Overall avg like per frame (Gaussian only) = "
               << (tot_like/tot_t) << " over " << tot_t << " frames.";
     {
       Output ko(accs_wxfilename, binary);
       transition_accs.Write(ko.Stream(), binary);
       gmm_accs.Write(ko.Stream(), binary);
     }
     KALDI_LOG << "Written accs.";
     if (num_done != 0)
       return 0;
     else
       return 1;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }