Kaldi: "Classes and functions related to context expansion"
"Classes and functions related to context expansion"
Classes
class ContextFstImpl< Arc, LabelT >
class ContextFst< Arc, LabelT >
class StateIterator< ContextFst< A > >
class ArcIterator< ContextFst< A > >
class ContextMatcher< Arc, LabelT >
Functions
template<class Arc >
void AddSubsequentialLoop (typename Arc::Label subseq_symbol, MutableFst< Arc > *fst)
Modifies an FST so that it transuces the same paths, but the input side of the paths can all have the subsequential symbol '$' appended to them any number of times (we could easily specify the number of times, but accepting any number of repetitions is just more convenient).
template<class I >
void WriteILabelInfo (std::ostream &os, bool binary, const vector< vector< I > > &info)
Useful utility function for writing these vectors to disk.
template<class I >
void ReadILabelInfo (std::istream &is, bool binary, vector< vector< I > > *info)
Useful utility function for reading these vectors from disk.
template<class I >
SymbolTable * CreateILabelInfoSymbolTable (const vector< vector< I > > &info, const SymbolTable &phones_symtab, std::string separator, std::string disambig_prefix)
The following function is mainly of use for printing and debugging.
void ComposeContext (const vector< int32 > &disambig_syms, int N, int P, VectorFst< StdArc > *ifst, VectorFst< StdArc > *ofst, vector< vector< int32 > > *ilabels_out)
Used in the command-line tool fstcomposecontext.
template<class Arc , class LabelT >
void ComposeContextFst (const ContextFst< Arc, LabelT > &ifst1, const Fst< Arc > &ifst2, MutableFst< Arc > *ofst, const ComposeOptions &opts=ComposeOptions())
StateId FindState (const vector< LabelT > &seq)
Finds state-id corresponding to this vector of phones. Inserts it if necessary.
Label FindLabel (const vector< LabelT > &label_info)
Finds the label index corresponding to this context-window of phones.
StateId Start ()
ContextFstImpl (const ContextFstImpl &other)
Weight Final (StateId s)
size_t NumArcs (StateId s)
size_t NumInputEpsilons (StateId s)
void InitArcIterator (StateId s, ArcIteratorData< Arc > *data)
void CreateDisambigArc (StateId s, Label olabel, Arc *oarc)
bool CreatePhoneOrEpsArc (StateId src, StateId dst, Label olabel, const vector< LabelT > &phone_seq, Arc *oarc)
bool CreateArc (StateId s, Label olabel, Arc *oarc)
void Expand (StateId s)
ContextFst (const ContextFst< Arc, LabelT > &fst, bool reset=false)
bool Find (Label match_label)
virtual void InitStateIterator (StateIteratorData< Arc > *data) const
Detailed Description
Function Documentation
void AddSubsequentialLoop (typename Arc::Label subseq_symbol, MutableFst< Arc > * fst)
Modifies an FST so that it transuces the same paths, but the input side of the paths can all have the subsequential symbol '$' appended to them any number of times (we could easily specify the number of times, but accepting any number of repetitions is just more convenient).
The actual way we do this is for each final state, we add a transition with weight equal to the final-weight of that state, with input-symbol '$' and output-symbols <eps>, and ending in a new super-final state that has unit final-probability and a unit-weight self-loop with '$' on its input and <eps> on its output. The reason we don't just add a loop to each final-state has to do with preserving stochasticity (see Preserving stochasticity and testing it). We keep the final-probability in all the original final-states rather than setting them to zero, so the resulting FST can accept zero '$' symbols at the end (in case we had no right context).
Definition at line 401 of file context-fst-inl.h.
References rnnlm::i.
Referenced by fst::ComposeContext(), main(), and TrainingGraphCompiler::TrainingGraphCompiler().
{
   typedef typename Arc::StateId StateId;
   typedef typename Arc::Weight Weight;
   vector<StateId> final_states;
   for (StateIterator<MutableFst<Arc> > siter(*fst); !siter.Done(); siter.Next()) {
     StateId s = siter.Value();
     if (fst->Final(s) != Weight::Zero())  final_states.push_back(s);
   }
   StateId superfinal = fst->AddState();
   Arc arc(subseq_symbol, 0, Weight::One(), superfinal);
   fst->AddArc(superfinal, arc);  // loop at superfinal.
   fst->SetFinal(superfinal, Weight::One());
   for (size_t i = 0; i < final_states.size(); i++) {
     StateId s = final_states[i];
     fst->AddArc(s, Arc(subseq_symbol, 0, fst->Final(s), superfinal));
     // No, don't remove the final-weights of the original states..
     // this is so we can add the subsequential loop in cases where
     // there is no context, and it won't hurt.
     // fst->SetFinal(s, Weight::Zero());
     arc.nextstate = final_states[i];
   }
 }
void ComposeContext (const vector< int32 > & disambig_syms, int N, int P, VectorFst< StdArc > * ifst, VectorFst< StdArc > * ofst, vector< vector< int32 > > * ilabels_out) inline
Used in the command-line tool fstcomposecontext.
It creates a context FST and composes it on the left with "ifst" to make "ofst". It outputs the label information to ilabels_out. "ifst" is mutable because we need to add the subsequential loop.
Definition at line 514 of file context-fst-inl.h.
References fst::AddSubsequentialLoop(), fst::ComposeContextFst(), fst::GetInputSymbols(), rnnlm::i, and ContextFst< Arc, LabelT >::ILabelInfo().
Referenced by main().
{
   assert(ifst != NULL && ofst != NULL);
   assert(N > 0);
   assert(P >= 0);
   assert(P < N);
   vector<int32> disambig_syms(disambig_syms_in);
   std::sort(disambig_syms.begin(), disambig_syms.end());
   vector<int32> all_syms;
   GetInputSymbols(*ifst, false/*no eps*/, &all_syms);
   std::sort(all_syms.begin(), all_syms.end());
   vector<int32> phones;
   for (size_t i = 0; i < all_syms.size(); i++)
     if (!std::binary_search(disambig_syms.begin(),
                             disambig_syms.end(), all_syms[i]))
       phones.push_back(all_syms[i]);
   // Get subsequential symbol that does not clash with
   // any disambiguation symbol or symbol in the FST.
   int32 subseq_sym = 1;
   if (!all_syms.empty())
     subseq_sym = std::max(subseq_sym, all_syms.back() + 1);
   if (!disambig_syms.empty())
     subseq_sym = std::max(subseq_sym, disambig_syms.back() + 1);
   // if P == N-1, it's left-context, and no subsequential symbol needed.
   if (P != N-1)
     AddSubsequentialLoop(subseq_sym, ifst);
   ContextFst<StdArc, int32> cfst(subseq_sym, phones, disambig_syms, N, P);
   ComposeContextFst(cfst, *ifst, ofst);
   *ilabels_out = cfst.ILabelInfo();
 }
void fst::ComposeContextFst (const ContextFst< Arc, LabelT > & ifst1, const Fst< Arc > & ifst2, MutableFst< Arc > * ofst, const ComposeOptions & opts = ComposeOptions())
Definition at line 491 of file context-fst.h.
Referenced by TrainingGraphCompiler::CompileGraph(), TrainingGraphCompiler::CompileGraphs(), fst::ComposeContext(), and fst::TestContextFst().
{
   ComposeFstOptions<Arc, ContextMatcher<Arc, LabelT> > nopts;
   nopts.gc_limit = 0;  // Cache only the most recent state for fastest copy.
   *ofst = ComposeFst<Arc>(ifst1, ifst2, nopts);
   if (opts.connect)
     Connect(ofst);
 }
ContextFst (const ContextFst< Arc, LabelT > & fst, bool reset = false)
Definition at line 361 of file context-fst-inl.h.
References ContextFst< Arc, LabelT >::impl_.
{
   if (reset) {
     impl_ = new ContextFstImpl<Arc, LabelT>(*(fst.impl_));
     // Copy constructor of ContextFstImpl.
     // Main use of calling with reset = true is to free up memory
     // (e.g. then you could delete original one).  Might be useful in transcription
     // expansion during training.
   } else {
     impl_ = fst.impl_;
     impl_->IncrRefCount();
   }
 }
ContextFstImpl (const ContextFstImpl< Arc, LabelT > & other)
Definition at line 88 of file context-fst-inl.h.
                                                                       :
     phone_syms_(other.phone_syms_),
     disambig_syms_(other.disambig_syms_) {
   std::cerr << "ContextFst copying not yet supported [not hard, but would have to test.]";
   exit(1);
 }
bool CreateArc (StateId s, Label olabel, Arc * oarc)
Definition at line 272 of file context-fst-inl.h.
References rnnlm::i.
{
   // Returns true to indicate the arc exists.
   if (olabel == 0) return false;  // No epsilon-output arcs in this FST.
   const vector<LabelT> &seq = state_seqs_[s];
   if (IsDisambigSymbol(olabel)) {  // Disambiguation-symbol arcs.. create self-loop.
     CreateDisambigArc(s, olabel, oarc);
     return true;
   } else if (IsPhoneSymbol(olabel) || olabel == subsequential_symbol_) {
     // If all is OK, we shift the old sequence left by 1 and push on the new phone.
     if (olabel != subsequential_symbol_ && !seq.empty() &&
         seq.back() == subsequential_symbol_) {
       return false;  // Phone not allowed to follow subsequential symbol.
     }
     if (olabel == subsequential_symbol_ &&
         (P_ == N_-1 || seq[P_] == subsequential_symbol_)) {
       // We already had "enough" subsequential symbols in a row and don't want to
       // accept any more, or we'd be making the subsequential symbol the central phone.
       return false;
     }
     vector<LabelT> newseq(N_-1);  // seq shifted left by 1.
     for (int i = 0;i < N_-2;i++) newseq[i] = seq[i+1];
     if (N_ > 1) newseq[N_-2] = olabel;
     vector<LabelT> phoneseq(seq);  // copy it before FindState which
     // possibly changes the address.
     StateId nextstate = FindState(newseq);
     phoneseq.push_back(olabel);  // Now it's the full context window of size N_.
     for (int i = 1; i < N_ ; i++)
       if (phoneseq[i] == subsequential_symbol_) phoneseq[i] = 0;  // don't put subseq. symbol on
     // the output arcs, just 0.
     return CreatePhoneOrEpsArc(s, nextstate, olabel, phoneseq, oarc);
   } else {
     std::cerr << "ContextFst: CreateArc, invalid olabel supplied [confusion about phone list or disambig symbols?]: "<<(olabel);
     exit(1);
  }
   return false;  // won't get here.  suppress compiler error.
 }
void CreateDisambigArc (StateId s, Label olabel, Arc * oarc) inline private
Definition at line 221 of file context-fst-inl.h.
                                                                {  // called from CreateArc.
   // Creates a self-loop arc corresponding to the disambiguation symbol.
   vector<LabelT> label_info;  // (olabel);
   label_info.push_back(-olabel);  // olabel is a disambiguation symbol.  Use its negative
   // so we can easily distinguish them.
   Label ilabel = FindLabel(label_info);
   oarc->ilabel = ilabel;
   oarc->olabel = olabel;
   oarc->weight = Weight::One();
   oarc->nextstate = s;  // self-loop.
 }
SymbolTable * CreateILabelInfoSymbolTable (const vector< vector< I > > & info, const SymbolTable & phones_symtab, std::string separator, std::string initial_disambig)
The following function is mainly of use for printing and debugging.
Definition at line 453 of file context-fst-inl.h.
References rnnlm::i, and rnnlm::j.
Referenced by main().
                                                                      {  // e.g. separator = "/", initial-disambig="#-1"
   assert(std::numeric_limits<I>::is_signed);  // make sure is signed type.
   assert(!info.empty());
   assert(info[0].empty());
   SymbolTable *ans = new SymbolTable("ilabel-info-symtab");
   int64 s = ans->AddSymbol(phones_symtab.Find(static_cast<int64>(0)));
   assert(s == 0);
   for (size_t i = 1; i < info.size(); i++) {
     if (info[i].size() == 0) {
       std::cerr << "CreateILabelInfoSymbolTable: invalid ilabel-info";
       exit(1);
     }
     if (info[i].size() == 1 &&
        info[i][0] <= 0) {
       if (info[i][0] == 0) {  // special symbol at start that we want to call #-1.
         s = ans->AddSymbol(initial_disambig);
         if (s != i) {
           std::cerr << "Disambig symbol " << initial_disambig
                     << " already in vocab\n";
           exit(1);
         }
       } else {
         std::string disambig_sym = phones_symtab.Find(-info[i][0]);
         if (disambig_sym == "") {
           std::cerr << "CreateILabelInfoSymbolTable: disambig symbol "
                     << -info[i][0] << " not in phone symbol-table.";
           exit(1);
         }
         s = ans->AddSymbol(disambig_sym);
         if (s != i) {
           std::cerr << "Disambig symbol " << disambig_sym
                     << " already in vocab\n";
           exit(1);
         }
       }
     } else {
       // is a phone-context-window.
       std::string newsym;
       for (size_t j = 0; j < info[i].size(); j++) {
         std::string phonesym = phones_symtab.Find(info[i][j]);
         if (phonesym == "") {
           std::cerr << "CreateILabelInfoSymbolTable: symbol "
                     << info[i][j] << " not in phone symbol-table.";
           exit(1);
         }
         if (j != 0) newsym += separator;
         newsym += phonesym;
       }
       int64 s = ans->AddSymbol(newsym);
       if (s != static_cast<int64>(i)) {
         std::cerr << "CreateILabelInfoSymbolTable: some problem with duplicate symbols.";
         exit(1);
       }
     }
   }
   return ans;
 }
bool CreatePhoneOrEpsArc (StateId src, StateId dst, Label olabel, const vector< LabelT > & phone_seq, Arc * oarc) inline private
Definition at line 236 of file context-fst-inl.h.
{
   // called from CreateArc.
   // creates the arc with a phone's state on its input labels (or epsilon).
   // returns true if it created the arc.
   // returns false if it could not create an arc due to the decision-tree returning false
   // [this only happens if opts_.behavior_on_failure == ContextFstOptions::kNoArc].
   assert(phone_seq[P_] != subsequential_symbol_);  // would be coding error.
   if (phone_seq[P_] == 0) {  // this can happen at the beginning of the graph.
     // we don't output a real phone.  Epsilon arc (but sometimes we need to
     // use a special disambiguation symbol instead of epsilon).
     *oarc = Arc(pseudo_eps_symbol_, olabel, Weight::One(), dst);
     // This 1 is a "special" disambiguation symbol (#-1 in printed form) that
     // we use to represent epsilons.
     return true;
   } else {
     // have a phone in central position.
     Label ilabel = FindLabel(phone_seq);
     *oarc = Arc(ilabel, olabel, Weight::One(), dst);
     return true;
   }
 }
void Expand (StateId s)
Definition at line 322 of file context-fst-inl.h.
                                                   {  // expands arcs only [not final state weight].
   assert(static_cast<size_t>(s) < state_seqs_.size());  // make sure state exists already.
   // We just try adding all possible symbols on the output side.
   Arc arc;
   if (this->CreateArc(s, subsequential_symbol_, &arc)) {
 #ifdef HAVE_OPENFST_GE_10400
     this->PushArc(s, arc);
 #else
     this->AddArc(s, arc);
 #endif
   }
   for (typename kaldi::ConstIntegerSet<Label>::iterator iter = phone_syms_.begin();
        iter != phone_syms_.end(); ++iter) {
     Label phone = *iter;
     if (this->CreateArc(s, phone, &arc)) {
 #ifdef HAVE_OPENFST_GE_10400
       this->PushArc(s, arc);
 #else
       this->AddArc(s, arc);
 #endif
     }
   }
   for (typename kaldi::ConstIntegerSet<Label>::iterator iter = disambig_syms_.begin();
        iter != disambig_syms_.end(); ++iter) {
     Label disambig_sym = *iter;
     if (this->CreateArc(s, disambig_sym, &arc)) {
 #ifdef HAVE_OPENFST_GE_10400
       this->PushArc(s, arc);
 #else
       this->AddArc(s, arc);
 #endif
     }
   }
   this->SetArcs(s);  // mark the arcs as "done". [so HasArcs returns true].
 }
ContextFstImpl< Arc, LabelT >::Weight Final (StateId s)
Definition at line 148 of file context-fst-inl.h.
{
   assert(static_cast<size_t>(s) < state_seqs_.size());  // make sure state exists already.
   if (!this->HasFinal(s)) {  // Work out final-state weight.
     const vector<LabelT> &seq = state_seqs_[s];
     bool final_ok;
     assert(static_cast<int32>(seq.size()) == N_-1);
     if (P_ < N_ - 1) {
       /* Note that P_ (in zero based indexing) is the "central position", and for arcs out of
          this state the thing at P_ will be the one we expand.  If this is the subsequential symbol,
          it means we will output nothing (and will obviously never output anything).  Thus we make
          this state the final state.
       */
       final_ok = (seq[P_] == subsequential_symbol_);
     } else {
       /* If P_ == N_-1, then the "central phone" is the last one in the list (we have a left-context system).
          In this case everything is output immediately and there is no need for a subsequential symbol.
          Here, any state in the FST can be the final state.
       */
       final_ok = true;
     }
     Weight w = final_ok ? Weight::One() : Weight::Zero();
     this->SetFinal(s, w);
     return w;
   }
   return CacheImpl<Arc>::Final(s);
 }
bool Find (typename Arc::Label match_label)
Definition at line 377 of file context-fst-inl.h.
References ContextFst< Arc, LabelT >::CreateArc().
Referenced by ContextMatcher< Arc, LabelT >::Find_().
{
   assert(s_ != kNoStateId);
   // we know at this point that match_type_ == MATCH_OUTPUT.  we are matching output.
   if (match_label == kNoLabel) {
     // A ContextFst has no epsilons on its output.  So
     // we don't need to match self-loops on the other FST.
     ready_ = false;
     return false;
   } else if (match_label == 0) {
     arc_.ilabel = 0;
     arc_.olabel = kNoLabel;  // epsilon_L
     arc_.weight = Weight::One();
     arc_.nextstate = s_;  // loop.
     ready_ = true;
     return true;  // epsilon_L loop.
   } else {
     const ContextFst<Arc, LabelT> *cfst = static_cast<const ContextFst<Arc, LabelT>*> (fst_);  // we checked in initializer, that it is.
     ready_ = cfst->CreateArc(s_, match_label, &arc_);
     return ready_;
   }
 }
ContextFstImpl< Arc, LabelT >::Label FindLabel (const vector< LabelT > & label_info) private
Finds the label index corresponding to this context-window of phones.
Inserts it if necessary.
Definition at line 60 of file context-fst-inl.h.
{
   // Finds ilabel corresponding to this information.. Creates new ilabel if necessary.
   VectorToLabelIter iter = ilabel_map_.find(label_vec);
   if (iter == ilabel_map_.end()) {  // Not already in map.
     Label this_label = ilabel_info_.size();
     ilabel_info_.push_back(label_vec);
     ilabel_map_[label_vec] = this_label;
     return this_label;
   } else {
     return iter->second;
   }
 }
ContextFstImpl< Arc, LabelT >::StateId FindState (const vector< LabelT > & seq) private
Finds state-id corresponding to this vector of phones. Inserts it if necessary.
Definition at line 37 of file context-fst-inl.h.
{
   // Finds state-id corresponding to this vector of phones.  Inserts it if
   // necessary.
   assert(static_cast<int32>(seq.size()) == N_-1);
   VectorToStateIter iter = state_map_.find(seq);
   if (iter == state_map_.end()) {  // Not already in map.
     StateId this_state_id = (StateId)state_seqs_.size();
     //This check is not needed with OpenFst >= 1.4
 #ifndef HAVE_OPENFST_GE_10400
     StateId this_state_id_check = CacheImpl<Arc>::AddState();
     // goes back to VectorFstBaseImpl<Arc>, inherited via CacheFst<Arc>
     assert(this_state_id == this_state_id_check);
 #endif
     state_seqs_.push_back(seq);
     state_map_[seq] = this_state_id;
     return this_state_id;
   } else {
     return iter->second;
   }
 }
void InitArcIterator (StateId s, ArcIteratorData< Arc > * data)
Definition at line 213 of file context-fst-inl.h.
{
   if (!this->HasArcs(s))
     Expand(s);
   CacheImpl<Arc>::InitArcIterator(s, data);
 }
void InitStateIterator (StateIteratorData< Arc > * data) const inline virtual
Definition at line 372 of file context-fst.h.
{
   data->base = new StateIterator< ContextFst<A> >(*this);
 }
size_t NumArcs (StateId s)
Definition at line 180 of file context-fst-inl.h.
References KALDI_ASSERT, and fst::NumArcs().
{
   if (this->HasArcs(s)) {
     return CacheImpl<Arc>::NumArcs(s);
   }
   KALDI_ASSERT(s >= 0 && s < state_seqs_.size());
   const vector<LabelT> &seq = state_seqs_[s];
   KALDI_ASSERT(seq.size() == N_ - 1);
   if (!seq.empty() && seq.back() == subsequential_symbol_) {
     // State is not a "normal" state because it just saw the subsequential symbol,
     // hence it cannot accept phones.
     if (P_ == N_ - 1 || seq[P_] == subsequential_symbol_) { // don't
       // accept subsequential symbol.. c.f. logic in CreateArc().
       return disambig_syms_.size();
     } else {
       return disambig_syms_.size() + 1; // Accept disambig syms and
                                         // subsequential symbol.
     }
   } else {
     // For normal states, in general there is potentially an arc for each phone and an arc
     // for each disambiguation symbol, plus one for the subsequential symbol.
     return phone_syms_.size() + disambig_syms_.size() + 1;
   }
 }
size_t NumInputEpsilons (StateId s)
Definition at line 206 of file context-fst-inl.h.
{
   if (!this->HasArcs(s))
     Expand(s);
   return CacheImpl<Arc>::NumInputEpsilons(s);
 }
void ReadILabelInfo (std::istream & is, bool binary, vector< vector< I > > * info)
Useful utility function for reading these vectors from disk.
writes as int32 (see WriteILabelInfo above).
Definition at line 440 of file context-fst-inl.h.
References rnnlm::i, kaldi::ReadBasicType(), and kaldi::ReadIntegerVector().
Referenced by main(), and fst::TestContextFst().
{
   I sz = info->size();
   kaldi::ReadBasicType(is, binary, &sz);
   assert(info != NULL);
   info->resize(sz);
   for (int i = 0; i < sz; i++) {
     kaldi::ReadIntegerVector(is, binary, &((*info)[i]));
   }
 }
ContextFstImpl< Arc, LabelT >::StateId Start ()
Definition at line 75 of file context-fst-inl.h.
{
   if (! CacheImpl<Arc>::HasStart()) {
     vector<LabelT> vec(N_-1, 0);  // Vector of N_-1 epsilons. [e.g. N = 3].
     StateId s = FindState(vec);
     assert(s == 0);
     this->SetStart(s);
   }
   return CacheImpl<Arc>::Start();
 }
void WriteILabelInfo (std::ostream & os, bool binary, const vector< vector< I > > & info)
Useful utility function for writing these vectors to disk.
writes as int32 for binary compatibility since I will typically be "int".
Definition at line 429 of file context-fst-inl.h.
References rnnlm::i, kaldi::WriteBasicType(), and kaldi::WriteIntegerVector().
Referenced by main(), and fst::TestContextFst().
{
   I sz = info.size();
   kaldi::WriteBasicType(os, binary, sz);
   for (I i = 0; i < sz; i++) {
     kaldi::WriteIntegerVector(os, binary, info[i]);
   }
 }