Kaldi: "Classes for opening streams"
"Classes for opening streams"
This group contains the Input and Output classes, which are provided to open streams for reading and writing in Kaldi code; for an explanation of how this fits into the bigger picture of Kaldi I/O, see How to open files in Kaldi.
Classes
class Output
class Input
Enumerations
enum OutputType { kNoOutput, kFileOutput, kStandardOutput, kPipeOutput }
enum InputType {
kNoInput, kFileInput, kStandardInput, kOffsetFileInput,
kPipeInput
}
Functions
OutputType ClassifyWxfilename (const std::string &wxfilename)
ClassifyWxfilename interprets filenames as follows:
InputType ClassifyRxfilename (const std::string &rxfilename)
ClassifyRxfilenames interprets filenames for reading as follows:
template<class C >
void ReadKaldiObject (const std::string &filename, C *c)
template<class C >
void WriteKaldiObject (const C &c, const std::string &filename, bool binary)
std::string PrintableRxfilename (std::string rxfilename)
PrintableRxfilename turns the rxfilename into a more human-readable form for error reporting, i.e.
std::string PrintableWxfilename (std::string wxfilename)
PrintableWxfilename turns the filename into a more human-readable form for error reporting, i.e.
Detailed Description
This group contains the Input and Output classes, which are provided to open streams for reading and writing in Kaldi code; for an explanation of how this fits into the bigger picture of Kaldi I/O, see How to open files in Kaldi.
Enumeration Type Documentation
enum InputType
Enumerator
kNoInput
kFileInput
kStandardInput
kOffsetFileInput
kPipeInput
Definition at line 103 of file kaldi-io.h.
                {
   kNoInput,
   kFileInput,
   kStandardInput,
   kOffsetFileInput,
   kPipeInput
 };
enum OutputType
Enumerator
kNoOutput
kFileOutput
kStandardOutput
kPipeOutput
Definition at line 87 of file kaldi-io.h.
                 {
   kNoOutput,
   kFileOutput,
   kStandardOutput,
   kPipeOutput
 };
Function Documentation
InputType ClassifyRxfilename (const std::string & rxfilename)
ClassifyRxfilenames interprets filenames for reading as follows:
kNoInput: invalid filenames (leading or trailing space, things that look like wspecifiers and rspecifiers or pipes to write to with trailing |.
kFileInput: normal filenames
kStandardInput: the empty string or "-"
kPipeInput: e.g. "| gzip -c > blah.gz"
kOffsetFileInput: offsets into files, e.g. /some/filename:12970
Definition at line 128 of file kaldi-io.cc.
References rnnlm::d, KALDI_WARN, kaldi::kFileInput, kaldi::kNoInput, kaldi::kOffsetFileInput, kaldi::kPipeInput, and kaldi::kStandardInput.
Referenced by Input::OpenInternal(), and kaldi::UnitTestClassifyRxfilename().
{
   const char *c = filename.c_str();
   if (*c == '\0' || (*c == '-' && c[1] == '\0')) return kStandardInput;  // ""
   // or "-".
   else if (*c == '|') return kNoInput;  // An output pipe like "|blah": not
   // valid for input.
   else if (isspace(*c) || isspace(c[filename.length()-1])) return kNoInput;  //
   // Leading or trailing space.
   else if ((*c == 't'||*c == 'b') && c[1] == ',') {
     // We have detected that the user has supplied a wspecifier
     // or rspecifier (as in kaldi-table.h) where a wxfilename was
     // needed.  Since this is almost certain not to be a real filename
     // (and would cause a lot of confusion if it were a real filename), we
     // refuse to deal with it upfront.
     return kNoInput;
   } else {
     const char *d = c;
     while (d[1] != '\0') d++;  // go to last char.
     if (*d == '|') return kPipeInput;  // an input pipe.
     if (isspace(*d)) return kNoInput;  // trailing space which is never valid.
     else if (isdigit(*d)) {
       // OK, it could be an offset into a file
       // which is not allowed.
       while (isdigit(*d) && d > c) d--;
       if (*d == ':') return kOffsetFileInput;  // Filename is like
       // some_file:12345
       else
         return kFileInput;
     } else {
       // at this point it matched no other pattern so we assume a filename, but
       // we check for '|' as it's a common source of errors to have pipe
       // commands without the pipe in the right place.  Say that it can't be
       // classified in this case.
       if (strchr(c, '|') != NULL) {
         KALDI_WARN << "Trying to classify rxfilename with pipe symbol in the"
                       " wrong place (pipe without | at the end?): " << filename;
         return kNoInput;
       }
       return kFileInput;  // matched no other pattern: assume it's an actual
       // filename.
     }
   }
 }
OutputType ClassifyWxfilename (const std::string & wxfilename)
ClassifyWxfilename interprets filenames as follows:
kNoOutput: invalid filenames (leading or trailing space, things that look like wspecifiers and rspecifiers or like pipes to read from with leading |.
kFileOutput: Normal filenames
kStandardOutput: The empty string or "-", interpreted as standard output
kPipeOutput: pipes, e.g. "gunzip -c some_file.gz |"
Definition at line 80 of file kaldi-io.cc.
References rnnlm::d, KALDI_WARN, kaldi::kFileOutput, kaldi::kNoOutput, kaldi::kPipeOutput, and kaldi::kStandardOutput.
Referenced by Output::Open(), TableWriterBothImpl< Holder >::Open(), kaldi::UnitTestClassifyWxfilename(), and Output::~Output().
{
   const char *c = filename.c_str();
   if (*c == '\0' || (*c == '-' && c[1] == '\0')) return kStandardOutput;  // ""
   // or "-".
   else if (*c == '|') return kPipeOutput;  // An output pipe like "|blah".
   else if (isspace(*c) || isspace(c[filename.length()-1])) return kNoOutput;  //
   // Leading or trailing space: can't interpret this.
   else if ((*c == 't'||*c == 'b') && c[1] == ',') {
     // We have detected that the user has supplied a wspecifier
     // or rspecifier (as in kaldi-table.h) where a wxfilename was
     // needed.  Since this is almost certain not to be a real filename
     // (and would cause confusion if it were a real filename), we
     // refuse to deal with it.
     return kNoOutput;
   } else {
     const char *d = c;
     while (d[1] != '\0') d++;  // go to last char.
     if (*d == '|' || isspace(*d)) return kNoOutput;  // An input pipe (not
     // allowed in this context) or trailing space which is just wrong.
     else if (isdigit(*d)) {
       // OK, it could be a file, but we have to see if it's an offset into a
       // file, which is not allowed.
       while (isdigit(*d) && d > c) d--;
       if (*d == ':') return kNoOutput;  // Filename is like some_file:12345;
       // not allowed,
       else
         return kFileOutput;
       // as we cannot write to an offset into a file (and if we interpreted it
       // as an actual filename, the reading code would misinterpret it as an
       // offset.
     } else {
       // at this point it matched no other pattern so we assume a filename, but
       // we check for '|' as it's a common source of errors to have pipe
       // commands without the pipe in the right place.  Say that it can't be
       // classified.
       if (strchr(c, '|') != NULL) {
         KALDI_WARN << "Trying to classify wxfilename with pipe symbol in the"
                       " wrong place (pipe without | at the beginning?): " <<
                       filename;
         return kNoOutput;
       }
       return kFileOutput;  // matched no other pattern: assume it's an actual
       // filename.
     }
   }
 }
std::string PrintableRxfilename (std::string rxfilename)
PrintableRxfilename turns the rxfilename into a more human-readable form for error reporting, i.e.
it does quoting and escaping and replaces "" or "-" with "standard input".
Definition at line 56 of file kaldi-io.cc.
References ParseOptions::Escape().
Referenced by SequentialTableReaderArchiveImpl< Holder >::Close(), RandomAccessTableReaderSortedArchiveImpl< Holder >::FindKeyInternal(), kaldi::GetUtterancePairs(), RandomAccessTableReaderMapped< Holder >::HasKey(), RandomAccessTableReaderScriptImpl< Holder >::HasKeyInternal(), Input::Input(), SequentialTableReaderScriptImpl< Holder >::LoadCurrent(), main(), SequentialTableReaderArchiveImpl< Holder >::Next(), SequentialTableReaderScriptImpl< Holder >::Open(), SequentialTableReaderArchiveImpl< Holder >::Open(), PipeInputImpl::Open(), TableWriterScriptImpl< Holder >::Open(), RandomAccessTableReaderScriptImpl< Holder >::Open(), RandomAccessTableReaderArchiveImplBase< Holder >::Open(), Input::OpenInternal(), LangModelFst::Read(), fst::ReadFstKaldi(), RandomAccessTableReaderArchiveImplBase< Holder >::ReadNextObject(), kaldi::ReadPhoneMap(), kaldi::ReadScriptFile(), kaldi::ReadSharedPhonesList(), kaldi::ReadSymbolList(), SequentialTableReaderScriptImpl< Holder >::Value(), RandomAccessTableReaderMapped< Holder >::Value(), RandomAccessTableReaderDSortedArchiveImpl< Holder >::Value(), RandomAccessTableReaderSortedArchiveImpl< Holder >::Value(), RandomAccessTableReaderUnsortedArchiveImpl< Holder >::Value(), TableWriterScriptImpl< Holder >::Write(), SequentialTableReaderArchiveImpl< Holder >::~SequentialTableReaderArchiveImpl(), and SequentialTableReaderScriptImpl< Holder >::~SequentialTableReaderScriptImpl().
{
   if (rxfilename == "" || rxfilename == "-") {
     return "standard input";
   } else {
     // If this call to Escape later causes compilation issues,
     // just replace it with "return rxfilename"; it's only a
     // pretty-printing issue.
     return ParseOptions::Escape(rxfilename);
   }
 }
std::string PrintableWxfilename (std::string wxfilename)
PrintableWxfilename turns the filename into a more human-readable form for error reporting, i.e.
it does quoting and escaping and replaces "" or "-" with "standard output".
Definition at line 68 of file kaldi-io.cc.
References ParseOptions::Escape().
Referenced by main(), Output::Open(), Output::Output(), kaldi::TypeThreeUsage(), kaldi::TypeTwoUsage(), LangModelFst::Write(), TableWriterArchiveImpl< Holder >::Write(), TableWriterScriptImpl< Holder >::Write(), TableWriterBothImpl< Holder >::Write(), fst::WriteFstKaldi(), kaldi::WriteScriptFile(), Output::~Output(), and PipeOutputImpl::~PipeOutputImpl().
{
   if (wxfilename == "" || wxfilename == "-") {
     return "standard output";
   } else {
     // If this call to Escape later causes compilation issues,
     // just replace it with "return rxfilename"; it's only a
     // pretty-printing issue.
     return ParseOptions::Escape(wxfilename);
   }
 }
void kaldi::ReadKaldiObject (const std::string & filename, C * c) inline
Definition at line 236 of file kaldi-io.h.
References Input::Stream().
Referenced by kaldi::BuildConstArpaLm(), ComputeLogPosteriors(), ComputeScores(), NaturalGradientAffineComponent::Init(), AffineComponent::Init(), AffineComponentPreconditioned::Init(), AffineComponentPreconditionedOnline::Init(), PerElementScaleComponent::Init(), PerElementOffsetComponent::Init(), ConvolutionComponent::Init(), Convolutional1dComponent::Init(), FixedScaleComponent::InitFromConfig(), FixedBiasComponent::InitFromConfig(), FixedScaleComponent::InitFromString(), FixedBiasComponent::InitFromString(), main(), and kaldi::RunPerSpeaker().
{
   bool binary_in;
   Input ki(filename, &binary_in);
   c->Read(ki.Stream(), binary_in);
 }
void kaldi::WriteKaldiObject (const C & c, const std::string & filename, bool binary) inline
Definition at line 243 of file kaldi-io.h.
References Output::Stream().
Referenced by kaldi::BuildConstArpaLm(), main(), kaldi::TypeThreeUsage(), kaldi::TypeTwoUsage(), kaldi::nnet2::UnitTestAffineComponent(), kaldi::nnet2::UnitTestAffineComponentPreconditioned(), kaldi::nnet2::UnitTestAffineComponentPreconditionedOnline(), kaldi::nnet2::UnitTestConvolutional1dComponent(), and NnetLdaStatsAccumulator::WriteStats().
{
   Output ko(filename, binary);
   c.Write(ko.Stream(), binary);
 }