Kaldi: "Implementation classes for Table types"
"Implementation classes for Table types"
This group is for classes that implement specific ways of reading and writing Tables; see also "Table types and related functions", "Specific Table types", "Specific Table types", and for a description of the Table concept see The Table concept.
Classes
class SequentialTableReaderImplBase< Holder >
class SequentialTableReaderScriptImpl< Holder >
class SequentialTableReaderArchiveImpl< Holder >
class TableWriterImplBase< Holder >
class TableWriterArchiveImpl< Holder >
class TableWriterScriptImpl< Holder >
class TableWriterBothImpl< Holder >
class RandomAccessTableReaderImplBase< Holder >
class RandomAccessTableReaderScriptImpl< Holder >
class RandomAccessTableReaderArchiveImplBase< Holder >
class RandomAccessTableReaderDSortedArchiveImpl< Holder >
class RandomAccessTableReaderSortedArchiveImpl< Holder >
class RandomAccessTableReaderUnsortedArchiveImpl< Holder >
Functions
SequentialTableReader (const std::string &rspecifier)
bool Open (const std::string &rspecifier)
bool Close ()
bool IsOpen () const
std::string Key ()
void FreeCurrent ()
const T & Value ()
void Next ()
bool Done ()
~SequentialTableReader ()
TableWriter (const std::string &wspecifier)
bool IsOpen () const
bool Open (const std::string &wspecifier)
void Write (const std::string &key, const T &value) const
void Flush ()
bool Close ()
~TableWriter ()
RandomAccessTableReader (const std::string &rspecifier)
bool Open (const std::string &rspecifier)
bool HasKey (const std::string &key)
const T & Value (const std::string &key)
bool Close ()
~RandomAccessTableReader ()
void CheckImpl () const
void CheckImpl () const
void CheckImpl () const
RandomAccessTableReaderMapped (const std::string &table_rxfilename, const std::string &utt2spk_rxfilename)
Note: "utt2spk_rxfilename" will in the normal case be an rxfilename for an utterance to speaker map, but this code is general; it accepts a generic map.
bool Open (const std::string &table_rxfilename, const std::string &utt2spk_rxfilename)
Note: when calling Open, utt2spk_rxfilename may be empty.
bool HasKey (const std::string &key)
const T & Value (const std::string &key)
Detailed Description
This group is for classes that implement specific ways of reading and writing Tables; see also "Table types and related functions", "Specific Table types", "Specific Table types", and for a description of the Table concept see The Table concept.
Function Documentation
void CheckImpl () const private
Definition at line 2214 of file kaldi-table-inl.h.
References KALDI_ERR.
{
   if (!impl_) {
     KALDI_ERR << "Trying to use empty RandomAccessTableReader (perhaps you "
               << "passed the empty string as an argument to a program?)";
   }
 }
void CheckImpl () const private
Definition at line 2206 of file kaldi-table-inl.h.
References KALDI_ERR.
{
   if (!impl_) {
     KALDI_ERR << "Trying to use empty SequentialTableReader (perhaps you "
               << "passed the empty string as an argument to a program?)";
   }
 }
void CheckImpl () const private
Definition at line 2222 of file kaldi-table-inl.h.
References KALDI_ERR.
{
   if (!impl_) {
     KALDI_ERR << "Trying to use empty TableWriter (perhaps you "
               << "passed the empty string as an argument to a program?)";
   }
 }
bool Close ()
Definition at line 2191 of file kaldi-table-inl.h.
{
   CheckImpl();
   bool ans =impl_->Close();
   delete impl_;
   impl_ = NULL;
   return ans;
 }
bool Close ()
Definition at line 566 of file kaldi-table-inl.h.
Referenced by main(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   bool ans = impl_->Close();
   delete impl_;  // We don't keep around empty impl_ objects.
   impl_ = NULL;
   return ans;
 }
bool Close ()
Definition at line 1197 of file kaldi-table-inl.h.
Referenced by kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), kaldi::TestLatticeTableCross(), kaldi::UnitTestTableRandomBothDouble(), kaldi::UnitTestTableRandomBothDoubleMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   bool ans = impl_->Close();
   delete impl_;  // We don't keep around non-open impl_ objects
                  // [c.f. definition of IsOpen()]
   impl_ = NULL;
   return ans;
 }
bool Done () inline
Definition at line 613 of file kaldi-table-inl.h.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::nnet2::DoBackpropParallel(), kaldi::GetFeatureMeanAndVariance(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), NnetExampleBackgroundReader::ReadExamples(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   return impl_->Done();
 }
void Flush ()
Definition at line 1191 of file kaldi-table-inl.h.
{
   CheckImpl();
   impl_->Flush();
 }
void FreeCurrent ()
Definition at line 591 of file kaldi-table-inl.h.
Referenced by main(), CRnnLM::setUnkPenalty(), and kaldi::TypeOneUsage().
{
   CheckImpl();
   impl_->FreeCurrent();
 }
bool HasKey (const std::string & key)
Definition at line 2175 of file kaldi-table-inl.h.
References kaldi::IsToken(), and KALDI_ERR.
Referenced by kaldi::AccCmvnStatsWrapper(), kaldi::AccumulateForUtterance(), ComputeScores(), main(), kaldi::ProcessUtterance(), kaldi::RunPerSpeaker(), kaldi::UnitTestTableRandomBothDouble(), and kaldi::UnitTestTableRandomBothDoubleMatrix().
{
   CheckImpl();
   if (!IsToken(key))
     KALDI_ERR << "Invalid key \"" << key << '"';
   return impl_->HasKey(key);
 }
bool HasKey (const std::string & key)
Definition at line 2257 of file kaldi-table-inl.h.
References KALDI_ERR, and kaldi::PrintableRxfilename().
Referenced by main(), and kaldi::ProcessUtterance().
{
   // We don't check IsOpen, we let the call go through to the member variable
   // (reader_), which will crash with a more informative error message than
   // we can give here, as we don't any longer know the rxfilename.
   if (token_reader_.IsOpen()) {  // We need to map the key from utt to spk.
     if (!token_reader_.HasKey(utt))
       KALDI_ERR << "Attempting to read key " << utt << ", which is not present "
                 << "in utt2spk map or similar map being read from "
                 << PrintableRxfilename(utt2spk_rxfilename_);
     const std::string &spk = token_reader_.Value(utt);
     return reader_.HasKey(spk);
   } else {
     return reader_.HasKey(utt);
   }
 }
bool IsOpen () const
Definition at line 576 of file kaldi-table-inl.h.
{
   return (impl_ != NULL);  // Because we delete the object whenever
   // that object is not open.  Thus, the IsOpen functions of the
   // Impl objects are not really needed.
 }
bool IsOpen () const
Definition at line 1144 of file kaldi-table-inl.h.
Referenced by kaldi::AlignUtteranceWrapper(), kaldi::DecodeUtterance(), DecodeUtterance(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::DecodeUtteranceLatticeSimple(), kaldi::DecodeUtteranceLatticeTracking(), main(), and DecodeUtteranceLatticeFasterClass::~DecodeUtteranceLatticeFasterClass().
{
   return (impl_ != NULL);
 }
std::string Key () inline
Definition at line 583 of file kaldi-table-inl.h.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), main(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   return impl_->Key();  // this call may throw if called wrongly in other ways,
   // e.g. eof.
 }
void Next ()
Definition at line 607 of file kaldi-table-inl.h.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::nnet2::DoBackpropParallel(), kaldi::GetFeatureMeanAndVariance(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), NnetExampleBackgroundReader::ReadExamples(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   impl_->Next();
 }
bool Open (const std::string & rspecifier)
Definition at line 2140 of file kaldi-table-inl.h.
References RspecifierOptions::called_sorted, kaldi::ClassifyRspecifier(), KALDI_ERR, KALDI_WARN, kaldi::kArchiveRspecifier, kaldi::kNoRspecifier, kaldi::kScriptRspecifier, and RspecifierOptions::sorted.
Referenced by main(), and RandomAccessTableReader< Holder >::RandomAccessTableReader().
{
   if (IsOpen())
     KALDI_ERR << "Already open.";
   RspecifierOptions opts;
   RspecifierType rs = ClassifyRspecifier(rspecifier, NULL, &opts);
   switch (rs) {
     case kScriptRspecifier:
       impl_ = new RandomAccessTableReaderScriptImpl<Holder>();
       break;
     case kArchiveRspecifier:
       if (opts.sorted) {
         if (opts.called_sorted)  // "doubly" sorted case.
           impl_ = new RandomAccessTableReaderDSortedArchiveImpl<Holder>();
         else
           impl_ = new RandomAccessTableReaderSortedArchiveImpl<Holder>();
       } else {
         impl_ = new RandomAccessTableReaderUnsortedArchiveImpl<Holder>();
       }
       break;
     case kNoRspecifier: default:
       KALDI_WARN << "Invalid rspecifier: "
                  << rspecifier;
       return false;
   }
   if (impl_->Open(rspecifier)) {
     return true;
   } else {
     // Warning will already have been printed.
     delete impl_;
     impl_ = NULL;
     return false;
   }
 }
bool Open (const std::string & rspecifier)
Definition at line 538 of file kaldi-table-inl.h.
References kaldi::ClassifyRspecifier(), KALDI_ERR, KALDI_WARN, kaldi::kArchiveRspecifier, kaldi::kNoRspecifier, and kaldi::kScriptRspecifier.
Referenced by main(), and SequentialTableReader< Holder >::SequentialTableReader().
{
   if (IsOpen())
     if (!Close())
       KALDI_ERR << "Could not close previously open object.";
   // now impl_ will be NULL.
   RspecifierType wt = ClassifyRspecifier(rspecifier, NULL, NULL);
   switch (wt) {
     case kArchiveRspecifier:
       impl_ = new SequentialTableReaderArchiveImpl<Holder>();
       break;
     case kScriptRspecifier:
       impl_ = new SequentialTableReaderScriptImpl<Holder>();
       break;
     case kNoRspecifier: default:
       KALDI_WARN << "Invalid rspecifier " << rspecifier;
       return false;
   }
   if (!impl_->Open(rspecifier)) {
     delete impl_;
     impl_ = NULL;
     return false;  // sub-object will have printed warnings.
   } else {
     return true;
   }
 }
bool Open (const std::string & wspecifier)
Definition at line 1150 of file kaldi-table-inl.h.
References kaldi::ClassifyWspecifier(), KALDI_ASSERT, KALDI_ERR, KALDI_WARN, kaldi::kArchiveWspecifier, kaldi::kBothWspecifier, kaldi::kNoWspecifier, and kaldi::kScriptWspecifier.
Referenced by main(), and TableWriter< Holder >::TableWriter().
{
   if (IsOpen()) {
     if (!Close())  // call Close() yourself to suppress this exception.
       KALDI_ERR << "TableWriter::Open, failed to close previously open writer.";
   }
   KALDI_ASSERT(impl_ == NULL);
   WspecifierType wtype = ClassifyWspecifier(wspecifier, NULL, NULL, NULL);
   switch (wtype) {
     case kBothWspecifier:
       impl_ = new TableWriterBothImpl<Holder>();
       break;
     case kArchiveWspecifier:
       impl_ = new TableWriterArchiveImpl<Holder>();
       break;
     case kScriptWspecifier:
       impl_ = new TableWriterScriptImpl<Holder>();
       break;
     case kNoWspecifier: default:
       KALDI_WARN << "ClassifyWspecifier: invalid wspecifier " << wspecifier;
       return false;
   }
   if (impl_->Open(wspecifier)) {
     return true;
   } else {  // The class will have printed a more specific warning.
     delete impl_;
     impl_ = NULL;
     return false;
   }
 }
bool Open (const std::string & table_rxfilename, const std::string & utt2spk_rxfilename)
Note: when calling Open, utt2spk_rxfilename may be empty.
Definition at line 2238 of file kaldi-table-inl.h.
References KALDI_ASSERT.
{
   if (reader_.IsOpen()) reader_.Close();
   if (token_reader_.IsOpen()) token_reader_.Close();
   KALDI_ASSERT(!table_rxfilename.empty());
   if (!reader_.Open(table_rxfilename)) return false;  // will have printed
   // warning internally, probably.
   if (!utt2spk_rxfilename.empty()) {
     if (!token_reader_.Open(utt2spk_rxfilename)) {
       reader_.Close();
       return false;
     }
   }
   return true;
 }
RandomAccessTableReader (const std::string & rspecifier) explicit
Definition at line 2131 of file kaldi-table-inl.h.
References KALDI_ERR, and RandomAccessTableReader< Holder >::Open().
                                                                              :
     impl_(NULL) {
   if (rspecifier != "" && !Open(rspecifier))
     KALDI_ERR << "Error opening RandomAccessTableReader object "
         " (rspecifier is: " << rspecifier << ")";
 }
RandomAccessTableReaderMapped (const std::string & table_rxfilename, const std::string & utt2spk_rxfilename)
Note: "utt2spk_rxfilename" will in the normal case be an rxfilename for an utterance to speaker map, but this code is general; it accepts a generic map.
Definition at line 2230 of file kaldi-table-inl.h.
                                         :
     reader_(table_rxfilename), token_reader_(table_rxfilename.empty() ? "" :
                                              utt2spk_rxfilename),
     utt2spk_rxfilename_(utt2spk_rxfilename) { }
SequentialTableReader (const std::string & rspecifier) explicit
Definition at line 531 of file kaldi-table-inl.h.
References KALDI_ERR, and SequentialTableReader< Holder >::Open().
                                                                  : impl_(NULL) {
   if (rspecifier != "" && !Open(rspecifier))
     KALDI_ERR << "Error constructing TableReader: rspecifier is " << rspecifier;
 }
TableWriter (const std::string & wspecifier) explicit
Definition at line 1136 of file kaldi-table-inl.h.
References KALDI_ERR, and TableWriter< Holder >::Open().
                                                            : impl_(NULL) {
   if (wspecifier != "" && !Open(wspecifier)) {
     KALDI_ERR << "TableWriter: failed to write to "
               << wspecifier;
   }
 }
const RandomAccessTableReader< Holder >::T & Value (const std::string & key)
Definition at line 2185 of file kaldi-table-inl.h.
Referenced by kaldi::AccCmvnStatsWrapper(), kaldi::AccumulateForUtterance(), ComputeScores(), main(), kaldi::ProcessUtterance(), kaldi::RunPerSpeaker(), kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), kaldi::TestLatticeTableCross(), kaldi::UnitTestTableRandomBothDouble(), and kaldi::UnitTestTableRandomBothDoubleMatrix().
{
   CheckImpl();
   return impl_->Value(key);
 }
const SequentialTableReader< Holder >::T & Value ()
Definition at line 599 of file kaldi-table-inl.h.
Referenced by ComputeLogPosteriors(), ComputeScores(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::nnet2::DoBackpropParallel(), kaldi::GetFeatureMeanAndVariance(), main(), kaldi::nnet2::NnetDiscriminativeUpdateParallel(), NnetExampleBackgroundReader::ReadExamples(), kaldi::RunPerSpeaker(), CRnnLM::setUnkPenalty(), kaldi::TypeOneUsage(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), and kaldi::UnitTestTableSequentialInt32VectorVectorBoth().
{
   CheckImpl();
   return impl_->Value();  // This may throw (if LoadCurrent() returned false you
                           // are safe.).
 }
const Holder::T & Value (const std::string & key)
Definition at line 2274 of file kaldi-table-inl.h.
References KALDI_ERR, and kaldi::PrintableRxfilename().
Referenced by main(), and kaldi::ProcessUtterance().
{
   if (token_reader_.IsOpen()) {  // We need to map the key from utt to spk.
     if (!token_reader_.HasKey(utt))
       KALDI_ERR << "Attempting to read key " << utt << ", which is not present "
                 << "in utt2spk map or similar map being read from "
                 << PrintableRxfilename(utt2spk_rxfilename_);
     const std::string &spk = token_reader_.Value(utt);
     return reader_.Value(spk);
   } else {
     return reader_.Value(utt);
   }
 }
void Write (const std::string & key, const T & value) const inline
Definition at line 1181 of file kaldi-table-inl.h.
References KALDI_ERR.
Referenced by kaldi::AlignUtteranceWrapper(), ComputeLogPosteriors(), CopyExcludedFeats(), CopyIncludedFeats(), kaldi::DecodeUtterance(), DecodeUtterance(), kaldi::DecodeUtteranceLatticeFaster(), kaldi::DecodeUtteranceLatticeSimple(), kaldi::DecodeUtteranceLatticeTracking(), main(), kaldi::nnet2::ProcessFile(), kaldi::nnet3::ProcessFile(), kaldi::RunPerSpeaker(), kaldi::TestCompactLatticeTable(), kaldi::TestCompactLatticeTableCross(), kaldi::TestLatticeTable(), kaldi::TestLatticeTableCross(), kaldi::TypeOneUsage(), kaldi::UnitTestTableRandomBothDouble(), kaldi::UnitTestTableRandomBothDoubleMatrix(), kaldi::UnitTestTableSequentialBaseFloatVectorBoth(), kaldi::UnitTestTableSequentialBool(), kaldi::UnitTestTableSequentialDouble(), kaldi::UnitTestTableSequentialDoubleBoth(), kaldi::UnitTestTableSequentialDoubleMatrixBoth(), kaldi::UnitTestTableSequentialInt32(), kaldi::UnitTestTableSequentialInt32PairVectorBoth(), kaldi::UnitTestTableSequentialInt32Script(), kaldi::UnitTestTableSequentialInt32VectorBoth(), kaldi::UnitTestTableSequentialInt32VectorVectorBoth(), DecodeUtteranceLatticeFasterClass::~DecodeUtteranceLatticeFasterClass(), DeterminizeLatticeTask::~DeterminizeLatticeTask(), IvectorExtractTask::~IvectorExtractTask(), and NnetLogprobTask::~NnetLogprobTask().
{
   CheckImpl();
   if (!impl_->Write(key, value))
     KALDI_ERR << "Error in TableWriter::Write";
   // More specific warning will have
   // been printed in the Write function.
 }
~RandomAccessTableReader ()
Definition at line 2200 of file kaldi-table-inl.h.
References KALDI_ERR.
{
   if (IsOpen() && !Close())  // call Close() yourself to stop this being thrown.
     KALDI_ERR << "failure detected in destructor.";
 }
~SequentialTableReader ()
Definition at line 620 of file kaldi-table-inl.h.
{
   delete impl_;
   // Destructor of impl_ may throw.
 }
~TableWriter ()
Definition at line 1207 of file kaldi-table-inl.h.
References KALDI_ERR.
{
   if (IsOpen() && !Close()) {
     KALDI_ERR << "Error closing TableWriter [in destructor].";
   }
 }