Kaldi: FeatureExtraction
FeatureExtraction
Files
file resample.h
]
Classes
struct FbankOptions
FbankOptions contains basic options for computing FBANK features It only includes things that can be done in a "stateless" way, i.e.
class Fbank
Class for computing mel-filterbank features; see Computing MFCC features for more information.
struct MelBanksOptions
struct FrameExtractionOptions
struct FeatureWindowFunction
struct DeltaFeaturesOptions
class DeltaFeatures
struct ShiftedDeltaFeaturesOptions
class ShiftedDeltaFeatures
struct SlidingWindowCmnOptions
struct MfccOptions
MfccOptions contains basic options for computing MFCC features It only includes things that can be done in a "stateless" way, i.e.
class Mfcc
Class for computing MFCC features; see Computing MFCC features for more information.
struct PlpOptions
PlpOptions contains basic options for computing PLP features.
class Plp
Class for computing PLP features.
struct SpectrogramOptions
SpectrogramOptions contains basic options for computing SPECTROGRAM features It only includes things that can be done in a "stateless" way, i.e.
class Spectrogram
Class for computing SPECTROGRAM features; see Computing MFCC features for more information.
class MelBanks
struct PitchExtractionOptions
struct ProcessPitchOptions
class OnlinePitchFeature
class OnlineProcessPitch
This online-feature class implements post processing of pitch features.
class ArbitraryResample
Class ArbitraryResample allows you to resample a signal (assumed zero outside the sample region, not periodic) at arbitrary specified time values, which don't have to be linearly spaced.
class LinearResample
LinearResample is a special case of ArbitraryResample, where we want to resample a signal at linearly spaced intervals (this means we want to upsample or downsample the signal).
struct Sinusoid
class SinusoidDetector
struct MultiSinusoidDetectorConfig
This configuration class is for the frame-by-frame detection of cases where there are one or two sinusoids that can explain a lot of the energy in the signal.
struct MultiSinusoidDetectorOutput
class MultiSinusoidDetector
Functions
int32 NumFrames (int32 nsamp, const FrameExtractionOptions &opts)
void Dither (VectorBase< BaseFloat > *waveform, BaseFloat dither_value)
void Preemphasize (VectorBase< BaseFloat > *waveform, BaseFloat preemph_coeff)
void ExtractWindow (const VectorBase< BaseFloat > &wave, int32 f, const FrameExtractionOptions &opts, const FeatureWindowFunction &window_function, Vector< BaseFloat > *window, BaseFloat *log_energy_pre_window)
void ExtractWaveformRemainder (const VectorBase< BaseFloat > &wave, const FrameExtractionOptions &opts, Vector< BaseFloat > *wave_remainder)
void ComputePowerSpectrum (VectorBase< BaseFloat > *waveform)
void MaxNormalizeEnergy (Matrix< BaseFloat > *feats)
void ComputeDeltas (const DeltaFeaturesOptions &delta_opts, const MatrixBase< BaseFloat > &input_features, Matrix< BaseFloat > *output_features)
void ComputeShiftedDeltas (const ShiftedDeltaFeaturesOptions &delta_opts, const MatrixBase< BaseFloat > &input_features, Matrix< BaseFloat > *output_features)
void SpliceFrames (const MatrixBase< BaseFloat > &input_features, int32 left_context, int32 right_context, Matrix< BaseFloat > *output_features)
void ReverseFrames (const MatrixBase< BaseFloat > &input_features, Matrix< BaseFloat > *output_features)
void GetEqualLoudnessVector (const MelBanks &mel_banks, Vector< BaseFloat > *ans)
void InitIdftBases (int32 n_bases, int32 dimension, Matrix< BaseFloat > *mat_out)
BaseFloat ComputeLpc (const VectorBase< BaseFloat > &autocorr_in, Vector< BaseFloat > *lpc_out)
void SlidingWindowCmn (const SlidingWindowCmnOptions &opts, const MatrixBase< BaseFloat > &input, MatrixBase< BaseFloat > *output)
Applies sliding-window cepstral mean and/or variance normalization.
void ComputeLifterCoeffs (BaseFloat Q, VectorBase< BaseFloat > *coeffs)
BaseFloat Durbin (int n, const BaseFloat *pAC, BaseFloat *pLP, BaseFloat *pTmp)
void Lpc2Cepstrum (int n, const BaseFloat *pLPC, BaseFloat *pCepst)
void ComputeKaldiPitch (const PitchExtractionOptions &opts, const VectorBase< BaseFloat > &wave, Matrix< BaseFloat > *output)
This function extracts (pitch, NCCF) per frame, using the pitch extraction method described in "A Pitch Extraction Algorithm Tuned for Automatic Speech Recognition", Pegah Ghahremani, Bagher BabaAli, Daniel Povey, Korbinian Riedhammer, Jan Trmal and Sanjeev Khudanpur, ICASSP 2014.
void ProcessPitch (const ProcessPitchOptions &opts, const MatrixBase< BaseFloat > &input, Matrix< BaseFloat > *output)
This function processes the raw (NCCF, pitch) quantities computed by ComputeKaldiPitch, and processes them into features.
void ComputeAndProcessKaldiPitch (const PitchExtractionOptions &pitch_opts, const ProcessPitchOptions &process_opts, const VectorBase< BaseFloat > &wave, Matrix< BaseFloat > *output)
This function combines ComputeKaldiPitch and ProcessPitch.
void AddSinusoid (BaseFloat samp_freq, const Sinusoid &sinusoid, VectorBase< BaseFloat > *signal)
void DetectSinusoids (const VectorBase< BaseFloat > &signal, MultiSinusoidDetector *detector, Matrix< BaseFloat > *output)
Detailed Description
Function Documentation
void AddSinusoid (BaseFloat samp_freq, const Sinusoid & sinusoid, VectorBase< BaseFloat > * signal)
Definition at line 31 of file sinusoid-detection.cc.
References Sinusoid::amplitude, kaldi::ComplexMul(), VectorBase< Real >::Data(), VectorBase< Real >::Dim(), Sinusoid::freq, M_2PI, and Sinusoid::phase.
Referenced by MultiSinusoidDetector::GetNextFrame(), kaldi::UnitTestAddSinusoid(), kaldi::UnitTestSinusoidDetector(), and kaldi::UnitTestSinusoidDetectorNoisy().
{
   // treat "factor" as a complex variable equal to exp(i * 2 pi freq / samp_freq); it's
   // the factor by which we multiply on each frame.
   BaseFloat factor_real = cos(M_2PI * sinusoid.freq / samp_freq),
       factor_im = sin(M_2PI * sinusoid.freq / samp_freq);
   BaseFloat *signal_data = signal->Data();
   int32 dim = signal->Dim(), batch_size = 100;
   // process frames in batches of size "batch_size", after which we recompute
   // the starting point to prevent loss of accuracy due to drift.
   for (int32 b = 0; b * batch_size < dim; b++) {
     int32 t_offset = b * batch_size,
         t_end = std::min(dim, t_offset + batch_size);
     double phase = sinusoid.phase + M_2PI * t_offset * sinusoid.freq / samp_freq;
     // treat x as a complex variable which initially is equal to amplitude * exp(i * phase),
     // but which gets multiplied by "factor" on each frame.
     BaseFloat x_real = sinusoid.amplitude * cos(phase),
         x_im = sinusoid.amplitude * sin(phase);
     for (int32 t = t_offset; t < t_end; t++) {
       signal_data[t] += x_real;
       ComplexMul(factor_real, factor_im, &x_real, &x_im);  // x *= factor.
     }
   }
 }
void ComputeAndProcessKaldiPitch (const PitchExtractionOptions & pitch_opts, const ProcessPitchOptions & process_opts, const VectorBase< BaseFloat > & wave, Matrix< BaseFloat > * output)
This function combines ComputeKaldiPitch and ProcessPitch.
The reason why we need a separate function to do this is in order to be able to accurately simulate the online pitch-processing, for testing and for training models matched to the "first-pass" features. It is sensitive to the variables in pitch_opts that relate to online processing, i.e. max_frames_latency, frames_per_chunk, simulate_first_pass_online, recompute_frame.
Definition at line 1552 of file pitch-functions.cc.
References OnlinePitchFeature::AcceptWaveform(), VectorBase< Real >::Dim(), OnlineProcessPitch::Dim(), PitchExtractionOptions::frame_shift_ms, PitchExtractionOptions::frames_per_chunk, OnlineProcessPitch::GetFrame(), OnlinePitchFeature::InputFinished(), KALDI_ASSERT, KALDI_WARN, kaldi::kCopyData, OnlineProcessPitch::NumFramesReady(), Matrix< Real >::Resize(), MatrixBase< Real >::RowRange(), PitchExtractionOptions::samp_freq, and PitchExtractionOptions::simulate_first_pass_online.
Referenced by main(), and kaldi::UnitTestSimple().
{
   OnlinePitchFeature pitch_extractor(pitch_opts);
   if (pitch_opts.simulate_first_pass_online) {
     KALDI_ASSERT(pitch_opts.frames_per_chunk > 0 &&
                  "--simulate-first-pass-online option does not make sense "
                  "unless you specify --frames-per-chunk");
   }
   OnlineProcessPitch post_process(process_opts, &pitch_extractor);
   int32 cur_rows = 100;
   Matrix<BaseFloat> feats(cur_rows, post_process.Dim());
   int32 cur_offset = 0, cur_frame = 0,
       samp_per_chunk = pitch_opts.frames_per_chunk *
       pitch_opts.samp_freq * 1.0e-03 * pitch_opts.frame_shift_ms;
   // We request the first-pass features as soon as they are available,
   // regardless of whether opts.simulate_first_pass_online == true.  If
   // opts.simulate_first_pass_online == true this should
   // not affect the features generated, but it helps us to test the code
   // in a way that's closer to what online decoding would see.
   while (cur_offset < wave.Dim()) {
     int32 num_samp;
     if (samp_per_chunk > 0)
       num_samp = std::min(samp_per_chunk, wave.Dim() - cur_offset);
     else  // user left opts.frames_per_chunk at zero.
       num_samp = wave.Dim();
     SubVector<BaseFloat> wave_chunk(wave, cur_offset, num_samp);
     pitch_extractor.AcceptWaveform(pitch_opts.samp_freq, wave_chunk);
     cur_offset += num_samp;
     if (cur_offset == wave.Dim())
       pitch_extractor.InputFinished();
     // Get each frame as soon as it is ready.
     for (; cur_frame < post_process.NumFramesReady(); cur_frame++) {
       if (cur_frame >= cur_rows) {
         cur_rows *= 2;
         feats.Resize(cur_rows, post_process.Dim(), kCopyData);
       }
       SubVector<BaseFloat> row(feats, cur_frame);
       post_process.GetFrame(cur_frame, &row);
     }
   }
   if (pitch_opts.simulate_first_pass_online) {
     if (cur_frame == 0) {
       KALDI_WARN << "No features output since wave file too short";
       output->Resize(0, 0);
     } else {
       *output = feats.RowRange(0, cur_frame);
     }
   } else {
     // want the "final" features for second pass, so get them again.
     output->Resize(post_process.NumFramesReady(), post_process.Dim());
     for (int32 frame = 0; frame < post_process.NumFramesReady(); frame++) {
       SubVector<BaseFloat> row(*output, frame);
       post_process.GetFrame(frame, &row);
     }
   }
 }
void ComputeDeltas (const DeltaFeaturesOptions & delta_opts, const MatrixBase< BaseFloat > & input_features, Matrix< BaseFloat > * output_features)
Definition at line 316 of file feature-functions.cc.
References MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), DeltaFeaturesOptions::order, DeltaFeatures::Process(), and Matrix< Real >::Resize().
Referenced by OnlineProcessPitch::GetDeltaPitchFeature(), main(), kaldi::TestOnlineDeltaFeature(), UnitTestCompareWithDeltaFeatures(), UnitTestHTKCompare1(), UnitTestHTKCompare2(), UnitTestHTKCompare3(), UnitTestHTKCompare4(), UnitTestHTKCompare5(), and UnitTestHTKCompare6().
{
   output_features->Resize(input_features.NumRows(),
                           input_features.NumCols()
                           *(delta_opts.order + 1));
   DeltaFeatures delta(delta_opts);
   for (int32 r = 0; r < static_cast<int32>(input_features.NumRows()); r++) {
     SubVector<BaseFloat> row(*output_features, r);
     delta.Process(input_features, r, &row);
   }
 }
void ComputeKaldiPitch (const PitchExtractionOptions & opts, const VectorBase< BaseFloat > & wave, Matrix< BaseFloat > * output)
This function extracts (pitch, NCCF) per frame, using the pitch extraction method described in "A Pitch Extraction Algorithm Tuned for Automatic Speech Recognition", Pegah Ghahremani, Bagher BabaAli, Daniel Povey, Korbinian Riedhammer, Jan Trmal and Sanjeev Khudanpur, ICASSP 2014.
The output will have as many rows as there are frames, and two columns corresponding to (NCCF, pitch)
Definition at line 1246 of file pitch-functions.cc.
References OnlinePitchFeature::AcceptWaveform(), kaldi::ComputeKaldiPitchFirstPass(), VectorBase< Real >::Dim(), PitchExtractionOptions::frame_shift_ms, PitchExtractionOptions::frames_per_chunk, OnlinePitchFeature::GetFrame(), OnlinePitchFeature::InputFinished(), KALDI_ASSERT, KALDI_WARN, OnlinePitchFeature::NumFramesReady(), Matrix< Real >::Resize(), PitchExtractionOptions::samp_freq, and PitchExtractionOptions::simulate_first_pass_online.
Referenced by main(), kaldi::UnitTestDiffSampleRate(), kaldi::UnitTestKeele(), kaldi::UnitTestKeeleNccfBallast(), kaldi::UnitTestPenaltyFactor(), kaldi::UnitTestPieces(), kaldi::UnitTestPitchExtractionSpeed(), kaldi::UnitTestPitchExtractorCompareKeele(), kaldi::UnitTestProcess(), and kaldi::UnitTestSearch().
{
   if (opts.simulate_first_pass_online) {
     ComputeKaldiPitchFirstPass(opts, wave, output);
     return;
   }
   OnlinePitchFeature pitch_extractor(opts);
   if (opts.frames_per_chunk == 0) {
     pitch_extractor.AcceptWaveform(opts.samp_freq, wave);
   } else {
     // the user may set opts.frames_per_chunk for better compatibility with
     // online operation.
     KALDI_ASSERT(opts.frames_per_chunk > 0);
     int32 cur_offset = 0, samp_per_chunk =
         opts.frames_per_chunk * opts.samp_freq * 1.0e-03 * opts.frame_shift_ms;
     while (cur_offset < wave.Dim()) {
       int32 num_samp = std::min(samp_per_chunk, wave.Dim() - cur_offset);
       SubVector<BaseFloat> wave_chunk(wave, cur_offset, num_samp);
       pitch_extractor.AcceptWaveform(opts.samp_freq, wave_chunk);
       cur_offset += num_samp;
     }
   }
   pitch_extractor.InputFinished();
   int32 num_frames = pitch_extractor.NumFramesReady();
   if (num_frames == 0) {
     KALDI_WARN << "No frames output in pitch extraction";
     output->Resize(0, 0);
     return;
   }
   output->Resize(num_frames, 2);
   for (int32 frame = 0; frame < num_frames; frame++) {
     SubVector<BaseFloat> row(*output, frame);
     pitch_extractor.GetFrame(frame, &row);
   }
 }
void ComputeLifterCoeffs (BaseFloat Q, VectorBase< BaseFloat > * coeffs)
Definition at line 248 of file mel-computations.cc.
References VectorBase< Real >::Dim(), rnnlm::i, and M_PI.
Referenced by Mfcc::Mfcc(), and Plp::Plp().
{
   // Compute liftering coefficients (scaling on cepstral coeffs)
   // coeffs are numbered slightly differently from HTK: the zeroth
   // index is C0, which is not affected.
   for (int32 i = 0; i < coeffs->Dim(); i++)
     (*coeffs)(i) = 1.0 + 0.5 * Q * sin (M_PI * i / Q);
 }
BaseFloat ComputeLpc (const VectorBase< BaseFloat > & autocorr_in, Vector< BaseFloat > * lpc_out)
Definition at line 378 of file feature-functions.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), kaldi::Durbin(), KALDI_ASSERT, KALDI_WARN, kaldi::Log(), and rnnlm::n.
Referenced by Plp::ComputeInternal().
{
   int32 n = autocorr_in.Dim() - 1;
   KALDI_ASSERT(lpc_out->Dim() == n);
   Vector<BaseFloat> tmp(n);
   BaseFloat ans =  Durbin(n, autocorr_in.Data(),
                           lpc_out->Data(),
                           tmp.Data());
   if (ans <= 0.0)
     KALDI_WARN << "Zero energy in LPC computation";
   return -Log((double)1.0/ans);  // forms the C0 value
 }
void ComputePowerSpectrum (VectorBase< BaseFloat > * waveform)
Definition at line 185 of file feature-functions.cc.
References VectorBase< Real >::Dim(), and rnnlm::i.
Referenced by Spectrogram::Compute(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), and Plp::ComputeInternal().
{
   int32 dim = waveform->Dim();
   // no, letting it be non-power-of-two for now.
   // KALDI_ASSERT(dim > 0 && (dim & (dim-1) == 0));  // make sure a power of two.. actually my FFT code
   // does not require this (dan) but this is better in case we use different code [dan].
   // RealFft(waveform, true);  // true == forward (not inverse) FFT; makes no difference here,
   // as we just want power spectrum.
   // now we have in waveform, first half of complex spectrum
   // it's stored as [real0, realN/2-1, real1, im1, real2, im2, ...]
   int32 half_dim = dim/2;
   BaseFloat first_energy = (*waveform)(0) * (*waveform)(0),
       last_energy = (*waveform)(1) * (*waveform)(1);  // handle this special case
   for (int32 i = 1; i < half_dim; i++) {
     BaseFloat real = (*waveform)(i*2), im = (*waveform)(i*2 + 1);
     (*waveform)(i) = real*real + im*im;
   }
   (*waveform)(0) = first_energy;
   (*waveform)(half_dim) = last_energy;  // Will actually never be used, and anyway
   // if the signal has been bandlimited sensibly this should be zero.
 }
void ComputeShiftedDeltas (const ShiftedDeltaFeaturesOptions & delta_opts, const MatrixBase< BaseFloat > & input_features, Matrix< BaseFloat > * output_features)
Definition at line 329 of file feature-functions.cc.
References ShiftedDeltaFeaturesOptions::num_blocks, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ShiftedDeltaFeatures::Process(), and Matrix< Real >::Resize().
Referenced by main(), UnitTestCompareWithDeltaFeatures(), UnitTestEndEffects(), and UnitTestParams().
{
   output_features->Resize(input_features.NumRows(),
                           input_features.NumCols()
                           * (delta_opts.num_blocks + 1));
   ShiftedDeltaFeatures delta(delta_opts);
   for (int32 r = 0; r < static_cast<int32>(input_features.NumRows()); r++) {
     SubVector<BaseFloat> row(*output_features, r);
     delta.Process(input_features, r, &row);
   }
 }
void DetectSinusoids (const VectorBase< BaseFloat > & signal, MultiSinusoidDetector * detector, Matrix< BaseFloat > * output)
Definition at line 913 of file sinusoid-detection.cc.
References MultiSinusoidDetector::AcceptWaveform(), VectorBase< Real >::Dim(), MultiSinusoidDetector::Done(), MultiSinusoidDetectorOutput::energy1, MultiSinusoidDetectorOutput::energy2, MultiSinusoidDetector::FrameShiftSecs(), MultiSinusoidDetectorOutput::freq1, MultiSinusoidDetectorOutput::freq2, MultiSinusoidDetector::GetNextFrame(), rnnlm::i, kaldi::kUndefined, MatrixBase< Real >::NumRows(), MultiSinusoidDetector::Reset(), Matrix< Real >::Resize(), MatrixBase< Real >::RowData(), MultiSinusoidDetector::SamplingFrequency(), MultiSinusoidDetectorOutput::tot_energy, and MultiSinusoidDetector::WaveformFinished().
Referenced by main().
{
   std::vector<MultiSinusoidDetectorOutput> output_vec;
   detector->AcceptWaveform(signal);
   detector->WaveformFinished();
   int32 safety_margin = 10, approx_num_frames = safety_margin +
       (signal.Dim() / (detector->SamplingFrequency() *
                        detector->FrameShiftSecs()));
   output_vec.reserve(approx_num_frames);
   while (!detector->Done()) {
     output_vec.resize(output_vec.size() + 1);
     detector->GetNextFrame(&(output_vec.back()));
   }
   detector->Reset();
   if (output_vec.empty()) {
     output->Resize(0, 0);
   } else {
     output->Resize(output_vec.size(), 5, kUndefined);
     for (int32 i = 0; i < output->NumRows(); i++) {
       BaseFloat *row_data = output->RowData(i);
       MultiSinusoidDetectorOutput &this_output = output_vec[i];
       row_data[0] = this_output.tot_energy;
       row_data[1] = this_output.freq1;
       row_data[2] = this_output.energy1;
       row_data[3] = this_output.freq2;
       row_data[4] = this_output.energy2;
     }
   }
 }
void Dither (VectorBase< BaseFloat > * waveform, BaseFloat dither_value)
Definition at line 51 of file feature-functions.cc.
References VectorBase< Real >::Dim(), rnnlm::i, and kaldi::RandGauss().
Referenced by kaldi::ExtractWindow().
{
   for (int32 i = 0; i < waveform->Dim(); i++)
     (*waveform)(i) += RandGauss() * dither_value;
 }
BaseFloat Durbin (int n, const BaseFloat * pAC, BaseFloat * pLP, BaseFloat * pTmp)
Definition at line 262 of file mel-computations.cc.
References rnnlm::i, rnnlm::j, and rnnlm::n.
Referenced by kaldi::ComputeLpc().
{
   BaseFloat ki;                // reflection coefficient
   int i;
   int j;
   BaseFloat E = pAC[0];
   for (i = 0; i < n; i++) {
     // next reflection coefficient
     ki = pAC[i + 1];
     for (j = 0; j < i; j++)
       ki += pLP[j] * pAC[i - j];
     ki = ki / E;
     // new error
     BaseFloat c = 1 - ki * ki;
     if (c < 1.0e-5) // remove NaNs for constan signal
       c = 1.0e-5;
     E *= c;
     // new LP coefficients
     pTmp[i] = -ki;
     for (j = 0; j < i; j++)
       pTmp[j] = pLP[j] - ki * pLP[i - j - 1];
     for (j = 0; j <= i; j++)
       pLP[j] = pTmp[j];
   }
   return E;
 }
void ExtractWaveformRemainder (const VectorBase< BaseFloat > & wave, const FrameExtractionOptions & opts, Vector< BaseFloat > * wave_remainder)
Definition at line 169 of file feature-functions.cc.
References VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), KALDI_ASSERT, kaldi::NumFrames(), Vector< Real >::Resize(), and FrameExtractionOptions::WindowShift().
Referenced by Spectrogram::Compute(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), and Plp::ComputeInternal().
{
   int32 frame_shift = opts.WindowShift();
   int32 num_frames = NumFrames(wave.Dim(), opts);
   // offset is the amount at the start that has been extracted.
   int32 offset = num_frames * frame_shift;
   KALDI_ASSERT(wave_remainder != NULL);
   int32 remaining_len = wave.Dim() - offset;
   wave_remainder->Resize(remaining_len);
   KALDI_ASSERT(remaining_len >= 0);
   if (remaining_len > 0)
     wave_remainder->CopyFromVec(SubVector<BaseFloat>(wave, offset, remaining_len));
 }
void ExtractWindow (const VectorBase< BaseFloat > & wave, int32 f, const FrameExtractionOptions & opts, const FeatureWindowFunction & window_function, Vector< BaseFloat > * window, BaseFloat * log_energy_pre_window)
Definition at line 91 of file feature-functions.cc.
References VectorBase< Real >::Add(), VectorBase< Real >::CopyFromVec(), VectorBase< Real >::Dim(), kaldi::Dither(), FrameExtractionOptions::dither, KALDI_ASSERT, kaldi::Log(), VectorBase< Real >::MulElements(), FrameExtractionOptions::PaddedWindowSize(), FrameExtractionOptions::preemph_coeff, kaldi::Preemphasize(), VectorBase< Real >::Range(), FrameExtractionOptions::remove_dc_offset, Vector< Real >::Resize(), kaldi::nnet3::SetZero(), FrameExtractionOptions::snip_edges, VectorBase< Real >::Sum(), kaldi::VecVec(), FeatureWindowFunction::window, FrameExtractionOptions::WindowShift(), and FrameExtractionOptions::WindowSize().
Referenced by Spectrogram::Compute(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), and Plp::ComputeInternal().
{
   int32 frame_shift = opts.WindowShift();
   int32 frame_length = opts.WindowSize();
   KALDI_ASSERT(window_function.window.Dim() == frame_length);
   KALDI_ASSERT(frame_shift != 0 && frame_length != 0);
   Vector<BaseFloat> wave_part(frame_length);
   if (opts.snip_edges) {
     int32 start = frame_shift*f, end = start + frame_length;
     KALDI_ASSERT(start >= 0 && end <= wave.Dim());
     wave_part.CopyFromVec(wave.Range(start, frame_length));
   } else {
     // If opts.snip_edges = false, we allow the frames to go slightly over the
     // edges of the file; we'll extend the data by reflection.
     int32 mid = frame_shift * (f + 0.5),
         begin = mid - frame_length / 2,
         end = begin + frame_length,
         begin_limited = std::max<int32>(0, begin),
         end_limited = std::min(end, wave.Dim()),
         length_limited = end_limited - begin_limited;
     // Copy the main part.  Usually this will be the entire window.
     wave_part.Range(begin_limited - begin, length_limited).
         CopyFromVec(wave.Range(begin_limited, length_limited));
     // Deal with any end effects by reflection, if needed.  This code will
     // rarely be reached, so we don't concern ourselves with efficiency.
     for (int32 f = begin; f < 0; f++) {
       int32 reflected_f = -f;
       // The next statement will only have an effect in the case of files
       // shorter than a single frame, it's to avoid a crash in those cases.
       reflected_f = reflected_f % wave.Dim();
       wave_part(f - begin) = wave(reflected_f);
     }
     for (int32 f = wave.Dim(); f < end; f++) {
       int32 distance_to_end = f - wave.Dim();
       // The next statement will only have an effect in the case of files
       // shorter than a single frame, it's to avoid a crash in those cases.
       distance_to_end = distance_to_end % wave.Dim();
       int32 reflected_f = wave.Dim() - 1 - distance_to_end;
       wave_part(f - begin) = wave(reflected_f);
     }
   }
   KALDI_ASSERT(window != NULL);
   int32 frame_length_padded = opts.PaddedWindowSize();
   if (window->Dim() != frame_length_padded)
     window->Resize(frame_length_padded);
   SubVector<BaseFloat> window_part(*window, 0, frame_length);
   window_part.CopyFromVec(wave_part);
   if (opts.dither != 0.0) Dither(&window_part, opts.dither);
   if (opts.remove_dc_offset)
     window_part.Add(-window_part.Sum() / frame_length);
   if (log_energy_pre_window != NULL) {
     BaseFloat energy = std::max(VecVec(window_part, window_part),
                                 std::numeric_limits<BaseFloat>::min());
     *log_energy_pre_window = Log(energy);
   }
   if (opts.preemph_coeff != 0.0)
     Preemphasize(&window_part, opts.preemph_coeff);
   window_part.MulElements(window_function.window);
   if (frame_length != frame_length_padded)
     SubVector<BaseFloat>(*window, frame_length,
                          frame_length_padded-frame_length).SetZero();
 }
void GetEqualLoudnessVector (const MelBanks & mel_banks, Vector< BaseFloat > * ans)
Definition at line 347 of file feature-functions.cc.
References MelBanks::GetCenterFreqs(), rnnlm::i, rnnlm::n, MelBanks::NumBins(), and Vector< Real >::Resize().
Referenced by Plp::GetEqualLoudness().
{
   int32 n = mel_banks.NumBins();
   // central freq of each mel bin
   const Vector<BaseFloat> &f0 = mel_banks.GetCenterFreqs();
   ans->Resize(n);
   for (int32 i = 0; i < n; i++) {
     BaseFloat fsq = f0(i) * f0(i);
     BaseFloat fsub = fsq / (fsq + 1.6e5);
     (*ans)(i) = fsub * fsub * ((fsq + 1.44e6) / (fsq + 9.61e6));
   }
 }
void InitIdftBases (int32 n_bases, int32 dimension, Matrix< BaseFloat > * mat_out)
Definition at line 360 of file feature-functions.cc.
References rnnlm::i, rnnlm::j, M_PI, and Matrix< Real >::Resize().
Referenced by Plp::Plp().
{
   BaseFloat angle = M_PI / static_cast<BaseFloat>(dimension - 1);
   BaseFloat scale = 1.0f / (2.0 * static_cast<BaseFloat>(dimension - 1));
   mat_out->Resize(n_bases, dimension);
   for (int32 i = 0; i < n_bases; i++) {
     (*mat_out)(i, 0) = 1.0 * scale;
     BaseFloat i_fl = static_cast<BaseFloat>(i);
     for (int32 j = 1; j < dimension - 1; j++) {
       BaseFloat j_fl = static_cast<BaseFloat>(j);
       (*mat_out)(i, j) = 2.0 * scale * cos(angle * i_fl * j_fl);
     }
     (*mat_out)(i, dimension -1)
         = scale * cos(angle * i_fl * static_cast<BaseFloat>(dimension-1));
   }
 }
void Lpc2Cepstrum (int n, const BaseFloat * pLPC, BaseFloat * pCepst)
Definition at line 295 of file mel-computations.cc.
References rnnlm::i, rnnlm::j, and rnnlm::n.
Referenced by Plp::ComputeInternal().
{
   for (int32 i = 0; i < n; i++) {
     double sum = 0.0;
     int j;
     for (j = 0; j < i; j++) {
       sum += static_cast<BaseFloat>(i - j) * pLPC[j] * pCepst[i - j - 1];
     }
     pCepst[i] = -pLPC[i] - sum / static_cast<BaseFloat>(i + 1);
   }
 }
void kaldi::MaxNormalizeEnergy (Matrix< BaseFloat > * feats) inline
Definition at line 177 of file feature-functions.h.
References MatrixBase< Real >::Add(), and MatrixBase< Real >::NumRows().
{
   // Just subtract the largest energy value... assume energy is the first
   // column of the mfcc features.  Don't do the flooring of energy (dithering
   // should prevent exact zeros).
   // We didn't put this in the main MFCC computation as we wanted to make sure
   // it is stateless (so we can do it bit by bit for large waveforms).
   // not compatible with the order_as_htk_ option in MfccOptions.
   SubMatrix<BaseFloat> energy(*feats, 0, feats->NumRows(), 0, 1);
   energy.Add(-energy.Max());
 }
int32 NumFrames (int32 nsamp, const FrameExtractionOptions & opts)
Definition at line 29 of file feature-functions.cc.
References KALDI_ASSERT, FrameExtractionOptions::snip_edges, FrameExtractionOptions::WindowShift(), and FrameExtractionOptions::WindowSize().
Referenced by Spectrogram::Compute(), Fbank::ComputeInternal(), Mfcc::ComputeInternal(), Plp::ComputeInternal(), and kaldi::ExtractWaveformRemainder().
{
   int32 frame_shift = opts.WindowShift();
   int32 frame_length = opts.WindowSize();
   KALDI_ASSERT(frame_shift != 0 && frame_length != 0);
   if (opts.snip_edges) {
     if (static_cast<int32>(nsamp) < frame_length)
       return 0;
     else
       return (1 + ((nsamp - frame_length) / frame_shift));
       // view the expression above as: nsamp-frame_length is how much room we
       // have to shift the frame within the waveform; frame_shift is how much
       // we shift it each time and the ratio is how many times we can shift
       // it (integer arithmetic rounds down).
   } else {
     return (int32)(nsamp * 1.0f / frame_shift + 0.5f);
     // if --snip-edges=false, the number of frames would be determined by
     // rounding the (file-length / frame-shift) to the nearest integer
   }
 }
void Preemphasize (VectorBase< BaseFloat > * waveform, BaseFloat preemph_coeff)
Definition at line 57 of file feature-functions.cc.
References VectorBase< Real >::Dim(), rnnlm::i, and KALDI_ASSERT.
Referenced by kaldi::ExtractWindow().
{
   if (preemph_coeff == 0.0) return;
   KALDI_ASSERT(preemph_coeff >= 0.0 && preemph_coeff <= 1.0);
   for (int32 i = waveform->Dim()-1; i > 0; i--)
     (*waveform)(i) -= preemph_coeff * (*waveform)(i-1);
   (*waveform)(0) -= preemph_coeff * (*waveform)(0);
 }
void ProcessPitch (const ProcessPitchOptions & opts, const MatrixBase< BaseFloat > & input, Matrix< BaseFloat > * output)
This function processes the raw (NCCF, pitch) quantities computed by ComputeKaldiPitch, and processes them into features.
By default it will output three-dimensional features, (POV-feature, mean-subtracted-log-pitch, delta-of-raw-pitch), but this is configurable in the options. The number of rows of "output" will be the number of frames (rows) in "input", and the number of columns will be the number of different types of features requested (by default, 3; 4 is the max). The four config variables –add-pov-feature, –add-normalized-log-pitch, –add-delta-pitch, –add-raw-log-pitch determine which features we create; by default we create the first three.
Definition at line 1536 of file pitch-functions.cc.
References OnlineProcessPitch::Dim(), OnlineProcessPitch::GetFrame(), OnlineProcessPitch::NumFramesReady(), and Matrix< Real >::Resize().
Referenced by main(), kaldi::UnitTestPieces(), and kaldi::UnitTestProcess().
{
   OnlineMatrixFeature pitch_feat(input);
   OnlineProcessPitch online_process_pitch(opts, &pitch_feat);
   output->Resize(online_process_pitch.NumFramesReady(),
                  online_process_pitch.Dim());
   for (int32 t = 0; t < online_process_pitch.NumFramesReady(); t++) {
     SubVector<BaseFloat> row(*output, t);
     online_process_pitch.GetFrame(t, &row);
   }
 }
void ReverseFrames (const MatrixBase< BaseFloat > & input_features, Matrix< BaseFloat > * output_features)
Definition at line 414 of file feature-functions.cc.
References VectorBase< Real >::CopyFromVec(), KALDI_ERR, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and Matrix< Real >::Resize().
Referenced by main().
{
   int32 T = input_features.NumRows(), D = input_features.NumCols();
   if (T == 0 || D == 0)
     KALDI_ERR << "ReverseFrames: empty input";
   output_features->Resize(T, D);
   for (int32 t = 0; t < T; t++) {
     SubVector<BaseFloat> dst_row(*output_features, t);
     SubVector<BaseFloat> src_row(input_features, T-1-t);
     dst_row.CopyFromVec(src_row);
   }
 }
void SlidingWindowCmn (const SlidingWindowCmnOptions & opts, const MatrixBase< BaseFloat > & input, MatrixBase< BaseFloat > * output)
Applies sliding-window cepstral mean and/or variance normalization.
See the strings registering the options in the options class for information on how this works and what the options are. input and output must have the same dimension.
Definition at line 523 of file feature-functions.cc.
References MatrixBase< Real >::CopyFromMat(), KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), kaldi::SameDim(), and kaldi::SlidingWindowCmnInternal().
Referenced by main(), and kaldi::UnitTestOnlineCmvn().
{
   KALDI_ASSERT(SameDim(input, *output) && input.NumRows() > 0);
   Matrix<double> input_dbl(input), output_dbl(input.NumRows(), input.NumCols());
   // calll double-precision version
   SlidingWindowCmnInternal(opts, input_dbl, &output_dbl);
   output->CopyFromMat(output_dbl);
 }
void SpliceFrames (const MatrixBase< BaseFloat > & input_features, int32 left_context, int32 right_context, Matrix< BaseFloat > * output_features)
Definition at line 391 of file feature-functions.cc.
References rnnlm::j, KALDI_ASSERT, KALDI_ERR, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), and Matrix< Real >::Resize().
Referenced by main(), and kaldi::TestOnlineSpliceFrames().
{
   int32 T = input_features.NumRows(), D = input_features.NumCols();
   if (T == 0 || D == 0)
     KALDI_ERR << "SpliceFrames: empty input";
   KALDI_ASSERT(left_context >= 0 && right_context >= 0);
   int32 N = 1 + left_context + right_context;
   output_features->Resize(T, D*N);
   for (int32 t = 0; t < T; t++) {
     SubVector<BaseFloat> dst_row(*output_features, t);
     for (int32 j = 0; j < N; j++) {
       int32 t2 = t + j - left_context;
       if (t2 < 0) t2 = 0;
       if (t2 >= T) t2 = T-1;
       SubVector<BaseFloat> dst(dst_row, j*D, D),
           src(input_features, t2);
       dst.CopyFromVec(src);
     }
   }
 }