var hierarchy =
[
    [ "Access", "structkaldi_1_1nnet3_1_1Access.html", null ],
    [ "AccumAmDiagGmm", "classkaldi_1_1AccumAmDiagGmm.html", null ],
    [ "AccumDiagGmm", "classkaldi_1_1AccumDiagGmm.html", null ],
    [ "AccumFullGmm", "classkaldi_1_1AccumFullGmm.html", null ],
    [ "AccumulateTreeStatsInfo", "structkaldi_1_1AccumulateTreeStatsInfo.html", null ],
    [ "AccumulateTreeStatsOptions", "structkaldi_1_1AccumulateTreeStatsOptions.html", null ],
    [ "AffineXformStats", "classkaldi_1_1AffineXformStats.html", [
      [ "FmllrDiagGmmAccs", "classkaldi_1_1FmllrDiagGmmAccs.html", null ]
    ] ],
    [ "AlignConfig", "structkaldi_1_1AlignConfig.html", null ],
    [ "AmDiagGmm", "classkaldi_1_1AmDiagGmm.html", null ],
    [ "AmNnet", "classkaldi_1_1nnet2_1_1AmNnet.html", null ],
    [ "AmNnetSimple", "classkaldi_1_1nnet3_1_1AmNnetSimple.html", null ],
    [ "AmSgmm", "classkaldi_1_1AmSgmm.html", null ],
    [ "AmSgmm2", "classkaldi_1_1AmSgmm2.html", null ],
    [ "AmSgmmFunctions", "classkaldi_1_1AmSgmmFunctions.html", null ],
    [ "Analyzer", "structkaldi_1_1nnet3_1_1Analyzer.html", null ],
    [ "ArbitraryResample", "classkaldi_1_1ArbitraryResample.html", null ],
    [ "MinimumBayesRisk::Arc", "structkaldi_1_1MinimumBayesRisk_1_1Arc.html", null ],
    [ "ArpaFileParser", "classkaldi_1_1ArpaFileParser.html", [
      [ "ConstArpaLmBuilder", "classkaldi_1_1ConstArpaLmBuilder.html", null ]
    ] ],
    [ "ArpaLine", "structkaldi_1_1ArpaLine.html", null ],
    [ "ArpaParseOptions", "structkaldi_1_1ArpaParseOptions.html", null ],
    [ "Barrier", "classkaldi_1_1Barrier.html", null ],
    [ "basic_filebuf", null, [
      [ "basic_pipebuf< CharType, Traits >", "classkaldi_1_1basic__pipebuf.html", null ]
    ] ],
    [ "basic_streambuf", null, [
      [ "basic_filebuf< CharT, Traits >", "classkaldi_1_1basic__filebuf.html", null ]
    ] ],
    [ "BasicHolder< BasicType >", "classkaldi_1_1BasicHolder.html", null ],
    [ "BasicPairVectorHolder< BasicType >", "classkaldi_1_1BasicPairVectorHolder.html", null ],
    [ "BasicVectorHolder< BasicType >", "classkaldi_1_1BasicVectorHolder.html", null ],
    [ "BasicVectorVectorHolder< BasicType >", "classkaldi_1_1BasicVectorVectorHolder.html", null ],
    [ "BasisFmllrAccus", "classkaldi_1_1BasisFmllrAccus.html", null ],
    [ "BasisFmllrEstimate", "classkaldi_1_1BasisFmllrEstimate.html", null ],
    [ "BasisFmllrOptions", "structkaldi_1_1BasisFmllrOptions.html", null ],
    [ "LatticeFasterOnlineDecoder::BestPathIterator", "structkaldi_1_1LatticeFasterOnlineDecoder_1_1BestPathIterator.html", null ],
    [ "BiglmFasterDecoder", "classkaldi_1_1BiglmFasterDecoder.html", null ],
    [ "CuBlockMatrix< Real >::BlockMatrixData", "structkaldi_1_1CuBlockMatrix_1_1BlockMatrixData.html", null ],
    [ "BottomUpClusterer", "classkaldi_1_1BottomUpClusterer.html", null ],
    [ "CacheArcIterator", "classCacheArcIterator.html", [
      [ "ArcIterator< ContextFst< A > >", "classfst_1_1ArcIterator_3_01ContextFst_3_01A_01_4_01_4.html", null ],
      [ "ArcIterator< TrivialFactorWeightFst< A, F > >", "classfst_1_1ArcIterator_3_01TrivialFactorWeightFst_3_01A_00_01F_01_4_01_4.html", null ]
    ] ],
    [ "CacheImpl", "classCacheImpl.html", [
      [ "ContextFstImpl< Arc, LabelT >", "classfst_1_1ContextFstImpl.html", null ],
      [ "TrivialFactorWeightFstImpl< A, F >", "classfst_1_1TrivialFactorWeightFstImpl.html", null ]
    ] ],
    [ "CacheOptions", "classCacheOptions.html", [
      [ "TrivialFactorWeightOptions< Arc >", "structfst_1_1TrivialFactorWeightOptions.html", null ]
    ] ],
    [ "CacheStateIterator", "classCacheStateIterator.html", [
      [ "StateIterator< ContextFst< A > >", "classfst_1_1StateIterator_3_01ContextFst_3_01A_01_4_01_4.html", null ],
      [ "StateIterator< TrivialFactorWeightFst< A, F > >", "classfst_1_1StateIterator_3_01TrivialFactorWeightFst_3_01A_00_01F_01_4_01_4.html", null ]
    ] ],
    [ "CachingOptimizingCompiler", "classkaldi_1_1nnet3_1_1CachingOptimizingCompiler.html", null ],
    [ "CheckComputationOptions", "structkaldi_1_1nnet3_1_1CheckComputationOptions.html", null ],
    [ "LmState::ChildrenVectorLessThan", "structkaldi_1_1LmState_1_1ChildrenVectorLessThan.html", null ],
    [ "LmState::ChildType", "unionkaldi_1_1LmState_1_1ChildType.html", null ],
    [ "ChunkInfo", "classkaldi_1_1nnet2_1_1ChunkInfo.html", null ],
    [ "CindexHasher", "structkaldi_1_1nnet3_1_1CindexHasher.html", null ],
    [ "CindexSet", "classkaldi_1_1nnet3_1_1CindexSet.html", null ],
    [ "PldaStats::ClassInfo", "structkaldi_1_1PldaStats_1_1ClassInfo.html", null ],
    [ "ClatRescoreTuple", "structkaldi_1_1ClatRescoreTuple.html", null ],
    [ "Clusterable", "classkaldi_1_1Clusterable.html", [
      [ "GaussClusterable", "classkaldi_1_1GaussClusterable.html", null ],
      [ "ScalarClusterable", "classkaldi_1_1ScalarClusterable.html", null ],
      [ "SgmmClusterable", "classkaldi_1_1SgmmClusterable.html", null ],
      [ "VectorClusterable", "classkaldi_1_1VectorClusterable.html", null ]
    ] ],
    [ "ClusterKMeansOptions", "structkaldi_1_1ClusterKMeansOptions.html", null ],
    [ "NnetComputation::Command", "structkaldi_1_1nnet3_1_1NnetComputation_1_1Command.html", null ],
    [ "CommandAttributes", "structkaldi_1_1nnet3_1_1CommandAttributes.html", null ],
    [ "NnetComputer::CommandDebugInfo", "structkaldi_1_1nnet3_1_1NnetComputer_1_1CommandDebugInfo.html", null ],
    [ "CompactLatticeHolder", "classkaldi_1_1CompactLatticeHolder.html", null ],
    [ "CompactLatticeMinimizer< Weight, IntType >", "classfst_1_1CompactLatticeMinimizer.html", null ],
    [ "CompactLatticePusher< Weight, IntType >", "classfst_1_1CompactLatticePusher.html", null ],
    [ "CompactLatticeWeightCommonDivisorTpl< BaseWeightType, IntType >", "classfst_1_1CompactLatticeWeightCommonDivisorTpl.html", null ],
    [ "CompactLatticeWeightTpl< WeightType, IntType >", "classfst_1_1CompactLatticeWeightTpl.html", null ],
    [ "CompareFirst< Real >", "structkaldi_1_1sparse__vector__utils_1_1CompareFirst.html", null ],
    [ "CompareFirstMemberOfPair< A, B >", "structkaldi_1_1CompareFirstMemberOfPair.html", null ],
    [ "ComparePosteriorByPdfs", "structkaldi_1_1ComparePosteriorByPdfs.html", null ],
    [ "CompareReverseSecond", "structkaldi_1_1CompareReverseSecond.html", null ],
    [ "CompartmentalizedBottomUpClusterer", "classkaldi_1_1CompartmentalizedBottomUpClusterer.html", null ],
    [ "CompBotClustElem", "structkaldi_1_1CompBotClustElem.html", null ],
    [ "Compiler", "classkaldi_1_1nnet3_1_1Compiler.html", null ],
    [ "CompilerOptions", "structkaldi_1_1nnet3_1_1CompilerOptions.html", null ],
    [ "Component", "classkaldi_1_1nnet2_1_1Component.html", [
      [ "DctComponent", "classkaldi_1_1nnet2_1_1DctComponent.html", null ],
      [ "FixedAffineComponent", "classkaldi_1_1nnet2_1_1FixedAffineComponent.html", null ],
      [ "FixedBiasComponent", "classkaldi_1_1nnet2_1_1FixedBiasComponent.html", null ],
      [ "FixedLinearComponent", "classkaldi_1_1nnet2_1_1FixedLinearComponent.html", null ],
      [ "FixedScaleComponent", "classkaldi_1_1nnet2_1_1FixedScaleComponent.html", null ],
      [ "MaxoutComponent", "classkaldi_1_1nnet2_1_1MaxoutComponent.html", null ],
      [ "MaxpoolingComponent", "classkaldi_1_1nnet2_1_1MaxpoolingComponent.html", null ],
      [ "NonlinearComponent", "classkaldi_1_1nnet2_1_1NonlinearComponent.html", [
        [ "LogSoftmaxComponent", "classkaldi_1_1nnet2_1_1LogSoftmaxComponent.html", null ],
        [ "NormalizeComponent", "classkaldi_1_1nnet2_1_1NormalizeComponent.html", null ],
        [ "PowerComponent", "classkaldi_1_1nnet2_1_1PowerComponent.html", null ],
        [ "RectifiedLinearComponent", "classkaldi_1_1nnet2_1_1RectifiedLinearComponent.html", null ],
        [ "SigmoidComponent", "classkaldi_1_1nnet2_1_1SigmoidComponent.html", null ],
        [ "SoftHingeComponent", "classkaldi_1_1nnet2_1_1SoftHingeComponent.html", null ],
        [ "SoftmaxComponent", "classkaldi_1_1nnet2_1_1SoftmaxComponent.html", null ],
        [ "TanhComponent", "classkaldi_1_1nnet2_1_1TanhComponent.html", null ]
      ] ],
      [ "PermuteComponent", "classkaldi_1_1nnet2_1_1PermuteComponent.html", null ],
      [ "PnormComponent", "classkaldi_1_1nnet2_1_1PnormComponent.html", null ],
      [ "RandomComponent", "classkaldi_1_1nnet2_1_1RandomComponent.html", [
        [ "AdditiveNoiseComponent", "classkaldi_1_1nnet2_1_1AdditiveNoiseComponent.html", null ],
        [ "DropoutComponent", "classkaldi_1_1nnet2_1_1DropoutComponent.html", null ]
      ] ],
      [ "ScaleComponent", "classkaldi_1_1nnet2_1_1ScaleComponent.html", null ],
      [ "SpliceComponent", "classkaldi_1_1nnet2_1_1SpliceComponent.html", null ],
      [ "SpliceMaxComponent", "classkaldi_1_1nnet2_1_1SpliceMaxComponent.html", null ],
      [ "SumGroupComponent", "classkaldi_1_1nnet2_1_1SumGroupComponent.html", null ],
      [ "UpdatableComponent", "classkaldi_1_1nnet2_1_1UpdatableComponent.html", [
        [ "AffineComponent", "classkaldi_1_1nnet2_1_1AffineComponent.html", [
          [ "AffineComponentPreconditioned", "classkaldi_1_1nnet2_1_1AffineComponentPreconditioned.html", null ],
          [ "AffineComponentPreconditionedOnline", "classkaldi_1_1nnet2_1_1AffineComponentPreconditionedOnline.html", null ]
        ] ],
        [ "BlockAffineComponent", "classkaldi_1_1nnet2_1_1BlockAffineComponent.html", [
          [ "BlockAffineComponentPreconditioned", "classkaldi_1_1nnet2_1_1BlockAffineComponentPreconditioned.html", null ]
        ] ],
        [ "Convolutional1dComponent", "classkaldi_1_1nnet2_1_1Convolutional1dComponent.html", null ]
      ] ]
    ] ],
    [ "Component", "classkaldi_1_1nnet3_1_1Component.html", [
      [ "ClipGradientComponent", "classkaldi_1_1nnet3_1_1ClipGradientComponent.html", null ],
      [ "DistributeComponent", "classkaldi_1_1nnet3_1_1DistributeComponent.html", null ],
      [ "ElementwiseProductComponent", "classkaldi_1_1nnet3_1_1ElementwiseProductComponent.html", null ],
      [ "FixedAffineComponent", "classkaldi_1_1nnet3_1_1FixedAffineComponent.html", null ],
      [ "FixedBiasComponent", "classkaldi_1_1nnet3_1_1FixedBiasComponent.html", null ],
      [ "FixedScaleComponent", "classkaldi_1_1nnet3_1_1FixedScaleComponent.html", null ],
      [ "MaxpoolingComponent", "classkaldi_1_1nnet3_1_1MaxpoolingComponent.html", null ],
      [ "NonlinearComponent", "classkaldi_1_1nnet3_1_1NonlinearComponent.html", [
        [ "LogSoftmaxComponent", "classkaldi_1_1nnet3_1_1LogSoftmaxComponent.html", null ],
        [ "NoOpComponent", "classkaldi_1_1nnet3_1_1NoOpComponent.html", null ],
        [ "NormalizeComponent", "classkaldi_1_1nnet3_1_1NormalizeComponent.html", null ],
        [ "RectifiedLinearComponent", "classkaldi_1_1nnet3_1_1RectifiedLinearComponent.html", null ],
        [ "SigmoidComponent", "classkaldi_1_1nnet3_1_1SigmoidComponent.html", null ],
        [ "SoftmaxComponent", "classkaldi_1_1nnet3_1_1SoftmaxComponent.html", null ],
        [ "TanhComponent", "classkaldi_1_1nnet3_1_1TanhComponent.html", null ]
      ] ],
      [ "PermuteComponent", "classkaldi_1_1nnet3_1_1PermuteComponent.html", null ],
      [ "PnormComponent", "classkaldi_1_1nnet3_1_1PnormComponent.html", null ],
      [ "SumGroupComponent", "classkaldi_1_1nnet3_1_1SumGroupComponent.html", null ],
      [ "SumReduceComponent", "classkaldi_1_1nnet3_1_1SumReduceComponent.html", null ],
      [ "UpdatableComponent", "classkaldi_1_1nnet3_1_1UpdatableComponent.html", [
        [ "AffineComponent", "classkaldi_1_1nnet3_1_1AffineComponent.html", [
          [ "NaturalGradientAffineComponent", "classkaldi_1_1nnet3_1_1NaturalGradientAffineComponent.html", null ]
        ] ],
        [ "BlockAffineComponent", "classkaldi_1_1nnet3_1_1BlockAffineComponent.html", null ],
        [ "CompositeComponent", "classkaldi_1_1nnet3_1_1CompositeComponent.html", null ],
        [ "Convolutional1dComponent", "classkaldi_1_1nnet3_1_1Convolutional1dComponent.html", null ],
        [ "ConvolutionComponent", "classkaldi_1_1nnet3_1_1ConvolutionComponent.html", null ],
        [ "PerElementOffsetComponent", "classkaldi_1_1nnet3_1_1PerElementOffsetComponent.html", null ],
        [ "PerElementScaleComponent", "classkaldi_1_1nnet3_1_1PerElementScaleComponent.html", [
          [ "NaturalGradientPerElementScaleComponent", "classkaldi_1_1nnet3_1_1NaturalGradientPerElementScaleComponent.html", null ]
        ] ],
        [ "RepeatedAffineComponent", "classkaldi_1_1nnet3_1_1RepeatedAffineComponent.html", [
          [ "NaturalGradientRepeatedAffineComponent", "classkaldi_1_1nnet3_1_1NaturalGradientRepeatedAffineComponent.html", null ]
        ] ]
      ] ]
    ] ],
    [ "ComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1ComponentPrecomputedIndexes.html", [
      [ "DistributeComponentPrecomputedIndexes", "classkaldi_1_1nnet3_1_1DistributeComponentPrecomputedIndexes.html", null ]
    ] ],
    [ "CompressedAffineXformStats", "classkaldi_1_1CompressedAffineXformStats.html", null ],
    [ "CompressedMatrix", "classkaldi_1_1CompressedMatrix.html", null ],
    [ "ComputationAnalysis", "classkaldi_1_1nnet3_1_1ComputationAnalysis.html", null ],
    [ "ComputationChecker", "classkaldi_1_1nnet3_1_1ComputationChecker.html", null ],
    [ "ComputationGraph", "structkaldi_1_1nnet3_1_1ComputationGraph.html", null ],
    [ "ComputationGraphBuilder", "classkaldi_1_1nnet3_1_1ComputationGraphBuilder.html", null ],
    [ "ComputationRenumberer", "classkaldi_1_1nnet3_1_1ComputationRenumberer.html", null ],
    [ "ComputationRequest", "structkaldi_1_1nnet3_1_1ComputationRequest.html", null ],
    [ "ComputationRequestHasher", "structkaldi_1_1nnet3_1_1ComputationRequestHasher.html", null ],
    [ "ComputationRequestPtrEqual", "structkaldi_1_1nnet3_1_1ComputationRequestPtrEqual.html", null ],
    [ "LatticePhoneAligner::ComputationState", "classkaldi_1_1LatticePhoneAligner_1_1ComputationState.html", null ],
    [ "LatticeLexiconWordAligner::ComputationState", "classkaldi_1_1LatticeLexiconWordAligner_1_1ComputationState.html", null ],
    [ "LatticeWordAligner::ComputationState", "classkaldi_1_1LatticeWordAligner_1_1ComputationState.html", null ],
    [ "ComputationVariables", "classkaldi_1_1nnet3_1_1ComputationVariables.html", null ],
    [ "ConfigLine", "classkaldi_1_1nnet3_1_1ConfigLine.html", null ],
    [ "ConstArpaLm", "classkaldi_1_1ConstArpaLm.html", null ],
    [ "ConstIntegerSet< I >", "classkaldi_1_1ConstIntegerSet.html", null ],
    [ "ConstIntegerSet< EventValueType >", "classkaldi_1_1ConstIntegerSet.html", null ],
    [ "ConstIntegerSet< Label >", "classkaldi_1_1ConstIntegerSet.html", null ],
    [ "ContextDependencyInterface", "classkaldi_1_1ContextDependencyInterface.html", [
      [ "ContextDependency", "classkaldi_1_1ContextDependency.html", null ]
    ] ],
    [ "CountStats", "structkaldi_1_1CountStats.html", null ],
    [ "CovarianceStats", "classkaldi_1_1CovarianceStats.html", null ],
    [ "CRnnLM", "classrnnlm_1_1CRnnLM.html", null ],
    [ "CuArray< T >", "classkaldi_1_1CuArray.html", null ],
    [ "CuArray< int32 >", "classkaldi_1_1CuArray.html", null ],
    [ "CuArray< Int32Pair >", "classkaldi_1_1CuArray.html", null ],
    [ "CuArray< MatrixElement< Real > >", "classkaldi_1_1CuArray.html", null ],
    [ "CuBlockMatrix< Real >", "classkaldi_1_1CuBlockMatrix.html", null ],
    [ "CuBlockMatrixData_", "structCuBlockMatrixData__.html", null ],
    [ "CuMatrixBase< Real >", "classkaldi_1_1CuMatrixBase.html", [
      [ "CuMatrix< Real >", "classkaldi_1_1CuMatrix.html", null ],
      [ "CuSubMatrix< Real >", "classkaldi_1_1CuSubMatrix.html", null ]
    ] ],
    [ "CuMatrixBase< BaseFloat >", "classkaldi_1_1CuMatrixBase.html", [
      [ "CuMatrix< BaseFloat >", "classkaldi_1_1CuMatrix.html", null ]
    ] ],
    [ "CuPackedMatrix< Real >", "classkaldi_1_1CuPackedMatrix.html", [
      [ "CuSpMatrix< Real >", "classkaldi_1_1CuSpMatrix.html", null ],
      [ "CuTpMatrix< Real >", "classkaldi_1_1CuTpMatrix.html", null ]
    ] ],
    [ "CuRand< Real >", "classkaldi_1_1CuRand.html", null ],
    [ "CuRand< BaseFloat >", "classkaldi_1_1CuRand.html", null ],
    [ "CuSparseMatrix< Real >", "classkaldi_1_1CuSparseMatrix.html", null ],
    [ "CuValue< Real >", "classkaldi_1_1CuValue.html", null ],
    [ "CuVectorBase< Real >", "classkaldi_1_1CuVectorBase.html", [
      [ "CuSubVector< Real >", "classkaldi_1_1CuSubVector.html", null ],
      [ "CuVector< Real >", "classkaldi_1_1CuVector.html", null ]
    ] ],
    [ "CuVectorBase< BaseFloat >", "classkaldi_1_1CuVectorBase.html", [
      [ "CuVector< BaseFloat >", "classkaldi_1_1CuVector.html", null ]
    ] ],
    [ "CuVectorBase< double >", "classkaldi_1_1CuVectorBase.html", [
      [ "CuVector< double >", "classkaldi_1_1CuVector.html", null ]
    ] ],
    [ "DecisionTreeSplitter", "classkaldi_1_1DecisionTreeSplitter.html", null ],
    [ "DecodableInterface", "classkaldi_1_1DecodableInterface.html", [
      [ "DecodableAmDiagGmmUnmapped", "classkaldi_1_1DecodableAmDiagGmmUnmapped.html", [
        [ "DecodableAmDiagGmm", "classkaldi_1_1DecodableAmDiagGmm.html", null ],
        [ "DecodableAmDiagGmmRegtreeFmllr", "classkaldi_1_1DecodableAmDiagGmmRegtreeFmllr.html", null ],
        [ "DecodableAmDiagGmmRegtreeMllr", "classkaldi_1_1DecodableAmDiagGmmRegtreeMllr.html", null ],
        [ "DecodableAmDiagGmmScaled", "classkaldi_1_1DecodableAmDiagGmmScaled.html", null ]
      ] ],
      [ "DecodableAmSgmm", "classkaldi_1_1DecodableAmSgmm.html", [
        [ "DecodableAmSgmmScaled", "classkaldi_1_1DecodableAmSgmmScaled.html", null ]
      ] ],
      [ "DecodableAmSgmm2", "classkaldi_1_1DecodableAmSgmm2.html", [
        [ "DecodableAmSgmm2Scaled", "classkaldi_1_1DecodableAmSgmm2Scaled.html", null ]
      ] ],
      [ "DecodableMapped", "classkaldi_1_1DecodableMapped.html", null ],
      [ "DecodableMatrixMappedOffset", "classkaldi_1_1DecodableMatrixMappedOffset.html", null ],
      [ "DecodableMatrixScaled", "classkaldi_1_1DecodableMatrixScaled.html", null ],
      [ "DecodableMatrixScaledMapped", "classkaldi_1_1DecodableMatrixScaledMapped.html", null ],
      [ "DecodableSum", "classkaldi_1_1DecodableSum.html", [
        [ "DecodableSumScaled", "classkaldi_1_1DecodableSumScaled.html", null ]
      ] ],
      [ "DecodableAmNnet", "classkaldi_1_1nnet2_1_1DecodableAmNnet.html", null ],
      [ "DecodableAmNnetParallel", "classkaldi_1_1nnet2_1_1DecodableAmNnetParallel.html", null ],
      [ "DecodableNnet2Online", "classkaldi_1_1nnet2_1_1DecodableNnet2Online.html", null ],
      [ "DecodableAmNnetSimple", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimple.html", null ]
    ] ],
    [ "DecodableNnet2OnlineOptions", "structkaldi_1_1nnet2_1_1DecodableNnet2OnlineOptions.html", null ],
    [ "DecodeInfo", "structDecodeInfo.html", null ],
    [ "DecodeUtteranceLatticeFasterClass", "classkaldi_1_1DecodeUtteranceLatticeFasterClass.html", null ],
    [ "Definition", "classDefinition.html", null ],
    [ "DeltaFeatures", "classkaldi_1_1DeltaFeatures.html", null ],
    [ "DeltaFeaturesOptions", "structkaldi_1_1DeltaFeaturesOptions.html", null ],
    [ "DerivativeTimeLimiter", "classkaldi_1_1nnet3_1_1DerivativeTimeLimiter.html", null ],
    [ "Descriptor", "classkaldi_1_1nnet3_1_1Descriptor.html", null ],
    [ "DeterministicOnDemandFst< Arc >", "classfst_1_1DeterministicOnDemandFst.html", [
      [ "BackoffDeterministicOnDemandFst< Arc >", "classfst_1_1BackoffDeterministicOnDemandFst.html", null ],
      [ "CacheDeterministicOnDemandFst< Arc >", "classfst_1_1CacheDeterministicOnDemandFst.html", null ],
      [ "ComposeDeterministicOnDemandFst< Arc >", "classfst_1_1ComposeDeterministicOnDemandFst.html", null ],
      [ "LmExampleDeterministicOnDemandFst< Arc >", "classfst_1_1LmExampleDeterministicOnDemandFst.html", null ],
      [ "UnweightedNgramFst< Arc >", "classfst_1_1UnweightedNgramFst.html", null ]
    ] ],
    [ "DeterministicOnDemandFst< fst::StdArc >", "classfst_1_1DeterministicOnDemandFst.html", [
      [ "ConstArpaLmDeterministicFst", "classkaldi_1_1ConstArpaLmDeterministicFst.html", null ],
      [ "RnnlmDeterministicFst", "classkaldi_1_1RnnlmDeterministicFst.html", null ]
    ] ],
    [ "DeterminizeLatticeOptions", "structfst_1_1DeterminizeLatticeOptions.html", null ],
    [ "DeterminizeLatticePhonePrunedOptions", "structfst_1_1DeterminizeLatticePhonePrunedOptions.html", null ],
    [ "DeterminizeLatticePrunedOptions", "structfst_1_1DeterminizeLatticePrunedOptions.html", null ],
    [ "DeterminizeLatticeTask", "classkaldi_1_1DeterminizeLatticeTask.html", null ],
    [ "DeterminizerStar< F >", "classfst_1_1DeterminizerStar.html", null ],
    [ "DfsOrderVisitor< Arc >", "classfst_1_1DfsOrderVisitor.html", null ],
    [ "DiagGmm", "classkaldi_1_1DiagGmm.html", null ],
    [ "DiagGmmNormal", "classkaldi_1_1DiagGmmNormal.html", null ],
    [ "DiscriminativeExampleSplitter", "classkaldi_1_1nnet2_1_1DiscriminativeExampleSplitter.html", null ],
    [ "DiscriminativeExamplesRepository", "classkaldi_1_1nnet2_1_1DiscriminativeExamplesRepository.html", null ],
    [ "DiscriminativeNnetExample", "structkaldi_1_1nnet2_1_1DiscriminativeNnetExample.html", null ],
    [ "ParseOptions::DocInfo", "structkaldi_1_1ParseOptions_1_1DocInfo.html", null ],
    [ "DummyOptions", "structkaldi_1_1DummyOptions.html", null ],
    [ "EbwAmSgmm2Options", "structkaldi_1_1EbwAmSgmm2Options.html", null ],
    [ "EbwAmSgmm2Updater", "classkaldi_1_1EbwAmSgmm2Updater.html", null ],
    [ "EbwAmSgmmOptions", "structkaldi_1_1EbwAmSgmmOptions.html", null ],
    [ "EbwAmSgmmUpdater", "classkaldi_1_1EbwAmSgmmUpdater.html", null ],
    [ "EbwOptions", "structkaldi_1_1EbwOptions.html", null ],
    [ "EbwWeightOptions", "structkaldi_1_1EbwWeightOptions.html", null ],
    [ "EigenvalueDecomposition< Real >", "classkaldi_1_1EigenvalueDecomposition.html", null ],
    [ "HashList< I, T >::Elem", "structkaldi_1_1HashList_1_1Elem.html", null ],
    [ "LatticeDeterminizer< Weight, IntType >::Element", "structfst_1_1LatticeDeterminizer_1_1Element.html", null ],
    [ "DeterminizerStar< F >::Element", "structfst_1_1DeterminizerStar_1_1Element.html", null ],
    [ "TrivialFactorWeightFstImpl< A, F >::Element", "structfst_1_1TrivialFactorWeightFstImpl_1_1Element.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::Element", "structfst_1_1LatticeDeterminizerPruned_1_1Element.html", null ],
    [ "TrivialFactorWeightFstImpl< A, F >::ElementEqual", "classfst_1_1TrivialFactorWeightFstImpl_1_1ElementEqual.html", null ],
    [ "TrivialFactorWeightFstImpl< A, F >::ElementKey", "classfst_1_1TrivialFactorWeightFstImpl_1_1ElementKey.html", null ],
    [ "LatticeStringRepository< IntType >::Entry", "structfst_1_1LatticeStringRepository_1_1Entry.html", null ],
    [ "LatticeStringRepository< IntType >::EntryEqual", "classfst_1_1LatticeStringRepository_1_1EntryEqual.html", null ],
    [ "LatticeStringRepository< IntType >::EntryKey", "classfst_1_1LatticeStringRepository_1_1EntryKey.html", null ],
    [ "DeterminizerStar< F >::EpsilonClosure", "classfst_1_1DeterminizerStar_1_1EpsilonClosure.html", null ],
    [ "DeterminizerStar< F >::EpsilonClosure::EpsilonClosureInfo", "structfst_1_1DeterminizerStar_1_1EpsilonClosure_1_1EpsilonClosureInfo.html", null ],
    [ "CompactLatticeMinimizer< Weight, IntType >::EquivalenceSorter", "structfst_1_1CompactLatticeMinimizer_1_1EquivalenceSorter.html", null ],
    [ "error_stats", "structkaldi_1_1error__stats.html", null ],
    [ "EventMap", "classkaldi_1_1EventMap.html", [
      [ "ConstantEventMap", "classkaldi_1_1ConstantEventMap.html", null ],
      [ "SplitEventMap", "classkaldi_1_1SplitEventMap.html", null ],
      [ "TableEventMap", "classkaldi_1_1TableEventMap.html", null ]
    ] ],
    [ "EventMapVectorEqual", "structkaldi_1_1EventMapVectorEqual.html", null ],
    [ "EventMapVectorHash", "structkaldi_1_1EventMapVectorHash.html", null ],
    [ "ExamplesRepository", "classkaldi_1_1nnet2_1_1ExamplesRepository.html", null ],
    [ "FasterDecoder", "classkaldi_1_1FasterDecoder.html", null ],
    [ "FasterDecoderOptions", "structkaldi_1_1FasterDecoderOptions.html", [
      [ "BiglmFasterDecoderOptions", "structkaldi_1_1BiglmFasterDecoderOptions.html", null ]
    ] ],
    [ "FastNnetCombiner", "classkaldi_1_1nnet2_1_1FastNnetCombiner.html", null ],
    [ "Fbank", "classkaldi_1_1Fbank.html", null ],
    [ "FbankOptions", "structkaldi_1_1FbankOptions.html", null ],
    [ "FeatureTransformEstimateOptions", "structkaldi_1_1FeatureTransformEstimateOptions.html", null ],
    [ "FeatureWindowFunction", "structkaldi_1_1FeatureWindowFunction.html", null ],
    [ "FirstElementComparator", "structkaldi_1_1nnet3_1_1FirstElementComparator.html", null ],
    [ "FloatWeightTpl", "classFloatWeightTpl.html", [
      [ "ArcticWeightTpl< T >", "classfst_1_1ArcticWeightTpl.html", null ]
    ] ],
    [ "FmllrOptions", "structkaldi_1_1FmllrOptions.html", null ],
    [ "FmllrRawAccs", "classkaldi_1_1FmllrRawAccs.html", null ],
    [ "FmllrRawOptions", "structkaldi_1_1FmllrRawOptions.html", null ],
    [ "FmllrSgmm2Accs", "classkaldi_1_1FmllrSgmm2Accs.html", null ],
    [ "FmllrSgmmAccs", "classkaldi_1_1FmllrSgmmAccs.html", null ],
    [ "Fmpe", "classkaldi_1_1Fmpe.html", null ],
    [ "FmpeOptions", "structkaldi_1_1FmpeOptions.html", null ],
    [ "FmpeStats", "structkaldi_1_1FmpeStats.html", null ],
    [ "FmpeUpdateOptions", "structkaldi_1_1FmpeUpdateOptions.html", null ],
    [ "ForwardingDescriptor", "classkaldi_1_1nnet3_1_1ForwardingDescriptor.html", [
      [ "OffsetForwardingDescriptor", "classkaldi_1_1nnet3_1_1OffsetForwardingDescriptor.html", null ],
      [ "ReplaceIndexForwardingDescriptor", "classkaldi_1_1nnet3_1_1ReplaceIndexForwardingDescriptor.html", null ],
      [ "RoundingForwardingDescriptor", "classkaldi_1_1nnet3_1_1RoundingForwardingDescriptor.html", null ],
      [ "SimpleForwardingDescriptor", "classkaldi_1_1nnet3_1_1SimpleForwardingDescriptor.html", null ],
      [ "SwitchingForwardingDescriptor", "classkaldi_1_1nnet3_1_1SwitchingForwardingDescriptor.html", null ]
    ] ],
    [ "LatticeBiglmFasterDecoder::ForwardLink", "structkaldi_1_1LatticeBiglmFasterDecoder_1_1ForwardLink.html", null ],
    [ "LatticeFasterDecoder::ForwardLink", "structkaldi_1_1LatticeFasterDecoder_1_1ForwardLink.html", null ],
    [ "LatticeFasterOnlineDecoder::ForwardLink", "structkaldi_1_1LatticeFasterOnlineDecoder_1_1ForwardLink.html", null ],
    [ "LatticeSimpleDecoder::ForwardLink", "structkaldi_1_1LatticeSimpleDecoder_1_1ForwardLink.html", null ],
    [ "LatticeTrackingDecoder::ForwardLink", "structkaldi_1_1LatticeTrackingDecoder_1_1ForwardLink.html", null ],
    [ "FrameExtractionOptions", "structkaldi_1_1FrameExtractionOptions.html", null ],
    [ "DiscriminativeExampleSplitter::FrameInfo", "structkaldi_1_1nnet2_1_1DiscriminativeExampleSplitter_1_1FrameInfo.html", null ],
    [ "Fst", "classFst.html", [
      [ "ContextFst< Arc, LabelT >", "classfst_1_1ContextFst.html", null ]
    ] ],
    [ "FullGmm", "classkaldi_1_1FullGmm.html", null ],
    [ "FullGmmNormal", "classkaldi_1_1FullGmmNormal.html", null ],
    [ "MinimumBayesRisk::GammaCompare", "structkaldi_1_1MinimumBayesRisk_1_1GammaCompare.html", null ],
    [ "GaussPostHolder", "classkaldi_1_1GaussPostHolder.html", null ],
    [ "GeneralDescriptor", "structkaldi_1_1nnet3_1_1GeneralDescriptor.html", null ],
    [ "GeneralMatrix", "classkaldi_1_1GeneralMatrix.html", null ],
    [ "GenericHolder< SomeType >", "classkaldi_1_1GenericHolder.html", null ],
    [ "CompressedMatrix::GlobalHeader", "structkaldi_1_1CompressedMatrix_1_1GlobalHeader.html", null ],
    [ "GpsrConfig", "structkaldi_1_1GpsrConfig.html", null ],
    [ "HashList< I, T >::HashBucket", "structkaldi_1_1HashList_1_1HashBucket.html", null ],
    [ "HashList< I, T >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< PairId, kaldi::BiglmFasterDecoder::Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< PairId, kaldi::LatticeBiglmFasterDecoder::Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< StateId, kaldi::FasterDecoder::Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< StateId, kaldi::LatticeFasterDecoder::Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< StateId, kaldi::LatticeFasterOnlineDecoder::Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< StateId, kaldi::LatticeTrackingDecoder::Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HashList< StateId, Token * >", "classkaldi_1_1HashList.html", null ],
    [ "HldaAccsDiagGmm", "classkaldi_1_1HldaAccsDiagGmm.html", null ],
    [ "HmmCacheHash", "structkaldi_1_1HmmCacheHash.html", null ],
    [ "HmmTopology::HmmState", "structkaldi_1_1HmmTopology_1_1HmmState.html", null ],
    [ "HmmTopology", "classkaldi_1_1HmmTopology.html", null ],
    [ "HtkHeader", "structkaldi_1_1HtkHeader.html", null ],
    [ "HtkMatrixHolder", "classkaldi_1_1HtkMatrixHolder.html", null ],
    [ "HTransducerConfig", "structkaldi_1_1HTransducerConfig.html", null ],
    [ "IdentityFunction< T >", "structfst_1_1IdentityFunction.html", null ],
    [ "ImplToFst", "classImplToFst.html", [
      [ "TrivialFactorWeightFst< A, F >", "classfst_1_1TrivialFactorWeightFst.html", null ]
    ] ],
    [ "Index", "structkaldi_1_1nnet3_1_1Index.html", null ],
    [ "IndexHasher", "structkaldi_1_1nnet3_1_1IndexHasher.html", null ],
    [ "IndexSet", "classkaldi_1_1nnet3_1_1IndexSet.html", null ],
    [ "SinusoidDetector::InfoForBin", "structkaldi_1_1SinusoidDetector_1_1InfoForBin.html", null ],
    [ "Input", "classkaldi_1_1Input.html", null ],
    [ "InputImplBase", "classkaldi_1_1InputImplBase.html", [
      [ "FileInputImpl", "classkaldi_1_1FileInputImpl.html", null ],
      [ "OffsetFileInputImpl", "classkaldi_1_1OffsetFileInputImpl.html", null ],
      [ "PipeInputImpl", "classkaldi_1_1PipeInputImpl.html", null ],
      [ "StandardInputImpl", "classkaldi_1_1StandardInputImpl.html", null ]
    ] ],
    [ "Int32AndFloat", "unionkaldi_1_1Int32AndFloat.html", null ],
    [ "Int32IsZero", "structkaldi_1_1Int32IsZero.html", null ],
    [ "Int32Pair", "structInt32Pair.html", null ],
    [ "IoSpecification", "structkaldi_1_1nnet3_1_1IoSpecification.html", null ],
    [ "IvectorEstimationOptions", "structkaldi_1_1IvectorEstimationOptions.html", null ],
    [ "IvectorExtractor", "classkaldi_1_1IvectorExtractor.html", null ],
    [ "IvectorExtractorComputeDerivedVarsClass", "classkaldi_1_1IvectorExtractorComputeDerivedVarsClass.html", null ],
    [ "IvectorExtractorEstimationOptions", "structkaldi_1_1IvectorExtractorEstimationOptions.html", null ],
    [ "IvectorExtractorOptions", "structkaldi_1_1IvectorExtractorOptions.html", null ],
    [ "IvectorExtractorStats", "classkaldi_1_1IvectorExtractorStats.html", null ],
    [ "IvectorExtractorStatsOptions", "structkaldi_1_1IvectorExtractorStatsOptions.html", null ],
    [ "IvectorExtractorUpdateProjectionClass", "classkaldi_1_1IvectorExtractorUpdateProjectionClass.html", null ],
    [ "IvectorExtractorUpdateWeightClass", "classkaldi_1_1IvectorExtractorUpdateWeightClass.html", null ],
    [ "IvectorExtractorUtteranceStats", "classkaldi_1_1IvectorExtractorUtteranceStats.html", null ],
    [ "IvectorExtractTask", "classkaldi_1_1IvectorExtractTask.html", null ],
    [ "IvectorTask", "classkaldi_1_1IvectorTask.html", null ],
    [ "KaldiCompileTimeAssert< B >", "classKaldiCompileTimeAssert.html", null ],
    [ "KaldiCompileTimeAssert< true >", "classKaldiCompileTimeAssert_3_01true_01_4.html", null ],
    [ "KaldiErrorMessage", "classkaldi_1_1KaldiErrorMessage.html", null ],
    [ "KaldiLogMessage", "classkaldi_1_1KaldiLogMessage.html", null ],
    [ "KaldiObjectHolder< KaldiType >", "classkaldi_1_1KaldiObjectHolder.html", null ],
    [ "KaldiRnnlmWrapper", "classkaldi_1_1KaldiRnnlmWrapper.html", null ],
    [ "KaldiRnnlmWrapperOpts", "structkaldi_1_1KaldiRnnlmWrapperOpts.html", null ],
    [ "KaldiVlogMessage", "classkaldi_1_1KaldiVlogMessage.html", null ],
    [ "KaldiWarnMessage", "classkaldi_1_1KaldiWarnMessage.html", null ],
    [ "Component::key_value", "structkaldi_1_1nnet1_1_1Component_1_1key__value.html", null ],
    [ "kMarkerMap", "classkMarkerMap.html", [
      [ "Component", "structkaldi_1_1nnet1_1_1Component.html", [
        [ "AveragePooling2DComponent", "classkaldi_1_1nnet1_1_1AveragePooling2DComponent.html", null ],
        [ "AveragePoolingComponent", "classkaldi_1_1nnet1_1_1AveragePoolingComponent.html", null ],
        [ "BlockSoftmax", "classkaldi_1_1nnet1_1_1BlockSoftmax.html", null ],
        [ "CopyComponent", "classkaldi_1_1nnet1_1_1CopyComponent.html", null ],
        [ "Dropout", "classkaldi_1_1nnet1_1_1Dropout.html", null ],
        [ "KlHmm", "classkaldi_1_1nnet1_1_1KlHmm.html", null ],
        [ "LengthNormComponent", "classkaldi_1_1nnet1_1_1LengthNormComponent.html", null ],
        [ "MaxPooling2DComponent", "classkaldi_1_1nnet1_1_1MaxPooling2DComponent.html", null ],
        [ "MaxPoolingComponent", "classkaldi_1_1nnet1_1_1MaxPoolingComponent.html", null ],
        [ "RbmBase", "classkaldi_1_1nnet1_1_1RbmBase.html", [
          [ "Rbm", "classkaldi_1_1nnet1_1_1Rbm.html", null ]
        ] ],
        [ "Sigmoid", "classkaldi_1_1nnet1_1_1Sigmoid.html", null ],
        [ "SimpleSentenceAveragingComponent", "classkaldi_1_1nnet1_1_1SimpleSentenceAveragingComponent.html", null ],
        [ "Softmax", "classkaldi_1_1nnet1_1_1Softmax.html", null ],
        [ "Splice", "classkaldi_1_1nnet1_1_1Splice.html", null ],
        [ "Tanh", "classkaldi_1_1nnet1_1_1Tanh.html", null ],
        [ "UpdatableComponent", "classkaldi_1_1nnet1_1_1UpdatableComponent.html", [
          [ "AddShift", "classkaldi_1_1nnet1_1_1AddShift.html", null ],
          [ "AffineTransform", "classkaldi_1_1nnet1_1_1AffineTransform.html", null ],
          [ "BLstmProjectedStreams", "classkaldi_1_1nnet1_1_1BLstmProjectedStreams.html", null ],
          [ "Convolutional2DComponent", "classkaldi_1_1nnet1_1_1Convolutional2DComponent.html", null ],
          [ "ConvolutionalComponent", "classkaldi_1_1nnet1_1_1ConvolutionalComponent.html", null ],
          [ "FramePoolingComponent", "classkaldi_1_1nnet1_1_1FramePoolingComponent.html", null ],
          [ "LinearTransform", "classkaldi_1_1nnet1_1_1LinearTransform.html", null ],
          [ "LstmProjectedStreams", "classkaldi_1_1nnet1_1_1LstmProjectedStreams.html", null ],
          [ "ParallelComponent", "classkaldi_1_1nnet1_1_1ParallelComponent.html", null ],
          [ "Rescale", "classkaldi_1_1nnet1_1_1Rescale.html", null ],
          [ "SentenceAveragingComponent", "classkaldi_1_1nnet1_1_1SentenceAveragingComponent.html", null ],
          [ "TCNComponent", "classkaldi_1_1nnet1_1_1TCNComponent.html", null ],
          [ "TCNComponent", "classkaldi_1_1nnet1_1_1TCNComponent.html", null ],
          [ "TCNProjectionComponent", "classkaldi_1_1nnet1_1_1TCNProjectionComponent.html", null ]
        ] ]
      ] ]
    ] ],
    [ "LatticeArcRecord", "structkaldi_1_1LatticeArcRecord.html", null ],
    [ "LatticeBiglmFasterDecoder", "classkaldi_1_1LatticeBiglmFasterDecoder.html", null ],
    [ "LatticeDeterminizer< Weight, IntType >", "classfst_1_1LatticeDeterminizer.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >", "classfst_1_1LatticeDeterminizerPruned.html", null ],
    [ "LatticeFasterDecoder", "classkaldi_1_1LatticeFasterDecoder.html", null ],
    [ "LatticeFasterDecoderConfig", "structkaldi_1_1LatticeFasterDecoderConfig.html", null ],
    [ "LatticeFasterOnlineDecoder", "classkaldi_1_1LatticeFasterOnlineDecoder.html", null ],
    [ "LatticeHolder", "classkaldi_1_1LatticeHolder.html", null ],
    [ "LatticeLexiconWordAligner", "classkaldi_1_1LatticeLexiconWordAligner.html", null ],
    [ "LatticePhoneAligner", "classkaldi_1_1LatticePhoneAligner.html", null ],
    [ "LatticeReader", "classkaldi_1_1LatticeReader.html", null ],
    [ "LatticeSimpleDecoder", "classkaldi_1_1LatticeSimpleDecoder.html", null ],
    [ "LatticeSimpleDecoderConfig", "structkaldi_1_1LatticeSimpleDecoderConfig.html", null ],
    [ "LatticeStringRepository< IntType >", "classfst_1_1LatticeStringRepository.html", null ],
    [ "LatticeToStdMapper< Real >", "classfst_1_1LatticeToStdMapper.html", null ],
    [ "LatticeTrackingDecoder", "classkaldi_1_1LatticeTrackingDecoder.html", null ],
    [ "LatticeTrackingDecoderConfig", "structkaldi_1_1LatticeTrackingDecoderConfig.html", null ],
    [ "LatticeWeightTpl< FloatType >", "classfst_1_1LatticeWeightTpl.html", null ],
    [ "LatticeWeightTpl< BaseFloat >", "classfst_1_1LatticeWeightTpl.html", null ],
    [ "LatticeWordAligner", "classkaldi_1_1LatticeWordAligner.html", null ],
    [ "LbfgsOptions", "structkaldi_1_1LbfgsOptions.html", null ],
    [ "LdaEstimate", "classkaldi_1_1LdaEstimate.html", [
      [ "FeatureTransformEstimate", "classkaldi_1_1FeatureTransformEstimate.html", [
        [ "FeatureTransformEstimateMulti", "classkaldi_1_1FeatureTransformEstimateMulti.html", null ]
      ] ]
    ] ],
    [ "LdaEstimateOptions", "structkaldi_1_1LdaEstimateOptions.html", null ],
    [ "DecodableAmSgmm::LikelihoodCacheRecord", "structkaldi_1_1DecodableAmSgmm_1_1LikelihoodCacheRecord.html", null ],
    [ "DecodableAmDiagGmmUnmapped::LikelihoodCacheRecord", "structkaldi_1_1DecodableAmDiagGmmUnmapped_1_1LikelihoodCacheRecord.html", null ],
    [ "LimitRankClass", "classkaldi_1_1nnet2_1_1LimitRankClass.html", null ],
    [ "LinearCgdOptions", "structkaldi_1_1LinearCgdOptions.html", null ],
    [ "LinearResample", "classkaldi_1_1LinearResample.html", null ],
    [ "LinearVtln", "classkaldi_1_1LinearVtln.html", null ],
    [ "LmFstConverter", "classkaldi_1_1LmFstConverter.html", null ],
    [ "LmState", "classkaldi_1_1LmState.html", null ],
    [ "LmTable", "classkaldi_1_1LmTable.html", null ],
    [ "LogisticRegression", "classkaldi_1_1LogisticRegression.html", null ],
    [ "LogisticRegressionConfig", "structkaldi_1_1LogisticRegressionConfig.html", null ],
    [ "LossItf", "classkaldi_1_1nnet1_1_1LossItf.html", [
      [ "Mse", "classkaldi_1_1nnet1_1_1Mse.html", null ],
      [ "MultiTaskLoss", "classkaldi_1_1nnet1_1_1MultiTaskLoss.html", null ],
      [ "Xent", "classkaldi_1_1nnet1_1_1Xent.html", null ]
    ] ],
    [ "MapDiagGmmOptions", "structkaldi_1_1MapDiagGmmOptions.html", null ],
    [ "MapInputSymbolsMapper< Arc, I >", "classfst_1_1MapInputSymbolsMapper.html", null ],
    [ "MapTransitionUpdateConfig", "structkaldi_1_1MapTransitionUpdateConfig.html", null ],
    [ "MatcherBase", null, [
      [ "ContextMatcher< Arc, LabelT >", "classfst_1_1ContextMatcher.html", null ],
      [ "TableMatcher< F, BackoffMatcher >", "classfst_1_1TableMatcher.html", null ],
      [ "TableMatcherImpl< F, BackoffMatcher >", "classfst_1_1TableMatcherImpl.html", null ],
      [ "TableMatcher< F >", "classfst_1_1TableMatcher.html", null ],
      [ "TableMatcher< fst::Fst< fst::StdArc > >", "classfst_1_1TableMatcher.html", null ],
      [ "TableMatcherImpl< F, SortedMatcher< F > >", "classfst_1_1TableMatcherImpl.html", null ],
      [ "TableMatcherImpl< fst::Fst< fst::StdArc >, SortedMatcher< fst::Fst< fst::StdArc > > >", "classfst_1_1TableMatcherImpl.html", null ]
    ] ],
    [ "MatrixAccesses", "structkaldi_1_1nnet3_1_1MatrixAccesses.html", null ],
    [ "MatrixBase< Real >", "classkaldi_1_1MatrixBase.html", [
      [ "Matrix< Real >", "classkaldi_1_1Matrix.html", null ],
      [ "SubMatrix< Real >", "classkaldi_1_1SubMatrix.html", null ],
      [ "Tensor< Real >", "classkaldi_1_1Tensor.html", null ],
      [ "Matrix< double >", "classkaldi_1_1Matrix.html", null ],
      [ "Matrix< float >", "classkaldi_1_1Matrix.html", null ]
    ] ],
    [ "MatrixBase< BaseFloat >", "classkaldi_1_1MatrixBase.html", [
      [ "Matrix< BaseFloat >", "classkaldi_1_1Matrix.html", null ]
    ] ],
    [ "NnetComputation::MatrixDebugInfo", "structkaldi_1_1nnet3_1_1NnetComputation_1_1MatrixDebugInfo.html", null ],
    [ "MatrixDim_", "structMatrixDim__.html", null ],
    [ "MatrixElement< Real >", "structMatrixElement.html", null ],
    [ "MatrixExponential< Real >", "classkaldi_1_1MatrixExponential.html", null ],
    [ "NnetComputation::MatrixInfo", "structkaldi_1_1nnet3_1_1NnetComputation_1_1MatrixInfo.html", null ],
    [ "DerivativeTimeLimiter::MatrixPruneInfo", "structkaldi_1_1nnet3_1_1DerivativeTimeLimiter_1_1MatrixPruneInfo.html", null ],
    [ "MatrixRandomizer", "classkaldi_1_1nnet1_1_1MatrixRandomizer.html", null ],
    [ "MelBanks", "classkaldi_1_1MelBanks.html", null ],
    [ "MelBanksOptions", "structkaldi_1_1MelBanksOptions.html", null ],
    [ "Mfcc", "classkaldi_1_1Mfcc.html", null ],
    [ "MfccOptions", "structkaldi_1_1MfccOptions.html", null ],
    [ "MinimumBayesRisk", "classkaldi_1_1MinimumBayesRisk.html", null ],
    [ "MiscComputationInfo", "structkaldi_1_1nnet3_1_1MiscComputationInfo.html", null ],
    [ "MleAmSgmm2Accs", "classkaldi_1_1MleAmSgmm2Accs.html", null ],
    [ "MleAmSgmm2Options", "structkaldi_1_1MleAmSgmm2Options.html", null ],
    [ "MleAmSgmm2Updater", "classkaldi_1_1MleAmSgmm2Updater.html", null ],
    [ "MleAmSgmmAccs", "classkaldi_1_1MleAmSgmmAccs.html", null ],
    [ "MleAmSgmmGlobalAccs", "classkaldi_1_1MleAmSgmmGlobalAccs.html", null ],
    [ "MleAmSgmmOptions", "structkaldi_1_1MleAmSgmmOptions.html", null ],
    [ "MleAmSgmmUpdater", "classkaldi_1_1MleAmSgmmUpdater.html", null ],
    [ "MleAmSgmmUpdaterMulti", "classkaldi_1_1MleAmSgmmUpdaterMulti.html", null ],
    [ "MleDiagGmmOptions", "structkaldi_1_1MleDiagGmmOptions.html", null ],
    [ "MleFullGmmOptions", "structkaldi_1_1MleFullGmmOptions.html", null ],
    [ "MleSgmm2SpeakerAccs", "classkaldi_1_1MleSgmm2SpeakerAccs.html", null ],
    [ "MleSgmmSpeakerAccs", "classkaldi_1_1MleSgmmSpeakerAccs.html", null ],
    [ "MleTransitionUpdateConfig", "structkaldi_1_1MleTransitionUpdateConfig.html", null ],
    [ "MlltAccs", "classkaldi_1_1MlltAccs.html", null ],
    [ "ModelUpdateConsolidator", "classkaldi_1_1nnet3_1_1ModelUpdateConsolidator.html", null ],
    [ "MultiSinusoidDetector", "classkaldi_1_1MultiSinusoidDetector.html", null ],
    [ "MultiSinusoidDetectorConfig", "structkaldi_1_1MultiSinusoidDetectorConfig.html", null ],
    [ "MultiSinusoidDetectorOutput", "structkaldi_1_1MultiSinusoidDetectorOutput.html", null ],
    [ "MultiThreadable", "classkaldi_1_1MultiThreadable.html", [
      [ "AccumulateMultiThreadedClass", "classkaldi_1_1AccumulateMultiThreadedClass.html", null ],
      [ "ComputeNormalizersClass", "classkaldi_1_1ComputeNormalizersClass.html", null ],
      [ "ComputeNormalizersClass", "classkaldi_1_1ComputeNormalizersClass.html", null ],
      [ "EbwUpdatePhoneVectorsClass", "classkaldi_1_1EbwUpdatePhoneVectorsClass.html", null ],
      [ "EbwUpdatePhoneVectorsClass", "classkaldi_1_1EbwUpdatePhoneVectorsClass.html", null ],
      [ "ExampleClass", "classkaldi_1_1ExampleClass.html", null ],
      [ "DiscTrainParallelClass", "classkaldi_1_1nnet2_1_1DiscTrainParallelClass.html", null ],
      [ "DoBackpropParallelClass", "classkaldi_1_1nnet2_1_1DoBackpropParallelClass.html", null ],
      [ "FisherComputationClass", "classkaldi_1_1nnet2_1_1FisherComputationClass.html", null ],
      [ "UpdatePhoneVectorsCheckedFromClusterableClass", "classkaldi_1_1UpdatePhoneVectorsCheckedFromClusterableClass.html", null ],
      [ "UpdatePhoneVectorsClass", "classkaldi_1_1UpdatePhoneVectorsClass.html", null ],
      [ "UpdatePhoneVectorsClass", "classkaldi_1_1UpdatePhoneVectorsClass.html", null ],
      [ "UpdateWClass", "classkaldi_1_1UpdateWClass.html", null ],
      [ "UpdateWParallelClass", "classkaldi_1_1UpdateWParallelClass.html", null ]
    ] ],
    [ "MultiThreader< C >", "classkaldi_1_1MultiThreader.html", null ],
    [ "Mutex", "classkaldi_1_1Mutex.html", null ],
    [ "MyTaskClass", "classkaldi_1_1MyTaskClass.html", null ],
    [ "MyThreadClass", "classkaldi_1_1MyThreadClass.html", null ],
    [ "NaturalLess< CompactLatticeWeightTpl< LatticeWeightTpl< FloatType >, IntType > >", "classfst_1_1NaturalLess_3_01CompactLatticeWeightTpl_3_01LatticeWeightTpl_3_01FloatType_01_4_00_01IntType_01_4_01_4.html", null ],
    [ "NaturalLess< LatticeWeightTpl< FloatType > >", "classfst_1_1NaturalLess_3_01LatticeWeightTpl_3_01FloatType_01_4_01_4.html", null ],
    [ "NBestDecoder", "classkaldi_1_1NBestDecoder.html", null ],
    [ "NBestDecoderOptions", "structkaldi_1_1NBestDecoderOptions.html", null ],
    [ "NccfInfo", "structkaldi_1_1NccfInfo.html", null ],
    [ "NetworkNode", "structkaldi_1_1nnet3_1_1NetworkNode.html", null ],
    [ "neuron", "structrnnlm_1_1neuron.html", null ],
    [ "NGram", "structkaldi_1_1NGram.html", null ],
    [ "Nnet", "classkaldi_1_1nnet1_1_1Nnet.html", null ],
    [ "Nnet", "classkaldi_1_1nnet2_1_1Nnet.html", null ],
    [ "Nnet", "classkaldi_1_1nnet3_1_1Nnet.html", null ],
    [ "NnetCombineAconfig", "structkaldi_1_1nnet2_1_1NnetCombineAconfig.html", null ],
    [ "NnetCombineConfig", "structkaldi_1_1nnet2_1_1NnetCombineConfig.html", null ],
    [ "NnetCombineConfig", "structkaldi_1_1nnet3_1_1NnetCombineConfig.html", null ],
    [ "NnetCombineFastConfig", "structkaldi_1_1nnet2_1_1NnetCombineFastConfig.html", null ],
    [ "NnetCombiner", "classkaldi_1_1nnet3_1_1NnetCombiner.html", null ],
    [ "NnetComputation", "structkaldi_1_1nnet3_1_1NnetComputation.html", null ],
    [ "NnetComputeOptions", "structkaldi_1_1nnet3_1_1NnetComputeOptions.html", null ],
    [ "NnetComputeProb", "classkaldi_1_1nnet3_1_1NnetComputeProb.html", null ],
    [ "NnetComputeProbOptions", "structkaldi_1_1nnet3_1_1NnetComputeProbOptions.html", null ],
    [ "NnetComputer", "classkaldi_1_1nnet2_1_1NnetComputer.html", null ],
    [ "NnetComputer", "classkaldi_1_1nnet3_1_1NnetComputer.html", null ],
    [ "NnetComputerFromEg", "classkaldi_1_1nnet3_1_1NnetComputerFromEg.html", null ],
    [ "NnetDataRandomizerOptions", "structkaldi_1_1nnet1_1_1NnetDataRandomizerOptions.html", null ],
    [ "NnetDecodableBase", "classkaldi_1_1nnet3_1_1NnetDecodableBase.html", [
      [ "DecodableAmNnetSimple", "classkaldi_1_1nnet3_1_1DecodableAmNnetSimple.html", null ]
    ] ],
    [ "NnetDiscriminativeStats", "structkaldi_1_1nnet2_1_1NnetDiscriminativeStats.html", null ],
    [ "NnetDiscriminativeUpdateOptions", "structkaldi_1_1nnet2_1_1NnetDiscriminativeUpdateOptions.html", null ],
    [ "NnetDiscriminativeUpdater", "classkaldi_1_1nnet2_1_1NnetDiscriminativeUpdater.html", null ],
    [ "NnetEnsembleTrainer", "classkaldi_1_1nnet2_1_1NnetEnsembleTrainer.html", null ],
    [ "NnetEnsembleTrainerConfig", "structkaldi_1_1nnet2_1_1NnetEnsembleTrainerConfig.html", null ],
    [ "NnetExample", "structkaldi_1_1nnet2_1_1NnetExample.html", null ],
    [ "NnetExample", "structkaldi_1_1nnet3_1_1NnetExample.html", null ],
    [ "NnetExampleBackgroundReader", "classkaldi_1_1nnet2_1_1NnetExampleBackgroundReader.html", null ],
    [ "NnetFixConfig", "structkaldi_1_1nnet2_1_1NnetFixConfig.html", null ],
    [ "NnetGenerationOptions", "structkaldi_1_1nnet3_1_1NnetGenerationOptions.html", null ],
    [ "NnetIo", "structkaldi_1_1nnet3_1_1NnetIo.html", null ],
    [ "NnetLdaStatsAccumulator", "classkaldi_1_1nnet3_1_1NnetLdaStatsAccumulator.html", null ],
    [ "NnetLimitRankOpts", "structkaldi_1_1nnet2_1_1NnetLimitRankOpts.html", null ],
    [ "NnetLogprobTask", "structkaldi_1_1nnet2_1_1NnetLogprobTask.html", null ],
    [ "NnetMixupConfig", "structkaldi_1_1nnet2_1_1NnetMixupConfig.html", null ],
    [ "NnetOnlineComputer", "classkaldi_1_1nnet2_1_1NnetOnlineComputer.html", null ],
    [ "NnetOptimizeOptions", "structkaldi_1_1nnet3_1_1NnetOptimizeOptions.html", null ],
    [ "NnetRescaleConfig", "structkaldi_1_1nnet2_1_1NnetRescaleConfig.html", null ],
    [ "NnetRescaler", "classkaldi_1_1nnet2_1_1NnetRescaler.html", null ],
    [ "NnetShrinkConfig", "structkaldi_1_1nnet2_1_1NnetShrinkConfig.html", null ],
    [ "NnetSimpleComputationOptions", "structkaldi_1_1nnet3_1_1NnetSimpleComputationOptions.html", null ],
    [ "NnetSimpleTrainerConfig", "structkaldi_1_1nnet2_1_1NnetSimpleTrainerConfig.html", null ],
    [ "NnetStats", "classkaldi_1_1nnet2_1_1NnetStats.html", null ],
    [ "NnetStatsConfig", "structkaldi_1_1nnet2_1_1NnetStatsConfig.html", null ],
    [ "NnetTrainer", "classkaldi_1_1nnet3_1_1NnetTrainer.html", null ],
    [ "NnetTrainerOptions", "structkaldi_1_1nnet3_1_1NnetTrainerOptions.html", null ],
    [ "NnetTrainOptions", "structkaldi_1_1nnet1_1_1NnetTrainOptions.html", null ],
    [ "NnetUpdater", "classkaldi_1_1nnet2_1_1NnetUpdater.html", null ],
    [ "NnetWidenConfig", "structkaldi_1_1nnet2_1_1NnetWidenConfig.html", null ],
    [ "TreeClusterer::Node", "structkaldi_1_1TreeClusterer_1_1Node.html", null ],
    [ "OnlineProcessPitch::NormalizationStats", "structkaldi_1_1OnlineProcessPitch_1_1NormalizationStats.html", null ],
    [ "ObjectiveFunctionInfo", "structkaldi_1_1nnet3_1_1ObjectiveFunctionInfo.html", null ],
    [ "OnlineCmvnOptions", "structkaldi_1_1OnlineCmvnOptions.html", null ],
    [ "OnlineCmvnState", "structkaldi_1_1OnlineCmvnState.html", null ],
    [ "OnlineFeatureInterface", "classkaldi_1_1OnlineFeatureInterface.html", [
      [ "OnlineAppendFeature", "classkaldi_1_1OnlineAppendFeature.html", null ],
      [ "OnlineBaseFeature", "classkaldi_1_1OnlineBaseFeature.html", [
        [ "OnlineGenericBaseFeature< C >", "classkaldi_1_1OnlineGenericBaseFeature.html", null ],
        [ "OnlinePitchFeature", "classkaldi_1_1OnlinePitchFeature.html", null ]
      ] ],
      [ "OnlineCacheFeature", "classkaldi_1_1OnlineCacheFeature.html", null ],
      [ "OnlineCmvn", "classkaldi_1_1OnlineCmvn.html", null ],
      [ "OnlineDeltaFeature", "classkaldi_1_1OnlineDeltaFeature.html", null ],
      [ "OnlineMatrixFeature", "classkaldi_1_1OnlineMatrixFeature.html", null ],
      [ "OnlineProcessPitch", "classkaldi_1_1OnlineProcessPitch.html", null ],
      [ "OnlineSpliceFrames", "classkaldi_1_1OnlineSpliceFrames.html", null ],
      [ "OnlineTransform", "classkaldi_1_1OnlineTransform.html", null ]
    ] ],
    [ "OnlineIvectorEstimationStats", "classkaldi_1_1OnlineIvectorEstimationStats.html", null ],
    [ "OnlineNaturalGradient", "classkaldi_1_1nnet3_1_1OnlineNaturalGradient.html", null ],
    [ "OnlineNaturalGradientSimple", "classkaldi_1_1nnet3_1_1OnlineNaturalGradientSimple.html", null ],
    [ "OnlinePitchFeatureImpl", "classkaldi_1_1OnlinePitchFeatureImpl.html", null ],
    [ "OnlinePreconditioner", "classkaldi_1_1nnet2_1_1OnlinePreconditioner.html", null ],
    [ "OnlinePreconditionerSimple", "classkaldi_1_1nnet2_1_1OnlinePreconditionerSimple.html", null ],
    [ "OnlineSpliceOptions", "structkaldi_1_1OnlineSpliceOptions.html", null ],
    [ "OptimizableInterface< Real >", "classkaldi_1_1OptimizableInterface.html", null ],
    [ "SinusoidDetector::OptimizedInfo", "structkaldi_1_1SinusoidDetector_1_1OptimizedInfo.html", null ],
    [ "OptimizeLbfgs< Real >", "classkaldi_1_1OptimizeLbfgs.html", null ],
    [ "SimpleOptions::OptionInfo", "structkaldi_1_1SimpleOptions_1_1OptionInfo.html", null ],
    [ "OptionsItf", "classkaldi_1_1OptionsItf.html", [
      [ "ParseOptions", "classkaldi_1_1ParseOptions.html", null ],
      [ "SimpleOptions", "classkaldi_1_1SimpleOptions.html", null ]
    ] ],
    [ "OtherReal< T >", "classkaldi_1_1OtherReal.html", null ],
    [ "OtherReal< double >", "classkaldi_1_1OtherReal_3_01double_01_4.html", null ],
    [ "OtherReal< float >", "classkaldi_1_1OtherReal_3_01float_01_4.html", null ],
    [ "Output", "classkaldi_1_1Output.html", null ],
    [ "OutputImplBase", "classkaldi_1_1OutputImplBase.html", [
      [ "FileOutputImpl", "classkaldi_1_1FileOutputImpl.html", null ],
      [ "PipeOutputImpl", "classkaldi_1_1PipeOutputImpl.html", null ],
      [ "StandardOutputImpl", "classkaldi_1_1StandardOutputImpl.html", null ]
    ] ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::OutputState", "structfst_1_1LatticeDeterminizerPruned_1_1OutputState.html", null ],
    [ "PackedMatrix< Real >", "classkaldi_1_1PackedMatrix.html", [
      [ "SpMatrix< Real >", "classkaldi_1_1SpMatrix.html", null ],
      [ "TpMatrix< Real >", "classkaldi_1_1TpMatrix.html", null ]
    ] ],
    [ "PackedMatrix< BaseFloat >", "classkaldi_1_1PackedMatrix.html", [
      [ "SpMatrix< BaseFloat >", "classkaldi_1_1SpMatrix.html", null ],
      [ "TpMatrix< BaseFloat >", "classkaldi_1_1TpMatrix.html", null ]
    ] ],
    [ "PackedMatrix< double >", "classkaldi_1_1PackedMatrix.html", [
      [ "SpMatrix< double >", "classkaldi_1_1SpMatrix.html", null ],
      [ "TpMatrix< double >", "classkaldi_1_1TpMatrix.html", null ]
    ] ],
    [ "LatticeDeterminizer< Weight, IntType >::PairComparator", "classfst_1_1LatticeDeterminizer_1_1PairComparator.html", null ],
    [ "DeterminizerStar< F >::PairComparator", "classfst_1_1DeterminizerStar_1_1PairComparator.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::PairComparator", "classfst_1_1LatticeDeterminizerPruned_1_1PairComparator.html", null ],
    [ "RandomAccessTableReaderSortedArchiveImpl< Holder >::PairCompare", "structkaldi_1_1RandomAccessTableReaderSortedArchiveImpl_1_1PairCompare.html", null ],
    [ "PairHasher< Int >", "structkaldi_1_1PairHasher.html", null ],
    [ "Sgmm2LikelihoodCache::PdfCacheElement", "structkaldi_1_1Sgmm2LikelihoodCache_1_1PdfCacheElement.html", null ],
    [ "PdfPrior", "classkaldi_1_1nnet1_1_1PdfPrior.html", null ],
    [ "PdfPriorOptions", "structkaldi_1_1nnet1_1_1PdfPriorOptions.html", null ],
    [ "CompressedMatrix::PerColHeader", "structkaldi_1_1CompressedMatrix_1_1PerColHeader.html", null ],
    [ "PhoneAlignLatticeOptions", "structkaldi_1_1PhoneAlignLatticeOptions.html", null ],
    [ "PitchExtractionOptions", "structkaldi_1_1PitchExtractionOptions.html", null ],
    [ "PitchFrameInfo", "classkaldi_1_1PitchFrameInfo.html", null ],
    [ "PitchInterpolator", "classkaldi_1_1PitchInterpolator.html", null ],
    [ "PitchInterpolatorOptions", "structkaldi_1_1PitchInterpolatorOptions.html", null ],
    [ "PitchInterpolatorStats", "structkaldi_1_1PitchInterpolatorStats.html", null ],
    [ "Plda", "classkaldi_1_1Plda.html", null ],
    [ "PldaConfig", "structkaldi_1_1PldaConfig.html", null ],
    [ "PldaEstimationConfig", "structkaldi_1_1PldaEstimationConfig.html", null ],
    [ "PldaEstimator", "classkaldi_1_1PldaEstimator.html", null ],
    [ "PldaStats", "classkaldi_1_1PldaStats.html", null ],
    [ "PldaUnsupervisedAdaptor", "classkaldi_1_1PldaUnsupervisedAdaptor.html", null ],
    [ "PldaUnsupervisedAdaptorConfig", "structkaldi_1_1PldaUnsupervisedAdaptorConfig.html", null ],
    [ "Plp", "classkaldi_1_1Plp.html", null ],
    [ "PlpOptions", "structkaldi_1_1PlpOptions.html", null ],
    [ "RefineClusterer::point_info", "structkaldi_1_1RefineClusterer_1_1point__info.html", null ],
    [ "ComputationRenumberer::PointerCompare< T >", "structkaldi_1_1nnet3_1_1ComputationRenumberer_1_1PointerCompare.html", null ],
    [ "PosteriorHolder", "classkaldi_1_1PosteriorHolder.html", null ],
    [ "ProcessPitchOptions", "structkaldi_1_1ProcessPitchOptions.html", null ],
    [ "PruneSpecialClass< Arc >", "classfst_1_1PruneSpecialClass.html", null ],
    [ "PushSpecialClass", "classfst_1_1PushSpecialClass.html", null ],
    [ "Questions", "classkaldi_1_1Questions.html", null ],
    [ "QuestionsForKey", "structkaldi_1_1QuestionsForKey.html", null ],
    [ "RandFstOptions", "structfst_1_1RandFstOptions.html", null ],
    [ "RandomAccessTableReader< Holder >", "classkaldi_1_1RandomAccessTableReader.html", null ],
    [ "RandomAccessTableReader< kaldi::TokenHolder >", "classkaldi_1_1RandomAccessTableReader.html", null ],
    [ "RandomAccessTableReaderImplBase< Holder >", "classkaldi_1_1RandomAccessTableReaderImplBase.html", [
      [ "RandomAccessTableReaderArchiveImplBase< Holder >", "classkaldi_1_1RandomAccessTableReaderArchiveImplBase.html", [
        [ "RandomAccessTableReaderDSortedArchiveImpl< Holder >", "classkaldi_1_1RandomAccessTableReaderDSortedArchiveImpl.html", null ],
        [ "RandomAccessTableReaderSortedArchiveImpl< Holder >", "classkaldi_1_1RandomAccessTableReaderSortedArchiveImpl.html", null ],
        [ "RandomAccessTableReaderUnsortedArchiveImpl< Holder >", "classkaldi_1_1RandomAccessTableReaderUnsortedArchiveImpl.html", null ]
      ] ],
      [ "RandomAccessTableReaderScriptImpl< Holder >", "classkaldi_1_1RandomAccessTableReaderScriptImpl.html", null ]
    ] ],
    [ "RandomAccessTableReaderImplBase< kaldi::TokenHolder >", "classkaldi_1_1RandomAccessTableReaderImplBase.html", null ],
    [ "RandomAccessTableReaderMapped< Holder >", "classkaldi_1_1RandomAccessTableReaderMapped.html", null ],
    [ "RandomizerMask", "classkaldi_1_1nnet1_1_1RandomizerMask.html", null ],
    [ "RandomState", "structkaldi_1_1RandomState.html", null ],
    [ "RbmTrainOptions", "structkaldi_1_1nnet1_1_1RbmTrainOptions.html", null ],
    [ "RefineClusterer", "classkaldi_1_1RefineClusterer.html", null ],
    [ "RefineClustersOptions", "structkaldi_1_1RefineClustersOptions.html", null ],
    [ "RegressionTree", "classkaldi_1_1RegressionTree.html", null ],
    [ "RegtreeFmllrDiagGmm", "classkaldi_1_1RegtreeFmllrDiagGmm.html", null ],
    [ "RegtreeFmllrDiagGmmAccs", "classkaldi_1_1RegtreeFmllrDiagGmmAccs.html", null ],
    [ "RegtreeFmllrOptions", "structkaldi_1_1RegtreeFmllrOptions.html", null ],
    [ "RegtreeMllrDiagGmm", "classkaldi_1_1RegtreeMllrDiagGmm.html", null ],
    [ "RegtreeMllrDiagGmmAccs", "classkaldi_1_1RegtreeMllrDiagGmmAccs.html", null ],
    [ "RegtreeMllrOptions", "structkaldi_1_1RegtreeMllrOptions.html", null ],
    [ "RemoveEpsLocalClass< Arc, ReweightPlus >", "classfst_1_1RemoveEpsLocalClass.html", null ],
    [ "RemoveSomeInputSymbolsMapper< Arc, I >", "classfst_1_1RemoveSomeInputSymbolsMapper.html", null ],
    [ "ReweightPlusDefault< Weight >", "structfst_1_1ReweightPlusDefault.html", null ],
    [ "ReweightPlusLogArc", "structfst_1_1ReweightPlusLogArc.html", null ],
    [ "RspecifierOptions", "structkaldi_1_1RspecifierOptions.html", null ],
    [ "TaskSequencer< C >::RunTaskArgsList", "structkaldi_1_1TaskSequencer_1_1RunTaskArgsList.html", null ],
    [ "Semaphore", "classkaldi_1_1Semaphore.html", null ],
    [ "NBestDecoder::TokenStore::SeqToken", "structkaldi_1_1NBestDecoder_1_1TokenStore_1_1SeqToken.html", null ],
    [ "SequentialTableReader< Holder >", "classkaldi_1_1SequentialTableReader.html", null ],
    [ "SequentialTableReaderImplBase< Holder >", "classkaldi_1_1SequentialTableReaderImplBase.html", [
      [ "SequentialTableReaderArchiveImpl< Holder >", "classkaldi_1_1SequentialTableReaderArchiveImpl.html", null ],
      [ "SequentialTableReaderScriptImpl< Holder >", "classkaldi_1_1SequentialTableReaderScriptImpl.html", null ]
    ] ],
    [ "Sgmm2FmllrConfig", "structkaldi_1_1Sgmm2FmllrConfig.html", null ],
    [ "Sgmm2FmllrGlobalParams", "classkaldi_1_1Sgmm2FmllrGlobalParams.html", null ],
    [ "Sgmm2GauPostElement", "structkaldi_1_1Sgmm2GauPostElement.html", null ],
    [ "Sgmm2GselectConfig", "structkaldi_1_1Sgmm2GselectConfig.html", null ],
    [ "Sgmm2LikelihoodCache", "structkaldi_1_1Sgmm2LikelihoodCache.html", null ],
    [ "Sgmm2PerFrameDerivedVars", "structkaldi_1_1Sgmm2PerFrameDerivedVars.html", null ],
    [ "Sgmm2PerSpkDerivedVars", "classkaldi_1_1Sgmm2PerSpkDerivedVars.html", null ],
    [ "Sgmm2Project", "classkaldi_1_1Sgmm2Project.html", null ],
    [ "Sgmm2SplitSubstatesConfig", "structkaldi_1_1Sgmm2SplitSubstatesConfig.html", null ],
    [ "SgmmFmllrConfig", "structkaldi_1_1SgmmFmllrConfig.html", null ],
    [ "SgmmFmllrGlobalParams", "classkaldi_1_1SgmmFmllrGlobalParams.html", null ],
    [ "SgmmGauPostElement", "structkaldi_1_1SgmmGauPostElement.html", null ],
    [ "SgmmGselectConfig", "structkaldi_1_1SgmmGselectConfig.html", null ],
    [ "SgmmPerFrameDerivedVars", "structkaldi_1_1SgmmPerFrameDerivedVars.html", null ],
    [ "SgmmPerSpkDerivedVars", "structkaldi_1_1SgmmPerSpkDerivedVars.html", null ],
    [ "ShiftedDeltaFeatures", "classkaldi_1_1ShiftedDeltaFeatures.html", null ],
    [ "ShiftedDeltaFeaturesOptions", "structkaldi_1_1ShiftedDeltaFeaturesOptions.html", null ],
    [ "SimpleDecoder", "classkaldi_1_1SimpleDecoder.html", null ],
    [ "SimpleObjectiveInfo", "structkaldi_1_1nnet3_1_1SimpleObjectiveInfo.html", null ],
    [ "FmllrRawAccs::SingleFrameStats", "structkaldi_1_1FmllrRawAccs_1_1SingleFrameStats.html", null ],
    [ "FmllrDiagGmmAccs::SingleFrameStats", "structkaldi_1_1FmllrDiagGmmAccs_1_1SingleFrameStats.html", null ],
    [ "Sinusoid", "structkaldi_1_1Sinusoid.html", null ],
    [ "SinusoidDetector", "classkaldi_1_1SinusoidDetector.html", null ],
    [ "SlidingWindowCmnOptions", "structkaldi_1_1SlidingWindowCmnOptions.html", null ],
    [ "SolverOptions", "structkaldi_1_1SolverOptions.html", null ],
    [ "SparseMatrix< Real >", "classkaldi_1_1SparseMatrix.html", null ],
    [ "SparseMatrix< BaseFloat >", "classkaldi_1_1SparseMatrix.html", null ],
    [ "SparseVector< Real >", "classkaldi_1_1SparseVector.html", null ],
    [ "Spectrogram", "classkaldi_1_1Spectrogram.html", null ],
    [ "SpectrogramOptions", "structkaldi_1_1SpectrogramOptions.html", null ],
    [ "SphinxMatrixHolder< kFeatDim >", "classkaldi_1_1SphinxMatrixHolder.html", null ],
    [ "SplitDiscriminativeExampleConfig", "structkaldi_1_1nnet2_1_1SplitDiscriminativeExampleConfig.html", null ],
    [ "SplitExampleStats", "structkaldi_1_1nnet2_1_1SplitExampleStats.html", null ],
    [ "SplitRadixComplexFft< Real >", "classkaldi_1_1SplitRadixComplexFft.html", [
      [ "SplitRadixRealFft< Real >", "classkaldi_1_1SplitRadixRealFft.html", null ]
    ] ],
    [ "SplitRadixComplexFft< BaseFloat >", "classkaldi_1_1SplitRadixComplexFft.html", [
      [ "SplitRadixRealFft< BaseFloat >", "classkaldi_1_1SplitRadixRealFft.html", null ]
    ] ],
    [ "PitchFrameInfo::StateInfo", "structkaldi_1_1PitchFrameInfo_1_1StateInfo.html", null ],
    [ "NnetStats::StatsElement", "structkaldi_1_1nnet2_1_1NnetStats_1_1StatsElement.html", null ],
    [ "StdToLatticeMapper< Real >", "classfst_1_1StdToLatticeMapper.html", null ],
    [ "StdVectorRandomizer< T >", "classkaldi_1_1nnet1_1_1StdVectorRandomizer.html", null ],
    [ "Compiler::StepInfo", "structkaldi_1_1nnet3_1_1Compiler_1_1StepInfo.html", null ],
    [ "StringHasher", "structkaldi_1_1StringHasher.html", null ],
    [ "StringRepository< Label, StringId >", "classfst_1_1StringRepository.html", null ],
    [ "ComputationRenumberer::SubMatrixHasher", "structkaldi_1_1nnet3_1_1ComputationRenumberer_1_1SubMatrixHasher.html", null ],
    [ "NnetComputation::SubMatrixInfo", "structkaldi_1_1nnet3_1_1NnetComputation_1_1SubMatrixInfo.html", null ],
    [ "LatticeDeterminizer< Weight, IntType >::SubsetEqual", "classfst_1_1LatticeDeterminizer_1_1SubsetEqual.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::SubsetEqual", "classfst_1_1LatticeDeterminizerPruned_1_1SubsetEqual.html", null ],
    [ "DeterminizerStar< F >::SubsetEqual", "classfst_1_1DeterminizerStar_1_1SubsetEqual.html", null ],
    [ "LatticeDeterminizer< Weight, IntType >::SubsetEqualStates", "classfst_1_1LatticeDeterminizer_1_1SubsetEqualStates.html", null ],
    [ "DeterminizerStar< F >::SubsetEqualStates", "classfst_1_1DeterminizerStar_1_1SubsetEqualStates.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::SubsetEqualStates", "classfst_1_1LatticeDeterminizerPruned_1_1SubsetEqualStates.html", null ],
    [ "DeterminizerStar< F >::SubsetKey", "classfst_1_1DeterminizerStar_1_1SubsetKey.html", null ],
    [ "LatticeDeterminizer< Weight, IntType >::SubsetKey", "classfst_1_1LatticeDeterminizer_1_1SubsetKey.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::SubsetKey", "classfst_1_1LatticeDeterminizerPruned_1_1SubsetKey.html", null ],
    [ "Sgmm2LikelihoodCache::SubstateCacheElement", "structkaldi_1_1Sgmm2LikelihoodCache_1_1SubstateCacheElement.html", null ],
    [ "SubstateCounter", "structkaldi_1_1SubstateCounter.html", null ],
    [ "SumDescriptor", "classkaldi_1_1nnet3_1_1SumDescriptor.html", [
      [ "BinarySumDescriptor", "classkaldi_1_1nnet3_1_1BinarySumDescriptor.html", null ],
      [ "OptionalSumDescriptor", "classkaldi_1_1nnet3_1_1OptionalSumDescriptor.html", null ],
      [ "SimpleSumDescriptor", "classkaldi_1_1nnet3_1_1SimpleSumDescriptor.html", null ]
    ] ],
    [ "synapse", "structrnnlm_1_1synapse.html", null ],
    [ "TableComposeCache< F >", "structfst_1_1TableComposeCache.html", null ],
    [ "TableComposeCache< fst::Fst< fst::StdArc > >", "structfst_1_1TableComposeCache.html", null ],
    [ "TableMatcherOptions", "structfst_1_1TableMatcherOptions.html", [
      [ "TableComposeOptions", "structfst_1_1TableComposeOptions.html", null ]
    ] ],
    [ "TableWriter< Holder >", "classkaldi_1_1TableWriter.html", null ],
    [ "TableWriterImplBase< Holder >", "classkaldi_1_1TableWriterImplBase.html", [
      [ "TableWriterArchiveImpl< Holder >", "classkaldi_1_1TableWriterArchiveImpl.html", null ],
      [ "TableWriterBothImpl< Holder >", "classkaldi_1_1TableWriterBothImpl.html", null ],
      [ "TableWriterScriptImpl< Holder >", "classkaldi_1_1TableWriterScriptImpl.html", null ]
    ] ],
    [ "TarjanNode", "structkaldi_1_1nnet3_1_1TarjanNode.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::Task", "structfst_1_1LatticeDeterminizerPruned_1_1Task.html", null ],
    [ "PruneSpecialClass< Arc >::Task", "structfst_1_1PruneSpecialClass_1_1Task.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::TaskCompare", "structfst_1_1LatticeDeterminizerPruned_1_1TaskCompare.html", null ],
    [ "TaskSequencer< C >", "classkaldi_1_1TaskSequencer.html", null ],
    [ "TaskSequencerConfig", "structkaldi_1_1TaskSequencerConfig.html", null ],
    [ "LatticeDeterminizerPruned< Weight, IntType >::TempArc", "structfst_1_1LatticeDeterminizerPruned_1_1TempArc.html", null ],
    [ "LatticeDeterminizer< Weight, IntType >::TempArc", "structfst_1_1LatticeDeterminizer_1_1TempArc.html", null ],
    [ "DeterminizerStar< F >::TempArc", "structfst_1_1DeterminizerStar_1_1TempArc.html", null ],
    [ "TestFunction", "classTestFunction.html", null ],
    [ "TestFunctor< Arc >", "structfst_1_1TestFunctor.html", null ],
    [ "TidToTstateMapper", "classkaldi_1_1TidToTstateMapper.html", null ],
    [ "Timer", "classkaldi_1_1Timer.html", null ],
    [ "BiglmFasterDecoder::Token", "classkaldi_1_1BiglmFasterDecoder_1_1Token.html", null ],
    [ "LatticeFasterOnlineDecoder::Token", "structkaldi_1_1LatticeFasterOnlineDecoder_1_1Token.html", null ],
    [ "LatticeBiglmFasterDecoder::Token", "structkaldi_1_1LatticeBiglmFasterDecoder_1_1Token.html", null ],
    [ "FasterDecoder::Token", "classkaldi_1_1FasterDecoder_1_1Token.html", null ],
    [ "LatticeSimpleDecoder::Token", "structkaldi_1_1LatticeSimpleDecoder_1_1Token.html", null ],
    [ "LatticeTrackingDecoder::Token", "structkaldi_1_1LatticeTrackingDecoder_1_1Token.html", null ],
    [ "NBestDecoder::TokenStore::Token", "classkaldi_1_1NBestDecoder_1_1TokenStore_1_1Token.html", null ],
    [ "SimpleDecoder::Token", "classkaldi_1_1SimpleDecoder_1_1Token.html", null ],
    [ "LatticeFasterDecoder::Token", "structkaldi_1_1LatticeFasterDecoder_1_1Token.html", null ],
    [ "TokenHolder", "classkaldi_1_1TokenHolder.html", null ],
    [ "LatticeTrackingDecoder::TokenList", "structkaldi_1_1LatticeTrackingDecoder_1_1TokenList.html", null ],
    [ "LatticeBiglmFasterDecoder::TokenList", "structkaldi_1_1LatticeBiglmFasterDecoder_1_1TokenList.html", null ],
    [ "LatticeFasterDecoder::TokenList", "structkaldi_1_1LatticeFasterDecoder_1_1TokenList.html", null ],
    [ "LatticeFasterOnlineDecoder::TokenList", "structkaldi_1_1LatticeFasterOnlineDecoder_1_1TokenList.html", null ],
    [ "LatticeSimpleDecoder::TokenList", "structkaldi_1_1LatticeSimpleDecoder_1_1TokenList.html", null ],
    [ "NBestDecoder::TokenStore", "classkaldi_1_1NBestDecoder_1_1TokenStore.html", null ],
    [ "TokenVectorHolder", "classkaldi_1_1TokenVectorHolder.html", null ],
    [ "TrainingGraphCompiler", "classkaldi_1_1TrainingGraphCompiler.html", null ],
    [ "TrainingGraphCompilerOptions", "structkaldi_1_1TrainingGraphCompilerOptions.html", null ],
    [ "TransitionModel", "classkaldi_1_1TransitionModel.html", null ],
    [ "TreeClusterer", "classkaldi_1_1TreeClusterer.html", null ],
    [ "TreeClusterOptions", "structkaldi_1_1TreeClusterOptions.html", null ],
    [ "TreeRenderer", "classkaldi_1_1TreeRenderer.html", null ],
    [ "TransitionModel::Triple", "structkaldi_1_1TransitionModel_1_1Triple.html", null ],
    [ "LatticePhoneAligner::Tuple", "structkaldi_1_1LatticePhoneAligner_1_1Tuple.html", null ],
    [ "LatticeWordAligner::Tuple", "structkaldi_1_1LatticeWordAligner_1_1Tuple.html", null ],
    [ "LatticeLexiconWordAligner::Tuple", "structkaldi_1_1LatticeLexiconWordAligner_1_1Tuple.html", null ],
    [ "LatticeWordAligner::TupleEqual", "structkaldi_1_1LatticeWordAligner_1_1TupleEqual.html", null ],
    [ "LatticeLexiconWordAligner::TupleEqual", "structkaldi_1_1LatticeLexiconWordAligner_1_1TupleEqual.html", null ],
    [ "LatticePhoneAligner::TupleEqual", "structkaldi_1_1LatticePhoneAligner_1_1TupleEqual.html", null ],
    [ "LatticePhoneAligner::TupleHash", "structkaldi_1_1LatticePhoneAligner_1_1TupleHash.html", null ],
    [ "LatticeLexiconWordAligner::TupleHash", "structkaldi_1_1LatticeLexiconWordAligner_1_1TupleHash.html", null ],
    [ "LatticeWordAligner::TupleHash", "structkaldi_1_1LatticeWordAligner_1_1TupleHash.html", null ],
    [ "UbmClusteringOptions", "structkaldi_1_1UbmClusteringOptions.html", null ],
    [ "unary_function", null, [
      [ "ComparePair", "structkaldi_1_1nnet3_1_1ComparePair.html", null ],
      [ "FirstElementIsEqualComparator", "structkaldi_1_1nnet3_1_1FirstElementIsEqualComparator.html", null ],
      [ "PairIsEqualComparator", "structkaldi_1_1nnet3_1_1PairIsEqualComparator.html", null ],
      [ "PairIsEqualComparator", "structkaldi_1_1nnet3_1_1PairIsEqualComparator.html", null ]
    ] ],
    [ "VadEnergyOptions", "structkaldi_1_1VadEnergyOptions.html", null ],
    [ "VariableMergingOptimizer", "classkaldi_1_1nnet3_1_1VariableMergingOptimizer.html", null ],
    [ "vector", null, [
      [ "Sgmm2GauPost", "classkaldi_1_1Sgmm2GauPost.html", null ],
      [ "SgmmGauPost", "classkaldi_1_1SgmmGauPost.html", null ]
    ] ],
    [ "VectorBase< Real >", "classkaldi_1_1VectorBase.html", [
      [ "SubVector< Real >", "classkaldi_1_1SubVector.html", null ],
      [ "Vector< Real >", "classkaldi_1_1Vector.html", null ],
      [ "Vector< double >", "classkaldi_1_1Vector.html", null ]
    ] ],
    [ "VectorBase< BaseFloat >", "classkaldi_1_1VectorBase.html", [
      [ "Vector< BaseFloat >", "classkaldi_1_1Vector.html", null ]
    ] ],
    [ "StringRepository< Label, StringId >::VectorEqual", "classfst_1_1StringRepository_1_1VectorEqual.html", null ],
    [ "VectorFst", null, [
      [ "LangModelFst", "classkaldi_1_1LangModelFst.html", null ]
    ] ],
    [ "VectorFstToKwsLexicographicFstMapper", "classkaldi_1_1VectorFstToKwsLexicographicFstMapper.html", null ],
    [ "VectorFstTplHolder< Arc >", "classfst_1_1VectorFstTplHolder.html", null ],
    [ "VectorHasher< Int >", "structkaldi_1_1VectorHasher.html", null ],
    [ "StringRepository< Label, StringId >::VectorKey", "classfst_1_1StringRepository_1_1VectorKey.html", null ],
    [ "VectorRandomizer", "classkaldi_1_1nnet1_1_1VectorRandomizer.html", null ],
    [ "vocab_word", "structrnnlm_1_1vocab__word.html", null ],
    [ "WaveData", "classkaldi_1_1WaveData.html", null ],
    [ "WaveHolder", "classkaldi_1_1WaveHolder.html", null ],
    [ "WordAlignedLatticeTester", "classkaldi_1_1WordAlignedLatticeTester.html", null ],
    [ "WordAlignLatticeLexiconInfo", "classkaldi_1_1WordAlignLatticeLexiconInfo.html", null ],
    [ "WordAlignLatticeLexiconOpts", "structkaldi_1_1WordAlignLatticeLexiconOpts.html", null ],
    [ "WordBoundaryInfo", "structkaldi_1_1WordBoundaryInfo.html", null ],
    [ "WordBoundaryInfoNewOpts", "structkaldi_1_1WordBoundaryInfoNewOpts.html", null ],
    [ "WordBoundaryInfoOpts", "structkaldi_1_1WordBoundaryInfoOpts.html", null ],
    [ "ConstArpaLmBuilder::WordsAndLmStatePairLessThan", "structkaldi_1_1ConstArpaLmBuilder_1_1WordsAndLmStatePairLessThan.html", null ],
    [ "WspecifierOptions", "structkaldi_1_1WspecifierOptions.html", null ]
];