Kaldi: ivectorbin/ivector-adapt-plda.cc File Reference
ivector-adapt-plda.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "ivector/plda.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file ivector-adapt-plda.cc.
References PldaUnsupervisedAdaptor::AddStats(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), PldaUnsupervisedAdaptorConfig::Register(), PldaUnsupervisedAdaptor::UpdatePlda(), SequentialTableReader< Holder >::Value(), and kaldi::WriteKaldiObject().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
         "Adapt a PLDA object using unsupervised adaptation-data iVectors from a different\n"
         "domain to the training data.\n"
         "\n"
         "Usage: ivector-adapt-plda [options] <plda-in> <ivectors-rspecifier> <plda-out>\n"
         "e.g.: ivector-adapt-plda plda ark:ivectors.ark plda.adapted\n";
     ParseOptions po(usage);
     bool binary = true;
     po.Register("binary", &binary, "Write output in binary mode");
     PldaUnsupervisedAdaptorConfig config;
     config.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string plda_rxfilename = po.GetArg(1),
         ivector_rspecifier = po.GetArg(2),
         plda_wxfilename = po.GetArg(3);
     Plda plda;
     ReadKaldiObject(plda_rxfilename, &plda);
     SequentialBaseFloatVectorReader ivector_reader(ivector_rspecifier);
     int32 num_done = 0;
     PldaUnsupervisedAdaptor adaptor;
     for (; !ivector_reader.Done(); ivector_reader.Next(), num_done++)
       adaptor.AddStats(1.0, ivector_reader.Value());
     adaptor.UpdatePlda(config, &plda);
     WriteKaldiObject(plda, plda_wxfilename, binary);
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }