Kaldi: kaldi::nnet3 Namespace Reference
kaldi::nnet3 Namespace Reference
Namespaces
computation_graph
compute_computation_steps
Classes
class AmNnetSimple
class OnlineNaturalGradientSimple
class OnlineNaturalGradient
Keywords for search: natural gradient, naturalgradient, NG-SGD.
struct NnetSimpleComputationOptions
class NnetDecodableBase
class DecodableAmNnetSimple
struct CommandAttributes
class ComputationVariables
This class relates the matrices and sub-matrices in the computation to imaginary "variables", such that we can think of the operations as operating on sets of individual variables, and we can then do analysis that lets us do optimization.
struct Access
struct MatrixAccesses
struct Analyzer
This struct exists to set up various pieces of analysis; it helps avoid the repetition of code where we compute all these things in sequence.
class ComputationAnalysis
This class performs various kinds of specific analysis on top of what class Analyzer gives you immediately.
struct CheckComputationOptions
class ComputationChecker
struct NnetCombineConfig
Configuration class that controls neural net combination, where we combine a number of neural nets.
class NnetCombiner
struct Index
struct Index is intended to represent the various indexes by which we number the rows of the matrices that the Components process: mainly 'n', the index of the member of the minibatch, 't', used for the frame index in speech recognition, and 'x', which is a catch-all extra index which we might use in convolutional setups or for other reasons.
struct IndexHasher
struct CindexHasher
struct ComparePair
struct PairIsEqualComparator
struct FirstElementComparator
struct FirstElementIsEqualComparator
struct CompilerOptions
class Compiler
This class creates an initial version of the NnetComputation, without any optimization or sharing of matrices.
class ComponentPrecomputedIndexes
class Component
Abstract base-class for neural-net components.
class UpdatableComponent
Class UpdatableComponent is a Component which has trainable parameters; it extends the interface of Component.
class NonlinearComponent
This kind of Component is a base-class for things like sigmoid, softmax and ReLU: nonlinearities that don't change the dimension.
struct ComputationGraph
The first step in compilation is to turn the ComputationSpecification into a ComputationGraph, where for each Cindex we have a list of other Cindexes that it depends on.
class ComputationGraphBuilder
An abstract representation of a set of Cindexes.
class CindexSet
class IndexSet
An abstract representation of a set of Indexes.
struct MiscComputationInfo
struct IoSpecification
struct ComputationRequest
struct NnetComputation
struct NnetComputeOptions
class NnetComputer
class NnetComputer is responsible for executing the computation described in the "computation" object.
class ForwardingDescriptor
class SimpleForwardingDescriptor
class OffsetForwardingDescriptor
class SwitchingForwardingDescriptor
class RoundingForwardingDescriptor
For use in clockwork RNNs and the like, this forwarding-descriptor rounds the time-index t down to the the closest t' <= t that is an exact multiple of t_modulus_.
class ReplaceIndexForwardingDescriptor
This ForwardingDescriptor modifies the indexes (n, t, x) by replacing one of them (normally t) with a constant value and keeping the rest.
class SumDescriptor
This is an abstract base-class.
class OptionalSumDescriptor
This is the case of class SumDescriptor, in which we contain just one term, and that term is optional (an IfDefined() expression).
class SimpleSumDescriptor
class BinarySumDescriptor
BinarySumDescriptor can represent either A + B, or (A if defined, else B).
class Descriptor
struct GeneralDescriptor
This class is only used when parsing Descriptors.
struct SimpleObjectiveInfo
struct NnetComputeProbOptions
class NnetComputeProb
This class is for computing cross-entropy and accuracy values in a neural network, for diagnostics.
struct NnetIo
struct NnetExample
NnetExample is the input data and corresponding label (or labels) for one or more frames of input, used for standard cross-entropy training of neural nets (and possibly for other objective functions).
class DistributeComponentPrecomputedIndexes
class DistributeComponent
This Component takes a larger input-dim than output-dim, where the input-dim must be a multiple of the output-dim, and distributes different blocks of the input dimension to different 'x' values.
struct TarjanNode
struct NetworkNode
NetworkNode is used to represent, three types of thing: either an input of the network (which pretty much just states the dimension of the input vector); a Component (e.g.
class Nnet
class VariableMergingOptimizer
This class is responsible for merging matrices, although you probably want to access it via the the function VariableMergingOptimization().
class ModelUpdateConsolidator
This class is responsible for consolidating the model-update part of backprop commands, for components in (e.g.) recurrent networks that need to have many separate backprop commands, into more efficient single commands operating on consolidated data in larger matrices.
class ComputationRenumberer
class DerivativeTimeLimiter
struct NnetOptimizeOptions
struct ComputationRequestHasher
struct ComputationRequestPtrEqual
class CachingOptimizingCompiler
This class enables you to do the compilation and optimization in one call, and also ensures that if the ComputationRequest is identical to the previous one, the compilation process is not repeated.
class ConfigLine
This class is responsible for parsing input xx=yyy a=b c empty= f-oo=bar ba_z=123 bing='a b c' baz="a b c d='a b' e" and giving you access to the fields, in this case.
class PnormComponent
class ElementwiseProductComponent
class NormalizeComponent
class SigmoidComponent
class TanhComponent
class RectifiedLinearComponent
class SumReduceComponent
This component is a fixed (non-trainable) nonlinearity that sums its inputs to produce outputs.
class AffineComponent
class RepeatedAffineComponent
class NaturalGradientRepeatedAffineComponent
class BlockAffineComponent
This class implements an affine transform using a block diagonal matrix e.g., one whose weight matrix is all zeros except for blocks on the diagonal.
class SoftmaxComponent
class LogSoftmaxComponent
class NaturalGradientAffineComponent
Keywords: natural gradient descent, NG-SGD, naturalgradient.
class FixedAffineComponent
FixedAffineComponent is an affine transform that is supplied at network initialization time and is not trainable.
class SumGroupComponent
SumGroupComponent is used to sum up groups of posteriors.
class FixedScaleComponent
FixedScaleComponent applies a fixed per-element scale; it's similar to the Rescale component in the nnet1 setup (and only needed for nnet1 model conversion).
class FixedBiasComponent
FixedBiasComponent applies a fixed per-element bias; it's similar to the AddShift component in the nnet1 setup (and only needed for nnet1 model conversion.
class NoOpComponent
class ClipGradientComponent
class PermuteComponent
PermuteComponent changes the order of the columns (i.e.
class PerElementScaleComponent
class PerElementOffsetComponent
class NaturalGradientPerElementScaleComponent
class ConvolutionComponent
ConvolutionalComponent implements 2d-convolution.
class Convolutional1dComponent
Convolutional1dComponent implements convolution over frequency axis.
class MaxpoolingComponent
MaxPoolingComponent : Maxpooling component was firstly used in ConvNet for selecting an representative activation in an area.
class CompositeComponent
CompositeComponent is components representing a sequence of [simple] components.
struct NnetGenerationOptions
struct NnetTrainerOptions
struct ObjectiveFunctionInfo
class NnetTrainer
This class is for single-threaded training of neural nets using standard objective functions such as cross-entropy (implemented with logsoftmax nonlinearity and a linear objective function) and quadratic loss.
class NnetLdaStatsAccumulator
class NnetComputerFromEg
Typedefs
typedef std::pair< int32, Index > Cindex
typedef TableWriter
< KaldiObjectHolder
< NnetExample > > NnetExampleWriter
typedef SequentialTableReader
< KaldiObjectHolder
< NnetExample > > SequentialNnetExampleReader
typedef
RandomAccessTableReader
< KaldiObjectHolder
< NnetExample > > RandomAccessNnetExampleReader
Enumerations
enum AccessType { kReadAccess, kWriteAccess, kReadWriteAccess }
enum ComponentProperties {
kSimpleComponent = 0x001, kUpdatableComponent = 0x002, kLinearInInput = 0x004, kLinearInParameters = 0x008,
kPropagateInPlace = 0x010, kPropagateAdds = 0x020, kReordersIndexes = 0x040, kBackpropAdds = 0x080,
kBackpropNeedsInput = 0x100, kBackpropNeedsOutput = 0x200, kBackpropInPlace = 0x400, kStoresStats = 0x800
}
enum CommandType {
kAllocMatrixUndefined, kAllocMatrixZeroed, kDeallocMatrix, kAllocMatrixFromOther,
kAllocMatrixFromOtherZeroed, kPropagate, kStoreStats, kBackprop,
kBackpropNoModelUpdate, kMatrixCopy, kMatrixAdd, kCopyRows,
kAddRows, kCopyRowsMulti, kCopyToRowsMulti, kAddRowsMulti,
kAddToRowsMulti, kAddRowRanges, kNoOperation, kNoOperationMarker
}
CommandType is an enum that describes the category of the command used in the NnetComputation.
enum ObjectiveType { kLinear, kQuadratic }
This enum is for a kind of annotation we associate with output nodes of the network; it's for the convenience of calling code so that if the objective is one of a few standard types, we can compute it directly and know how to interpret the supervision labels.
enum NodeType {
kInput, kDescriptor, kComponent, kDimRange,
kNone
}
Functions
void UnitTestPreconditionDirectionsOnline ()
std::string PrintCommand (int32 num_commands, int32 command)
void UnitTestNnetAnalyze ()
static void IndexesMultiToSubmatrixIndexes (const std::vector< std::pair< int32, int32 > > &indexes_multi, std::vector< int32 > *submatrix_indexes)
given a vector of pairs from computation.indexes_multi_indexes containing paris (submatrix-index, row-index), this function outputs to "submatrix_indexes" all (unique) submatrix indexes that appear; and it outputs to "contains_null_marker" true if the pair (-1, -1) appears anywhere in indexes_multi, and false otherwise.
void ComputeCommandAttributes (const Nnet &nnet, const NnetComputation &computation, const ComputationVariables &vars, std::vector< CommandAttributes > *attributes)
void ComputeVariableAccesses (const ComputationVariables &variables, const std::vector< CommandAttributes > &command_attributes, std::vector< std::vector< Access > > *variable_accesses)
After the command-level attributes have been computed, this function organizes them per variable (see class ComputationVariables for how a variable is defined; it is part of a matrix).
void ComputeMatrixAccesses (const Nnet &nnet, const NnetComputation &computation, const ComputationVariables &variables, const std::vector< CommandAttributes > &command_attributes, std::vector< MatrixAccesses > *matrix_accesses)
This function organizes information in the CommandAttributes in a way that is convenient to access per matrix.
void CheckComputation (const Nnet &nnet, const ComputationRequest &request, const NnetComputation &computation, bool check_rewrite=false)
This is a convenience interface for class ComputationChecker.
void ComputeMatrixToSubmatrix (const NnetComputation &computation, std::vector< std::vector< int32 > > *mat_to_submat)
This function computes a vector 'mat_to_submat', indexed by matrix index, such that (*mat_to_submat)[m] is a list of all the submatrix indexes that refer to matrix m.
void PrintMatrixAccesses (std::ostream &os, const std::vector< MatrixAccesses > &matrix_accesses)
This function is to be used in debugging; it produces human-readable output.
void PrintCommandAttributes (std::ostream &os, const std::vector< CommandAttributes > &attributes)
This function is to be used in debugging; it produces human-readable output.
int32 MaxMemoryUsage (const NnetComputation &computation)
Returns the total memory, in bytes, used by the computation (just the temporary memory, not counting the memory used by the nnet itself).
void UnitTestIndexIo ()
static void WriteIndexVectorElementBinary (std::ostream &os, const std::vector< Index > &vec, int32 i)
static void ReadIndexVectorElementBinary (std::istream &is, int32 i, std::vector< Index > *vec)
void WriteIndexVector (std::ostream &os, bool binary, const std::vector< Index > &vec)
void ReadIndexVector (std::istream &is, bool binary, std::vector< Index > *vec)
std::ostream & operator<< (std::ostream &ostream, const Index &index)
std::ostream & operator<< (std::ostream &ostream, const Cindex &cindex)
void PrintCindex (std::ostream &os, const Cindex &cindex, const std::vector< std::string > &node_names)
void PrintIndexes (std::ostream &ostream, const std::vector< Index > &indexes)
this will only be used for pretty-printing.
void PrintCindexes (std::ostream &ostream, const std::vector< Cindex > &cindexes, const std::vector< std::string > &node_names)
this will only be used for pretty-printing.
void PrintIntegerVector (std::ostream &os, const std::vector< int32 > &ints)
void AppendCindexes (int32 node, const std::vector< Index > &indexes, std::vector< Cindex > *out)
Appends to 'out' the pairs (node, indexes[0]), (node, indexes[1]), ...
void UnitTestNnetCompile ()
void PrintVectorVectorPair (std::vector< std::vector< std::pair< int32, int32 > > > vec_vec_pair)
void UnitTestSplitLocationsBackward (bool verbose)
void UnitTestHasContiguousProperty ()
void UnitTestEnsureContiguousProperty ()
void UnitTestSplitLocations (bool verbose)
bool SecondElementComparator (const std::pair< int32, int32 > &first_pair, const std::pair< int32, int32 > &second_pair)
void SortSubmatLists (const std::vector< std::vector< std::pair< int32, int32 > > > submat_lists, std::vector< std::vector< std::pair< int32, int32 > > > *sorted_submat_lists, int32 *max_submat_list_size)
void ComputeSubmatIndexHistogram (const std::vector< std::vector< std::pair< int32, int32 > > > sorted_submat_lists, unordered_map< int32, std::vector< int32 > > *submat_histogram)
void FindSubmatIndexInSubmatLists (int32 submat_index, std::vector< std::vector< std::pair< int32, int32 > > > *sorted_submat_lists, std::vector< std::vector< std::pair< int32, int32 > >::iterator > *output_iterator_list, int32 *max_remaining_submat_list_size)
void ExtractGivenPairsFromSubmatLists (std::vector< std::vector< std::pair< int32, int32 > >::iterator > &input_iterator_list, std::vector< std::vector< std::pair< int32, int32 > > > *sorted_submat_lists, std::vector< std::pair< int32, int32 > > *list_of_pairs)
static void ExtractLastPairFromSubmatLists (std::vector< std::vector< std::pair< int32, int32 > > > *sorted_submat_lists, std::vector< std::pair< int32, int32 > > *list_of_pairs)
static void SplitLocationsUsingSubmatHistogram (int32 max_submat_list_size, std::vector< std::vector< std::pair< int32, int32 > > > *sorted_submat_lists, std::vector< std::pair< int32, int32 > > *submat_histogram_vector, std::vector< std::vector< std::pair< int32, int32 > > > *split_lists)
void SplitLocations (const std::vector< std::vector< std::pair< int32, int32 > > > &submat_lists, std::vector< std::vector< std::pair< int32, int32 > > > *split_lists)
The input to this function is a vector of lists of pairs, and this function splits it up into a list of vectors of pairs.
bool ConvertToIndexes (const std::vector< std::pair< int32, int32 > > &location_vector, int32 *first_value, std::vector< int32 > *second_values)
If it is the case for some i >= 0 that all the .first elements of "location_vector" are either i or -1, then output i to first_value and the .second elements into "second_values", and return true.
void EnsureContiguousProperty (const std::vector< int32 > &indexes, std::vector< std::vector< int32 > > *indexes_out)
This function takes a vector of indexes and splits it up into as separate vectors of the same size, as needed to ensure that the 'contiguous property' holds.
void SplitPairList (std::vector< std::pair< int32, int32 > > &list, std::vector< std::vector< std::pair< int32, int32 > > > *split_lists)
void SplitLocationsBackward (const std::vector< std::vector< std::pair< int32, int32 > > > &submat_lists, std::vector< std::vector< std::pair< int32, int32 > > > *split_lists)
This function has the same interface as SplitLocations(); however, it ensures certain additional properties of the output "split_lists", which are necessary because of the way it is used in backprop code.
bool HasContiguousProperty (const std::vector< int32 > &indexes, std::vector< std::pair< int32, int32 > > *reverse_indexes)
This function returns true if for each integer i != -1, all the indexes j at which indexes[j] == i are consecutive with no gaps (more formally: if j1 < j2 < j3 and indexes[j1] != -1 and indexes[j1] == indexes[j3], then indexes[j1] == indexes[j2]).
static bool StringsApproxEqual (const std::string &a, const std::string &b)
void TestNnetComponentIo (Component *c)
void TestNnetComponentCopy (Component *c)
void TestNnetComponentAddScale (Component *c)
void TestNnetComponentVectorizeUnVectorize (Component *c)
void TestStringsApproxEqual ()
void TestNnetComponentUpdatable (Component *c)
void TestSimpleComponentPropagateProperties (const Component &c)
bool TestSimpleComponentDataDerivative (const Component &c, BaseFloat perturb_delta)
bool TestSimpleComponentModelDerivative (const Component &c, BaseFloat perturb_delta, bool test_derivative)
void UnitTestNnetComponent ()
std::ostream & operator<< (std::ostream &os, const ComputationGraphBuilder::ComputableInfo &info)
This is to be used in logging only.
void ComputeComputationGraph (const Nnet &nnet, const ComputationRequest &request, ComputationGraph *graph)
static int32 SumVectorSizes (const std::vector< std::vector< int32 > > &vec)
static void ComputeComputationPhasesForEpoch (const Nnet &nnet, const ComputationGraph &graph, const std::vector< std::vector< int32 > > &dependencies_subset, const std::vector< std::vector< int32 > > &depend_on_subset, const std::vector< int32 > &this_epoch, bool epoch_is_trivial, std::vector< int32 > *phase_index, std::vector< std::vector< int32 > > *phases)
void ComputeComputationPhases (const Nnet &nnet, const ComputationGraph &computation_graph, std::vector< std::vector< int32 > > *phases)
Compute the phases in which we can compute each cindex in the computation; the cindexes will be grouped into phases.
void ComputeComputationSteps (const Nnet &nnet, const ComputationRequest &request, const std::vector< std::vector< int32 > > &phases, ComputationGraph *computation_graph, std::vector< std::vector< int32 > > *steps)
This function arranges the cindex_ids of the computation into a sequence of lists called "steps", which will correspond roughly to the commands in the compiled computation.
static void GetIndexesStrings (const Nnet &nnet, const NnetComputation &computation, std::vector< std::string > *indexes_strings)
static void GetIndexesMultiStrings (const Nnet &nnet, const NnetComputation &computation, std::vector< std::string > *indexes_multi_strings)
static void PrintCommand (std::ostream &os, const Nnet &nnet, const NnetComputation &computation, int32 command_index, const std::vector< std::string > &submatrix_strings, const std::vector< std::string > &indexes_strings, const std::vector< std::string > &indexes_multi_strings)
static void PrintComputationPreamble (std::ostream &os, const NnetComputation &c, const Nnet &nnet, const std::vector< std::string > &submatrix_strings, const std::vector< std::string > &indexes_strings, const std::vector< std::string > &indexes_multi_strings)
std::ostream & operator<< (std::ostream &os, NnetComputation &computation)
void TestNnetDecodable (const ComputationRequest &request, const std::vector< Matrix< BaseFloat > > &inputs, const Nnet &nnet, const CuMatrixBase< BaseFloat > &reference_output)
void UnitTestNnetCompute ()
void ComputeMinAndMaxTimes (const std::vector< Index > &indexes, int32 *min_t, int32 *max_t)
void SetDerivTimesOptions (const ComputationRequest &request, NnetOptimizeOptions *opt_config)
void UnitTestNnetModelDerivatives ()
void UnitTestNnetInputDerivatives ()
ForwardingDescriptor * GenRandForwardingDescriptor (int32 num_nodes)
SumDescriptor * GenRandSumDescriptor (int32 num_nodes)
void GenRandDescriptor (int32 num_nodes, Descriptor *desc)
void UnitTestDescriptorIo ()
void UnitTestGeneralDescriptor ()
std::string NormalizeTextDescriptor (const std::vector< std::string > &node_names, const std::string &desc_str)
void UnitTestGeneralDescriptorSpecial ()
static std::string ParsingContext (const std::string *token_ptr)
static void ExpectToken (const std::string &token, const std::string &what_we_are_parsing, const std::string **next_token)
static int32 ReadIntegerToken (const std::string &what_we_are_parsing, const std::string **next_token)
void ComputeAccuracy (const GeneralMatrix &supervision, const CuMatrixBase< BaseFloat > &nnet_output, BaseFloat *tot_weight, BaseFloat *tot_accuracy)
This function computes the frame accuracy for this minibatch.
void UnitTestNnetExample ()
void UnitTestNnetMergeExamples ()
static void GetIoNames (const std::vector< NnetExample > &src, std::vector< std::string > *names_vec)
static void GetIoSizes (const std::vector< NnetExample > &src, const std::vector< std::string > &names, std::vector< int32 > *sizes)
static void MergeIo (const std::vector< NnetExample > &src, const std::vector< std::string > &names, const std::vector< int32 > &sizes, bool compress, NnetExample *merged_eg)
void MergeExamples (const std::vector< NnetExample > &src, bool compress, NnetExample *dest)
Merge a set of input examples into a single example (typically the size of "src" will be the minibatch size).
void ShiftExampleTimes (int32 t_offset, const std::vector< std::string > &exclude_names, NnetExample *eg)
Shifts the time-index t of everything in the "eg" by adding "t_offset" to all "t" values.
void GetComputationRequest (const Nnet &nnet, const NnetExample &eg, bool need_model_derivative, bool store_component_stats, ComputationRequest *computation_request)
This function takes a NnetExample (which should already have been frame-selected, if desired, and merged into a minibatch) and produces a ComputationRequest.
bool AssertGraphEqual (const std::vector< std::vector< int32 > > &graph1, const std::vector< std::vector< int32 > > &graph2)
bool AssertVectorEqual (const std::vector< int32 > &vec1, const std::vector< int32 > &vec2)
void BuildTestGraph (std::vector< std::vector< int32 > > *graph)
void BuildTestGraphTranspose (std::vector< std::vector< int32 > > *graph)
void BuildTestSccs (std::vector< std::vector< int32 > > *sccs)
void BuildTestSccGraph (std::vector< std::vector< int32 > > *scc_graph)
void BuildTestTopSortOrder (std::vector< int32 > *node_to_order)
void UnitTestComputeGraphTranspose ()
void UnitTestFindSccs ()
void UnitTestMakeSccGraph ()
void UnitTestComputeTopSortOrder ()
void NnetToDirectedGraph (const Nnet &nnet, std::vector< std::vector< int32 > > *graph)
This function takes an nnet and turns it to a directed graph on nodes.
void ComputeGraphTranspose (const std::vector< std::vector< int32 > > &graph, std::vector< std::vector< int32 > > *graph_transpose)
Outputs a graph in which the order of arcs is reversed.
void TarjanSccRecursive (int32 node, const std::vector< std::vector< int32 > > &graph, int32 *global_index, std::vector< TarjanNode > *tarjan_nodes, std::vector< int32 > *tarjan_stack, std::vector< std::vector< int32 > > *sccs)
void FindSccsTarjan (const std::vector< std::vector< int32 > > &graph, std::vector< std::vector< int32 > > *sccs)
void FindSccs (const std::vector< std::vector< int32 > > &graph, std::vector< std::vector< int32 > > *sccs)
Given a directed graph (where each std::vector<int32> is a list of destination-nodes of arcs coming from the current node), partition it into strongly connected components (i.e.
void MakeSccGraph (const std::vector< std::vector< int32 > > &graph, const std::vector< std::vector< int32 > > &sccs, std::vector< std::vector< int32 > > *scc_graph)
Given a list of sccs of a graph (e.g.
void ComputeTopSortOrderRecursive (int32 node, const std::vector< std::vector< int32 > > &graph, std::vector< bool > *cycle_detector, std::vector< bool > *is_visited, std::vector< int32 > *reversed_orders)
void ComputeTopSortOrder (const std::vector< std::vector< int32 > > &graph, std::vector< int32 > *node_to_order)
Given an acyclic graph (where each std::vector<int32> is a list of destination-nodes of arcs coming from the current node), compute a topological ordering of the graph nodes.
std::string PrintGraphToString (const std::vector< std::vector< int32 > > &graph)
Prints a graph to a string in a pretty way for human readability, e.g.
void ComputeNnetComputationEpochs (const Nnet &nnet, std::vector< int32 > *node_to_epoch)
This function computes the order in which we need to compute each node in the graph, where each node-index n maps to an order-index t = 0, 1, ...
void UnitTestNnetIo ()
static bool UnitTestNnetOptimizeWithOptions (NnetOptimizeOptions opt_config)
static void UnitTestNnetOptimize ()
void IdentifySubmatrixArgs (NnetComputation::Command *command, std::vector< int32 * > *submatrix_args)
This function outputs to "submatrix_args" the addresses of a subset of arguments arg1 through arg6 in "command", that correspond to the indexes of submatrices.
void IdentifySubmatrixArgs (std::vector< NnetComputation::Command > *commands, std::vector< int32 * > *submatrix_args)
This function outputs to "submatrix_args" the addresses of the args (arguments arg1 through arg6) in the vector "commands", that correspond to the indexes of submatrices.
void IdentifyMatrixArgs (std::vector< NnetComputation::Command > *command, std::vector< int32 * > *matrix_args)
This function outputs to "matrix_args" the addresses of a subset of the arguments arg1 through arg6 in commands in "commands", that correspond to the indexes of matrices.
void IdentifyMatrixArgsInComputation (bool include_from_submatrices, NnetComputation *computation, std::vector< int32 * > *matrix_args)
This function outputs to "matrix_args" the addresses of indexes inside 'computation' that correspond to matrices.
void IdentifyIndexesMultiArgs (std::vector< NnetComputation::Command > *commands, std::vector< int32 * > *indexes_multi_args)
Identifies in the vector of commands, arguments that correspond to indexes into the computation's indexes_multi array, and outputs a list of pointers to those arguments to 'indexes_multi_args'.
void IdentifyIndexesRangesArgs (std::vector< NnetComputation::Command > *commands, std::vector< int32 * > *indexes_ranges_args)
Identifies in the vector of commands, arguments that correspond to indexes into the computation's 'indexes_ranges' array, and outputs a list of pointers to those arguments to 'indexes_ranges_args'.
void IdentifyIndexesArgs (std::vector< NnetComputation::Command > *commands, std::vector< int32 * > *indexes_args)
Identifies in the vector of commands, arguments that correspond to indexes into the computation's 'indexes' array, and outputs a list of pointers to those arguments to 'indexes_args'.
void IdentifyMatrixArgs (NnetComputation::Command *command, std::vector< int32 * > *matrix_args)
This function outputs to "matrix_args" the addresses of a subset of the arguments arg1 through arg6 in "command", that correspond to the indexes of matrices.
void IdentifySubmatrixArgsInComputation (NnetComputation *computation, std::vector< int32 * > *submatrix_args)
This function outputs to "submatrix_args" the addresses of integers in 'computation' that correspond to submatrices.
void RenumberComputation (NnetComputation *computation)
This function detects submatrices, matrices, and members of indexes_multi and indexes that are never used (e.g.
void RemoveNoOps (NnetComputation *computation)
Removes commands of type kNoOperation in the computation.
bool ReplaceInInput (const Nnet &nnet, int32 orig_matrix_index, int32 new_matrix_index, NnetComputation *computation)
Wherever matrix orig_matrix_index appears in the input of the network (i.e.
bool ReplaceInOutput (const Nnet &nnet, int32 orig_matrix_index, int32 new_matrix_index, NnetComputation *computation)
Wherever matrix orig_matrix_index appears in the output of the network (i.e.
static
NnetComputation::SubMatrixInfo GetSubMatrixOfSubMatrix (const NnetComputation &computation, int32 submat_a, int32 submat_b)
This static function returns a SubMatrixInfo corresponding to replacing the matrix-index in a's "matrix_index" with, essentially, sub-matrix b.
void LimitDerivativeTimes (const Nnet &nnet, int32 min_deriv_time, int32 max_deriv_time, NnetComputation *computation)
void MoveSizingCommands (const Nnet &nnet, NnetComputation *computation)
This optimization moves commands that initialize matrices to as late as possible, and commands that empty matrices to as early as possible.
void RemoveUnnecessaryZeroing (const Nnet &nnet, NnetComputation *computation)
This optimization function changes, where possible, matrix initializations of type kAllocMatrixZeroed to kAllocMatrixUndefined.
static void ComputeCommandPairs (const std::pair< std::vector< int32 >, std::vector< int32 > > &lists, std::vector< std::pair< int32, int32 > > *pairs)
void RemoveUnnecessaryAllocation (const Nnet &nnet, NnetComputation *computation)
This optimization detects cases where we deallocate a matrix, and then later allocate another matrix of the same size; and replaces them with commands of type kAllocFromOther or kAllocFromOtherZeroed.
void VariableMergingOptimization (const NnetOptimizeOptions &config, const Nnet &nnet, const ComputationRequest &request, NnetComputation *computation)
This wraps class VariableMergingOptimizer in a simplified interface.
void ConsolidateModelUpdate (const Nnet &nnet, const ComputationRequest &request, NnetComputation *computation)
This consolidates the model-update parts of the backprop into larger operations (applicable mostly to recurrent setups)– internally it uses class ModelUpdateConsolidator.
void ConvertAdditionToAssignment (const Nnet &nnet, NnetComputation *computation)
This converts addition operations (things with Add in their names) to copy operations (things with Copy in their names).
void Optimize (const NnetOptimizeOptions &config, const Nnet &nnet, const ComputationRequest &request, NnetComputation *computation)
This is the top-level function for optimizing a computation.
void LimitDerivativeTimes (const Nnet &nnet, const ComputationRequest &request, const NnetOptimizeOptions &opts, NnetComputation *computation)
This optimization, which has no effect unless you set –min-deriv-time or –max-deriv-time, modifies the backprop operations for efficiency based on the assumption that derivatives for any Cindex with t < min_deriv_time or t > max_deriv_time are zero.
void UnitTestConfigLineParse ()
void UnitTestReadConfig ()
void UnitTestDescriptorTokenize ()
void UnitTestSummarizeVector ()
void ExpectOneOrTwoTokens (std::istream &is, bool binary, const std::string &token1, const std::string &token2)
This function is like ExpectToken but for two tokens, and it will either accept token1 and then token2, or just token2.
bool ParseFromString (const std::string &name, std::string *string, int32 *param)
Function used in Init routines.
bool ParseFromString (const std::string &name, std::string *string, bool *param)
This version of ParseFromString is for parameters of type bool, which can appear as any string beginning with f, F, t or T.
bool ParseFromString (const std::string &name, std::string *string, BaseFloat *param)
This version of ParseFromString is for parameters of type BaseFloat.
bool ParseFromString (const std::string &name, std::string *string, std::string *param)
This version of ParseFromString is for parsing strings.
bool ParseFromString (const std::string &name, std::string *string, std::vector< int32 > *param)
This version of ParseFromString handles colon-separated or comma-separated lists of integers.
bool DescriptorTokenize (const std::string &input, std::vector< std::string > *tokens)
This function tokenizes input when parsing Descriptor configuration values.
bool IsValidName (const std::string &name)
Returns true if 'name' would be a valid name for a component or node in a Nnet.
void ReadConfigFile (std::istream &is, std::vector< std::string > *lines)
This function reads in a config file and *appends* its contents to a vector of lines; it is responsible for removing comments (anything after '#') and stripping out any lines that contain only whitespace after comment removal.
std::string ErrorContext (std::istream &is)
Return a string used in error messages.
std::string ErrorContext (const std::string &str)
static void PrintFloatSuccinctly (std::ostream &os, BaseFloat f)
std::string SummarizeVector (const Vector< BaseFloat > &vec)
void PrintParameterStats (std::ostringstream &os, const std::string &name, const CuVector< BaseFloat > &params, bool include_mean=false)
Print to 'os' some information about the mean and standard deviation of some parameters, used in Info() functions in nnet-simple-component.cc.
void PrintParameterStats (std::ostringstream &os, const std::string &name, const CuMatrix< BaseFloat > &params, bool include_mean=false)
Print to 'os' some information about the mean and standard deviation of some parameters, used in Info() functions in nnet-simple-component.cc.
int32 YzxVectorIndex (int32 x, int32 y, int32 z, int32 input_x_dim, int32 input_y_dim, int32 input_z_dim)
int32 ZyxVectorIndex (int32 x, int32 y, int32 z, int32 input_x_dim, int32 input_y_dim, int32 input_z_dim)
void RearrangeIndexes (const std::vector< std::vector< int32 > > &in, std::vector< std::vector< int32 > > *out)
void GenerateConfigSequenceSimplest (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceSimpleContext (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceSimple (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceRnn (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceRnnClockwork (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceLstm (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceLstmType2 (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceCnn (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceCnn2d (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequenceDistribute (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
void GenerateConfigSequence (const NnetGenerationOptions &opts, std::vector< std::string > *configs)
Generates a sequence of at least one config files, output as strings, where the first in the sequence is the initial nnet, and the remaining ones may do things like add layers.
void ComputeExampleComputationRequestSimple (const Nnet &nnet, ComputationRequest *request, std::vector< Matrix< BaseFloat > > *inputs)
This function computes an example computation request, for testing purposes.
static void GenerateRandomComponentConfig (std::string *component_type, std::string *config)
Component * GenerateRandomSimpleComponent ()
Generates random simple component for testing.
bool NnetParametersAreIdentical (const Nnet &nnet1, const Nnet &nnet2, BaseFloat threshold)
Used for testing that the updatable parameters in two networks are the same.
void GenerateSimpleNnetTrainingExample (int32 num_supervised_frames, int32 left_context, int32 right_context, int32 input_dim, int32 output_dim, int32 ivector_dim, NnetExample *example)
Low-level function that generates an nnet training example.
bool ExampleApproxEqual (const NnetExample &eg1, const NnetExample &eg2, BaseFloat delta)
Returns true if the examples are approximately equal (only intended to be used in testing).
void ComputeObjectiveFunction (const GeneralMatrix &supervision, ObjectiveType objective_type, const std::string &output_name, bool supply_deriv, NnetComputer *computer, BaseFloat *tot_weight, BaseFloat *tot_objf)
This function computes the objective function, and if supply_deriv = true, supplies its derivative to the NnetComputation object.
void UnitTestNnetContext ()
int32 NumOutputNodes (const Nnet &nnet)
returns the number of output nodes of this nnet.
int32 NumInputNodes (const Nnet &nnet)
returns the number of input nodes of this nnet.
bool IsSimpleNnet (const Nnet &nnet)
This function returns true if the nnet has the following properties: It has one output, called "output".
void EvaluateComputationRequest (const Nnet &nnet, const ComputationRequest &request, std::vector< std::vector< bool > > *is_computable)
Given an nnet and a computation request, this function works out which requested outputs in the computation request are computable; it outputs this information as a vector "is_computable" indexed by the same indexes as request.outputs.
static void ComputeSimpleNnetContextForShift (const Nnet &nnet, int32 input_start, int32 window_size, int32 *left_context, int32 *right_context)
void ComputeSimpleNnetContext (const Nnet &nnet, int32 *left_context, int32 *right_context)
ComputeNnetContext computes the left-context and right-context of a nnet.
void SetZero (bool is_gradient, Nnet *nnet)
Calls SetZero (with the given is_gradient parameter) on all updatable components of the nnet.
void PerturbParams (BaseFloat stddev, Nnet *nnet)
Calls PerturbParams (with the given stddev) on all updatable components of the nnet.
void ComponentDotProducts (const Nnet &nnet1, const Nnet &nnet2, VectorBase< BaseFloat > *dot_prod)
Returns dot products between two networks of the same structure (calls the DotProduct functions of the Updatable components and fill in the output vector).
std::string PrintVectorPerUpdatableComponent (const Nnet &nnet, const VectorBase< BaseFloat > &vec)
This function is for printing, to a string, a vector with one element per updatable component of the nnet (e.g.
BaseFloat DotProduct (const Nnet &nnet1, const Nnet &nnet2)
Returns dot product between two networks of the same structure (calls the DotProduct functions of the Updatable components and sums up the return values).
void ZeroComponentStats (Nnet *nnet)
Zeroes the component stats in all nonlinear components in the nnet.
void SetLearningRate (BaseFloat learning_rate, Nnet *nnet)
Sets the learning rate for all the components in the nnet to this value.
void ScaleNnet (BaseFloat scale, Nnet *nnet)
Scales the nnet parameters and stats by this scale.
void AddNnet (const Nnet &src, BaseFloat alpha, Nnet *dest)
Does *dest += alpha * src (affects nnet parameters and stored stats).
int32 NumParameters (const Nnet &src)
Returns the total of the number of parameters in the updatable components of the nnet.
void VectorizeNnet (const Nnet &src, VectorBase< BaseFloat > *params)
Copies the nnet parameters to *params, whose dimension must be equal to NumParameters(src).
void UnVectorizeNnet (const VectorBase< BaseFloat > &params, Nnet *dest)
Copies the parameters from params to *dest.
int32 NumUpdatableComponents (const Nnet &dest)
Returns the number of updatable components in the nnet.
std::string NnetInfo (const Nnet &nnet)
This function returns various info about the neural net.
BaseFloat KlDivergence (const Vector< BaseFloat > &p, const Vector< BaseFloat > &q)
void PrintPriorDiagnostics (const Vector< BaseFloat > &old_priors, const Vector< BaseFloat > &new_priors)
void SetPriors (const TransitionModel &tmodel, const Vector< double > &transition_accs, double prior_floor, AmNnetSimple *am_nnet)
int32 GetCount (double expected_count)
bool ContainsSingleExample (const NnetExample &eg, int32 *min_input_t, int32 *max_input_t, int32 *min_output_t, int32 *max_output_t)
Returns true if the "eg" contains just a single example, meaning that all the "n" values in the indexes are zero, and the example has NnetIo members named both "input" and "output".
void FilterExample (const NnetExample &eg, int32 min_input_t, int32 max_input_t, int32 min_output_t, int32 max_output_t, NnetExample *eg_out)
This function filters the indexes (and associated feature rows) in a NnetExample, removing any index/row in an NnetIo named "input" with t < min_input_t or t > max_input_t and any index/row in an NnetIo named "output" with t < min_output_t or t > max_output_t.
bool SelectFromExample (const NnetExample &eg, std::string frame_str, int32 left_context, int32 right_context, int32 frame_shift, NnetExample *eg_out)
This function is responsible for possibly selecting one frame from multiple supervised frames, and reducing the left and right context as specified.
static void ProcessFile (const MatrixBase< BaseFloat > &feats, const MatrixBase< BaseFloat > *ivector_feats, const MatrixBase< BaseFloat > &targets, const std::string &utt_id, bool compress, int32 num_targets, int32 left_context, int32 right_context, int32 frames_per_eg, int64 *num_frames_written, int64 *num_egs_written, NnetExampleWriter *example_writer)
static void ProcessFile (const MatrixBase< BaseFloat > &feats, const MatrixBase< BaseFloat > *ivector_feats, const Posterior &pdf_post, const std::string &utt_id, bool compress, int32 num_pdfs, int32 left_context, int32 right_context, int32 frames_per_eg, int64 *num_frames_written, int64 *num_egs_written, NnetExampleWriter *example_writer)
int32 NumOutputIndexes (const NnetExample &eg)
Variables
static bool computation_checker_warned_unused_input = false
Checks that we never use variables before they are allocated or after they are deallocated, and some other checks that can be done from the MatrixAccesses.
Typedef Documentation
typedef std::pair<int32, Index> Cindex
Definition at line 85 of file nnet-common.h.
typedef TableWriter<KaldiObjectHolder<NnetExample > > NnetExampleWriter
Definition at line 107 of file nnet-example.h.
typedef RandomAccessTableReader<KaldiObjectHolder<NnetExample > > RandomAccessNnetExampleReader
Definition at line 109 of file nnet-example.h.
typedef SequentialTableReader<KaldiObjectHolder<NnetExample > > SequentialNnetExampleReader
Definition at line 108 of file nnet-example.h.
Enumeration Type Documentation
enum AccessType
Enumerator
kReadAccess
kWriteAccess
kReadWriteAccess
Definition at line 76 of file nnet-analyze.h.
                 {
   kReadAccess,
   kWriteAccess,
   kReadWriteAccess
 };
enum CommandType
CommandType is an enum that describes the category of the command used in the NnetComputation.
We declare it outside that class because it's so frequently used and we got tired of typing NnetComputation:: everywhere. We document the commands here.
kAllocMatrixUndefined: Allocate a matrix. arg1 = index of matrix.
kAllocMatrixZeroed: Allocate and zero a matrix. arg1 = index of matrix.
kDeallocMatrix: Deallocate a matrix. arg1 = index of matrix.
kAllocMatrixFromOther: initialize matrix indexed arg1 using memory from matrix indexed arg2 (using shallow swap).
kAllocMatrixFromOtherZeroed: initialize matrix indexed arg1 using memory from matrix indexed arg2 (using shallow swap), then zero the matrix we just allocated.
kPropagate: Forward computation of neural net, see Component::Propagate()
arg1 is is component-index in neural net
arg2 is index into ComponentPrecomputedIndexes (0 if NULL; always 0 for simple Components)
arg3 is sub-matrix index of input
arg4 is sub-matrix index of output
kStoreStats: Call Component::StoreStats() (used for computing diagnostics such as average activations; called after Propagate).
arg1 is component-index in neural net
arg2 is sub-matrix index of the output of the Propagate function
kBackprop: Do the back-propagation operation, see Component::Backprop()
arg1 is index of component in neural net
arg2 is index into ComponentPrecomputedIndexes (0 if NULL; always 0 for simple Components)
arg3 is submatrix-index of input value (input to Propagate()); 0 if unused
arg4 is submatrix-index of output value (output of Propagate()); 0 if unused
arg5 is submatrix-index of output derivative
arg6 is submatrix-index of input derivative; 0 if unused.
kBackpropNoModelUpdate: as kBackprop, but does not set the 'to_update' argument to the Backprop call, even if the model is updatable, so it skips the model-update phase of backprop.
kMatrixCopy: Copy contents of sub-matrix arg2 to sub-matrix arg1
kMatrixAdd: Add contents of sub-matrix arg2 to sub-matrix arg1
kCopyRows: call CopyRows() on sub-matrix arg1 with sub-matrix arg2 and indexes[arg3] as arguments.
kAddRows: call AddRows() on sub-matrix arg1 with sub-matrix arg2 and indexes[arg3] as arguments.
kAddRowsMulti, kAddToRowsMulti, kCopyRowsMulti, kCopyToRowsMulti: Call the corresponding function in class CuMatrix.
arg1 is sub-matrix index of *this matrix in operation
arg2 is index into "indexes_multi", of which each pair is (sub-matrix index, row index) (or (-1,-1) for NULL marker), which is turned into a vector of BaseFloat* (pointers to matrix rows) before being given as the argument to the function.
kAddRowRanges: call AddRowRanges() on sub-matrix arg1, with arg2 as source sub-matrix, and indexes given indexes_ranges[arg3].
kNoOperation: does nothing (sometimes useful during optimization)
kNoOperationMarker: does nothing, but used to mark end of forward commands.
Enumerator
kAllocMatrixUndefined
kAllocMatrixZeroed
kDeallocMatrix
kAllocMatrixFromOther
kAllocMatrixFromOtherZeroed
kPropagate
kStoreStats
kBackprop
kBackpropNoModelUpdate
kMatrixCopy
kMatrixAdd
kCopyRows
kAddRows
kCopyRowsMulti
kCopyToRowsMulti
kAddRowsMulti
kAddToRowsMulti
kAddRowRanges
kNoOperation
kNoOperationMarker
Definition at line 201 of file nnet-computation.h.
                  {
   kAllocMatrixUndefined, kAllocMatrixZeroed,
   kDeallocMatrix, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed,
   kPropagate, kStoreStats, kBackprop, kBackpropNoModelUpdate,
   kMatrixCopy, kMatrixAdd, kCopyRows, kAddRows,
   kCopyRowsMulti, kCopyToRowsMulti, kAddRowsMulti, kAddToRowsMulti,
   kAddRowRanges, kNoOperation, kNoOperationMarker };
enum ComponentProperties
Enumerator
kSimpleComponent
kUpdatableComponent
kLinearInInput
kLinearInParameters
kPropagateInPlace
kPropagateAdds
kReordersIndexes
kBackpropAdds
kBackpropNeedsInput
kBackpropNeedsOutput
kBackpropInPlace
kStoresStats
Definition at line 37 of file nnet-component-itf.h.
{
   kSimpleComponent = 0x001,  // true if number of rows of input equals number of rows
                              // of output and this component doesn't care about the indexes
                              // (i.e. it maps each row of input to each row of output without
                              // regard to the index values).  Will normally be true.
   kUpdatableComponent = 0x002,  // true if the component has parameters that can
                                 // be updated.  Components that return this flag
                                 // must be dynamic_castable to type
                                 // UpdatableComponent (but components of type
                                 // UpdatableComponent do not have to return this
                                 // flag, e.g.  if this instance is not really
                                 // updatable).
   kLinearInInput = 0x004,    // true if the component's output is always a
                              // linear function of its input, i.e. alpha times
                              // input gives you alpha times output.
   kLinearInParameters = 0x008, // true if an updatable component's output is always a
                                // linear function of its parameters, i.e. alpha times
                                // parameters gives you alpha times output.  This is true
                                // for all updatable components we envisage.
   kPropagateInPlace = 0x010,  // true if we can do the propagate operation in-place
                               // (input and output matrices are the same).
                               // Note: if doing backprop, you'd also need to check
                               // that the kBackpropNeedsInput property is not true.
   kPropagateAdds = 0x020,  // true if the Propagate function adds to, rather
                            // than setting, its output.  The Component chooses
                            // whether to add or set, and the calling code has to
                            // accommodate it.
   kReordersIndexes = 0x040,  // true if the ReorderIndexes function might reorder
                              // the indexes (otherwise we can skip calling it).
                              // Must not be set for simple components.
   kBackpropAdds = 0x080,   // true if the Backprop function adds to, rather than
                            // setting, the "in_deriv" output.  The Component chooses
                            // whether to add or set, and the calling code has to
                            // accommodate it.
   kBackpropNeedsInput = 0x100,  // true if backprop operation needs access to
                                 // forward-pass input.
   kBackpropNeedsOutput = 0x200,  // true if backprop operation needs access to
                                  // forward-pass output (e.g. true for Sigmoid).
   kBackpropInPlace = 0x400,   // true if we can do the backprop operation in-place
                              // (input and output matrices may be the same).
   kStoresStats = 0x800       // true if the StoreStats operation stores
                              // statistics e.g. on average node activations and
                              // derivatives of the nonlinearity, (as it does for
                              // Tanh, Sigmoid, ReLU and Softmax).
 };
enum NodeType
Enumerator
kInput
kDescriptor
kComponent
kDimRange
kNone
Definition at line 55 of file nnet-nnet.h.
 { kInput, kDescriptor, kComponent, kDimRange, kNone };
enum ObjectiveType
This enum is for a kind of annotation we associate with output nodes of the network; it's for the convenience of calling code so that if the objective is one of a few standard types, we can compute it directly and know how to interpret the supervision labels.
However, the core of the framework never makes use of the objective types, other than making them available to calling code which then supplies the derivatives.
Objective type kLinear is intended for Neural nets where the final component is a LogSoftmaxComponent, so the log-prob (negative cross-entropy) objective is just a linear function of the input.
Objective type kQuadratic is used to mean the objective function f(x, y) = -0.5 (x-y).(x-y), which is to be maximized, as in the kLinear case.
Enumerator
kLinear
kQuadratic
Definition at line 52 of file nnet-nnet.h.
 { kLinear, kQuadratic };
Function Documentation
void AddNnet (const Nnet & src, BaseFloat alpha, Nnet * dest)
Does *dest += alpha * src (affects nnet parameters and stored stats).
Definition at line 279 of file nnet-utils.cc.
References Component::Add(), Nnet::GetComponent(), KALDI_ERR, and Nnet::NumComponents().
Referenced by main(), and NnetTrainer::Train().
{
   if (src.NumComponents() != dest->NumComponents())
     KALDI_ERR << "Trying to add incompatible nnets.";
   for (int32 c = 0; c < src.NumComponents(); c++) {
     const Component *src_comp = src.GetComponent(c);
     Component *dest_comp = dest->GetComponent(c);
     dest_comp->Add(alpha, *src_comp);
   }
 }
void AppendCindexes (int32 node, const std::vector< Index > & indexes, std::vector< Cindex > * out)
Appends to 'out' the pairs (node, indexes[0]), (node, indexes[1]), ...
Definition at line 966 of file nnet-compile.cc.
References rnnlm::i.
Referenced by Compiler::OutputDebugInfo().
{
   size_t indexes_size = indexes.size();
   if (indexes_size > out->size())
     out->reserve(out->size() + indexes_size);
   for (size_t i = 0; i < indexes_size; i++)
     out->push_back(Cindex(node, indexes[i]));
 }
bool kaldi::nnet3::AssertGraphEqual (const std::vector< std::vector< int32 > > & graph1, const std::vector< std::vector< int32 > > & graph2)
Definition at line 26 of file nnet-graph-test.cc.
References rnnlm::i, and rnnlm::j.
Referenced by UnitTestComputeGraphTranspose(), UnitTestFindSccs(), and UnitTestMakeSccGraph().
{
   if (graph1.size() != graph2.size()) { return false; }
   for (int32 i = 0; i < graph1.size(); ++i) {
     if (graph1[i].size() != graph2[i].size()) { return false; }
     for (int32 j = 0; j < graph1[i].size(); ++j) {
       if (graph1[i][j] != graph2[i][j]) { return false; }
     }
   }
   return true;
 }
bool kaldi::nnet3::AssertVectorEqual (const std::vector< int32 > & vec1, const std::vector< int32 > & vec2)
Definition at line 38 of file nnet-graph-test.cc.
References rnnlm::i.
Referenced by UnitTestComputeTopSortOrder().
{
   if (vec1.size() != vec2.size()) { return false; }
   for (int32 i = 0; i < vec1.size(); ++i) {
     if (vec1[i] != vec2[i]) { return false; }
   }
   return true;
 }
void kaldi::nnet3::BuildTestGraph (std::vector< std::vector< int32 > > * graph)
Definition at line 47 of file nnet-graph-test.cc.
References KALDI_ASSERT.
Referenced by UnitTestComputeGraphTranspose(), UnitTestFindSccs(), and UnitTestMakeSccGraph().
{
   KALDI_ASSERT(graph != NULL);
   graph->clear();
   graph->resize(8);
   // We create the following graph for testing.
   // 0 --> 4
   // 1 --> 0
   // 2 --> 1 3
   // 3 --> 2
   // 4 --> 1
   // 5 --> 1 4 6
   // 6 --> 5
   // 7 --> 7 3 6
   std::vector<int32> tmp;
   tmp.resize(1); tmp[0] = 4; (*graph)[0] = tmp;
   tmp.resize(1); tmp[0] = 0; (*graph)[1] = tmp;
   tmp.resize(2); tmp[0] = 1; tmp[1] = 3; (*graph)[2] = tmp;
   tmp.resize(1); tmp[0] = 2; (*graph)[3] = tmp;
   tmp.resize(1); tmp[0] = 1; (*graph)[4] = tmp;
   tmp.resize(3); tmp[0] = 1; tmp[1] = 4; tmp[2] = 6; (*graph)[5] = tmp;
   tmp.resize(1); tmp[0] = 5; (*graph)[6] = tmp;
   tmp.resize(3); tmp[0] = 7; tmp[1] = 3; tmp[2] = 6; (*graph)[7] = tmp;
 }
void kaldi::nnet3::BuildTestGraphTranspose (std::vector< std::vector< int32 > > * graph)
Definition at line 72 of file nnet-graph-test.cc.
References KALDI_ASSERT.
Referenced by UnitTestComputeGraphTranspose().
{
   KALDI_ASSERT(graph != NULL);
   graph->clear();
   graph->resize(8);
   // We create the following graph for testing.
   // 0 --> 1
   // 1 --> 2 4 5
   // 2 --> 3
   // 3 --> 2 7
   // 4 --> 0 5
   // 5 --> 6
   // 6 --> 5 7
   // 7 --> 7
   std::vector<int32> tmp;
   tmp.resize(1); tmp[0] = 1; (*graph)[0] = tmp;
   tmp.resize(3); tmp[0] = 2; tmp[1] = 4; tmp[2] = 5; (*graph)[1] = tmp;
   tmp.resize(1); tmp[0] = 3; (*graph)[2] = tmp;
   tmp.resize(2); tmp[0] = 2; tmp[1] = 7; (*graph)[3] = tmp;
   tmp.resize(2); tmp[0] = 0; tmp[1] = 5; (*graph)[4] = tmp;
   tmp.resize(1); tmp[0] = 6; (*graph)[5] = tmp;
   tmp.resize(2); tmp[0] = 5; tmp[1] = 7; (*graph)[6] = tmp;
   tmp.resize(1); tmp[0] = 7; (*graph)[7] = tmp;
 }
void kaldi::nnet3::BuildTestSccGraph (std::vector< std::vector< int32 > > * scc_graph)
Definition at line 114 of file nnet-graph-test.cc.
References KALDI_ASSERT.
Referenced by UnitTestComputeTopSortOrder(), and UnitTestMakeSccGraph().
{
   KALDI_ASSERT(scc_graph != NULL);
   scc_graph->clear();
   scc_graph->resize(4);
   // We create the following SCC graph for testing.
   // 0 -->
   // 1 --> 0
   // 2 --> 0
   // 3 --> 1 2
   std::vector<int32> tmp;
   tmp.resize(0); (*scc_graph)[0] = tmp;
   tmp.resize(1); tmp[0] = 0; (*scc_graph)[1] = tmp;
   tmp.resize(1); tmp[0] = 0; (*scc_graph)[2] = tmp;
   tmp.resize(2); tmp[0] = 1; tmp[1] = 2; (*scc_graph)[3] = tmp;
 }
void kaldi::nnet3::BuildTestSccs (std::vector< std::vector< int32 > > * sccs)
Definition at line 97 of file nnet-graph-test.cc.
References KALDI_ASSERT.
Referenced by UnitTestFindSccs(), and UnitTestMakeSccGraph().
{
   KALDI_ASSERT(sccs != NULL);
   sccs->clear();
   sccs->resize(4);
   // We create the following SCCs for testing.
   // 0 --> 1 4 0
   // 1 --> 3 2
   // 2 --> 6 5
   // 3 --> 7
   std::vector<int32> tmp;
   tmp.resize(3); tmp[0] = 1; tmp[1] = 4; tmp[2] = 0; (*sccs)[0] = tmp;
   tmp.resize(2); tmp[0] = 3; tmp[1] = 2; (*sccs)[1] = tmp;
   tmp.resize(2); tmp[0] = 6; tmp[1] = 5; (*sccs)[2] = tmp;
   tmp.resize(1); tmp[0] = 7; (*sccs)[3] = tmp;
 }
void kaldi::nnet3::BuildTestTopSortOrder (std::vector< int32 > * node_to_order)
Definition at line 131 of file nnet-graph-test.cc.
References KALDI_ASSERT.
Referenced by UnitTestComputeTopSortOrder().
{
   KALDI_ASSERT(node_to_order != NULL);
   node_to_order->clear();
   node_to_order->resize(4);
   // The topological sorting order of the above SCC graph is as follows (from
   // our particular algorithm):
   // 0 --> 3
   // 1 --> 2
   // 2 --> 1
   // 3 --> 0
   (*node_to_order)[0] = 3;
   (*node_to_order)[1] = 2;
   (*node_to_order)[2] = 1;
   (*node_to_order)[3] = 0;
 }
void CheckComputation (const Nnet & nnet, const ComputationRequest & request, const NnetComputation & computation, bool check_rewrite = false)
This is a convenience interface for class ComputationChecker.
Call it with check_rewrite = true only if the optimization is pre-optimization.
Definition at line 975 of file nnet-analyze.cc.
References ComputationChecker::Check(), and CheckComputationOptions::check_rewrite.
Referenced by Optimize().
{
   CheckComputationOptions opts;
   opts.check_rewrite = check_rewrite;
   ComputationChecker checker(opts, nnet, computation);
   checker.Check();
 }
void ComponentDotProducts (const Nnet & nnet1, const Nnet & nnet2, VectorBase< BaseFloat > * dot_prod)
Returns dot products between two networks of the same structure (calls the DotProduct functions of the Updatable components and fill in the output vector).
Definition at line 186 of file nnet-utils.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), UpdatableComponent::DotProduct(), Nnet::GetComponent(), KALDI_ASSERT, kUpdatableComponent, Nnet::NumComponents(), and Component::Properties().
Referenced by main().
{
   KALDI_ASSERT(nnet1.NumComponents() == nnet2.NumComponents());
   int32 updatable_c = 0;
   for (int32 c = 0; c < nnet1.NumComponents(); c++) {
     const Component *comp1 = nnet1.GetComponent(c),
                     *comp2 = nnet2.GetComponent(c);
     if (comp1->Properties() & kUpdatableComponent) {
       const UpdatableComponent
           *u_comp1 = dynamic_cast<const UpdatableComponent*>(comp1),
           *u_comp2 = dynamic_cast<const UpdatableComponent*>(comp2);
       KALDI_ASSERT(u_comp1 != NULL && u_comp2 != NULL);
       dot_prod->Data()[updatable_c] = u_comp1->DotProduct(*u_comp2);
       updatable_c++;
     }
   }
   KALDI_ASSERT(updatable_c == dot_prod->Dim());
 }
void ComputeAccuracy (const GeneralMatrix & supervision, const CuMatrixBase< BaseFloat > & nnet_output, BaseFloat * tot_weight, BaseFloat * tot_accuracy)
This function computes the frame accuracy for this minibatch.
It interprets the supervision information in "supervision" as labels or soft labels; it picks the maximum element in each row and treats that as the label for purposes of computing the accuracy (in situations where you would care about the accuracy, there will normally be just one nonzero label). The hypothesized labels are computed by taking the neural net output (supplied as a CuMatrix), and finding the maximum element in each row. See also the function ComputeObjectiveFunction, declared in nnet-training.h.
Parameters
[in] supervision The supervision information (no elements may be negative); only the maximum in each row matters (although we expect that usually there will be just one nonzero element in each row); and the sum of each row is interpreted as a weighting factor (although we expect that this sum will usually be one).
[in] nnet_output The neural net output must have the same dimensions as the supervision. Only the index of the maximum value in each row matters. Ties will be broken in an unspecified way.
[out] tot_weight The sum of the values in the supervision matrix
[out] tot_accuracy The total accuracy, equal to the sum over all row indexes r such that the maximum column index of row r of supervision and nnet_output is the same, of the sum of the r'th row of supervision (i.e. the row's weight).
Definition at line 156 of file nnet-diagnostics.cc.
References CuMatrixBase< Real >::FindRowMaxId(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), GeneralMatrix::GetSparseMatrix(), KALDI_ASSERT, KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kaldi::kSparseMatrix, SparseVector< Real >::Max(), VectorBase< Real >::Max(), CuMatrixBase< Real >::NumCols(), GeneralMatrix::NumCols(), CuMatrixBase< Real >::NumRows(), GeneralMatrix::NumRows(), SparseMatrix< Real >::Row(), SparseVector< Real >::Sum(), VectorBase< Real >::Sum(), and GeneralMatrix::Type().
Referenced by NnetComputeProb::ProcessOutputs().
{
   int32 num_rows = nnet_output.NumRows(),
       num_cols = nnet_output.NumCols();
   KALDI_ASSERT(supervision.NumRows() == num_rows &&
                supervision.NumCols() == num_cols);
   CuArray<int32> best_index(num_rows);
   nnet_output.FindRowMaxId(&best_index);
   std::vector<int32> best_index_cpu;
   // wasteful copy, but doesn't dominate.
   best_index.CopyToVec(&best_index_cpu);
   double tot_weight = 0.0,
       tot_accuracy = 0.0;
   // note: we expect that in most cases where this code is called,
   // supervision.Type() will be kSparseMatrix.
   switch (supervision.Type()) {
     case kCompressedMatrix: {
       Matrix<BaseFloat> mat;
       supervision.GetMatrix(&mat);
       for (int32 r = 0; r < num_rows; r++) {
         SubVector<BaseFloat> vec(mat, r);
         BaseFloat row_sum = vec.Sum();
         KALDI_ASSERT(row_sum >= 0.0);
         int32 best_index;
         vec.Max(&best_index);  // discard max value.
         tot_weight += row_sum;
         if (best_index == best_index_cpu[r])
           tot_accuracy += row_sum;
       }
       break;
     }
     case kFullMatrix: {
       const Matrix<BaseFloat> &mat = supervision.GetFullMatrix();
       for (int32 r = 0; r < num_rows; r++) {
         SubVector<BaseFloat> vec(mat, r);
         BaseFloat row_sum = vec.Sum();
         KALDI_ASSERT(row_sum >= 0.0);
         int32 best_index;
         vec.Max(&best_index);  // discard max value.
         tot_weight += row_sum;
         if (best_index == best_index_cpu[r])
           tot_accuracy += row_sum;
       }
       break;
     }
     case kSparseMatrix: {
       const SparseMatrix<BaseFloat> &smat = supervision.GetSparseMatrix();
       for (int32 r = 0; r < num_rows; r++) {
         const SparseVector<BaseFloat> &row = smat.Row(r);
         BaseFloat row_sum = row.Sum();
         int32 best_index;
         row.Max(&best_index);
         KALDI_ASSERT(best_index < num_cols);
         tot_weight += row_sum;
         if (best_index == best_index_cpu[r])
           tot_accuracy += row_sum;
       }
       break;
     }
     default: KALDI_ERR << "Bad general-matrix type.";
   }
   *tot_weight_out = tot_weight;
   *tot_accuracy_out = tot_accuracy;
 }
void ComputeCommandAttributes (const Nnet & nnet, const NnetComputation & computation, const ComputationVariables & vars, std::vector< CommandAttributes > * attributes)
Definition at line 267 of file nnet-analyze.cc.
References ComputationVariables::AppendVariablesForMatrix(), NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::arg3, NnetComputation::Command::arg4, NnetComputation::Command::arg5, NnetComputation::Command::arg6, NnetComputation::Command::command_type, NnetComputation::commands, count, Nnet::GetComponent(), CommandAttributes::has_side_effects, rnnlm::i, NnetComputation::indexes, NnetComputation::indexes_multi, IndexesMultiToSubmatrixIndexes(), kAddRowRanges, kAddRows, kAddRowsMulti, kAddToRowsMulti, KALDI_ERR, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed, kAllocMatrixUndefined, kAllocMatrixZeroed, kBackprop, kBackpropAdds, kBackpropNoModelUpdate, kCopyRows, kCopyRowsMulti, kCopyToRowsMulti, kDeallocMatrix, kMatrixAdd, kMatrixCopy, kNoOperation, kNoOperationMarker, kPropagate, kPropagateAdds, kReadAccess, kReadWriteAccess, kStoreStats, kUpdatableComponent, kWriteAccess, CommandAttributes::matrices_read, CommandAttributes::matrices_written, Component::Properties(), ComputationVariables::RecordAccessForSubmatrix(), kaldi::SortAndUniq(), CommandAttributes::submatrices_read, CommandAttributes::submatrices_written, CommandAttributes::variables_read, and CommandAttributes::variables_written.
Referenced by Analyzer::Init(), MoveSizingCommands(), and NnetComputer::NnetComputer().
{
   int32 num_commands = computation.commands.size();
   attributes->clear();
   attributes->resize(num_commands);
   for (int32 command_index = 0; command_index < num_commands; command_index++) {
     const NnetComputation::Command &c = computation.commands[command_index];
     CommandAttributes &attr = (*attributes)[command_index];
     switch (c.command_type) {
       case kAllocMatrixZeroed:
       case kAllocMatrixFromOtherZeroed:
         vars.AppendVariablesForMatrix(c.arg1, &attr.variables_written);
         attr.matrices_written.push_back(c.arg1);
         break;
       case kAllocMatrixUndefined: // nothing is written here.
       case kDeallocMatrix: // ditto.
       case kAllocMatrixFromOther: // ditto.
         break;
       case kPropagate:
         vars.RecordAccessForSubmatrix(c.arg3, kReadAccess, &attr);
         if (nnet.GetComponent(c.arg1)->Properties() & kPropagateAdds)
           vars.RecordAccessForSubmatrix(c.arg4, kReadWriteAccess, &attr);
         else
           vars.RecordAccessForSubmatrix(c.arg4, kWriteAccess, &attr);
         break;
       case kStoreStats:
         vars.RecordAccessForSubmatrix(c.arg2, kReadAccess, &attr);
         break;
       case kBackprop:
       case kBackpropNoModelUpdate:
         vars.RecordAccessForSubmatrix(c.arg3, kReadAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg4, kReadAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg5, kReadAccess, &attr);
         if (nnet.GetComponent(c.arg1)->Properties() & kBackpropAdds)
           vars.RecordAccessForSubmatrix(c.arg6, kReadWriteAccess, &attr);
         else
           vars.RecordAccessForSubmatrix(c.arg6, kWriteAccess, &attr);
         if (c.command_type == kBackprop &&
             nnet.GetComponent(c.arg1)->Properties() & kUpdatableComponent)
           attr.has_side_effects = true;
         break;
       case kMatrixCopy:
         vars.RecordAccessForSubmatrix(c.arg1, kWriteAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg2, kReadAccess, &attr);
         break;
       case kMatrixAdd:
         vars.RecordAccessForSubmatrix(c.arg1, kReadWriteAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg2, kReadAccess, &attr);
         break;
       case kAddRows:
         vars.RecordAccessForSubmatrix(c.arg1, kReadWriteAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg2, kReadAccess, &attr);
         break;
       case kCopyRows: {
         const std::vector<int32> &indexes = computation.indexes[c.arg3];
         // if there are -1's in "indexes", then the result of the operation
         // will depend on the initial value of the matrix, so it's
         // a "rw" operation, not a "write" operation.
         if (std::count(indexes.begin(), indexes.end(), -1) > 0)
           vars.RecordAccessForSubmatrix(c.arg1, kReadWriteAccess, &attr);
         else
           vars.RecordAccessForSubmatrix(c.arg1, kWriteAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg2, kReadAccess, &attr);
         break;
       }
       case kAddRowsMulti: {
         vars.RecordAccessForSubmatrix(c.arg1, kReadWriteAccess, &attr);
         std::vector<int32> submatrix_indexes;
         IndexesMultiToSubmatrixIndexes(computation.indexes_multi[c.arg2],
                                        &submatrix_indexes);
         for (size_t i = 0; i < submatrix_indexes.size(); i++)
           vars.RecordAccessForSubmatrix(submatrix_indexes[i],
                                         kReadAccess, &attr);
         break;
       }
       case kCopyRowsMulti: {
         std::vector<int32> submatrix_indexes;
         IndexesMultiToSubmatrixIndexes(computation.indexes_multi[c.arg2],
                                        &submatrix_indexes);
         // note: the CopyRows command assigns zero in cases where
         // there is no source for some row
         vars.RecordAccessForSubmatrix(c.arg1, kWriteAccess, &attr);
         for (size_t i = 0; i < submatrix_indexes.size(); i++)
           vars.RecordAccessForSubmatrix(submatrix_indexes[i],
                                         kReadAccess, &attr);
         break;
       }
       case kAddToRowsMulti:
       case kCopyToRowsMulti: {
         vars.RecordAccessForSubmatrix(c.arg1, kReadAccess, &attr);
         // if the submatrixes we're writing to (in kCopyToRowsMulti) had all
         // rows covered, it would be a pure write operation.
         std::vector<int32> submatrix_indexes;
         IndexesMultiToSubmatrixIndexes(computation.indexes_multi[c.arg2],
                                        &submatrix_indexes);
         for (size_t i = 0; i < submatrix_indexes.size(); i++)
           vars.RecordAccessForSubmatrix(submatrix_indexes[i], kReadWriteAccess,
                                         &attr);
         break;
       }
       case kAddRowRanges: {
         vars.RecordAccessForSubmatrix(c.arg1, kReadWriteAccess, &attr);
         vars.RecordAccessForSubmatrix(c.arg2, kReadAccess, &attr);
         break;
       }
       case kNoOperation:
       case kNoOperationMarker:
         break;
       default:
         KALDI_ERR << "Unknown command type.";
     }
     SortAndUniq(&attr.variables_read);
     SortAndUniq(&attr.variables_written);
     SortAndUniq(&attr.submatrices_read);
     SortAndUniq(&attr.submatrices_written);
     SortAndUniq(&attr.matrices_read);
     SortAndUniq(&attr.matrices_written);
   }
 }
static void kaldi::nnet3::ComputeCommandPairs (const std::pair< std::vector< int32 >, std::vector< int32 > > & lists, std::vector< std::pair< int32, int32 > > * pairs) static
Definition at line 158 of file nnet-optimize.cc.
References kaldi::CopyVectorToSet(), rnnlm::d, and KALDI_PARANOID_ASSERT.
Referenced by RemoveUnnecessaryAllocation().
{
   std::vector<int32> d_list = lists.first;
   std::set<int32> a_set;
   CopyVectorToSet(lists.second, &a_set);
   std::vector<int32>::reverse_iterator iter = d_list.rbegin(),
       end = d_list.rend();
   // from the latest to the earliest deallocation command...
   for (; iter != end; ++iter) {
     int32 d = *iter;
     std::set<int32>::iterator a_iter = a_set.upper_bound(d);
     // a_iter is an iterator to the first element a of the set 'a_set' such
     // that a > d, or a_set.end() if no such element exists.
     if (a_iter == a_set.end())
       continue;  // we will output no pair for this d.
     int32 a = *a_iter;
     KALDI_PARANOID_ASSERT(a > d);  // or code error
     a_set.erase(a_iter);  // remove this a from 'a_set' so it doesn't get used
                           // twice
     pairs->push_back(std::pair<int32,int32>(d, a));
   }
 }
void kaldi::nnet3::ComputeComputationGraph (const Nnet & nnet, const ComputationRequest & request, ComputationGraph * graph)
Definition at line 1058 of file nnet-computation-graph.cc.
References kaldi::nnet3::computation_graph::AddInputToGraph(), kaldi::nnet3::computation_graph::AddOutputToGraph(), ComputationGraph::cindexes, NetworkNode::component_index, ComputationGraph::dependencies, NetworkNode::descriptor, ComputationGraph::GetCindexId(), Nnet::GetComponent(), Descriptor::GetDependencies(), Component::GetInputIndexes(), Nnet::GetNode(), rnnlm::i, ComputationGraph::is_input, KALDI_ASSERT, KALDI_ERR, kComponent, kDescriptor, kDimRange, kInput, ComputationRequest::misc_info, rnnlm::n, NetworkNode::node_index, NetworkNode::node_type, kaldi::SortAndUniq(), and NetworkNode::u.
{
   using namespace computation_graph;
   // make sure graph is empty at the start.
   KALDI_ASSERT(graph->cindexes.empty());
   AddInputToGraph(request, nnet, graph);
   AddOutputToGraph(request, nnet, graph);
   // queue of cindex_ids to process.
   std::vector<int32> queue(graph->cindexes.size());
   for (int32 i = 0; i < graph->cindexes.size(); i++)
     queue.push_back(i);
   while (!queue.empty()) {
     int32 cindex_id = queue.back();
     queue.pop_back();
     if (static_cast<int32>(graph->dependencies.size()) <= cindex_id)
       graph->dependencies.resize(cindex_id + 1);
     if (graph->is_input[cindex_id])
       continue;
     Cindex cindex = graph->cindexes[cindex_id];
     // find the dependencies of this cindex.
     int32 n = cindex.first;
     const Index &index = cindex.second;
     const NetworkNode &node = nnet.GetNode(n);
     std::vector<Cindex> input_cindexes;
     // the following switch statement sets up "input_cindexes".
     switch (node.node_type) {
       case kDescriptor: {
         // desc describes how this node obtains its input from other nodes.
         const Descriptor &desc = node.descriptor;
         desc.GetDependencies(index, &input_cindexes);
         break;
       }
       case kComponent: {
         int32 c = node.u.component_index;
         const Component *component = nnet.GetComponent(c);
         std::vector<Index> input_indexes;
         component->GetInputIndexes(request.misc_info, index,
                                    &input_indexes);
         // each Component node should be preceded by a node that describes its
         // input, of type kDescriptor
         KALDI_ASSERT(nnet.GetNode(n-1).node_type ==
                      kDescriptor);
         input_cindexes.resize(input_indexes.size());
         for (size_t i = 0; i < input_indexes.size(); i++) {
           input_cindexes[i].first = n - 1;  // preceding node.
           input_cindexes[i].second = input_indexes[i];
         }
         break;
       }
       case kDimRange: {
         input_cindexes.resize(1);
         input_cindexes[0] = Cindex(node.u.node_index, index);
         break;
       }
       case kInput: default:
         // for kInput, you should have hit the "continue" statement above.
         KALDI_ERR << "Invalid node type";
     }
     std::vector<int32> &this_dep = graph->dependencies[cindex_id];
     int32 num_dependencies = input_cindexes.size();
     this_dep.resize(num_dependencies);
     for (size_t i = 0; i < num_dependencies; i++) {
       bool is_input = false, is_new;
       int32 dep_cindex_id = graph->GetCindexId(input_cindexes[i],
                                                is_input, &is_new);
       this_dep[i] = dep_cindex_id;
       if (is_new)
         queue.push_back(dep_cindex_id);
     }
     // remove duplicates of dependencies.
     SortAndUniq(&this_dep);
   }
 }
void ComputeComputationPhases (const Nnet & nnet, const ComputationGraph & computation_graph, std::vector< std::vector< int32 > > * phases)
Compute the phases in which we can compute each cindex in the computation; the cindexes will be grouped into phases.
This is a prelude to computing the steps of the computation (ComputeComputationSteps), and gives a coarser ordering than the steps. All input cindexes go to phase 0, and in general a phase contains all cindexes not in previous phases that can be computed immediately from cindexes in previous phases. It is an error if some cindexes cannot be computed (we assume that you have called PruneComputationGraph before this function), and it is an error if the computation graph contains cycles. Each element of *phases will be sorted numerically.
Definition at line 1252 of file nnet-computation-graph.cc.
References ComputationGraph::cindexes, ComputeComputationPhasesForEpoch(), kaldi::nnet3::computation_graph::ComputeDependenciesSubset(), kaldi::nnet3::computation_graph::ComputeEpochInfo(), ComputeGraphTranspose(), KALDI_ASSERT, and SumVectorSizes().
Referenced by Compiler::CreateComputation().
{
   using namespace computation_graph;
   int32 num_cindex_ids = graph.cindexes.size();
   std::vector<int32> cindex_id_to_epoch;
   std::vector<std::vector<int32 > > epochs;
   std::vector<bool> epoch_is_trivial;
   ComputeEpochInfo(nnet, graph, &cindex_id_to_epoch,
                         &epochs, &epoch_is_trivial);
   KALDI_ASSERT(SumVectorSizes(epochs) == num_cindex_ids);
   // dependencies_subset contains just the subset of dependencies
   // of each cindex_id, that have the same epoch index as
   // cindex_id itself.  This will be used to correctly order
   // cindexes that have a certain epoch index (i.e. they
   // likely come from the same strongly connected component of
   // the graph of nodes).
   std::vector<std::vector<int32> > dependencies_subset;
   ComputeDependenciesSubset(graph, cindex_id_to_epoch,
                             &dependencies_subset);
   // depend_on_subset is a subset of the normal "depend_on" list (i.e. a list of
   // all cindex_ids that depend on the current cindex_id), limited to just those
   // cindex_ids that have the same epoch index.
   std::vector<std::vector<int32> > depend_on_subset;
   ComputeGraphTranspose(dependencies_subset, &depend_on_subset);
   int32 num_epoch_indexes = epoch_is_trivial.size();
   // "phase_index" is used inside ComputeComputationPhasesForEpoch.
   std::vector<int32> phase_index(num_cindex_ids, -1);
   if (phases) {
     phases->clear();
     phases->reserve(50);  // minimize unnecessary copies.  50 is very
                             // arbitrarily chosen.
   }
   for (int32 epoch = 0;
        epoch < num_epoch_indexes;
        epoch++)
     ComputeComputationPhasesForEpoch(nnet, graph,
                                      dependencies_subset,
                                      depend_on_subset,
                                      epochs[epoch],
                                      epoch_is_trivial[epoch],
                                      &phase_index, phases);
   // make sure everything was computable.  If the next assert fails it's likely
   // a bug in this function or in PruneComputataionGraph.
   KALDI_ASSERT(SumVectorSizes(*phases) == num_cindex_ids);
 }
static void kaldi::nnet3::ComputeComputationPhasesForEpoch (const Nnet & nnet, const ComputationGraph & graph, const std::vector< std::vector< int32 > > & dependencies_subset, const std::vector< std::vector< int32 > > & depend_on_subset, const std::vector< int32 > & this_epoch, bool epoch_is_trivial, std::vector< int32 > * phase_index, std::vector< std::vector< int32 > > * phases) inline static
Definition at line 1162 of file nnet-computation-graph.cc.
References rnnlm::d, rnnlm::i, KALDI_ASSERT, KALDI_ERR, and kaldi::SortAndUniq().
Referenced by ComputeComputationPhases().
{
   std::vector<int32> this_phase, next_phase_candidates;
   if (this_epoch.empty())
     return;
   if (epoch_is_trivial) { // an optimization
     this_phase = this_epoch;
   } else {
     //  Start out with all elements of this epoch that have no
     // dependencies within the same epoch
     std::vector<int32>::const_iterator iter = this_epoch.begin(),
         end = this_epoch.end();
     for (; iter != end; ++iter) {
       int32 cindex_id = *iter;
       if (dependencies_subset[cindex_id].empty())
         this_phase.push_back(cindex_id);
     }
   }
   // if the next assert fails, the graph at the level of cindex_ids is not acyclic.
   KALDI_ASSERT(!this_phase.empty() &&
                "Trying to process computation with cycles");
   while (!this_phase.empty()) {
     phases->push_back(this_phase);
     // The next if-statement is an optimization: if for this epoch index
     // there is just one node, there will be just one order-index for this
     // epoch, so we can skip the rest of this loop.  Note: if
     // epoch == 0, even if there is just one node, cindex_ids from
     // multiple nodes may be put here because of the rule that cindex_ids which
     // are inputs always get epoch 0.  But it's still true that they
     // will have no dependencies, so we can still skip the code below.
     if (epoch_is_trivial)
       return;
     int32 cur_phase_index = phases->size() - 1;
     // next_phases_candidates is a list of cindexes that we should check
     // whether they are computable now, because one of the things they depend
     // on just became computable.
     next_phase_candidates.clear();
     int32 size = this_phase.size();
     for (int32 i = 0; i < size; i++) {
       int32 c = this_phase[i];  // c is a cindex_id with phase cur_phase_index.
       (*phase_index)[c] = cur_phase_index;
       std::vector<int32>::const_iterator iter = depend_on_subset[c].begin(),
           end = depend_on_subset[c].end();
       for (; iter != end; ++iter) {
         int32 d = *iter;  // cindex_id that depends on c.
         next_phase_candidates.push_back(d);
       }
     }
     SortAndUniq(&next_phase_candidates);
     this_phase.clear();
     // now check the candidates that might be in the next phase, and put any
     // members that we are currently able to compute into "this_phase".
     std::vector<int32>::const_iterator iter = next_phase_candidates.begin(),
         end = next_phase_candidates.end();
     for (; iter != end; ++iter) {
       int32 c = *iter;
       std::vector<int32>::const_iterator
           dep_iter = dependencies_subset[c].begin(),
           dep_end = dependencies_subset[c].end();
       for (; dep_iter != dep_end; ++dep_iter) {
         int32 d = *dep_iter;  // d is cindex_id that c depends on.
         if ((*phase_index)[d] < 0)  // we can't compute c yet as something we depend
           break;              // on is not yet computed.
       }
       if (dep_iter == dep_end) {
         // we reached the end and did not break -> all dependencies satisfied
         this_phase.push_back(c);
       }
     }
     if (!next_phase_candidates.empty() && this_phase.empty())  {
       // this should have been caught earlier so likely a code error rather than
       // a problem with user input.
       KALDI_ERR << "Possibly some cindexes were not reachable (code error?)";
     }
   }
 }
void ComputeComputationSteps (const Nnet & nnet, const ComputationRequest & request, const std::vector< std::vector< int32 > > & phases, ComputationGraph * computation_graph, std::vector< std::vector< int32 > > * steps)
This function arranges the cindex_ids of the computation into a sequence of lists called "steps", which will correspond roughly to the commands in the compiled computation.
The steps are finer than phases. (See Organizing the computation into steps for more info). To summarize the properties that these steps will satisfy:
All cindex_ids within a given step correspond to the same node in the graph
All dependencies of cindex_ids within a given step have been computed in earlier steps.
There are also some extra, more obscure properties that the sequence of steps must satisfy:
Any input or output in the ComputationRequest must be in one step, with the Indexes in the same order as specified in the ComputationRequest. (Note: inputs can be for nodes of type kComponent as well as kInput).
If a step corresponds to a node of type kComponent (and does not correspond to an input in the ComputationRequest), then the immediately preceding step must correspond to a node of type kDescriptor, and the sequence of Indexes in the two steps must be identical.
If a step corresponds to a node of type kDimRange, then there must be another step corresponding to the source node, with exactly the same Indexes appearing in the same order. (This lets us use a sub-matrix for the kDimRange node).
The reason why computation_graph is not provided as a const argument is that in order to ensure the final property we may have to add a few new cindex_ids.
Definition at line 1763 of file nnet-computation-graph.cc.
References kaldi::nnet3::compute_computation_steps::AddComponentInputSteps(), kaldi::nnet3::compute_computation_steps::AddComponentSteps(), kaldi::nnet3::compute_computation_steps::AddDimRangeSteps(), kaldi::nnet3::compute_computation_steps::AddInputSteps(), kaldi::nnet3::compute_computation_steps::AddOutputSteps(), ComputationGraph::cindexes, rnnlm::i, KALDI_ASSERT, and kaldi::nnet3::compute_computation_steps::ReorderIndexes().
Referenced by Compiler::CreateComputation().
{
   using namespace compute_computation_steps;
   steps->clear();
   AddInputSteps(nnet, request, *graph, steps);
   {
     std::vector<std::vector<int32> > component_steps;
     AddComponentSteps(nnet, *graph, phases, &component_steps);
     AddComponentInputSteps(*graph, &component_steps, steps);
   }
   // output steps don't get reordered so we do the reordering before adding
   // them.
   ReorderIndexes(nnet, request, *graph, steps);
   AddDimRangeSteps(nnet, graph, steps);
   AddOutputSteps(nnet, request, *graph, steps);
   int32 num_cindexes = 0;
   for (int32 i = 0; i < steps->size(); i++)
     num_cindexes += (*steps)[i].size();
   // The next line has ">=" not "==" because it is possible (although unlikely
   // in normal setups) that some cindexes of Descriptors which are at the inputs
   // of Components,
   KALDI_ASSERT(num_cindexes >= graph->cindexes.size());
 }
void ComputeExampleComputationRequestSimple (const Nnet & nnet, ComputationRequest * request, std::vector< Matrix< BaseFloat > > * inputs)
This function computes an example computation request, for testing purposes.
The "Simple" in the name means that it currently only supports neural nets that satisfy IsSimple(nnet) (defined in nnet-utils.h). If there are 2 inputs, the "input" will be first, followed by "ivector".
Definition at line 778 of file nnet-test-utils.cc.
References ComputeSimpleNnetContext(), Nnet::InputDim(), ComputationRequest::inputs, IsSimpleNnet(), KALDI_ASSERT, rnnlm::n, ComputationRequest::need_model_derivative, ComputationRequest::outputs, kaldi::Rand(), and ComputationRequest::store_component_stats.
Referenced by UnitTestNnetAnalyze(), UnitTestNnetCompile(), UnitTestNnetCompute(), UnitTestNnetInputDerivatives(), UnitTestNnetModelDerivatives(), and UnitTestNnetOptimizeWithOptions().
{
   KALDI_ASSERT(IsSimpleNnet(nnet));
   int32 left_context, right_context;
   ComputeSimpleNnetContext(nnet, &left_context, &right_context);
   int32 num_output_frames = 1 + Rand() % 10,
       output_start_frame = Rand() % 10,
       num_examples = 1 + Rand() % 10,
       output_end_frame = output_start_frame + num_output_frames,
       input_start_frame = output_start_frame - left_context - (Rand() % 3),
       input_end_frame = output_end_frame + right_context + (Rand() % 3),
       n_offset = Rand() % 2;
   bool need_deriv = (Rand() % 2 == 0);
   request->inputs.clear();
   request->outputs.clear();
   inputs->clear();
   std::vector<Index> input_indexes, ivector_indexes, output_indexes;
   for (int32 n = n_offset; n < n_offset + num_examples; n++) {
     for (int32 t = input_start_frame; t < input_end_frame; t++)
       input_indexes.push_back(Index(n, t, 0));
     for (int32 t = output_start_frame; t < output_end_frame; t++)
       output_indexes.push_back(Index(n, t, 0));
     ivector_indexes.push_back(Index(n, 0, 0));
   }
   request->outputs.push_back(IoSpecification("output", output_indexes));
   if (need_deriv || (Rand() % 3 == 0))
     request->outputs.back().has_deriv = true;
   request->inputs.push_back(IoSpecification("input", input_indexes));
   if (need_deriv && (Rand() % 2 == 0))
     request->inputs.back().has_deriv = true;
   int32 input_dim = nnet.InputDim("input");
   KALDI_ASSERT(input_dim > 0);
   inputs->push_back(
       Matrix<BaseFloat>((input_end_frame - input_start_frame) * num_examples,
                         input_dim));
   inputs->back().SetRandn();
   int32 ivector_dim = nnet.InputDim("ivector");  // may not exist.
   if (ivector_dim != -1) {
     request->inputs.push_back(IoSpecification("ivector", ivector_indexes));
     inputs->push_back(Matrix<BaseFloat>(num_examples, ivector_dim));
     inputs->back().SetRandn();
     if (need_deriv && (Rand() % 2 == 0))
       request->inputs.back().has_deriv = true;
   }
   if (Rand() % 2 == 0)
     request->need_model_derivative = need_deriv;
   if (Rand() % 2 == 0)
     request->store_component_stats = true;
 }
void ComputeGraphTranspose (const std::vector< std::vector< int32 > > & graph, std::vector< std::vector< int32 > > * graph_transpose)
Outputs a graph in which the order of arcs is reversed.
Definition at line 63 of file nnet-graph.cc.
References rnnlm::n.
Referenced by ComputeComputationPhases(), ComputeNnetComputationEpochs(), and UnitTestComputeGraphTranspose().
{
   int32 size = graph.size();
   graph_transpose->clear();
   graph_transpose->resize(size);
   for (int32 n = 0; n < size; n++) {
     const std::vector<int32> &nodes = graph[n];
     std::vector<int32>::const_iterator iter = nodes.begin(), end = nodes.end();
     for (; iter != end; ++iter) {
       int32 dest = *iter;
       (*graph_transpose)[dest].push_back(n);
     }
   }
 }
void ComputeMatrixAccesses (const Nnet & nnet, const NnetComputation & computation, const ComputationVariables & variables, const std::vector< CommandAttributes > & command_attributes, std::vector< MatrixAccesses > * matrix_accesses)
This function organizes information in the CommandAttributes in a way that is convenient to access per matrix.
See struct MatrixAccesses for the output format; the output "matrix_accesses" is indexed by the matrix index (the same index as computation.matrices).
Definition at line 436 of file nnet-analyze.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::command_type, NnetComputation::commands, NnetComputation::input_output_info, Nnet::IsInputNode(), Nnet::IsOutputNode(), kaldi::IsSortedAndUniq(), KALDI_ASSERT, KALDI_ERR, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed, kAllocMatrixUndefined, kAllocMatrixZeroed, kDeallocMatrix, kReadAccess, kReadWriteAccess, kWriteAccess, NnetComputation::matrices, CommandAttributes::matrices_read, CommandAttributes::matrices_written, and kaldi::SortAndUniq().
Referenced by Analyzer::Init(), and MoveSizingCommands().
{
   int32 num_matrices = computation.matrices.size(),
       num_commands = command_attributes.size();
   matrix_accesses->clear();
   matrix_accesses->resize(num_matrices);
   for (int32 c = 0; c < num_commands; c++) {
     const CommandAttributes &attr = command_attributes[c];
     KALDI_ASSERT(IsSortedAndUniq(attr.matrices_read));
     KALDI_ASSERT(IsSortedAndUniq(attr.matrices_written));
     std::vector<int32> all_matrices;
     all_matrices.reserve(attr.matrices_read.size() +
                           attr.matrices_written.size());
     all_matrices.insert(all_matrices.end(), attr.matrices_read.begin(),
                          attr.matrices_read.end());
     all_matrices.insert(all_matrices.end(), attr.matrices_written.begin(),
                          attr.matrices_written.end());
     SortAndUniq(&all_matrices);
     std::vector<int32>::const_iterator iter = all_matrices.begin(),
         end = all_matrices.end();
     for (; iter != end; ++iter) {
       int32 matrix_index = *iter;
       bool is_read = std::binary_search(attr.matrices_read.begin(),
                                         attr.matrices_read.end(),
                                         matrix_index),
           is_written = (!is_read ? true :
                         std::binary_search(attr.matrices_written.begin(),
                                            attr.matrices_written.end(),
                                            matrix_index));
       if (is_read && is_written) {
         (*matrix_accesses)[matrix_index].accesses.push_back(
             Access(c, kReadWriteAccess));
       } else if (is_read) {
         (*matrix_accesses)[matrix_index].accesses.push_back(
             Access(c, kReadAccess));
       } else {
         (*matrix_accesses)[matrix_index].accesses.push_back(
             Access(c, kWriteAccess));
       }
     }
     // Now set up allocate_command and deallocate_command.
     const NnetComputation::Command &command = computation.commands[c];
     int32 matrix_index = command.arg1,
         matrix_index2 = command.arg2;
     switch (command.command_type) {
       case kAllocMatrixZeroed:
       case kAllocMatrixUndefined:
         if ((*matrix_accesses)[matrix_index].allocate_command != -1)
           KALDI_ERR << "Matrix " << matrix_index << " initialized twice.";
         (*matrix_accesses)[matrix_index].allocate_command = c;
         break;
       case kAllocMatrixFromOther:
       case kAllocMatrixFromOtherZeroed:
         if ((*matrix_accesses)[matrix_index].allocate_command != -1)
           KALDI_ERR << "Matrix " << matrix_index << " initialized twice.";
         (*matrix_accesses)[matrix_index].allocate_command = c;
         if ((*matrix_accesses)[matrix_index2].deallocate_command != -1)
           KALDI_ERR << "Matrix " << matrix_index << " destroyed twice.";
         (*matrix_accesses)[matrix_index2].deallocate_command = c;
         break;
       case kDeallocMatrix:
         if ((*matrix_accesses)[matrix_index].deallocate_command != -1)
           KALDI_ERR << "Matrix " << matrix_index << " destroyed twice.";
         (*matrix_accesses)[matrix_index].deallocate_command = c;
         break;
       default:
         ;
     }
   }
   // now set up the is_input and is_output fields.
   unordered_map<int32, std::pair<int32, int32> >::const_iterator
       iter = computation.input_output_info.begin(),
       end = computation.input_output_info.end();
   for (; iter != end; ++iter) {
     int32 node_index = iter->first,
         value_matrix_index = iter->second.first,
         deriv_matrix_index = iter->second.second;
     KALDI_ASSERT(value_matrix_index > 0 && value_matrix_index < num_matrices);
     if (nnet.IsInputNode(node_index)) {
       // the assert checks for repeats
       KALDI_ASSERT(!(*matrix_accesses)[value_matrix_index].is_input);
       (*matrix_accesses)[value_matrix_index].is_input = true;
       if (deriv_matrix_index != 0) {
         // the derivatives, if requested, would be outputs of the computation,
         // even though the node is an input node.
         KALDI_ASSERT(!(*matrix_accesses)[deriv_matrix_index].is_output);
         (*matrix_accesses)[deriv_matrix_index].is_output = true;
       }
     } else {
       KALDI_ASSERT(nnet.IsOutputNode(node_index));
       // the assert checks for repeats
       KALDI_ASSERT(!(*matrix_accesses)[value_matrix_index].is_output);
       (*matrix_accesses)[value_matrix_index].is_output = true;
       if (deriv_matrix_index != 0) {
         // the derivatives, if provided, would be inputs to the computation,
         // even though the node is an output node.
         KALDI_ASSERT(!(*matrix_accesses)[deriv_matrix_index].is_input);
         (*matrix_accesses)[deriv_matrix_index].is_input = true;
       }
     }
   }
 }
void ComputeMatrixToSubmatrix (const NnetComputation & computation, std::vector< std::vector< int32 > > * mat_to_submat)
This function computes a vector 'mat_to_submat', indexed by matrix index, such that (*mat_to_submat)[m] is a list of all the submatrix indexes that refer to matrix m.
Note, (*mat_to_submat)[0] will be the empty vector.
Definition at line 985 of file nnet-analyze.cc.
References KALDI_ASSERT, NnetComputation::matrices, and NnetComputation::submatrices.
Referenced by VariableMergingOptimizer::VariableMergingOptimizer().
{
   int32 num_matrices = computation.matrices.size(),
       num_submatrices = computation.submatrices.size();
   mat_to_submat->clear();
   mat_to_submat->resize(num_matrices);
   for (int32 submatrix_index = 1;
        submatrix_index < num_submatrices;
        submatrix_index++) {
     int32 matrix_index = computation.submatrices[submatrix_index].matrix_index;
     KALDI_ASSERT(matrix_index > 0 && matrix_index < num_matrices);
     (*mat_to_submat)[matrix_index].push_back(submatrix_index);
   }
 }
void kaldi::nnet3::ComputeMinAndMaxTimes (const std::vector< Index > & indexes, int32 * min_t, int32 * max_t)
Definition at line 31 of file nnet-derivative-test.cc.
References KALDI_ASSERT, and rnnlm::n.
Referenced by SetDerivTimesOptions().
{
   KALDI_ASSERT(!indexes.empty());
   *min_t = indexes[0].t;
   *max_t = *min_t;
   for (int32 n = 1; n < static_cast<int32>(indexes.size()); n++) {
     *min_t = std::min(*min_t, indexes[n].t);
     *max_t = std::max(*max_t, indexes[n].t);
   }
 }
void ComputeNnetComputationEpochs (const Nnet & nnet, std::vector< int32 > * node_to_epoch)
This function computes the order in which we need to compute each node in the graph, where each node-index n maps to an order-index t = 0, 1, ...
that says when we should compute it. Nodes that are part of a strongly connected component (SCC) will all be computed at the same time, but any two nodes that are not part of an SCC will have different order-index, and these order-indexes will be such that a node computed at a larger order-index may depend on a node computed at a smaller order-index, but not vice versa.
Internally it calls NnetToDirectedGraph, FindSccs, MakeSccGraph and ComputeTopSortOrder.
Definition at line 265 of file nnet-graph.cc.
References ComputeGraphTranspose(), ComputeTopSortOrder(), FindSccs(), kaldi::GetVerboseLevel(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_VLOG, MakeSccGraph(), NnetToDirectedGraph(), and PrintGraphToString().
Referenced by kaldi::nnet3::computation_graph::ComputeEpochInfo().
{
   KALDI_ASSERT(node_to_epoch != NULL);
   std::vector<std::vector<int32> > graph;
   NnetToDirectedGraph(nnet, &graph);
   KALDI_VLOG(6) << "graph is: " << PrintGraphToString(graph);
   std::vector<std::vector<int32> > sccs;
   FindSccs(graph, &sccs);
   std::vector<std::vector<int32> > scc_graph;
   MakeSccGraph(graph, sccs, &scc_graph);
   KALDI_VLOG(6) << "scc graph is: " << PrintGraphToString(scc_graph);
   std::vector<std::vector<int32> > scc_graph_transpose;
   // compute transpose because we actually want the reverse of the topological
   // order so inputs come first and then outputs.
   ComputeGraphTranspose(scc_graph, &scc_graph_transpose);
   std::vector<int32> scc_node_to_epoch;
   ComputeTopSortOrder(scc_graph, &scc_node_to_epoch);
   if (GetVerboseLevel() >= 6) {
     std::ostringstream os;
     for (int32 i = 0; i < scc_node_to_epoch.size(); i++)
       os << scc_node_to_epoch[i] << ", ";
     KALDI_VLOG(6) << "scc_node_to_epoch is: " << os.str();
   }
   node_to_epoch->clear();
   node_to_epoch->resize(graph.size());
   for (int32 i = 0; i < sccs.size(); ++i) {
     for (int32 j = 0; j < sccs[i].size(); ++j) {
       int32 node = sccs[i][j];
       KALDI_ASSERT(node >= 0 && node < graph.size());
       (*node_to_epoch)[node] = scc_node_to_epoch[i];
     }
   }
 }
void ComputeObjectiveFunction (const GeneralMatrix & supervision, ObjectiveType objective_type, const std::string & output_name, bool supply_deriv, NnetComputer * computer, BaseFloat * tot_weight, BaseFloat * tot_objf)
This function computes the objective function, and if supply_deriv = true, supplies its derivative to the NnetComputation object.
See also the function ComputeAccuracy(), declared in nnet-diagnostics.h.
Parameters
[in] supervision A GeneralMatrix, typically derived from a NnetExample, containing the supervision posteriors or features.
[in] objective_type The objective function type: kLinear = output * supervision, or kQuadratic = -0.5 * (output - supervision)^2. kLinear is used for softmax objectives; the network contains a LogSoftmax layer which correctly normalizes its output.
[in] output_name The name of the output node (e.g. "output"), used to look up the output in the NnetComputer object.
[in] supply_deriv If this is true, this function will compute the derivative of the objective function and supply it to the network using the function NnetComputer::AcceptOutputDeriv
[in,out] computer The NnetComputer object, from which we get the output using GetOutput and to which we may supply the derivatives using AcceptOutputDeriv.
[out] tot_weight The total weight of the training examples. In the kLinear case, this is the sum of the supervision matrix; in the kQuadratic case, it is the number of rows of the supervision matrix. In order to make it possible to weight samples with quadratic objective functions, we may at some point make it possible for the supervision matrix to have an extra column containing weights. At the moment, this is not supported.
[out] tot_objf The total objective function; divide this by the tot_weight to get the normalized objective function.
Definition at line 167 of file nnet-training.cc.
References NnetComputer::AcceptOutputDeriv(), CuMatrixBase< Real >::CopyFromGeneralMat(), CuSparseMatrix< Real >::CopyToMat(), GeneralMatrix::GetFullMatrix(), GeneralMatrix::GetMatrix(), NnetComputer::GetOutput(), GeneralMatrix::GetSparseMatrix(), KALDI_ERR, kaldi::kCompressedMatrix, kaldi::kFullMatrix, kLinear, kQuadratic, kaldi::kSparseMatrix, kaldi::kTrans, kaldi::kUndefined, CuMatrixBase< Real >::NumCols(), GeneralMatrix::NumCols(), CuMatrixBase< Real >::NumRows(), GeneralMatrix::NumRows(), CuSparseMatrix< Real >::Sum(), CuMatrixBase< Real >::Sum(), CuMatrix< Real >::Swap(), kaldi::TraceMatMat(), kaldi::TraceMatSmat(), and GeneralMatrix::Type().
Referenced by NnetComputeProb::ProcessOutputs(), and NnetTrainer::ProcessOutputs().
{
   const CuMatrixBase<BaseFloat> &output = computer->GetOutput(output_name);
   if (output.NumCols() != supervision.NumCols())
     KALDI_ERR << "Nnet versus example output dimension (num-classes) "
               << "mismatch for '" << output_name << "': " << output.NumCols()
               << " (nnet) vs. " << supervision.NumCols() << " (egs)\n";
   switch (objective_type) {
     case kLinear: {
       // objective is x * y.
       switch (supervision.Type()) {
         case kSparseMatrix: {
           const SparseMatrix<BaseFloat> &post = supervision.GetSparseMatrix();
           CuSparseMatrix<BaseFloat> cu_post(post);
           // The cross-entropy objective is computed by a simple dot product,
           // because after the LogSoftmaxLayer, the output is already in the form
           // of log-likelihoods that are normalized to sum to one.
           *tot_weight = cu_post.Sum();
           *tot_objf = TraceMatSmat(output, cu_post, kTrans);
           if (supply_deriv) {
             CuMatrix<BaseFloat> output_deriv(output.NumRows(), output.NumCols(),
                                              kUndefined);
             cu_post.CopyToMat(&output_deriv);
             computer->AcceptOutputDeriv(output_name, &output_deriv);
           }
           break;
         }
         case kFullMatrix: {
           // there is a redundant matrix copy in here if we're not using a GPU
           // but we don't anticipate this code branch being used in many cases.
           CuMatrix<BaseFloat> cu_post(supervision.GetFullMatrix());
           *tot_weight = cu_post.Sum();
           *tot_objf = TraceMatMat(output, cu_post, kTrans);
           if (supply_deriv)
             computer->AcceptOutputDeriv(output_name, &cu_post);
           break;
         }
         case kCompressedMatrix: {
           Matrix<BaseFloat> post;
           supervision.GetMatrix(&post);
           CuMatrix<BaseFloat> cu_post;
           cu_post.Swap(&post);
           *tot_weight = cu_post.Sum();
           *tot_objf = TraceMatMat(output, cu_post, kTrans);
           if (supply_deriv)
             computer->AcceptOutputDeriv(output_name, &cu_post);
           break;
         }
       }
       break;
     }
     case kQuadratic: {
       // objective is -0.5 (x - y)^2
       CuMatrix<BaseFloat> diff(supervision.NumRows(),
                                supervision.NumCols(),
                                kUndefined);
       diff.CopyFromGeneralMat(supervision);
       diff.AddMat(-1.0, output);
       *tot_weight = diff.NumRows();
       *tot_objf = -0.5 * TraceMatMat(diff, diff, kTrans);
       if (supply_deriv)
         computer->AcceptOutputDeriv(output_name, &diff);
       break;
     }
     default:
       KALDI_ERR << "Objective function type " << objective_type
                 << " not handled.";
   }
 }
void ComputeSimpleNnetContext (const Nnet & nnet, int32 * left_context, int32 * right_context)
ComputeNnetContext computes the left-context and right-context of a nnet.
The nnet must satisfy IsSimpleNnet(nnet).
It does this by constructing a ComputationRequest with a certain number of inputs available, outputs can be computed.. It does the same after shifting the time index of the output to all values 0, 1, ... n-1, where n is the output of nnet.Modulus(). Then it returns the largest left context and the largest right context that it infers from any of these computation requests.
Definition at line 129 of file nnet-utils.cc.
References ComputeSimpleNnetContextForShift(), IsSimpleNnet(), KALDI_ASSERT, and Nnet::Modulus().
Referenced by ComputeExampleComputationRequestSimple(), NnetDecodableBase::NnetDecodableBase(), NnetInfo(), AmNnetSimple::SetContext(), and UnitTestNnetContext().
{
   KALDI_ASSERT(IsSimpleNnet(nnet));
   int32 modulus = nnet.Modulus();
   // modulus >= 1 is a number such that the network ought to be
   // invariant to time shifts (of both the input and output) that
   // are a multiple of this number.  We need to test all shifts modulo
   // this number in case the left and right context vary at all within
   // this range.
   std::vector<int32> left_contexts(modulus + 1);
   std::vector<int32> right_contexts(modulus + 1);
   // This will crash if the total context (left + right) is greater
   // than window_size.
   int32 window_size = 100;
   // by going "<= modulus" instead of "< modulus" we do one more computation
   // than we really need; it becomes a sanity check.
   for (int32 input_start = 0; input_start <= modulus; input_start++)
     ComputeSimpleNnetContextForShift(nnet, input_start, window_size,
                                      &(left_contexts[input_start]),
                                      &(right_contexts[input_start]));
   KALDI_ASSERT(left_contexts[0] == left_contexts[modulus] &&
                "nnet does not have the properties we expect.");
   KALDI_ASSERT(right_contexts[0] == right_contexts[modulus] &&
                "nnet does not have the properties we expect.");
   *left_context =
       *std::max_element(left_contexts.begin(), left_contexts.end());
   *right_context =
       *std::max_element(right_contexts.begin(), right_contexts.end());
 }
static void kaldi::nnet3::ComputeSimpleNnetContextForShift (const Nnet & nnet, int32 input_start, int32 window_size, int32 * left_context, int32 * right_context) static
Definition at line 82 of file nnet-utils.cc.
References EvaluateComputationRequest(), Nnet::GetNodeIndex(), IoSpecification::indexes, ComputationRequest::inputs, KALDI_ASSERT, KALDI_ERR, rnnlm::n, IoSpecification::name, and ComputationRequest::outputs.
Referenced by ComputeSimpleNnetContext().
{
   int32 input_end = input_start + window_size;
   IoSpecification input;
   input.name = "input";
   IoSpecification output;
   output.name = "output";
   IoSpecification ivector;  // we might or might not use this.
   ivector.name = "ivector";
   int32 n = rand() % 10;
   // in the IoSpecification for now we we will request all the same indexes at
   // output that we requested at input.
   for (int32 t = input_start; t < input_end; t++) {
     input.indexes.push_back(Index(n, t));
     output.indexes.push_back(Index(n, t));
   }
   // the assumption here is that the network just requires the ivector at time
   // t=0.
   ivector.indexes.push_back(Index(n, 0));
   ComputationRequest request;
   request.inputs.push_back(input);
   request.outputs.push_back(output);
   if (nnet.GetNodeIndex("ivector") != -1)
     request.inputs.push_back(ivector);
   std::vector<std::vector<bool> > computable;
   EvaluateComputationRequest(nnet, request, &computable);
   KALDI_ASSERT(computable.size() == 1);
   std::vector<bool> &output_ok = computable[0];
   std::vector<bool>::iterator iter =
       std::find(output_ok.begin(), output_ok.end(), true);
   int32 first_ok = iter - output_ok.begin();
   int32 first_not_ok = std::find(iter, output_ok.end(), false) -
       output_ok.begin();
   if (first_ok == window_size || first_not_ok <= first_ok)
     KALDI_ERR << "No outputs were computable (perhaps not a simple nnet?)";
   *left_context = first_ok;
   *right_context = window_size - first_not_ok;
 }
void kaldi::nnet3::ComputeSubmatIndexHistogram (const std::vector< std::vector< std::pair< int32, int32 > > > sorted_submat_lists, unordered_map< int32, std::vector< int32 > > * submat_histogram)
Definition at line 113 of file nnet-compile-utils.cc.
References rnnlm::i, rnnlm::j, and KALDI_ASSERT.
Referenced by SplitLocations().
       {
   KALDI_ASSERT(sorted_submat_lists.size() > 0);
   // computing the submat_histogram
   // counting the occurrences of each element in the current submat_list;
   // each new occurrence of the same element, in this list, is counted
   // as a seperate symbol for frequency counts
   for (int32 i = 0; i < sorted_submat_lists.size(); i++) {
     int j = 0;
     unordered_map<int32, std::vector<int32> >::iterator histogram_iterator
         = submat_histogram->end();
     int32 repetition_count = 0;
     while (j < sorted_submat_lists[i].size()) {
       if ((histogram_iterator == submat_histogram->end()) ||
           (histogram_iterator->first != sorted_submat_lists[i][j].first)) {
         histogram_iterator =
             submat_histogram->find(sorted_submat_lists[i][j].first);
         repetition_count = 0;
         // if a histogram entry was not found for this submat_index, add one
         if (histogram_iterator == submat_histogram->end()) {
           (*submat_histogram)[sorted_submat_lists[i][j].first];
           histogram_iterator = submat_histogram->find(
               sorted_submat_lists[i][j].first);
         }
       }
       if (repetition_count >= (histogram_iterator->second).size()) {
         // this is the first time the submat_index repeated this many times
         // so add an entry for this in the count vector
         (histogram_iterator->second).push_back(1);
       } else {
         (histogram_iterator->second)[repetition_count]++;
       }
       repetition_count++;
       j++;
     }
   }
 }
void ComputeTopSortOrder (const std::vector< std::vector< int32 > > & graph, std::vector< int32 > * node_to_order)
Given an acyclic graph (where each std::vector<int32> is a list of destination-nodes of arcs coming from the current node), compute a topological ordering of the graph nodes.
The output format is that node_to_order[n] contains an integer t = 0, 1, ... which is the order of node n in a topological sorting. node_to_order should contain some permutation of the numbers 0 ... graph.size() - 1. This function should crash if the graph contains cycles.
Definition at line 223 of file nnet-graph.cc.
References ComputeTopSortOrderRecursive(), rnnlm::i, and KALDI_ASSERT.
Referenced by ComputeNnetComputationEpochs(), and UnitTestComputeTopSortOrder().
{
   // Internally we use DFS, but we only put the node to <node_to_order> when all
   // its parents have been visited.
   KALDI_ASSERT(node_to_order != NULL);
   node_to_order->resize(graph.size());
   std::vector<bool> cycle_detector(graph.size(), false);
   std::vector<bool> is_visited(graph.size(), false);
   std::vector<int32> reversed_orders;
   for(int32 i = 0; i < graph.size(); ++i) {
     if (!is_visited[i]) {
       ComputeTopSortOrderRecursive(i, graph, &cycle_detector,
                                    &is_visited, &reversed_orders);
     }
   }
   KALDI_ASSERT(node_to_order->size() == reversed_orders.size());
   for (int32 i = 0; i < reversed_orders.size(); ++i) {
     KALDI_ASSERT(reversed_orders[i] >= 0 && reversed_orders[i] < graph.size());
     (*node_to_order)[reversed_orders[i]] = graph.size() - i - 1;
   }
 }
void kaldi::nnet3::ComputeTopSortOrderRecursive (int32 node, const std::vector< std::vector< int32 > > & graph, std::vector< bool > * cycle_detector, std::vector< bool > * is_visited, std::vector< int32 > * reversed_orders)
Definition at line 196 of file nnet-graph.cc.
References rnnlm::i, KALDI_ASSERT, and KALDI_ERR.
Referenced by ComputeTopSortOrder().
{
   KALDI_ASSERT(node >= 0 && node < graph.size());
   KALDI_ASSERT(cycle_detector != NULL);
   KALDI_ASSERT(is_visited != NULL);
   KALDI_ASSERT(reversed_orders != NULL);
   if ((*cycle_detector)[node]) {
     KALDI_ERR << "Cycle detected when computing the topological sorting order";
   }
   if (!(*is_visited)[node]) {
     (*cycle_detector)[node] = true;
     for (int32 i = 0; i < graph[node].size(); ++i) {
       ComputeTopSortOrderRecursive(graph[node][i], graph,
                                    cycle_detector, is_visited, reversed_orders);
     }
     (*cycle_detector)[node] = false;
     (*is_visited)[node] = true;
     // At this point we have added all the children to <reversed_orders>, so we
     // can add the current now.
     reversed_orders->push_back(node);
   }
 }
void ComputeVariableAccesses (const ComputationVariables & variables, const std::vector< CommandAttributes > & command_attributes, std::vector< std::vector< Access > > * variable_accesses)
After the command-level attributes have been computed, this function organizes them per variable (see class ComputationVariables for how a variable is defined; it is part of a matrix).
Parameters
[in] variables The definition of variables for this computation
[in] command_attributes A vector of attributes, one per command, as obtained from ComputeCommandAttributes().
[out] variable_accesses The output will have a size equal to the number of variables, and each element will be a vector of accesses, sorted by command index; each command will only be listed once in this vector.
Definition at line 390 of file nnet-analyze.cc.
References kaldi::IsSortedAndUniq(), KALDI_ASSERT, kReadAccess, kReadWriteAccess, kWriteAccess, ComputationVariables::NumVariables(), kaldi::SortAndUniq(), CommandAttributes::variables_read, and CommandAttributes::variables_written.
Referenced by Analyzer::Init(), and MoveSizingCommands().
{
   int32 num_variables = variables.NumVariables(),
       num_commands = command_attributes.size();
   variable_accesses->clear();
   variable_accesses->resize(num_variables);
   for (int32 c = 0; c < num_commands; c++) {
     const CommandAttributes &attr = command_attributes[c];
     KALDI_ASSERT(IsSortedAndUniq(attr.variables_read));
     KALDI_ASSERT(IsSortedAndUniq(attr.variables_written));
     std::vector<int32> all_variables;
     all_variables.reserve(attr.variables_read.size() +
                           attr.variables_written.size());
     all_variables.insert(all_variables.end(), attr.variables_read.begin(),
                          attr.variables_read.end());
     all_variables.insert(all_variables.end(), attr.variables_written.begin(),
                          attr.variables_written.end());
     SortAndUniq(&all_variables);
     std::vector<int32>::const_iterator iter = all_variables.begin(),
         end = all_variables.end();
     for (; iter != end; ++iter) {
       int32 variable_index = *iter;
       bool is_read = std::binary_search(attr.variables_read.begin(),
                                         attr.variables_read.end(),
                                         variable_index),
           is_written = (!is_read ? true :
                         std::binary_search(attr.variables_written.begin(),
                                            attr.variables_written.end(),
                                            variable_index));
       if (is_read && is_written) {
         (*variable_accesses)[variable_index].push_back(
             Access(c, kReadWriteAccess));
       } else if (is_read) {
         (*variable_accesses)[variable_index].push_back(
             Access(c, kReadAccess));
       } else {
         (*variable_accesses)[variable_index].push_back(
             Access(c, kWriteAccess));
       }
     }
   }
 }
void ConsolidateModelUpdate (const Nnet & nnet, const ComputationRequest & request, NnetComputation * computation)
This consolidates the model-update parts of the backprop into larger operations (applicable mostly to recurrent setups)– internally it uses class ModelUpdateConsolidator.
Will fail if called a second time.
Definition at line 266 of file nnet-optimize.cc.
References ModelUpdateConsolidator::ConsolidateModelUpdate(), and ComputationRequest::need_model_derivative.
Referenced by Optimize().
{
   if (!request.need_model_derivative)
     return;   // An optimization; there would be nothing to do in this case.
   ModelUpdateConsolidator consolidator(nnet, computation);
   consolidator.ConsolidateModelUpdate();
 }
bool kaldi::nnet3::ContainsSingleExample (const NnetExample & eg, int32 * min_input_t, int32 * max_input_t, int32 * min_output_t, int32 * max_output_t)
Returns true if the "eg" contains just a single example, meaning that all the "n" values in the indexes are zero, and the example has NnetIo members named both "input" and "output".
Also computes the minimum and maximum "t" values in the "input" and "output" NnetIo members.
Definition at line 48 of file nnet3-copy-egs.cc.
References rnnlm::i, NnetIo::indexes, NnetExample::io, KALDI_ASSERT, KALDI_WARN, and NnetIo::name.
Referenced by SelectFromExample().
{
   bool done_input = false, done_output = false;
   int32 num_indexes = eg.io.size();
   for (int32 i = 0; i < num_indexes; i++) {
     const NnetIo &io = eg.io[i];
     std::vector<Index>::const_iterator iter = io.indexes.begin(),
                                         end = io.indexes.end();
     // Should not have an empty input/output type.
     KALDI_ASSERT(!io.indexes.empty());
     if (io.name == "input" || io.name == "output") {
       int32 min_t = iter->t, max_t = iter->t;
       for (; iter != end; ++iter) {
         int32 this_t = iter->t;
         min_t = std::min(min_t, this_t);
         max_t = std::max(max_t, this_t);
         if (iter->n != 0) {
           KALDI_WARN << "Example does not contain just a single example; "
                      << "too late to do frame selection or reduce context.";
           return false;
         }
       }
       if (io.name == "input") {
         done_input = true;
         *min_input_t = min_t;
         *max_input_t = max_t;
       } else {
         KALDI_ASSERT(io.name == "output");
         done_output = true;
         *min_output_t = min_t;
         *max_output_t = max_t;
       }
     } else {
       for (; iter != end; ++iter) {
         if (iter->n != 0) {
           KALDI_WARN << "Example does not contain just a single example; "
                      << "too late to do frame selection or reduce context.";
           return false;
         }
       }
     }
   }
   if (!done_input) {
     KALDI_WARN << "Example does not have any input named 'input'";
     return false;
   }
   if (!done_output) {
     KALDI_WARN << "Example does not have any output named 'output'";
     return false;
   }
   return true;
 }
void ConvertAdditionToAssignment (const Nnet & nnet, NnetComputation * computation)
This converts addition operations (things with Add in their names) to copy operations (things with Copy in their names).
This is both slightly more efficient,
Definition at line 276 of file nnet-optimize.cc.
References Analyzer::command_attributes, NnetComputation::Command::command_type, NnetComputation::commands, ComputationAnalysis::FirstAccess(), Analyzer::Init(), kAddRows, kAddRowsMulti, kAddToRowsMulti, KALDI_ASSERT, KALDI_ERR, kAllocMatrixFromOther, kAllocMatrixUndefined, kCopyRows, kCopyRowsMulti, kCopyToRowsMulti, kMatrixAdd, and kMatrixCopy.
Referenced by Optimize().
{
   Analyzer analyzer;
   analyzer.Init(nnet, *computation);
   ComputationAnalysis analysis(*computation, analyzer);
   int32 num_commands = computation->commands.size();
   for (int32 command = 0; command < num_commands; command++) {
     NnetComputation::Command &c = computation->commands[command];
     switch (c.command_type) {
       case kAllocMatrixUndefined: case kAllocMatrixFromOther:
         KALDI_ERR << "Cannot call ConvertAdditionToAssignment after "
                   << "allowing undefined initialization.";
       case kMatrixAdd: case kAddRows: case kAddRowsMulti:
       case kAddToRowsMulti: {
         const std::vector<int32> &submatrices_written =
             analyzer.command_attributes[command].submatrices_written;
         KALDI_ASSERT(!submatrices_written.empty());
         std::vector<int32>::const_iterator iter = submatrices_written.begin(),
             end = submatrices_written.end();
         bool can_convert = true;
         for (; iter != end; ++iter) {
           int32 submatrix_written = *iter;
           int32 first_access_command = analysis.FirstAccess(submatrix_written);
           // first_access_command is first non-initialization command that
           // accesses this submatrix.  It can be assumed to be a write command,
           // since it makes no sense to read a variable before it's written to.
           // If it's before this command then we need to add rather than copy,
           // we can't do the conversion to a copy command.
           if (first_access_command != command) {
             can_convert = false;
             break;
           }
         }
         if (can_convert) {  // convert to a copy command.
           switch (c.command_type) {
             case kMatrixAdd: c.command_type = kMatrixCopy; break;
             case kAddRows: c.command_type = kCopyRows; break;
             case kAddRowsMulti: c.command_type = kCopyRowsMulti; break;
             case kAddToRowsMulti: c.command_type = kCopyToRowsMulti; break;
             default: KALDI_ERR << "Unexpected command type.";
           }
         }
         break;
       }
       default:
         break;
     }
   }
 }
bool ConvertToIndexes (const std::vector< std::pair< int32, int32 > > & location_vector, int32 * first_value, std::vector< int32 > * second_values)
If it is the case for some i >= 0 that all the .first elements of "location_vector" are either i or -1, then output i to first_value and the .second elements into "second_values", and return true.
Otherwise return false and the outputs are don't-cares.
Definition at line 377 of file nnet-compile-utils.cc.
Referenced by Compiler::DoForwardComputationFromSubmatLocations(), SplitLocationsBackward(), UnitTestSplitLocations(), and UnitTestSplitLocationsBackward().
{
   *first_value = -1;
   second_values->clear();
   second_values->reserve(location_vector.size());
   std::vector<std::pair<int32, int32> >::const_iterator iter;
   for (iter = location_vector.begin(); iter < location_vector.end(); ++iter)  {
     if (iter->first != -1) {
       if (*first_value == -1)
         *first_value = iter->first;
       if (iter->first != *first_value)
         return false;
       second_values->push_back(iter->second);
     } else  {
       second_values->push_back(-1);
     }
   }
   return true;
 }
bool DescriptorTokenize (const std::string & input, std::vector< std::string > * tokens)
This function tokenizes input when parsing Descriptor configuration values.
A token in this context is not the same as a generic Kaldi token, e.g. as defined in IsToken() in util/text_utils.h, which just means a non-empty whitespace-free string. Here a token is more like a programming-language token, and currently the following are allowed as tokens: "(" ")" ","
A nonempty string beginning with A-Za-z_, and containing only -_A-Za-z0-9.
An integer, optionally beginning with - or + and then a nonempty sequence of 0-9.
This function should return false and print an informative error with local context if it can't tokenize the input.
Definition at line 355 of file nnet-parse.cc.
References kaldi::ConvertStringToInteger(), ErrorContext(), IsValidName(), KALDI_ASSERT, and KALDI_WARN.
Referenced by NormalizeTextDescriptor(), Nnet::ProcessComponentNodeConfigLine(), Nnet::ProcessOutputNodeConfigLine(), UnitTestDescriptorIo(), UnitTestDescriptorTokenize(), and UnitTestGeneralDescriptor().
{
   KALDI_ASSERT(tokens != NULL);
   size_t start = input.find_first_not_of(" \t"), size = input.size();
   tokens->clear();
   while (start < size) {
     KALDI_ASSERT(!isspace(input[start]));
     if (input[start] == '(' || input[start] == ')' || input[start] == ',') {
       tokens->push_back(std::string(input, start, 1));
       start = input.find_first_not_of(" \t", start + 1);
     } else {
       size_t found = input.find_first_of(" \t(),", start);
       KALDI_ASSERT(found != start);
       if (found == std::string::npos) {
         std::string str(input, start, input.size() - start);
         int32 tmp;
         if (!IsValidName(str) && !ConvertStringToInteger(str, &tmp)) {
           KALDI_WARN << "Could not parse line " << ErrorContext(std::string(input, start));
           return false;
         }
         tokens->push_back(str);
         break;
       } else {
         if (input[found] == '(' || input[found] == ')' || input[found] == ',') {
           std::string str(input, start, found - start);
           int32 tmp;
           if (!IsValidName(str) && !ConvertStringToInteger(str, &tmp)) {
             KALDI_WARN << "Could not parse line " << ErrorContext(std::string(input, start));
             return false;
           }
           tokens->push_back(str);
           start = found;
         } else {
           std::string str(input, start, found - start);
           int32 tmp;
           if (!IsValidName(str) && !ConvertStringToInteger(str, &tmp)) {
             KALDI_WARN << "Could not parse line " << ErrorContext(std::string(input, start));
             return false;
           }
           tokens->push_back(str);
           start = input.find_first_not_of(" \t", found);
         }
       }
     }
   }
   return true;
 }
BaseFloat DotProduct (const Nnet & nnet1, const Nnet & nnet2)
Returns dot product between two networks of the same structure (calls the DotProduct functions of the Updatable components and sums up the return values).
Definition at line 225 of file nnet-utils.cc.
References UpdatableComponent::DotProduct(), Nnet::GetComponent(), KALDI_ASSERT, kUpdatableComponent, Nnet::NumComponents(), and Component::Properties().
Referenced by NnetTrainer::Train(), and UnitTestNnetModelDerivatives().
{
   KALDI_ASSERT(nnet1.NumComponents() == nnet2.NumComponents());
   BaseFloat ans = 0.0;
   for (int32 c = 0; c < nnet1.NumComponents(); c++) {
     const Component *comp1 = nnet1.GetComponent(c),
                     *comp2 = nnet2.GetComponent(c);
     if (comp1->Properties() & kUpdatableComponent) {
       const UpdatableComponent
           *u_comp1 = dynamic_cast<const UpdatableComponent*>(comp1),
           *u_comp2 = dynamic_cast<const UpdatableComponent*>(comp2);
       KALDI_ASSERT(u_comp1 != NULL && u_comp2 != NULL);
       ans += u_comp1->DotProduct(*u_comp2);
     }
   }
   return ans;
 }
void EnsureContiguousProperty (const std::vector< int32 > & indexes, std::vector< std::vector< int32 > > * indexes_out)
This function takes a vector of indexes and splits it up into as separate vectors of the same size, as needed to ensure that the 'contiguous property' holds.
This is done via padding with -1's. An example will clarify this. Suppose the input is: [ -1 1 1 1 2 2 1 1 ] which lacks the contiguous property because 1's appear in 2 different places, it would split it up as [ -1 1 1 1 2 2 -1 -1 ] [ -1 -1 -1 -1 -1 -1 1 1 ] If 'indexes' is empty or only contains -1's, 'indexes_out' will be empty.
Definition at line 401 of file nnet-compile-utils.cc.
References rnnlm::i.
Referenced by SplitLocationsBackward(), and UnitTestEnsureContiguousProperty().
{
   indexes_out->clear();
   indexes_out->reserve(3);
   if (indexes.empty()) return;
   int32 max_value = *std::max_element(indexes.begin(), indexes.end());
   if (max_value == -1) return;
   std::vector<int32> num_segments_seen(max_value + 1, 0);
   int32 dim = indexes.size(), num_output_vectors = 0;
   for (int32 i = 0; i < dim;) {
     // note, we increment i within the loop.
     if (indexes[i] == -1) {
       i++;
       continue;
     }
     int32 value = indexes[i], start_index = i;
     for (; i < dim && indexes[i] == value; i++);
     int32 end_index = i;  // one past the end.
     // the input 'indexes' contains a sequence of possibly-repeated instances of
     // the value 'value', starting at index 'start_index', with 'end_index' as
     // one past the end.
     int32 this_num_segments_seen = num_segments_seen[value]++;
     if (this_num_segments_seen >= num_output_vectors) {  // we have nowhere to
                                                          // put it.
       indexes_out->resize(++num_output_vectors);
       indexes_out->back().resize(dim, -1);  // fill newly added vector with -1's.
     }
     std::vector<int32> &this_out_vec((*indexes_out)[this_num_segments_seen]);
     std::vector<int32>::iterator iter = this_out_vec.begin() + start_index,
         end = this_out_vec.begin() + end_index;
     // Fill the appropriate range of the output vector with 'value'
     for (; iter != end; ++iter) *iter = value;
   }
 }
std::string ErrorContext (std::istream & is)
Return a string used in error messages.
Here, "is" will be from an istringstream derived from a single line or part of a line. If "is" is at EOF or in error state, this should just say "end of line", else if the contents of "is" before EOF is <20 characters it should return it all, else it should return the first 20 characters followed by "...".
Definition at line 429 of file nnet-parse.cc.
Referenced by DescriptorTokenize().
{
   if (!is.good()) return "end of line";
   char buf[21];
   is.read(buf, 21);
   if (is) {
     return (std::string(buf, 20) + "...");
   }
   return std::string(buf, is.gcount());
 }
std::string ErrorContext (const std::string & str)
Definition at line 439 of file nnet-parse.cc.
{
   if (str.size() == 0) return "end of line";
   if (str.size() <= 20) return str;
   return std::string(str, 0, 20) + "...";
 }
void EvaluateComputationRequest (const Nnet & nnet, const ComputationRequest & request, std::vector< std::vector< bool > > * is_computable)
Given an nnet and a computation request, this function works out which requested outputs in the computation request are computable; it outputs this information as a vector "is_computable" indexed by the same indexes as request.outputs.
It does this by executing some of the early stages of compilation.
Definition at line 64 of file nnet-utils.cc.
References ComputationGraphBuilder::Compute(), ComputationGraphBuilder::GetComputableInfo(), Nnet::GetNodeNames(), kaldi::GetVerboseLevel(), KALDI_VLOG, and ComputationGraph::Print().
Referenced by ComputeSimpleNnetContextForShift().
{
   ComputationGraph graph;
   ComputationGraphBuilder builder(nnet, request, &graph);
   builder.Compute();
   builder.GetComputableInfo(is_computable);
   if (GetVerboseLevel() >= 2) {
     std::ostringstream graph_pretty;
     graph.Print(graph_pretty, nnet.GetNodeNames());
     KALDI_VLOG(2) << "Graph is " << graph_pretty.str();
   }
 }
bool ExampleApproxEqual (const NnetExample & eg1, const NnetExample & eg2, BaseFloat delta)
Returns true if the examples are approximately equal (only intended to be used in testing).
Definition at line 1207 of file nnet-test-utils.cc.
References kaldi::ApproxEqual(), NnetIo::features, GeneralMatrix::GetMatrix(), rnnlm::i, NnetIo::indexes, NnetExample::io, and NnetIo::name.
Referenced by UnitTestNnetExample().
{
   if (eg1.io.size() != eg2.io.size())
     return false;
   for (size_t i = 0; i < eg1.io.size(); i++) {
     NnetIo io1 = eg1.io[i], io2 = eg2.io[i];
     if (io1.name != io2.name || io1.indexes != io2.indexes)
       return false;
     Matrix<BaseFloat> feat1, feat2;
     io1.features.GetMatrix(&feat1);
     io2.features.GetMatrix(&feat2);
     if (!ApproxEqual(feat1, feat2, delta))
       return false;
   }
   return true;
 }
void ExpectOneOrTwoTokens (std::istream & is, bool binary, const std::string & token1, const std::string & token2)
This function is like ExpectToken but for two tokens, and it will either accept token1 and then token2, or just token2.
This is useful in Read functions where the first token may already have been consumed.
Definition at line 202 of file nnet-parse.cc.
References ExpectToken(), KALDI_ASSERT, KALDI_ERR, and kaldi::ReadToken().
Referenced by PnormComponent::Read(), DistributeComponent::Read(), ElementwiseProductComponent::Read(), NormalizeComponent::Read(), SumReduceComponent::Read(), NonlinearComponent::Read(), FixedAffineComponent::Read(), SumGroupComponent::Read(), FixedScaleComponent::Read(), FixedBiasComponent::Read(), ClipGradientComponent::Read(), PermuteComponent::Read(), and MaxpoolingComponent::Read().
{
   KALDI_ASSERT(token1 != token2);
   std::string temp;
   ReadToken(is, binary, &temp);
   if (temp == token1) {
     ExpectToken(is, binary, token2);
   } else {
     if (temp != token2) {
       KALDI_ERR << "Expecting token " << token1 << " or " << token2
                 << " but got " << temp;
     }
   }
 }
static void kaldi::nnet3::ExpectToken (const std::string & token, const std::string & what_we_are_parsing, const std::string ** next_token) static
Definition at line 45 of file nnet-descriptor.cc.
References KALDI_ERR, and ParsingContext().
Referenced by ExpectOneOrTwoTokens(), GeneralDescriptor::Parse(), GeneralDescriptor::ParseFailover(), GeneralDescriptor::ParseIfDefined(), GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), GeneralDescriptor::ParseRound(), AmNnetSimple::Read(), Index::Read(), PnormComponent::Read(), NnetIo::Read(), DistributeComponent::Read(), NnetExample::Read(), ElementwiseProductComponent::Read(), NormalizeComponent::Read(), Nnet::Read(), SumReduceComponent::Read(), AffineComponent::Read(), RepeatedAffineComponent::Read(), NonlinearComponent::Read(), BlockAffineComponent::Read(), NaturalGradientAffineComponent::Read(), FixedAffineComponent::Read(), FixedScaleComponent::Read(), FixedBiasComponent::Read(), ClipGradientComponent::Read(), PermuteComponent::Read(), PerElementScaleComponent::Read(), PerElementOffsetComponent::Read(), NaturalGradientPerElementScaleComponent::Read(), ConvolutionComponent::Read(), Convolutional1dComponent::Read(), MaxpoolingComponent::Read(), CompositeComponent::Read(), and ReadIndexVector().
{
   if (**next_token != token)
     KALDI_ERR << "Expected '" << token << "' while parsing "
               << what_we_are_parsing << ", got "
               << **next_token << ParsingContext(*next_token);
   else  // advance token pointer.
     (*next_token)++;
 }
void kaldi::nnet3::ExtractGivenPairsFromSubmatLists (std::vector< std::vector< std::pair< int32, int32 > >::iterator > & input_iterator_list, std::vector< std::vector< std::pair< int32, int32 > > > * sorted_submat_lists, std::vector< std::pair< int32, int32 > > * list_of_pairs)
Definition at line 203 of file nnet-compile-utils.cc.
References rnnlm::i.
Referenced by SplitLocationsUsingSubmatHistogram().
{
   list_of_pairs->reserve(sorted_submat_lists->size());
   for (int32 i = 0; i < input_iterator_list.size(); i++) {
     if (input_iterator_list[i] != (*sorted_submat_lists)[i].end()) {
       // there was an element with the submat_index in the current list
       list_of_pairs->push_back(*input_iterator_list[i]);
       (*sorted_submat_lists)[i].erase(input_iterator_list[i]);
     } else  {
       // insert a dummy element. Callers of this function expect the dummy
       // element to be (-1, -1)
       list_of_pairs->push_back(std::make_pair(-1, -1));
     }
   }
 }
static void kaldi::nnet3::ExtractLastPairFromSubmatLists (std::vector< std::vector< std::pair< int32, int32 > > > * sorted_submat_lists, std::vector< std::pair< int32, int32 > > * list_of_pairs) static
Definition at line 224 of file nnet-compile-utils.cc.
References rnnlm::i.
Referenced by SplitLocationsUsingSubmatHistogram().
{
   list_of_pairs->reserve(sorted_submat_lists->size());
   for (int32 i = 0; i < sorted_submat_lists->size(); i++) {
     if ((*sorted_submat_lists)[i].size() == 0)  {
       // the value of the dummy has to be (-1, -1) as down stream code has
       // expects -1 values for dummies
       list_of_pairs->push_back(std::make_pair(-1, -1));
       continue;
     }
     list_of_pairs->push_back((*sorted_submat_lists)[i].back());
     (*sorted_submat_lists)[i].pop_back();
   }
 }
void kaldi::nnet3::FilterExample (const NnetExample & eg, int32 min_input_t, int32 max_input_t, int32 min_output_t, int32 max_output_t, NnetExample * eg_out)
This function filters the indexes (and associated feature rows) in a NnetExample, removing any index/row in an NnetIo named "input" with t < min_input_t or t > max_input_t and any index/row in an NnetIo named "output" with t < min_output_t or t > max_output_t.
Will crash if filtering removes all Indexes of "input" or "output".
Definition at line 111 of file nnet3-copy-egs.cc.
References NnetIo::features, kaldi::FilterGeneralMatrixRows(), rnnlm::i, NnetIo::indexes, NnetExample::io, KALDI_ASSERT, KALDI_ERR, NnetIo::name, and GeneralMatrix::NumRows().
Referenced by SelectFromExample().
{
   eg_out->io.clear();
   eg_out->io.resize(eg.io.size());
   for (size_t i = 0; i < eg.io.size(); i++) {
     bool is_input_or_output;
     int32 min_t, max_t;
     const NnetIo &io_in = eg.io[i];
     NnetIo &io_out = eg_out->io[i];
     const std::string &name = io_in.name;
     io_out.name = name;
     if (name == "input") {
       min_t = min_input_t;
       max_t = max_input_t;
       is_input_or_output = true;
     } else if (name == "output") {
       min_t = min_output_t;
       max_t = max_output_t;
       is_input_or_output = true;
     } else {
       is_input_or_output = false;
     }
     if (!is_input_or_output) {  // Just copy everything.
       io_out.indexes = io_in.indexes;
       io_out.features = io_in.features;
     } else {
       const std::vector<Index> &indexes_in = io_in.indexes;
       std::vector<Index> &indexes_out = io_out.indexes;
       indexes_out.reserve(indexes_in.size());
       int32 num_indexes = indexes_in.size(), num_kept = 0;
       KALDI_ASSERT(io_in.features.NumRows() == num_indexes);
       std::vector<bool> keep(num_indexes, false);
       std::vector<Index>::const_iterator iter_in = indexes_in.begin(),
                                           end_in = indexes_in.end();
       std::vector<bool>::iterator iter_out = keep.begin();
       for (; iter_in != end_in; ++iter_in,++iter_out) {
         int32 t = iter_in->t;
         bool is_within_range = (t >= min_t && t <= max_t);
         *iter_out = is_within_range;
         if (is_within_range) {
           indexes_out.push_back(*iter_in);
           num_kept++;
         }
       }
       KALDI_ASSERT(iter_out == keep.end());
       if (num_kept == 0)
         KALDI_ERR << "FilterExample removed all indexes for '" << name << "'";
       FilterGeneralMatrixRows(io_in.features, keep,
                               &io_out.features);
       KALDI_ASSERT(io_out.features.NumRows() == num_kept &&
                    indexes_out.size() == static_cast<size_t>(num_kept));
     }
   }
 }
void FindSccs (const std::vector< std::vector< int32 > > & graph, std::vector< std::vector< int32 > > * sccs)
Given a directed graph (where each std::vector<int32> is a list of destination-nodes of arcs coming from the current node), partition it into strongly connected components (i.e.
within each SCC, all nodes are reachable from all other nodes).
Definition at line 156 of file nnet-graph.cc.
References FindSccsTarjan(), and KALDI_ASSERT.
Referenced by ComputeNnetComputationEpochs(), and UnitTestFindSccs().
{
   // Internally we call Tarjan's SCC algorithm, as it only requires one DFS. We
   // can change this to other methods later on if necessary.
   KALDI_ASSERT(sccs != NULL);
   FindSccsTarjan(graph, sccs);
 }
void kaldi::nnet3::FindSccsTarjan (const std::vector< std::vector< int32 > > & graph, std::vector< std::vector< int32 > > * sccs)
Definition at line 138 of file nnet-graph.cc.
References KALDI_ASSERT, rnnlm::n, and TarjanSccRecursive().
Referenced by FindSccs().
{
   KALDI_ASSERT(sccs != NULL);
   // Initialization.
   std::vector<TarjanNode> tarjan_nodes(graph.size());
   std::vector<int32> tarjan_stack;
   int32 global_index = 0;
   // Calls the recursive function.
   for (int32 n = 0; n < graph.size(); ++n) {
     if (tarjan_nodes[n].index == -1) {
       TarjanSccRecursive(n, graph,
                          &global_index, &tarjan_nodes, &tarjan_stack, sccs);
     }
   }
 }
void kaldi::nnet3::FindSubmatIndexInSubmatLists (int32 submat_index, std::vector< std::vector< std::pair< int32, int32 > > > * sorted_submat_lists, std::vector< std::vector< std::pair< int32, int32 > >::iterator > * output_iterator_list, int32 * max_remaining_submat_list_size)
Definition at line 167 of file nnet-compile-utils.cc.
References rnnlm::i.
Referenced by SplitLocationsUsingSubmatHistogram().
{
   output_iterator_list->reserve(sorted_submat_lists->size());
   *max_remaining_submat_list_size = 0;
   for (int32 i = 0; i < sorted_submat_lists->size(); i++)  {
     std::vector< std::pair<int32, int32> > & submat_list =
         (*sorted_submat_lists)[i];
     output_iterator_list->push_back(
         std::find_if(submat_list.begin(), submat_list.end(),
                      FirstElementIsEqualComparator(submat_index)));
     int32 remaining_submat_list_size = submat_list.size();
     if  (output_iterator_list->back() != submat_list.end())  {
       // since the submat_index is present in this submat_list
       // if submat_index was deleted from the list
       // the remaining submat_list's size is reduced by 1
       remaining_submat_list_size--;
     }
     *max_remaining_submat_list_size = remaining_submat_list_size
                                       > *max_remaining_submat_list_size ? remaining_submat_list_size :
                                       *max_remaining_submat_list_size;
   }
 }
void GenerateConfigSequence (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Generates a sequence of at least one config files, output as strings, where the first in the sequence is the initial nnet, and the remaining ones may do things like add layers.
Definition at line 717 of file nnet-test-utils.cc.
References NnetGenerationOptions::allow_context, NnetGenerationOptions::allow_nonlinearity, NnetGenerationOptions::allow_recursion, GenerateConfigSequenceCnn(), GenerateConfigSequenceCnn2d(), GenerateConfigSequenceDistribute(), GenerateConfigSequenceLstm(), GenerateConfigSequenceRnn(), GenerateConfigSequenceRnnClockwork(), GenerateConfigSequenceSimple(), GenerateConfigSequenceSimpleContext(), GenerateConfigSequenceSimplest(), KALDI_ERR, and kaldi::RandInt().
Referenced by UnitTestNnetAnalyze(), UnitTestNnetCompile(), UnitTestNnetCompute(), UnitTestNnetContext(), UnitTestNnetInputDerivatives(), UnitTestNnetIo(), UnitTestNnetModelDerivatives(), and UnitTestNnetOptimizeWithOptions().
{
 start:
   int32 network_type = RandInt(0, 9);
   switch(network_type) {
     case 0:
       GenerateConfigSequenceSimplest(opts, configs);
       break;
     case 1:
       if (!opts.allow_context)
         goto start;
       GenerateConfigSequenceSimpleContext(opts, configs);
       break;
     case 2:
       if (!opts.allow_context || !opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceSimple(opts, configs);
       break;
     case 3:
       if (!opts.allow_recursion || !opts.allow_context ||
           !opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceRnn(opts, configs);
       break;
     case 4:
       if (!opts.allow_recursion || !opts.allow_context ||
           !opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceRnnClockwork(opts, configs);
       break;
     case 5:
       if (!opts.allow_recursion || !opts.allow_context ||
           !opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceLstm(opts, configs);
       break;
     case 6:
       if (!opts.allow_recursion || !opts.allow_context ||
           !opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceLstm(opts, configs);
       break;
     case 7:
       if (!opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceCnn(opts, configs);
       break;
     case 8:
       if (!opts.allow_nonlinearity)
         goto start;
       GenerateConfigSequenceCnn2d(opts, configs);
       break;
     case 9:
       GenerateConfigSequenceDistribute(opts, configs);
       break;
     default:
       KALDI_ERR << "Error generating config sequence.";
   }
 }
void kaldi::nnet3::GenerateConfigSequenceCnn (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 612 of file nnet-test-utils.cc.
References kaldi::Rand().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   int32 pool_stride = 5 + Rand() % 10, pool_size = 2 + Rand() % 3,
         num_pools = 1 + Rand() % 10;
   int32 num_patches = num_pools * pool_size;
   int32 patch_step = 1 + Rand() % 4, patch_dim = 4 + Rand () % 5,
         patch_stride = (num_patches - 1) * patch_step + patch_dim;
   int32 num_splice = 5 + Rand() % 10, num_filters = pool_stride;
   int32 input_dim = patch_stride * num_splice,
         hidden_dim = num_patches * num_filters,
         output_dim = num_pools * pool_stride;
   os << "component name=conv type=Convolutional1dComponent input-dim="
      << input_dim << " output-dim=" << hidden_dim
      << " patch-dim=" << patch_dim << " patch-step=" << patch_step
      << " patch-stride=" << patch_stride << std::endl;
   os << "component name=maxpooling type=MaxpoolingComponent input-dim="
      << hidden_dim << " output-dim=" << output_dim
      << " pool-size=" << pool_size << " pool-stride=" << pool_stride
      << std::endl;
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component-node name=conv_node component=conv input=input\n";
   os << "component-node name=maxpooling_node component=maxpooling input=conv_node\n";
   os << "output-node name=output input=maxpooling_node\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceCnn2d (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 644 of file nnet-test-utils.cc.
References kaldi::Rand().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   int32 input_x_dim = 10 + Rand() % 20,
         input_y_dim = 10 + Rand() % 20,
         input_z_dim = 3 + Rand() % 10,
         filt_x_dim = 1 + Rand() % input_x_dim,
         filt_y_dim = 1 + Rand() % input_y_dim,
         num_filters = 10 + Rand() % 20,
         filt_x_step = (1 + Rand() % filt_x_dim),
         filt_y_step = (1 + Rand() % filt_y_dim);
   int32 remainder = (input_x_dim - filt_x_dim) % filt_x_step;
   // adjusting input_x_dim to ensure divisibility
   input_x_dim = input_x_dim - remainder;
   remainder = (input_y_dim - filt_y_dim) % filt_y_step;
   // adjusting input_x_dim to ensure divisibility
   input_y_dim = input_y_dim - remainder;
   int32 input_vectorization = Rand() % 2;
   std::string vectorization;
   if (input_vectorization == 0) {
     vectorization = "yzx";
   } else  {
     vectorization = "zyx";
   }
   os << "component name=conv type=ConvolutionComponent "
      << " input-x-dim=" << input_x_dim
      << " input-y-dim=" << input_y_dim
      << " input-z-dim=" << input_z_dim
      << " filt-x-dim=" << filt_x_dim
      << " filt-y-dim=" << filt_y_dim
      << " filt-x-step=" << filt_x_step
      << " filt-y-step=" << filt_y_step
      << " num-filters=" << num_filters
      << " input-vectorization-order=" << vectorization
      << std::endl;
   os << "input-node name=input dim=" << (input_x_dim * input_y_dim * input_z_dim) << std::endl;
   os << "component-node name=conv_node component=conv input=input\n";
   os << "output-node name=output input=conv_node\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceDistribute (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 692 of file nnet-test-utils.cc.
References rnnlm::i, NnetGenerationOptions::output_dim, and kaldi::RandInt().
Referenced by GenerateConfigSequence().
{
   int32 output_dim = (opts.output_dim > 0 ? opts.output_dim : 100);
   int32 x_expand = RandInt(1, 5), after_expand_dim = RandInt(10, 20),
       input_dim = x_expand * after_expand_dim;
   std::ostringstream os;
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component name=distribute type=DistributeComponent input-dim="
      << input_dim << " output-dim=" << after_expand_dim << std::endl;
   os << "component-node name=distribute component=distribute input=input\n";
   os << "component name=affine type=AffineComponent input-dim="
      << after_expand_dim << " output-dim=" << output_dim << std::endl;
   os << "component-node name=affine component=affine input=distribute\n";
   os << "output-node name=output input=Sum(";
   for (int32 i = 0; i < x_expand; i++) {
     if (i > 0) os << ", ";
     os << "ReplaceIndex(affine, x, " << i << ")";
   }
   os << ")\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceLstm (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 317 of file nnet-test-utils.cc.
References rnnlm::i, NnetGenerationOptions::output_dim, and kaldi::Rand().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   std::vector<int32> splice_context;
   for (int32 i = -5; i < 4; i++)
     if (Rand() % 3 == 0)
       splice_context.push_back(i);
   if (splice_context.empty())
     splice_context.push_back(0);
   int32 input_dim = 10 + Rand() % 20,
       spliced_dim = input_dim * splice_context.size(),
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200),
       cell_dim = 40 + Rand() % 50,
       projection_dim = std::ceil(cell_dim / (Rand() % 10 + 1));
   os << "input-node name=input dim=" << input_dim << std::endl;
   // Parameter Definitions W*(* replaced by - to have valid names)
   // Input gate control : Wi* matrices
   os << "component name=Wi-xr type=NaturalGradientAffineComponent"
      << " input-dim=" << spliced_dim + projection_dim
      << " output-dim=" << cell_dim << std::endl;
   os << "component name=Wic type=PerElementScaleComponent "
      << " dim=" << cell_dim << std::endl;
   // Forget gate control : Wf* matrices
   os << "component name=Wf-xr type=NaturalGradientAffineComponent"
      << " input-dim=" << spliced_dim + projection_dim
      << " output-dim=" << cell_dim << std::endl;
   os << "component name=Wfc type=PerElementScaleComponent "
      << " dim=" << cell_dim << std::endl;
   // Output gate control : Wo* matrices
   os << "component name=Wo-xr type=NaturalGradientAffineComponent"
      << " input-dim=" << spliced_dim + projection_dim
      << " output-dim=" << cell_dim  << std::endl;
   os << "component name=Woc type=PerElementScaleComponent "
      << " dim=" << cell_dim << std::endl;
   // Cell input matrices : Wc* matrices
   os << "component name=Wc-xr type=NaturalGradientAffineComponent"
      << " input-dim=" << spliced_dim + projection_dim
      << " output-dim=" << cell_dim  << std::endl;
   // projection matrices : Wrm and Wpm
   os << "component name=W-m type=NaturalGradientAffineComponent "
      << " input-dim=" << cell_dim
      << " output-dim=" << 2 * projection_dim << std::endl;
   // Output : Wyr and Wyp
   os << "component name=Wy- type=NaturalGradientAffineComponent "
      << " input-dim=" << 2 * projection_dim
      << " output-dim=" << cell_dim << std::endl;
   // Defining the diagonal matrices
   // Defining the final affine transform
   os << "component name=final_affine type=NaturalGradientAffineComponent "
      << "input-dim=" << cell_dim << " output-dim=" << output_dim << std::endl;
   os << "component name=logsoftmax type=LogSoftmaxComponent dim="
      << output_dim << std::endl;
   // Defining the non-linearities
   //  declare a no-op component so that we can use a sum descriptor's output
   //  multiple times, and to make the config more readable given the equations
   os << "component name=i type=SigmoidComponent dim="
      << cell_dim << std::endl;
   os << "component name=f type=SigmoidComponent dim="
      << cell_dim << std::endl;
   os << "component name=o type=SigmoidComponent dim="
      << cell_dim << std::endl;
   os << "component name=g type=TanhComponent dim="
      << cell_dim << std::endl;
   os << "component name=h type=TanhComponent dim="
      << cell_dim << std::endl;
   os << "component name=c1 type=ElementwiseProductComponent "
      << " input-dim=" << 2 * cell_dim
      << " output-dim=" << cell_dim << std::endl;
   os << "component name=c2 type=ElementwiseProductComponent "
      << " input-dim=" << 2 * cell_dim
      << " output-dim=" << cell_dim << std::endl;
   os << "component name=m type=ElementwiseProductComponent "
      << " input-dim=" << 2 * cell_dim
      << " output-dim=" << cell_dim << std::endl;
   // Defining the computations
   std::ostringstream temp_string_stream;
   for (size_t i = 0; i < splice_context.size(); i++) {
     int32 offset = splice_context[i];
     temp_string_stream << "Offset(input, " << offset << ")";
     if (i + 1 < splice_context.size())
       temp_string_stream << ", ";
   }
   std::string spliced_input = temp_string_stream.str();
   std::string c_tminus1 = "Sum(IfDefined(Offset(c1_t, -1)), IfDefined(Offset( c2_t, -1)))";
   // i_t
   os << "component-node name=i1 component=Wi-xr input=Append("
      << spliced_input << ", IfDefined(Offset(r_t, -1)))\n";
   os << "component-node name=i2 component=Wic "
      << " input=" << c_tminus1 << std::endl;
   os << "component-node name=i_t component=i input=Sum(i1, i2)\n";
   // f_t
   os << "component-node name=f1 component=Wf-xr input=Append("
      << spliced_input << ", IfDefined(Offset(r_t, -1)))\n";
   os << "component-node name=f2 component=Wfc "
      << " input=" << c_tminus1 << std::endl;
   os << "component-node name=f_t component=f input=Sum(f1, f2)\n";
   // o_t
   os << "component-node name=o1 component=Wo-xr input=Append("
      << spliced_input << ", IfDefined(Offset(r_t, -1)))\n";
   os << "component-node name=o2 component=Woc input=Sum(c1_t, c2_t)\n";
   os << "component-node name=o_t component=o input=Sum(o1, o2)\n";
   // h_t
   os << "component-node name=h_t component=h input=Sum(c1_t, c2_t)\n";
   // g_t
   os << "component-node name=g1 component=Wc-xr input=Append("
      << spliced_input << ", IfDefined(Offset(r_t, -1)))\n";
   os << "component-node name=g_t component=g input=g1\n";
   // parts of c_t
   os << "component-node name=c1_t component=c1 "
      << " input=Append(f_t, " << c_tminus1 << ")\n";
   os << "component-node name=c2_t component=c2 input=Append(i_t, g_t)\n";
   // m_t
   os << "component-node name=m_t component=m input=Append(o_t, h_t)\n";
   // r_t and p_t
   os << "component-node name=rp_t component=W-m input=m_t\n";
   // Splitting outputs of Wy- node
   os << "dim-range-node name=r_t input-node=rp_t dim-offset=0 "
      << "dim=" << projection_dim << std::endl;
   // y_t
   os << "component-node name=y_t component=Wy- input=rp_t\n";
   // Final affine transform
   os << "component-node name=final_affine component=final_affine input=y_t\n";
   os << "component-node name=posteriors component=logsoftmax input=final_affine\n";
   os << "output-node name=output input=posteriors\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceLstmType2 (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 474 of file nnet-test-utils.cc.
References rnnlm::i, KALDI_ERR, NnetGenerationOptions::output_dim, and kaldi::Rand().
{
   KALDI_ERR << "Not Implemented";
   std::ostringstream os;
   std::vector<int32> splice_context;
   for (int32 i = -5; i < 4; i++)
     if (Rand() % 3 == 0)
       splice_context.push_back(i);
   if (splice_context.empty())
     splice_context.push_back(0);
   int32 input_dim = 10 + Rand() % 20,
       spliced_dim = input_dim * splice_context.size(),
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200),
       cell_dim = 40 + Rand() % 50,
       projection_dim = std::ceil(cell_dim / (Rand() % 10 + 2));
   os << "input-node name=input dim=" << input_dim << std::endl;
   // Parameter Definitions W*(* replaced by - to have valid names)
   os << "component name=W-x type=NaturalGradientAffineComponent input-dim="
      << spliced_dim << " output-dim=" << 4 * cell_dim << std::endl;
   os << "component name=W-r type=NaturalGradientAffineComponent input-dim="
      << projection_dim << " output-dim=" << 4 * cell_dim << std::endl;
   os << "component name=W-m type=NaturalGradientAffineComponent input-dim="
      << cell_dim << " output-dim=" << 2 * projection_dim  << std::endl;
   os << "component name=Wyr type=NaturalGradientAffineComponent input-dim="
      << projection_dim << " output-dim=" << cell_dim << std::endl;
   os << "component name=Wyp type=NaturalGradientAffineComponent input-dim="
      << projection_dim << " output-dim=" << cell_dim << std::endl;
   // Defining the diagonal matrices
   os << "component name=Wic type=PerElementScaleComponent "
      << " dim=" << cell_dim << std::endl;
   os << "component name=Wfc type=PerElementScaleComponent "
      << " dim=" << cell_dim << std::endl;
   os << "component name=Woc type=PerElementScaleComponent "
      << " dim=" << cell_dim << std::endl;
   // Defining the final affine transform
   os << "component name=final_affine type=NaturalGradientAffineComponent "
      << "input-dim=" << cell_dim << " output-dim=" << output_dim << std::endl;
   os << "component name=logsoftmax type=LogSoftmaxComponent dim="
      << output_dim << std::endl;
   // Defining the non-linearities
   //  declare a no-op component so that we can use a sum descriptor's output
   //  multiple times, and to make the config more readable given the equations
   os << "component name=c_t type=NoOpComponent dim="
      << cell_dim << std::endl;
   os << "component name=i_t type=SigmoidComponent dim="
      << cell_dim << std::endl;
   os << "component name=f_t type=SigmoidComponent dim="
      << cell_dim << std::endl;
   os << "component name=o_t type=SigmoidComponent dim="
      << cell_dim << std::endl;
   os << "component name=g type=TanhComponent dim="
      << cell_dim << std::endl;
   os << "component name=h type=TanhComponent dim="
      << cell_dim << std::endl;
   os << "component name=f_t-c_tminus1 type=ElementwiseProductComponent "
      << " input-dim=" << 2 * cell_dim
      << " output-dim=" << cell_dim << std::endl;
   os << "component name=i_t-g type=ElementwiseProductComponent "
      << " input-dim=" << 2 * cell_dim
      << " output-dim=" << cell_dim << std::endl;
   os << "component name=m_t type=ElementwiseProductComponent "
      << " input-dim=" << 2 * cell_dim
      << " output-dim=" << cell_dim << std::endl;
   // Defining the computations
   os << "component-node name=W-x component=W-x input=Append(";
   for (size_t i = 0; i < splice_context.size(); i++) {
     int32 offset = splice_context[i];
     os << "Offset(input, " << offset << ")";
     if (i + 1 < splice_context.size())
       os << ", ";
   }
   os << ")\n";
   os << "component-node name=W-r component=W-r input=IfDefined(Offset(r_t, -1))\n";
   os << "component-node name=W-m component=W-m input=m_t \n";
   os << "component-node name=Wic component=Wic input=IfDefined(Offset(c_t, -1))\n";
   os << "component-node name=Wfc component=Wfc input=IfDefined(Offset(c_t, -1))\n";
   os << "component-node name=Woc component=Woc input=c_t\n";
   // Splitting the outputs of W*m node
   os << "dim-range-node name=r_t input-node=W-m dim-offset=0 "
      << "dim=" << projection_dim << std::endl;
   os << "dim-range-node name=p_t input-node=W-m dim-offset=" << projection_dim
      << " dim=" << projection_dim << std::endl;
   // Splitting outputs of W*x node
   os << "dim-range-node name=W_ix-x_t input-node=W-x dim-offset=0 "
      << "dim=" << cell_dim << std::endl;
   os << "dim-range-node name=W_fx-x_t input-node=W-x "
      << "dim-offset=" << cell_dim << " dim="<<cell_dim << std::endl;
   os << "dim-range-node name=W_cx-x_t input-node=W-x "
      << "dim-offset=" << 2 * cell_dim << " dim="<<cell_dim << std::endl;
   os << "dim-range-node name=W_ox-x_t input-node=W-x "
      << "dim-offset=" << 3 * cell_dim << " dim="<<cell_dim << std::endl;
   // Splitting outputs of W*r node
   os << "dim-range-node name=W_ir-r_tminus1 input-node=W-r dim-offset=0 "
      << "dim=" << cell_dim << std::endl;
   os << "dim-range-node name=W_fr-r_tminus1 input-node=W-r "
      << "dim-offset=" << cell_dim << " dim="<<cell_dim << std::endl;
   os << "dim-range-node name=W_cr-r_tminus1 input-node=W-r "
      << "dim-offset=" << 2 * cell_dim << " dim="<<cell_dim << std::endl;
   os << "dim-range-node name=W_or-r_tminus1 input-node=W-r "
      << "dim-offset=" << 3 * cell_dim << " dim="<<cell_dim << std::endl;
   // Non-linear operations
   os << "component-node name=c_t component=c_t input=Sum(f_t-c_tminus1, i_t-g)\n";
   os << "component-node name=h component=h input=c_t\n";
   os << "component-node name=i_t component=i_t input=Sum(W_ix-x_t, Sum(W_ir-r_tminus1, Wic))\n";
   os << "component-node name=f_t component=f_t input=Sum(W_fx-x_t, Sum(W_fr-r_tminus1, Wfc))\n";
   os << "component-node name=o_t component=o_t input=Sum(W_ox-x_t, Sum(W_or-r_tminus1, Woc))\n";
   os << "component-node name=f_t-c_tminus1 component=f_t-c_tminus1 input=Append(f_t, Offset(c_t, -1))\n";
   os << "component-node name=i_t-g component=i_t-g input=Append(i_t, g)\n";
   os << "component-node name=m_t component=m_t input=Append(o_t, h)\n";
   os << "component-node name=g component=g input=Sum(W_cx-x_t, W_cr-r_tminus1)\n";
   // Final affine transform
   os << "component-node name=Wyr component=Wyr input=r_t\n";
   os << "component-node name=Wyp component=Wyp input=p_t\n";
   os << "component-node name=final_affine component=final_affine input=Sum(Wyr, Wyp)\n";
   os << "component-node name=posteriors component=logsoftmax input=final_affine\n";
   os << "output-node name=output input=posteriors\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceRnn (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 166 of file nnet-test-utils.cc.
References rnnlm::i, NnetGenerationOptions::output_dim, kaldi::Rand(), and kaldi::RandInt().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   std::vector<int32> splice_context;
   for (int32 i = -5; i < 4; i++)
     if (Rand() % 3 == 0)
       splice_context.push_back(i);
   if (splice_context.empty())
     splice_context.push_back(0);
   int32 input_dim = 10 + Rand() % 20,
       spliced_dim = input_dim * splice_context.size(),
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200),
       hidden_dim = 40 + Rand() % 50;
   os << "component name=affine1 type=NaturalGradientAffineComponent input-dim="
      << spliced_dim << " output-dim=" << hidden_dim << std::endl;
   if (RandInt(0, 1) == 0) {
     os << "component name=nonlin1 type=RectifiedLinearComponent dim="
        << hidden_dim << std::endl;
   } else {
     os << "component name=nonlin1 type=TanhComponent dim="
        << hidden_dim << std::endl;
   }
   os << "component name=recurrent_affine1 type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << hidden_dim << std::endl;
   os << "component name=affine2 type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << output_dim << std::endl;
   os << "component name=logsoftmax type=LogSoftmaxComponent dim="
      << output_dim << std::endl;
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component-node name=affine1_node component=affine1 input=Append(";
   for (size_t i = 0; i < splice_context.size(); i++) {
     int32 offset = splice_context[i];
     os << "Offset(input, " << offset << ")";
     if (i + 1 < splice_context.size())
       os << ", ";
   }
   os << ")\n";
   os << "component-node name=recurrent_affine1 component=recurrent_affine1 "
         "input=Offset(nonlin1, -1)\n";
   os << "component-node name=nonlin1 component=nonlin1 "
         "input=Sum(affine1_node, IfDefined(recurrent_affine1))\n";
   os << "component-node name=affine2 component=affine2 input=nonlin1\n";
   os << "component-node name=output_nonlin component=logsoftmax input=affine2\n";
   os << "output-node name=output input=output_nonlin\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceRnnClockwork (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 225 of file nnet-test-utils.cc.
References rnnlm::i, NnetGenerationOptions::output_dim, and kaldi::Rand().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   std::vector<int32> splice_context;
   for (int32 i = -5; i < 4; i++)
     if (Rand() % 3 == 0)
       splice_context.push_back(i);
   if (splice_context.empty())
     splice_context.push_back(0);
   int32 input_dim = 10 + Rand() % 20,
       spliced_dim = input_dim * splice_context.size(),
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200),
       hidden_dim = 40 + Rand() % 50;
   os << "component name=affine1 type=NaturalGradientAffineComponent input-dim="
      << spliced_dim << " output-dim=" << hidden_dim << std::endl;
   os << "component name=nonlin1 type=RectifiedLinearComponent dim="
      << hidden_dim << std::endl;
   os << "component name=recurrent_affine1 type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << hidden_dim << std::endl;
   // the suffix _0, _1, _2 equals the index of the output-frame modulo 3; there
   // are 3 versions of the final affine layer.  There was a paper by Vincent
   // Vanhoucke about something like this.
   os << "component name=final_affine_0 type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << output_dim << std::endl;
   os << "component name=final_affine_1 type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << output_dim << std::endl;
   os << "component name=final_affine_2 type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << output_dim << std::endl;
   os << "component name=logsoftmax type=LogSoftmaxComponent dim="
      << output_dim << std::endl;
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component-node name=affine1_node component=affine1 input=Append(";
   for (size_t i = 0; i < splice_context.size(); i++) {
     int32 offset = splice_context[i];
     os << "Offset(input, " << offset << ")";
     if (i + 1 < splice_context.size())
       os << ", ";
   }
   os << ")\n";
   os << "component-node name=recurrent_affine1 component=recurrent_affine1 "
         "input=Offset(nonlin1, -1)\n";
   os << "component-node name=nonlin1 component=nonlin1 "
         "input=Sum(affine1_node, IfDefined(recurrent_affine1))\n";
   os << "component-node name=final_affine_0 component=final_affine_0 input=nonlin1\n";
   os << "component-node name=final_affine_1 component=final_affine_1 input=Offset(nonlin1, -1)\n";
   os << "component-node name=final_affine_2 component=final_affine_2 input=Offset(nonlin1, 1)\n";
   os << "component-node name=output_nonlin component=logsoftmax input=Switch(final_affine_0, final_affine_1, final_affine_2)\n";
   os << "output-node name=output input=output_nonlin\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceSimple (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 93 of file nnet-test-utils.cc.
References NnetGenerationOptions::allow_final_nonlinearity, rnnlm::i, NnetGenerationOptions::output_dim, kaldi::Rand(), and kaldi::RandInt().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   std::vector<int32> splice_context;
   for (int32 i = -5; i < 4; i++)
     if (Rand() % 3 == 0)
       splice_context.push_back(i);
   if (splice_context.empty())
     splice_context.push_back(0);
   int32 input_dim = 10 + Rand() % 20,
       spliced_dim = input_dim * splice_context.size(),
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200),
       hidden_dim = 40 + Rand() % 50;
   bool use_final_nonlinearity = (opts.allow_final_nonlinearity &&
                                  RandInt(0, 1) == 0);
   os << "component name=affine1 type=NaturalGradientAffineComponent input-dim="
      << spliced_dim << " output-dim=" << hidden_dim << std::endl;
   os << "component name=relu1 type=RectifiedLinearComponent dim="
      << hidden_dim << std::endl;
   os << "component name=final_affine type=NaturalGradientAffineComponent input-dim="
      << hidden_dim << " output-dim=" << output_dim << std::endl;
   if (use_final_nonlinearity) {
     if (Rand() % 2 == 0) {
       os << "component name=logsoftmax type=SoftmaxComponent dim="
          << output_dim << std::endl;
     } else {
       os << "component name=logsoftmax type=LogSoftmaxComponent dim="
          << output_dim << std::endl;
     }
   }
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component-node name=affine1_node component=affine1 input=Append(";
   for (size_t i = 0; i < splice_context.size(); i++) {
     int32 offset = splice_context[i];
     os << "Offset(input, " << offset << ")";
     if (i + 1 < splice_context.size())
       os << ", ";
   }
   os << ")\n";
   os << "component-node name=nonlin1 component=relu1 input=affine1_node\n";
   os << "component-node name=final_affine component=final_affine input=nonlin1\n";
   if (use_final_nonlinearity) {
     os << "component-node name=output_nonlin component=logsoftmax input=final_affine\n";
     os << "output-node name=output input=output_nonlin\n";
   } else {
     os << "output-node name=output input=final_affine\n";
   }
   configs->push_back(os.str());
   if ((Rand() % 2) == 0) {
     std::ostringstream os2;
     os2 << "component name=affine2 type=NaturalGradientAffineComponent input-dim="
         << hidden_dim << " output-dim=" << hidden_dim << std::endl;
     os2 << "component name=relu2 type=RectifiedLinearComponent dim="
         << hidden_dim << std::endl;
     // regenerate the final_affine component when we add the new config.
     os2 << "component name=final_affine type=NaturalGradientAffineComponent input-dim="
         << hidden_dim << " output-dim=" << output_dim << std::endl;
     os2 << "component-node name=affine2 component=affine2 input=nonlin1\n";
     os2 << "component-node name=relu2 component=relu2 input=affine2\n";
     os2 << "component-node name=final_affine component=final_affine input=relu2\n";
     configs->push_back(os2.str());
   }
 }
void kaldi::nnet3::GenerateConfigSequenceSimpleContext (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 53 of file nnet-test-utils.cc.
References rnnlm::i, NnetGenerationOptions::output_dim, and kaldi::Rand().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   std::vector<int32> splice_context;
   for (int32 i = -5; i < 4; i++)
     if (Rand() % 3 == 0)
       splice_context.push_back(i);
   if (splice_context.empty())
     splice_context.push_back(0);
   int32 input_dim = 10 + Rand() % 20,
       spliced_dim = input_dim * splice_context.size(),
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200);
   os << "component name=affine1 type=AffineComponent input-dim="
      << spliced_dim << " output-dim=" << output_dim << std::endl;
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component-node name=affine1_node component=affine1 input=Append(";
   for (size_t i = 0; i < splice_context.size(); i++) {
     int32 offset = splice_context[i];
     os << "Offset(input, " << offset << ")";
     if (i + 1 < splice_context.size())
       os << ", ";
   }
   os << ")\n";
   os << "output-node name=output input=affine1_node\n";
   configs->push_back(os.str());
 }
void kaldi::nnet3::GenerateConfigSequenceSimplest (const NnetGenerationOptions & opts, std::vector< std::string > * configs)
Definition at line 32 of file nnet-test-utils.cc.
References NnetGenerationOptions::output_dim, and kaldi::Rand().
Referenced by GenerateConfigSequence().
{
   std::ostringstream os;
   int32 input_dim = 10 + Rand() % 20,
       output_dim = (opts.output_dim > 0 ?
                     opts.output_dim :
                     100 + Rand() % 200);
   os << "component name=affine1 type=AffineComponent input-dim="
      << input_dim << " output-dim=" << output_dim << std::endl;
   os << "input-node name=input dim=" << input_dim << std::endl;
   os << "component-node name=affine1_node component=affine1 input=input\n";
   os << "output-node name=output input=affine1_node\n";
   configs->push_back(os.str());
 }
static void kaldi::nnet3::GenerateRandomComponentConfig (std::string * component_type, std::string * config) static
Definition at line 835 of file nnet-test-utils.cc.
References rnnlm::i, KALDI_ERR, rnnlm::n, kaldi::Rand(), and kaldi::RandInt().
Referenced by GenerateRandomSimpleComponent().
{
   int32 n = RandInt(0, 27);
   BaseFloat learning_rate = 0.001 * RandInt(1, 3);
   std::ostringstream os;
   switch(n) {
     case 0: {
       *component_type = "PnormComponent";
       int32 output_dim = RandInt(1, 50), group_size = RandInt(1, 15),
           input_dim = output_dim * group_size;
       os << "input-dim=" << input_dim << " output-dim=" << output_dim;
       break;
     }
     case 1: {
       BaseFloat target_rms = (RandInt(1, 200) / 100.0);
       *component_type = "NormalizeComponent";
       os << "dim=" << RandInt(1, 50)
          << " target-rms=" << target_rms;
       break;
     }
     case 2: {
       *component_type = "SigmoidComponent";
       os << "dim=" << RandInt(1, 50);
       break;
     }
     case 3: {
       *component_type = "TanhComponent";
       os << "dim=" << RandInt(1, 50);
       break;
     }
     case 4: {
       *component_type = "RectifiedLinearComponent";
       os << "dim=" << RandInt(1, 50);
       break;
     }
     case 5: {
       *component_type = "SoftmaxComponent";
       os << "dim=" << RandInt(1, 50);
       break;
     }
     case 6: {
       *component_type = "LogSoftmaxComponent";
       os << "dim=" << RandInt(1, 50);
       break;
     }
     case 7: {
       *component_type = "NoOpComponent";
       os << "dim=" << RandInt(1, 50);
       break;
     }
     case 8: {
       *component_type = "FixedAffineComponent";
       int32 input_dim = RandInt(1, 50), output_dim = RandInt(1, 50);
       os << "input-dim=" << input_dim << " output-dim=" << output_dim;
       break;
     }
     case 9: {
       *component_type = "AffineComponent";
       int32 input_dim = RandInt(1, 50), output_dim = RandInt(1, 50);
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " learning-rate=" << learning_rate;
       break;
     }
     case 10: {
       *component_type = "NaturalGradientAffineComponent";
       int32 input_dim = RandInt(1, 50), output_dim = RandInt(1, 50);
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " learning-rate=" << learning_rate;
       break;
     }
     case 11: {
       *component_type = "SumGroupComponent";
       std::vector<int32> sizes;
       int32 num_groups = RandInt(1, 50);
       os << "sizes=";
       for (int32 i = 0; i < num_groups; i++) {
         os << RandInt(1, 5);
         if (i + 1 < num_groups)
           os << ',';
       }
       break;
     }
     case 12: {
       *component_type = "FixedScaleComponent";
       os << "dim=" << RandInt(1, 100);
       break;
     }
     case 13: {
       *component_type = "FixedBiasComponent";
       os << "dim=" << RandInt(1, 100);
       break;
     }
     case 14: {
       *component_type = "NaturalGradientPerElementScaleComponent";
       os << "dim=" << RandInt(1, 100)
          << " learning-rate=" << learning_rate;
       break;
     }
     case 15: {
       *component_type = "PerElementScaleComponent";
       os << "dim=" << RandInt(1, 100)
          << " learning-rate=" << learning_rate;
       break;
     }
     case 16: {
       *component_type = "ElementwiseProductComponent";
       int32 output_dim = RandInt(1, 100), multiple = RandInt(2, 4),
           input_dim = output_dim * multiple;
       os << "input-dim=" << input_dim << " output-dim=" << output_dim;
       break;
     }
     case 17: {
       *component_type = "Convolutional1dComponent";
       int32 patch_stride = 10 + Rand() % 50, patch_step = 1 + Rand() % 4,
             patch_dim = 4 + Rand () % 5;
       // decrease patch_stride so that
       // (patch_stride - patch_dim) % patch_step == 0
       patch_stride = patch_stride - ((patch_stride - patch_dim) % patch_step);
       int32 num_patches = 1 + (patch_stride - patch_dim) / patch_step;
       int32 num_splice = 5 + Rand() % 10, num_filters = 5 + Rand() % 10;
       int32 input_dim = patch_stride * num_splice;
       int32 output_dim = num_patches * num_filters;
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " patch-dim=" << patch_dim << " patch-step=" << patch_step
          << " patch-stride=" << patch_stride
          << " learning-rate=" << learning_rate;
       break;
     }
     case 18: {
       int32 input_vectorization = Rand() % 2;
       std::string vectorization;
       if (input_vectorization == 0) {
         vectorization = "yzx";
       } else  {
         vectorization = "zyx";
       }
       *component_type = "ConvolutionComponent";
       int32 input_x_dim = 10 + Rand() % 20,
             input_y_dim = 10 + Rand() % 20,
             input_z_dim = 3 + Rand() % 10,
             filt_x_dim = 1 + Rand() % input_x_dim,
             filt_y_dim = 1 + Rand() % input_y_dim,
             num_filters = 1 + Rand() % 10,
             filt_x_step = (1 + Rand() % filt_x_dim),
             filt_y_step = (1 + Rand() % filt_y_dim);
       int32 remainder = (input_x_dim - filt_x_dim) % filt_x_step;
       // adjusting input_x_dim to ensure divisibility
       input_x_dim = input_x_dim - remainder;
       remainder = (input_y_dim - filt_y_dim) % filt_y_step;
       // adjusting input_x_dim to ensure divisibility
       input_y_dim = input_y_dim - remainder;
       os << "input-x-dim=" << input_x_dim
          << " input-y-dim=" << input_y_dim
          << " input-z-dim=" << input_z_dim
          << " filt-x-dim=" << filt_x_dim
          << " filt-y-dim=" << filt_y_dim
          << " filt-x-step=" << filt_x_step
          << " filt-y-step=" << filt_y_step
          << " num-filters=" << num_filters
          << " input-vectorization-order=" << vectorization
          << " learning-rate=" << learning_rate;
       break;
       // TODO : add test for file based initialization. But confirm how to write
       // a file which is not going to be overwritten by other components
     }
     case 19: {
       *component_type = "MaxpoolingComponent";
       int32 pool_stride = 5 + Rand() % 10,
       pool_size = 2 + Rand() % 3,
       num_pools = 1 + Rand() % 10;
       int32 output_dim = num_pools * pool_stride;
       int32 num_patches = num_pools * pool_size;
       int32 input_dim = pool_stride * num_patches;
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " pool-size=" << pool_size << " pool-stride=" << pool_stride;
       break;
     }
     case 20: {
       *component_type = "PermuteComponent";
       int32 input_dim = 10 + Rand() % 100;
       std::vector<int32> column_map(input_dim);
       for (int32 i = 0; i < input_dim; i++)
         column_map[i] = i;
       std::random_shuffle(column_map.begin(), column_map.end());
       std::ostringstream buffer;
       for (int32 i = 0; i < input_dim-1; i++)
         buffer << column_map[i] << ",";
       buffer << column_map.back();
       os << "column-map=" << buffer.str();
       break;
     }
     case 21: {
       *component_type = "PerElementOffsetComponent";
       std::string param_config = RandInt(0, 1)?
                                  " param-mean=0.0 param-stddev=0.0":
                                  " param-mean=0.0 param-stddev=1.0";
       os << "dim=" << RandInt(1, 100)
          << " learning-rate=" << learning_rate << param_config;
       break;
     }
     case 22: {
       *component_type = "SumReduceComponent";
       int32 output_dim = RandInt(1, 50), group_size = RandInt(1, 15),
           input_dim = output_dim * group_size;
       os << "input-dim=" << input_dim << " output-dim=" << output_dim;
       break;
     }
     case 23: {
       *component_type = "CompositeComponent";
       int32 cur_dim = RandInt(20, 30), num_components = RandInt(1, 3),
           max_rows_process = RandInt(1, 30);
       os << "num-components=" << num_components
          << " max-rows-process=" << max_rows_process;
       std::vector<std::string> sub_configs;
       for (int32 i = 1; i <= num_components; i++) {
         if (RandInt(1, 3) == 1) {
           os << " component" << i << "='type=RectifiedLinearComponent dim="
              << cur_dim << "'";
         } else if (RandInt(1, 2) == 1) {
           os << " component" << i << "='type=TanhComponent dim="
              << cur_dim << "'";
         } else {
           int32 next_dim = RandInt(20, 30);
           os << " component" << i << "='type=AffineComponent input-dim="
              << cur_dim << " output-dim=" << next_dim << "'";
           cur_dim = next_dim;
         }
       }
       break;
     }
     case 24: {
       *component_type = "SumGroupComponent";
       int32 num_groups = RandInt(1, 50),
         input_dim = num_groups * RandInt(1, 15);
       os << "input-dim=" << input_dim << " output-dim=" << num_groups;
       break;
     }
     case 25: {
       *component_type = "RepeatedAffineComponent";
       int32 num_repeats = RandInt(1, 50),
           input_dim = num_repeats * RandInt(1, 15),
           output_dim = num_repeats * RandInt(1, 15);
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " num-repeats=" << num_repeats;
       break;
     }
     case 26: {
       *component_type = "BlockAffineComponent";
       int32 num_blocks = RandInt(1, 50),
           input_dim = num_blocks * RandInt(1, 15),
           output_dim = num_blocks * RandInt(1, 15);
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " num-blocks=" << num_blocks;
       break;
     }
     case 27: {
       *component_type = "NaturalGradientRepeatedAffineComponent";
       int32 num_repeats = RandInt(1, 50),
           input_dim = num_repeats * RandInt(1, 15),
           output_dim = num_repeats * RandInt(1, 15);
       os << "input-dim=" << input_dim << " output-dim=" << output_dim
          << " num-repeats=" << num_repeats;
       break;
     }
     default:
       KALDI_ERR << "Error generating random component";
   }
   *config = os.str();
 }
Component * GenerateRandomSimpleComponent ()
Generates random simple component for testing.
Definition at line 1110 of file nnet-test-utils.cc.
References GenerateRandomComponentConfig(), Component::InitFromConfig(), KALDI_ERR, Component::NewComponentOfType(), and ConfigLine::ParseLine().
Referenced by UnitTestNnetComponent().
{
   std::string component_type, config;
   GenerateRandomComponentConfig(&component_type, &config);
   ConfigLine config_line;
   if (!config_line.ParseLine(config))
     KALDI_ERR << "Bad config line " << config;
   Component *c = Component::NewComponentOfType(component_type);
   if (c == NULL)
     KALDI_ERR << "Invalid component type " << component_type;
   c->InitFromConfig(&config_line);
   return c;
 }
void GenerateSimpleNnetTrainingExample (int32 num_supervised_frames, int32 left_context, int32 right_context, int32 input_dim, int32 output_dim, int32 ivector_dim, NnetExample * example)
Low-level function that generates an nnet training example.
By "simple" we mean there is one output named "output", an input named "input", and possibly also an input named "ivector" (this will be assumed absent if ivector_dim <= 0). This function generates exactly "left_context" or "right_context" frames of context on the left and right respectively.
Definition at line 1154 of file nnet-test-utils.cc.
References GeneralMatrix::Compress(), NnetIo::features, rnnlm::i, NnetExample::io, KALDI_ASSERT, kaldi::RandInt(), kaldi::RandUniform(), and MatrixBase< Real >::SetRandn().
Referenced by UnitTestNnetExample(), and UnitTestNnetMergeExamples().
{
   KALDI_ASSERT(num_supervised_frames > 0 && left_context >= 0 &&
                right_context >= 0 && output_dim > 0 && input_dim > 0
                && example != NULL);
   example->io.clear();
   int32 feature_t_begin = RandInt(0, 2);
   int32 num_feat_frames = left_context + right_context + num_supervised_frames;
   Matrix<BaseFloat> input_mat(num_feat_frames, input_dim);
   input_mat.SetRandn();
   NnetIo input_feat("input", feature_t_begin, input_mat);
   if (RandInt(0, 1) == 0)
     input_feat.features.Compress();
   example->io.push_back(input_feat);
   if (ivector_dim > 0) {
     // Create a feature for the iVectors.  iVectors always have t=0 in the
     // current framework.
     Matrix<BaseFloat> ivector_mat(1, ivector_dim);
     ivector_mat.SetRandn();
     NnetIo ivector_feat("ivector", 0, ivector_mat);
     if (RandInt(0, 1) == 0)
       ivector_feat.features.Compress();
     example->io.push_back(ivector_feat);
   }
   {  // set up the output supervision.
     Posterior labels(num_supervised_frames);
     for (int32 t = 0; t < num_supervised_frames; t++) {
       int32 num_labels = RandInt(1, 3);
       BaseFloat remaining_prob_mass = 1.0;
       for (int32 i = 0; i < num_labels; i++) {
         BaseFloat this_prob = (i+1 == num_labels ? 1.0 : RandUniform()) *
             remaining_prob_mass;
         remaining_prob_mass -= this_prob;
         labels[t].push_back(std::pair<int32, BaseFloat>(RandInt(0, output_dim-1),
                                                         this_prob));
       }
     }
     int32 supervision_t_begin = feature_t_begin + left_context;
     NnetIo output_sup("output", output_dim, supervision_t_begin,
                       labels);
     example->io.push_back(output_sup);
   }
 }
void kaldi::nnet3::GenRandDescriptor (int32 num_nodes, Descriptor * desc)
Definition at line 75 of file nnet-descriptor-test.cc.
References GenRandSumDescriptor(), and kaldi::Rand().
Referenced by UnitTestDescriptorIo(), and UnitTestGeneralDescriptor().
{
   int32 num_parts = 1 + Rand() % 3;
   std::vector<SumDescriptor*> parts;
   for (int32 part = 0; part < num_parts; part++)
     parts.push_back(GenRandSumDescriptor(num_nodes));
   *desc = Descriptor(parts);
 }
ForwardingDescriptor* kaldi::nnet3::GenRandForwardingDescriptor (int32 num_nodes)
Definition at line 25 of file nnet-descriptor-test.cc.
References rnnlm::i, ReplaceIndexForwardingDescriptor::kT, ReplaceIndexForwardingDescriptor::kX, rnnlm::n, kaldi::Rand(), Index::t, and Index::x.
Referenced by GenRandSumDescriptor().
{
   if (Rand() % 2 != 0) {
     return new SimpleForwardingDescriptor(Rand() % num_nodes);
   } else {
     int32 r = Rand() % 4;
     if (r == 0) {
       Index offset;
       offset.t = Rand() % 5;
       offset.x = Rand() % 2;
       return
           new OffsetForwardingDescriptor(GenRandForwardingDescriptor(num_nodes),
                                          offset);
     } else if (r == 1) {
       std::vector<ForwardingDescriptor*> vec;
       int32 n = 1 + Rand() % 3;
       for (int32 i = 0; i < n; i++)
         vec.push_back(GenRandForwardingDescriptor(num_nodes));
       return new SwitchingForwardingDescriptor(vec);
     } else if (r == 2) {
       return new RoundingForwardingDescriptor(
           GenRandForwardingDescriptor(num_nodes), 1 + Rand() % 4);
     } else {
       return new ReplaceIndexForwardingDescriptor(
           GenRandForwardingDescriptor(num_nodes),
           (Rand() % 2 == 0 ? ReplaceIndexForwardingDescriptor::kT :
            ReplaceIndexForwardingDescriptor::kX),
           -2 + Rand() % 4);
     }
   }
 }
SumDescriptor* kaldi::nnet3::GenRandSumDescriptor (int32 num_nodes)
Definition at line 57 of file nnet-descriptor-test.cc.
References GenRandForwardingDescriptor(), BinarySumDescriptor::kFailover, BinarySumDescriptor::kSum, and kaldi::Rand().
Referenced by GenRandDescriptor().
                      {
   if (Rand() % 3 != 0) {
     bool not_required = (Rand() % 5 == 0);
     if (not_required)
       return new OptionalSumDescriptor(GenRandSumDescriptor(num_nodes));
     else
       return new SimpleSumDescriptor(GenRandForwardingDescriptor(num_nodes));
   } else {
     return new BinarySumDescriptor((Rand() % 2 == 0 ? BinarySumDescriptor::kSum:
                                     BinarySumDescriptor::kFailover),
                                    GenRandSumDescriptor(num_nodes),
                                    GenRandSumDescriptor(num_nodes));
   }
 }
void GetComputationRequest (const Nnet & nnet, const NnetExample & eg, bool need_model_derivative, bool store_component_stats, ComputationRequest * computation_request)
This function takes a NnetExample (which should already have been frame-selected, if desired, and merged into a minibatch) and produces a ComputationRequest.
It ssumes you don't want the derivatives w.r.t. the inputs; if you do, you can create/modify the ComputationRequest manually. Assumes that if need_model_derivative is true, you will be supplying derivatives w.r.t. all outputs.
Definition at line 187 of file nnet-example-utils.cc.
References Nnet::GetNodeIndex(), IoSpecification::has_deriv, rnnlm::i, NnetIo::indexes, IoSpecification::indexes, ComputationRequest::inputs, NnetExample::io, Nnet::IsInputNode(), Nnet::IsOutputNode(), KALDI_ERR, NnetIo::name, IoSpecification::name, ComputationRequest::need_model_derivative, ComputationRequest::outputs, and ComputationRequest::store_component_stats.
Referenced by NnetLdaStatsAccumulator::AccStats(), NnetComputerFromEg::Compute(), NnetComputeProb::Compute(), and NnetTrainer::Train().
{
   request->inputs.clear();
   request->inputs.reserve(eg.io.size());
   request->outputs.clear();
   request->outputs.reserve(eg.io.size());
   request->need_model_derivative = need_model_derivative;
   request->store_component_stats = store_component_stats;
   for (size_t i = 0; i < eg.io.size(); i++) {
     const NnetIo &io = eg.io[i];
     const std::string &name = io.name;
     int32 node_index = nnet.GetNodeIndex(name);
     if (node_index == -1 &&
         !nnet.IsInputNode(node_index) && !nnet.IsOutputNode(node_index))
       KALDI_ERR << "Nnet example has input or output named '" << name
                 << "', but no such input or output node is in the network.";
     std::vector<IoSpecification> &dest =
         nnet.IsInputNode(node_index) ? request->inputs : request->outputs;
     dest.resize(dest.size() + 1);
     IoSpecification &io_spec = dest.back();
     io_spec.name = name;
     io_spec.indexes = io.indexes;
     io_spec.has_deriv = nnet.IsOutputNode(node_index) && need_model_derivative;
   }
   // check to see if something went wrong.
   if (request->inputs.empty())
     KALDI_ERR << "No inputs in computation request.";
   if (request->outputs.empty())
     KALDI_ERR << "No outputs in computation request.";
 }
int32 kaldi::nnet3::GetCount (double expected_count)
Definition at line 32 of file nnet3-copy-egs.cc.
References KALDI_ASSERT, and kaldi::WithProb().
Referenced by main().
{
   KALDI_ASSERT(expected_count >= 0.0);
   int32 ans = floor(expected_count);
   expected_count -= ans;
   if (WithProb(expected_count))
     ans++;
   return ans;
 }
static void kaldi::nnet3::GetIndexesMultiStrings (const Nnet & nnet, const NnetComputation & computation, std::vector< std::string > * indexes_multi_strings) static
Definition at line 189 of file nnet-computation.cc.
References NnetComputation::SubMatrixInfo::col_offset, rnnlm::i, NnetComputation::indexes_multi, rnnlm::j, KALDI_WARN, NnetComputation::matrices, NnetComputation::SubMatrixInfo::matrix_index, NnetComputation::MatrixInfo::num_cols, NnetComputation::SubMatrixInfo::num_cols, NnetComputation::MatrixInfo::num_rows, NnetComputation::SubMatrixInfo::num_rows, NnetComputation::SubMatrixInfo::row_offset, and NnetComputation::submatrices.
Referenced by NnetComputation::GetCommandStrings(), and NnetComputation::Print().
{
   int32 indexes_multi_size = computation.indexes_multi.size();
   indexes_multi_strings->resize(indexes_multi_size);
   for (int32 i = 0; i < indexes_multi_size; i++) {
     std::ostringstream os;
     os << "[";
     const std::vector<std::pair<int32, int32> > &vec =
         computation.indexes_multi[i];
     int32 size = vec.size();
     for (int32 j = 0; j < size; j++) {
       int32 submat_index = vec[j].first, row_index = vec[j].second;
       if (submat_index == -1) {
         os << "NULL";
       } else {
         const NnetComputation::SubMatrixInfo &submat =
             computation.submatrices[submat_index];
         const NnetComputation::MatrixInfo &mat =
             computation.matrices[submat.matrix_index];
         int32 row = row_index + submat.row_offset;
         int32 col_start = submat.col_offset,
             col_end = col_start + submat.num_cols;
         if (!(row_index < submat.num_rows &&
               row < mat.num_rows)) {
           KALDI_WARN << "Invalid indexes in indexes-multi[" << i
                      << ": submatrix " << submat_index << " = m"
                      << submat.matrix_index << "(" << submat.row_offset
                      << ':' << (submat.row_offset + submat.num_rows - 1)
                      << ',' << submat.col_offset << ':'
                      << (submat.col_offset + submat.num_cols - 1) << ") has "
                      << submat.num_rows << " rows, but you access row "
                      << row_index;
         }
         if (col_start == 0 && col_end == mat.num_cols)
           os << 'm' << submat.matrix_index << '(' << row << ",:)";
         else
           os << 'm' << submat.matrix_index << '(' << row << ',' << col_start
              << ':' << (col_end - 1) << ')';
       }
       if (j + 1 < size) os << ",";
     }
     os << "]";
     (*indexes_multi_strings)[i] = os.str();
   }
 }
static void kaldi::nnet3::GetIndexesStrings (const Nnet & nnet, const NnetComputation & computation, std::vector< std::string > * indexes_strings) static
Definition at line 175 of file nnet-computation.cc.
References rnnlm::i, NnetComputation::indexes, and PrintIntegerVector().
Referenced by NnetComputation::GetCommandStrings(), and NnetComputation::Print().
{
   int32 size = computation.indexes.size();
   indexes_strings->resize(size);
   for (int32 i = 0; i < size; i++) {
     std::ostringstream os;
     PrintIntegerVector(os, computation.indexes[i]);
     (*indexes_strings)[i] = os.str();
   }
 }
static void kaldi::nnet3::GetIoNames (const std::vector< NnetExample > & src, std::vector< std::string > * names_vec) static
Definition at line 31 of file nnet-example-utils.cc.
References kaldi::CopySetToVector().
Referenced by MergeExamples().
{
   std::set<std::string> names;
   std::vector<NnetExample>::const_iterator iter = src.begin(), end = src.end();
   for (; iter != end; ++iter) {
     std::vector<NnetIo>::const_iterator iter2 = iter->io.begin(),
                                          end2 = iter->io.end();
     for (; iter2 != end2; ++iter2)
       names.insert(iter2->name);
   }
   CopySetToVector(names, names_vec);
 }
static void kaldi::nnet3::GetIoSizes (const std::vector< NnetExample > & src, const std::vector< std::string > & names, std::vector< int32 > * sizes) static
Definition at line 47 of file nnet-example-utils.cc.
References NnetIo::features, rnnlm::i, NnetIo::indexes, KALDI_ASSERT, KALDI_ERR, NnetIo::name, GeneralMatrix::NumCols(), and GeneralMatrix::NumRows().
Referenced by MergeExamples().
{
   std::vector<int32> dims(names.size(), -1);  // just for consistency checking.
   sizes->clear();
   sizes->resize(names.size(), 0);
   std::vector<std::string>::const_iterator names_begin = names.begin(),
                                              names_end = names.end();
   std::vector<NnetExample>::const_iterator iter = src.begin(), end = src.end();
   for (; iter != end; ++iter) {
     std::vector<NnetIo>::const_iterator iter2 = iter->io.begin(),
                                          end2 = iter->io.end();
     for (; iter2 != end2; ++iter2) {
       const NnetIo &io = *iter2;
       std::vector<std::string>::const_iterator names_iter =
           std::lower_bound(names_begin, names_end, io.name);
       KALDI_ASSERT(*names_iter == io.name);
       int32 i = names_iter - names_begin;
       int32 this_dim = io.features.NumCols();
       if (dims[i] == -1)
         dims[i] = this_dim;
       else if(dims[i] != this_dim) {
         KALDI_ERR << "Merging examples with inconsistent feature dims: "
                   << dims[i] << " vs. " << this_dim << " for '"
                   << io.name << "'.";
       }
       KALDI_ASSERT(io.features.NumRows() == io.indexes.size());
       int32 this_size = io.indexes.size();
       (*sizes)[i] += this_size;
     }
   }
 }
static NnetComputation::SubMatrixInfo kaldi::nnet3::GetSubMatrixOfSubMatrix (const NnetComputation & computation, int32 submat_a, int32 submat_b) static
This static function returns a SubMatrixInfo corresponding to replacing the matrix-index in a's "matrix_index" with, essentially, sub-matrix b.
Of course the matrix_index will be b's "matrix_index", but we may have to modify the row and column offsets. The idea is that sub-matrix submat_b should have the same dimensions as the matrix underlying submat_a.
Definition at line 773 of file nnet-optimize-utils.cc.
References NnetComputation::SubMatrixInfo::col_offset, KALDI_ASSERT, NnetComputation::matrices, NnetComputation::SubMatrixInfo::matrix_index, NnetComputation::MatrixInfo::num_cols, NnetComputation::SubMatrixInfo::num_cols, NnetComputation::MatrixInfo::num_rows, NnetComputation::SubMatrixInfo::num_rows, NnetComputation::SubMatrixInfo::row_offset, and NnetComputation::submatrices.
Referenced by VariableMergingOptimizer::DoLeftMerge(), and VariableMergingOptimizer::DoRightMerge().
{
   KALDI_ASSERT(static_cast<size_t>(submat_a) < computation.submatrices.size());
   KALDI_ASSERT(static_cast<size_t>(submat_b) < computation.submatrices.size());
   const NnetComputation::SubMatrixInfo &a = computation.submatrices[submat_a],
                                        &b = computation.submatrices[submat_b];
   const NnetComputation::MatrixInfo &a_mat =
       computation.matrices[a.matrix_index];
   KALDI_ASSERT(a_mat.num_rows == b.num_rows && a_mat.num_cols == b.num_cols);
   NnetComputation::SubMatrixInfo ans;
   ans.matrix_index = b.matrix_index;
   ans.row_offset = a.row_offset + b.row_offset;
   ans.num_rows = a.num_rows;
   ans.col_offset = a.col_offset + b.col_offset;
   ans.num_cols = a.num_cols;
   return ans;
 }
bool HasContiguousProperty (const std::vector< int32 > & indexes, std::vector< std::pair< int32, int32 > > * reverse_indexes)
This function returns true if for each integer i != -1, all the indexes j at which indexes[j] == i are consecutive with no gaps (more formally: if j1 < j2 < j3 and indexes[j1] != -1 and indexes[j1] == indexes[j3], then indexes[j1] == indexes[j2]).
For example, the vector [ 1 2 1 ] lacks the contiguous property because 1 appears in two places with a different number in the middle. If the vector has the contiguous property, this function also outputs to "reverse_indexes" the begin and end of these ranges, so that indexes[j] == i for all j such that (*reverse_indexes)[i].first <= j && j < (*reverse_indexes)[i].second.
Definition at line 523 of file nnet-compile-utils.cc.
References rnnlm::i, rnnlm::j, KALDI_ASSERT, and KALDI_WARN.
Referenced by Compiler::DoBackwardComputationFromIndexes(), UnitTestEnsureContiguousProperty(), and UnitTestHasContiguousProperty().
{
   reverse_indexes->clear();
   int32 num_indexes = indexes.size();
   if (num_indexes == 0)
     return true;
   int32 num_input_indexes =
       *std::max_element(indexes.begin(), indexes.end()) + 1;
   KALDI_ASSERT(num_input_indexes >= 0);
   if (num_input_indexes == 0) {
     // we don't really expect this input, filled with -1's.
     KALDI_WARN << "HasContiguousProperty called on vector of -1's.";
     return true;
   }
   reverse_indexes->resize(num_input_indexes,
                           std::pair<int32,int32>(-1, -1));
   // set each pair's "first" to the min index of all elements
   // of "indexes" with that value, and the "second" to the
   // max plus one.
   for (int32 i = 0; i < num_indexes; i++) {
     int32 j = indexes[i];
     if (j == -1) continue;
     KALDI_ASSERT(j >= 0);
     std::pair<int32, int32> &pair = (*reverse_indexes)[j];
     if (pair.first == -1) {
       pair.first = i;
       pair.second = i + 1;
     } else {
       pair.first = std::min(pair.first, i);
       pair.second = std::max(pair.second, i + 1);
     }
   }
   // check that the contiguous property holds.
   for (int32 i = 0; i < num_input_indexes; i++) {
     std::pair<int32, int32> pair = (*reverse_indexes)[i];
     if (pair.first != -1) {
       for (int32 j = pair.first; j < pair.second; j++)
         if (indexes[j] != i)
           return false;
     }
   }
   return true;
 }
void IdentifyIndexesArgs (std::vector< NnetComputation::Command > * commands, std::vector< int32 * > * indexes_args)
Identifies in the vector of commands, arguments that correspond to indexes into the computation's 'indexes' array, and outputs a list of pointers to those arguments to 'indexes_args'.
Useful in renumbering code.
Definition at line 155 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg3, NnetComputation::Command::command_type, kAddRows, and kCopyRows.
Referenced by ComputationRenumberer::RenumberIndexes().
{
   indexes_args->clear();
   std::vector<NnetComputation::Command>::iterator iter = commands->begin(),
       end = commands->end();
   for (; iter != end; ++iter) {
     NnetComputation::Command &command = *iter;
     if (command.command_type == kCopyRows ||
         command.command_type == kAddRows)
       indexes_args->push_back(&(command.arg3));
   }
 }
void IdentifyIndexesMultiArgs (std::vector< NnetComputation::Command > * commands, std::vector< int32 * > * indexes_multi_args)
Identifies in the vector of commands, arguments that correspond to indexes into the computation's indexes_multi array, and outputs a list of pointers to those arguments to 'indexes_multi_args'.
Useful in renumbering code.
Definition at line 127 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg2, NnetComputation::Command::command_type, kAddRowsMulti, kAddToRowsMulti, kCopyRowsMulti, and kCopyToRowsMulti.
Referenced by ComputationRenumberer::RemoveIndexesMultiDuplicates(), and ComputationRenumberer::RemoveUnusedIndexesMulti().
{
   indexes_multi_args->clear();
   std::vector<NnetComputation::Command>::iterator iter = commands->begin(),
       end = commands->end();
   for (; iter != end; ++iter) {
     NnetComputation::Command &command = *iter;
     if (command.command_type == kAddRowsMulti ||
         command.command_type == kAddToRowsMulti ||
         command.command_type == kCopyRowsMulti ||
         command.command_type == kCopyToRowsMulti)
       indexes_multi_args->push_back(&(command.arg2));
   }
 }
void IdentifyIndexesRangesArgs (std::vector< NnetComputation::Command > * commands, std::vector< int32 * > * indexes_ranges_args)
Identifies in the vector of commands, arguments that correspond to indexes into the computation's 'indexes_ranges' array, and outputs a list of pointers to those arguments to 'indexes_ranges_args'.
Useful in renumbering code.
Definition at line 143 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg3, NnetComputation::Command::command_type, and kAddRowRanges.
Referenced by ComputationRenumberer::RenumberIndexesRanges().
{
   indexes_ranges_args->clear();
   std::vector<NnetComputation::Command>::iterator iter = commands->begin(),
       end = commands->end();
   for (; iter != end; ++iter) {
     NnetComputation::Command &command = *iter;
     if (command.command_type == kAddRowRanges)
       indexes_ranges_args->push_back(&(command.arg3));
   }
 }
void IdentifyMatrixArgs (std::vector< NnetComputation::Command > * command, std::vector< int32 * > * matrix_args)
This function outputs to "matrix_args" the addresses of a subset of the arguments arg1 through arg6 in commands in "commands", that correspond to the indexes of matrices.
This is useful in renumbering code. (Note: only a few types of command use matrix indexes).
Definition at line 90 of file nnet-optimize-utils.cc.
Referenced by IdentifyMatrixArgsInComputation().
{
   matrix_args->clear();
   std::vector<NnetComputation::Command>::iterator iter = commands->begin(),
       end = commands->end();
   std::vector<int32*> this_matrix_args;
   for (; iter != end; ++iter) {
     IdentifyMatrixArgs(&(*iter), &this_matrix_args);
     matrix_args->insert(matrix_args->end(),
                         this_matrix_args.begin(),
                         this_matrix_args.end());
   }
 }
void IdentifyMatrixArgs (NnetComputation::Command * command, std::vector< int32 * > * matrix_args)
This function outputs to "matrix_args" the addresses of a subset of the arguments arg1 through arg6 in "command", that correspond to the indexes of matrices.
This is useful in renumbering code. (Note: only a few types of command use matrix indexes).
Definition at line 170 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::command_type, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed, kAllocMatrixUndefined, kAllocMatrixZeroed, and kDeallocMatrix.
{
   matrix_args->clear();
   switch (c->command_type) {
     case kAllocMatrixZeroed:
     case kAllocMatrixUndefined:
     case kDeallocMatrix:
       matrix_args->push_back(&c->arg1);
       break;
     case kAllocMatrixFromOther:
     case kAllocMatrixFromOtherZeroed:
       matrix_args->push_back(&c->arg1);
       matrix_args->push_back(&c->arg2);
       break;
     default:
       break;
   }
 }
void IdentifyMatrixArgsInComputation (bool include_from_submatrices, NnetComputation * computation, std::vector< int32 * > * matrix_args)
This function outputs to "matrix_args" the addresses of indexes inside 'computation' that correspond to matrices.
These live inside computation->commands and computation->input_output_info; and if 'include_from_submatrices' is true, then the matrix-indexes present in computation->submatrices[*].matrix_index will be included too. Zeros may be present if there were optional arguments; we do include pointers to them, but you can just ignore them.
Definition at line 105 of file nnet-optimize-utils.cc.
References NnetComputation::commands, IdentifyMatrixArgs(), NnetComputation::input_output_info, and NnetComputation::submatrices.
Referenced by ComputationRenumberer::ComputeMatrixIsUsed(), and ComputationRenumberer::RenumberMatrices().
{
   IdentifyMatrixArgs(&(computation->commands), matrix_args);
   int32 num_submatrices = computation->submatrices.size();
   matrix_args->reserve(matrix_args->size() +
                        (include_in_submatrices ?
                         computation->submatrices.size() : 0) +
                        2 * computation->input_output_info.size());
   if (include_in_submatrices)
     for (int32 s = 1; s < num_submatrices; s++)
       matrix_args->push_back(&(computation->submatrices[s].matrix_index));
   unordered_map<int32, std::pair<int32, int32> >::iterator
       iter = computation->input_output_info.begin(),
       end = computation->input_output_info.end();
   for (; iter != end; ++iter) {
     matrix_args->push_back(&(iter->second.first));
     matrix_args->push_back(&(iter->second.second));
   }
 }
void IdentifySubmatrixArgs (NnetComputation::Command * command, std::vector< int32 * > * submatrix_args)
This function outputs to "submatrix_args" the addresses of a subset of arguments arg1 through arg6 in "command", that correspond to the indexes of submatrices.
This is useful in renumbering code. Note: some of the pointers may point to a zero value, for optional submatrix args.
Definition at line 29 of file nnet-optimize-utils.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::arg3, NnetComputation::Command::arg4, NnetComputation::Command::arg5, NnetComputation::Command::arg6, NnetComputation::Command::command_type, kAddRowRanges, kAddRows, kAddRowsMulti, kAddToRowsMulti, KALDI_ERR, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed, kAllocMatrixUndefined, kAllocMatrixZeroed, kBackprop, kBackpropNoModelUpdate, kCopyRows, kCopyRowsMulti, kCopyToRowsMulti, kDeallocMatrix, kMatrixAdd, kMatrixCopy, kNoOperation, kNoOperationMarker, kPropagate, and kStoreStats.
Referenced by IdentifySubmatrixArgs(), and IdentifySubmatrixArgsInComputation().
{
   submatrix_args->clear();
   switch (c->command_type) {
     case kAllocMatrixZeroed:
     case kAllocMatrixUndefined:
     case kDeallocMatrix:
     case kAllocMatrixFromOther:
     case kAllocMatrixFromOtherZeroed:
       break;
     case kPropagate:
       submatrix_args->push_back(&c->arg3);
       submatrix_args->push_back(&c->arg4);
       break;
     case kStoreStats:
       submatrix_args->push_back(&c->arg2);
       break;
     case kBackprop:
     case kBackpropNoModelUpdate:
       submatrix_args->push_back(&c->arg3);
       submatrix_args->push_back(&c->arg4);
       submatrix_args->push_back(&c->arg5);
       submatrix_args->push_back(&c->arg6);
       break;
     case kMatrixCopy:
     case kMatrixAdd:
     case kAddRows:
     case kCopyRows:
     case kAddRowRanges:
       submatrix_args->push_back(&c->arg1);
       submatrix_args->push_back(&c->arg2);
       break;
     case kAddRowsMulti:
     case kCopyRowsMulti:
     case kAddToRowsMulti:
     case kCopyToRowsMulti:
       submatrix_args->push_back(&c->arg1);
       break;
     case kNoOperation:
     case kNoOperationMarker:
       break;
     default:
       KALDI_ERR << "Unknown command type.";
   }
 }
void IdentifySubmatrixArgs (std::vector< NnetComputation::Command > * commands, std::vector< int32 * > * submatrix_args)
This function outputs to "submatrix_args" the addresses of the args (arguments arg1 through arg6) in the vector "commands", that correspond to the indexes of submatrices.
This is useful in renumbering code. Note: some of the pointers may point to a zero value, for optional submatrix args.
Definition at line 75 of file nnet-optimize-utils.cc.
References IdentifySubmatrixArgs().
{
   submatrix_args->clear();
   std::vector<NnetComputation::Command>::iterator iter = commands->begin(),
       end = commands->end();
   std::vector<int32*> this_submatrix_args;
   for (; iter != end; ++iter) {
     IdentifySubmatrixArgs(&(*iter), &this_submatrix_args);
     submatrix_args->insert(submatrix_args->end(),
                            this_submatrix_args.begin(),
                            this_submatrix_args.end());
   }
 }
void IdentifySubmatrixArgsInComputation (NnetComputation * computation, std::vector< int32 * > * submatrix_args)
This function outputs to "submatrix_args" the addresses of integers in 'computation' that correspond to submatrices.
These may be present in 'commands', and in 'indexes_multi'. This is useful in renumbering code. Note: some of the pointers may point to a zero value, for optional submatrix args in commands, but for efficiency we don't provide pointers for the -1's in 'indexes_multi'.
Definition at line 230 of file nnet-optimize-utils.cc.
References NnetComputation::commands, rnnlm::i, IdentifySubmatrixArgs(), and NnetComputation::indexes_multi.
Referenced by ComputationRenumberer::ComputeSubmatrixIsUsed(), and ComputationRenumberer::RenumberSubmatrices().
{
   IdentifySubmatrixArgs(&(computation->commands), submatrix_args);
   size_t extra_size = 0;
   for (size_t i = 0; i < computation->indexes_multi.size(); i++)
     extra_size += computation->indexes_multi[i].size();
   submatrix_args->reserve(submatrix_args->size() + extra_size);
   for (size_t i = 0; i < computation->indexes_multi.size(); i++) {
     std::vector<std::pair<int32, int32> > &indexes_multi =
         computation->indexes_multi[i];
     std::vector<std::pair<int32, int32> >::iterator
         iter = indexes_multi.begin(), end = indexes_multi.end();
     for (; iter != end; ++iter)
       if (iter->first != -1)
         submatrix_args->push_back(&(iter->first));
   }
 }
static void kaldi::nnet3::IndexesMultiToSubmatrixIndexes (const std::vector< std::pair< int32, int32 > > & indexes_multi, std::vector< int32 > * submatrix_indexes) static
given a vector of pairs from computation.indexes_multi_indexes containing paris (submatrix-index, row-index), this function outputs to "submatrix_indexes" all (unique) submatrix indexes that appear; and it outputs to "contains_null_marker" true if the pair (-1, -1) appears anywhere in indexes_multi, and false otherwise.
Definition at line 247 of file nnet-analyze.cc.
References kaldi::SortAndUniq().
Referenced by ComputeCommandAttributes().
{
   submatrix_indexes->clear();
   std::vector<std::pair<int32, int32> >::const_iterator
       iter = indexes_multi.begin(), end = indexes_multi.end();
   int32 cur_submatrix_index = -1; // an optimization.
   for (; iter != end; ++iter) {
     int32 submatrix_index = iter->first;
     if (submatrix_index != -1 && submatrix_index != cur_submatrix_index) {
       cur_submatrix_index = submatrix_index;
       submatrix_indexes->push_back(submatrix_index);
     }
   }
   SortAndUniq(submatrix_indexes);
 }
bool IsSimpleNnet (const Nnet & nnet)
This function returns true if the nnet has the following properties: It has one output, called "output".
It has an input called "input", and possibly an extra input called "ivector", but no other inputs. There are probably some other properties that we really ought to be checking, and we may add more later on.
Definition at line 42 of file nnet-utils.cc.
References Nnet::GetNodeIndex(), Nnet::IsInputNode(), Nnet::IsOutputNode(), NumInputNodes(), and NumOutputNodes().
Referenced by ComputeExampleComputationRequestSimple(), ComputeSimpleNnetContext(), NnetDecodableBase::NnetDecodableBase(), NnetInfo(), and AmNnetSimple::SetContext().
{
   // check that we have just one output node and it is
   // called "output".
   if (NumOutputNodes(nnet) != 1 ||
       nnet.GetNodeIndex("output") == -1 ||
       !nnet.IsOutputNode(nnet.GetNodeIndex("output")))
     return false;
   // check that there is an input node named "input".
   if (nnet.GetNodeIndex("input") == -1 ||
       !nnet.IsInputNode(nnet.GetNodeIndex("input")))
     return false;
   // if there was just one input, then it was named
   // "input" and everything checks out.
   if (NumInputNodes(nnet) == 1)
     return true;
   // Otherwise, there should be 2 inputs and one
   // should be called "ivector".
   return NumInputNodes(nnet) == 2 &&
       nnet.GetNodeIndex("ivector") != -1 &&
       nnet.IsInputNode(nnet.GetNodeIndex("ivector"));
 }
bool IsValidName (const std::string & name)
Returns true if 'name' would be a valid name for a component or node in a Nnet.
This is a nonempty string beginning with A-Za-z_, and containing only -_A-Za-z0-9.
Definition at line 403 of file nnet-parse.cc.
References rnnlm::i.
Referenced by DescriptorTokenize(), ConfigLine::ParseLine(), Nnet::RemoveRedundantConfigLines(), and SimpleForwardingDescriptor::WriteConfig().
{
   if (name.size() == 0) return false;
   for (size_t i = 0; i < name.size(); i++) {
     if (i == 0 && !isalpha(name[i]) && name[i] != '_')
       return false;
     if (!isalnum(name[i]) && name[i] != '_' && name[i] != '-')
       return false;
   }
   return true;
 }
BaseFloat kaldi::nnet3::KlDivergence (const Vector< BaseFloat > & p, const Vector< BaseFloat > & q)
Definition at line 31 of file nnet3-am-adjust-priors.cc.
References VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, KALDI_WARN, kaldi::Log(), and VectorBase< Real >::Sum().
Referenced by PrintPriorDiagnostics().
{
   BaseFloat sum_p = p.Sum(), sum_q = q.Sum();
   if (fabs(sum_p - 1.0) > 0.01 || fabs(sum_q - 1.0) > 0.01) {
     KALDI_WARN << "KlDivergence: vectors are not close to being normalized "
                << sum_p << ", " << sum_q;
   }
   KALDI_ASSERT(p.Dim() == q.Dim());
   double ans = 0.0;
   for (int32 i = 0; i < p.Dim(); i++) {
     BaseFloat p_prob = p(i) / sum_p, q_prob = q(i) / sum_q;
     ans += p_prob * Log(p_prob / q_prob);
   }
   return ans;
 }
void kaldi::nnet3::LimitDerivativeTimes (const Nnet & nnet, const ComputationRequest & request, const NnetOptimizeOptions & opts, NnetComputation * computation)
This optimization, which has no effect unless you set –min-deriv-time or –max-deriv-time, modifies the backprop operations for efficiency based on the assumption that derivatives for any Cindex with t < min_deriv_time or t > max_deriv_time are zero.
(this is based on the fact that derivatives in recurrent setups will either decay to zero over time, or will explode and anyway become meaningless). This is only applied if you are not comoputing any input-derivatives). The assumption, for simple Components, is that backprop operations are no-ops as long as the input was zeroed, because the back-propagated derivatives would be zero and the model would not be updated.
The most important effect of this operation is to modify some operations of type kBackprop and kBackpropNoModelUpdate for simple Components, to either make them operate on row ranges of their original input (which in general will be newly created submatrices), or to remove them altogether if they do not operate on any 't' values within the correct range.
We assert as a requirement of this optimization that all allocation commands must zero their matrices (this effectively means that you cannot apply this optimization after RemoveUnnecessaryZeroing()). This means that we don't have to worry about leaving things undefined after removing backprop operations. We also assert that backprop commands that set instead of adding to their input, must not be outputting to things that were previously set to nonzero values. (this shouldn't ever be a problem, but we do check.
Note: after this optimization it will likely be beneficial to call RemoveUnnecessaryOperations to remove operations not of type kBackprop that have now become unnecessary– e.g. operations that do the backprop through Descriptors.
void LimitDerivativeTimes (const Nnet & nnet, int32 min_deriv_time, int32 max_deriv_time, NnetComputation * computation)
Definition at line 1805 of file nnet-optimize-utils.cc.
References DerivativeTimeLimiter::LimitDerivTimes().
Referenced by Optimize().
{
   DerivativeTimeLimiter limiter(nnet, min_deriv_time, max_deriv_time,
                                 computation);
   limiter.LimitDerivTimes();
 }
void MakeSccGraph (const std::vector< std::vector< int32 > > & graph, const std::vector< std::vector< int32 > > & sccs, std::vector< std::vector< int32 > > * scc_graph)
Given a list of sccs of a graph (e.g.
as computed by FindSccs), compute a directed graph on the sccs. Of course this directed graph will be acyclic.
Definition at line 164 of file nnet-graph.cc.
References rnnlm::i, rnnlm::j, KALDI_ASSERT, and kaldi::SortAndUniq().
Referenced by ComputeNnetComputationEpochs(), and UnitTestMakeSccGraph().
{
   KALDI_ASSERT(scc_graph != NULL);
   scc_graph->clear();
   scc_graph->resize(sccs.size());
   // Hash map from node to SCC index.
   std::vector<int32> node_to_scc_index(graph.size());
   for (int32 i = 0; i < sccs.size(); ++i) {
     for (int32 j = 0; j < sccs[i].size(); ++j) {
       KALDI_ASSERT(sccs[i][j] >= 0 && sccs[i][j] < graph.size());
       node_to_scc_index[sccs[i][j]] = i;
     }
   }
   // Builds graph.
   for (int32 i = 0; i < sccs.size(); ++i) {
     for (int32 j = 0; j < sccs[i].size(); ++j) {
       int32 node = sccs[i][j];
       KALDI_ASSERT(node >= 0 && node < graph.size());
       for (int32 k = 0; k < graph[node].size(); ++k) {
         if (node_to_scc_index[graph[node][k]] != i) { // Exclucding self.
           (*scc_graph)[i].push_back(node_to_scc_index[graph[node][k]]);
         }
       }
     }
     // If necessary, we can use a hash maps to avoid this sorting.
     SortAndUniq(&((*scc_graph)[i]));
   }
 }
int32 kaldi::nnet3::MaxMemoryUsage (const NnetComputation & computation)
Returns the total memory, in bytes, used by the computation (just the temporary memory, not counting the memory used by the nnet itself).
This is defined as the maximum amount of memory used at any one instant.
void MergeExamples (const std::vector< NnetExample > & src, bool compress, NnetExample * dest)
Merge a set of input examples into a single example (typically the size of "src" will be the minibatch size).
Will crash if "src" is the empty vector. If "compress" is true, it will compress any non-sparse features in the output.
Definition at line 147 of file nnet-example-utils.cc.
References GetIoNames(), GetIoSizes(), KALDI_ASSERT, and MergeIo().
Referenced by main(), and UnitTestNnetMergeExamples().
{
   KALDI_ASSERT(!src.empty());
   std::vector<std::string> io_names;
   GetIoNames(src, &io_names);
   // the sizes are the total number of Indexes we have across all examples.
   std::vector<int32> io_sizes;
   GetIoSizes(src, io_names, &io_sizes);
   MergeIo(src, io_names, io_sizes, compress, merged_eg);
 }
static void kaldi::nnet3::MergeIo (const std::vector< NnetExample > & src, const std::vector< std::string > & names, const std::vector< int32 > & sizes, bool compress, NnetExample * merged_eg) static
Definition at line 85 of file nnet-example-utils.cc.
References kaldi::AppendGeneralMatrixRows(), NnetIo::features, rnnlm::i, NnetIo::indexes, NnetExample::io, KALDI_ASSERT, rnnlm::n, and NnetIo::name.
Referenced by MergeExamples().
{
   int32 num_feats = names.size();
   std::vector<int32> cur_size(num_feats, 0);
   std::vector<std::vector<GeneralMatrix const*> > output_lists(num_feats);
   merged_eg->io.clear();
   merged_eg->io.resize(num_feats);
   for (int32 f = 0; f < num_feats; f++) {
     NnetIo &io = merged_eg->io[f];
     int32 size = sizes[f];
     KALDI_ASSERT(size > 0);
     io.name = names[f];
     io.indexes.resize(size);
   }
   std::vector<std::string>::const_iterator names_begin = names.begin(),
                                              names_end = names.end();
   std::vector<NnetExample>::const_iterator iter = src.begin(), end = src.end();
   for (int32 n = 0; iter != end; ++iter,++n) {
     std::vector<NnetIo>::const_iterator iter2 = iter->io.begin(),
                                          end2 = iter->io.end();
     for (; iter2 != end2; ++iter2) {
       const NnetIo &io = *iter2;
       std::vector<std::string>::const_iterator names_iter =
           std::lower_bound(names_begin, names_end, io.name);
       KALDI_ASSERT(*names_iter == io.name);
       int32 f = names_iter - names_begin;
       int32 this_size = io.indexes.size(),
           &this_offset = cur_size[f];
       KALDI_ASSERT(this_size + this_offset <= sizes[f]);
       output_lists[f].push_back(&(io.features));
       NnetIo &output_io = merged_eg->io[f];
       std::copy(io.indexes.begin(), io.indexes.end(),
                 output_io.indexes.begin() + this_offset);
       std::vector<Index>::iterator output_iter = output_io.indexes.begin();
       // Set the n index to be different for each of the original examples.
       for (int32 i = this_offset; i < this_offset + this_size; i++) {
         // we could easily support merging already-merged egs, but I don't see a
         // need for it right now.
         KALDI_ASSERT(output_iter[i].n == 0 &&
                      "Merging already-merged egs?  Not currentlysupported.");
         output_iter[i].n = n;
       }
       this_offset += this_size;  // note: this_offset is a reference.
     }
   }
   KALDI_ASSERT(cur_size == sizes);
   for (int32 f = 0; f < num_feats; f++) {
     AppendGeneralMatrixRows(output_lists[f],
                             &(merged_eg->io[f].features));
     if (compress) {
       // the following won't do anything if the features were sparse.
       merged_eg->io[f].features.Compress();
     }
   }
 }
void MoveSizingCommands (const Nnet & nnet, NnetComputation * computation)
This optimization moves commands that initialize matrices to as late as possible, and commands that empty matrices to as early as possible.
Definition at line 28 of file nnet-optimize.cc.
References MatrixAccesses::accesses, MatrixAccesses::allocate_command, NnetComputation::commands, ComputeCommandAttributes(), ComputeMatrixAccesses(), ComputeVariableAccesses(), MatrixAccesses::deallocate_command, ComputationVariables::Init(), and KALDI_ASSERT.
Referenced by Optimize().
{
   ComputationVariables variables;
   variables.Init(*computation);
   std::vector<CommandAttributes> attributes;
   ComputeCommandAttributes(nnet, *computation, variables, &attributes);
   std::vector<std::vector<Access> > variable_accesses;
   ComputeVariableAccesses(variables, attributes, &variable_accesses);
   std::vector<MatrixAccesses> matrix_accesses;
   ComputeMatrixAccesses(nnet, *computation, variables, attributes,
                         &matrix_accesses);
   // The way we will renumber the commands is, we will first set this vector up
   // with pairs (command-index * 3, pointer-to-command), and we will then modify
   // the command-indexes in this vector to the numbers that we want, and sort
   // it.  The reason for the * 3 is so that we can number commands "just-after"
   // existing indexes (by adding 1) and "just-before" (by subtracting 1).
   int32 num_commands = computation->commands.size(),
       num_matrices = matrix_accesses.size();
   std::vector<std::pair<int32,NnetComputation::Command*> >
       commands(num_commands);
   for (int32 c = 0; c < num_commands; c++) {
     commands[c].first = c * 3;
     commands[c].second = &(computation->commands[c]);
   }
   for (int32 m = 1; m < num_matrices; m++) {
     const MatrixAccesses &ma = matrix_accesses[m];
     if (ma.allocate_command != -1) {
       // first_access_command will be index of first non-initializing access.
       int32 first_access_command = -1;
       if (!ma.accesses.empty()) {
         first_access_command = ma.accesses[0].command_index;
         if (first_access_command == ma.allocate_command) {
           if (ma.accesses.size() > 1)
             first_access_command = ma.accesses[1].command_index;
           else
             first_access_command = -1;
         }
       }
       if (first_access_command != -1) {
         KALDI_ASSERT(first_access_command > ma.allocate_command);
         // move the initialization command to just before the first access.
         commands[ma.allocate_command].first = first_access_command * 3 - 1;
       }
     }
     if (ma.deallocate_command != -1) {
       if (!ma.accesses.empty()) {
         int32 last_access_command = ma.accesses.back().command_index;
         // move the destruction command to just after the last access.
         commands[ma.deallocate_command].first = last_access_command * 3 + 1;
       }
     }
   }
   std::sort(commands.begin(), commands.end());
   std::vector<NnetComputation::Command> reordered_commands(num_commands);
   for (int32 c = 0; c < num_commands; c++)
     reordered_commands[c] = *(commands[c].second);
   computation->commands = reordered_commands;
 }
std::string NnetInfo (const Nnet & nnet)
This function returns various info about the neural net.
If the nnet satisfied IsSimpleNnet(nnet), the info includes "left-context=5\nright-context=3\n...". The info includes the output of nnet.Info(). This is modeled after the info that AmNnetSimple returns in its Info() function (we need this in the CTC code).
Definition at line 362 of file nnet-utils.cc.
References ComputeSimpleNnetContext(), Nnet::Info(), Nnet::InputDim(), IsSimpleNnet(), and Nnet::OutputDim().
Referenced by UnitTestNnetContext().
{
   std::ostringstream ostr;
   if (IsSimpleNnet(nnet)) {
     int32 left_context, right_context;
     // this call will crash if the nnet is not 'simple'.
     ComputeSimpleNnetContext(nnet, &left_context, &right_context);
     ostr << "left-context: " << left_context << "\n";
     ostr << "right-context: " << right_context << "\n";
   }
   ostr << "input-dim: " << nnet.InputDim("input") << "\n";
   ostr << "ivector-dim: " << nnet.InputDim("ivector") << "\n";
   ostr << "output-dim: " << nnet.OutputDim("output") << "\n";
   ostr << "# Nnet info follows.\n";
   ostr << nnet.Info();
   return ostr.str();
 }
bool NnetParametersAreIdentical (const Nnet & nnet1, const Nnet & nnet2, BaseFloat threshold)
Used for testing that the updatable parameters in two networks are the same.
May crash if structure differs. Prints warning and returns false if parameters differ. E.g. set threshold to 1.0e-05 (it's a relative threshold, applied per component).
Definition at line 1124 of file nnet-test-utils.cc.
References UpdatableComponent::DotProduct(), Nnet::GetComponent(), Nnet::GetComponentName(), KALDI_ASSERT, KALDI_WARN, kUpdatableComponent, Nnet::NumComponents(), Component::Properties(), and Component::Type().
Referenced by UnitTestNnetOptimizeWithOptions().
{
   KALDI_ASSERT(nnet1.NumComponents() == nnet2.NumComponents());
   int32 num_components = nnet1.NumComponents();
   for (int32 c = 0; c < num_components; c++) {
     const Component *c1 = nnet1.GetComponent(c),
                     *c2 = nnet2.GetComponent(c);
     KALDI_ASSERT(c1->Type() == c2->Type());
     if (c1->Properties() & kUpdatableComponent) {
       const UpdatableComponent *u1 = dynamic_cast<const UpdatableComponent*>(c1),
                                *u2 = dynamic_cast<const UpdatableComponent*>(c2);
       KALDI_ASSERT(u1 != NULL && u2 != NULL);
       BaseFloat prod11 = u1->DotProduct(*u1), prod12 = u1->DotProduct(*u2),
                 prod21 = u2->DotProduct(*u1), prod22 = u2->DotProduct(*u2);
       BaseFloat max_prod = std::max(std::max(prod11, prod12),
                                     std::max(prod21, prod22)),
                 min_prod = std::min(std::min(prod11, prod12),
                                     std::min(prod21, prod22));
       if (max_prod - min_prod > threshold * max_prod) {
         KALDI_WARN << "Component '" << nnet1.GetComponentName(c)
                    << "' differs in nnet1 versus nnet2: prod(11,12,21,22) = "
                    << prod11 << ',' << prod12 << ',' << prod21 << ',' << prod22;
         return false;
       }
     }
   }
   return true;
 }
void NnetToDirectedGraph (const Nnet & nnet, std::vector< std::vector< int32 > > * graph)
This function takes an nnet and turns it to a directed graph on nodes.
The nodes will be numbered from 0 to graph->size() - 1, where graph->size() == nnet.NumNodes(). For each node-index n, the vector in (*graph)[n] will contain a list of all the nodes that have a direct dependency on node n (in order to compute them). For instance, if n is an input node, (*graph)[n] will be the empty list because it won't depend on anything.
Definition at line 30 of file nnet-graph.cc.
References NetworkNode::descriptor, Nnet::GetNode(), Descriptor::GetNodeDependencies(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, kComponent, kDescriptor, kDimRange, kInput, rnnlm::n, NetworkNode::node_index, NetworkNode::node_type, Nnet::NumNodes(), kaldi::SortAndUniq(), and NetworkNode::u.
Referenced by ComputeNnetComputationEpochs().
{
   graph->clear();
   int32 num_nodes = nnet.NumNodes();
   graph->resize(num_nodes);
   for (int32 n = 0; n < num_nodes; n++) {
     const NetworkNode &node = nnet.GetNode(n);
     // handle dependencies of this node.
     std::vector<int32> node_dependencies;
     switch (node.node_type) {
       case kInput:
         break;  // no node dependencies.
       case kDescriptor:
         node.descriptor.GetNodeDependencies(&node_dependencies);
         break;
       case kComponent:
         node_dependencies.push_back(n - 1);
         break;
       case kDimRange:
         node_dependencies.push_back(node.u.node_index);
         break;
       default:
         KALDI_ERR << "Invalid node type";
     }
     SortAndUniq(&node_dependencies);
     for (size_t i = 0; i < node_dependencies.size(); i++) {
       int32 dep_n = node_dependencies[i];
       KALDI_ASSERT(dep_n >= 0 && dep_n < num_nodes);
       (*graph)[dep_n].push_back(n);
     }
   }
 }
std::string kaldi::nnet3::NormalizeTextDescriptor (const std::vector< std::string > & node_names, const std::string & desc_str)
Definition at line 179 of file nnet-descriptor-test.cc.
References GeneralDescriptor::ConvertToDescriptor(), DescriptorTokenize(), KALDI_ERR, KALDI_LOG, GeneralDescriptor::Parse(), and Descriptor::WriteConfig().
Referenced by UnitTestGeneralDescriptorSpecial().
{
   std::vector<std::string> tokens;
   DescriptorTokenize(desc_str, &tokens);
   tokens.push_back("end of input");
   const std::string *next_token = &(tokens[0]);
   GeneralDescriptor *gen_desc = GeneralDescriptor::Parse(node_names,
                                                          &next_token);
   if (*next_token != "end of input")
     KALDI_ERR << "Parsing Descriptor, expected end of input but got "
               << "'" <<  *next_token << "'";
   Descriptor *desc = gen_desc->ConvertToDescriptor();
   std::ostringstream ostr;
   desc->WriteConfig(ostr, node_names);
   delete gen_desc;
   delete desc;
   KALDI_LOG << "Result of normalizing " << desc_str << " is: " << ostr.str();
   return ostr.str();
 }
int32 NumInputNodes (const Nnet & nnet)
returns the number of input nodes of this nnet.
Definition at line 33 of file nnet-utils.cc.
References Nnet::IsInputNode(), rnnlm::n, and Nnet::NumNodes().
Referenced by IsSimpleNnet().
{
   int32 ans = 0;
   for (int32 n = 0; n < nnet.NumNodes(); n++)
     if (nnet.IsInputNode(n))
       ans++;
   return ans;
 }
int32 kaldi::nnet3::NumOutputIndexes (const NnetExample & eg)
Definition at line 31 of file nnet3-merge-egs.cc.
References rnnlm::i, NnetExample::io, and KALDI_ERR.
Referenced by main().
{
   for (size_t i = 0; i < eg.io.size(); i++)
     if (eg.io[i].name == "output")
       return eg.io[i].indexes.size();
   KALDI_ERR << "No output named 'output' in the eg.";
   return 0;  // Suppress compiler warning.
 }
int32 NumOutputNodes (const Nnet & nnet)
returns the number of output nodes of this nnet.
Definition at line 25 of file nnet-utils.cc.
References Nnet::IsOutputNode(), rnnlm::n, and Nnet::NumNodes().
Referenced by IsSimpleNnet().
{
   int32 ans = 0;
   for (int32 n = 0; n < nnet.NumNodes(); n++)
     if (nnet.IsOutputNode(n))
       ans++;
   return ans;
 }
int32 NumParameters (const Nnet & src)
Returns the total of the number of parameters in the updatable components of the nnet.
Definition at line 289 of file nnet-utils.cc.
References Nnet::GetComponent(), KALDI_ERR, kUpdatableComponent, Nnet::NumComponents(), UpdatableComponent::NumParameters(), and Component::Properties().
Referenced by Nnet::Info(), main(), UnVectorizeNnet(), and VectorizeNnet().
{
   int32 ans = 0;
   for (int32 c = 0; c < src.NumComponents(); c++) {
     const Component *comp = src.GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       // For now all updatable components inherit from class UpdatableComponent.
       // If that changes in future, we will change this code.
       const UpdatableComponent *uc =
           dynamic_cast<const UpdatableComponent*>(comp);
       if (uc == NULL)
         KALDI_ERR << "Updatable component does not inherit from class "
             "UpdatableComponent; change this code.";
       ans += uc->NumParameters();
     }
   }
   return ans;
 }
int32 NumUpdatableComponents (const Nnet & dest)
Returns the number of updatable components in the nnet.
Definition at line 352 of file nnet-utils.cc.
References Nnet::GetComponent(), kUpdatableComponent, Nnet::NumComponents(), and Component::Properties().
Referenced by kaldi::nnet2::CombineNnets(), FastNnetCombiner::CombineNnets(), kaldi::nnet2::CombineNnetsA(), FastNnetCombiner::ComputeCurrentNnet(), kaldi::nnet2::GetUpdateDirection(), main(), and PrintVectorPerUpdatableComponent().
{
   int32 ans = 0;
   for (int32 c = 0; c < dest.NumComponents(); c++) {
       const Component *comp = dest.GetComponent(c);
     if (comp->Properties() & kUpdatableComponent)
       ans++;
   }
   return ans;
 }
std::ostream & operator<< (std::ostream & ostream, const Index & index)
Definition at line 172 of file nnet-common.cc.
References Index::n, Index::t, and Index::x.
{
   return ostream << '(' << index.n << ' ' << index.t << ' ' << index.x << ')';
 }
std::ostream & operator<< (std::ostream & ostream, const Cindex & cindex)
Definition at line 176 of file nnet-common.cc.
{
   return ostream << '(' << cindex.first << ' ' << cindex.second << ')';
 }
std::ostream & operator<< (std::ostream & os, const ComputationGraphBuilder::ComputableInfo & info)
This is to be used in logging only.
Definition at line 292 of file nnet-computation-graph.cc.
References ComputationGraphBuilder::kComputable, ComputationGraphBuilder::kNotComputable, ComputationGraphBuilder::kUnknown, and ComputationGraphBuilder::kWillNotCompute.
{
   switch (info) {
     case ComputationGraphBuilder::kUnknown: os << "kUnknown";
       break;
     case ComputationGraphBuilder::kComputable: os << "kComputable";
       break;
     case ComputationGraphBuilder::kNotComputable: os << "kNotComputable";
       break;
     case ComputationGraphBuilder::kWillNotCompute: os << "kWillNotCompute";
       break;
     default: os << "[invalid enum value]"; break;
   }
   return os;
 }
std::ostream& kaldi::nnet3::operator<< (std::ostream & os, NnetComputation & computation)
void Optimize (const NnetOptimizeOptions & config, const Nnet & nnet, const ComputationRequest & request, NnetComputation * computation)
This is the top-level function for optimizing a computation.
Definition at line 326 of file nnet-optimize.cc.
References NnetOptimizeOptions::allocate_from_other, NnetOptimizeOptions::backprop_in_place, CheckComputation(), NnetOptimizeOptions::consolidate_model_update, ConsolidateModelUpdate(), NnetOptimizeOptions::convert_addition, ConvertAdditionToAssignment(), kaldi::GetVerboseLevel(), NnetOptimizeOptions::initialize_undefined, LimitDerivativeTimes(), NnetOptimizeOptions::max_deriv_time, NnetOptimizeOptions::min_deriv_time, NnetOptimizeOptions::move_sizing_commands, MoveSizingCommands(), NnetOptimizeOptions::optimize, NnetOptimizeOptions::propagate_in_place, NnetOptimizeOptions::remove_assignments, RemoveUnnecessaryAllocation(), RemoveUnnecessaryZeroing(), and VariableMergingOptimization().
Referenced by CachingOptimizingCompiler::Compile(), UnitTestNnetCompute(), UnitTestNnetInputDerivatives(), UnitTestNnetModelDerivatives(), and UnitTestNnetOptimizeWithOptions().
{
   if (!config.optimize)
     return;
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, true);
   // this will do nothing unless --min-deriv-time or --max-deriv-time was
   // set.
   LimitDerivativeTimes(nnet, config.min_deriv_time, config.max_deriv_time,
                        computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, true);
   if (config.consolidate_model_update)
     ConsolidateModelUpdate(nnet, request, computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, true);
   if (config.convert_addition)
     ConvertAdditionToAssignment(nnet, computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, true);
   if (config.remove_assignments || config.backprop_in_place ||
       config.propagate_in_place)
     VariableMergingOptimization(config, nnet, request, computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, false);
   if (config.initialize_undefined)
     RemoveUnnecessaryZeroing(nnet, computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, false);
   if (config.move_sizing_commands)
     MoveSizingCommands(nnet, computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, false);
   if (config.allocate_from_other)
     RemoveUnnecessaryAllocation(nnet, computation);
   if (GetVerboseLevel() >= 4)
     CheckComputation(nnet, request, *computation, false);
 }
bool ParseFromString (const std::string & name, std::string * string, int32 * param)
Function used in Init routines.
Suppose name=="foo", if "string" has a field like foo=12, this function will set "param" to 12 and remove that element from "string". It returns true if the parameter was read.
Definition at line 219 of file nnet-parse.cc.
References kaldi::ConvertStringToInteger(), rnnlm::i, rnnlm::j, KALDI_ERR, and kaldi::SplitStringToVector().
{
   std::vector<std::string> split_string;
   SplitStringToVector(*string, " \t", true,
                       &split_string);
   std::string name_equals = name + "="; // the name and then the equals sign.
   size_t len = name_equals.length();
   for (size_t i = 0; i < split_string.size(); i++) {
     if (split_string[i].compare(0, len, name_equals) == 0) {
       if (!ConvertStringToInteger(split_string[i].substr(len), param))
         KALDI_ERR << "Bad option " << split_string[i];
       *string = "";
       // Set "string" to all the pieces but the one we used.
       for (size_t j = 0; j < split_string.size(); j++) {
         if (j != i) {
           if (!string->empty()) *string += " ";
           *string += split_string[j];
         }
       }
       return true;
     }
   }
   return false;
 }
bool ParseFromString (const std::string & name, std::string * string, bool * param)
This version of ParseFromString is for parameters of type bool, which can appear as any string beginning with f, F, t or T.
Definition at line 245 of file nnet-parse.cc.
References rnnlm::i, rnnlm::j, KALDI_ERR, and kaldi::SplitStringToVector().
{
   std::vector<std::string> split_string;
   SplitStringToVector(*string, " \t", true,
                       &split_string);
   std::string name_equals = name + "="; // the name and then the equals sign.
   size_t len = name_equals.length();
   for (size_t i = 0; i < split_string.size(); i++) {
     if (split_string[i].compare(0, len, name_equals) == 0) {
       std::string b = split_string[i].substr(len);
       if (b.empty())
         KALDI_ERR << "Bad option " << split_string[i];
       if (b[0] == 'f' || b[0] == 'F') *param = false;
       else if (b[0] == 't' || b[0] == 'T') *param = true;
       else
         KALDI_ERR << "Bad option " << split_string[i];
       *string = "";
       // Set "string" to all the pieces but the one we used.
       for (size_t j = 0; j < split_string.size(); j++) {
         if (j != i) {
           if (!string->empty()) *string += " ";
           *string += split_string[j];
         }
       }
       return true;
     }
   }
   return false;
 }
bool ParseFromString (const std::string & name, std::string * string, BaseFloat * param)
This version of ParseFromString is for parameters of type BaseFloat.
Definition at line 276 of file nnet-parse.cc.
References kaldi::ConvertStringToReal(), rnnlm::i, rnnlm::j, KALDI_ERR, and kaldi::SplitStringToVector().
{
   std::vector<std::string> split_string;
   SplitStringToVector(*string, " \t", true,
                       &split_string);
   std::string name_equals = name + "="; // the name and then the equals sign.
   size_t len = name_equals.length();
   for (size_t i = 0; i < split_string.size(); i++) {
     if (split_string[i].compare(0, len, name_equals) == 0) {
       if (!ConvertStringToReal(split_string[i].substr(len), param))
         KALDI_ERR << "Bad option " << split_string[i];
       *string = "";
       // Set "string" to all the pieces but the one we used.
       for (size_t j = 0; j < split_string.size(); j++) {
         if (j != i) {
           if (!string->empty()) *string += " ";
           *string += split_string[j];
         }
       }
       return true;
     }
   }
   return false;
 }
bool ParseFromString (const std::string & name, std::string * string, std::string * param)
This version of ParseFromString is for parsing strings.
(these should not contain space).
Definition at line 302 of file nnet-parse.cc.
References rnnlm::i, rnnlm::j, and kaldi::SplitStringToVector().
{
   std::vector<std::string> split_string;
   SplitStringToVector(*string, " \t", true,
                       &split_string);
   std::string name_equals = name + "="; // the name and then the equals sign.
   size_t len = name_equals.length();
   for (size_t i = 0; i < split_string.size(); i++) {
     if (split_string[i].compare(0, len, name_equals) == 0) {
       *param = split_string[i].substr(len);
       // Set "string" to all the pieces but the one we used.
       *string = "";
       for (size_t j = 0; j < split_string.size(); j++) {
         if (j != i) {
           if (!string->empty()) *string += " ";
           *string += split_string[j];
         }
       }
       return true;
     }
   }
   return false;
 }
bool ParseFromString (const std::string & name, std::string * string, std::vector< int32 > * param)
This version of ParseFromString handles colon-separated or comma-separated lists of integers.
Definition at line 328 of file nnet-parse.cc.
References rnnlm::i, rnnlm::j, KALDI_ERR, kaldi::SplitStringToIntegers(), and kaldi::SplitStringToVector().
{
   std::vector<std::string> split_string;
   SplitStringToVector(*string, " \t", true,
                       &split_string);
   std::string name_equals = name + "="; // the name and then the equals sign.
   size_t len = name_equals.length();
   for (size_t i = 0; i < split_string.size(); i++) {
     if (split_string[i].compare(0, len, name_equals) == 0) {
       if (!SplitStringToIntegers(split_string[i].substr(len), ":,",
                                  false, param))
         KALDI_ERR << "Bad option " << split_string[i];
       *string = "";
       // Set "string" to all the pieces but the one we used.
       for (size_t j = 0; j < split_string.size(); j++) {
         if (j != i) {
           if (!string->empty()) *string += " ";
           *string += split_string[j];
         }
       }
       return true;
     }
   }
   return false;
 }
static std::string kaldi::nnet3::ParsingContext (const std::string * token_ptr) static
Definition at line 29 of file nnet-descriptor.cc.
Referenced by ExpectToken(), and ReadIntegerToken().
{
   if (*token_ptr == "end of input")
     return "";
   std::string next_few_tokens = ", next part of line is: ";
   // in the next line, *token_ptr should never equal "" but it's to mitigate the
   // effect of bugs where we read past the end of the array.
   while (*token_ptr != "end of input" && *token_ptr != "" &&
          next_few_tokens.size() < 40) {
     next_few_tokens = (next_few_tokens + " ") + *token_ptr;
     token_ptr++;
   }
   if (*token_ptr != "end of input")
     next_few_tokens = next_few_tokens + " ...";
   return next_few_tokens;
 }
void PerturbParams (BaseFloat stddev, Nnet * nnet)
Calls PerturbParams (with the given stddev) on all updatable components of the nnet.
Definition at line 174 of file nnet-utils.cc.
References Nnet::GetComponent(), KALDI_ASSERT, kUpdatableComponent, Nnet::NumComponents(), UpdatableComponent::PerturbParams(), and Component::Properties().
Referenced by UnitTestNnetModelDerivatives().
{
   for (int32 c = 0; c < nnet->NumComponents(); c++) {
     Component *comp = nnet->GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       UpdatableComponent *u_comp = dynamic_cast<UpdatableComponent*>(comp);
       KALDI_ASSERT(u_comp != NULL);
       u_comp->PerturbParams(stddev);
     }
   }
 }
void PrintCindex (std::ostream & os, const Cindex & cindex, const std::vector< std::string > & node_names)
Definition at line 180 of file nnet-common.cc.
References KALDI_ASSERT.
Referenced by ComputationGraph::Print().
{
   KALDI_ASSERT(static_cast<size_t>(cindex.first) < node_names.size());
   os << node_names[cindex.first] << "(" << cindex.second.n << ","
      << cindex.second.t;
   if (cindex.second.x != 0)
     os << "," << cindex.second.x;
   os << ")";
 }
void PrintCindexes (std::ostream & ostream, const std::vector< Cindex > & cindexes, const std::vector< std::string > & node_names)
this will only be used for pretty-printing.
It prints a vector of Cindexes in a compact, human-readable way with compression of ranges. If the values of the node indexes are the same for the entire vector, it will just be node-name followed by the output of PrintIndexes, e.g. some_node[ (1,1,0) ]. Otherwise it will divide the vector into ranges that each have all the same node name, and will print out each range in the way we just mentioned. 'node_names' will usually come from a call like nnet.GetNodeNames().
Definition at line 232 of file nnet-common.cc.
References KALDI_ASSERT, and PrintIndexes().
Referenced by PrintComputationPreamble().
{
   int32 num_cindexes = cindexes.size();
   if (num_cindexes == 0) {
     ostream << "[ ]";
     return;
   }
   int32 cur_offset = 0;
   std::vector<Index> indexes;
   indexes.reserve(cindexes.size());
   while (cur_offset < num_cindexes) {
     int32 cur_node_index = cindexes[cur_offset].first;
     while (cur_offset < num_cindexes &&
            cindexes[cur_offset].first == cur_node_index) {
       indexes.push_back(cindexes[cur_offset].second);
       cur_offset++;
     }
     KALDI_ASSERT(static_cast<size_t>(cur_node_index) < node_names.size());
     const std::string &node_name = node_names[cur_node_index];
     ostream << node_name;
     PrintIndexes(ostream, indexes);
     indexes.clear();
   }
 }
std::string kaldi::nnet3::PrintCommand (int32 num_commands, int32 command)
Definition at line 28 of file nnet-analyze-test.cc.
Referenced by NnetComputation::GetCommandStrings(), NnetComputation::Print(), and UnitTestNnetAnalyze().
{
   std::ostringstream os;
   if (command < 0 || command >= num_commands)
     os << command;
   else
     os << 'c' << command;
   return os.str();
 }
static void kaldi::nnet3::PrintCommand (std::ostream & os, const Nnet & nnet, const NnetComputation & computation, int32 command_index, const std::vector< std::string > & submatrix_strings, const std::vector< std::string > & indexes_strings, const std::vector< std::string > & indexes_multi_strings) static
Definition at line 240 of file nnet-computation.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::arg2, NnetComputation::Command::arg3, NnetComputation::Command::arg4, NnetComputation::Command::arg5, NnetComputation::Command::arg6, NnetComputation::Command::command_type, NnetComputation::commands, Nnet::GetComponentName(), rnnlm::i, NnetComputation::indexes_ranges, kAddRowRanges, kAddRows, kAddRowsMulti, kAddToRowsMulti, KALDI_ASSERT, KALDI_ERR, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed, kAllocMatrixUndefined, kAllocMatrixZeroed, kBackprop, kBackpropNoModelUpdate, kCopyRows, kCopyRowsMulti, kCopyToRowsMulti, kDeallocMatrix, kMatrixAdd, kMatrixCopy, kNoOperation, kNoOperationMarker, kPropagate, kStoreStats, NnetComputation::matrices, and NnetComputation::need_model_derivative.
{
   KALDI_ASSERT(command_index < computation.commands.size());
   os << "c" << command_index << ": ";
   const NnetComputation::Command &c = computation.commands[command_index];
   switch (c.command_type) {
     case kAllocMatrixZeroed:
       os << "m" << c.arg1 << " = zeros("
          << computation.matrices[c.arg1].num_rows
          << ',' << computation.matrices[c.arg1].num_cols << ")\n";
       break;
     case kAllocMatrixUndefined:
       os << "m" << c.arg1 << " = undefined("
          << computation.matrices[c.arg1].num_rows
          << ',' << computation.matrices[c.arg1].num_cols << ")\n";
       break;
     case kDeallocMatrix:
       os << "m" << c.arg1 << " = []\n";
       break;
     case kAllocMatrixFromOther:
       os << "m" << c.arg1 << ".swap(m" << c.arg2 << ") [dim = "
          << computation.matrices[c.arg1].num_rows << " x "
          << computation.matrices[c.arg1].num_cols << "]\n";
       break;
     case kAllocMatrixFromOtherZeroed:
       os << "m" << c.arg1 << ".swap(m" << c.arg2 << ") [dim = "
          << computation.matrices[c.arg1].num_rows << " x "
          << computation.matrices[c.arg1].num_cols << "]; m"
          << c.arg1 << ".zero();\n";
       break;
     case kPropagate:
       os << nnet.GetComponentName(c.arg1) << ".Propagate(";
       if (c.arg2 == 0) os << "NULL, ";
       else os << "precomputed_indexes[" << c.arg2 << "], ";
       os << submatrix_strings[c.arg3] << ", &" << submatrix_strings[c.arg4]
          << ")\n";
       break;
     case kStoreStats:
       os << nnet.GetComponentName(c.arg1) << ".StoreStats("
          << submatrix_strings[c.arg2] << ")\n";
       break;
     case kBackprop:
     case kBackpropNoModelUpdate: {
       int32 component_index = c.arg1;
       os << nnet.GetComponentName(component_index) << ".Backprop(";
       if (c.arg2 == 0) os << "NULL, ";
       else os << "precomputed_indexes[" << c.arg2 << "], ";
       os << submatrix_strings[c.arg3] << ", "
          << submatrix_strings[c.arg4] << ", "
          << submatrix_strings[c.arg5] << ", "
          << (computation.need_model_derivative &&
              c.command_type == kBackprop ?
              "[component-pointer], " : "NULL, ")
          << (c.arg6 == 0 ? std::string("NULL") :
              std::string("&") + submatrix_strings[c.arg6]) << ")\n";
       break;
     }
     case kMatrixCopy:
       os << submatrix_strings[c.arg1] << " = "
          << submatrix_strings[c.arg2] << "\n";
       break;
     case kMatrixAdd:
       os << submatrix_strings[c.arg1] << " += "
          << submatrix_strings[c.arg2] << "\n";
       break;
     case kAddRows:
     case kCopyRows:
       os << submatrix_strings[c.arg1] << "."
          << (c.command_type == kAddRows ? "AddRows" :
              "CopyRows") << "(" << submatrix_strings[c.arg2]
          << indexes_strings[c.arg3] << ")\n";
       break;
     case kAddRowsMulti:
     case kAddToRowsMulti:
     case kCopyRowsMulti:
     case kCopyToRowsMulti: {
       CommandType ct = c.command_type;
       os << submatrix_strings[c.arg1] << "."
          << (ct == kAddRowsMulti ? "AddRowsMulti" :
              (ct == kAddToRowsMulti? "AddToRowsMulti" :
               (ct == kCopyRowsMulti ? "CopyRowsMulti" :
                "CopyToRowsMulti"))) << "("
          << indexes_multi_strings[c.arg2] << ")\n";
       break;
     }
     case kAddRowRanges: {
       os << submatrix_strings[c.arg1] << ".AddRowRanges("
          << submatrix_strings[c.arg2] << ", [";
       const std::vector<std::pair<int32, int32> > &pairs =
            computation.indexes_ranges[c.arg3];
       for (size_t i = 0; i < pairs.size(); i++) {
         os << pairs[i].first << ":" << (pairs[i].second - 1);
         if (i + 1 < pairs.size()) os << ",";
       }
       os << "])\n";
       break;
     }
     case kNoOperation:
       os << "[no-op]\n";
       break;
     case kNoOperationMarker:
       os << "# begin backward commands\n";
       break;
     default:
       KALDI_ERR << "Un-handled command type.";
   }
 }
void PrintCommandAttributes (std::ostream & os, const std::vector< CommandAttributes > & attributes)
This function is to be used in debugging; it produces human-readable output.
Definition at line 1180 of file nnet-analyze.cc.
References CommandAttributes::matrices_read, CommandAttributes::matrices_written, CommandAttributes::variables_read, and CommandAttributes::variables_written.
{
   int32 num_commands = attributes.size();
   for (int32 c = 0; c < num_commands; c++) {
     const CommandAttributes &this_attr = attributes[c];
     os << "c" << c << ": ";
     if (!this_attr.variables_read.empty()) {
       os << "r(";
       std::vector<int32>::const_iterator iter = this_attr.variables_read.begin(),
           end = this_attr.variables_read.end();
       for (; iter != end; ++iter) {
         os << "v" << *iter;
         if (iter+1 != end) os << ",";
       }
       os << ") ";
     }
     if (!this_attr.variables_written.empty()) {
       os << "w(";
       std::vector<int32>::const_iterator
           iter = this_attr.variables_written.begin(),
           end = this_attr.variables_written.end();
       for (; iter != end; ++iter) {
         os << "v" << *iter;
         if (iter+1 != end) os << ",";
       }
       os << ") ";
     }
     if (!this_attr.matrices_read.empty()) {
       os << "r(";
       std::vector<int32>::const_iterator iter = this_attr.matrices_read.begin(),
           end = this_attr.matrices_read.end();
       for (; iter != end; ++iter) {
         os << "m" << *iter;
         if (iter+1 != end) os << ",";
       }
       os << ") ";
     }
     if (!this_attr.matrices_written.empty()) {
       os << "w(";
       std::vector<int32>::const_iterator
           iter = this_attr.matrices_written.begin(),
           end = this_attr.matrices_written.end();
       for (; iter != end; ++iter) {
         os << "m" << *iter;
         if (iter+1 != end) os << ",";
       }
       os << ")";
     }
     os << "\n";
   }
 }
static void kaldi::nnet3::PrintComputationPreamble (std::ostream & os, const NnetComputation & c, const Nnet & nnet, const std::vector< std::string > & submatrix_strings, const std::vector< std::string > & indexes_strings, const std::vector< std::string > & indexes_multi_strings) static
Definition at line 354 of file nnet-computation.cc.
References NnetComputation::MatrixDebugInfo::cindexes, Nnet::GetNodeName(), Nnet::GetNodeNames(), rnnlm::i, NnetComputation::input_output_info, NnetComputation::MatrixDebugInfo::is_deriv, KALDI_ASSERT, NnetComputation::matrices, NnetComputation::matrix_debug_info, and PrintCindexes().
Referenced by NnetComputation::GetCommandStrings(), and NnetComputation::Print().
{
   // First print info about the matrices.
   os << "matrix ";
   for (int32 i = 1; i < c.matrices.size(); i++) {
     os << "m" << i << "(" << c.matrices[i].num_rows
        << ", " << c.matrices[i].num_cols << ")";
     if (i + 1 < c.matrices.size())
       os << ", ";
   }
   os << "\n";
   // show which matrices the inputs and outputs map to.
   for (unordered_map<int32, std::pair<int32, int32> >::const_iterator iter =
            c.input_output_info.begin(); iter != c.input_output_info.end();
        ++iter) {
     int32 node_index = iter->first,
         value_matrix_index = iter->second.first,
         deriv_matrix_index = iter->second.second;
     os << nnet.GetNodeName(node_index) << ".value -> m"
        << value_matrix_index << "\n";
     if (deriv_matrix_index != 0) {
       os << nnet.GetNodeName(node_index) << ".deriv -> m"
          << deriv_matrix_index << "\n";
     }
   }
   if (!c.matrix_debug_info.empty()) {
     os << "# The following show how matrices correspond to network-nodes and\n"
        << "# cindex-ids.  Format is: matrix = <node-id>.[value|deriv][ <list-of-cindex-ids> ]\n"
        << "# where a cindex-id is written as (n,t[,x]) but ranges of t values are compressed\n"
        << "# so we write (n, tfirst:tlast).\n";
     KALDI_ASSERT(c.matrix_debug_info.size() == c.matrices.size());
     for (int32 i = 1; i < c.matrices.size(); i++) {
       const NnetComputation::MatrixDebugInfo &debug_info =
           c.matrix_debug_info[i];
       os << "m" << i << " == " << (debug_info.is_deriv ? "deriv: " : "value: ");
       PrintCindexes(os, debug_info.cindexes, nnet.GetNodeNames());
       os << "\n";
     }
   }
 }
static void kaldi::nnet3::PrintFloatSuccinctly (std::ostream & os, BaseFloat f) static
Definition at line 445 of file nnet-parse.cc.
Referenced by SummarizeVector().
{
   if (fabs(f) < 10000.0 && fabs(f) >= 10.0) {
     os  << std::fixed << std::setprecision(0) << f;
   } else if (fabs(f) >= 0.995) {
     os  << std::fixed << std::setprecision(1) << f;
   } else if (fabs(f) >= 0.01) {
     os  << std::fixed << std::setprecision(2) << f;
   } else {
     os << std::setprecision(1) << f;
   }
   os.unsetf(std::ios_base::floatfield);
   os << std::setprecision(6);  // Restore the default.
 }
std::string PrintGraphToString (const std::vector< std::vector< int32 > > & graph)
Prints a graph to a string in a pretty way for human readability, e.g.
as 0 -> 1,2; 1 -> 2; 2 -> 3,4,5; etc.
Definition at line 248 of file nnet-graph.cc.
References rnnlm::i, and rnnlm::j.
Referenced by ComputeNnetComputationEpochs().
{
   std::ostringstream os;
   int32 num_nodes = graph.size();
   for (int32 i = 0; i < num_nodes; i++) {
     os << i << " -> (";
     const std::vector<int32> &vec = graph[i];
     int32 size = vec.size();
     for (int32 j = 0; j < size; j++) {
       os << vec[j];
       if (j + 1 < size) os << ",";
     }
     os << ")";
     if (i + 1 < num_nodes) os << "; ";
   }
   return os.str();
 }
void PrintIndexes (std::ostream & ostream, const std::vector< Index > & indexes)
this will only be used for pretty-printing.
It prints a vector of Indexes in a compact, human-readable way with compression of ranges (it also doesn't print the x index if it's 1.0. Example output: "[ (1,1:20), (2, 1:20) ]" which would correspond to the indexes [ (1,1,0), (1,2,0) ... (1,20,0) (2,1,0) ... (2,20,0) ].
Definition at line 190 of file nnet-common.cc.
References rnnlm::i, KALDI_ASSERT, Index::n, Index::t, and Index::x.
Referenced by IoSpecification::Print(), and PrintCindexes().
{
   if (indexes.empty()) {
     os << "[ ]";
     return;
   }
   // range_starts will be the starts of ranges (with consecutive t values and
   // the same n value and zero x values) that we compactly print.  we'll append
   // "end" to range_starts for convenience.n
   std::vector<int32> range_starts;
   int32 cur_start = 0, end = indexes.size();
   for (int32 i = cur_start; i < end; i++) {
     const Index &index = indexes[i];
     if (i > cur_start &&
         (index.t != indexes[i-1].t + 1 ||
          index.n != indexes[i-1].n ||
          index.x != indexes[i-1].x)) {
       range_starts.push_back(cur_start);
       cur_start = i;
     }
   }
   range_starts.push_back(cur_start);
   range_starts.push_back(end);
   os << "[";
   int32 num_ranges = range_starts.size() - 1;
   for (int32 r = 0; r < num_ranges; r++) {
     int32 range_start = range_starts[r], range_end = range_starts[r+1];
     KALDI_ASSERT(range_end > range_start);
     os << "(" << indexes[range_start].n << ",";
     if (range_end == range_start + 1)
       os << indexes[range_start].t;
     else
       os << indexes[range_start].t << ":" << indexes[range_end - 1].t;
     if (indexes[range_start].x != 0)
       os << "," << indexes[range_start].x;
     os << ")";
     if (r + 1 < num_ranges)
       os << ", ";
   }
   os << "]";
 }
void PrintIntegerVector (std::ostream & os, const std::vector< int32 > & ints)
Definition at line 259 of file nnet-common.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by kaldi::nnet3::computation_graph::ComputeEpochInfo(), and GetIndexesStrings().
{
   if (ints.empty()) {
     os << "[ ]";
     return;
   }
   // range_starts will be the starts of ranges (with consecutive or identical
   // values) that we compactly print.  we'll append "end" to range_starts for
   // convenience.
   std::vector<int32> range_starts;
   int32 cur_start = 0, end = ints.size();
   for (int32 i = cur_start; i < end; i++) {
     if (i > cur_start) {
       int32 range_start_val = ints[cur_start],
           range_start_plus_one_val = ints[cur_start+1],
           cur_val = ints[i];
       // if we have reached the end of a range...
       if (!((range_start_plus_one_val == range_start_val &&
              cur_val == range_start_val) ||
             (range_start_plus_one_val == range_start_val + 1 &&
              cur_val == range_start_val + i - cur_start))) {
         range_starts.push_back(cur_start);
         cur_start = i;
       }
     }
   }
   range_starts.push_back(cur_start);
   range_starts.push_back(end);
   os << "[";
   int32 num_ranges = range_starts.size() - 1;
   for (int32 r = 0; r < num_ranges; r++) {
     int32 range_start = range_starts[r], range_end = range_starts[r+1];
     KALDI_ASSERT(range_end > range_start);
     if (range_end == range_start + 1)
       os << ints[range_start];
     else if (range_end == range_start + 2)  // don't print ranges of 2.
       os << ints[range_start] << ", " << ints[range_start+1];
     else if (ints[range_start] == ints[range_start+1])
       os << ints[range_start] << "x" << (range_end - range_start);
     else
       os << ints[range_start] << ":" << ints[range_end - 1];
     if (r + 1 < num_ranges)
       os << ", ";
   }
   os << "]";
 }
void PrintMatrixAccesses (std::ostream & os, const std::vector< MatrixAccesses > & matrix_accesses)
This function is to be used in debugging; it produces human-readable output.
Definition at line 1162 of file nnet-analyze.cc.
References MatrixAccesses::accesses, MatrixAccesses::allocate_command, MatrixAccesses::deallocate_command, kReadAccess, and kWriteAccess.
{
   int32 num_matrices = matrix_accesses.size();
   for (int32 m = 1; m < num_matrices; m++) {
     const MatrixAccesses &a = matrix_accesses[m];
     os << "m" << m << ": init-command=" << a.allocate_command
        << ", destroy-command=" << a.deallocate_command
        << ", accesses=";
     std::vector<Access>::const_iterator iter = a.accesses.begin(),
         end = a.accesses.end();
     for (; iter != end; ++iter)
       os << 'c' << iter->command_index << "("
          << (iter->access_type == kReadAccess ? "r" :
              (iter->access_type == kWriteAccess ? "w" : "rw")) << ") ";
     os << "\n";
   }
 }
void PrintParameterStats (std::ostringstream & os, const std::string & name, const CuVector< BaseFloat > & params, bool include_mean = false)
Print to 'os' some information about the mean and standard deviation of some parameters, used in Info() functions in nnet-simple-component.cc.
For example: PrintParameterStats(os, "bias", bias_params_, true); would print to 'os' something like the string ", bias-{mean,stddev}=-0.013,0.196". If 'include_mean = false', it will print something like ", bias-rms=0.2416", and this represents and uncentered standard deviation.
Definition at line 498 of file nnet-parse.cc.
References CuVectorBase< Real >::Dim(), CuVectorBase< Real >::Sum(), and kaldi::VecVec().
Referenced by AffineComponent::Info(), RepeatedAffineComponent::Info(), BlockAffineComponent::Info(), NaturalGradientAffineComponent::Info(), FixedAffineComponent::Info(), FixedScaleComponent::Info(), FixedBiasComponent::Info(), PerElementScaleComponent::Info(), PerElementOffsetComponent::Info(), ConvolutionComponent::Info(), and Convolutional1dComponent::Info().
{
   os << std::setprecision(4);
   os << ", " << name << '-';
   if (include_mean) {
     BaseFloat mean = params.Sum() / params.Dim(),
         stddev = std::sqrt(VecVec(params, params) / params.Dim() - mean * mean);
     os << "{mean,stddev}=" << mean << ',' << stddev;
   } else {
     BaseFloat rms = std::sqrt(VecVec(params, params) / params.Dim());
     os << "rms=" << rms;
   }
   os << std::setprecision(6);  // restore the default precision.
 }
void PrintParameterStats (std::ostringstream & os, const std::string & name, const CuMatrix< BaseFloat > & params, bool include_mean = false)
Print to 'os' some information about the mean and standard deviation of some parameters, used in Info() functions in nnet-simple-component.cc.
For example: PrintParameterStats(os, "linear-params", linear_params_; would print to 'os' something like the string ", linear-params-rms=0.239". If you set include_mean to true, it will print something like ", linear-params-{mean-stddev}=0.103,0.183".
Definition at line 515 of file nnet-parse.cc.
References kaldi::kTrans, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), CuMatrixBase< Real >::Sum(), and kaldi::TraceMatMat().
{
   os << std::setprecision(4);
   os << ", " << name << '-';
   int32 dim = params.NumRows() * params.NumCols();
   if (include_mean) {
     BaseFloat mean = params.Sum() / dim,
         stddev = std::sqrt(TraceMatMat(params, params, kTrans) / dim -
                            mean * mean);
     os << "{mean,stddev}=" << mean << ',' << stddev;
   } else {
     BaseFloat rms = std::sqrt(TraceMatMat(params, params, kTrans) / dim);
     os << "rms=" << rms;
   }
   os << std::setprecision(6);  // restore the default precision.
 }
void kaldi::nnet3::PrintPriorDiagnostics (const Vector< BaseFloat > & old_priors, const Vector< BaseFloat > & new_priors)
Definition at line 48 of file nnet3-am-adjust-priors.cc.
References VectorBase< Real >::AddVec(), VectorBase< Real >::ApplyAbs(), VectorBase< Real >::Dim(), KALDI_LOG, KlDivergence(), and VectorBase< Real >::Max().
Referenced by main().
{
   if (old_priors.Dim() == 0) {
     KALDI_LOG << "Model did not previously have priors attached.";
   } else {
     Vector<BaseFloat> diff_prior(new_priors);
     diff_prior.AddVec(-1.0, old_priors);
     diff_prior.ApplyAbs();
     int32 max_index;
     diff_prior.Max(&max_index);
     KALDI_LOG << "Adjusting priors: largest absolute difference was for "
               << "pdf " << max_index << ", " << old_priors(max_index)
               << " -> " << new_priors(max_index);
     KALDI_LOG << "Adjusting priors: K-L divergence from old to new is "
               << KlDivergence(old_priors, new_priors);
   }
 }
std::string PrintVectorPerUpdatableComponent (const Nnet & nnet, const VectorBase< BaseFloat > & vec)
This function is for printing, to a string, a vector with one element per updatable component of the nnet (e.g.
the output of ComponentDotProducts), in a human readable way, as [ component-name1:number1 component-name2:number2 ... ].
Definition at line 206 of file nnet-utils.cc.
References VectorBase< Real >::Dim(), Nnet::GetComponent(), Nnet::GetComponentName(), KALDI_ASSERT, kUpdatableComponent, Nnet::NumComponents(), NumUpdatableComponents(), and Component::Properties().
Referenced by main().
{
   std::ostringstream os;
   os << "[ ";
   KALDI_ASSERT(NumUpdatableComponents(nnet) == vec.Dim());
   int32 updatable_c = 0;
   for (int32 c = 0; c < nnet.NumComponents(); c++) {
     const Component *comp = nnet.GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       const std::string &component_name = nnet.GetComponentName(c);
       os << component_name << ':' << vec(updatable_c) << ' ';
       updatable_c++;
     }
   }
   KALDI_ASSERT(updatable_c == vec.Dim());
   os << ']';
   return os.str();
 }
void kaldi::nnet3::PrintVectorVectorPair (std::vector< std::vector< std::pair< int32, int32 > > > vec_vec_pair)
Definition at line 50 of file nnet-compile-utils-test.cc.
References rnnlm::i, rnnlm::j, and KALDI_LOG.
Referenced by UnitTestSplitLocations(), and UnitTestSplitLocationsBackward().
{
   std::ostringstream ostream;
   for (int32 i = 0; i < vec_vec_pair.size(); i++) {
     for (int32 j = 0; j < vec_vec_pair[i].size(); j++)  {
       ostream << "(" << vec_vec_pair[i][j].first << ","
               << vec_vec_pair[i][j].second << ") ";
     }
     ostream << std::endl;
   }
   KALDI_LOG << ostream.str();
 }
static void kaldi::nnet3::ProcessFile (const MatrixBase< BaseFloat > & feats, const MatrixBase< BaseFloat > * ivector_feats, const MatrixBase< BaseFloat > & targets, const std::string & utt_id, bool compress, int32 num_targets, int32 left_context, int32 right_context, int32 frames_per_eg, int64 * num_frames_written, int64 * num_egs_written, NnetExampleWriter * example_writer) static
Definition at line 33 of file nnet3-get-egs-dense-targets.cc.
References NnetExample::Compress(), VectorBase< Real >::CopyFromVec(), rnnlm::i, NnetExample::io, rnnlm::j, KALDI_ASSERT, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), and TableWriter< Holder >::Write().
Referenced by main().
{
   KALDI_ASSERT(feats.NumRows() == static_cast<int32>(targets.NumRows()));
   for (int32 t = 0; t < feats.NumRows(); t += frames_per_eg) {
     // actual_frames_per_eg is the number of frames with actual targets.
     // At the end of the file, we pad with the last frame repeated
     // so that all examples have the same structure (prevents the need
     // for recompilations).
     // TODO: We might need to ignore the end of the file.
     int32 actual_frames_per_eg = std::min(frames_per_eg,
                                           feats.NumRows() - t);
     int32 tot_frames = left_context + frames_per_eg + right_context;
     Matrix<BaseFloat> input_frames(tot_frames, feats.NumCols());
     // Set up "input_frames".
     for (int32 j = -left_context; j < frames_per_eg + right_context; j++) {
       int32 t2 = j + t;
       if (t2 < 0) t2 = 0;
       if (t2 >= feats.NumRows()) t2 = feats.NumRows() - 1;
       SubVector<BaseFloat> src(feats, t2),
           dest(input_frames, j + left_context);
       dest.CopyFromVec(src);
     }
     NnetExample eg;
     // call the regular input "input".
     eg.io.push_back(NnetIo("input", - left_context,
                            input_frames));
     // if applicable, add the iVector feature.
     if (ivector_feats != NULL) {
       // try to get closest frame to middle of window to get
       // a representative iVector.
       int32 closest_frame = t + (actual_frames_per_eg / 2);
       KALDI_ASSERT(ivector_feats->NumRows() > 0);
       if (closest_frame >= ivector_feats->NumRows())
         closest_frame = ivector_feats->NumRows() - 1;
       Matrix<BaseFloat> ivector(1, ivector_feats->NumCols());
       ivector.Row(0).CopyFromVec(ivector_feats->Row(closest_frame));
       eg.io.push_back(NnetIo("ivector", 0, ivector));
     }
     // add the labels.
     Matrix<BaseFloat> targets_dest(frames_per_eg, targets.NumCols());
     for (int32 i = 0; i < actual_frames_per_eg; i++) {
       // Copy the i^th row of the target matrix from the (t+i)^th row of the
       // input targets matrix
       SubVector<BaseFloat> this_target_dest(targets_dest, i);
       SubVector<BaseFloat> this_target_src(targets, t+i);
       this_target_dest.CopyFromVec(this_target_src);
     }
     // Copy the last frame's target to the padded frames
     for (int32 i = actual_frames_per_eg; i < frames_per_eg; i++) {
       // Copy the i^th row of the target matrix from the last row of the
       // input targets matrix
       KALDI_ASSERT(t + actual_frames_per_eg - 1 == feats.NumRows() - 1);
       SubVector<BaseFloat> this_target_dest(targets_dest, i);
       SubVector<BaseFloat> this_target_src(targets, t+actual_frames_per_eg-1);
       this_target_dest.CopyFromVec(this_target_src);
     }
     // push this created targets matrix into the eg
     eg.io.push_back(NnetIo("output", 0, targets_dest));
     if (compress)
       eg.Compress();
     std::ostringstream os;
     os << utt_id << "-" << t;
     std::string key = os.str(); // key is <utt_id>-<frame_id>
     *num_frames_written += actual_frames_per_eg;
     *num_egs_written += 1;
     example_writer->Write(key, eg);
   }
 }
static void kaldi::nnet3::ProcessFile (const MatrixBase< BaseFloat > & feats, const MatrixBase< BaseFloat > * ivector_feats, const Posterior & pdf_post, const std::string & utt_id, bool compress, int32 num_pdfs, int32 left_context, int32 right_context, int32 frames_per_eg, int64 * num_frames_written, int64 * num_egs_written, NnetExampleWriter * example_writer) static
Definition at line 33 of file nnet3-get-egs.cc.
References NnetExample::Compress(), VectorBase< Real >::CopyFromVec(), rnnlm::i, NnetExample::io, rnnlm::j, KALDI_ASSERT, kaldi::kUndefined, MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), MatrixBase< Real >::Row(), and TableWriter< Holder >::Write().
{
   KALDI_ASSERT(feats.NumRows() == static_cast<int32>(pdf_post.size()));
   for (int32 t = 0; t < feats.NumRows(); t += frames_per_eg) {
     // actual_frames_per_eg is the number of frames with nonzero
     // posteriors.  At the end of the file we pad with zero posteriors
     // so that all examples have the same structure (prevents the need
     // for recompilations).
     int32 actual_frames_per_eg = std::min(frames_per_eg,
                                           feats.NumRows() - t);
     int32 tot_frames = left_context + frames_per_eg + right_context;
     Matrix<BaseFloat> input_frames(tot_frames, feats.NumCols(), kUndefined);
     // Set up "input_frames".
     for (int32 j = -left_context; j < frames_per_eg + right_context; j++) {
       int32 t2 = j + t;
       if (t2 < 0) t2 = 0;
       if (t2 >= feats.NumRows()) t2 = feats.NumRows() - 1;
       SubVector<BaseFloat> src(feats, t2),
           dest(input_frames, j + left_context);
       dest.CopyFromVec(src);
     }
     NnetExample eg;
     // call the regular input "input".
     eg.io.push_back(NnetIo("input", - left_context,
                            input_frames));
     // if applicable, add the iVector feature.
     if (ivector_feats != NULL) {
       // try to get closest frame to middle of window to get
       // a representative iVector.
       int32 closest_frame = t + (actual_frames_per_eg / 2);
       KALDI_ASSERT(ivector_feats->NumRows() > 0);
       if (closest_frame >= ivector_feats->NumRows())
         closest_frame = ivector_feats->NumRows() - 1;
       Matrix<BaseFloat> ivector(1, ivector_feats->NumCols());
       ivector.Row(0).CopyFromVec(ivector_feats->Row(closest_frame));
       eg.io.push_back(NnetIo("ivector", 0, ivector));
     }
     // add the labels.
     Posterior labels(frames_per_eg);
     for (int32 i = 0; i < actual_frames_per_eg; i++)
       labels[i] = pdf_post[t + i];
     // remaining posteriors for frames are empty.
     eg.io.push_back(NnetIo("output", num_pdfs, 0, labels));
     if (compress)
       eg.Compress();
     std::ostringstream os;
     os << utt_id << "-" << t;
     std::string key = os.str(); // key is <utt_id>-<frame_id>
     *num_frames_written += actual_frames_per_eg;
     *num_egs_written += 1;
     example_writer->Write(key, eg);
   }
 }
void ReadConfigFile (std::istream & is, std::vector< std::string > * lines)
This function reads in a config file and *appends* its contents to a vector of lines; it is responsible for removing comments (anything after '#') and stripping out any lines that contain only whitespace after comment removal.
Definition at line 414 of file nnet-parse.cc.
References KALDI_ASSERT.
Referenced by Nnet::ReadConfig(), and UnitTestReadConfig().
{
   KALDI_ASSERT(lines != NULL);
   std::string line;
   while (std::getline(is, line)) {
     if (line.size() == 0) continue;
     size_t start = line.find_first_not_of(" \t");
     size_t end = line.find_first_of('#');
     if (start == std::string::npos || start == end) continue;
     end = line.find_last_not_of(" \t", end - 1);
     KALDI_ASSERT(end >= start);
     lines->push_back(line.substr(start, end - start + 1));
   }
 }
void ReadIndexVector (std::istream & is, bool binary, std::vector< Index > * vec)
Definition at line 135 of file nnet-common.cc.
References ExpectToken(), rnnlm::i, KALDI_ERR, kaldi::ReadBasicType(), and ReadIndexVectorElementBinary().
Referenced by NnetIo::Read(), and UnitTestIndexIo().
{
   ExpectToken(is, binary, "<I1V>");
   int32 size;
   ReadBasicType(is, binary, &size);
   if (size < 0) {
     KALDI_ERR << "Error reading Index vector: size = "
               << size;
   }
   vec->resize(size);
   if (!binary) {
     for (int32 i = 0; i < size; i++)
       (*vec)[i].Read(is, binary);
   } else {
     for (int32 i = 0; i < size; i++)
       ReadIndexVectorElementBinary(is, i, vec);
   }
 }
static void kaldi::nnet3::ReadIndexVectorElementBinary (std::istream & is, int32 i, std::vector< Index > * vec) static
Definition at line 79 of file nnet-common.cc.
References rnnlm::i, KALDI_ERR, Index::n, kaldi::ReadBasicType(), Index::t, and Index::x.
Referenced by ReadIndexVector().
{
   bool binary = true;
   Index &index = (*vec)[i];
   if (!is.good())
     KALDI_ERR << "End of file while reading vector of Index.";
   signed char c = is.get();
   if (i == 0) {
     if (std::abs(int(c)) < 125) {
       index.n = 0;
       index.t = c;
       index.x = 0;
     } else {
       if (c != 127)
         KALDI_ERR << "Unexpected character " << c
                   << " encountered while reading Index vector.";
       ReadBasicType(is, binary, &(index.n));
       ReadBasicType(is, binary, &(index.t));
       ReadBasicType(is, binary, &(index.x));
     }
   } else {
     Index &last_index = (*vec)[i-1];
     if (std::abs(int(c)) < 125) {
       index.n = last_index.n;
       index.t = last_index.t + c;
       index.x = last_index.x;
     } else {
       if (c != 127)
         KALDI_ERR << "Unexpected character " << c
                   << " encountered while reading Index vector.";
       ReadBasicType(is, binary, &(index.n));
       ReadBasicType(is, binary, &(index.t));
       ReadBasicType(is, binary, &(index.x));
     }
   }
 }
static int32 kaldi::nnet3::ReadIntegerToken (const std::string & what_we_are_parsing, const std::string ** next_token) static
Definition at line 56 of file nnet-descriptor.cc.
References kaldi::ConvertStringToInteger(), KALDI_ERR, and ParsingContext().
Referenced by GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), and GeneralDescriptor::ParseRound().
{
   int32 ans;
   if (!ConvertStringToInteger(**next_token, &ans))
     KALDI_ERR << "Expected integer while parsing "
               << what_we_are_parsing << ", got '"
               << **next_token << "'" << ParsingContext(*next_token);
   (*next_token)++;  // advance token pointer.
   return ans;
 }
void kaldi::nnet3::RearrangeIndexes (const std::vector< std::vector< int32 > > & in, std::vector< std::vector< int32 > > * out)
Definition at line 3219 of file nnet-simple-component.cc.
References rnnlm::i, and rnnlm::j.
Referenced by ConvolutionComponent::InderivPatchesToInderiv().
{
   int32 D = in.size();
   int32 L = 0;
   for (int32 i = 0; i < D; i++)
     if (in[i].size() > L)
       L = in[i].size();
   out->resize(L);
   for (int32 i = 0; i < L; i++)
     (*out)[i].resize(D, -1);
   for (int32 i = 0; i < D; i++) {
     for (int32 j = 0; j < in[i].size(); j++) {
       (*out)[j][i] = in[i][j];
     }
   }
 }
void RemoveNoOps (NnetComputation * computation)
Removes commands of type kNoOperation in the computation.
Definition at line 604 of file nnet-optimize-utils.cc.
References NnetComputation::commands, and kNoOperation.
Referenced by DerivativeTimeLimiter::LimitDerivTimes(), VariableMergingOptimizer::MergeVariables(), and RemoveUnnecessaryAllocation().
{
   std::vector<NnetComputation::Command>::iterator
       input_iter = computation->commands.begin(),
       input_end = computation->commands.end(),
       output_iter = computation->commands.begin();
   for (; input_iter != input_end; ++input_iter) {
     if (input_iter->command_type != kNoOperation) {
       *output_iter = *input_iter;
       ++output_iter;
     }
   }
   computation->commands.resize(output_iter - computation->commands.begin());
 }
void RemoveUnnecessaryAllocation (const Nnet & nnet, NnetComputation * computation)
This optimization detects cases where we deallocate a matrix, and then later allocate another matrix of the same size; and replaces them with commands of type kAllocFromOther or kAllocFromOtherZeroed.
Definition at line 185 of file nnet-optimize.cc.
References NnetComputation::Command::arg1, NnetComputation::Command::command_type, NnetComputation::commands, ComputeCommandPairs(), rnnlm::i, KALDI_ASSERT, kAllocMatrixFromOther, kAllocMatrixFromOtherZeroed, kAllocMatrixUndefined, kAllocMatrixZeroed, kDeallocMatrix, kNoOperation, NnetComputation::matrices, and RemoveNoOps().
Referenced by Optimize().
{
   // For each size of matrix (i.e. each pair<int32,int32>), we
   // accumulate a list of indexes of deallocation commands that
   // are for that size, and a list of indexes of allocation commands
   // for that size.
   // For each distinct matrix size, we then call ComputeCommandPairs on those
   // two lists, to get pairs of (deallocation, allocation) command-indexes that
   // we can optimize out to a single command.
   // The map is from a (num-rows,num-columns) to two lists, of
   // (deallocation-commands, allocation-commands).  The order may seem
   // backwards, but that's the order of the pairs we are looking for.
   typedef unordered_map<std::pair<int32,int32>,
       std::pair<std::vector<int32>,std::vector<int32> >,
       PairHasher<int32> > MapType;
   MapType pair_map;
   int32 num_commands = computation->commands.size();
   for (int32 command_index = 0; command_index < num_commands; command_index++) {
     NnetComputation::Command &command = computation->commands[command_index];
     if (command.command_type == kAllocMatrixZeroed ||
         command.command_type == kAllocMatrixUndefined ||
         command.command_type == kDeallocMatrix) {
       int32 m = command.arg1, num_rows = computation->matrices[m].num_rows,
           num_cols = computation->matrices[m].num_cols;
       std::pair<int32,int32> p(num_rows, num_cols);
       std::pair<std::vector<int32>,std::vector<int32> > &lists = pair_map[p];
       if (command.command_type == kDeallocMatrix)
         lists.first.push_back(command_index);
       else
         lists.second.push_back(command_index);
     }
   }
   MapType::const_iterator iter = pair_map.begin(), end = pair_map.end();
   std::vector<std::pair<int32,int32> > command_pairs;
   for (; iter != end; ++iter)
     ComputeCommandPairs(iter->second, &command_pairs);
   for (size_t i = 0; i < command_pairs.size(); i++) {
     int32 dealloc_index = command_pairs[i].first,
         alloc_index = command_pairs[i].second;
     NnetComputation::Command
         &dealloc_command = computation->commands[dealloc_index],
         &alloc_command = computation->commands[alloc_index];
     KALDI_ASSERT(dealloc_command.command_type ==
                  kDeallocMatrix);
     KALDI_ASSERT(alloc_command.command_type ==
                  kAllocMatrixUndefined ||
                  alloc_command.command_type==
                  kAllocMatrixZeroed);
     // remove the deallocation command.
     dealloc_command.command_type =  kNoOperation;
     alloc_command.arg2 = dealloc_command.arg1;
     if (alloc_command.command_type ==
         kAllocMatrixUndefined)
       alloc_command.command_type =
           kAllocMatrixFromOther;
     else
       alloc_command.command_type =
           kAllocMatrixFromOtherZeroed;
   }
   RemoveNoOps(computation);
 }
void RemoveUnnecessaryZeroing (const Nnet & nnet, NnetComputation * computation)
This optimization function changes, where possible, matrix initializations of type kAllocMatrixZeroed to kAllocMatrixUndefined.
Definition at line 90 of file nnet-optimize.cc.
References MatrixAccesses::allocate_command, ComputationVariables::AppendVariablesForMatrix(), NnetComputation::commands, rnnlm::i, Analyzer::Init(), MatrixAccesses::is_output, KALDI_ASSERT, kAllocMatrixUndefined, kAllocMatrixZeroed, kWriteAccess, Analyzer::matrix_accesses, Analyzer::variable_accesses, and Analyzer::variables.
Referenced by Optimize().
{
   Analyzer a;
   a.Init(nnet, *computation);
   // OK, now we'll work out which matrices have all their pieces (i.e. all the
   // variables belonging to that matrix) written to as the first instruction
   // apart from the initial zeroing.  These matrices can have the initial
   // zeroing replaced by a sizing operation that leaves the data undefined.
   int32 num_matrices = a.matrix_accesses.size();
   for (int32 matrix_index = 0; matrix_index < num_matrices; matrix_index++) {
     const MatrixAccesses &accesses = a.matrix_accesses[matrix_index];
     int32 allocate_command = accesses.allocate_command;
     if (allocate_command == -1)  // an input
       continue;  // nothing to do.
     if (computation->commands[allocate_command].command_type !=
         kAllocMatrixZeroed) {
       KALDI_ASSERT(computation->commands[allocate_command].command_type ==
                    kAllocMatrixUndefined);
       continue;  // already leaving it undefined, so nothing to do.
     }
     std::vector<int32> variables_for_matrix;
     a.variables.AppendVariablesForMatrix(matrix_index, &variables_for_matrix);
     bool all_variables_ok = true;  // if this stays true, it means we don't need
                                    // the initial zeroing.
     for (size_t i = 0; i < variables_for_matrix.size(); i++) {
       int32 variable_index = variables_for_matrix[i];
       const std::vector<Access> &v_accesses =
           a.variable_accesses[variable_index];
       KALDI_ASSERT(v_accesses.size() > 0 &&
                    v_accesses[0].command_index == allocate_command &&
                    v_accesses[0].access_type == kWriteAccess);
       if (v_accesses.size() > 1 &&
           v_accesses[1].access_type != kWriteAccess) {
         all_variables_ok = false;  // first access after zeroing was not a write
         break;
       }
       if (v_accesses.size() == 1 &&
           accesses.is_output) {
         // the only command that touches this variable is the allocation, and it
         // is an output variable.  (this is unusual, but can happen e.g. if it's
         // a derivative, but due to min_deriv_time and max_deriv_time it ends up
         // always being zero.
         all_variables_ok = false;
         break;
       }
     }
     if (all_variables_ok) {
       // Here is where the change actually happens.
       computation->commands[allocate_command].command_type =
           kAllocMatrixUndefined;
     }
   }
 }
void RenumberComputation (NnetComputation * computation)
This function detects submatrices, matrices, and members of indexes_multi and indexes that are never used (e.g.
due to changes made in other optimization code), and removes them from the computation by way of suitable renumbering. It does not remove no-ops from computation->commands_; to do that, call RemoveNoOps(computation).
Definition at line 599 of file nnet-optimize-utils.cc.
References ComputationRenumberer::Renumber().
Referenced by DerivativeTimeLimiter::LimitDerivTimes(), and VariableMergingOptimizer::MergeVariables().
{
   ComputationRenumberer renumberer(computation);
   renumberer.Renumber();
 }
bool ReplaceInInput (const Nnet & nnet, int32 orig_matrix_index, int32 new_matrix_index, NnetComputation * computation)
Wherever matrix orig_matrix_index appears in the input of the network (i.e.
in computation->input_output_info), replaces it with new_matrix_index. Returns true if it did replace it.
Definition at line 621 of file nnet-optimize-utils.cc.
References NnetComputation::input_output_info, Nnet::IsOutputNode(), KALDI_ASSERT, and NnetComputation::matrices.
Referenced by VariableMergingOptimizer::DoRightMerge().
{
   bool ans = false;
   int32 num_matrices = computation->matrices.size();
   KALDI_ASSERT(orig_matrix_index > 0 && orig_matrix_index < num_matrices &&
                new_matrix_index > 0 && new_matrix_index < num_matrices);
   unordered_map<int32, std::pair<int32, int32> >::iterator
       iter = computation->input_output_info.begin(),
       end = computation->input_output_info.end();
   for (; iter != end; ++iter) {
     int32 network_node = iter->first,
         &value_matrix_index = iter->second.first,
         &deriv_matrix_index = iter->second.second;
     if (nnet.IsOutputNode(network_node)) {
       // deriv_matrix_index would be an input to the computation.
       if (deriv_matrix_index == orig_matrix_index) {
         deriv_matrix_index = new_matrix_index;
         ans = true;
       }
     } else {
       // value_matrix_index would be an input to the computation.
       if (value_matrix_index == orig_matrix_index) {
         value_matrix_index = new_matrix_index;
         ans = true;
       }
     }
   }
   return ans;
 }
bool ReplaceInOutput (const Nnet & nnet, int32 orig_matrix_index, int32 new_matrix_index, NnetComputation * computation)
Wherever matrix orig_matrix_index appears in the output of the network (i.e.
A helper function used in some optimization functions.
in computation->input_output_info), replaces it with new_matrix_index. Returns true if it did replace it.
Wherever matrix orig_matrix_index appears in the output of the network (i.e. in computation->input_output_info), replaces it with new_matrix_index. Returns true if it did replace it.
Definition at line 657 of file nnet-optimize-utils.cc.
References NnetComputation::input_output_info, Nnet::IsInputNode(), Nnet::IsOutputNode(), KALDI_ASSERT, and NnetComputation::matrices.
Referenced by VariableMergingOptimizer::DoLeftMerge().
{
   bool ans = false;
   int32 num_matrices = computation->matrices.size();
   KALDI_ASSERT(orig_matrix_index > 0 && orig_matrix_index < num_matrices &&
                new_matrix_index > 0 && new_matrix_index < num_matrices);
   unordered_map<int32, std::pair<int32, int32> >::iterator
       iter = computation->input_output_info.begin(),
       end = computation->input_output_info.end();
   for (; iter != end; ++iter) {
     int32 network_node = iter->first,
         &value_matrix_index = iter->second.first,
         &deriv_matrix_index = iter->second.second;
     if (nnet.IsOutputNode(network_node)) {
       // value_matrix_index would be an output of the computation.
       if (value_matrix_index == orig_matrix_index) {
         value_matrix_index = new_matrix_index;
         ans = true;
       }
     } else {
       // deriv_matrix_index would be an output of the computation.
       if (deriv_matrix_index == orig_matrix_index) {
         // we'd only have derivatives for actual inputs. [note: we also allow
         // users to provide inputs for component nodes, but these would not have
         // derivatives.]
         KALDI_ASSERT(nnet.IsInputNode(network_node));
         deriv_matrix_index = new_matrix_index;
         ans = true;
       }
     }
   }
   return ans;
 }
void ScaleNnet (BaseFloat scale, Nnet * nnet)
Scales the nnet parameters and stats by this scale.
Definition at line 267 of file nnet-utils.cc.
References Nnet::GetComponent(), Nnet::NumComponents(), Component::Scale(), and SetZero().
Referenced by main(), and NnetTrainer::Train().
{
   if (scale == 1.0) return;
   else if (scale == 0.0) {
     SetZero(false, nnet);
   } else {
     for (int32 c = 0; c < nnet->NumComponents(); c++) {
       Component *comp = nnet->GetComponent(c);
       comp->Scale(scale);
     }
   }
 }
bool kaldi::nnet3::SecondElementComparator (const std::pair< int32, int32 > & first_pair, const std::pair< int32, int32 > & second_pair)
Definition at line 78 of file nnet-compile-utils.cc.
Referenced by SplitLocationsUsingSubmatHistogram().
{
   if (first_pair.second == second_pair.second)
     return first_pair.first > second_pair.first;
   return first_pair.second > second_pair.second;
 }
bool kaldi::nnet3::SelectFromExample (const NnetExample & eg, std::string frame_str, int32 left_context, int32 right_context, int32 frame_shift, NnetExample * eg_out)
This function is responsible for possibly selecting one frame from multiple supervised frames, and reducing the left and right context as specified.
If frame == "" it does not reduce the supervised frames; if frame == "random" it selects one random frame; otherwise it expects frame to be an integer, and will select only the output with that frame index (or return false if there was no such output).
If left_context != -1 it removes any inputs with t < (smallest output - left_context). If left_context != -1 it removes any inputs with t < (smallest output - left_context).
It returns true if it was able to select a frame. We only anticipate it ever returning false in situations where frame is an integer, and the eg came from the end of a file and has a smaller than normal number of supervised frames.
Definition at line 188 of file nnet3-copy-egs.cc.
References ContainsSingleExample(), kaldi::ConvertStringToInteger(), FilterExample(), KALDI_ERR, kaldi::RandInt(), and ShiftExampleTimes().
Referenced by main().
{
   int32 min_input_t, max_input_t,
       min_output_t, max_output_t;
   if (!ContainsSingleExample(eg, &min_input_t, &max_input_t,
                              &min_output_t, &max_output_t))
     KALDI_ERR << "Too late to perform frame selection/context reduction on "
               << "these examples (already merged?)";
   if (frame_str != "") {
     // select one frame.
     if (frame_str == "random") {
       min_output_t = max_output_t = RandInt(min_output_t,
                                                           max_output_t);
     } else {
       int32 frame;
       if (!ConvertStringToInteger(frame_str, &frame))
         KALDI_ERR << "Invalid option --frame='" << frame_str << "'";
       if (frame < min_output_t || frame > max_output_t) {
         // Frame is out of range.  Should happen only rarely.  Calling code
         // makes sure of this.
         return false;
       }
       min_output_t = max_output_t = frame;
     }
   }
   // There may come a time when we want to remove or make it possible to disable
   // the error messages below.  The std::max and std::min expressions may seem
   // unnecessary but are intended to make life easier if and when we do that.
   if (left_context != -1) {
     if (min_input_t > min_output_t - left_context)
       KALDI_ERR << "You requested --left-context=" << left_context
                 << ", but example only has left-context of "
                 <<  (min_output_t - min_input_t);
     min_input_t = std::max(min_input_t, min_output_t - left_context);
   }
   if (right_context != -1) {
     if (max_input_t < max_output_t + right_context)
       KALDI_ERR << "You requested --right-context=" << right_context
                 << ", but example only has right-context of "
                 <<  (max_input_t - max_output_t);
     max_input_t = std::min(max_input_t, max_output_t + right_context);
   }
   FilterExample(eg,
                 min_input_t, max_input_t,
                 min_output_t, max_output_t,
                 eg_out);
   if (frame_shift != 0) {
     std::vector<std::string> exclude_names;  // we can later make this
     exclude_names.push_back(std::string("ivector")); // configurable.
     ShiftExampleTimes(frame_shift, exclude_names, eg_out);
   }
   return true;
 }
void kaldi::nnet3::SetDerivTimesOptions (const ComputationRequest & request, NnetOptimizeOptions * opt_config)
Definition at line 46 of file nnet-derivative-test.cc.
References ComputeMinAndMaxTimes(), ComputationRequest::inputs, KALDI_ASSERT, KALDI_LOG, NnetOptimizeOptions::max_deriv_time, NnetOptimizeOptions::min_deriv_time, ComputationRequest::outputs, and kaldi::RandInt().
Referenced by UnitTestNnetModelDerivatives().
{
   int32 min_t, max_t;
   KALDI_ASSERT(request.inputs[0].name == "input");
   const std::vector<Index> &input_indexes = request.inputs[0].indexes;
   ComputeMinAndMaxTimes(input_indexes, &min_t, &max_t);
   int32 orig_min_t = min_t, orig_max_t = max_t;
   int t_length = max_t + 1 - min_t;
   KALDI_ASSERT(t_length > 0);
   if (t_length == 1)
     return;
   if (RandInt(0, 2) == 0) {
     // remove as much as 4 frames from the left (but don't remove everything).
     min_t += std::min(4, RandInt(0, t_length - 1));
     opt_config->min_deriv_time = min_t;
     t_length = max_t + 1 - min_t;
     KALDI_ASSERT(t_length > 0);
   }
   if (RandInt(0, 2) == 0) {
     max_t -= std::min(4, RandInt(0, t_length - 1));
     opt_config->max_deriv_time = max_t;
     t_length = max_t + 1 - min_t;
     KALDI_ASSERT(t_length > 0);
   }
   if (RandInt(0, 4) == 0) {
     // ensure that all derivs will be pruned away;
     // this tests more code.
     min_t = orig_min_t - 10;
     max_t = min_t + 1;
   }
   int32 output_min_t, output_max_t;
   KALDI_ASSERT(request.outputs[0].name == "output");
   ComputeMinAndMaxTimes(request.outputs[0].indexes,
                         &output_min_t, &output_max_t);
   KALDI_LOG << "ComputationRequest has output (min,max) = (" << output_min_t
             << ',' << output_max_t << "), input (min,max) = (" << orig_min_t
             << ',' << orig_max_t << "), limiting deriv times to ("
             << opt_config->min_deriv_time << ','
             << opt_config->max_deriv_time;
 }
void SetLearningRate (BaseFloat learning_rate, Nnet * nnet)
Sets the learning rate for all the components in the nnet to this value.
Definition at line 251 of file nnet-utils.cc.
References Nnet::GetComponent(), KALDI_ERR, kUpdatableComponent, Nnet::NumComponents(), Component::Properties(), and UpdatableComponent::SetLearningRate().
Referenced by main().
{
   for (int32 c = 0; c < nnet->NumComponents(); c++) {
     Component *comp = nnet->GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       // For now all updatable components inherit from class UpdatableComponent.
       // If that changes in future, we will change this code.
       UpdatableComponent *uc = dynamic_cast<UpdatableComponent*>(comp);
       if (uc == NULL)
         KALDI_ERR << "Updatable component does not inherit from class "
             "UpdatableComponent; change this code.";
       uc->SetLearningRate(learning_rate);
     }
   }
 }
void kaldi::nnet3::SetPriors (const TransitionModel & tmodel, const Vector< double > & transition_accs, double prior_floor, AmNnetSimple * am_nnet)
Definition at line 28 of file nnet3-am-train-transitions.cc.
References VectorBase< Real >::Dim(), KALDI_ASSERT, AmNnetSimple::NumPdfs(), TransitionModel::NumPdfs(), AmNnetSimple::SetPriors(), and TransitionModel::TransitionIdToPdf().
Referenced by main().
{
   KALDI_ASSERT(tmodel.NumPdfs() == am_nnet->NumPdfs());
   Vector<BaseFloat> pdf_counts(tmodel.NumPdfs());
   KALDI_ASSERT(transition_accs(0) == 0.0); // There is
   // no zero transition-id.
   for (int32 tid = 1; tid < transition_accs.Dim(); tid++) {
     int32 pdf = tmodel.TransitionIdToPdf(tid);
     pdf_counts(pdf) += transition_accs(tid);
   }
   BaseFloat sum = pdf_counts.Sum();
   KALDI_ASSERT(sum != 0.0);
   KALDI_ASSERT(prior_floor > 0.0 && prior_floor < 1.0);
   pdf_counts.Scale(1.0 / sum);
   pdf_counts.ApplyFloor(prior_floor);
   pdf_counts.Scale(1.0 / pdf_counts.Sum()); // normalize again.
   am_nnet->SetPriors(pdf_counts);
 }
void SetZero (bool is_gradient, Nnet * nnet)
Calls SetZero (with the given is_gradient parameter) on all updatable components of the nnet.
Definition at line 162 of file nnet-utils.cc.
References Nnet::GetComponent(), KALDI_ASSERT, kUpdatableComponent, Nnet::NumComponents(), Component::Properties(), and UpdatableComponent::SetZero().
Referenced by MatrixRandomizer::AddData(), VectorRandomizer::AddData(), TpMatrix< Real >::Cholesky(), CuMatrixBase< Real >::CopyFromBlock(), MatrixBase< Real >::CopyFromTp(), kaldi::ExtractWindow(), NnetComputeProb::NnetComputeProb(), NnetTrainer::NnetTrainer(), SpMatrix< Real >::Qr(), NnetComputeProb::Reset(), CuArray< T >::Resize(), PackedMatrix< Real >::Resize(), CuPackedMatrix< Real >::Resize(), CuVector< Real >::Resize(), Vector< Real >::Resize(), CuMatrix< Real >::Resize(), Matrix< Real >::Resize(), ScaleNnet(), CuPackedMatrix< Real >::SetUnit(), MatrixBase< Real >::SetUnit(), NnetTrainer::Train(), UnitTestNnetInputDerivatives(), UnitTestNnetModelDerivatives(), UnitTestNnetOptimizeWithOptions(), and MleAmSgmmGlobalAccs::ZeroAccumulators().
{
   for (int32 c = 0; c < nnet->NumComponents(); c++) {
     Component *comp = nnet->GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       UpdatableComponent *u_comp = dynamic_cast<UpdatableComponent*>(comp);
       KALDI_ASSERT(u_comp != NULL);
       u_comp->SetZero(is_gradient);
     }
   }
 }
void ShiftExampleTimes (int32 t_offset, const std::vector< std::string > & exclude_names, NnetExample * eg)
Shifts the time-index t of everything in the "eg" by adding "t_offset" to all "t" values.
This might be useful in things like clockwork RNNs that are not invariant to time-shifts, to ensure that we see different shifts of each example during training. "exclude_names" is a vector (not necessarily sorted) of names of nnet inputs that we avoid shifting the "t" values of– normally it will contain just the single string "ivector" because we always leave t=0 for any ivector.
Definition at line 159 of file nnet-example-utils.cc.
References NnetExample::io.
Referenced by SelectFromExample().
{
   if (t_offset == 0)
     return;
   std::vector<NnetIo>::iterator iter = eg->io.begin(),
       end = eg->io.end();
   for (; iter != end; iter++) {
     bool name_is_excluded = false;
     std::vector<std::string>::const_iterator
         exclude_iter = exclude_names.begin(),
         exclude_end = exclude_names.end();
     for (; exclude_iter != exclude_end; ++exclude_iter) {
       if (iter->name == *exclude_iter) {
         name_is_excluded = true;
         break;
       }
     }
     if (!name_is_excluded) {
       // name is not something like "ivector" that we exclude from shifting.
       std::vector<Index>::iterator index_iter = iter->indexes.begin(),
           index_end = iter->indexes.end();
       for (; index_iter != index_end; ++index_iter)
         index_iter->t += t_offset;
     }
   }
 }
void kaldi::nnet3::SortSubmatLists (const std::vector< std::vector< std::pair< int32, int32 > > > submat_lists, std::vector< std::vector< std::pair< int32, int32 > > > * sorted_submat_lists, int32 * max_submat_list_size)
Definition at line 87 of file nnet-compile-utils.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by SplitLocations().
 {
   *max_submat_list_size = 0;
   sorted_submat_lists->reserve(submat_lists.size());
   KALDI_ASSERT(submat_lists.size() > 0);
   for (int32 i = 0; i < submat_lists.size(); i++) {
     if (submat_lists[i].size() > *max_submat_list_size)
       *max_submat_list_size = submat_lists[i].size();
     sorted_submat_lists->push_back(submat_lists[i]);
     std::sort((*sorted_submat_lists)[i].begin(),
               (*sorted_submat_lists)[i].end(),
               FirstElementComparator());
   }
 }
void SplitLocations (const std::vector< std::vector< std::pair< int32, int32 > > > & submat_lists, std::vector< std::vector< std::pair< int32, int32 > > > * split_lists)
The input to this function is a vector of lists of pairs, and this function splits it up into a list of vectors of pairs.
In order to make the lists all the same length it may have to insert "dummy" pairs with value (-1, -1). In addition, this function implement certain heuristics to break up the list into pairs in a particular desirable way, as we will describe below.
submat_lists.dim() may be large e.g. 1024 (it usually represents a minibatch size), but the maximum size of the lists will usually be fairly small e.g. no more than 4 or so, as it represents the number of terms in a hand-coded summation expression.
The use of this function is in interpreting a command to set each row of a matrix to a sum of terms. Each pair represents an input term, interpreted as (index-of-matrix, row-index), which represents a vector that will form part of the sum.
It would be possible to simply pad at the end with (-1, -1), but this function also makes an attempt to pad more carefully so that for the most part, each output vector of pairs has inputs from only one matrix, i.e. the pair.first values are all the same. This will allow us to use a potentially more efficient command in the compiled code. It doesn't have to be 100% optimal. Note: in the most common case, all the lists will have the same length and padding will not be necessary at all.
See documentation here: Forward computation for Descriptors (SplitLocations)
Definition at line 337 of file nnet-compile-utils.cc.
References ComputeSubmatIndexHistogram(), rnnlm::i, SortSubmatLists(), and SplitLocationsUsingSubmatHistogram().
Referenced by Compiler::DoForwardComputationFromSubmatLocationsList(), SplitLocationsBackward(), and UnitTestSplitLocations().
{
   // a histogram of the submat_indexes in the submat_lists
   // each occurence in a given submat_list is considered unique so we maintain
   // a vector to count each occurrence separately.
   // The i'th element in the vector corresponds to the count of
   // the (i+1)'th occurrence of a submat_index in a submat_list
   unordered_map<int32, std::vector<int32> > submat_histogram;
   int32 max_submat_list_size = 0;
   // initializing a vector of list of pairs to store the sorted submat_lists
   std::vector<std::vector< std::pair<int32, int32> > >
       sorted_submat_lists;
   SortSubmatLists(submat_lists, &sorted_submat_lists, &max_submat_list_size);
   ComputeSubmatIndexHistogram(sorted_submat_lists, &submat_histogram);
   // the vector has same information as the submat_histogram, but it is
   // suitable for sorting according to frequency. The first elements of pairs
   // can be repeated, these correspond to different occurrences in the same list
   std::vector<std::pair<int32, int32> > submat_histogram_vector;
   // copy the key, occurence_counts from submat_histogram to a vector
   unordered_map<int32, std::vector<int32> >::iterator hist_iter;
   for (hist_iter = submat_histogram.begin();
        hist_iter != submat_histogram.end();
        ++hist_iter) {
     for (int32 i = 0; i < (hist_iter->second).size(); i++)  {
       submat_histogram_vector.push_back(
           std::make_pair(hist_iter->first, (hist_iter->second)[i]));
     }
   }
   SplitLocationsUsingSubmatHistogram(max_submat_list_size, &sorted_submat_lists,
                                      &submat_histogram_vector, split_lists);
 }
void SplitLocationsBackward (const std::vector< std::vector< std::pair< int32, int32 > > > & submat_lists, std::vector< std::vector< std::pair< int32, int32 > > > * split_lists)
This function has the same interface as SplitLocations(); however, it ensures certain additional properties of the output "split_lists", which are necessary because of the way it is used in backprop code.
For each sub-list sublist = (*split_lists)[i], the properties it ensures are: Either:
all pairs in the list "sublist" are unique (except that the special pair (-1, -1) may be repeated), Or:
the .first values in the list "sublist" are all the same, and the .second have a special property [see the function HasContiguousProperty in nnet-compile.cc]- basically that if we list the .second elements, each unique number that appears there appears only in one contiguous range, e.g. the list [ 6 6 6 1 5 5 5 ] has this property, but [ 1 2 1 ] does not. (however, -1's are not subject to this limitation, so [ -1 4 -1 ] satisfies the property). This function ensures this property by first calling SplitLocations, and then doing further splitting as necessary to ensure the property. However, if as a result it needs to split any given initially-split list into more than 2 sub-lists, it will print a warning (once per process). If we have to split into too many lists it will generate inefficient computations, and we will need to extend the backprop code to support more general types of operation. If all elements of submat_lists are empty, the output split_lists will be the empty vector.
Definition at line 469 of file nnet-compile-utils.cc.
References ConvertToIndexes(), EnsureContiguousProperty(), rnnlm::i, rnnlm::j, SplitLocations(), and SplitPairList().
Referenced by Compiler::DoBackwardComputationFromSubmatLocationsList(), and UnitTestSplitLocationsBackward().
{
   std::vector<std::vector<std::pair<int32, int32> > > split_lists_intermediate;
   // Split the submat_lists
   SplitLocations(submat_lists, &split_lists_intermediate);
   for (size_t i = 0; i < split_lists_intermediate.size(); i++) {
     int32 first_value;
     std::vector<int32> second_values;
     if (ConvertToIndexes(split_lists_intermediate[i],
                          &first_value, &second_values)) {
       // the .first values are the same
       if (first_value == -1) continue;  // don't output anything for this.
       std::vector<std::vector<int32> > second_values_split;
       EnsureContiguousProperty(second_values, &second_values_split);
       if (second_values_split.size() == 1) {
         // this branch is an optimization for speed.
         split_lists->push_back(split_lists_intermediate[i]);
       } else {
         for (size_t j = 0; j < second_values_split.size(); j++) {
           split_lists->resize(split_lists->size() + 1);
           const std::vector<int32> &input_list = second_values_split[j];
           std::vector<std::pair<int32, int32> > &output_list =
               split_lists->back();
           output_list.resize(input_list.size());
           int32 size = input_list.size();
           for (int32 k = 0; k < size; k++) {
             int32 row = input_list[k];
             if (row == -1) output_list[k].first = -1;
             else output_list[k].first = first_value;
             output_list[k].second = row;
           }
         }
       }
     } else {
       // the .first values are not the same
       // splitting the list of pairs to ensure unique pairs, unless it is
       // (-1,-1)
       std::vector<std::vector<std::pair<int32, int32> > > new_split_lists;
       SplitPairList(split_lists_intermediate[i],
                     &new_split_lists);
       for (int32 j = 0; j < new_split_lists.size(); j++)  {
         split_lists->push_back(new_split_lists[j]);
       }
     }
   }
 }
static void kaldi::nnet3::SplitLocationsUsingSubmatHistogram (int32 max_submat_list_size, std::vector< std::vector< std::pair< int32, int32 > > > * sorted_submat_lists, std::vector< std::pair< int32, int32 > > * submat_histogram_vector, std::vector< std::vector< std::pair< int32, int32 > > > * split_lists) static
Definition at line 243 of file nnet-compile-utils.cc.
References ExtractGivenPairsFromSubmatLists(), ExtractLastPairFromSubmatLists(), FindSubmatIndexInSubmatLists(), rnnlm::i, and SecondElementComparator().
Referenced by SplitLocations().
{
   // sort the submat_histogram_vector based on second element of pair
   // in descending order then first element of pair in descending order
   std::sort(submat_histogram_vector->begin(),
             submat_histogram_vector->end(), SecondElementComparator);
   int32 prev_max_remaining_submat_list_size = max_submat_list_size;
   std::vector<std::pair<int32, int32> >::iterator iter;
   for (iter = submat_histogram_vector->begin();
        iter != submat_histogram_vector->end();
        ++iter)  {
     std::pair<int32, int32> submat_index_and_count = *iter;
     std::vector<std::vector<std::pair<int32, int32> >::iterator>
         output_iterator_list;
     int32 max_remaining_submat_list_size = 0;
     FindSubmatIndexInSubmatLists(submat_index_and_count.first,
                                  sorted_submat_lists,
                                  &output_iterator_list,
                                  &max_remaining_submat_list_size);
     if (max_remaining_submat_list_size
         < prev_max_remaining_submat_list_size)  {
       // since we will have a smaller max_remaining_submat_list_size by
       // splitting this submat_index into a seperate list,
       // we will split it;
       std::vector<std::pair<int32, int32> > list_of_pairs;
       ExtractGivenPairsFromSubmatLists(output_iterator_list,
                                        sorted_submat_lists,
                                        &list_of_pairs);
       split_lists->push_back(list_of_pairs);
       prev_max_remaining_submat_list_size = max_remaining_submat_list_size;
     }
   }
   // rearrange the remaining pairs into lists where
   // pairs with multiple first elements are allowed
   // Note : we don't yet know if there is any advantage of having multiple
   // calls to the same submat in kAddRowsMulti. If this is actually helpful
   // then use the sorted_histogram_vector to first copy submat_indexes which
   // did not make it to kAddRows calls
   for (int32 i = 0; i < prev_max_remaining_submat_list_size; i++) {
     std::vector<std::pair<int32, int32> > list_of_pairs;
     ExtractLastPairFromSubmatLists(sorted_submat_lists,
                                    &list_of_pairs);
     split_lists->push_back(list_of_pairs);
   }
 }
void kaldi::nnet3::SplitPairList (std::vector< std::pair< int32, int32 > > & list, std::vector< std::vector< std::pair< int32, int32 > > > * split_lists)
Definition at line 438 of file nnet-compile-utils.cc.
References rnnlm::i, rnnlm::j, and KALDI_ERR.
Referenced by SplitLocationsBackward().
{
   split_lists->clear();
   for (int32 i = 0; i < list.size(); i++)  {
     // searching for the new pair in the new_split_lists
     bool added_pair = false;
     if ( list[i].first == -1)
       continue;
     for (int32 j = 0; j < split_lists->size(); j++)  {
       std::vector<std::pair<int32, int32> >::const_iterator iter
           = std::find_if((*split_lists)[j].begin(),
                          (*split_lists)[j].end(),
                          PairIsEqualComparator(list[i]));
       if (iter == (*split_lists)[j].end()) {
         // this pair is not in this list
         (*split_lists)[j][i] = list[i];
         added_pair = true;
         break;
       }
     }
     if (!added_pair)  {
       std::vector<std::pair<int32, int32> > list_of_pairs(list.size(),
                                                           std::make_pair(-1, -1));
       list_of_pairs[i] = list[i];
       split_lists->push_back(list_of_pairs);
     }
   }
   if (split_lists->size() == 0)
     KALDI_ERR << "Input list has just dummy pairs";
 }
static bool kaldi::nnet3::StringsApproxEqual (const std::string & a, const std::string & b) static
Definition at line 30 of file nnet-component-test.cc.
References KALDI_WARN.
Referenced by TestNnetComponentAddScale(), TestNnetComponentCopy(), TestNnetComponentUpdatable(), TestNnetComponentVectorizeUnVectorize(), and TestStringsApproxEqual().
{
   if (a == b || a.size() != b.size())
     return true;
   size_t size = a.size();
   for (size_t pos = 0; pos < size; pos++) {
     if (a[pos] != b[pos]) {
       if (!isdigit(a[pos]) || !isdigit(b[pos]))
         goto fail;
       // if it's not the last digit in the string, goto fail
       if (pos + 1 != size && isdigit(a[pos+1]))
         goto fail;
       size_t pos2;
       for (pos2 = pos - 1; pos2 > 0; pos2--) {
         if (a[pos2] == '.') break;  // we accept this difference: we went backwards and found a '.'
         if (!isdigit(a[pos2]))  // we reject this difference: we went back and
                                 // found non-digit before '.' -> not floating
                                 // point.
           goto fail;
       }
       if (pos2 == 0)
         goto fail;
     }
   }
   return true;
 fail:
   KALDI_WARN << "Info strings differ: '" << a << "' vs. '" << b << "'.";
   return false;
 }
std::string SummarizeVector (const Vector< BaseFloat > & vec)
Definition at line 462 of file nnet-parse.cc.
References VectorBase< Real >::Data(), VectorBase< Real >::Dim(), rnnlm::i, KALDI_ASSERT, rnnlm::n, PrintFloatSuccinctly(), kaldi::SplitStringToIntegers(), VectorBase< Real >::Sum(), and kaldi::VecVec().
Referenced by NonlinearComponent::Info(), and UnitTestSummarizeVector().
{
   std::ostringstream os;
   if (vec.Dim() < 10) {
     os << "[ ";
     for (int32 i = 0; i < vec.Dim(); i++) {
       PrintFloatSuccinctly(os, vec(i));
       os << ' ';
     }
     os << "]";
   } else {
     // print out mean and standard deviation, and some selected values.
     BaseFloat mean = vec.Sum() / vec.Dim(),
         stddev = sqrt(VecVec(vec, vec) / vec.Dim() - mean * mean);
     std::string percentiles_str = "0,1,2,5 10,20,50,80,90 95,98,99,100";
     std::vector<int32> percentiles;
     bool ans = SplitStringToIntegers(percentiles_str, ", ", false,
                                      &percentiles);
     KALDI_ASSERT(ans);
     os << "[percentiles(" << percentiles_str << ")=(";
     Vector<BaseFloat> vec_sorted(vec);
     std::sort(vec_sorted.Data(), vec_sorted.Data() + vec_sorted.Dim());
     int32 n = vec.Dim() - 1;
     for (size_t i = 0; i < percentiles.size(); i++) {
       int32 percentile = percentiles[i];
       BaseFloat value = vec_sorted((n * percentile) / 100);
       PrintFloatSuccinctly(os, value);
       if (i + 1 < percentiles.size())
         os << (i == 3 || i == 8 ? ' ' : ',');
     }
     os << std::setprecision(3);
     os << "), mean=" << mean << ", stddev=" << stddev << "]";
   }
   return os.str();
 }
static int32 kaldi::nnet3::SumVectorSizes (const std::vector< std::vector< int32 > > & vec) static
Definition at line 1144 of file nnet-computation-graph.cc.
Referenced by ComputeComputationPhases().
{
   int32 ans = 0;
   std::vector<std::vector<int32> >::const_iterator iter = vec.begin(),
       end = vec.end();
   for (; iter != end; ++iter)
     ans += iter->size();
   return ans;
 }
void kaldi::nnet3::TarjanSccRecursive (int32 node, const std::vector< std::vector< int32 > > & graph, int32 * global_index, std::vector< TarjanNode > * tarjan_nodes, std::vector< int32 > * tarjan_stack, std::vector< std::vector< int32 > > * sccs)
Definition at line 85 of file nnet-graph.cc.
References rnnlm::i, and KALDI_ASSERT.
Referenced by FindSccsTarjan().
{
   KALDI_ASSERT(sccs != NULL);
   KALDI_ASSERT(tarjan_nodes != NULL);
   KALDI_ASSERT(tarjan_stack != NULL);
   KALDI_ASSERT(global_index != NULL);
   KALDI_ASSERT(node >= 0 && node < graph.size());
   // Initializes the current Tarjan node.
   (*tarjan_nodes)[node].index = *global_index;
   (*tarjan_nodes)[node].lowlink = *global_index;
   *global_index += 1;
   (*tarjan_nodes)[node].on_stack = true;
   tarjan_stack->push_back(node);
   // DFS from the current node.
   for (int32 i = 0; i < graph[node].size(); ++i) {
     int32 next = graph[node][i];
     if ((*tarjan_nodes)[next].index == -1) {
       // First time we see this node.
       TarjanSccRecursive(next, graph,
                          global_index, tarjan_nodes, tarjan_stack, sccs);
       (*tarjan_nodes)[node].lowlink = std::min((*tarjan_nodes)[node].lowlink,
                                                (*tarjan_nodes)[next].lowlink);
     } else if ((*tarjan_nodes)[next].on_stack) {
       // Next node is on the stack -- back edge. We can't use the lowlink of
       // next node, because that may point to the index of the root, while the
       // current node can't be the root.
       (*tarjan_nodes)[node].lowlink = std::min((*tarjan_nodes)[node].lowlink,
                                                (*tarjan_nodes)[next].index);
     }
   }
   // Output SCC.
   if ((*tarjan_nodes)[node].index == (*tarjan_nodes)[node].lowlink) {
     std::vector<int32> scc;
     int32 pop_node;
     do {
       pop_node = tarjan_stack->back();
       tarjan_stack->pop_back();
       (*tarjan_nodes)[pop_node].on_stack = false;
       scc.push_back(pop_node);
     } while (pop_node != node);
     KALDI_ASSERT(pop_node == node);
     sccs->push_back(scc);
   }
 }
void kaldi::nnet3::TestNnetComponentAddScale (Component * c)
Definition at line 84 of file nnet-component-test.cc.
References Component::Add(), Component::Copy(), Component::Info(), KALDI_ASSERT, Component::Scale(), and StringsApproxEqual().
Referenced by UnitTestNnetComponent().
{
   Component *c2 = c->Copy();
   Component *c3 = c2->Copy();
   c3->Add(0.5, *c2);
   c2->Scale(1.5);
   KALDI_ASSERT(StringsApproxEqual(c2->Info(), c3->Info()));
   delete c2;
   delete c3;
 }
void kaldi::nnet3::TestNnetComponentCopy (Component * c)
Definition at line 75 of file nnet-component-test.cc.
References Component::Copy(), Component::Info(), KALDI_ERR, and StringsApproxEqual().
Referenced by UnitTestNnetComponent().
{
   Component *c2 = c->Copy();
   if (!StringsApproxEqual(c->Info(), c2->Info())) {
     KALDI_ERR << "Expected info strings to be equal: '"
               << c->Info() << "' vs. '" << c2->Info() << "'";
   }
   delete c2;
 }
void kaldi::nnet3::TestNnetComponentIo (Component * c)
Definition at line 61 of file nnet-component-test.cc.
References KALDI_ASSERT, kaldi::Rand(), Component::ReadNew(), and Component::Write().
Referenced by UnitTestNnetComponent().
{
   bool binary = (Rand() % 2 == 0);
   std::ostringstream os1;
   c->Write(os1, binary);
   std::istringstream is(os1.str());
   Component *c2 = Component::ReadNew(is, binary);
   std::ostringstream os2;
   c2->Write(os2, binary);
   if (!binary) {
     KALDI_ASSERT(os2.str() == os1.str());
   }
   delete c2;
 }
void kaldi::nnet3::TestNnetComponentUpdatable (Component * c)
Definition at line 126 of file nnet-component-test.cc.
References Component::Copy(), UpdatableComponent::DotProduct(), UpdatableComponent::Info(), KALDI_ASSERT, KALDI_ERR, kUpdatableComponent, UpdatableComponent::NumParameters(), Component::Properties(), VectorBase< Real >::Scale(), Component::Scale(), UpdatableComponent::SetZero(), StringsApproxEqual(), and kaldi::VecVec().
Referenced by UnitTestNnetComponent().
{
   if (!(c->Properties() & kUpdatableComponent))
     return;
   UpdatableComponent *uc = dynamic_cast<UpdatableComponent*>(c);
   if (uc == NULL) {
     KALDI_ASSERT(!(c->Properties() & kUpdatableComponent) &&
                  "Component returns updatable flag but does not inherit "
                  "from UpdatableComponent");
     return;
   }
   if(!(uc->Properties() & kUpdatableComponent)){
     // testing that if it declares itself as non-updatable,
     // Scale() and Add() and SetZero() have no effect.
     KALDI_ASSERT(uc->NumParameters() == 0);
     KALDI_ASSERT(uc->DotProduct(*uc) == 0);
     UpdatableComponent *uc2 = dynamic_cast<UpdatableComponent*>(uc->Copy());
     uc2->Scale(7.0);
     uc2->Add(3.0, *uc);
     KALDI_ASSERT(StringsApproxEqual(uc2->Info(), uc->Info()));
     uc->SetZero(false);
     KALDI_ASSERT(StringsApproxEqual(uc2->Info(), uc->Info()));
     delete uc2;
   } else {
     KALDI_ASSERT(uc->NumParameters() != 0);
     UpdatableComponent *uc2 = dynamic_cast<UpdatableComponent*>(uc->Copy()),
         *uc3 = dynamic_cast<UpdatableComponent*>(uc->Copy());
     // testing some expected invariances of scale and add.
     uc2->Scale(5.0);
     uc2->Add(3.0, *uc3);
     uc3->Scale(8.0);
     // now they should both be scaled to 8 times the original component.
     if (!StringsApproxEqual(uc2->Info(), uc3->Info())) {
       KALDI_ERR << "Expected info strings to be equal: '"
                 << uc2->Info() << "' vs. '" << uc3->Info() << "'";
     }
     // testing that scaling by 0.5 works the same whether
     // done on the vectorized paramters or via Scale().
     Vector<BaseFloat> vec2(uc->NumParameters());
     uc2->Vectorize(&vec2);
     vec2.Scale(0.5);
     uc2->UnVectorize(vec2);
     uc3->Scale(0.5);
     KALDI_ASSERT(uc2->Info() == uc3->Info());
     // testing that SetZero() works the same whether done on the vectorized
     // paramters or via SetZero(), and that unvectorizing something that's been
     // zeroed gives us zero parameters.
     uc2->Vectorize(&vec2);
     vec2.SetZero();
     uc2->UnVectorize(vec2);
     uc3->SetZero(false);
     uc3->Vectorize(&vec2);
     KALDI_ASSERT(uc2->Info() == uc3->Info() && VecVec(vec2, vec2) == 0.0);
     delete uc2;
     delete uc3;
   }
 }
void kaldi::nnet3::TestNnetComponentVectorizeUnVectorize (Component * c)
Definition at line 94 of file nnet-component-test.cc.
References kaldi::ApproxEqual(), Component::Copy(), UpdatableComponent::DotProduct(), rnnlm::i, UpdatableComponent::Info(), KALDI_ASSERT, kUpdatableComponent, UpdatableComponent::NumParameters(), Component::Properties(), UpdatableComponent::SetZero(), StringsApproxEqual(), UpdatableComponent::UnVectorize(), and UpdatableComponent::Vectorize().
Referenced by UnitTestNnetComponent().
{
   if (!(c->Properties() & kUpdatableComponent))
     return;
   UpdatableComponent *uc = dynamic_cast<UpdatableComponent*>(c);
   KALDI_ASSERT(uc != NULL);
   UpdatableComponent *uc2 = dynamic_cast<UpdatableComponent*>(uc->Copy());
   uc2->SetZero(false);
   Vector<BaseFloat> params(uc2->NumParameters());
   uc2->Vectorize(&params);
   KALDI_ASSERT(params.Min()==0.0 && params.Sum()==0.0);
   uc->Vectorize(&params);
   uc2->UnVectorize(params);
   KALDI_ASSERT(StringsApproxEqual(uc2->Info(), uc->Info()));
   BaseFloat x = uc2->DotProduct(*uc2), y = uc->DotProduct(*uc),
       z = uc2->DotProduct(*uc);
   KALDI_ASSERT(ApproxEqual(x, y) && ApproxEqual(y, z));
   Vector<BaseFloat> params2(uc2->NumParameters());
   uc2->Vectorize(&params2);
   for(int i = 0; i < params.Dim(); i++)
     KALDI_ASSERT(params(i) == params2(i));
   delete uc2;
 }
void kaldi::nnet3::TestNnetDecodable (const ComputationRequest & request, const std::vector< Matrix< BaseFloat > > & inputs, const Nnet & nnet, const CuMatrixBase< BaseFloat > & reference_output)
Definition at line 31 of file nnet-compute-test.cc.
Referenced by UnitTestNnetCompute().
{
   // DecodableAmNnetSimpleOptions opts;
   // This is a placeholder for where we'll eventually test either the decodable
   // object or something similar to it (e.g. a base class)
 }
bool kaldi::nnet3::TestSimpleComponentDataDerivative (const Component & c, BaseFloat perturb_delta)
Definition at line 284 of file nnet-component-test.cc.
References kaldi::ApproxEqual(), Component::Backprop(), rnnlm::i, Component::InputDim(), KALDI_LOG, KALDI_WARN, kBackpropNeedsInput, kBackpropNeedsOutput, kaldi::kTrans, Component::OutputDim(), Component::Propagate(), Component::Properties(), kaldi::RandInt(), CuMatrixBase< Real >::SetRandn(), kaldi::TraceMatMat(), and Component::Type().
Referenced by UnitTestNnetComponent().
{
   int32 input_dim = c.InputDim(),
       output_dim = c.OutputDim(),
       num_rows = RandInt(1, 100);
   int32 properties = c.Properties();
   CuMatrix<BaseFloat> input_data(num_rows, input_dim),
       output_data(num_rows, output_dim),
       output_deriv(num_rows, output_dim);
   input_data.SetRandn();
   output_deriv.SetRandn();
   c.Propagate(NULL, input_data, &output_data);
   CuMatrix<BaseFloat> input_deriv(num_rows, input_dim), empty_mat;
   c.Backprop("foobar", NULL,
              ((properties & kBackpropNeedsInput) ? input_data : empty_mat),
              ((properties & kBackpropNeedsOutput) ? output_data : empty_mat),
              output_deriv, NULL, &input_deriv);
   int32 test_dim = 3;
   BaseFloat original_objf = TraceMatMat(output_deriv, output_data, kTrans);
   Vector<BaseFloat> measured_objf_change(test_dim),
       predicted_objf_change(test_dim);
   for (int32 i = 0; i < test_dim; i++) {
     CuMatrix<BaseFloat> perturbed_input_data(num_rows, input_dim),
         perturbed_output_data(num_rows, output_dim);
     perturbed_input_data.SetRandn();
     perturbed_input_data.Scale(perturb_delta);
     // at this point, perturbed_input_data contains the offset at the input data.
     predicted_objf_change(i) = TraceMatMat(perturbed_input_data, input_deriv,
                                            kTrans);
     perturbed_input_data.AddMat(1.0, input_data);
     c.Propagate(NULL, perturbed_input_data, &perturbed_output_data);
     measured_objf_change(i) = TraceMatMat(output_deriv, perturbed_output_data,
                                           kTrans) - original_objf;
   }
   KALDI_LOG << "Predicted objf-change = " << predicted_objf_change;
   KALDI_LOG << "Measured objf-change = " << measured_objf_change;
   BaseFloat threshold = 0.1;
   bool ans = ApproxEqual(predicted_objf_change, measured_objf_change, threshold);
   if (!ans)
     KALDI_WARN << "Data-derivative test failed, component-type="
                << c.Type() << ", input-dim=" << input_dim
                << ", output-dim=" << output_dim;
   if (c.Type() == "NormalizeComponent" && input_dim == 1) {
     // derivatives are mathematically zero, but the measured and predicted
     // objf have different roundoff and the relative differences are large.
     // this is not unexpected.
     KALDI_LOG << "Accepting deriv differences since it is NormalizeComponent "
               << "with dim=1.";
     return true;
   }
   return ans;
 }
bool kaldi::nnet3::TestSimpleComponentModelDerivative (const Component & c, BaseFloat perturb_delta, bool test_derivative)
Definition at line 345 of file nnet-component-test.cc.
References kaldi::ApproxEqual(), Component::Backprop(), Component::Copy(), UpdatableComponent::DotProduct(), rnnlm::i, Component::InputDim(), KALDI_ASSERT, KALDI_LOG, KALDI_WARN, kBackpropNeedsInput, kBackpropNeedsOutput, kaldi::kTrans, kUpdatableComponent, Component::OutputDim(), UpdatableComponent::PerturbParams(), Component::Propagate(), Component::Properties(), kaldi::RandInt(), CuMatrixBase< Real >::SetRandn(), UpdatableComponent::SetZero(), kaldi::TraceMatMat(), and Component::Type().
Referenced by UnitTestNnetComponent().
{
   int32 input_dim = c.InputDim(),
       output_dim = c.OutputDim(),
       num_rows = RandInt(1, 100);
   int32 properties = c.Properties();
   if ((properties & kUpdatableComponent) == 0) {
     // nothing to test.
     return true;
   }
   CuMatrix<BaseFloat> input_data(num_rows, input_dim),
       output_data(num_rows, output_dim),
       output_deriv(num_rows, output_dim);
   input_data.SetRandn();
   output_deriv.SetRandn();
   c.Propagate(NULL, input_data, &output_data);
   BaseFloat original_objf = TraceMatMat(output_deriv, output_data, kTrans);
   Component *c_copy = c.Copy();
   const UpdatableComponent *uc = dynamic_cast<const UpdatableComponent*>(&c);
   UpdatableComponent *uc_copy = dynamic_cast<UpdatableComponent*>(c_copy);
   KALDI_ASSERT(uc != NULL && uc_copy != NULL);
   if (test_derivative) {
     bool is_gradient = true;
     uc_copy->SetZero(is_gradient);
   }
   CuMatrix<BaseFloat> input_deriv(num_rows, input_dim), empty_mat;
   c.Backprop("foobar", NULL,
              ((properties & kBackpropNeedsInput) ? input_data : empty_mat),
              ((properties & kBackpropNeedsOutput) ? output_data : empty_mat),
              output_deriv, c_copy,
              (RandInt(0, 1) == 0 ? &input_deriv : NULL));
   if (!test_derivative) { // Just testing that the model update is downhill.
     CuMatrix<BaseFloat> new_output_data(num_rows, output_dim);
     c_copy->Propagate(NULL, input_data, &new_output_data);
     BaseFloat new_objf = TraceMatMat(output_deriv, new_output_data, kTrans);
     bool ans = (new_objf > original_objf);
     if (!ans) {
       KALDI_WARN << "After update, new objf is not better than the original objf: "
                  << new_objf << " <= " << original_objf;
     }
     delete c_copy;
     return ans;
   } else {
     // check that the model derivative is accurate.
     int32 test_dim = 3;
     Vector<BaseFloat> measured_objf_change(test_dim),
         predicted_objf_change(test_dim);
     for (int32 i = 0; i < test_dim; i++) {
       CuMatrix<BaseFloat> perturbed_output_data(num_rows, output_dim);
       Component *c_perturbed = c.Copy();
       UpdatableComponent *uc_perturbed =
           dynamic_cast<UpdatableComponent*>(c_perturbed);
       KALDI_ASSERT(uc_perturbed != NULL);
       uc_perturbed->PerturbParams(perturb_delta);
       predicted_objf_change(i) = uc_copy->DotProduct(*uc_perturbed) -
           uc_copy->DotProduct(*uc);
       c_perturbed->Propagate(NULL, input_data, &perturbed_output_data);
       measured_objf_change(i) = TraceMatMat(output_deriv, perturbed_output_data,
                                             kTrans) - original_objf;
       delete c_perturbed;
     }
     KALDI_LOG << "Predicted objf-change = " << predicted_objf_change;
     KALDI_LOG << "Measured objf-change = " << measured_objf_change;
     BaseFloat threshold = 0.1;
     bool ans = ApproxEqual(predicted_objf_change, measured_objf_change,
                            threshold);
     if (!ans)
       KALDI_WARN << "Model-derivative test failed, component-type="
                  << c.Type() << ", input-dim=" << input_dim
                  << ", output-dim=" << output_dim;
     delete c_copy;
     return ans;
   }
 }
void kaldi::nnet3::TestSimpleComponentPropagateProperties (const Component & c)
Definition at line 188 of file nnet-component-test.cc.
References kaldi::AssertEqual(), Component::Backprop(), Component::Copy(), Component::InputDim(), KALDI_ERR, kBackpropAdds, kBackpropInPlace, kBackpropNeedsInput, kBackpropNeedsOutput, kLinearInInput, kLinearInParameters, kPropagateAdds, kPropagateInPlace, Component::OutputDim(), Component::Propagate(), Component::Properties(), kaldi::RandInt(), Component::Scale(), CuMatrixBase< Real >::Scale(), CuMatrixBase< Real >::SetRandn(), and Component::Type().
Referenced by UnitTestNnetComponent().
{
   int32 properties = c.Properties();
   Component *c_copy = NULL, *c_copy_scaled = NULL;
   if (RandInt(0, 1) == 0)
     c_copy = c.Copy();  // This will test backprop with an updatable component.
   if (RandInt(0, 1) == 0 &&
       (properties & kLinearInParameters)) {
     c_copy_scaled = c.Copy();  // This will test backprop with an updatable component.
     c_copy_scaled->Scale(0.5);
   }
   int32 input_dim = c.InputDim(),
       output_dim = c.OutputDim(),
       num_rows = RandInt(1, 100);
   CuMatrix<BaseFloat> input_data(num_rows, input_dim);
   input_data.SetRandn();
   CuMatrix<BaseFloat>
       input_data_scaled(input_data),
       output_data1(num_rows, output_dim),
       output_data2(num_rows, output_dim),
       output_data3(input_data),
       output_data4(num_rows, output_dim),
       output_data5(num_rows, output_dim);
   output_data2.Add(1.0);
   input_data_scaled.Scale(2.0);
   if ((properties & kPropagateAdds) && (properties & kPropagateInPlace)) {
     KALDI_ERR << "kPropagateAdds and kPropagateInPlace flags are incompatible.";
   }
   c.Propagate(NULL, input_data, &output_data1);
   c.Propagate(NULL, input_data, &output_data2);
   if (properties & kPropagateInPlace) {
     c.Propagate(NULL, output_data3, &output_data3);
     if (!output_data1.ApproxEqual(output_data3)) {
       KALDI_ERR << "Test of kPropagateInPlace flag for component of type "
                 << c.Type() << " failed.";
     }
   }
   if (properties & kPropagateAdds)
     output_data2.Add(-1.0); // remove the offset
   AssertEqual(output_data1, output_data2);
   if (c_copy_scaled) {
     c_copy_scaled->Propagate(NULL, input_data, &output_data4);
     output_data4.Scale(2.0);  // we scaled the parameters by 0.5 above, and the
     // output is supposed to be linear in the parameter value.
     AssertEqual(output_data1, output_data4);
   }
   if (properties & kLinearInInput) {
     c.Propagate(NULL, input_data_scaled, &output_data5);
     output_data5.Scale(0.5);
     AssertEqual(output_data1, output_data5);
   }
   CuMatrix<BaseFloat> output_deriv(num_rows, output_dim);
   output_deriv.SetRandn();
   CuMatrix<BaseFloat> input_deriv1(num_rows, input_dim),
       input_deriv2(num_rows, input_dim),
       input_deriv3(output_deriv);
   input_deriv2.Add(1.0);
   CuMatrix<BaseFloat> empty_mat;
   // test with input_deriv1 that's zero
   c.Backprop("foobar", NULL,
              ((properties & kBackpropNeedsInput) ? input_data : empty_mat),
              ((properties & kBackpropNeedsOutput) ? output_data1 : empty_mat),
              output_deriv,
              c_copy,
              &input_deriv1);
   // test with input_deriv2 that's all ones.
   c.Backprop("foobar", NULL,
              ((properties & kBackpropNeedsInput) ? input_data : empty_mat),
              ((properties & kBackpropNeedsOutput) ? output_data1 : empty_mat),
              output_deriv,
              c_copy,
              &input_deriv2);
   // test backprop in place, if supported.
   if (properties & kBackpropInPlace) {
     c.Backprop("foobar", NULL,
                ((properties & kBackpropNeedsInput) ? input_data : empty_mat),
                ((properties & kBackpropNeedsOutput) ? output_data1 : empty_mat),
                input_deriv3,
                c_copy,
                &input_deriv3);
   }
   if (properties & kBackpropAdds)
     input_deriv2.Add(-1.0);  // subtract the offset.
   AssertEqual(input_deriv1, input_deriv2);
   if (properties & kBackpropInPlace)
     AssertEqual(input_deriv1, input_deriv3);
   delete c_copy;
   delete c_copy_scaled;
 }
void kaldi::nnet3::TestStringsApproxEqual ()
Definition at line 117 of file nnet-component-test.cc.
References KALDI_ASSERT, and StringsApproxEqual().
Referenced by main().
{
   // we must test the test.
   KALDI_ASSERT(!StringsApproxEqual("a", "b"));
   KALDI_ASSERT(!StringsApproxEqual("1", "2"));
   KALDI_ASSERT(StringsApproxEqual("1.234", "1.235"));
   KALDI_ASSERT(StringsApproxEqual("x 1.234 y", "x 1.235 y"));
   KALDI_ASSERT(StringsApproxEqual("x 1.234 y 6.41", "x 1.235 y 6.49"));
 }
void kaldi::nnet3::UnitTestComputeGraphTranspose ()
Definition at line 148 of file nnet-graph-test.cc.
References AssertGraphEqual(), BuildTestGraph(), BuildTestGraphTranspose(), ComputeGraphTranspose(), and KALDI_ASSERT.
Referenced by main().
{
   std::vector<std::vector<int32> > graph;
   BuildTestGraph(&graph);
   std::vector<std::vector<int32> > graph_transpose;
   ComputeGraphTranspose(graph, &graph_transpose);
   std::vector<std::vector<int32> > ref_graph_transpose;
   BuildTestGraphTranspose(&ref_graph_transpose);
   KALDI_ASSERT(AssertGraphEqual(graph_transpose, ref_graph_transpose));
 }
void kaldi::nnet3::UnitTestComputeTopSortOrder ()
Definition at line 187 of file nnet-graph-test.cc.
References AssertVectorEqual(), BuildTestSccGraph(), BuildTestTopSortOrder(), ComputeTopSortOrder(), and KALDI_ASSERT.
Referenced by main().
{
   std::vector<std::vector<int32> > scc_graph;
   BuildTestSccGraph(&scc_graph);
   std::vector<int32> node_to_order;
   ComputeTopSortOrder(scc_graph, &node_to_order);
   std::vector<int32> ref_node_to_order;
   BuildTestTopSortOrder(&ref_node_to_order);
   KALDI_ASSERT(AssertVectorEqual(node_to_order, ref_node_to_order));
 }
void kaldi::nnet3::UnitTestConfigLineParse ()
Definition at line 26 of file nnet-parse-test.cc.
References ConfigLine::GetValue(), ConfigLine::HasUnusedValues(), KALDI_ASSERT, ConfigLine::ParseLine(), and ConfigLine::UnusedValues().
Referenced by main().
{
   std::string str;
   {
     ConfigLine cfl;
     str = "xx=yyy foo=bar  baz=123 ba=1:2";
     bool status = cfl.ParseLine(str);
     KALDI_ASSERT(status);
     KALDI_ASSERT(cfl.HasUnusedValues());
     std::string str_value;
     KALDI_ASSERT(cfl.GetValue("xx", &str_value));
     KALDI_ASSERT(str_value == "yyy");
     KALDI_ASSERT(cfl.HasUnusedValues());
     KALDI_ASSERT(cfl.GetValue("foo", &str_value));
     KALDI_ASSERT(str_value == "bar");
     KALDI_ASSERT(cfl.HasUnusedValues());
     KALDI_ASSERT(!cfl.GetValue("xy", &str_value));
     KALDI_ASSERT(cfl.GetValue("baz", &str_value));
     KALDI_ASSERT(str_value == "123");
     std::vector<int32> int_values;
     KALDI_ASSERT(!cfl.GetValue("xx", &int_values));
     KALDI_ASSERT(cfl.GetValue("baz", &int_values));
     KALDI_ASSERT(cfl.HasUnusedValues());
     KALDI_ASSERT(int_values.size() == 1 && int_values[0] == 123);
     KALDI_ASSERT(cfl.GetValue("ba", &int_values));
     KALDI_ASSERT(int_values.size() == 2 && int_values[0] == 1 && int_values[1] == 2);
     KALDI_ASSERT(!cfl.HasUnusedValues());
   }
   {
     ConfigLine cfl;
     str = "baz=x y z pp = qq ab =cd ac= bd";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "baz=x y z pp = qq ab=cd ac=bd";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "baz";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "a=b baz";
     KALDI_ASSERT(cfl.ParseLine(str) && cfl.UnusedValues() == "a=b baz");
   }
   {
     ConfigLine cfl;
     str = "a=b baz ";
     KALDI_ASSERT(cfl.ParseLine(str) && cfl.UnusedValues() == "a=b baz");
   }
   {
     ConfigLine cfl;
     str = "a=b =c";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "baz='x y z' pp=qq ab=cd ac=bd";
     KALDI_ASSERT(cfl.ParseLine(str));
     std::string str_value;
     KALDI_ASSERT(cfl.GetValue("baz", &str_value));
     KALDI_ASSERT(str_value == "x y z");
     KALDI_ASSERT(cfl.GetValue("pp", &str_value));
     KALDI_ASSERT(str_value == "qq");
     KALDI_ASSERT(cfl.UnusedValues() == "ab=cd ac=bd");
     KALDI_ASSERT(cfl.GetValue("ab", &str_value));
     KALDI_ASSERT(str_value == "cd");
     KALDI_ASSERT(cfl.UnusedValues() == "ac=bd");
     KALDI_ASSERT(cfl.HasUnusedValues());
     KALDI_ASSERT(cfl.GetValue("ac", &str_value));
     KALDI_ASSERT(str_value == "bd");
     KALDI_ASSERT(!cfl.HasUnusedValues());
   }
   {
     ConfigLine cfl;
     str = "baz= pp = qq flag=t ";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = " baz= pp=qq flag=t  ";
     KALDI_ASSERT(cfl.ParseLine(str));
     std::string str_value;
     KALDI_ASSERT(cfl.GetValue("baz", &str_value));
     KALDI_ASSERT(str_value == "");
     KALDI_ASSERT(cfl.GetValue("pp", &str_value));
     KALDI_ASSERT(str_value == "qq");
     KALDI_ASSERT(cfl.HasUnusedValues());
     KALDI_ASSERT(cfl.GetValue("flag", &str_value));
     KALDI_ASSERT(str_value == "t");
     KALDI_ASSERT(!cfl.HasUnusedValues());
     bool bool_value = false;
     KALDI_ASSERT(cfl.GetValue("flag", &bool_value));
     KALDI_ASSERT(bool_value);
   }
   {
     ConfigLine cfl;
     str = "_baz=a -pp=qq";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "0baz=a pp=qq";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "-baz=a pp=qq";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "_baz'=a pp=qq";
     KALDI_ASSERT(!cfl.ParseLine(str));
   }
   {
     ConfigLine cfl;
     str = "baz=g";
     KALDI_ASSERT(cfl.ParseLine(str));
     bool flag;
     KALDI_ASSERT(!cfl.GetValue("baz", &flag));
   }
   {
     ConfigLine cfl;
     str = "_baz1=a pp=qq";
     KALDI_ASSERT(cfl.ParseLine(str));
     std::string str_value;
     KALDI_ASSERT(cfl.GetValue("_baz1", &str_value));
   }
 }
void kaldi::nnet3::UnitTestDescriptorIo ()
Definition at line 88 of file nnet-descriptor-test.cc.
References DescriptorTokenize(), GenRandDescriptor(), rnnlm::i, KALDI_ASSERT, KALDI_LOG, KALDI_WARN, Descriptor::Parse(), kaldi::Rand(), and Descriptor::WriteConfig().
Referenced by main().
{
   for (int32 i = 0; i < 100; i++) {
     int32 num_nodes = 1 + Rand() % 5;
     std::vector<std::string> node_names(num_nodes);
     for (int32 i = 0; i < node_names.size(); i++) {
       std::ostringstream ostr;
       ostr << "a" << (i+1);
       node_names[i] = ostr.str();
     }
     Descriptor desc;
     std::ostringstream ostr;
     GenRandDescriptor(num_nodes, &desc);
     desc.WriteConfig(ostr, node_names);
     Descriptor desc2(desc), desc3, desc4;
     desc3 = desc;
     std::vector<std::string> tokens;
     DescriptorTokenize(ostr.str(), &tokens);
     tokens.push_back("end of input");
     std::istringstream istr(ostr.str());
     const std::string *next_token = &(tokens[0]);
     bool ans = desc4.Parse(node_names, &next_token);
     KALDI_ASSERT(ans);
     std::ostringstream ostr2;
     desc2.WriteConfig(ostr2, node_names);
     std::ostringstream ostr3;
     desc3.WriteConfig(ostr3, node_names);
     std::ostringstream ostr4;
     desc4.WriteConfig(ostr4, node_names);
     KALDI_ASSERT(ostr.str() == ostr2.str());
     KALDI_ASSERT(ostr.str() == ostr3.str());
     KALDI_LOG << "x = " << ostr.str();
     KALDI_LOG << "y = " << ostr4.str();
     if (ostr.str() != ostr4.str()) {
       KALDI_WARN << "x and y differ: checking that it's due to Offset normalization.";
       KALDI_ASSERT(ostr.str().find("Offset(Offset") != std::string::npos ||
                    (ostr.str().find("Offset(") != std::string::npos &&
                     ostr.str().find(", 0)") != std::string::npos));
     }
   }
 }
void kaldi::nnet3::UnitTestDescriptorTokenize ()
Definition at line 195 of file nnet-parse-test.cc.
References DescriptorTokenize(), and KALDI_ASSERT.
Referenced by main().
{
   std::vector<std::string> lines;
   std::string str = "(,test )";
   KALDI_ASSERT(DescriptorTokenize(str, &lines));
   KALDI_ASSERT(lines[0] == "(" && lines[1] == "," && lines[2] == "test" && lines[3] == ")");
   str = "(,1test )";
   KALDI_ASSERT(!DescriptorTokenize(str, &lines));
   str = "t (,-1 )";
   KALDI_ASSERT(DescriptorTokenize(str, &lines));
   KALDI_ASSERT(lines.size() == 5 && lines[0] == "t" && lines[3] == "-1");
   str = "   sd , -112 )";
   KALDI_ASSERT(DescriptorTokenize(str, &lines));
   KALDI_ASSERT(lines.size() == 4 && lines[0] == "sd" && lines[2] == "-112");
   str = "   sd , +112 )";
   KALDI_ASSERT(DescriptorTokenize(str, &lines));
   KALDI_ASSERT(lines.size() == 4 && lines[0] == "sd" && lines[2] == "+112");
   str = "foo";
   KALDI_ASSERT(DescriptorTokenize(str, &lines));
   KALDI_ASSERT(lines.size() == 1 && lines[0] == "foo");
 }
void kaldi::nnet3::UnitTestEnsureContiguousProperty ()
Definition at line 222 of file nnet-compile-utils-test.cc.
References EnsureContiguousProperty(), HasContiguousProperty(), rnnlm::i, rnnlm::j, KALDI_ASSERT, and kaldi::RandInt().
Referenced by main().
{
   for (int32 k = 0; k < 10; k++) {
     int32 size = RandInt(0, 5);
     std::vector<int32> indexes(size);
     for (int32 i = 0; i < size; i++)
       indexes[i] = RandInt(-1, 4);
     std::vector<std::pair<int32, int32> > reverse_indexes;
     bool ans = HasContiguousProperty(indexes, &reverse_indexes);
     if (ans) { // has contiguous property -> EnsureContiguousProperty should do
                // nothing.
       std::vector<std::vector<int32> > indexes_split;
       EnsureContiguousProperty(indexes, &indexes_split);
       if (indexes.size() == 0 ||
           *std::max_element(indexes.begin(), indexes.end()) == -1) {
         KALDI_ASSERT(indexes_split.size() == 0);
       } else {
         KALDI_ASSERT(indexes_split.size() == 1 &&
                      indexes_split[0] == indexes);
       }
     } else {
       std::vector<std::vector<int32> > indexes_split;
       EnsureContiguousProperty(indexes, &indexes_split);
       KALDI_ASSERT(indexes_split.size() > 1);
       for (int32 i = 0; i < indexes.size(); i++) {
         int32 this_val = indexes[i];
         bool found = (this_val == -1);  // not looking for anything if
                                         // this_val is -1.
         for (int32 j = 0; j < indexes_split.size(); j++) {
           if (found) {
             KALDI_ASSERT(indexes_split[j][i] == -1);
           } else {
             if (indexes_split[j][i] == this_val) {
               found = true;
             } else {
               KALDI_ASSERT(indexes_split[j][i] == -1);
             }
           }
         }
         KALDI_ASSERT(found);
         for (int32 j = 0; j < indexes_split.size(); j++) {
           KALDI_ASSERT(indexes_split[j].size() == indexes.size() &&
                        HasContiguousProperty(indexes_split[j], &reverse_indexes));
         }
       }
     }
   }
 }
void kaldi::nnet3::UnitTestFindSccs ()
Definition at line 160 of file nnet-graph-test.cc.
References AssertGraphEqual(), BuildTestGraph(), BuildTestSccs(), FindSccs(), and KALDI_ASSERT.
Referenced by main().
{
   std::vector<std::vector<int32> > graph;
   BuildTestGraph(&graph);
   std::vector<std::vector<int32> > sccs;
   FindSccs(graph, &sccs);
   std::vector<std::vector<int32> > ref_sccs;
   BuildTestSccs(&ref_sccs);
   KALDI_ASSERT(AssertGraphEqual(sccs, ref_sccs));
 }
void kaldi::nnet3::UnitTestGeneralDescriptor ()
Definition at line 134 of file nnet-descriptor-test.cc.
References GeneralDescriptor::ConvertToDescriptor(), DescriptorTokenize(), GenRandDescriptor(), rnnlm::i, KALDI_ERR, KALDI_LOG, KALDI_WARN, GeneralDescriptor::Parse(), kaldi::Rand(), and Descriptor::WriteConfig().
Referenced by main().
{
   for (int32 i = 0; i < 100; i++) {
     int32 num_nodes = 1 + Rand() % 5;
     std::vector<std::string> node_names(num_nodes);
     for (int32 i = 0; i < node_names.size(); i++) {
       std::ostringstream ostr;
       ostr << "a" << (i+1);
       node_names[i] = ostr.str();
     }
     Descriptor desc;
     std::ostringstream ostr;
     GenRandDescriptor(num_nodes, &desc);
     desc.WriteConfig(ostr, node_names);
     Descriptor desc2(desc), desc3;
     desc3 = desc;
     std::vector<std::string> tokens;
     DescriptorTokenize(ostr.str(), &tokens);
     tokens.push_back("end of input");
     std::istringstream istr(ostr.str());
     const std::string *next_token = &(tokens[0]);
     GeneralDescriptor *gen_desc = GeneralDescriptor::Parse(node_names,
                                                            &next_token);
     if (*next_token != "end of input")
       KALDI_ERR << "Parsing Descriptor, expected end of input but got "
                 << "'" <<  *next_token << "'";
     Descriptor *desc4 = gen_desc->ConvertToDescriptor();
     std::ostringstream ostr2;
     desc4->WriteConfig(ostr2, node_names);
     KALDI_LOG << "Original descriptor was: " << ostr.str();
     KALDI_LOG << "Parsed descriptor was: " << ostr2.str();
     if (ostr2.str() != ostr.str())
       KALDI_WARN << "Strings differed.  Check manually.";
     delete gen_desc;
     delete desc4;
   }
 }
void kaldi::nnet3::UnitTestGeneralDescriptorSpecial ()
Definition at line 199 of file nnet-descriptor-test.cc.
References KALDI_ASSERT, and NormalizeTextDescriptor().
Referenced by main().
{
   std::vector<std::string> names;
   names.push_back("a");
   names.push_back("b");
   names.push_back("c");
   names.push_back("d");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "a") == "a");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Offset(Offset(a, 3, 5), 2, 1)") == "Offset(a, 5, 6)");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Offset(Sum(a, b), 2, 1)") ==
                "Sum(Offset(a, 2, 1), Offset(b, 2, 1))");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Sum(Append(a, b), Append(c, d))") ==
                "Append(Sum(a, c), Sum(b, d))");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Append(Append(a, b), Append(c, d))") ==
                "Append(a, b, c, d)");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Sum(a, b, c, d)") ==
                "Sum(a, Sum(b, Sum(c, d)))");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Sum(a)") == "a");
   KALDI_ASSERT(NormalizeTextDescriptor(names, "Offset(a, 0)") == "a");
 }
void kaldi::nnet3::UnitTestHasContiguousProperty ()
Definition at line 185 of file nnet-compile-utils-test.cc.
References HasContiguousProperty(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_LOG, and kaldi::RandInt().
Referenced by main().
{
   for (int32 k = 0; k < 10; k++) {
     int32 size = RandInt(0, 5);
     std::vector<int32> indexes(size);
     for (int32 i = 0; i < size; i++)
       indexes[i] = RandInt(-1, 4);
     std::vector<std::pair<int32, int32> > reverse_indexes;
     bool ans = HasContiguousProperty(indexes, &reverse_indexes);
     if (!ans) { // doesn't have contiguous propety.
       KALDI_LOG << "no.";
       bool found_example = false;
       for (int32 i = 0; i < size; i++) {
         if (indexes[i] != -1) {
           bool found_not_same = false;
           for (int32 j = i + 1; j < size; j++) {
             if (indexes[j] != indexes[i]) found_not_same = true;
             else if (found_not_same) found_example = true;  // found something like x y x.
           }
         }
       }
       KALDI_ASSERT(found_example);
     } else {
       KALDI_LOG << "yes.";
       for (int32 i = 0; i < reverse_indexes.size(); i++) {
         for (int32 j = reverse_indexes[i].first;
              j < reverse_indexes[i].second; j++) {
           KALDI_ASSERT(indexes[j] == i);
           indexes[j] = -1;
         }
       }
       for (int32 i = 0; i < size; i++)  // make sure all indexes covered.
         KALDI_ASSERT(indexes[i] == -1);
     }
   }
 }
void kaldi::nnet3::UnitTestIndexIo ()
Definition at line 27 of file nnet-common-test.cc.
References rnnlm::i, KALDI_ERR, kaldi::RandInt(), ReadIndexVector(), and WriteIndexVector().
Referenced by main().
{
   std::vector<Index> indexes(RandInt(0, 10));
   for (int32 i = 0; i < indexes.size(); i++) {
     if (i == 0 || RandInt(0, 1) == 0) {
       indexes[i].n = RandInt(-1, 2);
       indexes[i].t = RandInt(-150, 150);
       indexes[i].x = RandInt(-1, 1);
     } else {
       // this case gets optimized while writing. (if abs(diff-in-t) < 125).
       indexes[i].n = indexes[i-1].n;
       indexes[i].t = indexes[i-1].t + RandInt(-127, 127);
       indexes[i].x = indexes[i-1].x;
     }
   }
   std::ostringstream os;
   bool binary = (RandInt(0, 1) == 0);
   WriteIndexVector(os, binary, indexes);
   std::vector<Index> indexes2;
   if (RandInt(0, 1) == 0)
     indexes2 = indexes;
   std::istringstream is(os.str());
   ReadIndexVector(is, binary, &indexes2);
   if (indexes != indexes2) {
     WriteIndexVector(std::cerr, false, indexes);
     std::cerr << "  vs. \n";
     WriteIndexVector(std::cerr, false, indexes2);
     std::cerr << "\n";
     KALDI_ERR << "Indexes differ.";
   }
 }
void kaldi::nnet3::UnitTestMakeSccGraph ()
Definition at line 172 of file nnet-graph-test.cc.
References AssertGraphEqual(), BuildTestGraph(), BuildTestSccGraph(), BuildTestSccs(), KALDI_ASSERT, and MakeSccGraph().
Referenced by main().
{
   std::vector<std::vector<int32> > graph;
   BuildTestGraph(&graph);
   std::vector<std::vector<int32> > sccs;
   BuildTestSccs(&sccs);
   std::vector<std::vector<int32> > scc_graph;
   MakeSccGraph(graph, sccs, &scc_graph);
   std::vector<std::vector<int32> > ref_scc_graph;
   BuildTestSccGraph(&ref_scc_graph);
   KALDI_ASSERT(AssertGraphEqual(scc_graph, ref_scc_graph));
 }
void kaldi::nnet3::UnitTestNnetAnalyze ()
Definition at line 39 of file nnet-analyze-test.cc.
References ComputationChecker::Check(), CheckComputationOptions::check_rewrite, NnetComputation::commands, ComputeExampleComputationRequestSimple(), Compiler::CreateComputation(), ComputationAnalysis::DataInvalidatedCommand(), ComputationAnalysis::FirstAccess(), GenerateConfigSequence(), NnetComputation::GetSubmatrixStrings(), Analyzer::Init(), rnnlm::j, KALDI_LOG, ComputationAnalysis::LastAccess(), ComputationAnalysis::LastWriteAccess(), rnnlm::n, NnetComputation::Print(), PrintCommand(), kaldi::RandInt(), Nnet::ReadConfig(), and NnetComputation::submatrices.
Referenced by main().
{
   for (int32 n = 0; n < 20; n++) {
     struct NnetGenerationOptions gen_config;
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     for (size_t j = 0; j < configs.size(); j++) {
       KALDI_LOG << "Input config[" << j << "] is: " << configs[j];
       std::istringstream is(configs[j]);
       nnet.ReadConfig(is);
     }
     ComputationRequest request;
     std::vector<Matrix<BaseFloat> > inputs;
     ComputeExampleComputationRequestSimple(nnet, &request, &inputs);
     NnetComputation computation;
     Compiler compiler(request, nnet);
     CompilerOptions opts;
     compiler.CreateComputation(opts, &computation);
     std::ostringstream os;
     computation.Print(os, nnet);
     KALDI_LOG << "Generated computation is: " << os.str();
     CheckComputationOptions check_config;
     // we can do the rewrite check since it's before optimization.
     check_config.check_rewrite = true;
     ComputationChecker checker(check_config, nnet, computation);
     checker.Check();
     Analyzer analyzer;
     analyzer.Init(nnet, computation);
     ComputationAnalysis analysis(computation, analyzer);
     // The following output is to be eyeballed by a person.
     std::vector<std::string> submatrix_strings;
     computation.GetSubmatrixStrings(nnet, &submatrix_strings);
     int32 nc = computation.commands.size();
     for (int32 n = 0; n < 30; n++) {
       int32 s = RandInt(1, computation.submatrices.size() - 1);
       int32 c = RandInt(0, nc - 1);
       KALDI_LOG << "First access of submatrix " << submatrix_strings[s]
                 << " is command " << PrintCommand(nc, analysis.FirstAccess(s));
       KALDI_LOG << "Last access of submatrix " << submatrix_strings[s]
                 << " is command " << PrintCommand(nc, analysis.LastAccess(s));
       KALDI_LOG << "Last write access of submatrix " << submatrix_strings[s]
                 << " is command " << PrintCommand(nc, analysis.LastWriteAccess(s));
       KALDI_LOG << "Data present in " << submatrix_strings[s]
                 << " at command " << c << " is invalidated at command "
                 << PrintCommand(nc, analysis.DataInvalidatedCommand(c, s));
     }
   }
 }
void kaldi::nnet3::UnitTestNnetCompile ()
Definition at line 28 of file nnet-compile-test.cc.
References ComputeExampleComputationRequestSimple(), Compiler::CreateComputation(), GenerateConfigSequence(), rnnlm::j, KALDI_LOG, rnnlm::n, ComputationRequest::Print(), NnetComputation::Print(), and Nnet::ReadConfig().
Referenced by main().
{
   for (int32 n = 0; n < 20; n++) {
     struct NnetGenerationOptions gen_config;
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     for (size_t j = 0; j < configs.size(); j++) {
       KALDI_LOG << "Input config[" << j << "] is: " << configs[j];
       std::istringstream is(configs[j]);
       nnet.ReadConfig(is);
     }
     ComputationRequest request;
     std::vector<Matrix<BaseFloat> > inputs;
     ComputeExampleComputationRequestSimple(nnet, &request, &inputs);
     KALDI_LOG << "Computation request is:";
     request.Print(std::cerr);
     NnetComputation computation;
     Compiler compiler(request, nnet);
     CompilerOptions opts;
     compiler.CreateComputation(opts, &computation);
     std::ostringstream os;
     computation.Print(os, nnet);
     KALDI_LOG << "Generated computation is: " << os.str();
   }
 }
void kaldi::nnet3::UnitTestNnetComponent ()
Definition at line 433 of file nnet-component-test.cc.
References GenerateRandomSimpleComponent(), Component::Info(), KALDI_ERR, KALDI_LOG, rnnlm::n, TestNnetComponentAddScale(), TestNnetComponentCopy(), TestNnetComponentIo(), TestNnetComponentUpdatable(), TestNnetComponentVectorizeUnVectorize(), TestSimpleComponentDataDerivative(), TestSimpleComponentModelDerivative(), and TestSimpleComponentPropagateProperties().
Referenced by main().
{
   for (int32 n = 0; n < 200; n++)  {
     Component *c = GenerateRandomSimpleComponent();
     KALDI_LOG << c->Info();
     TestNnetComponentIo(c);
     TestNnetComponentCopy(c);
     TestNnetComponentAddScale(c);
     TestNnetComponentVectorizeUnVectorize(c);
     TestNnetComponentUpdatable(c);
     TestSimpleComponentPropagateProperties(*c);
     if (!TestSimpleComponentDataDerivative(*c, 1.0e-04) &&
         !TestSimpleComponentDataDerivative(*c, 1.0e-03) &&
         !TestSimpleComponentDataDerivative(*c, 1.0e-05) &&
         !TestSimpleComponentDataDerivative(*c, 1.0e-06))
       KALDI_ERR << "Component data-derivative test failed";
     if (!TestSimpleComponentModelDerivative(*c, 1.0e-04, false) &&
         !TestSimpleComponentModelDerivative(*c, 1.0e-03, false) &&
         !TestSimpleComponentModelDerivative(*c, 1.0e-06, false))
       KALDI_ERR << "Component downhill-update test failed";
     if (!TestSimpleComponentModelDerivative(*c, 1.0e-04, true) &&
         !TestSimpleComponentModelDerivative(*c, 1.0e-03, true) &&
         !TestSimpleComponentModelDerivative(*c, 1.0e-05, true) &&
         !TestSimpleComponentModelDerivative(*c, 1.0e-06, true))
       KALDI_ERR << "Component model-derivative test failed";
     delete c;
   }
 }
void kaldi::nnet3::UnitTestNnetCompute ()
Definition at line 40 of file nnet-compute-test.cc.
References NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), NnetComputer::Backward(), ComputationChecker::Check(), CheckComputationOptions::check_rewrite, NnetComputation::ComputeCudaIndexes(), ComputeExampleComputationRequestSimple(), Compiler::CreateComputation(), NnetComputeOptions::debug, NnetComputer::Forward(), GenerateConfigSequence(), NnetComputer::GetInputDeriv(), NnetComputer::GetOutput(), rnnlm::i, ComputationRequest::inputs, rnnlm::j, KALDI_LOG, rnnlm::n, Optimize(), ComputationRequest::outputs, NnetComputation::Print(), kaldi::RandInt(), Nnet::ReadConfig(), CuMatrixBase< Real >::SetRandn(), CuMatrixBase< Real >::Sum(), and TestNnetDecodable().
Referenced by main().
{
   for (int32 n = 0; n < 20; n++) {
     struct NnetGenerationOptions gen_config;
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     for (size_t j = 0; j < configs.size(); j++) {
       KALDI_LOG << "Input config[" << j << "] is: " << configs[j];
       std::istringstream is(configs[j]);
       nnet.ReadConfig(is);
     }
     ComputationRequest request;
     std::vector<Matrix<BaseFloat> > inputs;
     ComputeExampleComputationRequestSimple(nnet, &request, &inputs);
     NnetComputation computation;
     Compiler compiler(request, nnet);
     CompilerOptions opts;
     compiler.CreateComputation(opts, &computation);
     {
       std::ostringstream os;
       computation.Print(os, nnet);
       KALDI_LOG << "Generated computation is: " << os.str();
     }
     CheckComputationOptions check_config;
     // we can do the rewrite check since it's before optimization.
     check_config.check_rewrite = true;
     ComputationChecker checker(check_config, nnet, computation);
     checker.Check();
     if (RandInt(0, 1) == 0) {
       NnetOptimizeOptions opt_config;
       Optimize(opt_config, nnet, request, &computation);
       {
         std::ostringstream os;
         computation.Print(os, nnet);
         KALDI_LOG << "Optimized computation is: " << os.str();
       }
     }
     NnetComputeOptions compute_opts;
     if (RandInt(0, 1) == 0)
       compute_opts.debug = true;
     computation.ComputeCudaIndexes();
     NnetComputer computer(compute_opts,
                           computation,
                           nnet,
                           &nnet);
     // provide the input to the computation.
     for (size_t i = 0; i < request.inputs.size(); i++) {
       CuMatrix<BaseFloat> temp(inputs[i]);
       KALDI_LOG << "Input sum is " << temp.Sum();
       computer.AcceptInput(request.inputs[i].name, &temp);
     }
     computer.Forward();
     const CuMatrixBase<BaseFloat> &output(computer.GetOutput("output"));
     TestNnetDecodable(request, inputs, nnet, output);
     KALDI_LOG << "Output sum is " << output.Sum();
     CuMatrix<BaseFloat> output_deriv(output.NumRows(), output.NumCols());
     output_deriv.SetRandn();
     // output_deriv sum won't be informative so don't print it.
     if (request.outputs[0].has_deriv)
       computer.AcceptOutputDeriv("output", &output_deriv);
     computer.Backward();
     for (size_t i = 0; i < request.inputs.size(); i++) {
       if (request.inputs[i].has_deriv) {
         const CuMatrixBase<BaseFloat> &in_deriv =
             computer.GetInputDeriv(request.inputs[i].name);
         KALDI_LOG << "Input-deriv sum for input '"
                   << request.inputs[i].name << "' is " << in_deriv.Sum();
       }
     }
   }
 }
void kaldi::nnet3::UnitTestNnetContext ()
Definition at line 27 of file nnet-utils-test.cc.
References ComputeSimpleNnetContext(), GenerateConfigSequence(), KALDI_LOG, rnnlm::n, NnetInfo(), and Nnet::ReadConfig().
Referenced by main().
{
   for (int32 n = 0; n < 20; n++) {
     struct NnetGenerationOptions gen_config;
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     std::istringstream is(configs[0]);
     nnet.ReadConfig(is);
     // this test doesn't really test anything except that it runs;
     // we manually inspect the output.
     int32 left_context, right_context;
     ComputeSimpleNnetContext(nnet, &left_context, &right_context);
     KALDI_LOG << "Left,right-context= " << left_context << ","
               << right_context << " for config: " << configs[0];
     KALDI_LOG << "Info for nnet is: " << NnetInfo(nnet);
   }
 }
void kaldi::nnet3::UnitTestNnetExample ()
Definition at line 35 of file nnet-example-test.cc.
References ExampleApproxEqual(), GenerateSimpleNnetTrainingExample(), KALDI_ASSERT, rnnlm::n, kaldi::RandInt(), NnetExample::Read(), and NnetExample::Write().
Referenced by main().
{
   for (int32 n = 0; n < 50; n++) {
     NnetExample eg;
     int32 num_supervised_frames = RandInt(1, 10),
                    left_context = RandInt(0, 5),
                   right_context = RandInt(0, 5),
                       input_dim = RandInt(1, 10),
                      output_dim = RandInt(5, 10),
                     ivector_dim = RandInt(-1, 2);
     GenerateSimpleNnetTrainingExample(num_supervised_frames, left_context,
                                       right_context, input_dim, output_dim,
                                       ivector_dim, &eg);
     bool binary = (RandInt(0, 1) == 0);
     std::ostringstream os;
     eg.Write(os, binary);
     NnetExample eg_copy;
     if (RandInt(0, 1) == 0)
       eg_copy = eg;
     std::istringstream is(os.str());
     eg_copy.Read(is, binary);
     std::ostringstream os2;
     eg_copy.Write(os2, binary);
     if (binary) {
       KALDI_ASSERT(os.str() == os2.str());
       KALDI_ASSERT(eg_copy == eg);
     }
     KALDI_ASSERT(ExampleApproxEqual(eg, eg_copy, 0.1));
   }
 }
void kaldi::nnet3::UnitTestNnetInputDerivatives ()
Definition at line 258 of file nnet-derivative-test.cc.
References NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), CuMatrixBase< Real >::AddMat(), kaldi::ApproxEqual(), NnetComputer::Backward(), ComputationChecker::Check(), CheckComputationOptions::check_rewrite, ComputeExampleComputationRequestSimple(), rnnlm::d, NnetComputeOptions::debug, NnetComputer::Forward(), GenerateConfigSequence(), NnetComputer::GetInputDeriv(), NnetComputer::GetOutput(), rnnlm::i, ComputationRequest::inputs, rnnlm::j, KALDI_ASSERT, KALDI_ERR, KALDI_LOG, KALDI_WARN, kaldi::kTrans, rnnlm::n, ComputationRequest::need_model_derivative, Optimize(), Nnet::OutputDim(), ComputationRequest::outputs, kaldi::RandInt(), Nnet::ReadConfig(), CuMatrix< Real >::Resize(), CuMatrixBase< Real >::SetRandn(), SetZero(), and kaldi::TraceMatMat().
Referenced by main().
{
   int32 num_tries = 20, num_success = 0;
   for (int32 n = 0; n < num_tries; n++) {
     struct NnetGenerationOptions gen_config;
     //gen_config.allow_nonlinearity = false;
     //gen_config.allow_recursion = false;
     //gen_config.allow_final_nonlinearity = true;
     bool allow_optimization = true;
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     for (size_t j = 0; j < configs.size(); j++) {
       KALDI_LOG << "Input config[" << j << "] is: " << configs[j];
       std::istringstream is(configs[j]);
       nnet.ReadConfig(is);
     }
     ComputationRequest request;
     std::vector<Matrix<BaseFloat> > inputs;
     ComputeExampleComputationRequestSimple(nnet, &request, &inputs);
     // make sure that all inputs and outputs have derivatives requested/provided,
     // and that the model-update (need_model_derivative) is not requested.
     request.need_model_derivative = false;
     for (int32 i = 0; i < request.inputs.size(); i++)
       request.inputs[i].has_deriv = true;
     request.outputs[0].has_deriv = true;
     NnetComputation computation;
     Compiler compiler(request, nnet);
     CompilerOptions opts;
     compiler.CreateComputation(opts, &computation);
     {
       std::ostringstream os;
       computation.Print(os, nnet);
       KALDI_LOG << "Generated computation is: " << os.str();
     }
     CheckComputationOptions check_config;
     // we can do the rewrite check since it's before optimization.
     check_config.check_rewrite = true;
     ComputationChecker checker(check_config, nnet, computation);
     checker.Check();
     if (RandInt(0, 3) != 0 && allow_optimization) {
       NnetOptimizeOptions opt_config;
       // opt_config.initialize_undefined = false;  // temp
       Optimize(opt_config, nnet, request, &computation);
       std::ostringstream os;
       computation.Print(os, nnet);
       KALDI_LOG << "Optimized computation is: " << os.str();
     }
     NnetComputeOptions compute_opts;
     if (RandInt(0, 1) == 0)
       compute_opts.debug = true;
     computation.ComputeCudaIndexes();
     // the only reason we might need to provide the &nnet parameter is if the
     // StoreStats() operation had been requested.  We made sure no model update
     // is being performed.
     NnetComputer computer(compute_opts,
                           computation,
                           nnet,
                           &nnet);
     int32 num_directions = 3;  // must be >= 1.  Best if it's >1, will reduce
                                // the probability of random failures.
     // the order of these vectors is:
     // [ un-perturbed, perturbed-1, perturbed-2, perturbed-3, un-perturbed ].
     // we compute un-perturbed twice to double-check the model did not change.
     std::vector<BaseFloat> measured_objf(num_directions + 2, 0.0),
         predicted_objf_change(num_directions + 2, 0.0);
     BaseFloat delta = 1.0e-03;
     // output_deriv is the derivative of the objective function w.r.t. the
     // (single) output.  We make the objf a linear function of the output and
     // just set the output_deriv to be a random matrix, which defines the
     // objective function.
     CuMatrix<BaseFloat> output_deriv;
     output_deriv.Resize(request.outputs[0].indexes.size(),
                         nnet.OutputDim("output"));
     output_deriv.SetRandn();
     std::vector<CuMatrix<BaseFloat> > delta_inputs(inputs.size());
     std::vector<CuMatrix<BaseFloat> > input_derivs(inputs.size());
     // pass 0 is the forward pass with the un-perturbed features; so is
     // pass num_directions + 1.
     // Other passes are with various differently-perturbed versions of
     // the features.
     for (int32 pass = 0; pass <= num_directions + 1; pass++) {
       // provide the input to the computations.
       for (size_t i = 0; i < request.inputs.size(); i++) {
         CuMatrix<BaseFloat> temp(inputs[i]);
         if (pass > 0 && pass <= num_directions) {  // Perturb the input randomly.
           delta_inputs[i].Resize(inputs[i].NumRows(), inputs[i].NumCols());
           delta_inputs[i].SetRandn();
           delta_inputs[i].Scale(delta);
           // if there are >1 inputs, sometimes set the delta for input 0 to
           // zero.  might sometimes give more accurate test of error in iVector
           // derivative computation.
           if (i == 0 && request.inputs.size() > 1 && RandInt(0, 1) == 0)
             delta_inputs[i].SetZero();
           temp.AddMat(1.0, delta_inputs[i]);
           predicted_objf_change[pass] += TraceMatMat(input_derivs[i],
                                                      delta_inputs[i], kTrans);
         }
         computer.AcceptInput(request.inputs[i].name, &temp);
       }
       KALDI_LOG << "Running forward computation";
       computer.Forward();
       const CuMatrixBase<BaseFloat> &output(computer.GetOutput("output"));
       KALDI_LOG << "Output sum for pass " << pass << " is " << output.Sum();
       BaseFloat objf = TraceMatMat(output, output_deriv, kTrans);
       measured_objf[pass] = objf;
       if (pass == 0) {
         // We need to compute the input derivatives.
         CuMatrix<BaseFloat> temp(output_deriv);
         computer.AcceptOutputDeriv("output", &temp);
         KALDI_LOG << "Running backward computation";
         computer.Backward();
         for (size_t i = 0; i < request.inputs.size(); i++) {
           input_derivs[i] = computer.GetInputDeriv(request.inputs[i].name);
           KALDI_LOG << "Input-deriv norm for '" << request.inputs[i].name
                     << "' is " << input_derivs[i].FrobeniusNorm();
         }
       }
     }
     KALDI_ASSERT(ApproxEqual(measured_objf[0],
                              measured_objf[num_directions + 1]));
     Vector<BaseFloat> predicted_objf_change_vec(num_directions),
         measured_objf_change_vec(num_directions);
     for (int32 d = 0; d < num_directions; d++) {
       BaseFloat predicted_change = predicted_objf_change[d+1],
                  measured_change = measured_objf[d+1] - measured_objf[0];
       predicted_objf_change_vec(d) = predicted_change;
       measured_objf_change_vec(d) = measured_change;
     }
     KALDI_LOG << "Vector of predicted objf-change is: "
               << predicted_objf_change_vec;
     KALDI_LOG << "Vector of measured objf-change is: "
               << measured_objf_change_vec;
     BaseFloat delta_thresh = 0.1;
     if (!ApproxEqual(predicted_objf_change_vec,
                      measured_objf_change_vec, delta_thresh)) {
       KALDI_WARN << "Predicted and measured objf-changes differ too much.";
     } else {
       num_success++;
     }
   }
   KALDI_LOG << "Input-derivative check succeeded for " << num_success << " out of "
             << num_tries << " tries.";
   if (num_success < num_tries - (2 + num_tries / 5))
     KALDI_ERR << "Failed too many times.";
 }
void kaldi::nnet3::UnitTestNnetIo ()
Definition at line 27 of file nnet-nnet-test.cc.
References GenerateConfigSequence(), KALDI_ASSERT, rnnlm::n, kaldi::Rand(), Nnet::Read(), Nnet::ReadConfig(), and Nnet::Write().
Referenced by main().
                       {
   for (int32 n = 0; n < 100; n++) {
     struct NnetGenerationOptions gen_config;
     bool binary = (Rand() % 2 == 0);
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     std::istringstream is(configs[0]);
     nnet.ReadConfig(is);
     std::ostringstream os;
     nnet.Write(os, binary);
     const std::string &original_output = os.str();
     std::istringstream nnet_is(original_output);
     nnet.Read(nnet_is, binary);
     std::istringstream nnet_is2(original_output);
     Nnet nnet2;
     nnet2.Read(nnet_is2, binary);
     std::ostringstream os2, os3;
     nnet.Write(os2, binary);
     nnet2.Write(os3, binary);
     if (binary) {
       KALDI_ASSERT(os2.str() == original_output);
       KALDI_ASSERT(os3.str() == original_output);
     }
   }
 }
void kaldi::nnet3::UnitTestNnetMergeExamples ()
Definition at line 67 of file nnet-example-test.cc.
References GenerateSimpleNnetTrainingExample(), rnnlm::i, KALDI_LOG, MergeExamples(), rnnlm::n, kaldi::RandInt(), and NnetExample::Write().
Referenced by main().
{
   for (int32 n = 0; n < 50; n++) {
     int32 num_supervised_frames = RandInt(1, 10),
                    left_context = RandInt(0, 5),
                   right_context = RandInt(0, 5),
                       input_dim = RandInt(1, 10),
                      output_dim = RandInt(5, 10),
                     ivector_dim = RandInt(-1, 2);
     int32 num_egs = RandInt(1, 4);
     std::vector<NnetExample> egs_to_be_merged(num_egs);
     for (int32 i = 0; i < num_egs; i++) {
       NnetExample eg;
       // sometimes omit the ivector.  just tests things a bit more
       // thoroughly.
       GenerateSimpleNnetTrainingExample(num_supervised_frames, left_context,
                                         right_context, input_dim, output_dim,
                                         RandInt(0, 1) == 0 ? 0 : ivector_dim,
                                         &eg);
       KALDI_LOG << i << "'th example to be merged is: ";
       eg.Write(std::cerr, false);
       egs_to_be_merged[i].Swap(&eg);
     }
     NnetExample eg_merged;
     bool compress = (RandInt(0, 1) == 0);
     MergeExamples(egs_to_be_merged, compress, &eg_merged);
     KALDI_LOG << "Merged example is: ";
     eg_merged.Write(std::cerr, false);
   }
 }
void kaldi::nnet3::UnitTestNnetModelDerivatives ()
Definition at line 91 of file nnet-derivative-test.cc.
References NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), kaldi::ApproxEqual(), NnetComputer::Backward(), ComputationChecker::Check(), CheckComputationOptions::check_rewrite, NnetComputation::ComputeCudaIndexes(), ComputeExampleComputationRequestSimple(), Compiler::CreateComputation(), rnnlm::d, NnetComputeOptions::debug, DotProduct(), NnetComputer::Forward(), GenerateConfigSequence(), NnetComputer::GetOutput(), rnnlm::i, ComputationRequest::inputs, rnnlm::j, KALDI_ERR, KALDI_LOG, KALDI_WARN, kaldi::kTrans, rnnlm::n, ComputationRequest::need_model_derivative, Optimize(), Nnet::OutputDim(), ComputationRequest::outputs, PerturbParams(), NnetComputation::Print(), kaldi::RandInt(), Nnet::ReadConfig(), CuMatrix< Real >::Resize(), SetDerivTimesOptions(), CuMatrixBase< Real >::SetRandn(), SetZero(), and kaldi::TraceMatMat().
Referenced by main().
{
   int32 num_tries = 20, num_success = 0, num_fail = 0;
   for (int32 n = 0; n < num_tries; n++) {
     struct NnetGenerationOptions gen_config;
     //gen_config.allow_nonlinearity = false;
     //gen_config.allow_recursion = false;
     //gen_config.allow_final_nonlinearity = true;
     bool allow_optimization = true;
     bool limit_deriv_times = (RandInt(0, 2) == 0);
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     for (size_t j = 0; j < configs.size(); j++) {
       KALDI_LOG << "Input config[" << j << "] is: " << configs[j];
       std::istringstream is(configs[j]);
       nnet.ReadConfig(is);
     }
     ComputationRequest request;
     std::vector<Matrix<BaseFloat> > inputs;
     ComputeExampleComputationRequestSimple(nnet, &request, &inputs);
     // make sure that a model-derivative is requested, and an output-derivative
     // is supplied.
     request.need_model_derivative = true;
     request.outputs[0].has_deriv = true;
     // whether input-derivatives are required or not does not matter,
     // so leave it as it is in that regard.
     NnetComputation computation;
     Compiler compiler(request, nnet);
     CompilerOptions opts;
     compiler.CreateComputation(opts, &computation);
     {
       std::ostringstream os;
       computation.Print(os, nnet);
       KALDI_LOG << "Generated computation is: " << os.str();
     }
     CheckComputationOptions check_config;
     // we can do the rewrite check since it's before optimization.
     check_config.check_rewrite = true;
     ComputationChecker checker(check_config, nnet, computation);
     checker.Check();
     if (RandInt(0, 3) != 0 && allow_optimization) {
       NnetOptimizeOptions opt_config;
       if (limit_deriv_times)
         SetDerivTimesOptions(request, &opt_config);
       Optimize(opt_config, nnet, request, &computation);
       std::ostringstream os;
       computation.Print(os, nnet);
       KALDI_LOG << "Optimized computation is: " << os.str();
       check_config.check_rewrite = false;
       ComputationChecker checker_opt(check_config, nnet, computation);
       checker_opt.Check();
     }
     NnetComputeOptions compute_opts;
     if (RandInt(0, 1) == 0)
       compute_opts.debug = true;
     computation.ComputeCudaIndexes();
     Nnet nnet_deriv(nnet);
     bool is_gradient = true;
     SetZero(is_gradient, &nnet_deriv);  // forces "simple" update and unit
                                         // learning rate.
     int32 num_directions = 4;  // must be >= 1.  Best if it's >1, will reduce
                                // the probability of random failures.
     // the order of these vectors is:
     // [ un-perturbed, perturbed-1, perturbed-2, perturbed-3 ].
     std::vector<BaseFloat> measured_objf(num_directions + 1, 0.0),
         predicted_objf_change(num_directions + 1, 0.0);
     BaseFloat delta = 5.0e-04;
     // output_deriv is the derivative of the objective function w.r.t. the
     // (single) output.  We make the objf a linear function of the output and
     // just set the output_deriv to be a random matrix, which defines the
     // objective function.
     CuMatrix<BaseFloat> output_deriv;
     output_deriv.Resize(request.outputs[0].indexes.size(),
                         nnet.OutputDim("output"));
     output_deriv.SetRandn();
     // pass 0 is the forward pass with the un-perturbed model.
     // Other passes are with various differently-perturbed versions of
     // the model.
     for (int32 pass = 0; pass <= num_directions; pass++) {
       Nnet nnet_copy(nnet);
       if (pass > 0)
         PerturbParams(delta, &nnet_copy);
       NnetComputer computer(compute_opts,
                             computation,
                             nnet_copy,
                             (pass == 0 ? &nnet_deriv : &nnet_copy));
       // provide the input to the computation.
       for (size_t i = 0; i < request.inputs.size(); i++) {
         CuMatrix<BaseFloat> temp(inputs[i]);
         computer.AcceptInput(request.inputs[i].name, &temp);
       }
       KALDI_LOG << "Running forward computation";
       computer.Forward();
       const CuMatrixBase<BaseFloat> &output(computer.GetOutput("output"));
       KALDI_LOG << "Output sum for pass " << pass << " is " << output.Sum();
       BaseFloat objf = TraceMatMat(output, output_deriv, kTrans);
       measured_objf[pass] = objf;
       if (pass == 0) {
         // we need to do the backward computation (to get the model derivative)
         CuMatrix<BaseFloat> temp(output_deriv);
         computer.AcceptOutputDeriv("output", &temp);
         KALDI_LOG << "Running backward computation";
         computer.Backward();
       } else {
         // work out the predicted objf-change as dot-product of deriv and
         // parameter-change.  The expression below can be interpreted as
         // DotProduct(nnet_copy - nnet, nnet_deriv).
         predicted_objf_change[pass] = DotProduct(nnet_copy, nnet_deriv) -
                                       DotProduct(nnet, nnet_deriv);
       }
     }
     Vector<BaseFloat> predicted_objf_change_vec(num_directions),
         measured_objf_change_vec(num_directions);
     for (int32 d = 0; d < num_directions; d++) {
       BaseFloat predicted_change = predicted_objf_change[d+1],
                  measured_change = measured_objf[d+1] - measured_objf[0];
       predicted_objf_change_vec(d) = predicted_change;
       measured_objf_change_vec(d) = measured_change;
     }
     KALDI_LOG << "Vector of predicted objf-change is: "
               << predicted_objf_change_vec;
     KALDI_LOG << "Vector of measured objf-change is: "
               << measured_objf_change_vec;
     BaseFloat delta_thresh = 0.05;
     if (limit_deriv_times) {
       KALDI_LOG << "Not checking that predicted/measured changes matched "
                 << "because we limited times of derivatives.";
     } else {
       if (!ApproxEqual(predicted_objf_change_vec,
                        measured_objf_change_vec, delta_thresh)) {
         KALDI_WARN << "Predicted and measured objf-changes differ too much.";
         num_fail++;
       } else {
         num_success++;
       }
     }
   }
   KALDI_LOG << "Model-derivative check succeeded for " << num_success << " out of "
             << (num_fail + num_success) << " tries.";
   int32 num_checked = num_fail + num_success;
   if (num_success < num_checked - (2 + num_checked / 5))
     KALDI_ERR << "Failed too many times.";
 }
static void kaldi::nnet3::UnitTestNnetOptimize () static
Definition at line 178 of file nnet-optimize-test.cc.
References NnetOptimizeOptions::backprop_in_place, NnetOptimizeOptions::initialize_undefined, KALDI_ERR, KALDI_SUCCFAIL, NnetOptimizeOptions::max_deriv_time, NnetOptimizeOptions::min_deriv_time, NnetOptimizeOptions::move_sizing_commands, NnetOptimizeOptions::propagate_in_place, kaldi::RandInt(), NnetOptimizeOptions::remove_assignments, and UnitTestNnetOptimizeWithOptions().
Referenced by main().
{
   NnetOptimizeOptions optimize_all;
   // randomly sometimes set min_deriv and max_deriv to small/large values,
   // which will cause some of the LimitDerivativeTimes() code to be called
   // (without really changing anything).
   if (RandInt(0, 3) == 0) optimize_all.min_deriv_time = -200;
   if (RandInt(0, 3) == 0) optimize_all.max_deriv_time = 1000;
   // this is useful for debugging as it removes nans:
   // optimize_all.initialize_undefined = false;
   bool success = UnitTestNnetOptimizeWithOptions(optimize_all);
   if (success)
     return;
   // Test failed with full optimization. Slowly retry with various
   // optimizations switched off.
   NnetOptimizeOptions optimize = optimize_all;
   optimize.propagate_in_place = false;
   bool succ_no_propagate_in_place = UnitTestNnetOptimizeWithOptions(optimize);
   optimize = optimize_all;
   optimize.backprop_in_place = false;
   bool succ_no_backprop_in_place = UnitTestNnetOptimizeWithOptions(optimize);
   optimize = optimize_all;
   optimize.remove_assignments = false;
   bool succ_no_remove_assignments = UnitTestNnetOptimizeWithOptions(optimize);
   optimize = optimize_all;
   optimize.initialize_undefined = false;
   bool succ_no_initialize_undefined = UnitTestNnetOptimizeWithOptions(optimize);
   optimize = optimize_all;
   optimize.move_sizing_commands = false;
   bool succ_no_move_sizing_commands = UnitTestNnetOptimizeWithOptions(optimize);
 #define KALDI_SUCCFAIL(b) ((b) ? "SUCCESS" : "FAILURE")
   KALDI_ERR
     << "Test failed with all optimizations enabled. Retried test with the "
     << "following optimizations turned off:"
     << "\n  propagate_in_place   ... " << KALDI_SUCCFAIL(succ_no_propagate_in_place)
     << "\n  backprop_in_place    ... " << KALDI_SUCCFAIL(succ_no_backprop_in_place)
     << "\n  remove_assignments   ... " << KALDI_SUCCFAIL(succ_no_remove_assignments)
     << "\n  initialize_undefined ... " << KALDI_SUCCFAIL(succ_no_initialize_undefined)
     << "\n  move_sizing_commands ... " << KALDI_SUCCFAIL(succ_no_move_sizing_commands);
 #undef KALDI_SUCCFAIL
 }
static bool kaldi::nnet3::UnitTestNnetOptimizeWithOptions (NnetOptimizeOptions opt_config) static
Definition at line 32 of file nnet-optimize-test.cc.
References NnetComputer::AcceptInput(), NnetComputer::AcceptOutputDeriv(), kaldi::ApproxEqual(), NnetComputer::Backward(), ComputationChecker::Check(), CheckComputationOptions::check_rewrite, NnetComputation::ComputeCudaIndexes(), ComputeExampleComputationRequestSimple(), Compiler::CreateComputation(), NnetComputeOptions::debug, NnetComputer::Forward(), GenerateConfigSequence(), NnetComputer::GetInputDeriv(), NnetComputer::GetOutput(), rnnlm::i, ComputationRequest::inputs, rnnlm::j, KALDI_LOG, KALDI_WARN, rnnlm::n, NnetParametersAreIdentical(), Optimize(), ComputationRequest::outputs, NnetComputation::Print(), kaldi::RandInt(), Nnet::ReadConfig(), CuMatrixBase< Real >::SetRandn(), SetZero(), and CuMatrixBase< Real >::Sum().
Referenced by UnitTestNnetOptimize().
{
   //opt_config.convert_addition = false;
   //opt_config.remove_assignments = false;
   //opt_config.move_sizing_commands = false;
   //opt_config.allocate_from_other = false;
   srand(0);  // Every run must be deterministic.
   for (int32 n = 0; n < 40; n++) {
     struct NnetGenerationOptions gen_config;
     std::vector<std::string> configs;
     GenerateConfigSequence(gen_config, &configs);
     Nnet nnet;
     for (size_t j = 0; j < configs.size(); j++) {
       KALDI_LOG << "Input config[" << j << "] is: " << configs[j];
       std::istringstream is(configs[j]);
       nnet.ReadConfig(is);
     }
     ComputationRequest request;
     std::vector<Matrix<BaseFloat> > inputs;
     ComputeExampleComputationRequestSimple(nnet, &request, &inputs);
     NnetComputation computation;
     Compiler compiler(request, nnet);
     CompilerOptions opts;
     compiler.CreateComputation(opts, &computation);
     {
       std::ostringstream os;
       computation.Print(os, nnet);
       KALDI_LOG << "Generated computation is: " << os.str();
     }
     CheckComputationOptions check_config;
     // we can do the rewrite check since it's before optimization.
     check_config.check_rewrite = true;
     ComputationChecker checker(check_config, nnet, computation);
     checker.Check();
     NnetComputation computation_opt(computation);
     {
       Optimize(opt_config, nnet, request, &computation_opt);
       std::ostringstream os;
       computation_opt.Print(os, nnet);
       KALDI_LOG << "Optimized computation is: " << os.str();
     }
     NnetComputeOptions compute_opts;
     if (RandInt(0, 1) == 0)
       compute_opts.debug = true;
     computation.ComputeCudaIndexes();
     computation_opt.ComputeCudaIndexes();
     Nnet nnet_to_update(nnet);  // copy of the nnet that we update...  needed to
                                 // test the consolidation of backprop commands,
                                 // otherwise the optimized and non-optimized
                                 // comptuations differ.
     bool is_gradient = true;  // with natural gradient, the consolidation would
                               // affect the final model params -> test just the
                               // gradient.
     SetZero(is_gradient, &nnet_to_update);
     NnetComputer computer(compute_opts,
                           computation,
                           nnet,
                           &nnet_to_update);
     Nnet nnet_opt(nnet);  // copy of the nnet for the optimized computation.
                           // necessary in case backprop changes parameters.
     Nnet nnet_opt_to_update(nnet_opt);
     SetZero(is_gradient, &nnet_opt_to_update);
     // NnetComputer for the optimized version of the computation.
     NnetComputer computer_opt(compute_opts,
                               computation_opt,
                               nnet_opt,
                               &nnet_opt_to_update);
     // provide the input to the computations.
     for (size_t i = 0; i < request.inputs.size(); i++) {
       CuMatrix<BaseFloat> temp(inputs[i]);
       KALDI_LOG << "Input sum is " << temp.Sum();
       computer.AcceptInput(request.inputs[i].name, &temp);
       CuMatrix<BaseFloat> temp2(inputs[i]);
       computer_opt.AcceptInput(request.inputs[i].name, &temp2);
     }
     KALDI_LOG << "Running non-optimized forward computation";
     computer.Forward();
     KALDI_LOG << "Running optimized forward computation";
     computer_opt.Forward();
     const CuMatrixBase<BaseFloat> &output(computer.GetOutput("output"));
     KALDI_LOG << "Output sum (not optimized) is " << output.Sum();
     const CuMatrixBase<BaseFloat> &output_opt(computer_opt.GetOutput("output"));
     KALDI_LOG << "Output sum (optimized) is " << output_opt.Sum();
     if (!ApproxEqual(output, output_opt)) {
       KALDI_WARN << "Non-optimized and optimized versions of the computation give "
                  << "different outputs.";
       return false;
     }
     CuMatrix<BaseFloat> output_deriv(output.NumRows(), output.NumCols());
     output_deriv.SetRandn();
     CuMatrix<BaseFloat> output_deriv_opt(output_deriv);
     if (request.outputs[0].has_deriv) {
       computer.AcceptOutputDeriv("output", &output_deriv);
       computer_opt.AcceptOutputDeriv("output", &output_deriv_opt);
     }
     KALDI_LOG << "Running non-optimized backward computation";
     computer.Backward();
     KALDI_LOG << "Running optimized backward computation";
     computer_opt.Backward();
     for (size_t i = 0; i < request.inputs.size(); i++) {
       if (request.inputs[i].has_deriv) {
         const CuMatrixBase<BaseFloat> &in_deriv =
             computer.GetInputDeriv(request.inputs[i].name);
         const CuMatrixBase<BaseFloat> &in_deriv_opt =
             computer_opt.GetInputDeriv(request.inputs[i].name);
         KALDI_LOG << "Input-deriv sum for input '" << request.inputs[i].name
                   << "' (non-optimized) is " << in_deriv.Sum();
         KALDI_LOG << "Input-deriv sum for input '" << request.inputs[i].name
                   << "' (optimized) is " << in_deriv_opt.Sum();
         if (!ApproxEqual(in_deriv, in_deriv_opt)) {
           KALDI_WARN << "Non-optimized and optimized versions of the "
                      << "computation give different input-derivs.";
           return false;
         }
       }
     }
     if (!NnetParametersAreIdentical(nnet_to_update,
                                     nnet_opt_to_update, 1.0e-05)) {
       KALDI_WARN << "Neural networks differ after training, between "
                  << "optimized and non-optimized computation.";
       return false;
     }
   }
   return true;
 }
void kaldi::nnet3::UnitTestPreconditionDirectionsOnline ()
Definition at line 261 of file natural-gradient-online-test.cc.
References CuVectorBase< Real >::AddDiagMatMat(), MatrixBase< Real >::AddVecVec(), kaldi::AssertEqual(), KALDI_ASSERT, kaldi::kNoTrans, kaldi::kTrans, CuMatrixBase< Real >::NumRows(), OnlineNaturalGradientSimple::PreconditionDirections(), OnlineNaturalGradient::PreconditionDirections(), kaldi::Rand(), kaldi::RandInt(), VectorBase< Real >::Scale(), MatrixBase< Real >::Set(), VectorBase< Real >::SetRandn(), MatrixBase< Real >::SetRandn(), OnlineNaturalGradientSimple::SetRank(), OnlineNaturalGradient::SetRank(), kaldi::TraceMatMat(), and OnlineNaturalGradient::TurnOnDebug().
Referenced by main().
{
   MatrixIndexT R = 1 + Rand() % 30,  // rank of correction
       N = (2 * R) + Rand() % 30,  // batch size
       D = R + 1 + Rand() % 20; // problem dimension.  Must be > R.
   // Test sometimes with features that are all-zero or all-one; this will
   // help to make sure low-rank or zero input doesn't crash the code.
   bool zero = false;
   bool one = false;
   if (Rand() % 3 == 0) zero = true;
   //else if (Rand() % 2 == 0) one = true;
   CuVector<BaseFloat> row_prod1(N), row_prod2(N);
   BaseFloat gamma1, gamma2;
   BaseFloat big_eig_factor = RandInt(1, 20);
   big_eig_factor = big_eig_factor * big_eig_factor;
   Vector<BaseFloat> big_eig_vector(D);
   big_eig_vector.SetRandn();
   big_eig_vector.Scale(big_eig_factor);
   OnlineNaturalGradientSimple preconditioner1;
   OnlineNaturalGradient preconditioner2;
   preconditioner1.SetRank(R);
   preconditioner2.SetRank(R);
   preconditioner2.TurnOnDebug();
   int32 num_iters = 100;
   for (int32 iter = 0; iter < num_iters; iter++) {
     Matrix<BaseFloat> M_cpu(N, D);
     if (one) M_cpu.Set(1.0);
     else if (!zero) {
       M_cpu.SetRandn();
       Vector<BaseFloat> rand_vec(N);
       rand_vec.SetRandn();
       M_cpu.AddVecVec(1.0, rand_vec, big_eig_vector);
     }
     CuMatrix<BaseFloat> M(M_cpu);
     CuMatrix<BaseFloat> Mcopy1(M), Mcopy2(M);
     preconditioner1.PreconditionDirections(&Mcopy1, &row_prod1, &gamma1);
     preconditioner2.PreconditionDirections(&Mcopy2, &row_prod2, &gamma2);
     BaseFloat trace1 = TraceMatMat(M, M, kTrans),
         trace2 = TraceMatMat(Mcopy1, Mcopy1, kTrans);
     AssertEqual(trace1, trace2 * gamma2 * gamma2, 1.0e-02);
     AssertEqual(Mcopy1, Mcopy2);
     AssertEqual(row_prod1, row_prod2, 1.0e-02f);
     AssertEqual(gamma1, gamma2, 1.0e-02);
     // make sure positive definite
     CuVector<BaseFloat> inner_prods(M.NumRows());
     inner_prods.AddDiagMatMat(1.0, M, kNoTrans, Mcopy1, kTrans, 0.0);
     KALDI_ASSERT(inner_prods.Min() >= 0.0);
   }
   return;
 }
void kaldi::nnet3::UnitTestReadConfig ()
Definition at line 167 of file nnet-parse-test.cc.
References kaldi::ApproxEqual(), rnnlm::i, KALDI_ASSERT, and ReadConfigFile().
Referenced by main().
{
   std::string str = " alpha=aa beta=\"b b\"# String test\n"
       "beta2='b c' beta3=bd # \n"
       "gamma=1:2:3:4  # Int Vector test\n"
       " de1ta=f  # Bool + Integer in key Comment test delta=t  \n"
       "_epsilon=-1  # Int Vector test _epsilon=1 \n"
       " zet-_a=0.15   theta=1.1# Float, -, _ test\n"
       "quoted='a b c' # quoted string\n"
       "quoted2=\"d e 'a b=c' f\" # string quoted with double quotes";
   std::istringstream is(str);
   std::vector<std::string> lines;
   ReadConfigFile(is, &lines);
   KALDI_ASSERT(lines.size() == 8);
   ConfigLine cfl;
   for (size_t i = 0; i < lines.size(); i++) {
     KALDI_ASSERT(cfl.ParseLine(lines[i]));
   }
   KALDI_ASSERT(cfl.GetValue("beta2", &str) && str == "b c");
   KALDI_ASSERT(cfl.GetValue("_epsilon", &str) && str == "-1");
   KALDI_ASSERT(cfl.GetValue("quoted", &str) && str == "a b c");
   KALDI_ASSERT(cfl.GetValue("quoted2", &str) && str == "d e 'a b=c' f");
   BaseFloat float_val = 0;
   KALDI_ASSERT(cfl.GetValue("zet-_a", &float_val) && ApproxEqual(float_val, 0.15));
 }
void kaldi::nnet3::UnitTestSplitLocations (bool verbose)
Definition at line 275 of file nnet-compile-utils-test.cc.
References ConvertToIndexes(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_LOG, PrintVectorVectorPair(), kaldi::Rand(), and SplitLocations().
Referenced by main().
{
   int32 minibatch_size = Rand() % 1024 + 100;
   int32 num_submat_indexes = Rand() % 10 + 1;
   int32 max_submat_list_size = Rand() % 10 + 1;
   int32 min_num_kAddRows = Rand() % 2; // minimum number of kAddRows compatible
   // lists expected in the final split lists. This value will be used to
   // create input submat_lists so that this is guaranteed
   max_submat_list_size = min_num_kAddRows + max_submat_list_size;
   std::vector<std::pair<int32, int32> > all_pairs;
   all_pairs.reserve(minibatch_size * max_submat_list_size);
   std::vector<std::vector<std::pair<int32, int32> > >
       submat_lists(minibatch_size),
       split_lists;
   std::vector<int32> submat_indexes(num_submat_indexes);
   for (int32 i = 0; i < num_submat_indexes; i++)  {
     submat_indexes[i] = Rand();
   }
   // generating submat_lists
   int32 max_generated_submat_list_size = 0;
   for (int32 i = 0; i < minibatch_size; i++)  {
     int32 num_locations = Rand() % max_submat_list_size + 1;
     max_generated_submat_list_size =
         max_generated_submat_list_size < num_locations ?
         num_locations : max_generated_submat_list_size;
     submat_lists[i].reserve(num_locations);
     for (int32 j = 0; j < num_locations; j++) {
       if (j <= min_num_kAddRows)
         // since we need min_num_kAddRows in the split_lists we ensure that
         // we add a pair with the same first element in all the submat_lists
         submat_lists[i].push_back(std::make_pair(submat_indexes[j],
                            Rand() % minibatch_size));
       submat_lists[i].push_back(
           std::make_pair(submat_indexes[Rand() % num_submat_indexes],
                          Rand() % minibatch_size));
     }
     all_pairs.insert(all_pairs.end(), submat_lists[i].begin(),
                      submat_lists[i].end());
   }
   SplitLocations(submat_lists, &split_lists);
   if (verbose)  {
     KALDI_LOG << "submat_list";
     PrintVectorVectorPair(submat_lists);
     KALDI_LOG << "split_lists";
     PrintVectorVectorPair(split_lists);
     KALDI_LOG << "===========================";
     KALDI_LOG << split_lists.size();
   }
   int32 num_kAddRows_in_output = 0;
   int32 first_value;
   std::vector<int32> second_values;
   // ensure that elements in submat_lists are also present
   // in split_lists
   for (int32 i = 0 ; i < split_lists.size(); i++) {
     second_values.clear();
     if (ConvertToIndexes(split_lists[i], &first_value, &second_values)) {
       // Checking if ConvertToIndexes did a proper conversion of the indexes
       for (int32 j = 0; j < second_values.size(); j++)  {
         if (split_lists[i][j].first != -1)
           KALDI_ASSERT((split_lists[i][j].first == first_value) &&
                        (split_lists[i][j].second == second_values[j]));
       }
       num_kAddRows_in_output++;
     }
     for (int32 j = 0; j < split_lists[i].size(); j++) {
       if (split_lists[i][j].first == -1)
         continue;
       std::vector<std::pair<int32, int32> >::iterator iter =
           std::find_if(all_pairs.begin(), all_pairs.end(),
                     ComparePair(split_lists[i][j]));
       KALDI_ASSERT(iter != all_pairs.end());
       all_pairs.erase(iter);
     }
   }
   KALDI_ASSERT(all_pairs.size() == 0);
   // ensure that there are at least as many kAddRows compatible split_lists as
   // specified
   KALDI_ASSERT(num_kAddRows_in_output >= min_num_kAddRows);
 }
void kaldi::nnet3::UnitTestSplitLocationsBackward (bool verbose)
Definition at line 70 of file nnet-compile-utils-test.cc.
References ConvertToIndexes(), rnnlm::i, rnnlm::j, KALDI_ASSERT, KALDI_LOG, PrintVectorVectorPair(), kaldi::Rand(), and SplitLocationsBackward().
Referenced by main().
{
   int32 minibatch_size = Rand() % 1024 + 100;
   int32 num_submat_indexes = Rand() % 10 + 1;
   int32 max_submat_list_size = Rand() % 10 + 1;
   int32 min_num_kAddRows = Rand() % 2; // minimum number of kAddRows compatible
   // lists expected in the final split lists. This value will be used to
   // create input submat_lists so that this is guaranteed
   max_submat_list_size = min_num_kAddRows + max_submat_list_size;
   std::vector<std::pair<int32, int32> > all_pairs;
   all_pairs.reserve(minibatch_size * max_submat_list_size);
   std::vector<std::vector<std::pair<int32, int32> > >
       submat_lists(minibatch_size),
       split_lists;
   std::vector<int32> submat_indexes(num_submat_indexes);
   for (int32 i = 0; i < num_submat_indexes; i++)  {
     submat_indexes[i] = Rand();
   }
   // generating submat_lists
   int32 max_generated_submat_list_size = 0;
   for (int32 i = 0; i < minibatch_size; i++)  {
     int32 num_locations = Rand() % max_submat_list_size + 1;
     max_generated_submat_list_size =
         max_generated_submat_list_size < num_locations ?
         num_locations : max_generated_submat_list_size;
     submat_lists[i].reserve(num_locations);
     for (int32 j = 0; j < num_locations; j++) {
       if (j <= min_num_kAddRows)
         // since we need min_num_kAddRows in the split_lists we ensure that
         // we add a pair with the same first element in all the submat_lists
         submat_lists[i].push_back(std::make_pair(submat_indexes[j],
                            Rand() % minibatch_size));
       submat_lists[i].push_back(
           std::make_pair(submat_indexes[Rand() % num_submat_indexes],
                          Rand() % minibatch_size));
     }
     all_pairs.insert(all_pairs.end(), submat_lists[i].begin(),
                      submat_lists[i].end());
   }
   SplitLocationsBackward(submat_lists, &split_lists);
   // Checking split_lists has all the necessary properties
   for (int32 i = 0; i < split_lists.size(); i++)  {
     int32 first_value;
     std::vector<int32> second_values;
     if (ConvertToIndexes(split_lists[i], &first_value, &second_values))  {
       // checking for contiguity and uniqueness of .second elements
       std::vector<int32> occurred_values;
       int32 prev_value = -10; // using a negative value as all indices are > 0
       for (int32 j = 0; j < second_values.size(); j++)  {
         if (second_values[j] == -1)
           continue;
         if (second_values[j] != prev_value) {
           std::vector<int32>::iterator iter = std::find(occurred_values.begin(),
                                                         occurred_values.end(),
                                                         second_values[j]);
           KALDI_ASSERT(iter == occurred_values.end());
         }
       }
     } else {
       std::vector<std::pair<int32, int32> > list_of_pairs;
       // checking for uniques of elements in the list
       for (int32 j = 0; j < split_lists[i].size(); j++)  {
         if (split_lists[i][j].first == -1)
           continue;
         std::vector<std::pair<int32, int32> >::const_iterator iter =
             std::find_if(list_of_pairs.begin(), list_of_pairs.end(),
                          PairIsEqualComparator(split_lists[i][j]));
         KALDI_ASSERT(iter == list_of_pairs.end());
         list_of_pairs.push_back(split_lists[i][j]);
       }
     }
   }
   if (verbose)  {
     KALDI_LOG << "submat_list";
     PrintVectorVectorPair(submat_lists);
     KALDI_LOG << "split_lists";
     PrintVectorVectorPair(split_lists);
     KALDI_LOG << "===========================";
   }
   int32 num_kAddRows_in_output = 0;
   int32 first_value;
   std::vector<int32> second_values;
   // ensure that elements in submat_lists are also present
   // in split_lists
   for (int32 i = 0 ; i < split_lists.size(); i++) {
     second_values.clear();
     if (ConvertToIndexes(split_lists[i], &first_value, &second_values)) {
       // Checking if ConvertToIndexes did a proper conversion of the indexes
       KALDI_ASSERT(second_values.size() == split_lists[i].size());
       for (int32 j = 0; j < second_values.size(); j++)  {
         if (split_lists[i][j].first != -1)
           KALDI_ASSERT((split_lists[i][j].first == first_value) &&
                        (split_lists[i][j].second == second_values[j]));
       }
       num_kAddRows_in_output++;
     }
     for (int32 j = 0; j < split_lists[i].size(); j++) {
       if (split_lists[i][j].first == -1)
         continue;
       std::vector<std::pair<int32, int32> >::iterator iter =
           std::find_if(all_pairs.begin(), all_pairs.end(),
                     ComparePair(split_lists[i][j]));
       KALDI_ASSERT(iter != all_pairs.end());
       all_pairs.erase(iter);
     }
   }
   KALDI_ASSERT(all_pairs.size() == 0);
   // ensure that there are at least as many kAddRows compatible split_lists as
   // specified
   KALDI_ASSERT(num_kAddRows_in_output >= min_num_kAddRows);
 }
void kaldi::nnet3::UnitTestSummarizeVector ()
Definition at line 223 of file nnet-parse-test.cc.
References KALDI_LOG, kaldi::kCopyData, Vector< Real >::Resize(), VectorBase< Real >::SetRandn(), and SummarizeVector().
Referenced by main().
{
   // will be eyeballed by a human.
   Vector<BaseFloat> vec(9);
   vec.SetRandn();
   vec(0) = 1024.2343;
   vec(1) = 0.01;
   vec(2) = 0.001234;
   vec(3) = 0.000198;
   vec(3) = 1.98e-09;
   vec(4) = 153.0;
   vec(5) = 0.154;
   vec(6) = 1.2;
   vec(7) = 9.2;
   vec(8) = 10.8;
   KALDI_LOG << "vec = " << vec << " -> " << SummarizeVector(vec);
   vec.Resize(20, kCopyData);
   KALDI_LOG << "vec = " << vec << " -> " << SummarizeVector(vec);
 }
void UnVectorizeNnet (const VectorBase< BaseFloat > & params, Nnet * dest)
Copies the parameters from params to *dest.
the dimension of params must be equal to NumParameters(*dest).
Definition at line 331 of file nnet-utils.cc.
References VectorBase< Real >::Dim(), Nnet::GetComponent(), KALDI_ASSERT, KALDI_ERR, kUpdatableComponent, Nnet::NumComponents(), NumParameters(), UpdatableComponent::NumParameters(), Component::Properties(), and UpdatableComponent::UnVectorize().
Referenced by NnetCombiner::ComputeObjfAndDerivFromNnet().
{
   KALDI_ASSERT(parameters.Dim() == NumParameters(*dest));
   int32 dim_offset = 0;
   for (int32 c = 0; c < dest->NumComponents(); c++) {
     Component *comp = dest->GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       // For now all updatable components inherit from class UpdatableComponent.
       // If that changes in future, we will change this code.
       UpdatableComponent *uc = dynamic_cast<UpdatableComponent*>(comp);
       if (uc == NULL)
         KALDI_ERR << "Updatable component does not inherit from class "
             "UpdatableComponent; change this code.";
       int32 this_dim = uc->NumParameters();
       const SubVector<BaseFloat> this_part(parameters, dim_offset, this_dim);
       uc->UnVectorize(this_part);
       dim_offset += this_dim;
     }
   }
 }
void VariableMergingOptimization (const NnetOptimizeOptions & config, const Nnet & nnet, const ComputationRequest & request, NnetComputation * computation)
This wraps class VariableMergingOptimizer in a simplified interface.
Definition at line 251 of file nnet-optimize.cc.
References VariableMergingOptimizer::MergeVariables().
Referenced by Optimize().
{
   bool changed = true;
   while (changed) {
     changed = false;
     VariableMergingOptimizer opt(config, nnet, request, computation);
     if (opt.MergeVariables())
       changed = true;
   }
 }
void VectorizeNnet (const Nnet & src, VectorBase< BaseFloat > * params)
Copies the nnet parameters to *params, whose dimension must be equal to NumParameters(src).
Definition at line 308 of file nnet-utils.cc.
References VectorBase< Real >::Dim(), Nnet::GetComponent(), KALDI_ASSERT, KALDI_ERR, kUpdatableComponent, Nnet::NumComponents(), NumParameters(), UpdatableComponent::NumParameters(), Component::Properties(), and UpdatableComponent::Vectorize().
Referenced by NnetCombiner::AcceptNnet(), NnetCombiner::ComputeObjfAndDerivFromNnet(), and NnetCombiner::NnetCombiner().
{
   KALDI_ASSERT(parameters->Dim() == NumParameters(src));
   int32 dim_offset = 0;
   for (int32 c = 0; c < src.NumComponents(); c++) {
     const Component *comp = src.GetComponent(c);
     if (comp->Properties() & kUpdatableComponent) {
       // For now all updatable components inherit from class UpdatableComponent.
       // If that changes in future, we will change this code.
       const UpdatableComponent *uc =
           dynamic_cast<const UpdatableComponent*>(comp);
       if (uc == NULL)
         KALDI_ERR << "Updatable component does not inherit from class "
             "UpdatableComponent; change this code.";
       int32 this_dim = uc->NumParameters();
       SubVector<BaseFloat> this_part(*parameters, dim_offset, this_dim);
       uc->Vectorize(&this_part);
       dim_offset += this_dim;
     }
   }
 }
void WriteIndexVector (std::ostream & os, bool binary, const std::vector< Index > & vec)
Definition at line 118 of file nnet-common.cc.
References rnnlm::i, kaldi::WriteBasicType(), WriteIndexVectorElementBinary(), and kaldi::WriteToken().
Referenced by UnitTestIndexIo(), and NnetIo::Write().
{
   // This token will make it easier to write back-compatible code if we later
   // change the format.
   WriteToken(os, binary, "<I1V>");
   int32 size = vec.size();
   WriteBasicType(os, binary, size);
   if (!binary) {  // In text mode we just use the native Write functionality.
     for (int32 i = 0; i < size; i++)
       vec[i].Write(os, binary);
   } else {
     for (int32 i = 0; i < size; i++)
       WriteIndexVectorElementBinary(os, vec, i);
   }
 }
static void kaldi::nnet3::WriteIndexVectorElementBinary (std::ostream & os, const std::vector< Index > & vec, int32 i) static
Definition at line 44 of file nnet-common.cc.
References rnnlm::i, KALDI_ERR, Index::n, Index::t, kaldi::WriteBasicType(), and Index::x.
Referenced by WriteIndexVector().
              {
   bool binary = true;
   Index index = vec[i];
   if (i == 0) {
     if (index.n == 0 && index.x == 0 &&
         std::abs(index.t) < 125) {
       // handle this common case in one character.
       os.put(static_cast<signed char>(index.t));
     } else {  // handle the general case less efficiently.
       os.put(127);
       WriteBasicType(os, binary, index.n);
       WriteBasicType(os, binary, index.t);
       WriteBasicType(os, binary, index.x);
     }
   } else {
     Index last_index = vec[i-1];
     if (index.n == last_index.n && index.x == last_index.x &&
         std::abs(index.t - last_index.t) < 125) {
       signed char c = index.t - last_index.t;
       os.put(c);
     } else {  // handle the general case less efficiently.
       os.put(127);
       WriteBasicType(os, binary, index.n);
       WriteBasicType(os, binary, index.t);
       WriteBasicType(os, binary, index.x);
     }
   }
   if (!os.good())
     KALDI_ERR << "Output stream error detected";
 }
int32 kaldi::nnet3::YzxVectorIndex (int32 x, int32 y, int32 z, int32 input_x_dim, int32 input_y_dim, int32 input_z_dim) inline
Definition at line 3083 of file nnet-simple-component.cc.
References KALDI_PARANOID_ASSERT.
Referenced by ConvolutionComponent::InderivPatchesToInderiv(), and ConvolutionComponent::InputToInputPatches().
{
   KALDI_PARANOID_ASSERT(x < input_x_dim && y < input_y_dim && z < input_z_dim);
   return (input_y_dim * input_z_dim) * x + (input_y_dim) * z + y;
 }
void ZeroComponentStats (Nnet * nnet)
Zeroes the component stats in all nonlinear components in the nnet.
Definition at line 244 of file nnet-utils.cc.
References Nnet::GetComponent(), Nnet::NumComponents(), and Component::ZeroStats().
Referenced by NnetTrainer::NnetTrainer().
{
   for (int32 c = 0; c < nnet->NumComponents(); c++) {
     Component *comp = nnet->GetComponent(c);
     comp->ZeroStats();  // for some components, this won't do anything.
   }
 }
int32 kaldi::nnet3::ZyxVectorIndex (int32 x, int32 y, int32 z, int32 input_x_dim, int32 input_y_dim, int32 input_z_dim) inline
Definition at line 3091 of file nnet-simple-component.cc.
References KALDI_PARANOID_ASSERT.
Referenced by ConvolutionComponent::InderivPatchesToInderiv(), and ConvolutionComponent::InputToInputPatches().
{
   KALDI_PARANOID_ASSERT(x < input_x_dim && y < input_y_dim && z < input_z_dim);
   return (input_y_dim * input_z_dim) * x + (input_z_dim) * y + z;
 }
Variable Documentation
bool computation_checker_warned_unused_input = false static
Checks that we never use variables before they are allocated or after they are deallocated, and some other checks that can be done from the MatrixAccesses.
Definition at line 633 of file nnet-analyze.cc.
Referenced by ComputationChecker::CheckComputationMatrixAccesses().