Kaldi: latbin/nbest-to-lattice.cc File Reference
nbest-to-lattice.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "fstext/fstext-lib.h"
#include "lat/kaldi-lattice.h"
Functions
bool GetUtteranceId (const std::string &nbest_id, std::string *utterance_id)
int main (int argc, char *argv[])
Function Documentation
bool GetUtteranceId (const std::string & nbest_id, std::string * utterance_id)
Definition at line 27 of file nbest-to-lattice.cc.
Referenced by main().
{
   size_t pos = nbest_id.find_last_of('-');
   if (pos == std::string::npos || pos == 0) return false;
   else{
     *utterance_id = std::string(nbest_id, 0, pos);
     return true;
   }
 }
int main (int argc, char * argv[])
Definition at line 36 of file nbest-to-lattice.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), GetUtteranceId(), KALDI_ERR, KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Read in a Table containing N-best entries from a lattices (i.e. individual\n"
         "lattices with a linear structure, one for each N-best entry, indexed by\n"
         "utt_id_a-1, utt_id_a-2, etc., and take the union of them for each utterance\n"
         "id (e.g. utt_id_a), outputting a lattice for each.\n"
         "Usage:  nbest-to-lattice <nbest-rspecifier> <lattices-wspecifier>\n"
         " e.g.: nbest-to-lattice ark:1.nbest ark:1.lats\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string nbest_rspecifier = po.GetArg(1),
         lats_wspecifier = po.GetArg(2);
     SequentialCompactLatticeReader compact_nbest_reader(nbest_rspecifier);
     CompactLatticeWriter compact_lattice_writer(lats_wspecifier);
     int32 n_nbest_done = 0, n_utt_done = 0;
     // The variable "cur_union" will be the union of FSTs for a
     // particular utterance-id, if we have any "pending".
     CompactLattice cur_union;
     std::string cur_utt_id;
     for (; !compact_nbest_reader.Done(); compact_nbest_reader.Next()) {
       std::string nbest_id = compact_nbest_reader.Key();
       const CompactLattice &this_nbest = compact_nbest_reader.Value();
       std::string utt_id;
       if (!GetUtteranceId(nbest_id, &utt_id)) {
         KALDI_ERR << "Invalid n-best id " << nbest_id << ": make sure you "
             "are giving N-bests to nbest-to-lattice.";
       }
       if (utt_id != cur_utt_id) { // change in utterance.
         if (cur_utt_id != "") {
           compact_lattice_writer.Write(cur_utt_id, cur_union);
           cur_union.DeleteStates();
         }
         n_utt_done++; // We increment this when we start processing a
         // new utterance.
         cur_utt_id = utt_id;
       }
       Union(&cur_union, this_nbest);
       n_nbest_done++;
     }
     if (cur_utt_id != "")
       compact_lattice_writer.Write(cur_utt_id, cur_union);
     KALDI_LOG << "Done joining n-best into lattices for "
               << n_utt_done << " utterances, with on average "
               << (n_nbest_done/static_cast<BaseFloat>(n_utt_done))
               << " N-best paths per utterance.";
     return (n_utt_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }