Kaldi: nnet2bin/nnet-perturb-egs-fmllr.cc File Reference
nnet-perturb-egs-fmllr.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "transform/transform-common.h"
#include "nnet2/nnet-example-functions.h"
Namespaces
kaldi
kaldi::nnet2
Functions
void TransformTrainingExample (const Matrix< BaseFloat > &fmllr_mat, BaseFloat noise_factor, NnetExample *eg)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 50 of file nnet-perturb-egs-fmllr.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ERR, KALDI_LOG, SequentialTableReader< Holder >::Key(), rnnlm::n, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), kaldi::RandInt(), ParseOptions::Read(), ParseOptions::Register(), kaldi::nnet2::TransformTrainingExample(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Copy examples, perturbing them by multiplying by a randomly chosen fMLLR\n"
         "transform from a fixed set.  The option --noise-factor interpolates the\n"
         "un-transformed feature (times 1.0 - noise-factor) with the fMLLR feature\n"
         "(times noise-factor)\n"
         "\n"
         "Usage:  nnet-perturb-egs-fmllr [options] <fmllr-rspecifier> <egs-rspecifier> <egs-wspecifier>\n"
         "\n"
         "nnet-perturb-egs-fmllr --noise-factor=0.2 'ark:cat exp/tri4_ali/trans.*|' ark:- ark:-\n";
     BaseFloat noise_factor = 0.1;
     int32 srand_seed = 0;
     ParseOptions po(usage);
     po.Register("noise-factor", &noise_factor, "Factor to interpolate fMLLR-projected "
                 "data with raw data (1.0 would be pure fMLLR)");
     po.Register("srand", &srand_seed, "Seed for random number generator ");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string fmllr_rspecifier = po.GetArg(1),
         examples_rspecifier = po.GetArg(2),
         examples_wspecifier = po.GetArg(3);
     std::vector<Matrix<BaseFloat>* > fmllr_transforms;
     SequentialBaseFloatMatrixReader transform_reader(fmllr_rspecifier);
     for (; !transform_reader.Done(); transform_reader.Next())
       fmllr_transforms.push_back(new Matrix<BaseFloat>(transform_reader.Value()));
     if (fmllr_transforms.empty()) {
       KALDI_ERR << "Read no fMLLR transforms";
     }
     KALDI_LOG << "Read " << fmllr_transforms.size() << " transforms.";
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     NnetExampleWriter example_writer(examples_wspecifier);
     int64 num_done = 0;
     for (; !example_reader.Done(); example_reader.Next(), num_done++) {
       std::string key = example_reader.Key();
       NnetExample eg = example_reader.Value();
       int32 n = RandInt(0, fmllr_transforms.size() - 1);
       const Matrix<BaseFloat> &fmllr_mat = *(fmllr_transforms[n]);
       TransformTrainingExample(fmllr_mat, noise_factor, &eg);
       example_writer.Write(key, eg);
     }
     while (!fmllr_transforms.empty()) {
       delete fmllr_transforms.back();
       fmllr_transforms.pop_back();
     }
     KALDI_LOG << "Perturbed " << num_done << " neural-network training examples "
               << "using fMLLR, with noise factor " << noise_factor;
     return (num_done == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }