Kaldi: nnet2bin/nnet-shrink.cc File Reference
nnet-shrink.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/shrink-nnet.h"
#include "nnet2/am-nnet.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file nnet-shrink.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ASSERT, KALDI_LOG, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), kaldi::nnet2::ShrinkNnet(), Output::Stream(), Input::Stream(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Using a validation set, compute optimal scaling parameters for each\n"
         "class of neural network parameters (i.e. each updatable component), to\n"
         "maximize validation-set objective function.\n"
         "\n"
         "Usage:  nnet-shrink [options] <model-in> <valid-examples-in> <model-out>\n"
         "\n"
         "e.g.:\n"
         " nnet-shrink 1.nnet ark:valid.egs 2.nnet\n";
     bool binary_write = true;
     NnetShrinkConfig shrink_config;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     shrink_config.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet_rxfilename = po.GetArg(1),
         valid_examples_rspecifier = po.GetArg(2),
         nnet_wxfilename = po.GetArg(3);
     TransitionModel trans_model;
     AmNnet am_nnet;
     {
       bool binary_read;
       Input ki(nnet_rxfilename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
       am_nnet.Read(ki.Stream(), binary_read);
     }
     std::vector<NnetExample> validation_set; // stores validation
     // frames.
     { // This block adds samples to "validation_set".
       SequentialNnetExampleReader example_reader(
           valid_examples_rspecifier);
       for (; !example_reader.Done(); example_reader.Next())
         validation_set.push_back(example_reader.Value());
       KALDI_LOG << "Read " << validation_set.size() << " examples from the "
                 << "validation set.";
       KALDI_ASSERT(validation_set.size() > 0);
     }
     ShrinkNnet(shrink_config,
                validation_set,
                &(am_nnet.GetNnet()));
     {
       Output ko(nnet_wxfilename, binary_write);
       trans_model.Write(ko.Stream(), binary_write);
       am_nnet.Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Finished shrinking neural net, wrote model to "
               << nnet_wxfilename;
     return (validation_set.size() == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }