Kaldi: nnet3bin/nnet3-copy.cc File Reference
nnet3-copy.cc File Reference
#include <typeinfo>
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/am-nnet-simple.h"
#include "nnet3/nnet-utils.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file nnet3-copy.cc.
References ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), kaldi::nnet3::SetLearningRate(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     const char *usage =
         "Copy 'raw' nnet3 neural network to standard output\n"
         "Also supports setting all the learning rates to a value\n"
         "(the --learning-rate option)\n"
         "\n"
         "Usage:  nnet3-copy [options] <nnet-in> <nnet-out>\n"
         "e.g.:\n"
         " nnet3-copy --binary=false 0.raw text.raw\n";
     bool binary_write = true;
     BaseFloat learning_rate = -1;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("learning-rate", &learning_rate,
                 "If supplied, all the learning rates of updatable components"
                 "are set to this value.");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string raw_nnet_rxfilename = po.GetArg(1),
                 raw_nnet_wxfilename = po.GetArg(2);
     Nnet nnet;
     ReadKaldiObject(raw_nnet_rxfilename, &nnet);
     if (learning_rate >= 0)
       SetLearningRate(learning_rate, &nnet);
     WriteKaldiObject(nnet, raw_nnet_wxfilename, binary_write);
     KALDI_LOG << "Copied raw neural net from " << raw_nnet_rxfilename
               << " to " << raw_nnet_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }