Kaldi: nnet2bin/nnet-perturb-egs.cc File Reference
nnet-perturb-egs.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/nnet-example-functions.h"
Namespaces
kaldi
kaldi::nnet2
Functions
void PerturbTrainingExample (const TpMatrix< BaseFloat > &cholesky, BaseFloat noise_factor, NnetExample *eg)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 51 of file nnet-perturb-egs.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), kaldi::nnet2::PerturbTrainingExample(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Copy examples, perturbing them by adding a specified amount (--noise-factor)\n"
         "times the within-class covariance of the examples. the Cholesky factor of\n"
         "the examples (obtained from the --write-cholesky option of\n"
         "nnet-get-feature-transform) must be supplied.\n"
         "\n"
         "Usage:  nnet-perturb-egs [options] <cholesky> <egs-rspecifier> <egs-wspecifier>\n"
         "\n"
         "nnet-perturb-egs --noise-factor=0.2 exp/nnet5/cholesky.tpmat ark:- ark:-\n";
     BaseFloat noise_factor = 0.1;
     int32 srand_seed = 0;
     ParseOptions po(usage);
     po.Register("noise-factor", &noise_factor, "Factor to multiply noise generated "
                 "from within-class variance by before adding to egs");
     po.Register("srand", &srand_seed, "Seed for random number generator ");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string cholesky_rxfilename = po.GetArg(1),
         examples_rspecifier = po.GetArg(2),
         examples_wspecifier = po.GetArg(3);
     TpMatrix<BaseFloat> cholesky;
     ReadKaldiObject(cholesky_rxfilename, &cholesky);
     SequentialNnetExampleReader example_reader(examples_rspecifier);
     NnetExampleWriter example_writer(examples_wspecifier);
     int64 num_done = 0;
     for (; !example_reader.Done(); example_reader.Next(), num_done++) {
       std::string key = example_reader.Key();
       NnetExample eg = example_reader.Value();
       PerturbTrainingExample(cholesky, noise_factor, &eg);
       example_writer.Write(key, eg);
     }
     KALDI_LOG << "Perturbed " << num_done << " neural-network training examples "
               << "with noise factor " << noise_factor;
     return (num_done == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }