Kaldi: nnet2bin/nnet-logprob2-parallel.cc File Reference
nnet-logprob2-parallel.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/nnet-update-parallel.h"
#include "nnet2/am-nnet.h"
#include "nnet2/nnet-compute.h"
#include "thread/kaldi-task-sequence.h"
Classes
struct NnetLogprobTask
Namespaces
kaldi
kaldi::nnet2
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 83 of file nnet-logprob2-parallel.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_ASSERT, KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), TaskSequencer< C >::Run(), Input::Stream(), and SequentialTableReader< Holder >::Value().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     typedef kaldi::int64 int64;
     const char *usage =
         "Do the forward computation for a neural net acoustic model, and output\n"
         "matrix of logprobs.  This version of the program outputs to two tables,\n"
         "one table of probabilities without prior division and one table of\n"
         "log-probs with prior division.  It is intended for use in discriminative\n"
         "training.  This version supports multi-threaded operation (--num-threads\n"
         "option)\n"
         "\n"
         "Usage: nnet-logprob2-parallel [options] <model-in> <features-rspecifier> "
         "<probs-wspecifier-not-divided> <logprobs-wspecifier-divided>\n"
         "\n"
         "e.g.: nnet-logprob2-parallel 1.nnet \"$feats\" ark:- \"ark:|logprob-to-post ark:- 1.post\" ark:- \\"
         "        | latgen-faster-mapped [args]\n";
     TaskSequencerConfig thread_config;
     ParseOptions po(usage);
     thread_config.Register(&po);
     po.Read(argc, argv);
     if (po.NumArgs() != 4) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet_rxfilename = po.GetArg(1),
         feats_rspecifier = po.GetArg(2),
         prob_wspecifier_nodiv = po.GetArg(3),
         logprob_wspecifier_divided = po.GetArg(4);
     TransitionModel trans_model;
     AmNnet am_nnet;
     {
       bool binary_read;
       Input ki(nnet_rxfilename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
       am_nnet.Read(ki.Stream(), binary_read);
     }
     int64 num_done = 0, num_err = 0;
     CuVector<BaseFloat> inv_priors(am_nnet.Priors());
     KALDI_ASSERT(inv_priors.Dim() == am_nnet.NumPdfs() &&
                  "Priors in neural network not set up.");
     inv_priors.ApplyPow(-1.0);
     SequentialBaseFloatMatrixReader feature_reader(feats_rspecifier);
     BaseFloatMatrixWriter prob_writer_nodiv(prob_wspecifier_nodiv);
     BaseFloatMatrixWriter logprob_writer_divided(logprob_wspecifier_divided);
     {
       TaskSequencer<NnetLogprobTask> sequencer(thread_config);
       for (; !feature_reader.Done(); feature_reader.Next()) {
         std::string key = feature_reader.Key();
         const Matrix<BaseFloat> &feats = feature_reader.Value();
         sequencer.Run(new NnetLogprobTask(am_nnet, inv_priors, key, feats,
                                           &prob_writer_nodiv,
                                           &logprob_writer_divided));
         num_done++;
       }
     }
     KALDI_LOG << "Finished computing neural net log-probs, processed "
               << num_done << " utterances, " << num_err << " with errors.";
     return (num_done == 0 ? 1 : 0);
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }