Kaldi: nnetbin/nnet-info.cc File Reference
nnet-info.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet/nnet-nnet.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 24 of file nnet-info.cc.
References ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), and Input::Stream().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet1;
     typedef kaldi::int32 int32;
     const char *usage =
         "Print human-readable information about the neural network.\n"
         "(topology, various weight statistics, etc.) It prints to stdout.\n"
         "Usage:  nnet-info [options] <nnet-in>\n"
         "e.g.:\n"
         " nnet-info 1.nnet\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string nnet_rxfilename = po.GetArg(1);
     // load the network
     Nnet nnet;
     {
       bool binary_read;
       Input ki(nnet_rxfilename, &binary_read);
       nnet.Read(ki.Stream(), binary_read);
     }
     std::cout << nnet.Info();
     KALDI_LOG << "Printed info about " << nnet_rxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }