Kaldi: nnet3bin/nnet3-info.cc File Reference
nnet3-info.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet3/nnet-nnet.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 24 of file nnet3-info.cc.
References ParseOptions::GetArg(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), and kaldi::ReadKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet3;
     typedef kaldi::int32 int32;
     const char *usage =
         "Print some text information about 'raw' nnet3 neural network, to\n"
         "standard output\n"
         "\n"
         "Usage:  nnet3-info [options] <raw-nnet>\n"
         "e.g.:\n"
         " nnet3-info 0.raw\n"
         "See also: nnet3-am-info\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string raw_nnet_rxfilename = po.GetArg(1);
     Nnet nnet;
     ReadKaldiObject(raw_nnet_rxfilename, &nnet);
     std::cout << nnet.Info();
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }