Kaldi: nnet2bin/nnet-init.cc File Reference
nnet-init.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "nnet2/am-nnet.h"
#include "hmm/transition-model.h"
#include "tree/context-dep.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file nnet-init.cc.
References ParseOptions::GetArg(), KALDI_ASSERT, KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), Input::Stream(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     const char *usage =
         "Initialize the nnet2 neural network from a config file with a line for each\n"
         "component.  Note, this only outputs the neural net itself, not the associated\n"
         "information such as the transition-model; you'll probably want to pipe\n"
         "the output into something like nnet-am-init.\n"
         "\n"
         "Usage:  nnet-init [options] <config-in> <raw-nnet-out>\n"
         "e.g.:\n"
         " nnet-init nnet.config 1.raw\n";
     bool binary_write = true;
     int32 srand_seed = 0;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Register("srand", &srand_seed, "Seed for random number generator");
     po.Read(argc, argv);
     srand(srand_seed);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string config_rxfilename = po.GetArg(1),
         raw_nnet_wxfilename = po.GetArg(2);
     Nnet nnet;
     {
       bool binary;
       Input ki(config_rxfilename, &binary);
       KALDI_ASSERT(!binary && "Expect config file to contain text.");
       nnet.Init(ki.Stream());
     }
     WriteKaldiObject(nnet, raw_nnet_wxfilename, binary_write);
     KALDI_LOG << "Initialized raw neural net and wrote it to "
               << raw_nnet_wxfilename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }