Kaldi: feat/online-feature-test.cc File Reference
online-feature-test.cc File Reference
#include "feat/online-feature.h"
#include "feat/wave-reader.h"
#include "transform/transform-common.h"
Namespaces
kaldi
Functions
template<class Real >
static void AssertEqual (const Matrix< Real > &A, const Matrix< Real > &B, float tol=0.001)
void GetOutput (OnlineFeatureInterface *a, Matrix< BaseFloat > *output)
bool RandomSplit (int32 wav_dim, std::vector< int32 > *piece_dim, int32 num_pieces, int32 trials=5)
void TestOnlineMatrixCacheFeature ()
void TestOnlineDeltaFeature ()
void TestOnlineSpliceFrames ()
void TestOnlineMfcc ()
void TestOnlinePlp ()
void TestOnlineTransform ()
void TestOnlineAppendFeature ()
int main ()
Function Documentation
int main ()
Definition at line 389 of file online-feature-test.cc.
References rnnlm::i, kaldi::TestOnlineAppendFeature(), kaldi::TestOnlineDeltaFeature(), kaldi::TestOnlineMatrixCacheFeature(), kaldi::TestOnlineMfcc(), kaldi::TestOnlinePlp(), kaldi::TestOnlineSpliceFrames(), and kaldi::TestOnlineTransform().
            {
   using namespace kaldi;
   for (int i = 0; i < 10; i++) {
     TestOnlineMatrixCacheFeature();
     TestOnlineDeltaFeature();
     TestOnlineSpliceFrames();
     TestOnlineMfcc();
     TestOnlinePlp();
     TestOnlineTransform();
     TestOnlineAppendFeature();
   }
   std::cout << "Test OK.\n";
 }