Kaldi: featbin/paste-feats.cc File Reference
paste-feats.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "matrix/kaldi-matrix.h"
Namespaces
kaldi
Functions
bool AppendFeats (const std::vector< Matrix< BaseFloat > > &in, std::string utt, int32 tolerance, Matrix< BaseFloat > *out)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 70 of file paste-feats.cc.
References kaldi::AppendFeats(), kaldi::ClassifyRspecifier(), SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, KALDI_VLOG, KALDI_WARN, SequentialTableReader< Holder >::Key(), kaldi::kNoRspecifier, SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), SequentialTableReader< Holder >::Value(), TableWriter< Holder >::Write(), and kaldi::WriteKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace std;
     const char *usage =
         "Paste feature files (assuming they have the same lengths);  think of the\n"
         "unix command paste a b.\n"
         "Usage: paste-feats <in-rspecifier1> <in-rspecifier2> [<in-rspecifier3> ...] <out-wspecifier>\n"
         " or: paste-feats <in-rxfilename1> <in-rxfilename2> [<in-rxfilename3> ...] <out-wxfilename>\n"
         " e.g. paste-feats ark:feats1.ark \"ark:select-feats 0-3 ark:feats2.ark ark:- |\" ark:feats-out.ark\n"
         "  or: paste-feats foo.mat bar.mat baz.mat\n"
         "See also: copy-feats, copy-matrix, append-vector-to-feats\n";
     ParseOptions po(usage);
     int32 length_tolerance = 0;
     bool binary = true;
     po.Register("length-tolerance", &length_tolerance,
                 "If length is different, trim as shortest up to a frame "
                 " difference of length-tolerance, otherwise exclude segment.");
     po.Register("binary", &binary, "If true, output files in binary "
                 "(only relevant for single-file operation, i.e. no tables)");
     po.Read(argc, argv);
     if (po.NumArgs() < 3) {
       po.PrintUsage();
       exit(1);
     }
     if (ClassifyRspecifier(po.GetArg(1), NULL, NULL)
         != kNoRspecifier) {
       // We're operating on tables, e.g. archives.
       // Last argument is output
       string wspecifier = po.GetArg(po.NumArgs());
       BaseFloatMatrixWriter feat_writer(wspecifier);
       // First input is sequential
       string rspecifier1 = po.GetArg(1);
       SequentialBaseFloatMatrixReader input1(rspecifier1);
       // Assemble vector of other input readers (with random-access)
       vector<RandomAccessBaseFloatMatrixReader *> input;
       for (int32 i = 2; i < po.NumArgs(); i++) {
         string rspecifier = po.GetArg(i);
         RandomAccessBaseFloatMatrixReader *rd = new RandomAccessBaseFloatMatrixReader(rspecifier);
         input.push_back(rd);
       }
       int32 num_done = 0, num_err = 0;
       // Main loop
       for (; !input1.Done(); input1.Next()) {
         string utt = input1.Key();
         KALDI_VLOG(2) << "Merging features for utterance " << utt;
         // Collect features from streams to vector 'feats'
         vector<Matrix<BaseFloat> > feats(po.NumArgs() - 1);
         feats[0] = input1.Value();
         int32 i;
         for (i = 0; i < static_cast<int32>(input.size()); i++) {
           if (input[i]->HasKey(utt)) {
             feats[i + 1] = input[i]->Value(utt);
           } else {
             KALDI_WARN << "Missing utt " << utt << " from input "
                        << po.GetArg(i+2);
             num_err++;
             break;
           }
         }
         if (i != static_cast<int32>(input.size()))
           continue;
         Matrix<BaseFloat> output;
         if (!AppendFeats(feats, utt, length_tolerance, &output)) {
           num_err++;
           continue; // it will have printed a warning.
         }
         feat_writer.Write(utt, output);
         num_done++;
       }
       for (int32 i=0; i < input.size(); i++)
         delete input[i];
       input.clear();
       KALDI_LOG << "Done " << num_done << " utts, errors on "
                 << num_err;
       return (num_done == 0 ? -1 : 0);
     } else {
       // We're operating on rxfilenames|wxfilenames, most likely files.
       std::vector<Matrix<BaseFloat> > feats(po.NumArgs() - 1);
       for (int32 i = 1; i < po.NumArgs(); i++)
         ReadKaldiObject(po.GetArg(i), &(feats[i-1]));
       Matrix<BaseFloat> output;
       if (!AppendFeats(feats, "", length_tolerance, &output))
         return 1; // it will have printed a warning.
       std::string output_wxfilename = po.GetArg(po.NumArgs());
       WriteKaldiObject(output, output_wxfilename, binary);
       KALDI_LOG << "Wrote appended features to " << output_wxfilename;
       return 0;
     }
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }