Kaldi: nnet2bin/raw-nnet-info.cc File Reference
raw-nnet-info.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet2/nnet-nnet.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file raw-nnet-info.cc.
References ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), and kaldi::ReadKaldiObject().
{
   try {
     using namespace kaldi;
     using namespace kaldi::nnet2;
     typedef kaldi::int32 int32;
     const char *usage =
         "Print human-readable information about the raw neural network\n"
         "to the standard output\n"
         "Usage:  raw-nnet-info [options] <nnet-in>\n"
         "e.g.:\n"
         " raw-nnet-info 1.nnet\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 1) {
       po.PrintUsage();
       exit(1);
     }
     std::string raw_nnet_rxfilename = po.GetArg(1);
     Nnet nnet;
     ReadKaldiObject(raw_nnet_rxfilename, &nnet);
     std::cout << nnet.Info();
     KALDI_LOG << "Printed info about " << raw_nnet_rxfilename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }