Kaldi: sgmmbin/sgmm-calc-distances.cc File Reference
sgmm-calc-distances.cc File Reference
#include "util/common-utils.h"
#include "sgmm/am-sgmm.h"
#include "hmm/transition-model.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file sgmm-calc-distances.cc.
References AmSgmmFunctions::ComputeDistances(), ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), TransitionModel::Read(), kaldi::ReadKaldiObject(), ParseOptions::Register(), Output::Stream(), and Input::Stream().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Compute matrix of approximated K-L divergences between states\n"
         "Only works properly if a single substate per state.\n"
         "Usage: sgmm-calc-distances [options] model-in occs-in distances-out\n";
     bool binary = true;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() != 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1),
         occs_in_filename = po.GetArg(2),
         distances_out_filename = po.GetArg(3);
     AmSgmm am_sgmm;
     {
       bool binary;
       Input ki(model_in_filename, &binary);
       TransitionModel trans_model;
       trans_model.Read(ki.Stream(), binary);
       am_sgmm.Read(ki.Stream(), binary);
     }
     Vector<BaseFloat> occs;
     ReadKaldiObject(occs_in_filename, &occs);
     Matrix<BaseFloat> dists(am_sgmm.NumPdfs(), am_sgmm.NumPdfs());
     AmSgmmFunctions::ComputeDistances(am_sgmm, occs, &dists);
     Output ko(distances_out_filename, binary);
     dists.Write(ko.Stream(), binary);
     KALDI_LOG << "Wrote distances to " << distances_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }