Kaldi: sgmmbin/sgmm-write-ubm.cc File Reference
sgmm-write-ubm.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "sgmm/am-sgmm.h"
#include "hmm/transition-model.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file sgmm-write-ubm.cc.
References ParseOptions::GetArg(), KALDI_LOG, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), Output::Stream(), and Input::Stream().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Write out the full-covariance UBM of the SGMM\n"
         "Usage: sgmm-write-ubm [options] <model-in> <ubm-out>\n"
         "e.g.: sgmm-write-ubm 1.mdl 1.ubm\n";
     bool binary_write = true;
     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string model_in_filename = po.GetArg(1),
         ubm_out_filename = po.GetArg(2);
     AmSgmm am_sgmm;
     TransitionModel trans_model;
     {
       bool binary;
       Input ki(model_in_filename, &binary);
       trans_model.Read(ki.Stream(), binary);
       am_sgmm.Read(ki.Stream(), binary);
     }
     {
       Output ko(ubm_out_filename, binary_write);
       am_sgmm.full_ubm().Write(ko.Stream(), binary_write);
     }
     KALDI_LOG << "Written UBM to " << ubm_out_filename;
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }