Kaldi: sgmm2bin/sgmm2-comp-prexform.cc File Reference
sgmm2-comp-prexform.cc File Reference
#include "util/common-utils.h"
#include "sgmm2/am-sgmm2.h"
#include "sgmm2/fmllr-sgmm2.h"
#include "hmm/transition-model.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 26 of file sgmm2-comp-prexform.cc.
References AmSgmm2::ComputeFmllrPreXform(), ParseOptions::GetArg(), Sgmm2FmllrGlobalParams::inv_xform_, KALDI_LOG, kaldi::kSgmmWriteAll, Sgmm2FmllrGlobalParams::mean_scatter_, ParseOptions::NumArgs(), Sgmm2FmllrGlobalParams::pre_xform_, ParseOptions::PrintUsage(), ParseOptions::Read(), TransitionModel::Read(), AmSgmm2::Read(), Vector< Real >::Read(), ParseOptions::Register(), Output::Stream(), Input::Stream(), Sgmm2FmllrGlobalParams::Write(), TransitionModel::Write(), and AmSgmm2::Write().
{
   try {
     typedef kaldi::int32 int32;
     const char *usage =
         "Compute \"pre-transform\" parameters required for estimating fMLLR with\n"
         "SGMMs, and write to a model file, after the SGMM.\n"
         "Usage: sgmm2-comp-prexform [options] <sgmm2-in> <occs-in> <sgmm-out>\n";
     bool binary = true;
     kaldi::ParseOptions po(usage);
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() < 3) {
       po.PrintUsage();
       exit(1);
     }
     std::string sgmm_in_filename = po.GetArg(1),
         occs_filename = po.GetArg(2),
         sgmm_out_filename = po.GetArg(3);
     kaldi::AmSgmm2 sgmm_in;
     kaldi::TransitionModel trans_model;
     {
       bool binary_read;
       kaldi::Input ki(sgmm_in_filename, &binary_read);
       trans_model.Read(ki.Stream(), binary_read);
       sgmm_in.Read(ki.Stream(), binary_read);
     }
     kaldi::Vector<kaldi::BaseFloat> occs;
     {
       bool binary_read;
       kaldi::Input ki(occs_filename, &binary_read);
       occs.Read(ki.Stream(), binary_read);
     }
     kaldi::Sgmm2FmllrGlobalParams fmllr_globals;
     sgmm_in.ComputeFmllrPreXform(occs, &fmllr_globals.pre_xform_,
                                  &fmllr_globals.inv_xform_,
                                  &fmllr_globals.mean_scatter_);
     {
       kaldi::Output ko(sgmm_out_filename, binary);
       trans_model.Write(ko.Stream(), binary);
       sgmm_in.Write(ko.Stream(), binary, kaldi::kSgmmWriteAll);
       fmllr_globals.Write(ko.Stream(), binary);
     }
     KALDI_LOG << "Written model to " << sgmm_out_filename;
   } catch(const std::exception &e) {
     std::cerr << e.what() << '\n';
     return -1;
   }
 }