Kaldi: feat/sinusoid-detection-test.cc File Reference
sinusoid-detection-test.cc File Reference
#include <iostream>
#include "base/kaldi-math.h"
#include "feat/sinusoid-detection.h"
Namespaces
kaldi
Functions
void AddSinusoidSimple (BaseFloat samp_freq, const Sinusoid &sinusoid, VectorBase< BaseFloat > *signal)
void UnitTestAddSinusoid ()
void UnitTestQuadraticMaximizeEqualSpaced ()
void UnitTestQuadraticMaximize ()
void UnitTestSinusoidDetector ()
void UnitTestSinusoidDetectorNoisy ()
void AddFreqToSignal (BaseFloat base_freq, BaseFloat samp_freq, BaseFloat tolerance, BaseFloat gain, VectorBase< BaseFloat > *signal)
void GenerateDtmfTestCase (BaseFloat sampling_rate, Vector< BaseFloat > *signal, std::vector< MultiSinusoidDetectorOutput > *ref_output)
void UnitTestToneDetection2 ()
int main ()
Function Documentation
int main ()
Definition at line 438 of file sinusoid-detection-test.cc.
References rnnlm::i, kaldi::SetVerboseLevel(), kaldi::UnitTestAddSinusoid(), kaldi::UnitTestQuadraticMaximize(), kaldi::UnitTestQuadraticMaximizeEqualSpaced(), kaldi::UnitTestSinusoidDetector(), kaldi::UnitTestSinusoidDetectorNoisy(), and kaldi::UnitTestToneDetection2().
            {
   using namespace kaldi;
   SetVerboseLevel(4);
   UnitTestToneDetection2();
   UnitTestAddSinusoid();
   UnitTestQuadraticMaximizeEqualSpaced();
   UnitTestQuadraticMaximize();
   for (int32 i = 0; i < 10; i++) {
     UnitTestSinusoidDetector();
     UnitTestSinusoidDetectorNoisy();
   }
 }