Kaldi: GeneralDescriptor Struct Reference
GeneralDescriptor Struct Reference
This class is only used when parsing Descriptors.
#include <nnet-descriptor.h>
Public Types
enum DescriptorType {
kAppend, kSum, kFailover, kIfDefined,
kOffset, kSwitch, kRound, kReplaceIndex,
kNodeName
}
Public Member Functions
GeneralDescriptor (DescriptorType t, int32 value1=-1, int32 value2=-1)
~GeneralDescriptor ()
GeneralDescriptor * GetNormalizedDescriptor () const
Descriptor * ConvertToDescriptor ()
void Print (const std::vector< std::string > &node_names, std::ostream &os)
Static Public Member Functions
static GeneralDescriptor * Parse (const std::vector< std::string > &node_names, const std::string **next_token)
Private Member Functions
KALDI_DISALLOW_COPY_AND_ASSIGN (GeneralDescriptor)
void ParseAppendOrSumOrSwitch (const std::vector< std::string > &node_names, const std::string **next_token)
void ParseIfDefined (const std::vector< std::string > &node_names, const std::string **next_token)
void ParseOffset (const std::vector< std::string > &node_names, const std::string **next_token)
void ParseSwitch (const std::vector< std::string > &node_names, const std::string **next_token)
void ParseFailover (const std::vector< std::string > &node_names, const std::string **next_token)
void ParseRound (const std::vector< std::string > &node_names, const std::string **next_token)
void ParseReplaceIndex (const std::vector< std::string > &node_names, const std::string **next_token)
int32 NumAppendTerms () const
GeneralDescriptor * GetAppendTerm (int32 term) const
GeneralDescriptor * NormalizeAppend () const
SumDescriptor * ConvertToSumDescriptor () const
ForwardingDescriptor * ConvertToForwardingDescriptor () const
Static Private Member Functions
static bool Normalize (GeneralDescriptor *ptr)
Private Attributes
DescriptorType descriptor_type_
int32 value1_
int32 value2_
std::vector< GeneralDescriptor * > descriptors_
Detailed Description
This class is only used when parsing Descriptors.
It is useful for normalizing descriptors that are structured in an invalid or redundant way, into a form that can be turned into a real Descriptor.
Definition at line 513 of file nnet-descriptor.h.
Member Enumeration Documentation
enum DescriptorType
Enumerator
kAppend
kSum
kFailover
kIfDefined
kOffset
kSwitch
kRound
kReplaceIndex
kNodeName
Definition at line 514 of file nnet-descriptor.h.
                       { kAppend, kSum, kFailover, kIfDefined, kOffset, kSwitch,
                         kRound, kReplaceIndex, kNodeName };
Constructor & Destructor Documentation
GeneralDescriptor (DescriptorType t, int32 value1 = -1, int32 value2 = -1) inline explicit
Definition at line 527 of file nnet-descriptor.h.
Referenced by GeneralDescriptor::GetAppendTerm(), GeneralDescriptor::Normalize(), GeneralDescriptor::NormalizeAppend(), and GeneralDescriptor::Parse().
                                                :
       descriptor_type_(t), value1_(value1), value2_(value2) { }
~GeneralDescriptor () inline
Definition at line 531 of file nnet-descriptor.h.
References kaldi::DeletePointers(), and GeneralDescriptor::descriptors_.
 { DeletePointers(&descriptors_); }
Member Function Documentation
Descriptor * ConvertToDescriptor ()
Definition at line 825 of file nnet-descriptor.cc.
References GeneralDescriptor::ConvertToSumDescriptor(), GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, GeneralDescriptor::GetNormalizedDescriptor(), rnnlm::i, and GeneralDescriptor::kAppend.
Referenced by kaldi::nnet3::NormalizeTextDescriptor(), Descriptor::Parse(), and kaldi::nnet3::UnitTestGeneralDescriptor().
{
   GeneralDescriptor *normalized = GetNormalizedDescriptor();
   std::vector<SumDescriptor*> sum_descriptors;
   if (normalized->descriptor_type_ == kAppend) {
     for (size_t i = 0; i < normalized->descriptors_.size(); i++)
       sum_descriptors.push_back(
           normalized->descriptors_[i]->ConvertToSumDescriptor());
   } else {
     sum_descriptors.push_back(normalized->ConvertToSumDescriptor());
   }
   Descriptor *ans = new Descriptor(sum_descriptors);
   delete normalized;
   return ans;
 }
ForwardingDescriptor * ConvertToForwardingDescriptor () const private
Definition at line 866 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, rnnlm::i, KALDI_ASSERT, KALDI_ERR, GeneralDescriptor::kNodeName, GeneralDescriptor::kOffset, GeneralDescriptor::kReplaceIndex, GeneralDescriptor::kRound, GeneralDescriptor::kSwitch, ReplaceIndexForwardingDescriptor::kT, ReplaceIndexForwardingDescriptor::kX, GeneralDescriptor::value1_, and GeneralDescriptor::value2_.
Referenced by GeneralDescriptor::ConvertToSumDescriptor().
{
   switch (this->descriptor_type_) {
     case kNodeName: return new SimpleForwardingDescriptor(value1_);
     case kOffset: {
       KALDI_ASSERT(descriptors_.size() == 1 && "bad descriptor");
       return new OffsetForwardingDescriptor(
           descriptors_[0]->ConvertToForwardingDescriptor(),
           Index(0, value1_, value2_));
     }
     case kSwitch: {
       std::vector<ForwardingDescriptor*> descriptors;
       for (size_t i = 0; i < descriptors_.size(); i++)
         descriptors.push_back(descriptors_[i]->ConvertToForwardingDescriptor());
       return new SwitchingForwardingDescriptor(descriptors);
     }
     case kRound: {
       KALDI_ASSERT(descriptors_.size() == 1 && "bad descriptor");
       return new RoundingForwardingDescriptor(
           descriptors_[0]->ConvertToForwardingDescriptor(),
           value1_);
     }
     case kReplaceIndex: {
       KALDI_ASSERT(descriptors_.size() == 1 && "bad descriptor");
       KALDI_ASSERT(value1_ == int32(ReplaceIndexForwardingDescriptor::kT) ||
                    value1_ == int32(ReplaceIndexForwardingDescriptor::kX));
       return new ReplaceIndexForwardingDescriptor(
           descriptors_[0]->ConvertToForwardingDescriptor(),
           value1_ == int32(ReplaceIndexForwardingDescriptor::kT) ?
           ReplaceIndexForwardingDescriptor::kT :
           ReplaceIndexForwardingDescriptor::kX,
           value2_);
     }
     default:
       KALDI_ERR << "Invalid descriptor type (failure in normalization?)";
       return NULL;
   }
 }
SumDescriptor * ConvertToSumDescriptor () const private
Definition at line 840 of file nnet-descriptor.cc.
References GeneralDescriptor::ConvertToForwardingDescriptor(), GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, KALDI_ASSERT, KALDI_ERR, GeneralDescriptor::kAppend, BinarySumDescriptor::kFailover, GeneralDescriptor::kFailover, GeneralDescriptor::kIfDefined, BinarySumDescriptor::kSum, and GeneralDescriptor::kSum.
Referenced by GeneralDescriptor::ConvertToDescriptor().
{
   KALDI_ASSERT(descriptor_type_ != kAppend &&
                "Badly normalized descriptor");
   switch (descriptor_type_) {
     case kAppend:
       KALDI_ERR << "Badly normalized descriptor";
     case kSum: case kFailover: {
       KALDI_ASSERT(descriptors_.size() == 2 && "Bad descriptor");
       return new BinarySumDescriptor(
           descriptor_type_ == kSum ?
           BinarySumDescriptor::kSum : BinarySumDescriptor::kFailover,
           descriptors_[0]->ConvertToSumDescriptor(),
           descriptors_[1]->ConvertToSumDescriptor());
     }
     case kIfDefined: {
       KALDI_ASSERT(descriptors_.size() == 1 && "Bad descriptor");
       return new OptionalSumDescriptor(
           descriptors_[0]->ConvertToSumDescriptor());
     }
     default: {
       return new SimpleSumDescriptor(this->ConvertToForwardingDescriptor());
     }
   }
 }
GeneralDescriptor * GetAppendTerm (int32 term) const private
Definition at line 624 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, GeneralDescriptor::GeneralDescriptor(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, GeneralDescriptor::kAppend, GeneralDescriptor::kNodeName, GeneralDescriptor::value1_, and GeneralDescriptor::value2_.
Referenced by GeneralDescriptor::NormalizeAppend().
{
   switch (descriptor_type_) {
     case kNodeName:
       KALDI_ASSERT(term == 0);
       return new GeneralDescriptor(kNodeName, value1_);
     case kAppend: {
       int32 cur_term = term;
       for (size_t i = 0; i < descriptors_.size(); i++) {
         int32 this_num_terms = descriptors_[i]->NumAppendTerms();
         if (cur_term < this_num_terms)
           return descriptors_[i]->GetAppendTerm(cur_term);
         else
           cur_term -= this_num_terms;
       }
       KALDI_ERR << "Code error, getting append term.";
       return NULL; // avoid compiler warning
     }
     default: {
       GeneralDescriptor *ans = new GeneralDescriptor(descriptor_type_,
                                                      value1_, value2_);
       ans->descriptors_.resize(descriptors_.size());
       for (size_t i = 0; i < descriptors_.size(); i++)
         ans->descriptors_[i] = descriptors_[i]->GetAppendTerm(term);
       return ans;
     }
   }
 }
GeneralDescriptor * GetNormalizedDescriptor () const
Definition at line 772 of file nnet-descriptor.cc.
References GeneralDescriptor::Normalize(), and GeneralDescriptor::NormalizeAppend().
Referenced by GeneralDescriptor::ConvertToDescriptor().
{
   GeneralDescriptor *ans = NormalizeAppend();
   while (Normalize(ans));  // keep normalizing as long as it changes.
   return ans;
 }
KALDI_DISALLOW_COPY_AND_ASSIGN (GeneralDescriptor) private
bool Normalize (GeneralDescriptor * ptr) static private
Definition at line 671 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, GeneralDescriptor::GeneralDescriptor(), rnnlm::i, KALDI_ASSERT, KALDI_ERR, GeneralDescriptor::kAppend, GeneralDescriptor::kFailover, GeneralDescriptor::kIfDefined, GeneralDescriptor::kOffset, GeneralDescriptor::kReplaceIndex, GeneralDescriptor::kRound, GeneralDescriptor::kSum, GeneralDescriptor::kSwitch, GeneralDescriptor::value1_, and GeneralDescriptor::value2_.
Referenced by GeneralDescriptor::GetNormalizedDescriptor().
{
   bool changed = false;
   switch (parent->descriptor_type_) {
     case kOffset: {  // this block combines Offset(Offset(x, ..), ..).
       KALDI_ASSERT(parent->descriptors_.size() == 1);
       GeneralDescriptor *child = parent->descriptors_[0];
       if (child->descriptor_type_ == kOffset) {
         KALDI_ASSERT(child->descriptors_.size() == 1);
         GeneralDescriptor *grandchild = child->descriptors_[0];
         parent->value1_ += child->value1_;
         parent->value2_ += child->value2_;
         child->descriptors_.clear();  // avoid delete in destructor.
         delete child;
         parent->descriptors_[0] = grandchild;
         changed = true;
       } else if (parent->value1_ == 0 && parent->value2_ == 0) {
         // remove redundant Offset expression like Offset(x, 0).
         parent->descriptors_.swap(child->descriptors_);
         parent->descriptor_type_ = child->descriptor_type_;
         parent->value1_ = child->value1_;
         parent->value2_ = child->value2_;
         child->descriptors_.clear();  // avoid delete in destructor.
         delete child;
         changed = true;
         break;  // break from the switch ('parent' is no longer of type
         // kOffset)', so we don't want to carry through.
       }
     }
       // ... and continue through to the next case statement.
     case kSwitch: case kRound: case kReplaceIndex: { // ..and kOffset:
       KALDI_ASSERT(parent->descriptors_.size() >= 1);
       GeneralDescriptor *child = parent->descriptors_[0];
       KALDI_ASSERT(child->descriptor_type_ != kAppend);  // would be code error
       // (already did
       // NormalizeAppend()).
       if (child->descriptor_type_ == kSum ||
           child->descriptor_type_ == kFailover ||
           child->descriptor_type_ == kIfDefined) {
         if (parent->descriptors_.size() > 1) {
           KALDI_ASSERT(parent->descriptor_type_ == kSwitch);
           KALDI_ERR << "Sum(), Failover() or IfDefined() expression inside Switch(), "
                     << "we can't currently normalize this.";
         }
         // this is a forbidden case of a sum descriptor inside a forwarding
         // descriptor.  we need to rearrange.  E.g. Offset(Sum(x, y), 1) becomes
         // Sum(Offset(x, 1), Offset(y, 1)).
         for (size_t i = 0; i < child->descriptors_.size(); i++) {
           GeneralDescriptor *grandchild = child->descriptors_[i];
           GeneralDescriptor *modified_grandchild =
               new GeneralDescriptor(parent->descriptor_type_,
                                     parent->value1_,
                                     parent->value2_);
           // modified_grandchild takes ownership of grandchild.
           modified_grandchild->descriptors_.push_back(grandchild);
           child->descriptors_[i] = modified_grandchild;
         }
         // copy all members from child to parent.
         parent->descriptor_type_ = child->descriptor_type_;
         parent->value1_ = child->value1_;
         parent->value2_ = child->value2_;
         parent->descriptors_.swap(child->descriptors_);
         child->descriptors_.clear();  // avoid delete in destructor of 'child'
         delete child;
         changed = true;
       }
       break;
     }
     case kSum: {
       KALDI_ASSERT(!parent->descriptors_.empty());
       if (parent->descriptors_.size() == 1) {
         // convert Sum(x) to just x.
         GeneralDescriptor *child = parent->descriptors_[0];
         parent->descriptor_type_ = child->descriptor_type_;
         parent->descriptors_.swap(child->descriptors_);
         parent->value1_ = child->value1_;
         parent->value2_ = child->value2_;
         child->descriptors_.clear();  // avoid delete in destructor.
         delete child;
         changed = true;
       } else if (parent->descriptors_.size() > 2) {
         // convert Sum(a, b, c, ...) to Sum(a, Sum(b, c, ...)).
         GeneralDescriptor *new_child = new GeneralDescriptor(kSum);
         // assign b, c, .. to the descriptors of new_child.
         new_child->descriptors_.insert(new_child->descriptors_.begin(),
                                        parent->descriptors_.begin() + 1,
                                        parent->descriptors_.end());
         parent->descriptors_.erase(parent->descriptors_.begin() + 1,
                                    parent->descriptors_.end());
         parent->descriptors_.push_back(new_child);
         changed = true;
       }
       break;
     }
     default: { } // empty statement.
   }
   // ... and recurse.
   for (size_t i = 0; i < parent->descriptors_.size(); i++)
     changed = changed || Normalize(parent->descriptors_[i]);
   return changed;
 }
GeneralDescriptor * NormalizeAppend () const private
Definition at line 654 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, GeneralDescriptor::GeneralDescriptor(), GeneralDescriptor::GetAppendTerm(), rnnlm::i, KALDI_ASSERT, GeneralDescriptor::kAppend, and GeneralDescriptor::NumAppendTerms().
Referenced by GeneralDescriptor::GetNormalizedDescriptor().
{
   int32 num_terms = NumAppendTerms();
   KALDI_ASSERT(num_terms > 0);
   if (num_terms == 1) {
     return GetAppendTerm(0);
   } else {
     GeneralDescriptor *ans = new GeneralDescriptor(kAppend);
     ans->descriptors_.resize(num_terms);
     for (size_t i = 0; i < num_terms; i++) {
       ans->descriptors_[i] = GetAppendTerm(i);
     }
     return ans;
   }
 }
int32 NumAppendTerms () const private
Definition at line 606 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, rnnlm::i, KALDI_ASSERT, GeneralDescriptor::kAppend, and GeneralDescriptor::kNodeName.
Referenced by GeneralDescriptor::NormalizeAppend().
{
   int32 ans = 0;
   switch (descriptor_type_) {
     case kNodeName: ans = 1; break;
     case kAppend: {
       for (size_t i = 0; i < descriptors_.size(); i++)
         ans += descriptors_[i]->NumAppendTerms();
       break;
     }
     default:
       KALDI_ASSERT(descriptors_.size() > 0);
       ans = descriptors_[0]->NumAppendTerms();
       for (size_t i = 1; i < descriptors_.size(); i++)
         KALDI_ASSERT(descriptors_[i]->NumAppendTerms() == ans);
   }
   return ans;
 }
GeneralDescriptor * Parse (const std::vector< std::string > & node_names, const std::string ** next_token) static
Definition at line 474 of file nnet-descriptor.cc.
References kaldi::nnet3::ExpectToken(), GeneralDescriptor::GeneralDescriptor(), rnnlm::i, KALDI_ERR, GeneralDescriptor::kAppend, GeneralDescriptor::kFailover, GeneralDescriptor::kIfDefined, GeneralDescriptor::kNodeName, GeneralDescriptor::kOffset, GeneralDescriptor::kReplaceIndex, GeneralDescriptor::kRound, GeneralDescriptor::kSum, GeneralDescriptor::kSwitch, GeneralDescriptor::ParseAppendOrSumOrSwitch(), GeneralDescriptor::ParseFailover(), GeneralDescriptor::ParseIfDefined(), GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), and GeneralDescriptor::ParseRound().
Referenced by kaldi::nnet3::NormalizeTextDescriptor(), Descriptor::Parse(), GeneralDescriptor::ParseAppendOrSumOrSwitch(), GeneralDescriptor::ParseFailover(), GeneralDescriptor::ParseIfDefined(), GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), GeneralDescriptor::ParseRound(), and kaldi::nnet3::UnitTestGeneralDescriptor().
{
   DescriptorType t;
   if (**next_token == "Append") {
     t = kAppend;
   } else if (**next_token == "Sum") {
     t = kSum;
   } else if (**next_token == "Failover") {
     t = kFailover;
   } else if (**next_token == "IfDefined") {
     t = kIfDefined;
   } else if (**next_token == "Offset") {
     t = kOffset;
   } else if (**next_token == "Switch") {
     t = kSwitch;
   } else if (**next_token == "Round") {
     t = kRound;
   } else if (**next_token == "ReplaceIndex") {
     t = kReplaceIndex;
   } else {
     // what we read wasn't a reserved name like Offset, etc.
     // We expect a node name in that case.
     for (size_t i = 0; i < node_names.size(); i++) {
       if (**next_token == node_names[i]) {
         GeneralDescriptor *ans = new GeneralDescriptor(kNodeName, i);
         (*next_token)++;
         return ans;
       }
     }
     KALDI_ERR << "Expected a Descriptor, got instead "
               << **next_token;
     t = kNodeName;  // suppress compiler warning.
   }
   (*next_token)++;
   ExpectToken("(", "Descriptor", next_token);
   GeneralDescriptor *ans = new GeneralDescriptor(t);
   switch (t) {
     case kAppend: case kSum: case kSwitch:
       ans->ParseAppendOrSumOrSwitch(node_names, next_token); break;
     case kFailover: ans->ParseFailover(node_names, next_token); break;
     case kIfDefined: ans->ParseIfDefined(node_names, next_token); break;
     case kOffset: ans->ParseOffset(node_names, next_token); break;
     case kRound: ans->ParseRound(node_names, next_token); break;
     case kReplaceIndex: ans->ParseReplaceIndex(node_names, next_token); break;
     default:
       KALDI_ERR << "Code error";
   }
   return ans;
 }
void ParseAppendOrSumOrSwitch (const std::vector< std::string > & node_names, const std::string ** next_token) private
Definition at line 526 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, KALDI_ERR, and GeneralDescriptor::Parse().
Referenced by GeneralDescriptor::Parse().
{
   descriptors_.push_back(Parse(node_names, next_token));
   while (true) {
     if (**next_token == ")") {
       (*next_token)++;
       return;
     } else if (**next_token == ",") {
       (*next_token)++;
       descriptors_.push_back(Parse(node_names, next_token));
     } else {
       KALDI_ERR << "Expected ',' or ')', got "
                 << **next_token;
     }
   }
 }
void ParseFailover (const std::vector< std::string > & node_names, const std::string ** next_token) private
Definition at line 551 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, kaldi::nnet3::ExpectToken(), and GeneralDescriptor::Parse().
Referenced by GeneralDescriptor::Parse().
{
   descriptors_.push_back(Parse(node_names, next_token));
   ExpectToken(",", "Failover", next_token);
   descriptors_.push_back(Parse(node_names, next_token));
   ExpectToken(")", "Failover", next_token);
 }
void ParseIfDefined (const std::vector< std::string > & node_names, const std::string ** next_token) private
Definition at line 544 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, kaldi::nnet3::ExpectToken(), and GeneralDescriptor::Parse().
Referenced by GeneralDescriptor::Parse().
{
   descriptors_.push_back(Parse(node_names, next_token));
   ExpectToken(")", "IfDefined", next_token);
 }
void ParseOffset (const std::vector< std::string > & node_names, const std::string ** next_token) private
Definition at line 560 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, kaldi::nnet3::ExpectToken(), GeneralDescriptor::Parse(), kaldi::nnet3::ReadIntegerToken(), GeneralDescriptor::value1_, and GeneralDescriptor::value2_.
Referenced by GeneralDescriptor::Parse().
{
   descriptors_.push_back(Parse(node_names, next_token));
   ExpectToken(",", "Offset", next_token);
   value1_ = ReadIntegerToken("Offset", next_token);
   if (**next_token == ",") {
     (*next_token)++;
     value2_ = ReadIntegerToken("Offset", next_token);
   } else {
     value2_ = 0;
   }
   ExpectToken(")", "Offset", next_token);
 }
void ParseReplaceIndex (const std::vector< std::string > & node_names, const std::string ** next_token) private
Definition at line 586 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, kaldi::nnet3::ExpectToken(), KALDI_ERR, ReplaceIndexForwardingDescriptor::kT, ReplaceIndexForwardingDescriptor::kX, GeneralDescriptor::Parse(), kaldi::nnet3::ReadIntegerToken(), GeneralDescriptor::value1_, and GeneralDescriptor::value2_.
Referenced by GeneralDescriptor::Parse().
{
   descriptors_.push_back(Parse(node_names, next_token));
   ExpectToken(",", "ReplaceIndex", next_token);
   if (**next_token == "t") {
     value1_ = int32(ReplaceIndexForwardingDescriptor::kT);
     (*next_token)++;
   } else if (**next_token == "x") {
     value1_ = int32(ReplaceIndexForwardingDescriptor::kX);
     (*next_token)++;
   } else {
     KALDI_ERR << "Expected 't' or 'x', got " << **next_token;
   }
   ExpectToken(",", "ReplaceIndex", next_token);
   value2_ = ReadIntegerToken("Replace", next_token);
   ExpectToken(")", "ReplaceIndex", next_token);
 }
void ParseRound (const std::vector< std::string > & node_names, const std::string ** next_token) private
Definition at line 576 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptors_, kaldi::nnet3::ExpectToken(), GeneralDescriptor::Parse(), kaldi::nnet3::ReadIntegerToken(), and GeneralDescriptor::value1_.
Referenced by GeneralDescriptor::Parse().
{
   descriptors_.push_back(Parse(node_names, next_token));
   ExpectToken(",", "Round", next_token);
   value1_ = ReadIntegerToken("Round", next_token);
   ExpectToken(")", "Round", next_token);
 }
void ParseSwitch (const std::vector< std::string > & node_names, const std::string ** next_token) private
void Print (const std::vector< std::string > & node_names, std::ostream & os)
Definition at line 778 of file nnet-descriptor.cc.
References GeneralDescriptor::descriptor_type_, GeneralDescriptor::descriptors_, rnnlm::i, KALDI_ASSERT, GeneralDescriptor::kAppend, GeneralDescriptor::kFailover, GeneralDescriptor::kIfDefined, GeneralDescriptor::kNodeName, GeneralDescriptor::kOffset, GeneralDescriptor::kReplaceIndex, GeneralDescriptor::kRound, GeneralDescriptor::kSum, GeneralDescriptor::kSwitch, ReplaceIndexForwardingDescriptor::kT, ReplaceIndexForwardingDescriptor::kX, GeneralDescriptor::value1_, and GeneralDescriptor::value2_.
{
   switch (descriptor_type_) {
     // first handle all the expressions of the form "Operator(<desc1>, ... <descN>)".
     case kAppend: os << "Append("; break;
     case kSum: os << "Sum("; break;
     case kFailover: os << "Failover("; break;
     case kIfDefined: os << "IfDefined("; break;
     case kSwitch: os << "Switch("; break;
       // now handle the exceptions.
     case kOffset: case kRound: {
       os << "Offset(";
       KALDI_ASSERT(descriptors_.size() == 1);
       descriptors_[0]->Print(node_names, os);
       os << ", " << value1_;
       if (descriptor_type_ == kOffset && value2_ != 0) os << ", " << value2_;
       os << ")";
       return;
     }
     case kReplaceIndex: {
       os << "ReplaceIndex(";
       KALDI_ASSERT(descriptors_.size() == 1);
       descriptors_[0]->Print(node_names, os);
       KALDI_ASSERT(value1_ == int32(ReplaceIndexForwardingDescriptor::kT) ||
                    value1_ == int32(ReplaceIndexForwardingDescriptor::kX));
       if (value1_ == int32(ReplaceIndexForwardingDescriptor::kT)) {
         os << ", t, ";
       } else {
         os << ", x, ";
       }
       os << value2_ << ")";
       return;
     }
     case kNodeName: {
       KALDI_ASSERT(static_cast<size_t>(value1_) < node_names.size());
       os << node_names[value1_];
       return;
     }
   }
   for (size_t i = 0; i < descriptors_.size(); i++) {
     if (i > 0) os << ", ";
     descriptors_[i]->Print(node_names, os);
   }
   os << ")";
 }
Member Data Documentation
DescriptorType descriptor_type_ private
Definition at line 544 of file nnet-descriptor.h.
Referenced by GeneralDescriptor::ConvertToDescriptor(), GeneralDescriptor::ConvertToForwardingDescriptor(), GeneralDescriptor::ConvertToSumDescriptor(), GeneralDescriptor::GetAppendTerm(), GeneralDescriptor::Normalize(), GeneralDescriptor::NumAppendTerms(), and GeneralDescriptor::Print().
std::vector<GeneralDescriptor*> descriptors_ private
Definition at line 555 of file nnet-descriptor.h.
Referenced by GeneralDescriptor::ConvertToDescriptor(), GeneralDescriptor::ConvertToForwardingDescriptor(), GeneralDescriptor::ConvertToSumDescriptor(), GeneralDescriptor::GetAppendTerm(), GeneralDescriptor::Normalize(), GeneralDescriptor::NormalizeAppend(), GeneralDescriptor::NumAppendTerms(), GeneralDescriptor::ParseAppendOrSumOrSwitch(), GeneralDescriptor::ParseFailover(), GeneralDescriptor::ParseIfDefined(), GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), GeneralDescriptor::ParseRound(), GeneralDescriptor::Print(), and GeneralDescriptor::~GeneralDescriptor().
int32 value1_ private
Definition at line 548 of file nnet-descriptor.h.
Referenced by GeneralDescriptor::ConvertToForwardingDescriptor(), GeneralDescriptor::GetAppendTerm(), GeneralDescriptor::Normalize(), GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), GeneralDescriptor::ParseRound(), and GeneralDescriptor::Print().
int32 value2_ private
Definition at line 551 of file nnet-descriptor.h.
Referenced by GeneralDescriptor::ConvertToForwardingDescriptor(), GeneralDescriptor::GetAppendTerm(), GeneralDescriptor::Normalize(), GeneralDescriptor::ParseOffset(), GeneralDescriptor::ParseReplaceIndex(), and GeneralDescriptor::Print().
The documentation for this struct was generated from the following files:
nnet3/nnet-descriptor.h
nnet3/nnet-descriptor.cc