Kaldi: Component Class Reference
Component Class Reference abstract
Abstract class, building block of the network.
#include <nnet-component.h>
Classes
struct key_value
A pair of type and marker.
Public Types
enum ComponentType {
kUnknown = 0x0, kUpdatableComponent = 0x0100, kAffineTransform, kLinearTransform,
kConvolutionalComponent, kConvolutional2DComponent, kLstmProjectedStreams, kBLstmProjectedStreams,
scTCNComponent, scTCNProjectionComponent, kActivationFunction = 0x0200, kSoftmax,
kBlockSoftmax, kSigmoid, kTanh, kDropout,
kLengthNormComponent, kTranform = 0x0400, kRbm, kSplice,
kCopy, kTranspose, kBlockLinearity, kAddShift,
kRescale, kKlHmm = 0x0800, kSentenceAveragingComponent, kSimpleSentenceAveragingComponent,
kAveragePoolingComponent, kAveragePooling2DComponent, kMaxPoolingComponent, kMaxPooling2DComponent,
kFramePoolingComponent, kParallelComponent
}
Component type identification mechanism.
Public Member Functions
Component (int32 input_dim, int32 output_dim)
General interface of a component.
virtual ~Component ()
virtual Component * Copy () const =0
Copy component (deep copy).
virtual ComponentType GetType () const =0
Get Type Identification of the component.
virtual bool IsUpdatable () const
Check if contains trainable parameters.
int32 InputDim () const
Get size of input vectors.
int32 OutputDim () const
Get size of output vectors.
void Propagate (const CuMatrixBase< BaseFloat > &in, CuMatrix< BaseFloat > *out)
Perform forward pass propagation Input->Output.
void Backpropagate (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrix< BaseFloat > *in_diff)
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
void Write (std::ostream &os, bool binary) const
Write component to stream.
virtual std::string Info () const
Optionally print some additional info.
virtual std::string InfoGradient () const
Static Public Member Functions
static const char * TypeToMarker (ComponentType t)
Convert component type to marker.
static ComponentType MarkerToType (const std::string &s)
Convert marker to component type (case insensitive)
static Component * Init (const std::string &conf_line)
Initialize component from a line in config file.
static Component * Read (std::istream &is, bool binary)
Read component from stream.
Static Public Attributes
static const struct key_value kMarkerMap []
Mapping of types and markers (the table is defined in nnet-component.cc)
Protected Member Functions
virtual void PropagateFnc (const CuMatrixBase< BaseFloat > &in, CuMatrixBase< BaseFloat > *out)=0
Abstract interface for propagation/backpropagation.
virtual void BackpropagateFnc (const CuMatrixBase< BaseFloat > &in, const CuMatrixBase< BaseFloat > &out, const CuMatrixBase< BaseFloat > &out_diff, CuMatrixBase< BaseFloat > *in_diff)=0
Backward pass transformation (to be implemented by descending class...)
virtual void InitData (std::istream &is)
Initialize internal data of a component.
virtual void ReadData (std::istream &is, bool binary)
Reads the component content.
virtual void WriteData (std::ostream &os, bool binary) const
Writes the component content.
Protected Attributes
int32 input_dim_
Data members.
int32 output_dim_
Size of output vectors.
Static Private Member Functions
static Component * NewComponentOfType (ComponentType t, int32 input_dim, int32 output_dim)
Create new intance of component.
Detailed Description
Abstract class, building block of the network.
It is able to propagate (PropagateFnc: compute the output based on its input) and backpropagate (BackpropagateFnc: i.e. transform loss derivative w.r.t. output to derivative w.r.t. the input) the formulas are implemented in descendant classes (AffineTransform,Sigmoid,Softmax,...).
Definition at line 54 of file nnet-component.cc.
Member Enumeration Documentation
enum ComponentType
Component type identification mechanism.
Types of Components
Enumerator
kUnknown
kUpdatableComponent
kAffineTransform
kLinearTransform
kConvolutionalComponent
kConvolutional2DComponent
kLstmProjectedStreams
kBLstmProjectedStreams
scTCNComponent
scTCNProjectionComponent
kActivationFunction
kSoftmax
kBlockSoftmax
kSigmoid
kTanh
kDropout
kLengthNormComponent
kTranform
kRbm
kSplice
kCopy
kTranspose
kBlockLinearity
kAddShift
kRescale
kKlHmm
kSentenceAveragingComponent
kSimpleSentenceAveragingComponent
kAveragePoolingComponent
kAveragePooling2DComponent
kMaxPoolingComponent
kMaxPooling2DComponent
kFramePoolingComponent
kParallelComponent
Definition at line 48 of file nnet-component.h.
                {
     kUnknown = 0x0,
     kUpdatableComponent = 0x0100,
     kAffineTransform,
     kLinearTransform,
     kConvolutionalComponent,
     kConvolutional2DComponent,
     kLstmProjectedStreams,
     kBLstmProjectedStreams,
     scTCNComponent,//my TCN method
     scTCNProjectionComponent,//my TCN projection method
     kActivationFunction = 0x0200,
     kSoftmax,
     kBlockSoftmax,
     kSigmoid,
     kTanh,
     kDropout,
     kLengthNormComponent,
     kTranform = 0x0400,
     kRbm,
     kSplice,
     kCopy,
     kTranspose,
     kBlockLinearity,
     kAddShift,
     kRescale,
     kKlHmm = 0x0800,
     kSentenceAveragingComponent, /* deprecated */
     kSimpleSentenceAveragingComponent,
     kAveragePoolingComponent,
     kAveragePooling2DComponent,
     kMaxPoolingComponent,
     kMaxPooling2DComponent,
     kFramePoolingComponent,
     kParallelComponent
   } ComponentType;
Constructor & Destructor Documentation
Component (int32 input_dim, int32 output_dim) inline
General interface of a component.
Definition at line 102 of file nnet-component.h.
       : input_dim_(input_dim), output_dim_(output_dim) { }
virtual ~Component () inline virtual
Definition at line 104 of file nnet-component.h.
 { }
Member Function Documentation
void Backpropagate (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrix< BaseFloat > * in_diff) inline
Perform backward pass propagation, out_diff -> in_diff '&in' and '&out' will sometimes be unused...
Definition at line 235 of file nnet-component.h.
References Component::BackpropagateFnc(), Component::GetType(), Component::input_dim_, KALDI_ASSERT, KALDI_ERR, Component::kParallelComponent, Component::kSentenceAveragingComponent, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, and CuMatrix< Real >::Resize().
Referenced by kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestConvolutional2DComponent(), kaldi::nnet1::UnitTestConvolutionalComponent3x3(), kaldi::nnet1::UnitTestConvolutionalComponentUnity(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), kaldi::nnet1::UnitTestMaxPoolingComponent(), and kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent().
{
   // Check the dims
   if (output_dim_ != out_diff.NumCols()) {
     KALDI_ERR << "Non-matching output dims, component:" << output_dim_
               << " data:" << out_diff.NumCols();
   }
   // Target buffer NULL : backpropagate only through components with nested nnets.
   if (in_diff == NULL) {
     if (GetType() == kParallelComponent ||
         GetType() == kSentenceAveragingComponent) {
       BackpropagateFnc(in, out, out_diff, NULL);
     } else {
       return;
     }
   } else {
     // Allocate target buffer
     in_diff->Resize(out_diff.NumRows(), input_dim_, kSetZero); // reset
     // Asserts on the dims
     KALDI_ASSERT((in.NumRows() == out.NumRows()) &&
                  (in.NumRows() == out_diff.NumRows()) &&
                  (in.NumRows() == in_diff->NumRows()));
     KALDI_ASSERT(in.NumCols() == in_diff->NumCols());
     KALDI_ASSERT(out.NumCols() == out_diff.NumCols());
     // Call the backprop implementation of the component
     BackpropagateFnc(in, out, out_diff, in_diff);
   }
 }
virtual void BackpropagateFnc (const CuMatrixBase< BaseFloat > & in, const CuMatrixBase< BaseFloat > & out, const CuMatrixBase< BaseFloat > & out_diff, CuMatrixBase< BaseFloat > * in_diff) protected pure virtual
Backward pass transformation (to be implemented by descending class...)
Implemented in BLstmProjectedStreams, Rescale, LstmProjectedStreams, AddShift, ConvolutionalComponent, LengthNormComponent, Convolutional2DComponent, TCNComponent, TCNComponent, CopyComponent, Dropout, FramePoolingComponent, ParallelComponent, TCNProjectionComponent, Tanh, SentenceAveragingComponent, Sigmoid, AffineTransform, AveragePooling2DComponent, MaxPooling2DComponent, Splice, LinearTransform, BlockSoftmax, AveragePoolingComponent, MaxPoolingComponent, KlHmm, SimpleSentenceAveragingComponent, RbmBase, and Softmax.
Referenced by Component::Backpropagate().
virtual Component* Copy () const pure virtual
Copy component (deep copy).
Implemented in Rescale, AddShift, LengthNormComponent, Dropout, Tanh, CopyComponent, Sigmoid, SentenceAveragingComponent, Rbm, Convolutional2DComponent, ConvolutionalComponent, BlockSoftmax, BLstmProjectedStreams, LstmProjectedStreams, AveragePooling2DComponent, FramePoolingComponent, MaxPooling2DComponent, SimpleSentenceAveragingComponent, Splice, AveragePoolingComponent, MaxPoolingComponent, AffineTransform, KlHmm, ParallelComponent, Softmax, LinearTransform, TCNComponent, TCNComponent, and TCNProjectionComponent.
Referenced by Nnet::AppendNnet(), Nnet::Nnet(), and Nnet::operator=().
virtual ComponentType GetType () const pure virtual
Get Type Identification of the component.
Implemented in Rescale, AddShift, LengthNormComponent, Dropout, Tanh, CopyComponent, Sigmoid, SentenceAveragingComponent, Rbm, Convolutional2DComponent, ConvolutionalComponent, BlockSoftmax, BLstmProjectedStreams, LstmProjectedStreams, AveragePooling2DComponent, FramePoolingComponent, MaxPooling2DComponent, SimpleSentenceAveragingComponent, Splice, AveragePoolingComponent, MaxPoolingComponent, AffineTransform, KlHmm, ParallelComponent, Softmax, LinearTransform, TCNComponent, TCNComponent, and TCNProjectionComponent.
Referenced by Component::Backpropagate(), kaldi::ConvertComponent(), Component::Propagate(), Nnet::ResetLstmStreams(), Nnet::SetDropoutRetention(), Nnet::SetSeqLengths(), and Component::Write().
virtual std::string Info () const inline virtual
Optionally print some additional info.
Reimplemented in Rescale, AddShift, BLstmProjectedStreams, CopyComponent, Convolutional2DComponent, ConvolutionalComponent, LstmProjectedStreams, TCNComponent, TCNComponent, FramePoolingComponent, TCNProjectionComponent, SentenceAveragingComponent, ParallelComponent, BlockSoftmax, AffineTransform, Splice, LinearTransform, and SimpleSentenceAveragingComponent.
Definition at line 142 of file nnet-component.h.
 { return ""; }
virtual std::string InfoGradient () const inline virtual
Reimplemented in Rescale, AddShift, BLstmProjectedStreams, Convolutional2DComponent, LstmProjectedStreams, ConvolutionalComponent, TCNComponent, TCNComponent, FramePoolingComponent, TCNProjectionComponent, ParallelComponent, SentenceAveragingComponent, AffineTransform, LinearTransform, and SimpleSentenceAveragingComponent.
Definition at line 143 of file nnet-component.h.
 { return ""; }
Component * Init (const std::string & conf_line) static
Initialize component from a line in config file.
Definition at line 208 of file nnet-component.cc.
References kaldi::ExpectToken(), Component::InitData(), Component::MarkerToType(), Component::NewComponentOfType(), kaldi::ReadBasicType(), and kaldi::ReadToken().
Referenced by Nnet::Init(), kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), and kaldi::nnet1::UnitTestMaxPoolingComponent().
{
   std::istringstream is(conf_line);
   std::string component_type_string;
   int32 input_dim, output_dim;
   // initialize component w/o internal data
   ReadToken(is, false, &component_type_string);
   ComponentType component_type = MarkerToType(component_type_string);
   ExpectToken(is, false, "<InputDim>");
   ReadBasicType(is, false, &input_dim);
   ExpectToken(is, false, "<OutputDim>");
   ReadBasicType(is, false, &output_dim);
   Component *ans = NewComponentOfType(component_type, input_dim, output_dim);
   // initialize internal data with the remaining part of config line
   ans->InitData(is);
   return ans;
 }
virtual void InitData (std::istream & is) inline protected virtual
Initialize internal data of a component.
Reimplemented in Rescale, AddShift, UpdatableComponent, Dropout, CopyComponent, SentenceAveragingComponent, Rbm, Convolutional2DComponent, BLstmProjectedStreams, ConvolutionalComponent, LstmProjectedStreams, BlockSoftmax, FramePoolingComponent, AveragePooling2DComponent, MaxPooling2DComponent, SimpleSentenceAveragingComponent, Splice, AveragePoolingComponent, MaxPoolingComponent, AffineTransform, ParallelComponent, LinearTransform, TCNComponent, TCNProjectionComponent, and TCNComponent.
Definition at line 158 of file nnet-component.h.
Referenced by Component::Init().
 { }
int32 InputDim () const inline
Get size of input vectors.
Definition at line 117 of file nnet-component.h.
References Component::input_dim_.
Referenced by kaldi::ConvertSigmoidComponent(), kaldi::ConvertSoftmaxComponent(), kaldi::ConvertSpliceComponent(), AddShift::GetParams(), Rescale::GetParams(), ParallelComponent::InitData(), Splice::InitData(), FramePoolingComponent::InitData(), Rbm::InitData(), SentenceAveragingComponent::InitData(), CopyComponent::InitData(), AddShift::InitData(), Rescale::InitData(), SimpleSentenceAveragingComponent::PropagateFnc(), Nnet::Read(), ParallelComponent::ReadData(), FramePoolingComponent::ReadData(), Splice::ReadData(), SentenceAveragingComponent::ReadData(), AddShift::Update(), Rescale::Update(), Component::Write(), and Rbm::WriteAsNnet().
{
     return input_dim_;
   }
virtual bool IsUpdatable () const inline virtual
Check if contains trainable parameters.
Reimplemented in UpdatableComponent.
Definition at line 112 of file nnet-component.h.
Referenced by Nnet::SetTrainOptions().
{
     return false;
   }
Component::ComponentType MarkerToType (const std::string & s) static
Convert marker to component type (case insensitive)
Definition at line 95 of file nnet-component.cc.
References rnnlm::i, KALDI_ERR, Component::kMarkerMap, and Component::kUnknown.
Referenced by Component::Init(), and Component::Read().
{
   std::string s_lowercase(s);
   std::transform(s.begin(), s.end(), s_lowercase.begin(), ::tolower); // lc
   int32 N=sizeof(kMarkerMap)/sizeof(kMarkerMap[0]);
   for(int i=0; i<N; i++) {
     std::string m(kMarkerMap[i].value);
     std::string m_lowercase(m);
     std::transform(m.begin(), m.end(), m_lowercase.begin(), ::tolower);
     if (s_lowercase == m_lowercase) return kMarkerMap[i].key;
   }
   KALDI_ERR << "Unknown marker : '" << s << "'";
   return kUnknown;
 }
Component * NewComponentOfType (ComponentType t, int32 input_dim, int32 output_dim) static private
Create new intance of component.
Definition at line 110 of file nnet-component.cc.
References Component::kAddShift, Component::kAffineTransform, KALDI_ERR, Component::kAveragePooling2DComponent, Component::kAveragePoolingComponent, Component::kBlockSoftmax, Component::kBLstmProjectedStreams, Component::kConvolutional2DComponent, Component::kConvolutionalComponent, Component::kCopy, Component::kDropout, Component::kFramePoolingComponent, Component::kKlHmm, Component::kLengthNormComponent, Component::kLinearTransform, Component::kLstmProjectedStreams, Component::kMaxPooling2DComponent, Component::kMaxPoolingComponent, Component::kParallelComponent, Component::kRbm, Component::kRescale, Component::kSentenceAveragingComponent, Component::kSigmoid, Component::kSimpleSentenceAveragingComponent, Component::kSoftmax, Component::kSplice, Component::kTanh, Component::kUnknown, Component::scTCNComponent, Component::scTCNProjectionComponent, kaldi::cu::Splice(), and Component::TypeToMarker().
Referenced by Component::Init(), and Component::Read().
{
   Component *ans = NULL;
   switch (comp_type) {
     case Component::kAffineTransform :
       ans = new AffineTransform(input_dim, output_dim);
       break;
     case Component::kLinearTransform :
       ans = new LinearTransform(input_dim, output_dim);
       break;
     case Component::kConvolutionalComponent :
       ans = new ConvolutionalComponent(input_dim, output_dim);
       break;
     case Component::kConvolutional2DComponent :
       ans = new Convolutional2DComponent(input_dim, output_dim);
       break;
     case Component::kLstmProjectedStreams :
       ans = new LstmProjectedStreams(input_dim, output_dim);
       break;
     case Component::kBLstmProjectedStreams :
       ans = new BLstmProjectedStreams(input_dim, output_dim);
       break;
     case Component::kSoftmax :
       ans = new Softmax(input_dim, output_dim);
       break;
     case Component::kBlockSoftmax :
       ans = new BlockSoftmax(input_dim, output_dim);
       break;
     case Component::kSigmoid :
       ans = new Sigmoid(input_dim, output_dim);
       break;
     case Component::kTanh :
       ans = new Tanh(input_dim, output_dim);
       break;
     case Component::kDropout :
       ans = new Dropout(input_dim, output_dim);
       break;
     case Component::kLengthNormComponent :
       ans = new LengthNormComponent(input_dim, output_dim);
       break;
     case Component::kRbm :
       ans = new Rbm(input_dim, output_dim);
       break;
     case Component::kSplice :
       ans = new Splice(input_dim, output_dim);
       break;
     case Component::kCopy :
       ans = new CopyComponent(input_dim, output_dim);
       break;
     case Component::kAddShift :
       ans = new AddShift(input_dim, output_dim);
       break;
     case Component::kRescale :
       ans = new Rescale(input_dim, output_dim);
       break;
     case Component::kKlHmm :
       ans = new KlHmm(input_dim, output_dim);
       break;
     case Component::kSentenceAveragingComponent :
       ans = new SentenceAveragingComponent(input_dim, output_dim);
       break;
     case Component::kSimpleSentenceAveragingComponent :
       ans = new SimpleSentenceAveragingComponent(input_dim, output_dim);
       break;
     case Component::kAveragePoolingComponent :
       ans = new AveragePoolingComponent(input_dim, output_dim);
       break;
     case Component::kAveragePooling2DComponent :
       ans = new AveragePooling2DComponent(input_dim, output_dim);
       break;
     case Component::kMaxPoolingComponent :
       ans = new MaxPoolingComponent(input_dim, output_dim);
       break;
     case Component::kMaxPooling2DComponent :
       ans = new MaxPooling2DComponent(input_dim, output_dim);
       break;
     case Component::kFramePoolingComponent :
       ans = new FramePoolingComponent(input_dim, output_dim);
       break;
     case Component::kParallelComponent :
       ans = new ParallelComponent(input_dim, output_dim);
       break;
     // new TCN Component
     case Component::scTCNComponent :
       ans = new TCNComponent(input_dim, output_dim);
       break;
     // new TCNProjection Component
     case Component::scTCNProjectionComponent :
       ans = new TCNProjectionComponent(input_dim, output_dim);
       break;
     case Component::kUnknown :
     default :
       KALDI_ERR << "Missing type: " << TypeToMarker(comp_type);
   }
   return ans;
 }
int32 OutputDim () const inline
Get size of output vectors.
Definition at line 121 of file nnet-component.h.
References Component::output_dim_.
Referenced by SimpleSentenceAveragingComponent::BackpropagateFnc(), ParallelComponent::InitData(), Splice::InitData(), BlockSoftmax::InitData(), SentenceAveragingComponent::InitData(), CopyComponent::InitData(), BlockSoftmax::ReadData(), ParallelComponent::ReadData(), Splice::ReadData(), SentenceAveragingComponent::ReadData(), CopyComponent::ReadData(), AffineTransform::Update(), Component::Write(), and Rbm::WriteAsNnet().
{
     return output_dim_;
   }
void Propagate (const CuMatrixBase< BaseFloat > & in, CuMatrix< BaseFloat > * out) inline
Perform forward pass propagation Input->Output.
Definition at line 221 of file nnet-component.h.
References Component::GetType(), Component::input_dim_, KALDI_ERR, kaldi::kSetZero, CuMatrixBase< Real >::NumCols(), CuMatrixBase< Real >::NumRows(), Component::output_dim_, Component::PropagateFnc(), CuMatrix< Real >::Resize(), and Component::TypeToMarker().
Referenced by kaldi::nnet1::UnitTestAveragePooling2DComponent(), kaldi::nnet1::UnitTestConvolutional2DComponent(), kaldi::nnet1::UnitTestConvolutionalComponent3x3(), kaldi::nnet1::UnitTestConvolutionalComponentUnity(), kaldi::nnet1::UnitTestLengthNorm(), kaldi::nnet1::UnitTestMaxPooling2DComponent(), kaldi::nnet1::UnitTestMaxPoolingComponent(), and kaldi::nnet1::UnitTestSimpleSentenceAveragingComponent().
{
   // Check the dims
   if (input_dim_ != in.NumCols()) {
     KALDI_ERR << "Non-matching dims! " << TypeToMarker(GetType())
               << " input-dim : " << input_dim_ << " data : " << in.NumCols();
   }
   // Allocate target buffer
   out->Resize(in.NumRows(), output_dim_, kSetZero); // reset
   // Call the propagation implementation of the component
   PropagateFnc(in, out);
 }
virtual void PropagateFnc (const CuMatrixBase< BaseFloat > & in, CuMatrixBase< BaseFloat > * out) protected pure virtual
Abstract interface for propagation/backpropagation.
Forward pass transformation (to be implemented by descending class...)
Implemented in Rescale, BLstmProjectedStreams, AddShift, LengthNormComponent, LstmProjectedStreams, CopyComponent, Convolutional2DComponent, Dropout, TCNComponent, TCNComponent, ConvolutionalComponent, Rbm, FramePoolingComponent, ParallelComponent, TCNProjectionComponent, Tanh, SentenceAveragingComponent, Sigmoid, AffineTransform, Splice, AveragePooling2DComponent, MaxPooling2DComponent, LinearTransform, BlockSoftmax, AveragePoolingComponent, MaxPoolingComponent, SimpleSentenceAveragingComponent, KlHmm, and Softmax.
Referenced by Component::Propagate().
Component * Read (std::istream & is, bool binary) static
Read component from stream.
Definition at line 229 of file nnet-component.cc.
References Component::MarkerToType(), Component::NewComponentOfType(), kaldi::Peek(), kaldi::ReadBasicType(), Component::ReadData(), and kaldi::ReadToken().
Referenced by Nnet::Read(), and kaldi::nnet1::ReadComponentFromString().
{
   int32 dim_out, dim_in;
   std::string token;
   int first_char = Peek(is, binary);
   if (first_char == EOF) return NULL;
   ReadToken(is, binary, &token);
   // Skip optional initial token
   if(token == "<Nnet>") {
     ReadToken(is, binary, &token); // Next token is a Component
   }
   // Finish reading when optional terminal token appears
   if(token == "</Nnet>") {
     return NULL;
   }
   ReadBasicType(is, binary, &dim_out);
   ReadBasicType(is, binary, &dim_in);
   Component *ans = NewComponentOfType(MarkerToType(token), dim_in, dim_out);
   ans->ReadData(is, binary);
   return ans;
 }
virtual void ReadData (std::istream & is, bool binary) inline protected virtual
Reads the component content.
Reimplemented in Rescale, AddShift, CopyComponent, Dropout, Rbm, BLstmProjectedStreams, Convolutional2DComponent, SentenceAveragingComponent, ConvolutionalComponent, LstmProjectedStreams, TCNComponent, TCNComponent, Splice, FramePoolingComponent, KlHmm, TCNProjectionComponent, ParallelComponent, BlockSoftmax, AffineTransform, LinearTransform, AveragePooling2DComponent, MaxPooling2DComponent, AveragePoolingComponent, MaxPoolingComponent, and SimpleSentenceAveragingComponent.
Definition at line 161 of file nnet-component.h.
Referenced by Component::Read().
 { }
const char * TypeToMarker (ComponentType t) static
Convert component type to marker.
Definition at line 86 of file nnet-component.cc.
References rnnlm::i, KALDI_ERR, and Component::kMarkerMap.
Referenced by kaldi::ConvertComponent(), Nnet::GetGradient(), Nnet::GetWeights(), Nnet::Info(), Nnet::InfoBackPropagate(), Nnet::InfoGradient(), Nnet::InfoPropagate(), main(), Component::NewComponentOfType(), Component::Propagate(), Nnet::SetWeights(), Component::Write(), and Rbm::WriteAsNnet().
{
   int32 N=sizeof(kMarkerMap)/sizeof(kMarkerMap[0]);
   for(int i=0; i<N; i++) {
     if (kMarkerMap[i].key == t) return kMarkerMap[i].value;
   }
   KALDI_ERR << "Unknown type" << t;
   return NULL;
 }
void Write (std::ostream & os, bool binary) const
Write component to stream.
Definition at line 255 of file nnet-component.cc.
References Component::GetType(), Component::InputDim(), Component::OutputDim(), Component::TypeToMarker(), kaldi::WriteBasicType(), Component::WriteData(), and kaldi::WriteToken().
Referenced by main().
{
   WriteToken(os, binary, Component::TypeToMarker(GetType()));
   WriteBasicType(os, binary, OutputDim());
   WriteBasicType(os, binary, InputDim());
   if(!binary) os << "\n";
   this->WriteData(os, binary);
 }
virtual void WriteData (std::ostream & os, bool binary) const inline protected virtual
Writes the component content.
Reimplemented in Rescale, AddShift, CopyComponent, Dropout, BLstmProjectedStreams, Rbm, Convolutional2DComponent, ConvolutionalComponent, LstmProjectedStreams, TCNComponent, TCNComponent, SentenceAveragingComponent, FramePoolingComponent, TCNProjectionComponent, ParallelComponent, Splice, KlHmm, AffineTransform, AveragePooling2DComponent, MaxPooling2DComponent, BlockSoftmax, LinearTransform, AveragePoolingComponent, MaxPoolingComponent, and SimpleSentenceAveragingComponent.
Definition at line 164 of file nnet-component.h.
Referenced by Component::Write().
 { }
Member Data Documentation
int32 input_dim_ protected
Data members.
Size of input vectors
Definition at line 168 of file nnet-component.h.
Referenced by Component::Backpropagate(), MaxPoolingComponent::BackpropagateFnc(), AveragePoolingComponent::BackpropagateFnc(), MaxPooling2DComponent::BackpropagateFnc(), AveragePooling2DComponent::BackpropagateFnc(), Convolutional2DComponent::BackpropagateFnc(), LinearTransform::InitData(), AffineTransform::InitData(), LstmProjectedStreams::InitData(), ConvolutionalComponent::InitData(), BLstmProjectedStreams::InitData(), Convolutional2DComponent::InitData(), Rbm::InitData(), Component::InputDim(), Component::Propagate(), MaxPoolingComponent::PropagateFnc(), AveragePoolingComponent::PropagateFnc(), AveragePooling2DComponent::PropagateFnc(), MaxPooling2DComponent::PropagateFnc(), ConvolutionalComponent::PropagateFnc(), Convolutional2DComponent::PropagateFnc(), Rbm::RbmUpdate(), MaxPoolingComponent::ReadData(), AveragePoolingComponent::ReadData(), MaxPooling2DComponent::ReadData(), AveragePooling2DComponent::ReadData(), LinearTransform::ReadData(), AffineTransform::ReadData(), KlHmm::ReadData(), FramePoolingComponent::ReadData(), LstmProjectedStreams::ReadData(), ConvolutionalComponent::ReadData(), Convolutional2DComponent::ReadData(), BLstmProjectedStreams::ReadData(), Rbm::ReadData(), Rbm::Reconstruct(), ConvolutionalComponent::ReverseIndexes(), and KlHmm::SetStats().
const struct key_value kMarkerMap[] static
Mapping of types and markers (the table is defined in nnet-component.cc)
Definition at line 94 of file nnet-component.h.
Referenced by Component::MarkerToType(), and Component::TypeToMarker().
int32 output_dim_ protected
Size of output vectors.
Definition at line 169 of file nnet-component.h.
Referenced by Component::Backpropagate(), Convolutional2DComponent::BackpropagateFnc(), LinearTransform::InitData(), AffineTransform::InitData(), ConvolutionalComponent::InitData(), Convolutional2DComponent::InitData(), Rbm::InitData(), Component::OutputDim(), Component::Propagate(), Convolutional2DComponent::PropagateFnc(), Rbm::RbmUpdate(), AveragePoolingComponent::ReadData(), MaxPoolingComponent::ReadData(), MaxPooling2DComponent::ReadData(), AveragePooling2DComponent::ReadData(), LinearTransform::ReadData(), AffineTransform::ReadData(), KlHmm::ReadData(), FramePoolingComponent::ReadData(), ConvolutionalComponent::ReadData(), Convolutional2DComponent::ReadData(), Rbm::ReadData(), Rbm::Reconstruct(), KlHmm::SetStats(), and Convolutional2DComponent::Update().
The documentation for this class was generated from the following files:
nnet/nnet-component.cc
nnet/nnet-component.h