Kaldi: FmpeOptions Struct Reference
FmpeOptions Struct Reference
#include <fmpe.h>
Public Member Functions
FmpeOptions ()
void Register (OptionsItf *opts)
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary)
Public Attributes
std::string context_expansion
BaseFloat post_scale
Detailed Description
Definition at line 34 of file fmpe.h.
Constructor & Destructor Documentation
FmpeOptions () inline
Definition at line 72 of file fmpe.h.
                : context_expansion("0,1.0:-1,1.0:1,1.0:-2,0.5;-3,0.5:2,0.5;3,0.5:-4,0.5;-5,0.5:4,0.5;5,0.5:-6,0.333;-7,0.333;-8,0.333:6,0.333;7,0.333;8,0.333"),
                 post_scale(5.0) { }
Member Function Documentation
void Read (std::istream & is, bool binary)
Definition at line 430 of file fmpe.cc.
References FmpeOptions::context_expansion, FmpeOptions::post_scale, kaldi::ReadBasicType(), and kaldi::ReadToken().
Referenced by Fmpe::Read().
{
   ReadToken(is, binary, &context_expansion);
   ReadBasicType(is, binary, &post_scale);
 }
void Register (OptionsItf * opts) inline
Definition at line 75 of file fmpe.h.
References FmpeOptions::context_expansion, FmpeOptions::post_scale, and OptionsItf::Register().
Referenced by main().
{
     opts->Register("post-scale", &post_scale, "Scaling constant on posterior "
                    "element of offset features, to give it a faster learning "
                    "rate.");
     opts->Register("context-expansion", &context_expansion, "Specifies the "
                    "temporal context-splicing of high-dimensional features.");
   }
void Write (std::ostream & os, bool binary) const
Definition at line 426 of file fmpe.cc.
References FmpeOptions::context_expansion, FmpeOptions::post_scale, kaldi::WriteBasicType(), and kaldi::WriteToken().
Referenced by Fmpe::Write().
{
   WriteToken(os, binary, context_expansion);
   WriteBasicType(os, binary, post_scale);
 }
Member Data Documentation
std::string context_expansion
Definition at line 47 of file fmpe.h.
Referenced by Fmpe::Fmpe(), FmpeOptions::Read(), Fmpe::Read(), FmpeOptions::Register(), and FmpeOptions::Write().
BaseFloat post_scale
Definition at line 67 of file fmpe.h.
Referenced by Fmpe::ApplyProjection(), Fmpe::ApplyProjectionReverse(), FmpeOptions::Read(), FmpeOptions::Register(), and FmpeOptions::Write().
The documentation for this struct was generated from the following files:
transform/fmpe.h
transform/fmpe.cc