Kaldi: FmpeStats Struct Reference
FmpeStats Struct Reference
#include <fmpe.h>
Public Member Functions
FmpeStats ()
void Init (const Fmpe &fmpe)
FmpeStats (const Fmpe &fmpe)
void Write (std::ostream &os, bool binary) const
void Read (std::istream &is, bool binary, bool add=false)
SubMatrix< BaseFloat > DerivPlus () const
SubMatrix< BaseFloat > DerivMinus () const
void AccumulateChecks (const MatrixBase< BaseFloat > &feats, const MatrixBase< BaseFloat > &direct_deriv, const MatrixBase< BaseFloat > &indirect_deriv)
If we're using the indirect differential, accumulates certain quantities that will be used in the update phase to verify that the computation of the indirect differential was done correctly.
void DoChecks ()
Private Attributes
Matrix< BaseFloat > deriv
Matrix< double > checks
Detailed Description
Definition at line 105 of file fmpe.h.
Constructor & Destructor Documentation
FmpeStats () inline
Definition at line 106 of file fmpe.h.
 { };
FmpeStats (const Fmpe & fmpe) inline
Definition at line 108 of file fmpe.h.
References FmpeStats::Init().
 { Init(fmpe); }
Member Function Documentation
void AccumulateChecks (const MatrixBase< BaseFloat > & feats, const MatrixBase< BaseFloat > & direct_deriv, const MatrixBase< BaseFloat > & indirect_deriv)
If we're using the indirect differential, accumulates certain quantities that will be used in the update phase to verify that the computation of the indirect differential was done correctly.
Definition at line 627 of file fmpe.cc.
References FmpeStats::checks, rnnlm::d, KALDI_ASSERT, MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by Fmpe::AccStats().
{
   int32 T = feats.NumRows(), dim = feats.NumCols();
   KALDI_ASSERT(direct_deriv.NumRows() == T && direct_deriv.NumCols() == dim &&
                indirect_deriv.NumRows() == T && indirect_deriv.NumCols() == dim);
   KALDI_ASSERT(checks.NumRows() == 8 && checks.NumCols() == dim);
   for (int32 t = 0; t < T; t++) {
     for (int32 d = 0; d < dim; d++) {
       BaseFloat zero = 0.0;
       checks(0, d) += std::max(zero, direct_deriv(t, d));
       checks(1, d) += std::max(zero, -direct_deriv(t, d));
       checks(2, d) += std::max(zero, indirect_deriv(t, d));
       checks(3, d) += std::max(zero, -indirect_deriv(t, d));
       checks(4, d) += std::max(zero, feats(t, d)*direct_deriv(t, d));
       checks(5, d) += std::max(zero, -feats(t, d)*direct_deriv(t, d));
       checks(6, d) += std::max(zero, feats(t, d)*indirect_deriv(t, d));
       checks(7, d) += std::max(zero, -feats(t, d)*indirect_deriv(t, d));
     }
   }
 }
SubMatrix< BaseFloat > DerivMinus () const
Definition at line 610 of file fmpe.cc.
References FmpeStats::deriv, KALDI_ASSERT, MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by Fmpe::AccStats(), and Fmpe::Update().
                                                  { // const-ness not preserved.
   KALDI_ASSERT(deriv.NumRows() != 0);
   int32 proj_num_rows = deriv.NumRows(),
       proj_num_cols = deriv.NumCols()/2;
   return SubMatrix<BaseFloat>(deriv, 0, proj_num_rows,
                               proj_num_cols, proj_num_cols);
 }
SubMatrix< BaseFloat > DerivPlus () const
Definition at line 603 of file fmpe.cc.
References FmpeStats::deriv, KALDI_ASSERT, MatrixBase< Real >::NumCols(), and MatrixBase< Real >::NumRows().
Referenced by Fmpe::AccStats(), and Fmpe::Update().
                                                 { // const-ness not preserved.
   KALDI_ASSERT(deriv.NumRows() != 0);
   int32 proj_num_rows = deriv.NumRows(),
       proj_num_cols = deriv.NumCols()/2;
   return SubMatrix<BaseFloat>(deriv, 0, proj_num_rows,
                               0, proj_num_cols);
 }
void DoChecks ()
Definition at line 649 of file fmpe.cc.
References FmpeStats::checks, rnnlm::d, MatrixBase< Real >::IsZero(), KALDI_LOG, and MatrixBase< Real >::NumCols().
Referenced by main().
{
   if (checks.IsZero()) {
     KALDI_LOG << "No checks will be done, probably indirect derivative was not used.";
     return;
   }
   int32 dim = checks.NumCols();
   Vector<double> shift_check(dim), shift_check2(dim), scale_check(dim), scale_check2(dim);
   for (int32 d = 0; d < dim; d++) {
     // shiftnumerator = direct+indirect deriv-- should be zero.
     double shift_num = checks(0, d) - checks(1, d) + checks(2, d) - checks(3, d),
         shift_den = checks(0, d) + checks(1, d) + checks(2, d) + checks(3, d),
         shift_den2 = fabs(checks(0, d) - checks(1, d)) + fabs(checks(2, d) - checks(3, d));
     shift_check(d) = shift_num / shift_den;
     shift_check2(d) = shift_num / shift_den2;
     double scale_num = checks(4, d) - checks(5, d) + checks(6, d) - checks(7, d),
         scale_den = checks(4, d) + checks(5, d) + checks(6, d) + checks(7, d),
         scale_den2 = fabs(checks(4, d) - checks(5, d)) + fabs(checks(6, d) - checks(7, d));
     scale_check(d) = scale_num / scale_den;
     scale_check2(d) = scale_num / scale_den2;
   }
   KALDI_LOG << "Shift-check is as follows (should be in range +- 0.01 or less)."
             << shift_check;
   KALDI_LOG << "Scale-check is as follows (should be in range +- 0.01 or less)."
             << scale_check;
   KALDI_LOG << "Shift-check(2) is as follows: most elements should be in range +-0.1: "
             << shift_check2;
   KALDI_LOG << "Scale-check(2) is as follows: most elements should be in range +-0.1: "
             << scale_check2;
 }
void Init (const Fmpe & fmpe)
Definition at line 618 of file fmpe.cc.
References FmpeStats::checks, FmpeStats::deriv, Fmpe::FeatDim(), Fmpe::ProjectionTNumCols(), Fmpe::ProjectionTNumRows(), and Matrix< Real >::Resize().
Referenced by FmpeStats::FmpeStats().
{
   int32 num_rows = fmpe.ProjectionTNumRows(),
       num_cols = fmpe.ProjectionTNumCols();
   deriv.Resize(num_rows, num_cols*2);
   int32 feat_dim = fmpe.FeatDim();
   checks.Resize(8, feat_dim);
 }
void Read (std::istream & is, bool binary, bool add = false)
Definition at line 685 of file fmpe.cc.
References FmpeStats::checks, FmpeStats::deriv, and Matrix< Real >::Read().
Referenced by main().
{
   deriv.Read(is, binary, add);
   checks.Read(is, binary, add);
 }
void Write (std::ostream & os, bool binary) const
Definition at line 680 of file fmpe.cc.
References FmpeStats::checks, FmpeStats::deriv, and MatrixBase< Real >::Write().
Referenced by main().
{
   deriv.Write(os, binary);
   checks.Write(os, binary);
 }
Member Data Documentation
Matrix<double> checks private
Definition at line 133 of file fmpe.h.
Referenced by FmpeStats::AccumulateChecks(), FmpeStats::DoChecks(), FmpeStats::Init(), FmpeStats::Read(), and FmpeStats::Write().
Matrix<BaseFloat> deriv private
Definition at line 125 of file fmpe.h.
Referenced by FmpeStats::DerivMinus(), FmpeStats::DerivPlus(), FmpeStats::Init(), FmpeStats::Read(), and FmpeStats::Write().
The documentation for this struct was generated from the following files:
transform/fmpe.h
transform/fmpe.cc