Kaldi: NnetLogprobTask Struct Reference
NnetLogprobTask Struct Reference
Public Member Functions
NnetLogprobTask (const AmNnet &am_nnet, const CuVector< BaseFloat > &inv_priors, const std::string &key, const CuMatrix< BaseFloat > &feats, BaseFloatCuMatrixWriter *logprob_writer)
void operator() ()
~NnetLogprobTask ()
NnetLogprobTask (const AmNnet &am_nnet, const CuVector< BaseFloat > &inv_priors, const std::string &key, const Matrix< BaseFloat > &feats, BaseFloatMatrixWriter *prob_writer_nodiv, BaseFloatMatrixWriter *logprob_writer_divided)
void operator() ()
~NnetLogprobTask ()
Private Attributes
const AmNnet & am_nnet_
const CuVector< BaseFloat > & inv_priors_
std::string key_
CuMatrix< BaseFloat > feats_
CuMatrix< BaseFloat > log_probs_
BaseFloatCuMatrixWriter * logprob_writer_
BaseFloatMatrixWriter * prob_writer_nodiv_
BaseFloatMatrixWriter * logprob_writer_divided_
Detailed Description
Definition at line 31 of file nnet-logprob-parallel.cc.
Constructor & Destructor Documentation
NnetLogprobTask (const AmNnet & am_nnet, const CuVector< BaseFloat > & inv_priors, const std::string & key, const CuMatrix< BaseFloat > & feats, BaseFloatCuMatrixWriter * logprob_writer) inline
Definition at line 32 of file nnet-logprob-parallel.cc.
                                                           :
       am_nnet_(am_nnet), inv_priors_(inv_priors), key_(key), feats_(feats),
       logprob_writer_(logprob_writer) { }
~NnetLogprobTask () inline
Definition at line 46 of file nnet-logprob-parallel.cc.
References CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyLog(), rnnlm::i, NnetLogprobTask::inv_priors_, KALDI_WARN, NnetLogprobTask::key_, NnetLogprobTask::log_probs_, NnetLogprobTask::logprob_writer_, CuMatrixBase< Real >::MulColsVec(), CuMatrixBase< Real >::NumRows(), CuVectorBase< Real >::Scale(), CuVectorBase< Real >::Sum(), and TableWriter< Holder >::Write().
                      { // Produces output.  Run sequentially.
     // at this point they are probabilities, not log-probs, without prior division.
     log_probs_.MulColsVec(inv_priors_); // scales each column by the corresponding element
     // of inv_priors.
     for (int32 i = 0; i < log_probs_.NumRows(); i++) {
       CuSubVector<BaseFloat> frame(log_probs_, i);
       BaseFloat p = frame.Sum();
       if (!(p > 0.0)) {
         KALDI_WARN << "Bad sum of probabilities " << p;
       } else {
         frame.Scale(1.0 / p); // re-normalize to sum to one.
       }
     }
     log_probs_.ApplyFloor(1.0e-20); // To avoid log of zero which leads to NaN.
     log_probs_.ApplyLog();
     logprob_writer_->Write(key_, log_probs_);
   }
NnetLogprobTask (const AmNnet & am_nnet, const CuVector< BaseFloat > & inv_priors, const std::string & key, const Matrix< BaseFloat > & feats, BaseFloatMatrixWriter * prob_writer_nodiv, BaseFloatMatrixWriter * logprob_writer_divided) inline
Definition at line 32 of file nnet-logprob2-parallel.cc.
                                                                 :
       am_nnet_(am_nnet), inv_priors_(inv_priors), key_(key), feats_(feats),
       prob_writer_nodiv_(prob_writer_nodiv),
       logprob_writer_divided_(logprob_writer_divided) { }
~NnetLogprobTask () inline
Definition at line 48 of file nnet-logprob2-parallel.cc.
References CuMatrixBase< Real >::ApplyFloor(), CuMatrixBase< Real >::ApplyLog(), rnnlm::i, NnetLogprobTask::inv_priors_, KALDI_WARN, NnetLogprobTask::key_, NnetLogprobTask::log_probs_, NnetLogprobTask::logprob_writer_divided_, CuMatrixBase< Real >::MulColsVec(), CuMatrixBase< Real >::NumRows(), NnetLogprobTask::prob_writer_nodiv_, CuVectorBase< Real >::Scale(), CuVectorBase< Real >::Sum(), and TableWriter< Holder >::Write().
                      { // Produces output.  Run sequentially.
     // at this point they are probabilities, not log-probs, without prior division.
     prob_writer_nodiv_->Write(key_, Matrix<BaseFloat>(log_probs_));
     log_probs_.MulColsVec(inv_priors_); // scales each column by the corresponding element
     // of inv_priors.
     for (int32 i = 0; i < log_probs_.NumRows(); i++) {
       CuSubVector<BaseFloat> frame(log_probs_, i);
       BaseFloat p = frame.Sum();
       if (!(p > 0.0)) {
         KALDI_WARN << "Bad sum of probabilities " << p;
       } else {
         frame.Scale(1.0 / p); // re-normalize to sum to one.
       }
     }
     log_probs_.ApplyFloor(1.0e-20); // To avoid log of zero which leads to NaN.
     log_probs_.ApplyLog();
     logprob_writer_divided_->Write(key_, Matrix<BaseFloat>(log_probs_));
   }
Member Function Documentation
void operator() () inline
Definition at line 39 of file nnet-logprob-parallel.cc.
References NnetLogprobTask::am_nnet_, NnetLogprobTask::feats_, AmNnet::GetNnet(), NnetLogprobTask::log_probs_, kaldi::nnet2::NnetComputation(), AmNnet::NumPdfs(), CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
                       {
     log_probs_.Resize(feats_.NumRows(), am_nnet_.NumPdfs());
     bool pad_input = true;
     NnetComputation(am_nnet_.GetNnet(), feats_, pad_input,
                     &log_probs_);
   }
void operator() () inline
Definition at line 41 of file nnet-logprob2-parallel.cc.
References NnetLogprobTask::am_nnet_, NnetLogprobTask::feats_, AmNnet::GetNnet(), NnetLogprobTask::log_probs_, kaldi::nnet2::NnetComputation(), AmNnet::NumPdfs(), CuMatrixBase< Real >::NumRows(), and CuMatrix< Real >::Resize().
                       {
     log_probs_.Resize(feats_.NumRows(), am_nnet_.NumPdfs());
     bool pad_input = true;
     NnetComputation(am_nnet_.GetNnet(), feats_, pad_input,
                     &log_probs_);
   }
Member Data Documentation
const AmNnet & am_nnet_ private
Definition at line 66 of file nnet-logprob-parallel.cc.
Referenced by NnetLogprobTask::operator()().
CuMatrix< BaseFloat > feats_ private
Definition at line 69 of file nnet-logprob-parallel.cc.
Referenced by NnetLogprobTask::operator()().
const CuVector< BaseFloat > & inv_priors_ private
Definition at line 67 of file nnet-logprob-parallel.cc.
Referenced by NnetLogprobTask::~NnetLogprobTask().
std::string key_ private
Definition at line 68 of file nnet-logprob-parallel.cc.
Referenced by NnetLogprobTask::~NnetLogprobTask().
CuMatrix< BaseFloat > log_probs_ private
Definition at line 70 of file nnet-logprob-parallel.cc.
Referenced by NnetLogprobTask::operator()(), and NnetLogprobTask::~NnetLogprobTask().
BaseFloatCuMatrixWriter* logprob_writer_ private
Definition at line 71 of file nnet-logprob-parallel.cc.
Referenced by NnetLogprobTask::~NnetLogprobTask().
BaseFloatMatrixWriter* logprob_writer_divided_ private
Definition at line 75 of file nnet-logprob2-parallel.cc.
Referenced by NnetLogprobTask::~NnetLogprobTask().
BaseFloatMatrixWriter* prob_writer_nodiv_ private
Definition at line 74 of file nnet-logprob2-parallel.cc.
Referenced by NnetLogprobTask::~NnetLogprobTask().
The documentation for this struct was generated from the following files:
nnet2bin/nnet-logprob-parallel.cc
nnet2bin/nnet-logprob2-parallel.cc