Kaldi: bin/sum-matrices.cc File Reference
sum-matrices.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 24 of file sum-matrices.cc.
References ParseOptions::GetArg(), rnnlm::i, KALDI_LOG, ParseOptions::NumArgs(), MatrixBase< Real >::NumCols(), MatrixBase< Real >::NumRows(), ParseOptions::PrintUsage(), ParseOptions::Read(), Matrix< Real >::Read(), ParseOptions::Register(), and MatrixBase< Real >::Write().
{
   using namespace kaldi;
   typedef kaldi::int32 int32;
   try {
     const char *usage =
         "Sum matrices, e.g. stats for fMPE training\n"
         "Usage:  sum-matrices [options] <mat-out> <mat-in1> <mat-in2> ...\n"
         "e.g.:\n"
         " sum-matrices mat 1.mat 2.mat 3.mat\n";
     ParseOptions po(usage);
     bool binary = true;
     po.Register("binary", &binary, "Write output in binary mode");
     po.Read(argc, argv);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     Matrix<BaseFloat> mat;
     for (int32 i = 2; i <= po.NumArgs(); i++) {
       bool binary_in;
       Input ki(po.GetArg(i), &binary_in);
       mat.Read(ki.Stream(), binary_in, true); // true == add.
       // This will crash if dimensions do not match.
     }
     Output ko(po.GetArg(1), binary);
     mat.Write(ko.Stream(), binary);
     KALDI_LOG << "Summed " << (po.NumArgs()-1) << " matrices "
               << " of dimension " << mat.NumRows() << " by " << mat.NumCols();
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }