Kaldi: bin/sum-lda-accs.cc File Reference
sum-lda-accs.cc File Reference
#include "util/common-utils.h"
#include "gmm/mle-am-diag-gmm.h"
#include "transform/lda-estimate.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file sum-lda-accs.cc.
References ParseOptions::GetArg(), rnnlm::i, ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), ParseOptions::Register(), and Output::Stream().
{
   try {
     using namespace kaldi;
     typedef kaldi::int32 int32;
     const char *usage =
         "Sum stats obtained with acc-lda.\n"
         "Usage: sum-lda-accs [options] <stats-out> <stats-in1> <stats-in2> ...\n";
     bool binary = true;
     ParseOptions po(usage);
     po.Register("binary", &binary, "Write accumulators in binary mode.");
     po.Read(argc, argv);
     if (po.NumArgs() < 2) {
       po.PrintUsage();
       exit(1);
     }
     LdaEstimate lda;
     std::string stats_out_filename = po.GetArg(1);
     for (int32 i = 2; i <= po.NumArgs(); i++) {
       bool binary_in, add = true;
       Input ki(po.GetArg(i), &binary_in);
       lda.Read(ki.Stream(), binary_in, add);
     }
     Output ko(stats_out_filename, binary);
     lda.Write(ko.Stream(), binary);
     return 0;
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }