Kaldi: featbin/wav-copy.cc File Reference
wav-copy.cc File Reference
#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "feat/feature-mfcc.h"
#include "feat/wave-reader.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file wav-copy.cc.
References SequentialTableReader< Holder >::Done(), ParseOptions::GetArg(), KALDI_LOG, SequentialTableReader< Holder >::Key(), SequentialTableReader< Holder >::Next(), ParseOptions::NumArgs(), ParseOptions::PrintUsage(), ParseOptions::Read(), SequentialTableReader< Holder >::Value(), and TableWriter< Holder >::Write().
{
   try {
     using namespace kaldi;
     const char *usage =
         "Copy archives of wave files\n"
         "\n"
         "Usage:  wav-copy [options...] <wav-rspecifier> <wav-rspecifier>\n"
         "e.g. wav-copy scp:wav.scp ark:-\n"
         "See also: wav-to-duration extract-segments\n";
     ParseOptions po(usage);
     po.Read(argc, argv);
     if (po.NumArgs() != 2) {
       po.PrintUsage();
       exit(1);
     }
     std::string wav_rspecifier = po.GetArg(1),
         wav_wspecifier = po.GetArg(2);
     int32 num_done = 0;
     SequentialTableReader<WaveHolder> wav_reader(wav_rspecifier);
     TableWriter<WaveHolder> wav_writer(wav_wspecifier);
     for (; !wav_reader.Done(); wav_reader.Next()) {
       wav_writer.Write(wav_reader.Key(), wav_reader.Value());
       num_done++;
     }
     KALDI_LOG << "Copied " << num_done << " wave files";
     return (num_done != 0 ? 0 : 1);
   } catch(const std::exception &e) {
     std::cerr << e.what();
     return -1;
   }
 }